### ISSUE TITLE
Support for Unified Plan SDP Format

### ISSUE THREAD

**Issue by mshary** [sipwise/rtpengine#1000]
Since Chrome M72, the default format of SDP generated by Chrome's WebRTC stack has been changed to `unified-plan` instead of  Google's old `plan-b` format, which has now been deprecated and planned to be removed sometime in mid 2020. Here are more details about it.

https://webrtc.org/getting-started/unified-plan-transition-guide

This poses a big problem for non-web WebRTC clients, servers and proxies (such as RTPEngine) which will stop working as soon as Google Chrome removes support for legacy `plan-b` SDP format.

Are there any plans to support this?

Here is a comprehensive transition guide for in-depth analysis of both SDP formats.

https://docs.google.com/document/d/1-ZfikoUtoJa9k-GZG1daN0BU3IjIanQ_JSscHxQesvU/edit

**Comment by rfuchs** [comment]
I don't really see anything in the description of the "unified plan" that isn't supported by rtpengine. I guess will have to try and see. There may be a need to further rewrite it to make it work against legacy WebRTC clients, but that's a different topic.

**Comment by rfuchs** [comment]
Cleaning up old tickets
