### ISSUE TITLE
How to set complexity of OPUS codec ?

### ISSUE THREAD

**Issue by fedkis** [sipwise/rtpengine#1001]
Hello,
I found the following function. How to set complexity in this function ?

static void opus_set_enc_options(encoder_t *enc, const str *fmtp) {
        int ret;
        if (enc->ptime)
                if ((ret = av_opt_set_int(enc->u.avc.avcctx, "frame_duration", enc->ptime,
                                                AV_OPT_SEARCH_CHILDREN)))
                        ilog(LOG_WARN, "Failed to set Opus frame_duration option to %i: %s",
                                        enc->ptime, av_error(ret));
        // XXX additional opus options
}
Thank you!

**Comment by rfuchs** [comment]
You're probably talking about the `compression_level` setting? See https://ffmpeg.org/ffmpeg-codecs.html#libopus-1
So something like
```
                if ((ret = av_opt_set_int(enc->u.avc.avcctx, "compression_level", 10,
                                                AV_OPT_SEARCH_CHILDREN)))
                        ilog(LOG_WARN, "Failed to set Opus compression_level option to %i: %s",
                                        10, av_error(ret));
```
Let me know if this works for you and I can add proper support for it. (Or a pull request would be even better)

**Comment by fedkis** [comment]
Thank you! I will try
