### ISSUE TITLE
How to restart rtpengine after crash

### ISSUE THREAD

**Issue by fedkis** [sipwise/rtpengine#1003]
Hi,
Please advise how to restart rtpengine with clearing buffer. Rtpengine re-reads a group of packets that bring crashes again and again. If I delete table in /proc/rtpengine/control between restarts , will it disconnect all calls ?  I just want to ignore packets bringing crash , then start with the same table .

-rw------- 1 root root 347381760 мая 27 19:18 core.rtpengine.8779.rtp-de4.ddpp.net.1590596288
-rw------- 1 root root 348000256 мая 27 19:18 core.rtpengine.8827.rtp-de4.ddpp.net.1590596293
-rw------- 1 root root 347156480 мая 27 19:18 core.rtpengine.8878.rtp-de4.ddpp.net.1590596298
-rw------- 1 root root 345997312 мая 27 19:18 core.rtpengine.8929.rtp-de4.ddpp.net.1590596299
-rw------- 1 root root 346316800 мая 27 19:18 core.rtpengine.8976.rtp-de4.ddpp.net.1590596303
-rw------- 1 root root 351985664 мая 27 19:18 core.rtpengine.9023.rtp-de4.ddpp.net.1590596313
-rw------- 1 root root 347979776 мая 27 19:18 core.rtpengine.9086.rtp-de4.ddpp.net.1590596318
-rw------- 1 root root 347340800 мая 27 19:18 core.rtpengine.9137.rtp-de4.ddpp.net.1590596322
-rw------- 1 root root 347746304 мая 27 19:18 core.rtpengine.9186.rtp-de4.ddpp.net.1590596327
-rw------- 1 root root 346832896 мая 27 19:18 core.rtpengine.9233.rtp-de4.ddpp.net.1590596331
-rw------- 1 root root 346374144 мая 27 19:18 core.rtpengine.9280.rtp-de4.ddpp.net.1590596333
-rw------- 1 root root 346312704 мая 27 19:18 core.rtpengine.9327.rtp-de4.ddpp.net.1590596336

**Comment by rfuchs** [comment]
There's no packets being read. The only state information is kept in Redis if you have that enabled. So clear the Redis DB and then restart.
