### ISSUE TITLE
Really no enough local ip address after query

### ISSUE THREAD

**Issue by fedkis** [sipwise/rtpengine#1004]
Hello,
It is very good that you return local port in query but it is a pity that there is no local ip address.
I have 2 ip addresses on my server(ipv4 and ipv6). After rtpengine received offer command, I cant know which ip address was used for media exchange. 

                                                                            u'flags': [u'RTP',
                                                                                       u'filled'],
                                                                            u'last packet': 1590837514,
                                                                            u'local port': 32164,
                                                                            u'stats': {u'bytes': 0,
                                                                                       u'errors': 0,
                                                                                       u'packets': 0}},

**Comment by fedkis** [comment]
I have just added local address to ng_stats_stream for myself and it is returning correct address but I don't know if it is safety ?

  if (ps->selected_sfd) {
                bencode_dictionary_add_integer(dict, "local port", ps->selected_sfd->socket.local.port);
                bencode_dictionary_add_string_dup(dict, "local address", sockaddr_print_buf(&ps->selected_sfd->socket.local.address));
 }

**Comment by rfuchs** [comment]
That looks like the correct patch, yes.

**Comment by fedkis** [comment]
Then it's there too
bencode_dictionary_add_string(dict, "family", ps->selected_sfd->socket.local.address.family->name)
