### ISSUE TITLE
Problem starting RTPengine 

### ISSUE THREAD

**Issue by olofri304** [sipwise/rtpengine#1007]
Hi we have an issue starting RTPengine

sudo -u ngcp-rtpengine /usr/sbin/rtpengine --config-file=/etc/rtpengine/rtpengine.conf --pidfile=/run/rtpengine/rtpengine.pid
[1591189155.206898] ERR: FAILED TO OPEN KERNEL TABLE 0 (Permission denied), KERNEL FORWARDING DISABLED

This is with version 8.4.1.1 and it used to work in previous versions.

any ideas on how to solve this would be appreciated.

**Comment by rfuchs** [comment]
So you're starting rtpengine as a non-root user. By default, the kernel module is available only to root. You can change that by giving the xt_RTPENGINE module some options to set the desired uid or gid. I believe `modinfo -p xt_RTPENGINE` prints the available options. You can set them permanently through `/etc/modprobe.d/`

**Comment by olofri304** [comment]
Thanks for the bery quick response will try that

We use the default systemd rtpengine.service file and that does not start as root.

We also have seen some other minor issues with the default RPM build, can share them here or elsewhere.

**Comment by rfuchs** [comment]
We don't support the RPM stuff ourselves, so if you find any issues, please send a pull request to have them fixed.

**Comment by amessina** [comment]
I use the following which allows me to use the iptables rule insertions while running as the `rtpengine` user:

**/lib/systemd/system/rtpengine.service**
```
[Unit]
Description=Sipwise NGCP rtpengine RTP proxy
Documentation=https://github.com/sipwise/rtpengine
After=network-online.target
Before=kamailio.service
Wants=network-online.target

[Service]
Type=notify
User=rtpengine
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_RAW CAP_DAC_OVERRIDE
ExecStart=/usr/sbin/rtpengine -f --config-file=/etc/rtpengine/rtpengine.conf --config-section=rtpengine --pidfile=/run/rtpengine/rtpengine.pid
PIDFile=/run/rtpengine/rtpengine.pid
Restart=on-failure
RestartSec=30
StandardOutput=null

[Install]
WantedBy=multi-user.target
```

**/lib/modprobe.d/xt_RTPENGINE.conf**
The `proc_uid` and `proc_gid` are the userid of the `rtpengine` user.
```
options xt_RTPENGINE proc_uid=981 proc_gid=979
```
For history or reference: https://messinet.com/rpms/browser/rtpengine
