### ISSUE TITLE
Multiline a=fmtp attributes are processed incorrectly

### ISSUE THREAD

**Issue by abogosyan** [sipwise/rtpengine#1017]
In case of some WebRTC offer we could have SDP with attributes like that:
```
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=fmtp:102 x-google-start-bitrate=800
```
Unfortunately, modified offer will contain only the last line:
```
a=fmtp:96 x-google-start-bitrate=800
```
Thats because here hashtable is used to store format params string:
https://github.com/sipwise/rtpengine/blob/master/daemon/sdp.c#L1285
So the params are overwritten with each "a=fmtp" line of same payload type and later added to stream params and modified SDP: 
https://github.com/sipwise/rtpengine/blob/master/daemon/sdp.c#L1314
https://github.com/sipwise/rtpengine/blob/master/daemon/sdp.c#L1324 

All that leads to fmtp-dependent codecs are not working via rtpengine (for example Chrome screen-sharing with H264 codec)

**Comment by rfuchs** [comment]
RFC 4566 says about `a=fmtp`: `At most one instance of this attribute is allowed for each format.`

I suppose there's some WebRTC specific standard overriding that?

**Comment by abogosyan** [comment]
> RFC 4566 says about `a=fmtp`: `At most one instance of this attribute is allowed for each format.`
> 
> I suppose there's some WebRTC specific standard overriding that?

Yes, you are right, it's against RFC 4566, seems like some "bad client" trying to enable google-specific features that way. Not a problem of rtpengine thought

**Comment by rfuchs** [comment]
Let me know if this is indeed supposed to work and not just a broken client, because it shouldn't be too hard to implement.
