### ISSUE TITLE
Upon re-INVITE + ice restart - RTPEngine expects DTLS re-handshake (SRTP output wanted, but no crypto suite was negotiated)

### ISSUE THREAD

**Issue by saharh** [sipwise/rtpengine#1019]
Hello @rfuchs!,

Setup:  2x UA - Chrome(SIP.js) <-> Kamailio <-> RTPEngine

Initial connection works as expected, DTLS handshake is made between both UAs and RTPEngine, and audio goes through.
When issuing an iceRestart + following re-invite, RTPEngine expects a DTLS re-handshake to occur, but Chrome doesn't send any.
This results in both UAs considering the peer connectionstate = "connected", and send SRTP to RTPEngine, but RTPEngine errors with "SRTP output wanted, but no crypto suite was negotiated".

This issue has occurred in the past, (#182), however I'm not sure how "reset" solved it for this guy, as I've attempted to use "reset" as well as "port-latching" flags to no avail.

notice that - ice credentials do change (ufrag) over ice restart, but the DTLS fingerprint doesn't, which is why Chrome doesn't do any DTLS re-handshake as it isn't needed.

See logs:
https://gist.github.com/saharh/1d6da8b239b59966f8288f8f91b9932f

rtpengine -v
Version: 8.4.1.1+0~mr8.4.1.1
kamailio 5.3.4 (x86_64/linux)
Chrome 83
SIP.js 0.16.1

**Comment by rfuchs** [comment]
This is a bit hard to test/reproduce for me, so you'll have to assist with some trial and error. I think this stems from code in `__fill_stream()` which resets the crypto params when the RTP endpoint changes without paying heed to DTLS or ICE details. You can try removing this and see if it makes a difference:
```
diff --git a/daemon/call.c b/daemon/call.c
index 0ff52fd3..882f4468 100644
--- a/daemon/call.c
+++ b/daemon/call.c
@@ -1000,13 +1000,6 @@ static void __fill_stream(struct packet_stream *ps, const struct endpoint *epp,
 
        ps->endpoint = ep;
 
-       if (PS_ISSET(ps, FILLED)) {
-               /* we reset crypto params whenever the endpoint changes */
-               // XXX fix WRT SSRC handling
-               crypto_reset(&ps->crypto);
-               dtls_shutdown(ps);
-       }
-
        ilog(LOG_DEBUG, "set FILLED flag for stream %s%s:%d%s",
                        FMT_M(sockaddr_print_buf(&ps->endpoint.address), ps->endpoint.port));
        PS_SET(ps, FILLED);
```

**Comment by rfuchs** [comment]
See 21cd630 for the respective commit. This isn't supposed to be a final fix, but just a test run for you to confirm if that fixes it.

**Comment by saharh** [comment]
It is working now, thanks!
I am going to do some more testing to be sure, but I believe the issue can be closed.
