### ISSUE TITLE
No call audio when recording is enabled

### ISSUE THREAD

**Issue by hamid-elaosta** [sipwise/rtpengine#1025]
I'm using RTPEngine with Opensips 3.0.x. Originally I was using 8.0.1.1 but updated to 8.3.1.5 (8.4.1.1 wouldn't build under any Debian based OS I attempted to build on due to failing tests).

Under normal circumstances, call audio is fine, and I am able to have a two way conversation between two devices.

As soon as I pass the "call-recording=yes" flag from Opensips, in the `rtpengine_offer`, I can see "Turning on call recording." in RTPEngine logs. At this point I have no audio on the call. A tshark shows that traffic is coming in to the RTPEngine from both devices but nothing leaves the RTPEngine instance.

I'm running RTPEngine in Docker with host networking, I'm using the fallback method and not the kernel module, also I'm using an SRTP media stream which cannot be decrypted by RTPEngine, and I'm simply looking for passthrough behavior.

RTPEngine log:
```
Creating new call
Turning on call recording.
/var/spool/rtpengine/pcaps/d2e904a2-2121-4c86-8215-a7428d322fb1-cc597ae6f72deb09.pcap
Replying to 'offer' from 172.18.0.22:43286 (elapsed time 0.004234 sec)
SRTCP output wanted, but no crypto suite was negotiated
SRTP output wanted, but no crypto suite was negotiated
Received command 'answer' from 172.18.0.22:49440
Replying to 'answer' from 172.18.0.22:49440 (elapsed time 0.000180 sec)
SRTCP output wanted, but no crypto suite was negotiated
SRTP output wanted, but no crypto suite was negotiated
Confirmed peer address as 192.168.1.202:4000
Confirmed peer address as 192.168.1.54:4002
Confirmed peer address as 192.168.1.54:4003
Confirmed peer address as 192.168.1.202:4001
SRTP output wanted, but no crypto suite was negotiated
SRTP output wanted, but no crypto suite was negotiated
SRTCP output wanted, but no crypto suite was negotiated
SRTCP output wanted, but no crypto suite was negotiated
SRTP output wanted, but no crypto suite was negotiated
SRTP output wanted, but no crypto suite was negotiated
SRTCP output wanted, but no crypto suite was negotiated
SRTCP output wanted, but no crypto suite was negotiated

```
Is there some configuration I'm missing that's preventing call audio while recording? Or does RTPEngine not support STRP stream passthrough when it can't decrypt?

**Comment by rfuchs** [comment]
Post your full config please, as well as a full call log with log level 7 enabled.

**Comment by hamid-elaosta** [comment]
Hi @rfuchs Thanks for the quick response. Logs (attached) and config as requested;
```
LISTEN_ADDRESS=enp0s3
ADVERTISED_ADDRESS=192.168.1.243
CONTROL_ADDRESS=192.168.1.243
CONTROL_PORT=2333
RTP_PORT_MIN=10000
RTP_PORT_MAX=20000

rtpengine -E \
    --interface="$LISTEN_ADDRESS!$ADVERTISED_ADDRESS" \
    --listen-ng="$CONTROL_ADDRESS:$CONTROL_PORT" \
    -m $RTP_PORT_MIN -M $RTP_PORT_MAX \
    --foreground --recording-dir=/var/spool/rtpengine \
    --recording-format=eth \
    --recording-method=pcap \
    --log-format=parsable
```
[rtpengine.log](https://github.com/sipwise/rtpengine/files/4825326/rtpengine.log)

**Comment by rfuchs** [comment]
Ok, so the codecs are passthrough, but I also see that DTLS is being used that is not passthrough. So what I'm missing in the log is the DTLS establishment messages. Even more so, the initial offer is given as SRTP but neither SDES nor DTLS attributes are present. How is SRTP supposed to work here?

**Comment by hamid-elaosta** [comment]
I'm not sure that DTLS is being used, beyond the RTPEngine generating certificates for it at startup. Is there some indication in the log that the clients desire to use DTLS? Do I need to disable it in RTPEngine if they do/are not because because it's determined by the server? We're outside my area of expertise here, so apologies.

As for SRTP, we use an alternative key negotiation mechanism, it is passed in the SDP but is not something RTPEngine could understand, I removed the SDP lines from the log as beyond requiring them to passthrough, they're not relevant to the discussion.

When recording is disabled, RTPEngine functions as expected and calls behave as we would expect. The issue comes when I flag through Opensips to enable recording for a call, media does not forward on from RTPEngine to the end device in either direction.

I don't expect RTPEngine to do anything it can't, but only to store the raw pcaps and SDP/metadata.

What I see in practice is that the pcaps and metadata _are_ stored when recording is on, but no media passes between the devices in the conversation.

**Comment by rfuchs** [comment]
Ok I see. The thing is that the recording mechanism is designed to dump data (whether audio or raw packet data) in plaintext format. That means that when recording is enabled, rtpengine wants to decrypt the data in order to dump it. In your case it can't because it's not involved in the en/decryption, and so the whole mechanism fails. I'll have to see if there's an easy way to handle this exceptional use case.

**Comment by hamid-elaosta** [comment]
Thanks, that would be extremely helpful as I'm currently blocked on this issue. Even a small patch I could make, or a pointer to the relevant pars of the code, where I can make the change to allow the media to continue flowing would be appreciated in the short term. I'm currently switching from RTPProxy due to other shortcomings, but where recording was functioning normally so I hadn't foreseen an issue here.

**Comment by rfuchs** [comment]
As a quick workaround, you can probably just remove these two lines:
```
diff --git a/daemon/media_socket.c b/daemon/media_socket.c
index 91ae9886..d8e564c2 100644
--- a/daemon/media_socket.c
+++ b/daemon/media_socket.c
@@ -1296,8 +1296,6 @@ static void __determine_handler(struct packet_stream *in, const struct packet_st
 		must_recrypt = 1;
 	else if (MEDIA_ISSET(in->media, TRANSCODE) || MEDIA_ISSET(out->media, TRANSCODE))
 		must_recrypt = 1;
-	else if (in->call->recording)
-		must_recrypt = 1;
 	else if (in_proto->srtp && out_proto->srtp
 			&& in->selected_sfd && out->selected_sfd
 			&& (crypto_params_cmp(&in->crypto.params, &out->selected_sfd->crypto.params)
```

**Comment by hamid-elaosta** [comment]
Thanks @rfuchs. I can confirm that I have media flowing with that patch applied to 8.3.1.5, and that there is _something_ in the pcap, although I haven't verified its content yet.

So in terms of making this a supported feature, is it possible this could become a new flag? Perhaps an alternative recording flag without "recrypt"?

Appreciate the assistance so far!

**Comment by rfuchs** [comment]
My plan is to try to support this without requiring another explicit flag, meaning that rtpengine should detect this case on its own and act accordingly.
