### ISSUE TITLE
RFC2833 DTMF is being strangely reordered

### ISSUE THREAD

**Issue by linussuk** [sipwise/rtpengine#1027]
[rfc2833-seq-err.pcap.gz](https://github.com/sipwise/rtpengine/files/4836046/rfc2833-seq-err.pcap.gz)

As shown in the above file, there is RTP between 1.1.1.66 and 2.2.2.134 (RTPEngine). The RFC2833 packets here are perfectly ordered and following specification. When these are forwarded on to 3.3.3.135 they are strangely reordered. 

I have also noticed that whilst the source obeys the recommendation for the timestamp value to be constant for the entire RFC2833 event, RTPEngine does not follow that recommendation and tries to regenerate an incremental timestamp. The suspicion is of course that this is something to do with the problem. 

Obviously IP addresses have been mangled in the capture above, an original full capture can be supplied for private use by known contributors. 

Reproduced on: Version: 8.1.0.0+0~mr8.1.0.0 git-master-228d822 & Version: 8.3.0.0+0~mr8.3.0.0 git-master-fbaaf22d
Does not fail on the older: Version: 5.4.0.0+0~mr5.4.0.0 git-master-b6c9c6c

Thank you.

**Comment by rfuchs** [comment]
Any transcoding or DTMF logging or any other related functionality in use?

**Comment by linussuk** [comment]
Not active, as is a-law both ends, but command is:

rtpengine_manage("trust-address replace-origin replace-session-connection ICE=remove xmlrpc-callback=a.b.c.d transcode-PCMA transcode-PCMU transcode-G729");

**Comment by linussuk** [comment]
Debug from initial setup:
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: Adding a proxy for control ng stats:4.4.72.131
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: INFO: [1701094404_89098755@1.1.1.67]: Received command 'offer' from 4.4.72.131:56432
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Dump for 'offer' from 4.4.72.131:56432: { "sdp": "v=0
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: o=Sonus_UAC 488426 466362 IN IP4 1.1.1.67
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: s=SIP Media Capabilities
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: c=IN IP4 1.1.1.66
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: t=0 0
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: m=audio 26582 RTP/AVP 8 101
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=rtpmap:8 PCMA/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=rtpmap:101 telephone-event/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=fmtp:101 0-15
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=sendrecv
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=ptime:20
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: ", "ICE": "remove", "xmlrpc-callback": "4.4.73.131", "flags": [ "trust-address", "transcode-PCMA", "transcode-PCMU", "transcode-G729" ], "replace": [ "origin", "session-connection" ], "call-id": "1701094404_89098755@1.1.1.67", "received-from": [ "IP4", "1.1.1.67" ], "from-tag": "gK04691557", "command": "offer" }
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: NOTICE: [1701094404_89098755@1.1.1.67]: Creating new call
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Codec 'PCMA' requested for transcoding is already present
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Codec 'PCMU/8000' added for transcoding with payload type 0
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Codec 'G729/8000' added for transcoding with payload type 18
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Default sink codec is PCMA/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: 0 DTMF sink entries
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Creating codec handler for PCMA/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Sink supports codec PCMA/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Using passthrough handler for PCMA/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Creating codec handler for telephone-event/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Sink supports codec telephone-event/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Using passthrough handler for telephone-event/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Creating codec handler for PCMU/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Sink does not support codec PCMU/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Created transcode context for PCMU/8000 -> PCMA/8000 with DTMF output -1
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Creating SSRC transcoder from PCMU/8000/1 to PCMA/8000/1
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Initialized encoder with frame size 160 samples
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Encoder created with clockrate 8000, 1 channels, using sample format 1 (ptime 20 for 160 samples per frame and 160 samples (160 bytes) per packet, bitrate 0)
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Creating codec handler for G729/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Sink does not support codec G729/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Created transcode context for G729/8000 -> PCMA/8000 with DTMF output -1
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Creating SSRC transcoder from G729/8000/1 to PCMA/8000/1
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Initialized encoder with frame size 160 samples
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Encoder created with clockrate 8000, 1 channels, using sample format 1 (ptime 20 for 160 samples per frame and 160 samples (160 bytes) per packet, bitrate 0)
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Using existing encoder context
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: INFO: [1701094404_89098755@1.1.1.67]: Enabling transcoding engine
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: __free_ssrc_handler
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Using passthrough handler with new SSRC for telephone-event/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: __free_ssrc_handler
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Using passthrough handler with new SSRC for PCMA/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: creating send_timer
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: creating send_timer
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: creating send_timer
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: creating send_timer
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: set FILLED flag for stream 1.1.1.66:26582
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: set FILLED flag for stream 1.1.1.66:26583
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: INFO: [1701094404_89098755@1.1.1.67]: Replying to 'offer' from 4.4.72.131:56432 (elapsed time 0.001410 sec)
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Response dump for 'offer' to 4.4.72.131:56432: { "sdp": "v=0
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: o=Sonus_UAC 488426 466362 IN IP4 2.2.2.134
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: s=SIP Media Capabilities
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: c=IN IP4 2.2.2.134
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: t=0 0
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: m=audio 30000 RTP/AVP 8 101 0 18
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=rtpmap:8 PCMA/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=rtpmap:101 telephone-event/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=rtpmap:0 PCMU/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=rtpmap:18 G729/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=fmtp:101 0-15
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=sendrecv
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=rtcp:30001
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=ptime:20
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: ", "result": "ok" }
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Forward to sink endpoint: 1.1.1.66:26582 (RTP seq 64850 TS 160)
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: INFO: [1701094404_89098755@1.1.1.67]: Received command 'offer' from 4.4.72.131:42596
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Dump for 'offer' from 4.4.72.131:42596: { "sdp": "v=0
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: o=root 28895 28895 IN IP4 3.3.3.135
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: s=session
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: c=IN IP4 3.3.3.135
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: t=0 0
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: m=audio 18962 RTP/AVP 8 0 101
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=rtpmap:8 PCMA/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=rtpmap:0 PCMU/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=rtpmap:101 telephone-event/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=fmtp:101 0-16
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=silenceSupp:off - - - -
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=ptime:20
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=sendrecv
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: ", "flags": [ "trust-address" ], "replace": [ "origin", "session-connection" ], "call-id": "1701094404_89098755@1.1.1.67", "received-from": [ "IP4", "4.4.73.150" ], "from-tag": "8Sa3K7p0Q4eve", "to-tag": "gK04691557", "command": "offer" }
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Eliminating asymmetric inbound codec G729/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Default sink codec is PCMA/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: 1 DTMF sink entries
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Output DTMF payload type is 101
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Creating codec handler for PCMA/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Sink does not support codec PCMA/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Created transcode context for PCMA/8000 -> PCMA/8000 with DTMF output 101
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Creating SSRC transcoder from PCMA/8000/1 to PCMA/8000/1
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Initialized encoder with frame size 160 samples
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Encoder created with clockrate 8000, 1 channels, using sample format 1 (ptime 20 for 160 samples per frame and 160 samples (160 bytes) per packet, bitrate 0)
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Eliminating transcoded codec PCMU/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Creating codec handler for telephone-event/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Sink does not support codec telephone-event/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Created DTMF transcode context for telephone-event/8000 -> PT 101
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Creating SSRC DTMF transcoder from telephone-event/8000/1 to PT 101
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Initialized encoder with frame size 160 samples
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Encoder created with clockrate 8000, 1 channels, using sample format 1 (ptime 20 for 160 samples per frame and 160 samples (160 bytes) per packet, bitrate 0)
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Using existing encoder context
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: INFO: [1701094404_89098755@1.1.1.67]: Enabling transcoding engine
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: set FILLED flag for stream 3.3.3.135:18962
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: set FILLED flag for stream 3.3.3.135:18963
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: INFO: [1701094404_89098755@1.1.1.67]: Replying to 'offer' from 4.4.72.131:42596 (elapsed time 0.000579 sec)
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Response dump for 'offer' to 4.4.72.131:42596: { "sdp": "v=0
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: o=root 28895 28895 IN IP4 2.2.2.134
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: s=session
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: c=IN IP4 2.2.2.134
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: t=0 0
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: m=audio 30012 RTP/AVP 8 101
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=silenceSupp:off - - - -
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=rtpmap:8 PCMA/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=rtpmap:101 telephone-event/8000
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=fmtp:101 0-16
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=sendrecv
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=rtcp:30013
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: a=ptime:20
Jun 25 15:21:59 rdg-rtp-dev rtpengine[619]: ", "result": "ok" }

**Comment by linussuk** [comment]
Debug from actually handling the first digit. Have log at this detail for whole of call which can be forwarded privately too.

Jun 25 15:22:09 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67 port 30012]: Received RTP packet: SSRC 8ea9745c, PT 101, seq 502, TS 80000, len 4
Jun 25 15:22:09 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67 port 30012]: Decoding RTP packet: seq 502, TS 80000
Jun 25 15:22:09 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67 port 30012]: DTMF event: event 1, volume 4, end 0, duration 16385
Jun 25 15:22:09 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67 port 30012]: Switching context from decoder to encoder
Jun 25 15:22:09 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67 port 30012]: Scaling DTMF packet timestamp and duration: TS 80000 -> 80320 (8000 -> 8000)
Jun 25 15:22:09 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67 port 30012]: Scheduling to send RTP packet (seq 502 TS 80320) at 1593094929.396654
Jun 25 15:22:09 rdg-rtp-dev rtpengine[619]: DEBUG: [1701094404_89098755@1.1.1.67]: Forward to sink endpoint: 3.3.3.135:18962 (RTP seq 502 TS 80320)

**Comment by rfuchs** [comment]
Full log would be helpful, together with a better explanation of what the actual problem is, because I don't see any issue here.

**Comment by linussuk** [comment]
Full wireshark suppled on direct email. Log to follow

**Comment by rfuchs** [comment]
Ok, first thing you need to do is fix your signalling. The original offer from your A party is fine, but the answer from your B party is given to rtpengine also as an `offer`. I don't know if that will fix your issue, but you should start there.

**Comment by linussuk** [comment]
I am currently using: 

onreply_route[handle_ip_intercon] {
        if (has_body_part("application/sdp")) {
		if (isflagset(USE_RTP2)) {
			rtpengine_use_set("2");
		}
             rtpengine_manage("trust-address replace-origin replace-session-connection");
        }
}

How should this be improved? I understood rtpengine_manage covered all this? (version: opensips 2.4.6 (i386/linux))

**Comment by rfuchs** [comment]
It should, but we don't maintain the OpenSIPS module ourselves, so it's probably some kind of failure there. Either way, you should be able to call rtpengine_offer and rtpengine_answer explicitly.

**Comment by linussuk** [comment]
OK, will retest with rtpengine_answer explicit like suggested and report back tomorrow.

**Comment by linussuk** [comment]
Ok. Still fails. answer is occurring correctly now as per:

        if (has_body_part("application/sdp")) {
		if (isflagset(USE_RTP2)) {
			rtpengine_use_set("2");
			rtpengine_answer();


Jul  2 10:46:29 rdg-rtp-dev rtpengine[619]: INFO: [2001385157_133676718@x]: Received command 'answer' from x:40175
Jul  2 10:46:29 rdg-rtp-dev rtpengine[619]: DEBUG: [2001385157_133676718@x]: Dump for 'answer' from X:40175: { "sdp": "v=0

Initiation line is:
rtpengine_manage("trust-address replace-origin replace-session-connection ICE=remove xmlrpc-callback=x transcode-GSM transcode-PCMU transcode-G729");

Line initially included transcode-PCMA as well, but now tested without.

**Comment by rfuchs** [comment]
Ok thanks for taking care of that. Can you update to a newer master and try with that? There have been a number of related fixes since commit fbaaf22d, in particular I think that in your use case there's no need for transcoding and there were some commits that addressed this very issue.

**Comment by linussuk** [comment]
Ok - it'll take me a day or two to get onto this, so I'll close this issue for the moment and reopen if when I try the master it fails.

**Comment by elbow** [comment]
I'm seeing the same issue 1234567890*# sent came out the other side of rtpengine as 125346978*#0.  So I'll also try master and report.

**Comment by elbow** [comment]
Hi @linussuk (Mags Linus?) and @rfuchs 

I was having this problem with 7.5.2.6+0~mr7.5.2.6.  I updated to master as of today and it fixes the issue in my testing.

Thanks,
Steve
