### ISSUE TITLE
Explain release version numbering

### ISSUE THREAD

**Issue by billsimon** [sipwise/rtpengine#1028]
Hi, could you please explain the release version numbering ( & feature request, add to readme)? I see major releases 6, 7, and 8 still getting updates and would like to know how to choose the most appropriate release version for my use with opensips 3.0. Or is it preferred to use the latest code from the master branch at all times?

**Comment by rfuchs** [comment]
The last X.Y branch for each X (so 5.5, 6.5, 7.5, and soon 8.5) is an LTS branch and will receive bugfixes for years to come. Other than that, generally the last two X.Y branches (8.3 and 8.4 currently) receive bugfixes. X.Y.Z minor releases are branched from the respective X.Y periodically and generally only the last one for each X.Y receives bugfixes.

So, generally stick to X.Y branches if you're building yourself. Right now the most "stable" release is 8.4, while 7.5 is the latest LTS (until 8.5 is released). The master branch should generally be good to go as well, but can occasionally have bugs as all the new features go there.

**Comment by pwakano** [comment]
Sorry to write on a closed ticket, but I could not find anywhere what is the life cycle of the versions, and this is the question most related to versioning system used. So my questions are, how long is the LTS version supported? and is the X.5 always the LTS (so X.6 or X.7 never exists)?
