### ISSUE TITLE
how can I recv dtmf from outbound call.

### ISSUE THREAD

**Issue by zhangyww** [sipwise/rtpengine#1029]
when I make a inbound call     softphone -> (opensips)rtpengine ->freeswitch,  I can recv the dtmf in freeswitch.  But when I make a outbound call   freeswitch -> (opensips)rtpengine -> softphone,  I can not recv dtmf.  how can I recv dtmf from outbound call ? I don't want to open the transcode feature.

**Comment by rfuchs** [comment]
Receive how? Without transcoding, all media packets are passed through. So RFC DTMF events are passed through, and PCM DTMF tones are also passed through. What isn't working?

**Comment by zhangyww** [comment]
When I make inbound call, I see DTMD received in the log.


> Jun 30 08:41:23 testrtc215 rtpengine[15543]: DEBUG: [003FB3CC-D7B8-EA11-9646-FCE7B9B62F66@172.16.16.164 port 43508]: Received DTMF RTP packet: SSRC a487c385, PT 101, seq 2043, TS 65900, len 4
> Jun 30 08:41:23 testrtc215 rtpengine[15543]: DEBUG: [003FB3CC-D7B8-EA11-9646-FCE7B9B62F66@172.16.16.164 port 43508]: Primary RTP payload type for handling DTMF event is 0
> Jun 30 08:41:23 testrtc215 rtpengine[15543]: DEBUG: [003FB3CC-D7B8-EA11-9646-FCE7B9B62F66@172.16.16.164 port 43508]: Decoding RTP packet: seq 2043, TS 65900
> Jun 30 08:41:23 testrtc215 rtpengine[15543]: DEBUG: [003FB3CC-D7B8-EA11-9646-FCE7B9B62F66@172.16.16.164 port 43508]: DTMF event: event 2, volume 10, end 0, duration 57345
> Jun 30 08:41:23 testrtc215 rtpengine[15543]: DEBUG: [003FB3CC-D7B8-EA11-9646-FCE7B9B62F66@172.16.16.164 port 43508]: Scheduling to send RTP packet (seq 2043 TS 65900) at 0.000000
> Jun 30 08:41:23 testrtc215 rtpengine[15543]: DEBUG: [003FB3CC-D7B8-EA11-9646-FCE7B9B62F66@172.16.16.164]: Forward to sink endpoint: 172.16.0.233:49356 (RTP seq 2043 TS 65900)
> Jun 30 08:41:23 testrtc215 rtpengine[15543]: DEBUG: [003FB3CC-D7B8-EA11-9646-FCE7B9B62F66@172.16.16.164 port 43508]: Received DTMF RTP packet: SSRC a487c385, PT 101, seq 2044, TS 65900, len 4
> Jun 30 08:41:23 testrtc215 rtpengine[15543]: DEBUG: [003FB3CC-D7B8-EA11-9646-FCE7B9B62F66@172.16.16.164 port 43508]: Primary RTP payload type for handling DTMF event is 0
> Jun 30 08:41:23 testrtc215 rtpengine[15543]: DEBUG: [003FB3CC-D7B8-EA11-9646-FCE7B9B62F66@172.16.16.164 port 43508]: Decoding RTP packet: seq 2044, TS 65900
> Jun 30 08:41:23 testrtc215 rtpengine[15543]: DEBUG: [003FB3CC-D7B8-EA11-9646-FCE7B9B62F66@172.16.16.164 port 43508]: DTMF event: event 2, volume 10, end 1, duration 32770
> Jun 30 08:41:23 testrtc215 rtpengine[15543]: DEBUG: [003FB3CC-D7B8-EA11-9646-FCE7B9B62F66@172.16.16.164 port 43508]: Scheduling to send RTP packet (seq 2044 TS 65900) at 0.000000
> Jun 30 08:41:23 testrtc215 rtpengine[15543]: DEBUG: [003FB3CC-D7B8-EA11-9646-FCE7B9B62F66@172.16.16.164]: Forward to sink endpoint: 172.16.0.233:49356 (RTP seq 2044 TS 65900)
> Jun 30 08:41:23 testrtc215 rtpengine[15543]: DEBUG: [003FB3CC-D7B8-EA11-9646-FCE7B9B62F66@172.16.16.164 port 43508]: Received DTMF RTP packet: SSRC a487c385, PT 101, seq 2045, TS 65900, len 4
> Jun 30 08:41:23 testrtc215 rtpengine[15543]: DEBUG: [003FB3CC-D7B8-EA11-9646-FCE7B9B62F66@172.16.16.164 port 43508]: Primary RTP payload type for handling DTMF event is 0
> Jun 30 08:41:23 testrtc215 rtpengine[15543]: DEBUG: [003FB3CC-D7B8-EA11-9646-FCE7B9B62F66@172.16.16.164 port 43508]: Decoding RTP packet: seq 2045, TS 65900
> Jun 30 08:41:23 testrtc215 rtpengine[15543]: DEBUG: [003FB3CC-D7B8-EA11-9646-FCE7B9B62F66@172.16.16.164 port 43508]: DTMF event: event 2, volume 10, end 1, duration 8195
> Jun 30 08:41:23 testrtc215 rtpengine[15543]: DEBUG: [003FB3CC-D7B8-EA11-9646-FCE7B9B62F66@172.16.16.164 port 43508]: Scheduling to send RTP packet (seq 2045 TS 65900) at 0.000000


but when I make outbound call, I only see this


> Jun 30 08:39:45 testrtc215 rtpengine[15543]: DEBUG: [fc9c7c59-350c-1239-dda2-005056aecd66 port 43415]: Calling handler for RTCP packet type 201
> Jun 30 08:39:45 testrtc215 rtpengine[15543]: DEBUG: [fc9c7c59-350c-1239-dda2-005056aecd66 port 43415]: RR from aafc8ad4 about 8ffb11f2: FL 0 TL 1 HSR 51082 J 26 LSR 131466753 DLSR 85195
> Jun 30 08:39:45 testrtc215 rtpengine[15543]: DEBUG: [fc9c7c59-350c-1239-dda2-005056aecd66 port 43415]: Calculated round-trip time for 8ffb11f2 is 7759 us
> Jun 30 08:39:45 testrtc215 rtpengine[15543]: DEBUG: [fc9c7c59-350c-1239-dda2-005056aecd66 port 43415]: Calculated jitter for 8ffb11f2 is 3 ms
> Jun 30 08:39:45 testrtc215 rtpengine[15543]: DEBUG: [fc9c7c59-350c-1239-dda2-005056aecd66 port 43415]: Adding opposide side RTT of 0 us
> Jun 30 08:39:45 testrtc215 rtpengine[15543]: DEBUG: [fc9c7c59-350c-1239-dda2-005056aecd66 port 43415]: Calculated MOS from RR for aafc8ad4 is 4.3
> Jun 30 08:39:45 testrtc215 rtpengine[15543]: DEBUG: [fc9c7c59-350c-1239-dda2-005056aecd66 port 43415]: Calling handler for RTCP packet type 202

**Comment by zhangyww** [comment]
sorry for opening this issue , I found there is something wrong in freeswitch configuration,  rtpengine is fine.
