### ISSUE TITLE
rtpengine 7.5.3 core

### ISSUE THREAD

**Issue by descartin** [sipwise/rtpengine#1031]
dear all,

this might be related with issues treated on issues https://github.com/sipwise/rtpengine/issues/925 and https://github.com/sipwise/rtpengine/issues/915, where we got some patches that seemed to worked good and the version became stable and working good.

We noticed another core and i don know if it might have any relation with the other issue

```#0  0x000055fe37bcdbb1 in packet_dtmf_fwd (ch=ch@entry=0x7f65100a65a0, packet=packet@entry=0x7f651c0028f0, mp=mp@entry=0x7f64efffbe88, seq_inc=0) at codec.c:958
#1  0x000055fe37bcdd52 in packet_dtmf (ch=0x7f65100a65a0, packet=0x7f651c0028f0, mp=0x7f64efffbe88) at codec.c:1007
#2  0x000055fe37bcd115 in __handler_func_sequencer (mp=0x7f64efffbe88, packet=0x7f651c0028f0) at codec.c:829
#3  0x000055fe37bc3a2e in stream_packet (phc=0x7f64efffbe30) at media_socket.c:1800
#4  0x000055fe37bc3a2e in stream_fd_readable (fd=<optimized out>, p=0x7f64e40804c0, u=<optimized out>) at media_socket.c:1913
#5  0x000055fe37b8e5b0 in poller_poll (p=p@entry=0x55fe392c6930, timeout=timeout@entry=100) at poller.c:351
#6  0x000055fe37b8e94d in poller_loop (d=0x55fe392c6930) at poller.c:508
#7  0x000055fe37b8ea69 in thread_detach_func (d=0x55fe392cf840) at aux.c:207
#8  0x00007f655e5374a4 in start_thread (arg=0x7f64effff700) at pthread_create.c:456
#9  0x00007f655e075d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```
I add you a full backtrace of the core

Could you please take a look?
Now we are running the version
Version: 7.5.3.0+0~mr7.5.3.0 git-mr7.5-925-212d71e2

thanks a lot and regards
david
[core_25junio_btfull.log](https://github.com/sipwise/rtpengine/files/4852050/core_25junio_btfull.log)

**Comment by descartin** [comment]
this is the last commit we made a cherry pick on the mr7.5.3 version
``` 
commit 443ccec606731300124505e6667b81025db15990
Author: Richard Fuchs <rfuchs@sipwise.com>
Date:   Tue Feb 11 08:39:50 2020 -0500

    avoid calling a non existant encoder
    
    fixes #925
    
    Change-Id: I4743f0e87234fe3ddeb36b7355dcf80f651996c3
    (cherry picked from commit 088c58d88dbd9e0e45e3fbfb53de7b4fe3ab26c7)

```

**Comment by rfuchs** [comment]
I'm not able to debug this since you're running your own branch with your own commits. I suggest updating to our mr7.5, rebuild, and go from there.

**Comment by descartin** [comment]
Dear Richard

Ok, i had a branch based on remotes/origin/rfuchs/915-mr7.5 (commit 375d4bb055065fae149fc9a22a746d0057f1269b), and after that i added
```
commit 443ccec606731300124505e6667b81025db15990
Author: Richard Fuchs <rfuchs@sipwise.com>
Date:   Tue Feb 11 08:39:50 2020 -0500

    avoid calling a non existant encoder
    
    fixes #925
    
    Change-Id: I4743f0e87234fe3ddeb36b7355dcf80f651996c3
    (cherry picked from commit 088c58d88dbd9e0e45e3fbfb53de7b4fe3ab26c7)
```
by a cherry-pick when you provided the fixes on the issues.

But anycase, **i compiled now 
Version: 7.5.4.2+0~mr7.5.4.2 git-updated_7.5.4-a8bcb373**
since that branch includes all the fixes you provide for tha past issues 898, 915, 925
and i will lt you know if we have any other issue

thanks a lot and regards
david

**Comment by rfuchs** [comment]
I assume this can be closed then?

**Comment by descartin** [comment]
hello Richard

the servers are running ok by now, so we can close it and i will let you know if any issue is observed

thanks  a lot and regards
david
