### ISSUE TITLE
Video RTP packets erroneously briefly forwarded to audio port

### ISSUE THREAD

**Issue by jovermann** [sipwise/rtpengine#1032]
Setup: rtpengine acts as RTP proxy between an external UA providing video (camera and no display) and an internal UA (display and no camera). rtpengine driven by Kamailio 5.2.1 using the ng protocol. Happens with rtpengine mr8.3.1 and master (yesterday).

This happens:
The external UA sends an invite with audio+video in the SDP, the internal UA responds immediately with Session Progress, requesting video only in the SDP. The internal UA display the video as expected. Eventually the user will accept the call on the internal UA with 200 OK, requesting audio+video in the SDP. Immediately after the internal UA picks up the call (200 OK), rtpengine forwards about 20-40 video frames to the audio port. After that all packets go to the correct ports.

(Background: Why is this a problem?
A sane internal UA would simply drop the video packets received on the audio, or even process them using the video decoder. The problem was only noticed since the audio receiver in the internal UA chokes on the video packets and stops processing audio, leading to "no audio from external to internal", although rtopengine continues to forward all audio packets correctly to the internal UA at any point in time. This is a bug in the internal UA which is out of scope of this issue, just to explain why the problem in rtpengine was detected. Fixing the internal UA would also fix the "no audio" problem, but this is not always possible.)

Analysis: The 20-40 video packets going to the wrong port are the packets between the point in time when rtpengine (driven by Kamailio) already switched from video-only to audio-video, and the point when the external UA processes the 200 OK SDP generated by rtpengine and switches to the new video port.

All SDP messages looks good and all UAs send to the expected ports at any time. Just rtpengine

This is what happens concretely in terms of ports:
1. Session Progress: rtpengine asks video to be sent to port 31848
2. External UA startes sending to 31848. OK.
3. Internal UA answers call. Rtpengine asks  for audio on port 31878 and video on port 31862. OK. All differnt ports. No confusion.
4. External UA continues to send video packets to 31848 until it processed the 200 OK. Still OK.
5. Rtpengine erroneously sends the video packets received on the video port 31848 to the audio port of the internal UA. Error.
6. Eventually the external UA switches sending video packets from port 31848 to the new video port 31862. OK.
7. Rtpengine forwards all packets correctly from now on.

Theory: Apparently rtpengine re-uses media slots (the things called "Media #1 and Media #2 in the INFO log messages) from video to audio when switching from video-only to audio+video. It does not firmly associate the receiving and sending ports with the media streams transported over them.

Expected behaviour: Two behaviours would be acceptable: 
1. When switching from video-only to audio+video rtpengine continues to forward video packets received from the external UA to the old video port of the internal UA.
2. When switching from video-only to audio+video rtpengine drops all video packets received on the old video port and does not forward them.

Workaround: I have hacked a check into __send_timer_send_common() which drops all packets whose payloads are neither in st->sink->media->codecs_send nor in st->sink->media->codecs_recv. This works, but it would be more elegant to stop the packets upon reception, or even better, select the correct video sink for them, but I struggle to find where to do this.

I will send a pull request with my hack shortly.

**Comment by rfuchs** [comment]
Can you post a concrete example of what you see going on, especially with the SDP bodies involved? I have a feeling that this is actually due to a broken UA.

**Comment by jovermann** [comment]
Hi Richard,

many thanks for replying so quickly. I attached two tcpdump captures of the internal (eth0.pcap) and external (eth2.pcap) interfaces, and also the syslog of kamailio and rtpengine. The pcap files contain all the SDP bodies. Let me know if I should extract just the SDP bodies.

(I cannot attach files to the github issue, nasty! :-) )

192.168.8.2 is the internal UA and 192.168.7.3 is the external UA. 192.168.8.1 is the internal interface of the proxy and 192.168.7.1 is its external interface.

You can see the problem in eth0.pcap at packet number 660, immediately after the 200 OK: The packets 660-679 go to port 10500 (audio port of the internal UA) while they should either go to 11500 (video port of the internal UA) or they should be dropped by rtpengine.

And yes, I fully agree the patch is not good for the general case. It would be good to drop the packets much earlier, for example immediately after reception, after re-using media slot #1 for audio (from video). When re-using such a media slot (which is an rtpengine internal artifact) all traffic on all incoming ports should be either discarded, or it should somehow be sent to the originally intended destination (which would mean not to re-use the media slot #1). 

This can all be done without looking at the packet content. Just by correctly mapping the input and output ports. At the moment rtpengine is briefly forwarding between input and output ports which are not associated through SDP bodies, which is why I think this is a bug in rtpengine.

The underlying question regarding whether to discard or whether to forward is: When receiving another SDP, does is overwrite the first SDP, or does it add to it? I do not know the answer, but actually I also do not care much. I only care about not sending packets to a port to which they were never intended to be sent to.

If you could point me to the code in rtpengine which makes the decision onto which media slot an incoming packet should be mapped I will try to fix that. Or is it possible to tell rtpengine not to re-use media slots when additional SDPs arrive? This would also immediately solve the problem.

Any comments and insights welcome.

Cheers,
Johannes

> Am 01.07.2020 um 14:15 schrieb Richard Fuchs <notifications@github.com>:
> 
> 
> Can you post a concrete example of what you see going on, especially with the SDP bodies involved? I have a feeling that this is actually due to a broken UA.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

-- 
Johannes.Overmann@joov.de (http://joov.de)
Fichtenstr. 5, 79194 Gundelfingen, +49 761 556 3222

**Comment by rfuchs** [comment]
Your attachments were lost...

You can attach files here if you zip them up first.

**Comment by jovermann** [comment]
So github stripped them. I attached a zip file now.

Cheers,
Johannes

> Am 01.07.2020 um 16:39 schrieb Richard Fuchs <notifications@github.com>:
> 
> 
> Your attachments were lost...
> 
> You can attach files here if you zip them up first.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

-- 
Johannes.Overmann@joov.de (http://joov.de)
Fichtenstr. 5, 79194 Gundelfingen, +49 761 556 3222

**Comment by rfuchs** [comment]
I don't think you can attach files via email.

**Comment by jovermann** [comment]
Argh! 

Now via Firefox Send: https://send.firefox.com/download/47c3684ab3900f86/#QpAmSc10wPW5w8oOnaOxCg


> Am 01.07.2020 um 16:49 schrieb Richard Fuchs <notifications@github.com>:
> 
> 
> I don't think you can attach files via email.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

-- 
Johannes.Overmann@joov.de (http://joov.de)
Fichtenstr. 5, 79194 Gundelfingen, +49 761 556 3222

**Comment by rfuchs** [comment]
Ok, just as I expected. Or in fact it's even worse than I expected.

So the offer contains two `m=` lines: one audio and one video. Then the answer only contains one `m=` line for video. This is completely broken behaviour and goes against RFC 3264:
```
   For each "m=" line in the offer, there MUST be a corresponding "m="
   line in the answer.  The answer MUST contain exactly the same number
   of "m=" lines as the offer.  This allows for streams to be matched up
   based on their order.  This implies that if the offer contained zero
   "m=" lines, the answer MUST contain zero "m=" lines.
```
If the answer wishes to ignore the audio offer and only proceed with video, it MUST still include an `m=` line for the audio media. Everything else is completely broken.

**Comment by jovermann** [comment]
Thanks for clarifying that. I must admit, this was not clear to me.
