### ISSUE TITLE
DTLS - key negotiation is not started to a-leg

### ISSUE THREAD

**Issue by sergey-safarov** [sipwise/rtpengine#1035]
I have a test stand `Linphone -> RTPengine -> FreeSwitch`.
1) Linphone start DTLS call;
2) RTPengine decrypt call;
3) FreeSwitch process unencrypted call.

On this stand, I found:
1) Linphone public IP properly discovered;
2) but DTLS key negotiation not started because RTPengine does not sends a Client certificate to Linpphone.

Full RTPengine log and PCAP from RTPengine hosts are attached.
[rtpengine-dtls.pcap.gz](https://github.com/sipwise/rtpengine/files/4859851/rtpengine-dtls.pcap.gz)
[rtpengine-dtls.txt](https://github.com/sipwise/rtpengine/files/4859852/rtpengine-dtls.txt)

**Comment by sergey-safarov** [comment]
on kamailio side used commands
```
rtpengine_offer("RTP/AVP ICE=remove rtcp-mux-demux")
rtpengine_answer("UDP/TLS/RTP/SAVPF SDES-off ICE=force ");
```

**Comment by rfuchs** [comment]
Looks like this is because the ICE negotiation never finishes. I see that the priority of all 8 ICE candidates given in the received offer is the same (2130706303 for RTP and 2130706302 for RTCP). RFC 5245 says that `Each candidate for a media stream MUST have a unique priority that MUST be a positive integer between 1 and (2**31 - 1)` and I believe that's what causes the ICE process to be stalled.

**Comment by sergey-safarov** [comment]
I opened the ticket https://github.com/BelledonneCommunications/linphone-desktop/issues/399 for behavior.

Is possible here some workaround on the RTPengine side for similar badly SIP clients.
And for information write a warning for badly RFC5245 implementation?

**Comment by rfuchs** [comment]
Yes, but I'd like to confirm that this is actually the reason first, and that there isn't some other underlying issue lurking.

**Comment by sergey-safarov** [comment]
Yes, looks as this is the root of the issue.
I have disabled ICE in `Linpone` side and `RTPengnie` started key negotiation over DTLS.
Details in the attached files.

[no-ice-dtls.txt](https://github.com/sipwise/rtpengine/files/4866149/no-ice-dtls.txt)
[no-ice-dtls.pcap.gz](https://github.com/sipwise/rtpengine/files/4866150/no-ice-dtls.pcap.gz)

**Comment by rfuchs** [comment]
Trying to reproduce this, which version of Linphone are you using?

**Comment by sergey-safarov** [comment]
I use the latest appimage. https://www.linphone.org/snapshots/AppImages/
I have downloaded `Linphone-4.3.0-alpha.1+439d1882.AppImage`.

**Comment by rfuchs** [comment]
I've pushed some commits to branch `rfuchs/1035` that should improve this situation a bit. In particular it should allow DTLS to start and media to flow even if ICE doesn't finish.

Still working on detecting and handling the incorrect ICE priorities.

**Comment by sergey-safarov** [comment]
Just made a test  commit 91be78e4a216c8b6d387f1f3967f5b03de42b27b
Logs in the attached files.
[rtpengine-dtls2.pcap.gz](https://github.com/sipwise/rtpengine/files/4898346/rtpengine-dtls2.pcap.gz)
[rtpengine-dtls2.txt](https://github.com/sipwise/rtpengine/files/4898347/rtpengine-dtls2.txt)

Using PCAP file and Wireshark filer 'udp.port==16398' I see only `STUN` messages and not `DTLS` packets.

**Comment by rfuchs** [comment]
I'm afraid it's not currently feasible to work around this because the code relies heavily on the uniqueness of the ICE priorities.

**Comment by sergey-safarov** [comment]
Thanks, will try open feature request on Kamailio repo to patch SDP.

**Comment by rfuchs** [comment]
I'm not sure this would be enough. The priority is also communicated within the STUN packets and so you'd still get conflicts even if they're not listed in the SDP.

**Comment by sergey-safarov** [comment]
Attached log example of the current `master` with "Priority collision between candidate pairs" warning.
[rtpengine-dtls3.txt](https://github.com/sipwise/rtpengine/files/4899085/rtpengine-dtls3.txt)

**Comment by sergey-safarov** [comment]
Work-around to use DTLS with ICE.

If SDP transport ("UDP/TLS/RTP/SAVPF") passed to `FreeSwitch`, then RTPproxy transparently passes DTLS packets from FreeSwitch to Linphone.
