### ISSUE TITLE
Master (8.5?): "DTLS error: 1 (unexpected message)" for a couple of clients

### ISSUE THREAD

**Issue by elbow** [sipwise/rtpengine#1038]
Hi,

I updated my rtpengine to MASTER branch to deal with the DTMF duplication that was raised in issue #1027.
Updating to master did fix that problem.

Since then I am seeing an error " DTLS error: 1 (unexpected message)" for one or two clients.

rtpengine logs the error "DTLS error:1 (unexpected message)".

Client side logs:

```
common.js:114 JsSIP:ERROR:RTCSession emit "peerconnection:setremotedescriptionfailed" [error:DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Failed to apply the description for 0: Failed to set SSL role for the transport.]
```

This is rare - 45 occurrences out of 4000-odd calls.   But right now I can't see what is special about the users having the problem   So I'm hoping for a pointer as to how to diagnose it.

Thanks,
@Elbow

**Comment by elbow** [comment]
Could it be this recent commit?

```
Author: Richard Fuchs <rfuchs@sipwise.com>
Date:   Wed Jul 8 09:18:46 2020 -0400

    TT#84804 start DTLS as soon as ICE can communicate
    closes #1035
    Change-Id: I5cce8ab986f7d75d7ad88c53b4cc3b48f99a206a
```

**Comment by rfuchs** [comment]
That would be unexpected but you're welcome to revert that commit and try.

Generally a pcap for an affected call would be helpful, but I understand that this can be difficult if it only appear sporadically. Running with log level 7 could also be helpful.

**Comment by elbow** [comment]
Hi @rfuchs ,

I reproduced this issue on my test setup.

Using master head with the test call (candidates are the client's actual address 10.64.16.132 (which can reach the rtpengine box directly) and relay AAA.BBB.250.156, on the same subnet as the rtpengine.

rtpengine logs `DTLS error: 1 (unexpected message)`

Here is the INVITE:

```
INVITE sip:*1@rtc.tXXXX.com SIP/2.0
Via: SIP/2.0/WSS j5l1bqflur8b.invalid;branch=z9hG4bK4867368
Max-Forwards: 69
To: <sip:*1@rtc.tXXXX.com>
From: "2262" <sip:2852262@rtc.XXXX.com>;tag=gp3e93lvm0
Call-ID: anmgssgg62bkgbanolsv
CSeq: 5970 INVITE
Proxy-Authorization: Digest algorithm=MD5, username="285DDDD", realm="rtc.tXXXX.com", nonce="Xw3UNl8N0wos66Bdl5uAsY2oo0T1Kxeo", uri="sip:*1@rtc.tXXXX.com", response="04bd55ebc526fcd7b1ee1e0f2a6a189c"
Contact: <sip:2gvk5md3@j5l1bqflur8b.invalid;transport=ws;ob>
Content-Type: application/sdp
Session-Expires: 90
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
Supported: timer,ice,replaces,outbound
User-Agent: XXXX web 1.0 000
Content-Length: 1917

v=0
o=- 338364675231785358 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic: WMS pPvpQv2sjHtUSioZJQKrb6v3ox1bkPhGlG3T
m=audio 35983 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 AAA.BBB.250.156
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:2365191058 1 udp 2122260224 10.64.16.132 62680 typ host generation 0 network-id 1 network-cost 10
a=candidate:4039013047 1 udp 41885695 AAA.BBB.250.156 35983 typ relay raddr 10.64.16.132 rport 62680 generation 0 network-id 1 network-cost 10
a=ice-ufrag:7n+z
a=ice-pwd:OoMjv5DFWOxeYrTYR39JFXh8
a=ice-options:trickle
a=fingerprint:sha-256 B7:47:0A:19:DD:BE:60:A9:07:F8:21:BA:05:99:1C:DC:8F:F1:63:A0:95:76:1A:3B:94:83:12:FC:3A:71:72:F2
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:pPvpQv2sjHtUSioZJQKrb6v3ox1bkPhGlG3T e223670e-2520-4cd4-bf94-614ce0d93101
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:447619327 cname:LmVR6Mkgi5k4mNuT
a=ssrc:447619327 msid:pPvpQv2sjHtUSioZJQKrb6v3ox1bkPhGlG3T e223670e-2520-4cd4-bf94-614ce0d93101
a=ssrc:447619327 mslabel:pPvpQv2sjHtUSioZJQKrb6v3ox1bkPhGlG3T
a=ssrc:447619327 label:e223670e-2520-4cd4-bf94-614ce0d93101 
```

here is the OK that was sent back:

```
SIP/2.0 200 OK
Via: SIP/2.0/WSS j5l1bqflur8b.invalid;branch=z9hG4bK4867368;received=10.64.16.132;rport=56754
From: "2262" <sip:285dddd@rtc.xxxx.com>;tag=gp3e93lvm0
To: <sip:*1@rtc.xxxx.com>;tag=aZeS480663U2p
Call-ID: anmgssgg62bkgbanolsv
CSeq: 5970 INVITE
Contact: <sips:AAA.BBB.250.154:4433;transport=wss>
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Content-Type: application/sdp
Content-Length: 736

v=0
o=root 1884940906 1884940906 IN IP4 AAA.BBB.250.134
s=Telviva
c=IN IP4 AAA.BBB.250.154
t=0 0
m=audio 16680 UDP/TLS/RTP/SAVPF 111 110 112 113 126
a=maxptime:150
a=mid:0
a=rtpmap:111 opus/48000/2
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=fmtp:111 minptime=10;useinbandfec=1
a=fmtp:126 0-16
a=sendrecv
a=rtcp:16680
a=rtcp-mux
a=setup:passive
a=fingerprint:sha-1 78:67:47:9C:61:40:9C:12:0A:8F:AC:4A:67:C1:79:74:83:AE:14:EF
a=ptime:20
a=ice-ufrag:dOETRZy8
a=ice-pwd:NEIS3ogLy0nrot8SokfvbYYdTc
a=ice-options:trickle
a=candidate:SXLovURH9IIeuE8V 1 UDP 2130706431 AAA.BBB.250.154 16680 typ host
a=end-of-candidates 
```

On the client side the reply causes an error and it immediately BYEs the call with a Not Acceptable Here.

My hypothesis was that commit 54a39db40faaab83e12af0e78ac9d7c45cf3fd2d was involved since it starts DTLS sooner.

Here is the debug log for this case, using the latest master:

[rtpengine-dtls-unexpected-message.log](https://github.com/sipwise/rtpengine/files/4920405/rtpengine-dtls-unexpected-message.log)

I then checked out at commit cba812747584676c28ee4b6f275b32df130eb70f, which was the preceding commit.

(I tried to revert just the commit 54a39db40faaab83e12af0e78ac9d7c45cf3fd2d but got in a mess since later commits change the same code).

With this checkout the call is able to connect:

[rtpengine-dtls-unexpected-message-after-revert-to-cba812747584676c28ee4b6f275b32df130eb70f.log](https://github.com/sipwise/rtpengine/files/4920406/rtpengine-dtls-unexpected-message-after-revert-to-cba812747584676c28ee4b6f275b32df130eb70f.log)

I hope that this is helpful.

Let me know what else I can provide.

**Comment by rfuchs** [comment]
Ah because you're using `DTLS=passive` in the answer... Can you try without that?

**Comment by elbow** [comment]
Hi Richard.

In my application I am using rtpengine between a webrtc based SRTP/Opus side (the "outside") and a plain RTP/G722 side ("inside").

But technically I do want to accept clients using plain RTP on the outside.

In the test I've been doing I was calling from the "outside" to the "inside".  I used DTLS=off on the offer (to remove DTLS) and DTLS=passive on the answer to accept but not require DTLS on that side.

For calls going the way I do the reverse - DTLS=passive on the offer (inside->outside) and DTLS=off on the answer.

Does this seem reasonable?  It was working for us with 7.5.2.6.

Anyway - I did change DTLS=passive to DTLS=on and it does dodge this `DTLS error: 1 (unexpected message)`.

Here's the new trace:

[rtpengine-latest-master-using-dtls=on-in-answer.log](https://github.com/sipwise/rtpengine/files/4925428/rtpengine-latest-master-using-dtls.on-in-answer.log)

Thanks,
@Elbow (Steve)

**Comment by rfuchs** [comment]
Ok good. To explain: DTLS=passive is only meant as a workaround in case active-mode DTLS is not working for some reason. The intended way to use DTLS is without forcing passive mode, which is the default and is what happens when you simply omit the `DTLS` flag. So unless there's a good reason to force passive mode, I would suggest not to do so.

That being said, passive mode DTLS is still supposed to work if so desired, so I'll have a fix for this shortly.

**Comment by rfuchs** [comment]
So with the commit above (ec061bb) you should be able to add `DTLS-reverse=passive` to your offer flags to fix things up. Alternatively you can use the `dtls-passive` config option to globally force passive mode. But again, as I said before, you shouldn't really have to do any of this. In fact I believe you should be able to just omit all DTLS flags altogether and things should just work.

**Comment by elbow** [comment]
OK, thanks.

I don't recall the circumstances for using dtls=passive so I'm a little nervous to switch  but I'll test.

Thanks so much for the help

**Comment by elbow** [comment]
Hi,

Just for completeness - since I was dealing with issue #1059 I went back to this one.

I can confirm that removing the DTLS: passive option does resolve this issue.

Chrome sends "a=setup:actpass".  rtpengine replies "a=setup:active".

With DTLS: passive rtpengine's reply is "a=setup:passive".

Skimming the RFC it seems that a=setup:passive is permitted and then Chrome should initiate the TLS.

But is seems rtpengine contradicts itself from Chrome's point of view by saying "passive" but actually "start(ing) DTLS as soon as ICE can communicate" as per the commit of July 8th.
