### ISSUE TITLE
Problem with rtpe, opensips, and UAs all behind NAT

### ISSUE THREAD

**Issue by robdyck** [sipwise/rtpengine#1039]
Similar to issue #315 but pretty much webRTC specific. The scenario is external webrtc agent is calling a webrtc agent behind the NAT. More simplistic agents work fine with this setup with either rtpproxy or rtpengine. The trick to make it work there is use the media address parameter. With webrtc we have a problem. ICE is mandatory with webrtc so rtpproxy won't do. While rtpengine is ICE aware we still have a problem. The media address parameter/flag alters the c and m lines in the SDP. This works in the no ICE case. The webrtc agents I have tested ignore the c and m lines and only consider the candidates. Unfortunately media-address is not put into the candidate that rtpengine has inserted.

I have been using iptables DNAT as work around. When the agent behind the NAT sends its binding request to the public address, which won't work because the typical home router will not hairpin, the DNAT changes the address to rtpengine's actual private address.

If there is some configuration I have missed, put me out of my misery. Otherwise consider this a feature request. I can see two possible fixes. First have rtpengine put media-address into its candidate. Second possibility is to give ICE its own flag. Perhaps like candidate-media-address.

**Comment by rfuchs** [comment]
Can you post a concrete examples please, of what you see and what you expect to see instead.

**Comment by robdyck** [comment]
Agent A somewhere behind a NAT sends an INVITE to agent B behind NAT.  Opensips and rtpengine are behind the same NAT.

SDP from agent A (partial) before rtpengine
v=0
o=- 8709587266468576491 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic: WMS xULr2DQasLySTkPEHFPNmROWpUyPgtB6odqg
m=audio 9937 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 209.52.88.231
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:4242527773 1 udp 2122260223 192.168.42.184 44226 typ host generation 0 network-id 1 network-cost 50
a=candidate:810740110 1 udp 1686052607 209.52.88.231 9937 typ srflx raddr 192.168.42.184 rport 44226 generation 0 network-id 1 network-cost 50
a=candidate:2992384749 1 tcp 1518280447 192.168.42.184 9 typ host tcptype active generation 0 network-id 1 network-cost 50

SDP after rtpengine. Note that c and m lines have been altered by rtpengine to show the local rtpengine address and port. Also note that rtpengine inserted candidates at the end. The rtpengine port is correct but the address is unreachable, must be local private address. ( Address altered for privacy ). The candidate should be the same as the c and m lines.
v=0
o=- 8709587266468576491 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic: WMS xULr2DQasLySTkPEHFPNmROWpUyPgtB6odqg
m=audio 35000 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 192.168.1.1
a=candidate:4242527773 1 udp 2122260223 192.168.42.184 44226 typ host generation 0 network-id 1 network-cost 50
a=candidate:810740110 1 udp 1686052607 209.52.88.231 9937 typ srflx raddr 192.168.42.184 rport 44226 generation 0 network-id 1 network-cost 50
a=candidate:2992384749 1 tcp 1518280447 192.168.42.184 9 typ host tcptype active generation 0 network-id 1 network-cost 50
.
.
a=candidate:8cOujTMTI3Huu9pT 1 UDP 2122260479 50....44 35000 typ host
a=candidate:8cOujTMTI3Huu9pT 2 UDP 2122260478 50....44 35001 typ host

**Comment by robdyck** [comment]
Forgot the rtpengine flags
        $var(rtpengine_flags) = "SIP-source-address media-address=192.168.1.1";
        if !rtpengine_offer("$var(rtpengine_flags)")
        drop;
        }
        $var(rtpengine_flags) = "SIP-source-address";
        if !rtpengine_answer("$var(rtpengine_flags)")
        drop;

**Comment by rfuchs** [comment]
Is there a good reason to use the `media-address` flag instead of setting the advertised address for the interface? (Not that this doesn't need fixing, just wondering)

**Comment by robdyck** [comment]
Did you mean something like this --
listen=wss:192.168.1.1:8000 as bogus.com:8000 # public address
It doesn't help.

**Comment by rfuchs** [comment]
No I'm talking about the `interface` config. If your private NAT address is X and the respective public address is Y, you would configure the interface as something like `X!Y`. That way rtpengine would locally bind to X but put Y into the SDP.

**Comment by robdyck** [comment]
But we want X in the SDP. ( for WAN to LAN ). WAN to WAN we need the public address.

**Comment by rfuchs** [comment]
So configure two interfaces, one with advertised address and one without, and use `direction=` to select which one to use.

**Comment by robdyck** [comment]
A host on the LAN with the same address as the router. ( one to one NAT ) I see a conflict.

**Comment by rfuchs** [comment]
No, not two interfaces on the host. Two interfaces in the rtpengine config.

**Comment by robdyck** [comment]
I am using two interfaces for IPV4 <-> IPV6
### a single interface:
# interface = 123.234.345.456
### separate multiple interfaces with semicolons:
# interface = internal/12.23.34.45;external/23.34.45.54
### for different advertised address:
# interface = 12.23.34.45!23.34.45.56
interface = ipv4/192.168.1.1!50...44;ipv6/2001::

**Comment by rfuchs** [comment]
So something like:
`interface = ipv4-priv/192.168.1.1;ipv4-ext/192.168.1.1!50...44;ipv6/2001::`

**Comment by robdyck** [comment]
I thought we were limited to two interfaces.

**Comment by rfuchs** [comment]
No you can configure as many as you like

**Comment by robdyck** [comment]
OK, I'll play around with it. For now life intrudes.

**Comment by robdyck** [comment]
It worked. This is better than my iptables DNAT work around. I know that it is not my decision but I think the more elegant solution is to have the media-address flag apply to the candidate. After all the flag was invented for this sort of topology.

WAN to LAN scenario

rtpengine config
interface = ipv4-priv/192.168.1.1;ipv4-ext/192.168.1.1!50...44;ipv6/2001::

opensips script      
 $var(rtpengine_flags) = "out-iface=ipv4-priv in-iface=ipv4-ext SIP-source-address";
        if !rtpengine_offer("$var(rtpengine_flags)")
        drop;

$var(rtpengine_flags) = "out-iface=ipv4-ext in-iface=ipv4-priv SIP-source-address";
        if !rtpengine_answer("$var(rtpengine_flags)")
        drop;

**Comment by rfuchs** [comment]
Ah, but no, the `media-address` flag was not actually invented for that. The proper way to handle multiple different interfaces is, yes, through configuring and using multiple different interfaces. In particular, `media-address` is not usable for logical interfaces that contain multiple underlying interfaces at the same time for an ICE setup, as specifying an override address would override the address of all of these underlying interfaces, rendering them completely useless. That being said, the fix for this is coming shortly anyway.

**Comment by robdyck** [comment]
I'll look forward to the official solution. Thank you for the time spent.
