### ISSUE TITLE
RTPEngine "crashes" on assert(sub_label != NULL)

### ISSUE THREAD

**Issue by jakubkarolczyk** [sipwise/rtpengine#1042]
Hi Richard,

As in the topic. It's caught after you make at least one call since start the new daemon process.

[1594764302.143475] INFO: Received command 'statistics' from 127.0.0.1:33471
[1594764302.143529] DEBUG: Dump for 'statistics' from 127.0.0.1:33471: { "command": "statistics" }
rtpengine: statistics.c:761: statistics_ng: Assertion `sub_label != ((void *)0)' failed.

Thanks,
Jakub

**Comment by rfuchs** [comment]
Can't reproduce that. Any more information? More complete log, backtrace?

**Comment by jakubkarolczyk** [comment]
Please find both attached.

[bt.log](https://github.com/sipwise/rtpengine/files/4921818/bt.log)
[rtpengine.log](https://github.com/sipwise/rtpengine/files/4921819/rtpengine.log)
