### ISSUE TITLE
[Question] Why isn't it possible to access the allocated ports of RTPEngine ports?

### ISSUE THREAD

**Issue by idoMajor41** [sipwise/rtpengine#1044]
Hello,

I use a SIPREC server + drachtio + RTPEngine in order to record calls.
I tried to test out ffprobe and GStreamer on the ports of an allocated call.
 
When I tried accessing those ports directly with ffprobe I had received a message that those ports are already binded.
Once I tried using GStreamer to take the udp source(RTP) and save it to a wav file, it did worked only for the called side of the call, but the side of the caller it didn't.
By saying it didn't worked, the file of the called party was getting big and had the details of the media inside of it, while for the caller side, the file didn't get big at all(zero bytes) and no media description were added as well.

I made a pipeline of GStreamer that simply copies from the allocated ports to another port of mine.
Afterward, with that new port, I ran the ffprobe tool again,
The result was getting details on the called side port, and the caller side I didn't receive anything at all.

When I do shutdown RTPEngine after the call was established, and try working with both parties ports with gstreamer/ffprobe directly it works great(save to wav or see ffprobe output about the data).

So the question is, does RTPEngine do something special regarding the caller side of the call in terms of his packets or permissions to access it?

Thanks!

**Comment by rfuchs** [comment]
Rtpengine doesn't do anything special with the ports it allocates. But it sounds like you're trying to listen on the same ports with two applications at the same time? That will never work.

**Comment by idoMajor41** [comment]
Basically you're right with what you're saying that 2 applications can't listen to the same port.
But I did manage to receive 1 RTP port of the data with GStreamer while the other I couldn't.
Because of that, I wanted to ask if there's a specific behavior for a particular port of the conversation.

**Comment by rfuchs** [comment]
No there's nothing special going on. I'm pretty sure that two sockets listening on the same port gives you undefined behaviour, e.g. one of them receiving everything and the other one nothing, or perhaps even packets randomly distributed between then. So I suggest you just don't do that.
