### ISSUE TITLE
"timeout waiting reply for command "delete" from RTP proxy"" present in Kamailio logs when stats response exceeds the MTU 

### ISSUE THREAD

**Issue by kcroxford-mb** [sipwise/rtpengine#1045]
We are experiencing an issue where Kamailio does not receive a response from RTPengine when deleting a WebRTC call.  The payload that RTPengine sends is massive, and an example can be seen at the bottom of this. 

We are hosted this in a cloud provider and cannot adjust the MTU like to accommodate this traffic. Ideally we would switch this to TCP, and not worry about packet reordering, but I know that is not an option. With that in mind, is there any way to easily reduce what is presented in the dictionary response (apart from modifying call_interfaces.c)? 

Payload Example 
`d2:id20:0uff9a5tu11nnl777n472:ts16:15949015594291383:uid36:d0dd9fce-657c-4ba5-8f15-31693cece234e d7:createdi1594900250e10:created_usi6775e11:last signali1594900253e4:SSRCd10:1159134831d11:average MOSd3:MOSi42e15:round-trip timei10777e6:jitteri16e11:packet lossi0e7:samplesi261ee10:lowest MOSd3:MOSi39e15:round-trip timei349140e6:jitteri19e11:packet lossi3e11:reported ati1594900369ee11:highest MOSd3:MOSi43e15:round-trip timei8813e6:jitteri17e11:packet lossi1e11:reported ati1594900258ee15:MOS progressiond8:intervali130e7:entriesld3:MOSi43e15:round-trip timei8813e6:jitteri17e11:packet lossi1e11:reported ati1594900258eed3:MOSi43e15:round-trip timei7651e6:jitteri16e11:packet lossi1e11:reported ati1594900388eed3:MOSi43e15:round-trip timei7771e6:jitteri17e11:packet lossi1e11:reported ati1594900518eed3:MOSi43e15:round-trip timei8333e6:jitteri16e11:packet lossi0e11:reported ati1594900648eed3:MOSi43e15:round-trip timei7228e6:jitteri17e11:packet lossi1e11:reported ati1594900778eed3:MOSi43e15:round-trip timei7825e6:jitteri17e11:packet lossi1e11:reported ati1594900908eed3:MOSi43e15:round-trip timei7786e6:jitteri16e11:packet lossi1e11:reported ati1594901038eed3:MOSi43e15:round-trip timei8165e6:jitteri17e11:packet lossi1e11:reported ati1594901168eed3:MOSi43e15:round-trip timei8106e6:jitteri16e11:packet lossi0e11:reported ati1594901298eed3:MOSi43e15:round-trip timei7370e6:jitteri16e11:packet lossi1e11:reported ati1594901428eed3:MOSi43e15:round-trip timei7426e6:jitteri16e11:packet lossi0e11:reported ati1594901558eeeee10:1197334433dee4:tagsd10:o9uhn16dj6d3:tag10:o9uhn16dj67:createdi1594900250e16:in dialogue with36:19ac477d-4bab-4246-8023-b99d1eb88c726:mediasld5:indexi1e4:type5:audio8:protocol17:UDP/TLS/RTP/SAVPF7:streamsld10:local porti30722e8:endpointd6:family4:IPv47:address14:2.2.2.294:porti52334ee19:advertised endpointd6:family4:IPv47:address14:3.3.3.374:porti56932ee12:crypto suite23:AES_CM_128_HMAC_SHA1_8011:last packeti1594901558e5:flagsl3:RTP4:RTCP6:filled9:confirmed10:kernelized25:DTLS fingerprint verified3:ICEe4:SSRCi1197334433e5:statsd7:packetsi64555e5:bytesi5986217e6:errorsi0eeed10:local porti30723e8:endpointde19:advertised endpointde12:crypto suite23:AES_CM_128_HMAC_SHA1_8011:last packeti1594900250e5:flagsl4:RTCP13:fallback RTCP6:filled3:ICEe4:SSRCi1197334433e5:statsd7:packetsi0e5:bytesi0e6:errorsi0eeee5:flagsl11:initialized4:send4:recv8:rtcp-mux9:DTLS-SRTP17:DTLS role passive3:ICE11:trickle ICEeeee36:19ac477d-4bab-4246-8023-b99d1eb88c72d3:tag36:19ac477d-4bab-4246-8023-b99d1eb88c727:createdi1594900250e16:in dialogue with10:o9uhn16dj66:mediasld5:indexi1e4:type5:audio8:protocol7:RTP/AVP7:streamsld10:local porti30712e8:endpointd6:family4:IPv47:address11:1.1.1.1:porti19996ee19:advertised endpointd6:family4:IPv47:address11:1.1.1.14:porti19996ee11:last packeti1594901558e5:flagsl3:RTP4:RTCP6:filled9:confirmed10:kernelizede5:statsd7:packetsi261e5:bytesi20880e6:errorsi0eeed10:local porti30713e8:endpointde19:advertised endpointde11:last packeti1594900250e5:flagsl4:RTCP13:fallback RTCP6:fillede4:SSRCi1159134831e5:statsd7:packetsi0e5:bytesi0e6:errorsi0eeee5:flagsl11:initialized4:send4:recv8:rtcp-mux15:ICE controllingeeeee6:totalsd3:RTPd7:packetsi64816e5:bytesi6007097e6:errorsi0ee4:RTCPd7:packetsi0e5:bytesi0e6:errorsi0eee6:result2:oke`

**Comment by rfuchs** [comment]
You shouldn't have to adjust the MTU to accommodate large payloads as packets can be fragmented. If packet fragmentation doesn't work on your system then something is severely broken, and trying to work around it would only mask the underlying problem until you bump into it again elsewhere. So I would strongly suggest to look into why fragmented packets can't be sent.

To answer your question: no there's no option to reduce the payload.

**Comment by lemenkov** [comment]
I believe I was hit by this one. We'll post an update soon (hopefully).

**Comment by rfuchs** [comment]
Cleaning up old tickets
