### ISSUE TITLE
HTTP(Restful API) feature

### ISSUE THREAD

**Issue by pchero** [sipwise/rtpengine#1047]
Hi team,

I have a question regarding RTPEngine.

Is there any plan to adding a feature for HTTP(Restful API)?
If not, will the team minds if someone makes an MR for that?

**Comment by rfuchs** [comment]
Perhaps in the near future as we want to add a Prometheus exporter anyway, and a HTTP API might be one way to do it. But I can't tell you anything concrete yet.

**Comment by pchero** [comment]
Hi rfuchs, Thank you for your answer. That's clear enough. :) I'm closing this ticket.

**Comment by rfuchs** [comment]
HTTP interface is in progress now.

**Comment by rfuchs** [comment]
Now available in master
