### ISSUE TITLE
Stop recording on call A, audio from stream A appears in recording of call B

### ISSUE THREAD

**Issue by drylaarsdam** [sipwise/rtpengine#1048]
Using kamailio + rtpengine for call recording, and noticing that audio from one call is appearing in the audio recording of another call. This appears to be triggered when stop_recording() is used on a call.

General setup: SBC --- kamailio + rtpengine --- IVR

Call media is relayed through the rtpengine using rtpengine_manage() on INVITE/BYE. The IVR application can control call recording using INFO messages. Kamailio issues start_recording() or stop_recording() in response to a header in the INFO. Call recording is started at the beginning of each call, and some applications stop/restart recording during the call to avoid recording personal information.

Example case: In this case, call B is started shortly after Call A, around the time where stop-recording was executed on Call A. The recording for Call B contains speech from Call A.  

Call A: 9677109345 (recording info)
Call-ID: 2304446-3804190516-1072977490@genband1.corp.verascape.com
Sequence: INVITE | start-recording | stop-recording | start-recording | BYE
This call produces two recording files as expected, both OK.
Description of conversation during call:
* IVR prompts caller for dtmf: response 123 (recording is on)
* IVR prompts caller to speak digits: voice response 123 (recording is off)
* IVR prompts caller to speak digits again: voice response 123 (recording is on)

Call B: 3122811527 --> 9677109301 (basic test with long intro prompt)
Call-ID: 2304448-3804190536-250889833@genband1.corp.verascape.com
Sequence: INVITE | start-recording | BYE
This call produces one recording file as expected, but it contains audio from call A. 
Description of conversation during call:
* At start of call, there is a recorded prompt played from IVR regarding account number entry,
  but the audio recording also contains a voice speaking 1-2-3, which is from call A
* Prompt caller for dtmf: response 789
* Prompt caller to speak digits: voice response 789

I'm new to using rtpengine and am looking for any advice on how to understand what is causing this, or if it's possibly related to usage error.

[rec3-kamailio.log](https://github.com/sipwise/rtpengine/files/4948822/rec3-kamailio.log)
[rec3-rtpengine.log](https://github.com/sipwise/rtpengine/files/4948824/rec3-rtpengine.log)

[audio.zip](https://github.com/sipwise/rtpengine/files/4948828/audio.zip)

**Comment by drylaarsdam** [comment]
Another perspective on the same observation. Ran the same test again, this time with rtpengine-recording.conf configured with output-single true. 

Eight recordings are produced by the test. 

Two files for each part of call A (stream from caller, stream from IVR):
* A1 recording on
* A2 recording off
* A3 recording on

And  two files are from call B (recording on for the entire call). 

It would seem that recordings for A2 should not be produced at all, since recording was switched off. In addition, they are named with the call-id for call B. This seems consistent with the behavior from the first test, where the A2 recordings appeared to be mixed into the B recordings. Based on the audio contents of the files, they are labeled for the associated call part.

Recordings named with call-id for call A:
2329516-3804373271-1532581780%40genband1.corp.verascape.com-408b89fcc2ab0d8e-0000001b.wav -- A3-IVR
2329516-3804373271-1532581780%40genband1.corp.verascape.com-408b89fcc2ab0d8e-d0f1939c.wav -- A3-Phone
2329516-3804373271-1532581780%40genband1.corp.verascape.com-8b3e757da8c9234b-0000001b.wav -- A1-IVR
2329516-3804373271-1532581780%40genband1.corp.verascape.com-8b3e757da8c9234b-d0f1939c.wav -- A1-Phone

Recordings named with call-id for call B:
2329517-3804373290-520224742%40genband1.corp.verascape.com-c53bdc554f7d8192-0000001b.wav -- A2-IVR
2329517-3804373290-520224742%40genband1.corp.verascape.com-c53bdc554f7d8192-0000001f.wav -- B-IVR
2329517-3804373290-520224742%40genband1.corp.verascape.com-c53bdc554f7d8192-a599b0d4.wav -- B-Phone
2329517-3804373290-520224742%40genband1.corp.verascape.com-c53bdc554f7d8192-d0f1939c.wav -- A2-Phone

**Comment by rfuchs** [comment]
Ah it's getting the stream indexes mixed up... Will fix.

**Comment by rfuchs** [comment]
I don't have an easy way to try to reproduce this, but can you try with the commit 2bba15d applied?

**Comment by drylaarsdam** [comment]
Thank you. Yes, I will test with this.

**Comment by drylaarsdam** [comment]
I'm unable to reproduce after applying this change. It will be a bit before I can introduce this to more realistic call traffic where it was initially discovered. But there have been no more cases in the test environment (either output-mixed, or output-single) where it was previously reliably reproduced. Thanks!

**Comment by drylaarsdam** [comment]
Following up on testing, also getting good results (no mixed streams) using this code change in my expanded test environment.
