### ISSUE TITLE
unable to start rtpengine daemon on debian 10. 

### ISSUE THREAD

**Issue by johandeclercqdemocon** [sipwise/rtpengine#1050]
I am unable to start rtpengine on debian 10

● ngcp-rtpengine-daemon.service - NGCP RTP/media Proxy Daemon
   Loaded: loaded (/lib/systemd/system/ngcp-rtpengine-daemon.service; enabled; vendor preset: enabl
   Active: failed (Result: exit-code) since Fri 2020-07-24 09:41:24 UTC; 15s ago
 Main PID: 5206 (code=exited, status=255/EXCEPTION)

Jul 24 09:41:23 ns365555 ngcp-rtpengine-iptables-setup[5191]: modprobe: FATAL: Module xt_RTPENGINE 
Jul 24 09:41:23 ns365555 ngcp-rtpengine-iptables-setup[5191]: iptables v1.8.2 (nf_tables): unknown 
Jul 24 09:41:23 ns365555 ngcp-rtpengine-iptables-setup[5191]: Try `iptables -h' or 'iptables --help
Jul 24 09:41:23 ns365555 ngcp-rtpengine-iptables-setup[5191]: ip6tables v1.8.2 (nf_tables): unknown
Jul 24 09:41:23 ns365555 ngcp-rtpengine-iptables-setup[5191]: Try `ip6tables -h' or 'ip6tables --he
Jul 24 09:41:23 ns365555 rtpengine[5206]: CRIT: Fatal error: Bad command line: No such file or dire
Jul 24 09:41:23 ns365555 rtpengine[5206]: CRIT: Fatal error: Bad command line: No such file or dire
Jul 24 09:41:23 ns365555 systemd[1]: ngcp-rtpengine-daemon.service: Main process exited, code=exite
Jul 24 09:41:24 ns365555 systemd[1]: ngcp-rtpengine-daemon.service: Failed with result 'exit-code'.
Jul 24 09:41:24 ns365555 systemd[1]: Failed to start NGCP RTP/media Proxy Daemon.

In an older, I found this : pkg-config xtables --variable=xtlibdir     

I uninstalled the package, applied the above line and then reinstalled but upto no result. 

Please let me know what info is missing for a fix.

**Comment by johandeclercqdemocon** [comment]
I fixed this by installing all packets and adding [rtpengine] in the config file.

**Comment by johandeclercqdemocon** [comment]
I was not aware that you need to install all packages.  Can you please confirm that this is correct or am I overlooking something ?

**Comment by rfuchs** [comment]
Which packages in particular did you not have installed?

**Comment by johandeclercqdemocon** [comment]
I installed ONLY the daemon.

**Comment by rfuchs** [comment]
Ok, the included systemd/init script is supposed to work with the `ngcp-rtpengine` metapackage, which includes the kernel module (the dkms package)

**Comment by SachithKasthuriarachchi** [comment]
I also get the same error. 

```
Job for ngcp-rtpengine-daemon.service failed because the control process exited with error code.
See "systemctl status ngcp-rtpengine-daemon.service" and "journalctl -xe" for details.
invoke-rc.d: initscript ngcp-rtpengine-daemon, action "restart" failed.
● ngcp-rtpengine-daemon.service - NGCP RTP/media Proxy Daemon
   Loaded: loaded (/lib/systemd/system/ngcp-rtpengine-daemon.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-08-02 15:06:31 +0530; 10ms ago
  Process: 12011 ExecStartPre=/usr/sbin/ngcp-rtpengine-iptables-setup start (code=exited, status=0/SUCCESS)
  Process: 12026 ExecStart=/usr/sbin/rtpengine -f -E --no-log-timestamps --pidfile /run/ngcp-rtpengine-daemon.pid --config-file /etc/rtpengine/rtpengine.conf --table $TABLE (code=exited, status=255/EXCEPTION)
  Process: 12027 ExecStopPost=/usr/sbin/ngcp-rtpengine-iptables-setup stop (code=exited, status=0/SUCCESS)
 Main PID: 12026 (code=exited, status=255/EXCEPTION)

Aug 02 15:06:30 debian systemd[1]: Starting NGCP RTP/media Proxy Daemon...
Aug 02 15:06:30 debian rtpengine[12026]: CRIT: Fatal error: Invalid interface specification: '08:00:27:d5:ad:f4'
Aug 02 15:06:30 debian systemd[1]: ngcp-rtpengine-daemon.service: Main process exited, code=exited, status=255/EXCEPTION
Aug 02 15:06:31 debian systemd[1]: ngcp-rtpengine-daemon.service: Failed with result 'exit-code'.
Aug 02 15:06:31 debian systemd[1]: Failed to start NGCP RTP/media Proxy Daemon.
```

**Comment by rfuchs** [comment]
Not the same error. You've put a MAC address in the interface config. That's not supported.

**Comment by SachithKasthuriarachchi** [comment]
Thank you @rfuchs now the rtpengine works fine but, the kamailio starting fails. The log is as follows,
```
● kamailio.service - Kamailio (OpenSER) - the Open Source SIP Server
   Loaded: loaded (/lib/systemd/system/kamailio.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-08-02 22:46:54 +0530; 10s ago
  Process: 3108 ExecStart=/usr/sbin/kamailio -P /var/run/kamailio/kamailio.pid -f $CFGFILE -m $SHM_MEMORY -M $PKG_MEMORY -u $USER -g $GROUP (code=exited, status=255/EXCEPTION)

Aug 02 22:46:54 debian systemd[1]: kamailio.service: Control process exited, code=exited, status=255/EXCEPTION
Aug 02 22:46:54 debian systemd[1]: kamailio.service: Failed with result 'exit-code'.
Aug 02 22:46:54 debian systemd[1]: Failed to start Kamailio (OpenSER) - the Open Source SIP Server.
Aug 02 22:46:54 debian systemd[1]: kamailio.service: Service RestartSec=100ms expired, scheduling restart.
Aug 02 22:46:54 debian systemd[1]: kamailio.service: Scheduled restart job, restart counter is at 5.
Aug 02 22:46:54 debian systemd[1]: Stopped Kamailio (OpenSER) - the Open Source SIP Server.
Aug 02 22:46:54 debian systemd[1]: kamailio.service: Start request repeated too quickly.
Aug 02 22:46:54 debian systemd[1]: kamailio.service: Failed with result 'exit-code'.
Aug 02 22:46:54 debian systemd[1]: Failed to start Kamailio (OpenSER) - the Open Source SIP Server.
```

**Comment by rfuchs** [comment]
Cleaning up old tickets

**Comment by boukar10** [comment]
Hello, I'm using Ubuntu 18.04 and I'm getting the following error while installing Kamailio. Please can you help?

journalctl -xe
 systemd[1]: Reloading.
 systemd[1]: Reloading.
 kernel: usb 2-2: USB disconnect, device number 35
 systemd[1]: Reloading.
 kernel: usb 2-2: new low-speed USB device number 36 using ohci-pci
 kernel: usb 2-2: New USB device found, idVendor=04ca, idProduct=008a
 kernel: usb 2-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
 kernel: usb 2-2: Product: USB Optical Mouse
 kernel: usb 2-2: Manufacturer: PixArt
 kernel: input: PixArt USB Optical Mouse as /devices/pci0000:00/0000:00:02.0/usb2/2-2/2-2:1.0/0003:04CA:008A
 kernel: hid-generic 0003:04CA:008A.011E: input,hidraw2: USB HID v1.11 Mouse [PixArt USB Optical Mouse] on u
 systemd[1]: Reloading.
 systemd[1]: Starting NGCP RTP/media Proxy Daemon...
-- Subject: Unit ngcp-rtpengine-daemon.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit ngcp-rtpengine-daemon.service has begun starting up.
 kernel: Registering xt_RTPENGINE module - version 7.4.1.7+0~mr7.4.1.7
 rtpengine[5595]: CRIT: Fatal error: Bad command line: No such file or directory
 rtpengine[5595]: CRIT: Fatal error: Bad command line: No such file or directory
 systemd[1]: ngcp-rtpengine-daemon.service: Main process exited, code=exited, status=255/n/a
 systemd[1]: ngcp-rtpengine-daemon.service: Failed with result 'exit-code'.
 systemd[1]: Failed to start NGCP RTP/media Proxy Daemon.
-- Subject: Unit ngcp-rtpengine-daemon.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit ngcp-rtpengine-daemon.service has failed.
--
-- The result is RESULT.
systemd[1]: Reloading.
systemd[1]: Reloading.
systemd[1]: Reloading.
systemd[1]: Reloading.
kernel: usb 2-2: USB disconnect, device number 36

**Comment by shekhshadul** [comment]
> 

can you explain in detail sir

**Comment by Jsilvaaaa** [comment]
I have this error:
rtpengine.service - LSB: RTP engine
   Loaded: loaded (/etc/init.d/rtpengine; generated; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2023-06-04 17:28:35 -05; 6s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 3797 ExecStart=/etc/init.d/rtpengine start (code=exited, status=1/FAILURE)
    Tasks: 16 (limit: 4915)
   Memory: 18.3M
      CPU: 47ms
   CGroup: /system.slice/rtpengine.service
  
Jun 04 17:28:35 prosipmokco systemd[1]: Starting LSB: RTP engine...
Jun 04 17:28:35 prosipmokco rtpengine[3797]: Starting RTP engine(rtpengine): /usr/sbin/rtpengine already running.
Jun 04 17:28:35 prosipmokco rtpengine[3797]: failure
Jun 04 17:28:35 prosipmokco systemd[1]: rtpengine.service: Control process exited, code=exited status=1
Jun 04 17:28:35 prosipmokco systemd[1]: Failed to start LSB: RTP engine.
Jun 04 17:28:35 prosipmokco systemd[1]: rtpengine.service: Unit entered failed state.
Jun 04 17:28:35 prosipmokco systemd[1]: rtpengine.service: Failed with result 'exit-code'.
