### ISSUE TITLE
"SRTP output wanted, but no crypto suite was negotiated" on "wrong" side

### ISSUE THREAD

**Issue by gecame** [sipwise/rtpengine#1051]
Dear All,

I am facing a strange issue with rtpengine (via Kamailio) when proxying between a DTLS enabled client (UDP/TLS/RTP/SAVPF) on one hand, and an Asterisk server (no encryption, RTP/AVP) on the other. When setting up the connection, I get the following error from rtpengine:

"SRTP output wanted, but no crypto suite was negotiated" - but this is on the side talking to Asterisk, where there is no encryption configured.

Any hints of what that could be? rtpengine + Kamailio logs as well as rtpengine (level7) logs for one call are attached and a pcap can be provided as well.

many thanks in advance for any hint!
cheers, gecame

[rtpengine-log7-report.log](https://github.com/sipwise/rtpengine/files/4981064/rtpengine-log7-report.log)
[kamailio-rtpengine-report.log](https://github.com/sipwise/rtpengine/files/4981065/kamailio-rtpengine-report.log)

**Comment by rfuchs** [comment]
You're seeing this because there's incoming RTP before SRTP-DTLS was completed and SRTP keys could be exchanged. This is not unusual and media should start flowing normally after SRTP-DTLS was completed.

**Comment by gecame** [comment]
Thanks Richard! But just to double check - is it normal that we see this error on the rtpengine side that is talking to Asterisk? The port number in the log entry preceding the ERR message should never be talking SRTP as it's on the side between Kamailio and Asterisk - where there is no SRTP traffic.

**Comment by gecame** [comment]
Ah, I guess I understand. This is following on RTP early media reception coming in from Asterisk, that rtpengine passes on to the UA - and thus the warning that SRTP key exchange hasn't completed yet on the other side!

**Comment by rfuchs** [comment]
It's logged within the context of the port that received the RTP packet.

**Comment by gecame** [comment]
many thanks! Closing the issue then.
- thanks, Gecame
