### ISSUE TITLE
Comfort noise support

### ISSUE THREAD

**Issue by ahmedfayoub** [sipwise/rtpengine#1053]
Hi,

I'm wondering how can I offer comfort noise with rtpengine , I'd like to offer one of these

a=rtpmap:13 CN/8000
a=rtpmap:118 CN/16000
a=rtpmap:119 CN/24000

I enabled debugging and I see it's just passing through

DEBUG: [f65a08ae71d2559991439a1ee9d25f09]: Creating codec handler for CN/8000
DEBUG: [f65a08ae71d2559991439a1ee9d25f09]: Using passthrough handler for CN/8000
DEBUG: [f65a08ae71d2559991439a1ee9d25f09]: Creating codec handler for CN/16000
DEBUG: [f65a08ae71d2559991439a1ee9d25f09]: Using passthrough handler for CN/16000
DEBUG: [f65a08ae71d2559991439a1ee9d25f09]: Creating codec handler for CN/24000
DEBUG: [f65a08ae71d2559991439a1ee9d25f09]: Using passthrough handler for CN/24000

Thanks in advance,

**Comment by rfuchs** [comment]
Comfort noise is not currently supported.

**Comment by ahmedfayoub** [comment]
Thanks @rfuchs for the prompt reply.
any plans for supporting it ?

**Comment by rfuchs** [comment]
No concrete plans for it as of right now, so all I can offer is a definitive "maybe"

**Comment by rfuchs** [comment]
Support for CN is now present in current master
