### ISSUE TITLE
Codec order not preserved when using strip all and offer list

### ISSUE THREAD

**Issue by danieludy** [sipwise/rtpengine#1054]
For an offer request that uses "codec": { "offer": [ "telephone-event/8000", "PCMU/8000" ], "strip": [ "all" ] } the m line in the SDP returned uses the order from the codec offer list and not the order from the invite request... Basically it is treating the codec-offer list as a prioritized whitelist instead of just a whitelist of acceptable codecs.

For example, using the above codec settings:
Inbound request has: m=audio 19168 RTP/AVP 0 101 13
Response from RTP Engine: m=audio 5176 RTP/AVP 101 0

It correctly strips the 13 codec, but it reorders the 101 and 0 codecs. I know for the telephone-event it really doesn't change functionality, but the same happens for all codecs. The order of acceptable codecs should be preserved from the initial invite request.

**Comment by rfuchs** [comment]
That's actually by design in order to allow changing the codec priority.

**Comment by danieludy** [comment]
So then is there no way to not override the codec priority other than scanning and ordering the allowed codec list prior to sending to RTPEngine?

**Comment by rfuchs** [comment]
Not currently no, but we may add that in the future
