### ISSUE TITLE
[ZRTP] MOS statistics clarification

### ISSUE THREAD

**Issue by denyspozniak** [sipwise/rtpengine#1055]
Hello!
What MOS statistics will be relevant if the ZRTP protocol is used?
I am expecting that packetloss, jitter, roundtrip are real, but mos is not.

**Comment by rfuchs** [comment]
None of them probably, assuming that the RTCP packets are encrypted. The statistics are taken from the RTCP packets sent by the endpoints, not calculated by rtpengine.
