### ISSUE TITLE
Call from firefox-79 to sip-backend, return "Bad Media Description"

### ISSUE THREAD

**Issue by xmglin** [sipwise/rtpengine#1056]
latest firefox: 79.0    (vs. chrome 84.0.4147.105)
latest kamailio: 5.3.5
rtpengine: 8.2.1.2
latest jssip: 3.5.3

Call from browser to sip-backend via kamailio/rtpengine.
SIP-backend answers the call and returns 200 OK to browser.

Firefox-79 sent BYE immediately with SIP header  Reason: SIP ;cause=488; text="Not Acceptable Here".
and returned "Bad Media Description" in console.

But Chrome-84 setuped the call successfully, and worked as expected.

Anybody knows how to configure kamailio configuration to solve this Firefox compatibility?
Thanks.

##################
kamailiio log (grep rtpengine_manage):
method:INVITE, request     rtpengine_manage: replace-origin replace-session-connection trust-address via-branch=extra external internal rtcp-mux-demux DTLS=off SDES-off ICE=remove RTP/AVP
method:INVITE, reply:100   rtpengine_manage: replace-origin replace-session-connection trust-address via-branch=extra internal external rtcp-mux-offer generate-mid DTLS=passive SDES-off ICE=force UDP/TLS/RTP/SAVPF
method:INVITE, reply:200   rtpengine_manage: replace-origin replace-session-connection               via-branch=extra internal external rtcp-mux-offer generate-mid DTLS=passive SDES-off ICE=force UDP/TLS/RTP/SAVPF
method:ACK,                rtpengine_manage: replace-origin replace-session-connection trust-address external internal rtcp-mux-demux DTLS=off SDES-off ICE=remove RTP/AVP
method:BYE,                rtpengine_manage: replace-origin replace-session-connection trust-address external internal rtcp-mux-demux DTLS=off SDES-off ICE=remove RTP/AVP

**Comment by xmglin** [comment]
SDP in SIP 200 OK:

v=0
o=Hibot 1596744928 1596744929 IN IP4 11.22.33.44
s=Hibot
c=IN IP4 11.22.33.44
t=0 0
m=audio 27464 UDP/TLS/RTP/SAVPF 109 101
a=mid:0
a=rtpmap:109 opus/48000/2
a=rtpmap:101 telephone-event/8000
a=fmtp:109 useinbandfec=1; maxplaybackrate=48000; stereo=1
a=fmtp:101 0-16
a=sendrecv
a=rtcp:27464
a=rtcp-mux
a=setup:passive
a=fingerprint:sha-1 C1:B3:52:47:54:FC:2B:37:83:42:5A:91:76:44:54:2B:2F:04:EE:B1
a=ptime:20
a=ice-ufrag:nkCrwT3O
a=ice-pwd:5PIXtHVhXIXNiXYsSkU4UhZJga
a=candidate:bYkpkcTAqd5H3X6o 1 UDP 2130706431 11.22.33.44 27464 typ host

**Comment by rfuchs** [comment]
You'd have to look in Firefox' debugging to see why it rejects the SDP. From a quick glance it looks fine.

**Comment by rfuchs** [comment]
Cleaning up old tickets
