### ISSUE TITLE
Interacting with rtpengine when processing a reinvite coming from callee side

### ISSUE THREAD

**Issue by elbow** [sipwise/rtpengine#1059]
Hi Richard,

Is there a better place to ask for help?

My reinvite handling with rtpengine still doesn't seem to be right.

I have a situation where a call is setup from BOB to ALICE - Bob is talking G722 and ALICE Opus and rtpengine is transcoding.

On the original invite I send Bob's SDP as OFFER to rtpengine and Alice's as ANSWER.  All good.

ALICE then does a reinvite.  So against the direction of the original call.  So what now?

Currently I am calling rtpengine with OFFER in relation to Alice's reinvite.  I use the same callid as the original call, and with the from-tag of the original call, so rtpengine knows its the same connection), and with the sdp from Alice's reinvite.  The rest of the opts are the same as I used originally for the Alice->Bob direction, ie the opts I passed originally with ANSWER which are setup to force the transcode from Opus.

Then when I get the OK back from Bob for the reinvite I call ANSWER, with Bob's SDP and the same opts as I used originally for the Bob->Alice direction ie the opts I passed originally with OFFER, which are setup to force the transcode TO Opus.

The result is very funky.  The SDP that rtpengine makes for both directions seems fine and in my opinion the call should continue with codecs and transcoding as before.

But what actually happens is that rtpengine starts passing through Alice's OPUS as-is (even though Bob never said he could do Opus).  Bob isn't expecting that codec and throws the packets away and audio is lost.

Have I got this wrong? - it certainly seems I have something backwards still.  Do I actually need to deal with Alice's reinvite by calling "ANSWER" for her re-Invite and then "OFFER" for Bob's OK - IE for this process answer will be called first and offer second?

Or can you spot my misunderstanding?

Thanks,
Steve

**Comment by rfuchs** [comment]
In the reverse re-invite, do you have the from-tag and to-tag swapped?

**Comment by elbow** [comment]
In the original setup I pass in the OFFER:
```
call-id: "2eed6c7e220c5fb41a67533f73a67089@XXX.YYY.250.130:5060"
from-tag: "as50e15454"
```

and in the ANSWER:
```
call-id: "2eed6c7e220c5fb41a67533f73a67089@197.155.250.130:5060"
from-tag: "as50e15454"
to-tag: "5i4rocvmsr"
```

When processing the reinvite in the reverse direction, in the OFFER, which is the SDP from the reinvite from the callee:
```
call-id: "2eed6c7e220c5fb41a67533f73a67089@197.155.250.130:5060"
from-tag: "5i4rocvmsr"
to-tag: "as50e15454"
```

and when processing the OK to the reinvite:
```
call-id: "2eed6c7e220c5fb41a67533f73a67089@197.155.250.130:5060
from-tag: "5i4rocvmsr"
to-tag: "as50e15454"
```

So yes - the tags are the other way around from the original call.

Is that good or bad?

And thanks for the super-fast reply.  You are a machine!

**Comment by rfuchs** [comment]
That's what it should be, yes. Post a full debug log then.

**Comment by elbow** [comment]
It's version 8.6.0.0+0~mr8.6.0.0 git-master-de37041

Attached- its big because of the debug level.

Call started 17:08:08.

Reinvite at 10:08:38 and then again at 17:08:47

[reinvite.log](https://github.com/sipwise/rtpengine/files/5064567/reinvite.log)

Thanks.

**Comment by rfuchs** [comment]
This seems to be incorrect behaviour on Bob's side.

In the re-invite, Alice offers a whole list of codecs, most of which are masked or stripped, and so finally only G722, PCMA, PCMU are offered to Bob.

So Bob should list only a subset of these in his answer. Instead, Bob answers with a longer list of codecs, most of which were never offered to him, including Opus. So now rtpengine thinks both Alice and Bob speak Opus, therefore passthrough.

I can add extra code to rtpengine to detect and ignore these extra codecs, but this is what's happening here.

**Comment by rfuchs** [comment]
I should probably be a bit more specific: it's not actually against the RFC to list codecs in the answer that weren't offered. But it's unusual. And so Bob does say he can receive Opus, and therefore to avoid transcoding, Opus from Alice is passed through.

**Comment by elbow** [comment]
Hi,

I didn't notice that - it is surprising since Bob's original invite had only G722, ALAW and ULAW.

But why did rtpengine consider the Opus in the answer sdp as an option when in the answer options it was included in the "strip" array?

Here's all the SDPs:

```
From Alice in reinvite:

v=0
o=- 2652698026405860635 3 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS tTFC4SbniCuGPTqPzJ6TfQB365EFZ2KgqwEo
a=group:BUNDLE 0
m=audio 33497 UDP/TLS/RTP/SAVPF 101 96 103 104 9 0 8 106 105 13 110 112 113
c=IN IP4 aaa.bbb.ccc.156
a=rtpmap:101 telephone-event/8000
a=rtpmap:96 opus/48000/2
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=fmtp:96 minptime=10;useinbandfec=1
a=rtcp:9 IN IP4 0.0.0.0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=setup:actpass
a=mid:0
a=msid:tTFC4SbniCuGPTqPzJ6TfQB365EFZ2KgqwEo 566e9f1f-425d-42d7-914a-c7b7bf9a603f
a=sendonly
a=ice-ufrag:x/N6
a=ice-pwd:mheDjhfBgOn3pT59Fxn3jzUT
a=fingerprint:sha-256 96:63:52:5A:48:00:44:03:62:51:59:57:17:54:95:93:CF:12:B6:2D:47:85:37:4D:C7:28:C5:42:E7:40:6D:56
a=candidate:631409734 1 udp 2122260224 169.254.207.164 49434 typ host generation 0 network-id 2
a=candidate:2365191058 1 udp 2122194688 10.64.16.132 52609 typ host generation 0 network-id 1 network-cost 10
a=candidate:4039013047 1 udp 41820159 aaa.bbb.ccc.156 33497 typ relay raddr 10.64.16.132 rport 52609 generation 0 network-id 1 network-cost 10
a=candidate:3191705159 1 udp 25042687 aaa.bbb.ccc.156 39321 typ relay raddr 10.64.16.132 rport 65030 generation 0 network-id 1 network-cost 10
a=ice-options:trickle
a=ssrc:3788258917 cname:zHdknDp6b4hK/9Il
a=ssrc:3788258917 msid:tTFC4SbniCuGPTqPzJ6TfQB365EFZ2KgqwEo 566e9f1f-425d-42d7-914a-c7b7bf9a603f
a=ssrc:3788258917 mslabel:tTFC4SbniCuGPTqPzJ6TfQB365EFZ2KgqwEo
a=ssrc:3788258917 label:566e9f1f-425d-42d7-914a-c7b7bf9a603f
a=rtcp-mux

*** so 96 is offered and mapped to Opus ***

To Bob - re-invite passed on:

v=0
o=- 2652698026405860635 3 IN IP4 aaa.bbb.ccc.154
s=-
t=0 0
a=msid-semantic: WMS tTFC4SbniCuGPTqPzJ6TfQB365EFZ2KgqwEo
m=audio 16580 RTP/AVP 101 9 8 0
c=IN IP4 aaa.bbb.ccc.154
a=msid:tTFC4SbniCuGPTqPzJ6TfQB365EFZ2KgqwEo 566e9f1f-425d-42d7-914a-c7b7bf9a603f
a=ssrc:3788258917 cname:zHdknDp6b4hK/9Il
a=ssrc:3788258917 msid:tTFC4SbniCuGPTqPzJ6TfQB365EFZ2KgqwEo 566e9f1f-425d-42d7-914a-c7b7bf9a603f
a=ssrc:3788258917 mslabel:tTFC4SbniCuGPTqPzJ6TfQB365EFZ2KgqwEo
a=ssrc:3788258917 label:566e9f1f-425d-42d7-914a-c7b7bf9a603f
a=mid:0
a=rtpmap:101 telephone-event/8000
a=rtpmap:9 G722/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=sendonly
a=rtcp:16581
a=ptime:20

*** Opus codec and others are stripped, only G722, A and ULAW offered to Bob ***


From Bob - the OK:

v=0
o=root 1396081772 1396081773 IN IP4 aaa.bbb.ccc.130
s=Telviva
c=IN IP4 aaa.bbb.ccc.130
t=0 0
m=audio 18356 RTP/AVP 9 8 0 18 110 97 3 4 107 101
a=rtpmap:9 G722/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:110 speex/8000
a=rtpmap:97 iLBC/8000
a=rtpmap:3 GSM/8000
a=rtpmap:4 G723/8000
a=fmtp:4 annexa=no
a=rtpmap:107 opus/48000/2
a=fmtp:107 useinbandfec=1
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=maxptime:60
a=recvonly

*** Bob offers all those codecs.  It can do them all.  G722 first since that is what is currently in use ***

(As an aside - we are trying to keep the Opus transcodes in rtpengine to manage CPU load on our "Bob"s).

To Alice - the OK passed on:

v=0
o=root 1396081772 1396081773 IN IP4 aaa.bbb.ccc.130
s=Telviva
c=IN IP4 aaa.bbb.ccc.154
t=0 0
m=audio 16570 UDP/TLS/RTP/SAVPF 96 101 110 112 113
a=maxptime:60
a=mid:0
a=rtpmap:96 opus/48000/2
a=rtpmap:101 telephone-event/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=fmtp:96 minptime=10;useinbandfec=1
a=fmtp:101 0-16
a=recvonly
a=rtcp:16570
a=rtcp-mux
a=setup:passive
a=fingerprint:sha-1 B9:5F:E2:9C:09:10:DF:C0:15:9B:29:F1:56:8C:49:73:71:DD:3D:1F
a=ptime:20
a=ice-ufrag:jt1bODYt
a=ice-pwd:N9KRRmr8Wxhh3yW0EzTbBHiPuj
a=ice-options:trickle
a=candidate:pUuZBkCj41V48P57 1 UDP 2130706431 aaa.bbb.ccc.154 16570 typ host
a=end-of-candidates

*** So rtpengine picked up that Bob can do Opus, failing to notice it listed in the strip array, and propagated only that.  Since Opus had actually been removed from the offer actually propagated from Alice to Bob, Bob did not have the rtpmap assignment (there is no fixed assignment for Opus), so when it received RTP with payload 96 it didn't know what to do with it ***

```

If rtpengine had looked at the answer SDP from Bob in the light of the offer that had been send to Bob (by rtpengine), or with reference to the strip array, then it would have selected G722 the first codec in common and all would have been well.

From this I think I have a misunderstanding of some sort about the "codec" attributes and how they are used (or not used) in answer?

We have a great deal of general SIP usage on our Bob boxes.  So I'm scared of a regression on that side if I too casually change the config.  Is there anything I can do to my rtpengine calls to get this to work better?

```
Here's what I do for sdp that originated from Alice:
{
  'transport protocol': 'RTP/AVP',
  'DTLS': 'off',
  'SDES': 'off',
  'ICE': 'remove',
  'flags': ['port-latching'],
  'rtcp-mux': ['demux'],
'codec': {
    'strip': ['telephone-event', 'G722', 'PCMA', 'PCMU'],
    'mask': ['opus'],
    'set': ['opus/48000/2/32000//maxplaybackrate=16000;sprop-maxcapturerate=16000;useinbandfec=1;maxaveragebitrate=32000'],
    'transcode': ['G722', 'PCMA', 'PCMU'],
    'offer': ['telephone-event']
  }}

And here's the options I use with SDP that originated on Bob:

{ 'ICE': 'force',
  'SDES': 'off',
  'DTLS': 'passive',
  'flags': ['SDES-no', 'port-latching'],
  'rtcp-mux': ['require'],
  'codec': {
    // about stripping opus: may seem weird to remove it and then transcode it.
    // but Bob offers opus and if we pass it through then Bob likely ends up transcoding it, which we want to avoid
    // this may change if I can figure out how to get Bob to offer opus only if it can do it without transcoding.
    'strip': ['telephone-event', 'opus', 'G729', 'G729a', 'speex', 'G723', 'GSM', 'iLBC'],
    'mask': ['G722', 'PCMA', 'PCMU'],
    'transcode': ['opus/48000/2/32000//maxplaybackrate=16000;sprop-maxcapturerate=16000;useinbandfec=1;maxaveragebitrate=32000'],
    'offer': ['telephone-event']
  }}

```

I double checked and these were correctly passed to rtpengine.

Why did rtpengine consider Opus an option when in the answer options it was included in the "strip" array?

Thanks!

**Comment by elbow** [comment]
Hmmm - my bad, reading the docs again:

> These options are only processed in offer messages and ignored otherwise.

Does this mean that there is no way to do what I need?  That is to have some of the codecs in the answer SDP ignored?

I suppose I could tinker with the SDP m= line before passing it to rtpengine.

**Comment by elbow** [comment]
Ah, found this in an email you wrote elsewhere:

> At least in newer versions - older versions did accept them in an `answer`, but they didn't do what was expected, which is why they were removed in later versions

So this is probably a regression when I updated from version 7 to the master code - which was to fix an earlier issue.

**Comment by rfuchs** [comment]
I suppose the `strip` option could still be considered in answers. I'll have to think about that.

**Comment by elbow** [comment]
In the offer we don't "strip" Opus since we want to transcode it.
So it would have to be taken from the answer or maybe a "answer-strip" array in the offer?

Reading all the docs on mask=, strip=, transcode= I can see why we set things up as we did.  But I think I'm in a corner at this point.

**Comment by elbow** [comment]
Hi @rfuchs,

I modified my code so that the opus codec is removed from the sdp coming from "Bob" before it is passed to rtpengine "answer".

This sorts out the behaviour - codec on the "Alice" side stays Opus, codec on the "Bob" side stays G722.

From my side this is a servicable fix.

Thanks so much for the help.

**Comment by rfuchs** [comment]
See commit above c001890 which adds back support for codec-strip and codec-offer in answer messages. I think it makes sense to keep them supported there.

**Comment by elbow** [comment]
Thanks, you are amazing.

My change in my app to remove Opus is working, but I'll update to the latest and test that too.

**Comment by elbow** [comment]
Thanks - all working now.
