### ISSUE TITLE
No media when bridging web-->sip and sip-->web

### ISSUE THREAD

**Issue by joeygo** [sipwise/rtpengine#1066]
Hello,
I'm trying to bridge a call between WebRTC client (DTLS-SRTP) and SIP client (TLS SRTP) using Kamailio and RTPEngine.
Calls between 2 WebRTC clients works fine.
Calls between 2 SIP clients works fine.
Calls between WebRTC client and SIP client established successfully but no media can be heard.
Attached log with debug level 7.
Any help would be much appreciated.

Thanks

[syslog.log](https://github.com/sipwise/rtpengine/files/5121493/syslog.log)

**Comment by rfuchs** [comment]
This is probably why:
```
Aug 25 05:22:09 kamailio11 rtpengine[8358]: ERR: [c1236542-b8eb-41d1-a948-17b8b81a6bbc]: Failed to init DTLS connection: srtp unknown protection profile
Aug 25 05:22:09 kamailio11 rtpengine[8358]: ERR: [c1236542-b8eb-41d1-a948-17b8b81a6bbc]: Failed to init DTLS connection: srtp unknown protection profile
```
Try updating your OpenSSL library (and then rebuild against it).

**Comment by joeygo** [comment]
Thanks
