### ISSUE TITLE
T.38 and SRTP

### ISSUE THREAD

**Issue by nikbyte** [sipwise/rtpengine#1067]
Hello Richard.

I'm trying to understand why for audio SDP when I use "transport-protocol": "RTP/SAVP" rtpengine produces SDP with a=crypto, however when I receive t.38 SDP in reINVITE and call offer with "transport-protocol": "RTP/SAVP", I don't have a=crypto there. Is this correct behaviour of rtpengine?

**Comment by rfuchs** [comment]
No that doesn't sound right, unless there's something else going on. Do you have a full debug log?
