### ISSUE TITLE
RTPengine suddenly takes up all memory after enabling DTMF transcoding

### ISSUE THREAD

**Issue by SipSeb** [sipwise/rtpengine#1068]
We enabled DTMF transcoding today on a setup with five rtpengines. We call rtpenginge_manage() with these parameters:

```rtpengine_manage("trust-address ICE=remove direction=default direction=default replace-origin replace-session-connection codec-transcode-telephone-event");```

After enabling it, it ran for about ten minutes without problems, and then, all of a sudden, within 30 seconds, it had taken all available memory on the system, so the OOM killer came around and killed the process. Please see the attached screenshot from Grafana. This happened on two machines. Unfortunately, there is nothing in the log file, and as those machines run more than a thousand concurrent sessions, we are unable to enable debug logging. 

We have disabled transcoding again, but could of course enable it again if you need some more output or details we can collect.

Our version is 8.5.1.0 on Debian Buster from your Debian repository.

Do you have any idea why this could happen? When it started, there was a new call which needed transcoding being processed. I can see that the INVITE is correctly processed, the 200 OK however got stuck in Kamailio because of the unresponsive rtpengine.

<img width="1582" alt="Bildschirmfoto 2020-08-27 um 11 37 49" src="https://user-images.githubusercontent.com/9820790/91424736-7c664800-e85a-11ea-9405-06e8eed241fd.png">

**Comment by rfuchs** [comment]
Wow, ok. I assume it didn't leave a core dump after being killed?

It probably got stuck in a loop somewhere, so the best way to debug this would be to try to catch it in the act. Either kill it quicky with ABRT when it starts acting up, or quickly attach gdb and pull a full backtrace.

**Comment by SipSeb** [comment]
No, of course it didn't. We don't really know if we are keen on breaking telephony for our customers again. (We actually wouldn't need this feature if it wasn't for this bug: https://issues.asterisk.org/jira/browse/ASTERISK-29051)

We will discuss after the weekend, how we should proceed with this.

**Comment by rfuchs** [comment]
Another option is to set a memory usage resource limit for the daemon. That should make it fail and dump a core before it comes to OOM. But you'd still have an outage if this isn't reproducible in the lab.

**Comment by rfuchs** [comment]
Cleaning up old tickets
