### ISSUE TITLE
rtpengine with Homer enabled is not producing RTP records to the Heplify-Server

### ISSUE THREAD

**Issue by githubsw** [sipwise/rtpengine#1070]
Hello,

I have enabled Homer in rtpengine.  I have set --homer=Heplify-Server-IP:Port --homer-id=999 --homer-protocol=udp, but I am not seeing any RTP packets in Homer.  Note that I am also running Heplify and I am seeing SIP packets in Homer.  Shouldn't rtpengine be sending RTP records to the Heplify-Server for showing up in the Homer pcaps?

Thank you,

**Comment by rfuchs** [comment]
Homer is only used for RTCP reports, not for RTP.

**Comment by githubsw** [comment]
So I will not even see RTCP records in the Homer pcaps?

**Comment by adubovikov** [comment]
you should see RTCP HEP, can you run ngrep on port 9092 (9090) and check if you see the packets ?
also, you can use HEPSUB if you want to get wavs/pcap files in the Homer UI.
