### ISSUE TITLE
SIP Header 'Replaces' Support for 3GPP SRVCC functionality

### ISSUE THREAD

**Issue by hamidrhashmi** [sipwise/rtpengine#1071]
Do RTPEngine Supports 'Replaces' header (RFC 3891), if yes then how to use this feature if no then will RTPEngine will have support for 'Replaces' in the near future?  I have been using Freeswitch for this functionality but facing many difficulties in it.

**Comment by rfuchs** [comment]
We don't support it as such. Rtpengine isn't really involved in the SIP signalling. so the support would have to be in the controlling module. On the rtpengine side, it would need a signalling command to rename a call ID and/or from/to-tags. This shouldn't be too hard to add, but also doesn't currently exist.
