### ISSUE TITLE
Feature - add support for metadata in stop_recording

### ISSUE THREAD

**Issue by drylaarsdam** [sipwise/rtpengine#1075]
Could the metadata option in start_recording() (kamailio rtpengine module) be made available in stop_recording()?

Was able to make it work using attached diff, but not sure if there are other issues to consider.

[recording_stop_meta.txt](https://github.com/sipwise/rtpengine/files/5198130/recording_stop_meta.txt)

**Comment by rfuchs** [comment]
closed via #1077
