### ISSUE TITLE
error with keydb active active replication

### ISSUE THREAD

**Issue by aancona86** [sipwise/rtpengine#1079]
hi, 
i'm trying to configure rtpengine 9.1 to work with a keydb active replication.
rtpengine: 172.16.227.202/24
KEYDB_PROXY: 172.16.227.100/24
KEYDB_1: 172.16.228.202/24
KEYDB_2: 172.16.227.203/24

In HA proxy backend is configured to check Redis and everything is ok and everybody throw firewalls can reach eachother.

While trying to start rtpengine it say:
root@osip31:/home/service# rtpengine --redis=172.16.227.100:6379/1
[1599822212.169879] ERR: Failed to connect to Redis 172.16.227.100:6379
[1599822212.170401] CRIT: Fatal error: Cannot start up without running Redis 172.16.227.100:6379 database! See also NO_REDIS_REQUIRED parameter.
root@osip31:/home/service#

Also if i try to connect to single node with rtpengine:
root@osip31:/home/service# rtpengine --redis=172.16.228.202:6379/1
[1599822275.507135] ERR: Failed to connect to Redis 172.16.228.202:6379
[1599822275.507487] CRIT: Fatal error: Cannot start up without running keydb 172.16.228.202:6379 database! See also NO_REDIS_REQUIRED parameter.
root@osip31:/home/service#

But if I try for example with keydb-cli it works in every way, with vip and also with connecting to the single node.
Is there anything with rtpengine that is not managed to work with this kind of configuration?
Regards,

**Comment by rfuchs** [comment]
We support Redis, not KeyDB. No idea if this works with KeyDB at all.

**Comment by aancona86** [comment]
Hi, I also tryed with redis, and I got the same error.
I think rtpengine is not managing something that is regarding redis ROLE in redis.c of deamon package.
Regards,

**Comment by rfuchs** [comment]
No other log output even when you run with debug log level?

You can try to run rtpengine under `strace -f` to see what the last command to Redis was that fails.

**Comment by aancona86** [comment]
As expected in redis.c we added:

 else if (!memcmp(s, "role:active-replica", 17)) {
                        if (r->role == MASTER_REDIS_ROLE || r->role == ANY_REDIS_ROLE) {
                                ilog(LOG_INFO, "Connected to Redis %s in master mode",
                                        endpoint_print_buf(&r->endpoint));
                                goto done;

and it start working.
The error was that redis.c didn't manage role:active-replica.

Thank you anyway,
regards,
