### ISSUE TITLE
Error on media handling on 183 early media

### ISSUE THREAD

**Issue by flaviogoncalves** [sipwise/rtpengine#1080]
Symptom:

In a situation with NAT the phone does not hear the rigback

By the standard, when rtpengine receives an RTP packet it should send the media to the address from where the SIP request was received and ignore the SDP content (except if we use trust-sdp)

When rtpengine receives 183 it sends to the internal address of the phone 

![image](https://user-images.githubusercontent.com/4958202/93631164-7da21500-f9c1-11ea-85fe-8024ea832fcf.png)

OpenSIPS 3.1

The call completes normally, in the logs I see the external addresses.

**Comment by rfuchs** [comment]
Trusting the SDP address has been the default for a while now. Use `SIP-source-address` (or config option `sip-source`) for the opposite behaviour.

**Comment by flaviogoncalves** [comment]
Thank you, I will test tomorrow.
