### ISSUE TITLE
Missing crypto attributes on second invite after 401 digest auth 

### ISSUE THREAD

**Issue by towe75** [sipwise/rtpengine#1086]
Hi,

we upgraded rtpengine to 7.5.5.1 and faced a problem. Rtpengine is used here for adding tls/srtp to asterisk->carrier calls. It correctly rewrites the SDP body for the initial INVITE. The carrier asks with 401 for authentication and the next, authenticated, INVITE is not correctly processed.

Traces show that a=fingerprint is still added but crypto attributes are missing completely. Both INVITES are sent in the exact way from Kamailio to rtpengine. 

I can confirm that all 7.5.x versions from 7.5.4.2 onwards show this behavior. Versions 7.5.4.1 down to good old 6.5.8.2 are fine.
Possibly the problem was introduced via https://github.com/sipwise/rtpengine/commit/1a7ead1748cc03f73b08401eb1d7456033fb70b0 ?

Stripping srtp from endpoints towards asterisk is not affected. 

Let me know if you need more info, traces, logs etc.

**Comment by rfuchs** [comment]
Full debug log from rtpengine would be helpful.

**Comment by towe75** [comment]
Sure, taken with loglevel 7 in a testbed: [rtpengine.log](https://github.com/sipwise/rtpengine/files/5327298/rtpengine.log)

**Comment by rfuchs** [comment]
Ah, the `delete` in between is probably interfering with this. As a short-term workaround, you can probably add `delete-delay=0` to that delete to fix things up. I'll have a proper fix shortly.

**Comment by towe75** [comment]
@rfuchs we deployed an older version for now. I _think_ we're not sending a explicit delete here, btw. Rather kamailio rtpengine_manage() sends it as a result to code >= 300. 

Anyhow, glad that the log helped, thank you.

**Comment by rfuchs** [comment]
Ok so my initial diagnosis was actually wrong :smile: 

Fix should be in 3860759 (based on mr7.5.5)

Please test and confirm.

**Comment by towe75** [comment]
LGTM, 🚀  
It fixes the problem. Thank you @rfuchs !
