### ISSUE TITLE
modprobe: FATAL: Module xt_RTPENGINE not found in directory /lib/modules/5.4.34-1-pve

### ISSUE THREAD

**Issue by ForGuru** [sipwise/rtpengine#1089]
After installation getting this error

`
ct 12 19:40:05 hermes ngcp-rtpengine-iptables-setup[52733]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/5.4.34-1-pve/modules.dep.bin'
Oct 12 19:40:05 hermes ngcp-rtpengine-iptables-setup[52733]: modprobe: FATAL: Module xt_RTPENGINE not found in directory /lib/modules/5.4.34-1-pve
Oct 12 19:40:05 hermes ngcp-rtpengine-iptables-setup[52733]: iptables v1.8.2 (nf_tables): unknown option "--id"
Oct 12 19:40:05 hermes ngcp-rtpengine-iptables-setup[52733]: Try `iptables -h' or 'iptables --help' for more information.
Oct 12 19:40:05 hermes ngcp-rtpengine-iptables-setup[52733]: ip6tables v1.8.2 (nf_tables): unknown option "--id"
Oct 12 19:40:05 hermes ngcp-rtpengine-iptables-setup[52733]: Try `ip6tables -h' or 'ip6tables --help' for more information.
Oct 12 19:40:05 hermes rtpengine[52748]: CRIT: Fatal error: Missing option --interface
Oct 12 19:40:05 hermes systemd[1]: ngcp-rtpengine-daemon.service: Main process exited, code=exited, status=255/EXCEPTION
Oct 12 19:40:06 hermes systemd[1]: ngcp-rtpengine-daemon.service: Failed with result 'exit-code'.
Oct 12 19:40:06 hermes systemd[1]: Failed to start NGCP RTP/media Proxy Daemon.
Processing triggers for systemd (241-7~deb10u4) ...
Processing triggers for man-db (2.8.5-2) ...

`

**Comment by rfuchs** [comment]
Looks like you don't have a config file set up, and are missing the kernel module. For the kernel module, use the dkms package if on Debain. Or install manually.

**Comment by ForGuru** [comment]
It was config file issue
