### ISSUE TITLE
fingerprint mismatch 

### ISSUE THREAD

**Issue by juha-h** [sipwise/rtpengine#1092]
Incoming INVITE has 
```
a=fingerprint:SHA-256 E2:79:D8:5D:F9:C9:40:8B:ED:7F:5C:72:70:DA:A2:55:96:1A:B1:12:8D:90:70:C7:55:1B:72:F8:95:69:8C:3E
m=audio 3344 UDP/TLS/RTP/SAVPF 96 97 98 8 0 101
...
m=video 7262 UDP/TLS/RTP/SAVPF 96 97
...
```
Called party only supports RTP/AVP transport, so SIP Proxy makes this kind of rtpengine_offer() call:
```
Oct 20 10:12:17 sip-proxy[7454]: INFO: rtpengine_offer(ICE=force replace-session-connection replace-origin rtcp-mux-demux via-branch=extra RTP/AVP trust-address)
```
Called party is happy with the modified SDP and gives 200 OK reply with SDP:
```
m=audio 30752 RTP/AVP 96 97 8 0 101
...
m=video 0 RTP/AVP 0
```
SIP Proxy then makes this kind of rtpengine_answer() call:
```
Oct 20 10:12:21 sip-proxy[7454]: INFO: rtpengine_answer(ICE=force replace-session-connection replace-origin via branch=extra)
```
which results to SDP
```
m=audio 50398 UDP/TLS/RTP/SAVPF 96 97 8 0 101
a=fingerprint:sha-1 21:89:42:AC:FC:3B:D3:0E:5C:8C:84:B7:B6:8D:F7:F7:EE:43:26:D1
...
m=video 0 UDP/TLS/RTP/SAVPF 0
```
Calling party does not like it, because it does not support sha-1:
```
dtls_srtp: unsupported fingerprint hash `sha-1'
```
From README.md, I have understood that rtpengine should use in the answer the same hashing function that the peer was using in the offer:

`DTLS-fingerprint`
 `Contains a string and is used to select the hashing function to generate the DTLS fingerprint from the certificate. The default is SHA-1, or the same hashing function as was used by the peer. Available are SHA-1, SHA-224, SHA-256, SHA-384, and SHA-512.`

but that does not seem to be the case.

Is this a bug?

**Comment by rfuchs** [comment]
This has just been added last week. Are you up to date on the code?

**Comment by rfuchs** [comment]
https://github.com/sipwise/rtpengine/commit/dc4775d5ce655097e888e9de913ca009bd1f95c4

**Comment by juha-h** [comment]
Sorry, I didn't notice.  I'm still at 9.1.0.0+0~mr9.1.0.0.  Will upgrade, test and reopen if still an issue.

**Comment by juha-h** [comment]
Tested with latest master and the issue was solved.  Thanks.

**Comment by juha-h** [comment]
Juts one more comment:  should default be sha-256, since sha-1 has been deprecated due to its security vulnerabilities (https://www.keycdn.com/support/sha1-vs-sha256)?

**Comment by rfuchs** [comment]
We'll change the default in the future. For now I don't want to break existing setups which don't support sha-256 yet.

**Comment by juha-h** [comment]
I added
```
dtls-signature = SHA-256
```
to .conf file, but still rtpengine used sha-1 in outbound SDP:
```
m=audio 50238 RTP/SAVPF 96 8 0 101
...
a=fingerprint:sha-1 5C:C5:09:C9:3D:D6:86:FB:8B:1B:72:12:58:16:F8:CF:D9:59:A7:2B
```
Why is that?

**Comment by rfuchs** [comment]
That option is for the self-signed certificate, not for the SDP fingerprint.

**Comment by juha-h** [comment]
Richard Fuchs writes:

> That option is for the self-signed certificate, not for the SDP
> fingerprint.

OK, it might then be a good idea to add another .conf variable for SDP
fingerprint default that would allow overriding the current (unsafe)
SHA-1 default.

**Comment by juha-h** [comment]
I did some experimenting with DTLS-fingerprint=SHA-256 in the offer.  Both Firefox and Chrome accepted the INVITE, but audio worked only with Firefox.  Answer on 200 OK from chrome resulted in errors:
```
Oct 20 18:55:00 lohi rtpengine[24724]: WARNING: [32004a4d4b9df70b port 50810]: DTLS: Peer certificate rejected - fingerprint mismatch
Oct 20 18:55:00 lohi rtpengine[24724]: ERR: [32004a4d4b9df70b port 50810]: DTLS error: 1 (certificate verify failed)
Oct 20 18:55:00 lohi rtpengine[24724]: ERR: [32004a4d4b9df70b port 50810]: DTLS error on local port 50810
```
There was no errors on Chrome console.  So for some reason, rtpengine didn't like the fingerprint it got from Chrome.
