### ISSUE TITLE
Require dtls signature sha-256

### ISSUE THREAD

**Issue by robdyck** [sipwise/rtpengine#1094]
Some agents require sha-256 dtls signature. I have tried setting this from the command line, the configuration file and in the flags sent by the proxy. None of these have any effect and the signature presented to the agent is always sha-1. 

I wanted some debug information and tried starting rtpengine in the forground with
```
rtpengine -L 7 -f --debug-srtp --config-file=/etc/rtpengine/rtpengine.conf --dtls-signature=sha-256
```
I didn't get any output.
Why would rtpengine use sha-1 by default when it is obsolete?

**Comment by rfuchs** [comment]
That option is for the signature for the DTLS certificate, not the fingerprint.

Make sure you have a recent version from git master, then use `DTLS-fingerprint=sha-256` in your `offer` messages.

**Comment by juha-h** [comment]
This is related:  https://github.com/sipwise/rtpengine/issues/1092.  In my tests DTLS-fingerprint=sha-256 generates sha-256 fingerprint, which works fine with Firefox WebRTC, but rtpengine does not like what it gets back from Chrome WebRTC in 200 OK.  I haven't had time to investigate further.

@rfuchs, does rtpengine generated sha-256 work in your tests with Chrome webrtc?

**Comment by rfuchs** [comment]
Yes it works for me
```
Oct 21 21:27:19 sp1 rtpengine[16140]: DEBUG: [«cc1b1044-83ab-4024-b255-03d1a24e81a2»]: ... a=fingerprint:sha-256 C3:A7:EE:2B:0D:9F:B3:CA:C1:D6:54:3B:3B:24:9D:D8:7B:2D:95:FD:AC:69:DC:47:D0:8B:A7:79:C2:A3:78:1C ...
...
Oct 21 21:27:19 sp1 rtpengine[16140]: INFO: [«cc1b1044-83ab-4024-b255-03d1a24e81a2» port 30000]: DTLS: Peer certificate accepted
```

**Comment by robdyck** [comment]
I have now compiled rtpengine and replaced the old rtpengine binary. I can confirm that the fingerprint is sha-256. I seem to have an additional problem to investigate. On a call to WEBRTC it fails on INVITE.
This particular issue can be closed in my opinion. We'll see how it goes.
