### ISSUE TITLE
Latest commit (cd3652e) add SDES unnecessarily

### ISSUE THREAD

**Issue by robdyck** [sipwise/rtpengine#1097]
This commit fixed the problem reported in #1096 but it introduced an unwanted behaviour. When using rtpengine to work around a simple NAT with no RTP profile changes, rtpengine arbitrarily adds SDES to the sdp. This required modifying the script that invokes rtpengine to explicitly deny SDES.

Was this change intended?

**Comment by juha-h** [comment]
robdyck writes:
> This commit fixed the problem reported in #1096 but it introduced an unwanted behaviour. When using rtpengine to work around a simple NAT with no RTP profile changes, rtpengine arbitrarily adds SDES to the sdp. This required modifying the script that invokes rtpengine to explicitly deny SDES.

I just made this kind of offer:
```
rtpengine_offer(ICE=force replace-session-connection replace-origin rtcp-mux-demux via-branch=extra trust-address)
```
and don't see any SDES in the SDP.

How are you making the offer?  What rtp transport protocol is used?

**Comment by robdyck** [comment]
Interface flags only - in-iface=ipv4-ext out-iface=ipv6. The test case was WEBRTC to WEBRTC  with NAT so RTP profile and ICE were not changed. I reverted to an older daemon and the SDES disappeared.

**Comment by juha-h** [comment]
robdyck writes:

> Interface flags only - in-iface=ipv4-ext out-iface=ipv6. The test case
> was WEBRTC to WEBRTC  with NAT so RTP profile and ICE were not
> changed. I reverted to an older daemon and the SDES disappeared.

OK, I don't see that, because I always add SDES-off if destination is
webrtc.

**Comment by rfuchs** [comment]
You'll have to post a full debug log because it shouldn't do this.

**Comment by robdyck** [comment]
```
Oct 25 11:25:24 slim rtpengine[734570]: INFO: [2v2hlhdjjtrg1v4a8hve]: Received command 'offer' from 127.0.0.1:60177
Oct 25 11:25:24 slim rtpengine[734570]: NOTICE: [2v2hlhdjjtrg1v4a8hve]: Creating new call
Oct 25 11:25:24 slim rtpengine[734570]: INFO: [2v2hlhdjjtrg1v4a8hve]: Replying to 'offer' from 127.0.0.1:60177 (elapsed time 0.009932 sec)
Oct 25 11:25:28 slim rtpengine[734570]: INFO: [2v2hlhdjjtrg1v4a8hve]: Received command 'delete' from 127.0.0.1:39843
Oct 25 11:25:28 slim rtpengine[734570]: INFO: [2v2hlhdjjtrg1v4a8hve]: Scheduling deletion of call branch 'r80rave9u4' (via-branch '') in 30 seconds
Oct 25 11:25:28 slim rtpengine[734570]: INFO: [2v2hlhdjjtrg1v4a8hve]: Replying to 'delete' from 127.0.0.1:39843 (elapsed time 0.000233 sec)
Oct 25 11:25:58 slim rtpengine[734570]: INFO: [2v2hlhdjjtrg1v4a8hve]: Call branch 'r80rave9u4' (via-branch '') deleted, no more branches remaining
Oct 25 11:25:58 slim rtpengine[734570]: INFO: [2v2hlhdjjtrg1v4a8hve]: Final packet stats:
Oct 25 11:25:58 slim rtpengine[734570]: INFO: [2v2hlhdjjtrg1v4a8hve]: --- Tag 'r80rave9u4', created 0:34 ago for branch '', in dialogue with ''
Oct 25 11:25:58 slim rtpengine[734570]: INFO: [2v2hlhdjjtrg1v4a8hve]: ------ Media #1 (audio over UDP/TLS/RTP/SAVPF) using unknown codec
Oct 25 11:25:58 slim rtpengine[734570]: INFO: [2v2hlhdjjtrg1v4a8hve]: --------- Port     192.168.1.1:35000 <>    209.52.88.97:42630, SSRC 0, 0 p, 0 b, 0 e, 34 ts
Oct 25 11:25:58 slim rtpengine[734570]: INFO: [2v2hlhdjjtrg1v4a8hve]: ------ Media #2 (video over UDP/TLS/RTP/SAVPF) using unknown codec
Oct 25 11:25:58 slim rtpengine[734570]: INFO: [2v2hlhdjjtrg1v4a8hve]: --------- Port     192.168.1.1:35002 <>    209.52.88.97:48720, SSRC 0, 0 p, 0 b, 0 e, 34 ts
Oct 25 11:25:58 slim rtpengine[734570]: INFO: [2v2hlhdjjtrg1v4a8hve]: --- Tag '', created 0:34 ago for branch '', in dialogue with 'r80rave9u4'
Oct 25 11:25:58 slim rtpengine[734570]: INFO: [2v2hlhdjjtrg1v4a8hve]: ------ Media #1 (audio over UDP/TLS/RTP/SAVPF) using unknown codec
Oct 25 11:25:58 slim rtpengine[734570]: INFO: [2v2hlhdjjtrg1v4a8hve]: --------- Port 2001:569::d2b4:35000 <>                :0    , SSRC 0, 0 p, 0 b, 0 e, 34 ts
Oct 25 11:25:58 slim rtpengine[734570]: INFO: [2v2hlhdjjtrg1v4a8hve]: ------ Media #2 (video over UDP/TLS/RTP/SAVPF) using unknown codec
Oct 25 11:25:58 slim rtpengine[734570]: INFO: [2v2hlhdjjtrg1v4a8hve]: --------- Port 2001::d2b4:35002 <>                :0    , SSRC 0, 0 p, 0 b, 0 e, 34 ts
```
Public addresses modified.

**Comment by rfuchs** [comment]
You need to enable debug logging (log level 7) for this to be useful

**Comment by robdyck** [comment]
Sorry about the slow reply and the lack of information. I had a suspicion that it was incomplete. Anyway it was filtered out in rsyslog and now I have it.
[rtpe.txt](https://github.com/sipwise/rtpengine/files/5435987/rtpe.txt)

**Comment by rfuchs** [comment]
Ok, this is actually expected and I'm pretty sure it did that before. A fresh SRTP offer to an endpoint that hasn't been seen before will have both SDES and DTLS added to the SDP by default, even if the original offer from the other side didn't have SDES. Use `SDES=off` to suppress that.

**Comment by robdyck** [comment]
It was a scenario I had tested previously but no matter. I will adopt Juha-h practice and always use SDES-off for WEBRTC.

Off topic, what is the purpose of the foreground option? I expected to see some output.

**Comment by rfuchs** [comment]
Foreground is just to leave it in the foreground, e.g. for debugging or under systemd. It's unrelated to logging output. There's a `log-stderr` option for that.
