### ISSUE TITLE
manually settle on single-codec / missing telephone-event in onreply_route / sdp-answer

### ISSUE THREAD

**Issue by ldr** [sipwise/rtpengine#1098]
Hi,

I'm using the new single-codec function from onreply_route for one scenario which works great, but this will settle on the codec in the answer that had the highest prio in the offer, thus resulting in transcoding which I don't always want. Therefore I try to differentiate in Kamailio so that in some situations I may manually specify what will end up in the sdp-answer towards the caller, although in that situation I keep missing the telephone-event.

Here's an example to make things clear:

The offer I get from caller looks as follows:
```
v=0
o=- 3812713289 3812713289 IN IP4 foo.bar.com
s=-
c=IN IP4 1.1.1.1
t=0 0
m=audio 40732 RTP/AVP 111 108 8 101 96
a=ptime:20
a=rtpmap:111 AMR-WB/16000
a=fmtp:111 mode-set=0,1,2; mode-change-period=2; mode-change-capability=2
a=rtpmap:108 AMR/8000
a=fmtp:108 mode-set=7
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/16000
a=rtpmap:96 telephone-event/8000
a=fmtp:96 0-15
a=fmtp:101 0-15
```

In the request_route, I then make sure that G722 gets prepended by this list by running the following rtpengine_manage() command:
```
rtpengine_manage("codec-mask-all codec-transcode-G722 codec-transcode-AMR-WB/16000/1///mode-set--0,1,2;mode-change-period--2;mode-change-capability--2/dtx--1 codec-transcode-AMR codec-transcode-PCMA codec-transcode-telephone-event ICE=remove");
```

This results in the following SDP offer to be sent from RTPEngine to the callee:
```
v=0
o=- 3812713289 3812713289 IN IP4 foo.bar.com
s=-
c=IN IP4 2.2.2.2
t=0 0
m=audio 18670 RTP/AVP 9 96 108 8 101 96
a=rtpmap:9 G722/8000
a=rtpmap:96 AMR-WB/16000
a=rtpmap:108 AMR/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/16000
a=rtpmap:96 telephone-event/8000
a=fmtp:96 mode-set=0,1,2;mode-change-period=2;mode-change-capability=2
a=fmtp:108 mode-set=7
a=fmtp:101 0-15
a=fmtp:96 0-15
a=sendrecv
a=rtcp:18671
a=ptime:20
```

Then in the onreply_route, I make the differentiation on if G722 or AMR-WB is in the incoming SDP-answer, if so, then I know the initial offer had AMR-WB and thus I use the new single-codec argument.

So if the SDP-answer coming from callee looks like follows:
```
v=0
o=FreeSWITCH 1603706241 1603706242 IN IP4 3.3.3.3
s=FreeSWITCH
c=IN IP4 3.3.3.3
t=0 0
m=audio 18248 RTP/AVP 9 96
a=rtpmap:9 G722/8000
a=rtpmap:96 telephone-event/8000
a=fmtp:96 0-16
a=silenceSupp:off - - - -
a=ptime:20
a=rtcp:18249 IN IP4 3.3.3.3
```

Doing single-codec:
```
if (sdp_with_codecs_by_name("G722") || sdp_with_codecs_by_name("AMR-WB")) {
    rtpengine_manage("single-codec");
} else {
    ...
```

Then the resulting SDP-answer sent from RTPEngine back to the caller is as follows:
```
v=0
o=FreeSWITCH 1603706241 1603706242 IN IP4 185.112.44.46
s=FreeSWITCH
c=IN IP4 185.112.44.46
t=0 0
m=audio 18680 RTP/AVP 111 101 96
a=silenceSupp:off - - - -
a=rtpmap:111 AMR-WB/16000
a=rtpmap:101 telephone-event/16000
a=rtpmap:96 telephone-event/8000
a=fmtp:111 mode-set=0,1,2; mode-change-period=2; mode-change-capability=2
a=fmtp:101 0-15
a=fmtp:96 0-16
a=sendrecv
a=rtcp:18681
a=ptime:20
```

Now in this case, I would expect the telephone-event to only have clock rate 16000 since that's the same as the AMR-WB (can this somehow be done?), but still, this works towards the caller.

--

But now, if the SDP-answer from callee back to RTPEngine only contains PCMA:
```
v=0
o=FreeSWITCH 1603707514 1603707515 IN IP4 3.3.3.3
s=FreeSWITCH
c=IN IP4 3.3.3.3
t=0 0
m=audio 17766 RTP/AVP 8 96
a=rtpmap:8 PCMA/8000
a=rtpmap:96 telephone-event/8000
a=fmtp:96 0-16
a=silenceSupp:off - - - -
a=ptime:20
a=rtcp:17767 IN IP4 3.3.3.3
```

I would like to not transcode that PCMA to AMR-WB, since PCMA was also part of the callers offer. Therefore I have an else in the onreply_route, forcing the outbound SDP-answer towards caller to be PCMA only:
```
if (sdp_with_codecs_by_name("G722") || sdp_with_codecs_by_name("AMR-WB")) {
    rtpengine_manage("single-codec");
} else {
    rtpengine_manage("codec-strip-all codec-offer-PCMA");
}
```

But in this case, I don't get the telephone-event in it:
```
v=0
o=FreeSWITCH 1603707514 1603707515 IN IP4 2.2.2.2
s=FreeSWITCH
c=IN IP4 2.2.2.2
t=0 0
m=audio 18860 RTP/AVP 8
a=silenceSupp:off - - - -
a=rtpmap:8 PCMA/8000
a=sendrecv
a=rtcp:18861
a=ptime:20
```

So, then thinking that I have to add telephone-event to the offer as well, or by using except, like so:
```
...
} else {
    rtpengine_manage("codec-strip-all codec-offer-PCMA codec-offer-telephone-event");
}
```

But this results in all codecs of the offer from the caller to be put in the answer to the caller:
```
v=0
o=FreeSWITCH 1603706922 1603706923 IN IP4 2.2.2.2
s=FreeSWITCH
c=IN IP4 2.2.2.2
t=0 0
m=audio 19110 RTP/AVP 111 108 8 101 96
a=silenceSupp:off - - - -
a=rtpmap:111 AMR-WB/16000
a=rtpmap:108 AMR/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/16000
a=rtpmap:96 telephone-event/8000
a=fmtp:111 mode-set=0,1,2; mode-change-period=2; mode-change-capability=2
a=fmtp:108 mode-set=7
a=fmtp:101 0-15
a=fmtp:96 0-16
a=sendrecv
a=rtcp:19111
a=ptime:20
```

Is there something I have to do in a different way to manually steer the codec to be put in the SDP answer towards caller ?

End goal is to use the highest common denominator and only if that's not possible do transcoding to the highest preference that the caller gave in its SDP-offer.

Thanks,

Leon

**Comment by rfuchs** [comment]
So the first one should be fixed already by 68ccc52

I see the problem with the second case. You're right that you need to add `telephone-event` as `offer` or `except` to get it passed through, but it shouldn't add those other codecs. Will try to come up with a fix.

**Comment by rfuchs** [comment]
Ah, this is because the answer has the DTMF format parameters as `0-16` while we support `0-15` and so this is seen is a mismatch 😂

Easy to fix...

**Comment by ldr** [comment]
Verified that the telephone-event is now (fixed in later commit than where i was) sent out only with same clock rate as the audio codec. Thank you so much !
