### ISSUE TITLE
T.38 decoding does not work as expected

### ISSUE THREAD

**Issue by SipSeb** [sipwise/rtpengine#1100]
When there is an existing call and the SDP contains T.38, I want rtpengine to strip it and convert it to plain PCMA. If I understand the docs correctly, I have to specify `T.38=decode` in Kamailio. I do it, but the replaced SDP still contains T.38.

This is the debug log.

```
Oct 30 15:16:29 rtp01 rtpengine[958]: DEBUG: [1021018547@217.116.x.x]: Dump for 'offer' from 217.116.x.x:51393: { "sdp":
 "v=0
o=- 267579187 183479480 IN IP4 62.155.x.x
s=call
c=IN IP4 62.155.x.x
t=0 0
m=image 18288 udptl t38
a=T38FaxVersion:1
a=T38MaxBitRate:14400
a=T38FaxTranscodingMMR
a=T38FaxTranscodingJBIG
a=T38FaxRateManagement:transferredTCF
a=T38FaxUdpEC:t38UDPRedundancy
a=T38FaxUdpEC:t38UDPFEC
a=T38FaxMaxDatagram:512
a=sendrecv
a=ptime:20
", "T.38": "decode", "codec-offer": "alaw", "call-id": "1021018547@217.116.x.x, "received- ...
Oct 30 15:16:29 rtp01 rtpengine[958]: DEBUG: [1021018547@217.116.x.x]: ... from": [ "IP4", "217.116.a.b" ], "from-tag": "1346847722", "to-tag": "169956439", "command": "offer" }
Oct 30 15:16:29 rtp01 rtpengine[958]: DEBUG: [1021018547@217.116.x.x]: Eliminating asymmetric inbound codec PCMA/8000
Oct 30 15:16:29 rtp01 rtpengine[958]: DEBUG: [1021018547@217.116.x.x]: 0 DTMF sink entries
Oct 30 15:16:29 rtp01 rtpengine[958]: DEBUG: [1021018547@217.116.x.x]: Eliminating asymmetric outbound codec PCMA/8000
Oct 30 15:16:29 rtp01 rtpengine[958]: DEBUG: [1021018547@217.116.x.x]: Shutting down ICE agent (nothing to do)
Oct 30 15:16:29 rtp01 rtpengine[958]: DEBUG: [1021018547@217.116.x.x]: Response dump for 'offer' to 217.116.y.y:51393: { "sdp": "v=0
o=- 267579187 183479480 IN IP4 62.155.x.x
s=call
c=IN IP4 217.116.z.z
t=0 0
m=image 26852 udptl t38
a=T38FaxVersion:1
a=T38MaxBitRate:14400
a=T38FaxTranscodingMMR
a=T38FaxTranscodingJBIG
a=T38FaxRateManagement:transferredTCF
a=T38FaxUdpEC:t38UDPRedundancy
a=T38FaxUdpEC:t38UDPFEC
a=T38FaxMaxDatagram:512
a=ptime:20
a=sendrecv
a=ptime:20
", "result": "ok" }
```

What am I doing wrong? I'm running rtpengine version 8.2.2.0.

**Comment by SipSeb** [comment]
I just noticed, that T.38 support was not there in version 8.2.2.0, so I updated to 9.0.1.2. I can see, rtpengine is linked against libspandsp. But the log looks the same. Still the same question.

**Comment by rfuchs** [comment]
Your control module doesn't properly support the `T.38=...` options. Use a dash instead: `T.38-decode`

**Comment by rfuchs** [comment]
Hey nice classic deadlock :smile: 

Try with 0c581e5 applied (based on top of 9.0.1)

**Comment by rfuchs** [comment]
Any feedback on this?

**Comment by SipSeb** [comment]
Hi Richard,

I built and tested it with the new patch, this time the call went through. It wasn't successful, but that might be because of a suspected bug in libspandsp. I'll dig deeper into this when I find the time for it.

**Comment by rfuchs** [comment]
Ok, will merge and close this then. Feel free to open again or open another issue if you find something else.
