### ISSUE TITLE
[Feature] NG socket TCP

### ISSUE THREAD

**Issue by volga629-1** [sipwise/rtpengine#1101]
Hello Everyone,
Based on my previous ticket #946 was done more troubleshooting in order identify the issue.
The issue can be repeated when UDP fragmentation is occurring with high load systems. 
I was wondering if possible add TCP listener for NG protocol.

The test was done by John Quick

```
https://www.smartvox.co.uk/2020/11/latency-caused-by-udp-fragmentation/
```

Which support idea of growing delay between delete command and actual execution.

New option:

```
 --listen-ng-tcp 127.0.0.1:2223

```

Thank you.

**Comment by rfuchs** [comment]
We support NG over HTTP as well as over Websocket now (both plaintext and TLS). There's no support for this in the control modules (Kamailio, OpenSIPS) yet, but it just needs to be added there. The rtpengine side of things is done.

**Comment by volga629-1** [comment]
@rfuchs  Thank you for reply. Can you please clarify options to use to enable HTTP and Web Socket. I checked --help for version 9.0 and 8.3.1 and I don't anything specific.

**Comment by rfuchs** [comment]
It's a new feature, you'll have to pull code from master or the upcoming 9.1 release. There's some documentation at https://github.com/sipwise/rtpengine#httpwebsocket-support and the options are
```
  --listen-http=[IP46|HOSTNAME:]PORT                          Interface for HTTP and WS
  --listen-https=[IP46|HOSTNAME:]PORT                         Interface for HTTPS and WSS
  --https-cert=FILE                                           Certificate for HTTPS and WSS
  --https-key=FILE                                            Private key for HTTPS and WSS
  --http-threads=INT                                          Number of worker threads for HTTP and WS
```

**Comment by volga629-1** [comment]
Thank you. All those listeners is use NG protocol ?

**Comment by rfuchs** [comment]
You can use these interfaces for NG requests as well as a few other purposes. The details are described in the link I've posted (bottom of the README)
