### ISSUE TITLE
How create new Table

### ISSUE THREAD

**Issue by malvarado611** [sipwise/rtpengine#1103]
I am trying to create a new Table with the following command:

modprobe xt_RTPENGINE

iptables -I INPUT -p udp -d 192.168.1.250 -j RTPENGINE --id 0
iptables -I INPUT -p udp -d 192.168.43.250 -j RTPENGINE --id 1

/usr/sbin/rtpengine --table=0 --interface=192.168.1.250 --listen-ng=127.0.0.1:2223 --tos=184 --pidfile=/run/rtpengine-10.pid --no-fallback

/usr/sbin/rtpengine --table=1 --interface=192.168.43.250 --listen-ng=127.0.0.1:2224 --tos=184 --pidfile=/run/rtpengine-192.pid --no-fallback

But I get the following error when the last line is executed:

[1604428566.580720] ERR: Failed to open TCP control port: Address already in use
[1604428566.581012] CRIT: Fatal error: Failed to open TCP control connection port

Any idea why I get this error?

**Comment by rfuchs** [comment]
That error isn't actually related to the table. Do you have a config file in place? I think you may inadvertently share some config options between the two instances (TCP control or CLI interface).

**Comment by malvarado611** [comment]
I have the following configuration file:

[rtpengine]

table = 0
#no-fallback = false
### for userspace forwarding only:
#table = -1

### a single interface:
interface = 192.168.1.250
### separate multiple interfaces with semicolons:
# interface = internal/12.23.34.45;external/23.34.45.54
### for different advertised address:
##interface = internal/192.168.1.6

listen-ng = 192.168.1.250:2223
listen-tcp = 25060
listen-udp = 12222

timeout = 60
silent-timeout = 3600
tos = 184
control-tos = 184
delete-delay = 30
final-timeout = 10800

foreground = false
pidfile = /run/ngcp-rtpengine-daemon.pid
num-threads = 16

port-min = 30000
port-max = 40000
max-sessions = 5000

recording-dir = /var/spool/rtpengine
recording-method = proc
recording-format = raw

#redis = 127.0.0.1:6379/5
#redis-write = password@12.23.34.45:6379/42
#redis-num-threads = 8
#no-redis-required = false
#redis-expires = 86400
#redis-allowed-errors = -1
#redis-disable-time = 10
#redis-cmd-timeout = 0
#redis-connect-timeout = 1000

#b2b-url = http://127.0.0.1:8090/
#xmlrpc-format = 0

log-level = 6
log-stderr = false
log-facility = daemon
log-facility-cdr = local0
log-facility-rtcp = local1

#graphite = 127.0.0.1:9006
#graphite-interval = 60
#graphite-prefix = foobar.

#homer = 127.0.0.1:65432
#homer-protocol = udp
#homer-id = 2001

sip-source = false
dtls-passive = false

#[rtpengine-testing]
#table = -1
#interface = 192.168.1.250
#listen-ng = 2223
#foreground = true
#log-stderr = true
#log-level = 7

Could you create another Table using the same configuration file?

**Comment by rfuchs** [comment]
Sure you can, but you can't have two instances of rtpengine trying to listen on the same ports. In particular, the listen-ng/udp/tcp/cli options need to be set to listen on different ports and/or interfaces. Remove them from the config file and specify them on the command line instad.

**Comment by rfuchs** [comment]
(You just commented in the wrong issue...)

Just remove all the `listen-...` options from your config file and then try again.

**Comment by malvarado611** [comment]
Okay.
To make the configuration that you tell me, it is necessary to use different tables or I can use the same table by default (0).

**Comment by rfuchs** [comment]
If you want to run two instances, you have to use two tables.

**Comment by malvarado611** [comment]
Query:
I have an SBC that receives information from many clients. There is some way to be able to separate the recordings by clients, that is, in individual folders for each one.

**Comment by rfuchs** [comment]
We don't have customisable/configurable output paths for recordings right now. You'll have to do it after the recording is finished yourself, going by call ID or metadata.

**Comment by malvarado611** [comment]
I get it.

Thanks for your help.

One more query because when the call is recorded I see the following information in the daemon.log:

Nov  4 13:28:20 SipRec rtpengine[403]: INFO: [12627226944112020132816@192.168.1.235]: Received command 'offer' from 192.168.1.250:33938
Nov  4 13:28:20 SipRec rtpengine[403]: NOTICE: [12627226944112020132816@192.168.1.235]: Creating new call
Nov  4 13:28:20 SipRec rtpengine[403]: NOTICE: [12627226944112020132816@192.168.1.235]: Turning on call recording.
Nov  4 13:28:20 SipRec rtpengine[403]: INFO: [12627226944112020132816@192.168.1.235]: Replying to 'offer' from 192.168.1.250:33938 (elapsed time 0.051828 sec)
Nov  4 13:28:20 SipRec rtpengine[403]: INFO: [12627226944112020132816@192.168.1.235]: Received command 'answer' from 192.168.1.250:33938
Nov  4 13:28:20 SipRec rtpengine[403]: INFO: [12627226944112020132816@192.168.1.235]: Replying to 'answer' from 192.168.1.250:33938 (elapsed time 0.000201 sec)
Nov  4 13:28:20 SipRec rtpengine-recording[363]: ERR: [C 12627226944112020132816%40192.168.1.235-6915e4f19f77aa92.meta] [S tag-0-media-1-component-1-RTP-id-2] Trying to send packets, but connection not initialized!
Nov  4 13:28:20 SipRec rtpengine-recording[363]: ERR: [C 12627226944112020132816%40192.168.1.235-6915e4f19f77aa92.meta] [S tag-0-media-1-component-1-RTP-id-2] Trying to send packets, but connection not initialized!
Nov  4 13:28:20 SipRec rtpengine-recording[363]: ERR: [C 12627226944112020132816%40192.168.1.235-6915e4f19f77aa92.meta] [S tag-0-media-1-component-1-RTP-id-2] Trying to send packets, but connection not initialized!
Nov  4 13:28:20 SipRec rtpengine-recording[363]: ERR: [C 12627226944112020132816%40192.168.1.235-6915e4f19f77aa92.meta] [S tag-0-media-1-component-1-RTP-id-2] Trying to send packets, but connection not initialized!
Nov  4 13:28:20 SipRec rtpengine-recording[363]: ERR: [C 12627226944112020132816%40192.168.1.235-6915e4f19f77aa92.meta] [S tag-0-media-1-component-2-RTCP-id-3] Trying to send packets, but connection not initialized!
Nov  4 13:28:20 SipRec rtpengine-recording[363]: ERR: [C 12627226944112020132816%40192.168.1.235-6915e4f19f77aa92.meta] [S tag-0-media-1-component-1-RTP-id-2] Trying to send packets, but connection not initialized!
Nov  4 13:28:20 SipRec rtpengine-recording[363]: ERR: [C 12627226944112020132816%40192.168.1.235-6915e4f19f77aa92.meta] [S tag-0-media-1-component-1-RTP-id-2] Trying to send packets, but connection not initialized!
Nov  4 13:28:20 SipRec rtpengine-recording[363]: ERR: [C 12627226944112020132816%40192.168.1.235-6915e4f19f77aa92.meta] [S tag-0-media-1-component-1-RTP-id-2] Trying to send packets, but connection not initialized!

What can these errors be due to? Could this cause a problem in the future?, since despite these messages the recording is carried out without problems.

**Comment by rfuchs** [comment]
Do you have the packet forwarding mechanism enabled for the recording daemon when you're not actually using it?

**Comment by malvarado611** [comment]
It is correct I had not noticed.

Thanks a lot. I already managed to correct the error.

**Comment by malvarado611** [comment]
Query:
I have the following configuration file for the rtpengine-recoding service. It is possible to generate another similar file, but using 
table 1 as ID.

[rtpengine-recording]

table = 0

### directory containing rtpengine metadata files
spool-dir = /var/spool/rtpengine

### where to store media files to
output-dir = /var/lib/rtpengine-recording

### resample all output audio
resample-to = 8000

### mix participating sources into a single output
output-mixed = true

**Comment by rfuchs** [comment]
You can just copy the file and put `table=1` in the other and use that?

**Comment by malvarado611** [comment]
I have table 1 raised with the following command:
modprobe xt_RTPENGINE
iptables -I INPUT -p udp -d 192.168.1.250 -j RTPENGINE --id 1

/usr/sbin/rtpengine --table=1 --interface=192.168.1.250 --listen-ng=192.168.1.250:2223 --listen-tcp=25060 --listen-udp=12222 --tos=184 --pidfile=/run/ngcp-rtpengine-daemon.pid --no-fallback


I observe that the packages are entering:
root@SipRec:/var/lib/rtpengine-recording# cat /proc/rtpengine/1/list
local inet4 192.168.1.250:30096
       src inet4 192.168.1.250:30110
       dst inet4 192.168.1.235:6270
    stats:                15136 bytes,                   88 packets,                    0 errors
        RTP payload type   8:                15136 bytes,                   88 packets
  SSRC in: 285b3626
local inet4 192.168.1.250:30110
       src inet4 192.168.1.250:30096
       dst inet4 192.168.1.235:6265
    stats:                17716 bytes,                  103 packets,                    0 errors
        RTP payload type   8:                17716 bytes,                  103 packets
  SSRC in: 2bfb3f70


Additionally, I have the following file for rtpengine-recording:
[rtpengine-recording]
table = 1
spool-dir = /var/spool/rtpengine
output-dir = /var/lib/rtpengine-recording
resample-to = 8000
output-mixed = true

But, in the logs it is observed that the Kernel looks for table 0 to carry out the recording.
Nov  4 22:35:02 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235]: Received command 'offer' from 192.168.1.250:43301
Nov  4 22:35:02 SipRec rtpengine[461]: NOTICE: [11721196744112020223457@192.168.1.235]: Creating new call
Nov  4 22:35:02 SipRec rtpengine[461]: NOTICE: [11721196744112020223457@192.168.1.235]: Turning on call recording.
Nov  4 22:35:02 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235]: Replying to 'offer' from 192.168.1.250:43301 (elapsed time 0.000329 sec)
Nov  4 22:35:02 SipRec rtpengine-recording[339]: ERR: Failed to open kernel stream /proc/rtpengine/0/calls/11721196744112020223457%40192.168.1.235-eae164273c27d5c7/tag-1-media-1-component-1-RTP-id-0: No such file or directory
Nov  4 22:35:02 SipRec rtpengine-recording[339]: ERR: Failed to open kernel stream /proc/rtpengine/0/calls/11721196744112020223457%40192.168.1.235-eae164273c27d5c7/tag-1-media-1-component-2-RTCP-id-1: No such file or directory
Nov  4 22:35:02 SipRec rtpengine-recording[339]: ERR: Failed to open kernel stream /proc/rtpengine/0/calls/11721196744112020223457%40192.168.1.235-eae164273c27d5c7/tag-0-media-1-component-1-RTP-id-2: No such file or directory
Nov  4 22:35:02 SipRec rtpengine-recording[339]: ERR: Failed to open kernel stream /proc/rtpengine/0/calls/11721196744112020223457%40192.168.1.235-eae164273c27d5c7/tag-0-media-1-component-2-RTCP-id-3: No such file or directory
Nov  4 22:35:02 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235]: Received command 'answer' from 192.168.1.250:43301
Nov  4 22:35:02 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235]: Replying to 'answer' from 192.168.1.250:43301 (elapsed time 0.000130 sec)
Nov  4 22:35:06 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235 port 30110]: Confirmed peer address as 192.168.1.235:6270
Nov  4 22:35:06 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235 port 30096]: Confirmed peer address as 192.168.1.235:6265
Nov  4 22:35:06 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235 port 30096]: Kernelizing media stream: 192.168.1.235:6265
Nov  4 22:35:06 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235 port 30110]: Kernelizing media stream: 192.168.1.235:6270
Nov  4 22:35:07 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235 port 30097]: Confirmed peer address as 192.168.1.235:6266
Nov  4 22:35:08 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235 port 30111]: Confirmed peer address as 192.168.1.235:6271
Nov  4 22:35:12 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235 port 30097]: Confirmed peer address as 192.168.1.235:6266

Hay forma de que el Kernel pueda reenviar los paquetes de acuerdo a la tabla configurada?

**Comment by rfuchs** [comment]
It shouldn't do that. If you tell it to use table 1, it should use table 1. Make sure the recording daemon is started correctly and uses the right config file. Also make sure you don't use the same spool directory for both instances of rtpengine/recording. You need to use two different spool directories for your two instances.

**Comment by malvarado611** [comment]
Hi,
I tell you that by performing the following configuration.
modprobe xt_RTPENGINE
iptables -I INPUT -p udp -d 192.168.1.250 -j RTPENGINE --id 0
iptables -I INPUT -p udp -d 192.168.1.250 -j RTPENGINE --id 1

/usr/sbin/rtpengine --table=0 --interface=192.168.1.250 --listen-ng=192.168.1.250:2223 --listen-tcp=25060 --listen-udp=12222 --tos=184 --pidfile=/run/ngcp-rtpengine-daemon.pid --no-fallback --foreground

/usr/sbin/rtpengine --table=1 --interface=192.168.1.250 --listen-ng=192.168.1.250:2223 --listen-tcp=25060 --listen-udp=12222 --tos=184 --pidfile=/run/ngcp-rtpengine-daemon.pid --no-fallback --foreground

In RTPENGIENE-RECORDING I have the following file:

[rtpengine-recording]
table = 0
spool-dir = /var/spool/rtpengine
output-dir = /var/lib/rtpengine-recording
resample-to = 8000
output-mixed = true


table = 1
spool-dir = /var/spool/rtpengine
output-dir = /var/lib/prueba-recording
resample-to = 8000
output-mixed = true


I have the devil running smoothly
root@SipRec:~# systemctl status ngcp-rtpengine-recording-daemon
● ngcp-rtpengine-recording-daemon.service - NGCP RTP/media Recording Daemon
   Loaded: loaded (/lib/systemd/system/ngcp-rtpengine-recording-daemon.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-11-05 09:31:17 -05; 5min ago
 Main PID: 340 (rtpengine-recor)
    Tasks: 9 (limit: 1150)
   Memory: 49.0M
   CGroup: /system.slice/ngcp-rtpengine-recording-daemon.service
           └─340 /usr/sbin/rtpengine-recording -f -E --no-log-timestamps --pidfile /run/ngcp-rtpengine-recording-daemon.pid --config-file /etc

nov 05 09:31:13 SipRec systemd[1]: Starting NGCP RTP/media Recording Daemon...
nov 05 09:31:17 SipRec systemd[1]: Started NGCP RTP/media Recorning

The recording directories have been created correctly by the APP, but I still have the problem mentioned above.
Nov 4 22:35:02 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235]: Received command 'offer' from 192.168.1.250:43301
Nov 4 22:35:02 SipRec rtpengine[461]: NOTICE: [11721196744112020223457@192.168.1.235]: Creating new call
Nov 4 22:35:02 SipRec rtpengine[461]: NOTICE: [11721196744112020223457@192.168.1.235]: Turning on call recording.
Nov 4 22:35:02 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235]: Replying to 'offer' from 192.168.1.250:43301 (elapsed time 0.000329 sec)
Nov 4 22:35:02 SipRec rtpengine-recording[339]: ERR: Failed to open kernel stream /proc/rtpengine/0/calls/11721196744112020223457%40192.168.1.235-eae164273c27d5c7/tag-1-media-1-component-1-RTP-id-0: No such file or directory
Nov 4 22:35:02 SipRec rtpengine-recording[339]: ERR: Failed to open kernel stream /proc/rtpengine/0/calls/11721196744112020223457%40192.168.1.235-eae164273c27d5c7/tag-1-media-1-component-2-RTCP-id-1: No such file or directory
Nov 4 22:35:02 SipRec rtpengine-recording[339]: ERR: Failed to open kernel stream /proc/rtpengine/0/calls/11721196744112020223457%40192.168.1.235-eae164273c27d5c7/tag-0-media-1-component-1-RTP-id-2: No such file or directory
Nov 4 22:35:02 SipRec rtpengine-recording[339]: ERR: Failed to open kernel stream /proc/rtpengine/0/calls/11721196744112020223457%40192.168.1.235-eae164273c27d5c7/tag-0-media-1-component-2-RTCP-id-3: No such file or directory
Nov 4 22:35:02 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235]: Received command 'answer' from 192.168.1.250:43301
Nov 4 22:35:02 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235]: Replying to 'answer' from 192.168.1.250:43301 (elapsed time 0.000130 sec)
Nov 4 22:35:06 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235 port 30110]: Confirmed peer address as 192.168.1.235:6270
Nov 4 22:35:06 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235 port 30096]: Confirmed peer address as 192.168.1.235:6265
Nov 4 22:35:06 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235 port 30096]: Kernelizing media stream: 192.168.1.235:6265
Nov 4 22:35:06 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235 port 30110]: Kernelizing media stream: 192.168.1.235:6270
Nov 4 22:35:07 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235 port 30097]: Confirmed peer address as 192.168.1.235:6266
Nov 4 22:35:08 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235 port 30111]: Confirmed peer address as 192.168.1.235:6271
Nov 4 22:35:12 SipRec rtpengine[461]: INFO: [11721196744112020223457@192.168.1.235 port 30097]: Confirmed peer address as 192.168.1.235:6266

Regards,
Miguel Alvarado
________________________________
De: Richard Fuchs <notifications@github.com>
Enviado: jueves, 5 de noviembre de 2020 07:36
Para: sipwise/rtpengine <rtpengine@noreply.github.com>
Cc: Miguel Alvarado <malvarado@unifica2.pe>; Author <author@noreply.github.com>
Asunto: Re: [sipwise/rtpengine] How create new Table (#1103)


It shouldn't do that. If you tell it to use table 1, it should use table 1. Make sure the recording daemon is started correctly and uses the right config file. Also make sure you don't use the same spool directory for both instances of rtpengine/recording. You need to use two different spool directories for your two instances.

**Comment by rfuchs** [comment]
If you're running two instances of rtpengine with different tables, you also need to run two instances of the recording daemon with different tables (different config files, or specified at the command line)

**Comment by malvarado611** [comment]
How could I run two instances of the command line recording daemon?

**Comment by rfuchs** [comment]
Exactly the same way as you do for the main rtpengine daemon.

**Comment by rfuchs** [comment]
Cleaning up old tickets
