### ISSUE TITLE
ICE Candidates when there is a TURN Server

### ISSUE THREAD

**Issue by githubsw** [sipwise/rtpengine#1104]
Hello,

I have a situation where, when we have a TURN Server enabled, rtpengine appears to be ignoring certain ice-candidates that it sees.  Is this true? and if so, is there anything that can be done about this?

Can I manually add/remove ice-candidates? using rtpengine_manage?

Thank you!,

**Comment by rfuchs** [comment]
Can you post a concrete example?

**Comment by rfuchs** [comment]
Cleaning up old tickets
