### ISSUE TITLE
ICE-LITE mode

### ISSUE THREAD

**Issue by ahmedfayoub** [sipwise/rtpengine#1106]
Hi,

How can I enable rtpengine to act as ice-lite mode only ?

**Comment by rfuchs** [comment]
No, we decided to only support full ICE.

**Comment by ahmedfayoub** [comment]
But in older versions you were supporting ICE-Lite , correct ?
and if so what was the option to use with Kamailio to send a=ice-lite

**Comment by rfuchs** [comment]
Older versions only supported ICE lite. We decided to implement full ICE instead. There was never an option.

**Comment by ahmedfayoub** [comment]
Thanks for your answer and sorry to bother which older version was supporting the LITE ?

**Comment by rfuchs** [comment]
Wow that was a long time ago... Anything before f99d6d4f :smile: 

Looks like the last branch that doesn't have it is `mr3.7`

**Comment by ahmedfayoub** [comment]
Thanks but that's too old :)
What modifications or parameters to have rtpegnine always in controlled ICE state "NOT controlling" ?

**Comment by ahmedfayoub** [comment]
In ice.c I see a function called __ice_agent_initialize with the following line 

`bf_copy(&ag->agent_flags, ICE_AGENT_CONTROLLING, &media->media_flags, MEDIA_FLAG_ICE_CONTROLLING);`

what values should I replace there to stop being the controlling agent and just be a controlled one ?

**Comment by rfuchs** [comment]
You can probably just remove these lines from `call.c` (in `__ice_offer()`)
```
        /* determine roles (even if we don't actually do ICE) */
        /* this = receiver, other = sender */
        /* ICE_CONTROLLING is from our POV, the other ICE flags are from peer's POV */
        if (MEDIA_ISSET(this, ICE_LITE))
                MEDIA_SET(this, ICE_CONTROLLING);
        else if (!MEDIA_ISSET(this, INITIALIZED)) {
                if (flags->opmode == OP_OFFER)
                        MEDIA_SET(this, ICE_CONTROLLING);
                else
                        MEDIA_CLEAR(this, ICE_CONTROLLING);
        }

        /* roles are reversed for the other side */
        if (MEDIA_ISSET(other, ICE_LITE))
                MEDIA_SET(other, ICE_CONTROLLING);
        else if (!MEDIA_ISSET(other, INITIALIZED)) {
                if (flags->opmode == OP_OFFER)
                        MEDIA_CLEAR(other, ICE_CONTROLLING);
                else
                        MEDIA_SET(other, ICE_CONTROLLING);
        }
```
That should leave it in controlled mode. That's not the same as ICE lite though. Maybe you can explain what problem you're trying to solve?

**Comment by ahmedfayoub** [comment]
Hi,

The problem is when RTPengine sends a new offer with ICE=force to a FULL ICE we took the controlling part per RFC
When this happens remote candidates start to send STUN requests with being CONTROLLED and I'd like to have them CONTROLLING

in brief I'd like to always in controlled mode even if am sending the initial offer or replying.

Thanks again for your help , I'll try the above suggestion and update you in a few.

**Comment by ahmedfayoub** [comment]
I made the suggestion but still the other end is in CONTROLLED mode and logs shows it went to determine role conflict in ice.c and executed the role change to 1 (controlling)

` __role_change(ag, 1);`

What do you suggest ?

**Comment by rfuchs** [comment]
Can't really do anything about that. The RFC explains how the role is determined. You can't force one side to be the controlling side when it shouldn't be. You can try adding the `a=ice-lite` attribute to the SDP (in `sdp.c`) but rtpengine will still send STUN out, so that probably still won't work.

Why do you want your remote peer to be the controlling side?

**Comment by ahmedfayoub** [comment]
I already added this change in sdp.c and disabled the STUN out messages for the sake of experiment and am out of ideas !
The remote end is full ice and want to be always the controlling end and this is the requirement.

**Comment by ahmedfayoub** [comment]
Hi Richard,

In ice.c and function __ice_agent_initialize line 239
`bf_copy(&ag->agent_flags, ICE_AGENT_CONTROLLING, &media->media_flags, MEDIA_FLAG_ICE_CONTROLLING);`
I found these flags values in the header file as the following 
`call.h:#define MEDIA_FLAG_ICE_CONTROLLING               0x00200000
ice.h:#define ICE_AGENT_CONTROLLING             0x0004`

I tried to find any flags for CONTROLLED but there is none.

What are the meaning of these flags and their values related to controlling , can we set them to something else to be always in controlled state for any initial offer from rtpengine ?

**Comment by rfuchs** [comment]
It's either one or the other: If it's not controlling, then it's controlled. So there's no separate flag for that.

**Comment by ahmedfayoub** [comment]
Hmm I agree but because am the offer-er even when am in controlled mode , the receiver isn't taking the controlling while he is a FULL ice implementation.
