### ISSUE TITLE
rtpengine does not send out any T.38 packets

### ISSUE THREAD

**Issue by SipSeb** [sipwise/rtpengine#1107]
I tried T.38 de/encoding, the call gets setup, but rtpengine doesn't send out any packets. The only three packets being sent out are three `t30-ind: no-signal` packets, after that a lot of T.38 packets come in from the far end, but none are sent out.

I call rtpengine like this for all requests:
```
rtpengine_manage("T.38-decode ICE=remove no-rtcp-attribute");
```

And like this for all replies:
```
rtpengine_manage("no-rtcp-attribute");
```

Attached is a Wireshark screenshot, wildly anonymized. The 217 IP is our rtpengine, the 62 IP is the remote IP. RTP on the other leg goes both ways. 

<img width="1792" alt="Bildschirmfoto 2020-11-10 um 18 52 02" src="https://user-images.githubusercontent.com/9820790/98712100-251a4300-2386-11eb-87be-b5a4d1ffda33.png">

I have debug logs of this call as well, but since there are too many IPs and stuff in there, I'd like to rather not append that here. I could mail that it to somebody as well as the pcap trace if needed.

Is there anything I can do for debugging?

**Comment by rfuchs** [comment]
You can send the log and the pcap to my email.

**Comment by SipSeb** [comment]
Will do. I noticed something else. I just sent the very same fax to two different recipients. One doesn't reINVITE to T.38, so the fax is sent using G.711, the other one reINVITEs immediately after picking up. In Wireshark it looks like the T.38-decoded fax stream is not detected as a fax stream, so the sender does not send anything else but silence after two beeps. Maybe that's already the cause. I don't see what's wrong with the decoded stream, though.

This is the G.711 stream:
<img width="1380" alt="Bildschirmfoto 2020-11-10 um 20 53 27" src="https://user-images.githubusercontent.com/9820790/98727205-e1303980-2397-11eb-9a20-c304cb7ac181.png">

And this is the G.711-to-T.38 stream:
<img width="1380" alt="Bildschirmfoto 2020-11-10 um 20 53 16" src="https://user-images.githubusercontent.com/9820790/98727245-f016ec00-2397-11eb-8fc7-9b1aa1f609a8.png">

(The .219 IP address is the local machine.)

I'll send this pcap via mail, too.

**Comment by SipSeb** [comment]
Looks like it's a client problem. So I close this one for now.
