### ISSUE TITLE
 How much is the hardware requirement for the recordings?

### ISSUE THREAD

**Issue by malvarado611** [sipwise/rtpengine#1108]
I would appreciate if someone can tell me how much hardware is needed to install the recording system.

Regards,
Miguel Alvarado

**Comment by rfuchs** [comment]
It really depends on how many simultaneous recordings you plan to do and which codecs are involved. I don't have a hard number for you, but you should be able to handle at least several hundred simultaneous recordings on any moderately modern hardware.

**Comment by malvarado611** [comment]
Some minimal hardware required for the system. Just to know what hardware to buy.

**Comment by rfuchs** [comment]
There really is no minimal hardware requirement. You can run it on a Raspberry Pi if you wanted to. 🤷

**Comment by malvarado611** [comment]
Thanks You
