### ISSUE TITLE
No DTMF events are generated when --dtmf-log-dest is used.

### ISSUE THREAD

**Issue by sarumjanuch** [sipwise/rtpengine#1109]
Hi there! First of all Thanks a lot for all your work and effort you are putting into this amazing project. I love to read your code, I am actually learning C by reading it, so thanks for that. I was trying to play around with --dtmf-log-dest option, but have no any success. I am on version 8.4.2.0. I see that rtpengine is hooking up this option, and using strace, I can confirm that it calls connect to specified ip:port [over here](https://github.com/sipwise/rtpengine/blob/mr8.4.2/daemon/dtmf.c#L18) , but during the call it does not send any DTMF events information to socket, as well as I don't see them in logs . Maybe you can advice in which direction I should look for?  Edited (I was thinking I see them in logs, but those was SIP Info from Kamailio). I switched to using telephone-event, I can capture telephone events via sngrep, but can't capture any traffic on configured UDP server port. Also I checked my server, it works fine, as I can receive nc generated traffic.

**Comment by rfuchs** [comment]
What's your exact call setup? Are you using telephone-event natively from both peers, or is there any transcoding involved?

**Comment by rfuchs** [comment]
Can you share a debug log and a pcap?

**Comment by sarumjanuch** [comment]
I have send you link to google drive to rfuchs@sipwise.com, that includes pcap, debug.log and start command. If you need anything else, just let me know.

**Comment by rfuchs** [comment]
Is this a build with transcoding disabled?

**Comment by sarumjanuch** [comment]
That was something i was considering today, while reading the code, it
should not be, i asked our devops and they have swore that it is build with
transcoding and sent me this:
RTPENGINE_VERSION="\"%{version}-%{release}\"" with_transcoding=1 make. I
believe I should try to build my own version and retry, with my own hands
and eyes.

пн, 16 нояб. 2020 г. в 20:15, Richard Fuchs <notifications@github.com>:

**Comment by rfuchs** [comment]
`with_transcoding=1` would actually build without transcoding. The option should be set to `yes` (or just left at the default)

**Comment by sarumjanuch** [comment]
Thank you very much for your time and effort!

пн, 16 нояб. 2020 г. в 20:23, Richard Fuchs <notifications@github.com>:

**Comment by sarumjanuch** [comment]
https://github.com/sarumjanuch/node-rtpengine-ng If anyone would be
interested, i have refactored one of the nodejs libraries to work with
rtpengien, and also have added support for DTMF listener socket. Richard,
thanks for your help!

ср, 18 нояб. 2020 г. в 15:58, Sipwise Jenkins User <notifications@github.com

**Comment by rfuchs** [comment]
Nice work, thanks for the hint.

Since this is nodejs, you could also move it over to the new Websocket interface instead of UDP :smile:
