### ISSUE TITLE
Error parsing RTP header

### ISSUE THREAD

**Issue by caruizdiaz** [sipwise/rtpengine#111]
<pre>
[vvfk1s5cemi56odl9nq5 port 35052] Error parsing RTP header: invalid header version
</pre>

I get this when the request comes from FS, producing one way audio. 

I have limited access to sniffing the RTP flow. What else can I contribute to fix this problem?

**Comment by caruizdiaz** [comment]
More info: happens when activating media relay on RTP/AVP <-> RTP/AVP. 

RTP/AVP <-> RTP/SAVPF works alright.

**Comment by rfuchs** [comment]
Perhaps some other non-RTP traffic coming in on the port? But if this is AVP to AVP, then it shouldn't really matter. The RTP header is only parsed to keep stats on different payload types. Packets should be forwarded even if the header can't be parsed.

**Comment by caruizdiaz** [comment]
It only happens with AVP to AVP, and the audio isn't forwarded after the error.

**Comment by rfuchs** [comment]
You can look at the code yourself. The only call to rtp_payload() in a non-SRTP context is in call.c:721 and that's in an irrelevant conditional. You're probably looking at a different cause for not receiving audio.

**Comment by caruizdiaz** [comment]
Makes total sense. I'm gonna investigate that and reopen this ticket in case it's not an user error.
Thank you!
