### ISSUE TITLE
AMR decoding artifacts

### ISSUE THREAD

**Issue by kuleshov-aleksei** [sipwise/rtpengine#1112]
Hello!

### Problem description

I'm using recording-daemon for recording calls. When both sides of call have g711 recording file is fine, but when I'm switching to AMR I can get only highly-distorted audio. I even can't hear speech in this recordings. (I can provide recording samples if you want). 

Audio is distorted both in saved wav file and in tls endpoint.

I noticed that when using amr, `codeclib.c` uses [special media handling for amr](https://github.com/sipwise/rtpengine/blob/8ded0076da67a98bc5a4d1c9fc198f985b6c27af/lib/codeclib.c#L1791). I've tried to replace `amr_decoder_input` with `avc_decoder_input` [here](https://github.com/sipwise/rtpengine/blob/8ded0076da67a98bc5a4d1c9fc198f985b6c27af/lib/codeclib.c#L91) and I got less distorted audio. At least I can hear some words.

After a bit of debugging I found that every media sample have only 1 TOC, but after amr_decoder_input's conversion frame became 2x smaller.

Problem appears while using AMR and AMR-WB

Note that both members of call can hear each other, I got this problem only on recording.

I will appreciate if you can help me

### Software versions:

I've tried to use different ffmpeg versions:
Version from centos epel repo (v2.8.15)
Version built from current ffmpeg master with flags `--enable-libopencore-amrnb --enable-libopencore-amrwb`

I've found [this problem](https://trac.ffmpeg.org/ticket/232) and tried to add suggested flags:
Version built from current ffmpeg master with flags `--enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb`

Full configuration of ffmpeg: `--enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --disable-encoder=libopus --enable-libpulse --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libx264 --enable-libzvbi --enable-avfilter --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --enable-runtime-cpudetect --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb`

Rtpengine is build from master with latest commit c741d45cbac8b5dbfd1697a1f162cd2b1eb8ff3a and recording-daemon is also build from master, but with commit 9553af11dfad3a7794c58886dc3f0b2ee76d1843.

### Configuration

Rtpengine records packets using kernel module. Config of rtpengine:
```
[rtpengine]

table = 0

listen-ng = 2222
listen-tcp = 2222
listen-cli = 2223

timeout = 60
silent-timeout = 3600
tos = 184
port-min = 20000
port-max = 40000
interface = intnl/<my-ip>;extnl/<my-ip>
foreground = false
log-stderr = true
log-level = 6
log-facility = local0
log-facility-cdr = local0
log-facility-rtcp = local1

delete-delay = 5

recording-dir = /var/spool/rtpengine
recording-method = proc
recording-format = raw
```

Config of recording daemon:
```
[rtpengine-recording]

table = 0

tls-send-to = <ip:port-of-tls-endpoint>
tls-resample = 8000

output-storage = file
output-format = wav
resample-to = 8000
output-single = true

spool-dir = /var/spool/rtpengine
output-dir = /var/lib/rtpengine-recording
```

**Comment by kuleshov-aleksei** [comment]
After a bit of debugging, I've noticed that all media frames in TOC have F set to 0 and FT set to 0, that means that current packet have only 1 media packet with size of 95 bits, but incoming packet is always (in my case) 33 bytes (364 bits), that means that decoder does not receive huge part of data.

I got this information with simple loggin commands like here:
![image](https://user-images.githubusercontent.com/10367317/99684412-7e732800-2a92-11eb-8713-e810daf5ad0f.png)
Output:
```
handling parsed toc
FT in TOC = 0, bits = 95 
handling parsed toc
FT in TOC = 0, bits = 95
etc...
```

But if I look in traffic dump in wireshark, it becomes clear that media packet actually have FT = 7 - 244 bits per packet:

![image](https://user-images.githubusercontent.com/10367317/99684780-e45faf80-2a92-11eb-8f1b-1c5e64031283.png)

May be problem not in decoding packets but in sniffing packets dump from `/proc/rtpengine/0/calls/tag`?

**Comment by rfuchs** [comment]
Can you check if your AMR stream is in octet-aligned mode or in bandwidth-efficient mode? The `fmtp` in the SDP would tell you that.

**Comment by kuleshov-aleksei** [comment]
My stream is in octet-aligned mode. Here is sdp:
```
s=pjmedia
b=AS:29
t=0 0
a=X-nat:0
m=audio 29186 RTP/AVP 101 96
b=TIAS:12200
a=ssrc:322067289 cname:38d57e0b2bc512b3
a=rtpmap:101 telephone-event/8000
a=rtpmap:96 amr/8000
a=fmtp:101 0-16
a=fmtp:96 octet-align=1;mode-change-capability=2
a=sendrecv
a=rtcp:29187
```

But `dec->codec_options.amr.octet_aligned` is always equals to 0

**Comment by kuleshov-aleksei** [comment]
I've tried to set `dec->codec_options.amr.octet_aligned = 1;` before decoding (at start of `amr_decoder_input`) and it's works!
I will try to find where `octet_aligned` should be set to 1 and fix it in the right way

**Comment by rfuchs** [comment]
Right, that confirms my suspicion. The `fmtp` needs to be communicated to the recording daemon. Will have a fix shortly.

**Comment by kuleshov-aleksei** [comment]
Thank you very much!

**Comment by rfuchs** [comment]
See if a6022c9a works for you. Completely untested.

**Comment by kuleshov-aleksei** [comment]
Yes, this works! That was incredibly fast, thank you!
