### ISSUE TITLE
Very weird DTLS+ICE bridging problem when one UA has a VPN address

### ISSUE THREAD

**Issue by space88man** [sipwise/rtpengine#1115]
Scenario: 
1. UA1 to UA2 using rtpengine for DTLS+ICE bridging.
1. UAs are PJSIP.
1. UA1 has a VPN address by wireguard
1. No STUN/TURN used; "connectable" IP address is discovered by ICE as host/prflx

Note:
1. The caller UA always sends an UPDATE after INVITE/200 OK `sending UPDATE for updating ICE transport address after ICE negotiation`

Problems:
1. When UA1(VPN) calls UA2, call connects and media is exchanged. The port from rtpengine -> UA2 changes in UPDATE. But somehow rtpengine has remembered both ports, and for the original port (16720)

	ERR: [K3SQimQchQsNFz60rBLjZZyZ0lyq-S1i port 16720]: SRTP output wanted, but no crypto suite was negotiated
	ERR: SRTP output wanted, but no crypto suite was negotiated
	ERR: [K3SQimQchQsNFz60rBLjZZyZ0lyq-S1i port 16720]: SRTP output wanted, but no crypto suite was negotiated
	ERR: SRTP output wanted, but no crypto suite was negotiated
	ERR: [K3SQimQchQsNFz60rBLjZZyZ0lyq-S1i port 16720]: SRTP output wanted, but no crypto suite was negotiated
	ERR: [K3SQimQchQsNFz60rBLjZZyZ0lyq-S1i port 16720]: SRTP output wanted, but no crypto suite was negotiated
	ERR: SRTP output wanted, but no crypto suite was negotiated

2. When UA2 calls UA1(VPN), call connects and media is exchanged. The port from rtpengine -> UA2 changes in 200 OK(for the UPDATE). But somehow rtpengine has remembered both ports, and for the original port

	ERR: [ihjOFgUaydAZR6wAYRUY1SUwp9LB3C6T port 16786]: SRTCP output wanted, but no crypto suite was negotiated
	ERR: [ihjOFgUaydAZR6wAYRUY1SUwp9LB3C6T port 16786]: SRTCP output wanted, but no crypto suite was negotiated
	ERR: [ihjOFgUaydAZR6wAYRUY1SUwp9LB3C6T port 16786]: SRTCP output wanted, but no crypto suite was negotiated
	ERR: [ihjOFgUaydAZR6wAYRUY1SUwp9LB3C6T port 16786]: SRTCP output wanted, but no crypto suite was negotiated
	ERR: [ihjOFgUaydAZR6wAYRUY1SUwp9LB3C6T port 16786]: SRTCP output wanted, but no crypto suite was negotiated

Other information:
* if UA1 is bound to the VPN address, there are no ERR messages, port in UPDATE/200 OK does not change either as  caller or callee
* if UA1 is configured to use STUN and a single srflx candidate is added, there are no ERR messages
* if both UAs are not on VPN, there are no ERR messages
* if one UA is RTP/SAVP and rtpengine is bridging DTLS+ICE to RTP/SAVP there are no ERR messages

**Comment by space88man** [comment]
Problem 1: 

1. UA1 calls UA2, UA2 sees a changed port in UPDATE.
1. rtpengine complains about the original port.

SIP messages are from UA2(calle) POV:

INVITE sip:alice@10.13.20.1:38802;transport=TCP;ob SIP/2.0
Record-Route: <sip:example.com:5063;transport=tls;r2=on;lr;lr=on>
Via: SIP/2.0/TCP 10.13.20.15:5064;branch=z9hG4bKbc76.de9ba8345f25956c570045caeae65712.0;i=f4
Via: SIP/2.0/TLS 10.13.20.1:45878;received=10.13.20.1;rport=45878;branch=z9hG4bKPjtg9ndCrL2aBKjrlSSaO4LysKlZk15P4N;alias
Max-Forwards: 70
From: sip:mary@example.com;tag=7CRAzpmc2MHzxZ0GIxi-JQwaVpBtGkUp
To: sip:alice@example.com
Contact: <sip:mary@10.13.20.1:45878;transport=TLS;ob>;+sip.ice
Call-ID: K3SQimQchQsNFz60rBLjZZyZ0lyq-S1i
CSeq: 7622 INVITE
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Supported: replaces, 100rel, timer, norefersub
Session-Expires: 1800
Min-SE: 90
User-Agent: PJSUA v2.10-dev Linux-5.8.19.44/x86_64/glibc-2.32
Content-Type: application/sdp
Content-Length:   1583

v=0
o=- 3815039659 3815039659 IN IP4 192.168.1.7
s=pjmedia
b=AS:117
t=0 0
a=X-nat:0
m=audio 16720 UDP/TLS/RTP/SAVP 96 120
c=IN IP4 10.18.0.12
b=TIAS:96000
a=ssrc:1415018934 cname:422b11fd555c5b58
a=rtpmap:96 opus/48000/2
a=rtpmap:120 telephone-event/48000
a=fmtp:96 useinbandfec=1
a=fmtp:120 0-16
a=sendrecv
a=rtcp:16721
a=rtcp-mux
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:HgVFCj4Ohao3vGmjSwMxaiVaefizg2nlnXPHfoVb
a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:IGBrZDfSe8rrPmVnLBsJQSeaLIf7IJSMZ8CS3h0Z
a=crypto:3 AES_192_CM_HMAC_SHA1_80 inline:1wKtcA/+T5KNiKz3C12J7HF13HPsHOXisbUwxaFZDLAcymHqHeM
a=crypto:4 AES_192_CM_HMAC_SHA1_32 inline:LJ0BRuZ970I55V17EIXj/vklPdvBUWu9vldkvrAQIy0xXHg3WVM
a=crypto:5 AES_256_CM_HMAC_SHA1_80 inline:VOgcBKhLVz1MTQJJTHIH7HeF0gOkm9eQ1jCJe9SCkX6KwTHp+3JjiGBVUoTTVQ
a=crypto:6 AES_256_CM_HMAC_SHA1_32 inline:6IS+AJY0amvXlioj/G9L9dWMR5GMao0WxX+6yXjyI5hKZjglFqLoYi3eqbcrbw
a=crypto:7 F8_128_HMAC_SHA1_80 inline:jwdGwSpLhzehptSQxf5UkeUd7XvBinot1hffjsFR
a=crypto:8 F8_128_HMAC_SHA1_32 inline:nXMQP3aVkynfhNfAywCxYYUlAmvZ9uazScDKYK9C
a=crypto:9 NULL_HMAC_SHA1_80 inline:BSgdqAINRqaNgdOAoxfQhhMm4TUMDkdM+cnd1K2v
a=crypto:10 NULL_HMAC_SHA1_32 inline:uI7CNgsviTKfgdgCMKHOLBF0QBU1s0Ouxd3NA2+q
a=setup:actpass
a=fingerprint:sha-1 2B:7E:CE:55:E3:34:C9:CF:D9:A8:00:34:04:C5:2C:70:AE:8E:5F:12
a=ice-ufrag:YdXAYe5A
a=ice-pwd:74uCd5EdNkoDh0lMFWTY4fLuHq
a=candidate:5XFupX1gu4zM4Eht 1 UDP 2130706431 10.18.0.12 16720 typ host
a=candidate:5XFupX1gu4zM4Eht 2 UDP 2130706430 10.18.0.12 16721 typ host
m=video 0 RTP/AVP 31
c=IN IP4 10.18.0.12

SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.13.20.15:5064;received=10.18.0.12;branch=z9hG4bKbc76.de9ba8345f25956c570045caeae65712.0;i=f4
Via: SIP/2.0/TLS 10.13.20.1:45878;rport=45878;received=10.13.20.1;branch=z9hG4bKPjtg9ndCrL2aBKjrlSSaO4LysKlZk15P4N;alias
Record-Route: <sip:example.com:5063;transport=tls;lr;r2=on>
Call-ID: K3SQimQchQsNFz60rBLjZZyZ0lyq-S1i
From: <sip:mary@example.com>;tag=7CRAzpmc2MHzxZ0GIxi-JQwaVpBtGkUp
To: <sip:alice@example.com>;tag=MSND0U0phMDlRWyljB3yDdG58BDOLbnu
CSeq: 7622 INVITE
Contact: <sip:alice@10.13.20.1:38802;transport=TLS;ob>;+sip.ice
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Supported: replaces, 100rel, timer, norefersub
Session-Expires: 1800;refresher=uac
Require: timer
Content-Type: application/sdp
Content-Length:   658

v=0
o=- 3815039659 3815039660 IN IP4 192.168.12.42
s=pjmedia
b=AS:117
t=0 0
a=X-nat:1
m=audio 4005 UDP/TLS/RTP/SAVP 96 120
c=IN IP4 192.168.12.42
b=TIAS:96000
b=RS:0
b=RR:0
a=sendrecv
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
a=rtpmap:120 telephone-event/48000
a=fmtp:120 0-16
a=ssrc:274447857 cname:21f7833e76a3a987
a=ice-ufrag:50bf4f4c
a=ice-pwd:59af41433fb5267472b6d28a
a=candidate:Hc0a80c2a 1 UDP 2130706431 192.168.12.42 4005 typ host
a=rtcp-mux
a=setup:active
a=fingerprint:SHA-256 96:16:75:49:87:79:7E:08:C8:07:E5:9B:8B:F1:39:93:15:53:BC:58:33:48:00:26:F0:C7:B8:F5:94:85:B5:6C
m=video 0 RTP/AVP 31
c=IN IP4 10.18.0.12

UPDATE sip:alice@10.13.20.1:38802;transport=TCP;ob SIP/2.0
Via: SIP/2.0/TCP 10.13.20.15;branch=z9hG4bKcc76.ae44dc7ffee98de6c3f0de28ec744608.0;i=f4
Via: SIP/2.0/TLS 10.13.20.1:45878;received=10.13.20.1;rport=45878;branch=z9hG4bKPjGhEC6KILxmsNea.6kr59QyZbMXTzm7ec;alias
Max-Forwards: 70
From: sip:mary@example.com;tag=7CRAzpmc2MHzxZ0GIxi-JQwaVpBtGkUp
To: sip:alice@example.com;tag=MSND0U0phMDlRWyljB3yDdG58BDOLbnu
Contact: <sip:mary@10.13.20.1:45878;transport=TLS;ob>;+sip.ice
Call-ID: K3SQimQchQsNFz60rBLjZZyZ0lyq-S1i
CSeq: 7623 UPDATE
Supported: replaces, 100rel, timer, norefersub
Session-Expires: 1800;refresher=uac
Min-SE: 90
Content-Type: application/sdp
Content-Length:   1599

v=0
o=- 3815039659 3815039660 IN IP4 192.168.1.7
s=pjmedia
b=AS:117
t=0 0
a=X-nat:0
m=audio 16754 UDP/TLS/RTP/SAVP 96 120
c=IN IP4 10.18.0.12
b=TIAS:96000
b=RS:0
b=RR:0
a=ssrc:1415018934 cname:422b11fd555c5b58
a=rtpmap:96 opus/48000/2
a=rtpmap:120 telephone-event/48000
a=fmtp:96 useinbandfec=1
a=fmtp:120 0-16
a=sendrecv
a=rtcp:16755
a=rtcp-mux
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:HgVFCj4Ohao3vGmjSwMxaiVaefizg2nlnXPHfoVb
a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:IGBrZDfSe8rrPmVnLBsJQSeaLIf7IJSMZ8CS3h0Z
a=crypto:3 AES_192_CM_HMAC_SHA1_80 inline:1wKtcA/+T5KNiKz3C12J7HF13HPsHOXisbUwxaFZDLAcymHqHeM
a=crypto:4 AES_192_CM_HMAC_SHA1_32 inline:LJ0BRuZ970I55V17EIXj/vklPdvBUWu9vldkvrAQIy0xXHg3WVM
a=crypto:5 AES_256_CM_HMAC_SHA1_80 inline:VOgcBKhLVz1MTQJJTHIH7HeF0gOkm9eQ1jCJe9SCkX6KwTHp+3JjiGBVUoTTVQ
a=crypto:6 AES_256_CM_HMAC_SHA1_32 inline:6IS+AJY0amvXlioj/G9L9dWMR5GMao0WxX+6yXjyI5hKZjglFqLoYi3eqbcrbw
a=crypto:7 F8_128_HMAC_SHA1_80 inline:jwdGwSpLhzehptSQxf5UkeUd7XvBinot1hffjsFR
a=crypto:8 F8_128_HMAC_SHA1_32 inline:nXMQP3aVkynfhNfAywCxYYUlAmvZ9uazScDKYK9C
a=crypto:9 NULL_HMAC_SHA1_80 inline:BSgdqAINRqaNgdOAoxfQhhMm4TUMDkdM+cnd1K2v
a=crypto:10 NULL_HMAC_SHA1_32 inline:uI7CNgsviTKfgdgCMKHOLBF0QBU1s0Ouxd3NA2+q
a=setup:actpass
a=fingerprint:sha-1 2B:7E:CE:55:E3:34:C9:CF:D9:A8:00:34:04:C5:2C:70:AE:8E:5F:12
a=ice-ufrag:YdXAYe5A
a=ice-pwd:74uCd5EdNkoDh0lMFWTY4fLuHq
a=candidate:5XFupX1gu4zM4Eht 1 UDP 2130706431 10.18.0.12 16754 typ host
a=candidate:5XFupX1gu4zM4Eht 2 UDP 2130706430 10.18.0.12 16755 typ host
m=video 0 RTP/AVP 31
c=IN IP4 10.18.0.12

SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.13.20.15;received=10.18.0.12;branch=z9hG4bKcc76.ae44dc7ffee98de6c3f0de28ec744608.0;i=f4
Via: SIP/2.0/TLS 10.13.20.1:45878;rport=45878;received=10.13.20.1;branch=z9hG4bKPjGhEC6KILxmsNea.6kr59QyZbMXTzm7ec;alias
Call-ID: K3SQimQchQsNFz60rBLjZZyZ0lyq-S1i
From: <sip:mary@example.com>;tag=7CRAzpmc2MHzxZ0GIxi-JQwaVpBtGkUp
To: <sip:alice@example.com>;tag=MSND0U0phMDlRWyljB3yDdG58BDOLbnu
CSeq: 7623 UPDATE
Session-Expires: 1800;refresher=uac
Require: timer
Contact: <sip:alice@10.13.20.1:38802;transport=TLS;ob>;+sip.ice
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Supported: replaces, 100rel, timer, norefersub
Content-Type: application/sdp
Content-Length:   658

v=0
o=- 3815039659 3815039661 IN IP4 192.168.12.42
s=pjmedia
b=AS:117
t=0 0
a=X-nat:1
m=audio 4005 UDP/TLS/RTP/SAVP 96 120
c=IN IP4 192.168.12.42
b=TIAS:96000
b=RS:0
b=RR:0
a=sendrecv
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
a=rtpmap:120 telephone-event/48000
a=fmtp:120 0-16
a=ssrc:274447857 cname:21f7833e76a3a987
a=ice-ufrag:50bf4f4c
a=ice-pwd:59af41433fb5267472b6d28a
a=candidate:Hc0a80c2a 1 UDP 2130706431 192.168.12.42 4005 typ host
a=rtcp-mux
a=setup:active
a=fingerprint:SHA-256 96:16:75:49:87:79:7E:08:C8:07:E5:9B:8B:F1:39:93:15:53:BC:58:33:48:00:26:F0:C7:B8:F5:94:85:B5:6C
m=video 0 RTP/AVP 31
c=IN IP4 10.18.0.12
```

```

**Comment by space88man** [comment]
Problem 2: 

1. UA2 calls UA1(VPN), UA2 sees a changed port in 200 OK (for the UPDATE)
1. rtpengine complains about the original port and specifically about SRTCP.

SIP messages are from UA2(caller) POV:

```
```

**Comment by rfuchs** [comment]
Enable debug logging and post a full log please

**Comment by rfuchs** [comment]
Cleaning up old tickets
