### ISSUE TITLE
STUN issue - 401 Unauthorized

### ISSUE THREAD

**Issue by slavikbialik** [sipwise/rtpengine#1117]
Hi all,
I'm having an issue with making an outbound calls from my WebRTC client (SIP via web-socket). And I'm not sure if the issue is with the RTPEngine / Google Chrome or something else. Tried to investigated as far as I could and I have no additional ideas.

**This is my deployment:**
- SIP.js 0.17.1 client.
- Kamailio 5.4.2
- RTPEgine 9.1.1.1
- FreeSWITCH 1.10.5
- Google Chrome  87.0.4280.66

I'm using the default STUN server of Google that is pre-configured in SIP.js:
stun:stun.l.google.com:19302

What I'm experiencing is that one call out of 3-5 has no audio at all after connecting. I opened the Wireshark captures and I suddenly see that the failed calls are having bad responses to STUN requests:
`Binding Error Response error-code: 401 (Unauthorized) Unauthorized`

It starts by the RTPEngine sending my Bind request with the usernames from the INVITE & 200OK. And my client rejects it with 401 Unauthorized.

**Note**: On FireFox all calls are working smoothly without any STUN errors.

Here's the SIP messages of the INVITE and the 200 OK:

```
INVITE sip:+12126131234@userdomain.com SIP/2.0
Via: SIP/2.0/WSS userdomain.com;branch=z9hG4bK7461571
To: <sip:+12126131234@userdomain.com>
From: <sip:1000@userdomain.com>;tag=9bg940qpig
CSeq: 2 INVITE
Call-ID: gds8jj4l71uq1p4koeoj
Max-Forwards: 70
Proxy-Authorization: Digest algorithm=MD5, username="1000", realm="userdomain.com", nonce="ef37ead9-721f-4fa4-9bda-cf92a877a3fb", uri="sip:+12126131234@userdomain.com", response="022141f9d60c217aca5f03ec7e46edef", qop=auth, cnonce="cen53a7ar816", nc=00000001
Contact: <sip:vrk5u7ed@userdomain.com;transport=ws;ob>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: outbound
User-Agent: SIP.js/0.17.1
Content-Type: application/sdp
Content-Length: 1981

v=0
o=- 7795740338914485481 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic: WMS 963627f5-27d2-48cd-aa61-47073af43395
m=audio 57959 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 82.166.70.46
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:4020639172 1 udp 2122260223 172.18.48.1 57958 typ host generation 0 network-id 1
a=candidate:535800724 1 udp 2122194687 192.168.2.183 57959 typ host generation 0 network-id 2
a=ice-ufrag:Vb7w
a=ice-pwd:JVzcsKhzQ9tWy4SR/paNeR82
a=ice-options:trickle
a=fingerprint:sha-256 3D:D3:3B:8C:52:2D:9C:50:B4:1D:2C:E4:4D:0E:9A:F5:30:0F:CC:BB:FB:62:E7:2E:9B:D3:85:CA:1E:00:C1:8F
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:963627f5-27d2-48cd-aa61-47073af43395 c7945f5c-8e51-4087-bbf9-8abe5e714229
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:4013506923 cname:h5+lqmS+WrzQT02S
a=ssrc:4013506923 msid:963627f5-27d2-48cd-aa61-47073af43395 c7945f5c-8e51-4087-bbf9-8abe5e714229
a=ssrc:4013506923 mslabel:963627f5-27d2-48cd-aa61-47073af43395
a=ssrc:4013506923 label:c7945f5c-8e51-4087-bbf9-8abe5e714229






SIP/2.0 200 OK
Via: SIP/2.0/WSS userdomain.com;rport=53237;received=192.168.2.183;branch=z9hG4bK7461571
Record-Route: <sip:192.168.40.60:5060;transport=tcp;r2=on;lr=on;ftag=9bg940qpig;rtp=bridge;rtp=ws>
Record-Route: <sip:0.0.0.0:8443;transport=ws;r2=on;lr=on;ftag=9bg940qpig;rtp=bridge;rtp=ws>
From: <sip:1000@userdomain.com>;tag=9bg940qpig
To: <sip:+12126131234@userdomain.com>;tag=6ccXj8DUXt68r
Call-ID: gds8jj4l71uq1p4koeoj
CSeq: 2 INVITE
Contact: <sip:+12126131234@192.168.40.60:5081;transport=tcp>
User-Agent: FreeSWITCH-mod_sofia/1.10.5-release+git~20200818T185121Z~25569c1631~64bit
Accept: application/sdp
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
Supported: timer, path, replaces
Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
Content-Type: application/sdp
Content-Disposition: session
Content-Length: 586
Remote-Party-ID: "+12126131234" <sip:+12126131234@userdomain.com>;party=calling;privacy=off;screen=no

v=0
o=FreeSWITCH 1606275903 1606275904 IN IP4 192.168.40.60
s=FreeSWITCH
c=IN IP4 192.168.40.60
t=0 0
m=audio 23000 RTP/SAVPF 0 126
a=mid:0
a=rtpmap:0 PCMU/8000
a=rtpmap:126 telephone-event/8000
a=fmtp:126 0-16
a=sendrecv
a=rtcp:23000
a=rtcp-mux
a=setup:active
a=fingerprint:sha-256 8F:A0:AE:5F:66:13:06:EA:99:FE:EF:AA:22:8E:AA:67:80:87:9E:01:A4:03:59:5B:97:9D:3F:4C:1A:3A:F8:B1
a=ptime:20
a=ice-ufrag:oALQC1zL
a=ice-pwd:JdeNaPFOn2bZfwmB6ae6QHp5g5
a=ice-options:trickle
a=candidate:k0iQgeFqzPvIhsF6 1 UDP 2130706431 192.168.40.60 23000 typ host
a=end-of-candidates
```

**Here are the RTPEngine logs:**

```
[1606235131.226249] NOTICE: [h427ogt2itctmh2rv94c]: Creating new call
[1606235131.227221] INFO: [h427ogt2itctmh2rv94c]: Replying to 'offer' from 172.20.0.2:33808 (elapsed time 0.001297 sec)
[1606235131.230046] INFO: [h427ogt2itctmh2rv94c port 23000]: ICE negotiated: peer for component 1 is 192.168.2.183:57604
[1606235131.230066] INFO: [h427ogt2itctmh2rv94c port 23000]: ICE negotiated: local interface 172.20.0.2
[1606235131.230850] INFO: [h427ogt2itctmh2rv94c]: Received command 'delete' from 172.20.0.2:42779
[1606235131.231075] INFO: [h427ogt2itctmh2rv94c]: Deleting call branch '' (via-branch 'z9hG4bK94963300')
[1606235131.231110] INFO: [h427ogt2itctmh2rv94c]: Call branch '' (via-branch 'z9hG4bK94963300') deleted, no more branches remaining
[1606235131.231270] INFO: [h427ogt2itctmh2rv94c]: Deleting entire call
[1606235131.231286] INFO: [h427ogt2itctmh2rv94c]: Final packet stats:
[1606235131.231470] INFO: [h427ogt2itctmh2rv94c]: --- Tag 'r22obscju9', created 0:00 ago for branch '', in dialogue with ''
[1606235131.231693] INFO: [h427ogt2itctmh2rv94c]: ------ Media #1 (audio over UDP/TLS/RTP/SAVPF) using unknown codec
[1606235131.231855] INFO: [h427ogt2itctmh2rv94c]: --------- Port      172.20.0.2:23000 <>   192.168.2.183:57604, SSRC 0, 1 p, 64 b, 0 e, 0 ts
[1606235131.231869] INFO: [h427ogt2itctmh2rv94c]: --- Tag '', created 0:00 ago for branch 'z9hG4bK94963300', in dialogue with 'r22obscju9'
[1606235131.232003] INFO: [h427ogt2itctmh2rv94c]: ------ Media #1 (audio over RTP/AVP) using unknown codec
[1606235131.232020] INFO: [h427ogt2itctmh2rv94c]: --------- Port      172.20.0.2:23022 <>                :0    , SSRC 0, 0 p, 0 b, 0 e, 0 ts
[1606235131.232179] INFO: [h427ogt2itctmh2rv94c]: --------- Port      172.20.0.2:23023 <>                :0     (RTCP), SSRC 0, 0 p, 0 b, 0 e, 0 ts
[1606235131.232389] INFO: [h427ogt2itctmh2rv94c]: Replying to 'delete' from 172.20.0.2:42779 (elapsed time 0.001505 sec)
[1606235131.278390] INFO: [h427ogt2itctmh2rv94c]: Received command 'offer' from 172.20.0.2:33808
[1606235131.278476] NOTICE: [h427ogt2itctmh2rv94c]: Creating new call
[1606235131.279462] INFO: [h427ogt2itctmh2rv94c]: Replying to 'offer' from 172.20.0.2:33808 (elapsed time 0.001041 sec)
[1606235131.280939] NOTICE: [h427ogt2itctmh2rv94c port 23000]: Received invalid STUN packet from 192.168.2.183:57604: MESSAGE_INTEGRITY attribute missing
[1606235131.612861] INFO: [h427ogt2itctmh2rv94c]: Received command 'answer' from 172.20.0.2:42779
[1606235131.613228] INFO: [h427ogt2itctmh2rv94c]: Replying to 'answer' from 172.20.0.2:42779 (elapsed time 0.000343 sec)
[1606235131.680620] ERR: [h427ogt2itctmh2rv94c port 23020]: SRTP output wanted, but no crypto suite was negotiated
[1606235135.000280] INFO: [h427ogt2itctmh2rv94c port 23020]: Confirmed peer address as 172.20.0.1:44529
[1606235135.371619] INFO: [h427ogt2itctmh2rv94c]: Received command 'answer' from 172.20.0.2:42779
[1606235135.372115] INFO: [h427ogt2itctmh2rv94c]: Replying to 'answer' from 172.20.0.2:42779 (elapsed time 0.000447 sec)
[1606235139.019185] INFO: [h427ogt2itctmh2rv94c port 23020]: Confirmed peer address as 172.20.0.1:44529
[1606235146.019173] ERR: [h427ogt2itctmh2rv94c port 23020]: SRTP output wanted, but no crypto suite was negotiated
```
As you can see, I have an error stating:
`[1606235131.280939] NOTICE: [h427ogt2itctmh2rv94c port 23000]: Received invalid STUN packet from 192.168.2.183:57604: MESSAGE_INTEGRITY attribute missing`

Here's the Wireshark capture (filtered to show only DTLS & STUN traffic)
[wireshark-stun-issue.zip](https://github.com/sipwise/rtpengine/files/5597066/wireshark-stun-issue.zip)
IPs:

- 192.168.40.60 - Kamailio + RTPEngine
- 192.168.2.183 - My PC running the WebRTC client.

I an not a guru in all of those STUN/TURN/ICE matters... I know a little bit.. and I really hope you can see here something that I am missing. Although it happens only on Google Chrome, so it might be a bug with Google's WebRTC SDK or something like that.
Please tell me if you need me to provide any additional logs.

Thanks!

**Comment by rfuchs** [comment]
It might be related to the initial offer/delete that it shows in your log. If there's only one invite and one 200 OK, why is there an offer/delete before the expected offer/answer?

The first binding request from rtpengine (packet 3) is successful. It shows a different username fragment than what's in your SDP though: `YIZHDy2C` instead of `oALQC1zL`. Subsequent binding requests use `oALQC1zL` as it shows in the SDP and those are rejected. I'm guessing the the first username fragment was generated from the first offer, then the call is deleted and destroyed, then re-created again, but since it's now a new call a new username fragment is created.

So I suggest you check your signalling logic and find out why there is this extraneous offer/delete/offer going on.

**Comment by slavikbialik** [comment]
> The first binding request from rtpengine (packet 3) is successful. It shows a different username fragment than what's in your SDP though: `YIZHDy2C` instead of `oALQC1zL`. Subsequent binding requests use `oALQC1zL` as it shows in the SDP and those are rejected. I'm guessing the the first username fragment was generated from the first offer, then the call is deleted and destroyed, then re-created again, but since it's now a new call a new username fragment is created.

Thanks for the reply!
This is a strange case, because all of the calls are the same (same destination) and going the in the same signaling path.
What are the chances that the re-creation of the call can occur as a result of doing an authentication of the INVITE? Meaning I'm sending an initial INVITE which is rejected by FreeSWITCH with 407 message, then sending again an INVITE with the authorization information like nonce and all. Can something like that trigger it?
Another thing I'm doing with the call is that when it is being answered, I'm conferencing immediately both legs of the call into a FreeSWITCH conference. But as far as I recall, it is not something that Kamailio (and RTPEngine) "sees".

Thanks.

**Comment by rfuchs** [comment]
The chances are either 0% or 100%, depending on how you've set up the signalling :smile: 

But from the logs and the pcap, I'd say that the output of the original invite was delivered to the remote peer, and that would mean that it wasn't rejected with a 407.

**Comment by slavikbialik** [comment]
> But from the logs and the pcap, I'd say that the output of the original invite was delivered to the remote peer, and that would mean that it wasn't rejected with a 407.

Yeah, the SIP output in the original post is lacking the original INVITE and the 407 rejection. I pasted it only after the second INVITE went out. 😅

Also, is there a chance it has to do something with how I set the RTPEngine flags on Kamailio config? 
```
                if ($proto =~ "ws") { # web --> SIP
                        $xavp(r=>$T_branch_idx) = $xavp(r=>$T_branch_idx) + " rtcp-mux-demux generate-mid DTLS=off ICE=remove RTP/AVP";
                } else { # SIP --> web
                        $xavp(r=>$T_branch_idx) = $xavp(r=>$T_branch_idx) + " rtcp-mux-offer generate-mid DTLS=active SDES-off ICE=force RTP/SAVPF";
                }
```

The call flow is;
SIP.js client --- (#1 SIP via web socket) ----> Kamailio (+RTPEngine) ---(#2 SIP)---> FreeSWITCH ----- (SIP) -----> PSTN
While:
#1 - is SIP via Web Socket and DTLS is being used for media towards RTPEngine.
#2 - SIP (non-secured) with RTP (non secured) towards FreeSWITCH.

**Comment by rfuchs** [comment]
No, the flags have nothing to do with it.

Something in your Kamailio script is triggering a delete towards rtpengine (either from an explicit `rtpengine_delete` or from `rtpengine_manage` when called during a relevant event route). Find out what that is.

**Comment by slavikbialik** [comment]
> No, the flags have nothing to do with it.
> 
> Something in your Kamailio script is triggering a delete towards rtpengine (either from an explicit `rtpengine_delete` or from `rtpengine_manage` when called during a relevant event route). Find out what that is.

Thanks! I checked it, and it seems I'm getting some BRANCH FAILED error which leads me to this section of the script. 
Can you please tell me what is this event route and what can lead to this event route type (`tm:branch-failure:rtpengine`) to be triggered?
Because all of my calls are getting to this section, but not all calls are having the audio issue. So I'm assuming that I'm experiencing some race conditions or something like that.
By the way, when I delete the `rtpengine_delete` commands, the issue not occurs, although I think I'm experiencing a 1 second delay until the audio starts.

```
event_route[tm:branch-failure:rtpengine] {
	xlog("L_INFO", "BRANCH FAILED: $sel(via[1].branch) + $T_branch_idx");

#!ifdef WITH_BRIDGE_ON_FAIL
	if (!isbflagset(FLB_BRIDGE) && t_check_status("415|488")) {
		t_reuse_branch();
		setbflag(FLB_BRIDGE);
		xlog("L_INFO", "event_route[branch-failure:rtpengine]: trying again\n");

		route(RELAY);
	} else {
		$avp(extra_id) = @via[1].branch + $T_branch_idx;
		rtpengine_delete("via-branch=extra");
		xlog("L_INFO", "event_route[branch-failure:rtpengine]: failed\n");
	}
#!else
	$avp(extra_id) = @via[1].branch + $T_branch_idx;
	rtpengine_delete("via-branch=extra");
#!endif
}
```

Thanks again! :)

**Comment by slavikbialik** [comment]
Oh, and if it helps, here are the Kamailio + RTPEngine logs of a call that couldn't establish audio:

```
13(276) INFO: <script>: START: INVITE from sip:1000@userdomain.com (IP:192.168.2.183:51506)
13(276) INFO: <script>: MANAGE_BRANCH: New branch [0] to sip:+12126131234@userdomain.com
13(276) INFO: <script>: NATMANAGE branch_id:0 ruri: sip:+12126131234@userdomain.com, method:INVITE, status:<null>, extra_id: z9hG4bK62671740, rtpengine_manage: replace-origin replace-session-connection trust-address via-branch=extra rtcp-mux-demux generate-mid DTLS=off ICE=remove RTP/AVP
[1606643533.277602] INFO: [9id6r8g452s7kiiq4q13]: Received command 'offer' from 172.29.0.2:40402
[1606643533.277926] NOTICE: [9id6r8g452s7kiiq4q13]: Creating new call
[1606643533.278839] INFO: [9id6r8g452s7kiiq4q13]: Replying to 'offer' from 172.29.0.2:40402 (elapsed time 0.001107 sec)
[1606643533.280799] INFO: [9id6r8g452s7kiiq4q13 port 23000]: ICE negotiated: peer for component 1 is 192.168.2.183:59894
[1606643533.280815] INFO: [9id6r8g452s7kiiq4q13 port 23000]: ICE negotiated: local interface 172.29.0.2
14(277) INFO: <script>: BRANCH FAILED: z9hG4bK6267174 + 0[1606643533.407851] INFO: [9id6r8g452s7kiiq4q13]: Received command 'delete' from 172.29.0.2:53995
[1606643533.408052] INFO: [9id6r8g452s7kiiq4q13]: Deleting call branch '' (via-branch 'z9hG4bK62671740')
[1606643533.408182] INFO: [9id6r8g452s7kiiq4q13]: Call branch '' (via-branch 'z9hG4bK62671740') deleted, no more branches remaining
[1606643533.408239] INFO: [9id6r8g452s7kiiq4q13]: Deleting entire call
[1606643533.408369] INFO: [9id6r8g452s7kiiq4q13]: Final packet stats:
[1606643533.408385] INFO: [9id6r8g452s7kiiq4q13]: --- Tag '2iuqbkq1mf', created 0:00 ago for branch '', in dialogue with ''
[1606643533.408396] INFO: [9id6r8g452s7kiiq4q13]: ------ Media #1 (audio over UDP/TLS/RTP/SAVPF) using unknown codec
[1606643533.408410] INFO: [9id6r8g452s7kiiq4q13]: --------- Port      172.29.0.2:23000 <>   192.168.2.183:59894, SSRC 0, 1 p, 64 b, 0 e, 0 ts
[1606643533.408522] INFO: [9id6r8g452s7kiiq4q13]: --- Tag '', created 0:00 ago for branch 'z9hG4bK62671740', in dialogue with '2iuqbkq1mf'
[1606643533.408552] INFO: [9id6r8g452s7kiiq4q13]: ------ Media #1 (audio over RTP/AVP) using unknown codec
[1606643533.408712] INFO: [9id6r8g452s7kiiq4q13]: --------- Port      172.29.0.2:23018 <>                :0    , SSRC 0, 0 p, 0 b, 0 e, 0 ts
[1606643533.408800] INFO: [9id6r8g452s7kiiq4q13]: --------- Port      172.29.0.2:23019 <>                :0     (RTCP), SSRC 0, 0 p, 0 b, 0 e, 0 ts
[1606643533.408969] INFO: [9id6r8g452s7kiiq4q13]: Replying to 'delete' from 172.29.0.2:53995 (elapsed time 0.001081 sec)
14(277) INFO: <script>: Failure: <null>13(276) INFO: <script>: START: ACK from sip:1000@userdomain.com (IP:192.168.2.183:51506)
13(276) INFO: <script>: START: INVITE from sip:1000@userdomain.com (IP:192.168.2.183:51506)
13(276) INFO: <script>: MANAGE_BRANCH: New branch [0] to sip:+12126131234@userdomain.com
13(276) INFO: <script>: NATMANAGE branch_id:0 ruri: sip:+12126131234@userdomain.com, method:INVITE, status:<null>, extra_id: z9hG4bK38571220, rtpengine_manage: replace-origin replace-session-connection trust-address via-branch=extra rtcp-mux-demux generate-mid DTLS=off ICE=remove RTP/AVP
[1606643533.415550] INFO: [9id6r8g452s7kiiq4q13]: Received command 'offer' from 172.29.0.2:40402
[1606643533.415743] NOTICE: [9id6r8g452s7kiiq4q13]: Creating new call
[1606643533.416447] INFO: [9id6r8g452s7kiiq4q13]: Replying to 'offer' from 172.29.0.2:40402 (elapsed time 0.000870 sec)
[1606643533.418141] NOTICE: [9id6r8g452s7kiiq4q13 port 23000]: Received invalid STUN packet from 192.168.2.183:59894: MESSAGE_INTEGRITY attribute missing
14(277) INFO: <script>: NATMANAGE branch_id:0 ruri: <null>, method:INVITE, status:100, extra_id: 0, rtpengine_manage: replace-origin replace-session-connection trust-address via-branch=extra rtcp-mux-offer generate-mid DTLS=active SDES-off ICE=force RTP/SAVPF
15(278) INFO: <script>: START: NOTIFY from sip:1000@userdomain.com (IP:172.29.0.1:60624)
14(277) INFO: <script>: NATMANAGE branch_id:0 ruri: <null>, method:INVITE, status:183, extra_id: z9hG4bK38571220, rtpengine_manage: replace-origin replace-session-connection via-branch=extra rtcp-mux-offer generate-mid DTLS=active SDES-off ICE=force RTP/SAVPF
[1606643533.982120] INFO: [9id6r8g452s7kiiq4q13]: Received command 'answer' from 172.29.0.2:53995
[1606643533.982408] INFO: [9id6r8g452s7kiiq4q13]: Replying to 'answer' from 172.29.0.2:53995 (elapsed time 0.000273 sec)
[1606643534.033399] ERR: [9id6r8g452s7kiiq4q13 port 23018]: SRTP output wanted, but no crypto suite was negotiated
[1606643537.012865] INFO: [9id6r8g452s7kiiq4q13 port 23018]: Confirmed peer address as 172.29.0.1:42156
15(278) INFO: <script>: NATMANAGE branch_id:0 ruri: <null>, method:INVITE, status:200, extra_id: z9hG4bK38571220, rtpengine_manage: replace-origin replace-session-connection via-branch=extra rtcp-mux-offer generate-mid DTLS=active SDES-off ICE=force RTP/SAVPF
[1606643546.038443] INFO: [9id6r8g452s7kiiq4q13]: Received command 'answer' from 172.29.0.2:49738
[1606643546.038576] INFO: [9id6r8g452s7kiiq4q13]: Replying to 'answer' from 172.29.0.2:49738 (elapsed time 0.000114 sec)
12(275) INFO: <script>: START: NOTIFY from sip:1000@userdomain.com (IP:172.29.0.1:60624)
13(276) INFO: <script>: START: ACK from sip:1000@userdomain.com (IP:192.168.2.183:51506)
13(276) INFO: <script>: NATMANAGE branch_id:0 ruri: sip:+12126131234@192.168.40.60:5081;transport=tcp, method:ACK, status:<null>, extra_id: <null>, rtpengine_manage: replace-origin replace-session-connection trust-address rtcp-mux-demux generate-mid DTLS=off ICE=remove RTP/AVP
13(276) INFO: <script>: START: SUBSCRIBE from sip:1000@userdomain.com (IP:192.168.2.183:51506)
13(276) INFO: <script>: MANAGE_BRANCH: New branch [0] to sip:9id6r8g452s7kiiq4q13@userdomain.com
13(276) INFO: <script>: NATMANAGE branch_id:0 ruri: sip:9id6r8g452s7kiiq4q13@userdomain.com, method:SUBSCRIBE, status:<null>, extra_id: z9hG4bK80687120, rtpengine_manage: replace-origin replace-session-connection trust-address via-branch=extra rtcp-mux-demux generate-mid DTLS=off ICE=remove RTP/AVP
14(277) INFO: <script>: NATMANAGE branch_id:0 ruri: <null>, method:SUBSCRIBE, status:202, extra_id: z9hG4bK80687120, rtpengine_manage: replace-origin replace-session-connection trust-address via-branch=extra rtcp-mux-offer generate-mid DTLS=active SDES-off ICE=force RTP/SAVPF
12(275) INFO: <script>: START: NOTIFY from sip:9id6r8g452s7kiiq4q13@userdomain.com (IP:172.29.0.1:60696)
[1606643549.017727] ERR: [9id6r8g452s7kiiq4q13 port 23018]: SRTP output wanted, but no crypto suite was negotiated
[1606643550.017767] INFO: [9id6r8g452s7kiiq4q13 port 23018]: Confirmed peer address as 172.29.0.1:42156
```

**Comment by slavikbialik** [comment]
Hi @rfuchs 
I am still experiencing the same issue. I found that because of the following log:
`[1606235131.280939] NOTICE: [h427ogt2itctmh2rv94c port 23000]: Received invalid STUN packet from 192.168.2.183:57604: MESSAGE_INTEGRITY attribute missing`

It reaches to this line of code:
https://github.com/sipwise/rtpengine/blob/6431cde15143e890351494cdf1c67b26a19a78c4/daemon/stun.c#L597

As far as I understand from the code itself, is that it might not parsing correctly (sometimes) the attribute and it's hash value? Tried to follow the code itself where it parse it and looks for the relevant bytes indexes but I really lost it, heh.
Can you PLEASE give another look on my Wireshark capture and see if it could happen there? Frustrated already, working on this for 2 weeks and can't find a solution. 

Thanks!

**Comment by rfuchs** [comment]
There are STUN requests without the required message-integrity attribute in your pcap. These are not valid ICE STUN requests, and I can only guess that they're from non-ICE TURN/STUN services. These are ignored by rtpengine for ICE purposes, so I don't see a problem there.

If you can't figure out where the stray delete comes from or how to suppress it, you can try using a non-zero delete-delay in your config, because this is exactly what the delete-delay exists for.

**Comment by slavikbialik** [comment]
> There are STUN requests without the required message-integrity attribute in your pcap. These are not valid ICE STUN requests, and I can only guess that they're from non-ICE TURN/STUN services. These are ignored by rtpengine for ICE purposes, so I don't see a problem there.
> 
> If you can't figure out where the stray delete comes from or how to suppress it, you can try using a non-zero delete-delay in your config, because this is exactly what the delete-delay exists for.

Thanks for looking again, I really appreciate it!
Can please you point me to the packet number of those invalid ICE STUN requests? 
This capture is actually from the PC side, so you might see a STUN requests towards Google's STUN server (packet no. 1), or are you talking about the STUN responses that 192.168.2.183 is replying (with Unauthorized and Bad Request)?
192.168.2.183 - WebRTC client.
192.168.40.60 (Kamailio + RTPEngine)

Regarding the `MESSAGE_INTEGRITY attribute missing` error I'm getting from RTPEngine, it happens ONLY when the STUN issue occurs and observed on Wireshark. When there's a call that has no audio and STUN issues, we do not see this error from RTPEngine. That's why I can't really understand which invalid STUN packet can cause this, because all the requests have MESSAGE INTEGRITY attribute as far as I see.
So it might be some race condition that you suggest to make a delayed delete?

And the strange part is also that the 401 Unauthorized is being replied by the WebRTC client (192.168.2.183), not the RTPEngine. Which make me also think that there are cases where RTPEngine calculating wrong HMAC-SHA1 hash and sending it towards the WebRTC client which rejects it with 401 Unauthorized.

Thanks again! Very much appreciated!

**Comment by rfuchs** [comment]
In your capture for example packets 1, 27, 32, 58, 63, etc. These look like regular non-ICE STUN requests.

And the issue as what I explained before: The stray "delete" you're sending is destroying the internal call state, and the subsequent "offer" creates a new call with new internal details, while the client remained in the original state and expecting the details (ICE credentials) generated from the original offer. It's not a race condition, it's not calculating wrong hashes, and it's not parsing the STUN packets wrong. It's just that you're sending a delete when you shouldn't. Using a delete-delay would keep the call open after a delete and so keep the internal call state intact until the next offer comes in.

**Comment by slavikbialik** [comment]
> In your capture for example packets 1, 27, 32, 58, 63, etc. These look like regular non-ICE STUN requests.
> 
> And the issue as what I explained before: The stray "delete" you're sending is destroying the internal call state, and the subsequent "offer" creates a new call with new internal details, while the client remained in the original state and expecting the details (ICE credentials) generated from the original offer. It's not a race condition, it's not calculating wrong hashes, and it's not parsing the STUN packets wrong. It's just that you're sending a delete when you shouldn't. Using a delete-delay would keep the call open after a delete and so keep the internal call state intact until the next offer comes in.

Thanks!
Those packets you've mentioned are not actually arriving RTPEngine. So the RTPEngine is probably not alerting the error because of those packets as they're only on PC (WebRTC client) side.

Regarding the rest of the explanation, thanks, it is much more clear now. I will try it tomorrow and hopefully it'll solve this thing.
Hope that `delete-delay=1` will suffice. 
I tried also to understand from Kamailio's config / SIP signaling why I always see 2 call creation for each call (like you have mentioned in the beginning of this post), but can't find why it happens. I assume it is not a normal behavior, right?

**Comment by rfuchs** [comment]
> Those packets you've mentioned are not actually arriving RTPEngine. So the RTPEngine is probably not alerting the error because of those packets as they're only on PC (WebRTC client) side.

In that case it might actually be complaining about the 401 error replies, as those also don't contain a message-integrity attribute.

> I tried also to understand from Kamailio's config / SIP signaling why I always see 2 call creation for each call (like you have mentioned in the beginning of this post), but can't find why it happens. I assume it is not a normal behavior, right?

That really depends on your routing logic and how your Kamailio script is set up. If you're calling the rtpengine functions from the wrong places, then you might get the behaviour you see. Also if you're doing call forking and aren't dealing with the branches properly.

**Comment by slavikbialik** [comment]
> > Those packets you've mentioned are not actually arriving RTPEngine. So the RTPEngine is probably not alerting the error because of those packets as they're only on PC (WebRTC client) side.
> 
> In that case it might actually be complaining about the 401 error replies, as those also don't contain a message-integrity attribute.
> 
> > I tried also to understand from Kamailio's config / SIP signaling why I always see 2 call creation for each call (like you have mentioned in the beginning of this post), but can't find why it happens. I assume it is not a normal behavior, right?
> 
> That really depends on your routing logic and how your Kamailio script is set up. If you're calling the rtpengine functions from the wrong places, then you might get the behaviour you see. Also if you're doing call forking and aren't dealing with the branches properly.

Yes, unfortunately I do not have enough experience with fully understanding the Kamailio config and mostly the branches part. I'm only few months using it, and I used some config file I found on the Internet that is already compatible with handling WebRTC and just modified part of it according to what I need.
Here's my full config:
[Kamailio config](https://gist.github.com/slavikbialik/f8b360184be31dbc55a3eb604ac6cb4e)

Tell you the truth, I still cannot grasp the idea of how to work with branches and can't really find a theoretical explanations on Kamailio's documentation about it to learn it.
Sorry for being a newbie here, but this is where I currently stand for now 😅

**Comment by sarumjanuch** [comment]
@slavikbialik There is a good book: SIP: Understanding the Session Initiation Protocol, which you could buy and read to get to get solid base of your SIP knowledge. Also, Daniel (lead Kamailio developer and maintainer), has wrote an amazing book: https://www.asipto.com/sw/kamailio-admin-book/, which I strongly advice you to buy, as an act of appreciation of all his work and effort that he had invested into the Kamailio, and made available as open source. After reading it, you will literally open your eyes on Kamailio, it explains a lot, but requires you to to be at least familiar with SIP core concepts. Here is good set of blog posts that can quickly introduce you to core concepts in SIP: https://thanhloi2603.wordpress.com/category/sip.

**Comment by slavikbialik** [comment]
> @slavikbialik There is a good book: SIP: Understanding the Session Initiation Protocol, which you could buy and read to get to get solid base of your SIP knowledge. Also, Daniel (lead Kamailio developer and maintainer), has wrote an amazing book: https://www.asipto.com/sw/kamailio-admin-book/, which I strongly advice you to buy, as an act of appreciation of all his work and effort that he had invested into the Kamailio, and made available as open source. After reading it, you will literally open your eyes on Kamailio, it explains a lot, but requires you to to be at least familiar with SIP core concepts. Here is good set of blog posts that can quickly introduce you to core concepts in SIP: https://thanhloi2603.wordpress.com/category/sip.

Thanks! I'm actually thinking of buying Kamailio's admin book. Because the knowledge I'm lacking here is in Kamailio, not in SIP (unless this book is also covering WebRTC subjects like STUN + ICE + TURN which I am kind of new to it).

Anyway I solved this issue today. Thanks to @rfuchs and his guidance. 
What happened is that I have call authentication enabled on FreeSWITCH for every outbound call, so FreeSWITCH always responds with 407. When Kamailio got this 407 error, the routing script deciding to "delete" the call. That's why we always saw 2 calls, because the initial INVITE create the 1st call and the 2nd INVITE with the authentication itself created the second call.
So in the `event_route[tm:branch-failure:rtpengine]` block I just added a main IF condition that first checks that the reply error is NOT 407 and that it is not related to INVITE, and if it's not only then it'll delete the call. 
I actually tried the `delete-delay=3` command, and it also worked. But now seems like I solved the root issue.

Thanks!!!

**Comment by sarumjanuch** [comment]
@slavikbialik WebRTC is a huge topic that is far beyond the scope of Kamailio book. Kamailio is SIP proxy and SIP has nothing to do with WebRTC even despite the fact that you can create SIP signaling around WebRTC API.
