### ISSUE TITLE
Error with Cipher Key lenght?

### ISSUE THREAD

**Issue by rmartinezredvoiss** [sipwise/rtpengine#1119]
Hi.
I'm using RTPENGINE with OPENSIPS  to transform from a SRTP to RTP
When the SRTP offer came from my UAC indicates:

**a=crypto:1 AES_256_CM_HMAC_SHA1_80 inline:dVwYFc1ARkmoeVkPN9JdKXYbJHEA1womGZ3X4gvs3rGZHQew3AaHURWjvO6YtA==**
a=crypto:2 AES_256_CM_HMAC_SHA1_32 inline:oSgNVYgBtcnf9/tRduZ/3LUgTwqQMfUsOyQcZutOAnBhb+kOdtLN/o6Ezt/e/Q==
a=crypto:3 AES_CM_128_HMAC_SHA1_80 inline:PEwsve6fAIxUVHbBnhLZb303atLbFpw193GkTn/Q
a=crypto:4 AES_CM_128_HMAC_SHA1_32 inline:XRtaI0RO1Sfhaf8ZstLX5eRUF07y0vIcv9iAOVhC
a=sendrecv

and when my RTPENGINE answer to this offer i have:
**a=crypto:1 AES_256_CM_HMAC_SHA1_80 inline:mObON802Wis2GH0puTCaOznh7as+BTpu1IBZAzNcocQFn95N9YGuZRZ7dNWcyA**

I'm not an expert in key and cipher method... but my endpoint is sending an error like:
2020-11-25 16:45:20.755 | DEBUG | 104875 RemoteParticipant::adjustRTPStreams(): Crypto Suite: SRTP_AES_256_CM_HMAC_SHA1_80 Cipher Key Length: 46 SDP Cipher Key Length: 45
2020-11-25 16:45:20.755 | INFO | 104875 RemoteParticipant::adjustRTPStreams(): SDES crypto key found in SDP, but is not of correct length after base 64 decode: 45, should be: 46

Could be that the Cipher key lenght of the RTPENGINE is wrong?.
I can only count "by strings"... and all the other examples i see the Cipher Key Lenght is 64 strings... but the one generated by RTPENGINE has 62... 
Is this a problem? or a i'm missing something?
Thanks in advance.
Best Regards,

Ricardo

**Comment by rfuchs** [comment]
Add the option `pad-crypto` to your rtpengine flags.

**Comment by rmartinezredvoiss** [comment]
Hi.
Thanks for the tip.
I used this command in opensips as follows:
   rtpengine_manage("in-iface=lan out-iface=wan RTP/SAVP **SDES-pad-crypto** replace-origin");

But seems that the "200 OK" sent by OPENSIPS + RTPENGINE keeps the same lenght for the Cipher Key lenght.

{ "sdp": "v=0
o=root 1804338182 1804338182 IN IP4 192.XXX.XXX.94
s=GHJ
c=IN IP4 64.76.XXX.133
t=0 0
m=audio 10056 RTP/SAVP 0 101
a=maxptime:150
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=rtcp:10057
**a=crypto:1 AES_256_CM_HMAC_SHA1_80 inline:dH1hhlTe+6ORBYKRRWbfyhIDMcQGNhc41k3tHjNJX6MzrmgQWs1gzO5WLZLmDA**
", "result": "ok" }

Any ideas?
Best Regards,
Ricardo

**Comment by rfuchs** [comment]
It's either just `pad-crypto` or `SDES-pad`

**Comment by rmartinezredvoiss** [comment]
Thanks again.
Now I used SDES-pad
rtpengine_manage("in-iface=lan out-iface=wan RTP/SAVP SDES-pad replace-origin");

But the result is the same:

o=root 1608041583 1608041583 IN IP4 192.141.65.94
s=GHJ
c=IN IP4 192.141.64.133
t=0 0
m=audio 10100 RTP/SAVP 0 101
a=maxptime:150
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=rtcp:10101
a=crypto:1 AES_256_CM_HMAC_SHA1_80 inline:72TczhTy93NFNy1vkzWCB+DDlrCF9TenjPZ0N92DREl2fzK6SGCHeZmaJnhAEQ
", "result": "ok" }

I'm running out of ideas....
Thanks.
Ricardo

**Comment by rfuchs** [comment]
Is it an older version? It may support `pad-crypto` only

**Comment by rmartinezredvoiss** [comment]
I think it is a new version:
Version: git-master-e16cb57

But i manage to get it working...! 
I added the "pad-crypto" flag in the "on_reply_route" for my opensips configuration:
I had something like this:
if (is_method("INVITE") {
...
rtpengine_manage("in-iface=lan out-iface=wan RTP/SAVP pad-crypto replace-origin");
}

on_reply_route {
...
if (has_body("application/sdp"))
rtpengine_manage();
}

Then i changed the rtpengine_manage() for rtpengine_manage("pad-crypto")
And the 200 OK to the UAC is OK!

Nov 26 16:32:53 sbcar rtpengine[9684]: DEBUG: [104875Mzg4ZTEyMmE0YzFmYWRlM2UxNGMwMjUzZjgwNzExYTg]: Response dump for 'answer' to 127.0.0.1:38071: { "sdp": "v=0
o=root 1918643533 1918643533 IN IP4 192.141.64.133
s=GHJ
c=IN IP4 192.141.64.133
t=0 0
m=audio 10250 RTP/SAVP 0 101
a=maxptime:150
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=rtcp:10251
**a=crypto:1 AES_256_CM_HMAC_SHA1_80 inline:Eo/tuc38drq8sle4ukn9L28ZdV6C8T8YGlMOOAJZHUc9QZ165+jwfdrOBhBF1g==**
", "result": "ok" }

Is this the correct way to operate this ?!
Thanks!

Ricardo

**Comment by rfuchs** [comment]
Yup, exactly that. Not sure why `SDES-pad` wouldn't work for you with that version (it works for me), but those two flags are equivalent.
