### ISSUE TITLE
Loud noise on hold / unhold in a call between DTLS / SDES clients

### ISSUE THREAD

**Issue by alexcme** [sipwise/rtpengine#112]
It was mention before, but I collected all the logs and network captures, including decoded SDES and DTLS media streams for the following case:

1. Call from SDES (unauthenticated_srtp) client to webrtc DTLS client, media is ok both directions
2. DTLS client put call on hold for ~15 sec (inactive)
3. DTLS client unhold call, loud static heard on webrtc (DTLS) side, on SDES side somewhat distorted media still can be heard

SDES client changing SSRC from 0x836EE618 (2205083160) in original media session (#1 above) to 0x42B7FEF (69959663) after un-hold (#3 above). In addition ROC changed in #1 starting with sequence # 64278, going over to sequence # 301.

DTLS client not changing SSRC on hold/un-hold, keeping it the same 0x6E1918AE (1847138478)

Addresses and ports:

SDES client @ 10.160.1.150:10074 <-> RTPengine @ 10.160.1.87:10020

DTLS client @ 10.160.1.70:10000 <-> RTPengine @ 10.160.1.87:10000

Attached archive structure:

/rtpengine.log - RTPengine log - build with __DEBUG, running user space daemon only with dtls-passive, started like this: 

./rtpengine --table=-1 --interface=10.160.1.87 --port-min=10000 --port-max=20000 --listen-ng=0.0.0.0:2223 -f -L 7 --dtls-passive

/rtpengine.pcap - full network capture from RTPengine box

/dtls_2_rtpe_2_sdes - folder with filtered / decoded captures for media streams from DTLS client to RTPengine in /dtls_2_rtpe_2_sdes/dtls_2_rtpe folder and from RTPengine to SDES client in /dtls_2_rtpe_2_sdes/rtpe_2_sdes folder

/sdes_2_rtpe_2_dtls - folder with filtered / separated / decoded captures for media streams from SDES client to RTPengine and from RTPengine to DTLS client before hold and after un-hold

**Comment by alexcme** [comment]
oops, how can I submit an archive?

**Comment by rfuchs** [comment]
This is probably related to #102 and #110

**Comment by marcantonio** [comment]
We had this same issue with Firefox.  It seems to play static (the beautiful sound of encryption:) when the RTP isn't properly decrypted.  Chrome, on the other hand, actually seems to check the HMAC and, if it fails, doesn't play the audio.

**Comment by alexcme** [comment]
Can ssrc-roc branch changes be used in user space daemon only (that is how we use for testing)? It did not help so far with Chrome webrtc client and only when we have SDES on the other side, ie:

chrome (DTLS) <--> (DTLS) rtpengine (SDES) <--> (SDES) SIP phone

it works fine when internally we disable media encryption, ie:

chrome (DTLS) <--> (DTLS) rtpengine (RTP/AVP) <--> (RTP/AVP) SIP phone

**Comment by rfuchs** [comment]
The patches from #110 don't support SRTP<>SRTP properly. I'm working on fixing that right now.

**Comment by alexcme** [comment]
Nice, waiting to test it, and about FF @marcantonio - it does have another nasty differences vs Chrome - the most annoying one is G722 codec (G722/8000/1), actually with G722 there historically a mess - original G722/8000 were actually G722/16000 that is in fact used by Chrome and require corresponding SDP conversions for somewhat "old"/"original" devices.

**Comment by alexcme** [comment]
looks like it is fixed with f398d83

**Comment by rfuchs** [comment]
Good. Feel free to close the ticket if you've confirmed that all is well now.

**Comment by alexcme** [comment]
Tested on CentOS 7, user daemon only & in-kernel module works fine, trying to integrate into CentOS 6.5/6.6
