### ISSUE TITLE
a=rtcp-rsize and ICE=force

### ISSUE THREAD

**Issue by juha-h** [sipwise/rtpengine#1121]
Incoming request has SDP media attribute `a=rtcp-rsize`, but no ICE attributes.  I then call `rtpengine_offer()` with `ICE=force` key rtpengine adds ICE attributes to SDP, but does not remove  `a=rtcp-rsize` attribute. Microsoft SDP doc https://docs.microsoft.com/en-us/openspecs/office_protocols/ms-sdpext/6cbe6c6c-3ff4-4f45-9fae-f91d1581af8f claims that `a=rtcp-rsize`  should not be included if SDP contains ICE candidate attributes.  I'm not sure if that is true, but if so, should rtpengine drop `a=rtcp-rsize`, when it adds ICE candidates?

**Comment by rfuchs** [comment]
If true then yes, but I can find no mention of this requirement in either RFC 5506 nor in RFC 8445. I'm not even sure why that requirement would exist, or why usage of one would affect usage of the other. Also the linked article says "SHOULD NOT" and not "MUST NOT" so 🤷

**Comment by juha-h** [comment]
Yes, sounds like MS bulls**t to me.
