### ISSUE TITLE
Latest version source compilation error

### ISSUE THREAD

**Issue by woowadragonchan** [sipwise/rtpengine#1122]
**Current Version** : 7.4.0.0
**Current Commit** : https://github.com/sipwise/rtpengine/tree/5acbf1ec87bfdd5b685fd4ac929997e191f90a9e
**Current glib version** : 2.17
**OS** : Linux on AWS

Compilation error occurs when building the latest version(mr9.2 of master) source from the current version.
`undefined reference to g_option_context_parse_strv`
It looks like the glib library has been upgraded, which version should I use?

Best Regards.

**Comment by rfuchs** [comment]
According to https://developer.gnome.org/glib/stable/glib-Commandline-option-parser.html#g-option-context-parse-strv

`Since: 2.40`

**Comment by rfuchs** [comment]
We do support older versions elsewhere in the code, so might just add a version test macro here...

**Comment by rfuchs** [comment]
Does it work for you with 0853303 applied?

**Comment by woowadragonchan** [comment]
I applied the source and it works normally.

I want to apply the latest version of glib,
What should I do to upgrade to the latest version of glib?
Should the Linux version be upgraded?
Or do you have rtpengine installation documentation?

The reason to upgrade to the latest version of glib is to check if there were any bugs in 2.17.
Did you upgrade to 2.4 because of a bug in 2.17?
Specifically, what is the difference between the g_option_context_parse function and the g_option_context_parse_strv function? I wonder why it changed.
If there are no bugs in 2.17, it seems that there is no need to upgrade the glib library.

Thank you.
Best Regards.

**Comment by rfuchs** [comment]
This change was to aid in debugging: With the old function, there's a deliberate one-time memory leak during startup. With the new function, this is cleaned up properly, which helps in debugging real memory leaks.
