### ISSUE TITLE
Early Media not relayed if Kamailio and RTPEngine are on Different machines

### ISSUE THREAD

**Issue by hamidrhashmi** [sipwise/rtpengine#1125]
Hello

I have been facing a strange issue that if I connect Kamailio with RTPEngine which is on another machine then that RTPEngine didn't relay Early media traffic while if Kamailio and RTPEngine servers are on the same machine than early media works fine. 
Signaling Path 
 UE <-------> Kamailio <---2----> Freeswitch <---1-----> SIP Carrier
Early Media Path
 UE <---3-- RTPENGINE <---2--- Freeswitch <---1----- SIP Carrier

I took trace on  1, 2, and 3. I can see RTP packets on 1 and 2. But I cant see RTP Packets on 3. 

But if the Call got answered the same path works fine for actual user media.

**Comment by rfuchs** [comment]
Could be a NAT issue? If the addresses in the SDP aren't correct, then forwarding will fail if no packets were received in the reverse direction first.

**Comment by hamidrhashmi** [comment]
All communication is in a closed environment, no NAT is involved. Addresses in SDP are correct. Media flow in both directions when the call is answered. Do packets in the reverse direction required in the case of early media, where media flows in one direction only?

**Comment by rfuchs** [comment]
No, not at all. The usual use case is this: 'A' sends invite, triggers offer to rtpengine. Rewritten SDP goes to B. B can now send media to rtpengine's address, which is then forwarded to A. (Early media answer is optional but not required.) The only things that should make this fail are network related, like NAT or firewalls or things like that.

**Comment by hamidrhashmi** [comment]
the difference between working and not rtpengines

Working RTPENGINE

```
$ ls -lhtr /proc/rtpengine/
0 1 2 control list
```

not working RTPENGINE
```
$ ls -lhtr /proc/rtpengine/
```
the folder contains no pseudo-files


Can this cause issues in relying Early Media? Each machine has two instances of RTPENGINE. 

and I rebuild xt_RTPENGINE.ko  and tried to load it again by 
```
$ modprob -r xt_RTPENGINE
$ depmod -a
$ modprob xt_RTPENGINE
```
but it still not creating pseudo-files in /proc/rtpengine folder. what could be its reason?

**Comment by rfuchs** [comment]
At least `control` and `list` should always exist when the module is loaded. The numbered subdirectories are created when rtpengine is started, as per the `table=` option from the command line or config file. But all this happens during startup. What you do with rtpengine once it's running has no influence on what you see in `/proc/rtpengine`, and it also has no influence on media forwarding. In fact forwarding should work even without the kernel module loaded at all.

**Comment by hamidrhashmi** [comment]
I have created a new Debian (Buster) machine and install the latest  RTPEngine and it works for me.
