### ISSUE TITLE
Build error in rtpengine kernel module on debian buster with 4.19.0-13

### ISSUE THREAD

**Issue by boettner** [sipwise/rtpengine#1129]
Hi,

some of our servers got debian buster kernel upgrades. The rtpengine kernel module build failed with
```
Building module:
cleaning build area...
make -j2 KERNELRELEASE=4.19.0-13-amd64 -C /lib/modules/4.19.0-13-amd64/build M=/var/lib/dkms/ngcp-rtpengine/8.3.1.7+0~mr8.3.1.7/build RTPENGINE_VERSION=8.3.1.7+0~mr8.3.1.7...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.19.0-13-amd64 (x86_64)
Consult /var/lib/dkms/ngcp-rtpengine/8.3.1.7+0~mr8.3.1.7/build/make.log for more information.
```
`make.log` is attached: [make.log](https://github.com/sipwise/rtpengine/files/5653113/make.log)

Maybe this issue is related to #1111?

Edit: Same for rtpengine version 8.5.1.2 [make.log](https://github.com/sipwise/rtpengine/files/5653146/make.log)

**Comment by boettner** [comment]
Thanks a lot for your quick response. What is your schedule for debian packages?

**Comment by rfuchs** [comment]
Packages will become available later today.
