### ISSUE TITLE
RTPEngine does not connect to Redis

### ISSUE THREAD

**Issue by belkirdi** [sipwise/rtpengine#1131]
RTPEngine does not connect to Redis on centos 8. I am using the same configuration it works just fine. I tried redis-cli with the same information I passed to the RTP engine and I was able to connect on centos 8. Do you have any idea what's the root cause of that?

**Comment by rfuchs** [comment]
My crystal ball is in the shop for repairs right now, sorry...

Is there anything in the logs?
