### ISSUE TITLE
DTMF not relayed during Early Media

### ISSUE THREAD

**Issue by hamidrhashmi** [sipwise/rtpengine#1132]
There is a scenario in which I need to relay DTMF during early media but RTPEngine is not relaying it unless the call is answered.

UE ------>SIP/RTPEnngine ------> Carrier
INVITE -------> INVITE --------> INVITE
 183<---------- 183 <----------183
 RTP <=====  <=====  <==== RTP (Early Media)
**RTP EVENT (*)---->       XXX**    (RTPEngine blocks RTP Event) 
200<---------- 200 <--------- 200
ACK----------> ACK ---------> ACK
RTP <====>  <====>  <====> RTP (Two way media with RTP-Event)

Any setting which I can try to enable DTMF relay during early media ?

**Comment by rfuchs** [comment]
Do you have logs or a pcap? Because there should be no difference between DTMF events or other media, and both should be relayed equally.

**Comment by rfuchs** [comment]
Cleaning up old tickets
