### ISSUE TITLE
New prometheus metrics not accessible

### ISSUE THREAD

**Issue by ivlovric** [sipwise/rtpengine#1135]
Hi,

using latest release 9.1.1.6 from today compiled on Centos 7.

just wanted to try new prometheus exposed metrics but when I try to access to /metrics url i got an error in browser: `not found`.
Log in rtpengine service is this:
`rtpengine[25592]: WARNING: Unhandled HTTP GET URI: '/metrics'`

To confirm web interface is ok, `/ping` url works well and `pong` is received in web browser
Service log:
`rtpengine[25592]: INFO: Received command 'ping' from 127.0.0.1:56196
tpengine[25592]: INFO: Replying to 'ping' from 127.0.0.1:56196 (elapsed time 0.000001 sec)`

Thanks a lot,
Ivica

**Comment by rfuchs** [comment]
It's not available in the 9.1 branch. Update from current master.

**Comment by ivlovric** [comment]
Great, thank you for explanation. Closing this issue.
