### ISSUE TITLE
telephone-event clock rate must match audio codec, strips when different

### ISSUE THREAD

**Issue by jpyle490** [sipwise/rtpengine#1136]
This is offered from the client:

```
m=audio 16478 RTP/AVP 102 9 0 110 18 127
a=rtpmap:102 G7221/16000
a=fmtp:102 bitrate=32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:110 iLBC/8000
a=fmtp:110 mode=30
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:127 telephone-event/8000
```

rtpengine_offer() passes all the codecs.  The 200 OK from the far-end contains G7221/16000 and telephone-event/8000 only.  rtpengine_answer() passes G7221/16000, but strips telephone-event/8000, presumably because 8000 != 16000.

I've seen other client that offer telephone-event attributes for each of the clock rates, and ones like the Polycoms that don't.  Unfortunately this rtpengine functionality breaks DTMF functionality on those that don't.

I don't see a config option that would allow mismatched clock rates to pass through (restoring old rtpengine behavior).  Did I miss it?

**Comment by jpyle490** [comment]
I've discovered that the _asymmetric-codecs_ option on rtpengine_answer() allows the telephone-event/8000 to pass from b-leg to a-leg in the above scenario.  Is that the proper way to do it in this case?  No transcoding in this application.

**Comment by rfuchs** [comment]
Can you share the offer/answer flags used in this case please.

**Comment by jpyle490** [comment]
in branch_route:
`rtpengine_offer("ICE=remove address-family=IP4 replace-origin replace-session-connection port-latching rtcp-mux-offer rtcp-mux-accept $var(rtpopts)");`
where $var(rtpopts) is either 'RTP/AVP' or 'RTP/SAVP' depending on previous conditions.  This choice has no impact on the telephone-event behavior.

in onreply_route:
`rtpengine_answer("ICE=remove replace-origin replace-session-connection port-latching asymmetric-codecs");`
The 'asymmetric-codecs' flag is new, and with it telephone-event attribute with the differing rate is allowed to pass.  Without it, the attribute is stripped.

**Comment by rfuchs** [comment]
8423d10 should be a fix for this. I'll have to add a few more tests to confirm that it doesn't break anything else.

**Comment by rfuchs** [comment]
Did you get a chance to try this?

**Comment by jpyle490** [comment]
Yes, apologies!  Looks good.  With this it works without the asymmetric-codecs flag in rtpengine_answer().  I haven't noticed any other issues, but I can't claim to have make other scenarios.
