### ISSUE TITLE
Missing WITH_TRANSCODING wrapper in codec.c for mr7.5.6 branch

### ISSUE THREAD

**Issue by MingcongQi** [sipwise/rtpengine#1137]
When making rtpengine with `with_transcoding=no` without installing spandsp, below headers will report compiling errors.
```
#include <spandsp/telephony.h>
#include <spandsp/super_tone_rx.h>
#include <spandsp/logging.h>
#include <spandsp/dtmf.h>
```
They should be wrapped by `#ifdef WITH_TRANSCODING` `#endif`

**Comment by rfuchs** [comment]
Fixed by cherry-picking a0d07332 into mr7.5. Please update from mr7.5 or wait for mr7.5.7 to be branched.
