### ISSUE TITLE
Strange sounds when transcoding from G729 to PCMA

### ISSUE THREAD

**Issue by thomas414** [sipwise/rtpengine#1138]
When transcoding between g729 and pcma there are strange sounds in the direction that is transcoded from g729 to pcma, the sound stream in the other direction, pcma to g729, is very clear.

A: PCMA <--> rtpengine <--> B: G729

These strange sounds always occur shortly after the person in the direction B -> A has stopped speaking and when i view the sound stream through e.g. wireshark it seems they occur during the generated silence.
I read in an issue from about a year ago that VAD is disabled, could this maybe be the issue?

I have attached the debug log but could not find anything in there regarding this problem, i can also share the wireshark trace with the sound streams but would like to do that privately because of ip adresses and info that shouldn't be shared publicly, if that is possible and needed?
[g729_artifacts.log](https://github.com/sipwise/rtpengine/files/5687314/g729_artifacts.log)

**Comment by rfuchs** [comment]
A pcap that includes the RTP would be helpful,  yes. You can send it to my email through my profile.
