### ISSUE TITLE
One way voice to caller when webrtc as callee

### ISSUE THREAD

**Issue by magixyu** [sipwise/rtpengine#1139]
Hi Richard(@rfuchs)

I am struggling the issue for weeks. Here is the call flows

webrtc -> sipbox -> kamailio -> SIP 
SIP -> sipbox -> kamailio ->  webrtc
webrtc -> kamailio -> sipbox -> kamailio -> webrtc 

Now only the first one works. The rest two only have one direction of audio(callee - webrtc no voice， caller can hear voice)

Here are the logs for the 2nd case:
kamailio log: https://raw.githubusercontent.com/magixyu/webrtc-debug/master/sip
rtpengine log: https://raw.githubusercontent.com/magixyu/webrtc-debug/master/rtpengine
kamailio configuration: https://raw.githubusercontent.com/magixyu/webrtc-debug/master/kamailio.cfg
10005 is a webphone with SIP.js
10001 is a softphone 

Can you please help on this?

Thanks,
Tristan

**Comment by rfuchs** [comment]
I don't really see anything in that log that looks like an audio problem. Media seems to be flowing both ways. Can you point towards where or what the problem is?

**Comment by magixyu** [comment]
that's my question as well. All signaling is correct but the callee have no voice. I have changed computer, broswer, softphone client, and the issue is the same: No voice can be heard on the called webrtc side. 

SIP -> sipbox -> kamailio -> webrtc
webrtc -> kamailio -> sipbox -> kamailio -> webrtc

**Comment by magixyu** [comment]
https://github.com/collecttix/ctxSip which I use as webrtc client

**Comment by rfuchs** [comment]
Well there's nothing in the logs that indicates a problem, so you'll have to look elsewhere, for example on the network. The negotiated endpoints are 192.168.11.142:62160 and 192.168.11.124:40000. Are these correct? Do packets actually arrive there?

**Comment by magixyu** [comment]
well, i found another webclient and the result is the same. 

There is not error in chrome... very strange.

**Comment by magixyu** [comment]
The rtpengine I used is the version on raspberry.
Version: 9.0.0.0+0~mr9.0.0.0 git-HEAD-63388115

I switched to master branch and build for myself, there is a different issue. From the rtpengine log, the voice is send to one direction.

The log as below.
https://github.com/magixyu/webrtc-debug/blob/master/rtpengine.master

**Comment by rfuchs** [comment]
Again there is no indication in the log that there's any kind of problem. There is some media received and forwarded in the other direction: `DEBUG: [b76ac0a3-ba4a-1239-6a86-f8a03d5904eb]: Forward to sink endpoint: 192.168.11.161:4030 (RTP seq 12746 TS 1997391011)` but this seems to stop after the `answer`. Again you should confirm that 1) packets are actually received, 2) if they are, that they are forwarded, 3) investigate the RTP client because it looks like it just stops sending RTP.

**Comment by rfuchs** [comment]
By the way, some browsers and/or WebRTC clients refuse SHA-1 DTLS fingerprints these days, so you may want to try with `DTLS-fingerprint=SHA-256` in your offer. Similarly, some browsers/clients may refuse to work with an optional rtcp-mux offer, so you may want to try with `rtcp-mux-require` instead. Just some suggestions. Either way you should see the WebRTC client complaining about these things if they are indeed a problem.

**Comment by magixyu** [comment]
I switched to another webclient, then it works well. So it should be the issue on the javascript side.  I read the client and did not find anything wrong. Can you help to take a look?

https://github.com/collecttix/ctxSip. It uses SIP.js 0.7.8, very old version.

Thanks,
Tristan

**Comment by rfuchs** [comment]
No sorry, this is not my area. You can ask them for help.

**Comment by magixyu** [comment]
I have get this resolved. Thanks you.

**Comment by magixyu** [comment]
> Hi can you please write what your solution was

I upgrade the sipjs in the ctxPhone to 0.15.6, then the webrtc works well.
