### ISSUE TITLE
Remove SOFTWARE attribute in STUN

### ISSUE THREAD

**Issue by mgoodenUK** [sipwise/rtpengine#1141]
Hi,

Is it possible to configure RTPEngine to omit the SOFTWARE attribute in it's STUN binding messages? We're looking to sanitize our WebRTC traffic to make malicious actors lives more difficult..

Had a look around and can't seem to find any configuration parameters which help me out.

Many thanks
Mark

**Comment by rfuchs** [comment]
There's no option for that but it would be very easy to add one.

**Comment by mgoodenUK** [comment]
We could probably have a bash at this and raise a PR.

**Comment by rfuchs** [comment]
Add a field to `rtpe_config` in `main.h`, add the config option in `main.c`, and make the function call in `stun.c` conditional on that config value. Easy peasy.
