### ISSUE TITLE
metadata not written at the end of the metadata file

### ISSUE THREAD

**Issue by panitaxx** [sipwise/rtpengine#1142]
Hello I have a RTPEngine installation and I listen for changes in the metadata directory to read the metadata files when calls finish. I used to look at the end of the file for the metadata string but sometimes I see that additional data is written. Here is an example: 

<details>
<summary>metadata file</summary>

```
/var/spool/rtpengine/pcaps/7bd8e5bf3a3a2ea134abad135e701d1a%40XXX.XX.XX.XXX-2cace8fd1b63ec1c.pcap


Timestamp started ms: 1608330629262.804
SDP mode: answer
SDP before RTP packet: 1

v=0
o=- 2266959634 1780165162 IN IP4 XXX.XX.XX.XX
s=-
c=IN IP4 XX.XX.XX.X
t=0 0
m=audio 47654 RTP/AVP 18 101
a=maxptime:230
a=rtpmap:18 g729/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:18 annexb=no
a=fmtp:101 0-15
a=sendrecv
a=rtcp:47655

Timestamp terminated ms(first monologue): 1608330630471.558

call start time: 2020-12-18T22:30:29
call end time: 2020-12-18T22:30:35


user:0362491#50490000000|tags:testag:1212,tag2:an12|id:<null>|authkey=<null>
0
0:


STREAM 2 FORWARDING 0
0:


STREAM 3 FORWARDING 0
0:


RECORDING 1
0:


FORWARDING 0
0:


STREAM 0 FORWARDING 0
0:


STREAM 1 FORWARDING 0
0:


STREAM 2 FORWARDING 0
0:


STREAM 3 FORWARDING 0
0:
```

</details>

The metadata line is where it says 
```
user:0362491#50490000000|tags:testag:1212,tag2:an12|id:<null>|authkey=<null>
``` 

Most of the files have it at the end but some (less than 1%) dont.

**Comment by rfuchs** [comment]
Your complaint is that the metadata is not there at all, or that the metadata is not at the end of the file?

**Comment by panitaxx** [comment]
The problem for me is that the metadata is not at the end of the file. Is there a reason for that? I can do a workaround and detect the metadata line with a regex but then the docs should be corrected.  

BTW, not a complaint. Very thankful for this great work.

**Comment by rfuchs** [comment]
I think the problem is that the stuff you see at the end belongs to the `proc` recording method and shouldn't be there when using the `pcap` method. Will fix.

**Comment by rfuchs** [comment]
See 99de80aafc554799f040749d89432a71ae8685c0 if that fixes it for you.

**Comment by panitaxx** [comment]
Thanks for such a speedy fix. I tested with some calls and it didn't fail. I will test with some production calls over this Christmas weekend.

**Comment by panitaxx** [comment]
Hello. Today I have already over 500k calls without the issue showing up in the patched version.
