### ISSUE TITLE
Call forward and one way audio

### ISSUE THREAD

**Issue by ahmedfayoub** [sipwise/rtpengine#1143]
Hi,

I've a setup running Kamailio + RTPEngine and everything is working fine but I've one case when doing a call forward with one way audio so I enabled debugging and started to check what is going on.

The problem start with port mapping between 33864 <---> 33922 <---> 19946 , I see a new port generated from RTP engine 33940 that is causing the audio problem.

I tried port-latching and asymmetric in the options but still no joy , can you please check the attached log and tell me what is wrong ?

I'm running latest Kamailio and RTPengine.

[forward_debug.txt](https://github.com/sipwise/rtpengine/files/5720667/forward_debug.txt)

**Comment by rfuchs** [comment]
Port 33940 is generated on the second call ID (`9820e3ad31ac54339e0c93049fd0cdeb`) in this log. The call flow here is: Offer from 33864, rewrite to 33922. Answer from 19946, rewrite to 33940. So you have `(A) 33864 <> 33940 | 33922 <> 19946 (B)`. I'm not sure what else you would expect here?

**Comment by rfuchs** [comment]
Cleaning up old tickets
