### ISSUE TITLE
HTTP/WebSocket support

### ISSUE THREAD

**Issue by denyspozniak** [sipwise/rtpengine#1144]
Hello!

Could you explain how to enable HTTP/HTTPS interface on rtpengine?

https://github.com/sipwise/rtpengine#httpwebsocket-support
```If enabled in the config, rtpengine can handle requests made to it via HTTP, HTTPS, or WebSocket (WS or WSS) connections.```

But looks nothing related in config sample:
https://github.com/sipwise/rtpengine/blob/master/etc/rtpengine.sample.conf

**Comment by rfuchs** [comment]
It's in the man page: https://github.com/sipwise/rtpengine/blob/master/daemon/rtpengine.pod

Look under `listen-http` and `listen-https`

**Comment by denyspozniak** [comment]
Maybe somehow it's worth adding a link on the main page to this file?
