### ISSUE TITLE
rtpengine installation lxc

### ISSUE THREAD

**Issue by korithi** [sipwise/rtpengine#1145]
Hi All,

I am trying to install rtpengine in a lxc container.
The problem I am facing is that the rtpengine is installed by default using the kernel of the host libraries.
The host has different kernel version than the machine and when I try to start the service is shows the error below:
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/5.8.0-7630-generic/
modprobe: FATAL: Module xt_RTPENGINE not found in directory /lib/modules/5.8.0-7630-generic

It is searching for the lib of host kernel modules but this folder does not exist in there. In the /lib/modules are just the modules of the machine, which is another version.

How can I be able to make it running within lxc container?

Thanks

**Comment by rfuchs** [comment]
If your container isn't running its own kernel but using the host's kernel, then you cannot use the kernel module within the container. You have to install the module in the host's kernel. Or you can run rtpengine just in userspace mode without kernel support.

**Comment by korithi** [comment]
Hi,

Thank your for your prompt reply!
1. I have already installed the kernel module in the host but the container search within its directory /usr/lib/. The /usr/lib/ of the host it is not accessible from within the container.
2. How can I install it without the kernel support? Does it affect anything? 
3. Is there any documentation about the installation, because in the wiki I only could find just an instruction for centos7.

Thank your for your help!

**Comment by rfuchs** [comment]
It's all in the readme. The userspace daemon is mostly independent of the kernel module. Compile it normally and just run it.

**Comment by rfuchs** [comment]
Cleaning up old tickets
