### ISSUE TITLE
ICE Settings of call setup not used for reINVITE in branch 9.1

### ISSUE THREAD

**Issue by SipSeb** [sipwise/rtpengine#1147]
Hi,

to have rtpengine compatible with the latest Debian Buster kernel, we started updating all our rtpengines to the latest 9.1 relase, taking the 9.1.1.7 packages from your repository. However, after that, customers using our service through websocket clients started complaining.

1) In previous versions (in our case: 8.2.2) we didn't have to specify `ICE=optional` in the answer rtpengine call of outgoing websocket calls. Okay, the behavior change is documented somewhere hidden in the ICE section.

2) In previous versions, we didn't have to specify the same attributes for reINVITEs, because rtpengine would use the initial options for reINVITEs as well. Now, when a call is sent to websocket, we specify `ICE=force` and the call is setup fine. However, when a reINVITE goes to websocket, rtpengine doesn't add the ICE attributes unless we specify them again.

Is the second scenario wanted like that? To me, that sounds like a bug. 

Is there a page documenting behavior changes? Would be nice to find traps before updating rtpengine and deploying it to customers.

**Comment by rfuchs** [comment]
Can you post a concrete example of what you see in your case 2?

(BTW, the patches for the kernel module have been backported to all supported releases, and even some unsupported ones, such as 8.2.2)

**Comment by SipSeb** [comment]
Of course. 

For a call to Websocket, we use the following line in kamailio:
```
rtpengine_manage("trust-address replace-origin replace-session-connection ICE=force RTP/SAVPF rtcp-mux-offer SDES-off via-branch=extra")
```

This produces the following SDP going to the client:
```
v=0
o=root 1218971362 1218971363 IN IP4 192.0.2.4
s=sipgate VoIP GW
c=IN IP4 192.0.2.4
t=0 0
m=audio 18518 RTP/SAVPF 8 0 3 97 18 112 101
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:3 GSM/8000
a=rtpmap:97 iLBC/8000
a=fmtp:97 mode=30
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:112 G726-32/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=rtcp:18519
a=rtcp-mux
a=setup:actpass
a=fingerprint:sha-1 90:6E:FB:46:4E:A1:9D:FD:F8:BD:EA:A6:75:0E:C2:BC:14:B9:24:5D
a=ptime:20
a=ice-ufrag:TFaKVNbC
a=ice-pwd:5Fo1p4qF6PewOmqAIf997dNYhQ
a=candidate:IwHAZe7YLisH0nVt 1 UDP 2130706431 192.0.2.4 18518 typ host
a=candidate:IwHAZe7YLisH0nVt 2 UDP 2130706430 192.0.2.4 18519 typ host
```

Then, when a reINVITE comes in, we issue this in our in-call handling in Kamailio:
```
rtpengine_manage("pad-crypto");
```

This used to produce the same SDP as in the original INVITE, but now the SDP looks like this:
```
v=0
o=root 1218971362 1218971364 IN IP4 192.0.2.3
s=sipgate VoIP GW
c=IN IP4 192.0.2.4
t=0 0
m=audio 18518 RTP/SAVPF 8 0 101
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=rtcp:18519
a=rtcp-mux
a=setup:actpass
a=fingerprint:sha-256 91:FA:81:A9:29:EB:D5:87:92:7E:2A:E1:85:77:9F:AD:43:7A:4E:C2:05:17:91:E8:40:4D:56:CA:52:4D:7F:0D
a=ptime:20
a=ice-options:trickle
a=end-of-candidates
```

The ICE candidates and password are missing in the reINVITE. That of course causes the client to reject the reINVITE, leading to call drops.

**Comment by rfuchs** [comment]
Ok I see. Yes that does look wrong. Will fix.

**Comment by rfuchs** [comment]
See 44167eb for a possible fix. At least in the tests it looks good. Only caveat is that if you issue two consecutive offers without a matching answer in between, then the ICE flags are not remembered (which actually makes sense, because technically that's not a re-invite).

**Comment by SipSeb** [comment]
Thanks for the quick fix. Unfortunately, as always with my bug reports, I can't test with anything other than debian packages. Could you provide a 9.1.x package with that patch applied on top?

**Comment by rfuchs** [comment]
The -daemon package should be enough?

[ngcp-rtpengine-daemon_9.1.2.0+0_mr9.1.2.0+0_20201229193558.5909+buster_1.gbp0bd611_amd64.deb.gz](https://github.com/sipwise/rtpengine/files/5751914/ngcp-rtpengine-daemon_9.1.2.0%2B0_mr9.1.2.0%2B0_20201229193558.5909%2Bbuster_1.gbp0bd611_amd64.deb.gz)

**Comment by SipSeb** [comment]
Yes, that was enough. Made a scenario where one rtpengine with latest  8.5.2 would generate a correct reINVITE and 9.1.1 would not, then replaced 9.1.1 with your 9.1.2, which corrected the reINVITE.

As always, thanks for the help.
