### ISSUE TITLE
ICE=force: wanted protocol specification IPv4/IPv6 in c= line

### ISSUE THREAD

**Issue by sergey-safarov** [sipwise/rtpengine#1149]
We use RTPengine as:
1) RTP proxy between public Internet and private network;
2) as IPv4/IPv6 RTP stream conversion service.

In our use case, IPv6 ICE enabled client wants to make a call to IPv4, not ICE aware SIP client.
In this case RTPengine replace IP address in original SDP and send new SDP with "c=" line with IPv6 address to IPv4 client.

As IPv4 client discards ICE attributes, then the client does not have any chance to send RTP stream to IPv6 address.
We go call with dead air.

Could you force use IPv4 address in `c=` line when used `ICE=force-ipv4`?

**Comment by rfuchs** [comment]
You're probably looking for `address-family=IP4`

**Comment by sergey-safarov** [comment]
Thanks, Richard @rfuchs 
Yes, this solved my issue.
