### ISSUE TITLE
Chrome and Opera error during VP8 initialization (STUN authentication mismatch)

### ISSUE THREAD

**Issue by StanislavKo** [sipwise/rtpengine#115]
I'm sorry if it's not related to rtpengine, could you point the direction in this case. 
Most interesting are maybe attachment #1 (STUN authentication mismatch), #2 and #3 (STUN requests logs).
Problem: 
.  1) I can't establish video call from Chrome to Chrome, Opera to Opera, Chrome to FF. In this case audio doesn't exist also. Often there are a black rectangle on answering or caller side. 
.  2) I can establish audio call from Chrome to Chrome, FF to FF.
.  3) I can establish video call from FF to FF, FF to Chrome. 
Configuration: 
.  1) OS: Windows 7, 64, updated
.  2) Client: sipjs 0.6.4 or jssip (current online demo), 
.  3) Browser (latest): Chrome 42.0.2311.152 m, Opera 29.0.1795.47, FF 38.0.1
.  4) Server: Kamailio 4.2 + RTPENGINE (mr3.8 - I got it 2 weeks ago)
.  5) Sipjs is modified for changing SDP
.  6) Local network: browsers on 2 windows, server in virtualbox (network bridge). So there are 3 machines: 192.168.0.XXX (46 - caller, 99 - callee, 70 - kamailio)
I see a lot of error messages in kamailio log but they are there always (during working calls also).
Attachments:
.  1) RTPEngine logs (http://i.imgur.com/IU7nNRg.jpg)
.  2) Chrome 2 Chrome, caller, almost original sip.js.0.6.4  (http://pastebin.com/pV2yj6ZD) + (wireshark http://i.imgur.com/SJwuwmq.png)
.  As you can see there is no traffic on port 30216 (video).
.  3) FF 2 Chrome, caller (http://pastebin.com/jWeeivqz) + (wireshark http://i.imgur.com/hV0dIWq.png)
.  4) FF 2 Chrome, callee (http://pastebin.com/pCYTCv5d)
.  5) Chrome 2 Chrome, caller, modified sip.js.0.6.4 (Opus/VP8 only) (http://pastebin.com/PXic621z)
.  6) Chrome 2 Chrome, callee, modified sip.js.0.6.4 (Opus/VP8 only) (http://pastebin.com/M9Gxdkpy)
.  7) Kamailio.cfg (http://pastebin.com/m8Pk8Lfy - almost copy of https://github.com/caruizdiaz/kamailio-ws)
.  8) /usr/local/src/rtpengine-mr3.8/rtpengine/daemon/rtpengine --table=0 --interface=192.168.0.70 --listen-udp=127.0.0.1:12222 --listen-ng=127.0.0.1:22222 --pidfile=/var/run/rtpengine.pid

**Comment by rfuchs** [comment]
Please post the rtpengine logs as text, not as a screenshot.

**Comment by StanislavKo** [comment]
RTPEngine:
1) FF: https://gist.github.com/StanislavKo/465dcd35b07af0eb992e
2) Chrome: https://gist.github.com/StanislavKo/064947528f4322aafee6
Last line in chrome log shows that my outer IP is tried to be used (123.123.123.123). 
Please don't spend your time for now. I'll fix this and report about results.
Thanks.

**Comment by StanislavKo** [comment]
The problem is logged in my previous post (chrome log).
There are several problems there:
1) my outer IP is logged (123.123.123.123) for caller video transferring instead of 192.168.0.46
2) "using unknown codec" instead of "using VP8/90000"
3) maybe some other error that causes #1 and #2
What do you think the initial error is?

BTW: sipjs 0.6.4 has "SIP.Hacks.AllBrowsers.unmaskDtls(sdp)" Is it useful in my problem context? I tried with and without this function with exactly same results.
    unmaskDtls: function (sdp) {
      /**
       * Chrome does not handle DTLS correctly (Canaray does, but not production)
       * keeping Chrome as SDES until DTLS is fixed (comment out 'is_opera' condition)
       *
       * UPDATE: May 21, 2014
       * Chrome 35 now properly defaults to DTLS.  Only Opera remains using SDES
       *
       * UPDATE: 2014-09-24
       * Opera now supports DTLS by default as well.
       *
       **/
      return sdp.replace(/ RTP\/SAVP/gmi, " UDP/TLS/RTP/SAVP");
    }

**Comment by StanislavKo** [comment]
Please don't spend time now. I think I have a workaround.

**Comment by rfuchs** [comment]
I'm more interested in the logs from rtpengine itself, not from Chrome or FF.

Regarding your questions, rtpengine supports both RTP/SAVP(F) and UDP/TLS/RTP/SAVP(F) equally, so that shouldn't make a difference.

"Unknown codec" appears when no RTP packet has been received yet, as the reported codec depends on what's actually seen on the wire, and not what was negotiated in signalling.

**Comment by StanislavKo** [comment]
My problem was replacing UDP/TLS/RTP/SAVP which is used by Chrome and Opera to RTP/SAVP.

**Comment by bquandt** [comment]
Think I'm having a similar problem.   Here's my test enivron:

1) Google Chrome	43.0.2357.81 (Official Build) (64-bit)
2) two computers both using chrome and tryit.jssip.net and ws set to 
ws://myawssipserver:5060/ws
3) my sip server is my own via AWS AMI spce 3.8.2
4) subscriber prefs with these type of settings:
 * WebRTC Subscribers -> Details -> Preferences -> NAT and Media Flow Control
- 'use_rtpproxy:' Always with rtpproxy as additional/only ICE candidate
- 'transport_protocol:' RTP/SAVPF (encrypted SRTP with RTCP feedback) ­
* Domain -> Details -> Preferences -> NAT and Media Flow Control
- 'transport_protocol:' RTP/AVP (Plain RTP)

Results, everyone connect fine and gets registered.  Calling the other subscriber, rings through.  Upon answer, one side reports webrtc error, the other side reports "incompatible sdp".  

rtp.log shows (incompatible codec):
Jul  9 19:54:27 ip-10-220-196-230 rtpengine[6430]: [g474qoosomrrqq3tnd5a] ------ Media #1 (audio over RTP/SAVPF) using unknown codec
Jul  9 19:54:27 ip-10-220-196-230 rtpengine[6430]: [g474qoosomrrqq3tnd5a] --------- Port 33942 <>  157.254.210.20:56739, 0 p, 0 b, 0 e, 1436471632 last_packet
Jul  9 19:54:27 ip-10-220-196-230 rtpengine[6430]: [g474qoosomrrqq3tnd5a] ------ Media #2 (video over RTP/SAVPF) using unknown codec
Jul  9 19:54:27 ip-10-220-196-230 rtpengine[6430]: [g474qoosomrrqq3tnd5a] --------- Port 33968 <>  157.254.210.20:57218, 0 p, 0 b, 0 e, 1436471632 last_packet

I've tested this from clients running chrome on ubuntu 14.10 to OSX/Yosemite in differing combiantions to try to determine if it's a OS nuance.  In all combo's the resutls are the same.

Any thoughts?
