### ISSUE TITLE
rtpengine-recording filename

### ISSUE THREAD

**Issue by alexwqr** [sipwise/rtpengine#1150]
I am using rtpengine-recording deamon to record audio from two endpoints. The filename looks like VkQrBaNWk~-8327f1aa02d8c8ae-mix.wav. I guess it's related with Call Id from both endpoint.  Is there any way to config the filename to date format, like yyyy-MM-dd HH:mm:ss ?

**Comment by rfuchs** [comment]
Yes it's the call ID. We don't have support for flexible/configurable file names right now, but we may in the future.
