### ISSUE TITLE
Rtcp-mux attribute missing from answer SDP if two callees offered

### ISSUE THREAD

**Issue by robdyck** [sipwise/rtpengine#1151]
```rtpengine]# rtpengine -v
Version: git-master-f0a29d0c
```
Happy 2021.
This seemed like an intermittent problem but I think I can make it fail reliably. The key is call forking.

The caller is WebRTC. Rtpengine is required for a variety of reasons - NAT, legcy WebRTC interworking.
The call fails with an error message indicating a bad SDP. The UA requires rtcp-mux in the attributes which is clearly missing from answer SDP.
I am attaching two files. The first is a debug log from rtpengine. The second is an SDP dump from opensips for readability. I was too lazy to reformat the rtpengine debug.

[rtpengine-bad-call.txt](https://github.com/sipwise/rtpengine/files/5758388/rtpengine-bad-call.txt)
[sdp-bad-call.txt](https://github.com/sipwise/rtpengine/files/5758389/sdp-bad-call.txt)

**Comment by rfuchs** [comment]
If you're forking a call to multiple endpoints with multiple offers with different options, you must supply a `via-branch` so that rtpengine knows which offer the answer belongs to. If you add this, the answer going back to the original UA will be with `rtcp-mux`

**Comment by rfuchs** [comment]
In Kamailio you can use `via-branch=next` to pass the via branch ID that is generated when the message is relayed. If that's not available to you then you need to think of something else. It doesn't have to a real via branch ID string. It can be anything as long as the string from the offer matches the one from the answer.

**Comment by robdyck** [comment]
Sorry about the slow response. Blame lfe.
With opensips we have ```via-branch=extra``` and it is enabled with an rtpengine module parameter. I set it with the transaction's branch index for the offers and also the subsequent answer. It did not help.

While playing around with branches I found that the branch index is a factor in this issue. It is specific to a particular UA and branch 0. By playing around with registration I can move that UA to index 1 and it works fine. Meanwhile the new UA on index 0 also works.

Some more detail. The caller is a WebRTC UA and calling from an ipv4 only mobile network with who knows how many levels of NAT. One callee is also WebRTC which registers with an ipv6 address. This one works regardless of its branch index. Ordinarily ICE would allow interworking between ipv4 and dual stack but we are dealing with NAT here. The other callee does not support rtcp-mux. I could enable ICE and DTLS but it would have to go through rtpengine regardless due to the rtcp-mux requirement.  This UA fails when the answer is branch index 0.

Do you need an rtpengine log with the via-branch included?

**Comment by rfuchs** [comment]
I'm not sure what you mean with branch index, but sure, post a log.

**Comment by robdyck** [comment]
This is what goes into via-branch.
```1.5.1. $T_branch_idx
$T_branch_idx - the index (starting with 0 for the first branch) of the currently proccessed branch. This index makes sense only in BRANCH and REPLY routes (where there is a concept of per branch processing). In all the other types of routes, the value of this index will be NULL.
```

So I have to admit to a error in my previous comment resulting from an error in my opensips script. After correcting the script if I provide both the offer and answer with via-branch I am able to call and answer using the troublesome scenario that I previously described.

There is however a major problem with that configuration. It doesn't free the media ports. If I provision 16 ports and there 2 agents registered on the AOR, I run out of ports after 4 successful calls. I waited several minutes but no ports were available. It was necessary to restart rtpengine.

I am including the complete log of the 4 calls and subsequent port exhaustion.

[no-ports.log](https://github.com/sipwise/rtpengine/files/5789343/no-ports.log)

**Comment by rfuchs** [comment]
Ok, so in this log there is:

1) First offer, from-tag `rtb14llm9c`, via-branch `0`. Ok.
2) Second offer, from-tag `rtb14llm9c`, via-branch `1`. Ok, second branch of this offer.
3) Answer, from-tag `rtb14llm9c`, to-tag `2Gbw4wO` but no via-branch. Without via-branch, rtpengine still doesn't know which branch this answer belongs to. It will associate the to-tag `2Gbw4wO` with one of the branches, but it might be the wrong one.
4) Delete, from-tag `2Gbw4wO`, no to-tag, no via-branch. So this deletes the branch from the answer in `3`. The other branch is still active.
5) Another identical delete, which therefore has no effect.

So you see the ports remaining open because one half of the call is still active. The delete either needs to be for the originating side of the call (tag `rtb14llm9c`) which would delete all of the branches (or no tag at all given, which deletes the entire call), or you need one delete for each branch, either by its own tag (which you only have one of) or by the corresponding via-branch.

**Comment by robdyck** [comment]
That was my fault. When trying different configurations with different scenarios I neglected to remove a comment from the script. The script detected the answer branch but didn't actually insert the flag.

The good news is that including the branch index causes the rtcp-mux attribute to be included in the SDP. It works regardless the order of the registration.

I'm Ok with closing this issue. Thank you.
```
Jan 11 10:04:08 slim rtpengine[13744]: INFO: [fcj55cmmvlv3u05bo1n6]: Received command 'answer' from 127.0.0.1:34747
Jan 11 10:04:08 slim rtpengine[13744]: DEBUG: [fcj55cmmvlv3u05bo1n6]: Dump for 'answer' from 127.0.0.1:34747: { "sdp": "v=0#015#012o=4 120 44 IN IP4 192.168.1.3#015#012s=Talk#015#012c=IN IP4 192.168.1.3#015#012t=0 0#015#012m=audio 7078 RTP/AVP 111 9 0 110 126#015#012a=rtpmap:111 opus/48000/2#015#012a=fmtp:111 useinbandfec=1#015#012a=fmtp:0 mode=30#015#012a=rtpmap:110 telephone-event/48000#015#012a=rtpmap:126 telephone-event/8000#015#012a=rtcp-fb:* trr-int 1000#015#012m=video 9078 RTP/AVP 96 100#015#012a=rtpmap:96 VP8/90000#015#012a=rtpmap:100 H264/90000#015#012a=fmtp:100 profile-level-id=42801F; packetization-mode=1#015#012a=rtcp-fb:* trr-int 1000#015#012a=rtcp-fb ...
Jan 11 10:04:08 slim rtpengine[13744]: DEBUG: [fcj55cmmvlv3u05bo1n6]: ... :* nack#015#012a=rtcp-fb:96 nack pli#015#012a=rtcp-fb:96 ccm fir#015#012a=rtcp-fb:100 nack pli#015#012a=rtcp-fb:100 ccm fir#015#012", "ICE": "force", "DTLS-fingerprint": "sha-256", "direction": [ "ipv4-priv", "ipv4-ext" ], "flags": [ "SDES-off", "generate-mid" ], "replace": [ "session-connection", "origin" ], "transport-protocol": "UDP/TLS/RTP/SAVPF", "rtcp-mux": [ "require" ], "call-id": "fcj55cmmvlv3u05bo1n6", "via-branch": "0", "received-from": [ "IP4", "192.168.1.3" ], "from-tag": "knpgevlptu", "to-tag": "8x9JOON", "comm ...
Jan 11 10:04:08 slim rtpengine[13744]: DEBUG: [fcj55cmmvlv3u05bo1n6]: ... and": "answer" }
```
