### ISSUE TITLE
Logical interface parsing

### ISSUE THREAD

**Issue by VidarHUN** [sipwise/rtpengine#1153]
Hi,

I trying to specify multiple logical interfaces in one line but it is not working very well. Maybe am I doing something wrong? 

```
sudo rtpengine --interface=pub3/172.18.0.33;pub1/172.18.0.31;pub2/172.18.0.32
[1609921433.174457] ERR: Failed to resolve '172.18.0.33;pub1/172.18.0.31;pub2/172.18.0.32' as a DNS host name: Name or service not known
[1609921433.174472] CRIT: Fatal error: Invalid interface specification: 'pub3'
```
Below the two kind of specification will works as same? 

```
# Command line
sudo rtpengine --interface=pub3/172.18.0.33 --interface=pub1/172.18.0.31 --interface=pub2/172.18.0.32 

# Config file
--interface=pub3/172.18.0.33;pub1/172.18.0.31;pub2/172.18.0.32 
```

**Comment by rfuchs** [comment]
On the command line you would use multiple `--interface` options, while in the config file you would use a single one and separate the options by semicolons. So yes

> ```
> # Command line
> sudo rtpengine --interface=pub3/172.18.0.33 --interface=pub1/172.18.0.31 --interface=pub2/172.18.0.32 
> 
> # Config file
> --interface=pub3/172.18.0.33;pub1/172.18.0.31;pub2/172.18.0.32 
> ```

those two are identical and should both work (except that you don't put the `--` in the config file)

**Comment by VidarHUN** [comment]
Yes, yes I forgot in the config file. 
Thank you very much your answer!
