### ISSUE TITLE
play and repeat 

### ISSUE THREAD

**Issue by dvillaume** [sipwise/rtpengine#1154]
Hello,

we're trying to use kamaillio and rtpengine to play 'on hold music' and 'custom ringback', is there an easy way to repeat the music while stop hasn't been receiveived ?

Regards,
David

**Comment by rfuchs** [comment]
We don't have that option right now, but it should be pretty easy to implement. Pull requests welcome.

**Comment by dvillaume** [comment]
I did my best : https://github.com/sipwise/rtpengine/pull/1159.

I'm a newbie with dev and gitlab, so be kind with me ;)

Regards,
David

**Comment by rfuchs** [comment]
Looks decent enough. Closing this to continue discussion in the PR
