### ISSUE TITLE
 JSON sent to homer 7 unable to load Qos page

### ISSUE THREAD

**Issue by sunilmmore** [sipwise/rtpengine#1156]
Hello I am using RTPENGINE Version: 9.1.1.2+0~mr9.1.1.2 and trying to connect with homer 7 . The QOS page in homer could not load up. Upon inspection I could observe that the statistics are sent to homer however the sdes_information type 8 has a text value `{"sdes_chunk_ssrc":3191907923,"type":8,"text":".x-rtp-session-idB9166F4F7DDA430584831CDB41C09BD5"}`
which makes the JSON invalid and looks like this 
`{"sdes_chunk_ssrc":3191907923,"type":8,"text":"x-rtp-session-idB9166F4F7DDA430584831CDB41C09BD5`
. After manually editing the value and removing the invalid character from db, I could get the QOS page. 

`
{ "sender_information":{"ntp_timestamp_sec":3818986922,"ntp_timestamp_usec":1687922147,"octets":29584,"rtp_timestamp":2840360, "packets":172},"ssrc":3191907923,"type":200,"report_count":1,"report_blocks":[{"source_ssrc":47986343,"highest_seq_no":39887,"fraction_lost":0,"ia_jitter":114,"packets_lost":0,"lsr":0,"dlsr":0}],"sdes_report_count":1,"sdes_information": [ {"sdes_chunk_ssrc":3191907923,"type":1,"text":"6F34204489AE4BB09E80D6356EE7CBB3@unique.zB7EA455E93BC46D1.org"},{"sdes_chunk_ssrc":3191907923,"type":8,"text":".x-rtp-session-idB9166F4F7DDA430584831CDB41C09BD5"}] }
`

**Comment by rfuchs** [comment]
Are you able to get a pcap or a hex dump or something of an RTCP packet that produces these JSON strings? I'd be interested in the raw contents.

**Comment by sunilmmore** [comment]
@rfuchs I digged a little and could find that the json stored by home in db is causing a problem . I have raised an issue with them . Here's the link https://github.com/sipcapture/homer-ui/issues/384 .

**Comment by rfuchs** [comment]
Ok I see. I think this still is a problem on the rtpengine side of things as well, because it shouldn't be sending invalid UTF-8.
