### ISSUE TITLE
Using redis with 2 rtpengine on separate machines

### ISSUE THREAD

**Issue by VidarHUN** [sipwise/rtpengine#1157]
Hi, 

I want to achieve a setup where are three machine behind NAT:

- RTPengine1: The machine has one interface: 172.18.0.xx
- RTPengine2: The machine has one interface: 172.18.0.yy
- Redis: 172.18.0.30

I can send traffic any of the RTPengine1 and it does the job good, but the RTPengine2 will has this kind of error: 

```
[1610038395.585900] NOTICE: Creating new call
[1610038395.585997] ERR: [3002-3004]: Failed to get 1 consecutive ports on interface 172.18.0.2 for media relay (last error: Cannot assign requested address)
[1610038395.586002] ERR: [3002-3004]: Error creating sfd: failed to open ports
[1610038395.586043] WARNING: Failed to restore call ID '3002-3004' from Redis: failed to create sfds
```
The port range on each machine is 23000-30000, but if I increase this number does not change anything. 
I assume the redis is working fine. 

The configs: 

RTPengine1

```
interface=pub1/rtpengine1;pub2/rtpengine2
redis=172.18.0.30:6379/1
subscribe-keyspace=2
foreground=true
log-stderr=true
listen-ng=rtpengine1:22222
log-level=6
delete-delay=0
timeout=600
port-min=23000
port-max=30000
```

RTPengine2

```
interface=pub2/rtpengine2;pub1/rtpengine1
redis=172.18.0.30:6379/2
subscribe-keyspace=1
foreground=true
log-stderr=true
listen-ng=rtpengine2:22222
log-level=6
delete-delay=0
timeout=600
port-min=23000
port-max=30000
```

**Comment by rfuchs** [comment]
If your setup involves a floating IP address, you can set the sysctl `net.ipv4.ip_nonlocal_bind=1`

Otherwise you'll have to bind the alternative IP address locally, for example on a dummy device or as an alias IP address.

**Comment by VidarHUN** [comment]
Thank you very much your answer!
