### ISSUE TITLE
Transcoding problems

### ISSUE THREAD

**Issue by borikinternet** [sipwise/rtpengine#1158]
Client A send me an SDP
```
...
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:120 telephone-event/48000
a=fmtp:120 0-16
a=rtpmap:121 telephone-event/8000
a=fmtp:121 0-16
...
```
Client B accept only PCMU and PCMA. I want transcoding from opus to PCMU and back.
How????!!! I tried all possible variants (as I understand). Best match was at version mr9.2 and looks like this:
```
opus   -> rtpengine  -> PCMU
PCMU   <- rtpengine  <- PCMU
```

**Comment by rfuchs** [comment]
What "all possible options" were those?

With a recent rtpengine, simply adding either `codec-accept-opus` or `codec-consume-opus` to the offer flags should do what you want. Alternatively you can add `always-transcode` to the offer flags, which should also work with older versions.

**Comment by borikinternet** [comment]
Yes, you are right, so simple variant work well. Thank you!
