### ISSUE TITLE
MESSAGE_INTEGRITY attribute missing

### ISSUE THREAD

**Issue by africallshop** [sipwise/rtpengine#116]
Hello,

We try to establish a call with ICE.

The call flow is : 

SIP softphone (with ICE) => Kamailio + rtpengine (with ICE : flag=ICE force) ==> Asterisk.

ICE failed : I can see the following error (MESSAGE_INTEGRITY attribute missing) in ngcp-rtpengine-daemon.log file : 

May 22 21:42:02 sd-75975 rtpengine[19247]: [dAAfe2~3e7] Response dump for 'answer' to 127.0.0.1:43788: { "sdp": "v=0#015#012o=root 974647701 974647701 IN IP4 62.210.220.120#015#012s=Asterisk PBX 11.11.0~dfsg-2ubuntu1#015#012c=IN IP4 212.83.182.55#015#012t=0 0#015#012m=audio 37452 RTP/SAVP 99 102#015#012a=rtpmap:99 speex/8000#015#012a=rtpmap:102 telephone-event/8000#015#012a=fmtp:102 0-16#015#012a=ptime:20#015#012a=sendrecv#015#012a=rtcp:37453#015#012a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:X+fKz6HW8C5UqequZ1VZ6X3wUtpz4hUn1ykCOkLi#015#012a=ice-ufrag:JVh3FZXg#015#012a=ice-pwd:Fuw8u9iAUdsWxuRTxmZPLWosPD#015#012a=candidate:i1pQZoxqUCm8O3L7 1 ...
May 22 21:42:02 sd-75975 rtpengine[19247]: [dAAfe2~3e7] ...  UDP 2130706431 212.83.182.55 37452 typ host#015#012a=candidate:i1pQZoxqUCm8O3L7 2 UDP 2130706430 212.83.182.55 37453 typ host#015#012", "result": "ok" }
May 22 21:42:03 sd-75975 rtpengine[19247]: [dAAfe2~3e7/qblq63ipy/1] Sending ICE/STUN request for candidate pair i1pQZoxqUCm8O3L7:1:1 from 212.83.182.55 to 192.168.1.61:7076
May 22 21:42:04 sd-75975 rtpengine[19247]: [dAAfe2~3e7/qblq63ipy/1] Sending ICE/STUN request for candidate pair i1pQZoxqUCm8O3L7:2:1 from 212.83.182.55 to 176.182.63.143:7076
May 22 21:42:04 sd-75975 rtpengine[19247]: [dAAfe2~3e7/qblq63ipy/1] Sending ICE/STUN request for candidate pair i1pQZoxqUCm8O3L7:1:2 from 212.83.182.55 to 192.168.1.61:7077
May 22 21:42:04 sd-75975 rtpengine[19247]: [dAAfe2~3e7 port 37452] Received invalid STUN packet from 176.182.63.143:7076: MESSAGE_INTEGRITY attribute missing
May 22 21:42:04 sd-75975 rtpengine[19247]: [dAAfe2~3e7/qblq63ipy/1] Sending ICE/STUN request for candidate pair i1pQZoxqUCm8O3L7:2:2 from 212.83.182.55 to 176.182.63.143:7077
May 22 21:42:04 sd-75975 rtpengine[19247]: [dAAfe2~3e7 port 37453] Received invalid STUN packet from 176.182.63.143:7077: MESSAGE_INTEGRITY attribute missing
May 22 21:42:06 sd-75975 rtpengine[19247]: [dAAfe2~3e7 port 37452] Confirmed peer address as 176.182.63.143:7076

Thanks.
Regards.
AfriCallShop

**Comment by rfuchs** [comment]
You're probably seen non-ICE STUN packets arriving on these ports. ICE requires the message-integrity attribute be present in all STUN packets, while regular STUN (outside of ICE) doesn't. Rtpengine only does ICE, but not any other kind of STUN.

You can run a packet capture (Wireshark etc) to see exactly what kind of STUN packets you're getting there.

Alternatively it could be a bug in one of the clients' ICE implementation in that it leaves out the required message-integrity. Again you can see that in a Wireshark capture.
