### ISSUE TITLE
TOS issue on latest master

### ISSUE THREAD

**Issue by smititelu** [sipwise/rtpengine#1161]
Hi,

I've been building and testing latest master rtpengine and found out TOS bit is not set for RTP packets, except for first 2-3 packets.

Trying to debug this, I've spotted it happening from commit 09026c19108a13c5af4d6af850dce2f9067092a9. However, the commit looks like adding in kernel rtp stats, so nothing related to TOS.

Trying to debug this further, I commented out all the ```kernel-module/xt_RTPENGINE.c``` code added by that commit, the issue was still happening. I commented out the line ```107``` in ```kernel-module/xt_RTPENGINE.h``` code added by that commit, issue was NOT happening anymore.

I am a bit confused why this might be happening, do you have any ideas?

Thank you,
Stefan

**Comment by rfuchs** [comment]
Sounds like you have a version mismatch between the kernel module and the daemon. Make sure both are compiled from the same sources at the same time, and make sure you don't have a stray older `xt_RTPENGINE.h` laying around anywhere.

**Comment by smititelu** [comment]
I am building rtpengine packages using a build daemon, from tar.gz archive. I checked to have the same versions of daemon vs kernel rtpengine packages. Also I checked that there is no previous kernel module installed, before actually installing.

Still same issue.

**Comment by rfuchs** [comment]
The new `clock_rates` struct member from xt_RTPENGINE.h is also used by the daemon. How were you able to build the daemon with that struct member removed from the .h?

**Comment by smititelu** [comment]
After i found the commit 09026c1, I started debugging from there, taking out the code. So the code on the daemon side, wasn't yet added in commit 09026c1. Have a look here: https://github.com/smititelu/rtpengine/commits/master

- After commit "Possible fix tos 1" -> issue still happening
- After commit "Possible fix tos 2" -> issue not happening

The kernel version I have on the test machine:
```4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux```

**Comment by smititelu** [comment]
I don't know how much of a sense it makes but moving the ```clock_rates``` array at the end of the structure and build/install new packages makes it run ok; see "Possible fix tos 3" commit

**Comment by rfuchs** [comment]
Moving a struct member around is not a proper fix and would only mask a different underlying issue.

**Comment by rfuchs** [comment]
You can do something like d318d3d. With this, the daemon will log:
```
DEBUG: [«8270fb3ef864f94c0e16ec486d9ea531@0:0:0:0:0:0:0:0» port 30014]: [core] XXXXXXXXXXX 904
```
and the kernel will log
```
[  300.173450] XXXXXXXXX 904 <> 904
```
The numbers might be different on your system, but all three numbers should be the same.

**Comment by smititelu** [comment]
I was getting the kernel message:
```xt_RTPENGINE unimplemented op 11``` => indeed old kernel module was used on my test machine, even if I installed new packages, consistently

After force-removing the xt_RTPENGINE module, and re-installing packages, TOS works again, with the latest master.

Thanks for the debugging tips,
Stefan
