### ISSUE TITLE
Upgraded to 9.2.1.1 from 9.1.1.7 stopped transcoding audio

### ISSUE THREAD

**Issue by lasseo** [sipwise/rtpengine#1165]
Tested to upgrade from 9.1.1.7 to 9.2.1.1 

Now I get problem with a transcoding scenario that previously worked.
According to "sngrep" no rtp packages is flowing between rtpengine and SEMS.

Bug or incorrect handling by me?

Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [control] Adding a proxy for control ng stats:127.0.0.1
Jan 19 00:11:16 siplab rtpengine[19447]: INFO: [15482aef-5ec5-4c82-945e-214185d04f1a]: [control] Received command 'offer' from 127.0.0.1:50478
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [control] Dump for 'offer' from 127.0.0.1:50478: { "supports": [ "load limit" ], "sdp": "v=0
Jan 19 00:11:16 siplab rtpengine[19447]: o=- 3820000275 3820000275 IN IP4 10.145.233.117
Jan 19 00:11:16 siplab rtpengine[19447]: s=media
Jan 19 00:11:16 siplab rtpengine[19447]: b=AS:50
Jan 19 00:11:16 siplab rtpengine[19447]: t=0 0
Jan 19 00:11:16 siplab rtpengine[19447]: a=X-nat:0
Jan 19 00:11:16 siplab rtpengine[19447]: m=audio 4016 RTP/SAVP 96 120
Jan 19 00:11:16 siplab rtpengine[19447]: c=IN IP4 10.145.233.117
Jan 19 00:11:16 siplab rtpengine[19447]: b=TIAS:32000
Jan 19 00:11:16 siplab rtpengine[19447]: a=rtcp:4017 IN IP4 10.145.233.117
Jan 19 00:11:16 siplab rtpengine[19447]: a=sendrecv
Jan 19 00:11:16 siplab rtpengine[19447]: a=rtpmap:96 opus/48000/2
Jan 19 00:11:16 siplab rtpengine[19447]: a=fmtp:96 maxplaybackrate=16000;sprop-maxcapturerate=16000;maxaveragebitrate=12000;cbr=1;useinbandfec=1
Jan 19 00:11:16 siplab rtpengine[19447]: a=rtpmap:120 telephone-event/48000
Jan 19 00:11:16 siplab rtpengine[19447]: a=fmtp:120 0-16
Jan 19 00:11:16 siplab rtpengine[19447]: a=ssrc:1068449950 cname:111d2b8058a082b4
Jan 19 00:11:16 siplab rtpengine[19447]: a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:8ODW5n5SmRoMaf2rnwNA6anT7h48vR62mj9/pPx4
Jan 19 00:11:16 siplab rtpengine[19447]: a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:d3AKS0WBfiR75C44xQO54s9IGkUWTOz8xA+D7nbf
Jan 19 00:11:16 siplab rtpengine[19447]: ", "ICE": "remove", "direction": [ "external", "internal" ], "replace": [ "origin", "session-connection" ], "codec": { "mask": [ "all" ], "transcode": [ "PCMA", "telephone-event" ] }, "transport-protocol": "RTP/AVP", "call-id": "15482aef-5ec5-4c82-945e-214185d04f1a", "received-from": [ "IP4", "95.199.9.117" ], "from-tag": "9452cfe0-f0d6-4df9-b2da-26770c447932", "command": "offer" }
Jan 19 00:11:16 siplab rtpengine[19447]: NOTICE: [15482aef-5ec5-4c82-945e-214185d04f1a]: [core] Creating new call
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Masking codec 'opus/48000/2'
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Masking codec 'telephone-event/48000'
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Codec 'PCMA/8000' added for transcoding with payload type 8
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Restoring codec 'telephone-event' from masked codecs (1 payload types)
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Default sink codec is opus/48000/2
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Output DTMF payload type is 120
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Creating codec handler for PCMA/8000
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Sink does not support codec PCMA/8000
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Created transcode context for PCMA/8000 -> opus/48000/2 with DTMF output 120
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Creating SSRC transcoder from PCMA/8000/1 to opus/48000/2
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [core] Setting ffmpeg 'frame_duration' option for 'opus' to 20
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [core] Initialized encoder with frame size 960 samples
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Encoder created with clockrate 48000, 2 channels, using sample format 1 (ptime 20 for 960 samples per frame and 960 samples (0 bytes) per packet, bitrate 32000)
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Creating codec handler for telephone-event/48000
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Sink supports codec telephone-event/48000
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Using passthrough handler for telephone-event/48000
Jan 19 00:11:16 siplab rtpengine[19447]: INFO: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Enabling transcoding engine
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Using passthrough handler with new SSRC for telephone-event/48000
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Adding supplemental codec telephone-event for clock rate 8000
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Eliminating supplemental codec telephone-event with stray clock rate 48000
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [core] set FILLED flag for stream 10.145.233.117:4016
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [crypto] [192.168.55.67:30020] Initialized incoming SRTP with SDES crypto params: suite AES_CM_128_HMAC_SHA1_80, tag 1, key 8ODW5n5SmRoMaf2rnwNA6Q== salt qdPuHjy9HraaP3+k/Hg=
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [crypto] [1] Initialized outgoing SRTP with SDES crypto params: <none>
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [core] set FILLED flag for stream 10.145.233.117:4017
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [crypto] [192.168.55.67:30021] Initialized incoming SRTP with SDES crypto params: suite AES_CM_128_HMAC_SHA1_80, tag 1, key 8ODW5n5SmRoMaf2rnwNA6Q== salt qdPuHjy9HraaP3+k/Hg=
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [crypto] [2] Initialized outgoing SRTP with SDES crypto params: <none>
Jan 19 00:11:16 siplab rtpengine[19447]: INFO: [15482aef-5ec5-4c82-945e-214185d04f1a]: [control] Replying to 'offer' from 127.0.0.1:50478 (elapsed time 0.000772 sec)
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [control] Response dump for 'offer' to 127.0.0.1:50478: { "sdp": "v=0
Jan 19 00:11:16 siplab rtpengine[19447]: o=- 3820000275 3820000275 IN IP4 192.168.55.67
Jan 19 00:11:16 siplab rtpengine[19447]: s=media
Jan 19 00:11:16 siplab rtpengine[19447]: b=AS:50
Jan 19 00:11:16 siplab rtpengine[19447]: t=0 0
Jan 19 00:11:16 siplab rtpengine[19447]: a=X-nat:0
Jan 19 00:11:16 siplab rtpengine[19447]: m=audio 30000 RTP/AVP 8 96
Jan 19 00:11:16 siplab rtpengine[19447]: c=IN IP4 192.168.55.67
Jan 19 00:11:16 siplab rtpengine[19447]: b=TIAS:32000
Jan 19 00:11:16 siplab rtpengine[19447]: a=ssrc:1068449950 cname:111d2b8058a082b4
Jan 19 00:11:16 siplab rtpengine[19447]: a=rtpmap:8 PCMA/8000
Jan 19 00:11:16 siplab rtpengine[19447]: a=rtpmap:96 telephone-event/8000
Jan 19 00:11:16 siplab rtpengine[19447]: a=fmtp:96 0-15
Jan 19 00:11:16 siplab rtpengine[19447]: a=sendrecv
Jan 19 00:11:16 siplab rtpengine[19447]: a=rtcp:30001
Jan 19 00:11:16 siplab rtpengine[19447]: ", "result": "ok" }
Jan 19 00:11:16 siplab rtpengine[19447]: INFO: [15482aef-5ec5-4c82-945e-214185d04f1a]: [control] Received command 'offer' from 127.0.0.1:50478
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [control] Dump for 'offer' from 127.0.0.1:50478: { "supports": [ "load limit" ], "sdp": "v=0
Jan 19 00:11:16 siplab rtpengine[19447]: o=- 3820000275 3820000275 IN IP4 10.145.233.117
Jan 19 00:11:16 siplab rtpengine[19447]: s=media
Jan 19 00:11:16 siplab rtpengine[19447]: b=AS:50
Jan 19 00:11:16 siplab rtpengine[19447]: t=0 0
Jan 19 00:11:16 siplab rtpengine[19447]: a=X-nat:0
Jan 19 00:11:16 siplab rtpengine[19447]: m=audio 4016 RTP/SAVP 96 120
Jan 19 00:11:16 siplab rtpengine[19447]: c=IN IP4 10.145.233.117
Jan 19 00:11:16 siplab rtpengine[19447]: b=TIAS:32000
Jan 19 00:11:16 siplab rtpengine[19447]: a=rtcp:4017 IN IP4 10.145.233.117
Jan 19 00:11:16 siplab rtpengine[19447]: a=sendrecv
Jan 19 00:11:16 siplab rtpengine[19447]: a=rtpmap:96 opus/48000/2
Jan 19 00:11:16 siplab rtpengine[19447]: a=fmtp:96 maxplaybackrate=16000;sprop-maxcapturerate=16000;maxaveragebitrate=12000;cbr=1;useinbandfec=1
Jan 19 00:11:16 siplab rtpengine[19447]: a=rtpmap:120 telephone-event/48000
Jan 19 00:11:16 siplab rtpengine[19447]: a=fmtp:120 0-16
Jan 19 00:11:16 siplab rtpengine[19447]: a=ssrc:1068449950 cname:111d2b8058a082b4
Jan 19 00:11:16 siplab rtpengine[19447]: a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:8ODW5n5SmRoMaf2rnwNA6anT7h48vR62mj9/pPx4
Jan 19 00:11:16 siplab rtpengine[19447]: a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:d3AKS0WBfiR75C44xQO54s9IGkUWTOz8xA+D7nbf
Jan 19 00:11:16 siplab rtpengine[19447]: ", "ICE": "remove", "direction": [ "external", "internal" ], "replace": [ "origin", "session-connection" ], "codec": { "mask": [ "all" ], "transcode": [ "PCMA", "telephone-event" ] }, "transport-protocol": "RTP/AVP", "call-id": "15482aef-5ec5-4c82-945e-214185d04f1a", "received-from": [ "IP4", "95.199.9.117" ], "from-tag": "9452cfe0-f0d6-4df9-b2da-26770c447932", "command": "offer" }
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Masking codec 'opus/48000/2'
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Masking codec 'telephone-event/48000'
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Codec 'PCMA/8000' added for transcoding with payload type 8
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Restoring codec 'telephone-event' from masked codecs (1 payload types)
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Default sink codec is opus/48000/2
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Output DTMF payload type is 120
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Sink does not support codec PCMA/8000
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Leaving transcode context for PCMA/8000 -> opus/48000/2 intact
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Sink supports codec telephone-event/48000
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Using passthrough handler for telephone-event/48000
Jan 19 00:11:16 siplab rtpengine[19447]: INFO: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Enabling transcoding engine
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Using passthrough handler with new SSRC for telephone-event/48000
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Adding supplemental codec telephone-event for clock rate 8000
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Eliminating supplemental codec telephone-event with stray clock rate 48000
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [crypto] [192.168.55.67:30020] Initialized incoming SRTP with SDES crypto params: suite AES_CM_128_HMAC_SHA1_80, tag 1, key 8ODW5n5SmRoMaf2rnwNA6Q== salt qdPuHjy9HraaP3+k/Hg=
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [crypto] [1] Initialized outgoing SRTP with SDES crypto params: <none>
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [crypto] [192.168.55.67:30021] Initialized incoming SRTP with SDES crypto params: suite AES_CM_128_HMAC_SHA1_80, tag 1, key 8ODW5n5SmRoMaf2rnwNA6Q== salt qdPuHjy9HraaP3+k/Hg=
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [crypto] [2] Initialized outgoing SRTP with SDES crypto params: <none>
Jan 19 00:11:16 siplab rtpengine[19447]: INFO: [15482aef-5ec5-4c82-945e-214185d04f1a]: [control] Replying to 'offer' from 127.0.0.1:50478 (elapsed time 0.000167 sec)
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [control] Response dump for 'offer' to 127.0.0.1:50478: { "sdp": "v=0
Jan 19 00:11:16 siplab rtpengine[19447]: o=- 3820000275 3820000275 IN IP4 192.168.55.67
Jan 19 00:11:16 siplab rtpengine[19447]: s=media
Jan 19 00:11:16 siplab rtpengine[19447]: b=AS:50
Jan 19 00:11:16 siplab rtpengine[19447]: t=0 0
Jan 19 00:11:16 siplab rtpengine[19447]: a=X-nat:0
Jan 19 00:11:16 siplab rtpengine[19447]: m=audio 30000 RTP/AVP 8 96
Jan 19 00:11:16 siplab rtpengine[19447]: c=IN IP4 192.168.55.67
Jan 19 00:11:16 siplab rtpengine[19447]: b=TIAS:32000
Jan 19 00:11:16 siplab rtpengine[19447]: a=ssrc:1068449950 cname:111d2b8058a082b4
Jan 19 00:11:16 siplab rtpengine[19447]: a=rtpmap:8 PCMA/8000
Jan 19 00:11:16 siplab rtpengine[19447]: a=rtpmap:96 telephone-event/8000
Jan 19 00:11:16 siplab rtpengine[19447]: a=fmtp:96 0-15
Jan 19 00:11:16 siplab rtpengine[19447]: a=sendrecv
Jan 19 00:11:16 siplab rtpengine[19447]: a=rtcp:30001
Jan 19 00:11:16 siplab rtpengine[19447]: ", "result": "ok" }
Jan 19 00:11:16 siplab rtpengine[19447]: INFO: [15482aef-5ec5-4c82-945e-214185d04f1a]: [control] Received command 'answer' from 127.0.0.1:39752
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [control] Dump for 'answer' from 127.0.0.1:39752: { "supports": [ "load limit" ], "sdp": "v=0
Jan 19 00:11:16 siplab rtpengine[19447]: o=sems 873606352 1598496083 IN IP4 192.168.55.67
Jan 19 00:11:16 siplab rtpengine[19447]: s=sems
Jan 19 00:11:16 siplab rtpengine[19447]: c=IN IP4 192.168.55.67
Jan 19 00:11:16 siplab rtpengine[19447]: t=0 0
Jan 19 00:11:16 siplab rtpengine[19447]: m=audio 1204 RTP/AVP 8 96
Jan 19 00:11:16 siplab rtpengine[19447]: a=rtpmap:8 PCMA/8000
Jan 19 00:11:16 siplab rtpengine[19447]: a=rtpmap:96 telephone-event/8000
Jan 19 00:11:16 siplab rtpengine[19447]: a=fmtp:96 0-15
Jan 19 00:11:16 siplab rtpengine[19447]: a=sendrecv
Jan 19 00:11:16 siplab rtpengine[19447]: a=direction:both
Jan 19 00:11:16 siplab rtpengine[19447]: ", "flags": [ "single-codec" ], "replace": [ "origin", "session-connection" ], "call-id": "15482aef-5ec5-4c82-945e-214185d04f1a", "received-from": [ "IP4", "192.168.55.67" ], "from-tag": "9452cfe0-f0d6-4df9-b2da-26770c447932", "to-tag": "01044768-600615940003131D-73AFA700", "command": "answer" }
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Default sink codec is PCMA/8000
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Output DTMF payload type is 96
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Renumbering 'telephone-event/8000' from PT 96 to 96 due to 'opus/48000/2'
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Accepting offered codec opus/48000/2 due to transcoding
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Accepting offered codec telephone-event/48000 due to transcoding
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Removing codec 'PCMA/8000' due to 'single codec' flag
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Creating codec handler for opus/48000/2
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Sink does not support codec opus/48000/2
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Created transcode context for opus/48000/2 -> PCMA/8000 with DTMF output 96
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Creating SSRC transcoder from opus/48000/2 to PCMA/8000/1
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [core] Initialized encoder with frame size 160 samples
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Encoder created with clockrate 8000, 1 channels, using sample format 1 (ptime 20 for 160 samples per frame and 160 samples (160 bytes) per packet, bitrate 0)
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Creating codec handler for telephone-event/48000
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Sink does not support codec telephone-event/48000
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Created DTMF transcode context for telephone-event/48000 -> PT 96
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Creating SSRC DTMF transcoder from telephone-event/48000/1 to PT 96
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [core] Initialized encoder with frame size 160 samples
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Encoder created with clockrate 8000, 1 channels, using sample format 1 (ptime 20 for 160 samples per frame and 160 samples (160 bytes) per packet, bitrate 0)
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Using existing encoder context
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Resetting codec handler for PT 96
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Creating codec handler for telephone-event/8000
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Sink supports codec telephone-event/8000
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Using passthrough handler for telephone-event/8000
Jan 19 00:11:16 siplab rtpengine[19447]: INFO: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Enabling transcoding engine
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Using passthrough handler with new SSRC for telephone-event/8000
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [codec] Eliminating supplemental codec telephone-event with stray clock rate 8000
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [crypto] Creating new SRTP crypto params for 1:AES_CM_128_HMAC_SHA1_80
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [crypto] [192.168.55.67:30020] Initialized incoming SRTP with SDES crypto params: suite AES_CM_128_HMAC_SHA1_80, tag 1, key 8ODW5n5SmRoMaf2rnwNA6Q== salt qdPuHjy9HraaP3+k/Hg=
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [crypto] [1] Initialized outgoing SRTP with SDES crypto params: suite AES_CM_128_HMAC_SHA1_80, tag 1, key 9GHd03MhphQ04Qm+rVWzjA== salt tvhOdeXzYmuV7jYxIr8=
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [crypto] [192.168.55.67:30021] Initialized incoming SRTP with SDES crypto params: suite AES_CM_128_HMAC_SHA1_80, tag 1, key 8ODW5n5SmRoMaf2rnwNA6Q== salt qdPuHjy9HraaP3+k/Hg=
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [crypto] [2] Initialized outgoing SRTP with SDES crypto params: suite AES_CM_128_HMAC_SHA1_80, tag 1, key 9GHd03MhphQ04Qm+rVWzjA== salt tvhOdeXzYmuV7jYxIr8=
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [core] set FILLED flag for stream 192.168.55.67:1204
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [core] set FILLED flag for stream 192.168.55.67:1205
Jan 19 00:11:16 siplab rtpengine[19447]: INFO: [15482aef-5ec5-4c82-945e-214185d04f1a]: [control] Replying to 'answer' from 127.0.0.1:39752 (elapsed time 0.000565 sec)
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a]: [control] Response dump for 'answer' to 127.0.0.1:39752: { "sdp": "v=0
Jan 19 00:11:16 siplab rtpengine[19447]: o=sems 873606352 1598496083 IN IP4 5.150.249.85
Jan 19 00:11:16 siplab rtpengine[19447]: s=sems
Jan 19 00:11:16 siplab rtpengine[19447]: c=IN IP4 5.150.249.85
Jan 19 00:11:16 siplab rtpengine[19447]: t=0 0
Jan 19 00:11:16 siplab rtpengine[19447]: m=audio 30020 RTP/SAVP 96 120
Jan 19 00:11:16 siplab rtpengine[19447]: a=direction:both
Jan 19 00:11:16 siplab rtpengine[19447]: a=rtpmap:96 opus/48000/2
Jan 19 00:11:16 siplab rtpengine[19447]: a=fmtp:96 maxplaybackrate=16000;sprop-maxcapturerate=16000;maxaveragebitrate=12000;cbr=1;useinbandfec=1
Jan 19 00:11:16 siplab rtpengine[19447]: a=rtpmap:120 telephone-event/48000
Jan 19 00:11:16 siplab rtpengine[19447]: a=fmtp:120 0-16
Jan 19 00:11:16 siplab rtpengine[19447]: a=sendrecv
Jan 19 00:11:16 siplab rtpengine[19447]: a=rtcp:30021
Jan 19 00:11:16 siplab rtpengine[19447]: a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:9GHd03MhphQ04Qm+rVWzjLb4TnXl82Jrle42MSK/
Jan 19 00:11:16 siplab rtpengine[19447]: ", "result": "ok" }
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a port 30000]: [transcoding] Received RTP packet: SSRC 5befc9ff, PT 8, seq 701, TS 115049120, len 160
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a port 30000]: [codec] Creating SSRC transcoder from PCMA/8000/1 to opus/48000/2
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a port 30000]: [core] Setting ffmpeg 'frame_duration' option for 'opus' to 20
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a port 30000]: [core] Initialized encoder with frame size 960 samples
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a port 30000]: [codec] Encoder created with clockrate 48000, 2 channels, using sample format 1 (ptime 20 for 960 samples per frame and 960 samples (0 bytes) per packet, bitrate 32000)
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a port 30000]: [transcoding] Processing RTP packet: seq 701, TS 115049120
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a port 30000]: [transcoding] Decoding RTP packet now
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a port 30000]: [ffmpeg] av_log: Using s16p internally between filters
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a port 30000]: [ffmpeg] av_log: Matrix coefficients:
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a port 30000]: [ffmpeg] av_log: FL:
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a port 30000]: [ffmpeg] av_log: FC:0.707107
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a port 30000]: [ffmpeg] av_log:
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d04f1a port 30000]: [ffmpeg] av_log: FR:
Jan 19 00:11:16 siplab rtpengine[19447]: DEBUG: [15482aef-5ec5-4c82-945e-214185d0

**Comment by rfuchs** [comment]
Log looks clean so far. The last few lines report a PCMA packet being received, I'm assuming from sems. The rest of the log is truncated. You should see more packets being received afterwards.

**Comment by rfuchs** [comment]
Cleaning up old tickets
