### ISSUE TITLE
No sound after REINVITE

### ISSUE THREAD

**Issue by obarash-widebridge** [sipwise/rtpengine#1167]
Hello,

I have 2 android clients running pjsip v2.10 with Kamailio v5.4.3 as sip proxy and RTPEngine (Version: 8.5.2.7+0~mr8.5.2.7 git-mr8.5.2-423e2135).
Call is established successfully with clear sound.
After some time, due to poor connection on one of the devices the TLS socket breaks and the client re-register and send REINVITE.
I can see that the call still running on both clients but with no sound on both direction.
PS, RTCP sent and received successfully on both ways.

What can cause this issue? 

log is attached.

Thanks,

Oren.
[rtpengine.log](https://github.com/sipwise/rtpengine/files/5846055/rtpengine.log)

**Comment by rfuchs** [comment]
I don't really see a problem in the log. Media seems to be flowing after the re-invite. I suggest to look at the RTP flow with Wireshark and/or look at what the clients are doing.

**Comment by rfuchs** [comment]
Cleaning up old tickets
