### ISSUE TITLE
[HELP] Play media file over wss

### ISSUE THREAD

**Issue by volga629-1** [sipwise/rtpengine#1168]
Hello Everyone,
What will be recommended setting to play audio file over UDP/TLS/RTP/SAVPF websocket. I don't see  an error, but no file sound either.
Debug of the call attached.
[61_wss_rtpengine_debug.log](https://github.com/sipwise/rtpengine/files/5846238/61_wss_rtpengine_debug.log)

**Comment by volga629-1** [comment]
I see in log 

```
Creating SSRC transcoder from PCM-S16LE/8000/1 to opus/48000/2

```

I wonder if it some codec issue.

**Comment by rfuchs** [comment]
You may have to send an answer back to the client first before you can play media. For a WebRTC client, DTLS needs to be established first, and for that some ICE exchanges need to happen. The log doesn't show any ICE/STUN received from the client, so I'm guessing the client is waiting for the answer before it starts its ICE processing.

**Comment by volga629-1** [comment]
So we need use ICE=force  as flag ? I am trying play media between offer and answer. On answer  with 200 OK we are stop play media.

**Comment by rfuchs** [comment]
No this is a problem on the client side. Rtpengine tries to establish ICE and then DTLS, and this would enable sending media. But it looks like the client isn't responding to the requests sent by rtpengine, and I'm guessing it's because it's waiting for an answer first.

**Comment by volga629-1** [comment]
Is this message mean that SRTP  crypto negotiation failing ?

```
Jan 26 22:39:02 vprx02 rtpengine[20099]: INFO: [r8jm7qc6qnhohcprcth4]: [control] Received command 'play media' from 10.30.100.61:21355
Jan 26 22:39:02 vprx02 rtpengine[20099]: ERR: [r8jm7qc6qnhohcprcth4]: [core] SRTP output wanted, but no crypto suite was negotiated
Jan 26 22:39:02 vprx02 rtpengine[20099]: INFO: [control] Replying to 'play media' from 10.30.100.61:21355 (elapsed time 0.031293 sec)

```

**Comment by rfuchs** [comment]
Not necessarily failing, but it hasn't completed. For DTLS, the DTLS handshake must have completed. For SDES, an offer/answer exchange must have taken place. Otherwise no crpyto keys are known and so SRTP cannot be sent.

**Comment by rfuchs** [comment]
Cleaning up old tickets
