### ISSUE TITLE
Getting "bencodepy.exceptions.BencodeDecodeError: not a valid bencoded string" while try to fire query command using python script

### ISSUE THREAD

**Issue by kunal-k2** [sipwise/rtpengine#1170]
**I am unable to find why it is showing not a valid bencoded string.**

does rtpengine is sending the correct bencoded string or my code is having some fault?.

File "new_ng.py", line 41, in <module>
    bencoded_data = bencodepy.decode(data[1])
  File "/usr/lib/python2.7/site-packages/bencodepy/__init__.py", line 155, in bdecode
    return DEFAULT.decode(value)
  File "/usr/lib/python2.7/site-packages/bencodepy/__init__.py", line 72, in decode
    return self.decoder.decode(value)
  File "/usr/lib/python2.7/site-packages/bencodepy/decoder.py", line 87, in decode
    raise BencodeDecodeError("not a valid bencoded string")
bencodepy.exceptions.BencodeDecodeError: not a valid bencoded string

[source_code.txt](https://github.com/sipwise/rtpengine/files/5865058/source_code.txt)

Output :

[root@ctl utils]# python new_ng.py
0_2393_6 d7:command4:liste
waiting to receive
received "0_2393_6 d5:callsl16:0201FFFFD1F7F00D20:odckcjvpuf3ue82nkqqee6:result2:oke"
Cookie is: 0_2393_6
Data is: {'result': 'ok', 'calls': ['0201FFFFD1F7F00D', 'odckcjvpuf3ue82nkqqe']}
There are 2 calls up on RTPengine at 127.0.0.1
0201FFFFD1F7F00D
data : "d7:call-id16:0201FFFFD1F7F00D7:command5:querye"

waiting to receive
len(data) : 2
('data[0] : ', '1_2393_6')
('data[1] : ', 'd7:createdi1611556084e10:created_usi583677e11:last signali1611556089e4:SSRCd6:152626d11:average MOSd3:MOSi42e15:round-trip timei84272e6:jitteri8e11:packet lossi0e7:samplesi2066ee10:lowest MOSd3:MOSi10e15:round-trip timei4486794e6:jitteri104e11:packet lossi47e11:reported ati1611558181ee11:highest MOSd3:MOSi43e15:round-trip timei2403e6:jitteri8e11:packet lossi0e11:reported ati1611556090ee15:MOS progressiond8:intervali561e7:entriesld3:MOSi43e15:round-trip timei2403e6:jitteri8e11:packet lossi0e11:reported ati1611556090eed3:MOSi43e15:round-trip timei74800e6:jitteri6e11:packet lossi0e11:reported ati1611556654eed3:MOSi43e15:round-trip timei68175e6:jitteri5e11:packet lossi0e11:reported ati1611557212eed3:MOSi43e15:round-trip timei76657e6:jitteri7e11:packet lossi0e11:reported ati1611557775eed3:MOSi43e15:round-trip timei80658e6:jitteri9e11:packet lossi0e11:reported ati1611558334eed3:MOSi43e15:round-trip timei73190e6:jitteri6e11:packet lossi0e11:reported ati1611558896eed3:MOSi43e15:round-trip timei82939e6:jitteri8e11:packet lossi0e11:reported ati1611559457eed3:MOSi43e15:round-trip timei80417e6:jitteri5e11:packet lossi0e11:reported ati1611560018eed3:MOSi43e15:round-trip timei85519e6:jitteri4e11:packet lossi0e11:reported ati1611560579eed3:MOSi43e15:round-trip timei77948e6:jitteri7e11:packet lossi0e11:reported ati1611561140eed3:MOSi43e15:round-trip timei75841e6:jitteri6e11:packet lossi0e11:reported ati1611561700eeeee9:104105125d11:average MOSd3:MOSi42e15:round-trip timei93448e6:jitteri1e11:packet lossi0e7:samplesi1127ee10:lowest MOSd3:MOSi10e15:round-trip timei4736334e6:jitteri107e11:packet lossi0e11:reported ati1611558179ee11:highest MOSd3:MOSi43e15:round-trip timei83385e6:jitteri1e11:packet lossi0e11:reported ati1611556097ee15:MOS progressiond8:intervali560e7:entriesld3:MOSi43e15:round-trip timei83385e6:jitteri1e11:packet lossi0e11:reported ati1611556097eed3:MOSi40e15:round-trip timei71562e6:jitteri1e11:packet lossi4e11:reported ati1611556660eed3:MOSi43e15:round-trip timei78611e6:jitteri3e11:packet lossi0e11:reported ati1611557221eed3:MOSi43e15:round-trip timei82876e6:jitteri1e11:packet lossi0e11:reported ati1611557781eed3:MOSi43e15:round-trip timei76496e6:jitteri1e11:packet lossi0e11:reported ati1611558338eed3:MOSi43e15:round-trip timei72178e6:jitteri2e11:packet lossi0e11:reported ati1611558898eed3:MOSi43e15:round-trip timei99106e6:jitteri3e11:packet lossi0e11:reported ati1611559460eed3:MOSi42e15:round-trip timei82752e6:jitteri1e11:packet lossi1e11:reported ati1611560018eed3:MOSi43e15:round-trip timei70042e6:jitteri1e11:packet lossi0e11:reported ati1611560577eed3:MOSi43e15:round-trip timei81596e6:jitteri0e11:packet lossi0e11:reported ati1611561139eed3:MOSi43e15:round-trip timei82662e6:jitteri1e11:packet lossi0e11:reported ati1611561701eeeee6:170102d11:average MOSd3:MOSi42e15:round-trip timei93180e6:jitteri4e11:packet lossi0e7:samplesi1049ee10:lowest MOSd3:MOSi10e15:round-trip timei4737879e6:jitteri35e11:packet lossi0e11:reported ati1611558180ee11:highest MOSd3:MOSi43e15:round-trip timei6911e6:jitteri11e11:packet lossi0e11:reported ati1611556092ee15:MOS progressiond8:intervali561e7:entriesld3:MOSi43e15:round-trip timei6911e6:jitteri11e11:packet lossi0e11:reported ati1611556092eed3:MOSi43e15:round-trip timei82005e6:jitteri3e11:packet lossi0e11:reported ati1611556653eed3:MOSi43e15:round-trip timei69870e6:jitteri0e11:packet lossi0e11:reported ati1611557216eed3:MOSi43e15:round-trip timei85913e6:jitteri0e11:packet lossi0e11:reported ati1611557779eed3:MOSi43e15:round-trip timei86117e6:jitteri7e11:packet lossi0e11:reported ati1611558337eed3:MOSi43e15:round-trip timei86215e6:jitteri0e11:packet lossi0e11:reported ati1611558899eed3:MOSi43e15:round-trip timei89473e6:jitteri3e11:packet lossi0e11:reported ati1611559458eed3:MOSi43e15:round-trip timei88240e6:jitteri1e11:packet lossi0e11:reported ati1611560021eed3:MOSi43e15:round-trip timei81920e6:jitteri5e11:packet lossi0e11:reported ati1611560585eed3:MOSi43e15:round-trip timei95903e6:jitteri6e11:packet lossi0e11:reported ati1611561144eed3:MOSi43e15:round-trip timei84555e6:jitteri0e11:packet lossi0e11:reported ati1611561707eeeee10:3304219541d11:average MOSd3:MOSi42e15:round-trip timei81241e6:jitteri1e11:packet lossi0e7:samplesi3729ee10:lowest MOSd3:MOSi10e15:round-trip timei77557e6:jitteri1e11:packet lossi66e11:reported ati1611556240ee11:highest MOSd3:MOSi43e15:round-trip timei68653e6:jitteri4e11:packet lossi0e11:reported ati1611556092ee15:MOS progressiond8:intervali561e7:entriesld3:MOSi26e15:round-trip timei77961e6:jitteri1e11:packet lossi16e11:reported ati1611556091eed3:MOSi43e15:round-trip timei76318e6:jitteri1e11:packet lossi0e11:reported ati1611556653eed3:MOSi43e15:round-trip timei72268e6:jitteri2e11:packet lossi0e11:reported ati1611557213eed3:MOSi43e15:round-trip timei74953e6:jitteri1e11:packet lossi0e11:reported ati1611557774eed3:MOSi43e15:round-trip timei77971e6:jitteri2e11:packet lossi0e11:reported ati1611558335eed3:MOSi43e15:round-trip timei72812e6:jitteri1e11:packet lossi0e11:reported ati1611558897eed3:MOSi43e15:round-trip timei72876e6:jitteri2e11:packet lossi0e11:reported ati1611559457eed3:MOSi37e15:round-trip timei79378e6:jitteri1e11:packet lossi7e11:reported ati1611560019eed3:MOSi43e15:round-trip timei86512e6:jitteri1e11:packet lossi0e11:reported ati1611560579eed3:MOSi43e15:round-trip timei77590e6:jitteri1e11:packet lossi0e11:reported ati1611561141eed3:MOSi43e15:round-trip timei71529e6:jitteri1e11:packet lossi0e11:reported ati1611561701eeeeee4:tagsd53:2E080FF2_nab_0202_isp_01FF_cco_00CA_igo_EA25_mgt_FFFFd3:tag53:2E080FF2_nab_0202_isp_01FF_cco_00CA_igo_EA25_mgt_FFFF7:createdi1611556084e16:in dialogue with10:jfs8g0c3mf6:mediasld5:indexi1e4:type5:audio8:protocol7:RTP/AVP7:streamsld10:local porti32116e13:local address14:10.211.160.1326:family4:IPv48:endpointd6:family4:IPv47:address14:10.211.160.1324:porti33016ee19:advertised endpointd6:family4:IPv47:address14:10.211.160.1324:porti33016ee11:last packeti1611561709e5:flagsl3:RTP6:filled9:confirmed10:kernelized17:no kernel supporte4:SSRCi170102e5:statsd7:packetsi256297e5:bytesi44083084e6:errorsi0eeed10:local porti32117e13:local address14:10.211.160.1326:family4:IPv48:endpointd6:family4:IPv47:address14:10.211.160.1324:porti33017ee19:advertised endpointd6:family4:IPv47:address14:10.211.160.1324:porti33017ee11:last packeti1611561707e5:flagsl4:RTCP6:filled9:confirmed10:kernelized17:no kernel supporte4:SSRCi170102e5:statsd7:packetsi1049e5:bytesi96508e6:errorsi0eeee5:flagsl11:initialized4:send4:recveed5:indexi2e4:type5:video8:protocol7:RTP/AVP7:streamsld10:local porti32148e13:local address14:10.211.160.1326:family4:IPv48:endpointd6:family4:IPv47:address14:10.211.160.1324:porti33022ee19:advertised endpointd6:family4:IPv47:address14:10.211.160.1324:porti33022ee11:last packeti1611561709e5:flagsl3:RTP6:filled9:confirmed10:kernelized17:no kernel supporte4:SSRCi152626e5:statsd7:packetsi163063e5:bytesi18309276e6:errorsi0eeed10:local porti32149e13:local address14:10.211.160.1326:family4:IPv48:endpointd6:family4:IPv47:address14:10.211.160.1324:porti33023ee19:advertised endpointd6:family4:IPv47:address14:10.211.160.1324:porti33023ee11:last packeti1611561707e5:flagsl4:RTCP6:filled9:confirmed10:kernelized17:no kernel supporte4:SSRCi152626e5:statsd7:packetsi2990e5:bytesi307532e6:errorsi0eeee5:flagsl11:initialized4:send4:recveeee10:jfs8g0c3mfd3:tag10:jfs8g0c3mf7:createdi1611556084e16:in dialogue with53:2E080FF2_nab_0202_isp_01FF_cco_00CA_igo_EA25_mgt_FFFF6:mediasld5:indexi1e4:type5:audio8:protocol17:UDP/TLS/RTP/SAVPF7:streamsld10:local porti32102e13:local address14:10.211.160.1326:family4:IPv48:endpointd6:family4:IPv47:address12:10.8.128.1684:porti57517ee19:advertised endpointd6:family4:IPv47:address12:10.8.128.1684:porti57517ee12:crypto suite23:AES_CM_128_HMAC_SHA1_8011:last packeti1611561709e5:flagsl3:RTP4:RTCP6:filled9:confirmed10:kernelized17:no kernel support25:DTLS fingerprint verified3:ICEe4:SSRCi104105125e5:statsd7:packetsi283223e5:bytesi48425372e6:errorsi0eeed10:local porti32103e13:local address14:10.211.160.1326:family4:IPv48:endpointde19:advertised endpointde12:crypto suite23:AES_CM_128_HMAC_SHA1_8011:last packeti1611556084e5:flagsl4:RTCP13:fallback RTCP6:fi')
('server :', ('127.0.0.1', 8500))
Traceback (most recent call last):
  File "new_ng.py", line 42, in <module>
    bencoded_data = bencodepy.decode(data[1])
  File "/usr/lib/python2.7/site-packages/bencodepy/__init__.py", line 155, in bdecode
    return DEFAULT.decode(value)
  File "/usr/lib/python2.7/site-packages/bencodepy/__init__.py", line 72, in decode
    return self.decoder.decode(value)
  File "/usr/lib/python2.7/site-packages/bencodepy/decoder.py", line 87, in decode
    raise BencodeDecodeError("not a valid bencoded string")
bencodepy.exceptions.BencodeDecodeError: not a valid bencoded string
[root@ctl utils]#

**Comment by rfuchs** [comment]
From that output, it looks like the string is just truncated. You probably just need to extend your receive buffer.

**Comment by kunal-k2** [comment]
Thanks Richard, receive buffer was the problem.
