### ISSUE TITLE
Kamailio + rtpengine One way audio

### ISSUE THREAD

**Issue by Antoineb2s** [sipwise/rtpengine#1171]
Hi,

I use a kamailio v5.2.x (debian 10) with latest rpengine v9.3

I first started to use only one private interface in order to communicate with our sip providers.

rtpengine.conf : 
interface = 10.78.51.3

Works but SDP infos contain private IP indeed.

Then I tried to rewrite the correct public IP via rtpengine_manage("direction=public direction=private RTP/AVP replace-session-connection replace-origin ICE=remove")

rtpengine.conf : 
interface = public/10.78.51.3!130.22.41.56;private/10.78.51.3

=> Not working : one RTP flow is missing from rtpengine to device with private IP
After few seconds the logs show : 
_r_tpengine[512]: INFO: [19d5acc6742c60d57eb7dfb729732378@130.xx.xx.xx:5060]: [core] Closing call due to timeout
rtpengine[512]: INFO: [19d5acc6742c60d57eb7dfb729732378@130.xx.xx.xx:5060]: [core] Final packet stats:
rtpengine[512]: INFO: [19d5acc6742c60d57eb7dfb729732378@130.xx.xx.xx:5060]: [core] --- Tag 'as299874fc', created 1:22 ago for branch '', in dialogue with 'as484049c0'
rtpengine[512]: INFO: [19d5acc6742c60d57eb7dfb729732378@130.xx.xx.xx:5060]: [core] ------ Media #1 (audio over RTP/AVP) using PCMA/8000
rtpengine[512]: INFO: [19d5acc6742c60d57eb7dfb729732378@130.xx.xx.xx:5060]: [core] --------- Port      10.78.51.3:30078 <>    130.xx.xx.xx:22302, SSRC 6533a368, 756 p, 130032 b, 0 e, 60 ts
rtpengine[512]: INFO: [19d5acc6742c60d57eb7dfb729732378@130.xx.xx.xx:5060]: [core] --------- Port      10.78.51.3:30079 <>    130.xx.xx.xx:22303 (RTCP), SSRC 6533a368, 3 p, 192 b, 0 e, 62 ts
rtpengine[512]: INFO: [19d5acc6742c60d57eb7dfb729732378@130.xx.xx.xx:5060]: [core] --- Tag 'as484049c0', created 1:22 ago for branch '', in dialogue with 'as299874fc'
rtpengine[512]: INFO: [19d5acc6742c60d57eb7dfb729732378@130.xx.xx.xx:5060]: [core] ------ Media #1 (audio over RTP/AVP) using PCMA/8000
rtpengine[512]: INFO: [19d5acc6742c60d57eb7dfb729732378@130.xx.xx.xx:5060]: [core] --------- Port      10.78.51.3:30064 <>     10.78.50.11:11390, SSRC 90d6616, 763 p, 131236 b, 0 e, 60 ts
rtpengine[512]: INFO: [19d5acc6742c60d57eb7dfb729732378@130.xx.xx.xx:5060]: [core] --------- Port      10.78.51.3:30065 <>     10.78.50.11:11391 (RTCP), SSRC 0, 0 p, 0 b, 0 e, 82 ts__

root@th3ssbcin02:~# iptables -L -v -n
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
27647   12M rtpengine  udp  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain rtpengine (1 references)
 pkts bytes target     prot opt in     out     source               destination
27647   12M RTPENGINE  udp  --  *      *       0.0.0.0/0            0.0.0.0/0            RTPENGINE id:0

------

Then I settled a new interface with direct public IP address 

rtpengine.conf : 
interface = public/130.22.41.56;private/10.78.51.3

And everything works as expected...
But I'd rather prefer to work behind a firewall and use public/10.78.51.3!130.22.41.56 in rtpengine.conf
Is there a way to do it ? Is it a known issue ?

Thanks,

Antoine

**Comment by rfuchs** [comment]
The IP addresses you see in the log output you pasted are the locally allocated ones. You wouldn't see the advertised addresses there. So this is expected. You can confirm that the advertised address was used correctly by looking at the output SDPs.

Both ports have received packets, so media has flowed. So you should probably look elsewhere to find out why the media flow has stopped. Perhaps your firewall/NAT has started to drop them. I suggest Wireshark to inspect the RTP flow.

**Comment by Antoineb2s** [comment]
Thanks,

I launched tdpdump indeed.

What I got is : 

SIP Provider 130.X.X.X <====>Public IP FW/NAT====>10.78.51.3 Kamailio/RTPEngine<======> 10.78.50.11 Private (asterisk)

rtp flow from Private asterisk to SIP Provider received : OK
rtp flow from sip provider to Private asterisk stops at Kamailio/RTPEngine : KO

Kamailio/RTPEngine doesn't send any rtp packets (received from the SIP Provider) to Private asterisk, confirmed by a tcpdump and voipmonitor sensor. However, SDP infos are correct on INVITE and 200 OK.
![voipmonitor_rtpengine](https://user-images.githubusercontent.com/16756375/106006129-2de10200-60b5-11eb-857e-90ee17b88204.jpg)

A timestamp is attached. You'll see that one rtp leg is missing (from Kamailio/RTPEngine to Private asterisk)

Thanks,

Antoine

**Comment by Antoineb2s** [comment]
Found also a timestamps were RTPEngine is sending rtp to Sip provider but not to private asterisk : 
This timestamp is more relevant than the other one (not sure about the config)
![image](https://user-images.githubusercontent.com/16756375/106007982-291d4d80-60b7-11eb-93dc-5277af4febd3.png)

**Comment by rfuchs** [comment]
The only reason why an outbound media leg could be missing is that the system is not able to send to a public address from a socket locally bound to a private address. This is usually due to a problem in the network setup (routing or local firewall) so check that. (You can try to confirm e.g. with `ping -I 10.78.51.3 130.X.X.X`)

**Comment by Antoineb2s** [comment]
Hi, 

Is it normal after a clean BYE (good audio for both sides) to still have some values in /proc/rtpengine/0/list ?
After a while in logs : 
[core] Closing call due to timeout

rtpengine_manage(params) is not enough or do I need to use rtpengine _manage / delete even if sdp_content() is not true ?

**Comment by abieuzent** [comment]
Perso, je fais un rtpengine_delete pour tous les BYE et les CANCEL

 

De : Antoineb2s <notifications@github.com>
Répondre à : sipwise/rtpengine <reply@reply.github.com>
Date : jeudi 28 janvier 2021 à 11:40
À : sipwise/rtpengine <rtpengine@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [sipwise/rtpengine] Kamailio + rtpengine One way audio (#1171)

 

Hi,

Is it normal after a clean BYE (good audio for both sides) to still have some values in /proc/rtpengine/0/list ?
After a while in logs :
[core] Closing call due to timeout

rtpengine_manage(params) is not enough or do I need to use rtpengine _manage / delete even if sdp_content() is not true ?

**Comment by rfuchs** [comment]
You need to signal a call teardown (delete) somehow. If you use rtpengine_manage from a BYE route, then that will do it (or be more explicit with _delete). You should do the same for CANCEL, 4xx, 5xx responses, etc.

**Comment by Antoineb2s** [comment]
Hi thanks,

That's what I do now.
But still have an entry for few seconds on /proc/rtpengine/0/list

now after a while : 

rtpengine[11983]: DEBUG: [2f4d03805a6b8ffb1ab2eb48777256ff@130.93.0.228:5060]: [core] Destroying monologue 'as375de996' ()
rtpengine[11983]: DEBUG: [2f4d03805a6b8ffb1ab2eb48777256ff@130.93.0.228:5060]: [core] Destroying monologue 'as395f7ee0' ()
rtpengine[11983]: INFO: [2f4d03805a6b8ffb1ab2eb48777256ff@130.93.0.228:5060]: [core] Call branch 'as375de996' (via-branch '') deleted, no more branches remaining
rtpengine[11983]: DEBUG: [2f4d03805a6b8ffb1ab2eb48777256ff@130.93.0.228:5060]: [core] Redis delete_async=0
rtpengine[11983]: INFO: [2f4d03805a6b8ffb1ab2eb48777256ff@130.93.0.228:5060]: [core] Final packet stats:

**Comment by rfuchs** [comment]
Yeah that's fine. The call stays open for a while (see `delete-delay` option) after it's deleted, in case there's a re-invite for another branch or something like that. You can set the delete-delay to zero if you don't require that.

**Comment by Antoineb2s** [comment]
Great thanks :)

Still have to look forward to see what could be done in order to work with one private interface.

I tried your proposal with ping -I 10.78.51.3 130.X.X.X(my public IP address) but no replies come.
The weird thing is that I have a clone of this VM with on another hypervisor that accept to use interface = private/IP;public/IP!publicIP
On this VM ping -I 10.192.50.3 37.X.X.X(my public IP address) not working too...

Antoine

**Comment by rfuchs** [comment]
Cleaning up old tickets
