### ISSUE TITLE
Question regarding UDP port usage per call/session

### ISSUE THREAD

**Issue by schlagert** [sipwise/rtpengine#1173]
Hi all,

I have made a strange discovery that I cannot really explain: I have multiple working proxy setups in production that I always assumed would need 4 UDP ports for one audio-only (single m-line) call (RTP+RTCP). However, I just recently discovered using `lsof` that actually 8 UDP ports are used.

I started digging and tried to understand why but failed. Even when I turn on log level 7 I do not see 4 of the 8 used ports in the RTPEngine log file.

I have made one example call on an empty box. There's no fancy SIP stuff happening, just the basic INVITE with SDP to 200 OK with SDP call flow.

```
$ rtpengine -v
Version: 7.2.1.4-1.el7

$ cat /etc/sysconfig/rtpengine

KERNEL=yes
TABLE=0
FALLBACK=no

LISTEN_NG=127.0.0.1:2223
LISTEN_CLI=127.0.0.1:2224

RTP_IP[0]=prv/10.7.4.6
RTP_IP[1]=pub/10.7.4.6!ZZ.ZZ.ZZ.ZZ

PORT_MIN=45000
PORT_MAX=64999

LOG_LEVEL=7
LOG_FACILITY=local0

$ rtpengine-ctl -ip 127.0.0.1:2224 list sessions all
callid:                                                   1143936550 | deletionmark:  no | created:  1611825323 | proxy:127.0.0.1:53599 | redis_keyspace:0 | foreign:no

$ rtpengine-ctl -ip 127.0.0.1:2224 list sessions 1143936550

callid:                                                   1143936550 | deletionmark:  no | created:  1611825323  | proxy:127.0.0.1:53599 | tos:184 | last_signal:1611825323 | redis_keyspace:0 | foreign:no

--- Tag '460470147' type: FROM_TAG, callduration 35.693376 , in dialogue with '5a8a89d1-4794-4775-a5b2-b23a945d73ef'
------ Media #1,        10.7.4.6:45304 <>  XX.XX.XX.XX:16001, 1709 p, 293644 b, 0 e, 1611825358 last_packet
------ Media #1,        10.7.4.6:45305 <>  XX.XX.XX.XX:16014 (RTCP), 10 p, 1040 b, 0 e, 1611825358 last_packet
--- Tag '5a8a89d1-4794-4775-a5b2-b23a945d73ef' type: TO_TAG, callduration 35.643778 , in dialogue with '460470147'
------ Media #1,        10.7.4.6:45284 <>    YY.YY.YY.YY:36864, 1735 p, 298420 b, 0 e, 1611825358 last_packet
------ Media #1,        10.7.4.6:45285 <>    YY.YY.YY.YY:36865 (RTCP), 7 p, 700 b, 0 e, 1611825355 last_packet

$ sudo lsof -P | grep UDP | grep rtpengine | sort -k 10 -u
rtpengine  7288             root    6u     IPv4            5261917       0t0        UDP localhost.localdomain:2223
rtpengine  7288 7289        root    6u     IPv4            5261917       0t0        UDP localhost.localdomain:2223
rtpengine  7288 7289        root    9u     IPv4            5286733       0t0        UDP hostname:45284
rtpengine  7288 7289        root   10u     IPv4            5286734       0t0        UDP hostname:45285
rtpengine  7288 7289        root   11u     IPv4            5286735       0t0        UDP hostname:45294
rtpengine  7288 7289        root   12u     IPv4            5286736       0t0        UDP hostname:45295
rtpengine  7288 7289        root   13u     IPv4            5286737       0t0        UDP hostname:45304
rtpengine  7288 7289        root   14u     IPv4            5286738       0t0        UDP hostname:45305
rtpengine  7288 7289        root   15u     IPv4            5286739       0t0        UDP hostname:45314
rtpengine  7288 7289        root   16u     IPv4            5286740       0t0        UDP hostname:45315
```

The [rtpengine.log](https://github.com/sipwise/rtpengine/files/5886386/rtpengine.log) (filtered for the call id 1143936550) is attached to the issue.

Does anybody know why this is happening? Is this normal or am I just doing it wrong? Any pointers/help appreciated.

Edit1: Needless to say that when I hangup the call, all 8 ports vanish.
Edit2: Just found out about the `list interfaces` command. When I issue it during a call I get

```
$ rtpengine-ctl -ip 127.0.0.1:2224 list interfaces
Interface 'prv' address '10.7.4.6' (IPv4)
 Port range: 45000 - 64999
 Ports used:     8 / 20000 (  0.0%)
 Last port used: 45476
Interface 'pub' address '10.7.4.6' (IPv4)
 Port range: 45000 - 64999
 Ports used:     8 / 20000 (  0.0%)
 Last port used: 45476
Interface 'prv' address '10.7.4.6' (IPv4)
 Port range: 45000 - 64999
 Ports used:     8 / 20000 (  0.0%)
 Last port used: 45476
Interface 'pub' address '10.7.4.6' (IPv4)
 Port range: 45000 - 64999
 Ports used:     8 / 20000 (  0.0%)
 Last port used: 45476
```

**Comment by rfuchs** [comment]
Can't reproduce this, not on 7.2.1 nor on current master. I'm guessing it's a config issue. Either a problem in the startup script with handling CLI arguments (we don't support the RH sysconfig one ourselves) and/or a conflict with an existing config file. So check if there's a config file that you're inadvertently using, and/or check how the config from the sysconfig file comes out in practice (check the CLI arguments it's running with through `ps axuww`)

**Comment by schlagert** [comment]
I also assumed that a configuration error is most likely but the actual command line did not look suspicious to me. However, switching to version 8.3.1.5 which solely uses `--config-file` instead of single `--interface` arguments fixed it. When I run `list interfaces` on this version/configuration I get the expected number of interfaces:
```
$ rtpengine -v
Version: 8.3.1.5-1.el7

$ rtpengine-ctl -ip 127.0.0.1:2224 list interfaces
Interface 'prv' address '10.7.4.6' (IPv4)
 Port range: 45000 - 64999
 Ports used:     0 / 20000 (  0.0%)
 Last port used: 45046
Interface 'pub' address '10.7.4.6' (IPv4)
 Port range: 45000 - 64999
 Ports used:     0 / 20000 (  0.0%)
 Last port used: 45046
```
Thanks for your feedback/input.

**Comment by khorsmann** [comment]
Hi, i found the issue.

it seems that the "sys-v" style rh-systems with /etc/sysconfig/rtpengine and the default /etc/rtpengine/rtpengine.conf got mixed up in the cli and maybe the daemon.

For example, i configured /etc/sysconfig/rtpengine and  /etc/rtpengine/rtpengine.conf was package default. i got this:
`[root@rtpnode1.a.rtpengine.is.awesome rtpengine]# rtpengine-ctl -ip 127.0.0.1:4444 list interfaces
Interface '1' address '172.18.32.50' (IPv4)
 Port range: 35000 - 65000
 Ports used:     0 / 30001 (  0.0%)
 Last port used: 37646
Interface '101' address '10.120.41.21' (IPv4)
 Port range: 35000 - 65000
 Ports used:     0 / 30001 (  0.0%)
 Last port used: 37686
Interface '1' address '172.18.32.50' (IPv4)
 Port range: 35000 - 65000
 Ports used:     0 / 30001 (  0.0%)
 Last port used: 37646
Interface '101' address '10.120.41.21' (IPv4)
 Port range: 35000 - 65000
 Ports used:     0 / 30001 (  0.0%)
 Last port used: 37686`


and if i moved /etc/rtpengine/rtpengine.conf to /etc/rtpengine/rtpengine.conf_ and restart the rtpengine process the command is "okay":

`[root@rtpnode1.a.rtpengine.is.awesome rtpengine]# /usr/local/sbin/rtp-engine-stats.sh
rtpengine,active=true own=0,foreign=0,rejected=0,total=0,avgtime=0.000,up=2
[root@rtpnode1.a.rtpengine.is.awesome rtpengine]# rtpengine-ctl -ip 127.0.0.1:4444 list interfaces
Interface '1' address '172.18.32.50' (IPv4)
 Port range: 35000 - 65000
 Ports used:     0 / 30001 (  0.0%)
 Last port used:     0
Interface '101' address '10.120.41.21' (IPv4)
 Port range: 35000 - 65000
 Ports used:     0 / 30001 (  0.0%)
 Last port used:     0
`

**Comment by schlagert** [comment]
Confirmed! That is the issue. Simply deleting the default file fixes the problem. Thank you @khorsmann!
