### ISSUE TITLE
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

### ISSUE THREAD

**Issue by lawensong** [sipwise/rtpengine#1174]
build  in docker.   system is ubuntu18.04-server.   docker net is  host.
dpkg-buildpackage -uc -us   get this error:

[core] bubble up pt 120 from idx 1 to 0
test ok: payload-tracker-test.c:74
test ok: payload-tracker-test.c:79
[core] bubble up pt 5 from idx 2 to 1
test ok: payload-tracker-test.c:83
[core] bubble up pt 10 from idx 3 to 2
[core] bubble up pt 10 from idx 2 to 1
[core] bubble up pt 10 from idx 1 to 0
[core] bubble down pt 120 from idx 1 to 2
test ok: payload-tracker-test.c:88
[core] bubble up pt 0 from idx 3 to 2
[core] bubble up pt 0 from idx 2 to 1
[core] bubble up pt 0 from idx 1 to 0
test ok: payload-tracker-test.c:93
[core] bubble up pt 1 from idx 4 to 3
[core] bubble up pt 1 from idx 3 to 2
[core] bubble up pt 1 from idx 2 to 1
test ok: payload-tracker-test.c:97
cc -g -D_GNU_SOURCE -std=c99 -o tests-preload.so -Wall -shared -fPIC tests-preload.c -ldl
make -C ../daemon
make[4]: Entering directory '/home/vik/rtpengine/daemon'
make rtpengine rtpengine.8
make[5]: Entering directory '/home/vik/rtpengine/daemon'
make[5]: 'rtpengine' is up to date.
make[5]: 'rtpengine.8' is up to date.
make[5]: Leaving directory '/home/vik/rtpengine/daemon'
make[4]: Leaving directory '/home/vik/rtpengine/daemon'
make all-daemon-tests
make[4]: Entering directory '/home/vik/rtpengine/t'
Makefile:105: warning: overriding recipe for target 'all-tests'
../lib/common.Makefile:7: warning: ignoring old recipe for target 'all-tests'
rm -rf fake-daemon-tests-main-sockets
mkdir fake-daemon-tests-main-sockets
LD_PRELOAD=../t/tests-preload.so RTPE_BIN=../daemon/rtpengine TEST_SOCKET_PATH=./fake-daemon-tests-main-sockets \
	   perl -I../perl auto-daemon-tests.pl
ok 1 - LD_PRELOAD present
ok 2 - preload library is active
ok 3 - RTPE_BIN points to executable
ok 4 - daemon launched in background

No such file or directory	...propagated at ../perl/NGCP/Rtpengine/AutoTest.pm line 67.
Died at ../perl/NGCP/Rtpengine/AutoTest.pm line 265.
END failed--call queue aborted.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 22 just after 4.
Makefile:117: recipe for target 'daemon-tests-main' failed
make[4]: *** [daemon-tests-main] Error 22
make[4]: Leaving directory '/home/vik/rtpengine/t'
Makefile:111: recipe for target 'daemon-tests' failed
make[3]: *** [daemon-tests] Error 2
rm sdp.strhash.c control_ng.strhash.c call_interfaces.strhash.c
make[3]: Leaving directory '/home/vik/rtpengine/t'
../lib/common.Makefile:4: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/vik/rtpengine/t'
Makefile:37: recipe for target 'check' failed
make[1]: *** [check] Error 2
make[1]: Leaving directory '/home/vik/rtpengine'
dh_auto_test: make -j1 check returned exit code 2
debian/rules:25: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

**Comment by lawensong** [comment]
no  bcg729 .    export DEB_BUILD_PROFILES="pkg.ngcp-rtpengine.nobcg729"

**Comment by rfuchs** [comment]
Looks like the compiled binary didn't start up. Can you confirm that the compiled binary (`.../daemon/rtpengine`) is usable on this system?

**Comment by lawensong** [comment]
-rwxrwxr-x 1 vik vik 4787656 Jan 29 21:43 daemon/rtpengine
i use vik  account. it looks like the user have permissions.   should i start up it ?

**Comment by rfuchs** [comment]
Sure, just try with `--help` or `--codecs` to see if it works at all

**Comment by lawensong** [comment]
I get this
./rtpengine: error while loading shared libraries: libbcg729.so.0: cannot open shared object file: No such file or directory

but i use 
export DEB_BUILD_PROFILES="pkg.ngcp-rtpengine.nobcg729"
how can i fix it?

**Comment by rfuchs** [comment]
Ok. so the dpkg profile only alters the build dependencies. The build system itself still looks for the bcg729 headers in the system and will use them if available. See `daemon/Makefile` for the locations that it checks.

**Comment by lawensong** [comment]
ok.  I first install bcg729, but it not work.
and then i use   export DEB_BUILD_PROFILES="pkg.ngcp-rtpengine.nobcg729",  so it still not work.
now  I use a new docker, retry again.
thank you!

**Comment by lawensong** [comment]
I first cole this issues

**Comment by rfuchs** [comment]
Try with ffb9fe64cb6e310945475cab098d7d14149def80 and see if that works for you
