### ISSUE TITLE
High cpu usage on rtpengine , while no high usage after some hours

### ISSUE THREAD

**Issue by davyvdm** [sipwise/rtpengine#1175]
Dear,

we notice on version rtpengine Version: 9.2.0.0+0~mr9.2.0.0 git-HEAD-d90e5bfa, on a very low load , I notice the load of the machine is low, yet the cpu load in ps auwx is high. Even if there are 0 calls, the load remains higher. Also we notice quality degradation at that time. 

After a restart of the daemon, the quality is perfect at high volumes (2000+ channels). 

How can I get better debugging info , to pin this down? 

--------------------

root@rtpv2-bru-1:$ rtpengine-ctl -ip <ip> -port 7788 list numsessions
Current sessions own: 24
Current sessions foreign: 0
Current sessions total: 24
Current transcoded media: 0

root@rtpv2-bru-1:$ ps auwx|grep rtpen

root     19023  120  0.5 9986408 546700 ?      SLsl Jan24 6437:27 /usr/sbin/rtpengine -f -E --no-log-timestamps --pidfile /run/ngcp-rtpengine-daemon.pid --config-file /etc/rtpengine/rtpengine-v2.conf --table 0

root@rtpv2-bru-1:$ uptime
 14:02:31 up 28 days, 21:37,  4 users,  load average: 0.01, 0.06, 0.15

**Comment by davyvdm** [comment]
Same on version Version: 8.5.0.0+0~mr8.5.0.0 git-master-b7d3db1a

**Comment by rfuchs** [comment]
The number you see for CPU in the `ps` output is cumulative. It's the total CPU time spent by the process through its entire lifetime. It does not necessarily reflect current CPU usage. Try `top` for a better view of current CPU usage.

**Comment by davyvdm** [comment]
Aah ok, didn't know that. Then this is not an issue.
