### ISSUE TITLE
error: implicit declaration of function ‘aead_request_set_ad’

### ISSUE THREAD

**Issue by mkezys** [sipwise/rtpengine#1176]
Hello,

Can't compile Kernel module: error: implicit declaration of function ‘aead_request_set_ad’

Maybe related to https://github.com/sipwise/rtpengine/commit/6602a3a7c5f43ccaf81a1cefc724b9f6ba8a30a3

Newest code from git, Centos 7.9.2009, gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC), kernel: 3.10.0-1160.11.1.el7.x86_64, kernel-devel-3.10.0-1160.11.1.el7.x86_64

/usr/src/rtpengine/kernel-module/xt_RTPENGINE.c:3953:2: error: implicit declaration of function ‘aead_request_set_ad’ [-Werror=implicit-function-declaration]
  aead_request_set_ad(req, r->header_len);

If I add ccflags-y += -Wno-implicit-function-declaration into Makefile it compiles with a warning:

WARNING: "aead_request_set_ad" [/usr/src/rtpengine/kernel-module/xt_RTPENGINE.ko] undefined!

Then:
cp -fr xt_RTPENGINE.ko /lib/modules/`uname -r`/extra/xt_RTPENGINE.ko
depmod -a
modprobe -v xt_RTPENGINE
insmod /lib/modules/3.10.0-1160.11.1.el7.x86_64/extra/xt_RTPENGINE.ko
modprobe: ERROR: could not insert 'xt_RTPENGINE': Unknown symbol in module, or unknown parameter (see dmesg)

dmesg:
[ 9237.888894] xt_RTPENGINE: loading out-of-tree module taints kernel.
[ 9237.889084] xt_RTPENGINE: module verification failed: signature and/or required key missing - tainting kernel
[ 9237.889179] xt_RTPENGINE: Unknown symbol aead_request_set_ad (err 0)

**Comment by rfuchs** [comment]
Aha, I was waiting for the usual CentOS complaints about this...

**Comment by mkezys** [comment]
Until we migrate to Debian, this works:
git checkout d466e5c326d55bb1d2b6509266a59bcce8a73444

**Comment by rfuchs** [comment]
Well it's not really about CentOS itself, but rather about the older kernel version they use... See if fd74907 works for you. Unfortunately I have no way to test if the cipher actually works like this...

**Comment by mkezys** [comment]
Now it compiles with this change on Centos 7, kernel 3.10.0-1160.11.1.el7.x86_64
