### ISSUE TITLE
Rtpengine doesn't remove sessions with a deletionmark: yes after the timeout 

### ISSUE THREAD

**Issue by davyvdm** [sipwise/rtpengine#1181]
Regularly I see the following behavior, sessions are marked for deletion , but don't get deleted anymore. Only when I manually terminate the sessions, with a small bash loop, the sessions decrease again linearly, and suddenly we hit a point where the sessions scheduled for deletion again get removed by rtpengine. It's as if one sessions blocks the ability to delete sessions, and once that session is gone, the system continues it's normal functioning.

I cannot reproduce it reliably, but I have it a few times a week, so I can gather better logging, if you can point me. 

I see it both on 8.5.x and on 9.2.x

root@rtpv2-bru-2:/var/log/rtpengine# date "+%s"
1612193329
root@rtpv2-bru-2:/var/log/rtpengine# rtpengine-ctl -ip x.y.z.a -port 7788 list sessions 8beff5ac-df44-1239-dc9a-0cc47a990e00

callid: 8beff5ac-df44-1239-dc9a-0cc47a990e00
deletionmark: yes
created: 1612193124
proxy: x.y.z.a :33951
tos: 184
last_signal: 1612193158
redis_keyspace: 0
foreign: no

--- Tag 'SBc1y7j4XUg0D', type: FROM_TAG, label '', branch '', callduration 46.770058, in dialogue with '8mmUFy0g0ySgQ'
------ Media #1 (audio over RTP/AVP) using PCMA/8000
-------- Port     x.y.z.a :30094 <>   x.y.z.a :38294, SSRC 23ec6c, 159 p, 27348 b, 0 e, 1612193162 ts
-------- Port     x.y.z.a :30095 <>   x.y.z.a :38295 (RTCP), SSRC 23ec6c, 32 p, 3184 b, 0 e, 1612193170 ts
--- Tag '8mmUFy0g0ySgQ', type: TO_TAG, label '', branch '', callduration 12.912445, in dialogue with 'SBc1y7j4XUg0D'
------ Media #1 (audio over RTP/AVP) using PCMA/8000
-------- Port     x.y.z.a :30078 <>     x.y.z.a :21564, SSRC 851947c, 1720 p, 295840 b, 0 e, 1612193162 ts
-------- Port     x.y.z.a :30079 <>     x.y.z.a :21565 (RTCP), SSRC 851947c, 32 p, 3584 b, 0 e, 1612193170 ts

**Comment by rfuchs** [comment]
Is the daemon heavily loaded? The timeouts are processed in a timer with a flexible interval. If the timer takes too long to run, then the interval is increased. You should see log messages to that effect when it happens (`Increasing timer run interval` ...)

**Comment by davyvdm** [comment]
I notice a few 'Increase timer run interval' in the logfile, yet not a lot. The daemon gets some load, perhaps 20caps, the machine has 48 cores, and we assigned 16 threads. 

We'll restart the machine with irqbalance on it, and check if this behavior comes back.

**Comment by davyvdm** [comment]
We upgraded to 9.2.0.0, we assigned more threads, we have irqbalance running, but also today we got into the same state... :( in the syslog of today we don't find back any Increasing timer run interval. Any debugging advice?

**Comment by rfuchs** [comment]
Enable debug logging and watch for the `timer run time` log messages. If you see those, then the timer is running.

If you can identify one such "stuck" call, post the full debug log for that call ID, start to finish. There might be a signalling issue.

**Comment by davyvdm** [comment]
with the loglevel on 7, I see the load increase a lot, and I see a few timer run time passing by, with durations from 0,02 -> 0,5 

I'll try to script to find the details of a stuck call - detail.

**Comment by rfuchs** [comment]
Cleaning up old tickets
