### ISSUE TITLE
Protocol error in packet / Error rewriting SDP

### ISSUE THREAD

**Issue by mkezys** [sipwise/rtpengine#1182]
Hello,

Trying to migrate a client from Freeswitch to Kamailio/RTPEngine (master).

Sometimes INVITEs comes with such SDP:

v=0
o=FreeSWITCH 1611811564 1611811565 IN IP4 xxx.xxx.xxx.xxx
s=FreeSWITCH
c=IN IP4 xxx.xxx.xxx.xxx
t=0 0
m=audio 21260 RTP/AVP 18 101
a=rtpmap:18 G729/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:18 annexb=no
a=fmtp:101 0-16
a=sendrecv
a=rtcp:21261
a=ptime:20
v=0
o=FreeSWITCH 1611811564 1611811565 IN IP4 xxx.xxx.xxx.xxx
s=FreeSWITCH
c=IN IP4 xxx.xxx.xxx.xxx
t=0 0
m=audio 21260 RTP/AVP 18 101
a=rtpmap:18 G729/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:18 annexb=no
a=fmtp:101 0-16
a=sendrecv
a=rtcp:21261
a=ptime:20
a=ice-ufrag:Dlo1egh4
a=ice-pwd:JcJADIGSIsPiEJcSZOOC338XOi
a=candidate:1hE3JdH4XfzxapeW 1 UDP 2130706431 xxx.xxx.xxx.xxx 21260 typ host
a=candidate:1hE3JdH4XfzxapeW 2 UDP 2130706430 xxx.xxx.xxx.xxx 21261 typ host

and RTPEngine gives: Protocol error in packet from xxx.xxx.xxx.xxx:52700: Error rewriting SDP

Problem is that Freeswitch accepts such calls and Kamailio/RTPEngine drops them. We need to accept and process such calls also, we do not have an option to ask the caller not to send such SDPs.
Freeswitch --(INVITE with double SDP)--> Freeswitch works. 
Freeswitch --(INVITE with double SDP)--> Kam/RTPEngine does not work.

Please point in the right direction. The closest TT I found: https://github.com/sipwise/rtpengine/issues/815

Should I somehow clean the SDP in the Kamailio? Should I use some flags for RTPEngine to be able to handle this?
Currently: trust-address replace-origin replace-session-connection rtcp-mux-demux ICE=remove RTP/AVP

Thank you.

**Comment by rfuchs** [comment]
I actually have a patch for this pending that I can push to master. I do have to wonder though if this is actually a valid use case? Because it kind of looks like an SDP rewrite gone wrong.

**Comment by mkezys** [comment]
How to define if it is valid? My guess is that it's not RFC compliant and SDP is messed up. SDP looks similar when in the internal loop RTPEngine does not have a loop-protect flag. Problem is that Freeswitch accepts this SDP and call proceeds. The client does not care about RFC compliant traffic, he just wants to accept it without dropping it.

Maybe I could test your patch somehow without you pushing it to master?

**Comment by rfuchs** [comment]
It actually is a valid SDP, but not a usage I've ever seen in the wild. I have seen this as the result of a broken rewrite operation though, that's why I'm asking.

Anyway, fix will be coming shortly.

**Comment by mkezys** [comment]
Wow, you are fast! I will be able to test next week. Thank you. Not used to such a fast response. Let me know how can I buy you a virtual beer!

**Comment by mkezys** [comment]
Tested, now works ok.
