### ISSUE TITLE
RTPENGINE Utiliy is not working on cent os7

### ISSUE THREAD

**Issue by kunal-k2** [sipwise/rtpengine#1184]
Hi Team,

We are using sipwise rtpengine on centos 7. To get call related statistics from rtpengine. We tried to use utils "rtpengine-ng-client" but some library is missing.

**Rtpengine process status:**
[root@ctl utils]# ps -ef |grep rtpengine
root      3924   668  0 00:11 pts/0    00:00:00 grep --color=auto rtpengine
root     20502 20499  0 Jan19 ?        00:10:02 ../sbin/rtpengine -f --num-threads 4 -i pub/10.211.160.132 -i priv/10.211.160.132 -n 127.0.0.1:8500 -c 127.0.0.1:8500 -m 32001 -M 32500 -T 184 -o 90 -d 4 -s 900 -p /var/run/rtpengine1.pid --scheduling rr --priority 37
[root@ctl utils]#

 **rtpengine-ng-client:**
When I ran rtpengine-ng-client script, I was getting Bencode.pm missing, so I have manually installed perl bencode library "perl-Convert-Bencode-1.03-9.el7.noarch.rpm"  
Now when I ran rtpengine-ng-client I am getting the below error 

[root@ctl utils]# ./rtpengine-ng-client list
_Undefined subroutine &Bencode::bencode called at /usr/local/lib64/perl5/NGCP/Rtpengine.pm line 33._ 

[rtpengine-ctl.txt](https://github.com/sipwise/rtpengine/files/5912579/rtpengine-ctl.txt)
[rtpengine-ng-client.txt](https://github.com/sipwise/rtpengine/files/5912581/rtpengine-ng-client.txt)

Let me know how to resolve it.

Thnaks,
Kunal

**Comment by rfuchs** [comment]
I already replied to you on the sr-users mailing list: https://lists.kamailio.org/pipermail/sr-users/2021-January/111668.html
