### ISSUE TITLE
c line with 0.0.0.0 not replaced with specified interface. 

### ISSUE THREAD

**Issue by johandeclercqdemocon** [sipwise/rtpengine#1185]
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: DEBUG: [dbf527d9-ec91-40bd-9d26-ce1328435104]: [control] Dump for 'offer' from 127.0.0.1:57217: { "sdp": "v=0
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: o=click-to-dial 0 0 IN IP4 0.0.0.0
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: s=session
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: c=IN IP4 0.0.0.0
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: t=0 0
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: m=audio 9 RTP/AVP 0
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: a=rtpmap:0 PCMU/8000
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: ", "ICE": "remove", "direction": [ "internal", "internal" ], "flags": [ "codec-strip-telephone-event", "codec-strip-PCMA", "codec-strip-PCMU", "codec-mask-all", "codec-transcode-PCMA", "codec-transcode-PCMU", "codec-offer-telephone-event" ], "replace": [ "origin", "session-connection" ], "transport-protocol": "RTP/AVP", "call-id": "dbf527d9-ec91-40bd-9d26-ce1328435104", "received-from": [ "IP4", "192.168.68.115" ], "from-tag": "533cb9e91f4b999cf76861cbb9ed54ed-94d4", "command": "offer" }
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: NOTICE: [dbf527d9-ec91-40bd-9d26-ce1328435104]: [core] Creating new call
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: DEBUG: [dbf527d9-ec91-40bd-9d26-ce1328435104]: [codec] Stripping codec 'PCMU/8000'
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: DEBUG: [dbf527d9-ec91-40bd-9d26-ce1328435104]: [codec] Codec 'PCMA/8000' added for transcoding with payload type 8
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: DEBUG: [dbf527d9-ec91-40bd-9d26-ce1328435104]: [codec] Restoring codec 'PCMU' from stripped codecs (1 payload types)
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: DEBUG: [dbf527d9-ec91-40bd-9d26-ce1328435104]: [codec] Default sink codec is PCMU/8000
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: DEBUG: [dbf527d9-ec91-40bd-9d26-ce1328435104]: [codec] Creating codec handler for PCMA/8000
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: DEBUG: [dbf527d9-ec91-40bd-9d26-ce1328435104]: [codec] Sink does not support codec PCMA/8000
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: DEBUG: [dbf527d9-ec91-40bd-9d26-ce1328435104]: [codec] Created transcode context for PCMA/8000 -> PCMU/8000 with DTMF output -1
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: DEBUG: [dbf527d9-ec91-40bd-9d26-ce1328435104]: [codec] Creating SSRC transcoder from PCMA/8000/1 to PCMU/8000/1
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: DEBUG: [dbf527d9-ec91-40bd-9d26-ce1328435104]: [core] Initialized encoder with frame size 160 samples
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: DEBUG: [dbf527d9-ec91-40bd-9d26-ce1328435104]: [codec] Encoder created with clockrate 8000, 1 channels, using sample format 1 (ptime 20 for 160 samples per frame and 160 samples (160 bytes) per packet, bitrate 0)
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: DEBUG: [dbf527d9-ec91-40bd-9d26-ce1328435104]: [codec] Creating codec handler for PCMU/8000
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: DEBUG: [dbf527d9-ec91-40bd-9d26-ce1328435104]: [codec] Sink supports codec PCMU/8000
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: DEBUG: [dbf527d9-ec91-40bd-9d26-ce1328435104]: [codec] Using passthrough handler for PCMU/8000
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: INFO: [dbf527d9-ec91-40bd-9d26-ce1328435104]: [codec] Enabling transcoding engine
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: DEBUG: [dbf527d9-ec91-40bd-9d26-ce1328435104]: [codec] Using passthrough handler with new SSRC for PCMU/8000
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: DEBUG: [dbf527d9-ec91-40bd-9d26-ce1328435104]: [core] set FILLED flag for stream 0.0.0.0:9
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: DEBUG: [dbf527d9-ec91-40bd-9d26-ce1328435104]: [core] set FILLED flag for stream 0.0.0.0:10
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: INFO: [dbf527d9-ec91-40bd-9d26-ce1328435104]: [control] Replying to 'offer' from 127.0.0.1:57217 (elapsed time 0.003679 sec)
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: DEBUG: [dbf527d9-ec91-40bd-9d26-ce1328435104]: [control] Response dump for 'offer' to 127.0.0.1:57217: { "sdp": "v=0
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: o=click-to-dial 0 0 IN IP4 192.168.68.115
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: s=session
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: c=IN IP4 0.0.0.0
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: t=0 0
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: m=audio 30000 RTP/AVP 8 0
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: a=rtpmap:8 PCMA/8000
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: a=rtpmap:0 PCMU/8000
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: a=sendrecv
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: a=rtcp:30001
Feb  6 09:02:01 debian10opensips31 rtpengine[34538]: ", "result": "ok" }

Richard, can you please indicate what attribute is wrong ? 
I want the 0.0.0.0 to be replaced with 192.168.68.115

rtpengine.conf: 

[rtpengine]

table = 0
interface = internal/192.168.68.115;external/192.168.68.115
listen-ng = 127.0.0.1:60000
timeout = 60
silent-timeout = 3600
tos = 184
port-min = 30000
port-max = 4000 
 log-level = 7
 log-facility = local0

version used:  9.3.0.0+0~mr9.3.0.0 git-master-79bb147a

**Comment by rfuchs** [comment]
That looks like a trickle ICE address, except that there's no other ICE attributes in the SDP, which is why it's not seen as trickle ICE at all but instead treated as an intentionally muted stream. So the fact that it's muted is simply passed along.

**Comment by johandeclercqdemocon** [comment]
So I can’t change to normal ip with send-only or even inactive ?

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Richard Fuchs <notifications@github.com>
Verzonden: Saturday, February 6, 2021 3:26:24 PM
Aan: sipwise/rtpengine <rtpengine@noreply.github.com>
CC: johandeclercqdemocon <johan@democon.be>; Author <author@noreply.github.com>
Onderwerp: Re: [sipwise/rtpengine] c line with 0.0.0.0 not replaced with specified interface. (#1185)


That looks like a trickle ICE address, except that there's no other ICE attributes in the SDP, which is why it's not seen as trickle ICE at all but instead treated as an intentionally muted stream. So the fact that it's muted is simply passed along.

**Comment by rfuchs** [comment]
No we don't have such an option right now. (It should change to sendonly, but the zero IP would remain.)

**Comment by johandeclercqdemocon** [comment]
Ok, then I will rewrite it in opensips.

Thanks for the quick response Richard

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Richard Fuchs <notifications@github.com>
Verzonden: Saturday, February 6, 2021 8:12:02 PM
Aan: sipwise/rtpengine <rtpengine@noreply.github.com>
CC: johandeclercqdemocon <johan@democon.be>; Author <author@noreply.github.com>
Onderwerp: Re: [sipwise/rtpengine] c line with 0.0.0.0 not replaced with specified interface. (#1185)


No we don't have such an option right now. (It should change to sendonly, but the zero IP would remain.)

**Comment by johandeclercqdemocon** [comment]
Of topic Richard, where I can find documentation on making rtpengine HA
with redis ?

**Comment by johandeclercqdemocon** [comment]
Forget about this.

I overlooked it in the wiki.
