### ISSUE TITLE
Codec Reordering Breaking change for WebRTC -> SIP in 9.3... release

### ISSUE THREAD

**Issue by digipigeon** [sipwise/rtpengine#1187]
f2d7e71 (TT#108552 update crypto suite preference ordering) appears to break WebRTC in Chrome.

A WebRTC -> SIP call audio works for 3 seconds then drops (from SIP to WebRTC, SIP can still hear WebRTC audio)
This seems to work fine for a SIP-> WebRTC call two way audio no drops.

I have narrowed this down
f2d7e71 - and onwards does not work
0898923 - and prior works

I suspect that this is because the # 1 priority has been changed from AES128_CM_SHA1 to AES_256_GCM.

https://www.chromestatus.com/feature/5659196699705344#details does state support for AES_256_GCM

My Browser also reports (SSL Labs):
TLS_AES_128_GCM_SHA256
TLS_AES_256_GCM_SHA384

I am going to continue investigating if this is some default which I can modify from within sip.js. Failing that I know that we can manipulate the options in the offer / answer.

I don't necessarily think that this is a bug inside rtpengine yet until I can confirm that with extra testing.

Wanted to report this as I am sure that others will hit this problem, maybe someone else has had this problem and can assist.

**Comment by rfuchs** [comment]
Crypto suite order shouldn't matter for WebRTC because negotiation happens through DTLS and (AFAIK) order isn't important there (assuming you have SDES disabled). So I'd more strongly suspect the addition of the AEAD crypto suites rather than the crypto suite order.

**Comment by digipigeon** [comment]
After noticing #1190 I decided to disable kernel tables and was pleased to confirm that the audio did not drop, I believe that this is related.

**Comment by digipigeon** [comment]
Just incase you needed this info for this ticket as well, in answer to your question on #1190.

```
Feb 11 15:18:03 rtp-test-1 rtpengine[467221]: INFO: [lqcvf3ni9f3ukhe33c86 port 30010]: [crypto] DTLS-SRTP successfully negotiated using AEAD_AES_256_GCM
Feb 11 15:18:03 rtp-test-1 rtpengine[467221]: INFO: [lqcvf3ni9f3ukhe33c86 port 30010]: [crypto] DTLS-SRTP successfully negotiated using AEAD_AES_256_GCM
```

**Comment by rfuchs** [comment]
Try with the patch referenced above (b5f8c7c)

**Comment by rfuchs** [comment]
Try with the patch referenced above (2e52e0be)

**Comment by digipigeon** [comment]
Hi Richard, confirmed that this has fixed the problem, thank you for you speedy patch.
