### ISSUE TITLE
DTMF is not recognized correctly

### ISSUE THREAD

**Issue by ccppprogrammer** [sipwise/rtpengine#1188]
Hello Richard!

I have a really weird problem with `DTMF` recognition with `rtpegnine`.
In some unknown cases (`Screenshot 1`), `DTMF` from the same caller and from the same carrier is not recognized and in this case there are no records in the system log, and even more `rtpegnine` skips forwarding these packets to the downlink.
At the same time wireshark sees these `DTMF` events and reports them as packet loss (`Screenshot 2`).
For successful calls (`Screenshot 2`), `rtpegnine` recognizes the `DTMF` correctly, logs them to the system log and forwards them to the downlink.
I have tried both `rtpegnine` versions  `8.4.1.2+0~mr8.4.1.2` and `9.0.1.10+0~mr9.0.1.10` and both versions have the same problem.
If it helps, I can send you privately dumps with SIP and RTP packets for successful and unsuccessful calls.

Thanks in advance!

<details>
<summary>OS</summary>

```
# lsb_release -a
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```
</details>

<details>
<summary>uname -a</summary>

```
# uname -a
Linux ip 4.19.0-9-cloud-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
```
</details>

<details>
<summary>rtpengine -v</summary>

```
# rtpengine -v
Version: 9.0.1.10+0~mr9.0.1.10
```
</details>

<details>
<summary>rtpengine.conf</summary>

```
[rtpengine]
no-fallback = false
table = -1
interface = internal/x.x.x.x;external/x.x.x.x!y.y.y.y
listen-ng = x.x.x.x:2223
listen-tcp = x.x.x.x:2222
listen-cli = 127.0.0.1:9900
timeout = 60
offer-timeout = 60
silent-timeout = 3600
tos = 184
control-tos = 184
delete-delay = 0
final-timeout = 10800
foreground = false
pidfile = /run/rtpengine/rtpengine.pid
num-threads = 16
port-min = 10240
port-max = 65535
max-sessions = 5000
log-level = 0
log-stderr = false
log-facility = daemon
log-facility-dtmf = daemon
```
</details>

<details>
<summary>Screenshot 1</summary>

![image](https://user-images.githubusercontent.com/7936874/107573278-611ba900-6bfe-11eb-8402-271f1308277e.png)
</details>

<details>
<summary>Screenshot 2</summary>

![image](https://user-images.githubusercontent.com/7936874/107573492-a6d87180-6bfe-11eb-9987-7810c95ecd90.png)
</details>

<details>
<summary>Screenshot 3</summary>

![image](https://user-images.githubusercontent.com/7936874/107574336-a8ef0000-6bff-11eb-9752-2d74157be59c.png)
</details>

**Comment by rfuchs** [comment]
Well those two traces look basically identical, so there isn't anything to go on. Enable debug logging and see if there's any relevant output in the log. You can also try a newer version to see if it makes a difference.

**Comment by ccppprogrammer** [comment]
Hello Richard!
Thanks for the quick response!
I have updated `rtpegnine` to version `9.2.1.4+0~mr9.2.1.4`, but the `DTMF` problem still exists.
I will try to get the full debug log, but it will be difficult as this is a production system with high volume of calls.

**Comment by ccppprogrammer** [comment]
@rfuchs I've emailed you the `rtpengine` debug log and a fresh SIP dump.

**Comment by rfuchs** [comment]
There's simply no mention in the log of these DTMF packets being received at all. I suspect they're being dropped on a network level, before rtpengine even gets a chance to see them. UDP checksums in pcaps are notoriously unreliable, but in this case it looks like they might be correct: The only difference I see between the working and the non-working pcaps is that in the non-working pcaps, the UDP checksum on the inbound DTMF packets is wrong, while it's correct on all other packets. In the working pcap, the checksum is correct on all packets. So it looks like it's the kernel which is (correctly) dropping these packets. (Screenshots without identifying information attached)
![Screenshot_2021-02-12_08-15-57](https://user-images.githubusercontent.com/3227418/107772728-9d3c3000-6d0a-11eb-804b-ea415561e855.png)
![Screenshot_2021-02-12_08-15-21](https://user-images.githubusercontent.com/3227418/107772731-9d3c3000-6d0a-11eb-93d4-29f5727a3130.png)

**Comment by ccppprogrammer** [comment]
You're right! The problem was on the telcobridges freesbc side, which were generating packets with incorrect checksums.
Thanks for the help!

**Comment by mmarkwood611** [comment]
@ccppprogrammer  Were you able to resolve this issue on the FreeSBC side? If so can you share how ?
