### ISSUE TITLE
How to identify RTP Streams forwarded to a SOCK_SEQPACKET server ?

### ISSUE THREAD

**Issue by anis-bedhiafi** [sipwise/rtpengine#1191]
Hi,

Using the recording daemon I was able to forward RTP frames to a SOCK_SEQPACKET server written in C.

rtpengine.conf

recording-dir = /var/spool/rtpengine
recording-method = proc
recording-format = raw

rtpengine-recording.conf

forward-to = /run/rtpengine/sock
output-format = none
spool-dir = /var/spool/rtpengine

The recording daemon is forwarding the following streams:

stream tag-0-media-1-component-2-RTCP-id-3
stream tag-0-media-1-component-1-RTP-id-2
stream tag-1-media-1-component-2-RTCP-id-1
stream tag-1-media-1-component-1-RTP-id-0

I am only interested in the two RTP streams. What I know about raw audio packets is they don't include any headers to parse.

The problem is: On the socket server, I can't identify which packet belongs to which stream as the goal is to feed the RTP packets in real time into a speech recognition engine and I need to identify the two parties of the call.

So how can I accomplish this ? Is there a way to flag RTP packets ?

Thank you any suggestions.

**Comment by rfuchs** [comment]
The forwarding stuff isn't our code, but AFAIK the packets you get forwarded are not raw audio packets, but rather raw RTP packets. So they include the complete RTP header. You can use the SSRC to identify a particular media stream.

**Comment by anis-bedhiafi** [comment]
Okay, thank you @rfuchs.
I will do my tests and post the result here.

**Comment by rfuchs** [comment]
Cleaning up old tickets
