### ISSUE TITLE
rtpengine[959]: segfault - Debian 8.11 Jessie

### ISSUE THREAD

**Issue by jonhvoxbox** [sipwise/rtpengine#1192]
Hi Guys,

We are running rtpengine in debian, and the application crashed for the first time after a number of years in operation!

Please could you advise relating to the following;

Version: 6.4.0.0+0~mr6.4.0.0 git-master-a9ec666

I can see the following from the logs;

Feb 15 14:51:46 Dub-rtpengine1 rtpengine[627]: [1613400706.015404] WARNING: [06a07c6010eaecda24ee2a6261540385@10.200.40.136:5060 port 44380]: No support for kernel packet forwarding available (inter
face to kernel module not open)
Feb 15 14:51:46 Dub-rtpengine1 rtpengine[627]: [1613400706.025685] WARNING: [06a07c6010eaecda24ee2a6261540385@10.200.40.136:5060 port 31822]: No support for kernel packet forwarding available (inter
face to kernel module not open)
Feb 15 14:51:49 Dub-rtpengine1 kernel: [5421565.528177] rtpengine[959]: segfault at 20 ip 00007f36e954077a sp 00007f36c6ff9f08 error 6 in libpthread-2.19.so[7f36e9535000+18000]
Feb 15 14:51:50 Dub-rtpengine1 systemd[1]: ngcp-rtpengine-daemon.service: main process exited, code=killed, status=11/SEGV
Feb 15 14:51:51 Dub-rtpengine1 systemd[1]: Unit ngcp-rtpengine-daemon.service entered failed state.

Would you recommend we update or how can  I look to troubleshoot further? I noticed at the time memory was running low.

Many thanks

Jon

**Comment by rfuchs** [comment]
You should have gotten a core dump. Make sure the -dbg or -dbgsym packages are installed, then load up the core dump in gdb and pull a backtrace (`thread apply all bt`)

Since this is a very old version, it's possible that this is already fixed. See the commits that you seem to be missing in the code branch you're using: https://github.com/sipwise/rtpengine/commits/mr6.4

**Comment by jonhvoxbox** [comment]
Thanks for the response Richard, the core dump wasnt enabled, I will rectify and look to upgrade.

Thanks!
