### ISSUE TITLE
Rewrite Rule 

### ISSUE THREAD

**Issue by ideatells** [sipwise/rtpengine#1193]
Hi,

I am using mr8.5.3

I created a rewrite rule Outbound for Callee with the following values:
Match:
^([1-9]+)$

Replace:
54545\1

Enabled:
yes

WHen I try to place a call wilt outbound number: 1800654123 or 9165475633 than the prefix is not added in front of the 1 or 9.
But when I call a number in the range of 2-8 for example: 5975644555 than the prefix of 54545 is being placed in front of 5975644555 .

**Comment by rfuchs** [comment]
This is the rtpengine Github and not the right place for support for other Sipwise products. You want to be posting to the spce-users mailing list instead: https://lists.sipwise.com/mailman/listinfo/spce-user_lists.sipwise.com
