### ISSUE TITLE
How to identify sequence of RTP streams when writing to file without "output-mixed" option

### ISSUE THREAD

**Issue by ivlovric** [sipwise/rtpengine#1195]
Hi,

one question regarding rtp streams that we are writing locally to disk without rtpengine-recording native mixing option and post-processing them with external application. In some cases we have **early media** and there is more than 2 rtp streams which we have problem merging into one recording file in post-processing.

Is there any way to distinguish files that are recorded besides by ssrc? For us it would be of great benefit to have some info somewhere (filename, metadata, somewhere else) of order of streams to know how to merge them afterwards.

For example: one call, 3 rtp streams
_535fb7c09c915cf3db202d6b2240eeb5%4010.86.134.78-1d38bc81f143f832-0d4d9c00.wav
535fb7c09c915cf3db202d6b2240eeb5%4010.86.134.78-1d38bc81f143f832-225943fe.wav
535fb7c09c915cf3db202d6b2240eeb5%4010.86.134.78-1d38bc81f143f832-574f3639.wav_

Thansk a lot,
I

**Comment by rfuchs** [comment]
There's some metadata written to the database backend if you have that enabled. I'm not sure if it's enough for what you want to do though.

**Comment by ivlovric** [comment]
Thanks, we are aware of database backend for metadata but decided not to have it in our architecture. Will take a look at it once again to see if there is something that can be used to properly merge recordings in post-process custom backend.

Maybe rfuchs if you can give us first hand advice if something can be done on rtpengine-recording service part that is constructing filenames of each rtp stream? For instance, for each rtp stream to have additional suffix on recorded filename that correlate to sequence when that specific rtp stream arrived to rtpengine?

I

**Comment by rfuchs** [comment]
I'm working on adding support for configurable output file name patterns right now.
