### ISSUE TITLE
only the last a=rtcp-fb line per codec in SDP is forwarded

### ISSUE THREAD

**Issue by hrickes** [sipwise/rtpengine#1196]
Hi,

I miss the full set of a=rtcp-fb lines per codec in the forwarded SDP. Only the last one is forwarded. 

[1613836606.161311] INFO: [crypto] Generating new DTLS certificate
[1613836606.217478] INFO: [core] Startup complete, version mr9.2.1.4
[1613836633.336404] DEBUG: [control] Adding a proxy for control ng stats:172.22.11.7
[1613836633.336494] INFO: [1qfveor9b8uf2pj2hoa0]: [control] Received command 'offer' from 172.22.11.7:53738
[1613836633.336591] DEBUG: [1qfveor9b8uf2pj2hoa0]: [control] Dump for 'offer' from 172.22.11.7:53738: { "sdp": "v=0
o=mozilla...THIS_IS_SDPARTA-85.0.2 5816632414033028191 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 0D:DA:59:5A:51:85:36:DE:BD:56:53:B4:E0:0A:02:3B:48:E4:40:8F:D3:1E:5D:0E:AA:8A:CF:87:90:5B:03:1C
a=group:BUNDLE 0 1
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 61757 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 79.221.77.104
a=candidate:0 1 UDP 2122252543 2003:e3:6748:6800:757d:4495:f75:10db 61755 typ host
a=candidate:2 1 UDP 2122187007 fd00::757d:4495:f75:10db 61756 typ host
a=candidate:4 1 UDP 2122055935 172.31.2.200 61757 typ host
a=candidate:6 1 UDP 2122121471 192.168.56.1 61758 typ host
a=candidate:8 1 TCP 2105524479 2003:e3:6748:6800:757d:4495:f75:10db 9 typ host tcptype active
a=candidate:9 1 TCP 2105458943 fd00::757d:4495:f75:10db 9 typ host tcptype active
a=candidate:10 1 TCP 2105327871 172.31.2.200 9 typ host tcptype active
a=candidate:11 1 TCP 2105393407 192.168.56.1 9 typ host tcptype active
a=candidate:0 2 UDP 2122252542 2003:e3:6748:6800:757d:4495:f75:10db 61759 typ host
a=candidate:2 2 UDP 2122187006 fd00::757d:4495:f75:10db 61760 typ host
a=candidate:4 2 UDP 2122055934 172.31.2.200 61761 typ host
a=candidate:6 2 UDP 2122121470 192.168.56.1 61762 typ host
a=candidate:8 2 TCP 2105524478 2003:e3:6748:6800:757d:4495:f75:10db 9 typ host tcptype active
a=candidate:9 2 TCP 2105458942 fd00::757d:4495:f75:10db 9 typ host tcptype active
a=candidate:10 2 TCP 2105327870 172.31.2.200 9 typ host tcptype active
a=candidate:11 2 TCP 2105393406 192.168.56.1 9 typ host tcptype active
a=candidate:5 1 UDP 1685856255 79.221.77.104 61757 typ srflx raddr 172.31.2.200 rport 61757
a=candidate:5 2 UDP 1685856254 79.221.77.104 61761 typ srflx raddr 172.31.2.200 rport 61761
a=sendrecv
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=fmtp:101 0-15
a=ice-pwd:ace3b255f3bcd68e41c5084537028cea
a=ice-ufrag:8160e103
a=mid:0
a=msid:{c825508b-e40d-460e-be6f-26fb8c3f2c11} {3145884b-836d-4ddb-80e5-5a18aafc2609}
a=rtcp:61761 IN IP4 79.221.77.104
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=setup:actpass
a=ssrc:2836073120 cname:{50705200-3282-4386-9519-86ec4dad6c2d}
m=video 61765 UDP/TLS/RTP/SAVPF 120 124 121 125 126 127 97 98
c=IN IP4 79.221.77.104
a=candidate:0 1 UDP 2122252543 2003:e3:6748:6800:757d:4495:f75:10db 61763 typ host
a=candidate:2 1 UDP 2122187007 fd00::757d:4495:f75:10db 61764 typ host
a=candidate:4 1 UDP 2122055935 172.31.2.200 61765 typ host
a=candidate:6 1 UDP 2122121471 192.168.56.1 61766 typ host
a=candidate:8 1 TCP 2105524479 2003:e3:6748:6800:757d:4495:f75:10db 9 typ host tcptype active
a=candidate:9 1 TCP 2105458943 fd00::757d:4495:f75:10db 9 typ host tcptype active
a=candidate:10 1 TCP 2105327871 172.31.2.200 9 typ host tcptype active
a=candidate:11 1 TCP 2105393407 192.168.56.1 9 typ host tcptype active
a=candidate:0 2 UDP 2122252542 2003:e3:6748:6800:757d:4495:f75:10db 61767 typ host
a=candidate:2 2 UDP 2122187006 fd00::757d:4495:f75:10db 61768 typ host
a=candidate:4 2 UDP 2122055934 172.31.2.200 61769 typ host
a=candidate:6 2 UDP 2122121470 192.168.56.1 61770 typ host
a=candidate:8 2 TCP 2105524478 2003:e3:6748:6800:757d:4495:f75:10db 9 typ host tcptype active
a=candidate:9 2 TCP 2105458942 fd00::757d:4495:f75:10db 9 typ host tcptype active
a=candidate:10 2 TCP 2105327870 172.31.2.200 9 typ host tcptype active
a=candidate:11 2 TCP 2105393406 192.168.56.1 9 typ host tcptype active
a=candidate:5 1 UDP 1685856255 79.221.77.104 61765 typ srflx raddr 172.31.2.200 rport 61765
a=candidate:5 2 UDP 1685856254 79.221.77.104 61769 typ srflx raddr 172.31.2.200 rport 61769
a=sendrecv
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:5 urn:ietf:params:rtp-hdrext:toffset
a=extmap:6/recvonly http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1
a=fmtp:120 max-fs=12288;max-fr=60
a=fmtp:124 apt=120
a=fmtp:121 max-fs=12288;max-fr=60
a=fmtp:125 apt=121
a=fmtp:127 apt=126
a=fmtp:98 apt=97
a=ice-pwd:ace3b255f3bcd68e41c5084537028cea
a=ice-ufrag:8160e103
a=mid:1
a=msid:{c825508b-e40d-460e-be6f-26fb8c3f2c11} {35eedc36-ee76-47ab-8bc1-0e400d2b544b}
a=rtcp:61769 IN IP4 79.221.77.104
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 ccm fir
a=rtcp-fb:120 goog-remb
a=rtcp-fb:120 transport-cc
a=rtcp-fb:121 nack
a=rtcp-fb:121 nack pli
a=rtcp-fb:121 ccm fir
a=rtcp-fb:121 goog-remb
a=rtcp-fb:121 transport-cc
a=rtcp-fb:126 nack
a=rtcp-fb:126 nack pli
a=rtcp-fb:126 ccm fir
a=rtcp-fb:126 goog-remb
a=rtcp-fb:126 transport-cc
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 goog-remb
a=rtcp-fb:97 transport-cc
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:120 VP8/90000
a=rtpmap:124 rtx/90000
a=rtpmap:121 VP9/90000
a=rtpmap:125 rtx/90000
a=rtpmap:126 H264/90000
a=rtpmap:127 rtx/90000
a=rtpmap:97 H264/90000
a=rtpmap:98 rtx/90000
a=setup:actpass
a=ssrc:678999060 cname:{50705200-3282-4386-9519-86ec4dad6c2d}
a=ssrc:3129795366 cname:{50705200-3282-4386-9519-86ec4dad6c2d}
a=ssrc-group:FID 678999060 3129795366
", "DTLS": "off", "ICE": "remove", "flags": [ "trust-address", "loop-protect", "port-latching" ], "replace": [ "session-connection" ], "transport-protocol": "RTP/SAVP", "rtcp-mux": [ "demux" ], "call-id": "1qfveor9b8uf2pj2hoa0", "received-from": [ "IP4", "127.0.0.1" ], "from-tag": "a933ep3q9d", "command": "offer" }
[1613836633.337619] NOTICE: [1qfveor9b8uf2pj2hoa0]: [core] Creating new call
[1613836633.348641] INFO: [1qfveor9b8uf2pj2hoa0]: [control] Replying to 'offer' from 172.22.11.7:53738 (elapsed time 0.011632 sec)
[1613836633.348729] DEBUG: [1qfveor9b8uf2pj2hoa0]: [control] Response dump for 'offer' to 172.22.11.7:53738: { "sdp": "v=0
o=mozilla...THIS_IS_SDPARTA-85.0.2 5816632414033028191 0 IN IP4 0.0.0.0
s=-
t=0 0
a=msid-semantic:WMS *
a=rtpengine:0dfd98ad6c55
m=audio 25500 RTP/SAVP 109 9 0 8 101
c=IN IP4 172.22.11.7
a=msid:{c825508b-e40d-460e-be6f-26fb8c3f2c11} {3145884b-836d-4ddb-80e5-5a18aafc2609}
a=ssrc:2836073120 cname:{50705200-3282-4386-9519-86ec4dad6c2d}
a=mid:0
a=rtpmap:109 opus/48000/2
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=rtcp:25501
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:ejvYUDmtvqJIPCO7UQSdfLSkyCG0aDFeKR+7hCsI
a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:trB0S/5eCVA/XQoYenvA9LyyJvbvHeYvkJndOoLz
a=crypto:3 AES_192_CM_HMAC_SHA1_80 inline:PJd+SnjRs/W7RUVHhHIJeSlPaF9KAk5EtXsXUPkyc0bmECPl/ZM
a=crypto:4 AES_192_CM_HMAC_SHA1_32 inline:ZkT6uaka5jmZ2dIcW+5wG68pUsS4ausr2k5W/eyccPwn0UhMeSU
a=crypto:5 AES_256_CM_HMAC_SHA1_80 inline:MKlOIgiiLecyEVkK5mAo8w9NmVtZYjaY2kjPM2kyvcqCyt6tliJOi/962cajtg
a=crypto:6 AES_256_CM_HMAC_SHA1_32 inline:g36bfklaZro0s5cgOpy+MjKX0/y2IrjdWDyG/kgwlu9e2UZjwgpT+qlyCtAefA
a=crypto:7 F8_128_HMAC_SHA1_80 inline:gh/tLDHqb2zrId2aFkgrpepLVl76hBGXP20szM9K
a=crypto:8 F8_128_HMAC_SHA1_32 inline:hB4+Qtmjm4BRTA46TB7joRiCdjmeA/cYfCcfA1z3
a=crypto:9 NULL_HMAC_SHA1_80 inline:5to+n5ucxc+xHBScJ2H90VrdDRyUgVN15wHlvIsU
a=crypto:10 NULL_HMAC_SHA1_32 inline:eoE9P/tH+YLtdsUlmvCN6pwLbzd2Ws2ADdSH/aE8
m=video 25526 RTP/SAVP 120 124 121 125 126 127 97 98
c=IN IP4 172.22.11.7
a=msid:{c825508b-e40d-460e-be6f-26fb8c3f2c11} {35eedc36-ee76-47ab-8bc1-0e400d2b544b}
a=rtcp-rsize
a=ssrc:678999060 cname:{50705200-3282-4386-9519-86ec4dad6c2d}
a=ssrc:3129795366 cname:{50705200-3282-4386-9519-86ec4dad6c2d}
a=ssrc-group:FID 678999060 3129795366
a=mid:1
a=rtpmap:120 VP8/90000
a=fmtp:120 max-fs=12288;max-fr=60
a=rtcp-fb:120 transport-cc
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=120
a=rtpmap:121 VP9/90000
a=fmtp:121 max-fs=12288;max-fr=60
a=rtcp-fb:121 transport-cc
a=rtpmap:125 rtx/90000
a=fmtp:125 apt=121
a=rtpmap:126 H264/90000
a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=rtcp-fb:126 transport-cc
a=rtpmap:127 rtx/90000
a=fmtp:127 apt=126
a=rtpmap:97 H264/90000
a=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1
a=rtcp-fb:97 transport-cc
a=rtpmap:98 rtx/90000
a=fmtp:98 apt=97
a=sendrecv
a=rtcp:25527
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:o+x9qD4UHDd9B0S6avSOjnYcUV/QqhbYdtGD8i9p
a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:2ONb3dmKnndcYQNhklR1oPl4tmf0KwFASbUQtwN/
a=crypto:3 AES_192_CM_HMAC_SHA1_80 inline:TLR73Cfqw3j3jX9nd2U81PSjk8F+CwiXGKvAOmWFnmbl33hd/fA
a=crypto:4 AES_192_CM_HMAC_SHA1_32 inline:9ZjxCC59O+XC4eiGvjZ3tjzK4x1mlPTvSHBK+QBLKZx391vs2HY
a=crypto:5 AES_256_CM_HMAC_SHA1_80 inline:Kep4zw61i6wTzBRxFIMut4Zl6ZlkmrYZNo+q1kyrr0dS5Dz0DpEgAkttZKLZ2w
a=crypto:6 AES_256_CM_HMAC_SHA1_32 inline:K0v00GISmBEYLDFBLWi0mOYf6e0qEm5R5eLKF0tfHO6JktIqiEI+4kD4cQD5Cw
a=crypto:7 F8_128_HMAC_SHA1_80 inline:0aeBAO9zFk3BoNZmFj1qfOm3RuMXFdclUMfsA+rJ
a=crypto:8 F8_128_HMAC_SHA1_32 inline:dMp2fNFISzkRLIh88vgN9XhwWP+O0Wn3+eFWK/xE
a=crypto:9 NULL_HMAC_SHA1_80 inline:f99l++3NIXSsa8TugCsCseIWvwkE67X2MI3DFAjY
a=crypto:10 NULL_HMAC_SHA1_32 inline:oWncigScJT78zIrDgbbzPoWmVUC/CrETDq49K2pH
", "result": "ok" }

Thanks

**Comment by rfuchs** [comment]
Try with commit 25129fa - that should fix it.

**Comment by hrickes** [comment]
I have tried the patch and it fixes the issue. Thank you!
