### ISSUE TITLE
srtp failures with crypto suite AEAD_AES_256_GCM

### ISSUE THREAD

**Issue by juha-h** [sipwise/rtpengine#1197]
I have rtpengine between two baresip SIP UAs.  One baresip is configured without media encoding and the other is configured with srtp.

Call from srtp baresip to the other works fine as it offers AES_CM_128_HMAC_SHA1_80 crypto suite to rtpengine and rtpengine then decrypts the media to the other baresip.

The other way there is an issue. rtpengine offers a long list of crypto suites to baresip and baresip chooses this:
```
srtp: audio: SRTP is Enabled (cryptosuite=AEAD_AES_256_GCM)
```
However, baresip does not like what it gets:
```
srtp: AEAD_AES_256_GCM: srtp keylen is 42 (should be 44)
```
and starts to produce lots of error messages:
```
srtp: failed to decrypt RTP packet with 188 bytes (Unknown error 217)
srtp: failed to decrypt RTP packet with 188 bytes (Unknown error 217)
...
```
I don't have enough knowledge of the crypto suits and thus don't know whose fault this is.  I thus posted a similar issue also to baresip project.

**Comment by juha-h** [comment]
Tested with Linphone and same issue.  I don't know if baresip and linphone use the same crypto lib.

**Comment by rfuchs** [comment]
Try adding the option `pad-crypto` to your offer flags.

**Comment by juha-h** [comment]
That was it.  Thanks.
