### ISSUE TITLE
recording-daemon broken: create_parent_dirs() causes infinite loop

### ISSUE THREAD

**Issue by braddockcg** [sipwise/rtpengine#1205]
On master, recording-daemon's create_parent_dirs() is very broken and lands in an infinite loop calling `mkdir()` if part of the path already exists.  Looks like the code in question was added just a few weeks ago.

Here is the offending code:
https://github.com/sipwise/rtpengine/blob/master/recording-daemon/output.c#L50

I reverted to `mr8.5.3.2` and things work (is that the best stable version to be on now?  master seems in a state of rapid flux).

**Comment by rfuchs** [comment]
The latest stable release is mr9.3, and the latest LTS is mr8.5. I suggest staying on the main mrX.Y branches instead of one of the patch or tagged releases, as they get the most fixes.
