### ISSUE TITLE
Stopped receiving media somewhere between versions 8.3.2.3 and 8.4.1.5

### ISSUE THREAD

**Issue by githubsw** [sipwise/rtpengine#1206]
Hello,

I currently use rtpengine with Kamailio and Asterisk.  I decided to upgrade to a newer version and installed the latest release; at this point I no longer had media in either direction.  I started backing out to different versions and found that version 8.3.2.3 works, but version 8.4.1.5+ has no media.  Something appears to have happened somewhere between these versions.  I noticed in the traces that the non working version no longer has ice-candidates in the INVITE or 200 OK back.  As a side note, the SIP handshake still appears to work just fine.

Thank you, and thank you for this product!

**Comment by rfuchs** [comment]
Cleaning up old tickets
