### ISSUE TITLE
Error configuring media output: failed to open avio

### ISSUE THREAD

**Issue by furek1** [sipwise/rtpengine#1209]
Hello, 

I use sipwise mr9.2.1 and I have call recording enabled, when I try to make a call and make them, the calls are not recorded in the log rtp.log gets information that keeps scrolling

Mar 15 09:37:10 185 rtpengine-recording[8295]: ERR: [C «105536Y2JlZWViNTJjZjU4ODVmYmU3NGJhNWM2ZTFlZTA3Y2Q-1272a007b845a52e.meta»] [S «tag-1-media-1-component-1-RTP-id-0»] [«0x2d3c6b9f»] [core] Error configuring media output: failed to open avio
Mar 15 09:37:10 185 rtpengine-recording[8295]: ERR: [C «105536Y2JlZWViNTJjZjU4ODVmYmU3NGJhNWM2ZTFlZTA3Y2Q-1272a007b845a52e.meta»] [S «tag-1-media-1-component-1-RTP-id-0»] [«0x2d3c6b9f»] [core] Error returned from libav: Permission denied
Mar 15 09:37:10 185 rtpengine-recording[8295]: ERR: [C «105536Y2JlZWViNTJjZjU4ODVmYmU3NGJhNWM2ZTFlZTA3Y2Q-1272a007b845a52e.meta»] [S «tag-1-media-1-component-1-RTP-id-0»] [«0x2d3c6b9f»] [core] Failed to decode media packet
Mar 15 09:37:10 185 rtpengine-recording[8295]: ERR: [C «105536Y2JlZWViNTJjZjU4ODVmYmU3NGJhNWM2ZTFlZTA3Y2Q-1272a007b845a52e.meta»] [S «tag-1-media-1-component-1-RTP-id-0»] [«0x2d3c6b9f»] [core] Error configuring media output: failed to open avio
Mar 15 09:37:10 185 rtpengine-recording[8295]: ERR: [C «105536Y2JlZWViNTJjZjU4ODVmYmU3NGJhNWM2ZTFlZTA3Y2Q-1272a007b845a52e.meta»] [S «tag-1-media-1-component-1-RTP-id-0»] [«0x2d3c6b9f»] [core] Error returned from libav: Permission denied
Mar 15 09:37:10 185 rtpengine-recording[8295]: ERR: [C «105536Y2JlZWViNTJjZjU4ODVmYmU3NGJhNWM2ZTFlZTA3Y2Q-1272a007b845a52e.meta»] [S «tag-1-media-1-component-1-RTP-id-0»] [«0x2d3c6b9f»] [core] Error configuring media output: failed to open avio
Mar 15 09:37:10 185 rtpengine-recording[8295]: ERR: [C «105536Y2JlZWViNTJjZjU4ODVmYmU3NGJhNWM2ZTFlZTA3Y2Q-1272a007b845a52e.meta»] [S «tag-1-media-1-component-1-RTP-id-0»] [«0x2d3c6b9f»] [core] Error returned from libav: Permission denied
Mar 15 09:37:10 185 rtpengine-recording[8295]: ERR: [C «105536Y2JlZWViNTJjZjU4ODVmYmU3NGJhNWM2ZTFlZTA3Y2Q-1272a007b845a52e.meta»] [S «tag-1-media-1-component-1-RTP-id-0»] [«0x2d3c6b9f»] [core] Failed to decode media packet

in / var / spool / rtpengine a metadata file is created, but the recording is missing.
NFS is connected and starts with the script.

**Comment by rfuchs** [comment]
The reason is clearly stated there: `Error returned from libav: Permission denied`

The recording daemon doesn't have permission to create the files.

**Comment by furek1** [comment]
It runs as root, so it has author rights.

**Comment by rfuchs** [comment]
No it doesn't. The NFS can still deny permission.

**Comment by furek1** [comment]
From the server I go to the NFS directory and without any problems create a file on this share as root.

**Comment by rfuchs** [comment]
I don't know what else to tell you. There aren't many other ways that "permission denied" can be interpreted. The system isn't letting it create the files.

**Comment by furek1** [comment]
You were right, thanks for your help.
on nfs directory I changed the permissions
