### ISSUE TITLE
rtpengine removes 'a=inactive' attribute

### ISSUE THREAD

**Issue by juha-h** [sipwise/rtpengine#121]
Firefox does not like the sdp of 200 OK that it receives when video is inactive in the reply.  One possible reason is that rtpengine removes 'a=inactive' attribute from video media.  Dump is below.

-- Juha

May 29 09:40:37 foo rtpengine[25992]: [qomf11ihgd3eva2rfnhh] Received command 'answer' from 127.0.0.1:50777
May 29 09:40:37 foo rtpengine[25992]: [qomf11ihgd3eva2rfnhh] Dump for 'answer' from 127.0.0.1:50777: { "sdp": "v=0#015#012o=sems 926371314 470263868 IN IP4 192.98.102.30#015#012s=sems#015#012c=IN IP4 192.98.102.30#015#012t=0 0#015#012m=audio 8074 RTP/AVP 109 9 0 8#015#012a=rtpmap:109 opus/48000/2#015#012a=rtpmap:9 g722/8000#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:8 PCMA/8000#015#012a=sendrecv#015#012a=direction:both#015#012m=video 0 RTP/AVP 120#015#012a=inactive#015#012", "ICE": "force", "flags": [ "trust-address" ], "call-id": "qomf11ihgd3eva2rfnhh", "via-branch": "z9hG4bK3438610", "received-from": [ "IP4", "127.0.0.1" ], "from-tag" ...
May 29 09:40:37 foo rtpengine[25992]: [qomf11ihgd3eva2rfnhh] ... : "kmnkfg38i3", "to-tag": "3047902B-556809E50000712B-AA557700", "command": "answer" }
May 29 09:40:37 foo rtpengine[25992]: [qomf11ihgd3eva2rfnhh] Shutting down ICE agent (nothing to do)
May 29 09:40:37 foo rtpengine[25992]: [qomf11ihgd3eva2rfnhh] Shutting down ICE agent (nothing to do)
May 29 09:40:37 foo rtpengine[25992]: [qomf11ihgd3eva2rfnhh] Replying to 'answer' from 127.0.0.1:50777
May 29 09:40:37 foo rtpengine[25992]: [qomf11ihgd3eva2rfnhh] Response dump for 'answer' to 127.0.0.1:50777: { "sdp": "v=0#015#012o=sems 926371314 470263868 IN IP4 192.98.102.30#015#012s=sems#015#012c=IN IP4 192.98.102.30#015#012t=0 0#015#012m=audio 8012 RTP/SAVPF 109 9 0 8#015#012a=rtpmap:109 opus/48000/2#015#012a=rtpmap:9 g722/8000#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:8 PCMA/8000#015#012a=direction:both#015#012a=sendrecv#015#012a=rtcp:8012#015#012a=rtcp-mux#015#012a=setup:active#015#012a=fingerprint:sha-1 9C:48:A9:28:40:69:CB:57:BB:46:7F:1E:49:CD:9A:9E:7F:D3:17:CE#015#012a=ice-ufrag:74uFHx35#015#012a=ice-pwd:rH58D7WDBilrMTBPm6s79N0eRu#015#012a=candidate ...
May 29 09:40:37 foo rtpengine[25992]: [qomf11ihgd3eva2rfnhh] ... :fTW1UxNqekUOuWxE 1 UDP 2130706431 192.98.102.30 8012 typ host#015#012m=video 0 RTP/SAVPF 120#015#012", "result": "ok" }

**Comment by rfuchs** [comment]
This is removed on purpose. The RFC states that deleted/rejected streams need not have any other attributes, and also states that an a=inactive stream is in fact something different from a deleted/rejected stream (in that it should still send and receive RTCP and thus needs an endpoint address).

Rtpengine used to retain and even insert a=inactive for rejected/deleted stream, but we've run into a client which had problems with that, so it has been removed.

So if this is really what's causing problems in FF, then I'd say it's a bug in FF.

**Comment by juha-h** [comment]
Richard Fuchs writes:

> Rtpengine used to retain and even insert a=inactive for
> rejected/deleted stream, but we've run into a client which had
> problems with that, so it has been removed.
> 
> So if this is really what's causing problems in FF, then I'd say it's
> a bug in FF.

You may very be right.

Below is the sdp of invite that FF sent and 200 ok that FF receiced.  It
complains "Answer tried to set recv when offer did not set send".  In
voice media, both offer and answer has sendrecv so the issue must be
with video, where offer has recvonly and answer does not have anything.
May be FF does not check that voice media doesn't actually exist and
would like to see sendonly there.

I made another test call where video had sendrecv and in that case FF
accepted exactly the same sdp in the answer.  That sort of confirms what
speculated in above.  This is with FF version 38.0.1. An earlier version
FF (I think it was 31) accepted the sdp in both cases.

After a couple of days testing of webrtc calls with different browsers
my conclusion is that the target is moving too fast.  There is no chance
to use webrtc in real world, because the next version of the browser can
break what used to work earlier and it is not possible to tell users not
to upgrade their browsers.

-- Juha

----------------------- invite

v=0
o=mozilla...THIS_IS_SDPARTA-38.0.1 7368346782250671294 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 3E:DD:E2:59:37:8E:54:D2:77:F8:AA:1A:52:DC:95:5C:91:06:64:A0:B1:86:75:2D:5A:EC:A4:CA:DF:BA:C4:AF
a=group:BUNDLE sdparta_0 sdparta_1
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 57251 RTP/SAVPF 109 9 0 8
c=IN IP4 192.168.43.192
a=candidate:0 1 UDP 2122252543 192.168.43.192 57251 typ host
a=candidate:0 2 UDP 2122252542 192.168.43.192 39443 typ host
a=sendrecv
a=end-of-candidates
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=ice-pwd:18240463804619e3f97a4baa454b0392
a=ice-ufrag:9e216889
a=mid:sdparta_0
a=msid:{cee4ed8c-97f9-4b08-b153-761db9b792ec} {53437cdd-3842-424e-984d-544e04e8cf72}
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=setup:actpass
a=ssrc:2384670233 cname:{9d8d07f8-5a8a-4770-8ab1-a59723cc913c}
m=video 55931 RTP/SAVPF 120
c=IN IP4 192.168.43.192
a=candidate:0 1 UDP 2122252543 192.168.43.192 55931 typ host
a=candidate:0 2 UDP 2122252542 192.168.43.192 48323 typ host
a=recvonly
a=end-of-candidates
a=fmtp:120 max-fs=12288;max-fr=60
a=ice-pwd:18240463804619e3f97a4baa454b0392
a=ice-ufrag:9e216889
a=mid:sdparta_1
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 ccm fir
a=rtcp-mux
a=rtpmap:120 VP8/90000
a=setup:actpass

---------------------------------- 200 OK

v=0
o=sems 148432685 1758803039 IN IP4 192.98.102.10
s=sems
c=IN IP4 192.98.102.10
t=0 0
m=audio 8034 RTP/SAVPF 109 9 0 8
a=rtpmap:109 opus/48000/2
a=rtpmap:9 g722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=direction:both
a=sendrecv
a=rtcp:8034
a=rtcp-mux
a=setup:active
a=fingerprint:sha-1 9C:48:A9:28:40:69:CB:57:BB:46:7F:1E:49:CD:9A:9E:7F:D3:17:CE
a=ice-ufrag:gGcmM9Tz
a=ice-pwd:OlOAc1XiBNlo2TUW7ijprm0F3b
a=candidate:fTW1UxNqekUOuWxE 1 UDP 2130706431 192.98.102.10 8034 typ host
m=video 0 RTP/SAVPF 120

----------------------- error message

"rtcninja:ERROR:RTCPeerConnection " "setRemoteDescription() | error:" " +2ms" DOMException [InvalidSessionDescriptionError: "Answer tried to set recv when offer did not set send"
