### ISSUE TITLE
DTLS differences between 2 machines and newer versions of rtpengine

### ISSUE THREAD

**Issue by hydrosine** [sipwise/rtpengine#1210]
Hi,
I have two machines, both running a  different version of rtpengine. The nonworking is the newer version.
Nonworking Machine1,
Version: git-HEAD-ff0009a
Working Machine2
git-master-2a86d5d

The problem is that I am unable to recreate the workings of machine2, which is a test environment, to machine1 which would be production.
I've compared every installed package and kernel version, I cannot discern any important variances. note I'm using centos 7.9 openssl 1.0.2k on both.
I also tried to copy the compiled rtpengine binaries of the working machine to the nonworking with the same result... .

The goal is to bridge webrtc traffic into our internal network via rtpengine towards asterisk. preferably unencrypted (udp/rtp) on the internal side, at this moment i have a working scenario were the audio is still encrypted inside. Hopefully when I understand this problem better I can move towards having encryption end on the public side of the network.

Machine1 is running Opensips with a pub and internal interface, I used the same script and switched around the used rtpengine modparam to test this.
It seems that machine1 Rtpengine is unable to setup dtls, while machine2 is able to do it. Visible from the 
[crypto] Failed to init DTLS connection: srtp unknown protection profile

I have traces logs and signaling, inside and outside.
Attached,both working and nonworking rtpengine logs, and jssip client signaling. 
nonworking file also contains opensips logging to have insight in the flags passed. (this is the same for both working and non working.) each file starts with rtpengine logging then some whitespace with to follow up with the webrtc client signaling.
I've obfuscated some details.
Please let me know what would be more useful to help resolve this issue.
[workingrtpengine.txt](https://github.com/sipwise/rtpengine/files/6162685/workingrtpengine.txt)
[nonworkingrtpengine.txt](https://github.com/sipwise/rtpengine/files/6162686/nonworkingrtpengine.txt)

Thanks in advance.

**Comment by rfuchs** [comment]
Upgrade your OpenSSL to one that supports AEAD-GCM SRTP ciphers.  If that's not possible, comment out the lines
```
crypto.c
47:		.dtls_name		= "SRTP_AEAD_AES_256_GCM",
70:		.dtls_name		= "SRTP_AEAD_AES_128_GCM",
```

**Comment by pwakano** [comment]
Hi @rfuchs , apologies again for posting in this closed ticket.... But are we able to control this behaviour using the dtls-ciphers parameter instead of changing the source code?

**Comment by rfuchs** [comment]
> Hi @rfuchs , apologies again for posting in this closed ticket.... But are we able to control this behaviour using the dtls-ciphers parameter instead of changing the source code?

No, this is completely unrelated to the DTLS certificate. You're welcome to submit a patch to either make these ciphers optional, or somehow else properly support your old OpenSSL.

**Comment by pwakano** [comment]
Hi @rfuchs , sorry again, but in regards to this problem, I would like to understand if the latest RTPEngine works with openssl 1.1.1k, or do I need to upgrade to version 3? The docs mention dependency to openssl, but I couldn't find a minimum version.... Openssl 1.0.2.k is the latest for RHEL/Centos 7 (which is still under support) and it is now not fully compatible with RTPEngine, so it would be nice to have the information about the minimum openssl version that is required.

**Comment by rfuchs** [comment]
> Hi @rfuchs , sorry again, but in regards to this problem, I would like to understand if the latest RTPEngine works with openssl 1.1.1k, or do I need to upgrade to version 3? The docs mention dependency to openssl, but I couldn't find a minimum version.... Openssl 1.0.2.k is the latest for RHEL/Centos 7 (which is still under support) and it is now not fully compatible with RTPEngine, so it would be nice to have the information about the minimum openssl version that is required.

The oldest distro we support out of the box is Debian Stretch, which currently ships OpenSSL 1.1.0l. So I would suggest that as minimum version, although it's well possible that it works with older 1.1.x versions as well.

(RPM support is mostly community driven, so again if there's anything that can be improved here to support particular releases/distros, please submit PRs)
