### ISSUE TITLE
SSRC change & kernel media forwarding.

### ISSUE THREAD

**Issue by Den4t** [sipwise/rtpengine#1211]
Hi !

Periodicaly i have see change of SSRC inside the RTP stream from endpoints, especialy from asterisk servers,
when they do the native bridging, this seems to be normal, but have effect 
in kernel module, SSRC change detected and module refuse processing, so the packet moved to userspace, where
the daemon process relay them. I dont know what exactly rtpe daemon do with stream after kernrlizing media, but according
the debug logs, simple reay the packets. This behavior is not good in high pressure, because we have double work in kernel 
module and in userspace. I have made a litle patch for kenel module, here:
https://github.com/Den4t/rtpengine/commit/bf4ec8fd1b0ce2fc0c02a38bfc0a341bae360067

But not shure this broke aniting else, f.e. SRTP, in my lab this work. When module detect SSRC change, first packet moved
to userspace (may be rtpe daemon do some stat changes or anything else) then save new SSRC in internal structure,
after this no more packets moved to userspace.

So my question to the authors is - does this break anything, can I make a pull request ?

**Comment by rfuchs** [comment]
No this is not the right approach. What should happen is: the packet is passed on to userspace, which should then detect the SSRC change, update its internal data, then remove the kernel forwarding, and then reinstate the kernel forwarding with the updated SSRC. I'm guessing that the "remove kernel forwarding" step is missing or not working if there's a problem with this.

**Comment by Den4t** [comment]
How can i debug this: " I'm guessing that the "remove kernel forwarding" step is missing or not working if there's a problem with this".
In attachment the debug log of changed SSRC call, exept "Forward to sink endpoint" nothing from where i can catch on in daemon source.
[rtpe.log](https://github.com/sipwise/rtpengine/files/6173132/rtpe.log)

**Comment by rfuchs** [comment]
The SSRC that is pushed to the kernel comes from the `ssrc_in` pointer: https://github.com/sipwise/rtpengine/blob/master/daemon/media_socket.c#L1191

The main RTP packet handling is in `stream_packet`: https://github.com/sipwise/rtpengine/blob/master/daemon/media_socket.c#L1960

This then calls `media_packet_rtp()` for handling RTP-specific details, which in turns calls `__stream_ssrc()`: https://github.com/sipwise/rtpengine/blob/master/daemon/media_socket.c#L1451

That's the function that is responsible for fetching the object corresponding to the SSRC and assigning it to `ssrc_in`

It's at this point that the new SSRC is detected (you can see the code path starting at line 1463, and also below for the out direction), and when that happens the `unkernelize` flag needs to be set, like in https://github.com/sipwise/rtpengine/blob/master/daemon/media_socket.c#L1756

**Comment by rfuchs** [comment]
Let me know if you still want to take a stab at this - if not I can take over

**Comment by Den4t** [comment]
Thanks ! 
I will try, report later.

**Comment by Den4t** [comment]
Hi, rfuchs !

Setting unkernelize flag fix the problem. 
After SSRC change happend, media stay in kernel as expected.
Debug log and proc history log:
[proc.log](https://github.com/sipwise/rtpengine/files/6175172/proc.log)
[rtpengine.log](https://github.com/sipwise/rtpengine/files/6175174/rtpengine.log)

patch here:
https://github.com/Den4t/rtpengine/commit/7d3334c1bfe7ca7ae9b9bb2ba42c43f2e6d220c4

**Comment by rfuchs** [comment]
Merged as bfe6d596 - thanks
