### ISSUE TITLE
issue with play media. 

### ISSUE THREAD

**Issue by johandeclercqdemocon** [sipwise/rtpengine#1214]
Richard,
The idea is to play a wav file on a negative reply from the callee.  
can you please indicate what is the problem here : 
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [core] timer run time = 0.000063 sec
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [control] Adding a proxy for control ng stats:127.0.0.1
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: INFO: [_NyrI1t9F7vyse0oMyFjWA..]: [control] Received command 'offer' from 127.0.0.1:36368
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [control] Dump for 'offer' from 127.0.0.1:36368: { "sdp": "v=0
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: o=Zoiper 1616151963709 1 IN IP4 192.168.68.104
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: s=Z
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: c=IN IP4 192.168.68.104
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: t=0 0
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: m=audio 43054 RTP/AVP 0 101 8 3
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: a=rtpmap:101 telephone-event/8000
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: a=fmtp:101 0-16
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: a=sendrecv
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: ", "ICE": "remove", "direction": [ "internal", "internal" ], "flags": [ "codec-strip-telephone-event", "codec-
strip-PCMA", "codec-strip-PCMU", "codec-mask-all", "codec-transcode-PCMA", "codec-transcode-PCMU", "codec-offer-telephone-event" ], "replace": [ "zero address", "
origin", "session-connection" ], "transport-protocol": "RTP/AVP", "call-id": "_NyrI1t9F7vyse0oMyFjWA..", "received-from": [ "IP4", "192.168.68.104" ], "from-tag":
 "ad5df127", "command": "offer" }
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: NOTICE: [_NyrI1t9F7vyse0oMyFjWA..]: [core] Creating new call
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [codec] Stripping codec 'PCMU/8000'
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [codec] Stripping codec 'telephone-event/8000'
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [codec] Stripping codec 'PCMA/8000'
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [codec] Masking codec 'GSM/8000'
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [codec] Restoring codec 'telephone-event' from stripped codecs (1 payload t
ypes)
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [codec] Restoring codec 'PCMA' from stripped codecs (1 payload types)
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [codec] Restoring codec 'PCMU' from stripped codecs (1 payload types)
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [codec] Default sink codec is GSM/8000
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [codec] Output DTMF payload type is 101
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [codec] Creating codec handler for telephone-event/8000
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [codec] Sink supports codec telephone-event/8000
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [codec] Using passthrough handler for telephone-event/8000
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [codec] Creating codec handler for PCMA/8000
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [codec] Sink supports codec PCMA/8000
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [codec] Using passthrough handler for PCMA/8000
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [codec] Creating codec handler for PCMU/8000
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [codec] Sink supports codec PCMU/8000
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [codec] Using passthrough handler for PCMU/8000
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [core] set FILLED flag for stream 192.168.68.104:43054
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [core] set FILLED flag for stream 192.168.68.104:43055
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: INFO: [_NyrI1t9F7vyse0oMyFjWA..]: [control] Replying to 'offer' from 127.0.0.1:36368 (elapsed time 0.001001 se
c)
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [control] Response dump for 'offer' to 127.0.0.1:36368: { "sdp": "v=0
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: o=Zoiper 1616151963709 1 IN IP4 192.168.68.115
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: s=Z
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: c=IN IP4 192.168.68.115
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: t=0 0
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: m=audio 30000 RTP/AVP 101 8 0
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: a=rtpmap:101 telephone-event/8000
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: a=fmtp:101 0-16
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: a=rtpmap:8 PCMA/8000
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: a=rtpmap:0 PCMU/8000
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: a=sendrecv
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: a=rtcp:30001
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: ", "result": "ok" }
Mar 19 07:06:05 debian10opensips31 /data/opensips/sbin/opensips[4612]: DBG:rtpengine:rtpe_function_call: proxy reply: d3:sdp243:v=0#015#012o=Zoiper 1616151963709 
1 IN IP4 192.168.68.115#015#012s=Z#015#012c=IN IP4 192.168.68.115#015#012t=0 0#015#012m=audio 30000 RTP/AVP 101 8 0#015#012a=rtpmap:101 telephone-event/8000#015#0
12a=fmtp:101 0-16#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:0 PCMU/8000#015#012a=sendrecv#015#012a=rtcp:30001#015#0126:result2:oke
Mar 19 07:06:05 debian10opensips31 /data/opensips/sbin/opensips[4612]: callid=_NyrI1t9F7vyse0oMyFjWA..: route[rtpengine]: INVITE has SDP -> rtpengine_offered and 
successfull, avp(nat) normal
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: INFO: [_NyrI1t9F7vyse0oMyFjWA..]: [control] Received command 'play media' from 127.0.0.1:36368
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: DEBUG: [_NyrI1t9F7vyse0oMyFjWA..]: [control] Dump for 'play media' from 127.0.0.1:36368: { "file": "/home/joha
n/Downloads/discon-or-out-of-service.wav", "call-id": "_NyrI1t9F7vyse0oMyFjWA..", "received-from": [ "IP4", "192.168.68.104" ], "from-tag": "1304101d", "to-tag": 
"ad5df127", "command": "play media" }
Mar 19 07:06:05 debian10opensips31 rtpengine[4954]: ERR: [_NyrI1t9F7vyse0oMyFjWA..]: [core] No suitable SDP section for media playback

**Comment by rfuchs** [comment]
Your tags are reversed. You're trying to play media to the answerer, not the offerer.
`"from-tag": "1304101d", "to-tag": "ad5df127"`
The `from-tag` should be the tag that you want to play media to.

**Comment by johandeclercqdemocon** [comment]
Thanks Richard.

**Comment by johandeclercqdemocon** [comment]
Okay, I got it almost working : I see the rtp in the pcap going to port 8000. 
Am I overlooking something ? 
[mypcap.zip](https://github.com/sipwise/rtpengine/files/6172454/mypcap.zip)


Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: INFO: [we5jSuqmPYChHyjnoSp5DA..]: [control] Received command 'offer' from 127.0.0.1:38822
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [control] Dump for 'offer' from 127.0.0.1:38822: { "sdp": "v=0
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: o=Z 1616168134166 1 IN IP4 192.168.68.109
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: s=Z
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: c=IN IP4 192.168.68.109
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: t=0 0
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: m=audio 8000 RTP/AVP 8 101
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: a=rtpmap:101 telephone-event/8000
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: a=fmtp:101 0-16
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: a=sendrecv
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: ", "ICE": "remove", "direction": [ "internal", "internal" ], "flags": [ "codec-strip-telephone-event", "codec-
strip-PCMA", "codec-strip-PCMU", "codec-mask-all", "codec-transcode-PCMA", "codec-transcode-PCMU", "codec-offer-telephone-event" ], "replace": [ "zero address", "
origin", "session-connection" ], "transport-protocol": "RTP/AVP", "call-id": "we5jSuqmPYChHyjnoSp5DA..", "received-from": [ "IP4", "192.168.68.109" ], "from-tag":
 "9cfa6712", "command": "offer" }
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: NOTICE: [we5jSuqmPYChHyjnoSp5DA..]: [core] Creating new call
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [codec] Stripping codec 'PCMA/8000'
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [codec] Stripping codec 'telephone-event/8000'
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [codec] Restoring codec 'telephone-event' from stripped codecs (1 payload t
ypes)
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [codec] Restoring codec 'PCMA' from stripped codecs (1 payload types)
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [codec] Codec 'PCMU/8000' added for transcoding with payload type 0
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [codec] Default sink codec is PCMA/8000
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [codec] Output DTMF payload type is 101
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [codec] Creating codec handler for telephone-event/8000
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [codec] Sink supports codec telephone-event/8000
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [codec] Using passthrough handler for telephone-event/8000
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [codec] Creating codec handler for PCMA/8000
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [codec] Sink supports codec PCMA/8000
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [codec] Using passthrough handler for PCMA/8000
Mar 19 11:35:34 debian10opensips31 /data/opensips/sbin/opensips[6997]: callid=we5jSuqmPYChHyjnoSp5DA..: route[rtpengine]: INVITE has SDP -> rtpengine_offered and 
successfull, avp(nat) normal
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [codec] Creating codec handler for PCMU/8000
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [codec] Sink does not support codec PCMU/8000
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [codec] Created transcode context for PCMU/8000 -> PCMA/8000 with DTMF outp
ut 101
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [codec] Creating SSRC transcoder from PCMU/8000/1 to PCMA/8000/1
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [core] Initialized encoder with frame size 160 samples
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [codec] Encoder created with clockrate 8000, 1 channels, using sample forma
t 1 (ptime 20 for 160 samples per frame and 160 samples (160 bytes) per packet, bitrate 0)
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: INFO: [we5jSuqmPYChHyjnoSp5DA..]: [codec] Enabling transcoding engine
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [codec] Using passthrough handler with new SSRC for PCMA/8000
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [codec] Using passthrough handler with new SSRC for telephone-event/8000
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [core] set FILLED flag for stream 192.168.68.109:8000
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [core] set FILLED flag for stream 192.168.68.109:8001
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: INFO: [we5jSuqmPYChHyjnoSp5DA..]: [control] Replying to 'offer' from 127.0.0.1:38822 (elapsed time 0.000225 se
c)
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [control] Response dump for 'offer' to 127.0.0.1:38822: { "sdp": "v=0
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: o=Z 1616168134166 1 IN IP4 192.168.68.115
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: s=Z
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: c=IN IP4 192.168.68.115
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: t=0 0
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: m=audio 30370 RTP/AVP 101 8 0
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: a=rtpmap:101 telephone-event/8000
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: a=fmtp:101 0-16
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: a=rtpmap:8 PCMA/8000
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: a=rtpmap:0 PCMU/8000
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: a=sendrecv
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: a=rtcp:30371
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: ", "result": "ok" }
Mar 19 11:35:34 debian10opensips31 /data/opensips/sbin/opensips[6997]: new branch at sip:1001@192.168.68.104:51798;rinstance=fa75b7075ea6db80;transport=UDP
Mar 19 11:35:34 debian10opensips31 /data/opensips/sbin/opensips[6997]: callid=we5jSuqmPYChHyjnoSp5DA..: Onreply_route[handle_nat]: incoming reply mb [SIP/2.0 100 
Trying#015#012Via: SIP/2.0/UDP 192.168.68.115:5060;branch=z9hG4bKa4df.6b65e65.0#015#012Via: SIP/2.0/UDP 192.168.68.109:48961;received=192.168.68.109;branch=z9hG4b
K-524287-1---4d32329945fe357a;rport=48961#015#012To: <sip:1001@192.168.68.115:5060>#015#012From: <sip:1000@192.168.68.115:5060;transport=UDP>;tag=9cfa6712#015#012
Call-ID: we5jSuqmPYChHyjnoSp5DA..#015#012CSeq: 1 INVITE#015#012Content-Length: 0#015#012#015#012]
Mar 19 11:35:35 debian10opensips31 rtpengine[6231]: DEBUG: [core] timer run time = 0.000057 sec
Mar 19 11:35:37 debian10opensips31 rtpengine[6231]: DEBUG: [core] timer run time = 0.000060 sec
Mar 19 11:35:37 debian10opensips31 /data/opensips/sbin/opensips[6997]: callid=we5jSuqmPYChHyjnoSp5DA..: Onreply_route[handle_nat]: incoming reply mb [SIP/2.0 180 
Ringing#015#012Via: SIP/2.0/UDP 192.168.68.115:5060;branch=z9hG4bKa4df.6b65e65.0#015#012Via: SIP/2.0/UDP 192.168.68.109:48961;received=192.168.68.109;branch=z9hG4
bK-524287-1---4d32329945fe357a;rport=48961#015#012Record-Route: <sip:192.168.68.115;lr;did=31d.3ad54664>#015#012Contact: <sip:1001@192.168.68.104:51798>#015#012To
: <sip:1001@192.168.68.115:5060>;tag=2099eb78#015#012From: <sip:1000@192.168.68.115:5060;transport=UDP>;tag=9cfa6712#015#012Call-ID: we5jSuqmPYChHyjnoSp5DA..#015#
012CSeq: 1 INVITE#015#012Allow: INVITE, ACK, CANCEL, BYE, NOTIFY, REFER, MESSAGE, OPTIONS, INFO, SUBSCRIBE#015#012User-Agent: Zoiper rv2.10.12.3-mod#015#012Allow-
Events: presence, kpml, talk#015#012Content-Length: 0#015#012#015#012]
Mar 19 11:35:39 debian10opensips31 rtpengine[6231]: DEBUG: [core] timer run time = 0.000055 sec
Mar 19 11:35:39 debian10opensips31 /data/opensips/sbin/opensips[6997]: callid=we5jSuqmPYChHyjnoSp5DA..: Onreply_route[handle_nat]: incoming reply mb [SIP/2.0 486 
Busy Here#015#012Via: SIP/2.0/UDP 192.168.68.115:5060;branch=z9hG4bKa4df.6b65e65.0#015#012Via: SIP/2.0/UDP 192.168.68.109:48961;received=192.168.68.109;branch=z9h
G4bK-524287-1---4d32329945fe357a;rport=48961#015#012To: <sip:1001@192.168.68.115:5060>;tag=2099eb78#015#012From: <sip:1000@192.168.68.115:5060;transport=UDP>;tag=
9cfa6712#015#012Call-ID: we5jSuqmPYChHyjnoSp5DA..#015#012CSeq: 1 INVITE#015#012User-Agent: Zoiper rv2.10.12.3-mod#015#012Content-Length: 0#015#012#015#012]
Mar 19 11:35:39 debian10opensips31 /data/opensips/sbin/opensips[6997]: failure route ft [9cfa6712] tt [<null>]
Mar 19 11:35:39 debian10opensips31 /data/opensips/sbin/opensips[6997]: playwavfile string [file=/home/johan/Downloads/discon-or-out-of-service.wav from-tag=9cfa67
12]
Mar 19 11:35:39 debian10opensips31 rtpengine[6231]: INFO: [we5jSuqmPYChHyjnoSp5DA..]: [control] Received command 'play media' from 127.0.0.1:38822
Mar 19 11:35:39 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [control] Dump for 'play media' from 127.0.0.1:38822: { "file": "/home/joha
n/Downloads/discon-or-out-of-service.wav", "call-id": "we5jSuqmPYChHyjnoSp5DA..", "received-from": [ "IP4", "192.168.68.109" ], "from-tag": "9cfa6712", "command":
 "play media" }
Mar 19 11:35:39 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [ffmpeg] av_log: Opening '/home/johan/Downloads/discon-or-out-of-service.wa
v' for reading
Mar 19 11:35:39 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [ffmpeg] av_log: Setting default whitelist 'file,crypto'
Mar 19 11:35:39 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [ffmpeg] av_log: Probing wav score:99 size:2048
Mar 19 11:35:39 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [ffmpeg] av_log: Format wav probed with size=2048 and score=99
Mar 19 11:35:39 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [ffmpeg] av_log: Before avformat_find_stream_info() pos: 44 bytes read:6558
0 seeks:1 nb_streams:1
Mar 19 11:35:39 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [ffmpeg] av_log: probing stream 0 pp:32
Mar 19 11:35:39 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [ffmpeg] av_log: Probing mp3 score:1 size:4096
Mar 19 11:35:39 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [ffmpeg] av_log: Probe with size=4096, packets=2469 detected mp3 with score
=1
Mar 19 11:35:39 debian10opensips31 rtpengine[6231]: DEBUG: [we5jSuqmPYChHyjnoSp5DA..]: [ffmpeg] av_log: probing stream 0 pp:31

**Comment by rfuchs** [comment]
If you see RTP going, then what isn't working?

**Comment by johandeclercqdemocon** [comment]
It goes to port 8000 instead of the port announced in the sdp

**Comment by rfuchs** [comment]
```
Dump for 'offer' from 127.0.0.1:38822: { "sdp": "v=0
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: o=Z 1616168134166 1 IN IP4 192.168.68.109
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: s=Z
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: c=IN IP4 192.168.68.109
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: t=0 0
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: m=audio 8000 RTP/AVP 8 101
```
Says 8000 right there.

**Comment by johandeclercqdemocon** [comment]
Damn overlooked it.  Sorry Richard

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Richard Fuchs ***@***.***>
Verzonden: Friday, March 19, 2021 6:30:26 PM
Aan: sipwise/rtpengine ***@***.***>
CC: johandeclercqdemocon ***@***.***>; Author ***@***.***>
Onderwerp: Re: [sipwise/rtpengine] issue with play media. (#1214)


Dump for 'offer' from 127.0.0.1:38822: { "sdp": "v=0
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: o=Z 1616168134166 1 IN IP4 192.168.68.109
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: s=Z
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: c=IN IP4 192.168.68.109
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: t=0 0
Mar 19 11:35:34 debian10opensips31 rtpengine[6231]: m=audio 8000 RTP/AVP 8 101


Says 8000 right there.
