### ISSUE TITLE
Hold/UnHold – lost remote audio/video

### ISSUE THREAD

**Issue by Seanitis** [sipwise/rtpengine#1217]
Hi there,

**rtpengine**: git-master-46176f2
**kamailio** 5.4.3
   kamailio have these flags:   ICE=force  port-latching=on
**Signaling pat**h: WebRTC (JsSIP) --> Kamailio with Rtpengine -->   WebRTC (JsSIP)
**Problem:**
The browser to browser call ok. But if one browser puts the call “on hold” then “un hold”, lost remote side video and audio.

Here below is the level 7 log.
[rtpengine-debug.log](https://github.com/sipwise/rtpengine/files/6199682/rtpengine-debug.log)

Could you please help me with this? Thanks for your time!

Regards,
Sean

**Comment by rfuchs** [comment]
My guess is that this is due to a change in the DTLS fingerprint and an unhandled stray DTLS reset. Try passing `DTLS-fingerprint=sha-256` in your offer flags. Or update rtpengine - newer versions handle this automatically.

**Comment by Seanitis** [comment]
Hi @rfuchs 
Thanks for your fast reply.
I will give it a try and will let you know.

Regards,
Sean

**Comment by Seanitis** [comment]
Hi @rfuchs 
You are genius!  It really saved my day!
```DTLS-fingerprint=sha-256``` flag solved the problem.

Have a nice day!
Sean
