### ISSUE TITLE
Pub/sub events from media streams

### ISSUE THREAD

**Issue by manur** [sipwise/rtpengine#122]
Hello @rfuchs ,

I cannot find any documentation on this, so I thought to ask.

Does rtpengine support non-RPC methods of communication? I'm specifically interested on listening to subscribing to 'delete' events, for instance, to update database records based on stream state.

This is for the case of knowing when a stream has been dropped in the event of poor connectivity, and the stream itself is terminated on one end, i.e. the listening socket on rtpengine is terminated. 

Thanks in advance.

**Comment by rfuchs** [comment]
Only XMLRPC callbacks are supported right now.
