### ISSUE TITLE
Verifying rtpengine in kernel-mode

### ISSUE THREAD

**Issue by githubsw** [sipwise/rtpengine#1226]
Hello,
I have configured rtpengine to use kernel-mode and everything appears to be working as normal.  However, I am unsure how to verify that kernel-mode is actually in effect.  I was verifying calls by looking at Homer QoS reports and I do not see any difference in the statistics between rtpengine in kernel-mode vs. non kernel-mode, and this surprised me.  I am dealing with jitter issues and thought I would see some improvement (or at least some differences in the MOS) when in kernel-mode.  I would appreciate any thoughts on this subject.

Thank you,

**Comment by rfuchs** [comment]
The easiest way is to inspect `/proc/rtpengine/0/list` and see if the packet counters are increasing. If they are then it's working.

**Comment by githubsw** [comment]
Ah, I see the issue.  When I do an strace I see the following error =>
open("/proc/rtpengine/10/control", O_RDWR|O_TRUNC) = 4
write(4, "\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 840) = -1 EIO (Input/output error)
close(4)                                = 0
gettimeofday({tv_sec=1617648761, tv_usec=97935}, NULL) = 0
write(2, "[1617648761.097935] ERR: FAILED "..., 105[1617648761.097935] ERR: FAILED TO OPEN KERNEL TABLE 10 (Input/output eror), KERNEL FORWARDING DISABLED

But the file is there => if I list the files, 10 (10 is what I used for my id) is there =>
ll /proc/rtpengine/10
-r--r--r-- 1 root root 0 Apr  5 18:58 blist
dr-xr-xr-x 2 root root 0 Apr  5 18:58 calls
-rw-rw---- 1 root root 0 Apr  5 18:58 control
-r--r--r-- 1 root root 0 Apr  5 18:58 list
-r--r--r-- 1 root root 0 Apr  5 18:58 status

Any ideas on what could be triggering this.  I did following the install instructions in -https://github.com/sipwise/rtpengine/blob/master/README.md

Thank you rfuchs!

**Comment by rfuchs** [comment]
Almost certainly a version mismatch between the daemon and the kernel module, i.e. they're built from different sources.

**Comment by githubsw** [comment]
Thank you, I will investigate this further.  Also, did the Jitter Buffer ever get implemented because I do not see any mention of it in the documentation?  

Thanks again.

**Comment by rfuchs** [comment]
> Also, did the Jitter Buffer ever get implemented because I do not see any mention of it in the documentation?

See the `jitter-buffer` option here: https://github.com/sipwise/rtpengine/blob/master/daemon/rtpengine.pod

Note that this is contributed code so I can't vouch for how (well) it works. Also it's userspace only. For transcoding scenarios there's something similar coming very soon, at least for certain codecs.

**Comment by githubsw** [comment]
Sure enough, I did not remove the old Kernel module before recompiling and there was a version mismatch.  I resolved this issue and now Kernel-Mode is working!

Thank you again for your help and very fast response...this is very appreciated!!
