### ISSUE TITLE
rtpengine: codeclib.c:2051: packetizer_amr: Assertion `output->len >= pkt->size + 3' failed

### ISSUE THREAD

**Issue by vs1785** [sipwise/rtpengine#1227]
I got this error which leads to crashing rtpengine service.

Is there any way to fix this problem ?

**Comment by rfuchs** [comment]
Which version? What led to the crash? Open core dump in gdb and post a backtrace.

**Comment by vs1785** [comment]
I think this failed assertion led to the crash.

How can i collect core dump for rtpengine? Is there any documentation to do that ?

**Comment by rfuchs** [comment]
What I mean is: What led up to the crash? I'm aware that it was the assertion which ultimately caused the crash, but something must have triggered it.

Re core dumps, it depends on your system and how you start/run rtpengine. Under systemd there is https://www.freedesktop.org/software/systemd/man/systemd-coredump.html

If you start rtpengine manually from the command line, use `ulimit -c unlimited` on the same shell that you start rtpengine from.

**Comment by rfuchs** [comment]
Cleaning up old tickets
