### ISSUE TITLE
version 9.3.x, missing incomming video with DTLS-SRTP AEAD-GCM in Kernelizing mode

### ISSUE THREAD

**Issue by hrickes** [sipwise/rtpengine#1230]
Hello,

as soon as the kernelization mode is switched on, no incoming video is displayed in the browser. The same scenario with version 9.2.x it is ok. If I comment out the DTLS-SRTP AEAD-GCM cipher in crypto.c, it is also ok.

[rtpengine-9.3.1.4.txt](https://github.com/sipwise/rtpengine/files/6279246/rtpengine-9.3.1.4.txt)
[rtpengine-9.3.1.4_disable_aead.txt](https://github.com/sipwise/rtpengine/files/6279247/rtpengine-9.3.1.4_disable_aead.txt)

**Comment by rfuchs** [comment]
Only video or also audio? Do you have a pcap?

**Comment by hrickes** [comment]
only video, audio is ok, link for pcap comes via email

**Comment by rfuchs** [comment]
Also share your kernel version please

**Comment by hrickes** [comment]
Linux tess4 5.3.18-lp152.66-default #1 SMP Tue Mar 2 13:18:19 UTC 2021 (73933a3) x86_64 x86_64 x86_64 GNU/Linux

openSUSE Leap 15.2

Guest in Virtualbox 6.1.18

**Comment by hrickes** [comment]
Weeks later, I found the problem. Small RTP packets were simply not encrypted and were then missing from the recipient.
e.g. H264 PPS has a length of 4 bytes

[rtpengine-aead.patch.txt](https://github.com/sipwise/rtpengine/files/6422044/rtpengine-aead.patch.txt)

**Comment by rfuchs** [comment]
Good catch, thanks
