### ISSUE TITLE
DTLS-SRTP - one way audio

### ISSUE THREAD

**Issue by tculjaga** [sipwise/rtpengine#1235]
Hi,

Please help me with this issue:

I'm running RTPEngine Version: 9.1.1.2 with kamailio and FreeSWITCH and I get one way audio when interworking WebRTC to pure SIP (DTLS-SRTP ICE <> RTP).

```Signaling path:
[dtls-srtp-rtpengine.log](https://github.com/sipwise/rtpengine/files/6292206/dtls-srtp-rtpengine.log)

WebRCT_client <> Kamailio <sip> FreeSWITCH <sip> Kamailio <sip> Provider

Media path:
WebRTC_client <srtp> RTPEngine <rtp> FreeSWITCH <rtp> RTPEngine <rtp> Provider
```

FreeSWITCH is a B2BUA so it originates both legs towards WebRTC_client  and towards Provider then bridges them together.

When the call is established i get one way audio in WebRTC_client > RTPEngine direction. The opposite direction works well. Looking at wireshark pcaps (both on RTPEngine and client side) i see UDP/SRTP packets exchanged between  WebRTC_client and RTPEngine in both direction. I cannot listen to them as this is SRTP but i can listen the corresponding stream on the private side of RTPEngine and both forward and reverse streams are OK.

I'm wondering if there can be an issue/misconfiguration on RTPEngine side where the actual information in one stream is not encrypted or its dropped or silenced or else ??

Of course i dumped the audio on WebRTC_client side using chrome://webrtc-insternals and that just confirms the silence in one direction.

Well, I'm stuck here for a couple of days now... pls can you give me a hint where to look further.

[dtls-srtp-rtpengine.log](https://github.com/sipwise/rtpengine/files/6292208/dtls-srtp-rtpengine.log)

**Comment by rfuchs** [comment]
DTLS key exchange is always bidirectional, so a successful DTLS negotiation should always result in bidirectional media.

The SRTP keys generated by the DTLS exchange are actually logged to the logfile:
```
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: INFO: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16342]: DTLS: Peer certificate accepted
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: DEBUG: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16342]: DTLS handshake successful
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: INFO: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16342]: DTLS-SRTP successfully negotiated
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: DEBUG: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16342]: SRTP keys, incoming:
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: DEBUG: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16342]: --- AES_CM_128_HMAC_SHA1_80 key o5CgCFDOcr5APtUHumgEPQ== salt II8+eC79YiQAkpjuOzM=
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: DEBUG: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16342]: SRTP keys, outgoing:
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: DEBUG: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16342]: --- AES_CM_128_HMAC_SHA1_80 key 99RN7fq+HB2GlFYEJLEqKA== salt GWs2rvviwM+Rqe6rneY=
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: INFO: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16342]: DTLS-SRTP successfully negotiated
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: DEBUG: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16342]: SRTP keys, incoming:
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: DEBUG: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16342]: --- AES_CM_128_HMAC_SHA1_80 key o5CgCFDOcr5APtUHumgEPQ== salt II8+eC79YiQAkpjuOzM=
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: DEBUG: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16342]: SRTP keys, outgoing:
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: DEBUG: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16342]: --- AES_CM_128_HMAC_SHA1_80 key 99RN7fq+HB2GlFYEJLEqKA== salt GWs2rvviwM+Rqe6rneY=
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: DEBUG: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16342]: Sending DTLS packet
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: DEBUG: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16362]: Processing incoming DTLS packet
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: INFO: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16362]: DTLS: Peer certificate accepted
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: DEBUG: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16362]: DTLS handshake successful
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: INFO: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16362]: DTLS-SRTP successfully negotiated
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: DEBUG: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16362]: SRTP keys, incoming:
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: DEBUG: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16362]: --- AES_CM_128_HMAC_SHA1_80 key cM2QZcWAI8YHp2F49Olp7A== salt ykI4uSJvb3oqpOdwJxo=
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: DEBUG: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16362]: SRTP keys, outgoing:
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: DEBUG: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16362]: --- AES_CM_128_HMAC_SHA1_80 key mUlv3/XiWcPOsjhxE8bhNQ== salt NrG7e5bVUDAi2GNPc5k=
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: INFO: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16362]: DTLS-SRTP successfully negotiated
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: DEBUG: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16362]: SRTP keys, incoming:
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: DEBUG: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16362]: --- AES_CM_128_HMAC_SHA1_80 key cM2QZcWAI8YHp2F49Olp7A== salt ykI4uSJvb3oqpOdwJxo=
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: DEBUG: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16362]: SRTP keys, outgoing:
Apr 11 16:31:04 cci-mpxyt1 rtpengine[3178861]: DEBUG: [62ebe34c-1575-123a-a8b3-005056aefb58 port 16362]: --- AES_CM_128_HMAC_SHA1_80 key mUlv3/XiWcPOsjhxE8bhNQ== salt NrG7e5bVUDAi2GNPc5k=
```
You can use those to decrypt the SRTP and verify the media.

According to the log, ICE completes successfully, so with both ICE and DTLS completed, there shouldn't be anything impeding media flow. And the log seems to show media flowing both ways. So I don't really see any problem here.

**Comment by tculjaga** [comment]
Hi Richard,

thanks for your feedback!

yes, that's the entire point i see RTP traffic exchanged in both directions
but all chrome does is just play silence. On the internal side of RTPEngine
I can listen to RTP and I can confirm there is voice... but on Chrome
(webrtc client)  i get just silence

I need to listen to SRTP ... please, can you show me how to decode the SRTP
using SRTP keys ?

**Comment by rfuchs** [comment]
> I need to listen to SRTP ... please, can you show me how to decode the SRTP using SRTP keys ?

I've never done it myself, but I understand there's a tool to do it:
https://www.zoiper.com/en/support/home/article/162/How%20to%20decode%20SIP%20over%20TLS%20with%20Wireshark%20and%20Decrypting%20SDES%20Protected%20SRTP%20Stream

https://github.com/cisco/libsrtp/tree/master/test

There's also a simple tool included with rtpengine, but it works for single packets only: https://github.com/sipwise/rtpengine/blob/master/utils/srtp-debug-helper (first argument is the crypto suite name, second argument is the SDES key string, third argument is the RTP packet in hex)

Another thing you can do is hand-craft a fake SDES SRTP SDP, run that through rtpengine and have it translated to plain RTP, and then use tcpreplay to play the packets from the pcap into rtpengine. The output should then be plain RTP.

**Comment by tculjaga** [comment]
thanks,

just a quick question: in what format are key and salt in the logs ?

AES_CM_128_HMAC_SHA1_80 key o5CgCFDOcr5APtUHumgEPQ== salt
II8+eC79YiQAkpjuOzM=

**Comment by rfuchs** [comment]
Same format as in SDES, which is base64, key and salt concatenated. If you need key and salt separately, you need to split them up as required by the crypto suite (e.g. for AES_CM_128_HMAC_SHA1_80 it's 16 bytes key, 14 bytes salt)

**Comment by tculjaga** [comment]
per logs i got key o5CgCFDOcr5APtUHumgEPQ== salt II8+eC79YiQAkpjuOzM=

assuming base64... i decode them as:

key:  a390a00850ce72be403ed507ba68043d
salt:  208f3e782efd6224009298ee3b33



So for rtp_decoder the key should be:
a390a00850ce72be403ed507ba68043d208f3e782efd6224009298ee3b33
and thats hex

./rtp_decoder -a -t 0 -e 128 -k
a390a00850ce72be403ed507ba68043d208f3e782efd6224009298ee3b33 <
./forward_stream.pcap

RTP packets decoded: 683

ok, let me try now :=)... thanks!


small python code for further reference :=)
-- snip --
import base64

key_b64 = 'o5CgCFDOcr5APtUHumgEPQ=='
salt_b64 = 'II8+eC79YiQAkpjuOzM='

key_hex = base64.b64decode(key_b64).hex()
salt_hex = base64.b64decode(salt_b64).hex()


print(key_hex + salt_hex)
-- snip --

**Comment by tculjaga** [comment]
okay,

I took the pcap on the client computer just to be sure the client is
actually receiving the stream and have decoded confirming SRTP in both ways
has the correct audio payload so RTPEngine is fine.

so for some reason Chrome fails to decrypt SRTP.

so on Chrome (Version 89.0.4389.114 (Official Build) (64-bit)) and on
Microsoft Edge (Version 89.0.774.75 (Official build) (64-bit)) i got SRTP
issues.
On Firefox (87.0 (64-bit)) it works ...

so, maybe we are sending something the browser doesn't like ?

currently I'm sending this: replace-origin replace-session-connection
rtcp-mux-offer generate-mid DTLS=passive SDES-off ICE=force RTP/SAVPF
direction=internal direction=external

**Comment by rfuchs** [comment]
On a hunch, you can try adding `DTLS-fingerprint=sha-256`

Other than that, the browser's log should probably have details about what's happening...

**Comment by rfuchs** [comment]
Cleaning up old tickets
