### ISSUE TITLE
RTP streamed via wrong port (ICE + ReINVITE)

### ISSUE THREAD

**Issue by sergey-safarov** [sipwise/rtpengine#1236]
We use `ICE` to provide simplify `IPv4 <-> IPv6` RTP stream conversion management.
We found when used session refresher and endpoint send first ReINVITE, then RTP stream to IPv4 endpoint is correct.

When the IPv4 endpoint sends the second ReINVITE message then RTPengine starts sending RTP stream via RTCP port (event `no-rtcp-attribute` flag used).

Our test case
```
IPv4 endpoint <-> Kmailio + RTPengine <-> FreeSwitch IPv6
```

Call examples

[call1-120236233_63279339@206.147.236.78.pcapng.gz](https://github.com/sipwise/rtpengine/files/6306748/call1-120236233_63279339%40206.147.236.78.pcapng.gz)
[call2-122066590_97079439@206.147.236.78.pcapng.gz](https://github.com/sipwise/rtpengine/files/6306751/call2-122066590_97079439%40206.147.236.78.pcapng.gz)
[call3-138946992_104582558@206.147.236.78.pcapng.gz](https://github.com/sipwise/rtpengine/files/6306752/call3-138946992_104582558%40206.147.236.78.pcapng.gz)
[call5-306480814_72266418@206.147.236.78.pcapng.gz](https://github.com/sipwise/rtpengine/files/6306753/call5-306480814_72266418%40206.147.236.78.pcapng.gz)
[call6-369253291_134208028@206.147.236.78.pcapng.gz](https://github.com/sipwise/rtpengine/files/6306754/call6-369253291_134208028%40206.147.236.78.pcapng.gz)

For the last three calls,  I collected RTPengine debug logs.
[rtpengine.log.gz](https://github.com/sipwise/rtpengine/files/6306698/rtpengine.log.gz)

Call-ID present in log
1. without RTCP - 306480814_72266418@206.147.236.78
2. with    RTCP - 369253291_134208028@206.147.236.78

What I found in PCAP.
Looks as for leg toward to FreeSwitch changed RTP port.

RTPengine logs timestamp in GMT.

**Comment by sergey-safarov** [comment]
Hints for the first example
Wireshark filter
```
udp.port==5258
```

Hints for the second example
Wireshark filter
```
udp.port==5264
```

Hints for the third example
Wireshark filter
```
udp.port==5260
```

Hints for the fifty example
Wireshark filter
```
udp.port==5262
```

Hints for the sixth example
Wireshark filter
```
udp.port==5272
```

**Comment by rfuchs** [comment]
This happens because your ICE client sends STUN requests to the wrong port after the re-invite. Looking at the fifth pcap (`369253291_134208028@206.147.236.78`) you can see this when you use the filter `stun` in Wireshark. The first incorrect STUN packet is 12433: Here an STUN request is sent from the RTP port to rtpengine's RTCP port. Another example is packets 12652 (correct) and 12654 (incorrect). So through these ICE exchanges rtpengine learns that rtpengine must send the RTP from its RTCP port. (The ICE client also doesn't correctly respond to the 487 errors, so there's more things wrong with the ICE implementation there.)

**Comment by sergey-safarov** [comment]
Thank you Richard @rfuchs
Using PCAP I can see now `STUN request is sent from the RTP port to rtpengine's RTCP port`.
I also see FreeSwitch does not offer RTCP as attribute (like `a=rtcp:16943`) but offers in `ICE`.
According to FreeSwitch settings RTCP disabled.
According to [RFC 8839](https://tools.ietf.org/html/rfc8839#section-5.1)
> RTP media MUST
      have a component ID of 1, and candidates for RTCP MUST have a
      component ID of 2.

So from my point of view, FreeSwitch must do not provide ICE candidates with `component ID = 2`.
Could you confirm?

Also in PCAP and rtpengine log I can lot of error messages like
> Binding Error Response Role conflict
> ICE role conflict detected

Looks as FreeSwitch one time switched to `ICE-CONTROLLED` send binding request as `ICE-CONTROLLING` again and again.
Should it be also fixed?

**Comment by rfuchs** [comment]
> I also see FreeSwitch does not offer RTCP as attribute (like `a=rtcp:16943`) but offers in `ICE`.
> According to FreeSwitch settings RTCP disabled.
> According to [RFC 8839](https://tools.ietf.org/html/rfc8839#section-5.1)
> 
> > RTP media MUST
> > have a component ID of 1, and candidates for RTCP MUST have a
> > component ID of 2.
> 
> So from my point of view, FreeSwitch must do not provide ICE candidates with `component ID = 2`.
> Could you confirm?

No not really. RTCP must always be available and supported even if no `a=rtcp` attribute is present. The attribute exists merely to advertise a different address or port for receiving RTCP (with the default being the media port +1). So this is actually correct behaviour. (The only exception would be if `a=rtcp-mux` were in effect.)

> Also in PCAP and rtpengine log, I can see a lot of error messages like
> 
> > Binding Error Response Role conflict
> > ICE role conflict detected
> 
> Looks as FreeSwitch one time switched to `ICE-CONTROLLED` send a binding request as `ICE-CONTROLLING` again and again.
> Should it be also fixed?

Yes. The agent which started the ICE process (rtpengine) is supposed to be the controlling one (and remain the controlling one), and the other one (FS) is supposed to be the controlled. So FS is wrong here right away. But at least in the first iteration it correctly responds to the 487 by switching into controlled mode. After the re-invite it doesn't even do this.

**Comment by sergey-safarov** [comment]
For ICE role created ticket https://github.com/signalwire/freeswitch/issues/1163
Failed ICE negotiation related to first ReINVITE message.

Also in FreeSwitch log found message
```
2021-04-15 10:47:16.417287 [NOTICE] switch_rtp.c:1301 Auto Changing audio stun/rtp/dtls port from 2600:1f18:578:5700::1:f:17690 to 2600:1f18:578:5700::f:17621 idx:1
```
This message appear after second ReINVITE message.

We goes to fix ICE role first to make properly ICE negotiation after first ReINVITE.
When ICE role will be fixed on FreeSwitch site, then we will review STUN requests from RTP port to RTCP port.
