### ISSUE TITLE
Running in Docker w/ host kernel module: Invalid argument pushing relay stream

### ISSUE THREAD

**Issue by joshelson** [sipwise/rtpengine#1237]
I know the standard answer here is to make sure we have the same codebase compiling the kernel module and the rtpengine in the container, but that isn't resolving this issue for me now. This had been working properly for quite awhile until we attempted to update to current code here.

Now, when attempting to kernelize the media stream, we are seeing this set of errors:

```
kernel: Failed to generate session keys: failed to load AEAD
journal: [1618360527.009672] INFO: [u4v1e3g9oo7r8g5ujar5 port 50084]: [core] Kernelizing media stream: 10.100.127.164:16750
journal: [1618360527.010042] ERR: [u4v1e3g9oo7r8g5ujar5 port 50084]: [core] Failed to push relay stream to kernel: Invalid argument
journal: [1618360527.021201] INFO: [u4v1e3g9oo7r8g5ujar5 port 50096]: [core] Kernelizing media stream: 10.2.103.131:55314
journal: [1618360527.021736] ERR: [u4v1e3g9oo7r8g5ujar5 port 50096]: [core] Failed to push relay stream to kernel: Invalid argument
kernel: Failed to generate session keys: failed to load AEAD
journal: [1618360528.569302] INFO: [u4v1e3g9oo7r8g5ujar5 port 50085]: [core] Confirmed peer address as 10.100.127.164:16751
journal: [1618360528.570490] ERR: [core] Failed to get stream stats from kernel: No such file or directory
journal: [1618360528.570596] ERR: [core] Failed to delete relay stream from kernel: No such file or directory
journal: [1618360528.583498] INFO: [u4v1e3g9oo7r8g5ujar5 port 50096]: [core] Confirmed peer address as 10.2.103.131:55314
journal: [1618360528.583568] INFO: [u4v1e3g9oo7r8g5ujar5 port 50096]: [core] Kernelizing media stream: 10.2.103.131:55314
kernel: Failed to generate session keys: failed to load AEAD
journal: [1618360528.583793] ERR: [u4v1e3g9oo7r8g5ujar5 port 50096]: [core] Failed to push relay stream to kernel: Invalid argument
```

I've definitely run through all the scenarios here and can't see an obvious mismatch between the KO and the userspace process in the container. Host machine is fully patched CentOS 7 and container is running Buster, which has worked for us historically. Reverting seems to resolve the issue, though I'm not exactly sure where the issue may have been introduced for us. Have we run into a new mismatch between capabilities in the host and the container?

Anyone else run into this or have a good solution?

**Comment by rfuchs** [comment]
Sounds like your kernel is lacking support for AEAD-GCM encryption. In your `/proc/crypto` you should have an entry for `gcm(aes)` with `type = aead`

**Comment by joshelson** [comment]
So it looks like the host kernel does indeed have support for the AEAD-GCM.

Output here:

```
[root@host ~]# cat /proc/crypto
name         : gcm(aes)
driver       : gcm_base(ctr(aes-aesni),ghash-clmulni)
module       : gcm
priority     : 300
refcnt       : 1
selftest     : passed
type         : aead
async        : no
blocksize    : 1
ivsize       : 16
maxauthsize  : 16
geniv        : <built-in>
```

Anything else that's obvious I should look at?

**Comment by rfuchs** [comment]
Hm I'm not sure this is the same one. GCM-AES is supposed to have 12 bytes IV (not 16), and this is checked by the module when it's loaded: https://github.com/sipwise/rtpengine/blob/master/kernel-module/xt_RTPENGINE.c#L2058

e.g. on my system I see:

```
name         : gcm(aes)
driver       : generic-gcm-aesni
module       : aesni_intel
priority     : 400
refcnt       : 1
selftest     : passed
internal     : no
type         : aead
async        : yes
blocksize    : 1
ivsize       : 12
maxauthsize  : 16
geniv        : <none>
```

You can try disabling the check for the 12-byte IV in the kernel module and see what happens, but I suspect that AEAD won't work correctly then. Or you can comment out the AEAD stuff in crypto.c and just run without it. Or look for an updated kernel or AEAD driver that uses the correct 12-byte IV.

**Comment by rfuchs** [comment]
Cleaning up old tickets
