### ISSUE TITLE
Question : Is it possible to force rtpengine to use 101 PT instead of 126 when injecting DTMF ? 

### ISSUE THREAD

**Issue by sagarmalam** [sipwise/rtpengine#1238]
I am using rtpengine to convert sip info to rfc2833. I have observed that Rtpengine is using 126 PT instead of 101. For Example : 
v=0
o=FreeSWITCH 1618532762 1618532763 IN IP4 1.1.1.1
s=FreeSWITCH
c=IN IP4 1.1.1.1
t=0 0
m=audio 20966 RTP/AVP 0 126
a=rtpmap:0 PCMU/8000
a=rtpmap:**126** telephone-event/8000
a=fmtp:126 0-16
a=ptime:20
a=rtcp:20967 IN IP4 1.1.1.1

I am passing these params flags to rtpengine : 
inject-dtmf

I want to rtpengine to us 101 instead of 126. Is it possible ? 

Thanks in advance

**Comment by rfuchs** [comment]
`telephone-event` uses a dynamically allocated payload type, which start at 96. If rtpengine creates the PT, it would pick the first one available, which would be 96. If you see 126 then that must be coming from somewhere else. There's no inherent reason why 101 should be used for this. It's neither more nor less correct than 96 or 126 are.

**Comment by sagarmalam** [comment]
@rfuchs , Thank you reply. You are right. It is getting inherited from incoming invite.
