### ISSUE TITLE
RTP ports reused before they're free

### ISSUE THREAD

**Issue by mtryfoss** [sipwise/rtpengine#124]
This issue is found on a bit older version of rtpengine, but I'm submitting the issue anyway since It's hard to reproduce.

Scenario is as follows.
1) first call start. runs for over 2 hours without any problem
2) all of the 30000 allocated ports has been used (and most of them released again) so there are free ports available
3) new call starts and rtpengine tries to use a port still in used by the first call. fails with the following error: "Failed to push relay stream to kernel: File exists"
4) first call is disconnected, probably because of rtp missing

The ports in use for the first call:
Jun 17 11:44:57 rtp3 rtpengine[14825]: [7c2ddb6d-6df0e923@10.61.10.133] Final packet stats:
Jun 17 11:44:57 rtp3 rtpengine[14825]: [7c2ddb6d-6df0e923@10.61.10.133] --- Tag 'as25ceb574', created 136:32 ago, in dialogue with '41bf46e5ee85b40bo0'
Jun 17 11:44:57 rtp3 rtpengine[14825]: [7c2ddb6d-6df0e923@10.61.10.133] ------ Media #1, port 63986 <> 10.61.10.133:16442, 406684 p, 69923584 b, 0 e
Jun 17 11:44:57 rtp3 rtpengine[14825]: [7c2ddb6d-6df0e923@10.61.10.133] ------ Media #1, port 63987 <> 10.61.10.133:16443 (RTCP), 0 p, 0 b, 0 e
Jun 17 11:44:57 rtp3 rtpengine[14825]: [7c2ddb6d-6df0e923@10.61.10.133] --- Tag '41bf46e5ee85b40bo0', created 136:32 ago, in dialogue with 'as25ceb574'
Jun 17 11:44:57 rtp3 rtpengine[14825]: [7c2ddb6d-6df0e923@10.61.10.133] ------ Media #1, port 63984 <> x.x.x.21:18784, 406563 p, 69928836 b, 0 e
Jun 17 11:44:57 rtp3 rtpengine[14825]: [7c2ddb6d-6df0e923@10.61.10.133] ------ Media #1, port 63985 <> x.x.x.21:18785 (RTCP), 1626 p, 104064 b, 0 e

The second call:
Jun 17 11:44:06 rtp3 rtpengine[14825]: [5de1786b3370b7d828f35e85276e0ea4@x.x.x.45:5060 port 63984] Failed to push relay stream to kernel: File exists

Jun 17 11:46:08 rtp3 rtpengine[14825]: [5de1786b3370b7d828f35e85276e0ea4@x.x.x.45:5060] Final packet stats:
Jun 17 11:46:08 rtp3 rtpengine[14825]: [5de1786b3370b7d828f35e85276e0ea4@x.x.x.45:5060] --- Tag '3e959c5b', created 2:11 ago, in dialogue with 'as65e6667b'
Jun 17 11:46:08 rtp3 rtpengine[14825]: [5de1786b3370b7d828f35e85276e0ea4@x.x.x.45:5060] ------ Media #1, port 63984 <> x.x.x.45:15534, 4422 p, 760584 b, 0 e
Jun 17 11:46:08 rtp3 rtpengine[14825]: [5de1786b3370b7d828f35e85276e0ea4@x.x.x.45:5060] ------ Media #1, port 63985 <> x.x.x.45:15535 (RTCP), 17 p, 1088 b, 0 e
Jun 17 11:46:08 rtp3 rtpengine[14825]: [5de1786b3370b7d828f35e85276e0ea4@x.x.x.45:5060] --- Tag 'as65e6667b', created 2:11 ago, in dialogue with '3e959c5b'
Jun 17 11:46:08 rtp3 rtpengine[14825]: [5de1786b3370b7d828f35e85276e0ea4@x.x.x.45:5060] ------ Media #1, port 63982 <> x.x.x.120:44592, 902 p, 155052 b, 0 e
Jun 17 11:46:08 rtp3 rtpengine[14825]: [5de1786b3370b7d828f35e85276e0ea4@x.x.x.45:5060] ------ Media #1, port 63983 <> x.x.x.120:44593 (RTCP), 4 p, 296 b, 0 e
Jun 17 11:46:08 rtp3 rtpengine[14825]: [5de1786b3370b7d828f35e85276e0ea4@x.x.x.45:5060] Failed to delete relay stream from kernel: No such file or directory

I will try with a newer version of rtpengine as well, but it's hard to tell if the problem still exists.

**Comment by rfuchs** [comment]
Which version is this exactly?

**Comment by mtryfoss** [comment]
Seems like the latest git commit is this:
commit 88dfeee622772338a23157404c2cb827c07a18ee
Author: Richard Fuchs <rfuchs@sipwise.com>
Date:   Tue Apr 8 08:35:43 2014 -0400

**Comment by rfuchs** [comment]
This is probably fixed by e1cfc19c182d88c249d97bcd3821e5466c23efaf

**Comment by mtryfoss** [comment]
Thank you. I'll test a new checkout. Closing ticket for now and will reopen if problem persists.
