### ISSUE TITLE
cannot set maxsessions to default

### ISSUE THREAD

**Issue by sergey-safarov** [sipwise/rtpengine#1240]
I checked current `maxsessions` using command
```
[root@rtpengine ~]# rtpengine-ctl get maxsessions 
Maximum sessions configured on rtpengine: -1
```
Now I want set same  `maxsessions` value and get error
```
[root@rtp-us-east-1a-7 ~]# rtpengine-ctl set maxsessions -1
Unknown option: 1
```

**Comment by rfuchs** [comment]
That's just the Perl Getopt interpreting the leading dash `-` as a command line option (as is customary under POSIX). Use a double dash `--` to separate CLI options with verbatim arguments, e.g. `rtpengine-ctl -- set maxsessions -1`

**Comment by sergey-safarov** [comment]
I will create PR to update rtpengine-ctl help like
```
    set <option>
         help                  : generated complete list of sub-commands
         maxsessions  <int>    : set the max nr of allowed sessions. To disable limit please use 'rtpengine-ctl -- set maxsessions -1'
```

**Comment by rfuchs** [comment]
It might be better to tell Getopt not to allow this usage as it seems confusing. Setting `Getopt::Long::Configure('require_order')` in the script seems to do the trick.
