### ISSUE TITLE
missing a entry in /proc/rtpengine/0/list

### ISSUE THREAD

**Issue by hrickes** [sipwise/rtpengine#1244]
If i make a audio / video call with two sdes endpoints, the list has 4 entrys. This is ok.

If i make a audio / video call with a dtls and a sdes endpoint, the list has 3 entrys. One entry is missing.
[rtpengine_sdes.log](https://github.com/sipwise/rtpengine/files/6366606/rtpengine_sdes.log)
[rtpengine_sdes_proc.txt](https://github.com/sipwise/rtpengine/files/6366607/rtpengine_sdes_proc.txt)
[rtpengine_dtls.log](https://github.com/sipwise/rtpengine/files/6366608/rtpengine_dtls.log)
[rtpengine_dtls_proc.txt](https://github.com/sipwise/rtpengine/files/6366609/rtpengine_dtls_proc.txt)

**Comment by rfuchs** [comment]
Hm that's odd. Looks like local port 30026 is missing from the output. However the line `Targets:     4` indicates that it's actually there, and the log confirms (`INFO: [«bgfe2iqiv0a21uglhsi5» port 30026]: [core] Kernelizing media stream: «172.22.11.7:33260»
`). So this looks like a cosmetic issue of the section simply being omitted from the output for some reason.

Is this 100% reproducible? Any other factors that have an influence whether you see the section in the output or not? Anything relevant in `dmesg`?

**Comment by hrickes** [comment]
Yes it is reproducible. There is nothing to be seen in dmesg.
The same (3 entries, 2 audio and 1 video) can be seen when two dtls endpoints call each other or a sdes endpoint calls a dtls endpoint.
[rtpengine_dtls-dtls.log](https://github.com/sipwise/rtpengine/files/6383856/rtpengine_dtls-dtls.log)
[rtpengine_dtls-dtls_proc.txt](https://github.com/sipwise/rtpengine/files/6383857/rtpengine_dtls-dtls_proc.txt)
[rtpengine_sdes-dtls.log](https://github.com/sipwise/rtpengine/files/6383858/rtpengine_sdes-dtls.log)
[rtpengine_sdes-dtls_proc.txt](https://github.com/sipwise/rtpengine/files/6383859/rtpengine_sdes-dtls_proc.txt)
