### ISSUE TITLE
Discarded invalid SRTP packet: authentication failed; between call recording start/stop

### ISSUE THREAD

**Issue by smititelu** [sipwise/rtpengine#1248]
Hi, I am doing some SRTP tests using crypto aescm128sha1321audio and I saw the above warning.

I've modified the ilog() code in ```daemon/rtp.c``` line 233 so that it will print for every packet.

I noticed that the above warning is logged and ```cat /proc/rtpengine/0/list``` prints errors untill call recording stops. Afterwards, kernelization happened for both UAC and UAS, no more warning is logged and ```cat /proc/rtpengine/0/list``` doesn't print errors anymore.

I've attached an (IP obfuscated) logs to this issue:
1.1.1.1 -> sipp UAC
2.2.2.2 -> rtpengine
3.3.3. -> sipp UAS that acts as an rtp echo (when it receives anything)
99.99.99.99 -> rtpengine control

Do you have any idea what is happening?

Thank you,
Stefan

[rtpengine.zip](https://github.com/sipwise/rtpengine/files/6392760/rtpengine.zip)

**Comment by rfuchs** [comment]
Can't really say without having the SRTP keys to verify encryption. Recording doesn't really have an effect on SRTP, with the exception that recording requires decrypt/encrypt in case of symmetric SDES, while without recording the SRTP packets can simply be passed through (in this case you would not see any SRTP parameters in `../list`). So my guess is that this is with symmetric SDES and somehow the SDES keys are wrong.

**Comment by smititelu** [comment]
This are my new findings, related to auth keys used for *calculating and validating auth hmac*, for a newly run example (keys are regenerated each new example):
- sipp:
    - for sent packets, uses auth key: fabe604a3727170c80346d5dcb3f33ff78bb7cc2
    - for received packets, uses auth key: 5e0d754ffec2c50923616b8ae034b42b6ce05a2f (the rtpengine one)
- rtpengine:
    - for both received packets (e.g. when ```rtp_savp2avp()``` is called) and sent packets (e.g. when ```rtp_avp2savp()``` is called) uses auth key: 5e0d754ffec2c50923616b8ae034b42b6ce05a2f   (e.g. the one in ```struct crypto_context->session_auth_key[SRTP_MAX_SESSION_AUTH_LEN]```)
    
You were right in the first place, the auth keys used are wrong. This causes the auth hmac mismatch on rtpengine side when ```rtp_savp2avp()``` is called because mismatch of auth key used when sipp is sender and rtpengine is receiver.

I think rtpengine should be improved to keep and use 2 auth keys, one for received and one for sent packets, do you agree?

**Comment by rfuchs** [comment]
Er, no. We already have separate keys for sending and receiving. This is a requirement of SRTP.

The crypto context (which holds the keys) for receiving packets is kept in `struct stream_fd` while the crypto context for sending packets is kept in `struct packet_stream`

Auth keys are derived from the SRTP master keys, which are carried in the `a=crypto` SDP lines in case of SDES. Received SDP → incoming SRTP keys, sent SDP → outgoing SRTP keys.

IOW the only way rtpengine would use the same keys for both directions is if it had received the same SRTP keys in an incoming SDP as it had sent in an outgoing SDP. Do you perhaps have your from/to tags in the signalling going to rtpengine mixed up?

**Comment by smititelu** [comment]
Indeed, I had the to tag equal to from tag, in signalling. All works now. Thanks very much for the support.

Closing this as is not an issue.
