### ISSUE TITLE
No audio after reInvite on inbound call to webrtc

### ISSUE THREAD

**Issue by rhondahollis** [sipwise/rtpengine#1249]
I'm having an issue where inbound calls to a webrtc client are getting set up successfully, with audio in both directions, but after a reInvite to MOH or back off hold, there is no audio. In the Chrome debug logs I see these messages after the reInvites:
ERROR:dtls_transport.cc(622)] DtlsTransport[1|1|__]: Received non-DTLS packet before DTLS complete.

This same call is working in Firefox without any issue. And if the call direction is reversed, where it's outbound from webrtc, then there is no issue with the holds, regardless if they are initiated by caller or callee. 

I've tried some different values on the settings I am sending to rtpengine, but I haven't had any luck in resolving this, so I'm hoping you might be able to take a look and let me know if there is anything here that looks like it might be contributing to the issue.

I'm using the following flags in the offer/answer to rtpengine when facing the webrtc client:
{
    'transport-protocol': 'UDP/TLS/RTP/SAVPF',
    'ICE': 'force',
    'rtcp-mux': ['require'],
    'flags': ['SDES-no', 'generate mid', 'codec-strip-all', 'codec-except-G722', 'codec-except-PCMU','codec-except-PCMA', 'codec-offer-telephone-event']
  };

And these are the flags for the other side:
{
    'transport protocol': 'RTP/AVP',
    'DTLS': 'off',
    'ICE': 'remove',
    'rtcp-mux': ['demux'], 
    'flags':['SDES-no', 'codec-strip-all', 'codec-except-G722', 'codec-except-PCMU', 'codec-except-PCMA', 'codec-offer-telephone-event']
  };

The attached logs show a call coming in to the webrtc client, followed by 3 more offers: Invite on hold, Invite to MOH, Invite off hold.

I appreciate any assistance you can provide with this one! Thanks.

[rtpEngine_inbound_reInviteNoAudio.log](https://github.com/sipwise/rtpengine/files/6402258/rtpEngine_inbound_reInviteNoAudio.log)
[chromeDebug_inbound_reInviteNoAudio.txt](https://github.com/sipwise/rtpengine/files/6402260/chromeDebug_inbound_reInviteNoAudio.txt)

**Comment by rfuchs** [comment]
Upgrade rtpengine or use `DTLS-fingerprint=sha-256`

**Comment by rhondahollis** [comment]
I ran the test again with `DTLS-fingerprint=sha-256`, but the result is the same. I'll work on upgrading our rtpengine to the latest today, but to help me understand better what's going on, can you tell me what upgrade(s) in the later release will address this issue? thanks again!

[rtpEngine_Apr30.log](https://github.com/sipwise/rtpengine/files/6406216/rtpEngine_Apr30.log)

**Comment by rfuchs** [comment]
`Apr 30 07:38:20 dractchio-rtpengine01-dev-s03 rtpengine[8385]: WARNING: [BW073820432300421-594692488@10.103.43.11]: [core] Unknown flag encountered: 'DTLS-fingerprint=sha-256'`

No way around that upgrade...

The problem has been described several times before: The first offer coming out of rtpengine uses the default sha-1, then the answer from WebRTC uses sha-256, which makes rtpengine also switch to sha-256. The subsequent re-invite then uses sha-256, which WebRTC sees as a DTLS restart (fingerprint changed) but rtpengine doesn't, because it's still the same certificate. One side restarts DTLS but the other side doesn't -> no media.

**Comment by rhondahollis** [comment]
Calls are working great after the upgrade. Thanks!
