### ISSUE TITLE
AWS EC2 configuration

### ISSUE THREAD

**Issue by StanislavKo** [sipwise/rtpengine#125]
Just a question, not an issue.
I get hundreds of "ICE/STUN binding request received on unknown local interface address" messages in syslog.
Could somebody point EC2 configuration?

EC2 Public IP: 20.20.20.20
EC2 Private IP: 21.21.21.21
Client Internet IP: 77.77.77.77
1) startup
sudo /usr/local/src/rtpengine-mr3.8/rtpengine/daemon/rtpengine --table=0 --interface=internal/20.20.20.20\!21.21.21.21 --interface=external/20.20.20.20 --listen-udp=127.0.0.1:12222 --listen-ng=127.0.0.1:22222 --pidfile=/var/run/rtpengine.pid -L 7
2) kamailio.cfg
listen=udp:21.21.21.21:10080
listen=tcp:21.21.21.21:10080
listen=udp:21.21.21.21:5060
listen=tcp:21.21.21.21:5060
advertised_address = "20.20.20.20"
alias = "20.20.20.20"

rtpengine_manage("rtcp-mux-demux force trust-address replace-origin replace-session-connection external external media-address=20.20.20.20 ICE=force RTP/SAVPF");

I get lots of "ICE/STUN binding request received on unknown local interface address (from 77.77.77.77:51234 on interface 21.21.21.21)"
Thank you.

**Comment by linuxmaniac** [comment]
For questions please refer them to spce-user mailing list
spce-user@lists.sipwise.com
https://lists.sipwise.com/listinfo/spce-user
