### ISSUE TITLE
rtpengine transcoding options

### ISSUE THREAD

**Issue by jonhvoxbox** [sipwise/rtpengine#1254]
hi Guys,

Sorry for this question, however I wanted to know if this was possible and in the readme I am unsure.

Essentially I has a CPE device which supports G729 only, and a carrier that supports PCMA only, can I use rtpengine_manage for this in both offer and answer routes in kamailio, or is that not possible?

I need all offer/answers to be G729 to CPE, and likewise all PCMA on carrier side, is this possible?

I have tried the mask and transcode options but not had much look as yet, seems to only work on an offer. (however I assume this is my fault :).

Thanks

Jon

**Comment by jonhvoxbox** [comment]
Sorry correction the carrier support G711/G729 but I always want to enforce transcoding if this is the case, is to possible to force rtpengine to transcode?

**Comment by rfuchs** [comment]
Sure, you just have to mind the direction in which the signalling is travelling. For example, when signalling CPE -> carrier, you could use "codec-consume-G729" or "codec-mask-G729". Another option would be something like "codec-mask-all codec-transcode-PCMA". In direction carrier -> CPE you could use something like "codec-mask-PCMA" or "codec-accept-PCMA". I suggest using a recent version of rtpengine for this.

**Comment by jonhvoxbox** [comment]
Thanks Richard that works perfectly! Appreciate the response.
