### ISSUE TITLE
.MOV file name in digits. Need to DECIPHER guys! 

### ISSUE THREAD

**Issue by Bahtiyar-byte** [sipwise/rtpengine#1256]
So my friend sent me this video in iMessages. Lying to me that video was recorded at a different date. Can I tell by the name of the .MOV file some information. 
The name of the files are:
1. recorded-460485301973
2. recorded-4605120303849 

Is there any meaning in these numbers? Searched metadata, just shows as "Created" the Date and Time i saved in my files, does not have video TAKEN date&time.

Thank you people!

**Comment by rfuchs** [comment]
Is this related to rtpengine? We don't create .mov files anywhere.

**Comment by Bahtiyar-byte** [comment]
> Is this related to rtpengine? We don't create .mov files anywhere.

I got the Videos in iMessages on iPhone. The names of the videos are as follows: 

recorded-460485301973.mov
recorded-4605120303849.mov

Just wanted to see if someone could try to decipher the numbers/ints in the name of the file. Maybe somehow I could actually tell by looking at the names of these files when they were created.
