### ISSUE TITLE
Own sessions become foreign after restart

### ISSUE THREAD

**Issue by pkuzak** [sipwise/rtpengine#1257]
Own sessions become foreign after restart:

> rtpengine-ctl list numsessions all
Current sessions own: 50
Current sessions foreign: 0
Current sessions total: 50
Current transcoded media: 0
Current sessions ipv4 only media: 50
Current sessions ipv6 only media: 0
Current sessions ip mixed  media: 0
service ngcp-rtpengine-daemon restart
rtpengine-ctl list numsessions all
Current sessions own: 0
Current sessions foreign: 50
Current sessions total: 50
Current transcoded media: 0
Current sessions ipv4 only media: 50
Current sessions ipv6 only media: 0
Current sessions ip mixed  media: 0

Expected behavior would be that own sessions stay own after restart.

**Comment by rfuchs** [comment]
What does your config look like?

**Comment by pkuzak** [comment]
It is the latest code.
Config looks like:

> [rtpengine]
table = 0
interface = pub3/IPv41;pub3/IPv61;pub1/IPv42;pub1/IPv62
redis = 10.84.1.151:6379/3
redis-write = 10.84.1.47:6379/3
subscribe-keyspace=1
listen-ng = 10.84.1.151:8800
listen-cli = 127.0.0.1:9900
timeout = 3600
silent-timeout = 3600
tos = 144
delete-delay = 25
final-timeout = 11000
pidfile = /var/run/ngcp-rtpengine-daemon.pid
port-min = 8192
port-max = 63487
max-sessions = 10000
log-facility = local7
log-facility-cdr = local6
no-redis-required = true
redis-expires = 10860
redis-allowed-errors = 0
redis-disable-time = 10
redis-cmd-timeout = 10
redis-connect-timeout = 10
control-tos = 144
recording-dir = /var/spool/rtpengine
recording-method = proc
recording-format = raw
save-interface-ports = true
graphite = test-accvograph.server.lan:2003
graphite-interval = 60
graphite-prefix = system.test-rtpproxy1-bap_voip-test_server_lan.rtpengine.

It should be pretty easy to reproduce, simply restarting the service with Redis support as long as there are own sessions.

**Comment by rfuchs** [comment]
Do you use Redis replication?

The current logic during restart is: sessions restored from `redis-write` are owned, and sessions restored from the other one (`redis`) are foreign - because that is what they should have been before the restart.

**Comment by rfuchs** [comment]
> In our case, the decision whether the calls are foreign or own should be made based on the Redis keyspace where the data was read from. Calls which are restored from the keyspace that an RTPengine was subscribed to should be counted as foreign, the others own.

Ok I see. This is different from our setup where the Redis "read" DB number is the same as the keyspace that it's subscribed to. Would something like this work for your setup then?

1) Restore calls from "write" DB as "owned"
2) For the "read" DB, which is the same connection as is used for the notifications, restore calls from each DB number from the keyspace notifications list as "foreign", and completely ignore the DB number given for the "read" DB.

**Comment by pkuzak** [comment]
From the use case point of view, this would work for us. The only thing I do not like so much is that you have to load data from a distant DB (write DB) although the data is also present locally (read DB). But I have no alternative proposal so we'd go with your proposal.

**Comment by rfuchs** [comment]
So that would look something like 5547072 (untested)

I also considered adding a new option to disable this dual restore altogether if you say you don't need it.
