### ISSUE TITLE
Foreign sessions are stopped being established after some time of running

### ISSUE THREAD

**Issue by pkuzak** [sipwise/rtpengine#1258]
Foreign sessions are stopped being established after some time of running. It is difficult for me to give more details and it difficult for me to reproduce this. But running it in our live system, after some minutes there is no change on foreign sessions anymore. The established ones are slowly terminated by timeout, but no new ones are established. 
I saw in the commits that some work was done in this context, maybe you have a clue what change could cause this behavior.

**Comment by rfuchs** [comment]
Not off the top of my head. As long as the Redis key notifications are working, you should see new foreign sessions being established. You can verify that by looking at the data in Redis. Also sessions marked as "foreign" should be exempt from any timeouts (save the "final" timeout).
