### ISSUE TITLE
rtpengine log: [transcoding] Switched from input to output codec context, but no codec handler present

### ISSUE THREAD

**Issue by thomas414** [sipwise/rtpengine#1259]
Hi all,

since one of the recent updates rtpengine spams this line into the logfile:
ERR: [######################### port 38002]: [transcoding] Switched from input to output codec context, but no codec handler present

it doesn't happen on every call but when it happens it seems to do this on every transcoder context switch, so the log file gets very big very fast. The rtp stream for these calls is perfectly fine, so this seems to be only an issue with the logging.

Is there a way to suppress this message or maybe output this message only once per session?
I can also provide you with debug logs if you want to investigate the problem more closely.

Best regards,
Thomas

**Comment by rfuchs** [comment]
That's probably related to some supplemental codec (DTMF or CN). The codec stuff is being reworked right now, so there's not much point in investigating further here. I will add a log limiter to this log line.
