### ISSUE TITLE
rtpengine[15985]: realloc(): invalid next size

### ISSUE THREAD

**Issue by davidtek** [sipwise/rtpengine#1260]
After leaving rtpengine running for some time, it crashed outputting only the following message to syslog : 

```
rtpengine[15985]: realloc(): invalid next size
```

SystemD reports : 

```
systemd[1]: ngcp-rtpengine-daemon.service: Main process exited, code=killed, status=6/ABRT
```

Grepping the code shows the only call to realloc() is in daemon/poller.c:214 in the function __poller_add_item.

The documentation for realloc() says that NULL is returned in the event of an error, but there does not seem to be anything to handle this null value and I suspect that on line 215 during the call to memset, the NULL value caused the daemon to abort.

Kernel Version : 

```
uname -a
Linux  5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

RTPEngine : 9.4.0.0+0~mr9.4.0.0+nmu1

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```
Ubuntu Focal is based on Debian Bullseye.

dmesg shows no messages within 72 hours either side of the crash.

I found no other logs containing relevant information.

I am not able to reliably reproduce this issue.

**Comment by rfuchs** [comment]
Don't rebuild the package as the symbols will be different.

You should have a -dbg or -dbgsym package generated when building the packages. Simply install it and you will have the symbols.

**Comment by rfuchs** [comment]
Cleaning up old tickets
