### ISSUE TITLE
issues compiling latest git pull

### ISSUE THREAD

**Issue by soulofmischief87** [sipwise/rtpengine#1263]
Hello,

I am trying to update to the latest version on git but I am facing compilation issues. I am not sure if I am missing a dependency but it isn't clear.

  make
make -C daemon
make[1]: Entering directory `/usr/local/src/rtpengine/daemon'
make rtpengine rtpengine.8
make[2]: Entering directory `/usr/local/src/rtpengine/daemon'
cc -g -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wstrict-prototypes -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread     -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg     -DWITH_TRANSCODING -I/usr/include/mysql -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DHAVE_BCG729   -DRTPENGINE_VERSION="\"git-master-d3390ba\""   -c -o main.o main.c
cc -g -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wstrict-prototypes -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread     -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg     -DWITH_TRANSCODING -I/usr/include/mysql -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DHAVE_BCG729   -DRTPENGINE_VERSION="\"git-master-d3390ba\""   -c -o kernel.o kernel.c
cc -g -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wstrict-prototypes -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread     -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg     -DWITH_TRANSCODING -I/usr/include/mysql -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DHAVE_BCG729   -DRTPENGINE_VERSION="\"git-master-d3390ba\""   -c -o poller.o poller.c
cc -g -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wstrict-prototypes -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread     -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg     -DWITH_TRANSCODING -I/usr/include/mysql -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DHAVE_BCG729   -DRTPENGINE_VERSION="\"git-master-d3390ba\""   -c -o aux.o aux.c
cc -g -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wstrict-prototypes -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread     -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg     -DWITH_TRANSCODING -I/usr/include/mysql -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DHAVE_BCG729   -DRTPENGINE_VERSION="\"git-master-d3390ba\""   -c -o control_tcp.o control_tcp.c
cc -g -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wstrict-prototypes -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread     -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg     -DWITH_TRANSCODING -I/usr/include/mysql -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DHAVE_BCG729   -DRTPENGINE_VERSION="\"git-master-d3390ba\""   -c -o call.o call.c
cc -g -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wstrict-prototypes -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread     -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg     -DWITH_TRANSCODING -I/usr/include/mysql -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DHAVE_BCG729   -DRTPENGINE_VERSION="\"git-master-d3390ba\""   -c -o control_udp.o control_udp.c
cc -g -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wstrict-prototypes -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread     -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg     -DWITH_TRANSCODING -I/usr/include/mysql -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DHAVE_BCG729   -DRTPENGINE_VERSION="\"git-master-d3390ba\""   -c -o redis.o redis.c
cc -g -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wstrict-prototypes -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread     -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg     -DWITH_TRANSCODING -I/usr/include/mysql -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DHAVE_BCG729   -DRTPENGINE_VERSION="\"git-master-d3390ba\""   -c -o bencode.o bencode.c
bencode.c:39:2: warning: missing initializer for field ‘iov_len’ of ‘struct iovec’ [-Wmissing-field-initializers]
  .iov[0].iov_len = 1,
  ^
In file included from /usr/include/sys/uio.h:29:0,
                 from ../include/bencode.h:4,
                 from bencode.c:1:
/usr/include/bits/uio.h:46:12: note: ‘iov_len’ declared here
     size_t iov_len; /* Length of data.  */
            ^
cc -g -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wstrict-prototypes -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread     -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg     -DWITH_TRANSCODING -I/usr/include/mysql -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DHAVE_BCG729   -DRTPENGINE_VERSION="\"git-master-d3390ba\""   -c -o cookie_cache.o cookie_cache.c
cc -g -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wstrict-prototypes -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread     -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg     -DWITH_TRANSCODING -I/usr/include/mysql -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DHAVE_BCG729   -DRTPENGINE_VERSION="\"git-master-d3390ba\""   -c -o udp_listener.o udp_listener.c
../utils/const_str_hash < "control_ng.c" > "control_ng.strhash.c"
cc -g -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wstrict-prototypes -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread     -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg     -DWITH_TRANSCODING -I/usr/include/mysql -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DHAVE_BCG729   -DRTPENGINE_VERSION="\"git-master-d3390ba\""   -c -o control_ng.strhash.o control_ng.strhash.c
control_ng.strhash.c:45:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 __csh_hash (str, len)
 ^
control_ng.strhash.c:89:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 __csh_lookup_raw (str, len)
 ^
control_ng.strhash.c: In function ‘__csh_lookup_raw’:
control_ng.strhash.c:110:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""}, {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:110:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""}, {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:110:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""}, {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:110:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""}, {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:114:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:114:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:117:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:120:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:123:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:123:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:123:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:125:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:125:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:125:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:128:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:128:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:128:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:132:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:132:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:132:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:134:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""}, {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:134:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""}, {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:134:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""}, {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
control_ng.strhash.c:134:7: warning: missing initializer for field ‘num’ of ‘struct __csh_hash_lookup’ [-Wmissing-field-initializers]
       {""}, {""}, {""}, {""},
       ^
control_ng.strhash.c:33:44: note: ‘num’ declared here
 struct __csh_hash_lookup { char *name; int num; };
                                            ^
In file included from ../lib/loglib.h:9:0,
                 from ./log.h:6,
                 from ../include/obj.h:93,
                 from ../include/control_ng.h:4,
                 from control_ng.strhash.c:161:
../lib/auxlib.h: At top level:
../lib/auxlib.h:275:32: error: unknown type name ‘uint32_t’
 INLINE double ntp_ts_to_double(uint32_t whole, uint32_t frac) {
                                ^
../lib/auxlib.h:275:48: error: unknown type name ‘uint32_t’
 INLINE double ntp_ts_to_double(uint32_t whole, uint32_t frac) {
                                                ^
make[2]: *** [control_ng.strhash.o] Error 1
rm control_ng.strhash.c
make[2]: Leaving directory `/usr/local/src/rtpengine/daemon'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/

**Comment by rfuchs** [comment]
Which platform/distro is this on?

**Comment by soulofmischief87** [comment]
rfuchs,

I am using CentOS Linux release 7.9.2009 (Core).

I was using a previous version of rtpengine and compiled it fine from the latest git pull a year or so ago.

Thanks
