### ISSUE TITLE
Multicast possibilities

### ISSUE THREAD

**Issue by LadMartin** [sipwise/rtpengine#1264]
Hi, I would like to ask about the possibility to use IP multicast with rtpengine. My goal to have a broadcaster that will call all the endpoints, but the RTP of the broadcaster will go via multicast to the rtpengine. the endpoints might not support multicast, but I want to save the rtp channels at least on the local network.

Is something like that already possible? If not (at least I haven't find any evidence of it) then do you think that it's feasible to add it? If yes can you provide some hints on where to start so I can try to implement it?

Thanks

p.s. a rough schema
endpoint <---unicast-- rtpengine <--multicast <-- broadcaster
endpoint <---unicast-----|
endpoint <---unicast-----|
.                                     |
.                                     |
.                                     |
endpoint <---unicast-----|

**Comment by rfuchs** [comment]
There's zero support for multicast right now. We will have support for "multi forwarding" in the near future, where one unicast stream is duplicated to multiple unicast receivers. I suppose this could then be extended to a multicast listener, even though I have zero experience with multicast and don't really know what it would take to create a multicast listener.

**Comment by LadMartin** [comment]
The multi forwarding is very interesting I will think if I could have a use for that, what is "near" future, roughly?

I do not have experience with the multicast either, But I have tried this simple example https://www.tenouk.com/Module41c.html
it seems to be just about calling setsockopt in order to join the multicast group. Eventually setting TTL for the socket

and from SDP perspective it is about detecting that the address is multicast and then approaching it accordingly -  as described here https://datatracker.ietf.org/doc/html/rfc2327#section-5.1 so that the same address and port is used in the sdp answer as well

>    This address and port are the destination address and destination
   port of the multicast stream, whether being sent, received, or both.

**Comment by rfuchs** [comment]
> The multi forwarding is very interesting I will think if I could have a use for that, what is "near" future, roughly?

I don't have a firm timeline but I hope to have it ready within the next month. With that in place, it should be possible to achieve what you want, if all the peculiarities regarding multicast are taken care of.

**Comment by rfuchs** [comment]
Cleaning up old tickets (media forking patching are coming into master now)
