### ISSUE TITLE
segfaults on mr9.4

### ISSUE THREAD

**Issue by thomas414** [sipwise/rtpengine#1265]
Hi all,

after updating to rtpengine mr9.4 last weekend we now had the second case that rtpengine crashes with segfault errror. (while updating we also did a pretty big configuration change regarding dtmf transcoding and transcoding in general, so that could also be the cause) 
Following error is in kern.log:
```
poller[22604]: segfault at 138 ip 00005602aa09ae18 sp 00007fe07cf704e0 error 4 in rtpengine[5602aa02a000+92000]
```
and in coredump file:
```
#4  0x000000000007cb97 in __make_transcoder (handler=0xfffffffffffffff0, dest=0x7fe07d778700, output_transcoders=0x5602abc33640, dtmf_payload_type=-1, pcm_dtmf_detect=-1413270064) at codec.c:313 __PRETTY_FUNCTION__ = <error reading variable __PRETTY_FUNCTION__ (Cannot access memory at address 0xb5310)>
```
Hope this helps to resolve the issue, if you need more information please tell me.

Best regards
Thomas

**Comment by rfuchs** [comment]
A full backtrace would be helpful. Also which commit exactly are you on?

**Comment by thomas414** [comment]
Exact version is: 9.4.1.0+0~mr9.4.1.0 git-mr9.4-7a90c339 and i have attached a full backtrace

[gdb.log](https://github.com/sipwise/rtpengine/files/6494352/gdb.log)

**Comment by rfuchs** [comment]
Looks like you're missing the debug symbols. Install the -dbgsym package and run the backtrace again.

**Comment by thomas414** [comment]
Hi, sorry this is the first time i am working with coredumps and backtraces, so i am just introducing myself to the topic.
Which exactly is needed? I have installed all that are available after building the packages: ngcp-rtpengine-daemon-dbgsym, ngcp-rtpengine-iptables-dbgsym, ngcp-rtpengine-recording-daemon-dbgsym and libbcg729-0-dbg

**Comment by rfuchs** [comment]
That should be all that's necessary. Does the core dump match the binaries/packages that produced it? Or did you rebuild/reinstall the packages after the core was generated?

**Comment by thomas414** [comment]
Yes i'm pretty sure that they match. Only the dbgsym packages were installed after the core dump was generated.
But i can rebuild and reinstall all packages to be 100% sure and come back to you if we get another segfault crash.

**Comment by thomas414** [comment]
I think i have now managed to get a correct backtrace, it is attached.

[gdb.txt](https://github.com/sipwise/rtpengine/files/6501915/gdb.txt)

**Comment by rfuchs** [comment]
Ok I can see the problem. Do you know what leads up to these crashes by any chance? Re-invites with codec changes or any some such?

**Comment by rfuchs** [comment]
edd1464 should fix the crash but I can't say whether the behaviour is correct without knowing the circumstances.

**Comment by thomas414** [comment]
Re-invites with codec changes are very possible, though i can't be really sure about it, but we can try to find any cause if this should appear again.
Thank you for the quick fix, i can see that the automatic unit tests failed on your side, do you think it is safe to deploy this anyway?

**Comment by rfuchs** [comment]
> Thank you for the quick fix, i can see that the automatic unit tests failed on your side, do you think it is safe to deploy this anyway?

That looks like a false positive. We run the same tests on our own systems and they were successful there. Some of them are timing sensitive and so there can be the occasional stray failure on loaded systems.
