### ISSUE TITLE
one way audio after transfer from webrtc to PSTN

### ISSUE THREAD

**Issue by rhondahollis** [sipwise/rtpengine#1266]
When there are two webrtc clients on a call and one transfers the other to PSTN, the transferred call gets one way audio. 
The initial call is between two of our clients, so the flow is:
webrtc (jssip) --> Drachtio (b2bua) w/rtpengine --> SBC --> Drachtio/rtpengine --> webrtc
When one of the users is then transferred to a non-webrtc endpoint, the port and connection IP remains the same, but you can see in the sdp that the ssrc and msid attributes are removed.

Last sdp for webrtc far end:
v=0^M
o=BroadWorks 625749 1 IN IP4 208.73.144.98^M
s=-^M
t=0 0^M
a=msid-semantic:WMS *^M
m=audio 25270 RTP/AVP 9 0 8 126^M
c=IN IP4 208.73.144.98^M
a=msid:{92177f93-3c72-c442-aa47-5530cbac5278} {71c188ed-2286-1e41-91ae-cc76e1509bda}^M
a=ssrc:1101184494 cname:{5a8f184e-a38b-5944-93ce-aef3b174b983}^M
a=mid:0^M
a=rtpmap:9 G722/8000/1^M
a=rtpmap:0 PCMU/8000^M
a=rtpmap:8 PCMA/8000^M
a=rtpmap:126 telephone-event/8000^M
a=fmtp:126 0-15^M
a=sendrecv^M
a=end-of-candidates

sdp for connection to the transfer target:
v=0^M
o=BroadWorks 625749 2 IN IP4 208.73.144.98^M
s=-^M
c=IN IP4 208.73.144.98^M
t=0 0^M
m=audio 25270 RTP/AVP 0 126^M
a=rtpmap:0 PCMU/8000^M
a=rtpmap:126 telephone-event/8000^M
a=fmtp:126 0-15^M
a=sendrecv^M
a=maxptime:20

I did see that there were recent changes in rtpengine around ssrc handling, so I upgraded our build on Friday, but it did not change the behavior I'm seeing here. I've also tried to use the `reset` flag, but that didn't work either.  At this point, I would really like to get confirmation on whether or not my call flow at the rtpengine is correct. I'm still new at debugging at the rtpengine level, so your eyes on this would be a great help. Thank you!

[may17_transfer.log](https://github.com/sipwise/rtpengine/files/6497622/may17_transfer.log)

**Comment by rfuchs** [comment]
I'm not sure where you're seeing what you're describing. Rtpengine doesn't touch ssrc nor msid attributes (neither removes them nor adds them). The second SDP you posted is not an output from rtpengine, but is rather given to rtpengine as an incoming offer. So I'm a bit confused about what you expect to see here.

**Comment by rhondahollis** [comment]
Right, those SDP's were just to show where the transfer to the PSTN occurs. My concern was that the removal of the ssrc attribute would be causing problems, but as far as I can see it looks like all of the STUN requests and DTLS negotiations continue to happen without error. I've been looking at pcaps from within our network and haven't found yet where the audio is getting dropped, so basically, I want to make sure that I haven't missed something on the rtpengine side.

**Comment by rhondahollis** [comment]
For Chrome, I resolved this issue by removing the ssrc and msid attributes for the non-webrtc side of the call. Chrome was removing the receiving stream when the ssrc attribute was no longer presented in the sdp after the transfer.
For Firefox, which had the one way audio issue in the opposite direction, I had to add the `always transcode` flag.
