### ISSUE TITLE
rtpengine recording - possibility to have sdp stream label in filename

### ISSUE THREAD

**Issue by ivlovric** [sipwise/rtpengine#1269]
Hi rtpengine team and thanks for this nice project!

We are using rtpengine recording and have already requested some changes to filename patterns and thanks for that. Our next project we are trying to accomplish is to somehow distinguish calling and called side in recorded filenames as we are using separete recordings without mixing.

One possible way to do this could be to use INVITE SDP body **_stream label_** and pass it as option for filename pattern.
As we are using SIPREC protocol which also contains xml metadata in requests with same _**stream label**_ 

Maybe more details can be used from rfc definition here https://datatracker.ietf.org/doc/html/rfc7866#section-8.3.1

We are also attaching one example with SIPREC request.

Thans a lot,
I
[siprec_example.txt](https://github.com/sipwise/rtpengine/files/6518614/siprec_example.txt)

**Comment by rfuchs** [comment]
We already support labels for call recording, although they're labels for call participants (tags) and not individual streams. In the rtpengine offer/answer you would use the `label=...` option, and then with 274776e you can use the `%l` format to add it to a file name.

**Comment by ivlovric** [comment]
Thank you! We tried but cant get "%l" variable visible in filename, like variable is empty at that point. It is visible as label in rtpengine logs though. 
It still could not be enough for us as we need to distinguish individual streams from SDP labels and get it link somehow with filenames.
<img width="412" alt="image" src="https://user-images.githubusercontent.com/37185376/119354878-de969100-bca4-11eb-9174-a75f0b166cdb.png">

Ivica
