### ISSUE TITLE
Error parsing RTP header: invalid header version

### ISSUE THREAD

**Issue by mtryfoss** [sipwise/rtpengine#127]
Hi,

Rtpengine gives me this error, but audio seems to work:
Jun 25 08:38:51 rtp2new rtpengine[17397]: [509847897b43e1d56e566ced236e3360@10.11.40.45:5060] Received command 'offer' from 158.58.154.15:42317
Jun 25 08:38:51 rtp2new rtpengine[17397]: [509847897b43e1d56e566ced236e3360@10.11.40.45:5060] Creating new call
Jun 25 08:38:51 rtp2new rtpengine[17397]: [509847897b43e1d56e566ced236e3360@10.11.40.45:5060] Replying to 'offer' from 158.58.154.15:42317
Jun 25 08:38:51 rtp2new rtpengine[17397]: [509847897b43e1d56e566ced236e3360@10.11.40.45:5060 port 52698] Error parsing RTP header: invalid header version
Jun 25 08:38:51 rtp2new rtpengine[17397]: [509847897b43e1d56e566ced236e3360@10.11.40.45:5060] Received command 'answer' from 158.58.154.15:40627
Jun 25 08:38:51 rtp2new rtpengine[17397]: [509847897b43e1d56e566ced236e3360@10.11.40.45:5060] Replying to 'answer' from 158.58.154.15:40627
Jun 25 08:38:51 rtp2new rtpengine[17397]: [509847897b43e1d56e566ced236e3360@10.11.40.45:5060 port 52710] Error parsing RTP header: invalid header version
Jun 25 08:38:56 rtp2new rtpengine[17397]: [509847897b43e1d56e566ced236e3360@10.11.40.45:5060 port 52699] Confirmed peer address as 10.65.2.5:47685
Jun 25 08:39:03 rtp2new rtpengine[17397]: [509847897b43e1d56e566ced236e3360@10.11.40.45:5060] Received command 'answer' from 158.58.154.15:50496
Jun 25 08:39:03 rtp2new rtpengine[17397]: [509847897b43e1d56e566ced236e3360@10.11.40.45:5060] Replying to 'answer' from 158.58.154.15:50496
Jun 25 08:39:07 rtp2new rtpengine[17397]: [509847897b43e1d56e566ced236e3360@10.11.40.45:5060 port 52710] Confirmed peer address as 10.11.40.45:17954
Jun 25 08:39:07 rtp2new rtpengine[17397]: [509847897b43e1d56e566ced236e3360@10.11.40.45:5060 port 52698] Confirmed peer address as 10.65.2.5:47684
Jun 25 08:39:07 rtp2new rtpengine[17397]: [509847897b43e1d56e566ced236e3360@10.11.40.45:5060 port 52698] Kernelizing media stream
Jun 25 08:39:07 rtp2new rtpengine[17397]: [509847897b43e1d56e566ced236e3360@10.11.40.45:5060 port 52710] Kernelizing media stream
Jun 25 08:39:07 rtp2new rtpengine[17397]: [509847897b43e1d56e566ced236e3360@10.11.40.45:5060 port 52699] Confirmed peer address as 10.65.2.5:47685
Jun 25 08:39:09 rtp2new rtpengine[17397]: [509847897b43e1d56e566ced236e3360@10.11.40.45:5060 port 52711] Confirmed peer address as 10.11.40.45:17955

I think it's triggered by this:
v=0 
o=S3-SBC-1 4013 1 IN IP4 10.65.2.4 
s=sip call 
c=IN IP4 10.65.2.5 
b=CT:1000 
t=0 0 
m=audio 47684 RTP/AVP 8 101 
a=label:Audio 
a=sendrecv 
a=rtpmap:8 PCMA/8000 
a=rtpmap:101 telephone-event/8000 
a=fmtp:101 0-16

**Comment by mtryfoss** [comment]
I wonder if this to be related to some subsequent "183 session progress" without sdp.

However, there should maybe be a different error message (or any at all)?

**Comment by rfuchs** [comment]
You need to do a packet capture on the RTP data to see what is causing this. It's unrelated to the signalling, but rather caused by some unknown packet arriving on the RTP ports. It could be ZRTP or various other unsupported protocols or simply a stray packet. Usually there's no reason for concern, but do a packet capture anyway if you want to know.

**Comment by mtryfoss** [comment]
Ok. I didn't know if this was related to signalling or the RTP itself. 

The calls seems to go through anyway. Most of these calls involve MS Lync, so there might be something strange there. I'll just close the ticket for now.
