### ISSUE TITLE
extmap sdp attributes are stripped

### ISSUE THREAD

**Issue by typetetris** [sipwise/rtpengine#1271]
We are using a setup where rtpengine + kamailio relays video between a browser (WebRTC) and a media server.

We noticed that the sdp extmap attributes are removed by rtpengine which leads to common rtp header extensions like abs-send-time not being negotiated and therefore not used.

We have seen, that they are stripped because of the changes of commit 4e89ac966.
Is that still necessary?

In our experiments chrome was doing video just fine after we reverted said commit.

**Comment by rfuchs** [comment]
The problem is that rtpengine itself does not understand these header extensions and so when rtpengine is producing RTP itself (e.g. when transcoding) there would be a mismatch between negotiated header extensions and extensions actually being used.
