### ISSUE TITLE
No way to specify order of transcoded codecs?

### ISSUE THREAD

**Issue by gedia** [sipwise/rtpengine#1275]
Hello,

I'm testing out 9.4.1.1 and I was wondering if there's a way to add a codec in an offer and additionally specify its placement in the priority list. So far I'm seeing the following.

- Original SDP includes "G722,PCMA,PCMU,G729,telephone-event/8000"
- Rtpengine is sent an offer request with the following codec options:

```
"codec": {
    "strip": [
      "all"
    ],
    "offer": [
      "AMR-WB",
      "PCMA",
      "G722",
      "PCMU",
      "G729"
    ],
    "transcode": [
      "AMR-WB/16000/1/23850//mode-set--0,1,2,3,4,5,6,7;octet-align--1"
    ]
  }
```
- Resulting SDP after rtpengine processing includes: "PCMA,G722,PCMU,G729,AMR-WB"

So codecs in the original SDP are reordered according to "offer" list, but the codec in the "transcode" list always appears to be set to last, regardless of its position in the "offer" list. Is this a limitation of current code or am I using the ng-protocol wrong? Thanks!

**Comment by rfuchs** [comment]
Yes that's a limitation of the current code base. The `transcode` list is processed after the `offer` list. As a workaround you can put codecs you want to `offer` also into the `transcode` list: If the codec was present in the original SDP, then that codec being listed in `transcode` will have the same effect as `offer` except for the ordering.

**Comment by gedia** [comment]
```
"codec": {
    "strip": [
      "all"
    ],
    "offer": [
      "AMR-WB/16000/1/23850//mode-set--0,1,2,3,4,5,6,7;octet-align--1",
      "G722",
      "PCMA",
      "PCMU",
      "G729",
      "telephone-event"
    ],
    "transcode": [
      "AMR-WB/16000/1/23850//mode-set--0,1,2,3,4,5,6,7;octet-align--1",
      "G722",
      "PCMA",
      "PCMU",
      "G729",
      "telephone-event"
    ]
  }
```

Thank you for the reply. You mean like this? It didn't seem to work for me. Here's the outcome of the above codec dict:
- Original SDP includes "G722,PCMA,PCMU,G729,telephone-event/8000":
```
m=audio 18930 RTP/AVP 9 8 0 18 101  
a=rtpmap:9 G722/8000                
a=rtpmap:8 PCMA/8000                
a=rtpmap:0 PCMU/8000                
a=rtpmap:18 G729/8000               
a=fmtp:18 annexb=no                 
a=rtpmap:101 telephone-event/8000   
a=fmtp:101 0-16                     
```
- Resulting SDP after rtpengine processing includes: "G722,PCMA,PCMU,G729,AMR-WB,telephone-event/8000,telephone-event/16000"
```
m=audio 20034 RTP/AVP 9 8 0 18 96 101 97
a=rtpmap:9 G722/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:96 AMR-WB/16000
a=fmtp:96 mode-set=0,1,2,3,4,5,6,7;octet-align=1
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=rtpmap:97 telephone-event/16000
a=fmtp:97 0-15
```
Changing the order for codecs originally present works, but I can't seem to place AMR-WB as first priority despite listing it as first in both offer and transcode...

**Comment by rfuchs** [comment]
No I mean put the codecs into `transcode` instead of `offer` - not both

**Comment by rfuchs** [comment]
Cleaning up old tickets
