### ISSUE TITLE
DTLS session key output into file

### ISSUE THREAD

**Issue by sergey-safarov** [sipwise/rtpengine#1281]
I want to implement on Kamailio server-side dumping of `session` encryption keys.
This will allow the embed key into PCAPNG file and a later simple open file in Wireshark. Merge operation may be completed using `editcap` utility.
[More info](https://blog.didierstevens.com/2021/01/11/decrypting-tls-streams-with-wireshark-part-3/).

Could you also add support if dumping DTLS session keys into a file, so it can be merged with raw PCAP using `editcap` utility.
*Example*
```
editcap --inject-secrets tls,dtls12-aes128ccm8.key dtls12-aes128ccm8.pcap dtls12-aes128ccm8-dsb.pcapng
```
This command will produce `dtls12-aes128ccm8-dsb.pcapng` file that have decrypted DTLS data.

Attached [dtls12-aes128ccm8.tar.gz](https://github.com/sipwise/rtpengine/files/6643654/dtls12-aes128ccm8.tar.gz) with raw pcap and session encryption keys.

P.S. maybe need some `logrotate` support on the `HUP` signal.

**Comment by rfuchs** [comment]
Does `editcap` support SRTP at all? SRTP encryption isn't really DTLS - DTLS is only used as handshake and to exchange SRTP keys. The encryption itself is not DTLS.

**Comment by sergey-safarov** [comment]
For SRTP I think need to use [`rtp_decoder`](https://www.zoiper.com/en/support/home/article/162/How%20to%20decode%20SIP%20over%20TLS%20with%20Wireshark%20and%20Decrypting%20SDES%20Protected%20SRTP%20Stream).
Decryption key needs to get from call signaling.
Call signaling may be decrypted by exporting the TLS session key on the `Kamailio` side.

Also relevant [srtp-decrypt](https://github.com/gteissier/srtp-decrypt).

**Comment by rfuchs** [comment]
Right, and the SRTP keys derived from the DTLS handshake are already being logged. So I'm not sure what you would want the DTLS session keys for.

**Comment by sergey-safarov** [comment]
From my point of view
1) SRTP - key passed via call signaling, RTPengine has access to these keys via SDP, but this case useless for editcap;
2) DTLS - key generated during DTLS handshake procedure. Only RTPeninge and client ahs access to sessions keys.

SRTP may be generated by a lot of SIP clients.
DTLS may be generated by WebRTC clients and clients like Linphone.

I requesting to save session keys in the format like in the attached file. So it may easily be used by editcap without placing RTPengine in debug mode and then manually parsing logs to get session keys.

May I missed this feature in RTPeninge. Will be glad if this feature already implemented.

**Comment by rfuchs** [comment]
> 1. SRTP - key passed via call signaling, RTPengine has access to these keys via SDP, but this case useless for editcap;

This is only true for SDES. For DTLS: SRTP keys are negotiated by DTLS.

> 2. DTLS - key generated during DTLS handshake procedure. Only RTPeninge and client ahs access to sessions keys.

True, but sessions keys are not relevant for SRTP. DTLS is only used to exchange SRTP keys, and these are already logged. Actual DTLS encryption is not used. Therefore I see no point in adding this feature.

**Comment by sergey-safarov** [comment]
Let me make a DTLS call using FreeSwitch and try to decrypt this using Wireshark.
I want to decrypt the call signaling and try to decrypt DTLS and SRTP (if possible by Wireshark).

**Comment by sergey-safarov** [comment]
Hi Richard @rfuchs
In attached file `tls-with-keys.pcapng` with two calls:
1) with DTLS;
2) without DTLS.

Wireshark is able to display TLS encrypted calls and RTP streams without the original certificate used by SIP server.
Wireshark is not able to decrypt audio.

As you pointed above, SRTP keys for the first call generated via DTLS protocol.
Let assume Wireshark is able to decrypt SRTP and able get encryption keys from call signaling.

How Wireshark will get SRTP encryption keys for first call (with DTLS) when I not able to provide `certificate private key` for third parties?.

[tls-pcap.tar.gz](https://github.com/sipwise/rtpengine/files/6669570/tls-pcap.tar.gz)

**Comment by rfuchs** [comment]
> As you pointed above, SRTP keys for the first call generated via DTLS protocol.
> Let assume Wireshark is able to decrypt SRTP and able get encryption keys from call signaling.

SRTP keys are NOT coming from the call signalling. They're extracted from the DTLS handshake (`use_srtp` extension)

> How Wireshark will get SRTP encryption keys for first call (with DTLS) when I not able to provide `certificate private key` for third parties?.

It would have to extract the keys out of the DTLS exchange captured. What would it need to do that? I have no idea. Is it the certificate (which one? both or just one?) or something else generated during the key exchange? Not a clue. Let me know when Wireshark (or something else) can actually do that. But for now, the SRTP keys that are generated from the DTLS handshake are directly included in the log output, which allows the SRTP to be decrypted directly without getting into DTLS.

**Comment by sergey-safarov** [comment]
Ok.
I will close the ticket until the SRTP decryption will work on Wireshark
