### ISSUE TITLE
No audio due to rtp timeout immediately after answer

### ISSUE THREAD

**Issue by sem32** [sipwise/rtpengine#1283]
Hi!

We have an issue with no media immediately after answer the call.

Before answer in function call_timer_iterator() we check:
current time - &ps->last_packet > 3600 (default value for offer_timeout)
after answer we  check
current time - &ps->last_packet > 60 (default value for timeout)

But, in case of the call_timer_iterator() starts after answer, but before we got first RTP from the client, we have timer actuation.

In the [LOG](https://github.com/sipwise/rtpengine/files/6663646/rtpengine_timeout.txt) you can see answer at Jun 10 13:17:57
```
Jun 10 13:17:57 host rtpengine[2359]: INFO: [143702129-3832316202-368417308]: Received command 'answer' from 127.0.0.1:64859
```
and closing the call at
```
Jun 10 13:17:58 host rtpengine[2359]: INFO: [143702129-3832316202-368417308]: Closing call due to timeout
```
One second for rtptimeout.

As idea to fix it: refresh &ps->last_packet in monologue_offer_answer()
```
diff --git a/daemon/call.c b/daemon/call.c
@@ -1901,6 +1925,19 @@ int monologue_offer_answer(struct call_monologue *other_ml, GQueue *streams,

        ml_media = other_ml_media = NULL;

+       {
+               if (flags && flags->opmode == OP_ANSWER) {
+                       GList *it;
+                       struct packet_stream *ps;
+                       for (it = call->streams.head; it; it = it->next) {
+                               ps = it->data;
+                               if (!ps)
+                                       continue;
+                               atomic64_set_na(&ps->last_packet, rtpe_now.tv_sec);
+                       }
+               }
+       }
+
        for (media_iter = streams->head; media_iter; media_iter = media_iter->next) {
                sp = media_iter->data;
                __C_DBG("processing media stream #%u", sp->index);
```                

Thank you.

**Comment by rfuchs** [comment]
This can probably be integrated into __fill_stream, see 017dbbd

**Comment by sem32** [comment]
Hi @rfuchs !

It works. Are you going to commit these changes to master?

Thank you
