### ISSUE TITLE
Codec information in the response dump

### ISSUE THREAD

**Issue by mkezys** [sipwise/rtpengine#1284]
Hello,

I am looking to get codec information in the Kamailio from the RTPEngine. 

In the RTPEngine log I can see:

    [core] ------ Media #1 (audio over RTP/AVP) using g729/8000
    [core] ------ Media #1 (audio over RTP/AVP) using PCMA/8000

In my understanding, g729/8000, PCMA/8000, etc could be returned in the 

    [control] Response dump for 'delete' ... "medias": [ { "index": 1, "type": "audio", "protocol": "RTP/AVP", "streams": [ { "local port": 10106, ...

Later it could be retrieved by https://kamailio.org/docs/modules/5.4.x/modules/rtpengine.html

If there is another way to get the codec information from the RTPEngine to Kamailio, please let me know.

If no - I would like to sponsor the development of this functionality. Please let me know how to proceed.

Thank you.

**Comment by mkezys** [comment]
We patched rtpengine & kamailio rtpengine module to support this functionality. If anybody needs it, could be found there:

https://github.com/kolmisoft-company/kamailio/commits/5.4
https://github.com/kolmisoft-company/rtpengine

This issue can be closed.

**Comment by rfuchs** [comment]
Open a pull request to have it included in the mainline code base
