### ISSUE TITLE
cli not building?

### ISSUE THREAD

**Issue by etamme** [sipwise/rtpengine#129]
I just noticed that the CLI is not building an executable, and if i do "make cli" it errors out.  This is on master as well as mr3.8.2.

Am I missing some thing here or is it broken?

**Comment by rfuchs** [comment]
Which CLI are you referring to? There's `ng-client` and `rtpengine-ctl` (both from `utils/`) which are standalone scripts and don't require compilation.

**Comment by etamme** [comment]
is this not a command line interface ?

https://github.com/sipwise/rtpengine/blob/master/daemon/cli.c

**Comment by rfuchs** [comment]
Well, yes, but this file is part of the rtpengine daemon. You would control it from the command line using `rtpengine-ctl`

**Comment by etamme** [comment]
gotcha - i  had a feeling that I was just missing some thing.  Thanks for clarifying.
