### ISSUE TITLE
compilation errors on the current version

### ISSUE THREAD

**Issue by maalinux** [sipwise/rtpengine#1291]
Hi, I'm trying to compile the current version cloned from the master branch with the following details:
```
commit 1d845c2103843d742209b8abcb4f203cb2dc3066
Author: Richard Fuchs <rfuchs@sipwise.com>
Date:   Mon Jun 21 08:46:01 2021 -0400
    TT#111150 add top-level make target for asan test

    This is a convenient shortcut to also run these tests locally.

    Change-Id: Ifb1355319b7eebd708acddea6e0fc7fa2c7dcdfb
```
The library libwebsockets is missing in daemon, causing compilation errors on centos 7 (7.9.2009):
also the function dtmf_rx_fillin seems not to be defined causing an error of such:
```
/usr/local/src/rtpengine/daemon/dtmf_rx_fillin-test.c:4: undefined reference to `dtmf_rx_fillin'
collect2: error: ld returned 1 exit status
make[2]: *** [dtmf_rx_fillin-test] Error 1
```
Please notice that i was able to compile and successfully install rtpengine on the same server using an older version which I am not sure of its number with the following details:
```
commit 995375f500e6450cfc5a938178bc8db72d996b6e
Author: Doug Rylaarsdam <drylaarsdam@verascape.com>
Date:   Thu Sep 10 22:22:59 2020 +0000

    Add support for metadata in stop_recording.
    (Issue #1075 on sipwise/rtpengine)
```
Can you tell me which version that was in order to mention it in the git clone, and i hope there would be a fix to the current one.

**Comment by rfuchs** [comment]
What do you mean with "The library libwebsockets is missing in daemon" ?

You need to install this library on your system. It's not included with rtpengine.

**Comment by maalinux** [comment]
When I install the rtpengine using the version of "Sep 10.2020", I don't have to manually install the libwebsockets.
Only on the latest version it requires that I do, but I am also getting the other issue of the function.

**Comment by rfuchs** [comment]
The libwebsockets requirement was added relatively recently.

The other error you see is a build test, not an actual error. You can ignore it.

**Comment by maalinux** [comment]
I've compiled and installed the libwebsockets, but I am getting this error now while making in /daemon:
```
media_player.o: In function `__media_player_free':
/usr/local/src/rtpengine/daemon/media_player.c:101: undefined reference to `av_packet_free'
media_player.o: In function `media_player_new':
/usr/local/src/rtpengine/daemon/media_player.c:128: undefined reference to `av_packet_alloc'
codeclib.o: In function `avc_decoder_init':
/usr/local/src/rtpengine/daemon/codeclib.c:594: undefined reference to `av_packet_alloc'
codeclib.o: In function `avc_decoder_close':
/usr/local/src/rtpengine/daemon/codeclib.c:726: undefined reference to `av_packet_free'
codeclib.o: In function `encoder_config_fmtp':
/usr/local/src/rtpengine/daemon/codeclib.c:1316: undefined reference to `av_packet_alloc'
codeclib.o: In function `encoder_free':
/usr/local/src/rtpengine/daemon/codeclib.c:1375: undefined reference to `av_packet_free'
collect2: error: ld returned 1 exit status
make[1]: *** [rtpengine] Error 1
rm sdp.strhash.c control_ng.strhash.c call_interfaces.strhash.c
make[1]: Leaving directory `/usr/local/src/rtpengine/daemon'
make: *** [all] Error 2
```

**Comment by rfuchs** [comment]
Install ffmpeg libraries or compile without transcoding support

**Comment by maalinux** [comment]
I really appreciate your prompt response and help!
The ffmpeg packages (ffmpeg ffmpeg-devel) are already installed and latest versions.

**Comment by rfuchs** [comment]
> The ffmpeg packages (ffmpeg ffmpeg-devel) are already installed and latest versions.

I don't believe you, because the linker would find them if they were there :)

The .spec file lists `ffmpeg-libs` so how about that one?

**Comment by maalinux** [comment]
```
yum -y install ffmpeg ffmpeg-devel
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: rep-centos-il.upress.io
 * epel: rep-epel-il.upress.io
 * extras: rep-centos-il.upress.io
 * nux-dextop: mirror.li.nux.ro
 * updates: rep-centos-il.upress.io
Package ffmpeg-2.8.15-2.el7.nux.x86_64 already installed and latest version
Package ffmpeg-devel-2.8.15-2.el7.nux.x86_64 already installed and latest version
Nothing to do
[root@vcc-kam-test-2 daemon]# yum install ffmpeg-libs
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.isoc.org.il
 * epel: rep-epel-il.upress.io
 * extras: mirror.isoc.org.il
 * nux-dextop: mirror.li.nux.ro
 * updates: mirror.isoc.org.il
Package ffmpeg-libs-2.8.15-2.el7.nux.x86_64 already installed and latest version
Nothing to do

```

**Comment by rfuchs** [comment]
That's a very old version of ffmpeg. Maybe it doesn't support these functions. You should be able to find backports of a newer version. I have 3.4.8-1.el7 installed here on my VM.

**Comment by maalinux** [comment]
Those versions are the ones supplied by epel.
I've added fusion repo and was able to update to 3.4.8-1.el7 which solved the issue.
Thank you!
