### ISSUE TITLE
Segfault rtcp_xr at /usr/include/x86_64-linux-gnu/bits/byteswap.h

### ISSUE THREAD

**Issue by thomas414** [sipwise/rtpengine#1296]
Hi,

yesterday we got a segfault error on one of our rtpengine machines, backtrace is attached.
rtpengine version is: 9.5.1.0+0~mr9.5.1.0 git-mr9.5-451e11a6

Unfortunately i could not yet find a call that could have caused this error, maybe if you can tell me for what exactly i should look out.
[gdb.txt](https://github.com/sipwise/rtpengine/files/6731542/gdb.txt)

**Comment by rfuchs** [comment]
In gdb can you post the output of:
```
frame 1
p *el
p *hdr
```

**Comment by thomas414** [comment]
Hi, this is the output:

`(gdb) frame 1
#1  0x0000564ebd6d70d1 in rtcp_parse (q=q@entry=0x7f427959e5a0, mp=mp@entry=0x7f427959e6a8) at rtcp.c:711
711     rtcp.c: Datei oder Verzeichnis nicht gefunden.
(gdb) p *el
$1 = {type = 207, len = 4, u = {buf = 0x7f427959e814, rtcp_packet = 0x7f427959e814, sr = 0x7f427959e814, rr = 0x7f427959e814, sdes = 0x7f427959e814, bye = 0x7f427959e814, app = 0x7f427959e814,
    xr = 0x7f427959e814}}
(gdb) p *hdr
$2 = {count = 19, p = 0, version = 2, pt = 207 '\317', length = 0}
`

Hope its okay if i just post this directly
