### ISSUE TITLE
MOS calculation

### ISSUE THREAD

**Issue by Den4t** [sipwise/rtpengine#1297]
Hello !

I have a short question, are MOS values calculated only in RTCP RR blocks ?

**Comment by rfuchs** [comment]
Yes, but this includes self-generated RR if RTCP generation is enabled. With the newest version from master you can configure `mos=LQ` which would then report MOS even if no RTCP is received at all (with the default `mos=CQ` bidirectional RTCP is required).

**Comment by Den4t** [comment]
Good news, Thanks !
