### ISSUE TITLE
RTCP RR not passing through

### ISSUE THREAD

**Issue by jonastelzio** [sipwise/rtpengine#1298]
Hey there!

Firstly, I apologize if I'm getting the terminology wrong here.

After switching from an RTP Engine running release 9.4.1.1 to the header of master (needed an update there to get websockets working), I'm no longer seeing the `remote-inbound-rtp` WebRTC stats report being generated. This is something I've always assumed RTP Engine is generating (RTCP Receiver Report (RR)).

I'm unsure where I'd go debug this issue, so any feedback is appreciated!

**Comment by rfuchs** [comment]
RTCP has always only been passthrough by default. You can optionally enable local RTCP generation by using the flag `generate-RTCP`

**Comment by jonastelzio** [comment]
@rfuchs I just rolled back to 9.4, and I'm getting the Receiver Reports now. Is it possible that something between 9.4 and master is preventing these from passing through?

**Comment by rfuchs** [comment]
Not to my knowledge, but post a pcap and a full debug log and I can look into it.

**Comment by jonastelzio** [comment]
I've got both a debug log and a pcap (though it seems to be fully encrypted so not sure how good it's going to be).

I'm seeing these statements repeated in it:

`[1625131092.141923] DEBUG: [35443dd5-c6a7-45a7-8508-0cf5998e0b91 port 30000]: [core] No payload type known for RTCP RR, discarding`

[rtpengine-log.zip](https://github.com/sipwise/rtpengine/files/6747025/rtpengine-log.zip)

**Comment by rfuchs** [comment]
Also share which commit exactly you were on, as there's a lot of changes going on in master right now

**Comment by rfuchs** [comment]
Looks like the RRs are passing through, but the SSRC substitution when transcoding isn't being done. Thanks for reporting.

**Comment by jonastelzio** [comment]
@rfuchs thanks for the swift fix! I can confirm that `rfuchs/1298` passes RTCP RR across!
