### ISSUE TITLE
No audio of FF39

### ISSUE THREAD

**Issue by caruizdiaz** [sipwise/rtpengine#130]
Yesterday Mozilla shipped a new version of FF, and it's not working with rtpengine. This is being outputted.

<pre>
Jul  8 16:12:50 localhost rtpengine[31253]: [ggueebkf31m05bbmj2io port 30013] DTLS error: 1 (no shared cipher)
Jul  8 16:12:50 localhost rtpengine[31253]: [ggueebkf31m05bbmj2io port 30013] DTLS error on local port 30013
Jul  8 16:12:50 localhost rtpengine[31253]: [ggueebkf31m05bbmj2io port 30012] DTLS error: 1 (no shared cipher)
Jul  8 16:12:50 localhost rtpengine[31253]: [ggueebkf31m05bbmj2io port 30012] DTLS error on local port 30012
Jul  8 16:12:50 localhost rtpengine[31253]: [ggueebkf31m05bbmj2io port 30013] ICE negotiated: peer for component 1 is 189.217.251.147:36039
Jul  8 16:12:50 localhost rtpengine[31253]: [ggueebkf31m05bbmj2io port 30013] ICE negotiated: peer for component 2 is 189.217.251.147:36039
Jul  8 16:12:51 localhost rtpengine[31253]: [ggueebkf31m05bbmj2io port 30013] Error parsing RTCP header: invalid header version
Jul  8 16:12:51 localhost rtpengine[31253]: [ggueebkf31m05bbmj2io port 30012] Error parsing RTP header: invalid header version
Jul  8 16:12:54 localhost rtpengine[31253]: [ggueebkf31m05bbmj2io port 30000] Confirmed peer address as 189.217.251.147:28050
Jul  8 16:12:55 localhost rtpengine[31253]: [ggueebkf31m05bbmj2io port 30001] Confirmed peer address as 189.217.251.147:57275
Jul  8 16:12:57 localhost rtpengine[31253]: [ggueebkf31m05bbmj2io port 30013] Confirmed peer address as 189.217.251.147:36039
Jul  8 16:12:57 localhost rtpengine[31253]: [ggueebkf31m05bbmj2io port 30012] Confirmed peer address as 189.217.251.147:36039
Jul  8 16:13:04 localhost rtpengine[31253]: [ggueebkf31m05bbmj2io port 30001] SRTCP output wanted, but no crypto suite was negotiated
Jul  8 16:13:05 localhost rtpengine[31253]: [ggueebkf31m05bbmj2io port 30000] SRTP output wanted, but no crypto suite was negotiated
Jul  8 16:13:19 localhost rtpengine[31253]: [ggueebkf31m05bbmj2io port 30001] SRTCP output wanted, but no crypto suite was negotiated
Jul  8 16:13:20 localhost rtpengine[31253]: [ggueebkf31m05bbmj2io port 30000] SRTP output wanted, but no crypto suite was negotiated
Jul  8 16:13:21 localhost rtpengine[31253]: [ggueebkf31m05bbmj2io port 30013] Error parsing RTCP header: invalid header version
Jul  8 16:13:21 localhost rtpengine[31253]: [ggueebkf31m05bbmj2io port 30012] Error parsing RTP header: invalid header version
</pre>

**Comment by rfuchs** [comment]
"no shared cipher" is interesting. Any idea which ciphers FF now supports and which it doesn't support any more?

**Comment by caruizdiaz** [comment]
FF39 offer

![FF39 cipher suites](https://d1zjcuqflbd5k.cloudfront.net/files/acc_393172/XonC?response-content-disposition=inline;%20filename=Screen%20Shot%202015-07-08%20at%2011.31.10.png&Expires=1436373224&Signature=e3QCxxOd8hVUXJp5AnFH2N0gY~uflVYFLDrqhDybqjS5Pa2Y199HvbSZnLQgR4L89Hbl~8ZsDQ0LmoNPodOFCKUTIHvREzltCIro5Ixxor2H4o7pzvp3hbEEn7lmRUBTM-At3xWDKDk1aMLotMXrqWaCswTUB2kclMzhGRwl6Nc_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)

Chrome 43 offer

![Chrome 43 cipher suites](
https://d1zjcuqflbd5k.cloudfront.net/files/acc_393172/G8Qx?response-content-disposition=inline;%20filename=Screen%20Shot%202015-07-08%20at%2011.33.31.png&Expires=1436373293&Signature=XkK~VzPypbARAlTspOfk~HqPsP1rNohwdg2AYyrJuA9Wq1cxPv4ZHW1X-ywMTBCYu7TyZ6ivqGx69Aa4dVOpx1wTV7AlzjcyTPMa4vqxLZnIvirsX8FZClnZu1GmvNroWNtr7EfQN3IauR-cs5tvX7BbrX-XzvHVKRktjiSASvg_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)

**Comment by caruizdiaz** [comment]
I also tried updating openssl to the latest available on the RPM repo, the recompiled rtpengine. The server I'm using is a Fedora 19.

**Comment by rfuchs** [comment]
Those links don't work. And JFTR, the DTLS cipher list can't be seen in SIP/SDP, it's set through OpenSSL callbacks (e.g. daemon/dtls.c:503)

**Comment by caruizdiaz** [comment]
I updated the links (in my prev comment) of the disaggregated list of cipher suites offered by FF and Chrome

**Comment by rfuchs** [comment]
The cipher list seems to be identical in all software packages, but perhaps supporting elliptic curve DH is a solution. Can you please try with 21e1fb6 applied.

**Comment by caruizdiaz** [comment]
Maybe some further tests may be required, but it's working on both FF39 and Chrome43. 

Thank you!

**Comment by rfuchs** [comment]
You mean with this patch applied?

**Comment by caruizdiaz** [comment]
I applied the patch and ran a 3 mins test call on both browsers, and it worked.
