### ISSUE TITLE
rtpengine and forking streams for siprec

### ISSUE THREAD

**Issue by johandeclercqdemocon** [sipwise/rtpengine#1301]
Richard, 
this is more a question then a bug. 
Is htere a specific reason why rtpengine can't fork a media stream for siprec ? 

The reason that I have clients asking for siprec. But apparently that works only with rtpproxy as rtpengine can't fork streams. 
Can you please comment ?

**Comment by rfuchs** [comment]
> Is htere a specific reason why rtpengine can't fork a media stream for siprec ?

Yes, the reason being that this hasn't been implemented :smile: 

Support for media forking is coming shortly, and in a very much siprec-like fashion. In fact a good chunk of this feature set has already been merged to master in the last few weeks. Therefore closing this.

**Comment by mikhail-barg** [comment]
Thanks!

**Comment by leasual** [comment]
> See https://github.com/sipwise/rtpengine#subscribe-request-message and below
> 
> Full support for SIPREC-style sessions is coming shortly.

Hi Richard, could you share some demo code to explain how to work? Thanks.
