### ISSUE TITLE
Forwarded packet to wrong IP

### ISSUE THREAD

**Issue by sergey-safarov** [sipwise/rtpengine#1305]
I found that RTPengine by mistake try forward packets to IPv6 address instead of using IPv4 as it mandated in SDP.

Example in attached PCAP present call with `Call-ID: T1vz2FnUMC`.
Here RTPengine receives an SDP connection address `c=IN IP4 100.86.42.119` and candidates for `text` media
```
a=candidate:6453068426 1 udp 659136 100.86.42.119 26260 typ host generation 0
a=candidate:6453068426 2 udp 659135 100.86.42.119 26261 typ host generation 0
```

But according to logs try to deliver packets to
```
Jul 10 15:34:36 rtp-us-east-1a-6.nga911.com rtpengine[9608]: DEBUG: [T1vz2FnUMC port 18270]: [internals] Handling packet on: 178.176.72.39:62830
Jul 10 15:34:36 rtp-us-east-1a-6.nga911.com rtpengine[9608]: DEBUG: [T1vz2FnUMC port 18260]: [core] Forward to sink endpoint: 2600:1f18:578:5702::f6:26260 (RTP seq 4 TS 2638328436)
```
And as a result, packets are forwarded to `38.0.31.24` instead of the expected `100.86.42.119` (Wireshark filter `ip.addr==38.0.31.24 and udp.port==26260`).

Also similar behavior for `audio` media in `Call-ID: 0d0776c3-b9a2-429a-9f0a-c2ea5cca3128`.
RTPengine try send audio stream to host `38.0.31.24` port 26386 (Wireshark filter `ip.addr==38.0.31.24 and udp.port==26386`). 

On server compiled 82c741d88c70e9460ae6335698e37f1184c97868

[rtpengine.log](https://github.com/sipwise/rtpengine/files/6795632/rtpengine.log)
[calls.pcapng.gz](https://github.com/sipwise/rtpengine/files/6795633/calls.pcapng.gz)

**Comment by rfuchs** [comment]
Probably because you're using `SIP-source-address` and that's an IPv6 address...

**Comment by sergey-safarov** [comment]
in my config used construction like from [reference Kamailio config](https://github.com/kamailio/kamailio/blob/master/etc/kamailio.cfg#L853-L857).
```
	if(nat_uac_test("8")) {
		rtpengine_manage("SIP-source-address replace-origin replace-session-connection");
	} else {
		rtpengine_manage("replace-origin replace-session-connection");
	}
```
I will try modify this example to cover case when call signaling goes via IPv6 and media via IPv4.

May be need generate waring when we try stream media via IPv4 and call signaling IPv6?
And in other case when stream via IPv6 and call signaling via IPv4.

Should `SIP-source-address` be ignored in this case?

**Comment by rfuchs** [comment]
So that would be a88708c57bd303450c6bef330f1af257d87de803

Untested

**Comment by sergey-safarov** [comment]
I will test and provide feedback

**Comment by rfuchs** [comment]
I've updated the commit slightly with another safeguard against filling the peer address with an address of the wrong family, commit now 7a5e8ca

**Comment by rfuchs** [comment]
Any feedback here?

**Comment by sergey-safarov** [comment]
HI Richard.
Yes, I tested but was not able to provide feedback.
Response from IPv6 device with GNAT IPv4 address now ignored.
I will get logs today.

**Comment by sergey-safarov** [comment]
Hi Richard
Sorry for the delay.
Here are the test logs.
1. [rtpengine.log](https://github.com/sipwise/rtpengine/files/6874513/rtpengine.log)
2. server network traffic [sip.pcap.gz](https://github.com/sipwise/rtpengine/files/6874517/sip.pcap.gz)

From log, I can see
```
[1626358070.005838] WARNING: [1099255580]: [core] Failed to extract streams from SDP: No address info found for stream
[1626358070.005849] WARNING: [1099255580]: [control] Protocol error in packet from [::1]:47564: Incomplete SDP specification 
```

**Comment by sergey-safarov** [comment]
If IP addresses type mismatch is present (call signaling IP address and SDP IP address), then `SIP-source-address` cannot be used.

P.S. Just only my view.

**Comment by rfuchs** [comment]
> If IP addresses type mismatch is present (call signaling IP address and SDP IP address), then `SIP-source-address` cannot be used.
> 
> P.S. Just only my view.

Yes, that is/was the plan. The patch just didn't work :)

Updated to e0e672a (and now tested it myself)

**Comment by sergey-safarov** [comment]
tested on my test box.
Works as expected.
One more test with RTT text (1-2 days) and then can be merged.

**Comment by sergey-safarov** [comment]
I have made RTT media traversal test via RTPengine.
Now looks all fine.
I think the commit may be merged.
