### ISSUE TITLE
Restoring calls from Redis does not work starting from mr9.5

### ISSUE THREAD

**Issue by agrigorjevs** [sipwise/rtpengine#1308]
Hello,

Call restoring from Redis via keyspace notifications is not working on 9.5+ versions of rtpengine.

In my specific scenario it runs in docker and the passive node fails to create the call with the following errors.

Jul 14 11:52:13  docker[5786]: [1626263533.486967] NOTICE: [core] Creating new call
Jul 14 11:52:14  docker[5786]: [1626263534.822587] WARNING: [core] Failed to restore call ID '-mt_mmJOCAnUv3K4bmsRJg..' from Redis:
Jul 14 11:52:14 docker[5786]: [1626263534.823043] NOTICE: [core] Redis-Notifier: DEL did not find call with callid: __keyspace@1__

So the failover never works, although it works vice-versa - from 2nd node to 1st node - the same errors, though, are received.

Switching the version from mr9.5 to mr9.4 fixes the issue with identical config.

**Comment by rfuchs** [comment]
Is that with both nodes updated to 9.5 or just one of them?

Post your config and set log level to 7 and post a full log.

**Comment by agrigorjevs** [comment]
That is with both nodes updated to 9.5

Please see the configs and logs here
https://pastebin.com/UMqar1cq

**Comment by rfuchs** [comment]
I pushed a few commits to https://github.com/sipwise/rtpengine/compare/rfuchs/1308-mr9.5 in particular 0c6c6bc which should fix this. Those are on top of the m9.5 branch. See if that works.

**Comment by agrigorjevs** [comment]
@rfuchs ok, will try out, thanks.

JFYI Actually, when I tried the same thing previously on master branch, not mr9.5, rtpengine on slave instance was crashing when trying to restore the call.
