### ISSUE TITLE
debian/rules build gave error exit status 2

### ISSUE THREAD

**Issue by Kauef** [sipwise/rtpengine#1309]
Im trying to install rtpengine in Debian 9 but i cant seem to get through.

i used dpkg-checkbuilddeps to make sure that there are all the dependencies that i need. 
and then dpkg-buildpackage  to build them. 

but i got this at the end:

test "$(ls fake-daemon-tests-main-sockets)" = ""
rmdir fake-daemon-tests-main-sockets
make[4]: Leaving directory '/usr/src/rtpengine/t'
Makefile:111: recipe for target 'daemon-tests' failed
make[3]: * [daemon-tests] Error 2
rm sdp.strhash.c control_ng.strhash.c test-const_str_hash.strhash.c call_interfaces.strhash.c
make[3]: Leaving directory '/usr/src/rtpengine/t'
../lib/common.Makefile:4: recipe for target 'all' failed
make[2]: * [all] Error 2
make[2]: Leaving directory '/usr/src/rtpengine/t'
Makefile:54: recipe for target 'check' failed
make[1]: * [check] Error 2
make[1]: Leaving directory '/usr/src/rtpengine'
dh_auto_test: make -j4 check returned exit code 2
debian/rules:35: recipe for target 'build' failed
make: * [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

Any clue  of what can i look for?

**Comment by rfuchs** [comment]
One of the tests is failing. You need to look further up to see the actual error.

**Comment by Kauef** [comment]
This is the error that appears

  Failed test 'received packet matches'
#   at ../perl/NGCP/Rtpengine/AutoTest.pm line 190.
#                   '▒  ▒▒▒Ud▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒Ԝ4▒!▒ ▒▒(▒▒:▒▒"'
#     doesn't match '(?^s:^\▒\  \\▒\\\\▒\▒Ud\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\▒\,\▒\"\▒\ \\▒\%\\<\▒\▒\▒\▒\▒$)'
rtp recv 224 4002 8320 735852179 0b0a00a0
ok 653 - received packet matches
rtp in 8 4003 8480 25923
rtp recv 96 4003 8320 735852179 0b0a0140
ok 654 - received packet matches
rtp in 8 4004 8640 25923
rtp recv 96 4004 8320 735852179 0b0a01e0
ok 655 - received packet matches
rtp in 8 4005 8800 25923
rtp recv 96 4005 8320 735852179 0b0a0280
ok 656 - received packet matches
rtp in 8 4006 8960 25923
rtp recv 96 4006 8320 735852179 0b0a0320
ok 657 - received packet matches
rtp in 8 4007 9120 25923
rtp recv 96 4007 8320 735852179 0b8a03c0
ok 658 - received packet matches
rtp recv 96 4008 8320 735852179 0b8a03c0
ok 659 - received packet matches
rtp recv 96 4009 8320 735852179 0b8a03c0
rtp recv 9 2003 4480 3528811756 bc0ff11baf8899262998862ff934b45d6acb2f8b2cac3aaf0dee884c64e5338b72c94ae624ab0ffdcdcbda20a3466d8b0969e6e9ddd8c61ebb29b12cb7c42ed855eaf2df4b29ed8937ec778e32f8cfecdbda386f728f5ff95f689b79d5515a2a6694d37f8d3d69f16ddf8a4d356db66ff91d90d172947b2d79901f678a5625ffd17ef5903ff7776ad88d3bf8dc6d7597cc37fd2cb5d76cd5ce55de2e716fba58
800907d300001180d25564ecbc0ff11baf8899262998862ff934b45d6acb2f8b2cac3aaf0dee884c64e5338b72c94ae624ab0ffdcdcbda20a3466d8b0969e6e9ddd8c61ebb29b12cb7c42ed855eaf2df4b29ed8937ec778e32f8cfecdbda386f728f5ff95f689b79d5515a2a6694d37f8d3d69f16ddf8a4d356db66ff91d90d172947b2d79901f678a5625ffd17ef5903ff7776ad88d3bf8dc6d7597cc37fd2cb5d76cd5ce55de2e716fba58
not ok 45 - received packet matches
#   Failed test 'received packet matches'
#   at ../perl/NGCP/Rtpengine/AutoTest.pm line 190.
▒Ld▒3▒r▒J▒$▒▒▒▒▒ ▒Fm▒▒  i▒▒▒▒▒▒)▒,▒▒.▒U▒▒▒K)▒7▒w▒2▒▒▒▒▒8or▒_▒_h▒y▒QZ*f▒▒=i▒mߊM5m▒o▒▒▒r▒{-y▒g▒V%▒▒~▒?▒wj؍;▒▒mu▒▒7▒,▒▒l▒▒U▒.qo▒X'
#     doesn't match '(?^s:^\▒\  \\▒\\\\▒\▒Ud\▒\▒\▒\?\/\S\▒\▒7\\▒\▒Z\.\▒\▒\▒X6\▒f\▒7\▒6\{\▒smz\|\▒7\▒\▒\▒\.\▒3\▒\\▒v\$\▒V\:\▒\▒\'\▒x\{\▒\▒\?\▒\&\▒\*\▒\▒\/\▒\▒o\▒\▒\▒\/y\▒\,\▒\{\▒5\▒\]q\▒\▒\|\}7\▒w\▒q0\▒\▒\▒\▒\▒\'0\▒\▒\]\▒6\▒vx_\▒\▒vq\▒r\▒\>\▒\▒t\▒\▒q\▒\▒8\/\▒\▒\*\▒\▒\▒t\▒5\▒q4\▒\▒s\▒\|sw\▒\▒p\▒\.\▒4\▒\▒\▒\▒pt\-\▒\\$)'
rtp in 0 2003 4800 22136
ok 660 - received packet matches
rtp in 8 4008 9280 25923
rtp recv 9 2004 4640 3528811756 d150d62faf8e5e312bfaf6dcced6d2299f3867978d5cfbcc2e6a96d47f756c96ce2effd2d42ff97dea8f3773fc9ed9d9376c9f6dd84f31fed62e985cd12f9d576890dcd0326f91de7675907c67936f9c8c71fc74ed6c983fface75d2782a9e8c337d7af09371db8c75eedad4533379fc945d2999dd6ceef38f3ed350322cf176f8788f3d6fd96cbe6b933fda58d91d257cd755d01d7859775d7f595c5a5c5b5f
800907d400001220d25564ecd150d62faf8e5e312bfaf6dcced6d2299f3867978d5cfbcc2e6a96d47f756c96ce2effd2d42ff97dea8f3773fc9ed9d9376c9f6dd84f31fed62e985cd12f9d576890dcd0326f91de7675907c67936f9c8c71fc74ed6c983fface75d2782a9e8c337d7af09371db8c75eedad4533379fc945d2999dd6ceef38f3ed350322cf176f8788f3d6fd96cbe6b933fda58d91d257cd755d01d7859775d7f595c5a5c5b5f
not ok 46 - received packet matches
#   Failed test 'received packet matches'
#   at ../perl/NGCP/Rtpengine/AutoTest.pm line 190.
#                   '▒  ▒ ▒Ud▒▒P▒/▒▒^1+▒▒▒▒▒▒)▒8g▒▒\▒▒.j▒ul▒▒.▒▒▒/▒}▒7s▒▒▒7l▒m▒O1▒▒.▒\▒/▒Wh▒▒▒2o▒▒vu▒|g▒o▒▒q▒t▒l▒?▒▒u▒x*▒▒3}z▒qیu▒▒▒S3y▒])▒▒l▒▒>▒P2,▒v▒x▒=o▒l▒k▒?▒X▒%|▒U▒xYwY\Z\[_'
#     doesn't match '(?^s:^\▒\  \\▒\\\\ \▒Ud\▒\▒\▒\▒\+\▒\▒\▒r3\]6\▒\▒\▒\▒\)\▒r4\▒\▒t\▒\▒nq\▒\▒\▒v0\▒\▒p\▒\▒\▒\,\▒t2\▒t6y\▒\▒\▒2r\]2\▒\▒4\▒\▒\-\▒x\▒\*\▒yp\▒\▒\▒ou\▒\▒xx\▒t\,\▒1\▒\▒0\▒su\.\▒7\▒\▒\{\▒y\,\▒\▒p\▒4v\▒t\▒\▒rs\▒\▒\▒ty\▒\▒\▒\,\▒\.17\▒z\▒\▒s\+z7\\8\▒7u\|1\~\,\▒y\▒z\▒u\+v\▒\▒\▒y\▒\▒\▒\▒\▒\▒\▒\▒\[\\\▒$)'
ok 47 - G.722 DTX - 'delete' status
new call 12-test-callID-0.150404823312687
ok 48 - G.722 reverse DTX - 'offer' status
ok 49 - G.722 reverse DTX - output 'offer' SDP
ok 50 - G.722 reverse DTX - 'answer' status
ok 51 - G.722 reverse DTX - output 'answer' SDP


### Looks like you failed 3 tests of 59.


Makefile:141: recipe for target 'daemon-tests-dtx-cn' failed
make[4]: *** [daemon-tests-dtx-cn] Error 3
rtp recv 0 4006 8960 841096064 0e0c1db89da2bef9b4a0a33f140c14bd8e89934915121fe7b5d93c7ca19397d513090e45938b93c4201d2e6b46261f3d9d8d8eae17090d2c9c9098ba363dc7c42e1713279e8b8b9f1e0c0e25aa9ca5c8e8aea0aa2d100c1ba68c8a9a2c121327c3b3ed3ec89d939b380f0913ba8f8b984a1d1e34f93e2423ea988c92df10090f4d97909cd2313fc5d628161639978a8daf170b1032a29ba8d6d9aca1b3220e0e
make[4]: *** Waiting for unfinished jobs....
ok 688 - received packet matches
rtp in 0 4007 9120 25923




est "$(ls fake-daemon-tests-main-sockets)" = ""
rmdir fake-daemon-tests-main-sockets
make[4]: Leaving directory '/usr/src/rtpengine/t'
Makefile:111: recipe for target 'daemon-tests' failed
make[3]: *** [daemon-tests] Error 2
rm sdp.strhash.c control_ng.strhash.c test-const_str_hash.strhash.c call_interfaces.strhash.c
make[3]: Leaving directory '/usr/src/rtpengine/t'
../lib/common.Makefile:4: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/usr/src/rtpengine/t'
Makefile:54: recipe for target 'check' failed
make[1]: *** [check] Error 2
make[1]: Leaving directory '/usr/src/rtpengine'
dh_auto_test: make -j4 check returned exit code 2
debian/rules:35: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by Kauef** [comment]
I saw an old thread with a case that looks like this one https://github.com/sipwise/rtpengine/issues/950 but then im using a virtual machine in openstack.

Here is the  output: https://controlc.com/034f3a02

**Comment by rfuchs** [comment]
Post the output of `dpkg -l libav*` please

**Comment by Kauef** [comment]
![image](https://user-images.githubusercontent.com/87502921/125873012-abb1458d-84df-4b57-a9f6-bf974ab83b72.png)
 | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                 Version                 Architecture            Description
+++-====================================-=======================-=======================-=============================================================================
ii  libavcodec-dev:amd64                 7:3.2.15-0+deb9u2       amd64                   FFmpeg library with de/encoders for audio/video codecs - development files
un  libavcodec-extra57                   <none>                  <none>                  (no description available)
ii  libavcodec57:amd64                   7:3.2.15-0+deb9u2       amd64                   FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavfilter-dev:amd64                7:3.2.15-0+deb9u2       amd64                   FFmpeg library containing media filters - development files
un  libavfilter-extra6                   <none>                  <none>                  (no description available)
ii  libavfilter6:amd64                   7:3.2.15-0+deb9u2       amd64                   FFmpeg library containing media filters - runtime files
ii  libavformat-dev:amd64                7:3.2.15-0+deb9u2       amd64                   FFmpeg library with (de)muxers for multimedia containers - development files
ii  libavformat57:amd64                  7:3.2.15-0+deb9u2       amd64                   FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample-dev:amd64              7:3.2.15-0+deb9u2       amd64                   FFmpeg compatibility library for resampling - development files
ii  libavresample3:amd64                 7:3.2.15-0+deb9u2       amd64                   FFmpeg compatibility library for resampling - runtime files
ii  libavutil-dev:amd64                  7:3.2.15-0+deb9u2       amd64                   FFmpeg library with functions for simplifying programming - development files
ii  libavutil55:amd64                    7:3.2.15-0+deb9u2       amd64                   FFmpeg library with functions for simplifying programming - runtime files

**Comment by Kauef** [comment]
![image](https://user-images.githubusercontent.com/87502921/125878303-cdc527eb-eda3-4483-be6b-0fa6dd5b1850.png)

**Comment by rfuchs** [comment]
Looks like it's a matter of the DTX tests being unstable, and for some reason only(?) on jessie. I'm guessing it's because they're timing sensitive but don't really have an explanation beyond that. It's probably best to disable these tests for now. Try with 7e7b5976 and see if that works for you.

**Comment by Kauef** [comment]
Thank u @rfuchs i was able to get over that steep but then i met another problem 

dpkg -i  ngcp-rtpengine-daemon_10.0.0.0+0~mr10.0.0.0_amd64.deb
Selecting previously unselected package ngcp-rtpengine-daemon.
(Reading database ... 75021 files and directories currently installed.)
Preparing to unpack ngcp-rtpengine-daemon_10.0.0.0+0~mr10.0.0.0_amd64.deb ...
Unpacking ngcp-rtpengine-daemon (10.0.0.0+0~mr10.0.0.0) ...
Setting up ngcp-rtpengine-daemon (10.0.0.0+0~mr10.0.0.0) ...
invoke-rc.d: syntax error: unknown option "--skip-systemd-native"
dpkg: error processing package ngcp-rtpengine-daemon (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (232-25+deb9u12) ...
Processing triggers for man-db (2.7.6.1-2) ...
Errors were encountered while processing:
 ngcp-rtpengine-daemon

i found this issue https://github.com/sipwise/rtpengine/issues/848 but i had init-system-helpers already installed.

**Comment by Kauef** [comment]
the solution was really in #848 all i had to to was to update the init-system-helper i added deb http://ftp.de.debian.org/debian stretch-backports main to the source list to get a new version.

and then again i met another problem  <3 : 

The service doesnt start : 

Job for ngcp-rtpengine-daemon.service failed because the control process exited with error code.
See "systemctl status ngcp-rtpengine-daemon.service" and "journalctl -xe" for details.
root@rtpenginetry2:/home/debian# systemctl status ngcp-rtpengine-daemon.service
● ngcp-rtpengine-daemon.service - NGCP RTP/media Proxy Daemon
   Loaded: loaded (/lib/systemd/system/ngcp-rtpengine-daemon.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2021-07-17 23:46:29 UTC; 5min ago
  Process: 1891 ExecStopPost=/usr/sbin/ngcp-rtpengine-iptables-setup stop (code=exited, status=0/SUCCESS)
  Process: 1886 ExecStart=/usr/sbin/rtpengine -f -E --no-log-timestamps --pidfile /run/ngcp-rtpengine-daemon.pid --config-file /etc/rtpengine/rtpengine.conf --table $TA
  Process: 1869 ExecStartPre=/usr/sbin/ngcp-rtpengine-iptables-setup start (code=exited, status=0/SUCCESS)
 Main PID: 1886 (code=exited, status=255)

Jul 17 23:46:05 rtpenginetry2 systemd[1]: Starting NGCP RTP/media Proxy Daemon...
Jul 17 23:46:05 rtpenginetry2 ngcp-rtpengine-iptables-setup[1869]: modprobe: FATAL: Module xt_RTPENGINE not found in directory /lib/modules/4.19.0-0.bpo.9-cloud-amd64
Jul 17 23:46:05 rtpenginetry2 ngcp-rtpengine-iptables-setup[1869]: iptables: No chain/target/match by that name.
Jul 17 23:46:06 rtpenginetry2 ngcp-rtpengine-iptables-setup[1869]: ip6tables: No chain/target/match by that name.
Jul 17 23:46:27 rtpenginetry2 systemd[1]: ngcp-rtpengine-daemon.service: Main process exited, code=exited, status=255/n/a
Jul 17 23:46:29 rtpenginetry2 systemd[1]: Failed to start NGCP RTP/media Proxy Daemon.
Jul 17 23:46:29 rtpenginetry2 systemd[1]: ngcp-rtpengine-daemon.service: Unit entered failed state.
Jul 17 23:46:29 rtpenginetry2 systemd[1]: ngcp-rtpengine-daemon.service: Failed with result 'exit-code'.
lines 1-16/16 (END)

i found the https://github.com/sipwise/rtpengine/issues/761 and itsn't clear that it was solved with that but i tried updating the kernel that i had and reinstalling RTPENGINE again but the problem wasnt solved.

**Comment by Kauef** [comment]
I was trying to use dkms autoinstall but i got this:

**Comment by rfuchs** [comment]
See e3d9354 for a workaround for this

**Comment by Kauef** [comment]
This was it
