### ISSUE TITLE
Compile Error - No such file or directory	...propagated at ../perl/NGCP/Rtpengine/AutoTest.pm line 155.

### ISSUE THREAD

**Issue by webstean** [sipwise/rtpengine#1316]
ok 15 - CN passthrough - 'offer' status
ok 16 - CN passthrough - output 'offer' SDP
ok 17 - echo=fwd - 'answer' status
ok 18 - echo=fwd - output 'answer' SDP
rtp in 0 2000 4000 13398
No such file or directory	...propagated at ../perl/NGCP/Rtpengine/AutoTest.pm line 155.
# Tests were run but no plan was declared and done_testing() was not seen.
make[4]: *** [Makefile:119: daemon-tests-main] Error 254
make[4]: Leaving directory '/usr/local/src/rtpengine/t'
make[3]: *** [Makefile:112: daemon-tests] Error 2
rm sdp.strhash.c control_ng.strhash.c test-const_str_hash.strhash.c call_interfaces.strhash.c
make[3]: Leaving directory '/usr/local/src/rtpengine/t'
make[2]: *** [../lib/common.Makefile:4: all] Error 2
make[2]: Leaving directory '/usr/local/src/rtpengine/t'
make[1]: *** [Makefile:54: check] Error 2
make[1]: Leaving directory '/usr/local/src/rtpengine'
dh_auto_test: error: make -j1 check returned exit code 2
make: *** [debian/rules:35: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
root@host-sbc:/usr/local/src/rtpengine# vi perl/NGCP/Rtp
Rtpclient/    Rtpengine/    Rtpengine.pm  

The offending line in AutoTest.pm is:-

$sock->send($packet, 0, pack_sockaddr_in($dest, inet_aton($addr // '203.0.113.1'))) or die;

This a compile attempt from the master branch

**Comment by rfuchs** [comment]
Do you have any resource limits set or any other restricted permissions that would keep the test suite from using the fake network environment?
