### ISSUE TITLE
opensips 2.4.11 ERROR:rtpengine:parse_flags: error processing flag `ICE' (value 'optional'): invalid value

### ISSUE THREAD

**Issue by wenyuanZZ** [sipwise/rtpengine#1319]
I use it like in opensips 2.4.11

#####################################################################
#####################################################################
#modparam("rtpengine", "rtpengine_sock", "1 == udp:localhost:12221 udp:localhost:12222")
#modparam("rtpengine", "rtpengine_sock", "1 == udp:cooperation---test.vmic.xyz:60001")
modparam("rtpengine", "rtpengine_sock", "1 == udp:10.101.30.231:60001")
modparam("rtpengine", "rtpengine_disable_tout", 20)
modparam("rtpengine", "rtpengine_tout", 2)
modparam("rtpengine", "rtpengine_retr", 2)
#####################################################################
....
rtpengine_use_set("1");
$var(rtpengine_flags) = "ICE=optional";
....
rtpengine_offer("$var(rtpengine_flags)");
....
rtpengine_answer("$var(rtpengine_flags)");
.....

Then,opensips log say:
ERROR:rtpengine:parse_flags: error processing flag `ICE' (value 'optional'): invalid value

How to solve it?plz tell me 1014341495@qq.com,ths.

**Comment by wenyuanZZ** [comment]
I use rtpengine mr9.2 branch

**Comment by razvancrainea** [comment]
The `optional` flag is not yet supported in OpenSIPS - I will make sure it will be available in all supported branches. Unfortunately 2.4 is no longer supported, so it will not get there. If you want to use it, you'll have to backport the fix yourself.

PS: if you get an error in `opensips` log, you should open a report in `opensips` project, not `rtpengine` project.

**Comment by wenyuanZZ** [comment]
> The `optional` flag is not yet supported in OpenSIPS - I will make sure it will be available in all supported branches. Unfortunately 2.4 is no longer supported, so it will not get there. If you want to use it, you'll have to backport the fix yourself.
> 
> PS: if you get an error in `opensips` log, you should open a report in `opensips` project, not `rtpengine` project.

ths,very much, raz. And I has a question, which ver of kamailio support optional flag?Can I copy the opensips route into kamailio and run it immediately?

**Comment by razvancrainea** [comment]
Unfortunately I don't know the answer to the Kamailio question.
But if you are willing to upgrade, OpenSIPS 3.1 has now support for this flag.

**Comment by wenyuanZZ** [comment]
> Unfortunately I don't know the answer to the Kamailio question.
> But if you are willing to upgrade, OpenSIPS 3.1 has now support for this flag.
ths raz,you are great

**Comment by wenyuanZZ** [comment]
> Unfortunately I don't know the answer to the Kamailio question.
> But if you are willing to upgrade, OpenSIPS 3.1 has now support for this flag.

Do you has wechat?my Wechat is 13123382580. I think I should learn a lot from you!

**Comment by rfuchs** [comment]
> > The `optional` flag is not yet supported in OpenSIPS - I will make sure it will be available in all supported branches. Unfortunately 2.4 is no longer supported, so it will not get there. If you want to use it, you'll have to backport the fix yourself.
> > PS: if you get an error in `opensips` log, you should open a report in `opensips` project, not `rtpengine` project.
> 
> ths,very much, raz. And I has a question, which ver of kamailio support optional flag?Can I copy the opensips route into kamailio and run it immediately?

Kamailio doesn't care about the value you give to the `ICE=` option. You can put `ICE=foobar` and it will pass it through. So any Kamailio version that supports `ICE=` at all will also support `ICE=optional`

**Comment by rfuchs** [comment]
Also thanks for maintaining over at OpenSIPS @razvancrainea

**Comment by rfuchs** [comment]
Closing this as it's not an rtpengine issue
