### ISSUE TITLE
no media after re-INVITE (SRTP output wanted, but no crypto suite was negotiated)

### ISSUE THREAD

**Issue by vance-od** [sipwise/rtpengine#132]
Hi folk!
Have an issue with media after hold in call for such a scheme:
UA-A (SIP) -> Kamailio -> Asterisk -> Kamailio(here it involve RTPengine) -> UA-B WebRTC (jssip based)

rtpengine log with debug level 7 is placed here: http://pastebin.com/LSy3SDT2

The case when problem appears:
- UA-A  call UA-B,
- UA-B answers 200OK
- Asterisk send re-INVITE (put in SDP own address)
- UA-B answers 200OK
- ICE negotiation happens
- DTLS handshake happens
---------media exchange OK ------

- UA-B (WebRTC) put call on hold (re-INVITE send)

----------in this moment in log I began to see such messages:

----------SRTP output wanted, but no crypto suite was negotiated

- UA-B make hold-off
There is no media in both direction.

In tcpdump I can see:
- only one DTLS handshake (when initial call established). And no DTLS exchange when hold/unhold.
- after hold media come from WebRTC->rtpengine
                                       from UA-A->Asterisk->rtpengine
and rtpengine does nothing with it (only log messages: SRTP output wanted, but no crypto suite was negotiated)

(Asterisk send re-INVITE with own address this is our custom features. By default media connection is trying to be established directly between UAs, in this case it do not work and Asterisk put its address in SDP)

In log:
UA-A - 192.168.1.24
Kamailio/rtpengine/Asterisk - 192.168.1.85 (speak with each other on localhost)
UA-B - 192.168.1.218

Any ideas how to cope with such troubles would be greatly appreciated.

tried it with (the behaviour is the same):
3.8.2.2+0~mr3.8.2.2
and 
4.0.0.0+0~mr4.0.0.0

updated link, something wrong with first one

**Comment by rfuchs** [comment]
The log is not accessible.

**Comment by vance-od** [comment]
updated the link

**Comment by vance-od** [comment]
Hi Richard!
Any suggestions, or maybe additional information is necessary?
Thanks in advance!

**Comment by rfuchs** [comment]
It looks like the ICE restart doesn't happen when it should, because the ICE attributes have changed. This will need to be fixed in the code.

**Comment by vance-od** [comment]
How can I help with the solution of this problem? Any estimation of when it could be (fix) ? 
Thanks for your help!

**Comment by rfuchs** [comment]
I don't really have a good way to test this, so this will have to involve a bit trial and error. A first possible fix is b3456da (branch `rfuchs/issue132`)

**Comment by vance-od** [comment]
Thank you for the fix. I am starting testing it now, will write a report after tests

**Comment by vance-od** [comment]
Hi Richard!
Thank you again for the fix, tested it, the result is:
1) server in local network,  UAs in local network
calls:
--Test 1.1: UA-A(webRTC) -> UA-B(SIP) - OK 
--Test 1.2: UA-A(webRTC) -> UA-B(WebRTC) - OK

2) server in google cloud VM, UAs in local network (behind NAT)
calls:
--Test 2.1: UA-A(webRTC) -> UA-B(SIP) - OK
--Test 2.2: UA-A(webRTC) -> UA-B(WebRTC) - WRONG (the behaviour in logs as before fix)

Attached trace logs for Test 1.2 and 2.2 (UAs are started on the same PCs, the difference in server's location)

http://justpaste.it/Test_1_2_log_webRTC-webRTC_local
here, after hold in log I see: SSRC changed, updating SRTP crypto contexts

http://justpaste.it/Test_2_2_logwebRTC-webRTC_Gcloud
here, after hold in hold, on the same place I see: SRTP output wanted, but no crypto suite was negotiated

**Comment by alexcme** [comment]
We have the same issue in a slightly different scenario, just a relay between DTLS <-> SDES, but with two important points:

1. DTLS client only accessible through TURN server

2. Hold / un-hold always performed by called party (DTLS)

3. On un-hold port number changes in both offer and answer


So we have it like this:

1. Offer from SDES client A to DTLS client B, answered with the media path:

A <-SDES-> rtpengine <-DTLS-> turn <-DTLS-> B

2. Hold from DTLS client B (no changes in port numbers, no ICE restart)

3. Un-hold from DTLS client B:
 
- port number (and TURN relay) changes in offer from B

- port number changes in answer from SDES client A

4. At this point we have “ICE role conflict detected” in rtpengine log and it does not send ICE requests anymore (just error responses)

It does not happened all the time, I saved failed rtpengine log at:

https://www.dropbox.com/l/3BxscOysXK7AwAKo3abGRn

and successful log at:

https://www.dropbox.com/l/MPBNbwVRy43DLYLmNihOlo

the only difference I see is an extra statement in failing case after rtpengine generated response for answer from SDES client A:

"Created candidate pair ey41EdMzMLrZmjoK:00ffff00002dc4170a31:1 between 10.17.18.28 and 10.23.196.45:61371, type prflx"

**Comment by vance-od** [comment]
Hi Richard! 
Any news about our issue? )

Do you need anything additionally?

Thanks!

**Comment by rfuchs** [comment]
Can you please try again with the latest master. There have been a few changes regarding DTLS, re-invite and DTLS/SDES combos, which might just fix your problem.

**Comment by vance-od** [comment]
Tried the latest master 59b0f331ad214c21684e2964ecdc4fa99ea12417. The result is the same as in b3456da.

2) server in google cloud VM, UAs in local network (behind NAT)
calls:
--Test 2.2: UA-A(webRTC) -> UA-B(WebRTC) - WRONG (the behaviour in logs as before fix)

The current log of wrong call:
http://justpaste.it/new_log_webRTC-webRTC_cloud

**Comment by rfuchs** [comment]
OK, so this seems to be a different issue than before. I'm assuming that from the log, the relevant call is 25cc70845358b7913fcdc4ed3369e765 and not 6no0ip9tce432hhj4igr?

What seems to happen is that the re-invite from the RTP endpoint changes its endpoint, which causes rtpengine to also change endpoints on the SRTP side. This in turn causes ICE and DTLS to reset, which can be seen in a changed ICE details (ufrag). The SRTP endpoint then also correctly changes ICE details, indicating an ICE restart. However after this, ICE fails to be negotiated for some reason, which means that DTLS also cannot be established.

The log shows ICE authentication errors, indicating that at least one side probably hasn't updated its ICE details correctly. What would be interesting here now is a packet dump that includes the ICE packets sent back and forth. That would reveal which side of the ICE negotiation is in error.

**Comment by vance-od** [comment]
The asked dump is sent to mail, 
about relevant calls:
6no0ip9tce432hhj4igr - first leg (UA-A connect to kamailio/rtpengine)
25cc70845358b7913fcdc4ed3369e765 - second leg (UA-B connect to kamailio/rtpengine)
this is why I think they are both relevant.

**Comment by vance-od** [comment]
New aspect of investigation. The described problem appears only in case when:
Server in google cloud (public IP-A)
UA-A and UA-B in one local network, and in the point of view of rtpengine it is the same IP!

In case:
server (rtpengine) - public IP-A
UA-A - public IP-B
UA-B - public IP-C
after hold everything work OK.

Maybe this can help to reveal the root of the problem? Do I need to send logs traces for working case?

**Comment by alexcme** [comment]
Still think the problem is that we don't restart ICE when port changed in answer, i.e. when we do un-hold:

1. "A" send un-hold offer with new port number in offer
2. We start ICE from an "old" relay port on rtpengine, allocate new port for be side
3. "B" send  un-hold answer with new port number in answer
4. rtpengine change port on "A" side to new one (different from #1 above)
5. at this point we have to restart ICE on "A" side, bcs we still sending STUN requests from the port in #1, so responses will not match

**Comment by vance-od** [comment]
We have a working way for the problem, we switch off our custom feature direct RTP (I mentioned it in one of the first posts). Without it - works ok.
Also tested with current master brunch, that, as Richard said include logic of suggested here patch. Also works OK.
Currently the issue should be closed.
Great thanks for Richard for spending time with our issue, and for the rtpengine project development as well!
Cheers
