### ISSUE TITLE
opensips-3.1.3

### ISSUE THREAD

**Issue by wenyuanZZ** [sipwise/rtpengine#1321]
I can not load uri.so， Is this module killd in 3.1.3?Jul 22 10:54:47 vmeet-flexisip-dev-10-101-29-1 opensips: ERROR:core:sr_load_module: could not open module </usr/local/lib64/opensips/modules/uri.so>: /usr/local/lib64/opensips/modules/uri.so: undefined symbol: fixup_free_pvar_null

**Comment by razvancrainea** [comment]
The `uri` module is no longer available in OpenSIPS 3.1. Please follow the [migration tutorial](https://www.opensips.org/Documentation/Migration) if you are trying to migrate from an older OpenSIPS version.

PS: this is a 100% OpenSIPS question - not sure why bother rtpengine project/community with it. Please close this ticket and refer to OpenSIPS [Users List](http://lists.opensips.org/cgi-bin/mailman/listinfo/users) and/or OpenSIPS [Issue tracker](https://github.com/OpenSIPS/opensips/issues) for further assistence.
