### ISSUE TITLE
MOS stat is not provides in transcoded calls statistics

### ISSUE THREAD

**Issue by kertor** [sipwise/rtpengine#1324]
Hello! Could tou please check, why MOS stats is not present forr transcoded calls?

I see that MOS stats provided for calls without transcoding, example:
[call-without-transcoding.zip](https://github.com/sipwise/rtpengine/files/6886111/call-without-transcoding.zip)

And i see that MOS is not present in transcoded call statistics:
[call-with-transcoding.zip](https://github.com/sipwise/rtpengine/files/6886117/call-with-transcoding.zip)

As far as i understand, MOS must be provided for both types of calls.
Could you please check it? Thank you!

Rtpengine version:
```
Version: 9.5.0.0~20210511~aaddaa6a-1 git-master-addaa6ac
```

**Comment by rfuchs** [comment]
The MOS calculation does take place, but the MOS comes out as zero for some reason. There might be some strange values in the RTCP packets but the log doesn't really show anything. Try again after rebuilding from the top of the mr9.5 branch as you're missing a number of commits and there have been changes in this area.

**Comment by zenichev** [comment]
@kertor try to checkout this couple of issue reports:
- https://github.com/sipwise/rtpengine/issues/947
- https://github.com/kamailio/kamailio/issues/2340

I experienced similar issue as you, and using some hints from issue reports (mentioned above), was able to solve the thing.

**Comment by kertor** [comment]
@zenichev Thank you for advice!

**Comment by rfuchs** [comment]
Closing this as there's no evidence of an issue with the code here. This can be discussed further on our mailing list: https://rtpengine.com/mailing-list
