### ISSUE TITLE
SEGV when SDP have two identical DTMF PT

### ISSUE THREAD

**Issue by Den4t** [sipwise/rtpengine#1328]
Hi !

The problem appears when SDP have two identical DTMF PT in m=audio (101 & 96 in log).
At first, rtpengine decide to use transcoding by himself, but tis is a half of problem, when real DTMF event arrive, rtpengine crashed with SEGV.
Solution for now - disable transcoding at build time.

[call.log](https://github.com/sipwise/rtpengine/files/6960501/call.log)

**Comment by rfuchs** [comment]
Which version/commit?

Post a backtrace from the core dump

**Comment by Den4t** [comment]
9.4.1.1+0~mr9.4.1.1
Sorry, do not have core dump now.
