### ISSUE TITLE
Unknown codec issue in rtpengine using jtisi or jssip clients

### ISSUE THREAD

**Issue by bquandt** [sipwise/rtpengine#133]
I saw ticket #115  

Think I'm having a similar problem. Here's my test enivron:

1) Google Chrome 43.0.2357.81 (Official Build) (64-bit)
2) two computers both using chrome and tryit.jssip.net and ws set to
ws://myawssipserver:5060/ws
3) my sip server is my own via AWS AMI spce 3.8.2
4) subscriber prefs with these type of settings:

```
WebRTC Subscribers -> Details -> Preferences -> NAT and Media Flow Control
    'use_rtpproxy:' Always with rtpproxy as additional/only ICE candidate
    'transport_protocol:' RTP/SAVPF (encrypted SRTP with RTCP feedback) ­
    Domain -> Details -> Preferences -> NAT and Media Flow Control
    'transport_protocol:' RTP/AVP (Plain RTP)
```

Results, everyone connect fine and gets registered. Calling the other subscriber, rings through. Upon answer, one side reports webrtc error, the other side reports "incompatible sdp".

rtp.log shows (incompatible codec):
Jul 9 19:54:27 ip-10-220-196-230 rtpengine[6430]: [g474qoosomrrqq3tnd5a] ------ Media #1 (audio over RTP/SAVPF) using unknown codec
Jul 9 19:54:27 ip-10-220-196-230 rtpengine[6430]: [g474qoosomrrqq3tnd5a] --------- Port 33942 <> 157.254.210.20:56739, 0 p, 0 b, 0 e, 1436471632 last_packet
Jul 9 19:54:27 ip-10-220-196-230 rtpengine[6430]: [g474qoosomrrqq3tnd5a] ------ Media #2 (video over RTP/SAVPF) using unknown codec
Jul 9 19:54:27 ip-10-220-196-230 rtpengine[6430]: [g474qoosomrrqq3tnd5a] --------- Port 33968 <> 157.254.210.20:57218, 0 p, 0 b, 0 e, 1436471632 last_packet

I've tested this from clients running chrome on ubuntu 14.10 to OSX/Yosemite in differing combiantions to try to determine if it's a OS nuance. In all combo's the resutls are the same.

Any thoughts?

**Comment by rfuchs** [comment]
"Unknown codec" simply means that no RTP packets were received. You should look into the resulting SDP bodies to see why they're being rejected, either in rtpengine's log (if you increase the log level) or in your browser's log. One thing to try is to use UDP/TLS/RTP/SAVPF as transport protocol instead of RTP/SAVPF.

**Comment by bit4bit** [comment]
@rfuchs thanks it's works
