### ISSUE TITLE
Handling responses with different to-tags properly

### ISSUE THREAD

**Issue by jklingenmeyer** [sipwise/rtpengine#1330]
_It is more a question than an issue, please remove it if it is not the right place for such requests_

I am wondering how to deal with this kind of scenario:

```
... <-> Provider <--> Kamailio/RTPEngine <--> endpoint A
```

1. A is calling. (INVITE is sent).
2. Provider replies with:
> 183+SDP Progress, with To-Tag A (it is a kind of ringback tone). 
> 200+SDP OK, with To-Tag B (callee picks up).

SDP between the 183 and 200 are the same, excepting the session version which is incremented.
I face a one-way call with this scenario. My assumption is that it is because I maybe call rtpengine in a wrong way from Kamailio:
* Kamailio sends a offer request when dealing with the initial INVITE request
* Kamailio sends an answer request for each received reply.

From what I read in "standard" SIP implementation, I am wondering whether I should rather treat the responses as different dialogs. Because to-tag are different.

So what is the correct way to handle this case ? Do I need to have a couple of offer/answer for each dialog?
If so, when do I have to send the second offer request to rtpengine in the Kamailio script exactly?

Your tips would be appreciated, thanks.

**Comment by rfuchs** [comment]
This isn't really currently supported as it appears like a branched offer to rtpengine and we require one offer for each branch (with different via-branch tags) for each answer (different to-tag) that it might get to see. Your best bet without submitting a patch is to supply a fake to-tag to rtpengine so that the two answers appear to belong to the same dialogue.

**Comment by jklingenmeyer** [comment]
I already tried to send a fake to-tag to rtpengine when treating the 200 (the same as the one in the 183 in fact), and it works like a charm! But I was worried about maybe breaking some other scenarios by doing so.
In SIP it is like "fix one scenario and break 10 other ones" :)
Thank you it is clear to me, this can be closed.
