### ISSUE TITLE
segfault __output_ssrc_handler at codec.c

### ISSUE THREAD

**Issue by thomas414** [sipwise/rtpengine#1331]
[gdb.txt](https://github.com/sipwise/rtpengine/files/6990444/gdb.txt)

Hi,

backtrace is attached, rtpengine version is:
9.5.1.0+0~mr9.5.1.0 git-mr9.5-451e11a6

If you need anything else please let me know!

**Comment by rfuchs** [comment]
Fixed in mr9.5 as per above commits.

Master branch not affected.
