### ISSUE TITLE
Redis - Failed to restore call

### ISSUE THREAD

**Issue by Den4t** [sipwise/rtpengine#1334]
Hi !

After upgrade from mr9.4.1.1 to versions: mr9.5.1.3 and mr9.5.2.0 restoring the call from redis stopped working with keyspace notification.
Log from standby rtpengine instance:

Aug 16 19:42:55 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 0) pmessage
Aug 16 19:42:55 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 1) __keyspace@6__:*
Aug 16 19:42:55 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 2) __keyspace@6__:E2490E3953248CAC9429022567D79266
Aug 16 19:42:55 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 3) set
Aug 16 19:42:55 regtest1 rtpengine[29867]: NOTICE: [core] Creating new call
Aug 16 19:42:55 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 0) pmessage
Aug 16 19:42:55 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 1) __keyspace@6__:*
Aug 16 19:42:55 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 2) __keyspace@6__:E2490E3953248CAC9429022567D79266
Aug 16 19:42:55 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 3) expire
Aug 16 19:42:55 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 0) pmessage
Aug 16 19:42:55 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 1) __keyspace@6__:*
Aug 16 19:42:55 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 2) __keyspace@6__:E2490E3953248CAC9429022567D79266
Aug 16 19:42:55 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 3) set
**Aug 16 19:42:55 regtest1 rtpengine[29867]: WARNING: [core] Failed to restore call ID 'E2490E3953248CAC9429022567D79266' from Redis: could not retrieve JSON data from redis**
Aug 16 19:42:55 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 0) pmessage
Aug 16 19:42:55 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 1) __keyspace@6__:*
Aug 16 19:42:55 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 2) __keyspace@6__:E2490E3953248CAC9429022567D79266
Aug 16 19:42:55 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 3) expire
Aug 16 19:42:55 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 0) pmessage
Aug 16 19:42:55 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 1) __keyspace@6__:*
Aug 16 19:42:55 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 2) __keyspace@6__:E2490E3953248CAC9429022567D79266
Aug 16 19:42:55 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 3) del
Aug 16 19:42:55 regtest1 rtpengine[29867]: NOTICE: [core] Redis-Notifier: DEL did not find call with callid: __keyspace@6__:E2490E3953248CAC9429022567D79266
Aug 16 19:42:56 regtest1 rtpengine[29867]: DEBUG: [core] timer run time = 0.000040 sec
Aug 16 19:42:57 regtest1 rtpengine[29867]: DEBUG: [core] timer run time = 0.000060 sec
Aug 16 19:42:58 regtest1 rtpengine[29867]: DEBUG: [core] timer run time = 0.000040 sec
Aug 16 19:42:59 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 0) pmessage
Aug 16 19:42:59 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 1) __keyspace@6__:*
Aug 16 19:42:59 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 2) __keyspace@6__:E2490E3953248CAC9429022567D79266
Aug 16 19:42:59 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 3) set
Aug 16 19:42:59 regtest1 rtpengine[29867]: NOTICE: [core] Creating new call
Aug 16 19:42:59 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 0) pmessage
Aug 16 19:42:59 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 1) __keyspace@6__:*
Aug 16 19:42:59 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 2) __keyspace@6__:E2490E3953248CAC9429022567D79266
Aug 16 19:42:59 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 3) expire
Aug 16 19:42:59 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 0) pmessage
Aug 16 19:42:59 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 1) __keyspace@6__:*
Aug 16 19:42:59 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 2) __keyspace@6__:E2490E3953248CAC9429022567D79266
Aug 16 19:42:59 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 3) set
Aug 16 19:42:59 regtest1 rtpengine[29867]: WARNING: [core] Failed to restore call ID 'E2490E3953248CAC9429022567D79266' from Redis: could not retrieve JSON data from redis
Aug 16 19:42:59 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 0) pmessage
Aug 16 19:42:59 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 1) __keyspace@6__:*
Aug 16 19:42:59 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 2) __keyspace@6__:E2490E3953248CAC9429022567D79266
Aug 16 19:42:59 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 3) expire
Aug 16 19:42:59 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 0) pmessage
Aug 16 19:42:59 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 1) __keyspace@6__:*
Aug 16 19:42:59 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 2) __keyspace@6__:E2490E3953248CAC9429022567D79266
Aug 16 19:42:59 regtest1 rtpengine[29867]: DEBUG: [core] Redis-Notify: 3) del
Aug 16 19:42:59 regtest1 rtpengine[29867]: NOTICE: [core] Redis-Notifier: DEL did not find call with callid: __keyspace@6__:E2490E3953248CAC9429022567D79266

Master rtpengine instance work with db=6, slave subscribed to 6.

**Comment by rfuchs** [comment]
Probably same issue as #1308. There's some commits there (and a branch) that might fix it, but I haven't gotten any feedback from it.

**Comment by Den4t** [comment]
I applied a patch to m9.5 (9.5.2.0), can confirm that the error is gone, but there are a few messages "Create a new call"
i guess this is ok:

Aug 17 00:26:03 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 0) pmessage
Aug 17 00:26:03 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 1) __keyspace@6__:*
Aug 17 00:26:03 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 2) __keyspace@6__:6D1FF296149B8A541021788FE2A848ED
Aug 17 00:26:03 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 3) set
Aug 17 00:26:03 regtest1 rtpengine[19079]: NOTICE: [core] Creating new call
Aug 17 00:26:03 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 0) pmessage
Aug 17 00:26:03 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 1) __keyspace@6__:*
Aug 17 00:26:03 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 2) __keyspace@6__:6D1FF296149B8A541021788FE2A848ED
Aug 17 00:26:03 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 3) expire
Aug 17 00:26:03 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 0) pmessage
Aug 17 00:26:03 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 1) __keyspace@6__:*
Aug 17 00:26:03 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 2) __keyspace@6__:6D1FF296149B8A541021788FE2A848ED
Aug 17 00:26:03 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 3) set
Aug 17 00:26:03 regtest1 rtpengine[19079]: NOTICE: [6D1FF296149B8A541021788FE2A848ED]: [core] Creating new call
Aug 17 00:26:03 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 0) pmessage
Aug 17 00:26:03 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 1) __keyspace@6__:*
Aug 17 00:26:03 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 2) __keyspace@6__:6D1FF296149B8A541021788FE2A848ED
Aug 17 00:26:03 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 3) expire
Aug 17 00:26:04 regtest1 rtpengine[19079]: DEBUG: [core] timer run time = 0.000192 sec
Aug 17 00:26:06 regtest1 rtpengine[19079]: DEBUG: [core] timer run time = 0.000089 sec
Aug 17 00:26:07 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 0) pmessage
Aug 17 00:26:07 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 1) __keyspace@6__:*
Aug 17 00:26:07 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 2) __keyspace@6__:6D1FF296149B8A541021788FE2A848ED
Aug 17 00:26:07 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 3) set
Aug 17 00:26:07 regtest1 rtpengine[19079]: NOTICE: [6D1FF296149B8A541021788FE2A848ED]: [core] Creating new call
Aug 17 00:26:07 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 0) pmessage
Aug 17 00:26:07 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 1) __keyspace@6__:*
Aug 17 00:26:07 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 2) __keyspace@6__:6D1FF296149B8A541021788FE2A848ED
Aug 17 00:26:07 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 3) expire
Aug 17 00:26:07 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 0) pmessage
Aug 17 00:26:07 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 1) __keyspace@6__:*
Aug 17 00:26:07 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 2) __keyspace@6__:6D1FF296149B8A541021788FE2A848ED
Aug 17 00:26:07 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 3) set
Aug 17 00:26:07 regtest1 rtpengine[19079]: NOTICE: [6D1FF296149B8A541021788FE2A848ED]: [core] Creating new call
Aug 17 00:26:07 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 0) pmessage
Aug 17 00:26:07 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 1) __keyspace@6__:*
Aug 17 00:26:07 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 2) __keyspace@6__:6D1FF296149B8A541021788FE2A848ED
Aug 17 00:26:07 regtest1 rtpengine[19079]: DEBUG: [core] Redis-Notify: 3) expire

# rtpengine-ctl list numsessions all
Current sessions own: 0
Current sessions foreign: 1
Current sessions total: 1
Current transcoded media: 0
Current sessions ipv4 only media: 0
Current sessions ipv6 only media: 0
Current sessions ip mixed  media: 0

**Comment by rfuchs** [comment]
Yes that is expected behaviour under the current implementation.
