### ISSUE TITLE
Can't start to user space mode

### ISSUE THREAD

**Issue by korithi** [sipwise/rtpengine#1338]
Hello,

I just have installed rtpengine on debian 10. 
I change the table = -1 for user space mode in rtpengine.conf and it still shows the kernel error when it starts.

modprobe: FATAL: Module xt_RTPENGINE not found in directory /lib/modules/4.19.0-8-amd64

Thanks

**Comment by rfuchs** [comment]
Set `TABLE=-1` in /etc/default/ngcp-rtpengine-daemon

**Comment by guillemj** [comment]
I've merged some changes to git HEAD to make the table setting in the config the only source of truth. Now changing that will affect all its users and will not get out of sync. Closing.
