### ISSUE TITLE
I compiled on centos7.5 and reported the following error. Can anyone help me?

### ISSUE THREAD

**Issue by huangqingbiao8831** [sipwise/rtpengine#1339]
/bin/sh: exec_prefix: command not found
//usr/lib64/libfontconfig.so.1: undefined reference to `uuid_parse@UUID_1.0'
//usr/lib64/libfontconfig.so.1: undefined reference to `uuid_generate_random@UUID_1.0'
//usr/lib64/libblkid.so.1: undefined reference to `uuid_unparse@UUID_1.0'
//usr/lib64/libfontconfig.so.1: undefined reference to `uuid_copy@UUID_1.0'
collect2: error: ld returned 1 exit status

and the libontconfig.so.1 in 

[root@bogon daemon]# find / -name libfontconfig.so*
/usr/lib/libfontconfig.so.1
/usr/lib/libfontconfig.so.1.11.1
/usr/lib64/libfontconfig.so.1
/usr/lib64/libfontconfig.so.1.11.1
/usr/lib64/libfontconfig.so
[root@bogon daemon]#

**Comment by huangqingbiao8831** [comment]
modify Makefile  add -luuid.

**Comment by rfuchs** [comment]
We don't use libuuid directly. So if this requirement exists on your system, then that's probably a problem in the packaging of the library using it.
