### ISSUE TITLE
iptables: not found

### ISSUE THREAD

**Issue by juha-h** [sipwise/rtpengine#1343]
I installed rtpengine mr5.9.1 on Debian Bullseye.  Installation of rtpengine (and also building of the packages) went without errors, but when I started rtpengine, I got these messages to syslog:
```
Sep  7 10:05:55 bullseye systemd[1]: Starting NGCP RTP/media Proxy Daemon...
Sep  7 10:05:55 bullseye kernel: [  411.742916] xt_RTPENGINE: loading out-of-tree module taints kernel.
Sep  7 10:05:55 bullseye kernel: [  411.743010] xt_RTPENGINE: module verification failed: signature and/or required key missing - tainting kernel
Sep  7 10:05:55 bullseye kernel: [  411.747450] Registering xt_RTPENGINE module - version 9.5.1.3+0~mr9.5.1.3
Sep  7 10:05:55 bullseye rtpengine-iptables-setup[7114]: /usr/sbin/rtpengine-iptables-setup: 56: iptables: not found
Sep  7 10:05:55 bullseye rtpengine-iptables-setup[7114]: /usr/sbin/rtpengine-iptables-setup: 58: iptables: not found
Sep  7 10:05:55 bullseye rtpengine-iptables-setup[7114]: /usr/sbin/rtpengine-iptables-setup: 62: ip6tables: not found
Sep  7 10:05:55 bullseye rtpengine-iptables-setup[7114]: /usr/sbin/rtpengine-iptables-setup: 64: ip6tables: not found
Sep  7 10:05:55 bullseye systemd[1]: Started NGCP RTP/media Proxy Daemon.
```
rtpengine did start, but any idea why `iptables: not found` messages appeared and how to avoid them?

**Comment by rfuchs** [comment]
`apt install iptables` probably? Might need to be added as an explicit dependency for bullseye...

**Comment by juha-h** [comment]
Richard Fuchs writes:

> `apt install iptables` probably? Might need to be added as an explicit
> dependency for bullseye...

Yes, `apt install iptables` fixed the issue.  Looks like explicit
dependency is needed for Bullseye.  Buster didn't need it.
