### ISSUE TITLE
Support for Remote Call Recording

### ISSUE THREAD

**Issue by NaveenKhannaBM** [sipwise/rtpengine#1344]
We are implementing high availability recording. Is it possible to do a remote recording or external server?

Thanks,

Naveen Khanna

**Comment by rfuchs** [comment]
You can write the recordings to a network storage (e.g. NFS), or use the `tls-send-to` option to send the decoded PCM to an external server. Or you can do the entire decoding/recording on an external server, either with the `forward-to` option of the recording daemon, or use the new `subscribe` mechanism to implement something like SIPREC. Lots of options.

**Comment by NaveenKhannaBM** [comment]
Thanks, for the inputs and for providing the direction.

Is there any documentation on the tls-send-to / subscribe method?

Thanks,

Naveen Khanna

**Comment by rfuchs** [comment]
"Subscribe" is brand new and documented here: https://github.com/sipwise/rtpengine#subscribe-request-message

`tls-send-to` is an option to the recording daemon and can be used alongside or instead of other recording methods: https://github.com/sipwise/rtpengine/blob/master/recording-daemon/rtpengine-recording.pod#options

**Comment by NaveenKhannaBM** [comment]
Thank You!!!

I will go through the documents and will work on this.

Thanks,

Naveen Khanna

**Comment by genmzy** [comment]
> "Subscribe" is brand new and documented here: https://github.com/sipwise/rtpengine#subscribe-request-message
> 
> `tls-send-to` is an option to the recording daemon and can be used alongside or instead of other recording methods: https://github.com/sipwise/rtpengine/blob/master/recording-daemon/rtpengine-recording.pod#options

Hello Richard, recording metadata to NFS disk will be ok, but is there any solution to run rtpengine-recording daemon in another server which mounted the same NFS disk?
Rtpengine-recording and rtpengine will preempt CPU when they are in the same machine.

**Comment by genmzy** [comment]
> You can write the recordings to a network storage (e.g. NFS), or use the `tls-send-to` option to send the decoded PCM to an external server. Or you can do the entire decoding/recording on an external server, either with the `forward-to` option of the recording daemon, or use the new `subscribe` mechanism to implement something like SIPREC. Lots of options.

Hello Richard, recording metadata to NFS disk will be ok, but is there any solution to run rtpengine-recording daemon in another server which mounted the same NFS disk?
Rtpengine-recording and rtpengine will preempt CPU when they are in the same machine.

**Comment by rfuchs** [comment]
No, the recording daemon is designed to run on the same machine as rtpengine itself. You need to create some sort of media forking scenario if you want to do the recording on a different machine, which is what `subscribe` could be used for. I talked about this in my recent presentation at ClueCon (https://rfuchs.github.io/2022/10/19/cluecon.html) although this specific scenario isn't supported out of the box right now.

Closing this as this isn't an issue with the code. Direct general questions to the mailing list: https://rtpengine.com/mailing-list
