### ISSUE TITLE
Improper locking error, a lock is not released?

### ISSUE THREAD

**Issue by ryancaicse** [sipwise/rtpengine#1348]
HI, developers, it seems the lock **ret->lock** is never released in the program. Shoule it be a bug or on purpose? Thanks~

https://github.com/sipwise/rtpengine/blob/c7085085a7d154608144db2a201d65547f23f520/recording-daemon/packet.c#L173-L182

**Comment by rfuchs** [comment]
As per the leading comment for the function:  `// ... returns ssrc locked`

So the caller is responsible for releasing the lock.

**Comment by ryancaicse** [comment]
@rfuchs Hi, thank you for your checking.
