### ISSUE TITLE
PCMA transcoding ptime=30ms to 20ms and back again kamailio 5.4 and git-master-01f06ceb 

### ISSUE THREAD

**Issue by jonhvoxbox** [sipwise/rtpengine#1349]
Hi Guys,

I am currently using kamailio 5.4 and rtpengine git-master-01f06ceb within alpine docker containers and its been working well, however we have an issue with our onwards carrier so I need to use transcoding, however I am having issues with it.

Essentially an ATA CPE device when it sends a default INVITE with SDP is sending a ptime=30 as well as the list of codecs shown below;

ATA device sends in SDP of;
            Connection Information (c): IN IP4 10.20.0.182
            Time Description, active time (t): 0 0
            Media Description, name and address (m): audio 16396 RTP/AVP 0 2 8 18 100 101
            Media Attribute (a): rtpmap:0 PCMU/8000
            Media Attribute (a): rtpmap:2 G726-32/8000
            Media Attribute (a): rtpmap:8 PCMA/8000
            Media Attribute (a): rtpmap:18 G729a/8000
            Media Attribute (a): rtpmap:100 NSE/8000
            Media Attribute (a): fmtp:100 192-193
            Media Attribute (a): rtpmap:101 telephone-event/8000
            Media Attribute (a): fmtp:101 0-15
            Media Attribute (a): ptime:30
            Media Attribute (a): sendrecv
            [Generated Call-ID: 44294c4a-f62694f4@10.20.0.182]

Our carrier supports PCMA 20ms so was rejecting the request with 415, however I enabled transcoding and ptime as below and they now accept the call;

I enable rtpengine_manage("ICE=remove direction=external direction=internal replace-origin replace-session-connection codec-mask-all codec-transcode-PCMA ptime=20");

And the onwards offer to carrier SDP is;

 
            Connection Information (c): IN IP4 10.0.54.209
            Time Description, active time (t): 0 0
            Media Description, name and address (m): audio 32332 RTP/AVP 8
            Media Attribute (a): rtpmap:8 PCMA/8000
            Media Attribute (a): sendrecv
            Media Attribute (a): rtcp:32333
            Media Attribute (a): ptime:20
            [Generated Call-ID: 44294c4a-f62694f4@10.20.0.182]

So transcodes as required out to carrier, however on reply/answer we get back from carrier SDP of;

            Connection Information (c): IN IP4 10.0.54.222
            Time Description, active time (t): 0 0
            Media Description, name and address (m): audio 6164 RTP/AVP 8
            Media Attribute (a): rtpmap:8 PCMA/8000
            Media Attribute (a): silenceSupp:off - - - -
            Media Attribute (a): ptime:20
            [Generated Call-ID: 44294c4a-f62694f4@10.20.0.182]

And on receipt of this I have set;

rtpengine_manage("ICE=remove direction=internal direction=external replace-origin replace-session-connection codec-except-PCMA ptime-reverse=30");

However the SDP sent back in answer to the CPE is;

            Connection Information (c): IN IP4 XX.XX.XX.XX
            Time Description, active time (t): 0 0
            Media Description, name and address (m): audio 34600 RTP/AVP 0 8 18 101
            Media Attribute (a): silenceSupp:off - - - -
            Media Attribute (a): rtpmap:0 PCMU/8000
            Media Attribute (a): rtpmap:8 PCMA/8000
            Media Attribute (a): rtpmap:18 G729a/8000
            Media Attribute (a): rtpmap:101 telephone-event/8000
            Media Attribute (a): fmtp:101 0-15
            Media Attribute (a): sendrecv
            Media Attribute (a): rtcp:34601
            Media Attribute (a): ptime:30
            [Generated Call-ID: 44294c4a-f62694f4@10.20.0.182]

This is causing the CPE to have audio issues, so ideally I just want PCMA with ptime=30 sent back to the CPE, however rtpengine doesnt seem to allow me to do this, however I assume its user error? (me :)).

Could you please advise so I have only PCMA 30 ms on legs to CPE and PCMA 20 ms on carrier side.

Thanks

Jon

**Comment by rfuchs** [comment]
Are you saying that the RTP going back to the A-side ATA is not actually sent in 30-ms packets despite the SDP saying `ptime:30`?

**Comment by jonhvoxbox** [comment]
Hi Richard, 

Within the SDP I am expecting only G711A and ptime=20ms to be sent back to the ATA as this is specified by the flags/directives, instead multiple codecs and ptime=30ms is advertised in the SDP back on answer, I thought this would be modified by rtpengine by me adding except and pttime-reverse?

I haven't reviewed the rtp packets themselves as of yet I just want to get clarity on if setting the rtpengine flags, however can check this.

Also I only see this happen with this ATA when ptime=30ms. On other end devices I dont see this problem.

Thanks

Jon

**Comment by rfuchs** [comment]
I suggest updating your code as you're missing a crucial commit (1d387b9) which might just address this.

FTR, `ptime-reverse` is to be used in the "offer" not in the "answer" (as per docs it's ignored in an answer) but shouldn't be necessary in your case as the offer already specifies `ptime:30`

**Comment by jonhvoxbox** [comment]
Ok thankyou I will update and retest, many thanks.

**Comment by jonhvoxbox** [comment]
Hi Richard, great thank you for the update advise that fixes it!

Thanks again and sorry for the noise.

Jon
