### ISSUE TITLE
Error while compiling new 4.1 under debian 8.1

### ISSUE THREAD

**Issue by albersag** [sipwise/rtpengine#135]
I have compiled and created all .deb packages and installed with dpkg -i for iptables kernel operation.

module is created correctly under /lib/modules/3.16.0-4-amd64/updates/dkms/
```
root@kam01:~# ls -al /lib/modules/3.16.0-4-amd64/updates/dkms/
total 52
drwxr-xr-x 2 root root  4096 jul 15 16:21 .
drwxr-xr-x 3 root root  4096 jul 15 16:21 ..
-rw-r--r-- 1 root root 41264 jul 15 16:21 xt_RTPENGINE.ko
root@kam01:~# 
```
But when insmod  gotcha an Unknown symbol in module
```
insmod /lib/modules/3.16.0-4-amd64/updates/dkms/xt_RTPENGINE.ko
insmod: ERROR: could not insert module /lib/modules/3.16.0-4-amd64/updates/dkms/xt_RTPENGINE.ko: Unknown symbol in module
```
What could be wrong?

I did with 4.0 and worked fine
```
-rw-r--r--  1 root     root       155876 jul 15 16:00 ngcp-rtpengine-daemon_4.1.0.0+0~mr4.1.0.0_amd64.deb
-rw-r--r--  1 root     root       410626 jul 15 16:00 ngcp-rtpengine-dbg_4.1.0.0+0~mr4.1.0.0_amd64.deb
-rw-r--r--  1 root     root        73266 jul 15 16:00 ngcp-rtpengine-dev_4.1.0.0+0~mr4.1.0.0_all.deb
-rw-r--r--  1 root     root        49068 jul 15 16:00 ngcp-rtpengine-iptables_4.1.0.0+0~mr4.1.0.0_amd64.deb
-rw-r--r--  1 root     root        60848 jul 15 16:00 ngcp-rtpengine-kernel-dkms_4.1.0.0+0~mr4.1.0.0_all.deb
-rw-r--r--  1 root     root        74670 jul 15 16:00 ngcp-rtpengine-kernel-source_4.1.0.0+0~mr4.1.0.0_all.deb
```
Any thing i could test? Thanks

**Comment by albersag** [comment]
Here is log when installing kernel-dkms package

-------- Uninstall Beginning --------
Module:  ngcp-rtpengine
Version: 4.1.0.0+0~mr4.1.0.0
Kernel:  3.16.0-4-amd64 (x86_64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

xt_RTPENGINE.ko:
 - Uninstallation
   - Deleting from: /lib/modules/3.16.0-4-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod....

DKMS: uninstall completed.

------------------------------
Deleting module version: 4.1.0.0+0~mr4.1.0.0
completely from the DKMS tree.
------------------------------
Done.
Desempaquetando ngcp-rtpengine-kernel-dkms (4.1.0.0+0~mr4.1.0.0) sobre (4.1.0.0+0~mr4.1.0.0) ...
Configurando ngcp-rtpengine-kernel-dkms (4.1.0.0+0~mr4.1.0.0) ...

Creating symlink /var/lib/dkms/ngcp-rtpengine/4.1.0.0+0~mr4.1.0.0/source ->
                 /usr/src/ngcp-rtpengine-4.1.0.0+0~mr4.1.0.0

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area.....
make KERNELRELEASE=3.16.0-4-amd64 -C /lib/modules/3.16.0-4-amd64/build M=/var/lib/dkms/ngcp-rtpengine/4.1.0.0+0~mr4.1.0.0/build RTPENGINE_VERSION=4.1.0.0+0~mr4.1.0.0......
cleaning build area....

DKMS: build completed.

xt_RTPENGINE:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.16.0-4-amd64/updates/dkms/

depmod....

DKMS: install completed

**Comment by rfuchs** [comment]
You probably need to modprobe x_tables first.

**Comment by albersag** [comment]
Thanks rfuchs. You are right. Solved

I have an rtpengine 4.0 and do not need to add to /etc/modules? 

root@kam02:/usr/src# rtpengine -v
4.0.0.0+0~mr4.0.0.0 git-master-5ba8e2e

**Comment by rfuchs** [comment]
It depends. If you use insmod, then you need to manually load dependency modules first. If you use modprobe (or the included init.d script) then that happens automatically.

**Comment by albersag** [comment]
Ok. Thanks for clarification 

BR
