### ISSUE TITLE
Failed to compile rtpengine on centos 7

### ISSUE THREAD

**Issue by ccppprogrammer** [sipwise/rtpengine#1351]
Hello Richard!

I can't compile rtpengine on centos 7. With `with_transcoding 0` compilation works.
Probably related to #787.

<details>
  <summary>lsb_release</summary>

```
# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core
```
</details>
<details>
  <summary>git commit</summary>

```
# git log -1 --pretty="%H"
db53dd683a6613b6bba0041809b43e2df71b2def
```
</details>
<details>
  <summary>spandsp from epel</summary>

```
# rpm -q spandsp
spandsp-0.0.6-0.10.pre21.el7.x86_64
# rpm -q spandsp-devel
spandsp-devel-0.0.6-0.10.pre21.el7.x86_64
```
</details>
<details>
  <summary>error</summary>
  
```
/bin/sh: exec_prefix: command not found
In file included from dtmf_rx_fillin-test.c:1:0:
dtmf_rx_fillin.h:12:13: error: conflicting types for ‘dtmf_rx_fillin’
 INLINE void dtmf_rx_fillin(dtmf_rx_state_t *dsp, int n) {
             ^
In file included from dtmf_rx_fillin.h:9:0,
                 from dtmf_rx_fillin-test.c:1:
/usr/local/include/spandsp/dtmf.h:185:19: note: previous declaration of ‘dtmf_rx_fillin’ was here
 SPAN_DECLARE(int) dtmf_rx_fillin(dtmf_rx_state_t *s, int samples);
                   ^
make[2]: *** [dtmf_rx_fillin-test] Error 1
make[2]: Leaving directory `/usr/src/rtpengine/rtpengine-mr10.1.0.0+0~mr10.1.0.0/daemon'
Failed build with ../lib/dtmf_rx_fillin-02.h
make[1]: *** [dtmf_rx_fillin.h] Error 1
rm sdp.strhash.c control_ng.strhash.c call_interfaces.strhash.c
make[1]: Leaving directory `/usr/src/rtpengine/rtpengine-mr10.1.0.0+0~mr10.1.0.0/daemon'
make: *** [all] Error 2
```
</details>

**Comment by joshelson** [comment]
As a note, this issue still persists on CentOS 7 with the altest version.

```
media_player.o: In function `__media_player_free':
/usr/local/src/rtpengine/daemon/media_player.c:101: undefined reference to `av_packet_free'
media_player.o: In function `media_player_new':
/usr/local/src/rtpengine/daemon/media_player.c:128: undefined reference to `av_packet_alloc'
codeclib.o: In function `avc_decoder_init':
/usr/local/src/rtpengine/daemon/codeclib.c:598: undefined reference to `av_packet_alloc'
codeclib.o: In function `avc_decoder_close':
/usr/local/src/rtpengine/daemon/codeclib.c:730: undefined reference to `av_packet_free'
codeclib.o: In function `encoder_new':
/usr/local/src/rtpengine/daemon/codeclib.c:1242: undefined reference to `av_packet_alloc'
codeclib.o: In function `encoder_free':
/usr/local/src/rtpengine/daemon/codeclib.c:1384: undefined reference to `av_packet_free'
collect2: error: ld returned 1 exit status
```

**Comment by vadimd333** [comment]
Hello! I also have this problem. What do I need to fix this?

**Comment by vadimd333** [comment]
O...! Update the ffmpeg ( ... devel, libs) to the latest version helped me to fix this.

**Comment by rfuchs** [comment]
Closing this as it's obviously fixable and we don't want to perpetually support ancient library versions

**Comment by August1023** [comment]
> O...! Update the ffmpeg ( ... devel, libs) to the latest version helped me to fix this.


I have updated the ffmpeg library, but make still reports an error...


[ root@localhost daemon]# yum -y install ffmpeg ffmpeg-devel

Loaded plug-ins: fastestmirror, langpacks

Loading mirror speeds from cached hostfile

* base: mirrors.aliyun.com

* epel: hkg.mirror.rackspace.com

* extras: mirrors.aliyun.com

* nux-dextop: li.nux.ro

* rpmfusion-free-updates: mirrors.ustc.edu.cn

* updates: mirrors.ustc.edu.cn

Software package: ffmpeg-3.4.11-1.el7.x86_ 64 is installed and is the latest version

Software package: ffmpeg-devel-3.4.11-1.el7.x86_ 64 is installed and is the latest version

No treatment is required

[ root@localhost daemon]#




/bin/sh: exec_ Prefix: command not found

In file included from dtmf_ rx_ fillin-test.c:1:0:

dtmf_ rx_ fillin. h: 12:13: error: with 'DTMF_ rx_ Filling 'type conflict

INLINE void dtmf_ rx_ fillin(dtmf_rx_state_t *dsp, int n) {

^

In file included from dtmf_ rx_ fillin.h:9:0,

from dtmf_ rx_ fillin-test.c:1:

/usr/local/include/spandsp/dtmf. h: 179:19: Note: 'DTMF_ rx_ The last statement of fillin 'is here

SPAN_ DECLARE(int) dtmf_ rx_ fillin(dtmf_rx_state_t *s, int samples);

^

Make [2]: * * * [dtmf_rx_fill test] error 1

Make [2]: leave the directory "/ usr / local / SRC / rtpengine / daemon"

Failed build with ../lib/dtmf_ rx_ fillin-02.h

Make [1]: * * * [dtmf_rx_fill. H] error 1

Make [1]: leave the directory "/ usr / local / SRC / rtpengine / daemon"

Make: * * * [all] error 2

**Comment by August1023** [comment]
@ccppprogrammer Hello, has this problem been solved?
