### ISSUE TITLE
Curious about RTPEngine support for WebRTC SDP bundles

### ISSUE THREAD

**Issue by pwatson-ott** [sipwise/rtpengine#1355]
I am using RTPEngine to forward audio packets from my media server to a long term recorder (via SIPREC). I use WebRTC to connect RTPEngine to my media server and plain RTP connection to the LTR. 
             
                                 LTR -----   RTPEngine -------- media server

My media server supports only bundled SDP for WebRTC connections so is expecting all bundled media tracks (m= lines) to use the same “5 tuple”, meaning from the same IP and port, to the same IP and port, and over the same transport protocol.

The initial SDP offer from my media server contains only a single bundled track (m= line) and this is correctly processed by RTPEngine (creates a new call, allocates a port for the track, and negotiates ICE + DTLS with my media server). The resulting answer SDP from RTPEngine is missing the a=group:BUNDLE line but I am able to manually add that prior to sending it to my media server. Audio packets are received from my media server and forwarded to the LTR. Everything works fine to this point.

When another participant joins the call, my media server sends a new offer adding another bundled track for the new participant (same call). From what I can tell, RTPEngine creates a new port for the track. The resulting answer SDP from RTPEngine does not use the same 5 tuple so no audio packets are received for the track. I have tried manually manipulating the answer SDP from RTPEngine to force the same 5 tuple for each track without success. No audio packets are received for this track.

So I would like to know what support RTPEngine has for WebRTC SDP bundles?

I have included a short log file which gives the offer and answer processing.
I have also included a long log file with everything at log level=7.

[long.log](https://github.com/sipwise/rtpengine/files/7182718/long.log)
[short.log](https://github.com/sipwise/rtpengine/files/7182719/short.log)

**Comment by rfuchs** [comment]
At this point we only support "un-bundling" which means we can receive bundled SDPs but we don't send them out. So all generated/rewritten SDPs are not bundled.

**Comment by pwatson-ott** [comment]
Thanks for your quick reply. I'm not overly concerned about receiving an answer SDP with the bundled syntax. I can manually made the modifications necessary to keep my media server happy. My real problem is trying to get the audio from the new track processed on the original RTPEngine port.

So just to clarify, in the second offer case when another participant joins the call, is RTPEngine expecting to receive the audio packets for this new track on the new port that it has allocated? Because the RTPEngine stats at the end of the call do not mention the SSRC for this new track at all. Is there some way for RTPEngine to support this new SSRC in the first port?

**Comment by rfuchs** [comment]
We don't do any SSRC (de)muxing (nor RTP payload type (de)muxing) which is largely why we don't support sending/generating bundled SDPs. Each media section is expected to have its own set of local ports. So this isn't going to work just by manipulating the SDP to make it look like it's bundled.

**Comment by pwatson-ott** [comment]
Ok thanks for your time. Is supporting WebRTC bundling on the roadmap for RTPEngine? If yes, any rough timeframe?

**Comment by rfuchs** [comment]
We've been focusing a lot more on WebRTC lately so it's quite possible that we'll add support for it at some point. I don't have a timeline though.
