### ISSUE TITLE
dtmf transcoding issue in reverse direction

### ISSUE THREAD

**Issue by thomas414** [sipwise/rtpengine#1359]
Hi,

rtpengine version:
9.5.1.0+0~mr9.5.1.0 git-mr9.5-451e11a6

we have a problem with dtmf transcoding in the following scenario:
A --inband--> rtpengine --transcoding to telephone-event--> C

The problem occurs with dtmf in the reverse direction:
C --dtmf key over telephone-event--> rtpengine --no dtmf tone in audio stream--> A

The signalling in the SIP messages looks correct to me, so in theory it should work, so maybe we are just using a wrong parameter at the wrong place. I will send you the rtpengine logs and sip trace for two calls via email, maybe you can look over them?

Thanks in advance
Thomas

**Comment by rfuchs** [comment]
The first thing you can do is try the current master branch (or from the mr10.x builds) and see if that makes a difference.

The other thing is that phe pcap shows the ingress DTMF event packets interleaved with PCM audio packets, both running alongside each other with overlapping timestamps. This is a bit non standard and I'm not sure if this will work. The usual way is to have the DTMF event packets replace the respective audio packets.

**Comment by thomas414** [comment]
Update to mr10.x seems to have fixed the issue!
