### ISSUE TITLE
rtpengine modified a=mid in SDP in some cases where the callee sends re-invite, creating problem

### ISSUE THREAD

**Issue by jonathan415** [sipwise/rtpengine#1361]
I am running sip.js as clients with a  proxy with rtpengine in between.

1. In some cases, depending on the specific networking environments, when the callee starts the re-negotiation 
by contacting the caller, the a=mid:1 gets removed from the SDP by rtpengine, and causes the client re-negotiation to break.

2. When caller starts the renegotiation to the callee, the a=mid:0 and a=mid:1, gets passed okay in the SDP signaling.
   The a=mids does not get modified, and so the client renegotiation always work when made from the caller side
    under all networking envirornments.
 
3. In other cases, depending on the specific networking environments, the callee is able to start the re-negotiation by 
contacting the caller, and the a=mid:1 does not get removed. The SDP does not get modify by rtpegine,
and the renegotiation works.

> rtpengine --version
Version: 9.4.0.0+0~mr9.4.0.0 git-master-def813cf

I have attached the  rtpengine level 7 log, and the SIP signaling from the proxy's point of view. 
This debug is when the callee tries to renegotiate with the caller and fails because a=mid:1 was removed in SDP.

[rtp-engine-removing-renegotiation-mids-one-way-not-working.txt](https://github.com/sipwise/rtpengine/files/7230443/rtp-engine-removing-renegotiation-mids-one-way-not-working.txt)

Here is another attachment showing other cases to compare. This is a single phone call, in which the caller renegotiation succeeds to callee,  but when the callee renegotiation to caller, the attempt fails because the a=mid:1 is removed from the SDP.

[rtp-engine-removing-renegotiation-mids-one-way-working-other-way-not-working.txt](https://github.com/sipwise/rtpengine/files/7230454/rtp-engine-removing-renegotiation-mids-one-way-working-other-way-not-working.txt)

Update, I just installed the newest version, and the problem still exists:  > rtpengine --version
Version: 10.0.1.4+0~mr10.0.1.4

**Comment by rfuchs** [comment]
I'm guessing this is affecting media sections (`m=` lines) that have been rejected/removed during the re-invite negotiation (zero port in the `m=` line)? Removed media sections are not supposed to require any `a=` attributes at all, but I guess `a=mid` might be an exception to that rule (even though the RFC doesn't seem to say that).

**Comment by jonathan415** [comment]
Hello Richard,

Thanks for the explanation. That makes sense.

I will test the new updates and let you know.

Jonathan
