### ISSUE TITLE
renegotiation no longer removes a=mid:1, but removes remaining details associated with the a=mid:1

### ISSUE THREAD

**Issue by jonathan415** [sipwise/rtpengine#1362]
Regarding a fix to a previous issue with a=mid:1 being removed on renegotiation from callee:

https://github.com/sipwise/rtpengine/issues/1361

The a=mid:1 is retained now. But it truncates all the remaining 

### the recent fix added this back only
a=mid:1
#### But these other necessary details associated with mid:1 are removed by rtpengine
a=msid:- {3b84e0ae-b5e2-4360-a6ca-b2bcdfa42100}
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 ccm fir
a=rtcp-fb:120 goog-remb
a=rtcp-fb:120 transport-cc
a=rtcp-fb:121 nack
a=rtcp-fb:121 nack pli
a=rtcp-fb:121 ccm fir
a=rtcp-fb:121 goog-remb
a=rtcp-fb:121 transport-cc
a=rtcp-fb:126 nack
a=rtcp-fb:126 nack pli
a=rtcp-fb:126 ccm fir
a=rtcp-fb:126 goog-remb
a=rtcp-fb:126 transport-cc
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 goog-remb
a=rtcp-fb:97 transport-cc
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:120 VP8/90000
a=rtpmap:124 rtx/90000
a=rtpmap:121 VP9/90000
a=rtpmap:125 rtx/90000
a=rtpmap:126 H264/90000
a=rtpmap:127 rtx/90000
a=rtpmap:97 H264/90000
a=rtpmap:98 rtx/90000
a=setup:actpass
a=ssrc:2003291603 cname:{8e5c22e9-9271-4d10-ad60-d86c154a2c1e} 

Attached is the SIP signaling showing what comes into rtpengine, and what comes out afterwards.

[a-mid-1-fixed-but-removes-remaining-details-regarding-stream.txt](https://github.com/sipwise/rtpengine/files/7239791/a-mid-1-fixed-but-removes-remaining-details-regarding-stream.txt)

**Comment by rfuchs** [comment]
Yes that is expected. Removed/rejected media sections may omit all attributes as per RFC 3264.

**Comment by jonathan415** [comment]
> Yes that is expected. Removed/rejected media sections may omit all attributes as per RFC 3264.

But we are adding a new stream, not removing one. I can show you a working signaling where this case actually worked in some environment.

Here is a working case from callee renegotiating to caller, and adding a new stream.

1.1.1.1 (caller client) <----> Proxy (2.2.2.2) <---> 3.3.3.3(callee client)

2.2.2.2 is the proxy.   3.3.3 is the callee and 1.1.1.1 caller of a re-invite.


--------- in INVITE - From: wss:3.3.3.3:50140 To: wss:2.2.2.2:443 ------
INVITE sip:106@fe18opn9f11f.invalid;transport=ws;ob;alias=1.1.1.1~60104~6 SIP/2.0
Route: <sip:wZ6ktc823tJdHAZnxPldAbsvtc8f6sg=@2.2.2.2:443;transport=ws;r2=on;lr;did=18a.f3e1;nat=yes;xp=on;rtp=ws>
Route: <sip:wZ6ktc823tJdHAZnxPldAbsvtc8f6sg=@2.2.2.2:443;transport=ws;r2=on;lr;did=18a.f3e1;nat=yes;xp=on;rtp=ws>
Via: SIP/2.0/WSS dp2el4tvsouo.invalid;branch=z9hG4bK6517954
To: <sip:106@testsystem.example-domain.com>;tag=2vp9shujnb
From: <sip:115@testsystem.example-domain.com>;tag=0nu0gr1vku
CSeq: 1 INVITE
Call-ID: b8pnjqi9olcgcmqj7hdj
Max-Forwards: 69
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,REGISTER,SUBSCRIBE
Contact: <sip:115@dp2el4tvsouo.invalid;transport=ws>
Supported: outbound
User-Agent: MWWRTC 8.0
Content-Type: application/sdp
Content-Length: 7469

v=0
o=- 6086290613742468837 3 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 121 127 120 125 107 108 109 35 36 124 119 123
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:2918004515 1 udp 2113937151 47cb8ec9-94c4-459b-bb54-9316dfbb631f.local 59611 typ host generation 0 network-cost 999
a=candidate:2113222615 1 udp 2113939711 f58d4e0a-2892-414d-8c1f-072bf6b06e81.local 51707 typ host generation 0 network-cost 999
a=ice-ufrag:+dod
a=ice-pwd:+keBPujHH4wBpEXm51GJF9nF
a=ice-options:trickle
a=fingerprint:sha-256 ED:37:3C:39:EB:37:A9:8A:82:B9:B4:85:3C:12:D2:CB:73:BB:CA:EA:96:41:8D:C0:C0:8D:7F:E2:9C:A9:9E:84
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 urn:3gpp:video-orientation
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:- e3162b2c-5953-4cfb-b33a-e84a7a7b89b0
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:120 rtx/90000
a=fmtp:120 apt=127
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:35 AV1X/90000
a=rtcp-fb:35 goog-remb
a=rtcp-fb:35 transport-cc
a=rtcp-fb:35 ccm fir
a=rtcp-fb:35 nack
a=rtcp-fb:35 nack pli
a=rtpmap:36 rtx/90000
a=fmtp:36 apt=35
a=rtpmap:124 red/90000
a=rtpmap:119 rtx/90000
a=fmtp:119 apt=124
a=rtpmap:123 ulpfec/90000
a=ssrc-group:FID 2673867129 3086699305
a=ssrc:2673867129 cname:TWmHQF0WoRgHqWzf
a=ssrc:2673867129 msid:- e3162b2c-5953-4cfb-b33a-e84a7a7b89b0
a=ssrc:2673867129 mslabel:-
a=ssrc:2673867129 label:e3162b2c-5953-4cfb-b33a-e84a7a7b89b0
a=ssrc:3086699305 cname:TWmHQF0WoRgHqWzf
a=ssrc:3086699305 msid:- e3162b2c-5953-4cfb-b33a-e84a7a7b89b0
a=ssrc:3086699305 mslabel:-
a=ssrc:3086699305 label:e3162b2c-5953-4cfb-b33a-e84a7a7b89b0
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 121 127 120 125 107 108 109 35 36 124 119 123
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:+dod
a=ice-pwd:+keBPujHH4wBpEXm51GJF9nF
a=ice-options:trickle
a=fingerprint:sha-256 ED:37:3C:39:EB:37:A9:8A:82:B9:B4:85:3C:12:D2:CB:73:BB:CA:EA:96:41:8D:C0:C0:8D:7F:E2:9C:A9:9E:84
a=setup:actpass
a=mid:1
a=extmap:1 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 urn:3gpp:video-orientation
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:- d33359b2-5fa8-41f9-8538-f0c76d5e0a77
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:120 rtx/90000
a=fmtp:120 apt=127
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:35 AV1X/90000
a=rtcp-fb:35 goog-remb
a=rtcp-fb:35 transport-cc
a=rtcp-fb:35 ccm fir
a=rtcp-fb:35 nack
a=rtcp-fb:35 nack pli
a=rtpmap:36 rtx/90000
a=fmtp:36 apt=35
a=rtpmap:124 red/90000
a=rtpmap:119 rtx/90000
a=fmtp:119 apt=124
a=rtpmap:123 ulpfec/90000
a=ssrc-group:FID 1254327421 3044406319
a=ssrc:1254327421 cname:TWmHQF0WoRgHqWzf
a=ssrc:1254327421 msid:- d33359b2-5fa8-41f9-8538-f0c76d5e0a77
a=ssrc:1254327421 mslabel:-
a=ssrc:1254327421 label:d33359b2-5fa8-41f9-8538-f0c76d5e0a77
a=ssrc:3044406319 cname:TWmHQF0WoRgHqWzf
a=ssrc:3044406319 msid:- d33359b2-5fa8-41f9-8538-f0c76d5e0a77
a=ssrc:3044406319 mslabel:-
a=ssrc:3044406319 label:d33359b2-5fa8-41f9-8538-f0c76d5e0a77


--------- out INVITE - From: tls:2.2.2.2:443 To: tls:1.1.1.1:60104 ------
INVITE sip:106@fe18opn9f11f.invalid;transport=ws;ob;alias=1.1.1.1~60104~6 SIP/2.0
Via: SIP/2.0/WSS 2.2.2.2:443;branch=z9hG4bK8bad.665657d4c778c5d80d3acf9a9b3ec1b1.0
Via: SIP/2.0/WSS dp2el4tvsouo.invalid;rport=50140;received=3.3.3.3;branch=z9hG4bK6517954
To: <sip:106@testsystem.example-domain.com>;tag=2vp9shujnb
From: <sip:115@testsystem.example-domain.com>;tag=0nu0gr1vku
CSeq: 1 INVITE
Call-ID: b8pnjqi9olcgcmqj7hdj
Max-Forwards: 69
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,REGISTER,SUBSCRIBE
Contact: <sip:115@dp2el4tvsouo.invalid;transport=ws;alias=3.3.3.3~50140~6>
Supported: outbound
User-Agent: MWWRTC 8.0
Content-Type: application/sdp
Content-Length: 7739

v=0
o=- 6086290613742468837 3 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 121 127 120 125 107 108 109 35 36 124 119 123
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:2918004515 1 udp 2113937151 47cb8ec9-94c4-459b-bb54-9316dfbb631f.local 59611 typ host generation 0 network-cost 999
a=candidate:2113222615 1 udp 2113939711 f58d4e0a-2892-414d-8c1f-072bf6b06e81.local 51707 typ host generation 0 network-cost 999
a=ice-ufrag:+dod
a=ice-pwd:+keBPujHH4wBpEXm51GJF9nF
a=ice-options:trickle
a=fingerprint:sha-256 ED:37:3C:39:EB:37:A9:8A:82:B9:B4:85:3C:12:D2:CB:73:BB:CA:EA:96:41:8D:C0:C0:8D:7F:E2:9C:A9:9E:84
a=setup:actpass
a=extmap:1 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 urn:3gpp:video-orientation
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:- e3162b2c-5953-4cfb-b33a-e84a7a7b89b0
a=rtcp-mux
a=rtcp-rsize
a=ssrc-group:FID 2673867129 3086699305
a=ssrc:2673867129 cname:TWmHQF0WoRgHqWzf
a=ssrc:2673867129 msid:- e3162b2c-5953-4cfb-b33a-e84a7a7b89b0
a=ssrc:2673867129 mslabel:-
a=ssrc:2673867129 label:e3162b2c-5953-4cfb-b33a-e84a7a7b89b0
a=ssrc:3086699305 cname:TWmHQF0WoRgHqWzf
a=ssrc:3086699305 msid:- e3162b2c-5953-4cfb-b33a-e84a7a7b89b0
a=ssrc:3086699305 mslabel:-
a=ssrc:3086699305 label:e3162b2c-5953-4cfb-b33a-e84a7a7b89b0
a=mid:0
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=fmtp:98 profile-id=0
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=fmtp:100 profile-id=2
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:102 H264/90000
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=102
a=rtpmap:127 H264/90000
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=rtpmap:120 rtx/90000
a=fmtp:120 apt=127
a=rtpmap:125 H264/90000
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:108 H264/90000
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:35 AV1X/90000
a=rtcp-fb:35 goog-remb
a=rtcp-fb:35 transport-cc
a=rtcp-fb:35 ccm fir
a=rtcp-fb:35 nack
a=rtcp-fb:35 nack pli
a=rtpmap:36 rtx/90000
a=fmtp:36 apt=35
a=rtpmap:124 red/90000
a=rtpmap:119 rtx/90000
a=fmtp:119 apt=124
a=rtpmap:123 ulpfec/90000
a=rtcp:11902
a=rtcp-mux
a=candidate:mvFQrVLuJq807VTR 1 UDP 16777215 2.2.2.2 11902 typ relay raddr 2.2.2.2 rport 11902
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 121 127 120 125 107 108 109 35 36 124 119 123
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:+dod
a=ice-pwd:+keBPujHH4wBpEXm51GJF9nF
a=ice-options:trickle
a=fingerprint:sha-256 ED:37:3C:39:EB:37:A9:8A:82:B9:B4:85:3C:12:D2:CB:73:BB:CA:EA:96:41:8D:C0:C0:8D:7F:E2:9C:A9:9E:84
a=setup:actpass
a=extmap:1 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 urn:3gpp:video-orientation
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:- d33359b2-5fa8-41f9-8538-f0c76d5e0a77
a=rtcp-mux
a=rtcp-rsize
a=ssrc-group:FID 1254327421 3044406319
a=ssrc:1254327421 cname:TWmHQF0WoRgHqWzf
a=ssrc:1254327421 msid:- d33359b2-5fa8-41f9-8538-f0c76d5e0a77
a=ssrc:1254327421 mslabel:-
a=ssrc:1254327421 label:d33359b2-5fa8-41f9-8538-f0c76d5e0a77
a=ssrc:3044406319 cname:TWmHQF0WoRgHqWzf
a=ssrc:3044406319 msid:- d33359b2-5fa8-41f9-8538-f0c76d5e0a77
a=ssrc:3044406319 mslabel:-
a=ssrc:3044406319 label:d33359b2-5fa8-41f9-8538-f0c76d5e0a77
a=mid:1
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=fmtp:98 profile-id=0
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=fmtp:100 profile-id=2
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:102 H264/90000
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=102
a=rtpmap:127 H264/90000
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=rtpmap:120 rtx/90000
a=fmtp:120 apt=127
a=rtpmap:125 H264/90000
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:108 H264/90000
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:35 AV1X/90000
a=rtcp-fb:35 goog-remb
a=rtcp-fb:35 transport-cc
a=rtcp-fb:35 ccm fir
a=rtcp-fb:35 nack
a=rtcp-fb:35 nack pli
a=rtpmap:36 rtx/90000
a=fmtp:36 apt=35
a=rtpmap:124 red/90000
a=rtpmap:119 rtx/90000
a=fmtp:119 apt=124
a=rtpmap:123 ulpfec/90000
a=rtcp:11912
a=rtcp-mux
a=candidate:mvFQrVLuJq807VTR 1 UDP 16777215 2.2.2.2 11912 typ relay raddr 2.2.2.2 rport 11912

**Comment by rfuchs** [comment]
> But we are adding a new stream, not removing one. I can show you a working signaling where this case actually worked in some environment.

You're not adding a stream. The media section in question has a zero port, and zero port indicates a rejected or removed media section. Removed media sections are not required to have any attributes listed.

`m=video 0 UDP/TLS/RTP/SAVPF 120 124 121 125 126 127 97 98`

The working example you posted is using the trickle ICE address (zero address and port 9) which is valid.

**Comment by rfuchs** [comment]
https://datatracker.ietf.org/doc/html/rfc3264#section-8.2

```
8.2 Removing a Media Stream

   Existing media streams are removed by creating a new SDP with the
   port number for that stream set to zero.  The stream description MAY
   omit all attributes present previously, and MAY list just a single
   media format.

   A stream that is offered with a port of zero MUST be marked with port
   zero in the answer.  Like the offer, the answer MAY omit all
   attributes present previously, and MAY list just a single media
   format from amongst those in the offer.
```

**Comment by jonathan415** [comment]
> > But we are adding a new stream, not removing one. I can show you a working signaling where this case actually worked in some environment.
> 
> You're not adding a stream. The media section in question has a zero port, and zero port indicates a rejected or removed media section. Removed media sections are not required to have any attributes listed.
> 
> `m=video 0 UDP/TLS/RTP/SAVPF 120 124 121 125 126 127 97 98`
> 
> The working example you posted is using the trickle ICE address (zero address and port 9) which is valid.

You are so correct. I am amazed how smart you guys are. Thank you for explaining it to me.
