### ISSUE TITLE
Anomalous CPU and networking load on rtpengine restart

### ISSUE THREAD

**Issue by agrigorjevs** [sipwise/rtpengine#1363]
Hello,

I have come upon an issue when restarting rtpengine - if there are active calls going on, and rtpengine IS configured to use Redis - service restart causes to use a lot of CPU and starts to generate huge traffic towards all the call parties.

If connection to Redis is not configured - everything is fine upon restart.

There are no errors in rtpengine log, debug also doesn't give any clue.

rtpengine is contained within docker, in user-space mode, and is managed using systemd. Please see used rtpengine config below (IP's substituted).

[rtpengine]
interface=priv1/10.1.1.5;pub1/5.205.20.244
foreground=true
log-stderr=true
listen-ng=10.1.1.5:22222
port-min=23000
port-max=32768
log-level=6
delete-delay=0

In kamailio config I'm using rtpengine_manage everywhere with these kinds of params - "replace-origin replace-session-connection trust-address direction=pub1 direction=priv1 label=A-leg generate-RTCP=on"

Tried calling rtpengine_manage with "loop protect" option, but it didn't help.

Tried branches mr9.4, mr9.5, mr10.0 - the issue is present on all of them.

**Comment by agrigorjevs** [comment]
It seems like the problem is with enabling RTCP generation from rtpengine side - tests with it turned off show that the issue is not present.

Also I have taken tcpdump with generate-RTCP on, and I see that rtpengine starts to spam with RTCP packets, which seems to be the root cause of high networking bandwitdh use.

**Comment by rfuchs** [comment]
I haven't dug into this but on a hunch I added commit fd06430 (in a separate branch for now). See if this fixes the problem for you.

**Comment by agrigorjevs** [comment]
@rfuchs just tested - seems like it fixes the issue indeed!
