### ISSUE TITLE
segfault __re_address_translate_ep at media_socket.c

### ISSUE THREAD

**Issue by thomas414** [sipwise/rtpengine#1365]
Hi,

some hours ago there was a segfault at one of our rtpengine machines, backtrace is attached.
rtpengine version is: 10.0.1.0+0~mr10.0.1.0 git-mr10.0-8e27e3a5

[gdb.txt](https://github.com/sipwise/rtpengine/files/7267069/gdb.txt)

**Comment by rfuchs** [comment]
Probably already fixed in #1358 / 01b22eec7

Update your code.

**Comment by thomas414** [comment]
Thank you, we will update with the next release!
