### ISSUE TITLE
generate-RTCP question

### ISSUE THREAD

**Issue by mkezys** [sipwise/rtpengine#1368]
Hello,

RTPEngine wiki states: "received RTCP packets will not simply be passed through as usual, but instead will be consumed". 

Does it mean the call with the flag 'generate-RTCP' will not be kernelized?

All the best,
MK

**Comment by rfuchs** [comment]
The RTP streams will still be handled by the kernel module. RTCP is never handled by the kernel (even without local RTCP generation) so there really isn't any difference in this regard.

**Comment by mkezys** [comment]
Thank you.
