### ISSUE TITLE
subscribe to DTMF only

### ISSUE THREAD

**Issue by davehorton** [sipwise/rtpengine#1369]
I notice the new 'subscribe request' feature, which looks very interesting.  I have a use case where I need to detect DTMF events as they are passed through.  It looks like using the 'subscribe request' I could subscribe the entire audio stream and just pluck out the dtmf events that I want while ingoring/dropping other media, but just checking to see if there was any simpler method of being alerted by rtpengine of dtmf events received on a participant leg?

**Comment by rfuchs** [comment]
You're probably looking for the various DTMF logging options that we already have. Check the man page or pod file.

**Comment by davehorton** [comment]
perfect, thanks!
