### ISSUE TITLE
 No support for kernel packet forwarding available

### ISSUE THREAD

**Issue by albersag** [sipwise/rtpengine#137]
Hi

Im finding this error since but it was fine some days ago

 No support for kernel packet forwarding available (interface to kernel module not open)

root@kam02:/usr/src/tests# iptables -L -v
Chain INPUT (policy ACCEPT 51684 packets, 10M bytes)
 pkts bytes target     prot opt in     out     source               destination  
51684   10M rtpengine  all  --  any    any     anywhere             anywhere            

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 36722 packets, 7705K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain rtpengine (1 references)
 pkts bytes target     prot opt in     out     source               destination  
49998   10M RTPENGINE  udp  --  any    any     anywhere             anywhere             RTPENGINE id:0
root@kam02:/usr/src/tests# 

Any idea that could be wrong? Or what i missed?

**Comment by rfuchs** [comment]
Maybe the module wasn't loaded when the daemon was started? You should see an error messages in the logs just after the daemon was started that should explain it.
