### ISSUE TITLE
Non-compound PLI treated as invalid packet type.

### ISSUE THREAD

**Issue by cahlbin** [sipwise/rtpengine#138]
I'm sending a non-compound PLI message and I get:

```
Error parsing RTCP header: invalid packet type
```

The channel is setup so that rtpengine does RTP -> SRTP in the direction this RTCP packet is sent.

I briefly looked at the source in rtcp.c and noticed this:

```
static int rtcp_payload(struct rtcp_packet **out, str *p, const str *s) {
  ...

  if (rtcp->header.pt != RTCP_PT_SR
            && rtcp->header.pt != RTCP_PT_RR)
  goto error;
```

```
int rtcp_avp2savp(str *s, struct crypto_context *c) {
...
if (rtcp_payload(&rtcp, &payload, s))
  return -1;
```

In the case of a non-compound PLI, the PT will be RTCP_PT_PSFB, and it will essentially not be any payload. The RTP packet will just be the header, and length 12.

**Comment by rfuchs** [comment]
I wasn't aware that it was legal to send FB messages without SR or RR. Can you point out the section in the RFC which describe this?

**Comment by cahlbin** [comment]
It would be this draft then https://tools.ietf.org/html/draft-ietf-rtcweb-rtp-usage-25#section-4.6

**Comment by rfuchs** [comment]
Try with 51a6b57 applied

Entirely untested from my side :)

**Comment by rfuchs** [comment]
Any update here?

**Comment by rfuchs** [comment]
Cleaning up old tickets
