### ISSUE TITLE
RTP payload doesn't change after codec renegotiation

### ISSUE THREAD

**Issue by rhondahollis** [sipwise/rtpengine#1382]
I have a scenario, only with Firefox, where a change from g722 to PCMU results in no audio getting to the called party (pstn). What I see in the pcap is that the rtp packets toward the called party (udp.dstport == 17814) are G722 throughout the life of the call. Whereas if I look at the other direction, the packets change from G722 to PCMU after the reInvite with the codec change. This same call flow with Chrome also shows the change in the RTP packets in both directions.

After the codec change, I also start to see rtpengine logs noting that the payload type referenced in the Receiver Report cannot be identified. I've looked at the Receiver Reports, and the referenced streams are all valid, but I'm definitely missing something here. Can you help me understand what is happening at the rtpengine level in this call flow that is resulting in the one way audio?

You're assistance is greatly appreciated!

In the rtpengine log, the codec change occurs here:
Oct  4 12:12:21 drachtio-rtpengine01-dev-s03 rtpengine[56347]: DEBUG: [cckv57sa8tp9qkji40dv]: [control] Dump for 'offer

This is the first RR complaint:
Oct  4 12:12:22 drachtio-rtpengine01-dev-s03 rtpengine[56347]: DEBUG: [cckv57sa8tp9qkji40dv port 21556]: [rtcp] Calling handler for RTCP packet type 201
Oct  4 12:12:22 drachtio-rtpengine01-dev-s03 rtpengine[56347]: DEBUG: [cckv57sa8tp9qkji40dv port 21556]: [core] RR from 7ad49583 about d9a80833: FL 0 TL 0 HSR 1404 J 2 LSR 0 DLSR 0
Oct  4 12:12:22 drachtio-rtpengine01-dev-s03 rtpengine[56347]: DEBUG: [cckv57sa8tp9qkji40dv port 21556]: [core] No payload type known for RTCP RR, discarding
Oct  4 12:12:22 drachtio-rtpengine01-dev-s03 rtpengine[56347]: DEBUG: [cckv57sa8tp9qkji40dv port 21556]: [core] RR from 7ad49583 about e06b7f0c: FL 0 TL 0 HSR 60974 J 3 LSR 0 DLSR 0
Oct  4 12:12:22 drachtio-rtpengine01-dev-s03 rtpengine[56347]: DEBUG: [cckv57sa8tp9qkji40dv port 21556]: [core] No payload type known for RTCP RR, discarding

[FFOneWayAudio.zip](https://github.com/sipwise/rtpengine/files/7354927/FFOneWayAudio.zip)

**Comment by rfuchs** [comment]
There's nothing happening the rtpengine level that is causing this. It's not involved in the codec negotiation here, so you'll have to look at the browser to see what it's doing.

In particular the answer at `Oct  4 12:12:27` is problematic, as it looks like a duplicate/unsolicited answer (previous one was at `Oct  4 12:12:22`) with an incorrect codec list. The corresponding offer (immediately preceding the first answer) only offered PCMU, so the answer is supposed to only be able to list PCMU as well. The first answer does that, but then the second answer somehow also lists G.722, which wasn't offered during that exchange (as well as Opus and PCMA).
