### ISSUE TITLE
High CPU usage after upgrade from RTP engine 9.0.1.4 to 10.1.1.1

### ISSUE THREAD

**Issue by nomi1nomi1** [sipwise/rtpengine#1387]
Morning All,

We recently upgraded from RTP engine version 9 to 10 and CPU usage for multi-threaded RTP  Engine instances went from 10 per cent to 130%. This is without any call or load on the system(no users).  Single-threaded instance's CPU usage is the same pre and post-upgrade.
Can anyone shed some light on this, please?

![image](https://user-images.githubusercontent.com/92977437/138442484-858050aa-eb12-4417-a87d-a70f66ebb4d7.png)

**Comment by rfuchs** [comment]
Unless this turns out to be a problem with the code, this should be discussed on the new mailing list:  https://rtpengine.com/mailing-list
