### ISSUE TITLE
nub question, how to get the "mos" values on Kamailio.

### ISSUE THREAD

**Issue by antonio-couto** [sipwise/rtpengine#1392]
I am using SIP and I wish to log "mos" information and of course I am doing something wrong.
I am using rtpengine_manage() and the values of pseudo variables always are "null", even when I log after the function.

	if(nat_uac_test("8")) {
		rtpengine_manage("SIP-source-address replace-origin replace-session-connection");
                xlog("L_INFO","$avp(mos_min_jitter)\n");
	} else {
		rtpengine_manage("replace-origin replace-session-connection");
                xlog("L_INFO","$avp(mos_min_jitter)\n");
	}

Any help will be apreciated.
Thanks

**Comment by ahmedfayoub** [comment]
Hi,

I think you should check [947](https://github.com/sipwise/rtpengine/issues/947)

**Comment by rfuchs** [comment]
Have you set the modparam?

Note that the values are only available after a "delete"

Also note that they're filled only if RTCP is received from the peers, or local RTCP generation is enabled.

Closing this as we have a mailing list for these sorts of questions now: https://rtpengine.com/mailing-list
