### ISSUE TITLE
CPU Increase

### ISSUE THREAD

**Issue by john08burke** [sipwise/rtpengine#1394]
Hello, I am migrating from 7.0.0.1 running on debian 9 (I know... about time :smile:) to the newest version of rtpengine and noticed that CPU usage was ~2x from the previous version.  I did some troubleshooting and it seems to be related to the version of debian, not any specific commit / code revision.  Compiling the same source code against debian 9 results in 1/2 the CPU usage compared to the same source code compiled against debian 10/11.  This seems to be true regardless of rtpengine, as I ran some tests with the latest source code as well.

I compiled some data to illustrate some head-to-head testing.  The testing was done with the same scenario: ~10CPS/~700CC, no transcoding, PCMU, bare metal (same server).  From the data, it appears both kernel and user space reflect the CPU increase.

The iptables -> nftables migration from debian versions seems suspicious, especially given the fact that kernel space saw a 2X increase... which I was expecting to be relatively consistent.

Any ideas for further troubleshooting?

![image](https://user-images.githubusercontent.com/36895232/140374641-79b7d69a-1a3b-4643-bc05-f9ab958021b2.png)
![image](https://user-images.githubusercontent.com/36895232/140374663-ef9d2f27-ccd5-41be-855c-9c8b3072c559.png)
![image](https://user-images.githubusercontent.com/36895232/140374673-cdceeb29-75d4-4c05-9073-a19aaa6ffb22.png)

**Comment by rfuchs** [comment]
This has been asked before in #1387 and #1379

In particular I suggest looking at the kernel's CPU bug mitigation patches, as well as confirming that the kernel module does its job (inspect `/proc/rtpengine/0/list`)

Closing this as we now have a mailing list for these sorts of questions: https://rtpengine.com/mailing-list

**Comment by john08burke** [comment]
Thanks @rfuchs, I didn't know there was a mailing list!  Looking forward to subscribing.

I'll look into the mitigation patches, as I've already confirmed the module is working via `/proc/rtpengine/0/list`.
