### ISSUE TITLE
I can't write en a dedicated LOG file

### ISSUE THREAD

**Issue by voztovoice** [sipwise/rtpengine#1398]
Operating System: Rocky Linux 8.4
Rtpengine Version: Version: git-master-2c0e196b

Steps:
Rtpengine configuration: –-log-facility=local1

Rsyslog configuración: local1.*                                                /var/log/rtpengine.log

Then:
touch /var/log/rtpengine.log
systemctl restart rsyslog
systemctl restart rtpengine

rtpengine.log empty but rtpengine running.

Any hint to solve?

Thank you

**Comment by mkezys** [comment]
On Centos 7 it usually logs to /var/log/messages. If there is nothing, try to increase log level in rtpengine configuration -L 7

**Comment by voztovoice** [comment]
Hi, I know. On CentOS7 i can use a dedicated LOG file without problem but with Rocky Linux using the same configuration, I can't.
Is there a place where I can see to know where is the problem?
Regards

**Comment by mkezys** [comment]
If RTPEngine writes log to the /var/log/messages and you can't make it log to a dedicated log file, then this is a problem with the configuration or Rocky Linux, not RTPEngine.

**Comment by voztovoice** [comment]
Thank you. I write here only to know if someone has the same problem.
Regards
