### ISSUE TITLE
rtpengine-ctl list totals call duration stays 0

### ISSUE THREAD

**Issue by ricardas** [sipwise/rtpengine#1399]
Hello, when trying to retrieve totals in the latest revision (2c0e196be9f63c027b09b82884866843c3ed2e89), average call duration and total calls duration stays 0

/usr/src/rtpengine/utils/rtpengine-ctl -ip 127.0.0.1 -port 2223 list totals

Statistics over currently running sessions:

...

Total statistics (does not include current running sessions):

 Uptime of rtpengine                             :1113 seconds
 Total managed sessions                          :0
 Total rejected sessions                         :0
 Total timed-out sessions via TIMEOUT            :0
 Total timed-out sessions via SILENT_TIMEOUT     :0
 Total timed-out sessions via FINAL_TIMEOUT      :0
 Total timed-out sessions via OFFER_TIMEOUT      :0
 Total regular terminated sessions               :3
 Total forced terminated sessions                :0
 Total relayed packets (userspace)               :1161
 Total relayed packet errors (userspace)         :0
 Total relayed bytes (userspace)                 :196456
 Total relayed packets (kernel)                  :4491
 Total relayed packet errors (kernel)            :0
 Total relayed bytes (kernel)                    :772452
 Total relayed packets                           :5652
 Total relayed packet errors                     :0
 Total relayed bytes                             :968908
 Total number of streams with no relayed packets :3
 Total number of 1-way streams                   :0
 Average call duration                           :0.000000

Graphite interval statistics (last reported values to graphite):
 Total calls duration                            :0.000000

**Comment by rfuchs** [comment]
Post your config (in particular whether Graphite is enabled).

What was the behaviour previously?
