### ISSUE TITLE
Dealing with bodyless invites for 3pcc

### ISSUE THREAD

**Issue by soulofmischief87** [sipwise/rtpengine#140]
I am attempting to migrate from media proxy to rtpengine but I am facing an issue when attempting to initiate a 3pcc call that does not carry a body. I get an error in the opensips logs 
 ERROR:rtpengine:extract_body: failed to get the message body
 /sbin/opensips[10153]: ERROR:rtpengine:rtpe_function_call: can't extract body from the message.

and then 
ERROR:rtpengine:rtpe_function_call: proxy replied with error: Unknown call-id

in the on reply route. I am not sure how to deal with blank invites since 3pcc has a different flow as far as exchanging capabilities. As it is done in on reply 200 ok and then ack sdp in reply to the 200. Can someone provide guidance or tell me if it's even possible.

Thanks

**Comment by etamme** [comment]
Dont try to offer/answer if the request or response does not have a body.


In opensips you simply need to cover the different offer answer cases - i have a [wiki post](https://github.com/etamme/federated-sip/wiki/RTPEngine-offer-answer-in-opensips) i put together very quickly regarding offer/answer handling with opensips and rtpengine.

is it possibe? absolutely

**Comment by soulofmischief87** [comment]
etamme,

What model do you suggest I use. I am using the same model as your wiki the offer function should not be invoked because it relies on the Initial invite having a body. Would I have to engage rtpengine during the ack SDP? Do you suggest I use rtpengine_manage() refering to the 200 ok  from ? in this case during the on reply route ? Would a function have to be called during the ACK if is has an sdp body ? 


Thanks,
Tito

**Comment by soulofmischief87** [comment]
I changed the order of offer and answer based on the availability of an sdp. Thanks for your input
