### ISSUE TITLE
RTP Timeout per caller/callee stream

### ISSUE THREAD

**Issue by patrickarton** [sipwise/rtpengine#1402]
Hello,

with --timeout option in rtpengine we delete the call if all streams of the call ( caller and callee ) did not received any rtp packet within this amount of time. 

i looked in the code and did not see yet a way to enable --timeout only for one side stream.
For example even if caller streams are active (still sending packets) i want to close the call if callee streams are inactive ( did not received any packets within the --timeout option ).

Thanks.

**Comment by arnd-s** [comment]
Hello @patrickarton,

this is currently not possible as far as i know. I made for our internal use some patches against an older version which basically works. I will try to update the patches to the newest development version and create a PR in the next days.

I'll let you know...

Arnd

**Comment by patrickarton** [comment]
> Hello @patrickarton,
> 
> this is currently not possible as far as i know. I made for our internal use some patches against an older version which basically works. I will try to update the patches to the newest development version and create a PR in the next days.
> 
> I'll let you know...
> 
> Arnd

thanks for the reply.

i will be very glad to see that patch included.

i will  wait from your updates.

**Comment by arnd-s** [comment]
i created PR #1403.
It adds a  new timeout config option and interface parameter: timeout-mode
off == notimeout / any == timeout on a single stream / all == timeout on all streams (old behavior).

For best working: Start with timeout-mode=off (during early media) and when you receive a final answer (200 OK for example) activate timeout with timeout-mode=any.

If you enable it on start of call establishment you will get a timeout if early media is one-way only.

**Comment by patrickarton** [comment]
> i created PR #1403. It adds a new timeout config option and interface parameter: timeout-mode off == notimeout / any == timeout on a single stream / all == timeout on all streams (old behavior).
> 
> For best working: Start with timeout-mode=off (during early media) and when you receive a final answer (200 OK for example) activate timeout with timeout-mode=any.
> 
> If you enable it on start of call establishment you will get a timeout if early media is one-way only.

thank you very much. @arnd-s .

i will test it.

**Comment by rfuchs** [comment]
Closing this to continue discussion on #1403
