### ISSUE TITLE
Need some information regarding rtpengine . 

### ISSUE THREAD

**Issue by sasmita11** [sipwise/rtpengine#1410]
Hi All , 

Not raising any concern here . Just need to know what is the current stable version of rtpengine I should use right now .

**Comment by rfuchs** [comment]
Latest LTS is mr9.5, latest stable branch (released today) is mr10.2.

In the future direct questions like this to the mailing list: https://rtpengine.com/mailing-list

**Comment by sasmita11** [comment]
Thank u so much .
