### ISSUE TITLE
Call recording in combination with anycast

### ISSUE THREAD

**Issue by Shkiperon** [sipwise/rtpengine#1414]
Is it possible to configure call recording when  RTPEngine deployed on multiple servers with shared anycast IP address (sync of metadata configured via Redis notification mechanism)?
If I try turn on call recording on anycast interface when spool directory shared via GlusterFS then audio not passes proxy servers, but if call recording turned off - everything works fine. In man for rtpengine-recording for spool-dir option I found that this directory must support inotify mechanism, so the shared filesystem cannot help me in this scenario.

**Comment by rfuchs** [comment]
You should be able to use a local file system as spool directory and have each rtpengine instance generate the spool files locally. This isn't really a supported scenario but I think it should still work, assuming that only one rtpengine instance handles the media for any one call, and that the media isn't distributed among multiple instances.

Don't use GitHub issues for general questions. Use the mailing list: https://rtpengine.com/mailing-list
