### ISSUE TITLE
Potential deadlock due to cyclic lock acquisitions 

### ISSUE THREAD

**Issue by ryancaicse** [sipwise/rtpengine#1417]
Acquring Locks from `metafiles_lock` to `mf->lock`
https://github.com/sipwise/rtpengine/blob/d116b44cf20dc06646780fc58d17be39ca11c99b/recording-daemon/metafile.c#L202-L232

Acquring Locks from `mf->lock` to `metafiles_lock`
https://github.com/sipwise/rtpengine/blob/d116b44cf20dc06646780fc58d17be39ca11c99b/recording-daemon/metafile.c#L342-L357

**Comment by ryancaicse** [comment]
Also, I have a suggestion in the code: it is better to exchange the order between `pthread_mutex_lock(&ret->lock);` **(Line 174)**  and  `pthread_mutex_unlock(&mf->lock);` **(Line 175)** to acquire and release lock in order.
Otherwise,  it is easy to introduce cyclic lock acquisitions when the program acquires the lock `mf->lock` again in other places
https://github.com/sipwise/rtpengine/blob/c7085085a7d154608144db2a201d65547f23f520/recording-daemon/packet.c#L159-L175

**Comment by rfuchs** [comment]
> Acquring Locks from `metafiles_lock` to `mf->lock`
> 
> https://github.com/sipwise/rtpengine/blob/d116b44cf20dc06646780fc58d17be39ca11c99b/recording-daemon/metafile.c#L202-L232
> 
> Acquring Locks from `mf->lock` to `metafiles_lock`
> 
> https://github.com/sipwise/rtpengine/blob/d116b44cf20dc06646780fc58d17be39ca11c99b/recording-daemon/metafile.c#L342-L357

I don't think I'm seeing what you're seeing. Both code snippets acquire `metafiles_lock` first and `mf->lock` second, don't they?

**Comment by rfuchs** [comment]
> Also, I have a suggestion in the code: it is better to exchange the order between `pthread_mutex_lock(&ret->lock);` **(Line 174)** and `pthread_mutex_unlock(&mf->lock);` **(Line 175)** to acquire and release lock in order. Otherwise, it is easy to introduce cyclic lock acquisitions when the program acquires the lock `mf->lock` again in other places
> 
> https://github.com/sipwise/rtpengine/blob/c7085085a7d154608144db2a201d65547f23f520/recording-daemon/packet.c#L159-L175

Not quite seeing this one either. The lock order is supposed to be `metafile_t->lock` first and `ssrc_t->lock` (contained within `metafile_t`) second. It's not really possible to retrieve the `ssrc_t` that is contained within `metafile_t` without holding `metafile_t->lock`. The code just needs to make sure that it doesn't attempt to acquire any `metafile_t->lock` while holding a `ssrc_t->lock`.

**Comment by ryancaicse** [comment]
Sorry for my mistakes. Thank you for your checking.
