### ISSUE TITLE
Kernelizing works not as expected (Problem with a high CPU using )

### ISSUE THREAD

**Issue by kertor** [sipwise/rtpengine#1418]
Hello guys!

After updating from `7.0.0.0.20180928.3102357-1.el7` rtpengine to `10.0.0.0.20211202.ca0c6993-2.el8` i see, that now rtpengine use much more CPU resources.
I think root of the problem is that kernelize working as not as expected.

OS and kernel:
```
Oracle Linux Server release 8.4
4.18.0-305.19.1.el8_4.x86_64
```
rtpengine installed directly on server OS (without containers).
In statistics `list totals` i see:
```
 Total relayed packets (userspace)               :87778
 Total relayed packet errors (userspace)         :143
 Total relayed bytes (userspace)                 :15367272
 Total relayed packets (kernel)                  :4545
 Total relayed packet errors (kernel)            :0
 Total relayed bytes (kernel)                    :781740
 Total relayed packets                           :92323
 Total relayed packet errors                     :143
 Total relayed bytes                             :16149012
```

In stats i see that a biggest part of packets was not kernelized.
Module loaded:
```
# lsmod | grep -E 'xt_RTPENGINE|ip_tables|x_tables'
xt_RTPENGINE           57344  3
ip_tables              28672  0
```

iptables rules loaded:
```
-N SERVICES
-A INPUT -j SERVICES
-A SERVICES -p udp -m udp --dport 10000:60000 -j RTPENGINE --id 0
```

rtpengine conf have settings:
```
[rtpengine]
# start if kernel forwading available
table = 0
no-fallback = true
pidfile = /run/rtpengine.pid
```

Logs of the example of call:
[example-of-kernelized-call.txt](https://github.com/sipwise/rtpengine/files/7755427/example-of-kernelized-call.txt)
Also attached logs with example of call. In logs i see that RTP flows were kernelized, but in `kernel stats` (`list totals`) i see that after call was finished value `Total relayed packets (kernel)` was not changed. Also, after lines:
```
INFO: [core] Kernelizing media stream: 192.168.10.10:28892 -> 192.168.50.50:27572 | 77.77.77.77:27146 -> 88.88.88.88:4002
INFO: [core] Kernelizing media stream: 88.88.88.88:4002 -> 77.77.77.77:27146 | 192.168.50.50:27572 -> 192.168.10.10:28892
```
I still see in logs output of RTP stats:
```
Dec 21 14:21:54 srv232 rtpengine[3076807]: DEBUG: [kFv6KcNm1-1mja2c0j4stRxrwuhsLcgq port 27146]: [core] Forward to sink endpoint: 88.88.88.88:4002 (RTP seq 758 TS 3792959232)
Dec 21 14:21:54 srv232 rtpengine[3076807]: DEBUG: [kFv6KcNm1-1mja2c0j4stRxrwuhsLcgq port 27572]: [core] Forward to sink endpoint: 192.168.10.10:28892 (RTP seq 17849 TS 24960)
```
As far as i understand, if kernelizing was enabled, then rtpengine daemon can not see incoming RTP packets.
Also, attached call do not have transcoding and have simple scenario.

Let me summarise now:
1) Kernel module loaded, iptables rules present;
2) I see `Kernelizing media stream` in logs;
3) I see that only 1% percent of all processed packets gets into kernel stats;
4) I see that 99% of all processed packets gets into userspace stats;
5) We have simplest calls without SRTP and transcoding;
6) Problem happened after updating to new rtpengine version `10.0.0.0.20211202.ca0c6993-2.el8` from `7.0.0.0.20180928.3102357-1.el7`.

Could you please help me to understand, why kernelizing works not as expected?
Thank you.

**Comment by rfuchs** [comment]
Do you have any other iptables rules loaded? Check with `iptables -L -v -n` and also pay attention to the packet counters in the output.

Inspect `/proc/rtpengine/0/list` and watch the packet counters there. If they're not increasing then the kernel module isn't handling the packets.

Closing this is it's (probably) not a code issue. Take it to the mailing list: https://rtpengine.com/mailing-list

**Comment by kertor** [comment]
Thank you @rfuchs 
You was absolutely correct in this sentence:
> Do you have any other iptables rules loaded?

Was fixed, thank you.
