### ISSUE TITLE
Call Hold re-Invite Offer issue

### ISSUE THREAD

**Issue by hyavari** [sipwise/rtpengine#1419]
Hi to all,

I am not sure that I am doing the right way, but in a call that everything is OK, A party sends a re-invite to put the call on hold, when I send the offer with 'sendonly', again RTPEngine return 'sendrecv'. I used the 'original sendrecv' flag but did not help.

sample payload:

`payload":{"supports":["load limit"],"sdp":"v=0\r\no=Test-IMS-UE 30432555588 30432555589 IN IP6 X00Z:Y6b:f:125:0:3c:7fff:d801\r\ns=SS VOIP\r\nc=IN IP6 X00Z:Y6b:f:328:0:3c:7fff:d801\r\nt=0 0\r\nm=audio 1348 RTP/AVP 118 110\r\nb=AS:37\r\nb=RS:462\r\nb=RR:1387\r\na=rtpmap:118 AMR/8000/1\r\na=fmtp:118 mode-change-capability=2;max-red=220\r\na=rtpmap:110 telephone-event/8000\r\na=fmtp:110 0-15\r\na=maxptime:240\r\na=sendonly\r\n","ICE":"remove","direction":["ipv6_public","ipv4_private"],"flags":["loop protect","original sendrecv"],"replace":["origin","session-connection"],"transport-protocol":"RTP/AVP","call-id":"DBdFHvP7ijI27lw9bHCG6A..@X00Z:Y6b:f:328:0:3c:7fff:d801","received-from":["IP6","X00Z:Y6b:F:328:0:3D:7FFF:D801"],"from-tag":"8841e126","command":"offer","codec":{"transcode":["PCMU"]}}`

Any idea what is wrong?

**Comment by rfuchs** [comment]
You'll have to post a more detailed log than this. Post the full exchange taken from rtpengine's debug log. Also don't post it here since this a code issue tracker: post it to the mailing list: https://rtpengine.com/mailing-list
