### ISSUE TITLE
ng/udp control interface without ipv6?

### ISSUE THREAD

**Issue by itsroot** [sipwise/rtpengine#142]
Now this listeners not working with disabled ipv6. You will be fixed this issue or its no issue?)

**Comment by rfuchs** [comment]
If you listen only on a particular (IPv4) IP address, then it won't try to listen on IPv6.

**Comment by paulandrewhughes** [comment]
If the kernel module ipv6 is not loaded then you can get problem that sound like your issue.
strace shows error to be EAFNOSUPPORT.
strace ./rtpengine -f --interface 192.168.180.83 --listen-ng 192.168.180.83:5040
... snip ...
gettimeofday({1439429925, 543619}, NULL) = 0
epoll_create1(0)                        = 4
socket(PF_INET6, SOCK_DGRAM, IPPROTO_IP) = -1 EAFNOSUPPORT (Address family not supported by protocol)
write(2, "Failed to open UDP control conne"..., 42Failed to open UDP control connection port) = 42
write(2, "\n", 1
)                       = 1
gettimeofday({1439429925, 545160}, NULL) = 0
sendto(3, "<26>Aug 13 11:38:45 rtpengine[13"..., 80, MSG_NOSIGNAL, NULL, 0) = 80
exit_group(-1)                          = ?

Inserting kernel module allows rtpengine to work.
# insmod /lib/modules/2.6.32-504.1.3.el6.x86_64/kernel/net/ipv6/ipv6.ko

**Comment by cahlbin** [comment]
FYI I ran into a similar issue when running rtpengine on OS X, on which disabling IPV6_V6ONLY via setsockopt (https://github.com/sipwise/rtpengine/blob/master/daemon/udp_listener.c#L71) doesn't work if the bound address is not an "any-address", e.g. 0.0.0.0. (See https://github.com/cahlbin/rtpengine/commit/496522d1e94c5488a7f05a672db483d375ade0f8)

**Comment by rfuchs** [comment]
Just a heads-up here, the soon-to-be-master branch `rfuchs/socket-rework` changes socket handling to bind each socket to a specific interface/address and so avoids using AF_INET6 for every socket. This should largely eliminate issues with platforms not supporting IPv6.
