### ISSUE TITLE
Rtpengine segfault

### ISSUE THREAD

**Issue by jamesfranck** [sipwise/rtpengine#1422]
Hello all,

We faced again a new issue of segfault with rtpengine on Debian 10 : 
Version : 10.2.0.0+0~mr10.2.0.0

Backtrace : 
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/rtpengine...(no debugging symbols found)...done.
[New LWP 12341]
[New LWP 12311]
[New LWP 12314]
[New LWP 12317]
[New LWP 12315]
[New LWP 12328]
[New LWP 12332]
[New LWP 12312]
[New LWP 12313]
[New LWP 12309]
[New LWP 12381]
[New LWP 12383]
[New LWP 12382]
[New LWP 12376]
[New LWP 12370]
[New LWP 12379]
[New LWP 12337]
[New LWP 12373]
[New LWP 12408]
[New LWP 12369]
[New LWP 12391]
[New LWP 12384]
[New LWP 12367]
[New LWP 12396]
[New LWP 12388]
[New LWP 12387]
[New LWP 12385]
[New LWP 12375]
[New LWP 12394]
[New LWP 12378]
[New LWP 12473]
[New LWP 12399]
[New LWP 12372]
[New LWP 12331]
[New LWP 12361]
[New LWP 12371]
[New LWP 12355]
[New LWP 12316]
[New LWP 12310]
[New LWP 12389]
[New LWP 12374]
[New LWP 12513]
[New LWP 12392]
[New LWP 12358]
[New LWP 12443]
[New LWP 12483]
[New LWP 12485]
[New LWP 12503]
[New LWP 12461]
[New LWP 12325]
[New LWP 12398]
[New LWP 12327]
[New LWP 12329]
[New LWP 12402]
[New LWP 12496]
[New LWP 12509]
[New LWP 12415]
[New LWP 12441]
[New LWP 12423]
[New LWP 12507]
[New LWP 12488]
[New LWP 12508]
[New LWP 12410]
[New LWP 12356]
[New LWP 12414]
[New LWP 12413]
[New LWP 12451]
[New LWP 12454]
[New LWP 12416]
[New LWP 12429]
[New LWP 12504]
[New LWP 12478]
[New LWP 12456]
[New LWP 12436]
[New LWP 12475]
[New LWP 12354]
[New LWP 12439]
[New LWP 12466]
[New LWP 12510]
[New LWP 12505]
[New LWP 12424]
[New LWP 12449]
[New LWP 12440]
[New LWP 12490]
[New LWP 12458]
[New LWP 12324]
[New LWP 12318]
[New LWP 12511]
[New LWP 12345]
[New LWP 12431]
[New LWP 12411]
[New LWP 9903]
[New LWP 12338]
[New LWP 12364]
[New LWP 12347]
[New LWP 12319]
[New LWP 12409]
[New LWP 12459]
[New LWP 12495]
[New LWP 12407]
[New LWP 12455]
[New LWP 12468]
[New LWP 12362]
[New LWP 12430]
[New LWP 12493]
[New LWP 12469]
[New LWP 12421]
[New LWP 12340]
[New LWP 12343]
[New LWP 12420]
[New LWP 12432]
[New LWP 12437]
[New LWP 12435]
[New LWP 12465]
[New LWP 12502]
[New LWP 12481]
[New LWP 12444]
[New LWP 12471]
[New LWP 12349]
[New LWP 12393]
[New LWP 12498]
[New LWP 12366]
[New LWP 12489]
[New LWP 12464]
[New LWP 12491]
[New LWP 12499]
[New LWP 12474]
[New LWP 12501]
[New LWP 12497]
[New LWP 12326]
[New LWP 12477]
[New LWP 12359]
[New LWP 12346]
[New LWP 12434]
[New LWP 12500]
[New LWP 12336]
[New LWP 12334]
[New LWP 12348]
[New LWP 12335]
[New LWP 12323]
[New LWP 12330]
[New LWP 12350]
[New LWP 12506]
[New LWP 12322]
[New LWP 12333]
[New LWP 12447]
[New LWP 12467]
[New LWP 12351]
[New LWP 12494]
[New LWP 12422]
[New LWP 12452]
[New LWP 12417]
[New LWP 12492]
[New LWP 12442]
[New LWP 12403]
[New LWP 12484]
[New LWP 12390]
[New LWP 12453]
[New LWP 12446]
[New LWP 12428]
[New LWP 12406]
[New LWP 12400]
[New LWP 12397]
[New LWP 12482]
[New LWP 12427]
[New LWP 12457]
[New LWP 12395]
[New LWP 12460]
[New LWP 12486]
[New LWP 12476]
[New LWP 12401]
[New LWP 12463]
[New LWP 12365]
[New LWP 12450]
[New LWP 12353]
[New LWP 12339]
[New LWP 12368]
[New LWP 12320]
[New LWP 12321]
[New LWP 12352]
[New LWP 12360]
[New LWP 12342]
[New LWP 12512]
[New LWP 12405]
[New LWP 12470]
[New LWP 12479]
[New LWP 12380]
[New LWP 12377]
[New LWP 12433]
[New LWP 12438]
[New LWP 12419]
[New LWP 12426]
[New LWP 12412]
[New LWP 12462]
[New LWP 12445]
[New LWP 12386]
[New LWP 12448]
[New LWP 12480]
[New LWP 12487]
[New LWP 12472]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/rtpengine -f --no-log-timestamps --pidfile /run/ngcp-rtpengine-daemon'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000056046349dcbf in ?? ()
[Current thread is 1 (Thread 0x7fa9473f9700 (LWP 12341))]

Could you please help us troubleshooting this issue ?

Thanks in advance.

**Comment by rfuchs** [comment]
Same as always: Install -dbgsym packages, post full backtrace, post exact version (`10.2.0.0` is not a tagged version)

**Comment by jamesfranck** [comment]
Hello,
Here is the exact version compiled : 
Version: 10.2.0.0+0~mr10.2.0.0

I've installed dbgsym and here is the backtrace : 
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/rtpengine...Reading symbols from /usr/lib/debug/.build-id/d9/bb87603b336d18f63255415feafa6afa4fafa7.debug...done.
done.
[New LWP 12341]
[New LWP 12311]
[New LWP 12314]
[New LWP 12317]
[New LWP 12315]
[New LWP 12328]
[New LWP 12332]
[New LWP 12312]
[New LWP 12313]
[New LWP 12309]
[New LWP 12381]
[New LWP 12383]
[New LWP 12382]
[New LWP 12376]
[New LWP 12370]
[New LWP 12379]
[New LWP 12337]
[New LWP 12373]
[New LWP 12408]
[New LWP 12369]
[New LWP 12391]
[New LWP 12384]
[New LWP 12367]
[New LWP 12396]
[New LWP 12388]
[New LWP 12387]
[New LWP 12385]
[New LWP 12375]
[New LWP 12394]
[New LWP 12378]
[New LWP 12473]
[New LWP 12399]
[New LWP 12372]
[New LWP 12331]
[New LWP 12361]
[New LWP 12371]
[New LWP 12355]
[New LWP 12316]
[New LWP 12310]
[New LWP 12389]
[New LWP 12374]
[New LWP 12513]
[New LWP 12392]
[New LWP 12358]
[New LWP 12443]
[New LWP 12483]
[New LWP 12485]
[New LWP 12503]
[New LWP 12461]
[New LWP 12325]
[New LWP 12398]
[New LWP 12327]
[New LWP 12329]
[New LWP 12402]
[New LWP 12496]
[New LWP 12509]
[New LWP 12415]
[New LWP 12441]
[New LWP 12423]
[New LWP 12507]
[New LWP 12488]
[New LWP 12508]
[New LWP 12410]
[New LWP 12356]
[New LWP 12414]
[New LWP 12413]
[New LWP 12451]
[New LWP 12454]
[New LWP 12416]
[New LWP 12429]
[New LWP 12504]
[New LWP 12478]
[New LWP 12456]
[New LWP 12436]
[New LWP 12475]
[New LWP 12354]
[New LWP 12439]
[New LWP 12466]
[New LWP 12510]
[New LWP 12505]
[New LWP 12424]
[New LWP 12449]
[New LWP 12440]
[New LWP 12490]
[New LWP 12458]
[New LWP 12324]
[New LWP 12318]
[New LWP 12511]
[New LWP 12345]
[New LWP 12431]
[New LWP 12411]
[New LWP 9903]
[New LWP 12338]
[New LWP 12364]
[New LWP 12347]
[New LWP 12319]
[New LWP 12409]
[New LWP 12459]
[New LWP 12495]
[New LWP 12407]
[New LWP 12455]
[New LWP 12468]
[New LWP 12362]
[New LWP 12430]
[New LWP 12493]
[New LWP 12469]
[New LWP 12421]
[New LWP 12340]
[New LWP 12343]
[New LWP 12420]
[New LWP 12432]
[New LWP 12437]
[New LWP 12435]
[New LWP 12465]
[New LWP 12502]
[New LWP 12481]
[New LWP 12444]
[New LWP 12471]
[New LWP 12349]
[New LWP 12393]
[New LWP 12498]
[New LWP 12366]
[New LWP 12489]
[New LWP 12464]
[New LWP 12491]
[New LWP 12499]
[New LWP 12474]
[New LWP 12501]
[New LWP 12497]
[New LWP 12326]
[New LWP 12477]
[New LWP 12359]
[New LWP 12346]
[New LWP 12434]
[New LWP 12500]
[New LWP 12336]
[New LWP 12334]
[New LWP 12348]
[New LWP 12335]
[New LWP 12323]
[New LWP 12330]
[New LWP 12350]
[New LWP 12506]
[New LWP 12322]
[New LWP 12333]
[New LWP 12447]
[New LWP 12467]
[New LWP 12351]
[New LWP 12494]
[New LWP 12422]
[New LWP 12452]
[New LWP 12417]
[New LWP 12492]
[New LWP 12442]
[New LWP 12403]
[New LWP 12484]
[New LWP 12390]
[New LWP 12453]
[New LWP 12446]
[New LWP 12428]
[New LWP 12406]
[New LWP 12400]
[New LWP 12397]
[New LWP 12482]
[New LWP 12427]
[New LWP 12457]
[New LWP 12395]
[New LWP 12460]
[New LWP 12486]
[New LWP 12476]
[New LWP 12401]
[New LWP 12463]
[New LWP 12365]
[New LWP 12450]
[New LWP 12353]
[New LWP 12339]
[New LWP 12368]
[New LWP 12320]
[New LWP 12321]
[New LWP 12352]
[New LWP 12360]
[New LWP 12342]
[New LWP 12512]
[New LWP 12405]
[New LWP 12470]
[New LWP 12479]
[New LWP 12380]
[New LWP 12377]
[New LWP 12433]
[New LWP 12438]
[New LWP 12419]
[New LWP 12426]
[New LWP 12412]
[New LWP 12462]
[New LWP 12445]
[New LWP 12386]
[New LWP 12448]
[New LWP 12480]
[New LWP 12487]
[New LWP 12472]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/rtpengine -f --no-log-timestamps --pidfile /run/ngcp-rtpengine-daemon'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000056046349dcbf in __re_address_translate_ep (ep=0x30, o=0x7fa880167a00) at media_socket.c:1111
1111    media_socket.c: No such file or directory.
[Current thread is 1 (Thread 0x7fa9473f9700 (LWP 12341))]

Please let me know if you need any other information.
Thanks in advance.

**Comment by rfuchs** [comment]
Already fixed. Same as #1420 re-reported just a few days ago. Update your code.
