### ISSUE TITLE
Bridge sRTP using SDES <-> RTP: missing crypto params

### ISSUE THREAD

**Issue by wnke** [sipwise/rtpengine#1424]
Hello!

I got kamailio together with rtpengine connected to an external SIP provider (BroadWorks), this provider has both RTP and sRTP. 
RTP works fine, sRTP is using SDES and not working at all.

I am trying to bridge the sRTP media to RTP and forward it to an Asterisk PBX.

On kamailio I got for inbound calls, external (external SIP provider) -> internal (asterisk):
`rtpengine_manage("replace-origin replace-session-connection direction=external direction=internal media-address=LOCAL_IP rtcp-mux-demux DTLS=off SDES-off ICE=remove RTP/AVP);`

And the reply internal->external is handled with:
`rtpengine_manage("SIP-source-address replace-origin replace-session-connection direction=internal direction=external media-address=ADVERTISED_IP DTLS=off RTP/SAVP");`

On the inbound SIP INVITE SDP sent by the external SIP provider:
```
v=0
o=BroadWorks 22341 1 IN IP4 <IP>
s=-
c=IN IP4 <IP>
t=0 0
m=audio 65146 RTP/AVP 8 101
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=maxptime:30
a=silenceSupp:off - - - -
a=ptime:20
m=audio 65148 RTP/SAVP 8 101
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=maxptime:30
a=silenceSupp:off - - - -
a=ptime:20
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:7dFzE/6gTVVBJNWmF4gqOeS8UUpCYKjqYMrkuKsD
a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:wqwioQFI+zkDhCJpHluR3QODvLF8eWlUXKa0Aygx
```

Notice both the `RTP/AVP` and the `RTP/SAVP` being offered.

While on the response SDP provided by the rtpengine i got:

```
v=0
o=- 22341 3 IN IP4 <IP>
s=Asterisk
c=IN IP4 <IP>
t=0 0
m=audio 10324 RTP/SAVP 8 101
a=maxptime:150
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=rtcp:10325
a=ptime:20
m=audio 0 RTP/SAVP 8 101
```

Notice no crypto params and `RTP/SAVP` appears twice with the last entry being empty!

Finally on the rtpengine logs:
```
[1641248032.427698] DEBUG: [<CALL-ID>]: [crypto] [10.10.0.6:10224] Initialized incoming SRTP with SDES crypto params: suite AES_CM_128_HMAC_SHA1_80, tag 1, key qtPRK5CK740YxJy2P85FUA== salt sPFFZzNsLoikMuOQFJI=
[1641248032.427702] DEBUG: [<CALL-ID>]: [crypto] [1] Initialized outgoing SRTP with SDES crypto params: <none>
```

EDIT: Running version `Version 10.2.0.0+0~mr10.2.0.0 git-master-2c0e196b`

Do you guys have any idea why there are no crypto params on the reply SDP?

**Comment by rfuchs** [comment]
> On the inbound SIP INVITE SDP sent by the external SIP provider:
...
> Notice both the `RTP/AVP` and the `RTP/SAVP` being offered.

This is a dual RTP/SRTP offer, which is non-standard and not really supported by rtpengine. We do support OSRTP instead.

From what you posted this is then converted to a plain RTP offer with two audio sections. The called party would then probably reject the second audio section and only answer the first (which is where the zero port comes from). The first audio section was plain RTP, not SRTP, therefore no crypto attributes in the reply.

This is not a code issue and should have been sent to the mailing list. Closing.
