### ISSUE TITLE
Bridge SRTP and RTP

### ISSUE THREAD

**Issue by pengweichu** [sipwise/rtpengine#1426]
Hi, I would like to use rtpengine to build my SBC, when the call is between two users, one is used SRTP another one only supports normal RTP(For example, a WebRTC user makes the call with an IP Phone),  the RTPEngine will handle this scenario automatically? How can I build the offer Message for this scenario? Can I have an example?

**Comment by rfuchs** [comment]
We have a mailing list for these kinds of questions: https://rtpengine.com/mailing-list
