### ISSUE TITLE
libwebsockets: Unable to find interface ::1

### ISSUE THREAD

**Issue by pafels** [sipwise/rtpengine#1432]
After cloning of the current master, compiling a deb packet and installing it I got this error:

root@gt-124:/# rtpengine --table=2 --interface=192.168.0.13 --interface=fd18::321:4daa:baad:f3cea --listen-ng=127.0.0.1:9912 --tos=184 --pidfile=/run/rtpengine-ipv6_2.pid --no-fallback
[1643028013.149418] ERR: [http] libwebsockets: Unable to find interface ::1
[1643028013.149448] ERR: [http] Failed to start websocket listener: LWS failed to create vhost
[1643028013.150343] CRIT: [core] Fatal error: Failed to init websocket listener

I don't need http/ws but I couldn't find a way to stop it even with a config file as written in the Readme. 

Ipv6 loopback is present: 
root@gt-124:/tmp# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever

Last time I compiled current master and installed it on the same machine was 1-2 december. There were no such issues.

Any idea? 

Regards,
P

**Comment by whitepiratebaku** [comment]
I also get this issue, Debian 10

**Comment by whitepiratebaku** [comment]
I do not know how much version matters for you, because I do testing I went with older LTS 8.5 from https://dfx.at/rtpengine/  . It works fine

**Comment by rfuchs** [comment]
There's a default config file provided now. If you don't want to use it, pass `--config-file=none` in your CLI options.

**Comment by pafels** [comment]
> There's a default config file provided now. If you don't want to use it, pass `--config-file=none` in your CLI options. Or edit the config file to disable the HTTP/WS listener.

I've already tested with the default config and added # in front of listen-http:
[rtpengine]
#listen-http = 192.168.0.13:2225

It didn't disable HTTP/WS listener and I got the error I posted.

**Comment by pafels** [comment]
Hmm.. after setting _--config-file=none_ rtpengine is starting and working. Strange behavior but it's fine for me. Thanks @rfuchs !

**Comment by pafels** [comment]
After some investigation I found that on one side I've made a mistake trying to start rtpengine with:
**-f /tmp/rtpe.conf**
instead of the correct **--config-file=/tmp/rtpe.conf** 

I didn't got an error and it has started with the default config which is : **/etc/rtpengine/rtpengine.conf**
_[rtpengine]
table = 0
interface = any
listen-ng = localhost:2223
listen-http = localhost:2225
listen-cli = localhost:2224
timeout = 60
silent-timeout = 3600
tos = 184
port-min = 30000
port-max = 40000
recording-dir = /var/spool/rtpengine
recording-method = proc_

On the other side rtpengine is trying listen to 
**listen-ng = localhost:2223
listen-http = localhost:2225
listen-cli = localhost:2224**

localhost is by default:
_root@gt-124:/# cat /etc/hosts | grep localhost
127.0.0.1	localhost
::1     localhost ip6-localhost ip6-loopback_

So most likely there is an issue with libwebsockets and ipv6 localhost address ::1.

I've replaced localhost in the default config with 127.0.0.1 and rtpengine is working as expected also listening to ports 2223,2224,2225 ports.

Regards,
Pavel S
