### ISSUE TITLE
debian/rules build gave error exit status 2 (mr10.2.1)

### ISSUE THREAD

**Issue by abieuzent** [sipwise/rtpengine#1433]
I'm trying to migrate rtpengine in Debian 9 (from 7.5.9 to 10.2.1) but i cant seem to get through.

When i run dpkg-buildpackage i have this error :

test "$(ls fake-daemon-tests-main-sockets)" = ""
rmdir fake-daemon-tests-main-sockets
rm sdp.strhash.c control_ng.strhash.c test-const_str_hash.strhash.c call_interfaces.strhash.c janus.strhash.c
make[3]: Leaving directory '/usr/src/rtpengine-10.2.1/rtpengine-mr10.2.1/t'
../lib/common.Makefile:4: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/usr/src/rtpengine-10.2.1/rtpengine-mr10.2.1/t'
Makefile:54: recipe for target 'check' failed
make[1]: *** [check] Error 2
make[1]: Leaving directory '/usr/src/rtpengine-10.2.1/rtpengine-mr10.2.1'
dh_auto_test: make -j4 check returned exit code 2
debian/rules:33: recipe for target 'build' failed
make: *** [build] Error 2
[1mdpkg-buildpackage: [0m[1;31merror[0m: debian/rules build gave error exit status 2

when I look for the errors from before: 

ok 247 - received packet matches
rtp in 13 2001 4160 13398
mkdir fake-daemon-tests-websocket-sockets
LD_PRELOAD=../t/tests-preload.so RTPE_BIN=../daemon/rtpengine TEST_SOCKET_PATH=./fake-daemon-tests-websocket-sockets \
	   python3 auto-daemon-tests-websocket.py
rtp recv 0 2001 4160 3062161697 ce5669cc61ca63d26657e24765596a745d4a68e9604a634bf4434b4848523957374c394c483b4347445748f53e593e523b533d533b415b384a4b35484a3e52504b46fd3ef13ad635545d3a5845423d3e4c423a583c503b6e36603e3d3b413a473548354b3e3d473a3d394f40424a473d6b425a7553455a4b4f4859487843774c425947463e67443a674b3f5148443e54376c45453f6e3a68494e3f474b3ef339
ok 248 - received packet matches
rtp in 0 2002 4320 13398
  File "auto-daemon-tests-websocket.py", line 2074
    print(f"HINT: Stdout and stderr are {so.name} and {se.name}")
                                                               ^
SyntaxError: invalid syntax
Makefile:168: recipe for target 'daemon-tests-websocket' failed
make[3]: *** [daemon-tests-websocket] Error 1
make[3]: *** Waiting for unfinished jobs....
rtp recv 0 2002 4320 3062161697 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
ok 249 - received packet matches

Any clue of what can i look for?

thanks

**Comment by rfuchs** [comment]
We don't really support stretch any more (and the reason this is failing is because the Python version is too old) but you can try setting `DEB_BUILD_OPTIONS=nocheck` when building the package (e.g. `DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage`)

**Comment by abieuzent** [comment]
Thanks Richard,

 

If it can help, I removed daemon-tests-websocket on .t/Makefile to solve the issue.

 

Regards

 

De : Richard Fuchs ***@***.***>
Répondre à : sipwise/rtpengine ***@***.***>
Date : mardi 25 janvier 2022 à 14:19
À : sipwise/rtpengine ***@***.***>
Cc : Alain Bieuzent ***@***.***>, Author ***@***.***>
Objet : Re: [sipwise/rtpengine] debian/rules build gave error exit status 2 (mr10.2.1) (Issue #1433)

 

We don't really support stretch any more (and the reason this is failing is because the Python version is too old) but you can try setting DEB_BUILD_OPTIONS=nocheck when building the package (e.g. DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
