### ISSUE TITLE
No audio on outgoing call (MS Teams to PSTN)

### ISSUE THREAD

**Issue by Eulnono76** [sipwise/rtpengine#1435]
Hello Guys,

It's not one issue, it's a misconfiguration problem but I'm tearing my hair out because I don't see any problem in the frame.

The diagram is as follows :
`MS Teams (54) 52.114.76.76 --SRTP -- 217.169.242.148 (Kamailio) ----RTP -- 217.169.242.134 (Asterisk which represents the PSTN).`

PSTN calls to MS TEAMS works perfectly but in the other direction it doesn't work, and I don't understand why because everything seems absolutely correct.
I have the impression that MS Teams does not send me its RTP stream.

To show clearest logs, they  can be see here in TXT files : [https://dl.mcom.fr/98fcdeec6cef]

A very very big thank you to the personn who takes the time to look my logs. 

Regards.

**Comment by rfuchs** [comment]
Not a code issue. General questions should be directed to the mailing list: https://rtpengine.com/mailing-list
