### ISSUE TITLE
Looks like you failed 1 test of 589

### ISSUE THREAD

**Issue by juha-h** [sipwise/rtpengine#1436]
I had previously build successfully mr10.2.1 on Debian Bullseye.  Now I tried to build mr10.3, but it failed due to one test failing:
```
rtp in 0 1014 5240 4660
rtp recv 0 1013 5240 4660 a5a770221c2ead9ca1f327253bc2bad07dc5b3bc3b22245aa29bab311d2156aba8bc4d47f6ec3d2d35bca0a0c9231b29b79ea2cb2e2c3fdbe44c5bb8a9af3e1f1e3fa59ba73d202446b5b0c66ed3bdce35252bc49f9db9281c26c7a4a6c43c395377423444b3a2a74d1f1c33aa9ca554282943c5c679f1baadbc331f24df9f9caf2d1d25efacacc65162cefd342936b49ea1e4201b2db19fa6e130314be6523f
800003f50000147800001234a5a770221c2ead9ca1f327253bc2bad07dc5b3bc3b22245aa29bab311d2156aba8bc4d47f6ec3d2d35bca0a0c9231b29b79ea2cb2e2c3fdbe44c5bb8a9af3e1f1e3fa59ba73d202446b5b0c66ed3bdce35252bc49f9db9281c26c7a4a6c43c395377423444b3a2a74d1f1c33aa9ca554282943c5c679f1baadbc331f24df9f9caf2d1d25efacacc65162cefd342936b49ea1e4201b2db19fa6e130314be6523f
not ok 499 - received packet matches
#   Failed test 'received packet matches'
#   at ../perl/NGCP/Rtpengine/AutoTest.pm line 211.
#                   '��x4��p".����'%;º�}ų�;"$Z���1!V���MG��=-5����#���.,?��L[���>?���= $F���nӽ�5%+ğ��(&Ǥ��<9SwB4D���M3���T()C��y񺭼3$ߟ��-%שּׁ�Qb��4)6���� ���01K�R?'
#     doesn't match '(?^s:^\�\\\�\\\x\\\4\�\�p\"\\.\�\�\�\�\'\%\;\�\�\�\}\�\�\�\;\"\$Z\�\�\�1\\!V\�\�\�MG\�\�\=\-5\�\�\�\�\#\)\�\�\�\�\.\,\?\�\�L\[\�\�\�\>\\\?\�\�\�\=\ \$F\�\�\�n\�\�\�5\%\+\�\�\�\�\(\\&\�\�\�\�\<9SwB4D\�\�\�M\\3\�\�\�T\(\)C\�\�y\�\�\�\�3\\$\�\�\�\�\-\\%\�\�\�\�Qb\�\�4\)6\�\�\�\�\ \-\�\�\�\�01K\�R\?$)'
```
If commit https://github.com/sipwise/rtpengine/commit/261e6a6503c6d36042cea597b7db2dc2220a61d9 would help, could it be backported to mr10.3?

**Comment by juha-h** [comment]
Yes, I successfully built master.  So I can wait until commit https://github.com/sipwise/rtpengine/commit/261e6a6503c6d36042cea597b7db2dc2220a61d9 is included in a new branch or be backported to mr10.3.

**Comment by juha-h** [comment]
Turned out that commit `run rtpengine as non-root` did not yet support non-NGCP Debian packaging.  I was able to build working Debian package by checking out commit https://github.com/sipwise/rtpengine/commit/261e6a6503c6d36042cea597b7db2dc2220a61d9.

**Comment by rfuchs** [comment]
What problem did you have with 30c2de8 in combination with Debian packaging?

**Comment by juha-h** [comment]
Richard Fuchs writes:

> What problem did you have with 30c2de8 in combination with Debian
> packaging?

I just tried again and build of master on Debian 11 succeeded without
any errors:

$ ls -ls deb/20220131/
total 4172
  60 -rw-r--r-- 1 root root   59728 Jan 31 19:48 rtpengine_10.4.0.0+0~mr10.4.0.0_all.deb
 584 -rw-r--r-- 1 root root  597264 Jan 31 19:46 rtpengine_10.4.0.0+0~mr10.4.0.0.tar.xz
 448 -rw-r--r-- 1 root root  455384 Jan 31 19:48 rtpengine-daemon_10.4.0.0+0~mr10.4.0.0_amd64.deb
2164 -rw-r--r-- 1 root root 2213588 Jan 31 19:48 rtpengine-daemon-dbgsym_10.4.0.0+0~mr10.4.0.0_amd64.deb
  60 -rw-r--r-- 1 root root   60444 Jan 31 19:48 rtpengine-iptables_10.4.0.0+0~mr10.4.0.0_amd64.deb
   8 -rw-r--r-- 1 root root    6832 Jan 31 19:48 rtpengine-iptables-dbgsym_10.4.0.0+0~mr10.4.0.0_amd64.deb
  84 -rw-r--r-- 1 root root   83740 Jan 31 19:48 rtpengine-kernel-dkms_10.4.0.0+0~mr10.4.0.0_all.deb
 132 -rw-r--r-- 1 root root  132820 Jan 31 19:48 rtpengine-kernel-source_10.4.0.0+0~mr10.4.0.0_all.deb
 136 -rw-r--r-- 1 root root  138652 Jan 31 19:48 rtpengine-recording-daemon_10.4.0.0+0~mr10.4.0.0_amd64.deb
 412 -rw-r--r-- 1 root root  421324 Jan 31 19:48 rtpengine-recording-daemon-dbgsym_10.4.0.0+0~mr10.4.0.0_amd64.deb
  84 -rw-r--r-- 1 root root   82932 Jan 31 19:48 rtpengine-utils_10.4.0.0+0~mr10.4.0.0_all.deb
