### ISSUE TITLE
rtpengine-recording-daemon in debian 11

### ISSUE THREAD

**Issue by syco** [sipwise/rtpengine#1438]
Hi,
I've installed rtpengine with the following:
```bash
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E926C0E8E60F75AD
echo "deb https://dfx.at/rtpengine/latest bullseye main" > /etc/apt/sources.list.d/dfx.at-rtpengine.list
apt-get update
apt-get -y install rtpengine
```
But when I try to start `rtpengine-recording-daemon` I get this error:
```bash
systemctl start rtpengine-recording-daemon
Failed to restart rtpengine-recording-daemon.service: Unit rtpengine-recording-nfs-mount.service not found.
```
I can't find the `rtpengine-recording-nfs-mount` anywhere, is it safe to remove it from `rtpengine-recording-daemon.service`?
Thanks

**Comment by rfuchs** [comment]
It should be included in the recording-daemon package. Looks like there's a booboo in my build pipeline. I'll rebuild the packages.

**Comment by rfuchs** [comment]
Should be fixed now for the `latest` repo
