### ISSUE TITLE
Query: Is it possible to encrypt the recorded call

### ISSUE THREAD

**Issue by malvarado611** [sipwise/rtpengine#1444]
Sorry for the inconvenience, but could you tell me if it is possible to encrypt a call that has been recorded?

Regarding,
Miguel Alvarado

**Comment by rfuchs** [comment]
No, there's no such feature included. You could script around it by encrypting files as soon as they're finished writing. For a more comprehensive feature you'd have to hook into ffmpeg's AVIO (not sure if that's even possible).

Not a code issue, therefore closing. Questions should be directed to the mailing list.
