### ISSUE TITLE
Audio drop all packets under 1 min with single call 

### ISSUE THREAD

**Issue by paulandrewhughes** [sipwise/rtpengine#145]
Using mr3.7.2.2 on Centos 6.7 without iptables with strict source with opt build.

I experienced a problem with a single call where after about 30 seconds packets would start to be dropped and then after 1min nearly every call lost all audio.

The strict source check was found to be causing packets to be dropped even though the source on packets didn't change. Problem was found to be caused by memcmp between stream endpoint and 
endpoint of the packet finding packets are different when they are not.

In function stream_packet in call.c local variable endpoint is not initialised. According to gdb endpoint size is 20 bytes. A portion of the endpoint is assigned with code below.
```
endpoint.ip46 = fsin->sin6_addr;   /* 16 bytes */
endpoint.port = ntohs(fsin->sin6_port); /* 2 bytes */
```
Leaving 2 bytes uninitialised due to compiler alignment of struct.

Changing definition of endpoint to packed resolved the problem.
```
struct endpoint {
	struct in6_addr		ip46;
	u_int16_t		port;
} __attribute__((__packed__));
```

**Comment by rfuchs** [comment]
Good catch, thanks.
