### ISSUE TITLE
Forward the RTP stream to another Gateway realtime server

### ISSUE THREAD

**Issue by thieplehuu** [sipwise/rtpengine#1453]
I am using rtpengine for call recording.
Now I want to forward the RTP stream to another  Gateway server realtime  is it possible? please help me.

**Comment by rfuchs** [comment]
Not a code issue. Closing. We have a mailing list for generic questions.

You probably want to look at either one of the two "forward" options of the recording daemon, or the "subscribe" feature of rtpengine itself which can be used to facilitate SIPREC-like forwarding.
