### ISSUE TITLE
Limit of transcoding sessions

### ISSUE THREAD

**Issue by giupand** [sipwise/rtpengine#1454]
Hi,
can the rtpengine limit number of transcoding sessions? Is it present a configuration parameter like max-sessions?
If the feature is not present, is it possible plan a develop for it?

**Comment by rfuchs** [comment]
You can limit sessions overall, but you can't limit just transcoding sessions in particular. We don't have plans to develop this but pull requests are welcome.

Don't open Github issues to ask questions. We have a mailing list for that.

**Comment by giupand** [comment]
Ok, thanks.
