### ISSUE TITLE
Play media in kernel mode

### ISSUE THREAD

**Issue by bshirazi** [sipwise/rtpengine#1458]
Hi
I installed rtpengine via packages via suggested [repository](https://dfx.at/rtpengine/) Bullseye  REL=9.5.
I used @razvancrainea    [code](https://github.com/OpenSIPS/opensips/issues/1996) and made Opensips+rtpengine to play media.There is no B party, Opensips+rtpengine simulating B party also:

> route[play_media] {
    rtpengine_offer();
    append_to_reply("Content-Type: application/sdp\r\n");
    $var(body) = $(rb{re.subst,/(IP4.).*/\1127.0.0.1/g}); # replace the IP in the body
    t_reply_with_body(183, "Session Progress", $var(body));
    rtpengine_play_media("totag=$ft file=/My_media.wav");
}

I can play media but I cannot kernelize media. Output of ` cat /proc/rtpengine/0/list
` is always empty and even I used PCMA wav file and forced sipphone to just ALAW I see in logs: 

> Feb 27 14:50:36 RTP rtpengine[1363]: INFO: [a4f65d105ec04419a41218004f6b6291]: [control] Replying to 'offer' from 127.0.0.1:34011 (elapsed time 0.000999 sec)
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [control] Response dump for 'offer' to 127.0.0.1:34011: { "sdp": "v=0
Feb 27 14:50:36 RTP rtpengine[1363]: o=- 3854955045 3854955045 IN IP4 10.20.255.37
Feb 27 14:50:36 RTP rtpengine[1363]: s=pjmedia
Feb 27 14:50:36 RTP rtpengine[1363]: b=AS:84
Feb 27 14:50:36 RTP rtpengine[1363]: t=0 0
Feb 27 14:50:36 RTP rtpengine[1363]: a=X-nat:0
Feb 27 14:50:36 RTP rtpengine[1363]: m=audio 30402 RTP/AVP 8
Feb 27 14:50:36 RTP rtpengine[1363]: c=IN IP4 10.105.80.99
Feb 27 14:50:36 RTP rtpengine[1363]: b=TIAS:64000
Feb 27 14:50:36 RTP rtpengine[1363]: a=ssrc:1489066612 cname:5f0a12ed49ac0a2d
Feb 27 14:50:36 RTP rtpengine[1363]: a=rtpmap:8 PCMA/8000
Feb 27 14:50:36 RTP rtpengine[1363]: a=sendrecv
Feb 27 14:50:36 RTP rtpengine[1363]: a=rtcp:30403
Feb 27 14:50:36 RTP rtpengine[1363]: ", "result": "ok" }
Feb 27 14:50:36 RTP rtpengine[1363]: INFO: [a4f65d105ec04419a41218004f6b6291]: [control] Received command 'play media' from 127.0.0.1:34011
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [control] Dump for 'play media' from 127.0.0.1:34011: { "file": "/etc/rtpengine/600.wav", "call-id": "a4f65d105ec0441
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [ffmpeg] av_log: Opening '/etc/rtpengine/600.wav' for reading
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [ffmpeg] av_log: Setting default whitelist 'file,crypto,data'
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [ffmpeg] av_log: Probing wav score:99 size:2048
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [ffmpeg] av_log: Format wav probed with size=2048 and score=99
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [ffmpeg] av_log: Before avformat_find_stream_info() pos: 58 bytes read:32768 seeks:0 nb_streams:1
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [ffmpeg] av_log: parser not found for codec pcm_alaw, packets or times may be invalid.
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [ffmpeg] av_log: max_analyze_duration 5000000 reached at 5120000 microseconds st:0
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [ffmpeg] av_log: stream 0: start_time: NOPTS duration: 59.351
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [ffmpeg] av_log: format: start_time: NOPTS duration: 59.351 (estimate from stream) bitrate=64 kb/s
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [ffmpeg] av_log: After avformat_find_stream_info() pos: 53306 bytes read:65536 seeks:0 frames:12
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [core] Output codec for media playback is PCMA/8000
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [codec] Creating SSRC transcoder from PCMA/8000/1 to PCMA/8000/1
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [core] Initialized encoder with frame size 160 samples
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [codec] Encoder created with clockrate 8000, 1 channels, using sample format 1 (ptime 20 for 160 samples per frame an
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [codec] Created media playback context for PCMA/8000 -> PCMA/8000
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [core] read media packet: pts 0 duration 4096 (scaled 0/4096, 512000 us), sample rate 8000, time_base 1/8000
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [transcoding] RTP media successfully decoded: TS 0, samples 4096
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [transcoding] RTP media successfully encoded: TS 0, len 160
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [transcoding] Adding 160 bytes to packetizer
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [transcoding] Received packet of 160 bytes from packetizer
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [transcoding] Scheduling to send RTP packet (seq 16957 TS 7311981187981797817) in 0.0 ms (at 1645960836.540889)
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [transcoding] RTP media successfully encoded: TS 160, len 160
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [transcoding] Adding 160 bytes to packetizer
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [transcoding] Received packet of 160 bytes from packetizer
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [transcoding] Scheduling to send RTP packet (seq 16958 TS 7311981187981797977) in 20.0 ms (at 1645960836.560889)
Feb 27 14:50:36 RTP rtpengine[1363]: DEBUG: [a4f65d105ec04419a41218004f6b6291]: [transcoding] RTP media successfully encoded: TS 320, len 160
 
Do you think this is possible to play media in kernel mode ? Do you think transcode is responsible for not going to kernel mode or play media is responsible for invoking transcode:
`Creating SSRC transcoder from PCMA/8000/1 to PCMA/8000/1`
Is there any option for disabling transcode in offer ?

Regards
Shirazi

**Comment by rfuchs** [comment]
Not a code issue. This should have been sent to the mailing list.

Media playback always happens from userspace and always has a transcoding component. You can still use kernel based media forwarding at the same time, but playback itself never happens from kernel.
