### ISSUE TITLE
"Failed to get 2 consecutive ports" on public interface when using kernel module

### ISSUE THREAD

**Issue by davehorton** [sipwise/rtpengine#1459]
I am using the rtpengine kernel module on a debian 10 server.  In my rtpengine config I am defining a "public" interface as well as a "private" interface, e.g.:
```bash
/usr/local/bin/rtpengine --interface private/10.132.0.7 --interface public/34.76.136.198
```
I am running on GCP and determining the public address in my systemd service file, e.g.
```bash
ExecStartPre=/bin/sh -c systemctl set-environment LOCAL_IP=`curl -s -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/ip` (code=exited
ExecStartPre=/bin/sh -c systemctl set-environment PUBLIC_IP=`curl -s -H "Metadata-Flavor: Google" http://metadata/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip` (
ExecStart=/usr/local/bin/rtpengine --interface private/${LOCAL_IP} --interface public/${PUBLIC_IP} --listen-ng=22222 --listen-http=8080 --listen-udp=12222 --dtmf-log-dest=10.132.0.52:22223 --pid
```
However, when I send an 'offer' command with direction ['public', 'private'] I get this error:
```bash
[core] Failed to get 2 consecutive ports on interface 34.76.136.198 for media relay (last error: Cannot assign requested address)
Failed to get 2 consecutive ports on all locals of logical 'public'
```
Is this expected, or a limitation of some sort when using the kernel module?

**Comment by rfuchs** [comment]
This doesn't really have anything to do with the kernel module. I'm guessing the public IP address isn't really bound on the system directly, and so opening ports on that interface isn't possible. Assuming there's a 1-to-1 NAT between the public and private addresses, what you want is to use the "advertised address" syntax for the public interface, e.g. something like `--interface public/10.132.0.7!34.76.136.198`

Not a code issue, therefore closing. We have a mailing list for generic questions like this.

**Comment by davehorton** [comment]
ah yes, of course, my bad.  Thanks!

**Comment by prathibhacdac** [comment]
I am facing the same issue. Can someone pls help.

**Comment by prathibhacdac** [comment]
@rfuchs when I run the command /usr/bin/rtpengine --interface public/43.204.228.99 --foreground

Failure while trying to bind a port to the socket
[1695296758.906790] ERR: [f1m4u5jgbtoeth0ae1gq]: [core] Failed to get 2 consecutive ports on interface 43.204.228.99 for media relay (last error: Cannot assign requested address)
[1695296758.907095] ERR: [f1m4u5jgbtoeth0ae1gq]: [core] Failed to get 2 consecutive ports on all locals of logical 'default'
[1695296758.907388] ERR: [f1m4u5jgbtoeth0ae1gq]: [core] Error allocating media ports
[1695296758.908022] ERR: [f1m4u5jgbtoeth0ae1gq]: [core] Destroying call
[1695296758.909805] WARNING: [f1m4u5jgbtoeth0ae1gq]: [control] Protocol error in packet from 172.31.34.24:40246: Ran out of ports [d3:sdp8654:v=0

**Comment by davehorton** [comment]
> This doesn't really have anything to do with the kernel module. I'm guessing the public IP address isn't really bound on the system directly, and so opening ports on that interface isn't possible. Assuming there's a 1-to-1 NAT between the public and private addresses, what you want is to use the "advertised address" syntax for the public interface, e.g. something like `--interface public/10.132.0.7!34.76.136.198`
> 
> Not a code issue, therefore closing. We have a mailing list for generic questions like this.

I specifically followed the suggestion above, using the exclamation point to clarify that the public ip was assigned over the top by the cloud provider, not bound to an interface on the server

**Comment by prathibhacdac** [comment]
@davehorton can you pls share the command?

**Comment by moyuduo** [comment]
> > This doesn't really have anything to do with the kernel module. I'm guessing the public IP address isn't really bound on the system directly, and so opening ports on that interface isn't possible. Assuming there's a 1-to-1 NAT between the public and private addresses, what you want is to use the "advertised address" syntax for the public interface, e.g. something like `--interface public/10.132.0.7!34.76.136.198`
> > Not a code issue, therefore closing. We have a mailing list for generic questions like this.
> 
> I specifically followed the suggestion above, using the exclamation point to clarify that the public ip was assigned over the top by the cloud provider, not bound to an interface on the server

hello, i have the same problem. my start cmd like this:
` rtpengine --interface=priv/$RTPE_IP_LOCAL --interface=pub/$RTPE_IP_LOCAL\!$RTPE_IP_PUBLIC --listen-ng $RTPE_IP_LOCAL:2223 --dtls-passive -f -m $RTPE_RTP_START -M $RTPE_RTP_END  -E -L 7 --log-facility=local1`

two client can call each other, by no voice, i use wireshark to capture flow, just find the rtp ip set to a local ip, have any idea?
![image](https://github.com/sipwise/rtpengine/assets/59435134/f5f3a30e-824c-4fb9-82df-caa62c422368)
