### ISSUE TITLE
dpkg-buildpackage  failed, request the help

### ISSUE THREAD

**Issue by bluejade008** [sipwise/rtpengine#1460]
Hi sir,

Try to compile the rtpengine in ubuntu vm, but dpkg-buildpackage failed, could you help to check it? thanks.

my compile environment infromation:
root@DN2:~/rtpengine# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
[[172.17.40.25 (root)]-20220303_112700.log](https://github.com/sipwise/rtpengine/files/8174786/172.17.40.25.root.-20220303_112700.log)

Codename:       bionic
root@DN2:~/rtpengine# dpkg-checkbuilddeps

...............................................................................
the errors are raised, and the detailing logs are attached.

cc: error: unrecognized command line option ‘-fstack-protector-strong’
cc: error: unrecognized command line option ‘-Wdate-time’
cc: error: unrecognized command line option ‘-Wdate-time’
cc: error: unrecognized command line option ‘-Wdate-time’
cc: error: unrecognized command line option ‘-Wdate-time’
cc: error: unrecognized command line option ‘-Wdate-time’
<builtin>: recipe for target 'dtmf_rx_fillin-test' failed
make[4]: *** [dtmf_rx_fillin-test] Error 1
make[4]: Leaving directory '/root/rtpengine/daemon'
Failed build with ../lib/dtmf_rx_fillin-02.h
../lib/common.Makefile:50: recipe for target 'dtmf_rx_fillin.h' failed
make[3]: *** [dtmf_rx_fillin.h] Error 1
make[3]: Leaving directory '/root/rtpengine/daemon'
Failed build with ../lib/fix_frame_channel_layout-04.h
../lib/common.Makefile:50: recipe for target 'fix_frame_channel_layout.h' failed
make[2]: *** [fix_frame_channel_layout.h] Error 1
make[2]: Leaving directory '/root/rtpengine/daemon'
Makefile:18: recipe for target 'distclean' failed
make[1]: *** [distclean] Error 2
make[1]: Leaving directory '/root/rtpengine'
dh_auto_clean: make -j1 distclean returned exit code 2
debian/rules:25: recipe for target 'clean' failed
make: *** [clean] Error 2
dpkg-buildpackage: error: debian/rules clean subprocess returned exit status 2

**Comment by rfuchs** [comment]
Can't reproduce this on a stock Bionic installation.

I'm guessing your version of `cc` (`gcc`?) doesn't match the output of what `dpkg-buildflags` suggests to use as build flags.

```
dfx@dfx-VirtualBox:~/rtpengine$ dpkg-buildflags
CFLAGS=-g -O2 -fdebug-prefix-map=/home/dfx/rtpengine=. -fstack-protector-strong -Wformat -Werror=format-security
CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2
CXXFLAGS=-g -O2 -fdebug-prefix-map=/home/dfx/rtpengine=. -fstack-protector-strong -Wformat -Werror=format-security
FCFLAGS=-g -O2 -fdebug-prefix-map=/home/dfx/rtpengine=. -fstack-protector-strong
FFLAGS=-g -O2 -fdebug-prefix-map=/home/dfx/rtpengine=. -fstack-protector-strong
GCJFLAGS=-g -O2 -fdebug-prefix-map=/home/dfx/rtpengine=. -fstack-protector-strong
LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro
OBJCFLAGS=-g -O2 -fdebug-prefix-map=/home/dfx/rtpengine=. -fstack-protector-strong -Wformat -Werror=format-security
OBJCXXFLAGS=-g -O2 -fdebug-prefix-map=/home/dfx/rtpengine=. -fstack-protector-strong -Wformat -Werror=format-security
```
```
dfx@dfx-VirtualBox:~/rtpengine$ cc --version
cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

But we don't really support Bionic at this point and don't have packaging included in the code, therefore this is not a code issue. If you want to help and provide packaging for Bionic, open a pull request.
