### ISSUE TITLE
rtpengine seems to truncate m=application parameters

### ISSUE THREAD

**Issue by davehorton** [sipwise/rtpengine#1461]
I'm running rtpengine version 10.2.1.5+0~mr10.2.1.5 git-HEAD-bf78f7fd and seeing an interesting issue.

I am testing with a PolcyCom CCX 700 which is offering an application media in addition to audio and video.  The initial call, through rtpengine is set up fine.  Then, during a reinvite (when the poly has been muted and sends a re-invite) I am calling offer and answer again.  

The answer command sequence during the reinvite is giving me a problem.  In the 'answer' request I provide an sdp, the last line of which looks like this:
```
m=application 0 * 
```
the answer response from rtpengine seems to strip the last few characters, and the sdp returned to me ends like this
```
m=application
```
Since this is for a call that eventually hairpins through rtpengine, later I pass that same SDP I got back to rtpengine, and at that point it complains the SDP is invalid:
```
[core] Error parsing SDP at offset 373: Error parsing m= line
[control] Protocol error in packet from 127.0.0.1:52719: Failed to parse SDP [d4:DTLS3:off3:ICE6:remove4:SDES3:off7:call-id32:090f9af17d567d452ac5571aeddfdf237:command6:answer5:flagsl14:media-handover13:port-latchinge8:from-tag17:4AC9E3F0-D6C054767:replacel6:origin18:session-connectione8:rtcp-muxl6:accepte3:sdp388:v=0#015#012o=root 774306435 774306437 IN IP4 10.0.13.72#015#012s=Twilio Media Gateway#015#012c=IN IP4 10.0.13.72#015#012t=0 0#015#012m=audio 41074 RTP/AVP 0 8 127#015#012a=maxptime:150#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:8 P ...
Mar  3 15:04:49 ip-10-0-13-72 rtpengine[13461]: WARNING: [090f9af17d567d452ac5571aeddfdf23]: ... CMA/8000#015#012a=rtpmap:127 telephone-event/8000#015#012a=fmtp:127 0-16#015#012a=sendrecv#015#012a=rtcp:41075#015#012a=ptime:20#015#012m=video 0 RTP/AVP 100 113 109 99#015#012m=video 0 RTP/AVP 109 99#015#012m=application 0 RTP/AVP 124#015#012m=application#015#0126:to-tag13:BpZ8cQDK06HUD18:transport protocol7:RTP/AVPe]
```
So as far as I can tell, the problem begins when rtpengine has somehow truncated that m=application line.

I can recreate this at will.

[Here is a gist](https://gist.github.com/davehorton/1dab55b94e1c697c3d78104911f749d3) showing the full rtpengine log when it processes that rtp

**Comment by rfuchs** [comment]
The media line `m=application 0 * ` is invalid according to the RFC. A protocol of `*` is technically valid but an empty list of formats is not. So I wouldn't be too concerned about an invalid output coming out of an invalid input.

**Comment by davehorton** [comment]
ok, I agree.  Unfortunately, though, there are lot of Polycom CCX 700s out there...
