### ISSUE TITLE
T38 - ptime

### ISSUE THREAD

**Issue by nicoonline** [sipwise/rtpengine#1465]
Hello,

We have something very strange since some weeks / months. We are running rtpengine 6.5.13.1

We got this from the carrier

o=FreeSWITCH 1646661634 1646661637 IN IP4 188.xx
s=FreeSWITCH
c=IN IP4 188.xx
t=0 0
m=image 52358 udptl t38
a=T38FaxVersion:0
a=T38MaxBitRate:9600
a=T38FaxRateManagement:transferredTCF
a=T38FaxMaxBuffer:72
a=T38FaxMaxDatagram:176
a=T38FaxUdpEC:t38UDPRedundancy
a=sendrecv

after processing in rtp engine i got this:

v=0
o=Media*Proxy1 1646661634 1646661637 IN IP4 217.xx
s=SIP Call
c=IN IP4 217.xx
t=0 0
m=image 15834 udptl t38
a=T38FaxVersion:0
a=T38MaxBitRate:9600
a=T38FaxRateManagement:transferredTCF
a=T38FaxMaxBuffer:72
a=T38FaxMaxDatagram:176
a=T38FaxUdpEC:t38UDPRedundancy
a=sendrecv
a=ptime:20

the ptime:20 is added. I have checked the code and ptime is not added from there.

**Comment by rfuchs** [comment]
Is this doing T.38 <> PCM transcoding or passthrough or something else? `o=` and `s=` lines are different so this is obviously not the same SDP.

**Comment by nicoonline** [comment]
o & s are the same. We are just rewriting the content :) So we are not transcoding, it's passthrough.

**Comment by rfuchs** [comment]
Is this after a T.38 re-invite and ptime= was set in the SDP previous to the re-invite? (in the RTP SDP)

**Comment by nicoonline** [comment]
Correct the ptime was in the original SDP (on the call reply)

**Comment by rfuchs** [comment]
So that's probably this then: https://github.com/sipwise/rtpengine/blob/mr6.5/daemon/sdp.c#L2125

**Comment by nicoonline** [comment]
Thanks for the feedback. This is expected or a bug ? :)

**Comment by rfuchs** [comment]
A bug that's been fixed already, just not in mr6.5 which is out of support.

**Comment by nicoonline** [comment]
Thanks Richard.

**Comment by rfuchs** [comment]
See 2e151d685

**Comment by nicoonline** [comment]
i have some difficulties to install the new mr 8.5 (compilation issue). I have tried to fix myself the code but i have an error : undefined reference to `proto_is_rtp'. Any brilliant ideas?

**Comment by rfuchs** [comment]
Sounds like a problem with your code base. Make sure your build directory is clean before rebuilding. Otherwise post log, or use prebuilt packages.

**Comment by nicoonline** [comment]
![image](https://user-images.githubusercontent.com/2115195/157286138-7b855cb8-f8f9-46a4-a2a1-81a61771d620.png)
make[2]: Entering directory `/var/instapp/rtp-engine/rtp6.5.13/daemon'
cc  -g -Wall -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include           -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include     -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -DWITH_TRANSCODING -DHAVE_BCG729   -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DRTPENGINE_VERSION="\"git-mr6.5.13-c348006\"" -O3 -o rtpengine main.o kernel.o poller.o aux.o control_tcp.o streambuf.o call.o control_udp.o redis.o bencode.o cookie_cache.o udp_listener.o control_ng.o sdp.o stun.o rtcp.o crypto.o rtp.o call_interfaces.o dtls.o log.o cli.o graphite.o ice.o socket.o media_socket.o homer.o recording.o statistics.o cdr.o ssrc.o iptables.o tcp_listener.o codec.o load.o dtmf.o loglib.o auxlib.o rtplib.o str.o codeclib.o resample.o -lm -lglib-2.0   -pthread -lgthread-2.0 -lrt -lglib-2.0   -lz   -lpcre   -lcrypto   -lssl -lcrypto   -levent_pthreads -levent   -lpcap -lxmlrpc_client   -lxmlrpc   -lxmlrpc_util   -lhiredis -pthread -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0   -L/lib64 -liptc   -lavcodec   -lavformat   -lavutil   -lswresample   -lavfilter   -lbcg729  
sdp.o: In function `sdp_replace':
/var/instapp/rtp-engine/rtp6.5.13/daemon/sdp.c:2125: undefined reference to `proto_is_rtp'
collect2: ld returned 1 exit status
make[2]: *** [rtpengine] Error 1

**Comment by rfuchs** [comment]
`-DRTPENGINE_VERSION="\"git-mr6.5.13-c348006\""`

does not look like mr8.5 to me...

**Comment by nicoonline** [comment]
Nop. As i explained, i tried to change the 6.5 code directly in sdp.c

About the compilator error in 8.5.5;
make[2]: Entering directory `/var/instapp/rtp-engine/rtp8.5.5/daemon'
cc  -g -Wall -Wstrict-prototypes -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include           -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include     -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg     -DWITH_TRANSCODING -DHAVE_BCG729   -I/usr/include/mysql -m64  -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DRTPENGINE_VERSION="\"git-mr8.5.5-77d93bc\"" -O3 -o rtpengine main.o kernel.o poller.o aux.o control_tcp.o call.o control_udp.o redis.o bencode.o cookie_cache.o udp_listener.o control_ng.strhash.o sdp.strhash.o stun.o rtcp.o crypto.o rtp.o call_interfaces.strhash.o dtls.o log.o cli.o graphite.o ice.o media_socket.o homer.o recording.o statistics.o cdr.o ssrc.o iptables.o tcp_listener.o codec.o load.o dtmf.o timerthread.o media_player.o jitter_buffer.o t38.o loglib.o auxlib.o rtplib.o str.o socket.o streambuf.o ssllib.o dtmflib.o codeclib.o resample.o -lm -lglib-2.0   -pthread -lgthread-2.0 -lrt -lglib-2.0   -lz   -lpcre   -lcrypto   -lssl -lcrypto   -levent_pthreads -levent   -lpcap -lxmlrpc_client   -lxmlrpc   -lxmlrpc_util   -lhiredis -pthread -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0   -L/lib64 -liptc   -lavcodec   -lavformat   -lavutil   -lswresample   -lavfilter   -lspandsp -ltiff -lm   -lbcg729   -L/usr/lib64/mysql -lmysqlclient -lpthread -lm -lrt -ldl
control_tcp.o: In function `control_tcp_free':
/var/instapp/rtp-engine/rtp8.5.5/daemon/control_tcp.c:162: undefined reference to `pcre_free_study'
control_udp.o: In function `control_udp_free':
/var/instapp/rtp-engine/rtp8.5.5/daemon/control_udp.c:139: undefined reference to `pcre_free_study'
call_interfaces.strhash.o: In function `call_interfaces_free':
/var/instapp/rtp-engine/rtp8.5.5/daemon/call_interfaces.strhash.c:2381: undefined reference to `pcre_free_study'
/var/instapp/rtp-engine/rtp8.5.5/daemon/call_interfaces.strhash.c:2386: undefined reference to `pcre_free_study'
auxlib.o: In function `config_load':
/var/instapp/rtp-engine/rtp8.5.5/daemon/auxlib.c:257: undefined reference to `g_option_context_parse_strv'
collect2: ld returned 1 exit status
make[2]: *** [rtpengine] Error 1
make[2]: Leaving directory `/var/instapp/rtp-engine/rtp8.5.5/daemon'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/var/instapp/rtp-engine/rtp8.5.5/daemon'
make: *** [all] Error 2
[root@proxy1 rtp8.5.5]#

**Comment by rfuchs** [comment]
Probably an old version of glib and possible libpcre.

proto_is_rtp is defined here: https://github.com/sipwise/rtpengine/blob/mr8.5/include/media_socket.h#L199

Anyway, this is not a code issue.
