### ISSUE TITLE
run rtpengine as non-root and `FAILED TO DELETE KERNEL TABLE 0 (Permission denied)`

### ISSUE THREAD

**Issue by tommasinigiovanni** [sipwise/rtpengine#1466]
I received `rtpengine[40117]: ERR: [core] FAILED TO CREATE KERNEL TABLE 0 (No such file or directory), KERNEL FORWARDING DISABLED` when I start rtpengine

Ubuntu 20.04
rtpengine: version 10.4.0.0+0~mr10.4.0.0 git-master-799773b5

If i change my `/lib/systemd/system/ngcp-rtpengine-daemon.service`
from 

```
...
PIDFile=/run/rtpengine/ngcp-rtpengine-daemon.pid
User=rtpengine
Group=rtpengine
AmbientCapabilities=CAP_NET_ADMIN CAP_SYS_NICE
...
```

to
```
...
PIDFile=/run/rtpengine/ngcp-rtpengine-daemon.pid
User=root
Group=root
AmbientCapabilities=CAP_NET_ADMIN CAP_SYS_NICE
...
```
everything starts to work in the right way
```
...
 rtpengine[1791]: INFO: [crypto] Generating new DTLS certificate
 rtpengine[1791]: INFO: [core] Startup complete, version 10.4.0.0+0~mr10.4.0.0 git-master-799773b5
...
```
@rfuchs why in this your commit https://github.com/sipwise/rtpengine/commit/30c2de8e0f6b6944cfc7a577064e3f2bf4692060 you decide to "run rtpengine as non-root"?
And how can I use these settings and don't have problems with `FAILED TO DELETE KERNEL TABLE 0 (Permission denied)`

Thanks a lot
Giovanni

**Comment by rfuchs** [comment]
If you don't use the included scripts to manage the kernel module (see https://github.com/sipwise/rtpengine/blob/master/debian/ngcp-rtpengine-iptables-setup#L17 and https://github.com/sipwise/rtpengine/blob/master/debian/ngcp-rtpengine-daemon.default#L5) then you need to make sure the module load parameters match the systemd unit (either through /etc/modprobe.d/ or manually when you modprobe). Or use a systemd unit override to make it run a root anyway.

Not a code issue, closing. Use the mailing list next time.
