### ISSUE TITLE
Kernel module error when using --table flag

### ISSUE THREAD

**Issue by mkl262** [sipwise/rtpengine#1467]
Hi,
Im trying to run multiple instances of RTPengine on my Ubuntu AWS instance, but when I specify the `--table=10` flag the 
following error is logged:
```
Thu, Mar 10 2022 12:36:11 pm | [1646908571.703142] ERR: [core] FAILED TO DELETE KERNEL TABLE 10 (Permission denied), KERNEL FORWARDING DISABLED
Thu, Mar 10 2022 12:36:11 pm | [1646908571.703158] CRIT: [core] Userspace fallback disallowed - exiting
```
if I remove the `--table` flag, then the process starts up without any errors, even with the `--no-fallback` flag.

parametes: `-E --interface=external/<instance ip>!<elastic ip> --listen-ng=22222 --listen-cli=9900 --listen-udp=12222 --timeout=10 --silent-timeout=10 --pidfile=/var/run/rtpengine.pid --tos=184 --port-min=20000 --port-max=39999 --no-fallback --log-level=5 --log-stderr --foreground --table=10`

Kernel: `5.13.0-1017-aws`
rtpengine version: `9.5.4.1+0~mr9.5.4.1`

**Comment by rfuchs** [comment]
Do you have a config file (in /etc/rtpengine/) that sets the table= option?

What user/group is the daemon running as?

What user/group is the kernel module using? (see /proc/rtpengine/)

**Comment by mkl262** [comment]
/etc/rtpengine contains only the sample files

daemon and module are both root

**Comment by rfuchs** [comment]
Omitting --table= would result in userspace-only operation then, and wouldn't even try to use the kernel module (the default is table=-1).

No idea then. Something specific to AWS maybe? You can manually play with the kernel module to see what happens:

```
# echo "add 0" > /proc/rtpengine/control
# echo "del 0" > /proc/rtpengine/control
# echo "add 10" > /proc/rtpengine/control
# echo "del 10" > /proc/rtpengine/control
```

and so on. If this works as root then the rtpengine daemon should also be able to do it as root.
