### ISSUE TITLE
QUESTION Inject DTMF

### ISSUE THREAD

**Issue by volga629-1** [sipwise/rtpengine#1468]
Hello Everyone,
I am trying inject DTMF on specific  call where are end point use SRTP and getting error  

```
ERROR:rtpengine:rtpe_function_call: proxy replied with error: Monologue has no media capable of DTMF injection
ERROR:rtpengine:rtpe_function_call: proxy replied with error: No SSRC context present for DTMF injection
```

Version

```
rtpengine-9.5.1.2-8.fc32.x86_64

```

**Comment by rfuchs** [comment]
There must be some sort of transcoding active for DTMF injection to work. Usually this is achieved by supplying the flag `inject-DTMF` during call setup.

Please don't use the Github issue tracker to ask questions. We have a mailing list for that.

**Comment by volga629-1** [comment]
Inject-DTMF flag is specified in offer and answer.

Please see attached rtpengine debug 


[rtpengine-debug-14Mon2022.txt](https://github.com/sipwise/rtpengine/files/8255933/rtpengine-debug-14Mon2022.txt)
