### ISSUE TITLE
how to inject dtmf

### ISSUE THREAD

**Issue by johandeclercqdemocon** [sipwise/rtpengine#1469]
Richard, 

can you explain what I do wrong here.  I try to inject dmt but I don't see an event. 

Mar 22 14:47:02 debian10opensips31 rtpengine[3344]: INFO: [aQpErwnm3xdbXAP3l6rFhg..]: [control] Received command 'play DTMF' from 127.0.0.1:55318
Mar 22 14:47:02 debian10opensips31 rtpengine[3344]: DEBUG: [aQpErwnm3xdbXAP3l6rFhg..]: [control] Dump for 'play DTMF' from 127.0.0.1:55318: { "code": "0", "call-id": "aQpErwnm3xdbXAP3l6rFhg..", "received-from": [ "IP4", "192.168.68.109" ], "from-tag": "27997708", "to-tag": "e0203e60", "command": "play DTMF" }
Mar 22 14:47:02 debian10opensips31 rtpengine[3344]: DEBUG: [aQpErwnm3xdbXAP3l6rFhg..]: [core] DTMF injection: Using PT 95/-1 -> -1 (0), SSRC 7da7415
Mar 22 14:47:02 debian10opensips31 rtpengine[3344]: WARNING: [aQpErwnm3xdbXAP3l6rFhg..]: [control] Protocol error in packet from 127.0.0.1:55318: No suitable codec handler present [d4:code1:07:call-id24:aQpErwnm3xdbXAP3l6rFhg..13:received-froml3:IP414:192.168.68.109e8:from-tag8:279977086:to-tag8:e0203e607:command9:play DTMF]
[forrichardd.zip](https://github.com/sipwise/rtpengine/files/8327211/forrichardd.zip)

Let me know what else I can do to help.

**Comment by rfuchs** [comment]
Looks like you're trying to play DTMF before any media has passed through rtpengine. Some media needs to pass through before any DTMF can be injected.

Since we have a mailing list now, please don't use the Github issue tracker as a support forum.

**Comment by johandeclercqdemocon** [comment]
Okay, I made an account here https://lists.sipwise.com/mailman/listinfo/spce-user_lists.sipwise.com

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Richard Fuchs ***@***.***>
Verzonden: Tuesday, March 22, 2022 8:18:23 PM
Aan: sipwise/rtpengine ***@***.***>
CC: johandeclercqdemocon ***@***.***>; Author ***@***.***>
Onderwerp: Re: [sipwise/rtpengine] how to inject dtmf (Issue #1469)


Looks like you're trying to play DTMF before any media has passed through rtpengine. Some media needs to pass through before any DTMF can be injected.

Since we have a mailing list now, please don't use the Github issue tracker as a support forum.

**Comment by rfuchs** [comment]
The dedicated rtpengine mailing list is at https://rtpengine.com/mailing-list
