### ISSUE TITLE
dtmf transcoding issue with 10.3.1.7

### ISSUE THREAD

**Issue by thomas414** [sipwise/rtpengine#1470]
Hi Richard,

we are having a problem with dtmf transcoding on the version 10.3.1.7, the same call works on 10.2.1.0.

On version 10.2.1.0:
Invite: 96 telephone-event -> rtpengine -> 96 telephone-event
Ok:     96 telephone-event <- rtpengine <- 101 telephone-event

On version 10.3.1.7:
Invite: 96 telephone-event -> rtpengine -> 96 telephone-event
Ok:                                      <- rtpengine <- 101 telephone-event

Log is attached and in nok log i can see entry, which explains the behavior:

`Not adding stray answer codec telephone-event/8000 (101)`

If you need it i can also send pcap trace.
Question now is what version behaves correct and which not? And if 10.3.1.7 is correct, what flags would we need to change in order to restore functionality?

[dtmf_ok.txt](https://github.com/sipwise/rtpengine/files/8331559/dtmf_ok.txt)
[dtmf_nok.txt](https://github.com/sipwise/rtpengine/files/8331560/dtmf_nok.txt)

**Comment by rfuchs** [comment]
The logs you posted don't include the SDPs and so aren't very helpful. But from your description I'd say that 10.3 is behaving correctly. The answer SDP cannot include RTP payload types that were not offered. Using a different payload type number (101 instead of 96) is incorrect behaviour by the answering client.

**Comment by thomas414** [comment]
Thank you, we thought so too but wanted to make sure. We will look into the clients settings and see if we can change the behavior.

**Comment by barryo** [comment]
Hi @rfuchs - I hope you don't mind me poking this issue. I've the same problem as @thomas414 where the recipient changes the payload type for `telephone-event/8000` and I also don't think we had this problem on previous versions (recently upgraded from 8.x).

rfc3264 is a bit circumspect in the section re [generating a unicast stream answer](https://datatracker.ietf.org/doc/html/rfc3264#section-6.1):

>    In the case of RTP, if a particular codec was referenced with a
>    specific payload type number in the offer, that same payload type
>    number SHOULD be used for that codec in the answer.

And it doesn't suggest how to handle the case when not followed! 

Just wondering if there was a specific change to break this that can be reversed or is ths behavior now set in stone?

Thanks!

**Comment by rfuchs** [comment]
@barryo  In previous versions we (sort-of) supported asymmetric codec setup, meaning clients which were sending different codecs than they were receiving (or with different payload type numbers). But this was causing all kinds of problems with other clients that did not expect asymmetric codecs and were using a strict offer/answer routine, and in general it made deciding which codecs to use in which situation really difficult. So we decided to scrap this and completely rework the internal codec negotiation code to also use a proper offer/answer like most clients do. This made everything simpler and cleaner and eliminated a bunch of buggy corner cases that previously were either broken or made awkward workarounds necessary. So this is definitely not going to be reverted.

In case you're curious, this is the relevant change: https://github.com/sipwise/rtpengine/commit/1d387b98efbbb410b3b0c32a5a25435c65f4c098

**Comment by barryo** [comment]
Thanks for that explanation @rfuchs - very helpful to understand the change. And knowing that, I'd never ask you to add back hacks! Thanks for the reference also.
