### ISSUE TITLE
replace-session-name example

### ISSUE THREAD

**Issue by syco** [sipwise/rtpengine#1472]
Hi,

I'm using the latest rtpengine with opensips 3.2

I'm sending the flag "replace-session-name" in  the rtpengine_offer,
but the s= line doesn't change on the second leg of the call.

How should I use it?
Thanks

**Comment by rfuchs** [comment]
As per the docs, this flag makes sure the s= line remains the same and doesn't change. So the content is only changed if there's a reason to (in order to keep it unchanged).

Don't use the Github issue tracker to ask questions. Use the mailing list.
