### ISSUE TITLE
comfort noise question

### ISSUE THREAD

**Issue by davehorton** [sipwise/rtpengine#1475]
I have rtpengine with a pbx on one side and a twilio elastic trunk on the other.  My pbx generates discontinuous audio (ie only sends audio packets when it is playing a file) and I am wondering if I can get rtpengine to generate silence packets (because twilio, when receiving this discontinous audio does a horrible job of generating very noisy/distracting comfort noise). 

I see some of the dtx params seem like they could do this, but I also notice the docs say "applicable to transcoded audio streams only".  In my case there rtpengine is not transcoding, it is G711 in and out.

So is what I want possible:
- to fill in blanks in discontinuous audio with silence packets (in this case, preferably pure silence or if it must be comfort noise something with minimal noise) in the case where transcoding is not being done on a call.
- also, is it possibly to specify this behavior for only one direction of a call?

**Comment by rfuchs** [comment]
The only way to do this is to force back-to-back transcoding from/to G.711, at a heavy CPU penalty of course (especially over kernel-based forwarding).

Currently there's no way to control DTX behaviour for individual streams. If you want to go the transcoding route, I suppose it's possible to force transcoding directionally (and have the other direction passthrough). There isn't currently a flag to explicitly force transcoding, but I suppose it shouldn't be too difficult to add one.

We have a mailing list now (https://rtpengine.com/mailing-list) for generic questions like this. The Github issue tracker is reserved for code issues.
