### ISSUE TITLE
TLS support for ng Control Protocol

### ISSUE THREAD

**Issue by sammekh** [sipwise/rtpengine#1480]
Hello all!

Currently, ng protocol is supported by transports (plain UDP, plain TCP, HTTP, WebSocket), is there any plan to enable TLS as well or is there any reason why it hasn't or won't be added in the future?

**Comment by rfuchs** [comment]
Use can use the HTTPS or WSS transports if you want to use TLS. There's no plans to add support for TLS to the TCP or UDP transports.

Don't use the Github issue track to ask question. We have a mailing list for that purpose.
