### ISSUE TITLE
Issue restoring redis subscriptions

### ISSUE THREAD

**Issue by smititelu** [sipwise/rtpengine#1486]
Hello, I am getting the following errors with latest code, when the notification thread tries to restore from redis:
```
ERR: [15-7891@217.72.194.22]: [core] Key in json not found:subscriptions-oa-0
ERR: [15-7891@217.72.194.22]: [core] Key in json not found:subscriptions-0
WARNING: [15-7891@217.72.194.22]: [core] Failed to restore call ID '15-7891@217.72.194.22' from Redis: failed to link tags
```
I tried commenting out that part in ```json_link_tags()``` where it restores subscriptions and I get no errors anymore, and redis restore works again from notifications thread.

Can we make the subscriptions restore optional? E.g. don't ```return -1``` if subscriptions restore fails but just ```continue```

Thank you,
Stefan

**Comment by rfuchs** [comment]
Is this with mixing different versions of rtpengine?

**Comment by smititelu** [comment]
No, we are using the same packages on both rtpengine machines.

**Comment by rfuchs** [comment]
Hm ok, wonder why there's no subscriptions listed then 🤔

**Comment by smititelu** [comment]
Is this something that needs to be enabled/disabled from config? I am not aware of using any subscriptions, so far, so I think we are just using default.

**Comment by rfuchs** [comment]
No, subscriptions are used to associate offer/answer sides for normal calls. They're written to Redis in `redis_encode_json`:

```
			snprintf(tmp, sizeof(tmp), "subscriptions-%u", ml->unique_id);
			json_builder_set_member_name(builder, tmp);
			json_builder_begin_array(builder);
			for (k = ml->subscriptions.head; k; k = k->next) {
...
```

So it's quite strange that this is missing from the JSON unless the JSON was written by an older version.

**Comment by smititelu** [comment]
I have ngrep'ed on port 6379, on rtpenigne which gets the redis notifys. Indeed I can see the subscriptions strings:
```
..."subscriptions-0":["1/0/1/0/0"],"other_tags-1":["0"],"branches-1":[],"medias-1":["0"],"ssrc_table-1":[],"subscriptions-1":["0/0/1/0/0"],....
```
This should mean it cannot restore them properly.

**Comment by rfuchs** [comment]
Are you able to try and see if 0da7a06 fixes it for you?

**Comment by smititelu** [comment]
Yes, it solves the issue. Thank you.
