### ISSUE TITLE
SDP with two audio stream causes rtpengine to switch from SAVP to AVP during re-INVITE

### ISSUE THREAD

**Issue by henningw** [sipwise/rtpengine#1489]
In certain situation an SDP body with two audio stream causes rtpengine to switch from SAVP to AVP during processing of an re-INVITE. It might be related to the two m=audio lines, that also uses the same port in certain cases. Expected behaviour would be that rtpengine stays with two way SRTP transmission.

The RFC 4566 says for that scenario:

_The semantics of multiple "m=" lines using the same transport address are undefined._ 

Scenario: freeswitch <-> Kamailio Proxy <-> snom UA

rtpengine version: 8.5.8.1, problem also occurred with 9.0.x version

Thanks for your input in advance.

INVITE freeswitch -> Proxy

v=0
o=anonymous 1651545491 1651545492 IN IP4 10.100.200.167
s=anonymous
c=IN IP4 10.100.200.167
t=0 0
m=audio 30362 RTP/AVP 8 101
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=ptime:20

INVITE Proxy -> snom

v=0
o=anonymous 1651545491 1651545492 IN IP4 185.135.XX.XX
s=anonymous
c=IN IP4 185.135.XX.XX
t=0 0
m=audio 21628 RTP/SAVP 8 101
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=rtcp:21629
a=rtcp-mux
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:YvlwuL9G3iDjpMTsBh4eschn0KFWWPTVJb0u29Wa
a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:hHK6/wmzzBXYXmoZq27OMjRJMcSxvBbpx3pDA+aT
a=crypto:3 AES_192_CM_HMAC_SHA1_80 inline:0ghzfAEElCQENzV80a+xVr+tRFjAZ4RH/pSH4Prqre+w1ZVcaxU=
a=crypto:4 AES_192_CM_HMAC_SHA1_32 inline:iTNmeyXUJfvZ/yA/JUUlXqSIsASb4t227RCsTr7Bw/g/XI6U/OM=
a=crypto:5 AES_256_CM_HMAC_SHA1_80 inline:WLiE09KNv8oHSfucYtVPpHkcD/GA34RAWiB8AQX0Puf5PBRQsBsdXD1nQgYRpA==
a=crypto:6 AES_256_CM_HMAC_SHA1_32 inline:4OdxdRhid5vh/Td35B46bGQXgRE3J9olj67MdYiNtKDzdzD5RtiH169vxuxh8Q==
a=ptime:20

200 OK snom -> Proxy

v=0
o=root 1151103358 1151103359 IN IP4 192.168.110.156
s=call
c=IN IP4 192.168.110.156
t=0 0
m=audio 52462 RTP/SAVP 8 101
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=ptime:20
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:gYLlgA9aFNYF+DXJzueWHb0gm8Y875SRkl85/Xv4
a=sendrecv

200 OK Proxy -> freeswitch

v=0
o=root 1151103358 1151103359 IN IP4 10.100.200.170
s=call
c=IN IP4 10.100.200.170
t=0 0
m=audio 22140 RTP/AVP 8 101
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=rtcp:22141
a=ptime:20

**Now SRTP is flowing in both directions between snom and Proxy**

re-INVITE snom -> Proxy

v=0
o=root 1151103358 1151103360 IN IP4 192.168.110.156
s=call
c=IN IP4 192.168.110.156
t=0 0
m=audio 52462 RTP/AVP 9 0 8 3 99 111 18 101
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:3 GSM/8000
a=rtpmap:99 G726-32/8000
a=rtpmap:111 AAL2-G726-32/8000
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=ptime:20
a=sendonly
m=audio 52462 RTP/SAVP 9 0 8 3 99 111 18 101
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:gYLlgA9aFNYF+DXJzueWHb0gm8Y875SRkl85/Xv4
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:3 GSM/8000
a=rtpmap:99 G726-32/8000
a=rtpmap:111 AAL2-G726-32/8000
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=ptime:20
a=sendonly

re-INVITE Proxy -> freeswitch

v=0
o=root 1151103358 1151103361 IN IP4 10.100.200.170
s=call
c=IN IP4 10.100.200.170
t=0 0
m=audio 22140 RTP/AVP 9 0 8 3 99 111 18 101
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:3 GSM/8000
a=rtpmap:99 G726-32/8000
a=rtpmap:111 AAL2-G726-32/8000
a=rtpmap:18 G729/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:18 annexb=no
a=fmtp:101 0-15
a=sendrecv
a=rtcp:22141
a=ptime:20
m=audio 0 RTP/AVP 9 0 8 3 99 111 18 101
m=audio 22172 RTP/AVP 9 0 8 3 99 111 18 101
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:3 GSM/8000
a=rtpmap:99 G726-32/8000
a=rtpmap:111 AAL2-G726-32/8000
a=rtpmap:18 G729/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:18 annexb=no
a=fmtp:101 0-15
a=sendrecv
a=rtcp:22173
a=ptime:20

200 OK freeswitch -> Proxy

v=0
o=anonymous 1651545491 1651545493 IN IP4 10.100.200.167
s=anonymous
c=IN IP4 10.100.200.167
t=0 0
m=audio 30362 RTP/AVP 8 101
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=recvonly
a=ptime:20
a=rtcp:30363 IN IP4 10.100.200.167
m=audio 0 RTP/AVP 19

200 OK Proxy -> snom

v=0
o=anonymous 1651545491 1651545493 IN IP4 185.135.52.68
s=anonymous
c=IN IP4 185.135.XX.XX
t=0 0
m=audio 21628 RTP/SAVP 8 101
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=recvonly
a=rtcp:21629
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:YvlwuL9G3iDjpMTsBh4eschn0KFWWPTVJb0u29Wa
a=ptime:20
m=audio 0 RTP/SAVP 19

**Now rtpengine switches from SRTP to RTP, snom stays with SRTP**

rtpengine flags in re-INVITE case: 
replace-origin replace-session-connection via-branch=extra ICE=remove direction=voip direction=public RTP/SAVP rtcp-mux-accept rtcp-mux-offer DTLS=off SDES-no-F8_128_HMAC_SHA1_80 SDES-no-F8_128_HMAC_SHA1_32 SDES-no-NULL_HMAC_SHA1_80 SDES-no-NULL_HMAC_SHA1_32 SDES-pad

re-INVITE snom -> Proxy

v=0
o=root 1151103358 1151103361 IN IP4 192.168.110.156
s=call
c=IN IP4 192.168.110.156
t=0 0
m=audio 52462 RTP/AVP 9 0 8 3 99 111 18 101
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:3 GSM/8000
a=rtpmap:99 G726-32/8000
a=rtpmap:111 AAL2-G726-32/8000
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=ptime:20
a=sendrecv
m=audio 0 RTP/SAVP 9 0 8 3 99 111 18 101
m=audio 52462 RTP/SAVP 9 0 8 3 99 111 18 101
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:gYLlgA9aFNYF+DXJzueWHb0gm8Y875SRkl85/Xv4
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:3 GSM/8000
a=rtpmap:99 G726-32/8000
a=rtpmap:111 AAL2-G726-32/8000
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=ptime:20
a=sendrecv

re-INVITE Proxy -> freeswitch

v=0
o=root 1151103358 1151103361 IN IP4 10.100.200.170
s=call
c=IN IP4 10.100.200.170
t=0 0
m=audio 22140 RTP/AVP 9 0 8 3 99 111 18 101
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:3 GSM/8000
a=rtpmap:99 G726-32/8000
a=rtpmap:111 AAL2-G726-32/8000
a=rtpmap:18 G729/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:18 annexb=no
a=fmtp:101 0-15
a=sendrecv
a=rtcp:22141
a=ptime:20
m=audio 0 RTP/AVP 9 0 8 3 99 111 18 101
m=audio 22172 RTP/AVP 9 0 8 3 99 111 18 101
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:3 GSM/8000
a=rtpmap:99 G726-32/8000
a=rtpmap:111 AAL2-G726-32/8000
a=rtpmap:18 G729/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:18 annexb=no
a=fmtp:101 0-15
a=sendrecv
a=rtcp:22173
a=ptime:20

200 OK freeswitch -> Proxy

v=0
o=anonymous 1651545491 1651545494 IN IP4 10.100.200.167
s=anonymous
c=IN IP4 10.100.200.167
t=0 0
m=audio 30362 RTP/AVP 8 101
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=ptime:20
a=rtcp:30363 IN IP4 10.100.200.167
m=audio 0 RTP/AVP 19
m=audio 0 RTP/AVP 19

200 OK Proxy -> snom

v=0
o=anonymous 1651545491 1651545494 IN IP4 185.135.XX.XX
s=anonymous
c=IN IP4 185.135.XX.XX
t=0 0
m=audio 21628 RTP/SAVP 8 101
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=rtcp:21629
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:YvlwuL9G3iDjpMTsBh4eschn0KFWWPTVJb0u29Wa
a=ptime:20
m=audio 0 RTP/SAVP 19
m=audio 0 RTP/SAVP 19

**Comment by rfuchs** [comment]
This is a non-standard usage of multiple media sections to facilitate optional SRTP which we don't support. There's no RFC for this that I'm aware of. We do support OSRTP though, which is the standard way (RFC 8643) of doing this.

**Comment by henningw** [comment]
Thank you for the reply @rfuchs. Actually I would like to rtpengine to ignore this additional SDP case and just stay with SRTP. But if this is currently not supported in rtpengine, I need to find another way.

**Comment by rfuchs** [comment]
No that is not supported. Media sections must be matched up in the order that they're given, and so the snom effectively does an RTP re-invite for a stream that previously was SRTP. Therefore that stream is switched to RTP.

**Comment by henningw** [comment]
Thank you, close
