### ISSUE TITLE
rtpengine No voice and Failed to init DTLS connection: srtp unknown protection profile 

### ISSUE THREAD

**Issue by zsmin1982** [sipwise/rtpengine#1490]
My call model is as follows
jssip+webrtc(UAC,wss)<---->NAT1<----->NAT2<--->opensips+rtpengine（UAS）<--UDP---->freeswitch<---->PSTN
now The signaling interaction was successful but the media stream establishment failed.no voice stream with the UAC and the UAS.
but the stun and stun response in UAC and UAS is success. i can confirm the network is no problem.
opensips version:2.4.8
rtpengine version:10.0.1.1
openssl version:1.1.1O

the rtpengine log level 7 like this:
May 12 18:52:50 crm_reg_server rtpengine[24850]: INFO: [0b4mng9ugn8a9sm0hrph]: [control] Received command 'offer' from 172.18.51.115:34630
May 12 18:52:50 crm_reg_server rtpengine[24850]: NOTICE: [0b4mng9ugn8a9sm0hrph]: [core] Creating new call
May 12 18:52:50 crm_reg_server rtpengine[24850]: ERR: [0b4mng9ugn8a9sm0hrph]: [crypto] Failed to init DTLS connection: srtp unknown protection profile
May 12 18:52:50 crm_reg_server rtpengine[24850]: ERR: [0b4mng9ugn8a9sm0hrph]: [crypto] Failed to init DTLS connection: srtp unknown protection profile
May 12 18:52:50 crm_reg_server rtpengine[24850]: WARNING: [0b4mng9ugn8a9sm0hrph]: [core] Ignoring updated remote endpoint  as the local socket is IPv4
May 12 18:52:50 crm_reg_server rtpengine[24850]: INFO: [0b4mng9ugn8a9sm0hrph]: [control] Replying to 'offer' from 172.18.51.115:34630 (elapsed time 0.007662 sec)
May 12 18:52:50 crm_reg_server rtpengine[24850]: INFO: [0b4mng9ugn8a9sm0hrph]: [control] Received command 'answer' from 172.18.51.115:40883
May 12 18:52:50 crm_reg_server rtpengine[24850]: ERR: [0b4mng9ugn8a9sm0hrph]: [crypto] Failed to init DTLS connection: srtp unknown protection profile
May 12 18:52:50 crm_reg_server rtpengine[24850]: ERR: [0b4mng9ugn8a9sm0hrph]: [crypto] Failed to init DTLS connection: srtp unknown protection profile
May 12 18:52:50 crm_reg_server rtpengine[24850]: INFO: [0b4mng9ugn8a9sm0hrph]: [control] Replying to 'answer' from 172.18.51.115:40883 (elapsed time 0.006664 sec)
May 12 18:52:51 crm_reg_server rtpengine[24850]: INFO: [0b4mng9ugn8a9sm0hrph port 31808]: [ice] ICE negotiated: peer for component 1 is 183.233.214.126:56628
May 12 18:52:51 crm_reg_server rtpengine[24850]: INFO: [0b4mng9ugn8a9sm0hrph port 31808]: [ice] ICE negotiated: local interface 172.18.51.115
May 12 18:52:55 crm_reg_server rtpengine[24850]: INFO: [0b4mng9ugn8a9sm0hrph port 31795]: [core] Confirmed peer address as 120.77.3.170:56927
May 12 18:52:55 crm_reg_server rtpengine[24850]: [0b4mng9ugn8a9sm0hrph] version=2, padding=0, count=1, payloadtype=201, length=7, ssrc=1960417946, ssrc=0, fraction_lost=255, packet_loss=1, last_seq=0, jitter=0, last_sr=0, delay_since_last_sr=0, version=2, padding=0, count=1, payloadtype=202, length=14
May 12 18:52:55 crm_reg_server rtpengine[24850]: ERR: [0b4mng9ugn8a9sm0hrph port 31795]: [rtcp] SRTCP output wanted, but no crypto suite was negotiated
May 12 18:52:55 crm_reg_server rtpengine[24850]: ERR: [0b4mng9ugn8a9sm0hrph port 31795]: [core] Failed to get stream stats from kernel: No such file or directory

May 12 18:52:55 crm_reg_server rtpengine[24850]: ERR: [0b4mng9ugn8a9sm0hrph port 31795]: [core] Failed to delete relay stream from kernel: No such file or directory
May 12 18:52:59 crm_reg_server rtpengine[24850]: INFO: [0b4mng9ugn8a9sm0hrph port 31795]: [core] Confirmed peer address as 120.77.3.170:56927
May 12 18:52:59 crm_reg_server rtpengine[24850]: [0b4mng9ugn8a9sm0hrph] version=2, padding=0, count=1, payloadtype=201, length=7, ssrc=1960417946, ssrc=0, fraction_lost=0, packet_loss=1, last_seq=0, jitter=0, last_sr=0, delay_since_last_sr=0, version=2, padding=0, count=1, payloadtype=202, length=14
May 12 18:52:59 crm_reg_server rtpengine[24850]: INFO: [0b4mng9ugn8a9sm0hrph port 31794]: [core] Confirmed peer address as 120.77.3.170:56926
May 12 18:52:59 crm_reg_server rtpengine[24850]: ERR: [0b4mng9ugn8a9sm0hrph port 31794]: [core] SRTP output wanted, but no crypto suite was negotiated
May 12 18:52:59 crm_reg_server rtpengine[24850]: INFO: [0b4mng9ugn8a9sm0hrph port 31794]: [core] Kernelizing media stream: 120.77.3.170:56926 -> 172.18.51.115:31794 -> 183.233.214.126:56628
May 12 18:52:59 crm_reg_server rtpengine[24850]: WARNING: [0b4mng9ugn8a9sm0hrph port 31794]: [core] No support for kernel packet forwarding available (encryption cipher or HMAC not supported by kernel module)
May 12 18:52:59 crm_reg_server rtpengine[24850]: ERR: [0b4mng9ugn8a9sm0hrph port 31794]: [core] Failed to push relay stream to kernel: Invalid argument
May 12 18:52:59 crm_reg_server rtpengine[24850]: ERR: [0b4mng9ugn8a9sm0hrph port 31794]: [core] Failed to get stream stats from kernel: No such file or directory
May 12 18:52:59 crm_reg_server rtpengine[24850]: ERR: [0b4mng9ugn8a9sm0hrph port 31794]: [core] Failed to delete relay stream from kernel: No such file or directory
May 12 18:52:59 crm_reg_server rtpengine[24850]: INFO: [0b4mng9ugn8a9sm0hrph port 31794]: [core] Confirmed peer address as 120.77.3.170:56926
May 12 18:52:59 crm_reg_server rtpengine[24850]: INFO: [0b4mng9ugn8a9sm0hrph port 31794]: [core] Kernelizing media stream: 120.77.3.170:56926 -> 172.18.51.115:31794 -> 183.233.214.126:56628
May 12 18:52:59 crm_reg_server rtpengine[24850]: WARNING: [0b4mng9ugn8a9sm0hrph port 31794]: [core] No support for kernel packet forwarding available (encryption cipher or HMAC not supported by kernel module)
May 12 18:52:59 crm_reg_server rtpengine[24850]: ERR: [0b4mng9ugn8a9sm0hrph port 31794]: [core] Failed to push relay stream to kernel: Invalid argument
May 12 18:53:00 crm_reg_server rtpengine[24850]: INFO: [0b4mng9ugn8a9sm0hrph]: [control] Received command 'answer' from 172.18.51.115:40883
May 12 18:53:00 crm_reg_server rtpengine[24850]: ERR: [0b4mng9ugn8a9sm0hrph]: [core] Failed to get stream stats from kernel: No such file or directory
May 12 18:53:00 crm_reg_server rtpengine[24850]: ERR: [0b4mng9ugn8a9sm0hrph]: [core] Failed to delete relay stream from kernel: No such file or directory
May 12 18:53:00 crm_reg_server rtpengine[24850]: ERR: [0b4mng9ugn8a9sm0hrph]: [core] Failed to get stream stats from kernel: No such file or directory
May 12 18:53:00 crm_reg_server rtpengine[24850]: ERR: [0b4mng9ugn8a9sm0hrph]: [core] Failed to delete relay stream from kernel: No such file or directory
May 12 18:53:00 crm_reg_server rtpengine[24850]: ERR: [0b4mng9ugn8a9sm0hrph]: [crypto] Failed to init DTLS connection: srtp unknown protection profile
May 12 18:53:00 crm_reg_server rtpengine[24850]: ERR: [0b4mng9ugn8a9sm0hrph]: [crypto] Failed to init DTLS connection: srtp unknown protection profile
May 12 18:53:00 crm_reg_server rtpengine[24850]: INFO: [0b4mng9ugn8a9sm0hrph]: [control] Replying to 'answer' from 172.18.51.115:40883 (elapsed time 0.005561 sec)
May 12 18:53:03 crm_reg_server rtpengine[24850]: [0b4mng9ugn8a9sm0hrph] version=2, padding=0, count=1, payloadtype=200, length=12, ssrc=1960417946, ntp_sec=3861341583, ntp_fractions=122166049, rtp_ts=984377872, sender_packets=180, sender_bytes=28800, ssrc=0, fraction_lost=0, packet_loss=1, last_seq=0, jitter=0, last_sr=0, delay_since_last_sr=0, version=2, padding=0, count=1, payloadtype=202, length=14
May 12 18:53:04 crm_reg_server rtpengine[24850]: INFO: [0b4mng9ugn8a9sm0hrph port 31794]: [core] Confirmed peer address as 120.77.3.170:56926
May 12 18:53:04 crm_reg_server rtpengine[24850]: INFO: [0b4mng9ugn8a9sm0hrph port 31794]: [core] Kernelizing media stream: 120.77.3.170:56926 -> 172.18.51.115:31794 -> 183.233.214.126:56628
May 12 18:53:04 crm_reg_server rtpengine[24850]: WARNING: [0b4mng9ugn8a9sm0hrph port 31794]: [core] No support for kernel packet forwarding available (encryption cipher or HMAC not supported by kernel module)
May 12 18:53:04 crm_reg_server rtpengine[24850]: ERR: [0b4mng9ugn8a9sm0hrph port 31794]: [core] Failed to push relay stream to kernel: Invalid argument
May 12 18:53:07 crm_reg_server rtpengine[24850]: INFO: [0b4mng9ugn8a9sm0hrph port 31795]: [core] Confirmed peer address as 120.77.3.170:56927
May 12 18:53:07 crm_reg_server rtpengine[24850]: [0b4mng9ugn8a9sm0hrph] version=2, padding=0, count=1, payloadtype=200, length=12, ssrc=1960417946, ntp_sec=3861341587, ntp_fractions=208022446, rtp_ts=984410032, sender_packets=381, sender_bytes=60960, ssrc=0, fraction_lost=0, packet_loss=1, last_seq=0, jitter=0, last_sr=0, delay_since_last_sr=0, version=2, padding=0, count=1, payloadtype=202, length=14
May 12 18:53:08 crm_reg_server rtpengine[24850]: [0b4mng9ugn8a9sm0hrph] version=2, padding=0, count=1, payloadtype=200, length=12, ssrc=1960417946, ntp_sec=3861341588, ntp_fractions=293913201, rtp_ts=984418032, sender_packets=428, sender_bytes=68480, ssrc=0, fraction_lost=0, packet_loss=1, last_seq=0, jitter=0, last_sr=0, delay_since_last_sr=0, version=2, padding=0, count=1, payloadtype=202, length=14
May 12 18:53:09 crm_reg_server rtpengine[24850]: [0b4mng9ugn8a9sm0hrph] version=2, padding=0, count=1, payloadtype=200, length=12, ssrc=1960417946, ntp_sec=3861341589, ntp_fractions=379808252, rtp_ts=984426192, sender_packets=479, sender_bytes=76640, ssrc=0, fraction_lost=0, packet_loss=1, last_seq=0, jitter=0, last_sr=0, delay_since_last_sr=0, version=2, padding=0, count=1, payloadtype=202, length=14
May 12 18:53:10 crm_reg_server rtpengine[24850]: [0b4mng9ugn8a9sm0hrph] version=2, padding=0, count=1, payloadtype=200, length=12, ssrc=1960417946, ntp_sec=3861341590, ntp_fractions=465720483, rtp_ts=984434352, sender_packets=530, sender_bytes=84800, ssrc=0, fraction_lost=0, packet_loss=1, last_seq=0, jitter=0, last_sr=0, delay_since_last_sr=0, version=2, padding=0, count=1, payloadtype=202, length=14
May 12 18:53:10 crm_reg_server rtpengine[24850]: ERR: [0b4mng9ugn8a9sm0hrph port 31795]: [rtcp] SRTCP output wanted, but no crypto suite was negotiated
May 12 18:53:11 crm_reg_server rtpengine[24850]: [0b4mng9ugn8a9sm0hrph] version=2, padding=0, count=1, payloadtype=200, length=12, ssrc=1960417946, ntp_sec=3861341591, ntp_fractions=551624124, rtp_ts=984442512, sender_packets=581, sender_bytes=92960, ssrc=0, fraction_lost=0, packet_loss=1, last_seq=0, jitter=0, last_sr=0, delay_since_last_sr=0, version=2, padding=0, count=1, payloadtype=202, length=14
May 12 18:53:12 crm_reg_server rtpengine[24850]: [0b4mng9ugn8a9sm0hrph] version=2, padding=0, count=1, payloadtype=200, length=12, ssrc=1960417946, ntp_sec=3861341592, ntp_fractions=637566420, rtp_ts=984450672, sender_packets=632, sender_bytes=101120, ssrc=0, fraction_lost=0, packet_loss=1, last_seq=0, jitter=0, last_sr=0, delay_since_last_sr=0, version=2, padding=0, count=1, payloadtype=202, length=14
May 12 18:53:13 crm_reg_server rtpengine[24850]: [0b4mng9ugn8a9sm0hrph] version=2, padding=0, count=1, payloadtype=200, length=12, ssrc=1960417946, ntp_sec=3861341593, ntp_fractions=723409931, rtp_ts=984458832, sender_packets=683, sender_bytes=109280, ssrc=0, fraction_lost=0, packet_loss=1, last_seq=0, jitter=0, last_sr=0, delay_since_last_sr=0, version=2, padding=0, count=1, payloadtype=202, length=14
May 12 18:53:14 crm_reg_server rtpengine[24850]: ERR: [0b4mng9ugn8a9sm0hrph port 31794]: [core] SRTP output wanted, but no crypto suite was negotiated
May 12 18:53:14 crm_reg_server rtpengine[24850]: [0b4mng9ugn8a9sm0hrph] version=2, padding=0, count=1, payloadtype=200, length=12, ssrc=1960417946, ntp_sec=3861341594, ntp_fractions=809356522, rtp_ts=984466992, sender_packets=734, sender_bytes=117440, ssrc=0, fraction_lost=0, packet_loss=1, last_seq=0, jitter=0, last_sr=0, delay_since_last_sr=0, version=2, padding=0, count=1, payloadtype=202, length=14
May 12 18:53:15 crm_reg_server rtpengine[24850]: [0b4mng9ugn8a9sm0hrph] version=2, padding=0, count=1, payloadtype=200, length=12, ssrc=1960417946, ntp_sec=3861341595, ntp_fractions=895221508, rtp_ts=984475152, sender_packets=785, sender_bytes=125600, ssrc=0, fraction_lost=0, packet_loss=1, last_seq=0, jitter=0, last_sr=0, delay_since_last_sr=0, version=2, padding=0, count=1, payloadtype=202, length=14
May 12 18:53:16 crm_reg_server rtpengine[24850]: [0b4mng9ugn8a9sm0hrph] version=2, padding=0, count=1, payloadtype=200, length=12, ssrc=1960417946, ntp_sec=3861341596, ntp_fractions=981150919, rtp_ts=984483312, sender_packets=836, sender_bytes=133760, ssrc=0, fraction_lost=0, packet_loss=1, last_seq=0, jitter=0, last_sr=0, delay_since_last_sr=0, version=2, padding=0, count=1, payloadtype=202, length=14
May 12 18:53:17 crm_reg_server rtpengine[24850]: [0b4mng9ugn8a9sm0hrph] version=2, padding=0, count=1, payloadtype=200, length=12, ssrc=1960417946, ntp_sec=3861341597, ntp_fractions=1067024495, rtp_ts=984491472, sender_packets=887, sender_bytes=141920, ssrc=0, fraction_lost=0, packet_loss=1, last_seq=0, jitter=0, last_sr=0, delay_since_last_sr=0, version=2, padding=0, count=1, payloadtype=202, length=14
May 12 18:53:18 crm_reg_server rtpengine[24850]: [0b4mng9ugn8a9sm0hrph] version=2, padding=0, count=1, payloadtype=200, length=12, ssrc=1960417946, ntp_sec=3861341598, ntp_fractions=1152923841, rtp_ts=218400, sender_packets=936, sender_bytes=149760, ssrc=0, fraction_lost=0, packet_loss=1, last_seq=0, jitter=0, last_sr=0, delay_since_last_sr=0, version=2, padding=0, count=1, payloadtype=202, length=14

**Comment by rfuchs** [comment]
That looks like an outdated OpenSSL but the version you posted should be good I think? Perhaps there's other versions installed and rtpengine is linked against an older one?
