### ISSUE TITLE
prometheus metrics 

### ISSUE THREAD

**Issue by daknadnane** [sipwise/rtpengine#1491]
Hello , 
is there any docs describing meaning of each metric exposed to prometheus server

**Comment by rfuchs** [comment]
It's provided within the metrics themselves, if you pull up the output of `/metrics`

```
~# curl http://localhost:2225/metrics
# HELP rtpengine_sessions Owned sessions
# TYPE rtpengine_sessions gauge
rtpengine_sessions{type="own"} 0
rtpengine_sessions{type="foreign"} 0
# HELP rtpengine_transcoded_media Transcoded media
# TYPE rtpengine_transcoded_media gauge
rtpengine_transcoded_media 0
# HELP rtpengine_mediastreams Userspace-only media streams
# TYPE rtpengine_mediastreams gauge
rtpengine_mediastreams{type="userspace"} 0
```

Some might be missing but in general they correspond to what you see in `rtpengine-ctl list totals` so you should be able to figure it out.

Don't use the Github issue tracker to ask questions. Use the mailing list instead.

**Comment by daknadnane** [comment]
many  Thanks
