### ISSUE TITLE
different dynamic payload types in offer and answer 

### ISSUE THREAD

**Issue by MarcoHierl** [sipwise/rtpengine#1493]
Dear List,

my caller sends an INVITE with SDP offering telephone-event/8000 using dynamic payload type 110. Callee answers with 200ok using payload type 101 for telephone-event/8000.

For the sdp answer the rtpengine said:
h1 rtpengine[1270]: DEBUG: [8a06e15b21a563d3de4e27edc86f2a2b@87.136.7.30]: [codec] Not adding stray answer codec telephone-event/8000 (101)
and it just removes the 101 from the sdp answer.

Is this behaviour correct? It is only a "should be the same", or? RFC 3264 6.1. "... if a particular codec was referenced with a specific payload type number in the offer, that same payload type number SHOULD be used for that codec in the answer.“

I'm using Version: 10.3.1.6+0~mr10.3.1.6 git-HEAD-ac1b994f

thanks and best regards
  Marco

**Comment by rfuchs** [comment]
That is correct for the time being as we don't support answering an offered payload type with a different number (and I wouldn't even know what the correct behaviour would be in terms of which payload type to use for sending or receiving in that case). Feel free to submit a PR if you want to improve this somehow.

Also this is the Github issue tracker, not a mailing list. We do have a dedicated mailing list for questions.
