### ISSUE TITLE
Problem with ICE Lite and rtcp offer/demux in MS Teams

### ISSUE THREAD

**Issue by Oleg-voip** [sipwise/rtpengine#1494]
Hello!
We use rtpengine with MS Teams. And we face with problems after updating from version 9.5 to 10.4.
1) Commit f5a148f breaks ice lite. With this commit MS Teams killing call after 25 seconds with error "IceConnectivityChecksFailed" (MS Teams send us this reason in BYE request).
2) Commit 4658b90 breaks rtcp offer/demux, and with this commit we do not have audio in our test call.

Could you please check these commits? With them we can not work with MS Teams properly.
Thank you!

**Comment by rfuchs** [comment]
How or why are these commits breaking your calls?

**Comment by Oleg-voip** [comment]
We have stable Microsoft Teams setup. It works with all possible use cases.
We test use case when we call to teams and then put call on hold, return it back.

Before f5a148fb everything works ideally.
After f5a148fb when we put call on hold, we hear music for 25 seconds and then receive BYE from teams with error IceConnectivityChecksFailed.
After 4658b90 we even don't hear music.

**Comment by Oleg-voip** [comment]
How can we proceed with this?

**Comment by rfuchs** [comment]
Investigate and determine what exactly it is that makes the calls fail. For ICE issues you can inspect the STUN packets with Wireshark, and also look at the debug log from rtpengine to see what's going on. Is there an ICE reset when there shouldn't be, or vice versa (the ICE attributes in the SDP would also be relevant here)? Does the ICE role come out differently? Are the connectivity checks successful, and do they even take place?

For RTCP-mux you should probably look at the SDPs that are produced by rtpengine and see if there's a difference that makes MS Teams choke.
