### ISSUE TITLE
rtpengine slave logs 'Failed to get 1 consecutive ports...' under heavy traffic

### ISSUE THREAD

**Issue by kdanderso** [sipwise/rtpengine#1495]
I'm using rtpengine in a master/slave configuration with Kamailio and redis. When running load tests, the slave instance frequently logs errors like the following:

Jun  1 15:17:33 node2 rtpengine[2373641]: ERR: [10733460-1c68-46d4-b3ab-452519c2c63c]: [core] Failed to get 1 consecutive ports on interface 192.168.40.70 for media relay (last error: Success)
Jun  1 15:17:33 node2 rtpengine[2373641]: ERR: [10733460-1c68-46d4-b3ab-452519c2c63c]: [core] Error creating sfd: failed to open ports
Jun  1 15:17:33 node2 rtpengine[2373641]: WARNING: [10733460-1c68-46d4-b3ab-452519c2c63c]: [core] Failed to restore call ID '10733460-1c68-46d4-b3ab-452519c2c63c' from Redis: failed to create sfds
Jun  1 15:17:33 node2 rtpengine[2373641]: WARNING: [10733460-1c68-46d4-b3ab-452519c2c63c]: [core] Redis returned error to command 'DEL %b': READONLY You can't write against a read only replica.
Jun  1 15:17:33 node2 rtpengine[2373641]: WARNING: [core] Failed to restore call ID '10733460-1c68-46d4-b3ab-452519c2c63c' from Redis: could not retrieve JSON data from redis
Jun  1 15:17:33 node2 rtpengine[2373641]: WARNING: [core] Redis returned error to command 'DEL %b': READONLY You can't write against a read only replica.
Jun  1 15:17:33 node2 rtpengine[2373641]: NOTICE: [core] Redis-Notifier: DEL did not find call with callid: 10733460-1c68-46d4-b3ab-452519c2c63c

As near as I can tell, this issue did not happen on versions 10.2.1.14 or previous, but is present on 10.3.1.10 up through 10.4.2.0.

More detailed debugging information is in the attached log file.
[rtpengine.log.zip](https://github.com/sipwise/rtpengine/files/8815685/rtpengine.log.zip)

**Comment by kdanderso** [comment]
[rtpmaster.conf.txt](https://github.com/sipwise/rtpengine/files/8818064/rtpmaster.conf.txt)
[rtpslave.conf.txt](https://github.com/sipwise/rtpengine/files/8818065/rtpslave.conf.txt)

**Comment by rfuchs** [comment]
Also the general call flow of the first call on the master would be interesting, in particular if there was any branching involved, and/or when that part was released on the master.

**Comment by rfuchs** [comment]
Yes that would be helpful. What I'm wondering is whether this is a race condition that somehow stems from Redis itself (port is released first on master, but somehow the DEL is seen second on the slave), or whether the master releases the port before the DEL is sent to Redis.

**Comment by kdanderso** [comment]
Thank you.

I noticed that when this happens, the slave is not able to get the "wanted_start_port", so it tries to retrieve a port from the free list. In the failure cases, it is able to find a free port, but when it tries to open it, the port is already in use. Looking back in the log, that port was already in use, so it seems like it shouldn't have been on the free list. Is that expected?

Here are the related log messages:

Port 20016 is opened for a call:

Jun  1 19:53:53 node2 rtpengine[6728]: DEBUG: [1af8c03f-3070-4663-8c16-984c538379ee]: [core] wanted_start_port=20016
Jun  1 19:53:53 node2 rtpengine[6728]: DEBUG: [1af8c03f-3070-4663-8c16-984c538379ee]: [core] port=20016
Jun  1 19:53:53 node2 rtpengine[6728]: DEBUG: [1af8c03f-3070-4663-8c16-984c538379ee]: [core] port 20016 is NOT USED in port pool
Jun  1 19:53:53 node2 rtpengine[6728]: DEBUG: [1af8c03f-3070-4663-8c16-984c538379ee]: [core] cycle=0, port=20016
Jun  1 19:53:53 node2 rtpengine[6728]: DEBUG: [1af8c03f-3070-4663-8c16-984c538379ee]: [core] attempting to open port 20016
Jun  1 19:53:53 node2 rtpengine[6728]: DEBUG: [1af8c03f-3070-4663-8c16-984c538379ee]: [core] port 20016 locked
Jun  1 19:53:53 node2 rtpengine[6728]: DEBUG: [1af8c03f-3070-4663-8c16-984c538379ee]: [core] 6492 free ports remaining on interface 192.168.40.70
Jun  1 19:53:53 node2 rtpengine[6728]: DEBUG: [1af8c03f-3070-4663-8c16-984c538379ee]: [core] Opened ports 20016.. on interface 192.168.40.70 for media relay


Later, 29969 is requested, but is in use, so 20016 is selected from the free list, even though it should be unavailable:

Jun  1 19:54:04 node2 rtpengine[6728]: DEBUG: [59f59780-1f03-426b-9b69-43b7136a9b02]: [core] wanted_start_port=29969
Jun  1 19:54:04 node2 rtpengine[6728]: DEBUG: [59f59780-1f03-426b-9b69-43b7136a9b02]: [core] port=29969
Jun  1 19:54:04 node2 rtpengine[6728]: DEBUG: [59f59780-1f03-426b-9b69-43b7136a9b02]: [core] port 29969 is USED in port pool
Jun  1 19:54:04 node2 rtpengine[6728]: DEBUG: [59f59780-1f03-426b-9b69-43b7136a9b02]: [core] Picked port 20016 from free list
Jun  1 19:54:04 node2 rtpengine[6728]: DEBUG: [59f59780-1f03-426b-9b69-43b7136a9b02]: [core] cycle=0, port=20016
Jun  1 19:54:04 node2 rtpengine[6728]: DEBUG: [59f59780-1f03-426b-9b69-43b7136a9b02]: [core] attempting to open port 20016
Jun  1 19:54:04 node2 rtpengine[6728]: DEBUG: [59f59780-1f03-426b-9b69-43b7136a9b02]: [core] port 20016 in use
Jun  1 19:54:04 node2 rtpengine[6728]: DEBUG: [59f59780-1f03-426b-9b69-43b7136a9b02]: [core] trying to release port 0
Jun  1 19:54:04 node2 rtpengine[6728]: DEBUG: [59f59780-1f03-426b-9b69-43b7136a9b02]: [core] port 0 is NOT released
Jun  1 19:54:04 node2 rtpengine[6728]: ERR: [59f59780-1f03-426b-9b69-43b7136a9b02]: [core] Failed to get 1 consecutive ports on interface 192.168.40.70 for media relay (last error: Success)

**Comment by rfuchs** [comment]
Yeah I noticed that too, but that's a secondary issue, not directly responsible for what you're seeing.

**Comment by kdanderso** [comment]
I'll try it and let you know.

**Comment by kdanderso** [comment]
Unfortunately, those changes seem to have no effect on the issue. If you need any additional information, please let me know.

**Comment by rfuchs** [comment]
You updated the master or the slave? Or both?

**Comment by kdanderso** [comment]
Both. I added a couple of log messages to the master to make sure I was actually compiling the modified version.

**Comment by rfuchs** [comment]
Ok I see, looks like this is a bit more involved than I had thought. Try with cdede4b instead.

**Comment by rfuchs** [comment]
Wow ok 😆
Yes, the delete-delay made the difference... Third try lucky? With 15c7e9a

**Comment by kdanderso** [comment]
This seems better, but I'm still getting failures. On 10000 calls with the new version, I saw about 5 failures, compared with maybe 25 without any fixes.

**Comment by rfuchs** [comment]
Can you pull the debug log from one such call, from both master and slave, like you did before? There might be another instance of the same race condition hiding somewhere.

**Comment by kdanderso** [comment]
[rtplogs-15c7e9a.zip](https://github.com/sipwise/rtpengine/files/8873390/rtplogs-15c7e9a.zip)

**Comment by rfuchs** [comment]
I'm a bit stumped because I'm not sure where else this race condition could be hiding. I pushed another commit (17bda4b) with some things changed around, perhaps you can see if this works better? Apologies for the trial & error approach here, but this is inherently difficult to track down and I have no way of reproducing this myself.

**Comment by kdanderso** [comment]
After 50000 calls I haven't seen any errors, so this looks promising. I'll continue testing and let you know what happens.
Thanks.
