### ISSUE TITLE
remove specific attributes from SDP

### ISSUE THREAD

**Issue by patrickarton** [sipwise/rtpengine#1496]
Hello is there a way to remove specific attributes when doing Offer/Answer.

For example remove

Email Address ("e=") 
Repeat Times ("r=") 
Bandwidth ("b=") 
Encryption Keys ("k=") 
URI ("u=") 

Phone Number ("p=") 

Time Zones ("z=")

**Comment by rfuchs** [comment]
No we don't have such an option. Pull requests welcome.

This is the Github issue tracker, not a forum to ask question. We have a mailing list for questions.
