### ISSUE TITLE
Test Fail: object has no attribute '_ws' when compiling on jammy

### ISSUE THREAD

**Issue by plummyp** [sipwise/rtpengine#1497]
Hi,

I have a CI pipeline that is compiling rtpengine for different ubuntu releases (bionic, focal, jammy).

On bionic and focal it compiles fine, but on jammy I get errors:

ERROR: testKeepalive (__main__.TestVideoroom)
ERROR: testVideoroomDTLS (__main__.TestVideoroom)
ERROR: testVideoroomICE (__main__.TestVideoroom)
ERROR: testVideoroomPubSub (__main__.TestVideoroom)
ERROR: testVideoroomSDES (__main__.TestVideoroom)
ERROR: testVideoroomSDESDTLS (__main__.TestVideoroom)
ERROR: testVideoroomWebRTC (__main__.TestVideoroom)
ERROR: testVideoroomWebRTCVideo (__main__.TestVideoroom)
ERROR: testVideoroomWebrtcup (__main__.TestVideoroom)
These fail with: AttributeError: 'TestVideoroom' object has no attribute '_ws'

ERROR: testListNumsessions (__main__.TestWSCli) fails with: AttributeError: 'TestWSCli' object has no attribute '_ws'

ERROR: testEcho (__main__.TestWSEcho)
ERROR: testEchoText (__main__.TestWSEcho)
These fail with: AttributeError: 'TestWSEcho' object has no attribute '_ws'

ERROR: testInfo (__main__.TestWSJanus)
ERROR: testPing (__main__.TestWSJanus)
ERROR: testPingNoTS (__main__.TestWSJanus)
These fail with: AttributeError: 'TestWSJanus' object has no attribute '_ws'

On bionic and focal python 3.6 and 3.8 were used respectively and on jammy its 3.10

I presume something is missing from the jammy image, what needs to be installed for the tests to be successful? 

I am using tag mr10.4.1.3

**Comment by rfuchs** [comment]
Having python3-websockets installing normally fixes this. Do you have that package? Perhaps jammy has the `websockets` Python module somewhere else?

**Comment by darkorigins** [comment]
Hi, seeing same issue here on Ubuntu 22.04 jammy. 

python3-websocket & python3-websockets installed.

Lots of errors along these lines for TestWSCli/TestWSEcho/etc
```
======================================================================
ERROR: testPingNoTS (__main__.TestWSJanus)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mark/git/rtpengine/t/auto-daemon-tests-websocket.py", line 115, in testPingNoTS
    self._eventloop.run_until_complete(testIOJson(self, {"janus": "ping"}))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/mark/git/rtpengine/t/auto-daemon-tests-websocket.py", line 34, in testIOJson
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestWSJanus' **object has no attribute '_ws'**
----------------------------------------------------------------------
```
$ date
Mon Jun 27 12:20:41 UTC 2022

**Comment by rfuchs** [comment]
This seems to be a problem with the jammy packages. Even the most rudimentary Python websockets client, taking straight from the docs, doesn't seem to work.

```
dfx@jammy:~$ cat test.py 
import websockets
import asyncio

async def test():
    async with websockets.connect("ws://127.0.0.1:9191/") as w:
        w.send('foo')

asyncio.run(test())
dfx@jammy:~$ python3 test.py 
Traceback (most recent call last):
  File "/home/dfx/test.py", line 8, in <module>
    asyncio.run(test())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/dfx/test.py", line 5, in test
    async with websockets.connect("ws://127.0.0.1:9191/") as w:
  File "/usr/lib/python3/dist-packages/websockets/legacy/client.py", line 604, in __aenter__
    return await self
  File "/usr/lib/python3/dist-packages/websockets/legacy/client.py", line 622, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1107, in _create_connection_transport
    protocol = protocol_factory()
  File "/usr/lib/python3/dist-packages/websockets/legacy/client.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 154, in __init__
    self._drain_lock = asyncio.Lock(
  File "/usr/lib/python3.10/asyncio/locks.py", line 78, in __init__
    super().__init__(loop=loop)
  File "/usr/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary
```

Even the standalone interactive client doesn't work:

```
dfx@jammy:~$ python3 -m websockets ws://localhost:9191/
Failed to connect to ws://localhost:9191/: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary.
```

Seems to be a conflict with the new asyncio from Python 3.10.

**Comment by rfuchs** [comment]
https://bugs.launchpad.net/ubuntu/+source/python-websockets/+bug/1969902

**Comment by rfuchs** [comment]
Closing this issue then
