### ISSUE TITLE
Stray codec in answer SDP when UE gives  2 CODEC in which one in not available in Offer.

### ISSUE THREAD

**Issue by toharish** [sipwise/rtpengine#1499]
Scenario

UE A==> offer with codec **PCMU, G729, AMR ,PCMA** ==> RTPENGINE -> offer with codec **PCMU, G729, AMR ,PCMA**==> UE B

UEA<===== Answer with **PCMA,PCMU** codec<========RTPENGINE<==answer with **PCMA ,Telephony Event (101)**<===UE B

It is seen that Telephony Event (101) was not available on offer but UE B had sent this with negotiated codec and when it is passed through RTP Engine Telephony Event (101) is replaced with PCMU which was not available in answer.

 Results in One way speech as  UE A sends the RTP with PCMA UE B sends with PCMU
RTP engine transcodes the PCMA from UE A to PCMU while sending it to UE B
But it will not transcode PCMA from UE B to PCMU for UE A
UE A is expecting PCMU  and not able to play the RTP

ie ..
  UE A ===PCMU===> RTPENGINE ===PCMA===>UE B
  UE A <==PCMA==== RTPENGINE <==PCMA====UE B

UEA Expects the received RTP as PCMU but receives PCMA

The issue is observed since UE B is sending Telephony Event (101) in the answer which is not sent in the offer.
In such cases, transcoding is enabled 
I have solved it with a workaround to disable the transcoding at such cases

In **_call.c_**

function 
void codecs_offer_answer(struct call_media *media, struct call_media *other_media,
		struct stream_params *sp, struct sdp_ng_flags *flags)
In answer section
`

             if (other_media->streams.length == 0)

			codec_answer_only = false;

		else {

			struct packet_stream *ps = other_media->streams.head->data;

			//if (ps->endpoint.port == 0)

			//	codec_answer_only = false;

		}

`
I feel the endpoint.port is checked for each codec without checking if there is any other codec that is available in answer.

With these changes, this scenario was working fine.. RTPENGINE will not pass the telephony Event to UE A in the answer which is perfectly fine.

**Comment by rfuchs** [comment]
Which version are we talking about?

**Comment by toharish** [comment]
ngcp-rtpengine_10.5.0.0+0~mr10.5.0.0

**Comment by rfuchs** [comment]
I'm a bit confused about your proposed solution. The check it disables is meant for cases where a media stream is rejected or disabled by having a zero port in the SDP `m=` line. Is that what happens in your case?

**Comment by rfuchs** [comment]
Ok I see now. You're almost correct - it actually is the wrong port being checked in this code snippet. Fix coming.

**Comment by toharish** [comment]
> Ok I see now. You're almost correct - it actually is the wrong port being checked in this code snippet. Fix coming.

Thankyou
