### ISSUE TITLE
Error compiling Kernel module  on Centos 6.5

### ISSUE THREAD

**Issue by ekoome** [sipwise/rtpengine#150]
I get the following error when compiling kernel module. I have all kernel-devel and kernel-headers. Any thoughts what i may be missing?

make -C /lib/modules/2.6.32-431.17.1.el6.x86_64/build M=/usr/src/rtpengine/kernel-module O=/lib/modules/2.6.32-431.17.1.el6.x86_64/build modules
make[1]: Entering directory `/usr/src/kernels/2.6.32-431.17.1.el6.x86_64'
  CC [M]  /usr/src/rtpengine/kernel-module/xt_RTPENGINE.o
/usr/src/rtpengine/kernel-module/xt_RTPENGINE.c:20:27: error: linux/bsearch.h: No such file or directory
/usr/src/rtpengine/kernel-module/xt_RTPENGINE.c: In function ‘rtp_payload_type’:
/usr/src/rtpengine/kernel-module/xt_RTPENGINE.c:2198: error: implicit declaration of function ‘bsearch’
/usr/src/rtpengine/kernel-module/xt_RTPENGINE.c:2198: warning: assignment makes pointer from integer without a cast
make[3]: *** [/usr/src/rtpengine/kernel-module/xt_RTPENGINE.o] Error 1
make[2]: *** [_module_/usr/src/rtpengine/kernel-module] Error 2
make[1]: *** [sub-make] Error 2
make[1]: Leaving directory `/usr/src/kernels/2.6.32-431.17.1.el6.x86_64'
make: *** [modules] Error 2

**Comment by paulandrewhughes** [comment]
bsearch function is only ~20 lines code. 
https://github.com/torvalds/linux/blob/master/lib/bsearch.c
Why not add the function for kernels that don't have it?

**Comment by ekoome** [comment]
Also can use <stdlib.h> which has a definition and is included in Centos 6.5

**Comment by rfuchs** [comment]
stdlib is a C library header, not a kernel header and can't be used in the kernel.

Patches which improves this are welcome.
