### ISSUE TITLE
"subscribe request" creates SDP with private address

### ISSUE THREAD

**Issue by davehorton** [sipwise/rtpengine#1506]
I am trying to use 'subscribe request' to implement a SIPREC client, using version mr10.4.1.4.  The problem that I am having is that I want to send the streams to an external SIPREC server but the SDP returned from 'subscribe request' includes the IP on the private interface, not the public one.  I tried to adding direction: ['public', 'public'] to the options sent in the 'subscribe request' but this did not help.

I've defined my interfaces like this

```
ExecStart=/usr/local/bin/rtpengine \
--interface private/${LOCAL_IP} \
--interface public/${LOCAL_IP}!${PUBLIC_IP} \
```

rtpengine log is [here](https://gist.github.com/davehorton/8edbdb8d37475ac116b53f416a44a00d)

Is there a mechanism for indicating which interface I want the generated SDP to reference?

**Comment by rfuchs** [comment]
Yes there is, and it's described in the docs.
![Screenshot_2022-06-16_17-59-09](https://user-images.githubusercontent.com/3227418/174178982-d1891400-6788-4496-8646-b27270d6e5df.png)

**Comment by davehorton** [comment]
Ah, thanks!
