### ISSUE TITLE
unable to compile kernel module - atmoic issues

### ISSUE THREAD

**Issue by etamme** [sipwise/rtpengine#151]
CentOS release 6.2 (Final)
Linux media-relay1.55-broad-1.jnctn.net 2.6.32-220.13.1.el6.x86_64 #1 SMP Tue Apr 17 23:56:34 BST 2012 x86_64 x86_64 x86_64 GNU/Linux

currently on master at:

commit c6ff5e7c03fa49ef6216d7cfe09b3006ddb5d5f8
Author: Richard Fuchs <rfuchs@sipwise.com>
Date:   Wed Sep 2 09:50:33 2015 -0400

kernel-module]$make
make -C /lib/modules/2.6.32-220.13.1.el6.x86_64/build M=/usr/local/src/rtpengine/kernel-module O=/lib/modules/2.6.32-220.13.1.el6.x86_64/build modules
make[1]: Entering directory `/usr/src/kernels/2.6.32-220.13.1.el6.x86_64'
  CC [M]  /usr/local/src/rtpengine/kernel-module/xt_RTPENGINE.o
/usr/local/src/rtpengine/kernel-module/xt_RTPENGINE.c:23:26: error: linux/atomic.h: No such file or directory
make[3]: *** [/usr/local/src/rtpengine/kernel-module/xt_RTPENGINE.o] Error 1
make[2]: *** [_module_/usr/local/src/rtpengine/kernel-module] Error 2
make[1]: *** [sub-make] Error 2
make[1]: Leaving directory `/usr/src/kernels/2.6.32-220.13.1.el6.x86_64'
make: *** [modules] Error 2

I updated xt_RTPENGINE.c to:

//#include <linux/atomic.h>
#include <asm-generic/bitops/atomic.h>

This avoids the earlier error, but i get [other compile errors now](https://gist.github.com/etamme/feb3fddee1a1e31c0950)

Any pointers on where to go from here - is this simply too old of a kernel to build the kernel module?

**Comment by etamme** [comment]
erm .. apparently my include statements freaked out the markdown - so much so that I can not actually edit my comment - see [the following gist](https://gist.github.com/etamme/76c6bc8c8d2dbb6947d4) for the change i made to the include.

**Comment by rfuchs** [comment]
I think you're looking for the atomic64_* operations. Try with asm-generic/atomic64.h

**Comment by etamme** [comment]
hrm changing the include to: <asm-generic/atmoic64.h> ended up erroring out with [this](https://gist.githubusercontent.com/etamme/3752a4ad4df55b504548/raw/f4b1db76543d4e35c1fbf1f0a948688f7ad6a934/gistfile1.txt)

Thanks for help and responsiveness

**Comment by etamme** [comment]
blarg ... include messed up again.  I changed it to asm-generic/atmoic64.h
