### ISSUE TITLE
rtpengine 11.0.0.0+0~mr11.0.0.0  on Debian 11 bullseye from git

### ISSUE THREAD

**Issue by jonhvoxbox** [sipwise/rtpengine#1510]
Hi,

I was hoping someone could assist. I have installed rtpengine from GIT and it appears it has installed without issue on Debian 11, the problem is it wont start and I see the following issues;

● ngcp-rtpengine-daemon.service - NGCP RTP/media Proxy Daemon
     Loaded: loaded (/lib/systemd/system/ngcp-rtpengine-daemon.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2022-07-05 12:01:18 BST; 7s ago
    Process: 41466 ExecStartPre=/usr/sbin/ngcp-rtpengine-iptables-setup start (code=exited, status=226/NAMESPACE)
    Process: 41467 ExecStopPost=/usr/sbin/ngcp-rtpengine-iptables-setup stop (code=exited, status=226/NAMESPACE)
        CPU: 12ms

Jul 05 12:01:18 Kam-HA-Lab systemd[1]: Starting NGCP RTP/media Proxy Daemon...
Jul 05 12:01:18 Kam-HA-Lab systemd[41466]: ngcp-rtpengine-daemon.service: Failed to set up mount namespacing: /run/systemd/unit-root/var/spool/rtpengine: No such file or directory
Jul 05 12:01:18 Kam-HA-Lab systemd[41466]: ngcp-rtpengine-daemon.service: Failed at step NAMESPACE spawning /usr/sbin/ngcp-rtpengine-iptables-setup: No such file or directory
Jul 05 12:01:18 Kam-HA-Lab systemd[1]: ngcp-rtpengine-daemon.service: Control process exited, code=exited, status=226/NAMESPACE
Jul 05 12:01:18 Kam-HA-Lab systemd[41467]: ngcp-rtpengine-daemon.service: Failed to set up mount namespacing: /run/systemd/unit-root/var/spool/rtpengine: No such file or directory
Jul 05 12:01:18 Kam-HA-Lab systemd[41467]: ngcp-rtpengine-daemon.service: Failed at step NAMESPACE spawning /usr/sbin/ngcp-rtpengine-iptables-setup: No such file or directory
Jul 05 12:01:18 Kam-HA-Lab systemd[1]: ngcp-rtpengine-daemon.service: Control process exited, code=exited, status=226/NAMESPACE
Jul 05 12:01:18 Kam-HA-Lab systemd[1]: ngcp-rtpengine-daemon.service: Failed with result 'exit-code'.
Jul 05 12:01:18 Kam-HA-Lab systemd[1]: Failed to start NGCP RTP/media Proxy Daemon.

Am I missing something? Is it due to nftables/iptables ? If anyone could assist or point me in the correct direction I would be most grateful. 

Many thanks

Jon

**Comment by rfuchs** [comment]
First off it's not appropriate to use the Github issue tracker to ask general questions. We have a mailing list for that purpose.

I assume you've built Debian packages from the code? Which ones did you install? Is this a container environment?

**Comment by jonhvoxbox** [comment]
Hi Apologies happy to move this just let me know where.

Yes just cloned using git and then installed;

dpkg -i ngcp-rtpengine-daemon_*.deb ngcp-rtpengine-iptables_*.deb ngcp-rtpengine-kernel-dkms_*.deb

Version: 11.0.0.0+0~mr11.0.0.0 git-master-9c28951e

This is not container is a virtual machine upgraded to debian 11 bullseye.

**Comment by rfuchs** [comment]
Try either `sudo mkdir /var/spool/rtpengine` OR install the recording-daemon package, and see if that fixes it.
