### ISSUE TITLE
Audio goes dead when stream is kernelized

### ISSUE THREAD

**Issue by theresabugforsure** [sipwise/rtpengine#1517]
I'm using RTPEngine with OpenSIPs 3.2.6, which works fine when RTPEngine is in user space. When I put it in kernel space, audio disappears 5 seconds in (as soon as it gets kernelized).

This example I have call recording active. However, whether call recording is active or not, the result is the same. The moment media gets kernelized, it stops streaming.

All IPs are public, there is nothing behind a NAT anywhere. 

Jul 23 19:21:31 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [control] Received command 'offer' from 1.1.1.1:38111
Jul 23 19:21:31 monitor-1658602319 rtpengine[2530]: NOTICE: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [core] Creating new call
Jul 23 19:21:31 monitor-1658602319 rtpengine[2530]: NOTICE: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [core] Turning on call recording.
Jul 23 19:21:31 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [control] Replying to 'offer' from 1.1.1.1:38111 (elapsed time 0.001461 sec)
Jul 23 19:21:54 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [control] Received command 'answer' from 1.1.1.1:57749
Jul 23 19:21:54 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [control] Replying to 'answer' from 1.1.1.1:57749 (elapsed time 0.000508 sec)
Jul 23 19:21:54 monitor-1658602319 rtpengine[2530]: WARNING: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13 port 30046]: [core] RTP packet with unknown payload type 95 received from 2.2.2.2:40466
Jul 23 19:21:54 monitor-1658602319 rtpengine-recording[2589]: WARNING: [C 7d32b2ca-9b88-49cb-aae9-9e74f2631d13-da45f47ab2166e6c.meta] [S tag-0-media-1-component-1-RTP-id-2] [0xc8a8d09a] [core] Unknown RTP payload type 95
Jul 23 19:21:57 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [control] Received command 'answer' from 1.1.1.1:35303
Jul 23 19:21:57 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [control] Replying to 'answer' from 1.1.1.1:35303 (elapsed time 0.000589 sec)
Jul 23 19:22:01 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13 port 30046]: [core] Confirmed peer address as 2.2.2.2:40466
Jul 23 19:22:01 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13 port 30046]: [core] Kernelizing media stream: 2.2.2.2:40466 -> 4.4.4.4:30046 | 4.4.4.4:30024 -> 3.3.3.3:43632
Jul 23 19:22:01 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13 port 30024]: [core] Confirmed peer address as 3.3.3.3:43632
Jul 23 19:22:01 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13 port 30024]: [core] Kernelizing media stream: 3.3.3.3:43632 -> 4.4.4.4:30024 | 4.4.4.4:30046 -> 2.2.2.2:40466
Jul 23 19:22:03 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13 port 30047]: [core] Confirmed peer address as 2.2.2.2:40466
Jul 23 19:22:30 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [control] Received command 'delete' from 1.1.1.1:38111
Jul 23 19:22:30 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [core] Scheduling deletion of call branch 'DH1vXc2t270Zp' (via-branch '') in 30 seconds
Jul 23 19:22:30 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [control] Replying to 'delete' from 1.1.1.1:38111 (elapsed time 0.000139 sec)
Jul 23 19:22:30 monitor-1658602319 rtpengine[2530]: INFO: [-d77vm39yOjxPBa6LxAm3w..]: [control] Received command 'delete' from 1.1.1.1:38111
Jul 23 19:22:30 monitor-1658602319 rtpengine[2530]: INFO: [-d77vm39yOjxPBa6LxAm3w..]: [core] Call-ID to delete not found
Jul 23 19:22:30 monitor-1658602319 rtpengine[2530]: INFO: [-d77vm39yOjxPBa6LxAm3w..]: [control] Replying to 'delete' from 1.1.1.1:38111 (elapsed time 0.000011 sec)
Jul 23 19:23:00 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [core] Removing media stream from kernel: local 4.4.4.4:30024
Jul 23 19:23:00 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [core] Removing media stream from kernel: local 4.4.4.4:30046
Jul 23 19:23:00 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [core] Call branch 'DH1vXc2t270Zp' (via-branch '') deleted, no more branches remaining
Jul 23 19:23:00 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [core] Final packet stats:
Jul 23 19:23:00 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [core] --- Tag 'er9mpej5QrXDN', created 1:29 ago for branch ''
Jul 23 19:23:00 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [core] ---     subscribed to 'DH1vXc2t270Zp'
Jul 23 19:23:00 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [core] ---     subscription for 'DH1vXc2t270Zp'
Jul 23 19:23:00 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [core] ------ Media #1 (audio over RTP/AVP) using PCMU/8000
Jul 23 19:23:00 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [core] --------- Port   4.4.4.4:30046 <>     2.2.2.2:40466, SSRC c8a8d09a, 1790 p, 307721 b, 1 e, 29 ts
Jul 23 19:23:00 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [core] --------- Port   4.4.4.4:30047 <>     2.2.2.2:40466 (RTCP), SSRC c8a8d09a, 7 p, 420 b, 0 e, 30 ts
Jul 23 19:23:00 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [core] --- Tag 'DH1vXc2t270Zp', created 1:29 ago for branch ''
Jul 23 19:23:00 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [core] ---     subscribed to 'er9mpej5QrXDN'
Jul 23 19:23:00 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [core] ---     subscription for 'er9mpej5QrXDN'
Jul 23 19:23:00 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [core] ------ Media #1 (audio over RTP/AVP) using PCMU/8000
Jul 23 19:23:00 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [core] --------- Port   4.4.4.4:30024 <>  3.3.3.3:43632, SSRC 965fff10, 1811 p, 311492 b, 0 e, 29 ts
Jul 23 19:23:00 monitor-1658602319 rtpengine[2530]: INFO: [7d32b2ca-9b88-49cb-aae9-9e74f2631d13]: [core] --------- Port   4.4.4.4:30025 <>  3.3.3.3:43633 (RTCP), SSRC 0, 0 p, 0 b, 0 e, 63 ts
Jul 23 19:23:00 monitor-1658602319 rtpengine-recording[2589]: INFO: [C 7d32b2ca-9b88-49cb-aae9-9e74f2631d13-da45f47ab2166e6c.meta] [S tag-1-media-1-component-2-RTCP-id-1] [core] EOF on stream tag-1-media-1-component-2-RTCP-id-1
Jul 23 19:23:00 monitor-1658602319 rtpengine-recording[2589]: INFO: [C 7d32b2ca-9b88-49cb-aae9-9e74f2631d13-da45f47ab2166e6c.meta] [S tag-1-media-1-component-1-RTP-id-0] [core] EOF on stream tag-1-media-1-component-1-RTP-id-0
Jul 23 19:23:00 monitor-1658602319 rtpengine-recording[2589]: INFO: [C 7d32b2ca-9b88-49cb-aae9-9e74f2631d13-da45f47ab2166e6c.meta] [S tag-0-media-1-component-2-RTCP-id-3] [core] EOF on stream tag-0-media-1-component-2-RTCP-id-3
Jul 23 19:23:00 monitor-1658602319 rtpengine-recording[2589]: INFO: [C 7d32b2ca-9b88-49cb-aae9-9e74f2631d13-da45f47ab2166e6c.meta] [S tag-0-media-1-component-1-RTP-id-2] [core] EOF on stream tag-0-media-1-component-1-RTP-id-2
Jul 23 19:23:09 monitor-1658602319 rtpengine-recording[2589]: WARNING: [ffmpeg] av_log: 29 frames left in the queue on closing

**Comment by ineedassitance** [comment]
Just to add, audio stops in both directions. I increased to log-level 7 to log the streams and it stops logging as soon as the kernelize message comes on. 

Version: 11.0.0.0+0~mr11.0.0.0 git-master-5df21de3

**Comment by ineedassitance** [comment]
Just test 10.5.1 and got the same result. By the way, this is running on Debian 11 Bullseye.

**Comment by ineedassitance** [comment]
iptables is bare bones.

-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N rtpengine
-A INPUT -p udp -j rtpengine
-A rtpengine -p udp -j RTPENGINE --id 0

**Comment by ineedassitance** [comment]
[strace.txt](https://github.com/sipwise/rtpengine/files/9174794/strace.txt)

strace attached.

**Comment by theresabugforsure** [comment]
More info ...

Recording keeps going, so packets are still being captured by rtpengine, but it's no longer streaming them out to the source and destination. I kept the line open for 15 seconds, 10 seconds after audio died on both ends of the call, but it kept recording clear audio despite not being able to hear each other on the line.

**Comment by theresabugforsure** [comment]
Caught this in dmesg. 

[Sat Jul 23 20:06:13 2022] xt_RTPENGINE: loading out-of-tree module taints kernel.
[Sat Jul 23 20:06:13 2022] xt_RTPENGINE: module verification failed: signature and/or required key missing - tainting kernel
[Sat Jul 23 20:06:13 2022] Registering xt_RTPENGINE module - version 11.0.0.0+0~mr11.0.0.0

**Comment by rfuchs** [comment]
Post the contents of `/proc/rtpengine/0/list` after the stream has been pushed to kernel.

Also post your network setup, e.g. `ip a ls` and `ip r ls` and whether there's anything else that's unusual about your setup (e.g. container/VM environment, source-based routing, etc)

**Comment by theresabugforsure** [comment]
/proc/rtpengine/0/list

local inet4 207.148.21.65:30000
    stats:                98040 bytes,                  570 packets,                    0 errors
        RTP payload type   0:                98040 bytes,                  570 packets
        RTP payload type   8:                    0 bytes,                    0 packets
        RTP payload type  13:                    0 bytes,                    0 packets
    SSRC in: b33b6e91
    output #0
       src inet4 207.148.21.65:30020
       dst inet4 144.202.1.14:23852
local inet4 207.148.21.65:30020
    stats:                97868 bytes,                  569 packets,                    0 errors
        RTP payload type   0:                97868 bytes,                  569 packets
        RTP payload type   8:                    0 bytes,                    0 packets
        RTP payload type  13:                    0 bytes,                    0 packets
    SSRC in: 66e123ad
    output #0
       src inet4 207.148.21.65:30000
       dst inet4 68.68.124.49:43562

===============
ip a ls

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 56:00:04:14:5f:6c brd ff:ff:ff:ff:ff:ff
    inet 207.148.21.65/23 brd 207.148.21.255 scope global dynamic enp1s0
       valid_lft 50622sec preferred_lft 50622sec
    inet6 fe80::5400:4ff:fe14:5f6c/64 scope link 
       valid_lft forever preferred_lft forever
3: enp6s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc mq state UP group default qlen 1000
    link/ether 5a:00:04:14:5f:6c brd ff:ff:ff:ff:ff:ff
    inet 10.99.0.20/20 brd 10.99.15.255 scope global enp6s0
       valid_lft forever preferred_lft forever
    inet6 fe80::5800:4ff:fe14:5f6c/64 scope link 
       valid_lft forever preferred_lft forever


==========
ip r ls

default via 207.148.20.1 dev enp1s0 
10.99.0.0/20 dev enp6s0 proto kernel scope link src 10.99.0.20 
169.254.169.254 via 207.148.20.1 dev enp1s0 
207.148.20.0/23 dev enp1s0 proto kernel scope link src 207.148.21.65

**Comment by rfuchs** [comment]
Well that looks completely straight forward. No idea why you're not getting media. Do the outbound media packets show up in Wireshark or tcpdump?

**Comment by theresabugforsure** [comment]
Nothing shows up going out. As soon as it's kernelized, it stops transmitting to both legs.

**Comment by theresabugforsure** [comment]
Interesting development. If I modprobe the kernel driver BEFORE starting the rtpengine service, it works. It kernelizes media and packets keep flowing in both directions. However, I lose the ability to record.

**Comment by theresabugforsure** [comment]
This bug still persist. Any suggestions as to where I should look or what I should try?

**Comment by rfuchs** [comment]
Not a clue. This is obviously not reproducible and I have no explanation. It's gotta be something specific to your setup that's causing this.

**Comment by theresabugforsure** [comment]
Installed 10.5.1.3 and it works correctly. The only difference I see is that the kernel module needs to be loaded before anything starts and remains loaded regardless of whether rtpengine is running or stopped.

**Comment by theresabugforsure** [comment]
10.5.1.13 works but 11 doesn't. Like I said, the only difference between the two versions is that in 10.5.1.13 the kernel module is loaded independent of rtpengine, whereas in 11 rtpengine loads and unloads the module. It's still an unresolved issue with 11, so we should keep this open and at least test the next version once it has commits.

**Comment by rfuchs** [comment]
Sorry but I don't see that difference you're describing. The startup scripts are identical between the two versions. The only noticeable differences are a change in how permissions for the recording spool directory are set (irrelevant) and how the iptables module is packaged (`execute_after_dh_install` in the rules file vs `ngcp-rtpengine-iptables.install`). In both versions loading and unloading of the kernel module is handled by the `ngcp-rtpengine-iptables-setup` helper script which is invoked as a `ExecStartPre` and `ExecStopPost` from the `rtpengine-daemon` systemd service.

**Comment by theresabugforsure** [comment]
I'll try to break down my observations regarding kernel module.

10.5.1.13 - If I manually load the kernel module before starting rtpengine, the scripts no longer unload the module when stopping rtpengine.

11 - If I manually load the kernel module before starting rtpengine, the scripts will unload the module when rtpengine is stopped.

That aside, I spun up two servers, identically configured, one running 10.5.1.3 and one running 11, to test them side by side. 

1- server running 10.5.1.13 works fine but I need to manually load the kernel module because starting rtpengine doesn't seem to do so.
2- server running 11 stops sending packets as soon as the media is kernelized, regardless of whether I manually load the kernel module or let the scripts do it.

I've spun up a few more fresh VMs, each running either 10.1.5.13 or 11, to test both of these and the behavior is identical to the above for each respective version. The moment media is kernelized in 11 it just stops sending packets.

**Comment by rfuchs** [comment]
Are you building yourself or which packages are you using?

**Comment by melmawi** [comment]
I have exactly the same issue. Compiled from git -b mr11.2.1 
As soon as it kernelized, the media is gone!

**Comment by IgorrG** [comment]
Hello,

@rfuchs I wonder, if this issue was ever fixed? We have faced same issue on one of our QUEMU VPS servers. It running 11.5 branch, but we could update to latest and provide logs or access to investigate and fix that. Thanks.

**Comment by rfuchs** [comment]
> Hello,
> 
> [@rfuchs](https://github.com/rfuchs) I wonder, if this issue was ever fixed? We have faced same issue on one of our QUEMU VPS servers. It running 11.5 branch, but we could update to latest and provide logs or access to investigate and fix that. Thanks.

Someone on the mailing list was able to determine that a non-standard TOS value made the kernel forwarding not work. Other than that I don't know what the issue would be that needs fixing.

**Comment by IgorrG** [comment]
Thanks for the idea, we'll check mailing list and TOS bits in our case.

**Comment by IgorrG** [comment]
We have captured RTP and do not have anything unusual in DiffServ. We'll update rtpengine to latest version ans continue investigation. 

![Image](https://github.com/user-attachments/assets/38f20395-3b5e-49d8-8235-57e1cb477be8)

**Comment by rfuchs** [comment]
> We have captured RTP and do not have anything unusual in DiffServ. We'll update rtpengine to latest version ans continue investigation.
> 
> ![Image](https://github.com/user-attachments/assets/38f20395-3b5e-49d8-8235-57e1cb477be8)

To clarify, this wasn't about the TOS that appears in the wire, but rather about the setting in the rtpengine config

**Comment by IgorrG** [comment]
Thanks for the info. We have no ToS configured in rtpengine.conf
