### ISSUE TITLE
set a=inactive as default for 0.0.0.0 address on Offer

### ISSUE THREAD

**Issue by patrickarton** [sipwise/rtpengine#1518]
Hello,

this is not really an issue.

i would like to know if there is an option to set a=inactive attribute by default for an offer when receiving SDP with 0.0.0.0 and direction attribute set by default on that SDP instead of RTPENGINE put a=sendonly by default ?

Thanks.

**Comment by rfuchs** [comment]
No there's no such option. You would get `inactive` if the stream was `recvonly` previously, but that probably doesn't help you. The only relevant option is `original-sendrecv` which tells rtpengine to leave the send/recv attributes alone, whichever was there originally.

Don't use the Github issue tracker to ask general questions. Use the mailing list: https://rtpengine.com/mailing-list
