### ISSUE TITLE
Unable to create an rtpengine docker swarm service

### ISSUE THREAD

**Issue by githubsw** [sipwise/rtpengine#1519]
Hello,
rtpengine is working good when running in a Docker Container, but if I try to create a Swarm Service of rtpengine, rtpengine is not able to run.  I did notice in Swarm mode that running in 'privileged' mode is not allowed and wonder if this is the issue.

The only errors I am seeing look like => "sed: cannot rename /etc/sedaoKyS2: Device or resource busy".

Any thoughts?

Thank you.

**Comment by rfuchs** [comment]
Docker is not officially supported, so no idea. Don't even know what a swarm service is.

Closing since this is not a code issue. Ask on the mailing list, maybe someone there has an idea. https://rtpengine.com/mailing-list

**Comment by githubsw** [comment]
Thank you for the quick response.  I will try the mailing list.
