### ISSUE TITLE
Cannot open libwebsockets.so.15

### ISSUE THREAD

**Issue by davidvoisonics** [sipwise/rtpengine#1527]
We are installing rtpengine mr10.5.1 on Ubuntu 22.04, which ships with the "libwebsockets16" package which I believe contains Libwebsockets version 4.0.20. Running rtpengine fails with an error:

/usr/sbin/rtpengine: error while loading shared libraries: libwebsockets.so.15: cannot open shared object file: No such file or directory

Is this because rtpengine doesn't support the installed version of libwebsockets? If so, do you have any idea when it will be supported? Thank you.

**Comment by rfuchs** [comment]
Both versions are supported, but you need to use a build that links against the version that you have installed. Rebuild locally, or use a package that matches your distribution and version.

Not a code issue, closing. Use the mailing list for general questions: https://rtpengine.com/mailing-list
