### ISSUE TITLE
Cisco SPA-series and SRTP/RTCP

### ISSUE THREAD

**Issue by mtryfoss** [sipwise/rtpengine#153]
Hi,

Audio is working fine when using SRTP on these phones, but I get an error on RTCP:
Discarded invalid SRTCP packet: authentication failed

Based on a pcap, it seems like the Cisco sends RTCP unencrypted while encrypting the RTP?

http://code.tryfoss.no/files/rtcp2.pcap

**Comment by rfuchs** [comment]
That's what it looks like. SDES supports this if it was signalled properly. Was it?

**Comment by mtryfoss** [comment]
Actually, I missed something obvious. The phone doesn't seem to specify rtcp at all in the invite:
v=0 
o=- 2585 2585 IN IP4 10.61.10.160 
s=- 
c=IN IP4 10.61.10.160 
t=0 0 
m=audio 16478 RTP/SAVP 9 8 0 2 18 101 
a=rtpmap:9 G722/8000 
a=rtpmap:8 PCMA/8000 
a=rtpmap:0 PCMU/8000 
a=rtpmap:2 G726-32/8000 
a=rtpmap:18 G729a/8000 
a=rtpmap:101 telephone-event/8000 
a=fmtp:101 0-15 
a=ptime:20 
a=sendrecv 
a=crypto:1 AES_CM_128_HMAC_SHA1_32 inline:nnG/PpJHzE0uSirvQsgkIT5BpMVyvFTfzlpBQpW3 
a=crypto:2 AES_CM_128_HMAC_SHA1_80 inline:nnG/PpJHzE0uSirvQsgkIT5BpMVyvFTfzlpBQpW3 

But it sends anyway, and rtpengine sees it:
[9c9bfd0e-f033b2e2@10.61.10.160 port 47571] Confirmed peer address as 10.61.10.160:16479

I guess this is just a huge bug in the phone firmware then?

**Comment by rfuchs** [comment]
RTCP doesn't have to be explicitly specified in the SDP, its presence is implied. But the a=crypto attributes don't indicate unencrypted SRTCP, so this would indeed be a bug.
