### ISSUE TITLE
Cross server redis subscription (multiple redis connections)

### ISSUE THREAD

**Issue by etamme** [sipwise/rtpengine#1534]
I apologize, I wasn't sure where else to ask this.  

Is it possible to have a active/passive setup where each host A and B run their own local redis servers, and have host A subscribe to redis keyspaces on host B, and vice versa?  Every example, and documentation I have read shows subscribing to keyspaces on the SAME redis host.  

looking through the source code and see in `struct rtpengine_common_config common;` that there are two endpoints defined for redis...

`	endpoint_t		redis_ep;
	endpoint_t		redis_write_ep;`

is there any possibility to provide our "local" redis host for read/write and a secondary redis host for keyspace subscription?

**Comment by rfuchs** [comment]
Yes this should work just fine. Configure different Redis instances for `redis-read` and `redis-write`. Wherever you "write" to should trigger the notification on the other "read" instance and vice versa.

We have a mailing list for questions like this: https://rtpengine.com/mailing-list
