### ISSUE TITLE
Installing rtpengine onto Ubuntu 18

### ISSUE THREAD

**Issue by InnovateAsterisk** [sipwise/rtpengine#1536]
Hi, im running into multiple issues installing RTP Engine onto Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-1084-aws x86_64)

This site: https://dfx.at/rtpengine/ has no $DIST for 18 (bionic), and bullseye doesn't work.

Also trying to build via source get to this unsolvable issue:

```libsystemd-dev : Depends: libsystemd0 (= 237-3ubuntu10.53) but 237-3ubuntu10.54 is to be installed``` so 
i get 
```dpkg-checkbuilddeps: error: Unmet build dependencies: libsystemd-dev```

**Comment by rfuchs** [comment]
That looks like an Ubuntu-internal problem. We only depend on `libsystemd-dev` and don't depend on `libsystemd0` directly.

**Comment by InnovateAsterisk** [comment]
I found the deb file, and installed it without dependancies (```sudo dpkg -i --ignore-depends=libsystemd0 libsystemd-dev_237-3ubuntu10_amd64.deb```), this cleared the ```dpkg-checkbuilddeps``` error.

Now the installation has an error at:
```
dpkg-shlibdeps: error: no dependency information found for /usr/local/lib/libbcg729.so.0 (used by debian/ngcp-rtpengine-daemon/usr/bin/rtpengine)
Hint: check if the library actually comes from a package.
```
But this: https://github.com/BelledonneCommunications/bcg729 is installed. I would rather not exclude it g729.

**Comment by rfuchs** [comment]
You cannot build Debian packages using libraries that aren't also from Debian packages. Either package bcg729 as a .deb (or install an already built one), or omit it from your build. Or perhaps try with a statically linked library (not sure if that would work)

Closing this as this isn't an issue with the code but rather with your build environment. We have a mailing list for non-code-issues: https://rtpengine.com/mailing-list
