### ISSUE TITLE
Cannot send Publish command with video offer.

### ISSUE THREAD

**Issue by telcomate** [sipwise/rtpengine#1538]
I'm trying to create a mutli-party video conference using the low level Publish / Subscribe Request / Subscribe Answer commands. Publish with m=audio SDP is working fine. It gets processed and I receive SDP answer with recvonly as expected. However publish with SDP that contains m=video is not working and I'm getting warning about codec, see below log from rtpengine. Client generating this SDP is the most recent Chrome (I stripped everything but VP8 in this case, but it's not working with full Chrome's codec list either) and RTPEngine is at version: 11.0.1.0+0~mr11.0.1.0 git-HEAD-f0dc5379

Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: INFO: [aaaaaaaaaa]: [control] Received command 'publish' from 172.18.180.84:60084
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: DEBUG: [aaaaaaaaaa]: [control] Dump for 'publish' from 172.18.180.84:60084: { "call-id": "aaaaaaaaaa", "command": "publish", "from-tag": "c4a4c791-d880-43cf-aa41-0bd8dcf09040", "interface": "external", "sdp": "v=0
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: o=- 7368282606379984000 2 IN IP4 127.0.0.1
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: s=-
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: t=0 0
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=group:BUNDLE 0 1
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=extmap-allow-mixed
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=msid-semantic: WMS Zdvtbk40HevJEdPBCWfmWlEUDvJn7cZTjKfE
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: m=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 0 8 106 105 13 110 112 113 126
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: c=IN IP4 0.0.0.0
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtcp:9 IN IP4 0.0.0.0
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=candidate:2705937882 1 udp 2113937151 7565b89c-de1f-41ea-8b41-4dd01b03871c.local 60922 typ host generation 0 network-cost 999
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=ice-ufrag:OWXE
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=ice-pwd:v9aKEJt6vYQuJkFpCjXvDAuW
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=ice-options:trickle
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=fingerprint:sha-256 8E:6B:21:4B:E2:7D:DC:C2:11:88:A9:2B:80:98:76:C9:3A:ED:F1:80:BA:0D:B4:88:D0:B4:70:43:53:E4:8E:07
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=setup:actpass
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=mid:0
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=sendonly
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=msid:Zdvtbk40HevJEdPBCWfmWlEUDvJn7cZTjKfE 374bae45-5c56-4909-ae1d-acbf19f3890f
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtcp-mux
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtpmap:111 opus/48000/2
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtcp-fb:111 transport-cc
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=fmtp:111 minptime=10;useinbandfec=1
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtpmap:63 red/48000/2
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=fmtp:63 111/111
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtpmap:103 ISAC/16000
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtpmap:104 ISAC/32000
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtpmap:9 G722/8000
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtpmap:0 PCMU/8000
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtpmap:8 PCMA/8000
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtpmap:106 CN/32000
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtpmap:105 CN/16000
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtpmap:13 CN/8000
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtpmap:110 telephone-event/48000
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtpmap:112 telephone-event/32000
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtpmap:113 telephone-event/16000
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtpmap:126 telephone-event/8000
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=ssrc:1658967069 cname:/PE4D4gVYZpgR3qg
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=ssrc:1658967069 msid:Zdvtbk40HevJEdPBCWfmWlEUDvJn7cZTjKfE 374bae45-5c56-4909-ae1d-acbf19f3890f
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: m=video 9 UDP/TLS/RTP/SAVPF 96
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: c=IN IP4 0.0.0.0
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtcp:9 IN IP4 0.0.0.0
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=candidate:2705937882 1 udp 2113937151 7565b89c-de1f-41ea-8b41-4dd01b03871c.local 63696 typ host generation 0 network-cost 999
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=ice-ufrag:OWXE
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=ice-pwd:v9aKEJt6vYQuJkFpCjXvDAuW
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=ice-options:trickle
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=fingerprint:sha-256 8E:6B:21:4B:E2:7D:DC:C2:11:88:A9:2B:80:98:76:C9:3A:ED:F1:80:BA:0D:B4:88:D0:B4:70:43:53:E4:8E:07
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=setup:actpass
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=mid:1
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=extmap:13 urn:3gpp:video-orientation
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=sendonly
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=msid:Zdvtbk40HevJEdPBCWfmWlEUDvJn7cZTjKfE 65aa6e57-8149-4ce1-b2b9-342975555fb7
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtcp-mux
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtcp-rsize
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtpmap:96 VP8/90000
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtcp-fb:96 goog-remb
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtcp-fb:96 transport-cc
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtcp-fb:96 ccm fir
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtcp-fb:96 nack
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=rtcp-fb:96 nack pli
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=ssrc-group:FID 720909015 3303739857
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=ssrc:720909015 cname:/PE4D4gVYZpgR3qg
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=ssrc:720909015 msid:Zdvtbk40HevJEdPBCWfmWlEUDvJn7cZTjKfE 65aa6e57-8149-4ce1-b2b9-342975555fb7
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=ssrc:3303739857 cname:/PE4D4gVYZpgR3qg
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: a=ssrc:3303739857 msid:Zdvtbk40HevJEdPBCWfmWlEUDvJn7cZTjKfE 65aa6e57-8149-4ce1-b2b9-342975555fb7
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: " }
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: DEBUG: [aaaaaaaaaa]: [core] Using default bitrate of 32000 bps for 2-channel Opus
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: NOTICE: [aaaaaaaaaa]: [core] Creating new call
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: DEBUG: [aaaaaaaaaa]: [codec] Adding codec opus/48000/2 (111)
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: DEBUG: [aaaaaaaaaa]: [codec] Adding codec red/48000/2 (63)
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: DEBUG: [aaaaaaaaaa]: [codec] Adding codec ISAC/16000 (103)
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: DEBUG: [aaaaaaaaaa]: [codec] Adding codec ISAC/32000 (104)
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: DEBUG: [aaaaaaaaaa]: [codec] Adding codec G722/8000 (9)
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: DEBUG: [aaaaaaaaaa]: [codec] Adding codec PCMU/8000 (0)
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: DEBUG: [aaaaaaaaaa]: [codec] Adding codec PCMA/8000 (8)
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: DEBUG: [aaaaaaaaaa]: [codec] Adding codec CN/32000 (106)
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: DEBUG: [aaaaaaaaaa]: [codec] Adding codec CN/16000 (105)
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: DEBUG: [aaaaaaaaaa]: [codec] Adding codec CN/8000 (13)
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: DEBUG: [aaaaaaaaaa]: [codec] Adding codec telephone-event/48000 (110)
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: DEBUG: [aaaaaaaaaa]: [codec] Adding codec telephone-event/32000 (112)
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: DEBUG: [aaaaaaaaaa]: [codec] Adding codec telephone-event/16000 (113)
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: DEBUG: [aaaaaaaaaa]: [codec] Adding codec telephone-event/8000 (126)
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: DEBUG: [aaaaaaaaaa]: [core] set FILLED flag for stream, local 172.19.180.101:21744 remote 0.0.0.0:9
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: DEBUG: [aaaaaaaaaa]: [crypto] Creating active DTLS connection context
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: message repeated 2 times: [ DEBUG: [aaaaaaaaaa]: [crypto] Creating active DTLS connection context]
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: DEBUG: [aaaaaaaaaa]: [core] set FILLED flag for stream, local 172.19.180.101:0 remote 0.0.0.0:9
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: DEBUG: [aaaaaaaaaa]: [codec] Adding codec VP8/90000 (96)
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: WARNING: [aaaaaaaaaa]: [codec] No acceptable codecs found from publisher
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: ERR: [aaaaaaaaaa]: [core] Publish error
Sep  8 08:45:15 edn1-c-iacrtp-02t rtpengine[635700]: ERR: [aaaaaaaaaa]: [core] Failed to create SDP: Zero length media stream

**Comment by rfuchs** [comment]
Try again with an added `codec-accept-any` (i.e. `codec: { accept: [ any ] }`). Looks like this is missing from the docs.
