### ISSUE TITLE
Any chance we can get a new tag?

### ISSUE THREAD

**Issue by etamme** [sipwise/rtpengine#154]
A few fixes have gone in upstream recently to allow for building on older versions of both kernels, and centos.  Is there any way we can get a new tag at commit c6ff5e7c03fa49ef6216d7cfe09b3006ddb5d5f8 or later so we have some upstream marker vs. creating a local tag or branch off the commit?

**Comment by rfuchs** [comment]
What kind of tag would you like?

**Comment by etamme** [comment]
We are in the process of bringing rtpengine "in house" - the recent fixes on master are required for us to do this.  We would like to be able to have a tagged commit that is some point after these fixes (c6ff5e7 as i said would be a good place) because we do not want to just be running off latest master.  We would rather have the tag upstream so we can just update our upstream and merge to our local master.  I am not sure if what I am asking makes sense ... basically we dont want to run off master, but there is no tag current enough to contain the commits we need.

**Comment by taurus-forever** [comment]
Either wait for mr4.1 is released or fork and set the tag in necessary commit.

**Comment by etamme** [comment]
yeah we made a local tag for the time being - just like to keep things clean and in line with upstream

**Comment by taurus-forever** [comment]
Rtpengine is a part of Sipwise NGCP product which has simple and flexible releasing schema:
branch master - trunk, do everything you want
branch mrX.X (origin master) - stabilization branch for release mrX.X
branch mrX.X.Y (origin mrX.X) - frozen branch for release mrX.X (build Y)
tag mrX.X.Y.Z in branch mrX.X.Y - Git tag for public usage.

**Comment by etamme** [comment]
Thats good to know - and I was hoping there would be, for example, a mr4.0.1.3 at or after the commit i specified was really all.

**Comment by taurus-forever** [comment]
The commit c6ff5e7 is in master only for the moment (which is upcoming mr4.1.1.1).
To tag c6ff5e7 as mr4.0.1.3 we have to rollback changes to NGCP release mr4.0 build 1 (branched mr4.0 and mr4.0.1) which are a bit different code base. 

Our general policy is to spend our resources on high quality fast releases instead of on backporting.
So, for the moment you can tag your fork internally somehow and switch back to upstream as soon as mr4.1.1.1 is publicly available. I see no problems with that approach for you.

**Comment by etamme** [comment]
Thats fine - like i said, it was more of a convenience thing that anything else.  I appreciate the explanation of the release process.
