### ISSUE TITLE
Getting RTP stream statistics from RTPengine

### ISSUE THREAD

**Issue by masudmuborakshohi** [sipwise/rtpengine#1540]
OS: Debian 11.4
RTPengine-Version: 10.3.0.0+0~mr10.3.0.0 git-master-b8a554c0
Kamailio-version: kamailio 5.5.3 (x86_64/linux) 473cef  from GIT
Server params: Intel(R) Xeon(R) Silver 4314 CPU @ 2.40GHz/128Gb DDR-4

I tried to take statistics from RTPengine from Kamailio and after 2 hours of active work, RTPengine crashed. I have 2 RTPengine nodes working in parallel on different servers separately. The principle is https://denys-pozniak.medium.com/getting-rtp-stream-statistics-from-rtpengine-d5b92e408d28 , only I take all the parameters for A and B.
After the crash, I found a lot of such messages in the logs:
Sep 8 09:17:48 debian rtpengine[343985]: ERR: [core] Failed to push relay stream to kernel: File exists
Sep 8 09:17:48 debian rtpengine[343985]: ERR: [core] Failed to push relay stream destination to kernel: Device or resource busy
Sep 8 09:17:48 debian rtpengine[343985]: ERR: [core] Failed to push relay stream to kernel: File exists
Sep 8 09:17:48 debian rtpengine[343985]: ERR: [core] Failed to push relay stream destination to kernel: Device or resource busy
And after finishing this:
Sep 8 09:17:48 debian rtpengine[343985]: ERR: [core] Failed to push relay stream to kernel: File exists
Sep 8 09:17:48 debian rtpengine[343985]: ERR: [core] Failed to push relay stream destination to kernel: Device or resource busy
Sep 8 09:17:48 debian rtpengine[343985]: ERR: [core] Failed to push relay stream to kernel: File exists
Sep 8 09:17:48 debian rtpengine[343985]: ERR: [core] Failed to push relay stream destination to kernel: Device or resource busy
Sep 8 09:17:48 debian rtpengine[343985]: ERR: [2eade4ee-c928-4314-8c63-0aee00876769 port 35772]: [core] SRTP output wanted, but no crypto suite was negotiated
Sep 8 09:17:48 debian rtpengine[343985]: WARNING: [mzw3m3gej1wgthwehfmxcggf1dw0cgec@10.18.5.64]: [control] Protocol error in packet from 10.241.60.46:60727: Unknown call-id [d8:supportsl10:load limite7:call -id43:mzw3m3gej1wgthwehfmxcggf1dw0cgec@10.18.5.6413:received-froml3:IP411:10.110.1.14e8:from-tag24:jt0hfith-CC-1031-OFC-1086:to-tag36:9fd30200-de37-448a-aa9c-5566879825c77:command5: querye]
Sep 8 09:17:48 debian rtpengine[343985]: ERR: [core] Failed to push relay stream to kernel: File exists
Sep 8 09:17:48 debian rtpengine[343985]: ERR: [core] Failed to push relay stream destination to kernel: Device or resource busy
Sep 8 09:17:48 debian rtpengine[343985]: WARNING: [f59864ce-00d1-4c51-a60e-f0560c8f5daa port 30181]: [rtcp] Discarded invalid SRTCP packet: authentication failed
Sep 8 09:17:48 debian rtpengine[343985]: ERR: [core] Failed to push relay stream to kernel: File exists
Sep 8 09:17:48 debian rtpengine[343985]: ERR: [core] Failed to push relay stream destination to kernel: Device or resource busy
Sep 8 09:17:48 debian rtpengine[343985]: ERR: [720c9d7a-74f8-412b-83ad-21c1477a27ef port 35754]: [core] SRTP output wanted, but no crypto suite was negotiated
Sep 8 09:17:48 debian rtpengine[343985]: WARNING: [a88f67e7-a726-4c98-b2cd-821d7a0b2887 port 33023]: [rtcp] Discarded invalid SRTCP packet: authentication failed
Sep 8 09:17:48 debian rtpengine[343985]: WARNING: [esr0bbfo9fhvs0orbohq9mfrqsrpyypr@10.18.5.64]: [control] Protocol error in packet from 10.241.60.46:59655: Unknown call-id [d8:supportsl10:load limite7:call -id43:esr0bbfo9fhvs0orbohq9mfrqsrpyypr@10.18.5.6413:received-froml3:IP413:85.140.19.158e8:from-tag36:a324301d-e0c3-4d53-badf-da5d87d5d6926:to-tag24:sfvqqevv-CC-1041-OFC-1087:command5: querye]
Sep 8 09:17:49 debian rtpengine[343985]: rtpengine: media_socket.c:1031: stream_fd_closed: Assertion `sfd->socket.fd == fd' failed.
Sep 8 09:17:49 debian systemd[1]: ngcp-rtpengine-daemon.service: Main process exited, code=killed, status=6/ABRT
Sep 8 09:17:50 debian systemd[1]: ngcp-rtpengine-daemon.service: Failed with result 'signal'.
Sep 8 09:17:50 debian systemd[1]: ngcp-rtpengine-daemon.service: Consumed 31min 57.646s CPU time.
Please help me solve this problem.

**Comment by rfuchs** [comment]
This has already been fixed. You need to upgrade.
