### ISSUE TITLE
Query on rtpengine statistics

### ISSUE THREAD

**Issue by wdavies-git** [sipwise/rtpengine#1548]
I checked online for documentation to answer the below but could not find anything relevant.

I would like to get the avganswerdelay avgofferdelay kind of stats from rtpengine via rtpengine-ctl but it seems currently this is only possible if rtpengine has a connection to a configured socket for graphite. As a test I am simply using netcat to service the connection and discard the statistics. 

Is it possible in any current release to instead use a file system socket in lieu of a network socket? or another option?

Thanks and Kind Regards,

Wayne

**Comment by rfuchs** [comment]
These stats are reported in the JSON output (`list jsonstats`) and are also exported on the Prometheus interface (HTTP `/metrics` endpoint), although in a slightly different format.

```
  "controlstatistics": {
    "proxies": [
      {
        "proxy": "::1",
        "pingcount": 0,
        "pingduration": 0,
        "offercount": 3,
        "offerduration": 0.018257,
        "answercount": 3,
        "answerduration": 0.007692,
...
```

```
# TYPE rtpengine_request_seconds_total counter
rtpengine_request_seconds_total{proxy="::1",request="ping"} 0.000000
rtpengine_requests_total{proxy="::1",request="offer"} 3
rtpengine_request_seconds_total{proxy="::1",request="offer"} 0.018257
rtpengine_requests_total{proxy="::1",request="answer"} 3
rtpengine_request_seconds_total{proxy="::1",request="answer"} 0.007692
```

Currently there isn't a way to enable the internal per-interval stats gathering required for Graphite without actually connecting to Graphite.

Don't use the Github issue tracker to ask general questions, use the mailing list instead: https://rtpengine.com/mailing-list

**Comment by wdavies-git** [comment]
Thank you Richard for the quick response and info. Apologies for posting here I will ensure to use the mailing-list for any other queries.
