### ISSUE TITLE
max number of file descriptors is reduced if not power of 2 

### ISSUE THREAD

**Issue by paulandrewhughes** [sipwise/rtpengine#155]
If number of file descriptors is not a power of 2 then rtpengine will reduce it to the nearest lower power of 2 on startup. 

It would be nice to check the new value is not less than existing value in following function.

```
static void resources(void) {
	int tryv;

	rlim(RLIMIT_CORE, RLIM_INFINITY);
	for (tryv = ((1<<16) - 1); tryv && rlim(RLIMIT_NOFILE, tryv) == -1; tryv >>= 1)
		;

	rlim(RLIMIT_DATA, RLIM_INFINITY);
	rlim(RLIMIT_RSS, RLIM_INFINITY);
	rlim(RLIMIT_AS, RLIM_INFINITY);
}
```

**Comment by rfuchs** [comment]
Under which circumstances does this actually happen?

**Comment by paulandrewhughes** [comment]
E.g Start rtpengine with ulimit for file descriptors of 64000
```
[user@host]~% ulimit -n
64000
[user@host]~% rtpengine -L 3 -E --interface 10.10.10.43 --listen-ng 10.10.10.43:1025 -f -m 1026 -M 65535
```

Check value of limits of running process and find that it has been reduced to 32767.
```
[user@host fd]# ps -ef | grep rtpengine
user     5724  5698  0 09:40 pts/0    00:00:00 rtpengine -L 3 -E --interface 10.10.10.43 --listen-ng 10.10.10.43:1025 -f -m 1026 -M 65535

[user@host fd]# grep "Max open files" /proc/5724/limits 
Max open files            32767                32767                files     
[user@host fd]# 
```

The for loop in resource function tries 2^16 which fails, then tries 2^15 which works however this is significantly less than what it was already.

**Comment by rfuchs** [comment]
Already fixed in some recent commit
