### ISSUE TITLE
deterministic channel ordering for call recordings

### ISSUE THREAD

**Issue by ozgurakcali** [sipwise/rtpengine#1550]
I am using rtpengine for call recordings. I am using wav output type with mix-method: channels. I want to ensure though that the caller audio is on channel 0 and callee audio is on channel 1. As far as I can see, there is no way to ensure this yet, ordering is determined by whichever party sends rtp packets first.

I am thinking of creating an updated version of rtpengine for this need. What I think of is, sending special to / from tags when setting up a call, and reading these tags to determine channel indices here: https://github.com/sipwise/rtpengine/blob/4d148cd51abc8f18defdc66dade49ed1a4ad6199/recording-daemon/mix.c#L84

By doing something like:
```
  - read tag name for ssrc
  - if tag name corresponds to caller -> use index 0
  - if tag name corresponds to callee -> use index 1
  - otherwise -> proceed as is, starting from index 2
```

Do you think this approach makes sense? And if not, do you have any suggestions to make deterministic channel ordering work?

**Comment by rfuchs** [comment]
Tags are already numbered. You can see this in
```
struct call_monologue {
        struct call             *call;          /* RO */
        unsigned int            unique_id;      /* RO */
```
The unique ID starts at 0 for each call. This ID is also communicated to the recording daemon:
```
struct tag_s {
        unsigned long id;
```
And this ID is determined based on the order that they were created during the offer/answer exchange.

If you want more explicit control over the ordering, you could use the "label" field, which is user-settable and wouldn't require playing with the tag names themselves.

**Comment by ozgurakcali** [comment]
@rfuchs Thanks a lot for the help Richard, this makes it much simpler and cleaner.

**Comment by rfuchs** [comment]
Next time please use the mailing list for questions like this: https://rtpengine.com/mailing-list
