### ISSUE TITLE
sdp issue 

### ISSUE THREAD

**Issue by gerkernan** [sipwise/rtpengine#1551]
hi 
looking for advise on correct way to configure rtpengine with kamailio
setup is Kamailio running in front of asterisk . SIP/RTP are natted to the kamailio server private IP 
im using this setup for interface in rtpengine.conf
interface = internal/10.3.1.6;extenal/10.3.1.6!20.82.xx.xx

and in kamailio.conf 

 rtpengine_offer("replace-origin replace-session-connection ICE=remove direction=external direction=internal");

but the SDP thats sent to caller always has the private IP of the kamailio/rtpengine server in the c=IN field 

any advise to poimnt me in correct direction would be great 

Thanks
Gerry

**Comment by rfuchs** [comment]
Duplicated from here https://lists.kamailio.org/pipermail/sr-users/2022-October/115603.html

You're probably running with a different config or aren't engaging rtpengine properly.
