### ISSUE TITLE
rtp/avp and srtp/savp flows simultaneously

### ISSUE THREAD

**Issue by baevga** [sipwise/rtpengine#1555]
Hello!
I have a problem when i get 2 inbound flows: one rtp/avp and second srtp/savp. If there any possibility to make outbound the same way - one rtp/avp and second srtp/savp? 
If i set srtp flag then both of them become srtp, if unset it both just rtp.

Will be very apriciate for any help

**Comment by baevga** [comment]
Yes, this exactly what i do, please give me advice how to enable "strictly passthrough"

**Comment by rfuchs** [comment]
Strictly passthrough means not forcing any particular transport protocol. So if the input SDP is dual RTP and SRTP then the output SDP will also be dual RTP and SRTP if you don't specify anything else.
