### ISSUE TITLE
Write a wav file with 2 channel

### ISSUE THREAD

**Issue by denialhaq** [sipwise/rtpengine#1557]
Hi everyone,

I have rtp engine running and can doing siprec recording without no problem.
But i have a wav file with 4 channel stereo with 2 silent channel.

<img width="1440" alt="Screen Shot 2022-10-25 at 13 05 25" src="https://user-images.githubusercontent.com/46884796/197695086-e7660824-bf98-4b31-98a5-806134cd14b6.png">

Is there a way to make it ony 2 channel?
Here is my rtp engine settings

> [rtpengine]
> table=0
> interface=192.168.1.10       
> foreground=true
> log-stderr=true
> listen-ng=127.0.0.1:22222
> port-min=23000
> port-max=32768
> recording-dir=/var/spool/rtpengine
> recording-method=proc
> recording-format=eth
> log-level=7

> [rtpengine-recording]
> table = 0
> #output-format = mp3
> output-format = wav             
> #resample-to = 16000
> resample-to = 8000
> #mp3-bitrate = 48000
> #output-mixed = 1
> output-mixed = true
> #output-mixed = false
> #output-single = true
> mix-method = channels
> log-level = 7
> spool-dir = /var/spool/rtpengine
> output-dir = /var/lib/rtpengine-recording       
> output-storage = both

**Comment by rfuchs** [comment]
This is currently hard-coded (see `#define MIX_NUM_INPUTS 4` in `mix.h`) and due to limitations in how output files are generated cannot be changed on the fly. Either recompile with the default change, or downmix the file in post.

**Comment by denialhaq** [comment]
Thank you for your response, is there any reason why it put as 4 instead of 2?

**Comment by rfuchs** [comment]
To allow for things like call forwards, IVRs, music on hold, etc. Since the number of channels has to be predetermined when the file is initially created, limiting it to 2 would increase the chances that some SSRC needs to be dropped or discarded from the recording.

**Comment by rfuchs** [comment]
You will get this type of output any time you use the recording daemon with the `channels` mode mixed output.

**Comment by denialhaq** [comment]
Thank you for your response, i can produce 2 channels wav file with full audio now.

**Comment by denialhaq** [comment]
Is there a way to add this on rtpengine-recording parameter? it could more useful i think,  rather than we recompile the code each time we need it.

**Comment by rfuchs** [comment]
Sure there is way, someone just needs to do it 😃

**Comment by denialhaq** [comment]
maybe i can help 😄 , would you please explain the workflow

**Comment by rfuchs** [comment]
Convert the compile-time setting into a config variable, listed in main.h, and then convert the arrays that uses this variable as their size into dynamically allocated ones. That's all that should be required.
