### ISSUE TITLE
Add `log-name` option

### ISSUE THREAD

**Issue by Dup4** [sipwise/rtpengine#1559]
rtpengine supports writing logs to syslog and supports setting `log-facilty` to allow writing to a custom log-facilty

However, the only custom log-facilty in syslog is `local0 - local7`

So when I need to deploy multiple rtpengines on one machine and need them to write logs to different files, there is no other way than to configure different `log-facilty`s and the custom log-facilty is limited to 8, which means I can deploy a maximum of 8.

But if we can add an option, `log-name`, we can pass it into the `log_init()` function, so that the `log-name` configuration controls the prefix of log printing, and with the [filter conditions of syslog](https://www.rsyslog.com/doc/master/configuration/filters.html), we can configure all rtpengine instances with the same `log-facilty`, but write them to different files via `log-name`

The advantage of this is that `log-name` has an unlimited number of options.

https://github.com/sipwise/rtpengine/blob/aab897d62e9e549431b715f76971f5773f5643e8/daemon/main.c#L1026

<img width="840" alt="image" src="https://user-images.githubusercontent.com/38343778/199061655-ddca5c53-0e2d-4987-83e1-1d214a260844.png">

If this proposal works, I can submit a PR.

**Comment by rfuchs** [comment]
Sure, happy to accept such a PR. I suggest to put that option into `lib/auxlib.c` so that the recording daemon can benefit too. Remember to document it in the .pod file.
