### ISSUE TITLE
Loadable Kernel Module 

### ISSUE THREAD

**Issue by dia2e2** [sipwise/rtpengine#1565]
I am trying to create a Kernel Module but keep running into this issue and it won't compile make. 

alex@alex:~$ make
make -C /lib/modules/5.15.0-52-generic/build M=/home/alex modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-52-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
  You are using:           gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
make[2]: *** No rule to make target '/home/alex/hello.o', needed by '/home/alex/hello.mod'.  Stop.
make[1]: *** [Makefile:1900: /home/alex] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-52-generic'
make: *** [Makefile:4: all] Error 2

**Comment by rfuchs** [comment]
What on Earth is `hello.o`? Is this about rtpengine at all?

**Comment by mloskot** [comment]
@rfuchs It looks like a lost cowboy trying GitHub instead of StackOverflow. We've received similar garbage https://github.com/boostorg/gil/issues/721

**Comment by rfuchs** [comment]
> @rfuchs It looks like a lost cowboy trying GitHub instead of StackOverflow. We've received similar garbage [boostorg/gil#721](https://github.com/boostorg/gil/issues/721)

I thought as much. Thanks for the heads up @mloskot
