### ISSUE TITLE
Using offer in recorder setup with "media-echo"="blackhole" results in partial audio.

### ISSUE THREAD

**Issue by nschoemakerTelecats** [sipwise/rtpengine#1567]
Hello,

We are trying to set up RTP engine to produce wave files without returning the RTP-stream.

The Media-echo option in the offer command appears to be able to do this, however when reviewing the audio files afterwards they appear to be cut off at around the 3 second mark.
Am I missing something or am I looking in the wrong direction?
We are using the drachtio-SRS to send the offer command.

We appear to be able to achieve the desired result by sending a media stop on one leg directly after the offer, but I would like it better if it were fixed in either the offer or configuration.

Thank you in advance,
Niels Schoemaker

**Comment by rfuchs** [comment]
Try removing the iptables rule for the kernel module and see if that makes a difference.

**Comment by nschoemakerTelecats** [comment]
Thank you for the quik response, 

I've tried removing the iptables rule but the audio still cuts off between 2.6 and 3.5 seconds.

**Comment by nschoemakerTelecats** [comment]
Hello,

I've retested your suggestion and it works as long as you keep the rule(s) in the rtpengine chain deleted.
The reason my initial test failed was due to the machine restarting.

Could you explain why this solution works?

Thank you,
Niels Schoemaker

**Comment by rfuchs** [comment]
I suspected that the kernel module doesn't export the received packets back to userspace for recording in a blackhole scenario. Now that this is confirmed it should be relatively easy to fix this by moving some conditionals around.

**Comment by rfuchs** [comment]
0afc6fc358c2476ca4bbe895fd48f358a8a277aa is a possible fix for this

**Comment by nschoemakerTelecats** [comment]
We've tested the suggested fix and it appears to solve out issue.

Thank you
