### ISSUE TITLE
telephone-event digits are relayed all but the last digit in the transcoding scenario

### ISSUE THREAD

**Issue by andingv** [sipwise/rtpengine#1569]
**Issue :**
When multiple DTMF digits are sent from MT UE to MO UE  in a transcoded scenario, 
only the last DTMF digit is NOT received at MO UE side. ( here the last DTMF event is 3)
I see some issues at RTPEngine 1 side. It seems not to be processing the last DtmF digit 
(Here Incoming SSRC 5711bf84, PT 96 . Packets : seq 62814, seq 62815 , seq 62816 , seq 62817)

My colleague designed a slide and captured the issue scenario in the pic ( also included in the attachment)
pcap trace and syslog also included.
We would like to ask your feedback please about what could be causing this.
![Issue scenario](https://user-images.githubusercontent.com/74421031/202994882-9f1bda4e-7781-4627-8524-7a6372ec056f.JPG)

Both in pcap trace and in syslog I see DTMF digit 3 packets have been received at RTP engine 1
-----------------------

> Nov  8 14:24:32 hari-pcrf rtpengine[4994]: DEBUG: [1-7490@10.129.59.1 port 10116]: [transcoding] Received telephone-event supplemental RTP packet: SSRC 5711bf84, PT 224, seq 62814, TS 3931163961, len 4
> Nov  8 14:24:32 hari-pcrf rtpengine[4994]: DEBUG: [1-7490@10.129.59.1 port 10116]: [core] Handling packet: remote 10.129.4.7:10132 (expected: 10.129.4.7:10132) -> local 10.129.4.5:10116 (RTP seq 62815 TS 3931163961 SSRC 5711bf84)
> Nov  8 14:24:32 hari-pcrf rtpengine[4994]: DEBUG: [1-7490@10.129.59.1 port 10116]: [transcoding] Received telephone-event supplemental RTP packet: SSRC 5711bf84, PT 96, seq 62815, TS 3931163961, len 4
> Nov  8 14:24:32 hari-pcrf rtpengine[4994]: DEBUG: [1-7490@10.129.59.1 port 10116]: [core] Handling packet: remote 10.129.4.7:10132 (expected: 10.129.4.7:10132) -> local 10.129.4.5:10116 (RTP seq 62816 TS 3931163961 SSRC 5711bf84)
> Nov  8 14:24:32 hari-pcrf rtpengine[4994]: DEBUG: [1-7490@10.129.59.1 port 10116]: [transcoding] Received telephone-event supplemental RTP packet: SSRC 5711bf84, PT 96, seq 62816, TS 3931163961, len 4
> Nov  8 14:24:32 hari-pcrf rtpengine[4994]: DEBUG: [1-7490@10.129.59.1 port 10116]: [core] Handling packet: remote 10.129.4.7:10132 (expected: 10.129.4.7:10132) -> local 10.129.4.5:10116 (RTP seq 62817 TS 3931163961 SSRC 5711bf84)
> Nov  8 14:24:32 hari-pcrf rtpengine[4994]: DEBUG: [1-7490@10.129.59.1 port 10116]: [transcoding] Received telephone-event supplemental RTP packet: SSRC 5711bf84, PT 96, seq 62817, TS 3931163961, len 4
> Nov  8 14:24:32 hari-pcrf rtpengine[4994]: DEBUG: [1-7490@10.129.59.1 port 10116]: [core] Handling packet: remote 10.129.4.7:10132 (expected: 10.129.4.7:10132) -> local 10.129.4.5:10116 (RTP seq 62818 TS 3931163961 SSRC 5711bf84)
> Nov  8 14:24:32 hari-pcrf rtpengine[4994]: DEBUG: [1-7490@10.129.59.1 port 10116]: [transcoding] Received telephone-event supplemental RTP packet: SSRC 5711bf84, PT 96, seq 62818, TS 3931163961, len 4
---------------------

Version branch rfuchs/dtx-pt-change-fix
Thsi is mr10.5 snapshot around June 15
`commit 64d65de0f480060dd9cec7e6e0da0db5634754e2 (HEAD)
Author: Chris Lamb <lamby@debian.org>
Date:   Tue Jun 14 00:47:45 2022 +0200

commit 70cc3a98db0c79d2ac5902b683d3a3e677c229bd
Author: Richard Fuchs <rfuchs@sipwise.com>
Date:   Fri Jun 10 15:10:44 2022 -0400

    TT#14008 test correct port for rejected stream`

Configuration (same for RTP-1 and RTP-2 save the IPs)

`[rtpengine]
table = 0
interface = 10.129.4.5
listen-ng = 10.129.4.5:22222
listen-cli = 10.129.4.5:9900
timeout = 60
silent-timeout = 3600
tos = 184
port-min = 10000
port-max = 20000
log-level = 7 
log-stderr = false
log-facility = local0
b2b-url = http://%%:5060/
xmlrpc-format = 2
dtx-delay = 0
max-dtx = 0
dtx-buffer = 10
dtx-shift = 5
dtx-lag = 100
listen-http = 10.129.4.5:22223
num-threads = 16
media-num-threads = 16`

---------------------
Expected Result:
DTMF packets shall be arrived to the UE-B in the same order how the packets are sent from UE-A and viceversa.
[Last DTMF digit not forwarded_Nov15th.zip](https://github.com/sipwise/rtpengine/files/10054479/Last.DTMF.digit.not.forwarded_Nov15th.zip)

Q: could it be because of DTX and mentioned in the logs negative clock skew? But on the other hand, we expected that dtx-delay=0 means already disabled DTX buffer.

**Comment by rfuchs** [comment]
Am I seeing this right that the DTMF event packets are sent with a different SSRC and also different sequence numbers from the primary audio stream, including obvious jumps in sequence numbers between the individual digits?

**Comment by andingv** [comment]
Good question, I guess i should check the specs more on our end.
Yes I have seen this. I think the way this user behaves is like Out-Of-band DTMF.

Although its mostly seen in SS7 legacy network.  So here the DTMF stream is NOT part of the Audio / Speech stream.

 It is having have its separate SSRC and separate sequence number that it follows. So I observed their event duration is also different that of audio stream.
In between DTMF digits are sequence number jumps , but for a single DTMF digits all the packets are incremented by +1 with the Sequence number.

Is that a valid scenario?
The first DTMF packet M bit (Marker bit ) is correctly set and for the last packet E bit (End bit) also correctly set. Here all the digits are relayed and only the last DTMF digit gets missed every time. When the callee sends only one digit it is relayed to the caller.

**Comment by rfuchs** [comment]
> Is that a valid scenario?

Well, not quite. The gaps in sequence numbers are seen as packet loss, and so the subsequent packets are held in a buffer until the sequencer determines that the lost packets are truly lost (not just delayed), and only then they are processed. For the last digit that never happens as there are no more packets coming after.

**Comment by kuaranjan** [comment]
Okay I see . Thanks @rfuchs 
Here  Out-Of-band DTMF digits are NOT part of the audio stream.
Hence it has a separate SSRC stream and follow their own sequence number patterns.

So I guess the issue here is there is Sequence number gaps between different DTMF digits that is causing the issue ..

Example Digit 6 packets follow Sequence number incremented by +1
Then there is sequence number Jump for the next Digit 7 … Then Digit 7 packets follow correct sequence number incremented by +1.. Then again there is sequence number jump.

So this seems invalid and causing an issue.

**Comment by andingv** [comment]
This case can be closed, thanks
