### ISSUE TITLE
rtpengine breaks calls from Firefox to Chrome

### ISSUE THREAD

**Issue by krieger-od** [sipwise/rtpengine#157]
This is a log of FF 40.0.3 calling to Chrome 45 through Kamailio and Rtpengine.
https://gist.github.com/krieger-od/59bfc10403a3817c0045

Check ```rtcninja:RTCPeerConnection setRemoteDescription() +4ms jssip.js:21365:8
rtcninja:ERROR:RTCPeerConnection setRemoteDescription() | error: +6ms DOMException [InvalidSessionDescriptionError: "Answer changes mid for level, was 'sdparta_0', now 'audio'"```

Rtpengine handling is set up with
```
rtpengine_manage("force trust-address replace-origin replace-session-connection rtcp-mux-demux ICE=force UDP/TLS/RTP/SAVPF");
```
for both request and reply.

https://gist.github.com/krieger-od/523d344e615d5cb1911c - same, but with Rtpengine handling disabled.
Same happens with newer (development - v44) versions of both FF and Chrome (v46, v47).

Tested with rtpengine rev. dafde105718005d2bd83e65a09227407ad49198d

Please contact me for access to our test server.

Thanks in advance.

**Comment by rfuchs** [comment]
Can you also post the log from rtpengine please.

**Comment by krieger-od** [comment]
rtpengine rev. dafde10. ``` --log-level=7```. log excerpt: https://gist.github.com/krieger-od/2defc185a1db42d6cf43

**Comment by rfuchs** [comment]
Try again with the following patch applied.

```
diff --git a/daemon/sdp.c b/daemon/sdp.c
index 5b8f261..a78e6ab 100644
--- a/daemon/sdp.c
+++ b/daemon/sdp.c
@@ -1657,10 +1657,7 @@ static int process_media_attributes(struct sdp_chopper *chop, struct sdp_media *
                        case ATTR_MID:
                                if (MEDIA_ISSET(media, PASSTHRU))
                                        break;
-                               a = attr_get_by_id(&sdp->session->attributes, ATTR_GROUP);
-                               if (a && a->u.group.semantics == GROUP_BUNDLE)
-                                       goto strip;
-                               break;
+                               goto strip;
 
                        default:
                                break;
```

**Comment by krieger-od** [comment]
Yes, it solves the issue. Thanks a lot! Please update the ticket when you push the fix to master.
