### ISSUE TITLE
debhelper-compat = 13 dependency issue. 

### ISSUE THREAD

**Issue by sahil-siwatch** [sipwise/rtpengine#1572]
Hello. I am trying to install rtpengine in my debian buster system and i am getting this dependency issue that i need debhelper-compat = 13. i tried the way that was given in the README.md file. 

root@PPM-LP01:/usr/src/rtpengine# apt-get install debhelper -t bionic-backports
Reading package lists... Done
E: The value 'bionic-backports' is invalid for APT::Default-Release as such a release is not available in the sources

I am getting this error. Any clues that why this must be happening ??

**Comment by rfuchs** [comment]
You need to use the appropriate backports script from https://github.com/sipwise/rtpengine/tree/master/pkg/deb

Run the generator script first, then apply the release-specific backports script, then use that as `debian` directory.
