### ISSUE TITLE
SDP "sess-version" not increased with SDP changes

### ISSUE THREAD

**Issue by thuroc** [sipwise/rtpengine#1574]
Hello RTPEngine Team,

we have a problem with the sdp sess-version inside the rtpengine. Could you have a look at this please?

**RTPEngine version:**
11.0.2.0+0~mr11.0.2.0 git-mr11.0-637b62f7

**SIP-Server:**
opensips 3.2.8

**Description:**
We have a call with two 200 OKs in which the second 200 OK is sent as a sip retransmit (missing ACK on the first 200 OK).

The origin SDP between the first und retransmitted 200 OK has not changed, but the rtpengine sets a new port for the retransmitted SDP and doesn't increase the sess-version in the o-Line.

The next hop does not recognize a new session version and keeps the first port and we've got a one sided audio-stream.

**Example:**

Origin-SDP from my customer to the RTPEngine (the first 200 OK and the retransmitted 200 OK are exacly the same SDP):
(200 OK B -> rtpengine)

> v=0
> o=- 199987 99987 IN IP4 [customer_IP]
> s=Cataleya
> c=IN IP4 [customer_IP]
> t=0 0
> m=audio 53238 RTP/AVP 8 101
> a=rtpmap:8 PCMA/8000
> a=ptime:20
> a=sendrecv
> a=rtpmap:101 telephone-event/8000
> a=fmtp:101 0-15

RTP-Engine generated SDP in the first 200 OK (all fine):
(200 OK rtpengine -> A)

> v=0
> o=- 199987 **99987** IN IP4 [my_proxy_ip]
> s=Cataleya
> c=IN IP4 [my_proxy_ip]
> t=0 0
> m=audio **47524** RTP/AVP 8 101
> a=rtpmap:8 PCMA/8000
> a=rtpmap:101 telephone-event/8000
> a=fmtp:101 0-15
> a=sendrecv
> a=rtcp:47525
> a=ptime:20

RTP-Engine generated SDP in the second/retransmitted 200 OK (changed port, but same sess-version):
(200 OK rtpengine -> A)

> v=0
> o=- 199987 **99987** IN IP4 [my_proxy_ip]
> s=Cataleya
> c=IN IP4 [my_proxy_ip]
> t=0 0
> m=audio **47662** RTP/AVP 8 101
> a=rtpmap:8 PCMA/8000
> a=rtpmap:101 telephone-event/8000
> a=fmtp:101 0-15
> a=sendrecv
> a=rtcp:47663
> a=ptime:20

**Comment by rfuchs** [comment]
Are you using the `replace-sdp-version` flag?

**Comment by thuroc** [comment]
Hello rfuchs,

no we dont, the rtpengine_offer function in the opensips modules doesn't support this flag.

rtpengine[12276]: WARNING: ... [core] Unknown flag encountered: 'replace-sdp-version'

Is there any other way i could activate this flag? Maybe at with the start of the rtpengine (for all call-legs)? --help doesn't offer me this flag too.

**Comment by thuroc** [comment]
Oh, i've got a look into the source files from the opensips module and there is a flag "replace-SDP-version" instead of "replace-sdp-version". Its only with big SDP letters. 

Thank you for your very fast help. I would try this out and report back if it didn't solve the problem.

**Comment by rfuchs** [comment]
You can try with 54ba7bf which adds support for the alternative form of the `replace-` flags
