### ISSUE TITLE
ubuntu compile fail:  undefined reference to `av_register_all'...

### ISSUE THREAD

**Issue by lglhust** [sipwise/rtpengine#1578]
Hello:
I'm trying to build RTPengine on Ubuntu Server (Bionic), DRTPENGINE_VERSION="\"10.5.1.5+0~mr10.5.1.5 git-mr10.5.1-a190a549\"
 but fail to build:

Below is the build cmd:

~/rtpengine# export DEB_BUILD_PROFILES="pkg.ngcp-rtpengine.nobcg729"
~/rtpengine# apt install dpkg-dev
~/rtpengine# git clone https://github.com/sipwise/rtpengine
~/rtpengine# git checkout mr10.5.1
~/rtpengine# dpkg-buildpackage -uc -us

Below is the output error.

codeclib.o: In function `codeclib_init':
./codeclib.c:1000: undefined reference to `av_register_all'
./codeclib.c:1001: undefined reference to `avcodec_register_all'
./codeclib.c:1002: undefined reference to `avfilter_register_all'
resample.o: In function `fix_frame_channel_layout':
./fix_frame_channel_layout.h:10: undefined reference to `av_frame_get_channels'
./fix_frame_channel_layout.h:15: undefined reference to `av_frame_get_channels'
collect2: error: ld returned 1 exit status
../lib/common.Makefile:7: recipe for target 'rtpengine-recording' failed
make[3]: *** [rtpengine-recording] Error 1
make[3]: Leaving directory '/root/rtpengine/recording-daemon'
../lib/common.Makefile:4: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/root/rtpengine/recording-daemon'
Makefile:21: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/rtpengine'
dh_auto_build: error: make -j56 "INSTALL=install --strip-program=true" returned exit code 2
debian/rules:31: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

when i run dpkg-checkbuilddeps,  no output. Build dependencies are ok.

I appreciate very much if you could help me.

**Comment by rfuchs** [comment]
We don't support bionic out of the box. Try looking for newer ffmpeg libraries.
