### ISSUE TITLE
Rtpengine logs getting truncated while in load . 

### ISSUE THREAD

**Issue by sasmita11** [sipwise/rtpengine#1582]
We are using rtpengine version : rtpengine-mr9.5.2.3
We are using a port range of 10000 i.e from 25000 - 35000 for RTP/UDP 

We have added some custom debug logs to see MOS and jitter as well .. 

But sometime when there is 50/60 cuncorrent calls running , at that time we are facing some issue in printinig all logs in the log file . 
Some of the line of the logs getting truncated automatically . In the log file we are not getting entier call log even when we are 
printing the logs in a custome file using command **--log-facility=local5**

Instance type : 
AWS Ec2 - m5a.large
Centos 8 

Can anybody please suggest what we can do here ?

**Comment by rfuchs** [comment]
This might be due to your syslog daemon truncating the lines. AFAIK rtpengine doesn't truncate log lines itself.

**Comment by sasmita11** [comment]
Is there any configuration on syslog not to truncate the logs?

**Comment by rfuchs** [comment]
Depends on your syslog daemon and is outside of the scope for rtpengine.
