### ISSUE TITLE
No audio when handover occurs (DTLS negotiation)

### ISSUE THREAD

**Issue by Andronikus** [sipwise/rtpengine#1585]
Hello,

I think this more a doubt than an issue that could exist in `rtpengine`.

`rtpengine` version in use: `9.5.3.5-1`

We have a scenario like that

                                                                     
 Client   <---- RTP/DTLS --->   RTPENGINE   <------RTP/UDP----->   Media Server 
                                                                  

Our client is a mobile app and everything works fine when we try to make a call.

When we are on a call and change from network (wifi - data or vice versa) (handover) a new INVITE is sent with the new network info and (from the signaling perspective) everything looks good.

Although that, no audio is available in the mobile app when the handover occurs.

We already found the possible issue that makes this happen... 

From the `rtpengine` logs we have the following:

- When the client starts the call we can see the DTLS handshake being done (client request Hello, server response Hello, ... )
- When the client changes the network, we can see that the client requests DTLS negotiation (send a hello request), we can see from `rtpengine` logs that the package is received `[srtp] Processing incoming DTLS packet` but no answer is sent to the client.

As the client never receives an answer for the DTLS negotiation it started, it never reaches the state to be ready to send RTP packets.

We cannot find the reason the answer was not sent (from the rtpengine logs). There is any to overcome this behaviour?

Thanks in advance

**Comment by rfuchs** [comment]
Does the client support ICE?

**Comment by Andronikus** [comment]
Thanks @rfuchs for the fast feedback!

Yes, the client support ICE.

From `rtpengine` logs when the call is initiate:

DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] Received ICE/STUN response code 0 for candidate pair 6d5fYjrDvq0Lgb5G:8961d8b93d0e5a8e0:1 from xx.61.132.xx:4007 to 10.9.9.38
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] Setting ICE candidate pair 6d5fYjrDvq0Lgb5G:8961d8b93d0e5a8e0:1 as succeeded
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] Best succeeded ICE pair with all components is 6d5fYjrDvq0Lgb5G:8961d8b93d0e5a8e0:1
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] ICE completed, using pair 6d5fYjrDvq0Lgb5G:8961d8b93d0e5a8e0:1
INFO:  [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] ICE negotiated: peer for component 1 is xx.61.132.xx:4007
INFO:  [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] ICE negotiated: local interface 10.9.9.38
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [srtp] Processing incoming DTLS packet


When the handover happens:

DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] Received ICE/STUN response code 0 for candidate pair 6d5fYjrDvq0Lgb5G:5dc96853d0e5a8e0:1 from xx.103.57.xxx:7058 to 10.9.9.38
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] Setting ICE candidate pair 6d5fYjrDvq0Lgb5G:5dc96853d0e5a8e0:1 as succeeded
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] Best succeeded ICE pair with all components is 6d5fYjrDvq0Lgb5G:5dc96853d0e5a8e0:1
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] ICE completed, using pair 6d5fYjrDvq0Lgb5G:5dc96853d0e5a8e0:1
INFO:  [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] ICE negotiated: peer for component 1 is xx.103.57.xxx:7058
INFO:  [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] ICE negotiated: local interface 10.9.9.38
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [core] Forward to sink endpoint: xx.103.57.xxx:7058 (RTP seq 9670 TS 1974272827)
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [srtp] Processing incoming DTLS packet

From this last log, it seems that rtpengine is already ready to send rtp packets to the new ip:port where the client is listen to. The last `Processing incoming DTLS packet` from the logs is the DTLS Client Hello message that is never answer.

**Comment by rfuchs** [comment]
Does it perform an ICE reset or restart during the re-invite? Or does it simply advertise additional ICE candidates to the existing ICE connection?

The DTLS connection is supposed to remain intact as long as the ICE connection remains intact (i.e. not reset). And DTLS should only be reconnected if ICE is also reset and restarted. At least that's my understanding of the RFC.

**Comment by Andronikus** [comment]
After the offer (that happens after the re-INVITE) we have the following logs of ice component

DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b]: [ice] ICE restart, resetting ICE agent
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b]: [ice] Learning new ICE candidate Hac5ccc7:1
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b]: [ice] Created candidate pair 6d5fYjrDvq0Lgb5G:Hac5ccc7:1 between 10.9.9.38 and 10.197.204.199:4010, type host
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b]: [ice] Learning new ICE candidate Hac5ccc7:2
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b]: [ice] Sending ICE/STUN request for candidate pair 6d5fYjrDvq0Lgb5G:Hac5ccc7:1 from 10.9.9.38 to 10.197.204.199:4010
(...)
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] Created candidate pair 6d5fYjrDvq0Lgb5G:5dc96853d0e5a8e0:1 between 10.9.9.38 and xx.103.57.xxx:7058, type prflx
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] Triggering check for 6d5fYjrDvq0Lgb5G:5dc96853d0e5a8e0:1
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] ICE pair 6d5fYjrDvq0Lgb5G:5dc96853d0e5a8e0:1 has been nominated by peer
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] ICE not completed yet and no usable candidates
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] Triggering check for 6d5fYjrDvq0Lgb5G:5dc96853d0e5a8e0:1
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] Received ICE/STUN response code 0 for candidate pair 6d5fYjrDvq0Lgb5G:5dc96853d0e5a8e0:1 from xx.103.57.xxx:7058 to 10.9.9.38
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] Setting ICE candidate pair 6d5fYjrDvq0Lgb5G:5dc96853d0e5a8e0:1 as succeeded
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] Best succeeded ICE pair with all components is 6d5fYjrDvq0Lgb5G:5dc96853d0e5a8e0:1
DEBUG: [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] ICE completed, using pair 6d5fYjrDvq0Lgb5G:5dc96853d0e5a8e0:1
INFO:  [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] ICE negotiated: peer for component 1 is xx.103.57.xxx:7058
INFO:  [0c7f44ac-048e-4c43-9ad1-847a7559ed4b port 15116]: [ice] ICE negotiated: local interface 10.9.9.38

So, it looks like the restart/reset happened.

**Comment by rfuchs** [comment]
Yes, that should in fact do a DTLS reset as well. Can you try with a newer version? 10.5 or newer.

**Comment by Andronikus** [comment]
@rfuchs we will try with a newer version. Will give feedback later 🙏

**Comment by Andronikus** [comment]
Hello again @rfuchs 

We updated the `rtpengine` to a new version (Version: `10.5.3.1-1~bpo10+1`) and the behavior is still the same.

Will add here some logs we get from `rtpengine` (debug 7)
https://gist.github.com/Andronikus/dc29b85d0109f15a2bbc7b54d8274ba5#file-rtpengine-handover-log

The offer after re-Invite (search for RE-INVITE in logs) looks like it lead to an Ice Restart

`[ice] ICE restart detected, resetting ICE agent`

`rtpengine` starts to forward packets to the new remote endpoint without DTLS negotiation.

`[core] Forward to sink endpoint: local 10.9.9.38:15089 -> remote aa.103.cc.ddd:7088 (RTP seq 27702 TS 2666283289 SSRC fdf1dab)`

When we use `DTLS=passive`, the client initiate the new DTLS negotiation after the network change but `rtpengine`  not answer to the requests.
When we use rtpengine as the DTLS initiator, after the Ice Restart there is no new negotiation.

**Comment by rfuchs** [comment]
Can you tell if the DTLS fingerprint in the SDP exchanges has changed between the original invite and the re-invite?

Does the `a=ufrag` value change in between?

Is the attribute `a=tls-id` present?

I double checked the RFCs and sadly RFC 5763 is very vague about when a DTLS reset is required, but mostly seems to say that only a single DTLS connection is required when ICE is in use at all.

RFC 8842 updates this and is more explicit, requiring the `a=tls-id` attribute to indicate whether to restart DTLS or not, saying:

```
Every time an endpoint requests to establish a new DTLS association, the endpoint MUST generate a new local "tls-id" attribute value. An unchanged local "tls-id" attribute value, in combination with non-changed fingerprints, indicates that the endpoint intends to reuse the existing DTLS association.

The "tls-id" attribute value MUST be generated using a strong random function and include at least 120 bits of randomness.

No default value is defined for the SDP "tls-id" attribute. Implementations that wish to use the attribute MUST explicitly include it in SDP offers and answers. If an offer or answer does not contain a "tls-id" attribute (this could happen if the offerer or answerer represents an existing implementation that has not been updated to support the "tls-id" attribute), a modification of one or more of the following characteristics MUST be treated as an indication that an endpoint wants to establish a new DTLS association, unless there is another mechanism to explicitly indicate that a new DTLS association is to be established:

DTLS setup role; or
fingerprint set; or
local transport parameters
NOTE: A modification of the ufrag value is not treated as an indication that an endpoint wants to establish a new DTLS association. In order to indicate that a new DTLS association is to be established, one or more of the characteristics listed above have to be modified.
```

**Comment by Andronikus** [comment]
This is what happen during all session

```
Invite (offer)
a=fingerprint:SHA-256 FB:54:3F:F0:F5:A0:97:10:23:AD:D3:E4:06:A3:B8:24:9F:B5:A8:54:5E:7A:B9:2A:AC:1F:9D:A0:F0:81:72:AC
a=ice-ufrag:3930ee68
a=ice-pwd:2893d51e126f1e8f21116598
```

```
(183) answer
a=fingerprint:sha-256 0B:F9:1E:3D:EE:D1:D0:3E:B6:10:DC:C0:11:A7:DE:B0:18:93:00:F5:97:EB:8A:F4:54:69:C4:73:0E:D0:86:98
a=ice-ufrag:FTPuNcG4
a=ice-pwd:F8Abb7UtRparOb9mo1xG7JYO25
```


```
Update (offer)
a=fingerprint:SHA-256 FB:54:3F:F0:F5:A0:97:10:23:AD:D3:E4:06:A3:B8:24:9F:B5:A8:54:5E:7A:B9:2A:AC:1F:9D:A0:F0:81:72:AC
a=ice-ufrag:3930ee68
a=ice-pwd:2893d51e126f1e8f21116598
```

```
200OK/UPDATE (answer)
a=fingerprint:sha-256 0B:F9:1E:3D:EE:D1:D0:3E:B6:10:DC:C0:11:A7:DE:B0:18:93:00:F5:97:EB:8A:F4:54:69:C4:73:0E:D0:86:98
a=ice-ufrag:FTPuNcG4
a=ice-pwd:F8Abb7UtRparOb9mo1xG7JYO25
```


+++++ Network change +++++


```
re-Invite (offer)
a=fingerprint:SHA-256 FB:54:3F:F0:F5:A0:97:10:23:AD:D3:E4:06:A3:B8:24:9F:B5:A8:54:5E:7A:B9:2A:AC:1F:9D:A0:F0:81:72:AC
a=ice-ufrag:686bedb1
a=ice-pwd:7ae5cf1f7cf0533d1a34a1c2
```


```
(200) answer
a=fingerprint:sha-256 0B:F9:1E:3D:EE:D1:D0:3E:B6:10:DC:C0:11:A7:DE:B0:18:93:00:F5:97:EB:8A:F4:54:69:C4:73:0E:D0:86:98
a=ice-ufrag:amQLy8b2
a=ice-pwd:YDTENR3gLC58dxdx7UpZ6gZidx
```

```
Update (offer)
a=fingerprint:SHA-256 FB:54:3F:F0:F5:A0:97:10:23:AD:D3:E4:06:A3:B8:24:9F:B5:A8:54:5E:7A:B9:2A:AC:1F:9D:A0:F0:81:72:AC
a=ice-ufrag:686bedb1
a=ice-pwd:7ae5cf1f7cf0533d1a34a1c2
```

```
(200) answer
a=fingerprint:sha-256 0B:F9:1E:3D:EE:D1:D0:3E:B6:10:DC:C0:11:A7:DE:B0:18:93:00:F5:97:EB:8A:F4:54:69:C4:73:0E:D0:86:98
a=ice-ufrag:amQLy8b2
a=ice-pwd:YDTENR3gLC58dxdx7UpZ6gZidx
```

So,

- the `fingerprint` is the same during the session.
- `a=ufrag` changes after the re-Invite (ICE sessions should be different)
- `a=tls-id` is not present

We are not use `a=tls-id` and the `fingerprint` is the same... This could be the reason for the new negotiation not taking place after the network change?

**Comment by rfuchs** [comment]
Yes, I think this is incorrect behaviour of the mobile client, as neither ICE reset alone nor change in `ufrag` automatically implies a reset of the DTLS connection, at least not according to RFC 8842 (and RFC 5763 is ambiguous about it, but also makes it sound like the DTLS connection should remain intact).

Sadly simply initiating a new DTLS connection attempt (even from the client's side) is not enough, as the DTLS packets are simply handed to OpenSSL for processing, and if OpenSSL hasn't been told explicitly that the connection has been reset and needs to be restarted, it will simply consume these packets and not return a response.

**Comment by Andronikus** [comment]
@rfuchs, yes it sounds like that... but not 100% sure 😕

Our client is using `pjsip` and in the case of the handover (as we will change for another network it expected to receive a new set of IPs different the previous ones) it restarts/reset the ICE and the DTLS connection too. Don't know if this behavior is based in some RFC (like the one pointed here).

By the way, we made some changes in our client and when the handover occurs we are making a reset of `tls` too.

The re-Invite that is sent after the handover has a different fingerprint and `rtpengine` already react to this resetting the DTLS as expected.

`[crypto] DTLS fingerprint changed, restarting DTLS`

We are still doing some tests... but we can get audio now on both directions when handover happened.

**Comment by rfuchs** [comment]
Since you're busy testing :) can you try with 099ba38

That implements `a=tls-id` and also does a DTLS restart during an ICE reset if `a=tls-id` is not present.

Or at least it should... Virtually untested.

**Comment by Andronikus** [comment]
@rfuchs We are busy here! Will give feedback here as soon we could test it!

**Comment by creslin287** [comment]
Hey @rfuchs  - does the patch you posted in https://github.com/zhdetig/rtpengine/commit/614aa1a50ab93bd60db574da6c7cbe76f135c2fb need to be updated to see if the (flags->opmode == OP_OFFER)?

In this commit e59c06210808c2c396e963f4ef6434494d169385 you previously only allowed ICE resets when doing offer processing.

**Comment by rfuchs** [comment]
> Hey [@rfuchs](https://github.com/rfuchs) - does the patch you posted in [zhdetig@614aa1a](https://github.com/zhdetig/rtpengine/commit/614aa1a50ab93bd60db574da6c7cbe76f135c2fb) need to be updated to see if (ice_is_restart() && flags->opmode == OP_OFFER)?
> 
> In this commit [e59c062](https://github.com/sipwise/rtpengine/commit/e59c06210808c2c396e963f4ef6434494d169385) you previously only allowed ICE resets when doing offer processing.
> 
> Additionally, the __init_interface() code happens below __dtls_logic(), so if a logical_interface happens to change mid call, __dtls_logic()'s ice_is_restart() wouldn't catch this yet.

Is there a particular scenario you're having problems with? Post details to the mailing list if you want to discuss it. Or if you've found a bug, open a new ticket here.
