### ISSUE TITLE
ICE fails w/ Chrome and peer reflexive candidates

### ISSUE THREAD

**Issue by szcom** [sipwise/rtpengine#160]
in ice.c we find this in path of processing bind request:

```
old_cand = __foundation_lookup(ag, &cand->foundation, ps->component);
if (old_cand && old_cand->priority > priority) {
    /* this is possible if two distinct requests are received from the same NAT IP
     * address, but from different ports. we cannot distinguish such candidates and
     * will drop the one with the lower priority */
```

Here we drop potentially nominated by remote candidate in favor of old candidate and Chrome never say ICE completed as no bind request sent to new learned candidate. It's forgotten. 

Nominated candidate must be preferred regardless of the priority. 

solution : one more flag in args or sky high prio if learned candidate is nominated.

**Comment by szcom** [comment]
though real solution would be to use foundation from bind request and not come up with it  based on source ip address of the bind request. like for ex here:

	cand = __cand_lookup(ag, src, ps->component);

	if (!cand)
		pair = __learned_candidate(ag, ps, src, ifa, attrs->priority);

**Comment by rfuchs** [comment]
What do you mean with use the foundation from the binding request? AFAIK STUN packet don't contain the foundation string.

**Comment by szcom** [comment]
You right it is not there. I can remove my suggestion

**Comment by rfuchs** [comment]
Cleaning up old tickets
