### ISSUE TITLE
Looped call through RTPENGINE not properly handled

### ISSUE THREAD

**Issue by vladpaiu** [sipwise/rtpengine#1600]
Hello,

I have a setup with OpenSIPS and RTPEngine, converting from webrtc traffic to regular RTP.

The flow is WSS Client A -> OpenSIPS -> SIPProxy ->  back to OpenSIPS -> WSS Client B.

The callid stays the same throughout the call, the SIPProxy in the middle is some custom SIP server which does not do any media relay,  so the call gets looped through OpenSIPS with whatever SDP opensips has sent. So RTPEngine does UDP/TLS/RTP/SAVPF to RTP/AVP on the 1st leg and RTP/AVP to UDP/TLS/RTP/SAVPF to RTP/AVP  on the 2nd leg.

The INVITE offer for the 1st leg gets called with "RTP/AVP replace-session-connection replace-origin ICE=remove SDES-off rtcp-mux-demux" and it goes out fine.
The INVITE offer for the 2nd leg gets called with "calling offer with UDP/TLS/RTP/SAVPF ICE=force SDES-off rtcp-mux-offer" and it goes out fine.
The 200OK for the 1st leg gets called with "RTP/AVP replace-session-connection replace-origin ICE=remove SDES-off" and it's processed fine.
The final 200OK getting back is called with "UDP/TLS/RTP/SAVPF ICE=force DTLS=active" but I'm seeing RTPENGINE behaving badly, in the sense that it does not do much other than change RTP/AVP to UDP/TLS/RTP/SAVPF in the SDP ( the 200OK coming back already has the RTPENGINE IP & ports ) - ie. it doesn't add a=fingerprint for the DTLS, not a=setup, a=rtcp-mux, all the standard WEBRTC elements.

Not sure what I am doing wrong here - tried playing around with various options for engaging that final 200OK but with no luck.

**Comment by rfuchs** [comment]
Are the SIP tags (from-tag, to-tag) different for the two legs? If they're the same then this will not work.

**Comment by vladpaiu** [comment]
Hello,

Thanks for the reply.

Sadly, it's the same dialog identifiers ( callid, from-tag, to-tag ).  Any work arounds here ?

**Comment by rfuchs** [comment]
The only workaround is to make sure either the tags are different, or the call ID is different. You can fake them (or append a suffix or something) in your SIP proxy. Otherwise rtpengine won't be able to distinguish who is who. This is entirely expected.

**Comment by vladpaiu** [comment]
the workaround is good enough for me - thanks for the help, marking this as closed.
