### ISSUE TITLE
Problems with --b2b-url and xmlrpc-callback

### ISSUE THREAD

**Issue by Elhodred** [sipwise/rtpengine#1604]
Hi,

We are trying to use the XMLRPC timeout callback to end some calls when there is no media present. RTPENGINE version is 9.5.6.2
As we don't want to teardown all calls, we start rtpengine with pointing to a fake endpoint like this 
`--b2b-url=http://127.100.100.100:8204/`
Then, for the calls we want to end when there is no media, we add in the offer the option xmlrpc-callback with the correct IP address, as shown in the log when dumping the :

> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: [1675415972.973146] DEBUG: [74E3B64F-63DCD1A40004B0CB-41948700-Bleg]: [control] Dump for 'offer' from 127.200.40.101:42886: { "sdp": "v=0
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: o=- 1016 1001 IN IP4 10.100.3.14
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: s=QC VOIP
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: c=IN IP4 10.100.3.14
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: b=AS:41
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: b=RS:600
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: b=RR:2000
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: t=0 0
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: m=audio 10054 RTP/AVP 99 105
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: b=AS:41
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: b=RS:600
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: b=RR:2000
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: a=rtpmap:99 AMR-WB/16000/1
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: a=fmtp:99 mode-change-capability=2;max-red=0
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: a=rtpmap:105 telephone-event/16000
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: a=fmtp:105 0-15
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: a=sendrecv
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: a=curr:qos local sendrecv
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: a=curr:qos remote none
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: a=des:qos mandatory local sendrecv
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: a=des:qos mandatory remote sendrecv
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: a=maxptime:240
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: a=rtcp:10055
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: a=ptime:20
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: a=direction:both
> Feb 03 09:19:32 5gcn-ubuntu-base conmon[151415]: ", "ICE": "remove", "xmlrpc-callback": "127.200.40.101", "direction": [ "ipv4", "ipv4" ], "flags": [ "trust-address", "port-latching" ], "replace": [ "origin", "session-connection" ], "transport-protocol": "RTP/AVP", "call-id": "74E3B64F-63DCD1A40004B0CB-41948700-Bleg", "received-from": [ "IP4", "127.0.60.20" ], "from-tag": "51154807-63DCD1A40004B0C9-41948700", "to-tag": "2241839061", "command": "offer" }
> 

However, when we trigger the test to check the call is terminated, we find this in the log, like the xmlrpc-callback option is completely ignored

> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.013232] INFO: [core] Forking child to close call with tag 51154807-63DCD1A40004B0C9-41948700 via XMLRPC call to http://127.100.100.100:8204/
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.017541] INFO: [core] Initiating XMLRPC call for tag 51154807-63DCD1A40004B0C9-41948700
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.025878] WARNING: [core] XMLRPC fault occurred: libcurl failed to execute the HTTP POST transaction, explaining:  Failed to connect to 127.100.100.100 port 8204 after 0 ms: Connection refused
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.027938] INFO: [core] XMLRPC child exited with status 256
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.038044] INFO: [core] Forking child to close call with tag 51154807-63DCD1A40004B0C9-41948700 via XMLRPC call to http://127.100.100.100:8204/
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.040227] INFO: [core] Initiating XMLRPC call for tag 51154807-63DCD1A40004B0C9-41948700
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.041145] WARNING: [core] XMLRPC fault occurred: libcurl failed to execute the HTTP POST transaction, explaining:  Failed to connect to 127.100.100.100 port 8204 after 0 ms: Connection refused
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.043207] INFO: [core] XMLRPC child exited with status 256
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.053306] INFO: [core] Forking child to close call with tag 51154807-63DCD1A40004B0C9-41948700 via XMLRPC call to http://127.100.100.100:8204/
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.055470] INFO: [core] Initiating XMLRPC call for tag 51154807-63DCD1A40004B0C9-41948700
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.056408] WARNING: [core] XMLRPC fault occurred: libcurl failed to execute the HTTP POST transaction, explaining:  Failed to connect to 127.100.100.100 port 8204 after 0 ms: Connection refused
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.058307] INFO: [core] XMLRPC child exited with status 256
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.068391] INFO: [core] Forking child to close call with tag 51154807-63DCD1A40004B0C9-41948700 via XMLRPC call to http://127.100.100.100:8204/
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.070441] INFO: [core] Initiating XMLRPC call for tag 51154807-63DCD1A40004B0C9-41948700
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.071086] WARNING: [core] XMLRPC fault occurred: libcurl failed to execute the HTTP POST transaction, explaining:  Failed to connect to 127.100.100.100 port 8204 after 0 ms: Connection refused
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.082709] INFO: [core] Forking child to close call with tag 2241839061 via XMLRPC call to http://127.100.100.100:8204/
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.084956] INFO: [core] Initiating XMLRPC call for tag 2241839061
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.085605] WARNING: [core] XMLRPC fault occurred: libcurl failed to execute the HTTP POST transaction, explaining:  Failed to connect to 127.100.100.100 port 8204 after 0 ms: Connection refused
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.087307] INFO: [core] XMLRPC child exited with status 256
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.097408] INFO: [core] Forking child to close call with tag 2241839061 via XMLRPC call to http://127.100.100.100:8204/
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.099622] INFO: [core] Initiating XMLRPC call for tag 2241839061
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.100497] WARNING: [core] XMLRPC fault occurred: libcurl failed to execute the HTTP POST transaction, explaining:  Failed to connect to 127.100.100.100 port 8204 after 0 ms: Connection refused
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.102320] INFO: [core] XMLRPC child exited with status 256
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.112425] INFO: [core] Forking child to close call with tag 2241839061 via XMLRPC call to http://127.100.100.100:8204/
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.114591] INFO: [core] Initiating XMLRPC call for tag 2241839061
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.115188] WARNING: [core] XMLRPC fault occurred: libcurl failed to execute the HTTP POST transaction, explaining:  Failed to connect to 127.100.100.100 port 8204 after 0 ms: Connection refused
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.116774] INFO: [core] XMLRPC child exited with status 256
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.126916] INFO: [core] Forking child to close call with tag 2241839061 via XMLRPC call to http://127.100.100.100:8204/
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.128988] INFO: [core] Initiating XMLRPC call for tag 2241839061
> Feb 03 09:20:49 5gcn-ubuntu-base conmon[151415]: [1675416049.129607] WARNING: [core] XMLRPC fault occurred: libcurl failed to execute the HTTP POST transaction, explaining:  Failed to connect to 127.100.100.100 port 8204 after 0 ms: Connection refused

Are we missing any other options?

**Comment by rfuchs** [comment]
You need to use a wildcard pattern in your config (containing `%%`) that the callback address can be substituted into, so for example `b2b-url = http://%%:8204/`. The `%%` will then be replaced either with the address that the request originated from, or with the address given in `xmlrpc-callback`

Please don't use the Github issue tracker as a support forum. We have a mailing list for that.

**Comment by Elhodred** [comment]
Hi Richard, thanks for your answer. We will try with your suggestion. If anything arises I will send it over the mailing list. I completely forgot about it.
