### ISSUE TITLE
Realtime audio processing

### ISSUE THREAD

**Issue by wojciak** [sipwise/rtpengine#1607]
Hi! 

I'm looking for a way to process RAW audio data coming from one party, before it goes to the other party. 
The goal is to add audio augumentation on the server side (think noise removal)

So basically: [agent audio] -> rtpengine [process_audio] -> [customer audio]

Is this possible?

**Comment by rfuchs** [comment]
No we don't have any audio processing in rtpengine at the moment.

Please use the mailing list for generic questions like this.
