### ISSUE TITLE
DTLS fragmentation not working

### ISSUE THREAD

**Issue by abalashov** [sipwise/rtpengine#1610]
Hi, we have an issue with DTLS-SRTP Server Hellos from RTPEngine being too large for the constraints of our environment, where MTUs are abnormally low due to various tunneling layers. This results in fragmentation at the IP layer. 

Here is a normal hello:

<img width="1277" alt="not-set-to-dtls-fragment png" src="https://user-images.githubusercontent.com/5641703/217947134-ec444bd5-d809-4ba5-80bc-5ad168a5d214.png">

To fix this, I tried to use `--dtls-mtu=768` (and various other values). The expectation was that this would use the DTLS internal fragmentation mechanism, splitting up the payload into several messages without causing IP-layer fragmentation. Unfortunately, it seems this setting has no effect:

<img width="1262" alt="yes-set-to-dtls-fragment png" src="https://user-images.githubusercontent.com/5641703/217947468-59df3e18-a48a-415a-b749-4b8c93356ea3.png">

We have tried various things, like recompiling OpenSSL with the `SSL_OP_NO_QUERY_MTU` macro, which seems to lie close to the heart of this mechanism. From `dtls.c`:

```
#if defined(SSL_OP_NO_QUERY_MTU)
        SSL_CTX_set_options(d->ssl_ctx, SSL_OP_NO_QUERY_MTU);
        SSL_set_mtu(d->ssl, rtpe_config.dtls_mtu);
#if defined(DTLS_set_link_mtu) || defined(DTLS_CTRL_SET_LINK_MTU) || OPENSSL_VERSIO
N_NUMBER >= 0x10100000L
        DTLS_set_link_mtu(d->ssl, rtpe_config.dtls_mtu);
#endif
#endif
```

Sadly, no success. Any pointers on how to get this feature actually working would be deeply appreciated!

**Comment by rfuchs** [comment]
What version of OpenSSL are you using exactly?

**Comment by abalashov** [comment]
1.1.1k.—Sent from mobile, apologies for brevity and errors.On Feb 10, 2023, at 8:21 AM, Richard Fuchs ***@***.***> wrote:﻿
What version of OpenSSL are you using exactly?

**Comment by rfuchs** [comment]
Going by the sample `apps/s_client.c` from `OpenSSL_1_1_1k`, the only difference I can see in the code is that it uses `SSL_set_options(con, SSL_OP_NO_QUERY_MTU);` instead of `SSL_CTX_set_options(...)`

Can you try changing that in your code (or even just adding it) and see if it makes a difference?

`SSL_set_options(d->ssl, SSL_OP_NO_QUERY_MTU);`

(either in addition to `SSL_CTX_set_options` or instead of it)

**Comment by abalashov** [comment]
We never did manage to get this working, but I'm going to close because I don't think there is really an actionable item here.
