### ISSUE TITLE
How to modify /proc/rtpengine, when rtpengine is not running as root?

### ISSUE THREAD

**Issue by dilyanpalauzov** [sipwise/rtpengine#1615]
As far as I tried, runnig rtpengine as non-root fails. /proc/rtpengine/control and /proc/rtpengine/<NUMBER>/conrtol can only be written by the root user or by the root group.  Thus: can rtpengine be run as non-root, and utilize at the same time the in-kernel packet forwarding?

The debian/ngcp-rtpengine-daemon.service file contains:
```
[Service]
User=rtpengine
Group=rtpengine

# Limit set of capabilities
CapabilityBoundingSet=
# NOTE: when running rtpengine under root user (via User=root/Group=root), further capabilities are required:
# * CAP_CHOWN CAP_DAC_OVERRIDE CAP_SETGID CAP_SETUID => for ownership handling in e.g. /run/rtpengine/
# * CAP_FOWNER => for chmod-ing e.g. /run/rtpengine/
# * CAP_NET_ADMIN => for network-related operations
# * CAP_SYS_NICE => for e.g. setpriority usage
#CapabilityBoundingSet=CAP_CHOWN CAP_DAC_OVERRIDE CAP_SETGID CAP_SETUID CAP_FOWNER CAP_NET_ADMIN CAP_SYS_NICE

# Service process does not receive ambient capabilities
# NOTE: we need caps for running as non-root user
AmbientCapabilities=CAP_NET_ADMIN CAP_SYS_NICE
```

Here I am surprized: why are further capabilities necessary, when running under root, which capabilities are not needed when run as non-root?

Please advice how to run rtpengine as non-root, so that it can adjust the /proc/rtpengine/control and/proc/rtpengine/<number>/control files

**Comment by amessina** [comment]
I haven't had any issues with the following rtpengine.service unit running as the rtpengine user and using kernel forwarding:
```
[Unit]
Description=Sipwise NGCP rtpengine RTP proxy daemon
Documentation=man:rtpengine(8) https://github.com/sipwise/rtpengine
After=network-online.target
Before=kamailio.service
Wants=network-online.target

[Service]
Type=notify
User=rtpengine
ExecStart=/usr/sbin/rtpengine -f --config-file=/etc/rtpengine/rtpengine.conf
Restart=on-failure
RestartSec=30
StandardOutput=null

AmbientCapabilities=CAP_NET_ADMIN CAP_SYS_NICE
CapabilityBoundingSet=
LimitMEMLOCK=8388608
LimitNOFILE=150000
LockPersonality=yes
MemoryDenyWriteExecute=yes
NoNewPrivileges=yes
PrivateDevices=yes
PrivateIPC=yes
PrivateTmp=yes
ProcSubset=all
ProtectClock=yes
ProtectControlGroups=yes
ProtectHome=yes
ProtectHostname=yes
ProtectKernelLogs=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
ProtectProc=invisible
ProtectSystem=strict
ReadWritePaths=/var/spool/rtpengine
RemoveIPC=yes
RestrictAddressFamilies=AF_NETLINK AF_UNIX AF_INET AF_INET6
RestrictNamespaces=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
SystemCallArchitectures=native
SystemCallErrorNumber=ENOSYS
SystemCallFilter=@system-service
SystemCallLog=~@system-service seccomp
UMask=0077

[Install]
WantedBy=multi-user.target
```

**Comment by rfuchs** [comment]
You need to specify the UID and GID for the /proc files when loading the kernel module:

```
$ sudo modinfo -p xt_RTPENGINE 
proc_uid:rtpengine procfs tree user id (uint)
proc_gid:rtpengine procfs tree group id (uint)
proc_mask:rtpengine procfs tree mode mask (hexint)
stream_packets_list_limit:maximum number of packets to retain for intercept streams (uint)
log_errors:generate kernel log lines from forwarding errors (bool)
```

When using the bundled systemd unit, this is handled by the included script `rtpengine-iptables-setup`:
https://github.com/sipwise/rtpengine/blob/master/debian/ngcp-rtpengine-iptables-setup#L18
which in turn takes the settings from https://github.com/sipwise/rtpengine/blob/master/debian/ngcp-rtpengine-daemon.default

**Comment by dilyanpalauzov** [comment]
Yes, options `proc_uid= … proc_gid=` seem to do the right things.

The file debian/ngcp-rtpengine-daemon.service contains:
```
# NOTE: when running rtpengine under root user (via User=root/Group=root), further capabilities are required:
# * CAP_CHOWN CAP_DAC_OVERRIDE CAP_SETGID CAP_SETUID => for ownership handling in e.g. /run/rtpengine/
```

why are additional capabilities necessary, when running under root, but not necessary, when running as a different user?

**Comment by dilyanpalauzov** [comment]
> Why are additional capabilities necessary, when running under root, but not necessary, when running as a different user?

I run as root without the capabilities.

**Comment by dilyanpalauzov** [comment]
> $ sudo modinfo -p xt_RTPENGINE 
> log_errors:generate kernel log lines from forwarding errors (bool)

The last line should print the default value for log_errors.

**Comment by dilyanpalauzov** [comment]
> > $ sudo modinfo -p xt_RTPENGINE
> > log_errors:generate kernel log lines from forwarding errors (bool)
> 
> The last line should print the default value for log_errors.

This is not necessary correct.  If the presence of `log_errors` implies DO LOG, and the absence do NOT LOG, then the current form is good.

**Comment by rfuchs** [comment]
> Yes, options `proc_uid= … proc_gid=` seem to do the right things.
> 
> The file debian/ngcp-rtpengine-daemon.service contains:
> 
> ```
> # NOTE: when running rtpengine under root user (via User=root/Group=root), further capabilities are required:
> # * CAP_CHOWN CAP_DAC_OVERRIDE CAP_SETGID CAP_SETUID => for ownership handling in e.g. /run/rtpengine/
> ```
> 
> why are additional capabilities necessary, when running under root, but not necessary, when running as a different user?

They're not additional capabilities. That line exists to keep systemd from removing full root privileges via an empty bounding set (`CapabilityBoundingSet=`). You can also remove the bounding set from the systemd unit completely to run with full root privileges.

**Comment by rfuchs** [comment]
Also please use the Github issue tracker only to report issues with the code, and not as a support forum and to discuss general questions you have. We have a mailing list for that purpose.
