### ISSUE TITLE
Pause media for a subscription

### ISSUE THREAD

**Issue by razvancrainea** [sipwise/rtpengine#1620]
Is there any means one could pause the media for a particular subscription?
A common use case would be a siprec session that for a small period of time, would like to stop recording. Hence, a subscribe request command (probably with some modifiers) would result in an SDP with an `a=inactive` indicator. However, when the recording is resumed, the same SDP as a normal subscribe request is expected. Can this be achieved with the current implementation?

**Comment by rfuchs** [comment]
First off, please don't use the Github issue tracker as a support forum. Use the mailing list instead.

I don't have direct experience with this, but I believe it should work just as you describe. Repeat the subscribe request/answer with `a=inactive` to pause (using the same from/to-tags as before), then repeat again with `a=recvonly`.
