### ISSUE TITLE
rtpengine_delete does not delete session when new offer arrives right after

### ISSUE THREAD

**Issue by juha-h** [sipwise/rtpengine#1625]
We noticed that if one party of call sends BYE and the other party send re-INVITE at about the same time, then it may happen that rtpengine session does not get deleted by rtpengine_delete:
```
Mar 7 19:15:14 proxy /usr/bin/sip-proxy[1966314]: INFO: {1 8818 BYE 19eebeef-82b1-4571-ab12-b0057b9b68d9} ===== rtpengine_delete()
Mar 7 19:15:14 proxy /usr/bin/sip-proxy[1966314]: INFO: {1 8818 BYE 19eebeef-82b1-4571-ab12-b0057b9b68d9} Routing in-dialog BYE 
Mar 7 19:15:14 proxy /usr/bin/sip-proxy[1966312]: INFO: {1 819201 INVITE 19eebeef-82b1-4571-ab12-b0057b9b68d9} ===== rtpengine_offer(ICE=default replace-session-connection replace-origin generate-RTCP trust-address)
Mar 7 19:15:14 proxy /usr/bin/sip-proxy[1966312]: INFO: {1 819201 INVITE 19eebeef-82b1-4571-ab12-b0057b9b68d9} Routing in-dialog INVITE 
```
Since the SIP proxy is not dialog aware, it does not know that the call has already closed when the re-INVITE arrives and thus does not know that it should not send the new rtpengine_offer.

Should repengine notice that the rtpengine_delete has already arrived for the call and ignore the new offer?

**Comment by rfuchs** [comment]
What do you have your delete-delay set to?

**Comment by juha-h** [comment]
Richard Fuchs writes:

> What do you have your delete-delay set to?

It is not set so I think the default is 30 sec.  But the session is not
deleted after 30 seconds in the case when the re-INVITE arrives right
after BYE.

**Comment by juha-h** [comment]
Also such sessions are not deleted after:
```
# how long to wait until idle media session is terminated
timeout = 60
```
although the media session has been idle for so long at least to one direction.

The oldest such non-deleted sessions have been more than a week old and tcp dump has shown that there is no rtp flowing to either direction.

**Comment by rfuchs** [comment]
> Richard Fuchs writes:
> What do you have your delete-delay set to?
> It is not set so I think the default is 30 sec. But the session is not deleted after 30 seconds in the case when the re-INVITE arrives right after BYE.

Yes, that's exactly the point of the delete delay. To not delete the session immediately, so that it can be kept alive in case some other signalling revives it. If you don't need this behaviour then you can just set delete-delay=0. Although in your case, the stray re-invite would then simply create a new session with the same call ID, and you may run into the same problem.

> Also such sessions are not deleted after:
> 
> ```
> # how long to wait until idle media session is terminated
> timeout = 60
> ```
> 
> although the media session has been idle for so long at least to one direction.

The RTP `timeout` option is triggered when there is no RTP at all. If there's RTP in one direction then the timeout doesn't apply, as the UA is supposed to be responsible for terminating the session.

> The oldest such non-deleted sessions have been more than a week old and tcp dump has shown that there is no rtp flowing to either direction.

Those are probably half-established sessions that are waiting for some signalling?

If your SIP proxy cannot reliably manage RTP sessions and you need rtpengine to take care of timing out these broken sessions, you can use `final-timeout` to set a hard upper limit on session lifetime.

**Comment by juha-h** [comment]
Thanks for the reply.  Regarding delete-delay=0 in rtpengine_delete at BYE : when re-INVITE comes rtpengine_offer is called,  but is the new session really established, because no corresponding rtpengine_answer, since there is no 200 OK to the re-INVITE?

**Comment by rfuchs** [comment]
> Thanks for the reply. Regarding delete-delay=0 in rtpengine_delete at BYE : when re-INVITE comes rtpengine_offer is called, but is the new session really established, because no corresponding rtpengine_answer, since there is no 200 OK to the re-INVITE?

Yes, it would still be created in a half-established state, and would eventually time out.

If you need rtpengine's reaction to a stray invite for an already-deleted session to be "this is already deleted so I'm gonna ignore it" then that would require an extra option.

**Comment by juha-h** [comment]
If one party of call has already sent BYE, then I cannot imagine what kind of situation it would be when rtpengine still needs to keep the session alive. So perhaps "this is already deleted so I'm gonna ignore it"  could be the default.

But thanks, we'll try with `delete-delay=0` and/or `final-timeout`.
