### ISSUE TITLE
STUN message integrity in STUN error responses

### ISSUE THREAD

**Issue by Andronikus** [sipwise/rtpengine#1626]
Hello,

We are getting errors on our client of `Unauthorized` when processing the STUN responses that come from `rtpengine`.

From what we already explore, the STUN Bind request uses the ice-pw of `rtpengine` (present on the SDP we receive from `rtpengine`) to compute the message-integrity. 

This request is processed by `rtpengine` and ends with `ICE role conflict detected` (It is expected this behavior in our scenario as the client that not starts the session is sending a re-Invite to change session characteristics)

We check already that in this case, the message-integrity of the STUN response is computed with the client `ice-pw` password and not with the password used to compute the STUN Request message-integrity and for that reason the client cannot authenticate the response that came from `rtpengine`

We already tested the scenario where the `ICE role conflict detected` not happen in `rtpengine` and the response message-integrity is calculated with the password used in the STUN Request as expected.

From what we can see from the code it looks like in case of [error responses](https://github.com/sipwise/rtpengine/blob/master/daemon/stun.c#L420) and [successful responses](https://github.com/sipwise/rtpengine/blob/master/daemon/stun.c#L521) we are using different password.

Can you help us to validate if this is really an issue?

Thanks in advance.

**Comment by rfuchs** [comment]
Yeah I think you're right. At least I can't find anything in the RFC that says error responses use the opposite password from success responses, or anything to that effect. Hard to believe that this has gone unnoticed for so long (code is from 2015...)

**Comment by Andronikus** [comment]
@rfuchs we search in RFCs and as you said there is nothing pointing to this exception.

Btw, we tried in the stun response error [here](https://github.com/sipwise/rtpengine/blob/master/daemon/stun.c#L420) the second position of the array and the stun response is already accepted by the client ;-)

**Comment by Andronikus** [comment]
Hi @rfuchs.

We are using the `9.5.6.2-1~bpo10+1` rtpengine version. It's possible to get this fix in the branch 9.5 too?
