### ISSUE TITLE
rtpengine-recording not working with video call

### ISSUE THREAD

**Issue by kietcaodev** [sipwise/rtpengine#1630]
Hello admin,
I config rtpengine and kamailio work fine with audio call. But i config for video. i have message in rtpengine-recording.
rtpengine-recording[3219]: WARNING: [C 7stqk275pb976ki915o3-0b22b6fd23668b52.meta] [S tag-1-media-2-component-1-RTP-id-4] [0x287462b7] No decoder for payload VP8/90000
rtpengine-recording[3219]: WARNING: [C 7stqk275pb976ki915o3-0b22b6fd23668b52.meta] [S tag-1-media-2-component-1-RTP-id-4] [0x287462b7] Cannot decode RTP payload type 96 (VP8/90000)
--> How to fix problem. Any idea, i appreciate

**Comment by rfuchs** [comment]
We don't have any video processing or recording right now. Contributions welcome.
