### ISSUE TITLE
Do not send media out

### ISSUE THREAD

**Issue by chubenli** [sipwise/rtpengine#1632]
Hi team,
[](url)
I get this errors when when I make every calls (kamailio):

![image](https://user-images.githubusercontent.com/29852186/225606522-a46dec55-175b-41f8-bb9f-2d9a98d3ceb1.png)

RTPEngine does not send out the media it receives, resulting in neither party hearing the sound

the script like this:

    route[SDP_HANDLE_MANAGE] {
   
        $xavp(r=>$T_branch_idx) = "replace-origin replace-session-connection media-handover";

        if (is_request()) {
                if (!has_totag()) {
                        if (!t_is_failure_route()) {
                                $avp(extra_id) = @via[1].branch + $T_branch_idx;
                                $var(isFromFs) = ds_is_from_list();
                                if ($var(isFromFs)) {
                                        xlog("L_INFO", "SDP_HANDLE fix rtpengine fs call out\n ");
                                        $xavp(r=>$T_branch_idx) = $xavp(r=>$T_branch_idx) + " direction=priv direction=pub";   
                                } else {
                                        xlog("L_INFO", "SDP_HANDLE fix rtpengine client call fs\n ");
                                        $xavp(r=>$T_branch_idx) = $xavp(r=>$T_branch_idx) + " direction=pub direction=priv";   
                                }
                        }
                }
        }

        if (is_reply()) {
                $avp(extra_id) = @via[2].branch + $T_branch_idx;
                $var(isFromFs) = ds_is_from_list();
                if ($var(isFromFs)) {    
                        $xavp(r=>$T_branch_idx) = $xavp(r=>$T_branch_idx) + " direction=priv direction=pub";   
                } else {
                        $xavp(r=>$T_branch_idx) = $xavp(r=>$T_branch_idx) + " direction=pub direction=priv";   
                }
        }
        rtpengine_manage($xavp(r=>$T_branch_idx));
        return;
    }

OS: CentOS Linux release 7.9.2009 (Core)
RTPEngine: git-master-cc969049

config file like this: 

[rtpengine]
table = 0
interface = priv/192.168.162.3;pub/94.74.XXX.XXX
listen-ng = 127.0.0.1:2223
listen-http = 127.0.0.1:2225
listen-cli = 127.0.0.1:2224
tos = 184
pidfile = /var/run/rtpengine.pid
num-threads = 16
port-min = 49500
port-max = 50000
log-level = 6
log-facility = local2

where is problem?

Thanks for your help!

**Comment by rfuchs** [comment]
Double posted to mailing list
