### ISSUE TITLE
RTPengine forms identical SDP on different calls

### ISSUE THREAD

**Issue by devoxy1** [sipwise/rtpengine#1634]
Hello!

We use Kamailio with WebRTC clients and rtpengine as rtpproxy. Recently we started to experience intermittent issue when rtpengine generates identical SDP for 2 different calls. 
Two INVITEs coming to Kamailio from different servers, with different callids, branches, TO/FROM headers. Kamailio replies with 200OK on both calls with identical SDP bodies using rtp_manage(). The only thing unites these calls is time - they come to kamailio close in time, about 40 seconds difference( one 11:33:06, the other one is 11:33:45). This causes 2 calls connect and form like a conference.

What could cause such issue?
How rtpengine stores allocated ports, ssrc and other settings? Is there a way i can check them via rtpengine-ctl or other way? Is it stored in memory?

Please let me know if i can provide more information.
Any help would me much appreciated!

**Comment by rfuchs** [comment]
All call state is stored internally and can be inspected with `rtpengine-ctl` and the various `list` subcommands.

Log output would be most helpful.

Let me guess: You're signalling the same rtpengine instance from multiple Kamailio instances and haven't set the server_id in Kamailio?

**Comment by rfuchs** [comment]
> Hello rfuchs!
> 
> Thank you for your reply! Yes, we have 2 redundant kamailio instances and they have several rtpengine instances, so they might use the same rtpengine. server_id is kamailio setting in rtpengine module?

Kamailio core.

http://www.kamailio.org/wiki/cookbooks/devel/core#server_id

**Comment by rfuchs** [comment]
> Yes, we don't use this setting. Could this be the reason?

That would be my guess. Check if both Kamailio instances share some of the same process IDs. You would see info-level log messages from rtpengine "Detected command from ... as a duplicate" if that is what's happening.

**Comment by devoxy1** [comment]
Yes, both kamailio's have some identical process IDs, that's strange! If we add server_id and restart one kamailio and generate different process IDs, might this help?

**Comment by devoxy1** [comment]
Hello rfuchs!

We added server_id and restarted kamailio. Everything looks good, no issues today. Thanks a lot for your help!
