### ISSUE TITLE
recording: ssrc ALWAYS in filename, and %l output-pattern do not work for me

### ISSUE THREAD

**Issue by gmaruzz** [sipwise/rtpengine#1636]
I've tried hard, all versions, all permutations :)

LABEL shows up in metadata
do not shows in wav filename

========

Also, %c (call id) is actually rendered as [callid]-[ssrcexa], even in mixed files

so, %c-%t (or default, if not specified) results in a filename like: [callid]-[ssrcexa]-mix

========

can you give me a config hint on how to have a filename like:

[callid]-mix
or
[label]-[callid]-mix

eg, how to avoid ssrcexa to show up in filename?

**Comment by gmaruzz** [comment]
(also, less important but desired, how to add the label to filename?)

**Comment by rfuchs** [comment]
I think you're confusing the SSRC with a random tag that's appended to the call ID.

**Comment by gmaruzz** [comment]
ah, ok, sorry!
random tag appended to callid is not documented, or at least I have not seen that, so I was assuming it was the ssrc in exadecimal

even if it's not possible to have the callid without the random tag

how I can add the label (that's correctly in the metadata) to the filename? 
using "%l" in output-pattern just add "mix" to the filename, always

**Comment by rfuchs** [comment]
The `%l` label is participant-specific and only applies to non-mixed output files.

**Comment by gmaruzz** [comment]
ah, ok
thank you!!
