### ISSUE TITLE
DTMF packets relayed out of order

### ISSUE THREAD

**Issue by saraxxin** [sipwise/rtpengine#1638]
Hi there.

I am experiencing an issue in mr11.3.0.0 whereby dtmf packets are intermittently delivered out of order.
I am running Debian 11.6 with kernel 5.10.0-9-amd64.

Below is a log of a same call. with a screenshot of the out of order packets.

[rtpengine_log.txt](https://github.com/sipwise/rtpengine/files/11120455/rtpengine_log.txt)

![image](https://user-images.githubusercontent.com/7115732/229084582-af679707-1eb5-44b9-8e28-52221b039199.png)

I have checked iptables and there's only one -j RTPENGINE rule. 
The server is almost under no load whatsoever with a current load average of 0.07 and no wait time.

Any ideas as to what may be causing this would be most welcome.

Edit:

I have tested outside of production on MR11.2 and MR10.4.1.
On 11.2 the fault is present, but on 10.4.1, I cannot reproduce it.

Here is my config. I hope this helps.
[rtpengine]

table = 0

interface = 41.79.80.151
listen-ng = 2223
listen-cli = 9000

timeout = 60
delete-delay = 1
silent-timeout = 3600
tos = 184
port-min = 16384
port-max = 65535

log-level = 0

**Comment by SamuelLayNZ** [comment]
I've encountered this same issue with the DTMF packets being sent all at once and out of order.

![image](https://user-images.githubusercontent.com/36492073/231623680-aba1a463-b86b-418a-b40e-f6ef9c2ace71.png)
This is the incoming call leg, everything looks fine.

![image](https://user-images.githubusercontent.com/36492073/231623963-f34d0c21-9336-460a-a792-5362ef8a7282.png)
This is the outgoing call leg, many packets are not sent in regular 20ms intervals and out of order.

![image](https://user-images.githubusercontent.com/36492073/231624896-9388e968-4d0d-4091-b8fb-f31c427d7671.png)
I should add that the very first outgoing DTMF of each call seems to work fine, but all subsequent DTMF has the same issue.

I tested using the latest of previous versions and had the exact same problem on latest 10.5, 9.5 and 8.5
It wasn't until I built 10.4.2.0+0~mr10.4.2.0 from source (close to what @saraxxin tested with) and used that, that I was no longer able to reproduce the issue.
