### ISSUE TITLE
configurable rtcp sending interval

### ISSUE THREAD

**Issue by andingv** [sipwise/rtpengine#1644]
When generate-RTCP is on, the interval between packets is around 10-14 seconds because this value of the timer inside the source code is effectively doubled:
`timeval_add_usec(&ct->next, 5000000 + (ssl_random() % 2000000));`
Per IMS spec, the interval should not exceed 10 seconds.
I have currently set this in source code to be between 3.5 and 4.99 seconds (when generate-RTCP=on)
If you have a wishlist for future version, please make it configurable.

**Comment by pnlarsson** [comment]
I did change it to:

```
# git diff
diff --git a/daemon/codec.c b/daemon/codec.c
index 67c38846..b0b56a3e 100644
--- a/daemon/codec.c
+++ b/daemon/codec.c
@@ -926,7 +926,7 @@ static void __codec_rtcp_timer_schedule(struct call_media *media) {
                rt->ct.timer_func = __rtcp_timer_run;
        }
 
-       timeval_add_usec(&rt->ct.next, 5000000 + (ssl_random() % 2000000));
+       timeval_add_usec(&rt->ct.next, 1250000 + (ssl_random() % 200000));
        timerthread_obj_schedule_abs(&rt->ct.tt_obj, &rt->ct.next);
 }
 // no lock held
@@ -945,7 +945,7 @@ static void __rtcp_timer_run(struct codec_timer *ct) {
                rwlock_unlock_w(&rt->call->master_lock);
                goto out;
        }
-       timeval_add_usec(&ct->next, 5000000 + (ssl_random() % 2000000));
+       timeval_add_usec(&ct->next, 1250000 + (ssl_random() % 200000));
        __codec_rtcp_timer_schedule(media);

```
And got around 3 seconds between each RTCP

**Comment by andingv** [comment]
Suggested my code change in https://github.com/sipwise/rtpengine/pull/1759
