### ISSUE TITLE
Redis entries not being removed after update

### ISSUE THREAD

**Issue by rrb3942** [sipwise/rtpengine#1645]
We updated from version 11.1.1.2 to 11.2.1.5 and saw a dramatic increase in our memory usage on redis.
Linux Version: 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
Install source: https://dfx.at/rtpengine

![Screenshot_20230411_095445](https://user-images.githubusercontent.com/197956/231234949-acacd605-1267-4dcd-9f7e-d687085679d3.png)

It looks like entries are not being removed and just accumulate.

I did a quick capture and do see that DEL commands are being issued when a call is ended, but I then see another SET command soon follows for some reason, which is then never cleared.

Sessions reported by rtpengine are being setup and torn down as expected, so I don't believe its an issue with setup/tear-down with rtpengine itself, just something with the commands being sent to the redis back-end.

**Comment by pkuzak** [comment]
Issue probably related to #1646

**Comment by rfuchs** [comment]
closed by #1646
