### ISSUE TITLE
webrtc client offering ICE complaining of missing ice-ufrag and ice-pwd on re-invite

### ISSUE THREAD

**Issue by davehorton** [sipwise/rtpengine#1647]
I am not sure if this is an issue with the webrtc client, or with the commands I am sending to rtpengine, but here is the scenario:

We get an incoming call from a webrtc client advertising ICE support, we create a session on rtpengine with SRTP on the incoming side and RTP on the outgoing side.  All is good.  

Immediately after the call is connected, we are receiving a reinvite on the RTP side, calling 'offer' on rtpengine and then sending a re-invite to the webrtc client.  The webrtc client rejects our re-invite with a 488 Not Acceptable here and logs an error:

```
04:37:07.927 _processInDialogSdpOffer() failed [error: DOMException: 
Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': 
Failed to set remote offer sdp: Called with SDP without ice-ufrag and ice-pwd.]
```
That much is true - the initial SDPs exchanged in the INVITE/200 with the webrtc client *did* have ice-ufrag and ice-pwd, our re-invite that we send does not.

The full rtpengine log [is here](https://gist.github.com/davehorton/06df13b2caa2f3ade259c68a091ded97).

The sip signaling log [is here](https://gist.github.com/davehorton/bb7177ba3c640a315ee08059786e79ab).

The webrtc client is an audiocodes product.

Does this seem like an error on the webrtc client side, or should there in fact be  ice-ufrag and ice-pwd on the re-invite we send, and if so, what options should I be using in my 'offer' in the reinvite transaction to make it so.  

Thanks in advance for any help you can provide.

**Comment by rfuchs** [comment]
Possibly related to the usage of `reset` in the re-invite flags, although that should still work. Is that intentional?

**Comment by davehorton** [comment]
I can't recall exactly why I put `reset` in there....but I removed it and the problem did indeed go away.  Thanks
