### ISSUE TITLE
compilation fails with with_transcoding=no (mix_buffer.c:2:33: fatal error: libavutil/samplefmt.h: No such file or directory)

### ISSUE THREAD

**Issue by aldennisa15** [sipwise/rtpengine#1648]
with `make with_transcoding=no`, compilation fails with...
`mix_buffer.c:2:33: fatal error: libavutil/samplefmt.h: No such file or directory`

**Comment by aldennisa15** [comment]
Wrapping things (`#include <libavutil/samplefmt.h>`, `mix_buffer_ssrc_new()` and `mix_buffer_init_active()`) in `#ifdef WITH_TRANSCODING` .. `#endif` seems to make the compilation work, but no idea if that's the correct fix or not?

**Comment by themsley-voiceflex** [comment]
It seems that ffmpeg has now been made a hard requirement - maybe by mistake? I would very much prefer not to have to install anything ffmpeg in order to run rtpengine.

**Comment by themsley-voiceflex** [comment]
So it builds with the following patch as per comment #1

[rtpengine-no-ffmpeg.patch.txt](https://github.com/sipwise/rtpengine/files/11251686/rtpengine-no-ffmpeg.patch.txt)

Completely untested so might crash on startup!

**Comment by themsley-voiceflex** [comment]
Installed and it has managed the grand total of 2 calls so far but it appears to work and has audio in both directions.
