### ISSUE TITLE
Build fails using el/rtpengine.spec

### ISSUE THREAD

**Issue by themsley-voiceflex** [sipwise/rtpengine#1650]
There is a sample RPM spec file to allow it to be packaged on RPM based distros. It fails in 11.4 because the dkms config file template has changed names/locations. It now needs to say

-install -D -p -m644 debian/dkms.conf.in %{buildroot}%{_usrsrc}/%{name}-%{version}-%{release}/dkms.conf
-sed -i -e "s/__VERSION__/%{version}-%{release}/g" %{buildroot}%{_usrsrc}/%{name}-%{version}-%{release}/dkms.conf
+install -D -p -m644 debian/ngcp-rtpengine-kernel-dkms.dkms %{buildroot}%{_usrsrc}/%{name}-%{version}-%{release}/dkms.conf
+sed -i -e "s/#MODULE_VERSION#/%{version}-%{release}/g" %{buildroot}%{_usrsrc}/%{name}-%{version}-%{release}/dkms.conf

**Comment by mika** [comment]
@rfuchs @themsley-voiceflex sure, no problem - how about https://github.com/sipwise/rtpengine/pull/1657?
