### ISSUE TITLE
Media Latching Issues on Callee Side

### ISSUE THREAD

**Issue by emvondo** [sipwise/rtpengine#1655]
I'm using this setup with kamailio and RTPENGINE and im facing issues for  media latching on callee side.

is there something wrong with flags involved ? 

thanks
![callee-media-latching drawio](https://user-images.githubusercontent.com/106535097/234112235-160e0f64-8d7c-43d9-8a09-9fd92d7541fe.png)

**Comment by rfuchs** [comment]
Not sure what your expectation is, but maybe this is was 900d2beb had addressed?

**Comment by emvondo** [comment]
> Not sure what your expectation is, but maybe this is was [900d2be](https://github.com/sipwise/rtpengine/commit/900d2bebee0dfee99c3a10f0391f667b2c93cd01) has addressed?

Well that patch fixes strict source ip for asymmetric RTP and its done once (**learned_endpoint**  for that stream **is set once and forever** for asymmetric).

stream2 from callee side (**ssrc=5555 & src_ip=z.z.y.t**) comes from different ip that stream1 (**ssrc=7777 & src_ip=z.z.y.y**) and stream2 is perfectly blocked before Flow '#'4.


but after Flow '#'4 not only stream2 is now the relayed one to caller side but also rtp from caller is now relayed to **z.z.y.t** whereas there is no ip address and port did not change in sdp answer.


Also want to ask

```
static int stream_packet(struct packet_handler_ctx *phc) {


           // for asymmetric and imediate endpoint-learning with strict-source
          // we potentially add ssrc from non authorized source
           media_packet_rtp_in(phc);      <-- should not be this done after some address checking ??             

           media_packet_address_check(phc);  

}
```

**Comment by emvondo** [comment]
> Oh I see. Possibly because endpoint learning is re-enabled after a signalling event such as an answer, and if a packet from stream 2 is received first, then that stream will be seen as the "correct" one?

yes looks like endpoint learning is re-enabled or stream->learned_endpoint is reset somewhere. i will check further

**Comment by emvondo** [comment]
> Oh I see. Possibly because endpoint learning is re-enabled after a signalling event such as an answer, and if a packet from stream 2 is received first, then that stream will be seen as the "correct" one?
> 
> And yes, you're probably right that address checking should be done first, assuming there are no inter-dependencies between the two functions.


i made a small update in my local copy of rtpengine and i confirm that media_packet_address_check done before all ssrc operations solve this issue.

now i did not have too much time to look how much impact is added. 
i can see that all other ssrc stats (packets,octets,seq_num,last_seq,bytes,last_packet) will not be handled (recorded,incremented ....) but for me it should be this way. 

```
static int stream_packet(struct packet_handler_ctx *phc) {
	int ret = 0, handler_ret = 0;
	GQueue free_list = G_QUEUE_INIT;

	phc->mp.call = phc->mp.sfd->call;

	rwlock_lock_r(&phc->mp.call->master_lock);

	phc->mp.stream = phc->mp.sfd->stream;
	if (G_UNLIKELY(!phc->mp.stream))
		goto out;
	__C_DBG("Handling packet on: %s", endpoint_print_buf(&phc->mp.stream->endpoint));


	phc->mp.media = phc->mp.stream->media;

	///////////////// INGRESS HANDLING

	if (!phc->mp.stream->selected_sfd)
		goto out;

	phc->mp.call->foreign_media = 0;

	if (phc->mp.call->drop_traffic) {
		goto drop;
	}

	int stun_ret = media_demux_protocols(phc);
	if (stun_ret == 0) // packet processed
		goto out;
	if (stun_ret == 1) {
		media_packet_kernel_check(phc);
		goto drop;
	}


#if RTP_LOOP_PROTECT
	if (MEDIA_ISSET(phc->mp.media, LOOP_CHECK)) {
		if (media_loop_detect(phc))
			goto out;
	}
#endif

	if (rtpe_config.active_switchover && IS_FOREIGN_CALL(phc->mp.call))
		call_make_own_foreign(phc->mp.call, false);

	int ip_check = media_packet_address_check(phc); // <------- address_check before ssrc stuffs
	if (ip_check)
		goto drop;

	// this sets rtcp, in_srtp, and sinks
	media_packet_rtcp_demux(phc);

	// this set payload_type, ssrc_in, and mp payloads
	media_packet_rtp_in(phc);
```
