### ISSUE TITLE
rtpengine-recording notify-uri doesn't send a notification

### ISSUE THREAD

**Issue by miklinson** [sipwise/rtpengine#1662]
There are no issues with the recorded file. But we couldn't receive a HTTP notification for finished recordings.

**rtpengine-recording.conf**
```
##HTTP notification for finished recordings
notify-uri = http://localhost:3001
notify-post = false
notify-no-verify = true
notify-concurrency = 5
notify-retries = 5
```
When doing `curl http://localhost:3001` we can confirm that it's accessible

**Comment by rfuchs** [comment]
Which version? Steps to reproduce?

**Comment by miklinson** [comment]
Thank you for your prompt reply, apologies for the late revert @rfuchs We're using version `mr11.2.1.6` 
To reproduce we're using the RTPengine as media for the Drachtio based app. When the call comes in, we just call the start recording command. We didn't have any issues in the `.wav` file produced and the quality of the call, just the notify part, so we know for a fact that the recording is working.

I'll try to post the logs later. Thanks!

**Comment by rfuchs** [comment]
Well that answers the question. The HTTP notification feature isn't included in mr11.2. Try mr11.3 or later.
