### ISSUE TITLE
Unable to set output-destination on start_recording

### ISSUE THREAD

**Issue by joeygo** [sipwise/rtpengine#1667]
Hello,

I have a call running between 2 clients on a Kamailio server.
The rtpengine_manage command is called without record-call=on flag because I want to start the recording manually at a later stage of the call.
During the call, I'm calling the start_recording function with the output-destination flag but rtpengine ignores the flag and records the file using its regular file output pattern.

I have checked the code and I think I found the reason. on the recording.c file there is a function: update_output_dest
The first condition in that function is: if (!output_dest || !output_dest->s || !call->recording)
The call->recording is null in that case.

If I'm repeating everything but sending record-call=on flag during call setup everything works fine and I can set the output-destination as desired.

How can I achieve the desired behavior and set the output-destination when starting the recording manually?

Thanks,
Joey.

**Comment by joeygo** [comment]
I forgot to mention, I'm using version 11.3.1.7 but it reproduces on the master as well.

**Comment by joeygo** [comment]
Anyone?

**Comment by joeygo** [comment]
I check against the master version and it is still reproducible.

These are the logs of start-recording command:

Jun 11 13:39:26 kamailio01 rtpengine[24638]: DEBUG: [B45195B7-AC57-487D-B083-E8A347A09DAB]: [control] Dump for 'start recording' from 172.19.140.70:41857: { "supports": [ "load limit" ], "output-destination": "joey-B45195B7-AC57-487D-B083-E8A347A09DAB-1686490766.mp3", "call-id": "B45195B7-AC57-487D-B083-E8A347A09DAB", "received-from": [ "IP4", "172.19.140.73" ], "from-tag": "p9eHSjvypZNXj", "to-tag": "CEA5D7A8-D07A-4C11-9B74-0319BDEB28AE", "command": "start recording" }
Jun 11 13:39:26 kamailio01 rtpengine[24638]: NOTICE: [B45195B7-AC57-487D-B083-E8A347A09DAB]: [core] Turning on call recording.
Jun 11 13:39:26 kamailio01 rtpengine[24638]: DEBUG: [B45195B7-AC57-487D-B083-E8A347A09DAB]: [core] kernel call idx is 0
Jun 11 13:39:26 kamailio01 rtpengine[24638]: DEBUG: [B45195B7-AC57-487D-B083-E8A347A09DAB]: [core] kernel stream idx is 0
Jun 11 13:39:26 kamailio01 rtpengine[24638]: INFO: [B45195B7-AC57-487D-B083-E8A347A09DAB]: [core] Removing media stream from kernel: local 172.19.140.70:39390 (recording start)
Jun 11 13:39:26 kamailio01 rtpengine[24638]: DEBUG: [B45195B7-AC57-487D-B083-E8A347A09DAB]: [core] kernel stream idx is 1
Jun 11 13:39:26 kamailio01 rtpengine[24638]: DEBUG: [B45195B7-AC57-487D-B083-E8A347A09DAB]: [core] kernel stream idx is 2
Jun 11 13:39:26 kamailio01 rtpengine[24638]: INFO: [B45195B7-AC57-487D-B083-E8A347A09DAB]: [core] Removing media stream from kernel: local 172.19.140.70:40918 (recording start)
Jun 11 13:39:26 kamailio01 rtpengine[24638]: DEBUG: [B45195B7-AC57-487D-B083-E8A347A09DAB]: [core] kernel stream idx is 3
Jun 11 13:39:26 kamailio01 rtpengine[24638]: INFO: [B45195B7-AC57-487D-B083-E8A347A09DAB]: [control] Replying to 'start recording' from 172.19.140.70:41857 (elapsed time 0.001600 sec)
Jun 11 13:39:26 kamailio01 rtpengine[24638]: DEBUG: [B45195B7-AC57-487D-B083-E8A347A09DAB]: [control] Response dump for 'start recording' to 172.19.140.70:41857: { "result": "ok" }


This is the log line showing that rtpengine ignores the output-destination flag provided during start-recording command and uses its regular output pattern instead:

Jun 11 13:39:26 kamailio01 rtpengine-recording[24438]: INFO: [C B45195B7-AC57-487D-B083-E8A347A09DAB-5fe25ac10208b15c.meta] [S tag-0-media-1-component-1-RTP-id-2] [0x51fbd651] [core] Opened output media file '/mnt/nfs/storage/recordings/joey/B45195B7-AC57-487D-B083-E8A347A09DAB-5fe25ac10208b15c-mix.mp3' for writing

In addition, I have tried to include a subdirectory in the start-recording command ("output-destination": "subdir/joey-B45195B7-AC57-487D-B083-E8A347A09DAB-1686490766.mp3") but same result.

**Comment by joeygo** [comment]
The last commit fixed the problem.
Thanks!

**Comment by joeygo** [comment]
It worked. Thanks.

One last question, I see lots of the following log error:
Jun 14 17:07:45 kamailio01 rtpengine-recording[17505]: WARNING: [C 8BFA4D94-7441-48AF-81B6-94E2878CFB2F-1323b5438f5d1958.meta] [S tag-0-media-1-component-1-RTP-id-2] [0x79655c23] [core] Cannot decode RTP payload type 121 (telephone-event/48000)
Jun 14 17:07:45 kamailio01 rtpengine-recording[17505]: WARNING: [C 8BFA4D94-7441-48AF-81B6-94E2878CFB2F-1323b5438f5d1958.meta] [S tag-0-media-1-component-1-RTP-id-2] [0x79655c23] [core] Cannot decode RTP payload type 121 (telephone-event/48000)
Jun 14 17:07:45 kamailio01 rtpengine-recording[17505]: ERR: [C 8BFA4D94-7441-48AF-81B6-94E2878CFB2F-1323b5438f5d1958.meta] [S tag-1-media-1-component-1-RTP-id-0] [0x8577861] [core] Failed to add frame to mixer: received samples for old re-used input channel
Jun 14 17:07:45 kamailio01 rtpengine-recording[17505]: ERR: [C 8BFA4D94-7441-48AF-81B6-94E2878CFB2F-1323b5438f5d1958.meta] [S tag-1-media-1-component-1-RTP-id-0] [0x8577861] [core] Failed to add decoded packet to mixed output
Jun 14 17:07:45 kamailio01 rtpengine-recording[17505]: ERR: [C 8BFA4D94-7441-48AF-81B6-94E2878CFB2F-1323b5438f5d1958.meta] [S tag-1-media-1-component-1-RTP-id-0] [0x8577861] [core] Failed to add frame to mixer: received samples for old re-used input channel
Jun 14 17:07:45 kamailio01 rtpengine-recording[17505]: ERR: [C 8BFA4D94-7441-48AF-81B6-94E2878CFB2F-1323b5438f5d1958.meta] [S tag-1-media-1-component-1-RTP-id-0] [0x8577861] [core] Failed to add decoded packet to mixed output
Jun 14 17:07:45 kamailio01 rtpengine-recording[17505]: ERR: [C 8BFA4D94-7441-48AF-81B6-94E2878CFB2F-1323b5438f5d1958.meta] [S tag-1-media-1-component-1-RTP-id-0] [0x8577861] [core] Failed to add frame to mixer: received samples for old re-used input channel

Can you guess what might be the cause?

**Comment by rfuchs** [comment]
Probably too many contributing SSRCs. Check the `mix-num-inputs` option.

BTW we have a mailing list for general questions.
