### ISSUE TITLE
No audio RTP stream being send from rtpengine after the SIP Re-Invite

### ISSUE THREAD

**Issue by adil-mafzool** [sipwise/rtpengine#1669]
I have an issue with particular scenario where rtpengine is not sending audio stream after SIP re-INVITE is initiated where as opposite side is sending rtp. RTCP is being sent to/from by rtpengine but RTP is only in one direction: -

SIP signalling and RTP streams info: -

```
(third party)10.211.72.1 --------------------> (kamailio/rtpengine)10.211.95.7 ----------------> (webrtc gateway/janus) 10.219.36.155
10.211.95.2                                       10.211.95.8                                     10.219.36.155
 (OFFER) audio 24046 RTP/AVP                 (ANSWER) audio 30018 / (OFFER) audio 30000          (ANSWER)  audio 35954
 RTP/AVP 111 9 8 126 110 18                      RTP/AVP 111 9 8 126 110                         RTP/AVP 111 9 8 126 110
RTP            <===================================>              ===================================>
                                                              (Incoming stream is received with delay from 10.219.36.155 until after re-invite)

Re-INVITE
(third party)10.211.72.1 ---------------------> (kamailio/rtpengine)10.211.95.7 -----------------> (webrtc gateway/janus) 10.219.36.155
10.210.72.111                                   10.211.95.8                                     10.219.36.155
 (OFFER) audio 13812 RTP/AVP                 (ANSWER) audio 30018 / (OFFER) audio 30000          (ANSWER)  audio 35954
  RTP/AVP 8  18 9 101                               RTP/AVP 8 9 111 101 96                        RTP/AVP 8 9 111 101 96

RTP            ====================================>            <=================================>
                    Audio stream is not sent to 10.210.72.111 by rtpengine

RTCP(No Issues)   <============================>              <==================================>
```
wireshark image: -
![image](https://github.com/sipwise/rtpengine/assets/36664780/094015c8-478e-4c08-b9b7-509d7d085834)

rtpengine version: 9.5.7.1 custom running on the redhat
`Linux xxx-xxxx-xxx-xxx-02.xxxxxxxxxx3.xxxxx 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
`
Attached rtpengine log with loglevel 7
[rtpengine-1.log](https://github.com/sipwise/rtpengine/files/11573959/rtpengine-1.log)

Please can someone pointers me where can be the issue :)

**Comment by adil-mafzool** [comment]
@rfuchs Thanks for your response! 
Couple of questions: -
>>And so rtpengine assumes the address from the SDP is wrong, learns the correct address from the received media, and >>starts sending reverse media there as well.
Do we have timing of the learning correct address process? How is it possible to increase or decrease the time of the learning correct address?
And secondly,  will using option like media handover or strict source.. will it make any difference in this situation?

Finally, tell me which mailing list should I use for rtpengine support questions?

**Comment by rfuchs** [comment]
> Do we have timing of the learning correct address process? How is it possible to increase or decrease the time of the learning correct address?

The duration of the learning phase is hard-coded as around 2 seconds.

> And secondly, will using option like media handover or strict source.. will it make any difference in this situation?

`media handover` would work if the media is first arriving from the wrong source and then switches over to the correct one.

Another option is to disable endpoint learning altogether and just go with the address advertised in the SDP. Not sure if that would work in your use case.

> Finally, tell me which mailing list should I use for rtpengine support questions?

https://rtpengine.com/mailing-list
