### ISSUE TITLE
When I install, I get an error，libswresample/swresample.h: No such file or directory

### ISSUE THREAD

**Issue by damded** [sipwise/rtpengine#1670]
# make
Package 'libswresample' requires 'libavutil >= 55.78.100' but version of libavutil is 55.20.0
make rtpengine rtpengine.8
Package 'libswresample' requires 'libavutil >= 55.78.100' but version of libavutil is 55.20.0
Package 'libswresample' requires 'libavutil >= 55.78.100' but version of libavutil is 55.20.0
make[1]: Entering directory `/usr/local/share/rtpengine/daemon'
cc -g -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wstrict-prototypes -Werror=return-type -Wshadow -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread     -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/local/include   -I/usr/local/include   -I/usr/local/include    -I/usr/local/include   -I/usr/local/include   -I/usr/local/include/opus   -DWITH_TRANSCODING -I/usr/include/mysql -DRTPENGINE_VERSION="\"git-master-22b4d92\""   -c -o main.o main.c
In file included from ../include/call.h:29:0,
                 from ../include/udp_listener.h:9,
                 from ../include/control_udp.h:15,
                 from main.c:26:
../lib/codeclib.h:51:38: fatal error: libswresample/swresample.h: No such file or directory
 #include <libswresample/swresample.h>

This is my system information
# uname -a
Linux p-l27 4.9.0 #1 SMP Tue May 10 16:25:10 CST 2022 x86_64 x86_64 x86_64 GNU/Linux
# cat -ns /etc/redhat-release
     1	CentOS Linux release 7.4.1708 (Core) 
# cat -ns /proc/version
     1	Linux version 4.9.0 (root@localhost.localdomain) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Tue May 10 16:25:10 CST 2022

**Comment by rfuchs** [comment]
Probably an old version of the ffmpeg devel packages? Your build log even says so:

Package 'libswresample' requires 'libavutil >= 55.78.100' but version of libavutil is 55.20.0

Find newer packages for your OS.

Closing as this is not an issue with the code.
