### ISSUE TITLE
Does rtpengine only support 400-channel 1080p video playback?

### ISSUE THREAD

**Issue by miszuoer** [sipwise/rtpengine#1672]
Does rtpengine only support 400-channel 1080p video playback? Or do I have any performance optimization method？

**Comment by rfuchs** [comment]
We don't support any kind of video playback. We support RTP passthrough of any media type though.

We have a mailing list for general questions, therefore closing this.

**Comment by miszuoer** [comment]
I'm sorry that I didn't make my question clear. I use rtpengine for the video playback of the surveillance camera. I used opensips and rtpengine, but I found that it only supports 400 channels of 1080p video traffic at most. Is this the limit performance of rtpengine?
