### ISSUE TITLE
Problem with mapping recorded stream into stereo file channel

### ISSUE THREAD

**Issue by liv1657** [sipwise/rtpengine#1673]
Hello,
I have a problem with rtpengine-recording when I'm trying to record two streams into the stereo file. I'm using configuration option:
output-mixed = true
mix-method = channels

rtpengine-recording is creating stereo file however, I can't predict the channel where each stream got recorded.

Could you advice how to control stream placement into Left or Right channel?
Thank you!

**Comment by rfuchs** [comment]
There's no such feature currently. The first source to appear gets assigned the first channel.

Not an issue with the code, therefore closing. Use the mailing list for questions and support.
