### ISSUE TITLE
is keyDB supported from rtpengine?

### ISSUE THREAD

**Issue by henningw** [sipwise/rtpengine#1674]
Hello,

I have seen in #1079 that keydb is not supported from rtpengine. This issue was discussed almost three years ago.
I also found in a changelog for a release this topic [link](https://www.sipwise.com/wp-content/uploads/2022/02/Changelog_for_mr10.3.1_2022-02-22T12_27_28.pdf)

> Check KeyDB as a Redis replacement to provide master-master replication
> 153700, Change Request for mr10.3.1

Is still KeyDB not supported from rtpengine? This is not a feature request or similar. Its only about not using something unsupported in a possible new setup.

Thank you very much for the feedback.

**Comment by rfuchs** [comment]
We're using KeyDB ourselves these days, so there's no reason why it shouldn't work.

We have a mailing list for general questions like this BTW.
