### ISSUE TITLE
XML-RPC response not well-formed

### ISSUE THREAD

**Issue by phildeb** [sipwise/rtpengine#1691]
Hello,
Using Kamailio, I succesfully receive from Rtpengine the XML-RPC teardown packet (using --b2b-url with %%):
```
<methodCall>
<methodName>teardown</methodName>
<params>
<param><value><string>VmJbReHeOl</string></value></param>
</params>
</methodCall>
```

could anyone tell me where to find the xml formatting of the XML-RPC response to send to Rtpengine ?

What I tried in Kamailio:
`_xhttp_reply("200", "OK", "application/xml","<?xml version='1.0' encoding='UTF-8'?><methodResponse><methodName>teardown</methodName><params><param><value><string>OK</string></value></param></params></methodResponse></xml>");`

But Rtpengine is complaining :(
`_WARNING: [core] XMLRPC fault occurred: Unable to make sense of XML-RPC response from server.  Not valid XML.  Invalid XML "content".  Problem with token at '</methodResponse></xml>...': not well-formed`

**Comment by phildeb** [comment]
Eventually found the simple solution using kamailio xmlrpc.so :
`xmlrpc_reply("200", "");`
instead of 
`xhttp_reply("200", "OK", "application/xml",...`

**Comment by rfuchs** [comment]
Please don't use the Github issue tracker as a support forum. Use the mailing list instead.
