### ISSUE TITLE
support for both rtp and srtp with ca certificate

### ISSUE THREAD

**Issue by sumit-kumar-iitm** [sipwise/rtpengine#1696]
I want to configure my ca certificate with rtpengine and need to handle rtp as well srtp on the same instance. Do I need to put a reverse proxy in front of rtpengine or how can I achieve that? I am using rtpengine in siprec setup, where rtpengine is receiving rtp packets directly from SBC which is not our control.

**Comment by rfuchs** [comment]
Please don't use the Github issue tracker as a support forum. Use the mailing list: https://rtpengine.com/mailing-list

You should probably start by explaining why you need a CA for SRTP?
