### ISSUE TITLE
transcoded AMR switching OA->BE mode on reINVITE?

### ISSUE THREAD

**Issue by whyteks** [sipwise/rtpengine#1697]
Hi @rfuchs 
Maybe something might jump to your mind quickly about this, in the mean time, I'm investigating, if I can't figure it out, I'll add more logs/trace etc if I find anything helpful. Thanks!

An upstream provider is sometimes (for reasons I cannot ascertain) now sending a re-INVITE immediately after we reply with 200 to the original INVITE.
I handle that (in kamailio) and normally everything has been fine with re-INVITES. (we send the same transcoding directives etc)
They offer PMCA (first-choice) and we transcode to AMR.

Anyway,  without getting into programming some sip test, my poor man's reproduction of the issue is to call into my system as the provider would, and then pretty quickly after getting 200, I hold and un-hold the call. This of course, sends reINVITES, (albeit slightly different to upstream due to sendrecv params in SDP), but this seems be reproducing the issue.

What seems to be happening from my analysis of rtpengine debug log is that on getting this subsequent offer, we identify the dialogue, and then we actually tear down the transcoding and recreate it (and we're changing the RTP dynamic PT), redacted excerpt:

```
 [internals] found existing dialogue
 [internals] this=4Uc6Sapap68aS other=c2ce15ebeee8d4ao0
 [internals] processing media stream #1
 [internals] found existing call_media for stream #1
 [codec] Eliminating asymmetric inbound codec AMR/8000
 [codec] Codec 'AMR/8000' added for transcoding with payload type 97
 [codec] Default sink codec is PCMU/8000
 [codec] Output DTMF payload type is 101
 [codec] Accepting offered codec AMR/8000 due to transcoding
 [internals] checking recv codec AMR
 [codec] Resetting codec handler for PT 96
 [internals] receive packet ret -11
 [codec] Creating codec handler for AMR/8000

```

What is happening as far as I can make out it is that after the reINVITE, (or after unhold in the case of my test), rtpengine is sending non octet-aligned AMR to the other end. My trace of RTP shows in wireshark vaild TOC and all, but actually this is being fed to osmocom's Media Gateway which is complaining about getting non OE AMR.

What's odd is that if I hold/unhold again, the stream is then correct octet-aligned AMR and I can keep on doing reINVITES and it's fine, it just the first reINVITE, or maybe a reINVITE that is happening quickly after initial setup. 
I tried overriding the 
`if (enc->codec_options.amr.octet_aligned)`
in codeclib.c:packetizer_amr() but that makes no difference.

It is mr9.5.7.1 but a quick git grep for octet-align and such does not turn up anything obviously related since then. I thought I'd go ahead and write this up here as I need to setup some test infra and try out current master and a few other things, (like disabling codec renegotiation) but maybe in the meantime something might occur to you, and you're often quite fast to spot the bug fixes.

As an aside, i am wondering if it's necessary to tear down and recreate (if i'm correct that is actually what's happening) the transcoding on reINVITE provoked offer, maybe one could check to see if anything's actually changed in the SDP first, or maybe that'd be a big code change.

**Comment by rfuchs** [comment]
Can you post the SDPs involved? And the signalling (flags to rtpengine) would be of interest too.

**Comment by rfuchs** [comment]
> Actually, I just noticed that in the SDP from FreeSwitch, in response to the 1st re-INVITE, (but only the first) for some reason it is totally missing the a=fmtp line, (no octet-align=1 directive) although it appears to still be sendng OA AMR. So maybe rtpengine is just fine here, it's indeed doing what it's told, but something looks wrong, the way rtpengine is offering in the reINVITE, both PT 96 and 97?

That's somewhat expected because two different `a=fmtp` strings make it think that these are two different/mismatched codecs. In mr9.5 we didn't have proper offer/answer format matching for AMR. Newer versions of rtpengine are able to determine which AMR formats are compatible and which are not.

In mr9.5 we also didn't have `reuse-codecs`.
