### ISSUE TITLE
rtpengine with docker?

### ISSUE THREAD

**Issue by javitorl** [sipwise/rtpengine#170]
I wonder if anybody has  been playing around with rtpengine and docker or even if it makes sense considering performance, any experience?

**Comment by Binan** [comment]
The xt_RTPENGINE kernel module needs to be compiled against the source of the host kernel so it can works with it. 
Also You need to be able to load the xt_RTPENGINE kernel module in the host kernel. You need to have privileges to do that (privileged container). 
In case you are not using the rtpengine kernel module (xt_RTPENGINE) and only the normal userspace operations, you will not get the better performance, the in-kernel forwarding gives (low latency and CPU usage).
