### ISSUE TITLE
Document which kernel options must be enabled, e.g. as modules, for xt_RTPENGINE to function.

### ISSUE THREAD

**Issue by dilyanpalauzov** [sipwise/rtpengine#1706]
I run a Linux from Scratch system.  In the past rtpengine was able to utilize the in-kernel forwarding.  Now it does not work.

It either prints 

> ERR: [krg7cjellodq80k39lu8/as30961924/1 port 34395]: [core] Failed to send RTCP via kernel interface: Function not implemented

So write() in daemon/kernel.c:kernel_send_rtcp either sets errno to  38, or it prints

> WARNING: [core] Run time of timer "kill calls": 3.424099 sec, exceeding limit of 20% (0.200000 sec)
> ERR: [d8ta656qntngp9rqja7i/as399209d1/1 port 36769]: [core] sending descriptor 5 len 160
>  WARNING: [core] Run time of timer "kill calls": 3.424099 sec, exceeding limit of 20% (0.200000 sec)
> ERR: [d8ta656qntngp9rqja7i/as399209d1/1 port 36769]: [core] sending descriptor 5 len 160
> ERR: [d8ta656qntngp9rqja7i/de4c8uov6m/1 port 36881]: [core] Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
> ERR: [d8ta656qntngp9rqja7i/de4c8uov6m/1 port 36881]: [core] Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible

Where descriptor 5 means /proc/rtpengine/30/control and 30 is the correct group number.  That descriptor 5 lines come from extra debug I have added
```diff
diff --git a/daemon/kernel.c b/daemon/kernel.c
index 191d21e5..a7234292 100644
--- a/daemon/kernel.c
+++ b/daemon/kernel.c
@@ -299,12 +299,13 @@ int kernel_send_rtcp(struct rtpengine_send_packet_info *info, const char *buf, s
        cmd->cmd = REMG_SEND_RTCP;
        cmd->send_packet = *info;
        memcpy(&cmd->send_packet.data, buf, len);
-
+       errno = 0;
+       ilog(LOG_ERR, "sending descriptor %i len %lu", kernel.fd, total_len);
        ssize_t ret = write(kernel.fd, cmd, total_len);
 
        if (ret != total_len) {
                if (ret == -1)
-                       ilog(LOG_ERR, "Failed to send RTCP via kernel interface: %s", strerror(errno));
+                       ilog(LOG_ERR, "Failed to send RTCP via kernel interface: %i %s ", errno, strerror(errno));
                else
                        ilog(LOG_ERR, "Failed to send RTCP via kernel interface (%zi != %zu)",
                                        ret, total_len);
```

I realize now that it is actually not documented which kernel parameters must be turned on, in order for xt_RTPENGINE.ko to be functional.  To my knowledge xt_RTPENGINE can do encryption/decription, this functionality is likely provided by other kernel modules, but the file docs/compiling_and_installing.md does not say, which other kernel switches must be enabled (integrated or as module) for xt_RTPENGINE to function.

Please document on which kernel parameters are required for xt_RTPENGINE (e.g. to do in-kernel re-encryption), or if no such options are needed, state so.

The timers reported above are not good, but I know that my system is slow.

In addition, `lsmod` returns
```
# lsmod    
Module                  Size  Used by
xt_tcpudp              20480  0 
nft_compat             20480  1 
xt_RTPENGINE           61440  5 
nft_counter            16384  1 
serio_raw              20480  0 
evdev                  28672  4 
sch_fq_codel           20480  2 
sctp                  401408  4 
br_netfilter           32768  0 
bridge                233472  1 br_netfilter
stp                    16384  1 bridge
llc                    16384  2 bridge,stp
drm                   466944  0 
drm_panel_orientation_quirks    24576  1 drm
backlight              20480  1 drm
x_tables               40960  3 nft_compat,xt_tcpudp,xt_RTPENGINE
```
so xt_RTPENGINE is used by 5, but the only reported user of xt_RTPENGINE is x_tables.  I would expect to see on the xt_RTPENGINE line who uses xt_RTPENGINE - five items.

When I stop rtpengine, my iptables are clear:
```
# systemctl start rtpengine && iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
RTPENGINE  udp  --  anywhere             anywhere             udp dpts:30000:40000 RTPENGINE id:30

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

# systemctl stop rtpengine && iptables -L 
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
```
According to the documentation I shall be able to unload xt_rtpengine.
```
# rmmod xt_RTPENGINE
rmmod: ERROR: Module xt_RTPENGINE is in use

# lsmod
Module                  Size  Used by
xt_tcpudp              20480  0 
nft_compat             20480  0 
xt_RTPENGINE           61440  2 
nft_counter            16384  0 
serio_raw              20480  0 
evdev                  28672  4 
sch_fq_codel           20480  2 
sctp                  401408  4 
br_netfilter           32768  0 
bridge                233472  1 br_netfilter
stp                    16384  1 bridge
llc                    16384  2 bridge,stp
drm                   466944  0 
drm_panel_orientation_quirks    24576  1 drm
backlight              20480  1 drm
x_tables               40960  3 nft_compat,xt_tcpudp,xt_RTPENGINE
```
I have to add, that once I restarted the system, I could several times start rtpengine, which loaded xt_RTPENGINE, and then stop rtpengine, which unloaded xt_RPTENGINE.  But from one moment on I was not able to unload xt_RTPENGINE.

**Comment by rfuchs** [comment]
> I run a Linux from Scratch system. In the past rtpengine was able to utilize the in-kernel forwarding. Now it does not work.
> 
> It either prints
> 
> > ERR: [krg7cjellodq80k39lu8/as30961924/1 port 34395]: [core] Failed to send RTCP via kernel interface: Function not implemented

Do you perhaps have a mismatch between the version of the daemon and the version of the kernel module?

**Comment by dilyanpalauzov** [comment]
Now the first two numbers of the versions in the kernel are the same, maybe the last number was different.  I cannot say anymore how this happened exactly.

In any case it is not documented what options shall be enabled, when the Kernel is compiled, so that xt_RTPENGINE.ko can work.  For instance, for in-kernel re-encryption, does the kernel need to have specific functions  (as modules or built-in functions).

Another problem is that `lsmod` shows
```
Module                  Size  Used by
xt_RTPENGINE           61440  3 
evdev                  28672  4 
serio_raw              20480  0 
sch_fq_codel           20480  2 
drm                   466944  0 
drm_panel_orientation_quirks    24576  1 drm
backlight              20480  1 drm
ip_tables              32768  0 
```
so it does not display which three modules used xt_RTPENGINE.

**Comment by rfuchs** [comment]
> In any case it is not documented what options shall be enabled, when the Kernel is compiled, so that xt_RTPENGINE.ko can work. For instance, for in-kernel re-encryption, does the kernel need to have specific functions (as modules or built-in functions).

I would tell you if I knew. But I don't. If you find out, open a PR and add it to the documentation.



> Another problem is that `lsmod` shows
> 
> ```
> Module                  Size  Used by
> xt_RTPENGINE           61440  3 
> evdev                  28672  4 
> serio_raw              20480  0 
> sch_fq_codel           20480  2 
> drm                   466944  0 
> drm_panel_orientation_quirks    24576  1 drm
> backlight              20480  1 drm
> ip_tables              32768  0 
> ```
> 
> so it does not display which three modules used xt_RTPENGINE.

No other modules are using `xt_RTPENGINE`. The usage count is increased by iptables rules being present, by the `rtpengine` daemon running and having the kernel interface open, and by kernel forwarding tables being present (see `/proc/rtpengine/list`). So there's nothing to show in `lsmod`

**Comment by dilyanpalauzov** [comment]
Rigth now I do not get these messages any more:

> WARNING: [core] Run time of timer "kill calls": 3.424099 sec, exceeding limit of 20% (0.200000 sec)
> ERR: [d8ta656qntngp9rqja7i/as399209d1/1 port 36769]: [core] sending descriptor 5 len 160

and also in `kernel_send_rtcp()` ` write(kernel.fd, cmd, total_len);` does succeed.

I am closing this as my problem is gone.
