### ISSUE TITLE
collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped

### ISSUE THREAD

**Issue by voztovoice** [sipwise/rtpengine#1707]
Rocky Linux 8
DigitalOcean VPS 1GB Ram

git clone https://github.com/sipwise/rtpengine.git
cd /usr/src/rtpengine/daemon
make

cc -rdynamic -g -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wstrict-prototypes -Werror=return-type -Wshadow -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include    -pthread      -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread    -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg  -I/usr/include/ffmpeg  -I/usr/include/ffmpeg  -I/usr/include/ffmpeg  -I/usr/include/ffmpeg   -I/usr/include/opus  -DWITH_TRANSCODING -I/usr/include/mysql -I/usr/include/mysql/mysql -DHAVE_BCG729 -I/usr/src/bcg729/include/ -DRTPENGINE_VERSION="\"git-master-3a940935\""  -DHAVE_LIBSYSTEMD -o rtpengine main.o kernel.o helpers.o control_tcp.o call.o control_udp.o redis.o bencode.o cookie_cache.o udp_listener.o control_ng.strhash.o sdp.strhash.o stun.o rtcp.o crypto.o rtp.o call_interfaces.strhash.o dtls.o log.o cli.o graphite.o ice.o media_socket.o homer.o recording.o statistics.o cdr.o ssrc.o iptables.o tcp_listener.o codec.o load.o dtmf.o timerthread.o media_player.o jitter_buffer.o t38.o websocket.o mqtt.o janus.strhash.o audio_player.o loglib.o auxlib.o rtplib.o str.o socket.o streambuf.o ssllib.o dtmflib.o mix_buffer.o poller.o codeclib.strhash.o resample.o mvr2s_x64_avx2.o mvr2s_x64_avx512.o mix_in_x64_avx2.o mix_in_x64_avx512bw.o mix_in_x64_sse2.o -lm -ldl -lglib-2.0  -lgthread-2.0 -pthread -lglib-2.0  -lz  -lpcre  -lcrypto  -lssl -lcrypto  -levent_pthreads -levent  -lpcap -lxmlrpc_client  -lxmlrpc  -lxmlrpc_util  -lhiredis -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lwebsockets  -lip4tc -lip6tc  -lavcodec  -lavformat  -lavutil  -lswresample  -lavfilter  -lspandsp  -lopus  -L/usr/lib64/ -lmariadb -L/usr/src/bcg729/src/ -lbcg729 -lsystemd
collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
make[1]: *** [../lib/common.Makefile:7: rtpengine] Error 1
rm sdp.strhash.c control_ng.strhash.c call_interfaces.strhash.c janus.strhash.c
make[1]: Leaving directory '/usr/src/rtpengine/daemon'
make: *** [../lib/common.Makefile:4: all] Error 2

**Comment by dilyanpalauzov** [comment]
You shall get the backtrace from collect2 and submit is as bug report to your distribution, or to the compiler.

> DigitalOcean VPS 1GB Ram

Enabling swap might help.

**Comment by voztovoice** [comment]
Rocky Linux 9 
DigitalOcean VPS 1GB Ram

compile without problems.

**Comment by voztovoice** [comment]
Installing binutils 2.41 from source solve the error. The binutils version came with Rocky Linux 8 at this moment is 2.30
