### ISSUE TITLE
kernel-module make failed. 

### ISSUE THREAD

**Issue by gao114882** [sipwise/rtpengine#1708]
uname -a 
Linux test-oa-03 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
gcc -v 
gcc 版本 8.3.0 (GCC) 
rtpengine version : master

Hello: 
the error is

![image](https://github.com/sipwise/rtpengine/assets/22283924/2c288689-c05e-4ff5-94c3-138f6c5031c2)

 please help me

**Comment by rfuchs** [comment]
A translation of what the error means might help?

**Comment by gao114882** [comment]
this means the type of oskb->tstamp can't  use minus sign 

> A translation of what the error means might help?
