### ISSUE TITLE
RTPEngine doesn't send RTP Traffic

### ISSUE THREAD

**Issue by iliesh** [sipwise/rtpengine#1709]
I'm encountering an unusual issue with one of our RTPEngine instances. It seems that after a user changes their network, the RTP traffic isn't being correctly routed to the new endpoint.

Here's the scenario: We have a mobile app running on Wi-Fi, and when a call is initiated, the RTP traffic flows smoothly to the server and back. However, if the user switches their network from Wi-Fi to 5G during an ongoing call, the RTP engine continues to send RTP traffic to the old IP address, failing to adapt to the new network settings.

Upon inspecting the logs and examining the Wireshark captures, I can observe STUN packets arriving from the new IP address, indicating awareness of the network change. However, there's no RTP traffic directed to this updated address.

Some logs relevant to this particular call when the network was switched:

1.2.74.239 - Wi-Fi IP Address
11.12.174.137 - Mobile IP Address
21.22.180.76 - Server IP Address

```
Aug 21 13:11:43 k7-core5 rtpengine[5098]: DEBUG: [9serer0lngtqvbl6q4ok/u4km9cppfd/1 port 19869]: [core] Successful STUN binding request from 11.12.174.137:19224
Aug 21 13:11:44 server-111 rtpengine[5098]: DEBUG: [9serer0lngtqvbl6q4ok/u4km9cppfd/1 port 19869]: [core] Successful STUN binding request from 11.12.174.137:19224
Aug 21 13:11:46 server-111 rtpengine[5098]: DEBUG: [9serer0lngtqvbl6q4ok/u4km9cppfd/1 port 19869]: [ice] ICE pair XB4j3OpAqJGSDLWn:89d5ed44359bf90:1 has been nominated by peer
Aug 21 13:11:46 server-111 rtpengine[5098]: DEBUG: [9serer0lngtqvbl6q4ok/u4km9cppfd/1 port 19869]: [ice] ICE completed, using pair XB4j3OpAqJGSDLWn:ef31471f359bf90:1
Aug 21 13:11:46 server-111 rtpengine[5098]: INFO: [9serer0lngtqvbl6q4ok/u4km9cppfd/1 port 19869]: [ice] ICE negotiated: peer for component 1 is 1.2.74.239:57417
Aug 21 13:11:46 server-111 rtpengine[5098]: DEBUG: [9serer0lngtqvbl6q4ok/u4km9cppfd/1 port 19869]: [core] Successful STUN binding request from 11.12.174.137:19224
Aug 21 13:11:48 server-111 rtpengine[5098]: NOTICE: [9serer0lngtqvbl6q4ok/u4km9cppfd/1 port 19869]: [srtp] Crypto debug: RTCP SSRC e1a91953, enc pl: 0a6a44b29de51bd5cd235148314198b70280313ce6efef1c80000009, idx 2147483657, rcv hmac: d836ff43b6c8d7c39748, calc hmac: d836ff43b6c8d7c39748, dec pl: 064aa68c00000000000016cc0000000cd2f7c6c0000c94a9
Aug 21 13:11:49 server-111 rtpengine[5098]: DEBUG: [9serer0lngtqvbl6q4ok/u4km9cppfd/1 port 19869]: [core] Successful STUN binding request from 11.12.174.137:19224
Aug 21 13:11:49 server-111 rtpengine[5098]: DEBUG: [9serer0lngtqvbl6q4ok/u4km9cppfd/1 port 19869]: [core] Handling packet: remote 11.12.174.137:19224 (expected: 1.2.74.239:57417) -> local 21.22.180.76:19869
Aug 21 13:11:51 server-111 rtpengine[5098]: DEBUG: [9serer0lngtqvbl6q4ok/u4km9cppfd/1 port 19869]: [core] Successful STUN binding request from 11.12.174.137:19224
```

![2023-08-21_13-45](https://github.com/sipwise/rtpengine/assets/14953151/8ae683b1-fb59-4554-b7dd-b2453bdce202)

OS: CentOS Stream release 8
Kamailio version: 5.7.1
RTPEngine: git-mr11.3.1-70c5b95e

This is the relevant kamailio code:
```
rtpengine_manage("rtcp-mux-demux DTLS=off SDES-off ICE=remove RTP/AVP loop-protect");
```

At the same time, I have another box with a different environment running an older rtpengine version compiled from the master branch, and there, I don't have this problem. 

Are there any specific configuration flags that I should pay attention in this context?

**Comment by rfuchs** [comment]
I'm not sure if it's a valid scenario for ICE to simply nominate a new candidate pair after ICE has already finished processing, without doing an ICE restart. I'll have to check the RFC.

**Comment by rfuchs** [comment]
Do you happen to have a pcap that shows the entire ICE/STUN exchanges for such a call, meaning before and after the network change?

**Comment by iliesh** [comment]
@rfuchs - Yes, I do have it. 
Can I share it with you privately?

**Comment by rfuchs** [comment]
> @rfuchs - Yes, I do have it. Can I share it with you privately?

Email is in my profile

**Comment by rfuchs** [comment]
What happens in that pcap is:

The mobile device was in "ICE controlling" mode. ICE negotiation happens, and the mobile device ends up settling on the wifi interface. As the mobile device is in controlling mode, the mobile device itself nominates that interface to be used for media.

In the meantime, ICE exchanges also take place over the alternative network interface. They're successful, but the ICE priority is lower, and the device does not nominate these candidates, so they end up not being used.

ICE/STUN keealives continue afterwards.

At some point the wifi interface stops communicating. The ICE/STUN keepalives over the alternative network interface continue. However, the ICE priority is still lower, and the mobile device does not at any point nominate the alternative network interface.

To my knowledge there is no mechanism in ICE to facilitate a media handover in this case. There is no explicit indication that the wifi interface is gone. ICE has concluded, a candidate pair was nominated, and this candidate pair is supposed to be used for the remainder of the ICE session. AFAIK ICE has no support for dynamic on-the-fly switching of interfaces or candidates during runtime after ICE has concluded.

I would say it's the responsibility of the mobile device to signal a change in network environment by doing an ICE restart.

**Comment by iliesh** [comment]
Hi @rfuchs,

Thank you a lot for your assistance in investigating this matter. But, based on my analysis of the pcap file, I think that the mobile application is nominating candidates after a network switch has occurred. Please refer to packet number 4013, where you will observe a STUN request originating from the ICE-CONTROLLING device:

<img width="1128" alt="image" src="https://github.com/sipwise/rtpengine/assets/14953151/6b3ad7f7-ff74-4b14-8fcc-6488c0494aee">

Shouldn't rtpengine start sending RTP traffic after this process? At least, this is what happen using an older rtpengine instance (packet 1208):

<img width="1104" alt="image" src="https://github.com/sipwise/rtpengine/assets/14953151/e3283edb-04b6-4c58-8bcf-7192cbde5e19">

**Comment by rfuchs** [comment]
> Shouldn't rtpengine start sending RTP traffic after this process?

Well no, because that just gives you two nominated candidate pairs, and the candidate pair with the highest priority ought to be used in this case, which would still be the original one (wifi interface). AFAIK ICE doesn't provide a mechanism for invalidating a candidate pair that has already been marked as valid.

Quoting RFC 8445:

   Once the controlling agent has successfully nominated a candidate
   pair ([Section 7.2.5.3.4](https://datatracker.ietf.org/doc/html/rfc8445#section-7.2.5.3.4)), the agent MUST NOT nominate another pair
   for same component of the data stream within the ICE session.  Doing
   so requires an ICE restart.

   A controlling agent that does not support this specification (i.e.,
   it is implemented according to [RFC 5245](https://datatracker.ietf.org/doc/html/rfc5245)) might nominate more than one
   candidate pair.  This was referred to as "aggressive nomination" in
   [RFC 5245](https://datatracker.ietf.org/doc/html/rfc5245).  If more than one candidate pair is nominated by the
   controlling agent, and if the controlled agent accepts multiple
   nominations requests, the agents MUST produce the selected pairs and
   use the pairs with the highest priority.

**Comment by iliesh** [comment]
Hi @rfuchs ,

After using ICE Restart, we noticed that rtpengine stopped sending RTP. We have sent more details privately. Could you please investigate when you have a chance? Is there anything we are overlooking?

**Comment by rfuchs** [comment]
> After using ICE Restart, we noticed that rtpengine stopped sending RTP. We have sent more details privately. Could you please investigate when you have a chance? Is there anything we are overlooking?

Yes there is. ICE restart is working now:

```
Aug 25 19:24:14 k7-core5 rtpengine[14783]: INFO: [mlslshrir19nj5t8gkak]: [crypto] ICE restart without TLS-ID, restarting DTLS
...
Aug 25 19:24:14 k7-core5 rtpengine[14783]: DEBUG: [mlslshrir19nj5t8gkak/ock7uaveg1/1]: [ice] ICE restart detected, resetting ICE agent
...
Aug 25 19:24:15 k7-core5 rtpengine[14783]: DEBUG: [mlslshrir19nj5t8gkak/ock7uaveg1/1 port 22074]: [ice] ICE completed, using pair rQNyMEzyMy4fGcK9:47d7cc3f35a0b90:1
Aug 25 19:24:15 k7-core5 rtpengine[14783]: INFO: [mlslshrir19nj5t8gkak/ock7uaveg1/1 port 22074]: [ice] ICE negotiated: peer for component 1 is ...:3203
Aug 25 19:24:15 k7-core5 rtpengine[14783]: INFO: [mlslshrir19nj5t8gkak/ock7uaveg1/1 port 22074]: [ice] ICE negotiated: local interface ...
```

but

```
Aug 25 19:24:14 k7-core5 rtpengine[14783]: INFO: [mlslshrir19nj5t8gkak]: [crypto] ICE restart without TLS-ID, restarting DTLS
```

The RFC is not explicit about this, which is why `a=tls-id` was introduced. But the most common case is that when ICE is restarted, DTLS also needs to be reset and re-established. So rtpengine is expecting to see a new incoming DTLS connection (because rtpengine is in passive role). But this never happens.

**Comment by mariouzae** [comment]
Hi @rfuchs,

Should the rtpengine change its fingerprint when doing the DTLS restarting? when it is working as the active role we see the rtpengine sending the Client Hello but our app doesn't reply with Server Hello because the fingerprint is the same.

**Comment by rfuchs** [comment]
Fingerprint remains the same as it's always the same certificate. The `tls-id` changes though.

**Comment by iliesh** [comment]
We are going to stick to the oldest version of RTPengine until the webrtc library used in our app will be updated to the latest RFC. Thank you @rfuchs for your help.
