### ISSUE TITLE
Segfault in 11.4.1

### ISSUE THREAD

**Issue by saraxxin** [sipwise/rtpengine#1710]
Hi there.

I have recently updated from rtpengine 11.2 to 11.4.1, but since doing so the system segfaults from time to time.

`Aug 24 10:38:19 cgrt-jhb-sbc01 kernel: [129549.596490] rtpengine[1163988]: segfault at 70 ip 0000562bcda3efad sp 00007f97d534de70 error 4 in rtpengine[562bcd9cc000+c5000]
Aug 24 10:38:19 cgrt-jhb-sbc01 kernel: [129549.596504] Code: 24 20 ba 00 00 00 00 48 8b b8 30 87 00 00 48 89 f9 48 29 f1 48 39 f7 48 0f 42 ca f0 48 01 8b 58 03 00 00 48 8b b3 88 00 00 00 <4
8> 8b 76 70 f0 48 01 4e 68 f0 48 01 0d 22 92 09 00 48 8b b3 80 03
`

I have been trying to get a core dump of what is causing the segfault but so far I have had no luck.. 
I installed both ngcp-rtpengine-daemon-dbgsym_11.4.1.3+0~mr11.4.1.3_amd64.deb and ngcp-rtpengine-iptables-dbgsym_11.4.1.3+0~mr11.4.1.3_amd64.deb and also run the below.

`sysctl -w kernel.core_pattern=/tmp/core.%e.%p.%h.%t 
ulimit -c unlimited`

I am running Debian 11.7 with kernel 5.10.0-25-amd64.

Any guidance on how to get the core dump so that I can get to the bottom of this issue would be highly appreciated.

Thanks!

**Comment by rfuchs** [comment]
If running under systemd, have a look at `systemd-coredump` as a service to manage core dumps.

**Comment by saraxxin** [comment]
Thanks! This worked.
Here is the coredump.
[rtpengine_coredump.txt](https://github.com/sipwise/rtpengine/files/12438642/rtpengine_coredump.txt)

It looks like it is complaining about this.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055f4364a8fad in atomic64_add (a=640, u=<error reading variable: Cannot access memory at address 0x70>) at ../include/aux.h:443

**Comment by saraxxin** [comment]
Sorry about that! I realized I need to run bt full.
See below.
[rtpengine_coredump.txt](https://github.com/sipwise/rtpengine/files/12439591/rtpengine_coredump.txt)
