### ISSUE TITLE
Call references not being expunged

### ISSUE THREAD

**Issue by abalashov** [sipwise/rtpengine#1713]
Using `11.4.1.1+0~mr11.4.1.1` (`git-HEAD-76857ad4`) on Ubuntu Server 22.04.3 (x86_64 in AWS EC2, kernel `6.2.0-1009-aws`) with a trivial number of concurrent streams (varying between 0 and 4). 

However, the streams listed in `cat /proc/rtpengine/0/status` and `cat /proc/rtpengine/0/list` seem to increase monotonically:

<img width="800" alt="east1" src="https://github.com/sipwise/rtpengine/assets/5641703/3228facf-ce4e-4a69-ac5c-01da2be22a7f">

This state of affairs persists indefinitely, despite an obvious lack of commensurate RTP forwarding activity:

```
# cat /proc/rtpengine/0/status
Refcount:    1
Control PID: 471
Targets:     130

# while : ; do sleep 10 ; echo ; date ; iptables -L INPUT -nv ; done

Mon Aug 28 13:49:32 CDT 2023
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
3545K  783M RTPENGINE  udp  --  *      *       0.0.0.0/0            0.0.0.0/0            RTPENGINE id:0

Mon Aug 28 13:49:42 CDT 2023
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
3547K  783M RTPENGINE  udp  --  *      *       0.0.0.0/0            0.0.0.0/0            RTPENGINE id:0

Mon Aug 28 13:49:52 CDT 2023
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
3549K  783M RTPENGINE  udp  --  *      *       0.0.0.0/0            0.0.0.0/0            RTPENGINE id:0

Mon Aug 28 13:50:02 CDT 2023
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
3552K  784M RTPENGINE  udp  --  *      *       0.0.0.0/0            0.0.0.0/0            RTPENGINE id:0
```

The only other thing of note is that the `delete` commands, while recognised in the logs, do not appear to lead to the characteristic end-of-call summary, the one with packet counters, octet counters, inferred MOS score, etc:

```
Aug 28 12:46:47 rtpengine01 rtpengine[840]: INFO: [QxnHv72S4da3FFXamslSRA..]: [control] Received command 'delete' from 127.0.0.1:37134
Aug 28 12:46:47 rtpengine01 rtpengine[840]: INFO: [QxnHv72S4da3FFXamslSRA..]: [core] Scheduling deletion of call branch 'b104262b' (via-branch '') in 30 seconds
Aug 28 12:46:47 rtpengine01 rtpengine[840]: INFO: [QxnHv72S4da3FFXamslSRA..]: [core] Scheduling deletion of call branch 'gK04c72970' (via-branch '') in 30 seconds
Aug 28 12:46:47 rtpengine01 rtpengine[840]: INFO: [QxnHv72S4da3FFXamslSRA..]: [core] Scheduling deletion of entire call in 30 seconds
Aug 28 12:46:47 rtpengine01 rtpengine[840]: INFO: [QxnHv72S4da3FFXamslSRA..]: [control] Replying to 'delete' from 127.0.0.1:37134 (elapsed time 0.000126 sec)
```

This leads me to think that the deletion is not fully completing or that some reference to the dialog->stream structure is not being released. The delete commands from Kamailio are quite unremarkable, just `rtpengine_delete()` calls upon `BYE` and `CANCEL` as one might expect.

Thank you in advance!

**Comment by rfuchs** [comment]
Update your code. You're missing ff6d24e

**Comment by abalashov** [comment]
Thank you, @rfuchs, much appreciated, and more so the quick response!
