### ISSUE TITLE
Failed to start rtpengine

### ISSUE THREAD

**Issue by prathibhacdac** [sipwise/rtpengine#1714]
when starting rtpengine using the command

systemctl start rtpengine

and on running 

systemctl status rtpengine

the following error occured

ERR: [http] libwebsockets: ERROR on binding fd 9 to port 2225 (-1 98)
Aug 31 08:27:33 ip-172-31-34-24 rtpengine[347912]: ERR: [http] libwebsockets: init server failed
Aug 31 08:27:33 ip-172-31-34-24 rtpengine[347912]: ERR: [http] Failed to start websocket listener: LWS failed to create vhost
Aug 31 08:27:33 ip-172-31-34-24 rtpengine[347912]: Fatal error: Failed to init websocket listener
Aug 31 08:27:33 ip-172-31-34-24 rtpengine[347912]: CRIT: [core] Fatal error: Failed to init websocket listener
Aug 31 08:27:33 ip-172-31-34-24 systemd[1]: ngcp-rtpengine-daemon.service: Main process exited, code=exited, status=255/EXCEPTION
Aug 31 08:27:33 ip-172-31-34-24 systemd[1]: ngcp-rtpengine-daemon.service: Failed with result 'exit-code'.
Aug 31 08:27:33 ip-172-31-34-24 systemd[1]: Failed to start NGCP RTP/media Proxy Daemon.

**Comment by rfuchs** [comment]
X-posted to mailing list
