### ISSUE TITLE
ERROR:rtpengine:send_rtpe_command: can't send (#7 iovec buffers) command to a RTP proxy (111:Connection refused)

### ISSUE THREAD

**Issue by prathibhacdac** [sipwise/rtpengine#1716]
rtpeninge package is removed from the system. Still getting the following errors while checking the systemctl status opensips

ERROR:rtpengine:send_rtpe_command: can't send (#7 iovec buffers) command to a RTP proxy (111:Connection refused)
Sep 07 08:26:22 ip-172-31-34-24 opensips[239917]: Sep  7 08:26:22 [239917] ERROR:rtpengine:send_rtpe_command: timeout waiting reply from a RTP proxy
Sep 07 08:26:22 ip-172-31-34-24 opensips[239917]: Sep  7 08:26:22 [239917] ERROR:rtpengine:send_rtpe_command: proxy <udp:127.0.0.0:60000> does not respond, disable it
Sep 07 08:26:22 ip-172-31-34-24 opensips[239917]: Sep  7 08:26:22 [239917] ERROR:rtpengine:rtpe_test: proxy did not respond to ping
Sep 07 08:26:22 ip-172-31-34-24 opensips[239916]: Sep  7 08:26:22 [239916] ERROR:rtpengine:send_rtpe_command: can't send (#7 iovec buffers) command to a RTP proxy (111:Connection refused)
Sep 07 08:26:22 ip-172-31-34-24 opensips[239916]: Sep  7 08:26:22 [239916] ERROR:rtpengine:send_rtpe_command: can't send (#7 iovec buffers) command to a RTP proxy (111:Connection refused)
Sep 07 08:26:22 ip-172-31-34-24 opensips[239916]: Sep  7 08:26:22 [239916] ERROR:rtpengine:send_rtpe_command: timeout waiting reply from a RTP proxy
Sep 07 08:26:22 ip-172-31-34-24 opensips[239916]: Sep  7 08:26:22 [239916] ERROR:rtpengine:send_rtpe_command: proxy <udp:127.0.0.0:60000> does not respond, disable it
Sep 07 08:26:22 ip-172-31-34-24 opensips[239916]: Sep  7 08:26:22 [239916] ERROR:rtpengine:rtpe_test: proxy did not respond to ping

**Comment by rfuchs** [comment]
Maybe remove the invocation of rtpengine from the OpenSIPS config scripts?

Not an issue with the code, therefore closing. Maybe check with the OpenSIPS support forums.
