### ISSUE TITLE
socket_sendiov: Assertion `cm != NULL' 

### ISSUE THREAD

**Issue by smititelu** [sipwise/rtpengine#1720]
Hello, getting this below error with the latest build. I think this is the commit causing it: 8684a1933a3aad0731aec86ca242ea2e363cbe01
```
Sep 11 15:43:00 test-rtpproxy2-bs rtpengine[2356464]: INFO: [control] Received command 'ping' from 10.84.1.13:45266
Sep 11 15:43:00 test-rtpproxy2-bs rtpengine[2356464]: INFO: [control] Replying to 'ping' from 10.84.1.13:45266 (elapsed time 0.000001 sec)
Sep 11 15:43:00 test-rtpproxy2-bs rtpengine[2356464]: rtpengine: ../lib/socket.h:198: socket_sendiov: Assertion `cm != NULL' failed.
```
My system is debian bullseye:
```
Linux test-rtpproxy 5.10.0-22-amd64 #1 SMP Debian 5.10.178-3 (2023-04-22) x86_64 GNU/Linux
```
Having a look in the man page here [1] looks like it returns NULL when there is not enough space in the buffer. Do you know if I should update some system params?

[1] https://man7.org/linux/man-pages/man3/cmsg.3.html

**Comment by rfuchs** [comment]
b9af9d0e4 should have fixed this

**Comment by smititelu** [comment]
Indeed it works with that commit. Issue was because of a local patch, that commit did not apply. Closing this issue.

Thank you,
Stefan

**Comment by smititelu** [comment]
My bad... still not working. I tried with a fresh local rtpengine build and sending PING from sip server:
```
stefan@thinkpad:~/allgit/kamailio$ sudo kamcmd rtpengine.ping all
{
	url: all
	status: fail
}
...
stefan@thinkpad:~/rtpengine$ sudo rtpengine -f --config-file /home/stefan/rtpengine/etc/rtpengine.conf
rtpengine: ../lib/socket.h:198: socket_sendiov: Assertion `cm != NULL' failed.
Aborted
```
