### ISSUE TITLE
ICE role detection for incoming call

### ISSUE THREAD

**Issue by vijaykumar-exotel** [sipwise/rtpengine#1721]
As of now, rtpengine is sending stun request with ICE_Controlled attribute, however peer is sending offer with ice_lite in sdp session attirbute in sdp. due to which rtpengine try to send stun request with ICE_CONTROLLED attribute and when tie_breaker value is lesser than when peer send stun request rtpengine sends role conflict.
However there are logic implemented in rtpengine sdp.c that if ice-lite option is coming in media attribute, then rtpengine assume peer with ice_lite. in that case rtpengine change its own role during stun request then it could send stun request with ICE_CONTROLLING attribute.
However as per the RFC ice-lite attribute in sdp should be session level attribute. so not sure why sdp.c checking ice-lite attribute from media attribute.? is it a bug or ice-lite line should be expected in media attribute only?

**Comment by rfuchs** [comment]
Cross posted to mailing list
