### ISSUE TITLE
FAILED TO CREATE KERNEL TABLE 0 (No such file or directory), KERNEL FORWARDING DISABLED

### ISSUE THREAD

**Issue by jj1682000** [sipwise/rtpengine#1727]
every one, any idea for this?

`
$ docker compose up
[+] Running 1/0
 ✔ Container rtpengine  Created                                                                               0.0s
Attaching to rtpengine
rtpengine  | [1695607209.005503] ERR: [core] FAILED TO CREATE KERNEL TABLE 0 (No such file or directory), KERNEL FORWARDING DISABLED
rtpengine exited with code 0

`

Dockerfile:

`
FROM alpine:latest AS builder
RUN apk update && apk upgrade && apk add build-base git pkgconf perl gperf glib-dev ffmpeg-dev openssl-dev \
    libevent-dev libpcap-dev spandsp-dev json-glib-dev hiredis-dev xmlrpc-c-dev \
    mariadb-connector-c-dev cmake \
    pcre-dev libwebsockets-dev opus-dev linux-headers
RUN git clone https://github.com/sipwise/rtpengine -b mr11.2.1.12
RUN cd rtpengine/daemon && with_iptables_option=no make

FROM alpine:latest
RUN apk update && apk upgrade && apk add glib ffmpeg openssl libevent libpcap spandsp \
    json-glib hiredis xmlrpc-c xmlrpc-c-client mariadb-connector-c strace gdb \
    pcre libwebsockets \
    && addgroup -S rtpengine && adduser -S rtpengine -G rtpengine
COPY --from=builder /rtpengine/daemon/rtpengine /usr/bin/
RUN mkdir /var/spool/rtpengine
RUN chown -R rtpengine.rtpengine /var/spool/rtpengine
USER rtpengine
ENTRYPOINT ["/usr/bin/rtpengine"]
`

docker-compose.yml

`
version: '3'
services:

  rtpengine:
    container_name: rtpengine
    image: rtpengine:mr11.2.1.12-alpine-build
    network_mode: "host"
    volumes:
       - '/etc/rtpengine:/etc/rtpengine'
`

**Comment by rfuchs** [comment]
Not an issue with the code, therefore closing. The question should probably be directed to the author of the docker image.

My guess is that the host system must load the kernel module, or that the config should indicate table = -1 to disable the warning.

**Comment by jj1682000** [comment]
> Not an issue with the code, therefore closing. The question should probably be directed to the author of the docker image.
> 
> My guess is that the host system must load the kernel module, or that the config should indicate table = -1 to disable the warning.

Thanks for your help and recommend!

I built the image based on Debian and it works fine. but there is ERROR in log as below:

`
$ docker compose up
[+] Running 1/0
 ✔ Container rtpengine  Created                                                                             0.0s 
Attaching to rtpengine
rtpengine  | Starting rtpengine daemon
rtpengine  | [1696216644.037530] ERR: [core] FAILED TO DELETE KERNEL TABLE 0 (Permission denied), KERNEL FORWARDING DISABLED
rtpengine  | Starting RTP/media proxy: rtpengine-daemon.
`

Dockerfile:
`
FROM debian:bullseye-slim

RUN apt update -y
RUN apt install wget nano -y
RUN wget https://dfx.at/rtpengine/latest/pool/main/r/rtpengine-dfx-repo-keyring/rtpengine-dfx-repo-keyring_1.0_a>
RUN dpkg -i rtpengine-dfx-repo-keyring_1.0_all.deb

#Debian release
ENV DIST="bullseye"
#Rtpengine version
ENV REL="11.2"

RUN echo "deb [signed-by=/usr/share/keyrings/dfx.at-rtpengine-archive-keyring.gpg] \
  https://dfx.at/rtpengine/$REL $DIST main" | tee /etc/apt/sources.list.d/dfx.at-rtpengine.list
RUN apt update -y
RUN apt install rtpengine rsyslog -y

COPY rtpengine_bkp.conf /etc/rtpengine/

# Startup script
COPY start.sh /start.sh
RUN chmod +x /start.sh

#Command to run every time the container starts
#ENTRYPOINT ["/start.sh"]
ENTRYPOINT /start.sh && /bin/bash
`

docker-compose.yml
`
version: '3'
services:

  rtpengine:
    container_name: rtpengine
    image: rtpengine:11.2-bullseye-slim
    network_mode: "host"
    privileged: true
    volumes:
      - '/lib/modules/5.10.0-21-amd64:/lib/modules/5.10.0-21-amd64'
      - '/etc/rtpengine:/etc/rtpengine'
`
