### ISSUE TITLE
RTP droped : Too many packets in UDP receive queue

### ISSUE THREAD

**Issue by Hyleoss** [sipwise/rtpengine#1728]
Hi,

I experienced a strange issue since I updated RTPEngine from 11.2.1.5 to 11.3.1.9 (Debian 11).
I got a scenario where RTPEngine stop forwarding RTP with this error : 

`[core] Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible`

I googled this error and it seems to happens when their is a loop on rtp, or when RTPEngine receive same sdp info multiple time.
But in my case, it's just a classic call without re-invite.

Also tried to update to 11.5.1.2 but same problem.

Here is the scenario and the call flow : 

End user (A) behind Wildix PBX with overflow on user B.
Someone (Toto) call A, ringing for few seconds, then overflow. B take the call, RTP is fine for ~1 second and then drop with the error Too many packets in UDP receive queue. B can ear Toto but Toto don't have any sound.

Provider --> OpenSIPS + RTPEngine --> Asterisk C5 --> Client PBX (Wildix)

Here is the flow from Provider --> OpenSIPS -> Asterisk :
![image](https://github.com/sipwise/rtpengine/assets/91903480/719de256-7f93-4e76-8896-83197054afef)

And here is the log from RTPEngine at loglevel 7 : https://pastebin.com/cbPYvZsb

Any idea what might be causing this problem ? I tried to add loop-protect args but nothing changed.

Thanks,

**Comment by rfuchs** [comment]
A loop is one possibility. It could also be a load issue, or something with your network setup. The log looks straight forward and doesn't indicate a loop. It kinda looks like all the RTP packets suddenly arrived in one burst.

This is almost certainly not a problem with the code, therefore closing it. Requests for support should be taken to the mailing list.
