### ISSUE TITLE
sdp-attr-substitute flag results in duplicate attribute instead of substitution

### ISSUE THREAD

**Issue by gedia** [sipwise/rtpengine#1730]
Hello all,

I tested this against rtpengine 11.5.1.3-1~bpo11+1

I seems using sdp-attr-substitute flags fails to properly replace the attribute, adding a new value instead. Here's a dump from rtpengine logs:

[control] Dump for 'answer' from 172.30.154.1:58148:
```
{   "supports": [ "load limit" ],
    "sdp": "v=0
            o=- 2017319236 2017319237 IN IP4 172.28.152.1
            s=modCOM v2 Media Gateway
            c=IN IP4 172.28.152.1
            t=0 0
            m=audio 16626 RTP/AVP 9 101
            a=rtpmap:9 G722/8000
            a=rtpmap:101 telephone-event/8000
            a=fmtp:101 0-16
            a=ptime:20
            a=sendrecv",
    "ICE": "remove",
    "direction": [ "internal", "external" ],
    "flags": [ "trust-address", "sdp-attr-substitute-audio-fmtp:101..0-16>fmtp:101..0-15,32,36" ],
    "replace": [ "origin", "session-connection", "SDP-version" ],
    "rtcp-mux": [ "demux" ],
    "call-id": "a92cac0b-aa6e-4182-b377-ccdfb6902ffd",
    "received-from": [ "IP4", "172.28.152.1" ],
    "from-tag": "GAKTVPFrZfb3kt23",
    "to-tag": "fdab0da9-2ee8-4419-afbb-0c28a4cac607",
    "command": "answer"
}
```
[control] Response dump for 'answer' to 172.30.154.1:58148:
```
{
    "sdp": "v=0
            o=- 2017319236 2017319237 IN IP4 X.X.X.X
            s=modCOM v2 Media Gateway
            c=IN IP4 X.X.X.X
            t=0 0
            m=audio 23806 RTP/AVP 9 101
            a=fmtp:101 0-15,32,36
            a=rtpmap:9 G722/8000
            a=rtpmap:101 telephone-event/8000
            a=fmtp:101 0-16
            a=sendrecv
            a=rtcp:23807
            a=ptime:20",
    "result": "ok"
}
```
According to ng control protocol documentation, the flag `"sdp-attr-substitute-audio-fmtp:101..0-16>fmtp:101..0-15,32,36"` should replace `a=fmtp:101 0-16` with `a=fmtp:101 0-15,32,36`. Instead what happens is that both values are present in rtpengine's response to the client (an instance of kamailio 5.6.2 in my case).

This looks like a bug to me, but do let me know if I'm using it wrong. Thanks!

BR,
George

**Comment by zenichev** [comment]
Hi @gedia, I think there is a bit of mess in our doc in regards of how to use the substitution part of the sdp-attr manipulations.
This relates to the way of syntax used by you. I should look into that and actualize it.

For now try to use the full syntax using dictionaries and lists as suggested in the doc mainly.
For example:

```
'sdp-attr' => { audio => { substitute => [['fmtp:101..0-16', 'fmtp:101..0-15,32,36']] } }
```

**Comment by gedia** [comment]
Hello @zenichev, thanks for looking into this.
> Hi @gedia, I think there is a bit of mess in our doc in regards of how to use the substitution part of the sdp-attr manipulations. This relates to the way of syntax used by you. I should look into that and actualize it.

I'm not sure the docs are to blame here. In commit 0a400e0, there seem to be tests which use the same syntax I did in the logs above. From the tests, [auto-daemon-tests.pl](https://github.com/sipwise/rtpengine/commit/0a400e05c2c1598e0ab2a9c124dc0d005c17f884#diff-dae5e700397533b28433d317dfaf3886727906ba31e32ef3e61a22892f3c2e14), line 16739:
```
flags => ['sdp-attr-substitute-audio-test1>test2'] 
```
> 
> For now try to use the full syntax using dictionaries and lists as suggested in the doc mainly. For example:
> 
> ```
> 'sdp-attr' => { audio => { substitute => [['fmtp:101..0-16', 'fmtp:101..0-15,32,36']] } }
> ```
Unfortunately I can't use the full syntax for my use case, as kamailio's rtpengine module doesn't have support for this. @rfuchs has mentioned (https://github.com/kamailio/kamailio/issues/3509) eventually supporting a JSON-esque syntax for rtpengine_manage functions, but this hasn't materialized yet. I understand this syntax was supposed to be an interim solution until this refactoring lands.

**Comment by zenichev** [comment]
@gedia Alright, I see now. I will check the syntax you've used out and see what's up here.
I'll keep you posted.

**Comment by zenichev** [comment]
Fixed in:
- 1725c92cb10c1ef1de4a0954ea8dd9cc328198f9
- 1bf894cc9e13aa71aa7d16f5b369a283dedf4779
- fff475cc455ba9c2e137dfbf97591c0194cf98b5
- 5e62bc5ee2946eca32a97d6064415165d3dc5071
- ffd0ec96c52e143750789259dcd08d35cb43c18f

**Comment by zenichev** [comment]
@gedia upgrade to `11.5.1.8+0~mr11.5.1.8` and see, if it works for you now.

**Comment by gedia** [comment]
Wow, that doesn't seem to have been as trivial a fix as I was expecting!

I'll check the new code once binaries are made available, thanks for looking into this so promptly!

**Comment by gedia** [comment]
Hello again,

It took a little longer than I anticipated, but I can now confirm that attr-substitute seems to be working as intended on rtpengine 11.5.1.9-1~bpo11+1.

I'm closing this for now, thank you for the fix!
