### ISSUE TITLE
rtprecording-engine mistmatch the metadata

### ISSUE THREAD

**Issue by vdharashive** [sipwise/rtpengine#1735]
below offer

   'offer',
   {
     'call-id': '33828659-dfbc-123c-62b6-0eb94b3c8831',
     'from-tag': 'S7856546KXZmr',
     sdp: 'v=0\r\n' +
       'o=- 7287215210909041465 7287215210909042000 IN IP4 3.3.3.190\r\n' +
       's=jambonz Siprec Client\r\n' +
       't=0 0\r\n' +
       'm=audio 44286 RTP/AVP 0 101\r\n' +
       'c=IN IP4 3.225.225.190\r\n' +
       'a=rtpmap:0 PCMU/8000\r\n' +
       'a=rtpmap:101 telephone-event/8000\r\n' +
       'a=fmtp:101 0-15\r\n' +
       'a=rtcp:44287\r\n' +
       'a=mid:1\r\n' +
       'a=sendonly\r\n' +
       'a=label:1\r\n',
     replace: [ 'origin', 'session-connection' ],
     'transport protocol': 'RTP/AVP',
     'record call': 'yes',
     DTLS: 'off',
     ICE: 'remove',
     SDES: 'off',
     flags: [ 'media handover', 'port latching' ],
     'rtcp-mux': [ 'accept' ],
     direction: [ 'public', 'public' ],
     metadata: 'syscallid:dd24c875-2183-4df4-9a58-fdb24e41a3d0|caller.aor:sip:842299|caller.number:842299|caller.host:audiocodes-sbc-prod.kore.ai|callee.aor:sip:+133933@50.19|callee.number:+13393|callee.host:50.19|'
     
     }

the metadata passed does not relate to same called in recording_metakeys table , rather it updates with any other calls meta data

**Comment by rfuchs** [comment]
Can you be more specific? I don't understand what you mean with "the metadata passed does not relate to same called in recording_metakeys table , rather it updates with any other calls meta data"

**Comment by planmans** [comment]
``https://hearthis.at/djjx/club-session-mix-dj-jx-csm339/
![Uploading Aquaman_logo_PNG5.png…]()
/
![Uploading Msn_logo_PNG1.png…]()
[Uploading Electro Organic mix house.mp3…]()
