### ISSUE TITLE
No iptables package anymore

### ISSUE THREAD

**Issue by smititelu** [sipwise/rtpengine#1739]
Hi, I saw that iptables packages is removed in this commit: eea3824725ce00e142d7a057ceb4dbec0ae4525d 

This makes our nightly build/install/test fail, because we still use iptables and not nftables for now. Can it be reverted?! Or is intended to not support iptables anymore?

Thank you,
Stefan

**Comment by rfuchs** [comment]
The package isn't needed any more even if you're still using iptables, as long as you have a kernel recent enough to support the new nftables interface.
