### ISSUE TITLE
ok answer different behaviour beetween 10.3.0.0 & 11.5.1.0

### ISSUE THREAD

**Issue by melvlt** [sipwise/rtpengine#1740]
Hello,

During a call where the offer contains a dtmf payload at 96 and the recipient hangs up with a dtmf payload at 101, we observe a difference in behavior between two versions of rtpengine :

In version 10.3.0.0+0~mr10.3.0.0 git-master-649fdb95: the dtmf payload is transmitted at 101 by rtpengine in the ok packet in response to the answer packet.

In version 11.5.1.0+0~mr11.5.1.0 git-mr11.5-3a7a2d5a: the dtmf payload is removed by rtpengine from ok in the ok package in response to the answer package.

Please find attached the pcap of exchanges between our media dispatcher kamailio and our rtpengine servers in the 2 versions.
[extracts_rtpengine.zip](https://github.com/sipwise/rtpengine/files/12999143/extracts_rtpengine.zip)

What is sent by our kamailio is identical. The only difference is the change in rtpengine version.

What do you think of this difference in behavior? Is it a regression for you?

Regards Melvyn

**Comment by rfuchs** [comment]
See #1556

I consider this an improvement as accepting a payload type that wasn't offered isn't exactly nice behaviour of a UA.
