### ISSUE TITLE
use ASAN to detect memory leaks on rtpengine-recording

### ISSUE THREAD

**Issue by pengwang7** [sipwise/rtpengine#1748]
When I use ASAN to detect memory leaks on rtpengine-recording, I cannot generate the stack of related calls.
Has anyone encountered similar problems? It seems that only the glib-related interfaces cannot be displayed.
    #0 0x7f02bf24cba8 in __interceptor_malloc (/lib64/libasan.so.5+0xefba8)
    #1 0x7f02bee7b350 in g_malloc ../glib/gmem.c:130

**Comment by pengwang7** [comment]
sorry

**Comment by pengwang7** [comment]
.

**Comment by rfuchs** [comment]
Make sure you set `G_SLICE=always-malloc` when doing tests like this, especially if you have a not-very-recent glib.

If asan isn't able to produce a good backtrace, run it through valgrind instead (without asan linked in).
