### ISSUE TITLE
After a call recording is initiated, it takes approximately 10 seconds until the recorded file has a significant size and can be played

### ISSUE THREAD

**Issue by joeygo** [sipwise/rtpengine#1749]
I have encountered a delay issue when using RTPengine's call recording feature. After a call recording is initiated, it takes approximately 10 seconds until the recorded file has a significant size and can be played. 

I have also attempted to configure the rtpengine-recording module to record files as both MP3 and WAV, but the issue remains unchanged.

This delay seems longer than expected, and I would like to understand the underlying reasons and explore potential solutions.

**Comment by rfuchs** [comment]
This is probably from the `delete-delay` setting. If you don't need that feature, you can set it to zero, and calls (and recordings) should be closed immediately.

General questions should be directed to the mailing list. The Github issue tracker is to track issues with the code.

**Comment by joeygo** [comment]
Thanks for the reply @rfuchs.
Actually, it didn't help. I tried setting the delete-delay to zero in the rtpengine.conf but the issue remains the same.

I can add more info on how I implemented this.
My clients are sending DTMFs which rtpengine notifies the kamailio server and from the kamailio I send start-record and stop-record on the call-id. That mechanism works perfectly besides the fact that the recorded file is available for playback after 10 seconds and not immediately after I send the stop-record command.
Can you think on other flags that might do the trick?

Thanks,.
Joey
