### ISSUE TITLE
called twice rtpengine_manage trigger looped media

### ISSUE THREAD

**Issue by sergey-safarov** [sipwise/rtpengine#1758]
We have a carrier that ignores the `Record-Route` and `Route` headers negotiated at the start of the dialog and sends a ReINVITE to another Kamailio server.
Second Kamailio calls `rtpengine_manage` and then relay ReINVITE message according to Route header to the first Kamailio.
The first Kamailio calls `rtpengine_manage` again and this triggers high CPU load on the server and pike of network traffic via loopback interface. Screenshot attached

![image](https://github.com/sipwise/rtpengine/assets/2562241/2519658a-cfa2-40ed-896c-5c968104ca2d)

And in the RTPEngine logs we can see in the [rtpengine.log](https://github.com/sipwise/rtpengine/files/13418491/rtpengine.log)
Here you will find
```
safarov@nout:~$ grep offer rtpengine.log
INFO: [3ebd87f3-f13d-443d-b8c1-5bcb3c2560d4]: [control] Received command 'offer' from [xxxx:xxxx:xxxx:xxxx::7]:49476
INFO: [3ebd87f3-f13d-443d-b8c1-5bcb3c2560d4]: [control] Replying to 'offer' from [xxxx:xxxx:xxxx:xxxx::7]:49476 (elapsed time 0.000201 sec)
INFO: [3ebd87f3-f13d-443d-b8c1-5bcb3c2560d4]: [control] Received command 'offer' from [xxxx:xxxx:xxxx:xxxx::6]:40415
INFO: [3ebd87f3-f13d-443d-b8c1-5bcb3c2560d4]: [control] Replying to 'offer' from [xxxx:xxxx:xxxx:xxxx::6]:40415 (elapsed time 0.000281 sec)
```

We will try make a workarround for not expected behoifour from the carrier equipemnt, but will be fine to avoid create loop on the RTPengine.
I think will be fine to return error if rtpengine_manage received own IP in the peer SDP.

**Comment by sergey-safarov** [comment]
[not-expected-reinvite.pcap.gz](https://github.com/sipwise/rtpengine/files/13418585/not-expected-reinvite.pcap.gz)

**Comment by zenichev** [comment]
@sergey-safarov hm, good catch, let me see, what we can do here.

**Comment by zenichev** [comment]
@sergey-safarov you could probably try to use the `loop protect` flag, which prevents processing of SDPs generated previously by rtpengine. Would that work for you?

Check the doc:
https://rtpengine.readthedocs.io/en/latest/ng_control_protocol.html

**Comment by sergey-safarov** [comment]
For me looks like it is an appropriate change in the Kamailio config to avoid this case.
But cannot test it now because another carrier disabled the "timer" feature and ReINVITE does not send more.
I will close it at solved.
