### ISSUE TITLE
How to write stream in real time

### ISSUE THREAD

**Issue by 2954456878** [sipwise/rtpengine#1761]
rtpengine-recording:
Currently, the stream is written to the file once every 256k. How to achieve real-time writing?
![image](https://github.com/sipwise/rtpengine/assets/88914706/2ba53211-211a-41a6-a121-b3db3a930430)
![image](https://github.com/sipwise/rtpengine/assets/88914706/248a8b3e-19cc-4b22-a9d5-762f8127ef49)

**Comment by zenichev** [comment]
It's not a bug, but a question, please re-create on the rtpengine's mailing lists.
