### ISSUE TITLE
kernelized packets visibile in user-space 

### ISSUE THREAD

**Issue by rohjac** [sipwise/rtpengine#1762]
i have installed kamailio with rtpengine on ubuntu 22.04 system with 8gb ram and the versions are as follows:
kamailio : 5.5.7
rtpengine : 11.5.1.9+0~mr11.5.1.9+omnivigil1

on establishing call the rtpengine logs are as shown:

Nov 24 11:21:51 telecom-HP-ProBook-430-G5 rtpengine[4011]: INFO: [803DCD1E-FB88-EE11-873F-C7E80122A74D@192.168.12.25/1973482320/1 port 34962]: [core] Kernelizing media stream: 192.168.12.25:5062 -> 192.168.12.20:34962 | 192.168.12.20:37136 -> 192.168.12.159:5012
Nov 24 11:21:52 telecom-HP-ProBook-430-G5 rtpengine[4011]: INFO: [803DCD1E-FB88-EE11-873F-C7E80122A74D@192.168.12.25/1370322772/1 port 37137]: [core] Confirmed peer address as 192.168.12.159:5013
Nov 24 11:21:52 telecom-HP-ProBook-430-G5 rtpengine[4011]: INFO: [803DCD1E-FB88-EE11-873F-C7E80122A74D@192.168.12.25/1370322772/1 port 37137]: [core] Kernelizing media stream: 192.168.12.159:5013 -> 192.168.12.20:37137 | 192.168.12.20:34963 -> 192.168.12.25:5063

It shows that rtpengine is enabled with kernel-mode, it is working but i am observing the packets on wireshark which is opened on the same system where kamailio and rtpengine is running, i am assuming that packets should not be seen in wireshark.

please correct me if am wrong

The iptable content is as follows:

-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N rtpengine
-A INPUT -p udp -j rtpengine
-A rtpengine -p udp -j RTPENGINE --id 0

More over the kamailio server with rtpengine is not able to handle more than 500 simultaneous calls

**Comment by rfuchs** [comment]
Your assumption is incorrect. The packets will be visible in Wireshark even if handled by the kernel module.
