### ISSUE TITLE
Does rtpengine support advertise FQDN instead of IP address?

### ISSUE THREAD

**Issue by Jakihiko** [sipwise/rtpengine#1763]
Hi 
I'm using rtpengine + kamailio as the edge proxy (media/sip),  I want to archive SDP use FQDN instead of IP address, how can I archive that? 

example: my RTPserver has **1.2.3.4**  and DNS has set A record: **rtp-server1.example.com**
here is what current SDP with IP address
```
v=0
o=Node 1 1 IN IP4 1.2.3.4 
s=Stream1
t=0 0
m=audio 5004 RTP/AVP 96
c=IN IP4 1.2.3.4
a=rtpmap:96 L24/48000/2
a=recvonly
a=ptime:1
a=ts-refclk:ptp=IEEE1588-2008:01-23-45-67-89-AB-CD-EF:127
a=mediaclk:direct=0
a=sync-time:0
```

What I need is:

```
v=0
o=Node 1 1 IN IP4 rtp-server1.example.com
s=Stream1
t=0 0
m=audio 5004 RTP/AVP 96
c=IN IP4 rtp-server1.example.com
a=rtpmap:96 L24/48000/2
a=recvonly
a=ptime:1
a=ts-refclk:ptp=IEEE1588-2008:01-23-45-67-89-AB-CD-EF:127
a=mediaclk:direct=0
a=sync-time:0
```

**Comment by rfuchs** [comment]
No sorry, not supported.

Direct questions like this to the mailing list. The Github issue tracker exists to track issues with the code.

**Comment by homepy** [comment]
It seems support FQDN in the o= line , see https://github.com/sipwise/rtpengine/commit/50f2bfbc4dc7f73a1fa215e1c80e89ccc1887d85

but the c= line, I don' t know...

**Comment by homepy** [comment]
It seems support FQDN in the o= line , see https://github.com/sipwise/rtpengine/commit/50f2bfbc4dc7f73a1fa215e1c80e89ccc1887d85

but the c= line, I don' t know...
