### ISSUE TITLE
Getting zero values on MOS score 

### ISSUE THREAD

**Issue by giofrigo** [sipwise/rtpengine#1764]
Hello sipwise

We are trying to obtain the MOS score with `measure-rtp` `mos=LQ` and set `generqte-RTCP` in the kamailio flags enabled, but we are not receiving any values.

I am executing the rtpengine like this:
`/usr/local/bin/rtpengine --config-file=none --log-stderr --measure-rtp --no-fallback --foreground  --port-min=35000 --port-max=45000 --log-level=7 --interface=xxx.xx.4.30 --listen-ng=xxx.xx.4.30:5050 --mos=LQ --mqtt-port=1883 --mqtt-host=xxx.xx.4.20 --mqtt-publish-scope=global --mqtt-publish-topic=rtpenginevoip --mqtt-publish-qos=1`

**Comment by rfuchs** [comment]
x-posted to mailing list
