### ISSUE TITLE
Wrong src.ip address in RTP package

### ISSUE THREAD

**Issue by robeyg** [sipwise/rtpengine#177]
I'm trying to replace rtpproxy by rtpengine. I'm using kamailio and rtpengine as proxy/bridge between voip clients on the internet and asterisk in local network.

This was the setup for rtpproxy
EXTRA_OPTS="-l wan.ipaddress/lan.ipaddress -m 35000 -M 44999" 

now  rtpengine setup:
INTERFACES="external/lan.ip.address!wan.ip.address internal/wan.ip.address!lan.ip.address"
(kamailio added: replace-session-connection replace-origin)

Now kamailio adds correct SDP headers in wan and lan, but still can't hear any audio.
I've noticed that RTP packages in LAN have wan.ip.address as source ip address, 
and WAN see lan.ip.adress as source ip address.
Destination ip address is correct.

Can rtpengine fix this behavior?
rtpengine version: 4.1.0.0+0~mr4.1.0.0 git-master-e5665c8

Regards, Rob.

**Comment by rfuchs** [comment]
Unless you're behind some sort of NAT, the correct options to duplicate rtpproxy's behaviour would be '-i internal/lan.ipaddress -i external/wan.ipaddress` (or maybe the other way around).

**Comment by robeyg** [comment]
If I do that, then I see in  SIP message that SDP shows wrong ip addresses: lan.ipaddress for WAN and wan.ipaddress for LAN.
with the bridge function, SIP SDP is ok.

**Comment by rfuchs** [comment]
Yeah, that's why I said "maybe the other way around." Just swap the addresses.

**Comment by robeyg** [comment]
Thanks. case closed.
