### ISSUE TITLE
Dtls fingerprint verification fails on signed certificates

### ISSUE THREAD

**Issue by szcom** [sipwise/rtpengine#1771]
Running version Version: 11.5.1.11+0~mr11.5.1.11 git-HEAD-51248ea, I am seeing DTLS fingerprint verification failures.
I suspect it involves signed Server certificates from the peer.

For example this works:
<img width="931" alt="image" src="https://github.com/sipwise/rtpengine/assets/1636682/f3161eb6-b19d-4b45-a5ea-97b1993d7739">
1 packet used to send server cert

But this does not:
<img width="908" alt="image" src="https://github.com/sipwise/rtpengine/assets/1636682/072ccd18-909b-4002-8400-ac54bdecab07">
3 packets used to send server cert, appears to be a signed cert, with root CA included.

**Comment by szcom** [comment]
I think it fails to verity CA when it is provided. So most likely ssl config, and not the rtpengine

**Comment by rfuchs** [comment]
How to reproduce?

**Comment by szcom** [comment]
One option is to build chain with CA and signed cert and execute verify_callback code on it to verify. CA will not match fingerprint of signed cert and it should fail.

**Comment by szcom** [comment]
Actually it may be use of X509_STORE_CTX_get_current_cert when we need leaf certificate available via ‎X509_STORE_CTX_get0_cert

[as in here for ex ](https://github.com/maitrungduc1410/webrtc/blob/b17d53d971a4f29b3a42b45c5a4312d32f4d8239/rtc_base/openssl_stream_adapter.cc#L1155C21-L1155C21)

**Comment by rfuchs** [comment]
So something like 8fba68f perhaps then?
