### ISSUE TITLE
Failed to send RTCP via kernel interface

### ISSUE THREAD

**Issue by 2954456878** [sipwise/rtpengine#1778]
### rtpengine version the issue has been seen with

Version: 11.5.1.18-1~bpo11+1

### Used distribution and its version

Debian 11

### Linux kernel version used

5.10.0-25-amd64

### CPU architecture issue was seen on (see `uname -m`)

x86_64

### Unexpected behaviour you saw

rtpengine[1107]: ERR: [3532cb68f63616c6c0c2df939@192.168.13.1/1c5bdc7f76e153f3/1 port 52777]: [core] Failed to send RTCP via kernel interface: Function not implemented
 rtpengine[1107]: ERR: [f29b53f1a63616c6c0c2df813@192.168.13.1/2ed1449b682561ad/1 port 44773]: [core] Failed to send RTCP via kernel interface: Function not implemented

### Steps to reproduce the problem

I'm not able to find the reason of this error，Do you have any idea to share ?

**Comment by 2954456878** [comment]
table = 0
interface = priv/192.168.13.1;pub/192.168.13.1!192.168.13.1
timeout = 120
silent-timeout = 3600
tos = 184
port-min = 29000
port-max = 60000
max-sessions = 10000
log-level = 5

**Comment by rfuchs** [comment]
x-posted to mailing list
