### ISSUE TITLE
Siprec - rtpengine missing the recording duration for which the sdp was sent as inactive 

### ISSUE THREAD

**Issue by vdharashive** [sipwise/rtpengine#1779]
### rtpengine version the issue has been seen with

11.5.1.18+0~mr11.5.1.18 git-HEAD-40d51d2c

### CPU architecture issue was seen on (see `uname -m`)

None

### Expected behaviour you didn't see

on recieving re-invite with inactive sdp rtpengine recording process is not having silence for the duration of inactive media . only recvonly recording is done 

INVITE sip:44.217.32.184;user=phone SIP/2.0
Via: SIP/2.0/UDP 35.153.90.242:5070;branch=z9hG4bKac1557092126
Max-Forwards: 70
From: <sip:172.31.146.45;user=phone>;tag=1c1627354814
To: <sip:44.217.32.184;user=phone>
Call-ID: 19209638322712202334434@35.153.90.242
CSeq: 1 INVITE
Contact: <sip:35.153.90.242:5070>;src
Supported: replaces,resource-priority,sdp-anat
Allow: REGISTER,OPTIONS,INVITE,ACK,CANCEL,BYE,NOTIFY,PRACK,REFER,INFO,SUBSCRIBE,UPDATE
Require: siprec
User-Agent: Mediant VE SBC/v.7.40A.500.357
Content-Type: multipart/mixed;boundary=boundary_ac1578
Content-Length: 2357
x-audc-call-id: 4dbdf6d85550ddaaef34d86de4f1338a

--boundary_ac1578
Content-Type: application/sdp

v=0
o=AudiocodesGW 1098579236 567485652 IN IP4 35.153.90.242
s=SBC-Call
c=IN IP4 35.153.90.242
t=0 0
m=audio 12464 RTP/AVP 0 8 111 126
c=IN IP4 35.153.90.242
a=ptime:20
a=sendonly
a=label:1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:111 OPUS/48000/2
a=fmtp:111 minptime=20; maxplaybackrate=8000; maxaveragebitrate=50000; useinbandfec=1
a=rtpmap:126 telephone-event/8000
a=fmtp:126 0-15,16
m=audio 12468 RTP/AVP 0 8 111 126
c=IN IP4 35.153.90.242
a=ptime:20
a=sendonly
a=label:2
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:111 OPUS/48000/2
a=fmtp:111 minptime=20; maxplaybackrate=8000; maxaveragebitrate=50000; useinbandfec=1
a=rtpmap:126 telephone-event/8000
a=fmtp:126 0-15,16

--boundary_ac1578
Content-Type: application/rs-metadata
Content-Disposition: recording-session

<?xml version="1.0" encoding="UTF-8"?>
<recording xmlns="urn:ietf:params:xml:ns:recording" xmlns:ac="http://AudioCodes">
  <datamode>complete</datamode>
  <group id="00000000-0000-00d7-2bb4-1f0000134ba8">
    <associate-time>2023-12-27T03:44:34</associate-time>
  </group>
  <session id="0000-0000-0000-0000-f5be9a848c0c5be5">
    <group-ref>00000000-0000-00d7-2bb4-1f0000134ba8</group-ref>
    <associate-time>2023-12-27T03:44:34</associate-time>
  </session>
  <participant id="+14158536006" session="0000-0000-0000-0000-f5be9a848c0c5be5">
    <nameID aor="+14158536006@koreoutbound.pstn.twilio.com">
        <name xml:lang="en">+14158536006</name>
    </nameID>
    <associate-time>2023-12-27T03:44:34</associate-time>
    <send>00000001-ae03-00d7-2bb4-1f0000134ba8</send>
    <recv>00000000-4484-00d7-2bb4-1f0000134ba8</recv>
  </participant>
  <participant id="472c5aa341b25e3a91463a56a4c30e85" session="0000-0000-0000-0000-f5be9a848c0c5be5">
    <nameID aor="koreadmin@50.19.121.248"></nameID>
    <associate-time>2023-12-27T03:44:34</associate-time>
    <send>00000000-4484-00d7-2bb4-1f0000134ba8</send>
    <recv>00000001-ae03-00d7-2bb4-1f0000134ba8</recv>
  </participant>
  <stream id="00000000-4484-00d7-2bb4-1f0000134ba8" session="0000-0000-0000-0000-f5be9a848c0c5be5">
    <label>1</label>
  </stream>
  <stream id="00000001-ae03-00d7-2bb4-1f0000134ba8" session="0000-0000-0000-0000-f5be9a848c0c5be5">
    <label>2</label>
  </stream>
</recording>
--boundary_ac1578--
SIP/2.0 100 Trying
Via: SIP/2.0/UDP 35.153.90.242:5070;branch=z9hG4bKac1557092126;rport=5070
From: <sip:172.31.146.45;user=phone>;tag=1c1627354814
To: <sip:44.217.32.184;user=phone>
Call-ID: 19209638322712202334434@35.153.90.242
CSeq: 1 INVITE
Content-Length: 0

SIP/2.0 200 OK
Via: SIP/2.0/UDP 35.153.90.242:5070;branch=z9hG4bKac1557092126;rport=5070
From: <sip:172.31.146.45;user=phone>;tag=1c1627354814
To: <sip:44.217.32.184;user=phone>;tag=30vKyyBgN82ag
Call-ID: 19209638322712202334434@35.153.90.242
CSeq: 1 INVITE
Contact: <sip:44.217.32.184:5060>
Content-Type: application/sdp
Content-Length: 748

v=0
o=AudiocodesGW 1098579236 567485652 IN IP4 44.217.32.184
s=SBC-Call
c=IN IP4 44.217.32.184
t=0 0
m=audio 43442 RTP/AVP 0 8 111 126
c=IN IP4 44.217.32.184
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:111 OPUS/48000/2
a=rtpmap:126 telephone-event/8000
a=fmtp:111 useinbandfec=1; maxplaybackrate=8000; maxaveragebitrate=50000; minptime=20
a=fmtp:126 0-15,16
a=rtcp:43443
a=ptime:20
a=recvonly
a=label:1
m=audio 43902 RTP/AVP 0 8 111 126
c=IN IP4 44.217.32.184
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:111 OPUS/48000/2
a=rtpmap:126 telephone-event/8000
a=fmtp:111 useinbandfec=1; maxplaybackrate=8000; maxaveragebitrate=50000; minptime=20
a=fmtp:126 0-15,16
a=rtcp:43903
a=ptime:20
a=recvonly
a=label:2
ACK sip:44.217.32.184:5060 SIP/2.0
Via: SIP/2.0/UDP 35.153.90.242:5070;branch=z9hG4bKac1804770512
Max-Forwards: 70
From: <sip:172.31.146.45;user=phone>;tag=1c1627354814
To: <sip:44.217.32.184;user=phone>;tag=30vKyyBgN82ag
Call-ID: 19209638322712202334434@35.153.90.242
CSeq: 1 ACK
Contact: <sip:35.153.90.242:5070>
User-Agent: Mediant VE SBC/v.7.40A.500.357
Content-Length: 0

INVITE sip:44.217.32.184:5060 SIP/2.0
Via: SIP/2.0/UDP 35.153.90.242:5070;branch=z9hG4bKac693964475
Max-Forwards: 70
From: <sip:172.31.146.45;user=phone>;tag=1c1627354814
To: <sip:44.217.32.184;user=phone>;tag=30vKyyBgN82ag
Call-ID: 19209638322712202334434@35.153.90.242
CSeq: 2 INVITE
Contact: <sip:35.153.90.242:5070>;src
Supported: sdp-anat
Require: siprec
User-Agent: Mediant VE SBC/v.7.40A.500.357
Content-Type: multipart/mixed;boundary=boundary_ac160
Content-Length: 2354

--boundary_ac160
Content-Type: application/sdp

v=0
o=AudiocodesGW 1098579236 567485653 IN IP4 35.153.90.242
s=SBC-Call
c=IN IP4 35.153.90.242
t=0 0
m=audio 12464 RTP/AVP 0 8 111 126
c=IN IP4 35.153.90.242
a=ptime:20
a=inactive
a=label:1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:111 OPUS/48000/2
a=fmtp:111 minptime=20; maxplaybackrate=8000; maxaveragebitrate=50000; useinbandfec=1
a=rtpmap:126 telephone-event/8000
a=fmtp:126 0-15,16
m=audio 12468 RTP/AVP 0 8 111 126
c=IN IP4 35.153.90.242
a=ptime:20
a=inactive
a=label:2
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:111 OPUS/48000/2
a=fmtp:111 minptime=20; maxplaybackrate=8000; maxaveragebitrate=50000; useinbandfec=1
a=rtpmap:126 telephone-event/8000
a=fmtp:126 0-15,16

--boundary_ac160
Content-Type: application/rs-metadata
Content-Disposition: recording-session

<?xml version="1.0" encoding="UTF-8"?>
<recording xmlns="urn:ietf:params:xml:ns:recording" xmlns:ac="http://AudioCodes">
  <datamode>complete</datamode>
  <group id="00000000-0000-00d7-2bb4-1f0000134ba8">
    <associate-time>2023-12-27T03:44:59</associate-time>
  </group>
  <session id="0000-0000-0000-0000-f5be9a848c0c5be5">
    <group-ref>00000000-0000-00d7-2bb4-1f0000134ba8</group-ref>
    <associate-time>2023-12-27T03:44:59</associate-time>
  </session>
  <participant id="+14158536006" session="0000-0000-0000-0000-f5be9a848c0c5be5">
    <nameID aor="+14158536006@koreoutbound.pstn.twilio.com">
        <name xml:lang="en">+14158536006</name>
    </nameID>
    <associate-time>2023-12-27T03:44:59</associate-time>
    <send>00000001-ae03-00d7-2bb4-1f0000134ba8</send>
    <recv>00000000-4484-00d7-2bb4-1f0000134ba8</recv>
  </participant>
  <participant id="472c5aa341b25e3a91463a56a4c30e85" session="0000-0000-0000-0000-f5be9a848c0c5be5">
    <nameID aor="koreadmin@50.19.121.248"></nameID>
    <associate-time>2023-12-27T03:44:59</associate-time>
    <send>00000000-4484-00d7-2bb4-1f0000134ba8</send>
    <recv>00000001-ae03-00d7-2bb4-1f0000134ba8</recv>
  </participant>
  <stream id="00000000-4484-00d7-2bb4-1f0000134ba8" session="0000-0000-0000-0000-f5be9a848c0c5be5">
    <label>1</label>
  </stream>
  <stream id="00000001-ae03-00d7-2bb4-1f0000134ba8" session="0000-0000-0000-0000-f5be9a848c0c5be5">
    <label>2</label>
  </stream>
</recording>
--boundary_ac160--
SIP/2.0 100 Trying
Via: SIP/2.0/UDP 35.153.90.242:5070;branch=z9hG4bKac693964475;rport=5070
From: <sip:172.31.146.45;user=phone>;tag=1c1627354814
To: <sip:44.217.32.184;user=phone>;tag=30vKyyBgN82ag
Call-ID: 19209638322712202334434@35.153.90.242
CSeq: 2 INVITE
Content-Length: 0

SIP/2.0 200 OK
Via: SIP/2.0/UDP 35.153.90.242:5070;branch=z9hG4bKac693964475;rport=5070
From: <sip:172.31.146.45;user=phone>;tag=1c1627354814
To: <sip:44.217.32.184;user=phone>;tag=30vKyyBgN82ag
Call-ID: 19209638322712202334434@35.153.90.242
CSeq: 2 INVITE
Contact: <sip:44.217.32.184:5060>
Content-Type: application/sdp
Content-Length: 748

v=0
o=AudiocodesGW 1098579236 567485652 IN IP4 44.217.32.184
s=SBC-Call
c=IN IP4 44.217.32.184
t=0 0
m=audio 43442 RTP/AVP 0 8 111 126
c=IN IP4 44.217.32.184
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:111 OPUS/48000/2
a=rtpmap:126 telephone-event/8000
a=fmtp:111 useinbandfec=1; maxplaybackrate=8000; maxaveragebitrate=50000; minptime=20
a=fmtp:126 0-15,16
a=rtcp:43443
a=ptime:20
a=inactive
a=label:1
m=audio 43902 RTP/AVP 0 8 111 126
c=IN IP4 44.217.32.184
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:111 OPUS/48000/2
a=rtpmap:126 telephone-event/8000
a=fmtp:111 useinbandfec=1; maxplaybackrate=8000; maxaveragebitrate=50000; minptime=20
a=fmtp:126 0-15,16
a=rtcp:43903
a=ptime:20
a=inactive
a=label:2
ACK sip:44.217.32.184:5060 SIP/2.0
Via: SIP/2.0/UDP 35.153.90.242:5070;branch=z9hG4bKac831077041
Max-Forwards: 70
From: <sip:172.31.146.45;user=phone>;tag=1c1627354814
To: <sip:44.217.32.184;user=phone>;tag=30vKyyBgN82ag
Call-ID: 19209638322712202334434@35.153.90.242
CSeq: 2 ACK
Contact: <sip:35.153.90.242:5070>
User-Agent: Mediant VE SBC/v.7.40A.500.357
Content-Length: 0

INVITE sip:44.217.32.184:5060 SIP/2.0
Via: SIP/2.0/UDP 35.153.90.242:5070;branch=z9hG4bKac883741655
Max-Forwards: 70
From: <sip:172.31.146.45;user=phone>;tag=1c1627354814
To: <sip:44.217.32.184;user=phone>;tag=30vKyyBgN82ag
Call-ID: 19209638322712202334434@35.153.90.242
CSeq: 3 INVITE
Contact: <sip:35.153.90.242:5070>;src
Supported: sdp-anat
Require: siprec
User-Agent: Mediant VE SBC/v.7.40A.500.357
Content-Type: multipart/mixed;boundary=boundary_ac1bf5
Content-Length: 2357

--boundary_ac1bf5
Content-Type: application/sdp

v=0
o=AudiocodesGW 1098579236 567485654 IN IP4 35.153.90.242
s=SBC-Call
c=IN IP4 35.153.90.242
t=0 0
m=audio 12464 RTP/AVP 0 8 111 126
c=IN IP4 35.153.90.242
a=ptime:20
a=sendonly
a=label:1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:111 OPUS/48000/2
a=fmtp:111 minptime=20; maxplaybackrate=8000; maxaveragebitrate=50000; useinbandfec=1
a=rtpmap:126 telephone-event/8000
a=fmtp:126 0-15,16
m=audio 12468 RTP/AVP 0 8 111 126
c=IN IP4 35.153.90.242
a=ptime:20
a=sendonly
a=label:2
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:111 OPUS/48000/2
a=fmtp:111 minptime=20; maxplaybackrate=8000; maxaveragebitrate=50000; useinbandfec=1
a=rtpmap:126 telephone-event/8000
a=fmtp:126 0-15,16

--boundary_ac1bf5
Content-Type: application/rs-metadata
Content-Disposition: recording-session

<?xml version="1.0" encoding="UTF-8"?>
<recording xmlns="urn:ietf:params:xml:ns:recording" xmlns:ac="http://AudioCodes">
  <datamode>complete</datamode>
  <group id="00000000-0000-00d7-2bb4-1f0000134ba8">
    <associate-time>2023-12-27T03:45:17</associate-time>
  </group>
  <session id="0000-0000-0000-0000-f5be9a848c0c5be5">
    <group-ref>00000000-0000-00d7-2bb4-1f0000134ba8</group-ref>
    <associate-time>2023-12-27T03:45:17</associate-time>
  </session>
  <participant id="+14158536006" session="0000-0000-0000-0000-f5be9a848c0c5be5">
    <nameID aor="+14158536006@koreoutbound.pstn.twilio.com">
        <name xml:lang="en">+14158536006</name>
    </nameID>
    <associate-time>2023-12-27T03:45:17</associate-time>
    <send>00000001-ae03-00d7-2bb4-1f0000134ba8</send>
    <recv>00000000-4484-00d7-2bb4-1f0000134ba8</recv>
  </participant>
  <participant id="472c5aa341b25e3a91463a56a4c30e85" session="0000-0000-0000-0000-f5be9a848c0c5be5">
    <nameID aor="koreadmin@50.19.121.248"></nameID>
    <associate-time>2023-12-27T03:45:17</associate-time>
    <send>00000000-4484-00d7-2bb4-1f0000134ba8</send>
    <recv>00000001-ae03-00d7-2bb4-1f0000134ba8</recv>
  </participant>
  <stream id="00000000-4484-00d7-2bb4-1f0000134ba8" session="0000-0000-0000-0000-f5be9a848c0c5be5">
    <label>1</label>
  </stream>
  <stream id="00000001-ae03-00d7-2bb4-1f0000134ba8" session="0000-0000-0000-0000-f5be9a848c0c5be5">
    <label>2</label>
  </stream>
</recording>
--boundary_ac1bf5--
SIP/2.0 100 Trying
Via: SIP/2.0/UDP 35.153.90.242:5070;branch=z9hG4bKac883741655;rport=5070
From: <sip:172.31.146.45;user=phone>;tag=1c1627354814
To: <sip:44.217.32.184;user=phone>;tag=30vKyyBgN82ag
Call-ID: 19209638322712202334434@35.153.90.242
CSeq: 3 INVITE
Content-Length: 0

SIP/2.0 200 OK
Via: SIP/2.0/UDP 35.153.90.242:5070;branch=z9hG4bKac883741655;rport=5070
From: <sip:172.31.146.45;user=phone>;tag=1c1627354814
To: <sip:44.217.32.184;user=phone>;tag=30vKyyBgN82ag
Call-ID: 19209638322712202334434@35.153.90.242
CSeq: 3 INVITE
Contact: <sip:44.217.32.184:5060>
Content-Type: application/sdp
Content-Length: 748

v=0
o=AudiocodesGW 1098579236 567485652 IN IP4 44.217.32.184
s=SBC-Call
c=IN IP4 44.217.32.184
t=0 0
m=audio 43442 RTP/AVP 0 8 111 126
c=IN IP4 44.217.32.184
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:111 OPUS/48000/2
a=rtpmap:126 telephone-event/8000
a=fmtp:111 useinbandfec=1; maxplaybackrate=8000; maxaveragebitrate=50000; minptime=20
a=fmtp:126 0-15,16
a=rtcp:43443
a=ptime:20
a=recvonly
a=label:1
m=audio 43902 RTP/AVP 0 8 111 126
c=IN IP4 44.217.32.184
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:111 OPUS/48000/2
a=rtpmap:126 telephone-event/8000
a=fmtp:111 useinbandfec=1; maxplaybackrate=8000; maxaveragebitrate=50000; minptime=20
a=fmtp:126 0-15,16
a=rtcp:43903
a=ptime:20
a=recvonly
a=label:2
ACK sip:44.217.32.184:5060 SIP/2.0
Via: SIP/2.0/UDP 35.153.90.242:5070;branch=z9hG4bKac1946884499
Max-Forwards: 70
From: <sip:172.31.146.45;user=phone>;tag=1c1627354814
To: <sip:44.217.32.184;user=phone>;tag=30vKyyBgN82ag
Call-ID: 19209638322712202334434@35.153.90.242
CSeq: 3 ACK
Contact: <sip:35.153.90.242:5070>
User-Agent: Mediant VE SBC/v.7.40A.500.357
Content-Length: 0

BYE sip:44.217.32.184:5060 SIP/2.0
Via: SIP/2.0/UDP 35.153.90.242:5070;branch=z9hG4bKac60945145
Max-Forwards: 70
From: <sip:172.31.146.45;user=phone>;tag=1c1627354814
To: <sip:44.217.32.184;user=phone>;tag=30vKyyBgN82ag
Call-ID: 19209638322712202334434@35.153.90.242
CSeq: 4 BYE
User-Agent: Mediant VE SBC/v.7.40A.500.357
Content-Length: 0

SIP/2.0 200 OK
Via: SIP/2.0/UDP 35.153.90.242:5070;branch=z9hG4bKac60945145;rport=5070
From: <sip:172.31.146.45;user=phone>;tag=1c1627354814
To: <sip:44.217.32.184;user=phone>;tag=30vKyyBgN82ag
Call-ID: 19209638322712202334434@35.153.90.242
CSeq: 4 BYE
Content-Length: 0

### Steps to reproduce the problem

originate siprec with sendonly sdp rtpengine response back with recvonly , reinvite with sdp inactive and rtpengine ack with inactive 

the inactive duration is not recorded as silence in recording file

**Comment by rfuchs** [comment]
This is the expected behaviour at the moment. Silence fill-in is only performed for mixed output media (and TLS forwarding I believe)
