### ISSUE TITLE
ICE/STUN response received, but source address didn't match remote candidate address

### ISSUE THREAD

**Issue by caruizdiaz** [sipwise/rtpengine#179]
Is happening to me from time to time now.
<pre>
v=0
o=- 559404610483634928 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS zvcPsWecjMbVccUwgfCZsyuCmNMIzdS3G8yU
m=audio 51407 UDP/TLS/RTP/SAVPF 102
c=IN IP4 x.x.x.x
a=rtcp:63684 IN IP4 x.x.x.x
a=candidate:3918727013 1 udp 2122260223 192.168.59.3 59815 typ host generation 0
a=candidate:4051717925 1 udp 2122194687 192.168.3.100 51377 typ host generation 0
a=candidate:3918727013 2 udp 2122260222 192.168.59.3 58926 typ host generation 0
a=candidate:4051717925 2 udp 2122194686 192.168.3.100 50848 typ host generation 0
a=candidate:2802908053 1 tcp 1518280447 192.168.59.3 0 typ host tcptype active generation 0
a=candidate:3204690901 1 tcp 1518214911 192.168.3.100 0 typ host tcptype active generation 0
a=candidate:2802908053 2 tcp 1518280446 192.168.59.3 0 typ host tcptype active generation 0
a=candidate:3204690901 2 tcp 1518214910 192.168.3.100 0 typ host tcptype active generation 0
a=candidate:1892174225 2 udp 1685987070 201.141.157.101 36076 typ srflx raddr 192.168.3.100 rport 50848 generation 0
a=candidate:1892174225 1 udp 1685987071 201.141.88.165 15871 typ srflx raddr 192.168.3.100 rport 51377 generation 0
a=candidate:428873421 2 udp 41819902 x.x.x.x 63684 typ relay raddr 201.141.157.101 rport 36076 generation 0
a=candidate:428873421 1 udp 41819903 x.x.x.x 51407 typ relay raddr 201.141.157.101 rport 10195 generation 0
a=ice-ufrag:ztI7O4T01/4ik4SF
a=ice-pwd:k06pFlMUAiS4hq81xptA3LWi
a=fingerprint:sha-256 67:7D:A2:D6:3D:EB:C6:D7:A3:87:77:2D:7F:F2:38:DD:AE:A8:8C:E7:EA:01:AC:88:E0:3A:92:CB:01:34:B7:F2
a=setup:active
a=mid:audio
a=sendrecv
a=rtpmap:102 opus/48000/2
a=fmtp:102 minptime=10; useinbandfec=1
a=maxptime:60
a=ssrc:2840297718 cname:15nE1Vs7WsBxlJTw
a=ssrc:2840297718 msid:zvcPsWecjMbVccUwgfCZsyuCmNMIzdS3G8yU 59cc7fce-8bfe-4dd5-aeb9-9afccab3ff3e
a=ssrc:2840297718 mslabel:zvcPsWecjMbVccUwgfCZsyuCmNMIzdS3G8yU
a=ssrc:2840297718 label:59cc7fce-8bfe-4dd5-aeb9-9afccab3ff3e
</pre>

resulting in

<pre>
Oct 30 06:26:34 nyc rtpengine[25986]: [f8f9a967-f971-1233-cd81-0401336adf01 port 30301] ICE/STUN response received, but source address didn't match remote candidate address (from 201.141.88.165:55412 on interface y.y.y.y)
</pre>

It looks like ICE retrieves candidates with two different public IPs `201.141.157.101` and `201.141.88.165`, rtpengine accepts the first one, but packets are being sent from `201.141.88.165`.

Any thoughts?

**Comment by rfuchs** [comment]
Hmm, same foundation and same local address, but two different NAT'd addresses? How does that happen?

**Comment by rfuchs** [comment]
I would say that rtpengine is correct in rejecting the packet. Port 30301 is the RTCP stream, which is component number 2 and is supposed to come from 201.141.157.101

**Comment by caruizdiaz** [comment]
I thought the same. I checked my public IPs and it varies from one page to another. I've never seen this before either. Should I blame my ISP and close the ticket?

**Comment by rfuchs** [comment]
Sounds good to me :)

**Comment by caruizdiaz** [comment]
I just tried the same scenario backwards, initiating the call. This time rtpengine wasn't in the media path and FreeSwitch was. Audio flowed normally between endpoints.

How do I interpret this?

**Comment by rfuchs** [comment]
You'd have to look at what ICE was doing. I would say that even if the srflx candidates fail to be negotiated, the relay candidates should still work.

**Comment by caruizdiaz** [comment]
Not sure how to do that with FS. 

INVITE sent:

<pre>
v=0
o=- 1418613678984742191 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS 5bwQYhcVfHsqyv7JzIC2Apxu3jU3HcltWT1c
m=audio 53878 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 126
c=IN IP4 z.z.z.z
a=rtcp:57521 IN IP4 z.z.z.z
a=candidate:3918727013 1 udp 2122260223 192.168.59.3 57452 typ host generation 0
a=candidate:4051717925 1 udp 2122194687 192.168.3.100 54892 typ host generation 0
a=candidate:3918727013 2 udp 2122260222 192.168.59.3 54507 typ host generation 0
a=candidate:4051717925 2 udp 2122194686 192.168.3.100 54375 typ host generation 0
a=candidate:2802908053 1 tcp 1518280447 192.168.59.3 0 typ host tcptype active generation 0
a=candidate:3204690901 1 tcp 1518214911 192.168.3.100 0 typ host tcptype active generation 0
a=candidate:2802908053 2 tcp 1518280446 192.168.59.3 0 typ host tcptype active generation 0
a=candidate:3204690901 2 tcp 1518214910 192.168.3.100 0 typ host tcptype active generation 0
a=candidate:1892174225 1 udp 1685987071 201.141.88.165 56886 typ srflx raddr 192.168.3.100 rport 54892 generation 0
a=candidate:1892174225 2 udp 1685987070 201.141.157.101 59977 typ srflx raddr 192.168.3.100 rport 54375 generation 0
a=candidate:1892174225 1 udp 1685987071 201.141.157.101 18248 typ srflx raddr 192.168.3.100 rport 54892 generation 0
a=candidate:428873421 2 udp 41819902 z.z.z.z 57521 typ relay raddr 201.141.157.101 rport 59977 generation 0
a=candidate:1892174225 2 udp 1685987070 201.141.88.165 17835 typ srflx raddr 192.168.3.100 rport 54375 generation 0
a=candidate:428873421 1 udp 41819903 z.z.z.z 53878 typ relay raddr 201.141.88.165 rport 56886 generation 0
a=ice-ufrag:yIVKqGgArG5a4dHI
a=ice-pwd:5kftAWqj6e9HPmedzM64CUgR
a=fingerprint:sha-256 67:7D:A2:D6:3D:EB:C6:D7:A3:87:77:2D:7F:F2:38:DD:AE:A8:8C:E7:EA:01:AC:88:E0:3A:92:CB:01:34:B7:F2
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
a=ssrc:1381649679 cname:es/dFXl1XL826j5H
a=ssrc:1381649679 msid:5bwQYhcVfHsqyv7JzIC2Apxu3jU3HcltWT1c d356a077-9f48-4162-a351-b13c18145d3f
a=ssrc:1381649679 mslabel:5bwQYhcVfHsqyv7JzIC2Apxu3jU3HcltWT1c
a=ssrc:1381649679 label:d356a077-9f48-4162-a351-b13c18145d3f
</pre>

Reply sent by FS

<pre>
   v=0
   o=FreeSWITCH 1446190125 1446190126 IN IP4 x.x.x.x
   s=FreeSWITCH
   c=IN IP4 x.x.x.x
   t=0 0
   a=msid-semantic: WMS GpsC8zrQvQbAHLN3qOCMV0RxuRRnGVud
   m=audio 32288 UDP/TLS/RTP/SAVPF 111 126 106
   a=rtpmap:111 opus/48000/2
   a=fmtp:111 useinbandfec=1; cbr=1; minptime=10
   a=rtpmap:126 telephone-event/8000
   a=rtpmap:106 CN/8000
   a=ptime:20
   a=fingerprint:sha-256 09:8E:AE:43:CE:81:2B:91:DE:C8:B9:79:AE:EC:D0:1E:3B:B8:E8:64:2B:ED:F8:E3:50:16:26:88:FF:D9:6D:6D
   a=setup:active
   a=rtcp-mux
   a=rtcp:32288 IN IP4 x.x.x.x
   a=ice-ufrag:gxl1n3pHL6VhSflT
   a=ice-pwd:SQTUDzi7g59yx47DrjvFdKdO
   a=candidate:3114024067 1 udp 659136 x.x.x.x 32288 typ host generation 0
   a=ssrc:1472684445 cname:bMF9cXPxEQXbsB4I
   a=ssrc:1472684445 msid:GpsC8zrQvQbAHLN3qOCMV0RxuRRnGVud a0
   a=ssrc:1472684445 mslabel:GpsC8zrQvQbAHLN3qOCMV0RxuRRnGVud
   a=ssrc:1472684445 label:GpsC8zrQvQbAHLN3qOCMV0RxuRRnGVuda0
</pre>

**Comment by rfuchs** [comment]
I must be seeing double. Duplicate ICE candidates in the offer?

```
a=candidate:1892174225 1 udp 1685987071 201.141.88.165 56886 typ srflx raddr 192.168.3.100 rport 54892 generation 0
a=candidate:1892174225 1 udp 1685987071 201.141.157.101 18248 typ srflx raddr 192.168.3.100 rport 54892 generation 0
a=candidate:1892174225 2 udp 1685987070 201.141.157.101 59977 typ srflx raddr 192.168.3.100 rport 54375 generation 0
a=candidate:1892174225 2 udp 1685987070 201.141.88.165 17835 typ srflx raddr 192.168.3.100 rport 54375 generation 0
```

Also, FreeSwitch is accepting the rtcp-mux, which may alleviate the problem. You can try doing that with rtpengine with, say, rtcp-mux-accept or rtcp-mux-demux

**Comment by caruizdiaz** [comment]
Adding  `rtcp-mux-accept` and `rtcp-mux-demux` fixed the problem <3. 

Any penalties in performance we should know about for adding these two params to the offer?

Luckily, I didn't give up so quickly so we now know a new use case that rtpengine is able to handle :).

**Comment by caruizdiaz** [comment]
False alarm. It failed again after the third test :(

**Comment by rfuchs** [comment]
Yeah, it probably randomly depends on which NAT IP address you get each time. If it works each and every time with FreeSwitch, I can only guess that it's less strict with verifying the source address of each packet, something it shouldn't do according to the RFC. You can try verifying that with a packet dump.

**Comment by caruizdiaz** [comment]
I'll do that, thank you!

I will update the ticket while I find things during my investigation.

**Comment by caruizdiaz** [comment]
The only thing that worked was disabling the control in `ice.c`. Can this be an option that can be enabled with a flag?

I'm just thinking that following exactly the RFC is what everyone does in the ideal world, but this is hardly what happens. The ultimate goal of rtpengine is to relay media traffic which in those cases, won't be possible because of faulty implementations running out there. 

Rtpengine is an amazing piece of software and maybe we should add this (apparently harmless) permissive behavior to its already flexible infrastructure.

**Comment by rfuchs** [comment]
I'm certainly open to that idea if it can be confirmed that this is what other implementations are doing and that there aren't any negative side effects to doing so.

**Comment by caruizdiaz** [comment]
Awesome. 

On my side, I modified my rtpengine instances to disable this check, and I'll see if everything holds together after this change.

Thank you.
