### ISSUE TITLE
Error! Bad return status for module build on kernel:

### ISSUE THREAD

**Issue by faratell** [sipwise/rtpengine#1790]
hello.
Iam tried to install RTPEngine  mr7.4.1 on ubuntu 18.04 but when i run dpkg -i *.deb have this error:
depmod...

DKMS: install completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j8 KERNELRELEASE=5.4.0-150-generic -C /lib/modules/5.4.0-150-generic/build M=/var/lib/dkms/ngcp-rtpengine/7.4.1.7+0~mr7.4.1.7/build RTPENGINE_VERSION=7.4.1.7+0~mr7.4.1.7...(bad exit status: 2)
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/ngcp-rtpengine-kernel-dkms.0.crash'
Error! Bad return status for module build on kernel: 5.4.0-150-generic (x86_64)
Consult /var/lib/dkms/ngcp-rtpengine/7.4.1.7+0~mr7.4.1.7/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j8 KERNELRELEASE=5.4.0-84-generic -C /lib/modules/5.4.0-84-generic/build M=/var/lib/dkms/ngcp-rtpengine/7.4.1.7+0~mr7.4.1.7/build RTPENGINE_VERSION=7.4.1.7+0~mr7.4.1.7...(bad exit status: 2)
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/ngcp-rtpengine-kernel-dkms.0.crash'
Error! Bad return status for module build on kernel: 5.4.0-84-generic (x86_64)
Consult /var/lib/dkms/ngcp-rtpengine/7.4.1.7+0~mr7.4.1.7/build/make.log for more information.
Job for ngcp-rtpengine-daemon.service failed because the control process exited with error code.
See "systemctl status ngcp-rtpengine-daemon.service" and "journalctl -xe" for details.
invoke-rc.d: initscript ngcp-rtpengine-daemon, action "restart" failed.
● ngcp-rtpengine-daemon.service - NGCP RTP/media Proxy Daemon
   Loaded: loaded (/lib/systemd/system/ngcp-rtpengine-daemon.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2024-02-05 15:10:22 +0330; 14ms ago
  Process: 8681 ExecStopPost=/usr/sbin/ngcp-rtpengine-iptables-setup stop (code=exited, status=0/SUCCESS)
  Process: 8679 ExecStart=/usr/sbin/rtpengine -f -E --no-log-timestamps --pidfile /run/ngcp-rtpengine-daemon.pid --config-file /etc/rtpengine/rtpengine.conf --table $TABLE (code=exited, status=255)
  Process: 8664 ExecStartPre=/usr/sbin/ngcp-rtpengine-iptables-setup start (code=exited, status=0/SUCCESS)
 Main PID: 8679 (code=exited, status=255)

فوریه 05 15:10:21 faraz-System-Product-Name systemd[1]: Starting NGCP RTP/media Proxy Daemon...
فوریه 05 15:10:21 faraz-System-Product-Name rtpengine[8679]: CRIT: Fatal error: Bad command line: No such file or directory
فوریه 05 15:10:21 faraz-System-Product-Name rtpengine[8679]: CRIT: Fatal error: Bad command line: No such file or directory
فوریه 05 15:10:21 faraz-System-Product-Name systemd[1]: ngcp-rtpengine-daemon.service: Main process exited, code=exited, status=255/n/a
فوریه 05 15:10:22 faraz-System-Product-Name systemd[1]: ngcp-rtpengine-daemon.service: Failed with result 'exit-code'.
فوریه 05 15:10:22 faraz-System-Product-Name systemd[1]: Failed to start NGCP RTP/media Proxy Daemon.
Setting up ngcp-rtpengine-kernel-source (7.4.1.7+0~mr7.4.1.7) ...
Setting up ngcp-rtpengine-recording-daemon (7.4.1.7+0~mr7.4.1.7) ...
Setting up ngcp-rtpengine-utils (7.4.1.7+0~mr7.4.1.7) ...
Setting up ngcp-rtpengine (7.4.1.7+0~mr7.4.1.7) ...
Processing triggers for systemd (237-3ubuntu10.57) ...
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
can anyone hepl me to solve it?

**Comment by rfuchs** [comment]
This is an ancient and unsupported version of rtpengine. Try something newer.

**Comment by faratell** [comment]
Thanks. I tried to install version mr11.3 but can not install dependencies dh-sequence-dkms. how can solve it?

**Comment by faratell** [comment]
i have solved it by this instaruction:
To install dh-dkms on Ubuntu 18.04, you can follow these steps:
1.	Download the dh-dkms package from the link provided: [dh-dkms_3.0.10-7_all.deb](https://answers.launchpad.net/ubuntu/lunar/amd64/dh-dkms/3.0.10-7).
2.	Install the package using the dpkg command:
bash
sudo dpkg -i dh-dkms_3.0.10-7_all.deb
3.	Verify the installation by checking the status of the package:
bash
dpkg -l | grep dh-dkms

**Comment by faratell** [comment]
i tried to uninstall dh-dkms and install dkms. but when i want to install dpkg -i  ngcp-rtpengine-daemon_11.3.2.0+0~mr11.3.2.0_amd64.deb  have this error: 
ngcp-rtpengine-daemon pre-depends on init-system-helpers (>= 1.54~)
  init-system-helpers is installed, but is version 1.51.

dpkg: error processing archive ngcp-rtpengine-daemon_11.3.2.0+0~mr11.3.2.0_amd64.deb (--install):
 pre-dependency problem - not installing ngcp-rtpengine-daemon
Errors were encountered while processing:
 ngcp-rtpengine-daemon_11.3.2.0+0~mr11.3.2.0_amd64.deb
 how can i fix it on ubuntu 18.04?

**Comment by faratell** [comment]
Hello. I have encountered another error when run dpkg -i *.deb. it depends on the dkms but i installed dh-dkms (according to dpkg-checkbuilddeps).
dpkg -i *.deb
(Reading database ... 232170 files and directories currently installed.)
Preparing to unpack ngcp-rtpengine_11.3.2.0+0~mr11.3.2.0_all.deb ...
Unpacking ngcp-rtpengine (11.3.2.0+0~mr11.3.2.0) over (11.3.2.0+0~mr11.3.2.0) ...
dpkg: regarding ngcp-rtpengine-daemon_11.3.2.0+0~mr11.3.2.0_amd64.deb containing ngcp-rtpengine-daemon, pre-dependency problem:
 ngcp-rtpengine-daemon pre-depends on init-system-helpers (>= 1.54~)
  init-system-helpers is installed, but is version 1.51.

dpkg: error processing archive ngcp-rtpengine-daemon_11.3.2.0+0~mr11.3.2.0_amd64.deb (--install):
 pre-dependency problem - not installing ngcp-rtpengine-daemon
Preparing to unpack ngcp-rtpengine-iptables_11.3.2.0+0~mr11.3.2.0_amd64.deb ...
Unpacking ngcp-rtpengine-iptables (11.3.2.0+0~mr11.3.2.0) over (11.3.2.0+0~mr11.3.2.0) ...
Preparing to unpack ngcp-rtpengine-kernel-dkms_11.3.2.0+0~mr11.3.2.0_all.deb ...
Unpacking ngcp-rtpengine-kernel-dkms (11.3.2.0+0~mr11.3.2.0) over (11.3.2.0+0~mr11.3.2.0) ...
Preparing to unpack ngcp-rtpengine-recording-daemon_11.3.2.0+0~mr11.3.2.0_amd64.deb ...
Unpacking ngcp-rtpengine-recording-daemon (11.3.2.0+0~mr11.3.2.0) over (11.3.2.0+0~mr11.3.2.0) ...
Preparing to unpack ngcp-rtpengine-utils_11.3.2.0+0~mr11.3.2.0_all.deb ...
Unpacking ngcp-rtpengine-utils (11.3.2.0+0~mr11.3.2.0) over (11.3.2.0+0~mr11.3.2.0) ...
dpkg: dependency problems prevent configuration of ngcp-rtpengine:
 ngcp-rtpengine depends on ngcp-rtpengine-daemon (>= 11.3.2.0+0~mr11.3.2.0); however:
  Version of ngcp-rtpengine-daemon on system is 7.4.1.7+0~mr7.4.1.7.

dpkg: error processing package ngcp-rtpengine (--install):
 dependency problems - leaving unconfigured
Setting up ngcp-rtpengine-iptables (11.3.2.0+0~mr11.3.2.0) ...
dpkg: dependency problems prevent configuration of ngcp-rtpengine-kernel-dkms:
 ngcp-rtpengine-kernel-dkms depends on dkms (>= 2.1.0.0); however:
  Package dkms is not installed.

dpkg: error processing package ngcp-rtpengine-kernel-dkms (--install):
 dependency problems - leaving unconfigured
Setting up ngcp-rtpengine-recording-daemon (11.3.2.0+0~mr11.3.2.0) ...
chown: invalid user: ‘rtpengine:rtpengine’
dpkg: error processing package ngcp-rtpengine-recording-daemon (--install):
 installed ngcp-rtpengine-recording-daemon package post-installation script subprocess returned error exit status 1
Setting up ngcp-rtpengine-utils (11.3.2.0+0~mr11.3.2.0) ...
Processing triggers for systemd (237-3ubuntu10.57) ...
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Errors were encountered while processing:
 ngcp-rtpengine-daemon_11.3.2.0+0~mr11.3.2.0_amd64.deb
 ngcp-rtpengine
 ngcp-rtpengine-kernel-dkms
 ngcp-rtpengine-recording-daemon


 for installing dkms it is forced that ubinstall dh-dkms.

**Comment by faratell** [comment]
i tried to uninstall dh-dkms and install dkms. but when i want to install dpkg -i ngcp-rtpengine-daemon_11.3.2.0+0mr11.3.2.0_amd64.deb have this error:
ngcp-rtpengine-daemon pre-depends on init-system-helpers (>= 1.54)
init-system-helpers is installed, but is version 1.51.


for solvong it i uninstall  version 1.51 and install a newer version by this instruction:

wget http://ftp.kr.debian.org/debian/pool/main/i/init-system-helpers/init-system-helpers_1.60_all.deb
sudo apt install ./init-system-helpers_1.60_all.deb

**Comment by faratell** [comment]
Now I have the same error of my first command on version 7.4.
xt_RTPENGINE:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.15.0-213-lowlatency/updates/dkms/

depmod...

DKMS: install completed.
Building initial module for 5.4.0-150-generic
Done.

xt_RTPENGINE:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.0-150-generic/updates/dkms/

depmod...

DKMS: install completed.
Job for ngcp-rtpengine-daemon.service failed because the control process exited with error code.
See "systemctl status ngcp-rtpengine-daemon.service" and "journalctl -xe" for details.
invoke-rc.d: initscript ngcp-rtpengine-daemon, action "restart" failed.
● ngcp-rtpengine-daemon.service - NGCP RTP/media Proxy Daemon
   Loaded: loaded (/lib/systemd/system/ngcp-rtpengine-daemon.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2024-02-07 11:19:18 +0330; 13ms ago
  Process: 6427 ExecStopPost=/usr/sbin/ngcp-rtpengine-iptables-setup stop (code=exited, status=0/SUCCESS)
  Process: 6425 ExecStart=/usr/bin/rtpengine -f -E --no-log-timestamps --pidfile /run/rtpengine/ngcp-rtpengine-daemon.pid --config-file /etc/rtpengine/rtpengine.conf (code=exited, status=218/CAPABILITIES)
  Process: 6403 ExecStartPre=/usr/sbin/ngcp-rtpengine-iptables-setup start (code=exited, status=0/SUCCESS)
 Main PID: 6425 (code=exited, status=218/CAPABILITIES)

فوریه 07 11:19:18 faraz-System-Product-Name systemd[1]: Starting NGCP RTP/media Proxy Daemon...
فوریه 07 11:19:18 faraz-System-Product-Name ngcp-rtpengine-iptables-setup[6403]: modprobe: FATAL: Module xt_RTPENGINE not found in directory /lib/modules/4.15.0-213-lowlatency
فوریه 07 11:19:18 faraz-System-Product-Name systemd[6425]: ngcp-rtpengine-daemon.service: Failed to apply ambient capabilities (before UID change): Operation not permitted
فوریه 07 11:19:18 faraz-System-Product-Name systemd[6425]: ngcp-rtpengine-daemon.service: Failed at step CAPABILITIES spawning /usr/bin/rtpengine: Operation not permitted
فوریه 07 11:19:18 faraz-System-Product-Name systemd[1]: ngcp-rtpengine-daemon.service: Main process exited, code=exited, status=218/CAPABILITIES
فوریه 07 11:19:18 faraz-System-Product-Name systemd[1]: ngcp-rtpengine-daemon.service: Failed with result 'exit-code'.
فوریه 07 11:19:18 faraz-System-Product-Name systemd[1]: Failed to start NGCP RTP/media Proxy Daemon.
Setting up ngcp-rtpengine-recording-daemon (11.3.2.0+0~mr11.3.2.0) ...
Failed to restart ngcp-rtpengine-recording-daemon.service: Unit ngcp-rtpengine-recording-nfs-mount.service is masked.
