### ISSUE TITLE
RTCP feedback TMMBR

### ISSUE THREAD

**Issue by hnimminh** [sipwise/rtpengine#1798]
I would like to ask if rtpengine supports RTCP feedback (TMMBR) in audio calls?

Additional Information: TMMBR is supported by Linphone, link for reference https://wiki.linphone.org/xwiki/wiki/public/view/FAQ/How%20does%20adaptive%20bitrate%20algorithm%20work%20%3F/

**Comment by rfuchs** [comment]
Questions should be directed to the mailing list
