### ISSUE TITLE
Surprises with multi-destination call

### ISSUE THREAD

**Issue by krieger-od** [sipwise/rtpengine#180]
In our VoIP system setup, rtpengine offers are generated in branch_route after lookup() to serve parallel calls to different kinds of endpoints.
Making some changes, I have occasionally dropped one recently-added (randomly added, to be honest) conditional in reply_route:

```
if ($rs == 200) {
        rtpengine_manage(...);
```

so that it became just `rtpengine_manage(...);`
And this took me to long painful journey into the land of broken calls. When there are several registrations on the called party, the established call is dropped after 30 seconds of perfectly working media. It happens because rtpengine_manage() from reply_route catches "487 Request Terminated" (as those parties get CANCEL and reply with 487 to INVITE) and performs as rtpengine_delete().
I rejected to believe that rtpengine could be so dumb or malicious that it would just kill the whole call when it sees that only certain branches get shut down.
Then I've realized this, matching tags mentioned in rtpengine logs.
Then I've met via-branch flag description in Kamailio's rtpengine module doc:

> When sending a subsequent “delete” command to the RTP proxy, you can then stop just the session for a specific branch when passing the flag '1' or '2' in the “rtpengine_delete”, or stop all sessions for a call when not passing one of those two flags there. This is especially useful if you have serially forked call scenarios where the RTP proxy gets an “offer” command for a new branch, and then a “delete” command for the previous branch, which would otherwise delete the full call, breaking the subsequent “answer” for the new branch.

Which would otherwise delete the full call, Karl!

But
- via-branch=auto simply doesn't work due to trivial bug - it falls into the case at line 1875 of modules/rtpengine/rtpengine.c , always giving us "can't get Via branch/extra ID"
- via-branch=1 for request handling, and =2 for replies, which is told to be the behaviour of =auto, gives no difference to no via-branch flag at all.
- via-branch=1 everywhere - the same as previous, makes no difference to the situation, calls still get dropped.

Then I realized that the condition "if ($rs == 200)" saved me from rtpengine_delete() being triggered at all, and I decided to add it back and go this way. The only thing that concerns me - can there be resources leak in such case (I hope no).

But I'm not writing this not to accuse you, but to propose you to reconsider default behaviour:
1) the whole call shouldn't be dropped when single branch fails and others are alive;
2) rtpengine should distinguish call branches correctly as needed without special flag.
Of course, if this all won't break other usecases.

Via-branch option real behaviour makes me think that many adopters of rtpengine may run into same issue, and they won't be able to recognize and fix it easily, unless rpengine doc will be extended with more versatile examples - the present one doesn't cover this http://kamailio.org/docs/modules/devel/modules/rtpengine.html#idp17124544

**Comment by rfuchs** [comment]
Two things here. The "delete" function can either send only the from-tag, or both the from-tag and the to-tag. If both are specified, the only that particular call leg will be deleted, otherwise all branches created from the from-tag will be deleted (usually the whole call). See the docs for the module.

The via-branch handling works correctly to anticipate branch creation in rtpengine, but there can be a problem with how Kamailio handles the via/branch header. The details depend on your Kamailio config and where branch creation happens exactly. There's some discussion about this here http://lists.sip-router.org/pipermail/sr-users/2014-October/085414.html and here http://lists.sip-router.org/pipermail/sr-users/2015-May/088399.html
