### ISSUE TITLE
dtls-mtu param does not have any effect on RTPEngine

### ISSUE THREAD

**Issue by tculjaga** [sipwise/rtpengine#1806]
### rtpengine version the issue has been seen with

Version: 9.5.1.1-1.el8

### Used distribution and its version

Rocky linux 9

### Linux kernel version used

4.18.0-372.32.1.el8_6.x86_64

### CPU architecture issue was seen on (see `uname -m`)

x86_64

### Expected behaviour you didn't see

RTPEngine is returning a DTLS Server Hello packet that is 1397 bytes. When i set dtls-mtu to 1200 i should see DTLS Server Hello packet fragmented but this is not the case. RTPEngine still sends the same packet size.

while DTLS handshake works well in my pcap, on VPN network where the transport as a limited MTU (below 1350) we are unable to place calls.
![image](https://github.com/sipwise/rtpengine/assets/6218342/d97314f7-62e3-4c6a-9abd-32a2f83a82b3)

### Steps to reproduce the problem

in rtpengine.conf confiugure dtls-mtu = 1200 and restart. 

place a WebRTC call and RTPEngine will respond with a DTLS Server Hello packet that is larger than what was configured.

**Comment by rfuchs** [comment]
Could be related to your OpenSSL version?

**Comment by tculjaga** [comment]
hm, i got OpenSSL 1.1.1k on the server. When was this feature introduced ?

**Comment by rfuchs** [comment]
> hm, i got OpenSSL 1.1.1k on the server. When was this feature introduced ? Do we need to do anything specific on the underlaying OS for this to work ?

I'm not sure about the specifics (but it does look like 1.1.1 should work), but it does depend on the build environment as well. If the package was built with an older version of OpenSSL then the feature won't work, even if the runtime version is newer.

**Comment by tculjaga** [comment]
good point!

i have built rpms on centos back in 2017 and definitely we didn't have 1.1.1 at that time :)
Now i re-built the RPMs having 1.1.1k for the same version and for the latest [mr12.2.1.4].

Need to do non regression tests and finally test it in this specific scenario.

**Comment by tculjaga** [comment]
Sadly, 9.5.1.1 built with openssl 1.1.1k still doesn't return fragmented DTLS packets.
![image](https://github.com/sipwise/rtpengine/assets/6218342/250463ee-1124-49a3-937d-4d0e1dd0c5f1)

Im preparing 11.4.1.8 for test... anything above 11.4.1.8 (that still have iptables support) fails building. The linker segfaults on me (collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped)

I failed to start 12.2.1.4 (rtpengine[1783]: CRIT: [core] Fatal error: Failed to create nftables chains or rules: error returned from netlink for iterate rules (Operation not permitted))... well, need to learn more about nftables then i can run that version.
