### ISSUE TITLE
Packet loss in rtp packets during high load

### ISSUE THREAD

**Issue by rubendsousa** [sipwise/rtpengine#181]
Hello,

we are seeing some packet loss under a high load (high number of simultaneous calls) using rtpengine. If the load is low there isn't any problem.

After activating the debug to 7 in rtpengine we have in some messages:

rtpengine[23073]: [2d2b8f0f0@192.168.197.10 port 61402] No matching local interface for destination address 192.168.197.184 found
rtpengine[23073]: [2d2b8f0f0@192.168.197.10 port 61402] Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible

Then we also see some logs with this "protocol error unknown call-id":
rtpengine[23298]: [4e73a3550@192.168.197.13] Protocol error in packet from 10.0.20.166:12885: Unknown call-id [d3:sdp283:v=0

We are running with latest rtpengine-4.2 branch (git-master-d059a6c) and using kernel module and the following command:

00:40:00 /usr/sbin/rtpengine --pidfile /var/run/rtpengine.pid --table=0 --no-fallback --interface=client/192.168.197.24 --interface=carrier/192.168.197.184 --listen-ng=10.0.20.196:7722 --listen-cli=10.0.20.196:7723 --timeout=30 --silent-timeout=60 --port-min=6000 --port-max=64000 --num-threads=16 --delete-delay=0 --tos=184 -L 0

Thank you.

**Comment by rfuchs** [comment]
Please confirm that kernel forwarding is working as expected. Check /proc/rtpengine/0/list for a plausible number of forwardings and see if the counters are increasing.

**Comment by rubendsousa** [comment]
Yes, the kernel forwarding seems to be working ok, there is sessions being deleted and new ones are being created. I also checked the /proc/rtpengine/0/status and the "Targets" are always changing.

**Comment by rfuchs** [comment]
Yes, but are the packet counters increasing? The rules might be there, but the packets might still go to userspace.

**Comment by rubendsousa** [comment]
Yes, I see them increasing, in total stats and packets and also in the RTP payload type 18 (g.729), the same number of bytes and packets are always increasing.

**Comment by rfuchs** [comment]
Then I see no reason for the error message that you posted above, which indicates that the packets went to userspace. Is the CPU maxed out? Is this a virtual machine of some sort?

**Comment by rubendsousa** [comment]
The CPU isn't maxed out. Yes, it's a virtual machine, with SR-IOV, meaning that the network card is exposed directly to the VM.

Is there any limits to the kernel module? Is there any way to check if there is calls (and what are those) being relayed in userspace instead of kernel?

**Comment by rfuchs** [comment]
The limits are primarily the CPU and how much the network stack and drivers can handle. In case of a VM it also depends on the virtualization environment of course.

The way to check kernel forwarding is explained above: the rules must be in the /proc list and the counters must be increasing. But even if packets are forwarded in userspace, there shouldn't be a problems as long as the CPU isn't maxed out. I would put the blame on the VM environment here.

**Comment by rubendsousa** [comment]
We detected there is a memory leak when we use the kernel module. Can it be related? (issue #169)

**Comment by rfuchs** [comment]
Unlikely since you see the kernel packet counters increasing. That's a definitive sign that the kernel module is handling the packets, not the userspace daemon.

**Comment by rubendsousa** [comment]
Hi, this isn't an issue after all the customer wasn't reporting it correctly. So, we don't have packet loss but we still have the issue #169.
