### ISSUE TITLE
Proposal to change this log from ERR to WARN

### ISSUE THREAD

**Issue by smititelu** [sipwise/rtpengine#1813]
### Is your feature request related to a problem? Please describe

Hello, I am forcefully trying this scenario with the purpose to printing that log:
1. start rtpengine with ```--max-recv-iters=1```
2. make a call (in my case was a call with INVITE and 183 SDP with early media playback from callee, but I think can be any regular call)

I get this logs:
```
LOG_LINE_1: ERR: [core] Too many packets in UDP receive queue (more than 1), aborting loop. Dropped packets possible
LOG_LINE_2: ERR: [core] UDP receive queue exceeded 5 times: discarding packet
```
I am wondering if RTP proxy-ing is a problem only when LOG_LINE_2 appears? If so, can LOG_LINE_1 be changed to WARN?

Thank you,
Stefan

### Describe the solution you'd like

Change the log from ERR to WARN.

### Describe alternatives you've considered

-

### The rtpengine version you checked that didn't have the feature you are asking for

latest master

**Comment by rfuchs** [comment]
You can have a dropped packet from just the first log message if there are no more packets received afterwards. But I think the severity can be reduced for both of them, and made rate-limited.
