### ISSUE TITLE
with beta chrome 47, errors SRTP output wanted, but no crypto suite was negotiated 

### ISSUE THREAD

**Issue by vance-od** [sipwise/rtpengine#182]
Hi Richard!

We have an issue, that appear with new beta Chrome 47.

The call script (the scheme is similar with issue-132):
UA-A(sip) -> Server(Kamailio+rtpengine+asterisk) -> UA-B(webrtc)

simplified call flow:
Server -> INVITE -> UA-B
Server <- 200OK <- UA-B
in browser:
--- ICEGatheringStateComplete
--- ICEConnectionStateConnected
in dump, and in rtpengine log (level 7) I see successful DTLS handshake
Server -> re-INVITE -> UA-B
Server <- 200OK <- UA-B

in log I start to see errors
SRTP output wanted, but no crypto suite was negotiated

The reason of re-INVITE is switching off custom direct-media feature 
(by default Asterisk put in first INVITE SDP - IP of UA-A, 
when UA-B answer, Asterisk re-INVITE with server's IP)

Rtpengine when receive to rewrite SDP from re-INVITE, allocate new ports and make ICE restart

rtpengine -v
4.1.0.0+0~mr4.1.0.0

Rtpengine log (debug 7) - https://gist.github.com/vance-od/d72f83a9e1466f505412

10.100.1.253 - server local ip
10.100.1.218 - pc with webrtc client

The difference in operability of Chrome 46 and 47 (what I see), that 46 start DTLS handshake after 200OK to re-INVITE, and it works OK.

Can you suggest anything? How we can renegotiate DTLS? Or some other approaches?

**Comment by rfuchs** [comment]
The ICE restart is done correctly, as the ICE parameters (ufrag) change. After the second run of ICE has been completed, DTLS should be restarted and re-negotiated. Can you confirm in a packet dump that this happens?

**Comment by vance-od** [comment]
Cannot confirm this (there is only one DTLS negotiation)

files with dump and rtpengine log sent in private mail

**Comment by rfuchs** [comment]
Please try the code from branch `rfuchs/issue182` (commit 568c8aa9c) and see if that fixes it.

**Comment by vance-od** [comment]
Thank for the commit, tried it, have troubles with build with redis, looking for the solutions, will report the result of testing and logs, asap

**Comment by rfuchs** [comment]
Yes, this is hiredis (`libhiredis-dev` on Debian). But you can also just take the single commit and apply it over whatever code base you already have.

**Comment by vance-od** [comment]
tried merging this commit to our current sources, (4.1.0)
the DTLS does not restart, trace and logs sent to mail

About hiredis - maybe it should be mentioned in Readme?

**Comment by rfuchs** [comment]
As far as I can tell, this seems to be a problem with Chrome. Chrome is in the "active" DTLS role here, meaning that it's responsible for establishing DTLS after ICE has completed. in the pcap you've sent me, it does that correctly starting with packet 1255 (in fact even before ICE has completed, but that's OK).

After the ICE restart, it should do the same, or at least after ICE has completed. In packet 1653 you can see rtpengine nominating an ICE pair, which should conclude ICE and get DTLS going. However, Chrome obviously doesn't see ICE as completed and for some reason starts sending ICE checks with the _old_ ICE credentials and the old port (from before the re-invite and ICE restart) in packet 1723, which I don't think it should do.

**Comment by vance-od** [comment]
Thank you for analyse and explanation! 
Prepared description and created bug request in Chromium bug tracker.
if someone is interested to get in touch with the discussion, the link is:
https://bugs.chromium.org/p/webrtc/issues/detail?id=5205

will report here the result asap.

**Comment by vance-od** [comment]
have an answer from chromium list:
"An ICE restart shouldn't cause a new DTLS handshake.  In other words, step 4 is wrong.  If you want to a new DTLS handshake, you need to change the DTLS fingerprint. "

Step 4 - this is about my description for the issue (4. Chrome DOES NOT make new DTLS handshake because of changed ICE.)

the resolution for my request: "Status: Invalid"

**Comment by rfuchs** [comment]
Ah, but the port has changed, which means a new DTLS connection must be established. DTLS connections are bound to individual ports.

**Comment by rfuchs** [comment]
And that doesn't even address the actual problem, which is that ICE fails to complete because it's stuck using the old ICE info.

**Comment by vance-od** [comment]
Hi Richard!

Because of setting invalid status for my request to chromium list, we were looking for the way how to cope with issue. We found a workaround:
In jssip when re-INVITE comes, we reset peer connection, and browser initialise all from the beginning (set remote/local description, make ICE exchange, DTLS handshake)

But, this leads to another issue

Legent:
UA-A, UA-C (sip phones) 
UA-B (sipjs based) - local ip - 10.100.1.218, external ip in log masked UA_real_ip
server (asterisk + kamailio/rtpengine) (server's local IP - 10.240.154.52, external ip in log masked as server_real_ip) 
rtpengine run with parameters:
 /usr/sbin/rtpengine --interface=10.240.154.52 --interface=server_real_ip --listen-ng=127.0.0.1:1026 --timeout=60 --silent-timeout=3600 --pidfile=/var/run/rtpengine.pid 
 --port-min=14001 --port-max=15000 --table=-1 --log-level=5 --log-facility=daemon --num-threads=5 --delete-delay=60

How issue appear:
UA-A call UA-B (it answer)
UA-A make blind transfer to UA-C (sip phone)

because of different codec priority in UA-A and UA-C, after transfer complete, UA-B receive re-INVITE, (in SDP changed sequence of codecs, all other as I see is the same)
here is the problem:
in SDP to browser, candidates list consist records only for local interface (in contrast in first INVITE there were candidates for both IP - local and external) 

Before our workaround, there were no issue on the Chrome's side (as I understand, when re-INVITE comes, old description continue working)
Now, when re-INVITE comes, chrome delete old description, that consist candidate with serever's real_ip, but new description does not have it.

Result - no audio, and in Chrome:
ICEConnectionStateFailed

Does our workaround is the wrong way from the beginning? Or any explanation, why rtpengine, set candidates list in different manner for initial INVITE and re-INVITE (in Kamailio rtpengine_manage is the same for both)?

or maybe I need to set parameters with IP in config in another manner? now it is:
INTERFACES="10.240.154.52 server_real_ip"

rtpengine log:
https://gist.github.com/vance-od/7ae4dc6e3ecc26c4bbed

**Comment by rfuchs** [comment]
This is due to a requirement of the ICE RFC. Specifically, at the time when the re-invite is made, from rtpengine's POV the offer is going to the same endpoint as the original one, which means that it considers ICE completed and RFC 5245 says in section 9.1.2.2:

```
   The default destination for media (i.e., the values of the IP
   addresses and ports in the m and c lines used for that media stream)
   MUST be the local candidate from the highest-priority nominated pair
   in the valid list for each component.  This "fixes" the default
   destination for media to equal the destination ICE has selected for
   media.

   The agent MUST include candidate attributes for candidates matching
   the default destination for each component of the media stream, and
   MUST NOT include any other candidates.
```

AFAICT you have several options here.

1. The proper solution would be to instruct rtpengine that the re-invite is going to a different endpoint than the one before. Endpoints are identified through their from/to-tag. Since the to-tag isn't known when the re-invite happens, the way to distinguish them is through the via-branch. If the via-branch values (or "extra pv") in the original invite is different from the one in the re-invite, then rtpengine will know that this is going to a different endpoint. The respective answers would have to contain the same via-branch value so they can be matched up with the to-tag.

2. You can try the recently added `reset` flag which partly tries to address this problem if the via-branch solution isn't feasible. I don't know off hand if it's current implementation is complete enough to actually reset the entire ICE agent, but that can easily be added.

For the previous issue, I was considering adding a port latching option, where rtpengine would retain the already allocated ports even if the remote endpoint changes. But I'm not sure if that would actually help in your particular case.

**Comment by vance-od** [comment]
Hi Richard!

Thank you for the explanation, and suggestions!

for the first suggestion:
tried adding via-branch parameter, it is one for initial INVITE/200OK, and different for re-INVITE/200OK
(you said that when re-INVITE comes, the to-tag is unknown - this is false in my case, to-tag is set when 200OK for initial INVITE)
the from-tag is also unchanged. 

the result - changing via-branch does not help, I have the same candidates in re-INVITE, as before.
log for such call here - https://gist.github.com/vance-od/53e70b36d625e034d600
(the call scheme is the same as in my previous message, UA-A (sip) call UA-B(webrtc), UA-A make blind transfer to UA-C (sip))

for the second suggestion - I have built rtpengine from the latest master branch, used the reset flag in rtpengine_manage for re-INVITE - the result is the same (no external_ip candidates, no media).

what I could be missing? any idea?
about "adding a port latching option" - if you do it, and need qa, I'm ready to provide testing.

thank you in advance!

**Comment by rfuchs** [comment]
This log is slightly different than the one before. Neither to-tag nor via-branch change, so this obviously doesn't help.

As for the `reset` flag, try with the following patch applied.

```
diff --git a/daemon/call.c b/daemon/call.c
index 85933af..ef1358d 100644
--- a/daemon/call.c
+++ b/daemon/call.c
@@ -2571,6 +2571,10 @@ int monologue_offer_answer(struct call_monologue *other_ml, GQueue *streams,
                if (flags && flags->opmode == OP_OFFER && flags->reset) {
                        MEDIA_CLEAR(media, INITIALIZED);
                        MEDIA_CLEAR(other_media, INITIALIZED);
+                       if (media->ice_agent)
+                               ice_restart(media->ice_agent);
+                       if (other_media->ice_agent)
+                               ice_restart(other_media->ice_agent);
                }
 
                /* deduct protocol from stream parameters received */
```

**Comment by vance-od** [comment]
With this patch, it works! 
using the patch, the log for issuing call:
https://gist.github.com/vance-od/0172f7b404fb053d1490

will provide additional testing and report the results.

Are you going to merge this to master in case of successful testing?

Thanks!

**Comment by rfuchs** [comment]
With some slight modifications, yes.

**Comment by vance-od** [comment]
ok, after additional testing, will report the results.

**Comment by vance-od** [comment]
made a test series in Chrome 47, works as we expected

But here is an important point - if browser does not reset peer connection (this is what we do now, when re-INVITE comes) - when rtpengine_manage with reset flag, - browser does not accept such re-INVITE (it answers 488 Not acceptable here)
in webrtc log I see:
setRemoteDescriptionOnFailure ->>> 
Failed to set remote offer sdp: Session error code: ERROR_CONTENT. Session error description: Cryptos must be empty when DTLS is active..

Is it ok for rtpengine to use reset flag in such manner (I am in doubt that it is common to make reset peer connection, and this will be useful for other who use rtpengine)

**Comment by rfuchs** [comment]
If it complains about SDES and DTLS being used at the same time (which is the default), you can try with the flag SDES=off

**Comment by vance-od** [comment]
It is not trouble for me (b.t.w. SDES=off does not help, the issue is not here), I am pointing out how it works, if browser does not reset peer connection.

**Comment by rfuchs** [comment]
Yes I understand. The `reset` flag causes rtpengine to forget certain things it has learned about the endpoint, such as support for DTLS and SDES, and so it will offer both again even if it has previously learned that e.g. SDES isn't supported. If this is done mid-call, then I can understand how a client can get confused.
