### ISSUE TITLE
for rhel 8.9 mr11.5 there is an compilation issue

### ISSUE THREAD

**Issue by Ravuru-Hemanth-Sai** [sipwise/rtpengine#1820]
### rtpengine version the issue has been seen with

mr11.5.1.24

### Used distribution and its version

rhel 8.9

### Linux kernel version used

4.18.0-513.24.1.el8_9.x86_64

### CPU architecture issue was seen on (see `uname -m`)

x86_64

### Unexpected behaviour you saw

cc    -c -o mix_in_x64_sse2.o mix_in_x64_sse2.S
cc -rdynamic -g -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wstrict-prototypes -Werror=return-type -Wshadow -pthread -fno-strict-aliasing -std=c11 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include    -pthread  -DPCRE2_CODE_UNIT_WIDTH=8     -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread  -I/usr/local/include   -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg  -I/usr/include/ffmpeg  -I/usr/include/ffmpeg  -I/usr/include/ffmpeg  -I/usr/include/ffmpeg  -I/usr/local/include  -I/usr/include/opus  -DWITH_TRANSCODING -I/usr/include/mysql -I/usr/include/mysql/mysql -DHAVE_BCG729  -DRTPENGINE_VERSION="\"git-HEAD-7d7de304\""  -DHAVE_LIBSYSTEMD -o rtpengine main.o kernel.o helpers.o control_tcp.o call.o control_udp.o redis.o bencode.o cookie_cache.o udp_listener.o control_ng.strhash.o sdp.strhash.o stun.o rtcp.o crypto.o rtp.o call_interfaces.strhash.o dtls.o log.o cli.o graphite.o ice.o media_socket.o homer.o recording.o statistics.o cdr.o ssrc.o iptables.o tcp_listener.o codec.o load.o dtmf.o timerthread.o media_player.o jitter_buffer.o t38.o websocket.o mqtt.o janus.strhash.o audio_player.o loglib.o auxlib.o rtplib.o str.o socket.o streambuf.o ssllib.o dtmflib.o mix_buffer.o poller.o codeclib.strhash.o resample.o mvr2s_x64_avx2.o mvr2s_x64_avx512.o mix_in_x64_avx2.o mix_in_x64_avx512bw.o mix_in_x64_sse2.o -lm -ldl -lglib-2.0  -lgthread-2.0 -pthread -lglib-2.0  -lz  -lpcre2-8  -lcrypto  -lssl -lcrypto  -levent_pthreads -levent  -lpcap -lxmlrpc_client  -lxmlrpc  -lxmlrpc_util  -lhiredis -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -L/usr/local/lib -lwebsockets  -lip4tc -lip6tc  -lavcodec  -lavformat  -lavutil  -lswresample  -lavfilter  -L/usr/local/lib -lspandsp  -lopus  -L/usr/lib64/ -lmariadb -lbcg729  -lsystemd
collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
make[2]: *** [../lib/common.Makefile:7: rtpengine] Error 1
rm sdp.strhash.c control_ng.strhash.c call_interfaces.strhash.c janus.strhash.c
make[2]: Leaving directory '/usr/local/src/rtpengine/daemon'
make[1]: *** [../lib/common.Makefile:4: all] Error 2
make[1]: Leaving directory '/usr/local/src/rtpengine/daemon'
make: *** [Makefile:22: all] Error 2
copying kernel module into /lib/modules/4.18.0-513.24.1.el8_9.x86_64/updates
cp: cannot stat './kernel-module/xt_RTPENGINE.ko': No such file or directory
copying iptables extension into config xtables --variable=xtlibdir
cp: cannot stat './iptables-extension/libxt_RTPENGINE.so': No such file or directory
cp: cannot stat '/usr/local/src/rtpengine/recording-daemon/rtpengine-recording': No such file or directory
Created symlink /etc/systemd/system/multi-user.target.wants/rtpengine-recording.service → /etc/systemd/system/rtpengine-recording.service.
Job for rtpengine-recording.service failed because the control process exited with error code.
See "systemctl status rtpengine-recording.service" and "journalctl -xe" for details.

### Anything else?

for every mr11.5 version we are fasing this issue can anyone can help us to solve this
we are using this command for compiling
make KSRC=/lib/modules/4.18.0-513.24.1.el8_9.x86_64/build with_transcoding=yes with_iptables_option=yes with-kernel

**Comment by rfuchs** [comment]
> collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped

There's something very wrong with your build environment. The build isn't failing because there's something wrong with the code, it's because your compiler/linker crashes.

**Comment by henningw** [comment]
I can reproduce this with version 11.5.1.32, exactly the same error. This is a freshly installed system which was not used for something else.

```
cc -rdynamic -g -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wstrict-prototypes -Werror=return-type -Wshadow -pthread -fno-strict-aliasing -std=c11 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include    -pthread  -DPCRE2_CODE_UNIT_WIDTH=8     -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread    -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg  -I/usr/include/ffmpeg  -I/usr/include/ffmpeg  -I/usr/include/ffmpeg  -I/usr/include/ffmpeg   -I/usr/include/opus  -DWITH_TRANSCODING -I/usr/include/mysql -I/usr/include/mysql/mysql -DHAVE_MQTT  -DRTPENGINE_VERSION="\""11.5.1.32+0~mr11.5.1.32-1.el8"\"" -o rtpengine main.o kernel.o helpers.o control_tcp.o call.o control_udp.o redis.o bencode.o cookie_cache.o udp_listener.o control_ng.strhash.o sdp.strhash.o stun.o rtcp.o crypto.o rtp.o call_interfaces.strhash.o dtls.o log.o cli.o graphite.o ice.o media_socket.o homer.o recording.o statistics.o cdr.o ssrc.o iptables.o tcp_listener.o codec.o load.o dtmf.o timerthread.o media_player.o jitter_buffer.o t38.o websocket.o mqtt.o janus.strhash.o audio_player.o loglib.o auxlib.o rtplib.o str.o socket.o streambuf.o ssllib.o dtmflib.o mix_buffer.o poller.o codeclib.strhash.o resample.o mvr2s_x64_avx2.o mvr2s_x64_avx512.o mix_in_x64_avx2.o mix_in_x64_avx512bw.o mix_in_x64_sse2.o -lm -ldl -lglib-2.0  -lgthread-2.0 -pthread -lglib-2.0  -lz  -lpcre2-8  -lcrypto  -lssl -lcrypto  -levent_pthreads -levent  -lpcap -lxmlrpc_client  -lxmlrpc  -lxmlrpc_util  -lhiredis -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lwebsockets  -lip4tc -lip6tc  -lavcodec  -lavformat  -lavutil  -lswresample  -lavfilter  -lspandsp  -lopus  -L/usr/lib64/ -lmariadb -L/usr/lib -lmosquitto
collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
make[1]: *** [../lib/common.Makefile:7: rtpengine] Error 1
rm sdp.strhash.c control_ng.strhash.c call_interfaces.strhash.c janus.strhash.c
make[1]: Leaving directory '/root/rpmbuild/BUILD/ngcp-rtpengine-11.5.1.32+0~mr11.5.1.32/daemon'
make: *** [../lib/common.Makefile:4: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.as3xqE (%build)
```

Might be that the gcc and/or linker in almalinux 8.x is just to old:
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.5.0 20210514 (Red Hat 8.5.0-22) (GCC)
```

I will try to add the additional linker flags mentioned in #1846

**Comment by henningw** [comment]
The compiler/linker flags did not worked for 11.5 branch. 12.5 branch compilation worked on almalinux 8.x
