### ISSUE TITLE
DKMS Rebuild modules failed

### ISSUE THREAD

**Issue by lrh3321** [sipwise/rtpengine#1825]
### rtpengine version the issue has been seen with

_ngcp-rtpengine-12.4.0.0+0~mr12.4.0.0-1_

### Used distribution and its version

openEuler 22.03 (LTS-SP3)

### Linux kernel version used

5.10.0-197.0.0.110.oe2203sp3.aarch64

### CPU architecture issue was seen on (see `uname -m`)

aarch64

### Expected behaviour you didn't see

Rebuild success

### Unexpected behaviour you saw

```plaintext
DKMS make.log for ngcp-rtpengine-12.4.0.0+0~mr12.4.0.0-1 for kernel 5.10.0-197.0.0.110.oe2203sp3.aarch64 (aarch64)
Wed May  8 13:52:55 HKT 2024
make: Entering directory '/usr/src/kernels/5.10.0-197.0.0.110.oe2203sp3.aarch64'
  CC [M]  /var/lib/dkms/ngcp-rtpengine/12.4.0.0+0~mr12.4.0.0-1/build/xt_RTPENGINE.o
In file included from /var/lib/dkms/ngcp-rtpengine/12.4.0.0+0~mr12.4.0.0-1/build/xt_RTPENGINE.c:36:
/var/lib/dkms/ngcp-rtpengine/12.4.0.0+0~mr12.4.0.0-1/build/xt_RTPENGINE.h:5:10: fatal error: common_stats.h: No such file or directory
    5 | #include "common_stats.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [scripts/Makefile.build:286: /var/lib/dkms/ngcp-rtpengine/12.4.0.0+0~mr12.4.0.0-1/build/xt_RTPENGINE.o] Error 1
make: *** [Makefile:1850: /var/lib/dkms/ngcp-rtpengine/12.4.0.0+0~mr12.4.0.0-1/build] Error 2
make: Leaving directory '/usr/src/kernels/5.10.0-197.0.0.110.oe2203sp3.aarch64'
```

### Steps to reproduce the problem

1. build rpm packages and install
2. `dkms autoinstall`

### Anything else?

`el/rtpengine.spec`

https://github.com/sipwise/rtpengine/blob/c40c117a12cc064e2603909a2883e5ae41da025a/el/rtpengine.spec#L170-L180

Missing `common_stats.h`

```Makefile
install -D -p -m644 kernel-module/common_stats.h \
	 %{buildroot}%{_usrsrc}/%{name}-%{version}-%{release}/common_stats.h
```

**Comment by rfuchs** [comment]
Can you open a pull request with the fix? I can't easily test the RPM packaging myself.

**Comment by rfuchs** [comment]
Thank you
