### ISSUE TITLE
Removal of IPV6 candidates

### ISSUE THREAD

**Issue by soulofmischief87** [sipwise/rtpengine#184]
More of a question than an and issue here. Is it possible to remove IPv6 ICE candidates from an offer using rtpengine flags? The latest chrome on windows is adding a couple of IPv6 addresses that are breaking the Max SDP length on one of my media servers. 

Thanks in Advance.

**Comment by rfuchs** [comment]
Only by using ICE=force or ICE=remove, which removes all original candidates.

A proper solution would be to fix the network so large UDP packets are fragmented properly, or use TCP.

**Comment by soulofmischief87** [comment]
Rfuchs,

Thanks for your reply and input. The issue is the vendor has a hard coded limit on the max SDP length which is outside of fragmentation problems.
