### ISSUE TITLE
silent-timeout doesn't work on calls

### ISSUE THREAD

**Issue by devoxy1** [sipwise/rtpengine#1856]
### rtpengine version the issue has been seen with

Version: 13.0.0.0+0~mr13.0.0.0 git-master-7308a88b

### Used distribution and its version

Debian

### Linux kernel version used

6.1.50-1-generic

### CPU architecture issue was seen on (see `uname -m`)

x86_64

### Expected behaviour you didn't see

Recently we found a problem with our internal infrastructure where Kamailio didn't receive reply for rtpengine_query command before rtpengine_delete and started to throw an error that there are "no available proxies". This lead to rtpengine not closing the session and UDP sockets not being released. If rtpengine's uptime is long enough it can use all UDP sockets and server can fail, after a day we reach around 1000 zombie calls which are not valid anymore and can be dropped by restarting rtpengine or be terminated via ctl. 
After some debugging we found that rtpengine sends reply for query with packet size around 5k while on some kamailio servers we had 1500 MTU, which caused reply packets to be dropped and kamailio marking proxy unavailable and not sending delete afterwords. 

We can fix the problem by resizing mtu or enable packet fragmentation, however my question is about timeout option.
We have `timeout=60` setting enabled which, based on documentation: 

> Takes the number of seconds as argument after which a media stream should be considered dead if no media traffic has been received. If all media streams belonging to a particular call go dead, then the call is removed from rtpengine’s internal state table.

These dead sessions have no streams going on and there are no media passing through. If we remove rtpengine from balancing on kamailio, calls will go to 0, media streams on metrics page will go to 0 but Sessions will be equal to amount of all those stuck calls and these sessions are not closed by timeout option. Is this valid behavior? Seems like not, as it doesn't close sessions with no media stream as it supposed to.

### Unexpected behaviour you saw

Sessions without media streams should be closed within timeout set by `timeout` options, however they stay forever

### Steps to reproduce the problem

Set 9000 mtu on rtpengine server, set 1500 on kamailio server, setup kamailio to do rtpengine_query before rtpengine_delete. Once call is finished kamailio will send packet for query and rtpengine will reply with packet exceeding 1500 size which will be dropped by kamailio due to not being fragmented because of mtu 9000. Such call won't be deleted by kamailio and hence will stay unclosed on rtpengine

**Comment by rfuchs** [comment]
Probably already fixed by 1d18f4a0b -- please update

**Comment by devoxy1** [comment]
Will update and revert back, thanks!

**Comment by devoxy1** [comment]
Calls look good with new version, sessions are now closing fine. Thank you!
