### ISSUE TITLE
Сrash when placing a call on hold while playing media

### ISSUE THREAD

**Issue by RodionovNikolay** [sipwise/rtpengine#1858]
### rtpengine version the issue has been seen with

12.3.1.3 mr12.3.1.3

### Used distribution and its version

Red Hat Enterprise Linux 8.10 (Ootpa)

### Linux kernel version used

4.18.0-553.8.1.el8_10.x86_64

### CPU architecture issue was seen on (see `uname -m`)

x86_64

### Expected behaviour you didn't see

The agent receives an incoming call, an audio notification is played. If the agent simply accepts the call, then everything is fine.

Settings for rtpengine:
audio-player=play-media

Settings for kamailio:
event_route[dialog:start]{
        xlog("L_INFO", "dialog started, received 200OK");
        if ((is_in_profile("inbound_call") && $dlg_var(announcement) == "true" ) {
                xlog("L_INFO", "dialog in inbound_call profile, start announcement");

                                play_media("all file=/data/announcement/kazakh.wav"); # <---------------- If you put the call on hold while the media is playing, the service will crash.

		}

	}

### Unexpected behaviour you saw

If the agent puts the call on hold while the notification is playing, the service crashes 
[dump.zip](https://github.com/user-attachments/files/16926547/dump.zip)
and all incoming calls are terminated.

### Steps to reproduce the problem

You need to make an incoming call - When the audio notification is playing, you need to put the call on hold.
(if you put the call on hold after the audio notification has played, then everything will be fine with the service)

**Comment by rfuchs** [comment]
The core file isn't helpful to a 3rd party. Can you open the core in `gdb` and post the output of `bt full` ? Make sure debug packages are installed if there are any.

**Comment by rfuchs** [comment]
Tried to reproduce on current master but no luck. Have you tried 12.5?

**Comment by RodionovNikolay** [comment]
[dump.txt](https://github.com/user-attachments/files/16929747/dump.txt)
Uploaded bt full.
We will check version 12.1.5, thanks.

**Comment by rfuchs** [comment]
The line numbers from the backtrace don't really match the code in mr12.3.1.3. Is this from some modified code base?

**Comment by RodionovNikolay** [comment]
Sorry, we tried to reproduce the problem on different OS versions (RedHat 8 and 9) and on different versions of RTPEngine 11.5 and 12.2 and 12.3 - the problem persists everywhere.
In the last dump we reproduced the problem on the 11.5 test environment. 
[dump12-5.txt](https://github.com/user-attachments/files/16940585/dump12-5.txt)
Now we have updated to version 12.5, I am attaching the dump, the problem persists.

**Comment by RodionovNikolay** [comment]
[gdb-offer-answer .txt](https://github.com/user-attachments/files/16961359/gdb-offer-answer.txt)

Can you check please

**Comment by rfuchs** [comment]
See if ef00acd fixes this for you

**Comment by RodionovNikolay** [comment]
Hi! The fix works, the problem could not be reproduced! But there are some errors that cause concern.

[core] replace-session-connection flag encountered, but not supported anymore.

Is this fix expected in a major or minor version?
![screen](https://github.com/user-attachments/assets/b42e6877-5694-49eb-86db-aa707974b5fc)

**Comment by rfuchs** [comment]
> Hi! The fix works, the problem could not be reproduced! But there are some errors that cause concern.
> 
> [core] replace-session-connection flag encountered, but not supported anymore.

This is expected due to the master version and not a concern.

> Is this fix expected in a major or minor version? 

It will be backported to all supported and affected releases.
