### ISSUE TITLE
Re-resolve Redis ip-address when RE-Establishing connection for Redis server

### ISSUE THREAD

**Issue by NikolayShakin** [sipwise/rtpengine#1865]
### Is your feature request related to a problem? Please describe

When using `rtpengine` with a `redis` cluster after the redis master node has changed, the `rtpengine` loses `redis` connection even when FQDN is used as the `redis` server address and DNS record was updated.

### Describe the solution you'd like

When we try to re-establish connection to `redis` we can re-resolve IP address after every N failed tries to connect. It will not be too expensive as we lost the connection anyway. Assuming that DNS record was updated when the `redis` master node changed, it will allow `rtpengine` automatically switch to a new `redis` master node

### Describe alternatives you've considered

Restart `rtpengine` after `redis` master node change 

### The rtpengine version you checked that didn't have the feature you are asking for
`Version: 12.5.1.5-1~bpo11+1`

**Comment by guss77** [comment]
@zenichev I'm a bit confused about your statement - can you please expand on the difference between "force rtpengine to re-resolve the FQDN" and "the system provides an actual record just in-time"?

The way I understand the situation, the libnss `hosts` driver (or another mechanism that uses the local system configuration in `/etc/nsswitch.conf` or `/etc/resolv.conf` directlry) is quarried for the IP address for the host defined in the configuration. The problem the OP describes (which is very similar to the issue I have) is that first the DNS records - and hence the local system configuration (not the RTPEngine configuration file) has been updated with a new IP address for the existing host name, and only then the older server - whose IP address RTPEngine has used to connect is dropped.

The request is that when the redis connection drops, only then is RTPEngine expected to refresh its cache of the DNS results - under the assumption that the rest of the system is working correctly.

**Comment by guss77** [comment]
> > I disagree - it should be the default and only behavior: do not cache the DNS result and when a new connection needs to be opened - run the resolver again.
> 
> I'm not sure I agree. [...]. Most users won't have a need to re-resolve the host name during runtime, so expecting them to have a special DNS setup just to avoid a potential fire is not reasonable. It can be the default/only behaviour only if it creates no additional hazards.

My opinion is that static Redis installations are becoming rare, but we are talking about VoIP use cases - which are notorious for having a very long legacy tail, so :shrug: .

For myself - I'd be very happy to have a configuration option that I can toggle so I will no longer need to *restart* RTPEngine every time I deploy a security update to my Redis cluster - restarting is massively more disruptive then even a huge 100ms remote DNS lookup latency.

**Comment by NikolayShakin** [comment]
> I'm not sure I agree. Redis operations are synchronous, which makes a reconnect quite an expensive and critical situation. 
My original suggestion was to make a new DNS query only after a reasonable number of failed reconnection attempts. So these extra 100-500ms shouldn't be that bad because the system has been broken for a few seconds at this point. 

I believe that most users who don't imply changing Redis address will use IP-address instead of DNS-name in the configuration, and they will not be affected. I reckon the default behavior should implement the re-resolve feature, and the configuration option should allow disabling it. For instance, the option can define the number of failed re-connect attempts before re-resolve address, by default `5`, and `0` to disable

**Comment by zenichev** [comment]
@NikolayShakin try this out: https://github.com/zenichev/rtpengine/tree/redis_reconnect_resolve_support

To enable the newer behavior, after the rtpengine is compiled (from the given branch I sent you), add the following config line to the rtpengine.conf:
```
redis-resolve-on-reconnect = true
```

If it works fine for you, we will add this to the current master.

**Comment by NikolayShakin** [comment]
@zenichev, thanks for the fix! It works! But I noticed an issue with logs when I was testing different scenarios.
If I changed DNS record from  10.45.96.11(which rejects packets-->`Connection refused`) to 1.1.1.2 (which drops packets-->`Connection timed out`) in logs I saw 10.45.96.11, but in `tcpdump` I saw that `rtpengine` was trying to connect to a new address(1.1.1.2)
```
rtpengine[28806]: ERR: [core] Failed to connect to Redis 10.45.96.11:6379, error: Connection refused
rtpengine[28806]: INFO: [core] RE-Establishing connection for Redis server 10.45.96.11:6379
....
rtpengine[28806]: ERR: [core] Failed to connect to Redis 10.45.96.11:6379, error: Connection timed out
rtpengine[28806]: INFO: [core] RE-Establishing connection for Redis server 10.45.96.11:6379
```

**Comment by zenichev** [comment]
@NikolayShakin yeah, that's because the program doesn't know at a point of time upon logging that,
what will be the new IP address after re-resolve. I've just added changes, so it logs in this case given hostname.
You will still see in the end the new resolved IP logged with:
```
RE-Established connection to Redis '<ip_address_here>'
```

**Comment by zenichev** [comment]
It's in the master now. Let us know if you have any other complaints later.
Otherwise closing it.

**Comment by Serg1289** [comment]
Can anyone please share rtpengine.conf with connection to Redis cluster (sentinel)?
not sure what to put inside Redis=... as we have multiple Redis IPs in the cluster.

**Comment by alexbakker** [comment]
@zenichev Would backporting support for the new ``redis-resolve-on-reconnect`` option to the mr12.5.1 LTS branch be an option?
