### ISSUE TITLE
dtmf_rx_fillin-01.h compilation error

### ISSUE THREAD

**Issue by voztovoice** [sipwise/rtpengine#1866]
### rtpengine version the issue has been seen with

last Github

### Used distribution and its version

Rocky Linux 9

### Linux kernel version used

5.14.0-427.37.1.el9_4.x86_64

### CPU architecture issue was seen on (see `uname -m`)

x86_64

### Unexpected behaviour you saw

Failed build with ../lib/dtmf_rx_fillin-01.h
Trying build with ../lib/dtmf_rx_fillin-02.h
make[2]: Entering directory '/usr/src/rtpengine/daemon'
cc -g -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wstrict-prototypes -Werror=return-type -Wshadow -pthread -fno-strict-aliasing -std=c11 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -pthread  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -pthread     -DPCRE2_CODE_UNIT_WIDTH=8  -I/usr/include/libxml2  -I/usr/include/libxml2   -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/libmount -I/usr/include/blkid -pthread      -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg  -I/usr/include/ffmpeg  -I/usr/include/ffmpeg  -I/usr/include/ffmpeg  -I/usr/include/ffmpeg   -I/usr/include/opus  -DWITH_TRANSCODING -I/usr/include/mysql -I/usr/include/mysql/mysql -DHAVE_BCG729  -DRTPENGINE_VERSION="\"git-master-c865c492\""  -DHAVE_LIBSYSTEMD -O3 -flto=auto -ffat-lto-objects -fPIE  -rdynamic -flto=auto -pie  dtmf_rx_fillin-test.c  -lm -ldl -lglib-2.0  -lgthread-2.0 -pthread -lglib-2.0  -lz  -lpcre2-8  -lcrypto  -lssl -lcrypto  -levent_pthreads -levent  -lpcap -lxmlrpc_client  -lxmlrpc  -lxmlrpc_util  -lhiredis -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lwebsockets  -lnftnl  -lmnl  -lip4tc -lip6tc  -lavcodec  -lavformat  -lavutil  -lswresample  -lavfilter  -lspandsp  -lopus  -L/usr/lib64/ -lmariadb -lbcg729  -lsystemd  -latomic -o dtmf_rx_fillin-test
make[2]: Leaving directory '/usr/src/rtpengine/daemon'
Failed build with ../lib/dtmf_rx_fillin-02.h
make[1]: *** [../lib/common.Makefile:61: dtmf_rx_fillin.h] Error 1
rm control_ng.strhash.c sdp.strhash.c call_interfaces.strhash.c
make[1]: Leaving directory '/usr/src/rtpengine/daemon'
make: *** [../lib/common.Makefile:8: all] Error 2

**Comment by asolovjov** [comment]
In order to build latest versions of rtpengine on Almalinux 9 (and probably any RHEL-like distro) you need to install libatomic package.
`dnf -y install libatomic`

**Comment by rfuchs** [comment]
> In order to build latest versions of rtpengine on Almalinux 9 (and probably any RHEL-like distro) you need to install libatomic package. `dnf -y install libatomic`

Maybe should add that to the el/ build dependencies?

**Comment by asolovjov** [comment]
> > In order to build latest versions of rtpengine on Almalinux 9 (and probably any RHEL-like distro) you need to install libatomic package. `dnf -y install libatomic`
> 
> Maybe should add that to the el/ build dependencies?

Yes, I've made the PR. Unfortunately this is not enough because there is broken dependency between rpmfusion and elrepo related to ffmpeg-libs. The updated version of libdav1d (1.5.0) has been added to ELrepo recently but ffmpeg-libs from rpmfusion requires the old one (libdav1d-1.2.1). Currently you have to "manually" find and install libdav1d-1.2.1
