### ISSUE TITLE
The actual data transfer port is not the P4 port negotiated by the sdp. How can I solve this problem?

### ISSUE THREAD

**Issue by yuanlai45** [sipwise/rtpengine#1868]
### rtpengine version the issue has been seen with

12.5.0.0+0~mr12.5.0.0 git-master-d02ce7e8

### Used distribution and its version

No LSB modules are available. Distributor ID: Ubuntu Description:    Ubuntu 22.04.4 LTS Release:        22.04 Codename:       jammy

### Linux kernel version used

5.15.0-122-generic

### CPU architecture issue was seen on (see `uname -m`)

x86_64

### Expected behaviour you didn't see

When the calling party and the called party interact through rtpengine, there are four ports. P1 is the outgoing port through which the calling party sends invirte to rtpengine, P2 is the outgoing port through which rtpengine processes Invirte to the called party, and P3 is the port through which the called party sends a message to rtpengine. P4 is the port that rtpengine sends to the calling party after processing the message received by P3. Some mobile phones strictly only receive information from the P4 port negotiated between the calling party and rtpengine. However, when my current rtpengine detects rtpengine messages, it does not always reply messages to the calling party through the P4 port, resulting in the failure of playback. Now I hope that he can use the negotiated port to transmit RTP streams

### Unexpected behaviour you saw

When the calling party and the called party interact through rtpengine, there are four ports. P1 is the outgoing port through which the calling party sends invirte to rtpengine, P2 is the outgoing port through which rtpengine processes Invirte to the called party, and P3 is the port through which the called party sends a message to rtpengine. P4 is the port that rtpengine sends to the calling party after processing the message received by P3. Some mobile phones strictly only receive information from the P4 port negotiated between the calling party and rtpengine. However, when my current rtpengine detects rtpengine messages, it does not always reply messages to the calling party through the P4 port, resulting in the failure of playback. Now I hope that he can use the negotiated port to transmit RTP streams

**Comment by rfuchs** [comment]
The Github issue tracker is not a support forum. Use the mailing list.
