### ISSUE TITLE
SRTP output wanted, but no crypto suite was negotiated

### ISSUE THREAD

**Issue by nickong1205** [sipwise/rtpengine#187]
Been at this for a few days already, I can't seem to figure it out why? I'm hooked up Kamailio to PSTN and got websockets working. Was able to ring through but on the browser and on rtpengine log says issues with SRTP. On the server side it says SRTP output wanted, but no crypto suite was negotiated. Browser side it says Failed to set remote answer sdp: Called with SDP without DTLS fingerprint.

Now from wireshark i see that the browser is sending a invite with srtp i see on kamailio then i see rtp coming in from the pstn. I kinda based my script off this one https://github.com/caruizdiaz/kamailio-ws

Any tips ideas on what might be causing that error message.

Thanks in advance!

**Comment by nickong1205** [comment]
Leaving a pastebin of logs http://pastebin.com/njDx0rBk

**Comment by vance-od** [comment]
show how do you call  rtpmanage in kamailio's config (logs says that you call it for request but do not for response)

show INVITE/200OK  from browser

**Comment by nickong1205** [comment]
http://pastebin.com/rdBhfkzb
Here is my kamailio config im not sure why the 183 and 200 coming back from itsp doesn't get parsed the way I expect it to log out. 

When i went to the browser inspect elements network ws 
THis is whats coming back it looks like its not changed 

```
SIP/2.0 183 Session Progress
From: "momo"<sip:momo@sipr.kosmosmobile.com>;tag=pegclyz9FQ4SxNNsz1RD
To: <sip:+17788934277@sipr.kosmosmobile.com>;tag=SDpc5bc99-3656965818-601252
Via: SIP/2.0/WS df7jal23ls0d.invalid;received=206.116.9.145;branch=z9hG4bKRoVKXNqGQora1XqDzoGo1NOKTd8QWo93;rport=56551
Call-ID: 4869f6ce-9dc0-7323-901b-3434b71c6c93
CSeq: 57650 INVITE
Record-Route: <sip:216.115.69.133;lr>
Record-Route: <sip:216.115.69.144;lr>
Contact: <sip:17788934277@65.98.237.158:5060;transport=udp>
Content-Type: application/sdp
Content-Length: 182

v=0
o=- 4294967295 4294967295 IN IP4 65.98.237.158
s=-
c=IN IP4 65.98.237.158
t=0 0
m=audio 13534 RTP/AVP 0 101
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=ptime:20
```

```
SIP/2.0 200 OK
From: "momo"<sip:momo@sipr.kosmosmobile.com>;tag=pegclyz9FQ4SxNNsz1RD
To: <sip:+17788934277@sipr.kosmosmobile.com>;tag=SDpc5bc99-3656965818-601252
Via: SIP/2.0/WS df7jal23ls0d.invalid;received=206.116.9.145;branch=z9hG4bKRoVKXNqGQora1XqDzoGo1NOKTd8QWo93;rport=56551
Call-ID: 4869f6ce-9dc0-7323-901b-3434b71c6c93
CSeq: 57650 INVITE
Record-Route: <sip:216.115.69.133;lr>
Record-Route: <sip:216.115.69.144;lr>
Contact: <sip:17788934277@65.98.237.158:5060;transport=udp>
Content-Type: application/sdp
Content-Length: 182

v=0
o=- 4294967295 4294967295 IN IP4 65.98.237.158
s=-
c=IN IP4 65.98.237.158
t=0 0
m=audio 13534 RTP/AVP 0 101
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=ptime:20
```

**Comment by vance-od** [comment]
after brief look, can suggest only:
investigate logs (start kamailio with debug level 2, to see "L_INFO" messages).
add custom logs if necessary, be sure, that for INVITE worked lines 979-984, cos replies for this INVITE will be handled in onreply_route[REPLY_TO_WS]  1055-1065 (again check logs, that it worked). 
If not find out what part of script handle your request/reply for such call.

**Comment by nickong1205** [comment]
Thanks closing tip worked!
