### ISSUE TITLE
A,B,C calls created a meeting by offer/answer, subscribe request/answer

### ISSUE THREAD

**Issue by JackMa2023** [sipwise/rtpengine#1877]
### Is your feature request related to a problem? Please describe

A and B have modified their SDP on the rtpengine through offer/answer and connected.  Can I put A, B, C in the same conference by C publish with the call-id of A and B's call?  Finally, C subscribes to the conference's rtp stream through subscribe request/answer.

**Comment by rfuchs** [comment]
Not an issue with the code. Direct general questions to the mailing list.
