### ISSUE TITLE
Issue restoring redis subscriptions

### ISSUE THREAD

**Issue by lbalaceanu** [sipwise/rtpengine#1878]
Hello,

I am getting the following warnings with latest code in master, when the notification thread tries to restore from Redis:
`[core] Failed to restore call ID 'YYYYY@XX.XX.XX.XX' from Redis: missing 'created' timestamp`

This is how Redis entries look like on the writing rtpengine (the one subscribed to):

```
"d4:jsond7:created16:17325437832311889:destroyed1:011:last_signal10:17325437833:tos3:1447:deleted1:08:num_sfds1:411:num_streams1:410:num_medias1:28:num_tags1:28:num_maps1:210:ml_deleted1:012:created_from16:10.84.1.12:4988517:created_from_addr10:10.84.1.1215:redis_hosted_db1:218:recording_metadata0:10:block_dtmf1:010:call_flags7:1376256e5:sfd-0d11:pref_family3:IP49:localport5:198962:fd2:1712:logical_intf4:pub214:local_intf_u
1:06:stream1:0e5:sfd-1d11:pref_family3:IP49:localport5:198972:fd2:1812:logical_intf4:pub214:local_intf_uid1:06:stream1:1e5:sfd-2d11:pref_family3:IP49:localport5:520422:fd2:1912:logical_intf4:pub214:local_intf_uid1:06:stream1:2e5:sfd-3d11:pref_family3:IP49:localport5:520432:fd2:2012:logical_intf4:pub214:local_intf_uid1:06:stream1:3e8:stream-0d5:media1:03:sfd1:012:rtcp_sibling1:111:last_packet10:17325437838:ps_flags7:11143689:component1:18:
18:XX.XX.XX.XX:610719:advertised_endpoint18:XX.XX.XX.XX:610713:stats-packets1:011:stats-bytes1:012:stats-errors1:0e13:stream_sfds-0l1:0e11:rtp_sinks-0l1:2e12:rtcp_sinks-0lwickede8:stream-1d5:media1:03:sfd1:112:rtcp_sibling10:429496729511:last_packet10:17325437838:ps_flags7:11799059:component1:28:endpoint18:XX.XX.XX.XX:610819:advertised_endpoint18:XX.XX.XX.XX:610813:stats-packets1:011:stats-bytes1:012:stats ...."
``` 

Is this correct? Mention of json and then bencode?

Thank you,
Lucian

**Comment by lbalaceanu** [comment]
Then maybe one needs to do some extra configuration since the `rtpengine-ctl list numsessions` suggests the call has not been created on the restoring rtpengine?

**Comment by rfuchs** [comment]
Don't really know. How to reproduce?

**Comment by lbalaceanu** [comment]
Hi,

Thanks for the prompt answers. I will investigate further and double check the setup. As a reply to the reproduce question, this is  the current machines arrangement I was talking about:

Redis central machine with CENTRAL_REDIS_IP.
Rtpengine1 with RTP1_IP, has Redis installed, replica of CENTRAL_REDIS_IP.
Rtpengine2 with RTP2_IP, has Redis installed, replica of CENTRAL_REDIS_IP.

Rtpengine1 with RTP1_IP.
redis = RTP1_IP:6379/2
redis-write = CENTRAL_REDIS_IP:6379/2
subscribe-keyspace=4

Rtepengine2 with RTP2_IP. It is subscribed to notifications like this:
redis = RTP2_IP:6379/4
redis-write = CENTRAL_REDIS_IP:6379/4
subscribe-keyspace=2

Rtpengine1 receives call and writes to database. Rtpengine2 receives notification and tries to recreate the call.

**Comment by rfuchs** [comment]
Both rtpengines the same version I assume?

**Comment by lbalaceanu** [comment]
Yes.
