### ISSUE TITLE
Using RTP Engine in conjunction with a turn server

### ISSUE THREAD

**Issue by sgibbons** [sipwise/rtpengine#198]
I'm trying to get the following setup to work:

[webRTC client] <-- (RTP over TCP) --> [turn server] <--- (RTP over UDP) ---> [RTPEngine] <--- (RTP Over UDP) ---> [VoIP Trunking Provider]

I'm able to get things to work either with the turn server between two endpoints (and without RTP Engine in the loop) or with RTP Engine between two endpoints (but without a TURN server in the loop).

Is a setup with both a turn server and rtp engine between the endpoints supported? This setup may be a bit unusual, but on certain networks that engage in packet filtering I've found RTP over TCP to get through a lot more often than straight RTP over UDP, thus the need for the intermediate turn server. I'd use just a turn server to achieve this, but I need RTP Engine in the middle to convert between WebRTC media streams and the traditional RTP streams that my voip trunk supports.

**Comment by rfuchs** [comment]
Unfortunately I don't really have a good answer for you. Theoretically it should be possible as it's only a matter of signalling the correct RTP endpoints to each involved party (potentially using faux SDP bodies towards rtpengine or some such) but I don't have a recipe to make it work.

What may be of interest to you though is that support for RTP over TCP is planned for rtpengine in the (somewhat) near future.

**Comment by havfo** [comment]
Checkout my config in [WebRTC-to-SIP](https://github.com/havfo/WEBRTC-to-SIP), it has a working example of the case you are describing.

**Comment by alexcme** [comment]
It works fine in our case:

WebRTC client1 <--> 443 TURN <--> RTPE <--> TURN 443 <--> WebRTC client2

I would recommend to test with "shared" secret on TURN and make sure that clients not have direct access to RTPE and / or vice versa (ie access through TURN only both directions), otherwise WebRTC not works correctly

**Comment by ovoshlook** [comment]
Hello. I need to implement the same schema as  CLIENT -> [TCP] -> TURN -> [UDP] -> RTPengine and my question is: does RTPengine can act as TURN client?
As I see this - there should be negotiation between TURN and RTPengine what ports to use
For this RTPengine have to make a request to TURN server with allocating ports for sending traffic via it.

**Comment by rfuchs** [comment]
Rtpengine does not support acting as a TURN client.
