### ISSUE TITLE
Chrome 47 no longer supports RTP. 

### ISSUE THREAD

**Issue by ovoshlook** [sipwise/rtpengine#199]
https://developers.google.com/web/updates/2015/10/chrome-47-webrtc
Just ask for forecast about work for handling it.

**Comment by rfuchs** [comment]
This is about data channels, not media channels. Or do I read it wrong?

**Comment by ovoshlook** [comment]
Public Service Announcements
Starting with Chrome 47, getUserMedia() requests are only allowed from secure origins: HTTPS or localhost.
RTP data channel support has been removed. Any remaining applications still using RTP data channels should use the standard data channels instead.

**Comment by rfuchs** [comment]
Yes I've read it. Data channels only, right?

**Comment by ovoshlook** [comment]
So As I understand it means transfer of voice packets, am i right?

**Comment by rfuchs** [comment]
No, this is about things like screen sharing, file transfers etc. At least that's how I read it.

**Comment by ovoshlook** [comment]
hmmm. I have trouble with last update of chrome. I have no sound at my webrtc endpoint. At 45 and 46 chrome it works good.

**Comment by rfuchs** [comment]
You'll have to post a full rtpengine debug log from such a call to investigate this further.
