### ISSUE TITLE
SRTP Not working with Skype For Business Server 2015

### ISSUE THREAD

**Issue by nakchak** [sipwise/rtpengine#203]
Hi, have a bit of a strange one happening here, when i place an inbound call to Skype (Lync) server from either the pstn or local PBX i get encrypted audio (i.e. white noise) on the calling end.  When i dial out from skype server to either PSTN or PBX every thing works as expected...
Looking at the logs and a packet capture it seems that Skype Server is sending a STUN message to negotiated RTPEngine port, which corralates to the time stamp of the `Error parsing RTP header: invalid header version` message in the RTPEngine logs, which is immediatly followed with a lot of duplicate packet errors.  My gut is telling me that something odd is happening with key exchange on an inbound call but i cant for the life of me spot what is going on...
Im using the latest master revision of RTPEngine

`Dec 17 11:36:15 vs-kam-uat01 rtpengine[11239]: Response dump for 'ping' to 127.0.0.1:49237: { "result": "pong" }
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] Received command 'offer' from 127.0.0.1:44280
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] Dump for 'offer' from 127.0.0.1:44280: { "sdp": "v=0#015#012o=root 945107416 945107416 IN IP4 172.16.52.203#015#012s=Asterisk PBX 11.16.0#015#012c=IN IP4 172.16.52.203#015#012b=CT:384#015#012t=0 0#015#012m=audio 17562 RTP/AVP 8 0 101#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-16#015#012a=ptime:20#015#012a=sendrecv#015#012m=video 13298 RTP/AVP 34 98 99#015#012a=rtpmap:34 H263/90000#015#012a=fmtp:34 F=0;I=0;J=0;T=0;K=0;N=0;BPP=0;HRD=0#015#012a=rtpmap:98 H263-1998/90000#015#012a=fmtp:98 F=0;I=0;J=0;T=0;K=0;N=0;BPP=0;HRD=0#015#012a= ...
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] ... rtpmap:99 H264/90000#015#012a=fmtp:99 redundant-pic-cap=0;parameter-add=0;packetization-mode=0;level-asymmetry-allowed=0#015#012a=sendrecv#015#012", "direction": [ "internal", "internal" ], "replace": [ "origin", "session-connection" ], "transport-protocol": "RTP/SAVP", "call-id": "6ff885c15162296b61bfefc45557ea82@sipuat", "received-from": [ "IP4", "172.16.52.203" ], "from-tag": "as6dcd0a11", "command": "offer" }
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] Creating new call
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] set FILLED flag for stream 172.16.52.203:17562
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] set FILLED flag for stream 172.16.52.203:17563
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] set FILLED flag for stream 172.16.52.203:13298
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] set FILLED flag for stream 172.16.52.203:13299
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] Replying to 'offer' from 127.0.0.1:44280
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] Response dump for 'offer' to 127.0.0.1:44280: { "sdp": "v=0#015#012o=root 945107416 945107416 IN IP4 172.16.52.200#015#012s=Asterisk PBX 11.16.0#015#012c=IN IP4 172.16.52.200#015#012b=CT:384#015#012t=0 0#015#012m=audio 35000 RTP/SAVP 8 0 101#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-16#015#012a=ptime:20#015#012a=sendrecv#015#012a=rtcp:35001#015#012a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:WvpNZtJPiGk/mGdv0jdmHNfYrO8BcJS6VXNUOK7q#015#012a=setup:actpass#015#012a=fingerprint:sha-1 DF:46:32:B4:2A:B7:0B:E3:A0:DA:4A:AD:B2 ...
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] ... :01:C5:E5:3E:BF:9F:C0#015#012a=ice-ufrag:397BLUu6#015#012a=ice-pwd:SYJphelkc8UFeVPH6C5Us9LtjS#015#012a=candidate:2e7gyCPUmYuDzlxW 1 UDP 2130706431 172.16.52.200 35000 typ host#015#012a=candidate:2e7gyCPUmYuDzlxW 2 UDP 2130706430 172.16.52.200 35001 typ host#015#012m=video 35030 RTP/SAVP 34 98 99#015#012a=rtpmap:34 H263/90000#015#012a=fmtp:34 F=0;I=0;J=0;T=0;K=0;N=0;BPP=0;HRD=0#015#012a=rtpmap:98 H263-1998/90000#015#012a=fmtp:98 F=0;I=0;J=0;T=0;K=0;N=0;BPP=0;HRD=0#015#012a=rtpmap:99 H264/90000#015#012a=fmtp:99 redundant-pic-cap=0;parameter-add=0;packetization-m ...
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] ... ode=0;level-asymmetry-allowed=0#015#012a=sendrecv#015#012a=rtcp:35031#015#012a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:+ZrmMyAyOo5ZvSYimJsSDcIze5m5uNnHYccbYaaQ#015#012a=setup:actpass#015#012a=fingerprint:sha-1 DF:46:32:B4:2A:B7:0B:E3:A0:DA:4A:AD:B2:01:C5:E5:3E:BF:9F:C0#015#012a=ice-ufrag:Mx8CtQ1I#015#012a=ice-pwd:4k2esUTFQJkWlqOLzzfQpgTbNZ#015#012a=candidate:2e7gyCPUmYuDzlxW 1 UDP 2130706431 172.16.52.200 35030 typ host#015#012a=candidate:2e7gyCPUmYuDzlxW 2 UDP 2130706430 172.16.52.200 35031 typ host#015#012", "result": "ok" }
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] Received command 'offer' from 127.0.0.1:44280
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] Dump for 'offer' from 127.0.0.1:44280: { "sdp": "v=0#015#012o=root 945107416 945107416 IN IP4 172.16.52.200#015#012s=Asterisk PBX 11.16.0#015#012c=IN IP4 172.16.52.200#015#012b=CT:384#015#012t=0 0#015#012m=audio 35000 RTP/SAVP 8 0 101#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-16#015#012a=ptime:20#015#012a=sendrecv#015#012a=rtcp:35001#015#012a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:WvpNZtJPiGk/mGdv0jdmHNfYrO8BcJS6VXNUOK7q#015#012a=fingerprint:sha-1 DF:46:32:B4:2A:B7:0B:E3:A0:DA:4A:AD:B2:01:C5:E5:3E:BF:9F:C0#015#012a ...
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] ... =ice-ufrag:397BLUu6#015#012a=ice-pwd:SYJphelkc8UFeVPH6C5Us9LtjS#015#012a=candidate:2e7gyCPUmYuDzlxW 1 UDP 2130706431 172.16.52.200 35000 typ host#015#012a=candidate:2e7gyCPUmYuDzlxW 2 UDP 2130706430 172.16.52.200 35001 typ host#015#012m=video 35030 RTP/SAVP 34 98 99#015#012a=rtpmap:34 H263/90000#015#012a=fmtp:34 F=0;I=0;J=0;T=0;K=0;N=0;BPP=0;HRD=0#015#012a=rtpmap:98 H263-1998/90000#015#012a=fmtp:98 F=0;I=0;J=0;T=0;K=0;N=0;BPP=0;HRD=0#015#012a=rtpmap:99 H264/90000#015#012a=fmtp:99 redundant-pic-cap=0;parameter-add=0;packetization-mode=0;level-asymmetry-al ...
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] ... lowed=0#015#012a=sendrecv#015#012a=rtcp:35031#015#012a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:+ZrmMyAyOo5ZvSYimJsSDcIze5m5uNnHYccbYaaQ#015#012a=fingerprint:sha-1 DF:46:32:B4:2A:B7:0B:E3:A0:DA:4A:AD:B2:01:C5:E5:3E:BF:9F:C0#015#012a=ice-ufrag:Mx8CtQ1I#015#012a=ice-pwd:4k2esUTFQJkWlqOLzzfQpgTbNZ#015#012a=candidate:2e7gyCPUmYuDzlxW 1 UDP 2130706431 172.16.52.200 35030 typ host#015#012a=candidate:2e7gyCPUmYuDzlxW 2 UDP 2130706430 172.16.52.200 35031 typ host#015#012", "direction": [ "internal", "internal" ], "replace": [ "origin", "session-connection"  ...
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] ... ], "transport-protocol": "RTP/SAVP", "call-id": "6ff885c15162296b61bfefc45557ea82@sipuat", "received-from": [ "IP4", "172.16.52.203" ], "from-tag": "as6dcd0a11", "command": "offer" }
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] enabling passthrough mode
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] set FILLED flag for stream 172.16.52.200:35000
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] set FILLED flag for stream 172.16.52.200:35001
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] enabling passthrough mode
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] set FILLED flag for stream 172.16.52.200:35030
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] set FILLED flag for stream 172.16.52.200:35031
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] Replying to 'offer' from 127.0.0.1:44280
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] Response dump for 'offer' to 127.0.0.1:44280: { "sdp": "v=0#015#012o=root 945107416 945107416 IN IP4 172.16.52.200#015#012s=Asterisk PBX 11.16.0#015#012c=IN IP4 172.16.52.200#015#012b=CT:384#015#012t=0 0#015#012m=audio 35000 RTP/SAVP 8 0 101#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-16#015#012a=ptime:20#015#012a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:WvpNZtJPiGk/mGdv0jdmHNfYrO8BcJS6VXNUOK7q#015#012a=fingerprint:sha-1 DF:46:32:B4:2A:B7:0B:E3:A0:DA:4A:AD:B2:01:C5:E5:3E:BF:9F:C0#015#012a=ice-ufrag:397BLUu6 ...
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] ... #015#012a=ice-pwd:SYJphelkc8UFeVPH6C5Us9LtjS#015#012a=candidate:2e7gyCPUmYuDzlxW 1 UDP 2130706431 172.16.52.200 35000 typ host#015#012a=candidate:2e7gyCPUmYuDzlxW 2 UDP 2130706430 172.16.52.200 35001 typ host#015#012a=sendrecv#015#012a=rtcp:35001#015#012a=candidate:2e7gyCPUmYuDzlxW 1 UDP 2097152255 172.16.52.200 35056 typ host#015#012a=candidate:2e7gyCPUmYuDzlxW 2 UDP 2097152254 172.16.52.200 35057 typ host#015#012m=video 35030 RTP/SAVP 34 98 99#015#012a=rtpmap:34 H263/90000#015#012a=fmtp:34 F=0;I=0;J=0;T=0;K=0;N=0;BPP=0;HRD=0#015#012a=rtpmap:98 H263-1998/9000 ...
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] ... 0#015#012a=fmtp:98 F=0;I=0;J=0;T=0;K=0;N=0;BPP=0;HRD=0#015#012a=rtpmap:99 H264/90000#015#012a=fmtp:99 redundant-pic-cap=0;parameter-add=0;packetization-mode=0;level-asymmetry-allowed=0#015#012a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:+ZrmMyAyOo5ZvSYimJsSDcIze5m5uNnHYccbYaaQ#015#012a=fingerprint:sha-1 DF:46:32:B4:2A:B7:0B:E3:A0:DA:4A:AD:B2:01:C5:E5:3E:BF:9F:C0#015#012a=ice-ufrag:Mx8CtQ1I#015#012a=ice-pwd:4k2esUTFQJkWlqOLzzfQpgTbNZ#015#012a=candidate:2e7gyCPUmYuDzlxW 1 UDP 2130706431 172.16.52.200 35030 typ host#015#012a=candidate:2e7gyCPUmYuDzlxW 2  ...
Dec 17 11:36:22 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] ... UDP 2130706430 172.16.52.200 35031 typ host#015#012a=sendrecv#015#012a=rtcp:35031#015#012a=candidate:2e7gyCPUmYuDzlxW 1 UDP 2097152255 172.16.52.200 35074 typ host#015#012a=candidate:2e7gyCPUmYuDzlxW 2 UDP 2097152254 172.16.52.200 35075 typ host#015#012", "result": "ok" }
Dec 17 11:36:23 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35000] Error parsing RTP header: invalid header version
Dec 17 11:36:23 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35000] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:23 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35000] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:23 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:23 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:23 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35000] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:23 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:23 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:23 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:23 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35000] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:25 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:25 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:25 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:25 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] Received command 'answer' from 127.0.0.1:36806
Dec 17 11:36:25 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] Dump for 'answer' from 127.0.0.1:36806: { "sdp": "v=0#015#012o=- 0 1 IN IP4 172.16.8.100#015#012s=session#015#012c=IN IP4 172.16.8.100#015#012b=CT:9980#015#012t=0 0#015#012m=audio 9826 RTP/SAVP 8 0 101#015#012c=IN IP4 172.16.8.100#015#012a=rtcp:9827#015#012a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:Yp0/JbRyFNLkCf/PfEnpGWQvFY/97kxweRgk9Ng/|2^31#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-16#015#012a=ptime:20#015#012m=video 0 RTP/SAVP 34 98 99#015#012", "direction": [ "internal", "internal" ], "replace": [ "origin", "ses ...
Dec 17 11:36:25 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] ... sion-connection" ], "transport-protocol": "RTP/AVP", "call-id": "6ff885c15162296b61bfefc45557ea82@sipuat", "received-from": [ "IP4", "172.16.52.230" ], "from-tag": "as6dcd0a11", "to-tag": "99e83c7196", "command": "answer" }
Dec 17 11:36:25 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] set FILLED flag for stream 172.16.8.100:9826
Dec 17 11:36:25 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] set FILLED flag for stream 172.16.8.100:9827
Dec 17 11:36:25 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] enabling passthrough mode
Dec 17 11:36:25 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] set FILLED flag for stream 172.16.8.100:0
Dec 17 11:36:25 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] set FILLED flag for stream 172.16.8.100:1
Dec 17 11:36:25 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] Replying to 'answer' from 127.0.0.1:36806
Dec 17 11:36:25 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] Response dump for 'answer' to 127.0.0.1:36806: { "sdp": "v=0#015#012o=- 0 1 IN IP4 172.16.52.200#015#012s=session#015#012c=IN IP4 172.16.52.200#015#012b=CT:9980#015#012t=0 0#015#012m=audio 35014 RTP/AVP 8 0 101#015#012c=IN IP4 172.16.52.200#015#012a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:Yp0/JbRyFNLkCf/PfEnpGWQvFY/97kxweRgk9Ng/|2^31#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-16#015#012a=ptime:20#015#012a=sendrecv#015#012a=rtcp:35015#015#012a=candidate:2e7gyCPUmYuDzlxW 1 UDP 2130706431 172.16.52.200 35014 typ host#015#012a ...
Dec 17 11:36:25 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat] ... =candidate:2e7gyCPUmYuDzlxW 2 UDP 2130706430 172.16.52.200 35015 typ host#015#012m=video 0 RTP/AVP 34 98 99#015#012", "result": "ok" }
Dec 17 11:36:25 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:25 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
Dec 17 11:36:25 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:27 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:27 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
Dec 17 11:36:27 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:29 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35014] Confirmed peer address as 172.16.52.203:17562
Dec 17 11:36:29 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35000] Confirmed peer address as 172.16.8.100:9826
Dec 17 11:36:29 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35000] Kernelizing media stream: 172.16.8.100:9826
Dec 17 11:36:29 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35014] Kernelizing media stream: 172.16.52.203:17562
Dec 17 11:36:30 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] Confirmed peer address as 172.16.8.100:9827
Dec 17 11:36:30 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:30 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:32 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:32 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:36 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:36 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:40 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:40 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Dec 17 11:36:42 vs-kam-uat01 rtpengine[11239]: [6ff885c15162296b61bfefc45557ea82@sipuat port 35001] More than 30 duplicate packets detected, dropping packet to avoid potential loop
`

Capture with session keys is available if needed

**Comment by rfuchs** [comment]
For some reason, the SDP in the second `offer` is exactly the same as the rewritten output SDP from the first `offer`, meaning rtpengine would send packets to itself, which is the reason for the loop warning, as there really was a loop. There's something wrong in your signalling setup.

**Comment by nakchak** [comment]
Doh, gone log blind staring at it too long

Pretty sure that is being caused by a call to msg_apply_changes() and using sdpops kamailio module to remove the a=setup line from the SDP, which i needed to do as Lync/Skype server returns a SIP 488 error if that attribute is present (yup MS's infinite wisdom at play here, why they cant just ignore it have no idea!!!!), will close this non issue and attempt to hack a flag to omit that attribute if set, as it will be much easier to "break" rtpengine than it will be to get MS to fix that stupidity on their part!

Thanks Richard

**Comment by rfuchs** [comment]
`a=setup` is added by DTLS-SRTP... if that is a problem, you can do the rtpengine calls with DTLS=off to remove it.

**Comment by nakchak** [comment]
Is that a valid flag for the kamailio module?, just undocumented on their wiki if it is

**Comment by rfuchs** [comment]
It should be. Recent versions of the module don't really care much about the flags, they just pass them down to rtpengine.

**Comment by nakchak** [comment]
That did it brilliant thank you!
