### ISSUE TITLE
SRTP + OpenSIPS

### ISSUE THREAD

**Issue by cepehutu** [sipwise/rtpengine#207]
Really, who? 

Tried all flags. But any time had an errors like:
SRTP output wanted, but no crypto suite was negotiated
Failed to parse a=crypto attribute: unknown crypto suite

P.S. Yes, googled all posobilites, all varies, all docs.

Please Help!
Sos!

**Comment by rfuchs** [comment]
Can you please post the full debug log of such a failed call?

**Comment by cepehutu** [comment]
Whe find solution.
On linphone a=crypto has 4 lines of different crypto keys, and rtpengine go away with this suite.
Solution: use only 1 line a crypto and everething be ok ( MS_AES_128_SHA1_80 )

Also we send bug trace to our email for improvement .
