### ISSUE TITLE
memory leak, maybe from socket-rework

### ISSUE THREAD

**Issue by khoegh** [sipwise/rtpengine#210]
We are seeing a memory leak in rtpengine.
As far I can tell, the leak happened between commit 8219921 and 548b710.

We only use a single interface for media and call 'rtpengine_manage("ICE=remove");' from kamailio.
Using sipp I created 20.000 calls, and rtpengine leak around 12MB.
The calls are answered, and after 5 sec. they are terminated. (more or less basic uas-rtp/uac-rtp scenarios)

I attach a valgrind report from git trunk (6f2dc00), running 1234 calls - same scenario as above.
valgrind --leak-check=full --show-leak-kinds=all --trace-children=yes --log-fd=9 rtpengine --listen-ng=10.w.x.200:12221 --listen-cli=10.w.x.200:9900 --listen-cli=127.0.0.1:9900 --no-fallback --table=0 --interface=178.y.z.60 --port-min=50000 --port-max=54999 9>valgrind.txt

The debug log from a single session is also attached.
[debug.txt](https://github.com/sipwise/rtpengine/files/103250/debug.txt)
[valgrind.txt](https://github.com/sipwise/rtpengine/files/103249/valgrind.txt)

**Comment by rfuchs** [comment]
Thanks for the detailed report. Just to confirm, the valgrind log was taken after all calls have terminated?

**Comment by khoegh** [comment]
Yes, I waited more than 30 seconds after last call before i killed it.

**Comment by khoegh** [comment]
That did it, thanks a lot @rfuchs.
