### ISSUE TITLE
rtpengine send DTLS Client Hello when in passive mode

### ISSUE THREAD

**Issue by alexcme** [sipwise/rtpengine#211]
RTP engine send DTLS Client Hello even when configured with —dtls-passive role that can randomly result in DTLS error from Chrome (depends on when rtpengine receive / send Client Hello).

RTP engine log and network capture uploaded to:

https://www.dropbox.com/s/x8m7wl7t8bppw3g/dtls_error.zip?dl=0

Sequence is like below (call-id is 00200000136568f1e99000c293193b2@EYEP_954e7983fe0a_3125_avp)

*1. Initial offer (a=sendrecv) from Chrome to IVR (lines # 1 - 28 in rtpengine_log.txt):

Chrome 10.160.0.175:10010 -> (DTLS) 10.17.18.28:32934 RTPEngine 10.17.18.28:32924 (AVPF) -> 10.17.18.24:10000 IVR

*2. Answer from IVR (a=sendrecv) to Chrome (lines # 71 - 84 in rtpengine_log.txt):

Chrome 10.160.0.175:10010 <- (DTLS) 10.17.18.28:32934 RTPEngine 10.17.18.28:32924 (AVPF) <- 10.17.18.24:10000 IVR

*3. Offer from IVR (a=sendonly) to Chrome (lines # 94 - 106 in rtpengine_log.txt):

Chrome 10.160.0.175:10010 <- (DTLS) 10.17.18.28:32934 RTPEngine 10.17.18.28:32924 (AVPF) <- 10.17.18.24:10000 IVR

=====

**DTLS error at line # 129 (in rtpengine_log.txt) due to Client Hello from RTP engine (configured / started to use “passive” mode)
Related packets # 15 / 16 / 17 in dtls_avp_error.pcapng**

=====

*4. Answer from Chrome (a=recvonly) to IVR (lines # 132 - 153 in rtpengine_log.txt):

Chrome 10.160.0.175:10010 -> (DTLS) 10.17.18.28:32934 RTPEngine 10.17.18.28:32924 (AVPF) -> 10.17.18.24:10000 IVR

*5. Offer from IVR (a=sendrecv) to Chrome (lines # 177 - 189 in rtpengine_log.txt):

Chrome 10.160.0.175:10010 <- (DTLS) 10.17.18.28:32934 RTPEngine 10.17.18.28:32924 (AVPF) <- 10.17.18.24:10000 IVR

*6. Answer from Chrome (a=sendrecv) to IVR (lines # 197 - 219 in rtpengine_log.txt):

Chrome 10.160.0.175:10010 -> (DTLS) 10.17.18.28:32934 RTPEngine 10.17.18.28:32924 (AVPF) -> 10.17.18.24:10000 IVR

**Comment by rfuchs** [comment]
I've pushed a possible fix for this into a new branch `rfuchs/issue211` (commit f79f38b).

JFTR, the RFC mandates that the a=setup attribute always contain the role `actpass`, but with this fix applied the actual role should be retained after the re-invite.

**Comment by rfuchs** [comment]
Any news here?

**Comment by alexcme** [comment]
Just finished testing - it works fine, thank you.
