### ISSUE TITLE
dpkg-buildpackage failed on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by altzone** [sipwise/rtpengine#215]
Hello, 
from fresh git clone rtpengine repo and after having satisfied all the dependencies, when i run dpkg-buildpackage, the following error occurs in building ngcp-rtpengine-daemon :
`dh_shlibdeps         -pngcp-rtpengine-daemon -P/usr/src/rtpengine/debian/ngcp-rtpengine-daemon
dpkg-shlibdeps: error: no dependency information found for /usr/lib/libxmlrpc.so.3 (used by /usr/src/rtpengine/debian/ngcp-rtpengine-daemon/usr/sbin/rtpengine)
dh_shlibdeps: dpkg-shlibdeps -Tdebian/ngcp-rtpengine-daemon.substvars /usr/src/rtpengine/debian/ngcp-rtpengine-daemon/usr/sbin/rtpengine returned exit code 2
make: *** [ngcp-rtpengine-daemon] Error 2
dpkg-buildpackage: error: debian/rules binary gave error exit status 2
`
Do you have any solutions to build packages?
Thank you very much!

**Comment by rfuchs** [comment]
I just ran `dpkg-buildpackage` on a freshly installed and upgraded 14.04 LTS and it completed without a hitch. Complete output at https://gist.github.com/rfuchs/c363aa71109620d3fa75

My first guess would be a problem with the xmlrpc library. Installed here is `libxmlrpc-core-c3` and `libxmlrpc-core-c3-dev` both at version `1.33.06-0ubuntu1`. Please check if this is what you have and/or if there's any updates available.

My full list of all packages: https://gist.github.com/rfuchs/c4bc143c28b32ff15a00
