### ISSUE TITLE
rtpengine in with only one Iocal network

### ISSUE THREAD

**Issue by lestaupes** [sipwise/rtpengine#216]
Hi,

I'm using the last version of rtpengine + kamailio and I have an issue when I use only one local network. My goal is to advertised the SDP (with the public address) for LAN to WAN requests and keep the local IP in the SDP for the requests from WAN to LAN.
In the commande I have --interface pub=Local_IP!advertised_pub_addr priv=Local_IP
In the ng command I use the flag direction= priv direction = pub or direction= pub direction = priv (according to the direction of the request).
But both cases rtpengine advertised the SDP with the public address.

Does this configuration with only one local network (no bridge) should work?

Thanks

Lestaupes

**Comment by rfuchs** [comment]
It's supposed to work, but looks like it doesn't. :) I'll look into it.

**Comment by rfuchs** [comment]
Please have a look at the code from branch `rfuchs/issue216` (commit bfd841d) and see if that fixes your issue.

**Comment by lestaupes** [comment]
Yes, it fixes the issue.

Thanks!
