### ISSUE TITLE
rtpengine + uac module

### ISSUE THREAD

**Issue by andrewvmail** [sipwise/rtpengine#217]
just wondering if anyone have tried to use these two modules together sucesfully? im getting disconnection after a few seconds..

**Comment by vance-od** [comment]
please provide more details about what you are doing, and details about disconnection. What you are sending with uac (you mean kamailio's module) ?

**Comment by andrewvmail** [comment]
Actually closing this, I thought it was a problem with rtpengine but it's something else.
