### ISSUE TITLE
One Way Audio Due to STUN request after Candidates not removed

### ISSUE THREAD

**Issue by hunterj91** [sipwise/rtpengine#218]
Hi All,

Sorry if this isnt 100% rtpengine but I am getting 1 way audio issues on centos 6.7 with rtpengine when interworking between IPv6 and IPv4.

I have a client on IPv6 (Freeswitch) which then connects to OpenSIPS with Another FreeSWITCH behind it.

In opensips I am trying to remove ice, so adding this to configuration file;
rtpengine_manage("address-family=IP4 ICE=remove");

However I still see candidates in the 200ok that rtpengine send back to client, which in turn is making the client send a STUN query which isnt replied too, and I then get 1 way audio.

If I bypass rtpengine and use freeSWITCH on an IPv6 profile I get 2 way audio, so wondered if anyone had this issue before?

Ideally I want to remove all ICE from SDP.

Thanks

Jon

**Comment by vance-od** [comment]
Do you call rtpengine_manage for both INVITE/200OK?
"Ideally I want to remove all ICE from SDP." - please, provide the example call-flow, how it should work

**Comment by hunterj91** [comment]
Hi Vance,

Sorry my apologies, I didnt remove ICE in the 200ok and other provisional responses with SDP.

I have now added that and it works perfectly!

Many thanks and apologies!

Jon
