### ISSUE TITLE
redis auth for rtpengine

### ISSUE THREAD

**Issue by ovoshlook** [sipwise/rtpengine#219]
Hello. I need share data between some rtpengine services (for HA realisation) butt my redis server uses AUTH param. Is it possible to use AUTH for rtpengine  coonection to redis. If yes- how? Did ot find any discribtion about it at README

P.S. Sorry for qestions here. did not find any mailing lists.

**Comment by rfuchs** [comment]
Not supported at the moment, but should be fairly trivial to implement.

**Comment by ovoshlook** [comment]
Im I need to do some changes in code by myself or it will be in the next release? If yes when will be new release?

**Comment by rfuchs** [comment]
You can submit a patch if you don't want to wait, otherwise I'll do it as soon as I get around to it. I don't have a timeline for the next mr release.
