### ISSUE TITLE
STUN Error-code 401

### ISSUE THREAD

**Issue by ibaques** [sipwise/rtpengine#223]
Hi,

We have dropped calls by RTP Timeout with Kamailio 4.2 and RTPENGINE. In Chrome console the ICE is disconnected, and no errors in rtpengine.log(level 7).

When i capture with tcpdump, the call is running ok with audio and STUN request are responded with:

Success Response XOR-MAPPED-ADDRESS

suddenly the server response with 

```
    ERROR-CODE 401 (Unauthorized): Unauthorized
```

The binding request user and password is the same all the time. What can be the problem with rtpengine?

Best regards.

**Comment by rfuchs** [comment]
What server is responding to whose requsts? Perhaps post the rtpengine log and the pcap.

**Comment by ibaques** [comment]
Hi,

In the rtpengine log:

Successful STUN binding request from every second, suddenly no messages
from this call and after 15 seconds, the command delete (when the browser
send BYE to Kamailio)

Best regards.



2016-02-25 14:18 GMT+01:00 Richard Fuchs <notifications@github.com>:

**Comment by rfuchs** [comment]
I can't reproduce this. From the log and the pcap, it looks like rtpengine stopped receiving packets in this port altogether - not just STUN.

The last_packet timestamp for port 33946 is 1456907776, which is the last time an STUN packet was seen and answered (09:36:16). Nothing else was received on that port afterwards. The only explanation I can think of is that something else on the system prevented the packets from being delivered to rtpengine. Perhaps an iptables rules went up (or down), or routing/interface config has changed, or some other process allocated the same port at the same time.

**Comment by rfuchs** [comment]
Cleaning up old tickets
