### ISSUE TITLE
Audio drop on session refresh on webrtc call

### ISSUE THREAD

**Issue by mtryfoss** [sipwise/rtpengine#226]
I've tested this with the latest master and Chrome 48.
Every time the session is refreshed, audio is dropped for a small second.

On an earlier release of rtpengine, this appears in the log:
Mar  3 16:32:13 rtp3new rtpengine[2208]: [36eafpn4peh7sr9pe8jf] Received command 'offer' from 158.58.154.84:23301
Mar  3 16:32:13 rtp3new rtpengine[2208]: [36eafpn4peh7sr9pe8jf] Replying to 'offer' from 158.58.154.84:23301
Mar  3 16:32:13 rtp3new rtpengine[2208]: [36eafpn4peh7sr9pe8jf port 38726] DTLS error: 1 (bad message type)
Mar  3 16:32:13 rtp3new rtpengine[2208]: [36eafpn4peh7sr9pe8jf port 38726] DTLS error on local port 38726
Mar  3 16:32:13 rtp3new rtpengine[2208]: [36eafpn4peh7sr9pe8jf port 38726] Received invalid STUN packet from 10.61.11.30:45076: MESSAGE_INTEGRITY attribute missing
Mar  3 16:32:13 rtp3new rtpengine[2208]: [36eafpn4peh7sr9pe8jf] Received command 'answer' from 158.58.154.84:30756
Mar  3 16:32:13 rtp3new rtpengine[2208]: [36eafpn4peh7sr9pe8jf] Replying to 'answer' from 158.58.154.84:30756

Here's what appears in the log for master:
Mar  4 10:37:39 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj] Received command 'offer' from 158.58.152.19:47859
Mar  4 10:37:39 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj] Dump for 'offer' from 158.58.152.19:47859: { "sdp": "v=0#015#012o=root 65633435 65633435 IN IP4 158.58.154.23#015#012s=Nordicom#015#012c=IN IP4 158.58.154.23#015#012t=0 0#015#012m=audio 10122 RTP/AVP 111#015#012a=rtpmap:111 opus/48000/2#015#012a=fmtp:111 maxplaybackrate=48000;sprop-maxcapturerate=48000;minptime=10;maxaveragebitrate=20000;stereo=0;sprop-stereo=0;cbr=0;useinbandfec=0;usedtx=0#015#012a=ptime:20#015#012a=maxptime:60#015#012a=sendrecv#015#012", "ICE": "force", "flags": [ "trust-address" ], "replace": [ "origin", "session-connection" ], "transport-p ...
Mar  4 10:37:39 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj] ... rotocol": "RTP/SAVPF", "rtcp-mux": [ "offer" ], "call-id": "3h6et4gi5ukbte1bf8mj", "received-from": [ "IP4", "158.58.154.23" ], "from-tag": "as5b611536", "to-tag": "bgi4l0e1hh", "command": "offer" }
Mar  4 10:37:39 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj] Replying to 'offer' from 158.58.152.19:47859
Mar  4 10:37:39 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj] Response dump for 'offer' to 158.58.152.19:47859: { "sdp": "v=0#015#012o=root 65633435 65633435 IN IP4 158.58.154.97#015#012s=Nordicom#015#012c=IN IP4 158.58.154.97#015#012t=0 0#015#012m=audio 35078 RTP/SAVPF 111#015#012a=rtpmap:111 opus/48000/2#015#012a=fmtp:111 maxplaybackrate=48000;sprop-maxcapturerate=48000;minptime=10;maxaveragebitrate=20000;stereo=0;sprop-stereo=0;cbr=0;useinbandfec=0;usedtx=0#015#012a=ptime:20#015#012a=maxptime:60#015#012a=sendrecv#015#012a=rtcp:35079#015#012a=rtcp-mux#015#012a=setup:actpass#015#012a=fingerprint:sha-1 56:30:FC:36:45:DF:D8:7D:C0:3D:4C:C5: ...
Mar  4 10:37:39 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj] ... 6D:0E:EB:48:A6:6F:91:C6#015#012a=ice-ufrag:XoQpebzx#015#012a=ice-pwd:F8te3J3Y2XVWjfdqKEpZLaeIw3#015#012a=candidate:lOP5zsVkeSyBeNMt 1 UDP 2130706431 158.58.154.97 35078 typ host#015#012a=candidate:lOP5zsVkeSyBeNMt 2 UDP 2130706430 158.58.154.97 35079 typ host#015#012", "result": "ok" }
Mar  4 10:37:39 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] Processing incoming DTLS packet
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] Created candidate pair lOP5zsVkeSyBeNMt:a96e467c30:1 between 158.58.154.97 and 10.61.10.169:57686, type prflx
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] ICE role conflict detected
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] ICE role conflict detected
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] ICE role conflict detected
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj] Received command 'answer' from 158.58.152.19:57638
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj] Dump for 'answer' from 158.58.152.19:57638: { "sdp": "v=0#015#012o=- 8587875480108689691 2 IN IP4 127.0.0.1#015#012s=-#015#012t=0 0#015#012a=msid-semantic: WMS yFlhPatm8ykUrWPmZ9aeJ3giJHTJv8UzfbqL#015#012m=audio 57686 RTP/SAVPF 111#015#012c=IN IP4 10.61.10.169#015#012a=rtcp:9 IN IP4 0.0.0.0#015#012a=candidate:606101030 1 udp 2122260223 10.61.10.169 57686 typ host generation 0#015#012a=candidate:1789108950 1 tcp 1518280447 10.61.10.169 0 typ host tcptype active generation 0#015#012a=ice-ufrag:ns511ruLkGh+QMMZ#015#012a=ice-pwd:ecv2cIDO7K2csJ6LeEGqp9+z#015#012a=fingerp ...
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj] ... rint:sha-256 DC:86:86:3C:56:88:54:DC:59:9A:EF:49:6E:65:10:A1:C5:AB:C8:DA:CD:3B:64:99:B8:32:11:D8:5F:2A:D3:16#015#012a=setup:active#015#012a=mid:audio#015#012a=sendrecv#015#012a=rtcp-mux#015#012a=rtpmap:111 opus/48000/2#015#012a=fmtp:111 minptime=10; useinbandfec=1#015#012a=maxptime:60#015#012a=ssrc:3639788410 cname:6z60UvGlVB0N75qQ#015#012a=ssrc:3639788410 msid:yFlhPatm8ykUrWPmZ9aeJ3giJHTJv8UzfbqL 19a9ada7-da93-4549-a5f4-f2c7446eec67#015#012a=ssrc:3639788410 mslabel:yFlhPatm8ykUrWPmZ9aeJ3giJHTJv8UzfbqL#015#012a=ssrc:3639788410 label:19a9ada7-da93-4549-a5f4-f2c ...
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj] ... 7446eec67#015#012", "ICE": "remove", "call-id": "3h6et4gi5ukbte1bf8mj", "received-from": [ "IP4", "158.58.154.153" ], "from-tag": "as5b611536", "to-tag": "bgi4l0e1hh", "command": "answer" }
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj] Sending DTLS packet
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj] set FILLED flag for stream 10.61.10.169:57686
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj] ICE restart, resetting ICE agent
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj] Learning new ICE candidate 606101030:1
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj] Created candidate pair lOP5zsVkeSyBeNMt:606101030:1 between 158.58.154.97 and 10.61.10.169:57686, type host
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj] Sending ICE/STUN request for candidate pair lOP5zsVkeSyBeNMt:606101030:1 from 158.58.154.97 to 10.61.10.169:57686
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj] Replying to 'answer' from 158.58.152.19:57638
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj] Response dump for 'answer' to 158.58.152.19:57638: { "sdp": "v=0#015#012o=- 8587875480108689691 2 IN IP4 127.0.0.1#015#012s=-#015#012t=0 0#015#012a=msid-semantic: WMS yFlhPatm8ykUrWPmZ9aeJ3giJHTJv8UzfbqL#015#012m=audio 35090 RTP/AVP 111#015#012c=IN IP4 158.58.154.97#015#012a=rtpmap:111 opus/48000/2#015#012a=fmtp:111 minptime=10; useinbandfec=1#015#012a=maxptime:60#015#012a=ssrc:3639788410 cname:6z60UvGlVB0N75qQ#015#012a=ssrc:3639788410 msid:yFlhPatm8ykUrWPmZ9aeJ3giJHTJv8UzfbqL 19a9ada7-da93-4549-a5f4-f2c7446eec67#015#012a=ssrc:3639788410 mslabel:yFlhPatm8ykUrWPmZ9ae ...
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj] ... J3giJHTJv8UzfbqL#015#012a=ssrc:3639788410 label:19a9ada7-da93-4549-a5f4-f2c7446eec67#015#012a=sendrecv#015#012a=rtcp:35091#015#012", "result": "ok" }
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] Received ICE/STUN response code 0 for candidate pair lOP5zsVkeSyBeNMt:606101030:1 from 10.61.10.169:57686 to 158.58.154.97
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] Setting ICE candidate pair lOP5zsVkeSyBeNMt:606101030:1 as succeeded
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] Best succeeded ICE pair with all components is lOP5zsVkeSyBeNMt:606101030:1
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35060] SRTP output wanted, but no crypto suite was negotiated
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35060] Switching local interface to 158.58.154.97:35060
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] ICE pair lOP5zsVkeSyBeNMt:606101030:1 has been nominated by peer
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] ICE completed, using pair lOP5zsVkeSyBeNMt:606101030:1
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] ICE negotiated: local interface 158.58.154.97
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] Successful STUN binding request from 10.61.10.169:57686
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] Processing incoming DTLS packet
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] Sending DTLS packet
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] Processing incoming DTLS packet
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] DTLS handshake successful
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] DTLS-SRTP successfully negotiated
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] SRTP keys, incoming:
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] --- AES_CM_128_HMAC_SHA1_80 key z9963RsOr4tpFRTuyZ5qSg== salt rVjJuHRHXEMJhVKHAT4=
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] SRTP keys, outgoing:
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] --- AES_CM_128_HMAC_SHA1_80 key I3K0o26egD8Dxm6St1IzfQ== salt qk3zl7E/Ei3x+PaBGms=
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] DTLS-SRTP successfully negotiated
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] SRTP keys, incoming:
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] --- AES_CM_128_HMAC_SHA1_80 key z9963RsOr4tpFRTuyZ5qSg== salt rVjJuHRHXEMJhVKHAT4=
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] SRTP keys, outgoing:
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] --- AES_CM_128_HMAC_SHA1_80 key I3K0o26egD8Dxm6St1IzfQ== salt qk3zl7E/Ei3x+PaBGms=
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] Sending DTLS packet
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35090] Switching local interface to 158.58.154.97:35090
Mar  4 10:37:40 rtptest2 rtpengine[2277]: [3h6et4gi5ukbte1bf8mj port 35078] Successful STUN binding request from 10.61.10.169:57686

Also attaching the complete log for whole call.
[rtpengine-log.txt.gz](https://github.com/sipwise/rtpengine/files/158459/rtpengine-log.txt.gz)

**Comment by rfuchs** [comment]
Looks like the ICE reset is responsible for it. Can you run a pcap (including the media ports) and post it along with the corresponding log?

**Comment by mtryfoss** [comment]
Here you go:
[rtpenginelog.txt](https://github.com/sipwise/rtpengine/files/160901/rtpenginelog.txt)
[webrtc-call.zip](https://github.com/sipwise/rtpengine/files/160898/webrtc-call.zip)

**Comment by rfuchs** [comment]
I don't think this is rtpengine's fault. When side B does a reinvite, side A (WebRTC) reacts with a DTLS teardown (packet 4533), ICE role change (cmp packet 4540 with 4502) and ICE restart. I see no reason for it to do that. The ICE stuff wouldn't be a problem, but the DTLS teardown definitely breaks communications until DTLS can be reestablished.

**Comment by mtryfoss** [comment]
Thank you so much. We'll have a look at the client side.

**Comment by mtryfoss** [comment]
The cause was an old implementation of jssip, which did connection reset on re-invite. Now everything works fine. Thank you!
