### ISSUE TITLE
RTPEngine with OpenSIPS : Called with SDP without DTLS fingerprint

### ISSUE THREAD

**Issue by mvenkatesh431** [sipwise/rtpengine#232]
I am using following setup
OpenSIPS 2.2 devel with wss support.
sipjs 0.7 as websocket client
RTPEngine 4.4 

I have two web users like 1000 and 2000. Both are registered to OpenSIPS through the WSS. Whenever i made call between the 1000 to 2000 or vice versa, i am getting error saying "** Failed to set remote offer sdp: Called with SDP without DTLS fingerprint".**

I am using default opensips.cfg  script. here is the url of the script http://www.opensips.org/Documentation/Tutorials-WebSocket-2-1

Basically I am calling rtpengine_offer like this.
$var(rtpengine_flags) = "ICE=force-relay DTLS=passive";
rtpengine_offer("$var(rtpengine_flags)");
I am doing same for the rtpengine_answer also.

Interesting thing is I am not getting any errors, if i call the rtpengine_offer and answer without any parameters. Call is connecting and i am able to get two way video. 

And also, If i try same thing with WS (i.e web clients registers to OpenSIPS through WS) it is working fine with the parameters.

Here i am attaching the rtpengine log, calling end web client log, called end web client log. 

any help is greatly appreciated. Thank you in advance.
[rtpengine log.txt](https://github.com/sipwise/rtpengine/files/208303/rtpengine.log.txt)
[opensips and rtpengine comms.txt](https://github.com/sipwise/rtpengine/files/208304/opensips.and.rtpengine.comms.txt)
[receiving end.txt](https://github.com/sipwise/rtpengine/files/208422/receiving.end.txt)
[calling party log.txt](https://github.com/sipwise/rtpengine/files/208423/calling.party.log.txt)

**Comment by rfuchs** [comment]
According to the log, you're instructing rtpengine to translate the DTLS-SRTP call to plaintext RTP (`"transport-protocol": "RTP/AVP"`). Do you have anything in your config that would do that?

**Comment by mvenkatesh431** [comment]
I am calling the rtpengine_offer like below.

 if (isflagset(SRC_WS) && isbflagset(DST_WS))
        $var(rtpengine_flags) = "ICE=force-relay DTLS=passive";
    else if (isflagset(SRC_WS) && !isbflagset(DST_WS))
        $var(rtpengine_flags) = "RTP/AVP replace-session-connection replace-origin ICE=remove";
    else if (!isflagset(SRC_WS) && isbflagset(DST_WS))
        $var(rtpengine_flags) = "UDP/TLS/RTP/SAVPF ICE=force";
    else if (!isflagset(SRC_WS) && !isbflagset(DST_WS))
        $var(rtpengine_flags) = "RTP/AVP replace-session-connection replace-origin ICE=remove";

    rtpengine_offer("$var(rtpengine_flags)");

Both are web clients so first if supposed to execute. After removing the all other if conditions it is working. Thanks. 

But still i need to figure out why other if conditions are executing.

**Comment by rfuchs** [comment]
Can't help you there, I'm not familiar with the OpenSIPS internals. I notice that some instances in the code above are `isflagset` while others are `isbflagset`. Not sure if that means anything though.

**Comment by soulofmischief87** [comment]
Venkatesh,

You have to set these flags in order for the condition to met. Please look
at the following
https://github.com/etamme/federated-sip/wiki/RTPEngine-offer-answer-in-opensips
.

**Comment by mvenkatesh431** [comment]
Thanks all, Now it is working. I needed to setup the flags properly.

**Comment by dubeyvishal** [comment]
Venkatesh,

I know its closed, Can you please share your config file. I am facing same issue.

Thanks,
Vishal

**Comment by prathibhacdac** [comment]
I am also facing the same issue. Can you share the config file?
