### ISSUE TITLE
Help with kernel module

### ISSUE THREAD

**Issue by volga629** [sipwise/rtpengine#233]
Hello Everyone,
Got error in attempt build kernel module for kernel 4.4.6-201.fc22.x86_64

Here log output 

http://fpaste.org/353283/02995071/

Any help thank you

**Comment by rfuchs** [comment]
Use a newer version please, this has already been fixed in c4f630c

**Comment by volga629** [comment]
thanks for answer what version is right now ?

**Comment by rfuchs** [comment]
Either use current git master, or the 4.3 branch

**Comment by volga629** [comment]
Thank you for help. issue has being resolved. I was be able build rpms and test it. Here repository 

http://ftpsrv01.networklab.ca/fedora/22/RPMS/x86_64/
