### ISSUE TITLE
SDES missed in re-INVITE based on a specific case

### ISSUE THREAD

**Issue by BroWater** [sipwise/rtpengine#236]
**version:** git-master-29545e5

**environment:**  2 SIP endpoints registered to a Kamailio SIP Server which uses rtpengine to bridge them,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Endpoint A (EP_A) support FECC while Endpoint B (EP_B) is not.
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Both support SRTP however BFCP signaling in SRTP are not supported

**Steps:**

1. EP_A call EP_B
2. for some reasons, EP_A send a re-INVITE to EP_B

**Result:**

The SDES of BFCP video was dropped while other media (ex: audio, video) are OK.

Following are the SDPs in this experiment:

_NOTICE:_
Since EP_B doesn't support FECC , the 200 OK it returned still included the application attribute
but with port 0, and it seems to be the cause makes SDES-missing happend.

I replace EP_B with a FECC-support one (we call EP_C here),
and it works like normal - the SDES is still there.
And I remove the FECC-support from EP_C, and it failed like EP_B.

**(1) Initial INVITE sent by EP_A**

v=0
o=EP_A 0 0 IN IP4 192.168.195.159
s=-
c=IN IP4 192.168.195.159
b=AS:2048
t=0 0
m=audio 30286 RTP/SAVP 9 0 8 15 101 102 103 104 105 97
a=encryption:optional
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:15 G728/8000
a=rtpmap:101 G7221/16000
a=fmtp:101 bitrate=24000
a=rtpmap:102 G7221/16000
a=fmtp:102 bitrate=32000
a=rtpmap:103 G7221/32000
a=fmtp:103 bitrate=24000
a=rtpmap:104 G7221/32000
a=fmtp:104 bitrate=32000
a=rtpmap:105 G7221/32000
a=fmtp:105 bitrate=48000
a=rtpmap:97 telephone-event/8000
a=fmtp:97 0-11
a=sendrecv
a=rtcp:30287
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:Jx5jGGwHFpya9V7t7z7LZhzpy+DdOE2bayw/L01T
m=video 30318 RTP/SAVP 107 106 34 31
b=TIAS:2048000
a=encryption:optional
a=content:main
a=label:1
a=rtpmap:107 H264/90000
a=fmtp:107 profile-level-id=428028;max-mbps=244800;max-fs=8160;max-br=2048;packetization-mode=0
a=rtpmap:106 H263-1998/90000
a=fmtp:106 CIF=1;QCIF=1
a=rtpmap:34 H263/90000
a=fmtp:34 CIF=1;QCIF=1
a=rtpmap:31 H261/90000
a=fmtp:31 CIF=2;QCIF=2
a=sendrecv
a=rtcp:30319
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:lXYf7hUbEV7uMJAN0UCfUixceNmZ+rD1dudm7yao
m=application 30346 RTP/SAVP 100
a=encryption:optional
a=rtpmap:100 H224/4800
a=sendrecv
a=rtcp:30347
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:LxYkSinA43/mGBJfvhMEGzlCAh6w8ezD5WZ7Sjd3
**m=application 30376 UDP/BFCP *         <---------- our BFCP does not support SRTP
a=floorctrl:c-s
a=connection:new
a=floorid:1 m-stream:3
a=confid:436
a=userid:2
a=sendrecv**
m=video 30416 RTP/SAVP 108 107
b=TIAS:2048000
a=encryption:optional
a=content:slides
a=label:3
a=rtpmap:108 H264/90000
a=fmtp:108 profile-level-id=64000d;max-mbps=108000;max-fs=3600;max-br=2048;packetization-mode=0
a=rtpmap:107 H264/90000
a=fmtp:107 profile-level-id=42800d;max-mbps=108000;max-fs=3600;max-br=2048;packetization-mode=0
a=sendrecv
a=rtcp:30417
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:Zks3++euHLE08HuZsWm6yjJTh33ib3kSxh+ys/Ou 
**↑↑↑ notice here and it will disappear in the later re-INVITE**

**(2) 200 OK responded by EP_B**

v=0
o=EP_B 0 1 IN IP4 192.168.195.171
s=talk
c=IN IP4 192.168.195.171
b=AS:2048
t=0 0
m=audio 30000 RTP/SAVP 9 0 8 97
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:97 telephone-event/8000
a=sendrecv
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:N2E0MTVkNGRlMmIyZTdlYjA4YjEyY2Q1MTIwZTgx
a=encryption:optional
a=fmtp:97 0-11
m=video 30002 RTP/SAVP 107
b=AS:2048
a=content:main
a=label:1
a=sendrecv
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:ZGQ3NmY1MDk1YjFjZmQ2NzA1MTIxZTczZGVkMzRh
a=encryption:optional
a=rtpmap:107 H264/90000
a=fmtp:107 profile-level-id=428028; max-mbps=244800; max-fs=8160; max-br=2048; packetization-mode=0
**m=application 0 RTP/SAVP 100  <---- point**
m=application 30004 UDP/BFCP *
a=floorctrl:c-only
a=setup:passive
a=connection:new
a=floorid:1 m-stream:3
m=video 30006 RTP/SAVP 107
b=AS:2048
a=content:slides
a=label:3
a=sendrecv
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:MmMxYTdlYjc0NzdiNTgwN2IzMTNmNGJkZGJmNjEz
a=encryption:optional
a=rtpmap:107 H264/90000
a=fmtp:107 profile-level-id=42800d; max-mbps=244800; max-fs=8160; max-br=2048; packetization-mode=0

**(3) EP_A send a re-INVITE to EP_B**

v=0
o=EP_A 0 0 IN IP4 192.168.195.159
s=-
c=IN IP4 192.168.195.159
b=AS:2048
t=0 0
m=audio 30286 RTP/SAVP 9 0 8 15 101 102 103 104 105 97
a=encryption:optional
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:15 G728/8000
a=rtpmap:101 G7221/16000
a=fmtp:101 bitrate=24000
a=rtpmap:102 G7221/16000
a=fmtp:102 bitrate=32000
a=rtpmap:103 G7221/32000
a=fmtp:103 bitrate=24000
a=rtpmap:104 G7221/32000
a=fmtp:104 bitrate=32000
a=rtpmap:105 G7221/32000
a=fmtp:105 bitrate=48000
a=rtpmap:97 telephone-event/8000
a=fmtp:97 0-11
a=sendrecv
a=rtcp:30287
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:+DGiWNCbRSXQHeo7KtYghF2j30EFh9PPxXQsCgai
m=video 30318 RTP/SAVP 107
b=TIAS:2048000
a=encryption:optional
a=content:main
a=label:1
a=rtpmap:107 H264/90000
a=fmtp:107 profile-level-id=42801e;max-mbps=108000;max-fs=3600;max-br=2048;packetization-mode=0
a=sendrecv
a=rtcp:30319
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:uPOUXfOpESnHs924a+MBrcHQvHN4KLJWzWRP0wOR
m=application 30440 UDP/BFCP *
a=floorctrl:s-only
a=connection:new
a=floorid:1 m-stream:3
a=confid:436
a=userid:2
a=sendrecv
m=video 30462 RTP/SAVP 107
b=TIAS:2048000
a=encryption:optional
a=content:slides
a=label:3
a=rtpmap:107 H264/90000
a=fmtp:107 profile-level-id=42800d;max-mbps=108000;max-fs=3600;max-br=2048;packetization-mode=0
a=sendrecv
a=rtcp:30463
**↑↑↑  crypto disappears!!**

I add some log in the source code and I found that 
in sdp_replace function the SDES flag of MEDIA_FLAG of BFCP video is not set ,
I'm trying to figure out why this happened and I wish to get some suggestions from you guys.

Thanks~!

**Comment by rfuchs** [comment]
Are these SDP bodies before or after they were rewritten by rtpengine?

If possible, please run rtpengine in log level 7 and then post the full log for one such call, as this shows all the flags used and the SDP bodies both incoming and outbound.

**Comment by BroWater** [comment]
Hello Richard,

From above SDPs, 
(1) and (3) are after rewritten by rtpengine, (2) is the original one.


Following is log with level 7: 
(EP_A is on 10.100.92.43 , rtpengine is the same as EP_A , and EP_B is on 10.100.92.70)

-----------------------------------------

[1461575361.901758] INFO: [1018973428] Received command 'offer' from 127.0.0.1:35412
[1461575361.901758] DEBUG: [1018973428] Dump for 'offer' from 127.0.0.1:35412: { "sdp": "v=0

o=EP_A 0 0 IN IP4 10.100.92.43

s=-

c=IN IP4 10.100.92.43

b=AS:2048

t=0 0

m=audio 30000 RTP/SAVP 9 0 8 15 101 102 103 104 105 97

a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:vwiojKVRKatixhSXFiYw5km6nizGYD4JGC7SRECi

a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:g4eDNnAIbuVDrECShKna7E4JMhzVrpbSpLEjHC59

a=encryption:optional

a=rtpmap:9 G722/8000

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:15 G728/8000

a=rtpmap:101 G7221/16000

a=fmtp:101 bitrate=24000

a=rtpmap:102 G7221/16000

a=fmtp:102 bitrate=32000

a=rtpmap:103 G7221/32000

a=fmtp:103 bitrate=24000

a=rtpmap:104 G7221/32000

a=fmtp:104 bitrate=32000

a=rtpmap:105 G7221/32000

a=fmtp:105 bitrate=48000

a=rtpmap:97 telephone-event/8000

a=fmtp:97 0-11

a=sendrecv

m=video 30002 RTP/SAVP 107 106 34 31

b=TIAS:2048000

a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:s5plc7Kn7Q53tSLnwrUTOI54uqZnZ6FsOjwH/bDy

a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:Xxr3hmInyM6wSAzuE+MQYlmFyFRXzFrbYIejgwVX

a=encryption:optional

a=content:main

a=label:1

a=rtpmap:107 H264/90000

a=fmtp:107 profile-level-id=428028;max-mbps=244800;max-fs=8160;max-br=2048;packetization-mode=0

a=rtpmap:106 H263-1998/90000

a=fmtp:106 CIF=1;QCIF=1

a=rtpmap:34 H263/90000

a=fmtp:34 CIF=1;QCIF=1

a=rtpmap:31 H261/90000

a=fmtp:31 CIF=2;QCIF=2

a=sendrecv

m=application 30006 RTP/SAVP 100

a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:+8OCAv9zujI37n+nCBSgcg6e4Px6j533k1yIqN8G

a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:57dUyysoyuWt0RzYVS4ocWXANpci5yWSNIa2DeeW

a=encryption:optional

a=rtpmap:100 H224/4800

a=sendrecv

m=application 30090 UDP/BFCP *

a=floorctrl:c-s

a=setup:passive

a=connection:new

a=floorid:1 m-stream:3

a=confid:895

a=userid:2

m=video 30004 RTP/SAVP 108 107

b=TIAS:2048000

a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:BOEU+oGjBxmUyE33M2/gif+d9GAdsWHaoDklBmG1

a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:df3t6UiY0qcs0Ab1tes2jXVj9GbJBo8bAll5+3gQ

a=encryption:optional

a=content:slides

a=label:3

a=rtpmap:108 H264/90000

a=fmtp:108 profile-level-id=64000d;max-mbps=108000;max-fs=3600;max-br=2048;packetization-mode=0

a=rtpmap:107 H264/90000

a=fmtp:107 profile-level-id=42800d;max-mbps=108000;max-fs=3600;max-br=2048;packetization-mode=0

a=sendrecv

", "DTLS": "no", "ICE": "remove", "call-id": "1018973428", "received-from": [ "IP4", "10.100.92.43" ], "from-tag": "568356777", "command": "offer" }
[1461575361.901758] NOTICE: [1018973428] Creating new call
[1461575361.901758] ERR: [1018973428] call.c.1499 monologue_offer_answer
[1461575361.901758] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.43:30000
[1461575361.901758] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.43:30001
[1461575361.901758] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.43:30002
[1461575361.901758] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.43:30003
[1461575361.901758] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.43:30006
[1461575361.901758] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.43:30007
[1461575361.901758] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.43:30090
[1461575361.901758] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.43:30091
[1461575361.901758] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.43:30004
[1461575361.901758] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.43:30005
[1461575361.901758] INFO: [1018973428] offer time = 0.002375 sec
[1461575361.901758] INFO: [1018973428] Replying to 'offer' from 127.0.0.1:35412
[1461575361.901758] DEBUG: [1018973428] Response dump for 'offer' to 127.0.0.1:35412: { "sdp": "v=0

o=EP_A 0 0 IN IP4 10.100.92.43

s=-

c=IN IP4 10.100.92.43

b=AS:2048

t=0 0

m=audio 30100 RTP/SAVP 9 0 8 15 101 102 103 104 105 97

a=encryption:optional

a=rtpmap:9 G722/8000

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:15 G728/8000

a=rtpmap:101 G7221/16000

a=fmtp:101 bitrate=24000

a=rtpmap:102 G7221/16000

a=fmtp:102 bitrate=32000

a=rtpmap:103 G7221/32000

a=fmtp:103 bitrate=24000

a=rtpmap:104 G7221/32000

a=fmtp:104 bitrate=32000

a=rtpmap:105 G7221/32000

a=fmtp:105 bitrate=48000

a=rtpmap:97 telephone-event/8000

a=fmtp:97 0-11

a=sendrecv

a=rtcp:30101

a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:vwiojKVRKatixhSXFiYw5km6nizGYD4JGC7SRECi

m=video 30124 RTP/SAVP 107 106 34 31

b=TIAS:2048000

a=encryption:optional

a=content:main

a=label:1

a=rtpmap:107 H264/90000

a=fmtp:107 profile-level-id=428028;max-mbps=244800;max-fs=8160;max-br=2048;packetization-mode=0

a=rtpmap:106 H263-1998/90000

a=fmtp:106 CIF=1;QCIF=1

a=rtpmap:34 H263/90000

a=fmtp:34 CIF=1;QCIF=1

a=rtpmap:31 H261/90000

a=fmtp:31 CIF=2;QCIF=2

a=sendrecv

a=rtcp:30125

a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:s5plc7Kn7Q53tSLnwrUTOI54uqZnZ6FsOjwH/bDy

m=application 30152 RTP/SAVP 100

a=encryption:optional

a=rtpmap:100 H224/4800

a=sendrecv

a=rtcp:30153

a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:+8OCAv9zujI37n+nCBSgcg6e4Px6j533k1yIqN8G

m=application 30180 UDP/BFCP *

a=floorctrl:c-s

a=connection:new

a=floorid:1 m-stream:3

a=confid:895

a=userid:2

a=sendrecv

m=video 30210 RTP/SAVP 108 107

b=TIAS:2048000

a=encryption:optional

a=content:slides

a=label:3

a=rtpmap:108 H264/90000

a=fmtp:108 profile-level-id=64000d;max-mbps=108000;max-fs=3600;max-br=2048;packetization-mode=0

a=rtpmap:107 H264/90000

a=fmtp:107 profile-level-id=42800d;max-mbps=108000;max-fs=3600;max-br=2048;packetization-mode=0

a=sendrecv

a=rtcp:30211

a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:BOEU+oGjBxmUyE33M2/gif+d9GAdsWHaoDklBmG1

", "result": "ok" }
[1461575363.817294] INFO: [1018973428] Received command 'answer' from 127.0.0.1:53584
[1461575363.817294] DEBUG: [1018973428] Dump for 'answer' from 127.0.0.1:53584: { "sdp": "v=0

o=EP_B 0 1 IN IP4 10.100.92.70

s=talk

c=IN IP4 10.100.92.70

b=AS:2048

t=0 0

m=audio 30000 RTP/SAVP 9 0 8 97

a=rtpmap:9 G722/8000

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:97 telephone-event/8000

a=sendrecv

a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:N2Y0NmQyNjdlZjg3Nzk3NTRhNmMxM2M3ZWVhNWMz

a=encryption:optional

a=fmtp:97 0-11

m=video 30002 RTP/SAVP 107

b=AS:2048

a=content:main

a=label:1

a=sendrecv

a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:N2UwNjFlMzMzMzU3OGM1ZmJiYTNhYzE4ZTk5MTEy

a=encryption:optional

a=rtpmap:107 H264/90000

a=fmtp:107 profile-level-id=428028; max-mbps=244800; max-fs=8160; max-br=2048; packetization-mode=0

**m=application 0 RTP/SAVP 100**

m=application 30004 UDP/BFCP *

a=floorctrl:c-only

a=setup:passive

a=connection:new

a=floorid:1 m-stream:3

m=video 30006 RTP/SAVP 107

b=AS:2048

a=content:slides

a=label:3

a=sendrecv

a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:MThjOTNlMmIwZTMzOTM5NmVmNDk4ZDY1YTk0YTg3

a=encryption:optional

a=rtpmap:107 H264/90000

a=fmtp:107 profile-level-id=42800d; max-mbps=244800; max-fs=8160; max-br=2048; packetization-mode=0

", "DTLS": "no", "ICE": "remove", "call-id": "1018973428", "received-from": [ "IP4", "10.100.92.70" ], "from-tag": "568356777", "to-tag": "981357603", "command": "answer" }
[1461575363.817294] ERR: [1018973428] call.c.1499 monologue_offer_answer
[1461575363.817294] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.70:30000
[1461575363.817294] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.70:30001
[1461575363.817294] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.70:30002
[1461575363.817294] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.70:30003
[1461575363.817294] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.70:0
[1461575363.817294] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.70:1
[1461575363.817294] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.70:30004
[1461575363.817294] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.70:30005
[1461575363.817294] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.70:30006
[1461575363.817294] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.70:30007
[1461575363.817294] INFO: [1018973428] answer time = 0.000827 sec
[1461575363.817294] INFO: [1018973428] Replying to 'answer' from 127.0.0.1:53584
[1461575363.817294] DEBUG: [1018973428] Response dump for 'answer' to 127.0.0.1:53584: { "sdp": "v=0

o=EP_B 0 1 IN IP4 10.100.92.70

s=talk

c=IN IP4 10.100.92.43

b=AS:2048

t=0 0

m=audio 30112 RTP/SAVP 9 0 8 97

a=rtpmap:9 G722/8000

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:97 telephone-event/8000

a=encryption:optional

a=fmtp:97 0-11

a=sendrecv

a=rtcp:30113

a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:N2Y0NmQyNjdlZjg3Nzk3NTRhNmMxM2M3ZWVhNWMz

m=video 30134 RTP/SAVP 107

b=AS:2048

a=content:main

a=label:1

a=encryption:optional

a=rtpmap:107 H264/90000

a=fmtp:107 profile-level-id=428028; max-mbps=244800; max-fs=8160; max-br=2048; packetization-mode=0

a=sendrecv

a=rtcp:30135

a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:N2UwNjFlMzMzMzU3OGM1ZmJiYTNhYzE4ZTk5MTEy

m=application 0 RTP/SAVP 100

m=application 30198 UDP/BFCP *

a=floorctrl:c-only

a=connection:new

a=floorid:1 m-stream:3

a=sendrecv

m=video 30224 RTP/SAVP 107

b=AS:2048

a=content:slides

a=label:3

a=encryption:optional

a=rtpmap:107 H264/90000

a=fmtp:107 profile-level-id=42800d; max-mbps=244800; max-fs=8160; max-br=2048; packetization-mode=0

a=sendrecv

a=rtcp:30225

a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:MThjOTNlMmIwZTMzOTM5NmVmNDk4ZDY1YTk0YTg3

", "result": "ok" }
[1461575364.831421] WARNING: [1018973428 port 30180] Unknown transport protocol encountered
[1461575364.832010] WARNING: [1018973428 port 30198] Unknown transport protocol encountered
[1461575367.000140] INFO: [1018973428 port 30100] Confirmed peer address as 10.100.92.70:30000
[1461575367.001893] INFO: [1018973428 port 30134] Confirmed peer address as 10.100.92.43:30002
[1461575367.010300] INFO: [1018973428 port 30124] Confirmed peer address as 10.100.92.70:30002
[1461575367.010741] INFO: [1018973428 port 30112] Confirmed peer address as 10.100.92.43:30000
[1461575368.517831] INFO: [1018973428 port 30180] Confirmed peer address as 10.100.92.70:30004
[1461575368.518976] INFO: [1018973428 port 30198] Confirmed peer address as 10.100.92.43:30090
[1461575368.840972] INFO: [1018973428 port 30210] Confirmed peer address as 10.100.92.70:30006
[1461575368.845475] INFO: [1018973428 port 30125] Confirmed peer address as 10.100.92.70:30003
[1461575370.313695] INFO: [1018973428 port 30135] Confirmed peer address as 10.100.92.43:30003
[1461575371.338728] INFO: [1018973428 port 30225] Confirmed peer address as 10.100.92.43:30005
[1461575371.819816] INFO: [1018973428 port 30113] Confirmed peer address as 10.100.92.43:30001
[1461575373.819066] INFO: [1018973428 port 30101] Confirmed peer address as 10.100.92.70:30001
[1461575373.875701] INFO: [1018973428 port 30211] Confirmed peer address as 10.100.92.70:30007
[1461575386.542375] INFO: [1018973428] Received command 'offer' from 127.0.0.1:35412
[1461575386.542375] DEBUG: [1018973428] Dump for 'offer' from 127.0.0.1:35412: { "sdp": "v=0

o=EP_A 0 0 IN IP4 10.100.92.43

s=-

c=IN IP4 10.100.92.43

b=AS:2048

t=0 0

m=audio 30000 RTP/SAVP 9 0 8 15 101 102 103 104 105 97

a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:17pDUcQ+H6Sw28LT1ZlrJFRSf7vkco8BSX6Ac41B

a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:8gcmPD6BsspOwWswf891wwmZ52f3sI2tbYeviJdg

a=encryption:optional

a=rtpmap:9 G722/8000

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:15 G728/8000

a=rtpmap:101 G7221/16000

a=fmtp:101 bitrate=24000

a=rtpmap:102 G7221/16000

a=fmtp:102 bitrate=32000

a=rtpmap:103 G7221/32000

a=fmtp:103 bitrate=24000

a=rtpmap:104 G7221/32000

a=fmtp:104 bitrate=32000

a=rtpmap:105 G7221/32000

a=fmtp:105 bitrate=48000

a=rtpmap:97 telephone-event/8000

a=fmtp:97 0-11

a=sendrecv

m=video 30002 RTP/SAVP 107

b=TIAS:2048000

a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:NlmvIwhluQws3eXNRUvC59kj0iWcdyQiOBfL43wc

a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:LLSZKoQAfHnjmm6DeuKbd1PVs+x/ATIp30riaX4Q

a=encryption:optional

a=content:main

a=label:1

a=rtpmap:107 H264/90000

a=fmtp:107 profile-level-id=42801e;max-mbps=108000;max-fs=3600;max-br=2048;packetization-mode=0

a=sendrecv

m=application 30090 UDP/BFCP *

a=floorctrl:s-only

a=setup:passive

a=connection:new

a=floorid:1 m-stream:3

a=confid:895

a=userid:2

m=video 30004 RTP/SAVP 107

b=TIAS:2048000

a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:DM2NJ73Hr1wt1oRHm0FJORO1ZJ0WYKZ7snl+aTt9

a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:L7akfnJx8lVt6CXl0YcCcnkYWVgIHBAAb4+JM39F

a=encryption:optional

a=content:slides

a=label:3

a=rtpmap:107 H264/90000

a=fmtp:107 profile-level-id=42800d;max-mbps=108000;max-fs=3600;max-br=2048;packetization-mode=0

a=sendrecv

", "DTLS": "no", "ICE": "remove", "call-id": "1018973428", "received-from": [ "IP4", "10.100.92.43" ], "from-tag": "568356777", "to-tag": "981357603", "command": "offer" }
[1461575386.542375] ERR: [1018973428] call.c.1499 monologue_offer_answer
[1461575386.542375] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.43:30090
[1461575386.542375] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.43:30091
[1461575386.542375] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.43:30004
[1461575386.542375] DEBUG: [1018973428] set FILLED flag for stream 10.100.92.43:30005
[1461575386.542375] INFO: [1018973428] offer time = 0.000835 sec
[1461575386.542375] INFO: [1018973428] Replying to 'offer' from 127.0.0.1:35412
[1461575386.542375] DEBUG: [1018973428] Response dump for 'offer' to 127.0.0.1:35412: { "sdp": "v=0

o=EP_A 0 0 IN IP4 10.100.92.43

s=-

c=IN IP4 10.100.92.43

b=AS:2048

t=0 0

m=audio 30100 RTP/SAVP 9 0 8 15 101 102 103 104 105 97

a=encryption:optional

a=rtpmap:9 G722/8000

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:15 G728/8000

a=rtpmap:101 G7221/16000

a=fmtp:101 bitrate=24000

a=rtpmap:102 G7221/16000

a=fmtp:102 bitrate=32000

a=rtpmap:103 G7221/32000

a=fmtp:103 bitrate=24000

a=rtpmap:104 G7221/32000

a=fmtp:104 bitrate=32000

a=rtpmap:105 G7221/32000

a=fmtp:105 bitrate=48000

a=rtpmap:97 telephone-event/8000

a=fmtp:97 0-11

a=sendrecv

a=rtcp:30101

a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:17pDUcQ+H6Sw28LT1ZlrJFRSf7vkco8BSX6Ac41B

m=video 30124 RTP/SAVP 107

b=TIAS:2048000

a=encryption:optional

a=content:main

a=label:1

a=rtpmap:107 H264/90000

a=fmtp:107 profile-level-id=42801e;max-mbps=108000;max-fs=3600;max-br=2048;packetization-mode=0

a=sendrecv

a=rtcp:30125

a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:NlmvIwhluQws3eXNRUvC59kj0iWcdyQiOBfL43wc

m=application 30240 UDP/BFCP *

a=floorctrl:s-only

a=connection:new

a=floorid:1 m-stream:3

a=confid:895

a=userid:2

a=sendrecv

m=video 30262 RTP/SAVP 107

b=TIAS:2048000

a=encryption:optional

a=content:slides

a=label:3

a=rtpmap:107 H264/90000

a=fmtp:107 profile-level-id=42800d;max-mbps=108000;max-fs=3600;max-br=2048;packetization-mode=0

a=sendrecv

a=rtcp:30263

", "result": "ok" }
[1461575387.570194] INFO: [1018973428] Received command 'answer' from 127.0.0.1:53584
[1461575387.570194] DEBUG: [1018973428] Dump for 'answer' from 127.0.0.1:53584: { "sdp": "v=0

**Comment by rfuchs** [comment]
You're right that it's the removal of a media stream that confuses rtpengine. The re-invite removes the SRTP `application` stream by setting the port to zero. The next re-invite them omits this `m=` line altogether, which is incorrect behaviour according to the RFC, which states:

```
   ... Because of
   these requirements, the number of "m=" lines in a stream never
   decreases, but either stays the same or increases.  Deleted media
   streams from a previous SDP MUST NOT be removed in a new SDP;
   however, attributes for these streams need not be present.
```

As such, rtpengine doesn't pair up the media streams the same way that the clients do and attributes get mixed up.

The proper solution would be to fix the clients so that they don't remove `m=` lines. I will try to implement a workaround for broken clients like these, but bear in mind that this will be just that - a workaround and not a properly supported use case.

**Comment by BroWater** [comment]
Thanks for your rapid response :)

You said, "...The next re-invite them omits this m= line altogether...",
however, I found that the m=application with port 0 is removed by the SIP client in re-INVITE
not  rtpengine.  Please check this.

So, is the behavior OK? Or the SIP client who send re-INVITE should keep m=application in SDP??

**Comment by rfuchs** [comment]
Yes, that's what I mean. It's the SIP client dropping the m= line. But dropping an m= line is not allowed by the RFC. So the SIP client is in the wrong here. The m= line with zero port should remain in the SDP until the call is finished.

**Comment by BroWater** [comment]
OK. The SIP client is programmable and I will try to fix the SIP client first since it is the root cause.

**Comment by BroWater** [comment]
Hey, Richard

Hers's the good news. After I keep the application stream in SDP of the re-INVITE,
It works ! The SDES is still there and the BFCP video stream is in SRTP (that's what I need).
I really appreciate your help (though it's not a matter of rtpengine :P)!

**Comment by rfuchs** [comment]
Good to hear. Closing ticket then - no change required.
