### ISSUE TITLE
Installation on Centos 6.7

### ISSUE THREAD

**Issue by stefancn** [sipwise/rtpengine#237]
Hi !

Tried to find info about the `libevent_pthreads.pc' problem on Centos 6.7 I did:

*****

make rtpengine
make[1]: Entering directory `/usr/src/rtpengine-master/daemon'
cc -g -Wall -pthread -fno-strict-aliasing -std=c99 `pkg-config --cflags glib-2.0` `pkg-config --cflags gthread-2.0` `pkg-config --cflags zlib` `pkg-config --cflags openssl` `pkg-config --cflags libevent_pthreads` `pcre-config --cflags` -I../kernel-module/ -D_GNU_SOURCE -DRTPENGINE_VERSION="\"undefined\"" -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -O3   -c -o redis.o redis.c
Package libevent_pthreads was not found in the pkg-config search path.
Perhaps you should add the directory containing `libevent_pthreads.pc'

*****

Can someone please help me in this matter.

Regards ...

/S

**Comment by rfuchs** [comment]
Do you have package libevent-devel installed?

**Comment by stefancn** [comment]
Ohh, thanks for your fast reply,  yes , it is installed.

Package libevent-devel-1.4.13-4.el6.x86_64 already installed and latest version

**Comment by rfuchs** [comment]
How about libevent2-devel?

**Comment by stefancn** [comment]
Got:

[root@svab-lab-opensips-ws daemon]# yum install libevent2-devel
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
epel/metalink                                                                                                             |  22 kB     00:00
 * base: centos.vianett.no
 * epel: ftp.nluug.nl
 * extras: centos.vianett.no
 * updates: centos.vianett.no
base                                                                                                                      | 3.7 kB     00:00
extras                                                                                                                    | 3.4 kB     00:00
opensips                                                                                                                  | 1.5 kB     00:00
updates                                                                                                                   | 3.4 kB     00:00
No package libevent2-devel available.
Error: Nothing to do

Interesting !!!

**Comment by stefancn** [comment]
Found a solution:

install/compile the libevent 2.0.22 from: https://github.com/sipwise/rtpengine
then copy all the .o and .pc to the appr. locations. (eg. lib or lib64)

Now I could compile the daemon,

You have to probably make some links, check with ldd rtpengine.

ln /usr/lib64/libevent-2.0.so.5 -> /usr/local/lib/libevent-2.0.so.5
ln /usr/lib64/libevent_pthreads-2.0.so.5 -> /usr/local/lib/libevent_pthreads-2.0.so.5

Don't know if this is the right method as I'm a newbi in Linux compiling, but it worked for me.

Take care 
/S

**Comment by rfuchs** [comment]
http://rpm.pbone.net/index.php3/stat/3/srodzaj/1/search/libevent2-devel seems to have builds for your distro

**Comment by stefancn** [comment]
Thanks, I really appreciate that you took some time to help me out.

Take care ...
