### ISSUE TITLE
RTPengine crashing

### ISSUE THREAD

**Issue by timrsa** [sipwise/rtpengine#241]
Hi Guys, 
I am new to rtpengine and hiredis, I am using rtpengine in conjunction with opensips 2.2, we want to use webrtc for our PBX's, I have successfully installed opensips and rtengine on 5 other boxes but this one seems to keep crashing. CPU spikes and this error is written to the log file:

May 28 13:06:10 {server} rtpengine[10684]: redis_notify_event_base is NULL on event base action 2
May 28 13:06:10 {server} rtpengine[10684]: Version 2.3.0 shutting down
May 28 13:06:11 {server} rtpengine[2761]: Generating new DTLS certificate
May 28 13:06:11 {server} rtpengine[2762]: Startup complete, version 2.3.0
May 28 13:19:54 {server} rtpengine[2762]: redis_notify_event_base is NULL on event base action 2
May 28 13:19:54 {server} rtpengine[2762]: Version 2.3.0 shutting down
May 28 13:20:31 {server} rtpengine[4906]: Generating new DTLS certificate
May 28 13:20:32 {server} rtpengine[4907]: Startup complete, version 2.3.0
May 28 13:20:59 {server} rtpengine[4907]: redis_notify_event_base is NULL on event base action 2
May 28 13:20:59 {server} rtpengine[4907]: Version 2.3.0 shutting down

These boxes are all very similar, I installed them the exact same way but this particular instance is giving issues... Any idea where to start debugging? as I said I'm not overly familiar with these services, any information or even pointing me in the right direction will be really great. 

Thanks

**Comment by rfuchs** [comment]
I don't think these are actually crashes - something seems to be explicitly stopping the service. The log message "... shutting down" only appears when the daemon is gracefully exiting, which happens when it receives a termination signal (SIGINT or SIGTERM for example).

**Comment by timrsa** [comment]
Hi Richard,

Thanks for having a look at the logs, subsequently I have come across some more information I would like to run by you. I see the box which is having issues is on:
_centos-release-6-3.el6.centos.9.x86_64_

The other boxes are upwards of:
_centos-release-6-4.el6.centos.10.x86_64_

Do you think the kernel version could be the issue? Do you think Redis would need to be updated with the updated kernel? I can yum update, it should get release 6.8 by now.

Is there any other log I could look at to get a better picture? have you ever come across this before?

Thanks again!

**Comment by rfuchs** [comment]
I don't think either the kernel version or Redis version would make a difference. (The error message pertaining Redis seems to be spurious.) I think it's some other service on the machine deliberately killing off the rtpengine service.

**Comment by timrsa** [comment]
Hi Richard,

It appears those logs were generated by another user terminating the service as you suggested.
My apologies, there is another issue logged pertaining to the issues we experiencing with the engine.

Thank you very much for your valued input I will close this issue.
