### ISSUE TITLE
RTPengine using all the CPU

### ISSUE THREAD

**Issue by conraddeweteuphoria** [sipwise/rtpengine#242]
I have just installed RTPengine on about 5 or 6 servers, some real, some virtual. They are all pretty much setup in the same way - CentOS 6.5.

On all of the servers RTPengine starts and runs perfectly fine, except on ONE of the servers RTPengine is using what looks like 75% CPU. There are other services like asterisk etc that run fine and use up a few percent CPU. Importantly, there are absolutely no calls over RTPengine. It immediately starts up and starts using 75%.

I'm not using the iptables extensions or the kernel mod - as it not necessary as i only plan on handing a handful of calls.

This is the system log:

> May 29 17:47:13 pbx2 rtpengine[32681]: Generating new DTLS certificate
> May 29 17:47:13 pbx2 rtpengine[32682]: Startup complete, version 2.3.0
> 

What else can I look at?

Edit: it appears there is a difference... its on Centos 6.2 all the others are 6.4 and above.

**Comment by rfuchs** [comment]
Is it user CPU or system CPU?
Is it any particular thread of rtpengine using that much CPU? (try `ps -efL`)
Try using `strace` to see what the whole process or the individual thread is doing. `strace -p $PID` can attach to a particular thread.

**Comment by conraddeweteuphoria** [comment]
If someone else stumbles upon this thread, doing a quick update (we went from 6.2 to 6.8) fixed the problem. RTPengine now uses 0.1% CPU.
