### ISSUE TITLE
STUN packet as rtpkeepalive does not open second leg stream (sometimes)

### ISSUE THREAD

**Issue by Maciej999** [sipwise/rtpengine#243]
rtpengine version: 4.4.0.0+0~mr4.4.0.0
Could you please take a look at the following situation?

(S&R = Send and Recv)

The scenario:
A is a device with no screen so it only sends the video, voice is enabled in both ways.

> A (Audio S&R + Video Sendonly) -> rtpengine -> B
> A <- rtpengine <- (Audio S&R + Video Recvonly) B

The problem is that very often the rtpengine keeps sending video packets from A to B's local IP. This situation would be ok because the rtpengine doesn't know the public coordinates of the B video port/ip but we use dummy STUN packets as RTPkeepalive to overcome this (as mentioned in https://tools.ietf.org/html/rfc6263#page-6).
However in most situations it does not work as expected (audio works both ways while there's no video on B).
I guess that sometimes the STUN packet is not ignored (which would be correct) and do some dirty logic with the video call.
I attach 2 logs, ok call and not ok call:
[nok.txt](https://github.com/sipwise/rtpengine/files/302404/nok.txt)
[ok.txt](https://github.com/sipwise/rtpengine/files/302405/ok.txt)

Im looking forward to see you answer and please let me know if you need some more information.
Regards,
Maciej

**Comment by rfuchs** [comment]
The dummy STUN packets are actually ignored in all cases, as rtpengine only supports the ICE variant of STUN and these packets don't quality as valid ICE-STUN packets.

In the working case, the correct IP endpoint is determined from an RTCP packet, as recvonly streams still send RTCP and an address learned from RTCP is duplicated into the RTP counterpart. Of course this means that if no RTCP packets are received, then this doesn't happen.

**Comment by Maciej999** [comment]
Thank you for your answer!
It seems you are correct, I didn't notice RTCP packets at all before. In the failed situation the there's no 'Receiver Report'.

Regards,
Maciej
