### ISSUE TITLE
issue while rtpengine_manage call with latest stable

### ISSUE THREAD

**Issue by vance-od** [sipwise/rtpengine#244]
Hi Richard!

Currently in production we are using rtpengine 4.2.0.0+0~mr4.2.0.0
Decided to update sources to current stable - 4.4.1.1+0~mr4.4.1.1
After update I have an issue while processing calls with rtpengine

Call script:
webrtc client -> kamailio+rtpengine -> asterisk -> kamailio -> legacy sip phone
when doing rtpengine_manage for INVITE from webrtc client, I'm getting errors. Log with debug level 7 for such call:
https://gist.github.com/vance-od/eb933dfe7cd6ee87732ed3d29e2e0b22

checked with old version - works OK.
the daemon is starting with following parameters (in this way it works in production):
```
root@myserver:/home/admin# ps aux |grep rtp
root     14448  0.0  0.0  73384   680 pts/0    Sl   14:01   0:00 /usr/sbin/rtpengine --interface=10.100.1.85 --interface=externip --listen-ng=127.0.0.1:22222 --listen-cli=127.0.0.1:22223 --timeout=60 --silent-timeout=3600 --pidfile=/var/run/rtpengine.pid --port-min=21000 --port-max=29999 --table=-1 --log-level=5 --log-facility=daemon --num-threads=5 --delete-delay=60
```

if I change --interface parameter (just for test):
```
root@myserver:/home/admin# ps aux |grep rtp
root     14448  0.0  0.0  73384   680 pts/0    Sl   14:01   0:00 /usr/sbin/rtpengine --interface=10.100.1.85!externip --listen-ng=127.0.0.1:22222 --listen-cli=127.0.0.1:22223 --timeout=60 --silent-timeout=3600 --pidfile=/var/run/rtpengine.pid --port-min=21000 --port-max=29999 --table=-1 --log-level=5 --log-facility=daemon --num-threads=5 --delete-delay=60
```
it works as expected (the same as on old version).

_External IP address of the server is masked as externip_

Any suggestions? 

Thanks in advance for your help!

**Comment by rfuchs** [comment]
If you're behind NAT, then you need to use `--interface=$INT_IP!EXT_IP`. Is there something not working when you do that?

**Comment by vance-od** [comment]
using:
`--interface=$INT_IP!EXT_IP`
rtpengine inserts in sdp (in response for offer) o= and c= lines address of `EXT_IP`

if I use
`--interface=10.100.1.85 --interface=externip`
than rtpengine inserts in sdp o= and c= lines address of `INT_IP` (in example 10.100.1.85)

This is needed not to route later media from asterisk to rtpengine via external address. (kamailio, rtpengine and asterisk are on the same host)

**Comment by rfuchs** [comment]
If you have a need for both, the preferred way is to use named interfaces, such as `--interface=int/$INT_IP --interface=ext/$INT_IP!$EXT_IP` and then use the `direction=` option to tell rtpengine which one to use.

If using the internal address only is sufficient, all you need to use is `--interface=$INT_IP` and don't even mention the external one.

**Comment by vance-od** [comment]
Thank you for suggestion, the first case above is looks like what I need. 
What I used before was incorrect?
Will give it a shot and come back with results
Many thanks!!!

**Comment by vance-od** [comment]
Tested it with `--interface=int/$INT_IP --interface=ext/$INT_IP!$EXT_IP` .

when INVITE  from webrtc client comes I do:
`rtpengine_manage("trust-address replace-origin replace-session-connection direction=ext direction=int ICE=remove RTP/AVP");`
result - INT_IP in SDP

reply to Webrtc client, I do:
`rtpengine_manage("trust-address replace-origin replace-session-connection ICE=force RTP/SAVPF");`
result - in candidates list only candidate with EXT_IP. 

Is there a way how to get both `INT_IP/EXT_IP` IPs in candidates? 

Or while INVITE processing check if user is not behind NAT call with `direction=int direction=int` , otherwise (behind NAT) call with `direction=ext direction=int` ?

**Comment by rfuchs** [comment]
If you want to get both addresses as candidates, you make one logical interface with both, e.g. `--interface=ext/$INT_IP --interface=ext/$INT_IP!$EXT_IP`

**Comment by vance-od** [comment]
This looks like what we needed! 
Currently provide additional testing also with cloud systems, will report the result and close the issue when finish.

**Comment by vance-od** [comment]
Hi Richard!
having tested running rtpengine with the new keys:
`--interface=ext/$INT_IP --interface=ext/$INT_IP!$EXT_IP`
with local server - it works, everything as I expect.

But I have difficulties if server is placed in cloud.
the call script is the same:
`webrtc client -> kamailio+rtpengine -> asterisk -> kamailio -> legacy sip phone`

Making such call, after answer processing, in logs (and in tcpdump) I see that ICE succeeded, but DTLS exchange does not start (I see no DTLS packets in dump, and nothing logged). Log for such call:
https://gist.github.com/vance-od/89bf6f92a11bc79bb21d9c74323a5f2a

if I change keys to `--interface=ext/$INT_IP!$EXT_IP` - than DTLS happens and I have media, appropriate log:
https://gist.github.com/vance-od/fc9e4609496301b2b1b65824f56cf5f7

another question, what could mean this logs (I am getting it in good and bad cases as well)?:
`Jun 15 12:26:40   rtpengine[30307]: [smgj3inrrqlr94okb3q3 port 13080] Unknown STUN attribute: 0xc057`

Thanks in advance for the help!

**Comment by rfuchs** [comment]
Can you tell if rtpengine is sending DTLS packets in this case? You'd have to do a packet dump to see them.

**Comment by vance-od** [comment]
making dump for issuing case, I see no DTLS packets sent/received

**Comment by vance-od** [comment]
Hi Richard!
Any ideas?

**Comment by rfuchs** [comment]
No, not really. DTLS should start right after ICE finishes.

**Comment by vance-od** [comment]
Hi again! 
The problem with DTLS is described by @vitalikvoip in [another thread](https://github.com/sipwise/rtpengine/issues/257).
This one is closed. 
Thanks for suggestions!
