### ISSUE TITLE
RTP packets from Yate Client softphone are not recognized

### ISSUE THREAD

**Issue by mbike2000ru** [sipwise/rtpengine#246]
Hi

RTPENGINE + KAMAILIO

Internal call between 2 yate softphones.

In tcpdump I see the first RTP packet is the packet with version 0 (actually this packet containes only version = 0 and data = 0000
The subsequent packets have version 2.

in /var/log/messages I see the followingg error:
Error parsing RTP header: short packet (header) and no audio is passed through.

Is it possible to fix it?

**Comment by rfuchs** [comment]
I don't think this message has any relevance on your issue. Packets are processed and forwarded even if they're not RTP.

**Comment by mbike2000ru** [comment]
I compared the subsequent packets to the RFC3550 - they comply to it. Only the first packet does not comply to it. The second RTP packet has a MARK. I saw RTP packets when I turned off the RTPENGINE( the freeswitch handles these RTP packets and I here audio).

The jnly short packet is the very first RTP packet.

**Comment by rfuchs** [comment]
Like I said - whether packets are RTP or not is not really relevant. If you get no audio forwarding, the problem must be elsewhere. Run rtpengine with log level 7 and check the debug log for more information.

**Comment by mbike2000ru** [comment]
[rtpengine_log.txt](https://github.com/sipwise/rtpengine/files/331294/rtpengine_log.txt)

Hi
I use --log-level=7
I attached the log file and I see:
 Final packet stats:
Jun 24 06:17:53 kazootest2 rtpengine[17342]: [304e0474-39d3-11e6-96c4-8d5655cb20a9] --- Tag '414130839', created 1:19 ago for branch '', in dialogue with '445HNXgHHyrKD'
Jun 24 06:17:53 kazootest2 rtpengine[17342]: [304e0474-39d3-11e6-96c4-8d5655cb20a9] ------ Media #1 (audio over RTP/AVP) using unknown codec
Jun 24 06:17:53 kazootest2 rtpengine[17342]: [304e0474-39d3-11e6-96c4-8d5655cb20a9] --------- Port 30040 <>   10.11.101.241:31554, 0 p, 0 b, 0 e, 1466748994 last_packet
Jun 24 06:17:53 kazootest2 rtpengine[17342]: [304e0474-39d3-11e6-96c4-8d5655cb20a9] --------- Port 30041 <>   10.11.101.241:31555 (RTCP), 0 p, 0 b, 0 e, 1466748994 last_packet
Jun 24 06:17:53 kazootest2 rtpengine[17342]: [304e0474-39d3-11e6-96c4-8d5655cb20a9] --- Tag '445HNXgHHyrKD', created 1:19 ago for branch '', in dialogue with '414130839'
Jun 24 06:17:53 kazootest2 rtpengine[17342]: [304e0474-39d3-11e6-96c4-8d5655cb20a9] ------ Media #1 (audio over RTP/AVP) using unknown codec
Jun 24 06:17:53 kazootest2 rtpengine[17342]: [304e0474-39d3-11e6-96c4-8d5655cb20a9] --------- Port 30026 <>          (null):0    , 0 p, 0 b, 0 e, 1466748994 last_packet
Jun 24 06:17:53 kazootest2 rtpengine[17342]: [304e0474-39d3-11e6-96c4-8d5655cb20a9] --------- Port 30027 <>          (null):0     (RTCP), 0 p, 0 b, 0 e, 1466748994 last_packet
Jun 24 06:17:53 kazootest2 rtpengine[17342]: [988053154@kazootest2.siplabs.local] Final packet stats:
Jun 24 06:17:53 kazootest2 rtpengine[17342]: [988053154@kazootest2.siplabs.local] --- Tag '683806444', created 1:25 ago for branch '', in dialogue with '3UcSK2ZDmN20H'
Jun 24 06:17:53 kazootest2 rtpengine[17342]: [988053154@kazootest2.siplabs.local] ------ Media #1 (audio over RTP/AVP) using unknown codec
Jun 24 06:17:53 kazootest2 rtpengine[17342]: [988053154@kazootest2.siplabs.local] --------- Port 30008 <>   10.11.101.241:48674, 1 p, 4 b, 0 e, 1466748994 last_packet
Jun 24 06:17:53 kazootest2 rtpengine[17342]: [988053154@kazootest2.siplabs.local] --------- Port 30009 <>   10.11.101.241:51167 (RTCP), 12 p, 332 b, 0 e, 1466749043 last_packet
Jun 24 06:17:53 kazootest2 rtpengine[17342]: [988053154@kazootest2.siplabs.local] --- Tag '3UcSK2ZDmN20H', created 1:25 ago for branch '', in dialogue with '683806444'
Jun 24 06:17:53 kazootest2 rtpengine[17342]: [988053154@kazootest2.siplabs.local] ------ Media #1 (audio over RTP/AVP) using PCMU/8000
Jun 24 06:17:53 kazootest2 rtpengine[17342]: [988053154@kazootest2.siplabs.local] --------- Port 30000 <>   10.11.101.104:26378, 1805 p, 454860 b, 0 e, 1466749043 last_packet
Jun 24 06:17:53 kazootest2 rtpengine[17342]: [988053154@kazootest2.siplabs.local] --------- Port 30001 <>   10.11.101.104:26379 (RTCP), 11 p, 584 b, 0 e, 1466749039 last_packet

This is the stats of the failed call.

**Comment by mbike2000ru** [comment]
in stats I see:
Media #1 (audio over RTP/AVP) using unknown codec
--------- Port 30040 <>   10.11.101.241:31554, 0 p, 0 b, 0 e, 1466748994 last_packet
does it mean that no packets received on this port?

**Comment by mbike2000ru** [comment]
in the log file:
port 30008] Error parsing RTP header: short packet (header)
Tag '683806444', created 1:25 ago for branch '', in dialogue with '3UcSK2ZDmN20H'
 ------ Media #1 (audio over RTP/AVP) using unknown codec
 --------- Port 30008 <>   10.11.101.241:48674, 1 p, 4 b, 0 e, 1466748994 last_packet

The port 30008 received something that caused this error.

**Comment by mbike2000ru** [comment]
here is what I think:
I would search for the first RTP packet with the Mark field, 
The daemon may give this error in the syslog but why not continue searching for subsequent packets
say, for example, - limit it to 5 attempts to find a correct RTP packet

**Comment by rfuchs** [comment]
I already explained that this error has nothing to do with your issue. Packets are handled and forwarded even if they're not recognized as RTP.

You're correct that the final stats indicate that simply nothing was received on these ports except the one non-RTP packet. Nothing else was received, so nothing could be forwarded. Perhaps there's a networking or firewall problem.

The log you posted doesn't really show all messages. I'm guessing that your syslogd filters out debug-level messages.

**Comment by mbike2000ru** [comment]
Ok,
yes, rsyslog debug was filtered, so I turned it on and I saw:
"ICE role conflict detected", so ICE=remove in rtpengine_manage  - fixed it.
The Voice is ok now.
