### ISSUE TITLE
Recording file is not recovered with redis

### ISSUE THREAD

**Issue by egreenmachine** [sipwise/rtpengine#254]
When using redis with call recording, the recording aspect of the call is not recovered when rtpengine restarts after a failure. I believe that this should be recovered when redis recovers the call.

**Comment by rfuchs** [comment]
What's the plan here? The basic data (filenames, metadata) can obviously be stored and recovered, but not the data from the pcap itself nor the metadata file obviously. Is it enough to just restore the status and then continue as if nothing happened?

**Comment by egreenmachine** [comment]
The call data is sent to libpcap as it comes in. So recovering the basic data into the call object and building a new pcap-writer to the pcap that was previously used (assuming there are no libpcap locks) should recover the recording.
