### ISSUE TITLE
Confirm documentation for call recording

### ISSUE THREAD

**Issue by digipigeon** [sipwise/rtpengine#261]
I see that some call recording features are been implemented, great. However can we have some clarification:

Does this activate on the `start recording` message from the SIP Server. Or is this implemented as always on recording?

The README.md page still says "Recording of media streams" is not yet supported, is the pcap and call recording separate things, or is the README.md just a bit behind?

Where is the best place to find out more about this new feature?
Thank you.

**Comment by egreenmachine** [comment]
The "Recording of media streams" is outdated for the master branch. For call recording to work you must have the `--recording-dir` option enabled. https://github.com/sipwise/rtpengine#userspace-daemon. Once that is enabled you must then send the `record-call=yes` option with each offer from the sip proxy (on calls that you want to record). https://github.com/sipwise/rtpengine#userspace-daemon.

I hope you find this helpful.

**Comment by rfuchs** [comment]
I'm working on various extensions to the current call recording framework, which will include support for the `start recording` message. It will be merged to master in a few weeks when it's ready.
