### ISSUE TITLE
ZRTP passthrough

### ISSUE THREAD

**Issue by efendizadeh** [sipwise/rtpengine#264]
Dear developers,

Can not find any place to ask you question regarding to ZRTP. Does rtpengine passthrough ZRTP? 
And second question is that, we are using custom client with XOR-ed RTP (RTP packet is just a couple of bits and does not look like a RTP) can we use rtpengine to relay this XOR-ed packet between clients? The same method we are using for RTCP too.

**Comment by rfuchs** [comment]
It should work for both use cases. Rtpengine doesn't really care much about what the packets it forwards really are, RTP or something else.
