### ISSUE TITLE
No audio with Chrome 52

### ISSUE THREAD

**Issue by charlesrchance** [sipwise/rtpengine#265]
Chrome 52 has recently been rolled out and things appear to be broken somehow:

```
Aug 10 19:36:10 acc03 rtpengine[24401]: [ofnl5rr51mg5lfvd8nr2 port 16340] DTLS error: 1 (sslv3 alert handshake failure)
Aug 10 19:36:10 acc03 rtpengine[24401]: [ofnl5rr51mg5lfvd8nr2 port 16340] DTLS error on local port 16340
```

Exactly the same client/server configuration works fine with Chrome 51:

```
Aug 10 19:36:56 acc03 rtpengine[24401]: [par15v327dfv19fujg23 port 16414] DTLS: Peer certificate accepted
Aug 10 19:36:56 acc03 rtpengine[24401]: [par15v327dfv19fujg23 port 16414] DTLS-SRTP successfully negotiated
Aug 10 19:36:56 acc03 rtpengine[24401]: [par15v327dfv19fujg23 port 16414] DTLS-SRTP successfully negotiated

```

I wonder if it has anything to do with this: https://developers.google.com/web/updates/2016/06/webrtc-ecdsa?hl=en

Although it seems rtpengine should support ECDSA keys just fine: https://github.com/sipwise/rtpengine/commit/21e1fb680762f421e05fab036f8138b2276f5037

**Comment by egreenmachine** [comment]
Try updating your version of openssl and recompiling rtpengine. That fixed it for us.

**Comment by charlesrchance** [comment]
Thanks, will try that - which version of openssl did you update to?

**Comment by egreenmachine** [comment]
We are running OpenSSL 1.0.1e-51 on Centos. I believe 1.0.1g and later has the correct ciphers for debian/ubuntu.

**Comment by charlesrchance** [comment]
That fixed it, thank you :+1: 

Sorry for the prematurely raised issue.
