### ISSUE TITLE
Rtpengine response wrong command on Kamailio's ping

### ISSUE THREAD

**Issue by ovoshlook** [sipwise/rtpengine#266]
Hi. kamailio 4.4.2 (x86_64/linux) ab9403
rtpengine version
4.5.1.0+0~mr4.5.1.0 git-mr4.5-1fbb29f

Gor error when starting kamailio

Aug 12 08:01:02 58627 kamailio[28111]: ERROR: rtpengine [rtpengine.c:2546]: rtpp_test(): proxy responded with invalid response
Aug 12 08:01:02 58627 rtpengine[28047]: WARNING: Failed to properly parse UDP command line '0_28116_0 d7:command4:pinge' from 127.0.0.1:32926, using fallback RE

**Comment by rfuchs** [comment]
Sorry for the late reply, I'm guessing you figured it out already. Substitute `--listen-udp` with `--listen-ng` on the command line.
