### ISSUE TITLE
interface configuration question

### ISSUE THREAD

**Issue by durd** [sipwise/rtpengine#270]
Hi,

We are using:

```
root@<machine>:~# rtpengine --version
4.6.0.0+0~mr5.0.0.0 git-master-2e5e2ec
```

on 2 virtual servers. One has both ipv4 and ipv6 and the other only has ipv4.
In Kamailio v4.3.4 and the rtpengine-module we have are using interface names "ipv4" and "ipv6" for NAT-traversal and v4v6 bridging.

Now that the one server only has ipv4, how are we supposed to configure rtpengine? Currently we have:
INTERFACES="ipv4/<same-ipv4-pub-addr> ipv4/<same-ipv4-pub-addr>"

And in Kamailio:
rtpengine_manage("direction=ipv4 direction=ipv4 address-family=IP4");

but that seems redundant, at least on the rtpengine side.
I tried only configuring one logical interface (ipv4) but got the following error:

```
Sep  2 10:20:38 <machine> rtpengine[11876]: INFO: Version 4.6.0.0+0~mr5.0.0.0 git-master-2e5e2ec shutting down
Sep  2 10:20:38 <machine> rtpengine[11985]: INFO: Generating new DTLS certificate
Sep  2 10:20:38 <machine> rtpengine[11985]: CRIT: FAILED TO CREATE KERNEL TABLE 0, KERNEL FORWARDING DISABLED
Sep  2 10:20:38 <machine> rtpengine[11986]: INFO: Startup complete, version 4.6.0.0+0~mr5.0.0.0 git-master-2e5e2ec
Sep  2 10:20:42 <machine> rtpengine[11986]: ERR: redis_notify_event_base is NULL on event base action 2
```

What we would like to do is to handle v4v4-NAT on at least both servers. We are working to get another v6-enabled server, but that is out of the scope for this issue.

Thanks!
David

**Comment by rfuchs** [comment]
You don't need any special configuration for IPv4 NAT traversal unless rtpengine itself is behind NAT. Just configure a single interface with the IPv4 address. It doesn't even have to be named and no special options need to be given in Kamailio config.

**Comment by durd** [comment]
Hmm, I did test just having one (named) interface in rtpengine. And got the critical error above, rtpengine not able to create the kernel table.
I did still have the configuration in Kamailio if that made a difference.
I'll give having no configuration a try. I'm assuming rtpengine will bridge v4v6 aswell without configuration?

**Comment by rfuchs** [comment]
Not being able to create the kernel table is unrelated to any interface configuration. Make sure the kernel module is loaded and that the table doesn't already exist. That being said, the daemon should function normally even if you do get this error, just without the benefit of kernel-space packet forwarding.

Bridging between IPv4 and IPv6 does happen automatically, but you may have to tell rtpengine in the initial offer to offer a particular address family. E.g. an offer coming from a v4 client going to a v6-only client would require an `address-family=IP6` option, otherwise rtpengine would use the IPv4 address because it doesn't know that the client needs IPv6.

**Comment by durd** [comment]
Okay, the kernel module is loaded. It's loaded dynamically and not added to /etc/modules, but that shouldn't be a problem, right?
The CRIT-error occurs when I restart the daemon from init.d, if I restart again I only get the ERR-error.
If, after getting a CRIT, I stop the daemon the table disappears and the module is unloaded. The same ERR also occurs if I use force-reload instead of restart, but not a CRIT.
If I just stop the daemon (after not getting a CRIT), the module stays loaded and the table is still there according to /proc/rtpengine/list:
```
root@<machine>:~# cat /proc/rtpengine/list
0
root@<machine>:~# /etc/init.d/ngcp-rtpengine-daemon stop
[ ok ] Stopping ngcp-rtpengine-daemon (via systemctl): ngcp-rtpengine-daemon.service.
root@<machine>:~# cat /proc/rtpengine/list
cat: /proc/rtpengine/list: No such file or directory
root@<machine>:~# /etc/init.d/ngcp-rtpengine-daemon start
[ ok ] Starting ngcp-rtpengine-daemon (via systemctl): ngcp-rtpengine-daemon.service.
root@<machine>:~# cat /proc/rtpengine/list
0
root@<machine>:~# /etc/init.d/ngcp-rtpengine-daemon stop
[ ok ] Stopping ngcp-rtpengine-daemon (via systemctl): ngcp-rtpengine-daemon.service.
root@<machine>:~# cat /proc/rtpengine/list
0
root@<machine>:~# cat /proc/rtpengine/0/status
Refcount:    1
Control PID: 0
Targets:     2 (woops)
root@<machine>:~# /etc/init.d/ngcp-rtpengine-daemon start
[ ok ] Starting ngcp-rtpengine-daemon (via systemctl): ngcp-rtpengine-daemon.service.
root@<machine>:~# cat /proc/rtpengine/list
0
```

Well, as you said, at least I know the error had nothing to do with the interface configuration :)
I also now know that a full stop is needed before starting again if I don't want to loose the kernel module or have an error message :)

```
root@<machine>:~# date; lsmod |grep RTPE; cat /proc/rtpengine/0/status; /etc/init.d/ngcp-rtpengine-daemon restart; lsmod |grep RTPE; cat /var/log/rtpengine.log | grep CRIT | tail -1; cat /proc/rtpengine/0/status
Fri Sep  2 20:49:57 CEST 2016
xt_RTPENGINE           26683  3
x_tables               27308  5 ip6table_filter,ip_tables,xt_RTPENGINE,iptable_filter,ip6_tables
Refcount:    1
Control PID: 14252
Targets:     0
[ ok ] Restarting ngcp-rtpengine-daemon (via systemctl): ngcp-rtpengine-daemon.service.
xt_RTPENGINE           26683  3
x_tables               27308  5 ip6table_filter,ip_tables,xt_RTPENGINE,iptable_filter,ip6_tables
Sep  2 20:49:57 <machine> rtpengine[14342]: CRIT: FAILED TO CREATE KERNEL TABLE 0, KERNEL FORWARDING DISABLED
Refcount:    1
Control PID: 0
Targets:     0
```

I'm not sure if you think this still is an issue, if not please do close this "issue".

I really truly do appreciate you answering on my issue, rtpengine is just so amazing coming from rtpproxy. The first few days I started running rtpengine I was giggling while watching all the stats coming in the log-file and /proc.

**Comment by rfuchs** [comment]
Can you try the following. Edit the init.d script and find all instances of `set +e`. Comment out each one. The execute `set -x` on the shell locally before re-trying the start/stop/restart sequence. I'm curious as to which step fails.

**Comment by durd** [comment]
Whatever I tried the output was pretty much the same:
```
root@<machine>:~# set +x
root@<machine>:~# cat /proc/rtpengine/0/list
root@<machine>:~# /etc/init.d/ngcp-rtpengine-daemon restart
[....] Restarting ngcp-rtpengine-daemon (via systemctl): ngcp-rtpengine-daemon.serviceWarning: Unit file of ngcp-rtpengine-daemon.service changed on disk, 'systemctl daemon-reload' recommended.
. ok
```

Could it be as simple as that I'm not using systemctl to restart/start/stop?

**Comment by rfuchs** [comment]
`set -x` not `set +x`

**Comment by rfuchs** [comment]
You may have to add it to the beginning of the init.d script in fact

**Comment by durd** [comment]
Wow sorry, I'm getting tired...
I tried restart/stop/start and pasted everything here - http://pastebin.com/JVQvktML

**Comment by rfuchs** [comment]
Cleaning up old tickets
