### ISSUE TITLE
force-relay new candidate after end-of-candidates

### ISSUE THREAD

**Issue by firstlevelIT** [sipwise/rtpengine#271]
I noticed that force relay insert the new candidate at the end of sdp, after the line

`a=end-of-candidates`

so SIPml5 on firefox ignores the new candidate.
Is it an issue?

**Comment by rfuchs** [comment]
Possibly, even though that attribute should only appear in a re-invite. It's worth fixing anyway.

**Comment by rfuchs** [comment]
Please apply the patch referenced above and try again
