### ISSUE TITLE
Media fails when 2 ICE/DTLS clients streams become kernelized

### ISSUE THREAD

**Issue by etamme** [sipwise/rtpengine#273]
$rtpengine -v 
$git-mr4.5.1-ac7c911

built from 

commit ac7c911657c381422997202946f193986593d986

We have encountered a strange issue where rtpengine is setup as a relay (force-relay) between two  browsers (happens with both chrome and firefox), where the initial call sets up fine, media (audio and video) flows in both directions and can be seen and heard.  As soon as rtpengine kernelizes the call,  audio and video can no longer be seen or heard, but we have observed that bi-directional rtp is still flowing.  

Here is a complete gist of debug log output during the call. https://gist.github.com/etamme/135cae26f6b5a4fba81bc7d4840b8bdf  

If we start rtpengine without kernel support (kernel table -1) the streams stay up for the duration, and can be seen and heard for the duration.

We are able to do kernelization between two clients that are doing plain rtp, e.g. two desk phones where rtpengine is in the middle, and even when we go from a ice/dtls <-> plain rtp user agent.  This issue only seems to be occuring when both clients are doing ice and dtls and rtpengine is acting as a relay.

**Comment by rfuchs** [comment]
Can you do a tcpdump/pcap that includes the relevant media packets?

**Comment by etamme** [comment]
Here is a pcap capturing all the traffic on our realtime interface (rtp)

https://owncloud.uphreak.com/index.php/s/Fyc9N2oinKXFCKL

and here is the log for the call.

https://gist.github.com/etamme/02677e99faaeb1aff9aa8c3c3d212a73

As described, audio/video sets up and is seen and heard on both ends, then stops as soon as the streams are kernelized.  You can see in the pcap that rtp continues to flow.  The relay is .195,  the two peers are .17 and .238.  I would very much appreciate any thoughts on where to start digging on this.

**Comment by rfuchs** [comment]
Looks like a bug on the kernel forwarding code. I notice that it seems to change the packet sizes, i.e. truncate them. Prior to kernelizing, in/out packets have the same size in the pcap (e.g. packets 1142/1143 or 1148/1152), but after kernelizing, the size changes (e.g. 3461/3462).

Please post the relevant sections from /proc/rtpengine/$ID/list with the streams kernelized.

**Comment by etamme** [comment]
After kernelizing, this is the contents of /proc/rtpengine/0/list.  We see errors only on calls with video, if we do audio only we dont see the error count, but the same issue still exists.


here is a video call:

$cat /proc/rtpengine/0/list 
local inet4 38.109.82.195:50056
       src inet4 38.109.82.195:50076
       dst inet4 50.199.232.225:51740
    stats:              9641847 bytes,                12491 packets,                 8872 errors
        RTP payload type   0:                    0 bytes,                    0 packets
        RTP payload type   8:                    0 bytes,                    0 packets
        RTP payload type   9:                    0 bytes,                    0 packets
        RTP payload type  13:                    0 bytes,                    0 packets
        RTP payload type 103:                    0 bytes,                    0 packets
        RTP payload type 104:                    0 bytes,                    0 packets
        RTP payload type 105:                    0 bytes,                    0 packets
        RTP payload type 106:                    0 bytes,                    0 packets
        RTP payload type 111:               370173 bytes,                 3563 packets
        RTP payload type 126:                    0 bytes,                    0 packets
    option: rtcp-mux
local inet4 38.109.82.195:50076
       src inet4 38.109.82.195:50056
       dst inet4 50.198.204.238:54401
    stats:             15590699 bytes,                17318 packets,                13700 errors
        RTP payload type   0:                    0 bytes,                    0 packets
        RTP payload type   8:                    0 bytes,                    0 packets
        RTP payload type   9:                    0 bytes,                    0 packets
        RTP payload type  13:                    0 bytes,                    0 packets
        RTP payload type 103:                    0 bytes,                    0 packets
        RTP payload type 104:                    0 bytes,                    0 packets
        RTP payload type 105:                    0 bytes,                    0 packets
        RTP payload type 106:                    0 bytes,                    0 packets
        RTP payload type 111:               379816 bytes,                 3561 packets
        RTP payload type 126:                    0 bytes,                    0 packets
    option: rtcp-mux


and here is an audio only call:

$cat /proc/rtpengine/0/list 
local inet4 38.109.82.195:50124
       src inet4 38.109.82.195:50140
       dst inet4 50.199.232.225:58794
    stats:                90888 bytes,                  894 packets,                    0 errors
        RTP payload type   0:                    0 bytes,                    0 packets
        RTP payload type   8:                    0 bytes,                    0 packets
        RTP payload type   9:                    0 bytes,                    0 packets
        RTP payload type  13:                    0 bytes,                    0 packets
        RTP payload type 103:                    0 bytes,                    0 packets
        RTP payload type 104:                    0 bytes,                    0 packets
        RTP payload type 105:                    0 bytes,                    0 packets
        RTP payload type 106:                    0 bytes,                    0 packets
        RTP payload type 111:                89768 bytes,                  880 packets
        RTP payload type 126:                    0 bytes,                    0 packets
    option: rtcp-mux
local inet4 38.109.82.195:50140
       src inet4 38.109.82.195:50124
       dst inet4 50.198.204.238:59562
    stats:                94009 bytes,                  894 packets,                    0 errors
        RTP payload type   0:                    0 bytes,                    0 packets
        RTP payload type   8:                    0 bytes,                    0 packets
        RTP payload type   9:                    0 bytes,                    0 packets
        RTP payload type  13:                    0 bytes,                    0 packets
        RTP payload type 103:                    0 bytes,                    0 packets
        RTP payload type 104:                    0 bytes,                    0 packets
        RTP payload type 105:                    0 bytes,                    0 packets
        RTP payload type 106:                    0 bytes,                    0 packets
        RTP payload type 111:                92861 bytes,                  880 packets
        RTP payload type 126:                    0 bytes,                    0 packets
    option: rtcp-mux

**Comment by rfuchs** [comment]
What kernel version are you using?

**Comment by etamme** [comment]
I copied over thew new xt_RTPENGINE.ko from the same commit build as the daemon.  Is there a way to verify that kernel module version matches the daemon version?

**Comment by rfuchs** [comment]
It prints the version to kernel log when the module is loaded. But I'm asking about the version of your kernel, not the module.

**Comment by etamme** [comment]
Ah sorry:

$uname -a
Linux media-relay3-0.55-broad-1.jnctn.net 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rfuchs** [comment]
Looks like there's a bug dealing with RTP header extensions in the kernel code. Try applying the patch referenced above and try again.

**Comment by etamme** [comment]
Thanks, I've built the patch, just trying to get a remote person to do a test call with.  I will advise after that.

**Comment by etamme** [comment]
I've updated the module and fully rebooted the box to make sure everything just unloads/loads cleanly, however we are experiencing the same issue still.

**Comment by etamme** [comment]
I verified that the module loaded is the same as the module that i just built:

```
$modinfo xt_RTPENGINE
filename:       /lib/modules/3.10.0-327.10.1.el7.x86_64/extra/xt_RTPENGINE.ko
license:        GPL
rhelversion:    7.2
srcversion:     B996A1F25A3119D5F8A528A
depends:        
vermagic:       3.10.0-327.10.1.el7.x86_64 SMP mod_unload modversions 
parm:           proc_uid:rtpengine procfs tree user id (uint)
parm:           proc_gid:rtpengine procfs tree group id (uint)


$md5sum /lib/modules/3.10.0-327.10.1.el7.x86_64/extra/xt_RTPENGINE.ko
81ac3a5919d23e3e2e3610f7ebe2ad78  /lib/modules/3.10.0-327.10.1.el7.x86_64/extra/xt_RTPENGINE.ko

$md5sum /usr/local/src/rtpengine/kernel-module/xt_RTPENGINE.ko 
81ac3a5919d23e3e2e3610f7ebe2ad78  /usr/local/src/rtpengine/kernel-module/xt_RTPENGINE.ko

```

**Comment by rfuchs** [comment]
Hm that's curious. Can you confirm through the pcap/Wireshark that it's still truncating packets by 8 bytes?

**Comment by etamme** [comment]
Yes this does appear to still be truncating packets by 8 bytes.

Here is a pcap from the patched relay: https://owncloud.uphreak.com/index.php/s/z3OXzxfUhcHo62m

**Comment by rfuchs** [comment]
That's strange, because for me, this patch fixes the problem when replaying one of the packets from your pcap.

Before patch:

  7 480.771227021 14:46:54.569104492 192.168.1.99 -> 192.168.1.99 UDP 1156 34110 → 9876  Len=1112
  8 480.771307625 14:46:54.569185096 192.168.1.99 -> 192.168.1.90 UDP 1148 1234 → 6543  Len=1104


After patch:

  9 547.388516690 14:48:01.186394161 192.168.1.99 -> 192.168.1.99 UDP 1156 46078 → 9876  Len=1112
 10 547.388552000 14:48:01.186429471 192.168.1.99 -> 192.168.1.90 UDP 1156 1234 → 6543  Len=1112

**Comment by etamme** [comment]
Looks like, for whatever reason, the code i compiled was not being loaded.  After re-testing on two different relays we have confirmed that kernelization is working between two ice/dtls user agents with this fix.

Thanks very much Richard.
