### ISSUE TITLE
Q: will/does rtpegine handle/adjust audio levels?

### ISSUE THREAD

**Issue by durd** [sipwise/rtpengine#276]
Hi,

We are experiencing distortion when making SIP-phonecalls to a certain brand of IP-encoders.
Today I got the question if rtpengine could adjust audio-levels? I'm pretty sure that rtpengine currently can't do that, but will rtpengine ever be able to do this?

Thanks in advance,
David

**Comment by rfuchs** [comment]
As you correctly thought, right now the answer is a categorical 'no'. It would be possible when full transcoding support finally comes around, but as of now there are no concrete plans for that.
