### ISSUE TITLE
[HELP] How to control RTP ENGINE

### ISSUE THREAD

**Issue by thanhthuy40** [sipwise/rtpengine#278]
Dear SipWise, 
i'm try to control media proxy ng with java to client, but i try send command 
{"command":"ping"} follow the example of readme. but i'm allway receiver messsage
WARNING: Failed to properly parse UDP command line '{"command":"ping"}' from 192.168.146.83:36988, using fallback RE
Can you help me write some example to use it?
P/s : I send back the current configuration of me
rtpengine --interface=192.168.146.83!10.42.0.1 --listen-udp=192.168.146.83:2222 --listen-ng=192.168.146.83:2223 --tos=184 --log-level=6

Ip Public : 10.42.0.1
Ip private : 192.168.146.83
Br.

**Comment by rfuchs** [comment]
Drop the `--listen-udp=` option and use port 2222 for `--listen-ng`

Or instruct your SIP proxy to send to port 2223 instead of 2222.

**Comment by thanhthuy40** [comment]
Hi rfuchs, 
thank for response, i will try again with port 2223 , but when i try send a message over JSON is
{"command":"ping"} but no have any thing response.
In this case i don't want kamailio control rtpengine i'm try using a program client to control and modifine the SDP with brige mode RTP with rtpengine.

Do you have any example about it or description how to intergrated with rtpengine because i try search but no have any description about protocol control it

**Comment by rfuchs** [comment]
It's not JSON. Look at `rtpengine-ng-client` in the `utils/` directory for an example of how to send and receive control messages.

**Comment by thanhthuy40** [comment]
So sad i don't understand python !

**Comment by rfuchs** [comment]
You're in luck then, because this is Perl, not Python :)

The protocol is described in detail in the readme: https://github.com/sipwise/rtpengine#the-ng-control-protocol

All information to get you started is there.

**Comment by thanhthuy40** [comment]
Thanks for reply!
