### ISSUE TITLE
[HELP] INVITE without SDP

### ISSUE THREAD

**Issue by AceAsket** [sipwise/rtpengine#279]
How match offer and answer if rtpengine response - No SDP body in message

example INVITE:
INVITE sip:2404987241@192.168.0.111:5060 SIP/2.0
Via:SIP/2.0/UDP as.iop1.broadworks.net;branch=z9hG4bKBroadWorks.iop1tok-192.168.0.111V5060-0-383670762-1382704079-1476088607699-
From:<sip:7242@as.iop1.broadworks.net;user=phone>;tag=1382704079-1476088607699-
To:<sip:2404987241@as.iop1.broadworks.net>
Call-ID:BW043647699101016-1984628412@192.168.1.111
CSeq:383670762 INVITE
Contact:<sip:as.iop1.broadworks.net>
Supported:100rel,timer
Allow:ACK,BYE,CANCEL,INVITE,OPTIONS,PRACK,REFER,NOTIFY,UPDATE,INFO
Call-Info:<sip:as.iop1.broadworks.net>;answer-after=0;appearance-index=1
Recv-Info:x-broadworks-client-session-info
Accept:application/btbc-session-info,application/dtmf-relay,application/media_control+xml,application/sdp,application/vnd.etsi.aco+xml,application/vnd.etsi.aoc+xml,application/vnd.etsi.sci+xml,multipart/mixed
Min-SE:120
Session-Expires:300;refresher=uac
Max-Forwards:70
Content-Length:0

**Comment by egreenmachine** [comment]
SDP negotiation is its own offer answer. You need to call `rtpengine_offer` and `rtpengine_answer` on the sdp offer answer, not the sip session offer/answer. @etamme has a [federated sip, opensips config](https://github.com/etamme/federated-sip/blob/master/core/opensips.cfg.erb#L515) that supports this.

**Comment by AceAsket** [comment]
Thanks
