### ISSUE TITLE
Invalid SDP from RTPEngine.

### ISSUE THREAD

**Issue by mvenkatesh431** [sipwise/rtpengine#285]
Hi all, 
   I am using RTPEngine and OpenSIPS, Everything working good. But i just updated RTPEngine and OpenSIPS to latest git versions. After that I am getting following error. 
 **DOMException: Failed to parse SessionDescription.  Invalid SDP line.**

I am calling RTPEngine offer on invite then RTPEngine giving the reply back, But that reply SDP have problem. It is including two **a= elements** in one line. Please see below.

**a=ssrc:2868484751 label:08b2bfc7-c88d-47c2-9c7a-e46e272f4533a=sendrecv.**

Here is the full trace between the OpenSIPS and RTPEngine.

U 127.0.0.1:50987 -> 127.0.0.1:60000
12046_1 d3:sdp1953:v=0.
o=- 7167002140681008373 2 IN IP4 127.0.0.1.
s=-.
t=0 0.
a=group:BUNDLE audio.
a=msid-semantic: WMS WN08KreSDvD4je0y6FG7PcMua0dljqDNd8Bs.
m=audio 44790 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 126.
c=IN IP4 111.93.2.52.
a=rtcp:32555 IN IP4 111.93.2.52.
a=candidate:3238997571 1 udp 2122260223 192.168.36.152 55562 typ host generation 0 network-id 1 network-cost 10.
a=candidate:3238997571 2 udp 2122260222 192.168.36.152 55563 typ host generation 0 network-id 1 network-cost 10.
a=candidate:2408370867 1 tcp 1518280447 192.168.36.152 9 typ host tcptype active generation 0 network-id 1 network-cost 10.
a=candidate:2408370867 2 tcp 1518280446 192.168.36.152 9 typ host tcptype active generation 0 network-id 1 network-cost 10.
a=candidate:226628048 1 udp 1686052607 111.93.2.52 44790 typ srflx raddr 192.168.36.152 rport 55562 generation 0 network-id 1 network-cost 10.
a=candidate:226628048 2 udp 1686052606 111.93.2.52 32555 typ srflx raddr 192.168.36.152 rport 55563 generation 0 network-id 1 network-cost 10.
a=ice-ufrag:AUIe.
a=ice-pwd:nIIXvCscW2xAy6ozyvvMi/SU.
a=fingerprint:sha-256 00:57:B1:20:06:00:92:E9:84:F9:FB:DB:FB:23:5F:68:29:7C:0C:73:C9:F8:AB:9C:7B:AF:25:9E:C5:B7:99:CC.
a=setup:actpass.
a=mid:audio.
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level.
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time.
a=sendrecv.
a=rtcp-mux.
a=rtpmap:111 opus/48000/2.
a=rtcp-fb:111 transport-cc.
a=fmtp:111 minptime=10;useinbandfec=1.
a=rtpmap:103 ISAC/16000.
a=rtpmap:104 ISAC/32000.
a=rtpmap:9 G722/8000.
a=rtpmap:0 PCMU/8000.
a=rtpmap:8 PCMA/8000.
a=rtpmap:106 CN/32000.
a=rtpmap:105 CN/16000.
a=rtpmap:13 CN/8000.
a=rtpmap:126 telephone-event/8000.
a=ssrc:2868484751 cname:mppSJ4WjknGpeX1J.
a=ssrc:2868484751 msid:WN08KreSDvD4je0y6FG7PcMua0dljqDNd8Bs 08b2bfc7-c88d-47c2-9c7a-e46e272f4533.
a=ssrc:2868484751 mslabel:WN08KreSDvD4je0y6FG7PcMua0dljqDNd8Bs.
a=ssrc:2868484751 label:08b2bfc7-c88d-47c2-9c7a-e46e272f45333:ICE11:force-relay4:DTLS7:passive7:call-id20:6e6v1f08lpak4m4refhq13:received-froml3:IP411:111.93.2.52e8:from-tag10:2kh3o0ooa07:command5:offere................

U 127.0.0.1:60000 -> 127.0.0.1:50987
12046_1 d10:recordingsle3:sdp2167:v=0.
o=- 7167002140681008373 2 IN IP4 127.0.0.1.
s=-.
t=0 0.
a=group:BUNDLE audio.
a=msid-semantic: WMS WN08KreSDvD4je0y6FG7PcMua0dljqDNd8Bs.
m=audio 44790 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 126.
c=IN IP4 111.93.2.52.
a=rtcp:32555 IN IP4 111.93.2.52.
a=candidate:3238997571 1 udp 2122260223 192.168.36.152 55562 typ host generation 0 network-id 1 network-cost 10.
a=candidate:3238997571 2 udp 2122260222 192.168.36.152 55563 typ host generation 0 network-id 1 network-cost 10.
a=candidate:2408370867 1 tcp 1518280447 192.168.36.152 9 typ host tcptype active generation 0 network-id 1 network-cost 10.
a=candidate:2408370867 2 tcp 1518280446 192.168.36.152 9 typ host tcptype active generation 0 network-id 1 network-cost 10.
a=candidate:226628048 1 udp 1686052607 111.93.2.52 44790 typ srflx raddr 192.168.36.152 rport 55562 generation 0 network-id 1 network-cost 10.
a=candidate:226628048 2 udp 1686052606 111.93.2.52 32555 typ srflx raddr 192.168.36.152 rport 55563 generation 0 network-id 1 network-cost 10.
a=ice-ufrag:AUIe.
a=ice-pwd:nIIXvCscW2xAy6ozyvvMi/SU.
a=fingerprint:sha-256 00:57:B1:20:06:00:92:E9:84:F9:FB:DB:FB:23:5F:68:29:7C:0C:73:C9:F8:AB:9C:7B:AF:25:9E:C5:B7:99:CC.
a=setup:actpass.
a=mid:audio.
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level.
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time.
a=rtcp-mux.
a=rtpmap:111 opus/48000/2.
a=rtcp-fb:111 transport-cc.
a=fmtp:111 minptime=10;useinbandfec=1.
a=rtpmap:103 ISAC/16000.
a=rtpmap:104 ISAC/32000.
a=rtpmap:9 G722/8000.
a=rtpmap:0 PCMU/8000.
a=rtpmap:8 PCMA/8000.
a=rtpmap:106 CN/32000.
a=rtpmap:105 CN/16000.
a=rtpmap:13 CN/8000.
a=rtpmap:126 telephone-event/8000.
a=ssrc:2868484751 cname:mppSJ4WjknGpeX1J.
a=ssrc:2868484751 msid:WN08KreSDvD4je0y6FG7PcMua0dljqDNd8Bs 08b2bfc7-c88d-47c2-9c7a-e46e272f4533.
a=ssrc:2868484751 mslabel:WN08KreSDvD4je0y6FG7PcMua0dljqDNd8Bs.
a=ssrc:2868484751 label:08b2bfc7-c88d-47c2-9c7a-e46e272f4533a=sendrecv.
a=candidate:6oqeMtNet1RzigEs 1 UDP 16777215 X.X.X.X 50070 typ relay raddr X.X.X.X rport 50070.
a=candidate:6oqeMtNet1RzigEs 2 UDP 16777214 X.X.X.X 50071 typ relay raddr X.X.X.X rport 50071.

I am using RTPEngine git version.
rtpengine -v
git-master-50daef0

Thank you.

**Comment by rfuchs** [comment]
Looks like the incoming SDP is invalid as well. It's missing the final trailing linefeed at the end of the SDP. This is required by the SDP specification.

**Comment by mvenkatesh431** [comment]
Here is the log file with debugging.
[rtpengine sdp.txt](https://github.com/sipwise/rtpengine/files/556025/rtpengine.sdp.txt)

It might help. Thanks.

**Comment by rfuchs** [comment]
This confirms what I said above. The incoming SDP is not terminated with a final trailing newline:

`... lV#015#012a=ssrc:91323071 label:1d9e900a-96f5-4e57-b05f-3e5bf1511a04", ...`

There should be another set of `#015#012` before the closing `"`

The fix needs to be done in the client producing the incoming SDP.

**Comment by rfuchs** [comment]
It's also possible that the OpenSIPS module is erroneously truncating the SDP coming from the client when passing it to rtpengine. You can confirm this by inspecting the SIP packet itself. If that's the case, you need to take it up with the OpenSIPS developers.

**Comment by mvenkatesh431** [comment]
OpenSIPS sending invalid SDP to RTPEngine. That  is due to the present development. I rolled back my git revision to few commits back, Now it is working. Thanks for you reply Richard !!
