### ISSUE TITLE
Recording, fake ethernet header

### ISSUE THREAD

**Issue by khoegh** [sipwise/rtpengine#290]
Would it be possible to save recordings as Ethernet instead of raw IP packages?

**Comment by rfuchs** [comment]
Yes and no. A fake ethernet header could certainly be added but the contents would have to be entirely bogus as this information isn't available in userspace. Why do you ask?

**Comment by khoegh** [comment]
I would like to merge SIP data captured from kamailio with the recording.
The pcap file from kamailio is in "Ethernet" format.
I don't care if all ethernet header is all bogus

**Comment by rfuchs** [comment]
What do you think @egreenmachine ? Any problems with this or should it be an option?

**Comment by egreenmachine** [comment]
I think it would be good to have it as an option, if people want it. When we first started we had fake ethernet headers, but then went to raw because we didn't want the bogus data.

**Comment by khoegh** [comment]
The following works for me. (ipv4 only).
MAC src and dst is set to all 0's, type to ipv4, no checksum.
It should be the same as tcpdump on loopback interface.

```
--- a/daemon/recording.c
+++ b/daemon/recording.c
@@ -397,7 +397,7 @@ static char *recording_setup_file(struct recording *recording) {
        recording_path = file_path_str(recording->meta_prefix, "/pcaps/", ".pcap");
        recording->pcap.recording_path = recording_path;
 
-       recording->pcap.recording_pd = pcap_open_dead(DLT_RAW, 65535);
+       recording->pcap.recording_pd = pcap_open_dead(DLT_EN10MB, 65535);
        recording->pcap.recording_pdumper = pcap_dump_open(recording->pcap.recording_pd, recording_path);
        if (recording->pcap.recording_pdumper == NULL) {
                pcap_close(recording->pcap.recording_pd);
@@ -448,8 +448,11 @@ static void stream_pcap_dump(pcap_dumper_t *pdumper, struct packet_stream *strea
        if (!pdumper)
                return;
 
-       unsigned char pkt[s->len + MAX_PACKET_HEADER_LEN];
-       unsigned int pkt_len = fake_ip_header(pkt, stream, s);
+       unsigned char pkt[s->len + MAX_PACKET_HEADER_LEN + 14];
+       unsigned int pkt_len = fake_ip_header(pkt+14, stream, s);
+       pkt_len+=14;
+       memset(pkt, 0, 14);
+       pkt[12]=0x08;
 
        // Set up PCAP packet header
        struct pcap_pkthdr header;
```

**Comment by egreenmachine** [comment]
I would definitely prefer if it were hidden behind an options flag so that the existing behavior is default.

**Comment by rfuchs** [comment]
Yes this definitely needs to be optional and IPv6 also needs to be supported as ethernet type.
