### ISSUE TITLE
should we implement RFC 7198 for redundancy on bad connection legs?

### ISSUE THREAD

**Issue by cypa** [sipwise/rtpengine#294]
I need some redundancy for site with unstable internet connections but with 2 internet provider channels available. So I imagine if rtpengine could send same RTP stream to 2 different IPs so duplicate RTP packets to go in parallel via 2 different internet channels to client. Then client's router to mix both streams and drop duplicate packets (the later received packets dropped) to form redundant (shining and clear ;) RTP stream.
As I understand this is the case of RFC 7198.

**Comment by rfuchs** [comment]
This can probably be supported (at least for a few common cases), but right now we don't have any plans to implement it.

**Comment by oej** [comment]
I find this very interesting. We have mobile devicess with multiple SIM cards as well as Wifi now and then. We are sending multiple streams using proprietary VPN solutions now, but using 7198 would be great. Our use case is sending over different media paths to RTPengine primarily, having RTPengine sort out multiple incoming streams into one rock solid RTP stream. I guess there are similar cases where RTPengine needs to send one stream over multiple network connections outbound too.
