### ISSUE TITLE
ngcp-rtpengine-kernel vs ngcp-rtpengine-dkms

### ISSUE THREAD

**Issue by winem** [sipwise/rtpengine#296]
Hi, 

I forked the repo to fix some issues with the specs files. I would create a pull request as soon as everything works as expected on CentOS 7.2 and I'm on a good way as there is only one issue left. 

The specs file provides 3 RPMs: 
ngcp-rtpengine-4.5.0-0.el7.centos.x86_64.rpm
ngcp-rtpengine-kernel-4.5.0-0.el7.centos.x86_64.rpm
ngcp-rtpengine-debuginfo-4.5.0-0.el7.centos.x86_64.rpm

At the top of the file, it says: 
%package kernel
Summary:        NGCP rtpengine in-kernel packet forwarding
Group:          System Environment/Daemons
BuildRequires:  gcc make redhat-rpm-config iptables-devel
Requires:       iptables iptables-ipv6
Requires:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-dkms%{?_isa} = %{version}-%{release}

%description kernel
%{summary}.

%package dkms
Summary:        Kernel module for NGCP rtpengine in-kernel packet forwarding
Group:          System Environment/Daemons
BuildArch:      noarch
BuildRequires:  redhat-rpm-config
Requires:       gcc make
Requires(post): epel-release dkms
Requires(preun): epel-release dkms

%description dkms
%{summary}.

Therefore, installing the ngcp-rtpengine-kernel fails with the following error: 
Error: Package: ngcp-rtpengine-kernel-4.5.0-0.el7.centos.x86_64 (rpm.ngvoice.com)
           Requires: ngcp-rtpengine-dkms(x86-64) = 4.5.0-0.el7.centos

Aren't the dkms- and the kernel-package the same package with a different name? I read the documentation and it looks like it's just a confusion. 

Would be great if anyone can confirm my assumption. So I would fix this, too, and create the pull request. 

Best regards, 
Marcel

**Comment by mtryfoss** [comment]
I remember I had some issues as well.

My fix for the spec file:
@@ -29,7 +29,7 @@
 BuildRequires:	gcc make redhat-rpm-config iptables-devel
 Requires:	iptables iptables-ipv6
 Requires:	%{name}%{?_isa} = %{version}-%{release}
-Requires:	%{name}-dkms%{?_isa} = %{version}-%{release}
+Requires:	%{name}-dkms = %{version}-%{release}

**Comment by winem** [comment]
@mtryfoss thanks, your suggestion works. But, to be honest, I don't get WHY it works. There is still no package ngcp-rtpengine-dkms available. So this dependency can not be satisfied and I would expect it to fail. 
Would appreciate if you can tell me where I am wrong.

**Comment by mtryfoss** [comment]
I don't quite understand? The dkms-package is being created, but it's written to the noarch-directory of you rpmbuild envirentment.

> %package dkms
Summary:        Kernel module for NGCP rtpengine in-kernel packet forwarding
Group:          System Environment/Daemons
**BuildArch:      noarch <--- noarch**
BuildRequires:  redhat-rpm-config
Requires:       gcc make
Requires(post): epel-release dkms
Requires(preun): epel-release dkms

**Comment by winem** [comment]
Argh, of course! Sorry... I knew it must be something stupid! Will create a pull request with the new spec file soon. 

Thank you for your input @mtryfoss
