### ISSUE TITLE
Chrome + RTPEngine re-Invite issue.

### ISSUE THREAD

**Issue by tarakm89** [sipwise/rtpengine#298]
Hi, 

I have found lots of post regarding this issue but none of them actually able to help me resolve my issue. 

I have following setup,

Opal Sip Client(RTP/AVP) ---> kamailio(4.2.3) + RTPEngine(mr5.1.0) ---> Sip.js + Chrome (sipjs 0.7.5 + Chrome 54) 

Note: Everything is behind the NAT.

When i call from Opal sip client to sip.js i have no audio coming from chrome to opal client. 

The issue was when chrome answers the call, **then opal client sends re-INVITE to re-negotiate codecs**.  Somehow that stop trasmitting audio from chrome to opal. Chrome still receives the audio but has some noise on it.

my rtpengine_manage flags are as follow,

  **rtpengine_manage("trust-address replace-origin replace-session-connection SDES-off ICE=force RTP/SAVPF");**

Final Call Status is as follow,

Final packet stats:
Tag '14f1fa20-04b1-e611-9fa9-fcc23d084b6b', created 2:10 ago for branch '', in dialogue with 'kdn5oss46k'
 Media #1 (audio over RTP/AVP) using PCMA/8000
    Port    192.168.0.15:30036 <>    192.168.0.23:5340 , 3250 p, 561100 b, 0 e, 1480027066 last_packet
    Port    192.168.0.15:30037 <>    192.168.0.23:5341  (RTCP), 29 p, 2430 b, 0 e, 1480027063 last_packet
Tag 'kdn5oss46k', created 2:10 ago for branch '', in dialogue with '14f1fa20-04b1-e611-9fa9-fcc23d084b6b'
 Media #1 (audio over UDP/TLS/RTP/SAVPF) using PCMA/8000/1
    Port    192.168.0.15:30026 <>    192.168.0.55:57078, 3278 p, 594216 b, 0 e, 1480027066 last_packet
    Port    192.168.0.15:30027 <>    192.168.0.55:57085 (RTCP), 41 p, 1392 b, 0 e, 1480027065 last_packet

Can you please help me figure out this issue. Let me know if you guys need further information or logs.

Thanks,

**Comment by egreenmachine** [comment]
I know this is an older issue, but SIP.js 0.7.X did not really support re-invites. Upgrading to 0.8.X has full support for re-invites. That may fix your issue.
