### ISSUE TITLE
dpkg-buildpackage fails on Jessie 8.6

### ISSUE THREAD

**Issue by ishmaelen** [sipwise/rtpengine#301]
Hello

Just downloaded master branch from git and did ./debian/flavors/no_ngcp before dpkg-buildpackage.
Installed the dependencies it complained about but ended up in an error.

Linux 3.16.0-4-amd64 1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

Please see the log [here](http://pastebin.com/e9tZNgUq)

**Comment by rfuchs** [comment]
Either start from a fresh source tree checkout (i.e. delete everything first), or manually delete the `.depend` files and try again.

**Comment by egreenmachine** [comment]
`git clean -fxd` will get you to a fresh checkout.
