### ISSUE TITLE
HA: RTPEngine + Redis

### ISSUE THREAD

**Issue by markiemooster** [sipwise/rtpengine#303]
Hello,

I have an issue using RTPEngine and Redis in an HA setup.  I have two RTPEngine servers: one active and one standby, and Redis (+ kamailio) running on a third server.  Both RTPEngines reference the same Redis DB instance on the third server.  In addition to this, I have a WebRTC client running in Chrome that makes secure TLS SIP calls through an encrypted web socket via the active RTPEngine.  

I can successfully make calls from the client and SRTP traffic flows as it should.  When I reboot the active RTPEngine server the system correctly fails over to the other server and, after only a small pause (~1s), incoming audio continues to arrive.  However, approximately 15 seconds after this I hear nothing but silence.  

Here are the entries from the syslog of the failed over server: 

```
Dec  7 12:19:25 Web-iPath-Test-1 rtpengine[2674]: INFO: Established initial connection to Redis 172.19.1.113:6379
Dec  7 12:19:26 Web-iPath-Test-1 rtpengine[2674]: INFO: Redis restore time = 130 ms
Dec  7 12:19:26 Web-iPath-Test-1 rtpengine[2674]: INFO: Startup complete, version 4.5.2.3
Dec  7 12:19:26 Web-iPath-Test-1 rtpengine[2674]: WARNING: [3965bqul6rdtak0394f7 port 16501]: Error parsing RTCP header: invalid header version
Dec  7 12:19:26 Web-iPath-Test-1 rtpengine[2674]: INFO: Use Redis 172.19.1.113:6379 for notifications
Dec  7 12:19:26 Web-iPath-Test-1 rtpengine[2674]: INFO: Use Redis 172.19.1.113:6379 to subscribe to notifications
Dec  7 12:19:26 Web-iPath-Test-1 rtpengine[2674]: WARNING: [3965bqul6rdtak0394f7 port 16500]: Error parsing RTP header: invalid header version
Dec  7 12:19:41 Web-iPath-Test-1 rtpengine[2674]: WARNING: [3965bqul6rdtak0394f7 port 16500]: Error parsing RTP header: invalid header version
```

I'm wondering what could cause this 'invalid header version' error.  As the newly active server did not participate in the DTLS handshake where the certificates and keys were exchanged, I wondered whether this might have anything to do with it not having the client's certificate.  Does Redis store this information? 

If anyone could shed any light on this issue it would be greatly appreciated.

Thanks,
Mark

**Comment by rfuchs** [comment]
Redis does indeed not store the DTLS state information, as currently I have no way of extracting this out of OpenSSL and then restoring it again. So, using DTLS in a HA scenario is currently unsupported.

**Comment by markiemooster** [comment]
Thanks Richard.  Do you have any plans to add this feature to the development roadmap?

**Comment by rfuchs** [comment]
It's not a matter of whether we implement it or not. The question is if it's possible to do this at all, since the DTLS connection state is managed by OpenSSL internally.

**Comment by markiemooster** [comment]
Tricky, I understand.  Would it be possible to implement the sending of a SIP REINVITE message when RTPEngine starts and discovers ongoing calls by querying Redis?  This would trigger a renegotiation of ports, keys, etc. between the client and RTPEngine and resolve the issue for an HA failover.  If I understand it correctly, this shouldn't have an adverse affect on a single server system where the RTPEngine daemon has restarted.

**Comment by rfuchs** [comment]
Rtpengine isn't in a position to be able to send reinvites as it can only act on SDP bodies generated by the endpoints and passed through it. The only thing rtpengine could do is simply start a new DTLS session from scratch, but I don't know if that would actually work. I have a feeling it might not. At the minimum, sharing with DTLS certificate would be required (as of not, it's always generated fresh when rtpengine starts).

**Comment by Jaykah** [comment]
Hey @markiemooster ! Were you ever able to figure that one out?

Thanks!

**Comment by Jaykah** [comment]
@rfuchs - is DTLS data now stored in Redis? Also, if something is missing from RTPengine to be able to fail over WSS calls - what would that be?

Thank you!

**Comment by rfuchs** [comment]
DTLS data is still not stored in Redis as (AFAIK) it's still not possible to store and restore OpenSSL state information. The SRTP keys generated from the DTLS handshare are stored in Redis, so encrypted media can continue to flow, but the DTLS connection itself is not, so any following DTLS handshake will fail or have to be restarted.

**Comment by Jaykah** [comment]
Thanks @rfuchs ! So in the case of encrypted media vs handshake preservation - what are the implications for WSS failover? Does the need for another handshake mean that the connection (read:the call) will be dropped?

Perhaps there is a way to fail the call over to another instance, buffering the packets using tc (or similar) until the DTLS is re-negotiated so that there is no visible impact except a brief sound delay?

**Comment by rfuchs** [comment]
I'd say it depends on the client implementation. There is no need for an immediate DTLS handshake or renegotiation after a failover. Encrypted media will continue to flow with the previously established SRTP keys. However, when and if the client sends another DTLS packet, say a keepalive or to start another handshake, then this will likely result in failure. The client could then possibly drop the call. It could also just start another completely new DTLS handshake, which should work. I don't have any real-life experience with this use case though.

**Comment by telcomate** [comment]
Late to the show, but we're handling this on our client by detecting ICE disconnect event. After detecting it we restart ICE and send re-invite. It's working fine. 1 or 2 seconds audio drop because of the signaling and media negotiation, which is ok for us. Restarting or failing over RTPEngine and picking up sessions from REDIS is an edge case for us anyway.
