### ISSUE TITLE
Error configuring media output: failed to open output context

### ISSUE THREAD

**Issue by amessina** [sipwise/rtpengine#306]
See #304.

This is connecting to Asterisk's ConfBridge through RTPEngine from Firefox WSS client (audio only) using Opus with rtpengine@a3d5764 built against ffmpeg-3.1.5-1.fc25.x86_64

```
~]# cat /etc/rtpengine/rtpengine.conf 
[rtpengine]
table = 0
interface=pub/<IP4_PUB>;pub/<IP6_PUB>;priv/10.1.1.3;priv/<IP6_PUB>
listen-cli=127.0.0.1:9900
listen-ng = 127.0.0.1:12221
tos = 184
recording-dir = /var/spool/rtpengine
recording-method = proc
log-level = 6

[rtpengine-recording]
table = 0
output-format = mp3
output-mixed = 1
resample-to = 16000
mp3-bitrate = 48000
log-level = 7
```
See attached log.
[rtpengine-recording.opus.failure.txt](https://github.com/sipwise/rtpengine/files/647664/rtpengine-recording.opus.failure.txt)

**Comment by rfuchs** [comment]
Does this happen only with opus?

**Comment by amessina** [comment]
I get a slightly different error `WARNING: Failed to parse packet headers` with G722 which repeats several times, then fails.  Log attached.
[rtpengine-recording.g722.failure.txt](https://github.com/sipwise/rtpengine/files/650315/rtpengine-recording.g722.failure.txt)

**Comment by rfuchs** [comment]
I'm wondering if this is because opus advertises itself as stereo. Is there a way for you to force it to mono and retest?

**Comment by amessina** [comment]
@rfuchs, here is the mono Opus log.
[rtpengine-recording.opus.mono.failure.txt](https://github.com/sipwise/rtpengine/files/671913/rtpengine-recording.opus.mono.failure.txt)
[rtpengine-recording-gdb.txt](https://github.com/sipwise/rtpengine/files/671914/rtpengine-recording-gdb.txt)

**Comment by rfuchs** [comment]
Also, can you tell me the version of your ffmpeg and libav* packages?

**Comment by rfuchs** [comment]
Oh sorry, you mentioned that already. Nevermind.
