### ISSUE TITLE
how to test the rtpengine reponse or not

### ISSUE THREAD

**Issue by alochym01** [sipwise/rtpengine#307]
Hi list

i am trying to monitor the rtpengine service,
and want to test the rtpengine service alive or not, reponse my request or not reponse my request

i use the https://github.com/sipwise/rtpengine/blob/master/t/test-basic.pl. when i run the script and always get result  /usr/local/lib64/perl5/NGCP/Rtpengine/Test.pm line 343

```
sub _input {
        my ($self, $fh, $input, $peer) = @_;
        my $component = $self->_peer_addr_check($fh, $peer);

        $self->{dtls} and $self->{dtls}->input($fh, $input, $peer);
        $self->{ice} and $self->{ice}->input($fh, $input, $peer);

        $$input eq '' and return;

        defined($component) or return; # not one of ours

        # must be RTP or RTCP input
        my $exp = shift(@{$self->{media_receive_queues}->[$component]}) or die;
        $$input eq $exp or die;
        $self->{media_packets_received}->[$component]++;
        $$input = '';
}
```

but dont know the result for success case and failure case

how to fix it

is there any method to check rtpengine beside test-basic.pl

**Comment by rfuchs** [comment]
That would be failure since the script died. You can check that by looking at the scripts status code.

By default, the local UDP ports are allocated starting at port 2000. Make sure nothing else is using these ports, otherwise the test will fail.

**Comment by rfuchs** [comment]
Cleaning up old tickets
