### ISSUE TITLE
rtcp-mux port number indicated not muxed

### ISSUE THREAD

**Issue by egreenmachine** [sipwise/rtpengine#310]
I have a call from WebRTC to a desk phone. One of the flags that I am passing is `rtcp-mux=offer`. In the SDP to the desk phone I would expect to see the the `a=rtcp:<PORT>` line with a port number that matches the port in the m-line. Instead I see an rtcp port that is not muxed with with the rtp. This causes some endpoints to not mux rtp/rtcp. Could we change the behavior of the rptengine to do this? or at least make it configurable in some way? The [log file](https://gist.github.com/egreenmachine/6bcb570536d2bc1fa92c737a2d7ea33b) for the call in question. Thanks.

**Comment by rfuchs** [comment]
I believe this would go against the RFC, which states (from memory) that a fallback RTCP port must be given (explicitly or implicitly as the RTP+1 port) in case the recipient doesn't support rtcp-mux or wishes not to use it. If rtcp-mux is supported and accepted, the given RTCP port would be ignored anyway.

**Comment by egreenmachine** [comment]
I think you are correct here. Upon further investigation with Wireshark is looks like the client is muxing the RTCP with this SDP. Closing this as it is not actually an issue with rtpengine. Thanks.
