### ISSUE TITLE
Kamailio behind NAT, /and/ media servers behind NAT.

### ISSUE THREAD

**Issue by daytonturner** [sipwise/rtpengine#315]
Hi there,

So I've got rtpengine configured and working for clients where the intention is to proxy media between endpoints and the otherwise unreachable-by-the-endpoints freeswitch servers.  Works wonderfully.

The other curveball here however, is that Kamailio itself is also behind NAT.  In most situations, the clients are on the same "NATed" LAN as Kamailio, but in some cases, we have external users who would also like to talk to kamailio (or some carriers) using a public 1:1 NAT we've set up.  In this case, of course, Kamailio and Linux on this host are completely unaware of the 1:1 NAT pointing to it, and therefore dont know how to answer using this address (specifically in the c= of the SDP)

I've configured an alternate port in Kamailio to send external users to (5070) and have set:
   listen=10.0.0.1:5070 advertise PUBLIC_IP:5070

However this isn't enough for the SDP to be rewritten correctly.

I've tried passing `-i=internal/10.0.0.1 -i=external/10.0.0.1!PUBLIC_IP` and then created a config block in kamailio testing for if $Rp was 5070, and if so, added `direction=external` to rtpengine_manage flags.  At that point, the SDP being sent looked correct, but RTP packets were still originating (verified by tcpdump) from 10.0.0.1.  I added an iptables nat POSTROUTING rule that SNAT'ed communications to the specific IP I am trying to communicate from, and that at least got the operating system sourcing the UDP packets from the PUBLIC_IP, but of course this seems like a step in the wrong direction (and, it didnt work anyways)

When rtpengine spits out its received packets and bytes stats, both are 0 from this external host, in case that helps.

Any tips?

**Comment by amessina** [comment]
@daytonturner, I'm considering a 1:1 NAT scenario and came across this.  Were you able to find a resolution?

**Comment by rfuchs** [comment]
Cleaning up old tickets
