### ISSUE TITLE
Failed to set remote answer sdp: Called with SDP without DTLS fingerprint

### ISSUE THREAD

**Issue by msalman212** [sipwise/rtpengine#320]
Hi,

Scenario: WSS to WSS

Installed rtpengine from current master  (`Version: git-master-06922c5`), on a separate server with kamailio on another using jssip client. Odd thing is same jssip client works for other setup I have having older rtpengine, but this particular setup is not completing handshake and giving subjected error:

**Failed to set remote answer sdp: Called with SDP without DTLS fingerprint**

**RTPengine Logs:**
http://pastebin.com/1MRDqQ1g

**Comment by msalman212** [comment]
More Info regarding Scenario:

Chrome to Chrome (Version 55.0.2883.87)
kamailio/rtpengine client config (https://github.com/caruizdiaz/kamailio-ws/blob/master/modules.cfg) - to rule out used this cfg still the same error in browser.

**Comment by rfuchs** [comment]
I can't quite tell at which point in those logs you saw this error as there are multiple calls shows and some restarts in between and what not, but I do notice that in one `answer` the flag `"transport-protocol": "RTP/AVP"` was given, which isn't what you would want to do in a WSS to WSS case.

**Comment by msalman212** [comment]
You are right, it turned out to be Kamailio function doing a strict match on sdp transport type in newer version. So `sdp_with_transport `was not passing `transport=UDP/TLS/RTP/SAVPF`. Can be easliy fixed by using `sdp_with_transport_like` or matching exactly `sdp_with_transport("UDP/TLS/RTP/SAVPF")`

Certainly not RTPengine issue, opened ticket a bit too early. 

Thanks for such a great product @rfuchs
