### ISSUE TITLE
Errir Web RTC

### ISSUE THREAD

**Issue by cedric0306** [sipwise/rtpengine#324]
Hi All,

We try to using the jssip to connect sipwise but not work. Please help to take a look and give me your advise.

It showed error message from web debug.

We can not find any log on sipwise

![unnamed](https://cloud.githubusercontent.com/assets/25994785/23288728/1d119970-fa80-11e6-8fd0-9b46301c11fb.png)

**Comment by rfuchs** [comment]
This is a frontend configuration error and unrelated to rtpengine.

http://stackoverflow.com/questions/11768221/firefox-websocket-security-issue
https://github.com/SignalR/SignalR/issues/2276
