### ISSUE TITLE
One leg only in netstat, no audio

### ISSUE THREAD

**Issue by kevin-olbrich** [sipwise/rtpengine#325]
Hi!

I set up kamailio and rtpengine. My options are:

> OPTIONS="--interface=priv/192.168.32.151 --interface=pub/172.31.0.1 --listen-ng 127.0.0.1:22222 -m 20000 -M 59999 --homer=192.168.32.250:9060 --homer-protocol=udp --homer-id=123"

If I set up a call (INVITE) from pub interface, new ports on the priv-interface are opened but none on pub side. Is this correct?

**Comment by rfuchs** [comment]
No that is not correct. Ports should be opened on all interfaces.

**Comment by kevin-olbrich** [comment]
Is there an example for kamailio 4.4.5? I want to use kamailio + rtpengine in front of asterisk.

**Comment by kevin-olbrich** [comment]
I tried to set up a Kamailio node like this:
http://kb.asipto.com/asterisk:realtime:kamailio-4.0.x-asterisk-11.3.0-astdb

My env uses Asterisk 13, Kamailio 4.4.5 and pjsip instead of chan_sip.
Register is working (client shows success, entry in location table and asterisk shows kamailio IP as contact).

When I set up a call from my softphone to kamailio, I can see how asterisk is preparing the call (answer and then bridged to Echo()), but my softphone does not show any incloming codec (also rtpengine is not opening ports for the interface facing the softphone, just facing asterisk).

I am new to kamailio but I am not sure if this is a problem with kamailio or rtpengine.

**Comment by rfuchs** [comment]
If you don't see ports being opened, my first guess would be a problem with the network config. Details about your network setup would be helpful as well as log messages from rtpengine (with log level 7)

**Comment by kevin-olbrich** [comment]
Env:
I have three interfaces:

- eth0 = public internet (public ip, default route), **not** used for VoIP
- eth1 = private ip (192.168.32.151), asterisk as media proxy is on this network (**external / pub**)
- tun0 = OpenVPN for externel clients which are unable to establish secure connections (purpose of this setup, **internal / priv**)

> OPTIONS="--interface=pub/172.31.0.1 --interface=priv/192.168.32.151 --listen-ng 127.0.0.1:22222 -m 20000 -M 59999 --homer=192.168.32.250:9060 --homer-protocol=udp --homer-id=123 -L 7 -E"


Scenario:
Zoiper / Phoner Lite as softphone registering successfully at kamailio which itself registers it's own IP and port at asterisk. Call is made from softphone to asterisk which transcodes the call and connects to external networks (other provider).

Problem:
RtpEngine only opens ports on public interface:
```
# netstat -tulpen | grep rtp
udp        0      0 172.31.0.1:20000        0.0.0.0:*                           0          36968      6482/rtpengine
udp        0      0 172.31.0.1:20001        0.0.0.0:*                           0          36969      6482/rtpengine
udp        0      0 172.31.0.1:20010        0.0.0.0:*                           0          36970      6482/rtpengine
udp        0      0 172.31.0.1:20011        0.0.0.0:*                           0          36971      6482/rtpengine
udp        0      0 127.0.0.1:22222         0.0.0.0:*                           0          34449      6482/rtpengine
```

Log:
```
Feb 27 16:33:06 sipconnect.example.com rtpengine[6482]: DEBUG: Adding a proxy for control ng stats:127.0.0.1
Feb 27 16:33:06 sipconnect.example.com rtpengine[6482]: INFO: [a9BdFPwK9YWExae5AQiGkQ..]: Received command 'offer' from 127.0.0.1:40125
Feb 27 16:33:06 sipconnect.example.com rtpengine[6482]: [447B blob data]
Feb 27 16:33:06 sipconnect.example.com rtpengine[6482]: NOTICE: [a9BdFPwK9YWExae5AQiGkQ..]: Creating new call
Feb 27 16:33:06 sipconnect.example.com rtpengine[6482]: DEBUG: [a9BdFPwK9YWExae5AQiGkQ..]: set FILLED flag for stream 172.31.0.6:8000
Feb 27 16:33:06 sipconnect.example.com rtpengine[6482]: DEBUG: [a9BdFPwK9YWExae5AQiGkQ..]: set FILLED flag for stream 172.31.0.6:8001
Feb 27 16:33:06 sipconnect.example.com rtpengine[6482]: INFO: [a9BdFPwK9YWExae5AQiGkQ..]: offer time = 0.000315 sec
Feb 27 16:33:06 sipconnect.example.com rtpengine[6482]: INFO: [a9BdFPwK9YWExae5AQiGkQ..]: Replying to 'offer' from 127.0.0.1:40125
Feb 27 16:33:06 sipconnect.example.com rtpengine[6482]: [566B blob data]
Feb 27 16:33:06 sipconnect.example.com rtpengine[6482]: INFO: [a9BdFPwK9YWExae5AQiGkQ..]: Received command 'answer' from 127.0.0.1:36871
Feb 27 16:33:06 sipconnect.example.com rtpengine[6482]: [488B blob data]
Feb 27 16:33:06 sipconnect.example.com rtpengine[6482]: DEBUG: [a9BdFPwK9YWExae5AQiGkQ..]: set FILLED flag for stream 192.168.32.42:11336
Feb 27 16:33:06 sipconnect.example.com rtpengine[6482]: DEBUG: [a9BdFPwK9YWExae5AQiGkQ..]: set FILLED flag for stream 192.168.32.42:11337
Feb 27 16:33:06 sipconnect.example.com rtpengine[6482]: DEBUG: [a9BdFPwK9YWExae5AQiGkQ..]: Shutting down ICE agent (nothing to do)
Feb 27 16:33:06 sipconnect.example.com rtpengine[6482]: INFO: [a9BdFPwK9YWExae5AQiGkQ..]: answer time = 0.000086 sec
Feb 27 16:33:06 sipconnect.example.com rtpengine[6482]: INFO: [a9BdFPwK9YWExae5AQiGkQ..]: Replying to 'answer' from 127.0.0.1:36871
Feb 27 16:33:06 sipconnect.example.com rtpengine[6482]: [489B blob data]
Feb 27 16:33:10 sipconnect.example.com rtpengine[6482]: INFO: [a9BdFPwK9YWExae5AQiGkQ.. port 20010]: Confirmed peer address as 172.31.0.6:8000
Feb 27 16:33:13 sipconnect.example.com rtpengine[6482]: DEBUG: [a9BdFPwK9YWExae5AQiGkQ.. port 20011]: JSON to send to Homer: '{ "sender_information":{"ntp_timestamp_sec":3697198388,"ntp_timestamp_usec":3758096384,"octets":52480,"rtp_timestamp":3831533218, "packets":328},"ssrc":648211076,"type":200,"report_count":0,"report_blocks":[],"sdes_ssrc":648211076,"sdes_report_count":1,"sdes_information": [ {"sdes_chunk_ssrc":648211076,"type":1,"text":"username@cwde0011"}] }'
Feb 27 16:33:13 sipconnect.example.com rtpengine[6482]: INFO: [a9BdFPwK9YWExae5AQiGkQ.. port 20011]: Connecting to Homer at 192.168.32.250:9060
Feb 27 16:33:13 sipconnect.example.com rtpengine[6482]: INFO: [a9BdFPwK9YWExae5AQiGkQ.. port 20011]: Connection to Homer at 192.168.32.250:9060 has been established
Feb 27 16:33:13 sipconnect.example.com rtpengine[6482]: DEBUG: [a9BdFPwK9YWExae5AQiGkQ.. port 20011]: dequeue send queue to Homer
Feb 27 16:33:13 sipconnect.example.com rtpengine[6482]: INFO: [a9BdFPwK9YWExae5AQiGkQ.. port 20011]: Confirmed peer address as 172.31.0.6:8001
Feb 27 16:33:19 sipconnect.example.com rtpengine[6482]: DEBUG: [a9BdFPwK9YWExae5AQiGkQ.. port 20011]: JSON to send to Homer: '{ "sender_information":{"ntp_timestamp_sec":3697198394,"ntp_timestamp_usec":2598455214,"octets":98400,"rtp_timestamp":3831579058, "packets":615},"ssrc":648211076,"type":200,"report_count":0,"report_blocks":[],"sdes_ssrc":648211076,"sdes_report_count":1,"sdes_information": [ {"sdes_chunk_ssrc":648211076,"type":1,"text":"username@cwde0011"}] }'
Feb 27 16:33:19 sipconnect.example.com rtpengine[6482]: DEBUG: [a9BdFPwK9YWExae5AQiGkQ.. port 20011]: dequeue send queue to Homer
Feb 27 16:33:24 sipconnect.example.com rtpengine[6482]: DEBUG: [a9BdFPwK9YWExae5AQiGkQ.. port 20011]: JSON to send to Homer: '{ "sender_information":{"ntp_timestamp_sec":3697198399,"ntp_timestamp_usec":3100966387,"octets":139360,"rtp_timestamp":3831620002, "packets":871},"ssrc":648211076,"type":200,"report_count":0,"report_blocks":[],"sdes_ssrc":648211076,"sdes_report_count":1,"sdes_information": [ {"sdes_chunk_ssrc":648211076,"type":1,"text":"username@cwde0011"}] }'
Feb 27 16:33:24 sipconnect.example.com rtpengine[6482]: DEBUG: [a9BdFPwK9YWExae5AQiGkQ.. port 20011]: dequeue send queue to Homer
Feb 27 16:33:29 sipconnect.example.com rtpengine[6482]: DEBUG: [a9BdFPwK9YWExae5AQiGkQ.. port 20011]: JSON to send to Homer: '{ "sender_information":{"ntp_timestamp_sec":3697198405,"ntp_timestamp_usec":1288490188,"octets":184000,"rtp_timestamp":3831664626, "packets":1150},"ssrc":648211076,"type":200,"report_count":0,"report_blocks":[],"sdes_ssrc":648211076,"sdes_report_count":1,"sdes_information": [ {"sdes_chunk_ssrc":648211076,"type":1,"text":"username@cwde0011"}] }'
Feb 27 16:33:29 sipconnect.example.com rtpengine[6482]: DEBUG: [a9BdFPwK9YWExae5AQiGkQ.. port 20011]: dequeue send queue to Homer
Feb 27 16:33:34 sipconnect.example.com rtpengine[6482]: DEBUG: [a9BdFPwK9YWExae5AQiGkQ.. port 20011]: JSON to send to Homer: '{ "sender_information":{"ntp_timestamp_sec":3697198409,"ntp_timestamp_usec":1975684956,"octets":217280,"rtp_timestamp":3831697898, "packets":1358},"ssrc":648211076,"type":200,"report_count":0,"report_blocks":[],"sdes_ssrc":648211076,"sdes_report_count":1,"sdes_information": [ {"sdes_chunk_ssrc":648211076,"type":1,"text":"username@cwde0011"}] }'
Feb 27 16:33:34 sipconnect.example.com rtpengine[6482]: DEBUG: [a9BdFPwK9YWExae5AQiGkQ.. port 20011]: dequeue send queue to Homer
```

**Comment by rfuchs** [comment]
The log is missing the details of the `offer` and `answer` messages. Are you using the `direction=` attributes correctly to signal which interfaces to use?

**Comment by kevin-olbrich** [comment]
Ah! Just added it to rtpengine_manage() and I now see ports on both interfaces! I now get SIP 488 but this could be crypto request in INVITE.

**Comment by kevin-olbrich** [comment]
Still no sound and client does not show codec for inbound.

Log:
```
Feb 27 18:27:48 sipconnect.example.com rtpengine[927]: INFO: [0045A7A5-7FFB-E611-9D6E-81BBBA89680B@172.31.0.6]: --- Tag '1340174154', created 0:30 ago for branch '', in dialogue with ''
Feb 27 18:27:48 sipconnect.example.com rtpengine[927]: INFO: [0045A7A5-7FFB-E611-9D6E-81BBBA89680B@172.31.0.6]: ------ Media #1 (audio over RTP/AVP) using unknown codec
Feb 27 18:27:48 sipconnect.example.com rtpengine[927]: INFO: [0045A7A5-7FFB-E611-9D6E-81BBBA89680B@172.31.0.6]: --------- Port  192.168.32.151:20288 <>      172.31.0.6:5062 , 0 p, 0 b, 0 e, 1488216438 last_packet
Feb 27 18:27:48 sipconnect.example.com rtpengine[927]: INFO: [0045A7A5-7FFB-E611-9D6E-81BBBA89680B@172.31.0.6]: --------- Port  192.168.32.151:20289 <>      172.31.0.6:5063  (RTCP), 0 p, 0 b, 0 e, 1488216438 last_packet
Feb 27 18:27:48 sipconnect.example.com rtpengine[927]: INFO: [0045A7A5-7FFB-E611-9D6E-81BBBA89680B@172.31.0.6]: --- Tag '', created 0:30 ago for branch '', in dialogue with '1340174154'
Feb 27 18:27:48 sipconnect.example.com rtpengine[927]: INFO: [0045A7A5-7FFB-E611-9D6E-81BBBA89680B@172.31.0.6]: ------ Media #1 (audio over RTP/AVP) using unknown codec
Feb 27 18:27:48 sipconnect.example.com rtpengine[927]: INFO: [0045A7A5-7FFB-E611-9D6E-81BBBA89680B@**172.31.0.6**]: --------- Port      172.31.0.1:20346 <>          **(null):0**    , 0 p, 0 b, 0 e, 1488216438 last_packet
Feb 27 18:27:48 sipconnect.example.com rtpengine[927]: INFO: [0045A7A5-7FFB-E611-9D6E-81BBBA89680B@**172.31.0.6**]: --------- Port      **172.31.0.1:20347 <>          (null):0**     (RTCP), 0 p, 0 b, 0 e, 1488216438 last_packet
```

**Comment by rfuchs** [comment]
This means that no media packets were received on that port. Maybe a network issue?

**Comment by rfuchs** [comment]
Actually I think that rtpengine didn't even see the respective `answer` (usually triggered from the 200 OK)

**Comment by kevin-olbrich** [comment]
I tcpdump'd the VPN and the internal interface. I can see rtp traffic coming in from the softphone to kamailio / rtpengine. On the priv-interface, it has the wrong source address while leaving the correct interface:

**eth1**
> Internet Protocol Version 4, Src: 172.31.0.1, Dst: 192.168.32.42

172.31.0.1 is the engine itself on public side, while 192.168.32.42 is the asterisk node.
I don't get warnings or error on asterisk, it seems to be ignoring the packets.

**Comment by rfuchs** [comment]
The `replace-*` options only affect what's going into the SDP body, not the RTP packets themselves. If you're talking to a host 192.168.32.42 and need to use 192.168.32.151 as source IP for that media leg, you need to use the appropriate `direction=` flag for this side (`direction=priv` in your case). If it's the caller's side (side A), it would be the first `direction=` flag, otherwise it's the second.

**Comment by kevin-olbrich** [comment]
This actualy is the case. Priv is first, Pub is second.

I justed tryed to change both directions in rtpengine_manage() and there is no RTP at all. It is the callers side (softphone, VPN). So the current setting seems to be correct.

RTP is working fine if I MASQ on all interfaces (iptables -t nat -A POSTROUTING -o XXX -j MASQUERADE). It is flowing fine, I hear asterisk Echo and softphone shows correct codec.

I am not sure how MASQ is performing on high load including connection tracking. Currently I don't see an error in network setup, as it is very simplified (simple CentOS 7 setup with RTPEngine latest master).

**Comment by rfuchs** [comment]
It can't be correct if the wrong IP address is being inserted. Are you using `direction=` flags in the reverse path (i.e. when the answer 200 OK is being processed) as well? (You shouldn't.) Any NAT being used anywhere?

**Comment by rfuchs** [comment]
Cleaning up old tickets
