### ISSUE TITLE
/var/lib/dpkg/info/ngcp-rtpengine-daemon.postinst: 21: [: Illegal number: 

### ISSUE THREAD

**Issue by juha-h** [sipwise/rtpengine#326]
I have started to get the error message on the subject line.  Could it happen because default file does not anymore contain NO_FALLBACK variable when config file is in use?

**Comment by rfuchs** [comment]
I think the missing TABLE= setting is to blame. The init.d script also seems to expect this variable to be set. Try with TABLE= included in the defaults file.

**Comment by juha-h** [comment]
Richard Fuchs writes:

> I think the missing TABLE= setting is to blame. The init.d script also
> seems to expect this variable to be set. Try with TABLE= included in
> the defaults file.

The error is gone when I added:

TABLE=0
NO_FALLBACK=yes

to the postinst file.  I didn't check, which one was the cause.

-- Juha

**Comment by juha-h** [comment]
Sipwise Jenkins User writes:

> Closed #326 via 77f9e4c31003c6c757757b5706754ff8e6d0f813.

Thanks.  Could you cherry pick to latest stable branch mr5.1.1?

-- Juha
