### ISSUE TITLE
rtpengine not updating endpoint ip

### ISSUE THREAD

**Issue by cm-gb** [sipwise/rtpengine#330]
One of our customers is using a SEMS server to place two outbound calls using our sip trunk. 
Once the first call is connected a second call is placed and when the second call answers their server sends a re-invite to switch audio ports so the rtp traffic doesn’t flow through their server anymore but is routed inside our platform.
Basically, they just switch SDP’s of both calls. 

It seems like a random issue, and is not really reproducible, except for placing multiple calls and sometimes both parties can hear each other, other times they can’t, because rtpengine fails to update the endpoint and keeps sending rtp back to their (customers) server for one of the call legs.

We tried to reproduce the case using a freeswitch box and it worked every time. After the reinvite, the rtp remained within our platform.
The signaling in both cases still goes through the freeswitch or sems for call control. 

It is yet unclear why this issue occurs when the calls are originated by a SEMS server.

Attached rtpengine logs:
failure.txt contains the failure case where rtpengine keeps sending rtp back to the customer's sems server.
success.txt contains the success scenario where rtp is routed internally inside our own platform.

Both samples are calls originated from the customers sems server.

IP explanation:
kamailio-01	10.10.31.10
kamailio-02	10.10.31.11
rtpengine-01	10.10.31.20
rtpengine-02	10.10.31.21

customer-sip(sems) 1.1.1.1		
carrier-sip	2.2.2.1
carrier-sip	2.2.2.2
carrier-sip	2.2.2.3
carrier-sip	2.2.2.4

[failure.txt](https://github.com/sipwise/rtpengine/files/824384/failure.txt)
[success.txt](https://github.com/sipwise/rtpengine/files/824385/success.txt)

We tried this with the following versions of rtpengine: 5.0.0 and 5.1.1.1.

**Comment by cm-gb** [comment]
See attachment for new call samples with debug on.

Both A-LEG and B-LEG are in the same file. Just do a find for both words.

It looks like syslog is truncating the log lines, if this is a problem, please let me know.

[failure_full.txt](https://github.com/sipwise/rtpengine/files/824751/failure_full.txt)
[success_full.txt](https://github.com/sipwise/rtpengine/files/824750/success_full.txt)

**Comment by rfuchs** [comment]
My guess is that rtpengine learning the correct endpoints (an anti NAT mechanism) gets in the way. After a reinvite, there's a short duration during which rtpengine looks at incoming packets and uses their source address to correct and override the address from the SDP (in case those are behind NAT).

You can try using the `asymmetric` flag in the offer/answer to disable this learning of endpoint addresses. Note that this will break media if the endpoints are behind NAT.

**Comment by cm-gb** [comment]
Our rtpengines are behind NAT, using a Juniper vSRX which handles NAT perfectly. We haven't had issues so far, except this specific scenario. 

What do you mean with "this will break media"? No media at all?

**Comment by rfuchs** [comment]
Yeah likely no media at all. With `asymmetric` set, rtpengine will send media to the endpoints specified in the SDP and not attempt to learn addresses from the received RTP packets. if there's a mismatch between SDP addresses and actual addresses due to NAT, then media will be sent to the wrong addresses.

**Comment by cm-gb** [comment]
@rfuchs setting the asymmetric flag did the trick! I placed a few calls and audio was flowing in both directions the whole time. I'll do some more testing with a regular sip traffic scenario to see if that still works. 
I'll update this issue tomorrow. 
Thank you for the help! Much appreciated :)

**Comment by rfuchs** [comment]
Glad to hear. Another possibility that came to mind is to play with the `via-branch=extra` and the `extra_id_pv`. Giving rtpengine a different via-branch will make it think that this is a new call leg and would make it open new ports.

**Comment by cm-gb** [comment]
Some tests with regular sip traffic also worked with asymmetric set. We still have to do more tests as each of our customer's have different setups and we cannot afford to break working scenarios. 

I haven't tried with the via-branch=extra setting yet, but will do that somewhere next week.

**Comment by cm-gb** [comment]
@rfuchs one more question regarding the asymmetric flag, do I need to supply this flag for every function call to rtpengine_manage(...) or is enough to call it just once on the initial INVITE message?

**Comment by rfuchs** [comment]
This flag is directional, so if given in the `offer` then it affects the streams processed in the `offer`, and ditto for the `answer`. If you want to treat all streams as asymmetric, you should use it everywhere.

**Comment by cm-gb** [comment]
Right! Thanks!
Our regular tests were okay, no issues found. 
I'll close the issue.

Thank you for the help!
