### ISSUE TITLE
Not able to compile rtpengine

### ISSUE THREAD

**Issue by Biswajit2902** [sipwise/rtpengine#331]
Hi am trying to install rtpengine in ubuntu 16.10 server.

while building package using **dpkg-buildpackage** , i am getting this error 

> output.c:201:46: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’; did you mean ‘codec’?
  avcodec_parameters_from_context(output->avst->codecpar, output->avcctx);

Can anyone please help me in this.

Thank you
-Biswajit

**Comment by pkuzak** [comment]
We had a similar issue. In our case enforcing a specific version of the libav library did the job (see #302 )

**Comment by Biswajit2902** [comment]
Hi pkuzak,
Thanks for reply.

Can you please mention the particular version for ffmpeg, that should be install.
