### ISSUE TITLE
Need help with recording-daemon (mr5.3.0.0)

### ISSUE THREAD

**Issue by denyspozniak** [sipwise/rtpengine#336]
Hello!
I want to record calls in the local directory in wav format via recording-daemon, but it does not work for me.
Below you can find rtpengine version and config files:

Rtpengine version is 5.3.0.0+0~mr5.3.0.0 git-master-7088e15

root@ip:/etc/rtpengine# cat **/etc/default/ngcp-rtpengine-recording-daemon**
RUN_RTPENGINE_RECORDING=yes
CONFIG_FILE=/etc/rtpengine/rtpengine-recording.conf
CONFIG_SECTION=rtpengine-recording
PIDFILE=/var/run/ngcp-rtpengine-recording-daemon.pid

root@ip:/etc/rtpengine# cat **/etc/rtpengine/rtpengine-recording.conf**
[rtpengine-recording]
table = 0
output-format = wav
output-mixed = 1
spool-dir = /var/spool/rtpengine/metadata
output-dir = /var/spool/rtpengine/recordings
log-level = 6

root@ip:/etc/rtpengine# **/etc/init.d/ngcp-rtpengine-recording-daemon status**
● ngcp-rtpengine-recording-daemon.service - LSB: Ngcp Rtpengine Recording Daemon
   Loaded: loaded (/etc/init.d/ngcp-rtpengine-recording-daemon; bad; vendor preset: enabled)
   Active: active (running) since Fri 2017-03-24 12:32:30 UTC; 4s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 23726 ExecStop=/etc/init.d/ngcp-rtpengine-recording-daemon stop (code=exited, status=0/SUCCESS)
  Process: 23736 ExecStart=/etc/init.d/ngcp-rtpengine-recording-daemon start (code=exited, status=0/SUCCESS)
    Tasks: 9
   Memory: 11.4M
      CPU: 33ms
   CGroup: /system.slice/ngcp-rtpengine-recording-daemon.service
           └─23743 /usr/sbin/rtpengine-recording --config-file=/etc/rtpengine/rtpengine-recording.conf --pidfile=/var/run/ngcp-rtpengine-recording-daemon.pid

**From log:**

Mar 24 12:49:51 ip rtpengine[7495]: INFO: [my.domain_6063]: Received command 'offer' from 10.23.10.23:53647
Mar 24 12:49:51 ip rtpengine[7495]: NOTICE: [my.domain_6063]: Creating new call
Mar 24 12:49:51 ip rtpengine[7495]: INFO: [my.domain_6063]: Replying to 'offer' from 10.23.10.23:53647
Mar 24 12:49:52 ip rtpengine[7495]: INFO: [my.domain_6063]: Received command 'start recording' from 10.23.10.23:39703
**Mar 24 12:49:52 ip rtpengine[7495]: NOTICE: [my.domain_6063]: Turning on call recording.**
Mar 24 12:49:52 ip rtpengine[7495]: INFO: [my.domain_6063]: Writing recording file: /var/spool/rtpengine/pcaps/my.domain_6063-8316837661995655.pcap
Mar 24 12:49:52 ip rtpengine[7495]: INFO: [my.domain_6063]: Replying to 'start recording' from 10.23.10.23:39703
Mar 24 12:49:54 ip rtpengine[7495]: INFO: [my.domain_6063]: Received command 'answer' from 10.23.10.23:39703
Mar 24 12:49:54 ip rtpengine[7495]: INFO: [my.domain_6063]: answer time = 0.000184 sec
Mar 24 12:49:54 ip rtpengine[7495]: INFO: [my.domain_6063]: Replying to 'answer' from 10.23.10.23:39703
Mar 24 12:49:54 ip rtpengine[7495]: INFO: [my.domain_6063]: Received command 'start recording' from 10.23.10.23:39703
Mar 24 12:49:54 ip rtpengine[7495]: INFO: [my.domain_6063]: Replying to 'start recording' from 10.23.10.23:39703
Mar 24 12:50:43 ip rtpengine[7495]: INFO: [my.domain_6063]: Moved metadata file "/var/spool/rtpengine/tmp/rtpengine-meta-my.domain_6063-8316837661995655.tmp" to "/var/spool/rtpengine/metadata"

**Comment by rfuchs** [comment]
Looks like you're using the wrong recording method. The recording daemon only works with `recording-method=proc`. It also requires the kernel module to be loaded and active.

**Comment by denyspozniak** [comment]
Still does not work....
Changed method to proc in  **/etc/default/ngcp-rtpengine-daemon**
 RECORDING_DIR=/var/spool/rtpengine/ 
 RECORDING_METHOD=proc

Now I see in **syslog** next:
 Mar 24 15:23:09 ip rtpengine-recording[25318]: DEBUG: running garbage collection thread 2
 Mar 24 15:23:09 ip rtpengine-recording[25318]: DEBUG: running garbage collection thread 6
 Mar 24 15:23:13 ip rtpengine[25519]: INFO: [my.domain_6100]: Received command 'start recording'  from 10.23.10.20:38441
 Mar 24 15:23:13 ip rtpengine[25519]: NOTICE: [my.domain_6100]: Turning on call recording.
 Mar 24 15:23:13 ip rtpengine[25519]: INFO: [my.domain_6100]: Replying to 'start recording' from 10.23.10.20:38441
 Mar 24 15:23:14 ip rtpengine[25519]: INFO: [my.domain_6100]: Received command 'start recording' from 10.23.10.20:38441
 Mar 24 15:23:14 ip rtpengine[25519]: INFO: [my.domain_6100]: Replying to 'start recording' from 10.23.10.20:38441
 Mar 24 15:23:18 ip rtpengine-recording[25318]: DEBUG: running garbage collection thread 7
 Mar 24 15:23:18 ip rtpengine-recording[25318]: DEBUG: running garbage collection thread 5
 Mar 24 15:23:18 ip rtpengine-recording[25318]: DEBUG: running garbage collection thread 4
 Mar 24 15:23:18 ip rtpengine-recording[25318]: DEBUG: running garbage collection thread 3
 Mar 24 15:23:19 ip rtpengine-recording[25318]: DEBUG: running garbage collection thread 0

**Comment by denyspozniak** [comment]
Module is also loaded:

root@ip:/etc/default# lsmod | grep RTPENGINE
xt_RTPENGINE           45056  4

**Comment by rfuchs** [comment]
Confirm that metadata files are created in `/var/spool/rtpengine/metadata` when recording is enabled.
Also confirm that `rtpengine` itself is using the kernel module using the same table number (0).
Also confirm that pseudofiles appear in `/proc/rtpengine/0/calls/` while calls are being recorded.

**Comment by denyspozniak** [comment]
**1. Confirm that metadata files are created in /var/spool/rtpengine/metadata when recording is enabled.**
Meta file appears for call duration in **/var/spool/rtpengine** folder (not in ../metadata):

root@ip:/etc/default# ls -al /var/spool/rtpengine/
total 160
drwxrwxrwx 6 root root  4096 Mar 24 16:05 .
drwxr-xr-x 5 root root  4096 Mar 15 14:29 ..
-rw-r--r-- 1 root root  2694 Mar 24 16:05 **my.domain_6102-f39f0e861ccf2fc5.meta**
drwxr-xr-x 2 root root 73728 Mar 24 14:58 metadata
drwxr-xr-x 2 root root 61440 Mar 24 14:58 pcaps
drwxr-xr-x 2 root root  4096 Mar 24 12:27 recordings
drwxr-xr-x 2 root root  4096 Mar 24 14:43 tmp

**2. Also confirm that rtpengine itself is using the kernel module using the same table number (0).**
root@ip:/etc/default# cat /etc/default/ngcp-rtpengine-daemon
...
**TABLE=0**

**3. Also confirm that pseudofiles appear in /proc/rtpengine/0/calls/ while calls are being recorded.**
Yes, it appears for period of call (the same as meta):

root@ip:/etc/default# ls -al /proc/rtpengine/0/calls/
total 0
dr-xr-xr-x 3 root root 0 Mar 24 16:05 .
dr-xr-xr-x 3 root root 0 Mar 24 15:19 ..
dr-xr-xr-x 2 root root 0 Mar 24 16:05 **my.domain_6102-f39f0e861ccf2fc5**

**Comment by rfuchs** [comment]
The subdirectories are only used for the `pcap` recording method, not the `pcap` recording method. So make sure the recording daemon uses `/var/spool/rtpengine` as spool directory, not `/var/spool/rtpengine/metadata`. (Or change the `rtpengine` config to use `../metadata` as spool directory.)

**Comment by denyspozniak** [comment]
Yes, it uses /var/spool/rtpengine

**Comment by rfuchs** [comment]
What are your libavcodec/libavformat/libavresample versions?

**Comment by denyspozniak** [comment]
root@ip:/etc/default# dpkg -l | grep libav
ii  libavcodec-dev:amd64               7:2.8.11-0ubuntu0.16.04.1          amd64        FFmpeg library with de/encoders for audio/video codecs - development files
ii  libavcodec-ffmpeg56:amd64          7:2.8.11-0ubuntu0.16.04.1          amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavfilter-dev:amd64              7:2.8.11-0ubuntu0.16.04.1          amd64        FFmpeg library containing media filters - development files
ii  libavfilter-ffmpeg5:amd64          7:2.8.11-0ubuntu0.16.04.1          amd64        FFmpeg library containing media filters - runtime files
ii  libavformat-dev:amd64              7:2.8.11-0ubuntu0.16.04.1          amd64        FFmpeg library with (de)muxers for multimedia containers - development files
ii  libavformat-ffmpeg56:amd64         7:2.8.11-0ubuntu0.16.04.1          amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample-dev:amd64            7:2.8.11-0ubuntu0.16.04.1          amd64        FFmpeg compatibility library for resampling - development files
ii  libavresample-ffmpeg2:amd64        7:2.8.11-0ubuntu0.16.04.1          amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil-dev:amd64                7:2.8.11-0ubuntu0.16.04.1          amd64        FFmpeg library with functions for simplifying programming - development files
ii  libavutil-ffmpeg54:amd64           7:2.8.11-0ubuntu0.16.04.1          amd64        FFmpeg library with functions for simplifying programming - runtime files
