### ISSUE TITLE
Failed to push relay stream to kernel: Invalid argument 

### ISSUE THREAD

**Issue by amessina** [sipwise/rtpengine#338]
rtpengine master @ af1db75 with kernel module emits the following errors
`Failed to push relay stream to kernel: Invalid argument ` as well as `Failed to delete relay stream from kernel: No such file or directory` and rtpengine-recording via `proc` method doesn't work any longer.  My previous build master @ b4694eb did not exhibit this.  Log attached.
[rtpengine-failed-to-push-relay-stream-to-kernel.txt](https://github.com/sipwise/rtpengine/files/871002/rtpengine-failed-to-push-relay-stream-to-kernel.txt)

**Comment by rfuchs** [comment]
Have updated, recompiled and reloaded the kernel module as well? There were some changes in the interface.

**Comment by amessina** [comment]
Yes, I did recompile the kernel module as well and also restarted the machine.  No issues with loading or starting anything.  Just the above errors when making calls.

**Comment by rfuchs** [comment]
I can't reproduce that. Please double check that the version of the kernel module matches the version of the daemon.

**Comment by amessina** [comment]
@rfuchs, the kernel module was built correctly, but I forgot to rebuild the initramfs and since I have xt_RTPENGINE loading at early boot, the older version was being loaded.  Sorry for the noise.  It's working well now.
