### ISSUE TITLE
Centos 6.6 -glib-2.0 rtpengine daemon install.

### ISSUE THREAD

**Issue by JonHVU** [sipwise/rtpengine#347]
Hi Guys,

I am aware of issue https://github.com/sipwise/rtpengine/issues/76, and this looks similar whereby I get an issue due to glib when trying to install the daemon.

see below;

 daemon]# make
make rtpengine
make[1]: Entering directory `/usr/src/rtpengine/daemon'
cc -g -Wall -pthread -fno-strict-aliasing -std=c99 `pkg-config --cflags glib-2.0` `pkg-config --cflags gthread-2.0` `pkg-config --cflags zlib` `pkg-config --cflags openssl` `pkg-config --cflags libevent_pthreads` `pcre-config --cflags` `pkg-config --cflags json-glib-1.0` -I. -I../kernel-module/ -I../lib/ -D_GNU_SOURCE -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DRTPENGINE_VERSION="\"undefined\"" -O3   -c -o recording.o recording.c
In file included from recording.h:16,
                 from recording.c:1:
aux.h: In function ‘atomic64_get_set’:
aux.h:491: warning: passing argument 1 of ‘g_atomic_pointer_compare_and_exchange’ from incompatible pointer type
/usr/include/glib-2.0/glib/gatomic.h:48: note: expected ‘void * volatile*’ but argument is of type ‘volatile void **’
In file included from recording.c:1:
recording.h: At top level:

I have version glib2-2.28.8-9.el6.x86_64 in place.

Is there anyway to resolve this as I havent had this issue on other centos 6.6 servers.

Many thanks

Jon

**Comment by rfuchs** [comment]
That's some picky compiler. Please try with the following patch.

```
diff --git a/daemon/aux.h b/daemon/aux.h
index d0d0af3..17a67ec 100644
--- a/daemon/aux.h
+++ b/daemon/aux.h
@@ -463,7 +463,7 @@ INLINE int bit_array_clear(volatile unsigned int *name, unsigned int bit) {
 #if GLIB_SIZEOF_VOID_P >= 8
 
 typedef struct {
-	volatile void *p;
+	volatile void * volatile p;
 } atomic64;
 
 INLINE u_int64_t atomic64_get(const atomic64 *u) {
```

**Comment by JonHVU** [comment]
Hi Richard,

Tell me about it, my heart drops when using it and Centos but hey ho!

I applied the patch, and it seemed to get further then sadly I get;

make[1]: Entering directory `/usr/src/rtpengine/daemon'
cc -g -Wall -pthread -fno-strict-aliasing -std=c99 `pkg-config --cflags glib-2.0` `pkg-config --cflags gthread-2.0` `pkg-config --cflags zlib` `pkg-config --cflags openssl` `pkg-config --cflags libevent_pthreads` `pcre-config --cflags` `pkg-config --cflags json-glib-1.0` -I. -I../kernel-module/ -I../lib/ -D_GNU_SOURCE -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DRTPENGINE_VERSION="\"undefined\"" -O3   -c -o recording.o recording.c
In file included from recording.h:16,
                 from recording.c:1:
aux.h: In function ‘atomic64_get_set’:
aux.h:491: warning: passing argument 1 of ‘g_atomic_pointer_compare_and_exchange’ from incompatible pointer type
/usr/include/glib-2.0/glib/gatomic.h:48: note: expected ‘void * volatile*’ but argument is of type ‘volatile void * volatile*’
In file included from recording.c:1:
recording.h: At top level:
recording.h:49: warning: declaration does not declare anything

So its now not  happy about line 491 in aux.h ?

Thanks again for help.

Jon

**Comment by rfuchs** [comment]
That's really only a warning though. It shouldn't fail at that point. Aren't there other errors following this?

**Comment by JonHVU** [comment]
[rtpengineinstallerror.txt](https://github.com/sipwise/rtpengine/files/903284/rtpengineinstallerror.txt)
Hi Richard,

Sorry please see all output attached when I issue make.

Jon
