### ISSUE TITLE
iptables v1.6.0 does not know option --id

### ISSUE THREAD

**Issue by juha-h** [sipwise/rtpengine#349]
I tried to start rtpengine-daemon on Debian Stretch that has iptables v1.6.0 and it failed due to --id per-target option in iptables commands:

Apr 14 15:33:26 rautu kernel: [ 3110.276175] Registering xt_RTPENGINE module - version 5.3.0.0+0~mr5.3.0.0
Apr 14 15:33:26 rautu rtpengine-daemon[7805]: Starting RTP/media proxy: rtpengine-daemon:iptables v1.6.0: unknown option "--id"
Apr 14 15:33:26 rautu rtpengine-daemon[7805]: Try `iptables -h' or 'iptables --help' for more information.

-- Juha

**Comment by rfuchs** [comment]
Check that you have the iptables module present and available. Normally it should be `/usr/lib/xtables/libxt_RTPENGINE.so` or `/usr/lib/x86_64-linux-gnu/xtables/libxt_RTPENGINE.so`

**Comment by juha-h** [comment]
Richard Fuchs writes:

> Check that you have the iptables module present and
> available. Normally it should be `/usr/lib/xtables/libxt_RTPENGINE.so`
> or `/usr/lib/x86_64-linux-gnu/xtables/libxt_RTPENGINE.so`

It got installed in /lib/xtables/libxt_RTPENGINE.so, not to
/usr/lib/x86_64-linux-gnu/xtables, where other .so files are.

-- Juha

**Comment by juha-h** [comment]
Richard Fuchs writes:

> Check that you have the iptables module present and
> available. Normally it should be `/usr/lib/xtables/libxt_RTPENGINE.so`
> or `/usr/lib/x86_64-linux-gnu/xtables/libxt_RTPENGINE.so`

I checked from Debian Jessie and in it all libxt so files are in
/lib/xtables dir.  Looks like this has now changed in Debian Stretch,
where the location is /usr/lib/x86_64-linux-gnu/xtables dir.  Perhaps
rtpengine-iptable package should somehow check, which version of Debian
it is being installed on?

-- Juha

**Comment by juha-h** [comment]
After I moved libxt_RTPENGINE.so from /usr/lib/xtables/ to /usr/lib/x86_64-linux-gnu/xtables/ and rebooted, rtpengine started fine.

Perhaps it could be checked during installation, which of two dirs exists and install  libxt_RTPENGINE.so to the existing one?

**Comment by rfuchs** [comment]
Looks like the installation location ought to be determined by `pkg-config xtables --variable=xtlibdir`. Gonna have to check if this is true for older distributions as well.

**Comment by juha-h** [comment]
Richard Fuchs writes:

> Looks like the installation location ought to be determined by
> `pkg-config xtables --variable=xtlibdir`. Gonna have to check if this
> is true for older distributions as well.

It works at least in Jessie and Stretch:

$ pkg-config xtables --variable=xtlibdir
/lib/xtables

$ pkg-config xtables --variable=xtlibdir
/usr/lib/x86_64-linux-gnu/xtables

I don't have Wheezy around anymore.

-- Juha

**Comment by juha-h** [comment]
I found Wheezy pbuilder environment, and pkg-config worked there too:

# pkg-config xtables --variable=xtlibdir
/lib/xtables

I doubt if anyone is using order Debians than that.
