### ISSUE TITLE
[rtpengine-recording] Sound distortion in mp3 file

### ISSUE THREAD

**Issue by denyspozniak** [sipwise/rtpengine#350]
Hello!

I have faced with sound distrotion in output mp3/wav file in case of recording with rtpengine recording daemon. My topology is next:
PSTN->FreeSWITCH->Kamailio + Rtpengine->WebRTC

If I record in FreeSWITCH sound is perfect (FS.wav).
If I record in Rtpengine sound is with distortion (RTPENG.wav).
On WebRTC side call is also with good quality.
If I record as pcap wireshark plays also perfect.

My system is Ubuntu 16.04.2 LTS (4.4.0-71-lowlatency)
libav*:amd64               7:2.8.11-0ubuntu0.16.04.1

```
root@ip# cat /etc/rtpengine/rtpengine-recording.conf
[rtpengine-recording]
table = 0
output-format = mp3
#output-format = wav
resample-to = 16000
mp3-bitrate = 48000
output-mixed = 1
#log-level = 0
spool-dir = /var/spool/rtpengine
output-dir = /var/spool/rtpengine/recordings

root@ip:~# cat /etc/default/ngcp-rtpengine-daemon
RUN_RTPENGINE=yes
LISTEN_TCP=25060
LISTEN_UDP=12222
LISTEN_NG=22222
LISTEN_CLI=9900
INTERFACES="external/172.31.11.11!5.5.5.5 internal/172.31.11.11!5.5.5.5.5"
TIMEOUT=60
SILENT_TIMEOUT=3600
PIDFILE=/var/run/ngcp-rtpengine-daemon.pid
FORK=yes
TABLE=0
NO_REDIS_REQUIRED=yes
CREATE_IPTABLES_CHAIN=yes
RECORDING_DIR=/var/spool/rtpengine/
RECORDING_FORMAT=eth
RECORDING_METHOD=proc

root@ip:~# cat /etc/default/ngcp-rtpengine-recording-daemon
RUN_RTPENGINE_RECORDING=yes
CONFIG_FILE=/etc/rtpengine/rtpengine-recording.conf
CONFIG_SECTION=rtpengine-recording
PIDFILE=/var/run/ngcp-rtpengine-recording-daemon.pid
MUST_NFS=no
```

Please help to find the source if this issue.

[WAVs.zip](https://github.com/sipwise/rtpengine/files/934385/WAVs.zip)

**Comment by rfuchs** [comment]
Please post a pcap with the RTP packets together with the output WAV files

**Comment by denyspozniak** [comment]
Can I record both pcap and mp3/wav (proc) file?

**Comment by rfuchs** [comment]
Not currently with the recording daemon, but you can use Wireshark or tcpdump to make the pcap.

**Comment by rfuchs** [comment]
Do you have these distortions only in the mixed output, or also in the single output files?

**Comment by denyspozniak** [comment]
Hello!
Single output streams do not have distortion, there is only in mixed file.

**Comment by denyspozniak** [comment]
What can I provide you to help solving this issue?

**Comment by rfuchs** [comment]
The syslog output would also be helpful. Run the recording daemon with log level 7 and then make a test call. It's probably going to produce a lot of output.

**Comment by denyspozniak** [comment]
Syslog is attached, collected from production system.


[syslog.zip](https://github.com/sipwise/rtpengine/files/943206/syslog.zip)

**Comment by rfuchs** [comment]
I tried to reproduce this using a replay of the pcap you provided, but can't. Which distribution and version are you using? What versions are your libav* packages?

**Comment by denyspozniak** [comment]
Ubuntu 16.04.2 LTS (4.4.0-71-lowlatency)
libav*:amd64 7:2.8.11-0ubuntu0.16.04.1

**Comment by rfuchs** [comment]
Can you try changing `#define NUM_INPUTS 4` to `#define NUM_INPUTS 2` in `recording-daemon/mix.c`, recompile, and see if that makes a difference?

**Comment by denyspozniak** [comment]
Recompiled, but issue is present (sent examples).

**Comment by rfuchs** [comment]
Please try with the code from branch https://github.com/sipwise/rtpengine/tree/rfuchs/350

This seems to fix it for me.

**Comment by denyspozniak** [comment]
Hello!
Fixed for me also :)
Thanks!
