### ISSUE TITLE
doubt when creating 2 rtpengine instances on the same server

### ISSUE THREAD

**Issue by descartin** [sipwise/rtpengine#352]
Hello all

i have created 2 rtpengine instances in the same server using different IP address but same ports. A kamailio sip server communicates with those 2 instances separately.

root@mad-ms-1:/var/log# iptables -L -n
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
RTPENGINE  udp  --  0.0.0.0/0            0.0.0.0/0            udp dpts:23000:63000 RTPENGINE id:2
RTPENGINE  udp  --  0.0.0.0/0            0.0.0.0/0            udp dpts:23000:63000 RTPENGINE id:1

root      3208     1 14  2016 ?        20-05:26:48 /usr/sbin/rtpengine --table=1 -i 1.1.1.1 -u 1.1.1.2:22221 -l 1.1.1.2:22221 -n 1.1.1.2:22222 -m 23000 -M 63000 -d 5 --no-fallback
root     20204     1  0 Apr19 pts/0    00:06:20 /usr/sbin/rtpengine --table=2 -i 2.2.2.1 -u 2.2.2.2:22221 -l 2.2.2.2:22221 -n 2.2.2.2:22222 -m 23000 -M 63000 -d 5 --no-fallback

i did the same in 2 diff servers on versions 3.3.0.0+0~mr3.8.0.0 and 4.4.0.0+0~mr4.4.0.0 

could be an issue to use the same port range on the instances?
could i have some kind of port overlapping affecting the rtp flow? or the server distinguish the sockets ?

thansk a lot and regards
david escartin

**Comment by rfuchs** [comment]
I would suggest to include the destination IP addresses in the iptables rules (`-d 1.1.1.1` etc).

This should work fine with `mr4.4` but probably doesn't work with `mr3.8` as the socket handling routines are different and don't bind the sockets to specific IP addresses.

**Comment by descartin** [comment]
hello Richard

thanks for the reply, you mean it wont work ok to use version3.3 by setting destination ip address in the iptables, or the thing that should now work ok with 3.3 is just configuring 2 rtpengine instances?

best regards
david

**Comment by rfuchs** [comment]
What I mean is that rtpengine `mr3.8` does not fully distinguish based on local destination IP addresses, so running two instances using the same port ranges but different local IP addresses likely won't work. It should work with `mr4.4`.

**Comment by descartin** [comment]
ok understood, thanks
