### ISSUE TITLE
Incorrect package name in dkms.conf.in

### ISSUE THREAD

**Issue by tiglat** [sipwise/rtpengine#354]
Hello!

Recently you renamed rtpengine packages to ngcp-rtpengine, but inside rtpengine.spec file during install step prefix ngcp is removed inside PACKAGE_NAME=ngcp-rtpengine.

As result during ngcp-rtpengine-dkms package installation dkms build step fails.

I think you need fix the following command from spec file
sed -i -e "s/__VERSION__/%{version}-%{release}/g;**s/ngcp-rtpengine/rtpengine/g**" debian/dkms.conf.in

Best regards,
Konstantin

**Comment by rfuchs** [comment]
We don't maintain the RPM build stuff ourselves, those were contributed by 3rd parties. If there's a problem, please fix and submit a pull request, thanks.
