### ISSUE TITLE
Play pcap file

### ISSUE THREAD

**Issue by albertollamaso** [sipwise/rtpengine#355]
Hi Guys,

This is not an issue, we have a setup:

version:
Version: 5.1.0.0+0~mr5.1.0.0 git-master-a3d5764

Command:
`/usr/sbin/rtpengine --interface=AAA.AAA.AAA.AAA. --listen-ng=127.0.0.1:8799 -m 40000 -M 44000 --dtls-passive --recording-dir=/var/spool/rtpengine --recording-format=raw --pidfile=/var/run/rtpengine.pid`

We have a video call using Opus for audio codec and Vp8 for video. We are trying to decode the file and be able to play the 4 streams (2 audios + 2 videos). We've tried different tools like videosnarf, x264 and ffmpeg without any luck

Any hint will be appreciated.

**Comment by albertollamaso** [comment]
We've tried `ffmpeg -f rtp  -vcodec libvpx -acodec opus -i data.pcap out.mp4` and getting the error: `Unsupported RTP version packet received, Guessing on RTP content - if not received properly you need an SDP file describing it`. 

Also we're not sure if that pcap file contains both streams (Audio and Video). 

Thanks,

**Comment by rfuchs** [comment]
I really can't provide any support for this. Videosnarf sounds like it should work, maybe try taking it up with them. If I'd have to guess, I'd guess that it needs a description of the video format and content, which would have to be taken from the SDP, which isn't included in the pcap dump output.
