### ISSUE TITLE
Incorrect user and group name in rtpengine.sysconfig

### ISSUE THREAD

**Issue by tiglat** [sipwise/rtpengine#356]
Hello!

rtpengine.sysconfig file contains incorrect default names for user and group of rtpengine.
According to rpm spec file the name should be ngcp-rtpengine instead of rtpengine.

Best regards

**Comment by rfuchs** [comment]
We don't maintain the RPM build stuff ourselves, those were contributed by 3rd parties. If there's a problem, please fix and submit a pull request, thanks.

**Comment by tiglat** [comment]
Hi,

In order to create pull request I need access to the repository I think.
I cannot push my branch with fixes to initiate review.
Could you please help me with that?

Thanks

**Comment by linuxmaniac** [comment]
https://help.github.com/articles/creating-a-pull-request/
