### ISSUE TITLE
Too many packets in UDP receive queue after upgrade from 4.6 to 5.0 & 5.1

### ISSUE THREAD

**Issue by digipigeon** [sipwise/rtpengine#358]
Running Ubuntu 16.04.2 LTS after upgrading from 4.6 to 5.0 and also testing with 5.1, I am getting the following error message:
```
ERR: [4eadaf3a54a0ebea6e44297060446067@XXX.XXX.XXX port 30180]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
```
This error standalone is understandable, however I have log files for over 20 hours with the same message continuously appearing, resulting in 100GB+ logs with just this message in.

Once multiple calls get stuck in this loop the server eventually comes to a halt and consequentially causes Opensips to crash.

Problem happens with 5.0.2.1+0~mr5.0.2.1 & 5.1.2.1+0~mr5.1.2.1

**Comment by rfuchs** [comment]
We've been through this already, haven't we? Your setup creating calls with packets going in a loop.

**Comment by digipigeon** [comment]
Hi Richard, I have checked the previously and you are correct I have had this bug in the past #20, I am sorry I forgot about it as things have been stable for a while.

I honestly don't know why I am so susceptible to it, my Opensips code is pretty standard when its comes to RTP Engine Engagement and I don't even know how I could make my code incorrect in a way that would advise RTP-Engine to forward packets to itself.

If you would be so kind to tell me how I could possible have configured this wrongly I would be very grateful.

Additionally I will speak with the Opensips team to see if they can identify what I may have done wrong. Nevertheless should c0f8196 have added some protection against this? If not, shouldn't there be something in place to prevent this from getting stuck in a loop?

**Comment by rfuchs** [comment]
The loop detection from that commit has been defused somewhat in the meantime, as it adds a quite a bit of overhead and is prone to false positives. It's now combined with detecting endpoints that actually point to itself. So whenever rtpengine detects an endpoint that belongs to one of its own interfaces, the loop detection is enabled for that media stream. Otherwise it remains disabled.

Since you know the culprit call ID, you can check the logs to see why there was a loop. You might need to enable debug logging first.

**Comment by digipigeon** [comment]
Firstly, I am attempting to downgrade to the 4.6 branch to try and achieve stability. I will see if I can leave 1 of the servers in the cluster on the latest version and try to do some more debugging.

I notice that I am not using final-timeout in my setup at the moment, if I was to set this, would this be effective closing this stuck/looped call (and therefore reduce this problem from compounding while I search for the root cause.).

**Comment by rfuchs** [comment]
`final-timeout` would close any call older than the given amount, no matter what. You decide if that's an appropriate workaround for you.

**Comment by digipigeon** [comment]
I have heard back from the OpenSIPS team regarding my script and they have confirmed that it is set correctly with no clear reason why this may be happening.

I also downgraded back to the 4.6 branch and achieved instant stability.

Could you suggest anything else which may be causing this loopback?
Seems very strange that this is increasing the traffic on my lo interface. Does that mean that there is some packet crafted with 127.0.0.1?

**Comment by rfuchs** [comment]
Without any additional details from logs or any other info, I can only speculate.

**Comment by digipigeon** [comment]
Please take a look at the file (last octet in IP's set to XXX on purpose). Hopefully this will help us explain what is going wrong.

[loop.txt](https://github.com/sipwise/rtpengine/files/999231/loop.txt)

**Comment by rfuchs** [comment]
OK, so you have client `as46bd4fc2` making an offer, which is then answered by `3703667312-1273655544`. So far so good. `as46bd4fc2` is at 192.168.0.XXX and `3703667312-1273655544` is at 109.159.136.XXX. Rtpengine rewrote both to its own local 178.62.29.XXX.

The answer by `3703667312-1273655544` is then repeated 15 seconds later for some reason. This is somewhat unusual, but not a problem. 109.159.136.XXX was again rewritten to 178.62.29.XXX.

`3703667312-1273655544` then initiates a reverse offer (probably a reverse re-invite). It still is at 109.159.136.XXX which again was rewritten to 178.62.29.XXX.

This reverse offer is then immediately repeated by `3703667312-1273655544`, but this time advertising an IP endpoint of 178.62.29.XXX. In fact this input SDP seen here is exactly the rewritten SDP produced in the last offer (timestamps 12:28:59, lines 40 and 46 in the log file - output SDP is in line 44). So from rtpengine's point of view, the client's IP endpoint is now one of its own RTP ports. You have a loop.

My guess is that the client isn't actually making this offer through a SIP invite, but rather that something in your config loops around rtpengine twice and passes the rewritten SDP right back into it.

**Comment by efiop** [comment]
Hi!

> My guess is that the client isn't actually making this offer through a SIP invite, but rather that something in your config loops around rtpengine twice and passes the rewritten SDP right back into it.

I'm not sure I follow why then this issue doesn't occur on 4.x and only appeared in 5.x? Seems like a regression introduced in 5.0. Unless I'm missing something.

**Comment by sergey-safarov** [comment]
I also faced this error on my installation on `5.0` branch.
