### ISSUE TITLE
core high temperature

### ISSUE THREAD

**Issue by descartin** [sipwise/rtpengine#359]
hello all

i'm observing a high core temperature in 2 rtpengine servers which run 4.4.0.0+0~mr4.4.0.0 version.
the kernel i have is 3.2.0-4-amd64 #1 SMP Debian 3.2.46-1 x86_64 GNU/Linux

i'm just wondering if it has any sense that the high temperature is caused by rtpengine.
cpu is very low under 5%
could it be any relation or preference to run a higher kernel for that rtpengine version or is it fine as it is?

best regards
david

**Comment by rfuchs** [comment]
Sorry but I really have no information here. The kernel version should be fine -- it's what we use.
