### ISSUE TITLE
[rtpengine] rtpengine 5.3.0.0 segfault

### ISSUE THREAD

**Issue by denyspozniak** [sipwise/rtpengine#361]
Hello!
I have segfault issue with rtpengine 5.3.0.0:

```
#dmesg
[ 1461.552974] Registering xt_RTPENGINE module - version 5.3.0.0+0~mr5.3.0.0
[ 1521.082902] rtpengine[2446]: segfault at 8 ip 000000000043a85a sp 00007f4ac0d64e20 error 4 in rtpengine[400000+57000]
[ 1583.597108] Unregistering xt_RTPENGINE module
```

```
# uname -a
Linux 4.4.0-71-lowlatency #92-Ubuntu SMP PREEMPT Fri Mar 24 14:04:37 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

```

syslog attached:
[syslog.txt](https://github.com/sipwise/rtpengine/files/996143/syslog.txt)

**Comment by rfuchs** [comment]
Please post a full gdb backtrace from the core dump

**Comment by marcinkowalczyk** [comment]
Hi,

 As far as I can see no core files were created. Crash happened 
/var/log/kern.log:May 12 12:01:42 ip-172-31-11-128 kernel: [ 1028.946569] rtpengine[1417]: segfault at 8 ip 000000000043a85a sp 00007f2305802e20 error 4 in rtpengine[400000+57000]
/var/log/kern.log:May 12 12:09:54 ip-172-31-11-128 kernel: [ 1521.082902] rtpengine[2446]: segfault at 8 ip 000000000043a85a sp 00007f4ac0d64e20 error 4 in rtpengine[400000+57000]
/var/log/kern.log:May 12 12:26:49 ip-172-31-11-128 kernel: [ 2536.115080] rtpengine[2563]: segfault at 8 ip 000000000043a85a sp 00007f35dd3a5e20 error 4 in rtpengine[400000+57000]
/var/log/kern.log:May 12 12:30:52 ip-172-31-11-128 kernel: [ 2779.117532] rtpengine[2993]: segfault at 8 ip 000000000043a85a sp 00007f4130c8ce20 error 4 in rtpengine[400000+57000]
/var/log/kern.log:May 12 14:49:21 ip-172-31-11-128 kernel: [11087.636696] rtpengine[5272]: segfault at 8 ip 000000000043a85a sp 00007fb89b16fe20 error 4 in rtpengine[400000+57000]

**Comment by marcinkowalczyk** [comment]
This is only file I've found related to crash. Trying to get full coredump. but I 'm not sure what the triger for crash is.

Regards
[rtpengine_crash.txt](https://github.com/sipwise/rtpengine/files/998471/rtpengine_crash.txt)

**Comment by marcinkowalczyk** [comment]
Hi,

 We will test later today, but seems it happens where to one RTPEngine is controlled by both Kam 4.4.5 and 5.1. same time.

**Comment by rfuchs** [comment]
Exec `ulimit -c unlimited` before starting rtpengine (from the same shell) to make sure a core dump is written.

**Comment by rfuchs** [comment]
Any update here?

**Comment by denyspozniak** [comment]
Hello! We jumped to Version: 5.4.1.1+0~mr5.4.1.1, works OK for current being.
