### ISSUE TITLE
Recording questions

### ISSUE THREAD

**Issue by chrisdoyle82** [sipwise/rtpengine#362]
Hello,

I am migrating from rtpproxy to rtpengine and had a few questions.

Right now I combine the 2 files for each call into one stereo file, but it looks like output-mixed=1 just makes one mono file in rtpengine. Is there a way to get it to combine them into a stereo file?

Also, i'm having issues identifying which of the 2 files is for the call originator and which call is from the other party.

Thanks!

**Comment by rfuchs** [comment]
Right now upsampling mono to stereo is not supported. It's an option we might have in the future though.

Output files are tagged by SSRC only right now. The recently introduced custom label (see `label` under https://github.com/sipwise/rtpengine#offer-message) can be used to differentiate between the two sides, but the label is only stored to the MySQL storage so far. We'll probably include the label in the output filename in the near future.
