### ISSUE TITLE
never-ending 'Kernelizing...' logs in WebRTC to classic phone scenario

### ISSUE THREAD

**Issue by smititelu** [sipwise/rtpengine#363]
Hi,

I'm trying a WebRTC(188.208.118.42) -> (86.104.210.152)Kamailio/Rtpengine(10.208.1.52) -> Freeswitch(10.208.1.53) scenario and both audio and video works.

However, I noticed the 'Kernelizing...' logs of the RTP/AVP steams kept appearing for rtpengine <-> Freeswitch audio/video legs and no incrementing packet stats in /proc/rtpengine/0/list. I have rtpengine configured like this since I'd like to do interface bridging in the near-future:
```
...
listen-ng = 127.0.0.1:2223
interface = internal/10.208.1.52;external/10.208.1.52!86.104.210.152
...
```

Any ideas why this might be happening? I've attached a .pcap and logs for the above scenario.

[rekernelizing.zip](https://github.com/sipwise/rtpengine/files/999695/rekernelizing.zip)

**Comment by smititelu** [comment]
when I replace:
```
// request from ws
rtpengine_manage("replace-origin direction=external direction=internal ICE=remove trust-address RTP/AVP");
```
with:
```
// request from ws
rtpengine_manage("replace-origin direction=external direction=internal trust-address");
```
it works and the kernelization and /proc stats are ok.

This is ok for me at the moment because Freeswitch knows ICE, but I wonder what about if the endpoint doesn't know ICE ?!...

**Comment by rfuchs** [comment]
Might be related to RTCP parsing and the rtcp-mux option. I'll look into it.

**Comment by smititelu** [comment]
Hi @rfuchs. Have you find out something related to this?

**Comment by smititelu** [comment]
Indeed it was related to rtcp mux. Setting rtcp-mux-demux for incoming calls and rtcp-mux-offer for outgoing calls solves this issue.

**Comment by rfuchs** [comment]
Good to know, thanks. It's still a bug as it shouldn't do it either way, but I couldn't reproduce it so far.
