### ISSUE TITLE
[rtpengine] Question about MOS reporting

### ISSUE THREAD

**Issue by denyspozniak** [sipwise/rtpengine#364]
Hello!
As I see in TT#12800 was adding ability to send MOS/jitter/delay reporting about RTP quality.
Please explain how it measures and what streams are analized.

Thanks!

**Comment by smititelu** [comment]
Hi @denyspozniak,

I don't know very much about that either but, you can start with [1] and [2].

[1] http://kamailio.org/docs/modules/devel/modules/rtpengine.html#rtpengine.p.mos_min_pv
[2] https://youtu.be/aGyEGhW-9N8

Thank you,
Stefan

**Comment by denyspozniak** [comment]
Hello @smititelu ,
I saw these links, but did not find the answers on my questions.
In our case we have 4 streams on rtpengine (2xIN and 2xOUT) and how as example  **mos_average_pv** calculates (based on INs streams OR also checks RTCP from OUTs)?

**Comment by rfuchs** [comment]
By default, the average is taken over all participating streams. Using the new custom label (see `label=` option) and the `_A_` and `_B_` label options of the Kamailio module, it's possible to selectively get stats from individual participating streams (e.g. all `IN` streams in your case, or only one individual stream).

**Comment by rfuchs** [comment]
Closing this as it's not a real issue. Feel free to ask follow up questions.
