### ISSUE TITLE
System crash in Centos 7,1

### ISSUE THREAD

**Issue by cfantasy74** [sipwise/rtpengine#368]
I'm using the recording-daemon, but get a system crash when a call is hungup. I am seeing the following messages in the log:
```
Jun  2 02:47:54 localhost rtpengine-recording[11934]: ERR: [C 2677206236%40192.168.0.161-727762f5efcd8cb8.meta] [S tag-0-media-1-component-1-RTP-id-2] [0x59964802] av_log: Invalid input channel layout: 0
Jun  2 02:47:54 localhost rtpengine-recording[11934]: ERR: [C 2677206236%40192.168.0.161-727762f5efcd8cb8.meta] [S tag-0-media-1-component-1-RTP-id-2] [0x59964802] Error resampling: failed to init resample context (code -22)
Jun  2 02:47:54 localhost rtpengine-recording[11934]: ERR: [C 2677206236%40192.168.0.161-727762f5efcd8cb8.meta] [S tag-0-media-1-component-1-RTP-id-2] [0x59964802] Failed to decode media packet
```

**Comment by egreenmachine** [comment]
We are running Centos 7.2 and not seeing these crashes. It may be worth updating your OS.

**Comment by rfuchs** [comment]
What does "system crash" mean? Does the daemon segfault? Is there a core dump? Or does it just produce log messages?

**Comment by cfantasy74** [comment]
OS stops responding. So guess it's the kernel module has crashes.

**Comment by rfuchs** [comment]
Anything in dmesg/kernel log/console?

**Comment by cfantasy74** [comment]
no just stops.. Nothing in dmesg or anywhere else

**Comment by cfantasy74** [comment]
When I stopped recording via the daemon, the system is stable.

**Comment by rfuchs** [comment]
Do you have a reliable way to reproduce this? I know there's a booboo in the kernel intercept code somewhere as I've come across it myself (I believe it's related to the select/poll function) but I haven't been able to reproduce it.

**Comment by cfantasy74** [comment]
Yes I can reproduce it reliably
I can even give you access to the machine doing it, but we will have to wait for a week since Im going on vacation

**Comment by rfuchs** [comment]
Can you describe steps to reproduce? Your system setup? Other details?

**Comment by cfantasy74** [comment]
I’ll get back to you

Kind Regards,

Claus

**Comment by rfuchs** [comment]
The commit references above may be a possible fix for this. I have no way of reproducing this, so this is a bit of a shot in the dark. But perhaps you can see if it makes a difference for you.

**Comment by cfantasy74** [comment]
I'll give it a try and report back

**Comment by rfuchs** [comment]
Any luck checking this?

**Comment by cfantasy74** [comment]
Hi Richard,

Sorry not yet. I am on vacation.. I will report backup as soon as I get a chance to check.

Kind Regards,

Claus

Den 17. jul. 2017 10.39 PM skrev Richard Fuchs <notifications@github.com>:

Any luck checking this?

**Comment by rfuchs** [comment]
Any feedback here yet? Otherwise I will just merge it to master as it seems like a good bugfix anyway.

**Comment by cfantasy74** [comment]
Seems to be working.

Fra: Richard Fuchs [mailto:notifications@github.com]
Sendt: 10. august 2017 18:31
Til: sipwise/rtpengine <rtpengine@noreply.github.com>
Cc: Claus Futtrup <cf@globalvoicerecording.com>; Author <author@noreply.github.com>
Emne: Re: [sipwise/rtpengine] System crash in Centos 7,1 (#368)


Any feedback here yet? Otherwise I will just merge it to master as it seems like a good bugfix anyway.
