### ISSUE TITLE
Crash with relase 5.3.1.1 on Centos 7.3

### ISSUE THREAD

**Issue by mtryfoss** [sipwise/rtpengine#370]
Hi!

Upgraded to 5.3.1.1 yesterday. Had a crash today. Here's the output from gdb.
[rtpengine-gdb.txt](https://github.com/sipwise/rtpengine/files/1070994/rtpengine-gdb.txt)

I notice this: nk_warn_msg = 0x450da8 "protocol not supported by kernel module"

Log file for call-id leading to crash(I think):
[log.txt](https://github.com/sipwise/rtpengine/files/1071003/log.txt)

I do not have the full SDP for the given INVITE, but here is a part of it:
[sdp.txt](https://github.com/sipwise/rtpengine/files/1071005/sdp.txt)

It got an ipv6 ice candidate. The server does have an ipv6-adress, but it's just the one auto-assigned by linux. No connection to internet.

Let me know if you need anything more.

**Comment by rfuchs** [comment]
Might be related to #366

**Comment by mtryfoss** [comment]
Thanks for quick response :-) The affected systems are patched now. I will let you know if we experience more issues related to this.
