### ISSUE TITLE
Missing '=' sign rtpengine 5.4 on Debian 8 installed from packages

### ISSUE THREAD

**Issue by JonHVU** [sipwise/rtpengine#371]
Hi,

Sorry to disturb, but having installed rtpengine 5.4 on debian 8 from packages I am seeing some strange behavior.

Essentially I am registering a client, and sending a call into kamailio with rtpengine, and then passing the request to another kamailio instance also running rtpengine for onwards termination.

 On the registrar I see this in terms of SDP in;

recieved SDP from client;
```
v=0
o=- 20031 20031 IN IP4 82.15.170.163
s=SDP data
c=IN IP4 82.15.170.163
t=0 0
m=audio 11842 RTP/AVP 8 101
a=rtpmap:8 PCMA/8000
a=ptime:20
a=sendrecv
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
```

After rtpengine engaged with rtpengine_manage("direction=external direction=internal"); in kamailio 4.4;
```
v=0
o=- 20031 20031 IN IP4 82.15.170.163
s=SDP data
c=IN IP4 192.168.1.159
t=0 0
m=audio 30328 RTP/AVP 8 101
a=rtpmap:8 PCMA/8000
a=ptime:20
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15a=sendrecv
a=rtcp:30329
a=ice-ufrag:ULlBlp0R
a=ice-pwd:gYLCkdzZ21jq4LwFdJnC0h5ggD
a=candidate:WHPBplmNJ5wYFafQ 1 UDP 2130706431 192.168.1.159 30328 typ host
a=candidate:WHPBplmNJ5wYFafQ 2 UDP 2130706430 192.168.1.159 30329 typ host
```

The ``a=sendrecv`` looks odd there, is that correct? 

Then when the second kamailio gets the request I get this error;

(And it gets the latter SDP above);
```
Jun 20 11:22:46 Kam-HA-OBP1 /usr/sbin/kamailio[30949]: INFO: <script>: Route:REGISTRARIN selected
Jun 20 11:22:46 Kam-HA-OBP1 rtpengine: INFO: [0_1627314934@82.15.170.163]: Received command 'offer' from 127.0.0.1:47706
Jun 20 11:22:46 Kam-HA-OBP1 rtpengine: WARNING: [0_1627314934@82.15.170.163]: Error parsing SDP at offset 437: Missing '=' sign
Jun 20 11:22:46 Kam-HA-OBP1 rtpengine: INFO: [0_1627314934@82.15.170.163]: offer time = 0.000041 sec
Jun 20 11:22:46 Kam-HA-OBP1 rtpengine: WARNING: [0_1627314934@82.15.170.163]: Protocol error in packet from 127.0.0.1:47706: Failed to parse SDP [d3:sdp439:v=0#015#012o=- 20031 20031 IN IP4 82.15.170.163#015#012s=SDP data#015#012c=IN IP4 192.168.1.159#015#012t=0 0#015#012m=audio 30328 RTP/AVP 8 101#015#012a=rtpmap:8 PCMA/8000#015#012a=ptime:20#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-15a=sendrecv#015#012a=rtcp:30329#015#012a=ice-ufrag:ULlBlp0R#015#012a=ice-pwd:gYLCkdzZ21jq4LwFdJnC0h5ggD#015#012a=candidate:WHPBplmNJ5wYFafQ 1 UDP 2130706431 192.168.1.159 30328 typ host#015#012a=candidate:WHPBplmNJ5wYFafQ 2 UDP 2130706430 192.168.1.159 30329 typ host#015#012#015#0129:directionl8:internal8:externale7:call-id26:0_1627314934@82.15.170.16313:received-froml3:IP413:192.168.1.159e8:from-tag10:37570803737:command5:offere]
```
Any help appreciated on this.

Many thanks

Jon

**Comment by rfuchs** [comment]
Do you have the debug log from the first rtpengine instance? It would show the SDP before and after it was rewritten.

**Comment by JonHVU** [comment]
Hi,

Please see below;

Jun 20 13:25:45 Kam-HA-1 rtpengine: DEBUG: [NDAxYTAwMGVhNWRlODVjNGQ0MDg1MmYwYjM1M2IyOTU]: Dump for 'offer' from 127.0.0.1:42052: { "sdp": "v=0#015#012o=- 13142435146244391 1 IN IP4 82.15.170.163#015#012s=Bria 3 release 3.5.5  stamp 71238#015#012c=IN IP4 82.15.170.163#015#012t=0 0#015#012m=audio 58672 RTP/AVP 8 101#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-15#015#012a=sendre", "direction": [ "external", "internal" ], "call-id": "NDAxYTAwMGVhNWRlODVjNGQ0MDg1MmYwYjM1M2IyOTU", "received-from": [ "IP4", "82.15.170.163" ], "from-tag": "96f9dd49", "command": "offer" }
Jun 20 13:25:45 Kam-HA-1 rtpengine: DEBUG: [NDAxYTAwMGVhNWRlODVjNGQ0MDg1MmYwYjM1M2IyOTU]: set FILLED flag for stream 82.15.170.163:58672
Jun 20 13:25:45 Kam-HA-1 rtpengine: DEBUG: [NDAxYTAwMGVhNWRlODVjNGQ0MDg1MmYwYjM1M2IyOTU]: set FILLED flag for stream 82.15.170.163:58673
Jun 20 13:25:45 Kam-HA-1 rtpengine: DEBUG: [NDAxYTAwMGVhNWRlODVjNGQ0MDg1MmYwYjM1M2IyOTU]: Response dump for 'offer' to 127.0.0.1:42052: { "sdp": "v=0#015#012o=- 13142435146244391 1 IN IP4 82.15.170.163#015#012s=Bria 3 release 3.5.5  stamp 71238#015#012c=IN IP4 192.168.1.159#015#012t=0 0#015#012m=audio 30354 RTP/AVP 8 101#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-15#015#012a=sendrea=sendrecv#015#012a=rtcp:30355#015#012a=ice-ufrag:UpoeTy0G#015#012a=ice-pwd:26hHxc2AWcOcIaoyPjcFxWkI6a#015#012a=candidate:WHPBplmNJ5wYFafQ 1 UDP 2130706431 192.168.1.159 30354 typ host#015#012a=candidate:WHPBplmNJ5wYFafQ 2 UDP 2130706430 192.168.1.159 30355 typ host#015#012", "result": "ok" }

Hope thats enough detail? Its the same when using a bria and a yealink client.

Thanks!

Jon

**Comment by rfuchs** [comment]
Yes, that's enough. The incoming SDP looks truncated. It ends in `a=sendre` and without a terminating newline. You need to figure out where and why it's getting truncated.

**Comment by JonHVU** [comment]
Hmm yes very strange as its coming in direct from the client into kamailio!

Thanks for looking will dig into it.
