### ISSUE TITLE
cant clone to a windows machine

### ISSUE THREAD

**Issue by nakchak** [sipwise/rtpengine#376]
It appears that its impossible to clone the project to a windows machine, as the filename aux.c and aux.h in the daemon folder are reserved names in windows land 0_o

https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

Somewhat annoying as i was hoping to store a copy on a windows file server for nonsense reasons to do with backup and a purchasing decision which means it only works on windows....

Figured i would log it so people wont be scratching their heads when a clone to a windows box fails.

**Comment by rfuchs** [comment]
Geez man...

**Comment by nakchak** [comment]
Closing as its just to explain why you cant clone to a windows box, i think its fine as it is just a bit annoying, no point in changing names or anything like that
