### ISSUE TITLE
Internal / external network setup

### ISSUE THREAD

**Issue by BertrandTotti** [sipwise/rtpengine#378]
Hello,

I am trying to setup Kamailio and rtpengine to listen simulatenaously to my internal and external network.
I have several sip clients on internal network registered to kamailio (without NAT).
I want bridgle all calls (signaling and media). My local network must keep isolated.
My use cases are :
	Internal SIP Client <-> external SIP Client
	Internal SIP Client <- external WebRTC client

Are these use cases easily realizable? What changes would be needed ?
Thanks.

**Comment by rfuchs** [comment]
Yes, this is possible. The SIP proxy needs to remember which client is plain RTP and which is WebRTC, and instruct rtpengine to translate the SDP and media appropriately. For calls going to WebRTC, you typically want to use `RTP/SAVPF rtcp-mux-demux ICE=force`, while for calls going to plain RTP you want `RTP/AVP ICE=remove`.

There are complete systems which already do this, such as https://www.sipwise.org/products/spce/
