### ISSUE TITLE
Received video freeze under chrome

### ISSUE THREAD

**Issue by BertrandTotti** [sipwise/rtpengine#379]
I have setup a webrtc sip bridge with kamailio and rtpengine.
Audio and video works under firefox but video freeze with chrome. 
Chrome receive packets without lost but frames decoded are very very low and NacksSent explode.
I suspect a problem with RTCP feedback.
Any track to explore ??

Thanks.

**Comment by rfuchs** [comment]
Rtpengine doesn't produce RTCP feedback messages. If you're bridging WebRTC to a plain RTP client, the plain RTP client must produce the RTCP feedback messages (i.e. support and use the RTP/AVPF profile).

**Comment by BertrandTotti** [comment]
Thanks for your response. I use a sip client from opal library that normaly support rtcp. But sometings go wrong...  I will try to solve the problem.

**Comment by BertrandTotti** [comment]
Maybe do you know a sip client that works well with the rtpengine in webrtc bridge mode to check if the problem come from my sip client ?

**Comment by rfuchs** [comment]
AFAIK Linphone works

**Comment by BertrandTotti** [comment]
thanks

**Comment by BertrandTotti** [comment]
The problem is with resolutions greater than or equal to 720p. It's not related to bandwidth...
 All lowests resolutions are smooth.

**Comment by rfuchs** [comment]
Cleaning up old tickets
