### ISSUE TITLE
RTPEngine sending RTP to SDP address, not SIP source

### ISSUE THREAD

**Issue by samael33** [sipwise/rtpengine#380]
Hi!
Not sure if this is an issue related to rtpengine, but in a case, when in SDP i have field (not sure who is adding this field)
a = alt:1 1 : D79BAE9F CE91368A 192.168.2.126 9442
It's sending media to 192.168.2.126 (private address listed in SDP). In a case if no such attribute, media sent correctly

[audio.pcap.zip](https://github.com/sipwise/rtpengine/files/1184171/audio.pcap.zip)

**Comment by rfuchs** [comment]
Rtpengine does not support the `a=alt` attribute. It will send media to the address specified in the `c=` line by default, or to the source address of any received RTP packets (reverse path). If you want to send media to the SIP source address by default, use the `sip-source` option.

**Comment by samael33** [comment]
That's the issue, to be honest. If there is no such a=alt attribute, SDP sent correctly.
rtpengine options are "internal external RTP/AVP ICE=remove replace-session-connection replace-origin".

**Comment by rfuchs** [comment]
Use the `sip-source` option if you want to force sending to the SIP source address instead of the address from the SDP.
