### ISSUE TITLE
Does rtpengine support opus codec?

### ISSUE THREAD

**Issue by tiglat** [sipwise/rtpengine#381]
Hi. 
We created WebRTC proxy on base Kamailio and RTPengine and found that opus audio goes only in one way.
Could you tell me how does RTPengine support opus? What could be wrong in our configuration if it fully support this coded?
Thank you.

**Comment by rfuchs** [comment]
Rtpengine does not get involved in codecs at all. They all pass through transparently. You can run rtpengine with log level 7 and then post the log resulting from a call.

**Comment by tiglat** [comment]
Thank you for the answer. It means we need to search the issue in other components. By the way, does your answer mean that rtpengine can not make transcoding of the rtp payload?

**Comment by rfuchs** [comment]
Correct. There may be support for transcoding in the future though.
