### ISSUE TITLE
SRTP output wanted, but no crypto suite was negotiated

### ISSUE THREAD

**Issue by africallshop** [sipwise/rtpengine#382]
[rtpengine.txt](https://github.com/sipwise/rtpengine/files/1233803/rtpengine.txt)
Hello,

There is a lot of messages like as : 
SRTP output wanted, but no crypto suite was negotiated

It seems there is no issue about the audio but I want undestand why I got this error.
Can you help me please ?

The call flow is:
UAC --> KAMALIO + RTPENGINE -> ASTERISK

I use rtpengine for : 
- Bridging between RTP and SRTP user agents
- Bridging between ICE-enabled and ICE-unaware user agents

Note:
I have also this error : Error parsing RTP header: invalid header version

Regards
Abdoul.

**Comment by rfuchs** [comment]
This is expected in an RTP/SRTP scenario when RTP early media comes in before the SRTP keys have been exchanged in both sides. In your case, the outgoing SRTP key is sent in the rewritten `answer`, so any RTP that is received before that moment cannot be encrypted and sent as SRTP. Thus the message you're seeing.

**Comment by africallshop** [comment]
Thanks.
