### ISSUE TITLE
SIPS to SIP rewrite / RTPEngine 63bdd615 stops RTP after 60 seconds 

### ISSUE THREAD

**Issue by khorsmann** [sipwise/rtpengine#383]
As described here https://lists.kamailio.org/pipermail/sr-users/2017-August/098241.html, 
i have dumb Softphones that force SIPS-URI scheme. 

Only in this szenario - rtp stops after 66 seconds and i have no clue why. I set up the debug-level to 7 and try to fetch some infos. I have no clue where to find the ml0_termination=TIMEOUT bug in my config. 

UAC (TLS with SIPS-URI) -----> tls/PUB-IP-kamailio [with rtp-engine] PRIV-IP/udp----> udp/FreeSWITCH.

`KERNEL=yes
TABLE=0
FALLBACK=yes
RTP_IP[0]=pub/212.XX.XX.XXX
RTP_IP[1]=prv/172.20.120.81
LISTEN_NG=127.0.0.1:2223
TOS=184
TIMEOUT=30
PORT_MIN=35000
PORT_MAX=65000
LOG_LEVEL=7
LOG_FACILITY=local6
LOG_FACILITY_CDR=local5
`

**rtpengine log**

`
Aug 21 17:21:33 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: Received command 'offer' from 127.0.0.1:33489
Aug 21 17:21:33 kamailio1 rtpengine[7564]: DEBUG: [ERRInM44QBd16aMqhJtBfg..]: Dump for 'offer' from 127.0.0.1:33489: 
{ "sdp": "v=0
012o=- 13147802492894111 13147802492894111 IN IP4 172.20.100.104
012s=-
012c=IN IP4 172.20.100.104
012t=0 0
012m=audio 17384 RTP/SAVP 8 0
012a=rtpmap:8 PCMA/8000
012a=rtpmap:0 PCMU/8000
012a=ptime:20
012a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:L4qhlCAYqg3v/WBJn7mbcRxFFlS2yTRU3M1pYAId
012a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:L4qhlCAYqg3v/WBJn7mbcRxFFlS2yTRU3M1pYAId
012a=sendrecv
012", "ICE": "remove", "direction": [ "pub", "prv" ], "replace": [ "origin", "session ...
Aug 21 17:21:33 kamailio1 rtpengine[7564]: DEBUG: [ERRInM44QBd16aMqhJtBfg..]: ... -connection" ], "transport-protocol": "RTP/AVP", 
"call-id": "ERRInM44QBd16aMqhJtBfg..", "received-from": [ "IP4", "217.YY.YY.YYY" ], "from-tag": "7847dc70", "command": "offer" }
Aug 21 17:21:33 kamailio1 rtpengine[7564]: NOTICE: [ERRInM44QBd16aMqhJtBfg..]: Creating new call
Aug 21 17:21:33 kamailio1 rtpengine[7564]: DEBUG: [ERRInM44QBd16aMqhJtBfg..]: set FILLED flag for stream 172.20.100.104:17384
Aug 21 17:21:33 kamailio1 rtpengine[7564]: DEBUG: [ERRInM44QBd16aMqhJtBfg..]: set FILLED flag for stream 172.20.100.104:17385
Aug 21 17:21:33 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: offer time = 0.000214 sec
Aug 21 17:21:33 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: Replying to 'offer' from 127.0.0.1:33489
Aug 21 17:21:33 kamailio1 rtpengine[7564]: DEBUG: [ERRInM44QBd16aMqhJtBfg..]: Response dump for 'offer' to 127.0.0.1:33489: { "sdp": "v=0
012o=- 13147802492894111 13147802492894111 IN IP4 172.20.120.81
012s=-
012c=IN IP4 172.20.120.81
012t=0 0
012m=audio 35136 RTP/AVP 8 0
012a=rtpmap:8 PCMA/8000
012a=rtpmap:0 PCMU/8000
012a=ptime:20
012a=sendrecv
012a=rtcp:35137
012", "result": "ok" }
Aug 21 17:21:33 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: Received command 'answer' from 127.0.0.1:54991
Aug 21 17:21:33 kamailio1 rtpengine[7564]: DEBUG: [ERRInM44QBd16aMqhJtBfg..]: Dump for 'answer' from 127.0.0.1:54991: { "sdp": "v=0
012o=FreeSWITCH 1503253764 1503253765 IN IP4 172.20.120.79
012s=FreeSWITCH
012c=IN IP4 172.20.120.79
012t=0 0
012m=audio 46700 RTP/AVP 8
012a=rtpmap:8 PCMA/8000
012a=ptime:20
012", "replace": [ "origin", "session-connection" ], "call-id": "ERRInM44QBd16aMqhJtBfg..", "received-from": [ "IP4", "172.20.120.79" ], 
"from-tag": "7847dc70", "to-tag": "vK9UHD7HQy63m", "command": "answer" }
Aug 21 17:21:33 kamailio1 rtpengine[7564]: DEBUG: [ERRInM44QBd16aMqhJtBfg..]: set FILLED flag for stream 172.20.120.79:46700
Aug 21 17:21:33 kamailio1 rtpengine[7564]: DEBUG: [ERRInM44QBd16aMqhJtBfg..]: set FILLED flag for stream 172.20.120.79:46701
Aug 21 17:21:33 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: answer time = 0.000106 sec
Aug 21 17:21:33 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: Replying to 'answer' from 127.0.0.1:54991
Aug 21 17:21:33 kamailio1 rtpengine[7564]: DEBUG: [ERRInM44QBd16aMqhJtBfg..]: Response dump for 'answer' to 127.0.0.1:54991: { "sdp": "v=0
012o=FreeSWITCH 1503253764 1503253765 IN IP4 212.XX.XX.XXX
012s=FreeSWITCH
012c=IN IP4 212.XX.XX.XXX
012t=0 0
012m=audio 35142 RTP/SAVP 8
012a=rtpmap:8 PCMA/8000
012a=ptime:20
012a=sendrecv
012a=rtcp:35143
012a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:RtYs4eVDBmT6O+vKF9diq8LTCv/xUVm4uv/eZo0u
012a=candidate:lz2LQOsbwYd15vBx 1 UDP 2130706431 212.XX.XX.XXX 35142 typ host
012a=candidate:lz2LQOsbwYd15vBx 2 UDP 2130706430 212.XX.XX.XXX 35143 typ host
012", "result": " ...
Aug 21 17:21:33 kamailio1 rtpengine[7564]: DEBUG: [ERRInM44QBd16aMqhJtBfg..]: ... ok" }
Aug 21 17:21:37 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg.. port 35142]: Confirmed peer address as 217.YY.YY.YYY:17384
Aug 21 17:21:37 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg.. port 35136]: Confirmed peer address as 172.20.120.79:46700
Aug 21 17:21:37 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg.. port 35136]: Kernelizing media stream: 172.20.120.79:46700
Aug 21 17:21:37 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg.. port 35142]: Kernelizing media stream: 217.YY.YY.YYY:17384
Aug 21 17:24:59 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: Closing call due to timeout
Aug 21 17:24:59 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: Final packet stats:
Aug 21 17:24:59 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: --- Tag '7847dc70', created 3:26 ago for branch '', in dialogue with 'vK9UHD7HQy63m'
Aug 21 17:24:59 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: ------ Media #1 (audio over RTP/SAVP) using PCMA/8000
Aug 21 17:24:59 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: --------- Port   212.XX.XX.XXX:35142 <>   217.YY.YY.YYY:17384, SSRC 1503092300, 8753 p, 1591186 b, 0 e, 30 ts
Aug 21 17:24:59 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: --------- Port   212.XX.XX.XXX:35143 <>  172.20.100.104:17385 (RTCP), SSRC 0, 0 p, 0 b, 0 e, 206 ts
Aug 21 17:24:59 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: --- Tag 'vK9UHD7HQy63m', created 3:26 ago for branch '', in dialogue with '7847dc70'
Aug 21 17:24:59 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: ------ Media #1 (audio over RTP/AVP) using PCMA/8000
Aug 21 17:24:59 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: --------- Port   172.20.120.81:35136 <>   172.20.120.79:46700, SSRC 3384145944, 3233 p, 557936 b, 0 e, 141 ts
Aug 21 17:24:59 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: --------- Port   172.20.120.81:35137 <>   172.20.120.79:46701 (RTCP), SSRC 0, 0 p, 0 b, 0 e, 206 ts

Aug 21 17:24:59 kamailio1 rtpengine[7564]: ci=ERRInM44QBd16aMqhJtBfg..,
 created_from=127.0.0.1:33489,
 last_signal=1503328893,
 tos=184,
 ml0_start_time=1503328893.185917,
 ml0_end_time=1503329099.000204,
 ml0_duration=205.814287,
 ml0_termination=TIMEOUT,
 ml0_local_tag=7847dc70,
 ml0_local_tag_type=FROM_TAG,
 ml0_remote_tag=vK9UHD7HQy63m,
 payload_type=8,
 ml0_midx1_rtp_endpoint_ip=217.YY.YY.YYY,
 ml0_midx1_rtp_endpoint_port=17384,
 ml0_midx1_rtp_local_relay_ip=212.XX.XX.XXX,
 ml0_midx1_rtp_local_relay_port=35142,
 ml0_midx1_rtp_relayed_packets=8753,
 ml0_midx1_rtp_relayed_bytes=1591186,
 ml0_midx1_rtp_relayed_errors=0,
 ml0_midx1_rtp_last_packet=1503329069,
 ml0_midx1_rtp_in_tos_tclass=0,
 ml0_midx1_rtcp_endpoint_ip=172.20.100.104,
 ml0_midx1_rtcp_endpoint_port=17385,
 ml0_midx1_rtcp_local_relay_ip=212.XX.XX.XXX,
 ml0_midx1_rtcp_local_relay_port=35143,
 ml0_midx1_rtcp_relayed_packets=0,
 ml0_midx1_rtcp_relayed_bytes=0,
 ml0_midx1_rtcp_relayed_errors=0,
 ml0_midx1_rtcp_last_packet=1503328893,
 ml0_midx1_rtcp_in_tos_tclass=0,
 ml1_start_time=1503328893.284014,
 ml1_end_time=1503329099.000205,
 ml1_duration=205.716191,
 ml1_termination=TIMEOUT,
 ml1_local_tag=vK9UHD7HQy63m,
 ml1_local_tag_type=TO_TAG,
 ml1_remote_tag=7847dc70,
 payload_type=8,
 ml1_midx1_rtp_endpoint_ip=172.20.120.79,
 ml1_midx1_rtp_endpoint_port=46700,
 ml1_midx1_rtp_local_relay_ip=172.20.120.81,
 ml1_midx1_rtp_local_relay_port=35136,
 ml1_midx1_rtp_relayed_packets=3233,
 ml1_midx1_rtp_relayed_bytes=557936,
 ml1_midx1_rtp_relayed_errors=0,
 ml1_midx1_rtp_last_packet=1503328958,
 ml1_midx1_rtp_in_tos_tclass=0,
 ml1_midx1_rtcp_endpoint_ip=172.20.120.79,
 ml1_midx1_rtcp_endpoint_port=46701,
 ml1_midx1_rtcp_local_relay_ip=172.20.120.81,
 ml1_midx1_rtcp_local_relay_port=35137,
 ml1_midx1_rtcp_relayed_packets=0,
 ml1_midx1_rtcp_relayed_bytes=0,
 ml1_midx1_rtcp_relayed_errors=0,
 ml1_midx1_rtcp_last_packet=1503328893,
 ml1_midx1_rtcp_in_tos_tclass=0,
`

**Comment by rfuchs** [comment]
The `ts` value in the final packet stats tells you how long ago the last packet was received.

```
Aug 21 17:24:59 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: --------- Port 212.XX.XX.XXX:35142 <> 217.YY.YY.YYY:17384, SSRC 1503092300, 8753 p, 1591186 b, 0 e, 30 ts
Aug 21 17:24:59 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: --------- Port 212.XX.XX.XXX:35143 <> 172.20.100.104:17385 (RTCP), SSRC 0, 0 p, 0 b, 0 e, 206 ts
Aug 21 17:24:59 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: --- Tag 'vK9UHD7HQy63m', created 3:26 ago for branch '', in dialogue with '7847dc70'
Aug 21 17:24:59 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: ------ Media #1 (audio over RTP/AVP) using PCMA/8000
Aug 21 17:24:59 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: --------- Port 172.20.120.81:35136 <> 172.20.120.79:46700, SSRC 3384145944, 3233 p, 557936 b, 0 e, 141 ts
Aug 21 17:24:59 kamailio1 rtpengine[7564]: INFO: [ERRInM44QBd16aMqhJtBfg..]: --------- Port 172.20.120.81:35137 <> 172.20.120.79:46701 (RTCP), SSRC 0, 0 p, 0 b, 0 e, 206 ts
```

The lowest value here is 30 seconds (`30 ts`). So the most recent packet was received 30 seconds ago; all other streams saw their last packet even longer ago. Since the RTP timeout is set to 30 seconds, rtpengine closes the call with a timeout condition.

I can't tell you why rtpengine stopped receiving packets. Either the RTP clients stopped sending RTP, or there's a booboo in your network config somewhere.

**Comment by khorsmann** [comment]
Thanks for your answer. 
I can force the problem with reinvites (on hold) in the Softphones. The problem phones use tls. Without tls reinvites works fine.

**Comment by khorsmann** [comment]
Just for the records. It was an combination of broken Softphone that dont support rfc4028 correct and some wrong rtpengine_manage() calls in kamailio.cfg. rtpengine works like a charme.

On the target sip-server side (FreeSWITCH) i could fix the rfc4028 issue with disabling enable-timer var in the sip_profile. 
```
 <param name="enable-timer" value="false"/>
```
