### ISSUE TITLE
Kernel forwarding activation problem

### ISSUE THREAD

**Issue by kbdfck** [sipwise/rtpengine#386]
Hi all, I'm facing strange issues with kernel mode. On some hosts it works, on others it doesn't. 
During startup there is following error message:
ERR: FAILED TO OPEN KERNEL TABLE 42 (Input/output error), KERNEL FORWARDING DISABLED

Kernel module is loaded, all control files are created, I can add and remove tables, but daemon doesn't catch table specified with this error. There are no much debug in kernel module, so I don't understand how to determine what prevents userspace program  from opening table.

It is a debian 8 with linux-image 3.16.43-2+deb8u3
On other host with similar environment it works without any problems, although there may be difference in some installed library package versions... 
I checked modules size and loaded lsmod sizes - they are same on both systems but rtpengine binary size is different, despite it was built to deb from same rtpengine version

How can I debug this further?

**Comment by rfuchs** [comment]
I/O error is returned if the read/write buffer size used by the daemon doesn't match the size expected by the kernel module. This normally indicates that the daemon was built using a different version of the `xt_RTPENGINE.h` file than was used when the kernel module was built.

Rebuild everything from a clean source tree and make sure there are no artefacts leftover from previous builds.

**Comment by kbdfck** [comment]
I've rebuilt all from mr5.4.1.1.tar.gz, removed all modules and reinstalled, but with no success. Still the same error message...

**Comment by rfuchs** [comment]
Impossible :) You must have another `xt_RTPENGINE.ko` installed somewhere that `modprobe` finds and loads or something.

`dmesg` shows the version of the kernel module when it's loaded. Another thing you can check is: load up both `xt_RTPENGINE.ko` and the main `rtpengine` binary in `gdb` and check the output of the command `print sizeof(struct rtpengine_message)`

**Comment by kbdfck** [comment]
[11326.817015] Registering xt_RTPENGINE module - version 5.4.1.1+0~mr5.4.1.1
rtpengine -v
Version: 5.4.1.1+0~mr5.4.1.1

Can you please explain how to load both of them in gdb to make check you suggested? I have only little experience with gdb. gdb I have on system seems not to load kernel module, but I think I'm doing something wrong despite some googling =).

**Comment by rfuchs** [comment]
Just like that:
```
$ gdb xt_RTPENGINE.ko
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from xt_RTPENGINE.ko...done.
(gdb) print sizeof(struct rtpengine_message)
$1 = 840
```

**Comment by kbdfck** [comment]
Thank you for your help!
After I build module and rtpengine daemon with -ggdb (without dpkg-buildpackage) it shows  
for xt_RTPENGINE.ko
(gdb) print sizeof(struct rtpengine_message)
$1 = 840

And for rtpengine binary it shows 
root@kam-sbc-1-01:/usr/src/rtpengine5.4/rtpengine-mr5.4.1.1/daemon# gdb ./rtpengine 
(gdb) print sizeof(struct rtpengine_message)
$1 = 832

So you were right, they are really different. How can I determine why they are different? Could it be some lib versions or my sources issue?

**Comment by rfuchs** [comment]
The struct size is determined at compile time through the contents of the `xt_RTPENGINE.h` file. There are no external dependencies. The only way that you could end up with two different struct sizes is that there two conflicting versions of that file present. Another possibility might be that a different compiler is used for the daemon than is used for the kernel module.

**Comment by kbdfck** [comment]
You are right, this is exactly what happens there. Different versions - GCC4.8 for kernel module and GCC4.9 for userspace daemon. 
Thank you for you help, will try to solve this.
