### ISSUE TITLE
rtpengine-ctl statistics

### ISSUE THREAD

**Issue by tiglat** [sipwise/rtpengine#387]
Hello,

Could you please explain what do mean the following statistic counters which can printed by "rtpengine-ctl -ip 127.0.0.1 -port 9900 list totals" command?
- "Total number of streams with no relayed packets"
- " Total number of 1-way streams"

Especially I am wonder about 1-way streams. It sounds like one way audio rtp stream. But we have actually 2-way rtp streams. Could you clarify that? 

Thank you in advance.
Best regards
Konstantin

**Comment by rfuchs** [comment]
Not my code (pinging @inf265 ) but if I understand it correctly, when a call is closed and all RTP packet counters are zero, it counts towards the "no relayed packets" counter. Similarly, when a call is closed and the RTP packet counters for one side are zero (but not for the other side), it counts towards the "1-way streams" counter.

**Comment by pkuzak** [comment]
@rfuchs you are right. @tiglat , does this answer your question?

**Comment by tiglat** [comment]
Hello. 
I will describe a little bit more detail my configuration. We make WebRTC call via Kamailio and RTPengine. tcpdump shows that there are two RTP streams from RTPengine to our telephony server. But rtpengine-ctl shows them as 1-way stream. Please look rtpengine-ctl stats below:

Total statistics (does not include current running sessions):

 Uptime of rtpengine                             :4160 seconds
 Total managed sessions                          :1
 Total rejected sessions                         :0
 Total timed-out sessions via TIMEOUT            :0
 Total timed-out sessions via SILENT_TIMEOUT     :0
 Total timed-out sessions via FINAL_TIMEOUT      :0
 Total regular terminated sessions               :1
 Total forced terminated sessions                :0
 Total relayed packets                           :3547
 Total relayed packet errors                     :0
 Total number of streams with no relayed packets :0
 Total number of 1-way streams                   :1
 Average call duration                           :42.687575


Graphite interval statistics (last reported values to graphite):
 Total calls duration                            :0.000000

 Min managed sessions                            :0
 Max managed sessions                            :0
 Min/Max/Avg offer processing delay              :0.000000/0.000000/0.000000 sec
 Min/Max/Avg answer processing delay             :0.000000/0.000000/0.000000 sec
 Min/Max/Avg delete processing delay             :0.000000/0.000000/0.000000 sec


Control statistics:

                Proxy |      Offer |     Answer |     Delete |       Ping |       List |      Query |   StartRec |     Errors
            127.0.0.1 |          1 |          1 |          1 |         22 |          0 |          1 |          0 |          0

**Comment by pkuzak** [comment]
Can you give me the output of the log from _rtpengine_ for that call? The log lines usually have the Call-ID as a prefix, this might help you identify the corresponding lines. Is your _rtpengine_ configured to write a CDR for each call? If so, could you paste it here as well?

**Comment by tiglat** [comment]
Hi, thank you for the quick answer.

Please find the log in attachment.
Our rtpengine is not configured to write a CDR.
[ngcp-rtpengine-callprompt-crop.txt](https://github.com/sipwise/rtpengine/files/1274746/ngcp-rtpengine-callprompt-crop.txt)

**Comment by pkuzak** [comment]
@rfuchs , in the logs, when the query command is received from the Proxy, following looks strange to me: 
```
Sep  4 16:18:42 localhost rtpengine[2387]: DEBUG: [tricjs5hbkobo6cequhr]: ... egr", "created": 1504531099, "in dialogue with": "2284f67d", "medias": [ { "index": 1, "type": "audio", "protocol": "UDP/TLS/RTP/SAVPF", "streams": [ { "local port": 30020, "endpoint": { "family": "IPv4", "address": "192.168.158.139", "port": 63930 }, "advertised endpoint": { "family": "IPv4", "address": "192.168.56.1", "port": 63931 }, "crypto suite": "AES_CM_128_HMAC_SHA1_80", "last packet": 1504531122, "flags": [ "RTP", "RTCP", "filled", "confirmed", "kernelized", "DTLS fingerprint verified"  ...
```
Both flags, for RTP and RTCP, are set. Is this normal behavior?

**Comment by tiglat** [comment]
From browser to the rtpengine we have muxed rtp and rtcp stream. But from rtpengine to our telephony we use demuxed streams. That is our config. So what is the problem?

**Comment by pkuzak** [comment]
A problem might arise in the code. When retrieving statistics, we have something like this:
```C
                if (ml->active_dialogue) {
                        // --- go through partner ml and search the RTP
                        for (k = ml->active_dialogue->medias.head; k; k = k->next) {
                                md = k->data;

                                for (o = md->streams.head; o; o = o->next) {
                                        ps2 = o->data;
                                        if ((PS_ISSET(ps2, RTP) && !PS_ISSET(ps2, RTCP))) {
                                                // --- only RTP is interesting
                                                found = 1;
                                                break;
                                        }
                                }
                                if (found) { break; }
                        }
                }
```
So it is checked whether either the RTP flag is set or the RTCP. A situation where both are set is not considered. We have provided a fix, can you test it if it works for you: https://github.com/1and1/rtpengine/tree/fix_1way_statistics

**Comment by tiglat** [comment]
Thank you very much. I will test your fix and report a result.

**Comment by tiglat** [comment]
I've just replaced my installed 5.2.1.1 version with your fixed rtpengine binary. Is that ok? Should I replaced rtpengine-ctl or kernel module or iptables module?  If it is ok, fix doesn't work.

**Comment by pkuzak** [comment]
Just replacing the binary should be enough. I assume you've restarted the process. No need to replace the other mentioned stuff. We will investigate this further. As we can't really test it, because we don't have such a setup, it would be great if you could help us testing. We will comment here when we have news.

**Comment by tiglat** [comment]
Ok, thank you

**Comment by claudiupb** [comment]
Looking at the logs I see an RTCP stream with 0 packets:
` Sep  4 16:19:12 localhost rtpengine[2387]: INFO: [tricjs5hbkobo6cequhr]: --------- Port 192.168.158.180:30001 <> 192.168.158.139:10001 (RTCP), 0 p, 0 b, 0 e, 1504531099 last_packet`

I suspect this is counted and this is why the statistics are wrong.

I have added a new commit to the branch https://github.com/1and1/rtpengine/tree/fix_1way_statistics
This adds some log messages when the counters should be increased, so we can better see what is happening.
Can you please add this commit also, test it, and then attach the logs?

**Comment by tiglat** [comment]
I need to clarify some detail - we establish RTCP, but we don't use it actually. That is why it is zero. So this counter shows correct value. Please confirm if i need test this new fix?

**Comment by pkuzak** [comment]
Yes, please try the new fix. We understand your setup. What we want to see is that the RTCP stream is mistakenly interpreted as the RTP stream in the statistics. In the new commit we also added some logs, which should help us identify the issue.

**Comment by tiglat** [comment]
Hello,

Excuse me. My test was wrong. By mistake I built the binary on other branch. So now it looks like statistics are correct. Please find the stats below and log in the attachment.

Total statistics (does not include current running sessions):

 Uptime of rtpengine                             :156 seconds
 Total managed sessions                          :1
 Total rejected sessions                         :0
 Total timed-out sessions via TIMEOUT            :0
 Total timed-out sessions via SILENT_TIMEOUT     :0
 Total timed-out sessions via FINAL_TIMEOUT      :0
 Total regular terminated sessions               :1
 Total forced terminated sessions                :0
 Total relayed packets                           :2070
 Total relayed packet errors                     :0
 Total number of streams with no relayed packets :0
 Total number of 1-way streams                   :0
 Average call duration                           :55.395167


Graphite interval statistics (last reported values to graphite):
 Total calls duration                            :0.000000

 Min managed sessions                            :0
 Max managed sessions                            :0
 Min/Max/Avg offer processing delay              :0.000000/0.000000/0.000000 sec
 Min/Max/Avg answer processing delay             :0.000000/0.000000/0.000000 sec
 Min/Max/Avg delete processing delay             :0.000000/0.000000/0.000000 sec


Control statistics:

                Proxy |      Offer |     Answer |     Delete |       Ping |       List |      Query |   StartRec |     Errors
            127.0.0.1 |          1 |          2 |          1 |          0 |          0 |          1 |          0 |          0
[rtpengine-ctl-issue.log.txt](https://github.com/sipwise/rtpengine/files/1284785/rtpengine-ctl-issue.log.txt)

**Comment by claudiupb** [comment]
Thank you for testing this!
Looking into the attached logs it seems that the streams are detected properly even if multiplexed. I have removed the second commit and created a pull request for the fix.

**Comment by tiglat** [comment]
Cool! Thank you.
