### ISSUE TITLE
Advertised interface selection question with forwarding issue

### ISSUE THREAD

**Issue by kbdfck** [sipwise/rtpengine#389]
I'm trying to implement rtpengine on host with multiple IP addresses on one ethernet interface with vlan tag, eth0.33 for example. There is no NAT, but my idea is to select advertized IP address from Kamailio config - this is needed to mask different domains to different RTP IPs. So I added multiple IP addresses to config file interface= section. 

When I'm specifying media-address from Kamailio rtpengine_manage, sometimes there is no media forwarding at all, sometimes it forwards in one-direction, and no kernelization happens.

When rtpengine has one IP and selected with rtpengine_setid, all works fine.

Is such setup supposed to work? It advertises correct addresses and there is inbound traffic to corresponding IP from endpoints, but no forwarding and kernelization.

**Comment by rfuchs** [comment]
Can you give a concrete example of what you're trying to do?

**Comment by kbdfck** [comment]
Sure, sorry for absence of details.
My rtpengine server is located on the same machine as Kamailio. Server has multiple IP addresses - 1.2.3.4, 2.3.4.5, 6.7.8.9 and domain.com, domain2.com, domain3.com are resolved to corresponding IPs.

My aim is when kamailio relays traffic it has ability to select media IP depenging on source/target domain, so for requests to domain1.com should advertise 1.2.3.4 as media ip, for domain2.com advertise 2.3.4.5 and so on.

I have these IPs as aliases on primary network interface and try to specify them in rtpengine_manage with media-address. For domain2.com I pass media-address=2.3.4.5.

rtpengine correctly advertises it in SDP and hosts are sending traffic to this ip, but rtpengine doesn't forward it between endpoints and doesn't kernelize.

**Comment by rfuchs** [comment]
OK, I see. No, that's not the proper approach. You need to use named interfaces together with the `direction=` options instead.

For example, in your config you would declare your interfaces as `interface = alice/1.2.3.4;bob/2.3.4.5;charlie=3.4.5.6` and then tell rtpengine at the moment of the initial invite (the offer) which interface the call is originating from and which interface it's going to. So if a call is coming from the `charlie` domain and going to the `alice` domain, you would use `rtpengine_offer("direction=charlie direction=alice")`

**Comment by kbdfck** [comment]
Thanks for explanation. 
I'll try to use named interfaces, and if I will go this way, can I use same interface for both endpoints? My main task is to advertise proper address to outside world domains' users. 
Will it be enough to use only one named interface in rtpengine_offer to make it advertised to both sides?

**Comment by rfuchs** [comment]
To use the same interface for both direction, just specify it twice, as in `direction=foo direction=foo`

**Comment by kbdfck** [comment]
Thanks Richard, this way it worked as expected!
