### ISSUE TITLE
Problem setting up

### ISSUE THREAD

**Issue by mvh77** [sipwise/rtpengine#391]
Hi,

I have trouble getting rtpengine to work, when I start kamailio I get a lot of this in the kamailio log:
```
ERROR: rtpengine [rtpengine.c:2204]: rtpp_test(): proxy responded with invalid response
```

and this in the rtpengine log:
```
 WARNING: Failed to properly parse UDP command line '0_5481_0 d7:command4:pinge' from 127.0.0.1:48226, using fallback RE
```

I'm quite a kamailio newb so sorry for that. I'm trying rtpengine because I need DTLS.

I'm starting rtpengine with
```
/usr/sbin/rtpengine --interface=10.102.15.35 --listen-udp=127.0.0.1:12221 --pidfile=/var/run/rtpengine.pid -f -L 7 -E
```

I've tried with kamailio 4.3, 4.4, 5.0 and rtpengine 5.4.1.1. There's no info about what version of rtpengine work with what version of kamailio. Does everything work with everything? Thanks!

**Comment by rfuchs** [comment]
Use `listen-ng=...` instead of `listen-udp=...`

**Comment by mvh77** [comment]
Ok thanks!

**Comment by ashupednekar** [comment]
@mvh77  did that work ?

**Comment by 9to1url** [comment]
I have the same issue, after changed to listen-ng it works. :-)
