### ISSUE TITLE
transcoding support?

### ISSUE THREAD

**Issue by syadnom** [sipwise/rtpengine#392]
I see that rtpengine doesn't currently support transcoding.  There is a huge gap in the market here for an open source sip/rtpproxy that can handle complex codecs such as opus.

My need would be specifically for opus and possibly siren7 and ilbc. 

Is there an effort to add this support and/or do any of the developers do feature bounties?  I think I could drum up a few people to kick in a worthwhile sum of money.

Thanks.

**Comment by rfuchs** [comment]
I'll get back to you

**Comment by digipigeon** [comment]
Hi Richard, I have sent you a contact request. I am interested in collaborating on and/or sponsoring this feature, please let me know.

**Comment by rfuchs** [comment]
I'll let you know - give me a few days

**Comment by syadnom** [comment]
Thanks Richard.   I think the guys are ivozprovider might be interested in
sponsoring this as well.  They make heavy use of rtpengine.  I might be
able to get some of the mirtapbx guys in as well.

**Comment by rfuchs** [comment]
Taking this to email - you should hear back shortly.

**Comment by syadnom** [comment]
great, thanks

**Comment by pavanps** [comment]
HI All,
Any new version of rtpengine with trans-coding can be excepted soon?. Please lets us know if there is any possibility of such thing.
Thanks

**Comment by pavanps** [comment]
Hi,
I have downloaded the latest code of rtpengine and when running make, am getting this error "/usr/local/src/rtpengine/daemon/codec.c:877: undefined reference to `g_queue_free_full'", please let me know what more libraries are required.
