### ISSUE TITLE
warning messages when using zrtp

### ISSUE THREAD

**Issue by juha-h** [sipwise/rtpengine#395]
When I make a call with ZRTP media, I get lots of these kind of warnings to syslog:

Sep 14 11:46:56 box rtpengine[1107]: WARNING: [611716df453d2bc9 port 60033]: Unknown RTCP version 0

Is there some means to avoid them?

If not, it might be a good idea to change the level of these messages to DEBUG.

**Comment by rfuchs** [comment]
The best option would be to just support the ZRTP packet format, recognize it as such and not try to parse it as RTP. I'll try to make that happen.

**Comment by rfuchs** [comment]
See the commit referenced above. This is a bit of a shot in the dark as I don't have a good ZRTP test case. Let me know.

**Comment by juha-h** [comment]
Unfortunately the commit didn't remove the warnings.  First comes:

Sep 14 18:36:32 box rtpengine[29041]: WARNING: [f187a2d36b766308 port 60128]: Error parsing RTP header: invalid header version
Sep 14 18:36:32 box rtpengine[29041]: WARNING: [f187a2d36b766308 port 60129]: Error parsing RTCP header: invalid header version
and then these:

Sep 14 18:36:32 box rtpengine[29041]: WARNING: [f187a2d36b766308 port 60129]: Unknown RTCP version 0
...

Should I try to capture the rtp trafic?

**Comment by rfuchs** [comment]
Yes please, RTP and RTCP

**Comment by juha-h** [comment]
I'll try, but in the meanwhile, if you want to try yourself, Linphone (at least Android version from Play Store) supports ZRTP.   In Settings/Call, choose ZRTP Media encryption.

**Comment by rfuchs** [comment]
Looks like these are not (only?) ZRTP packets causing these messages, but rather that Linphone is talking STUN even when no ICE support was advertised. Perhaps it's easier to just drop the log level on those messages.

**Comment by juha-h** [comment]
Richard Fuchs writes:

> Looks like these are not (only?) ZRTP packets causing these messages,
> but rather that Linphone is talking STUN even when no ICE support was
> advertised. Perhaps it's easier to just drop the log level on those
> messages.

Yes, it may be an issue in Linphone, since I'm not getting those
warnings with baresip.

-- Juha

**Comment by jalung** [comment]
Hi, to be clear : is it fair to say the zrtp packets are still transmitted, but log level changed as a result of not being supported? Just curious about the "return -1".

thanks.

**Comment by rfuchs** [comment]
Yes, they're still transmitted. The `return -1` simply signals that they should be attempted to parsed further.
