### ISSUE TITLE
Compile error in Centos 7

### ISSUE THREAD

**Issue by goup2010** [sipwise/rtpengine#396]
When try to install latest version in Centos 7 I get follow error:

make: *** No rule to make target `rtcp_xr.h', needed by `.depend'.  Stop.

I have installed follow modules:
mysql mariadb-devel mariadb-server gcc gcc-c++ bison bison-devel flex make expat
expat-devel net-snmp-devel  libxml2 libxml2-devel openssl-devel 
xmlrpc-c-devel lynx pcre pcre-devel ncurses-devel ncurses-libs gdb git
 net-snmp net-snmp-devel net-snmp-libs net-snmp-utils
unixODBC unixODBC-devel mysql-connector-odbc libtool-ltdl-devel
 iptables-devel iptables-services xmlrpc-c-devel libpcap-devel
 glib2-devel json-glib-devel hiredis-devel libevent-devel
 kernel-devel pjproject-devel

**Comment by rfuchs** [comment]
Delete your `.depend` file or do a `git clean -x -d -f`. Or just start from a clean download.

**Comment by goup2010** [comment]
Thanks!!!
Now working fine!

2017-09-18 0:23 GMT+03:00 Richard Fuchs <notifications@github.com>:
