### ISSUE TITLE
read() blocks on cli socket, resulting in rtpengine not responding to requests

### ISSUE THREAD

**Issue by efiop** [sipwise/rtpengine#399]
read() gets blocked waiting for input from the other end of the socket. It has logic for error check for non-blocking fd, but O_NONBLOCK isn't actually set.

cli.c +831
```
   nfd = accept(fd, (struct sockaddr *) &sin, &sinl);
   if (nfd == -1) {
       if (errno == EAGAIN || errno == EWOULDBLOCK) {
           goto cleanup2;
       }
       ilog(LOG_INFO, "Accept error:%s", strerror(errno));
       goto next;
   }

   ilog(LOG_INFO, "New cli connection from " DF, DP(sin));

   do {
       readbytes = read(nfd, inbuf+inlen, MAXINPUT-inlen);
       if (readbytes == -1) {
           if (errno == EAGAIN || errno == EWOULDBLOCK) {
               ilog(LOG_INFO, "Could currently not read CLI commands. Reason:%s", strerror(errno));
               goto cleanup;
           }
           ilog(LOG_INFO, "Could currently not read CLI commands. Reason:%s", strerror(errno));
       }
       inlen += readbytes;
   } while (readbytes > 0 && inlen < sizeof(inbuf)-1);
```

**Comment by rfuchs** [comment]
No no, that doesn't work. The CLI code is designed to be blocking right now. It's missing the multiplexing and buffering between invocations to be made non-blocking. Ideally the code should use the interface from `streambuf.c`

**Comment by efiop** [comment]
Oh, my bad. I noticed that one day it was hanging on that read for over 24h and concluded by "if (errno == EAGAIN || errno == EWOULDBLOCK) {" that there was just fcntl missing. Maybe you have some hints on what might be the cause? Would this patch in a more proper form(that you've mentioned) be a valid fix for this kind of issue?

**Comment by efiop** [comment]
A bit more info. My rtpengine instance is running on 1 CPU droplet without --num-threads specified, thus single instance of poller_loop hangs there and as a result whole rtpengine becomes not operational.
I agree that my latest patch is not a proper solution. A more better way would be i.e. to set some timeout or something like that, so we could drop that connection if it hangs too much. Probably it needs to be accompanied by --num-threads 2 to improve the flow on single CPU.

**Comment by efiop** [comment]
New update. Turned out there was some scanning on default cli port, which resulted in strange CLI commands('#001', '#003') received. If you take a look at cli.c in master(5.x) branch:
```
   } else {
       sprintf(replybuffer, "%s:%s\n", "Unknown or incomplete command:", inbuf);
   }

   do {
       rc += write( nfd, (char *)&replybuffer, strlen(replybuffer) );
   } while (rc < strlen(replybuffer));

cleanup:
   close(nfd);
   /* in case multiple incoming connections exist, read all of them */
   goto next;
```
Notice that 'goto next'(it is absent in 4.x, that is probably why this problem never occurred previously) . So after receiving bad command and sending response directly to nfd(without logging the error), it goes back to accept on that same fd. This is probably the point where everything goes wrong, as the other end probably doesn't expect to receive 'Unknown or incomplete command' back. This is where I'm not sure about the exact details as I'm new to CLI and don't have access to that scanning tool, so I suspect that this is the point where read() hangs and results in full rtpengine halt on single CPU droplet.

@rfuchs Shouldn't we just drop such connections if we receive bad CLI command? Even if we receive unknown command, we should drop the whole connection, as there might be consequences to skipping it. I would love to hear what you think.

Thanks,
Ruslan

**Comment by rfuchs** [comment]
The connection is dropped (`close(nfd)`) on error. The `goto next` must be present because the polling is done edge-triggered and so the handling function can be fired with multiple events in the queue. Simply bailing out at an error and not retrying would make it possible to lose events. The accept `fd` is set non-blocking, so returning to `accept` is not a problem if there actually aren't any waiting connections.

The quick fix here is to make sure rtpengine never runs with a single thread. The long-term solution is to change the CLI code to properly to multiplexing and non-blocking I/O, e.g. to use the `streambuf` interface.
