### ISSUE TITLE
rtcp-mux trouble

### ISSUE THREAD

**Issue by ovoshlook** [sipwise/rtpengine#404]
Hi. Preparing env to use with updated chrome (58) where rtcpMuxPolicy: required instead of negotiated

found that rtcp-mux-accept and rtcp-mux-offer just adds 
a=rtcp=mux
but
a=rtcp:<port number> still not same with m=audio
In webRTC context also has 2 ice candidates: for RTP and RTCP

Tried to find how to resolve this with RTPEngine but did not found any flags that accepts to do this
Is it unresolvable for now?

**Comment by rfuchs** [comment]
Currently rtpengine adheres to the RFC, which states that even when offering rtcp-mux, a separate RTCP port must still be provided and separate ICE candidates must also be provided, in case the recipient does not accept the rtcp-mux offer and these separate ports would then act as a fallback.

I understand that WebRTC mandates use of rtcp-mux and so a fallback RTCP port isn't really necessary, but doing this still goes against the RFC. Is there something in writing somewhere that overrides this?

**Comment by ovoshlook** [comment]
No no. I dont wanna say that you are not right. I fully agree with you that RFC is a main doc which need to be guided.
I just wanted to ask do you have plans for any hack or somethig like this for making it work with rtpengine side according this reality made by browsers?

**Comment by rfuchs** [comment]
See commit cc056c148f for a possible quick fix/implementation for this. Replace `rtcp-mux-offer` with `rtcp-mux-require` in your config script. Let me know how that works for you.

**Comment by ovoshlook** [comment]
Wow thx!
Will test today- let you know. Suppose by your morning test will be ready

**Comment by ovoshlook** [comment]
Can it be moved as console key? I use kamailio and Kamailio's rtpengine module says that don't know this param (because not added at the rtpengine module for use as API I suppose)
Meanwhile i will try to add it to the module formy dev. But i not too match good at C programming. dont knwo how many time it will take.

**Comment by rfuchs** [comment]
The kamailio module doesn't care about the parameters, it accepts any string starting with `rtcp-mux-`

**Comment by ovoshlook** [comment]
Yep sorry. Was got wrong branch. and also already saw at the rtpengine module that all just string
Yep if fixes SDP. thx.

**Comment by jeemeekay** [comment]
I added the line $var(rtpp_flags) = "replace-origin replace-session-connection rtcp-mux-require via-branch=1 strict-source "; into my rtpengine.cfg.tt2 file, however I'm still having this issue where it fails with Chrome as it requires rtcp-mux, I'm new with sipwise so would appreciate any help here please?

**Comment by ovoshlook** [comment]
If you have troubles with chrome i suppose your trouble other than this.
This trouble only on chromium ( 63 dev version )

**Comment by jeemeekay** [comment]
Hi, I finally fixed my problem. I had to update my rtpengine.cfg.tt2 properly as I updated the wrong section in the config. Sorry False Alarm all working for me now.
