### ISSUE TITLE
rtpengine is unable to send ssrc params to the Browser

### ISSUE THREAD

**Issue by raviraja0969** [sipwise/rtpengine#405]
Hi All,

Hope you are doing good.

We are facing one issue with Edge browser. We can negotiate STUN, DTLs successfully . As per wireshark packets we can see that all the rtp is flowing to the edge browser but no audio at browser side. But its clearly audible at called party side. 

After deep observation we came to know that Edge browser havent received ssrc parameters in 200 OK message. Could you please suggest me about this issue.

Thanks
Sreenivas

**Comment by rfuchs** [comment]
Currently rtpengine does not generate SSRC SDP attributes if they're not provided by the client. Reason being that rtpengine cannot know the SSRC before any RTP packets are actually received.

Can you somehow confirm that the lack of SSRC attributes is actually what's breaking audio?

**Comment by raviraja0969** [comment]
Hi Richard,
Thanks for the reply.

Yes ... since we havent received ssrc attributes in 200 OK .. we are unable to listen the voice eventhough we are receiving the audio (UDP packets)...

**Comment by raviraja0969** [comment]
Basically this issue only arises with Edge browser

**Comment by raviraja0969** [comment]
Hi Richard,

Can you please guide us if there is possibility of handling ssrc attributes.

Thanks
Ravi Raja

**Comment by rfuchs** [comment]
As I said, right now this is not supported

**Comment by rfuchs** [comment]
Cleaning up old tickets
