### ISSUE TITLE
WAV file distortion on G729 codec

### ISSUE THREAD

**Issue by lishubing** [sipwise/rtpengine#410]
I'm using rtpengine-recording to capture recording files from metadata, and my recording of G729 codec distorted after convert to wav file. It sound just like the whole sound file has been stretched. The example output wav files shows that a ringing sound being distored.
[35ff1c47-5950-47c8-8793-796e2f1bd743-65e6227997fa890b-mix.wav.zip](https://github.com/sipwise/rtpengine/files/1401485/35ff1c47-5950-47c8-8793-796e2f1bd743-65e6227997fa890b-mix.wav.zip)

Here are my .conf files:

```
[rtpengine]
table = 0
timeout = 60
silent-timeout = 3600
tos = 184
pidfile = /var/run/rtpengine.pid
port-min = 35000
port-max = 65000
recording-dir = /data/record/spool
recording-method = proc
recording-format = eth

[rtpengine-recording]
table = 0
resample-to = 8000
output-format = wav
spool-dir = /data/record/spool
output-dir = /data/record/wav
output-mixed = 1
num-threads = 4

```

Thank you!

**Comment by rfuchs** [comment]
Hard to tell from just a dialtone. Is it just the `mix` output that's affected or individual outputs as well? Does it make a difference if resampling is disabled? Would you be able to provide a matching pcap?

**Comment by lishubing** [comment]
I have tried:
1. remove output-mixed param.
2.remove resample-to param.
3.change #define NUM_INPUTS 4 to #define NUM_INPUTS 2 as you mentioned in #350 
4.change output-format to mp3
But none of them worked.

Here is a test recording[testmsg.wav.zip](https://github.com/sipwise/rtpengine/files/1403936/testmsg.wav.zip), it sound like a short sentence was stretched to a weird long one.
I can't reach the pcap file right now, I'll try to get one later.

BTW, I just found that not all the recording are being distorted, few recordings are good but most are bad.

**Comment by lishubing** [comment]
Here is a sample pcap file and its wav file, just see what you can get from them. [output.zip](https://github.com/sipwise/rtpengine/files/1405934/output.zip)

**Comment by lishubing** [comment]
A typical sample is here: 
[sample.zip](https://github.com/sipwise/rtpengine/files/1407206/sample.zip)
In this case, the conversation lasted for 42 seconds, but the duration of the separate channel are only few seconds. 
I dumped the whole log of rtpengine-recording in debug level, you can check that in the zipfile.

**Comment by rfuchs** [comment]
I can reproduce it through the pcap from `output.zip`, but only in the mixed output. The individual outputs are fine. Can you confirm that this is also what happens on your side?

**Comment by lishubing** [comment]
In most cases, there is always a broken one among the two individual output, the broken output contain last only 1-2 seconds, maybe that lead to the bad mixed output. 

Are both your two individual outputs good? 

Btw, due to this issue,  I already change the the recording method to pcap, and use wireshark to extract audio output. That works just fine.

**Comment by rfuchs** [comment]
Yes, for me only the mixed output is affected. The individual outputs are fine But I suppose the effects could be different depending on ffmpeg/libav version used. The above commit fixes it for me.

**Comment by lishubing** [comment]
Sadly it doesn't fix for me. This [sample](https://github.com/sipwise/rtpengine/files/1418060/sample2.zip) reproduce what I metioned before. One of the output is distorted. You can check the wav files for detail.

My libav version is:

```
 libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
```
Thank you!

**Comment by rfuchs** [comment]
I can't reproduce that with the provided pcap. I notice that your files are only 4000 Hz instead of 8000, do you have resampling enabled or is that a mistake?

FTR, you can use the script `utils/kernel-intercept-pcap-replay.pl` to replay a pcap into the recording daemon and have it recreate the output files. The main `rtpengine` daemon must not be running at the same time.

**Comment by rfuchs** [comment]
I can reproduce this neither with nor without resampling to 4000, neither on Debian jessie nor on Debian stretch. What distro are you on?

**Comment by lishubing** [comment]
The 4000 resample parameter is a mistake, sorry for that. However, removing the parameter didn't help.
I tried this on Ubuntu 16.04 and 17.10, the same results.
I will try the perl script to see what can I find.
