### ISSUE TITLE
SSRC hash table exceeded size limit

### ISSUE THREAD

**Issue by lishubing** [sipwise/rtpengine#417]
Rtpengine log has large numbers of duplicate messages:
`INFO: [5abc689b-d0f4-4557-af92-ee2595c81795 port 44422]: SSRC hash table exceeded size limit (trying to add 1400913811)`

It seems to happen when a connection hold for a long time.
Although its log level is INFO, I wonder if that indicates any performance issue?

**Comment by rfuchs** [comment]
Not a performance issue but rather a protection against excessive memory usage. Does your RTP client switch SSRC a lot?

**Comment by lishubing** [comment]
It seems that client didn't switch SSRC. The client tried to add the same SSRC but failed again and again. The duplicate messages are all about the same callid and SSRC.

Here is the log:
```
Nov  8 11:42:23 rtpengine-2 rtpengine[825]: INFO: [5abc689b-d0f4-4557-af92-ee2595c81795 port 44422]: SSRC hash table exceeded size limit (trying to add 2069607654)
Nov  8 11:42:23 rtpengine-2 rtpengine[825]: message repeated 17 times: [ INFO: [5abc689b-d0f4-4557-af92-ee2595c81795 port 44422]: SSRC hash table exceeded size limit (trying to add 2069607654)]
Nov  8 11:42:23 rtpengine-2 rtpengine[825]: INFO: [5abc689b-d0f4-4557-af92-ee2595c81795 port 44422]: SSRC hash table exceeded size limit (trying to add 2069607654)
Nov  8 11:42:23 rtpengine-2 rtpengine[825]: message repeated 65 times: [ INFO: [5abc689b-d0f4-4557-af92-ee2595c81795 port 44422]: SSRC hash table exceeded size limit (trying to add 2069607654)]
...
```

**Comment by rfuchs** [comment]
Well, once the hash table is full, the same SSRC would give you this error again and again. But there must be a reason that the hash table got full in the first place, and this can only happen when a lot of different SSRC have been used in the past.

**Comment by lishubing** [comment]
I checked some cases and found some cases in which client may change its SSRC in few particular situations, like changing its network from wifi to mobile traffic, or move from one mobile base station to another. In these cases, a session may last for a long time with multiple change of SSRC.

Is it possible to allow SSRC change more than 20 times? It is quite a common occasion when making long calls on VOIP.

**Comment by rfuchs** [comment]
Try with the commit referenced above (a30b47d)

**Comment by lishubing** [comment]
Thanks Richard, I'll check that in production environment.
I'll let you know if it fix the issue.

**Comment by lishubing** [comment]
Hi Richard, sorry for the slow response.

I checked the log, and the commit did fix for me. Thanks again for your help!

**Comment by thadin** [comment]
Is there any indication when this fix is finding its way to a release so we can update through the Debian apt repositories? We're currently still using mr5.4.* (Jessie) releases, so it would be great if the fix would be released there.

**Comment by rfuchs** [comment]
As long as you're using the mr5.4 branch (not mr5.4.x), you should see it within a few days. 5.4 is already end of life so there will be no more minor mr5.4.x releases.
