### ISSUE TITLE
Support for AEAD_AES_128_GCM/AEAD_AES_256_GCM crypto suites

### ISSUE THREAD

**Issue by foucse** [sipwise/rtpengine#422]
Currently (23bc99e) RTP Engine doesn't support the AEAD_AES_128_GCM/AEAD_AES_256_GCM crypto suites [https://tools.ietf.org/html/rfc5116].

So those crypto suites are just stripped out from the INVITEs SDPs when using the NG protocol in Kamailio RTP Engine module.

Will those crypto suites be supported some day ?

From what I understand, to add support for them, I just need to add them to the table in crypto.c ?

https://github.com/sipwise/rtpengine/blob/23bc99ed814bf6ca20e4d578d4154f9daf4c7520/daemon/crypto.c#L38-L62

**Comment by rfuchs** [comment]
We don't currently have any concrete plans to add support for these crypto suites, but there's nothing that speaks against having them added. Like you said, you would have to add them to the list in `crypto.c`, and provide an appropriate implementation according to RFC 7714 (a la `aes_cm_encrypt_rtp()` etc).

If kernel mode forwarding should be supported as well, an analogous implementation must be present in the kernel module code.

**Comment by justmobiledev** [comment]
Hi,

we would like to use Kamailio/RTPEngine with AEAD_AES_256_GCM for SRTP-DTLS. 
Can you please provide a status if this crypto is being considered for implementation?

Also, do you have some more details what would have to be done to implement this crypto according to aes_cm_encrypt_rtp()?

thanks!

Chris

**Comment by ffloimair** [comment]
I think this issue can be closed. Support for this has been added in https://github.com/sipwise/rtpengine/pull/1133
