### ISSUE TITLE
media port changes bewteen 2 answers

### ISSUE THREAD

**Issue by MarcoHierl** [sipwise/rtpengine#423]
Dear all,
I'm a newbie in rtpengine, please be patient..

I want to play an announcement bevor connecting a call to the callee, but media port within the replies to the caller changes between the first REPLY183 (originally from announcement server) and the REPLY200 (originally from the caller).

The caller does not accept the cange of the port. It's a big Ericsson iBCF...
What can I do?

(one more question:  "replace": [ "session-connection"] seems to have no influence on the c= line? It's changed even without this)

this is the log: (port changes from 22272 to 22286)

Nov 23 15:54:16 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de]: Received command 'offer' from 10.250.56.5:39533
Nov 23 15:54:16 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de]: Dump for 'offer' from 10.250.56.5:39533: { "sdp": "v=0#015#012o=root 1034552580 1034552580 IN IP4 10.249.152.10#015#012s=Asterisk PBX 11.22.0#015#012c=IN IP4 10.249.152.10#015#012t=0 0#015#012m=audio 21418 RTP/AVP 8 101#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-16#015#012a=ptime:20#015#012a=sendrecv#015#012", "direction": [ "internal", "internal" ], "replace": [ "origin" ], "transport-protocol": "RTP/AVP", "call-id": "6211d0936a5f97f5517c70873c182119@next-id.de", "received-from": [ "IP4", "10.249.152.10" ], "from- ...
Nov 23 15:54:16 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de]: ... tag": "as772abc3d", "command": "offer" }
Nov 23 15:54:16 rtp-dtag-bln rtpengine[10274]: NOTICE: [6211d0936a5f97f5517c70873c182119@next-id.de]: Creating new call
Nov 23 15:54:16 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de]: set FILLED flag for stream 10.249.152.10:21418
Nov 23 15:54:16 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de]: set FILLED flag for stream 10.249.152.10:21419
Nov 23 15:54:16 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de]: offer time = 0.000380 sec
Nov 23 15:54:16 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de]: Replying to 'offer' from 10.250.56.5:39533
Nov 23 15:54:16 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de]: Response dump for 'offer' to 10.250.56.5:39533: { "sdp": "v=0#015#012o=root 1034552580 1034552580 IN IP4 10.250.56.6#015#012s=Asterisk PBX 11.22.0#015#012c=IN IP4 10.250.56.6#015#012t=0 0#015#012m=audio 22258 RTP/AVP 8 101#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-16#015#012a=ptime:20#015#012a=sendrecv#015#012a=rtcp:22259#015#012a=ice-ufrag:UbytpI1r#015#012a=ice-pwd:HR3ygaTTLtXKultLz26b9oOr4V#015#012a=candidate:US0WIoZouGYljMMr 1 UDP 2130706431 10.250.56.6 22258 typ host#015#012a=candidate:US0WIoZouGYljMMr 2 UDP 2130706430 10.250.56.6 22 ...
Nov 23 15:54:16 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de]: ... 259 typ host#015#012", "result": "ok" }
Nov 23 15:54:16 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de]: Received command 'answer' from 10.250.56.5:39533
Nov 23 15:54:16 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de]: Dump for 'answer' from 10.250.56.5:39533: { "sdp": "v=0#015#012o=root 1837947679 1837947679 IN IP4 10.249.152.21#015#012s=Asterisk PBX 13.9.1#015#012c=IN IP4 10.249.152.21#015#012t=0 0#015#012m=audio 12632 RTP/AVP 8 101#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-16#015#012a=maxptime:150#015#012a=sendrecv#015#012", "direction": [ "internal", "internal" ], "replace": [ "origin" ], "transport-protocol": "RTP/AVP", "call-id": "6211d0936a5f97f5517c70873c182119@next-id.de", "received-from": [ "IP4", "10.249.152.21" ], "f ...
Nov 23 15:54:16 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de]: ... rom-tag": "as772abc3d", "to-tag": "as1819b543", "command": "answer" }
Nov 23 15:54:16 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de]: set FILLED flag for stream 10.249.152.21:12632
Nov 23 15:54:16 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de]: set FILLED flag for stream 10.249.152.21:12633
Nov 23 15:54:16 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de]: Shutting down ICE agent (nothing to do)
Nov 23 15:54:16 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de]: answer time = 0.000082 sec
Nov 23 15:54:16 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de]: Replying to 'answer' from 10.250.56.5:39533
Nov 23 15:54:16 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de]: Response dump for 'answer' to 10.250.56.5:39533: { "sdp": "v=0#015#012o=root 1837947679 1837947679 IN IP4 10.250.56.6#015#012s=Asterisk PBX 13.9.1#015#012c=IN IP4 10.250.56.6#015#012t=0 0#015#012m=audio 22272 RTP/AVP 8 101#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-16#015#012a=maxptime:150#015#012a=sendrecv#015#012a=rtcp:22273#015#012a=candidate:US0WIoZouGYljMMr 1 UDP 2130706431 10.250.56.6 22272 typ host#015#012a=candidate:US0WIoZouGYljMMr 2 UDP 2130706430 10.250.56.6 22273 typ host#015#012", "result": "ok" }
Nov 23 15:54:20 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de port 22258]: Confirmed peer address as 10.249.152.21:12632
Nov 23 15:54:20 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de port 22272]: Confirmed peer address as 10.249.152.10:21418
Nov 23 15:54:20 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de port 22272]: Kernelizing media stream: 10.249.152.10:21418
Nov 23 15:54:20 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de port 22258]: Kernelizing media stream: 10.249.152.21:12632
Nov 23 15:54:21 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22259]: Calling handler for RTCP packet type 200
Nov 23 15:54:21 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22259]: SR from 1415314287: RTP TS 40064 PC 253 OC 40064 NTP TS 3720437664/2040522474=3720437664.475096
Nov 23 15:54:21 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22259]: RR from 1415314287 about 1883414745: FL 0 TL 0 HSR 40744 J 9 LSR 0 DLSR 0
Nov 23 15:54:21 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22259]: Calculated jitter for 1883414745 is 1 ms
Nov 23 15:54:21 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22259]: Adding opposide side RTT of 0 us
Nov 23 15:54:21 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22259]: Calculated MOS from RR for 1415314287 is 4.4
Nov 23 15:54:21 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22259]: Calling handler for RTCP packet type 202
Nov 23 15:54:21 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de port 22259]: Confirmed peer address as 10.249.152.21:12633
Nov 23 15:54:21 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22273]: Calling handler for RTCP packet type 200
Nov 23 15:54:21 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22273]: SR from 1883414745: RTP TS 1619447240 PC 250 OC 40000 NTP TS 3720437661/3622819026=3720437661.843503
Nov 23 15:54:21 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22273]: RR from 1883414745 about 1415314287: FL 1 TL 1 HSR 62084 J 6 LSR 0 DLSR 3776829390
Nov 23 15:54:21 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22273]: Calculated jitter for 1415314287 is 0 ms
Nov 23 15:54:21 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22273]: Adding opposide side RTT of 0 us
Nov 23 15:54:21 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22273]: Calculated MOS from RR for 1883414745 is 4.4
Nov 23 15:54:21 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22273]: Calling handler for RTCP packet type 202
Nov 23 15:54:21 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de port 22273]: Confirmed peer address as 10.249.152.10:21419
Nov 23 15:54:26 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22273]: Calling handler for RTCP packet type 200
Nov 23 15:54:26 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22273]: SR from 1883414745: RTP TS 1619487240 PC 500 OC 80000 NTP TS 3720437666/3621375917=3720437666.843167
Nov 23 15:54:26 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22273]: RR from 1883414745 about 1415314287: FL 0 TL 0 HSR 6709 J 1 LSR 0 DLSR 3777157070
Nov 23 15:54:26 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22273]: Calculated jitter for 1415314287 is 0 ms
Nov 23 15:54:26 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22273]: Adding opposide side RTT of 0 us
Nov 23 15:54:26 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22273]: Calculated MOS from RR for 1883414745 is 4.4
Nov 23 15:54:26 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22273]: Calling handler for RTCP packet type 202
Nov 23 15:54:27 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de]: Received command 'answer' from 10.250.56.5:42449
Nov 23 15:54:27 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de]: Dump for 'answer' from 10.250.56.5:42449: { "sdp": "v=0#015#012o=root 416060021 416060021 IN IP4 10.250.56.31#015#012s=sip call#015#012c=IN IP4 10.250.56.31#015#012t=0 0#015#012m=audio 16362 RTP/AVP 8 101#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-16#015#012a=ptime:20#015#012a=sendrecv#015#012", "direction": [ "internal", "internal" ], "replace": [ "origin" ], "transport-protocol": "RTP/AVP", "call-id": "6211d0936a5f97f5517c70873c182119@next-id.de", "received-from": [ "IP4", "10.250.56.31" ], "from-tag": "as772abc3 ...
Nov 23 15:54:27 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de]: ... d", "to-tag": "as3095ae9f", "command": "answer" }
Nov 23 15:54:27 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de]: set FILLED flag for stream 10.250.56.31:16362
Nov 23 15:54:27 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de]: set FILLED flag for stream 10.250.56.31:16363
Nov 23 15:54:27 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de]: answer time = 0.000279 sec
Nov 23 15:54:27 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de]: Replying to 'answer' from 10.250.56.5:42449
Nov 23 15:54:27 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de]: Response dump for 'answer' to 10.250.56.5:42449: { "sdp": "v=0#015#012o=root 416060021 416060021 IN IP4 10.250.56.6#015#012s=sip call#015#012c=IN IP4 10.250.56.6#015#012t=0 0#015#012m=audio 22286 RTP/AVP 8 101#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-16#015#012a=ptime:20#015#012a=sendrecv#015#012a=rtcp:22287#015#012a=candidate:US0WIoZouGYljMMr 1 UDP 2130706431 10.250.56.6 22286 typ host#015#012a=candidate:US0WIoZouGYljMMr 2 UDP 2130706430 10.250.56.6 22287 typ host#015#012", "result": "ok" }
Nov 23 15:54:27 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de port 22272]: Switching local interface to 10.250.56.6:22272
Nov 23 15:54:28 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de port 22286]: Switching local interface to 10.250.56.6:22286
Nov 23 15:54:30 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22259]: Calling handler for RTCP packet type 200
Nov 23 15:54:30 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22259]: SR from 2061244268: RTP TS 40000 PC 250 OC 40000 NTP TS 3720437670/3597251077=3720437670.837550
Nov 23 15:54:30 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22259]: RR from 2061244268 about 1883414745: FL 0 TL 0 HSR 41199 J 7 LSR 0 DLSR 3777418821
Nov 23 15:54:30 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22259]: Calculated jitter for 1883414745 is 0 ms
Nov 23 15:54:30 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22259]: Adding opposide side RTT of 0 us
Nov 23 15:54:30 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22259]: Calculated MOS from RR for 2061244268 is 4.4
Nov 23 15:54:30 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22259]: Calling handler for RTCP packet type 202
Nov 23 15:54:31 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de port 22258]: Confirmed peer address as 10.250.56.31:16362
Nov 23 15:54:31 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de port 22286]: Confirmed peer address as 10.249.152.10:21418
Nov 23 15:54:31 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de port 22258]: Kernelizing media stream: 10.250.56.31:16362
Nov 23 15:54:31 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22287]: Calling handler for RTCP packet type 200
Nov 23 15:54:31 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22287]: SR from 1883414745: RTP TS 1619527400 PC 751 OC 120160 NTP TS 3720437671/3623312947=3720437671.843618
Nov 23 15:54:31 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22287]: RR from 1883414745 about 1415314287: FL 1 TL 1 HSR 6959 J 5 LSR 0 DLSR 3777484750
Nov 23 15:54:31 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22287]: Calculated jitter for 1415314287 is 0 ms
Nov 23 15:54:31 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22287]: Adding opposide side RTT of 0 us
Nov 23 15:54:31 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22287]: Calculated MOS from RR for 1883414745 is 4.4
Nov 23 15:54:31 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de port 22287]: Calling handler for RTCP packet type 202
Nov 23 15:54:31 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de port 22287]: Confirmed peer address as 10.249.152.10:21419
Nov 23 15:54:31 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de]: Received command 'answer' from 10.250.56.5:39533
Nov 23 15:54:31 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de]: Dump for 'answer' from 10.250.56.5:39533: { "sdp": "v=0#015#012o=root 416060021 416060022 IN IP4 10.250.56.31#015#012s=sip call#015#012c=IN IP4 10.250.56.31#015#012t=0 0#015#012m=audio 16362 RTP/AVP 8 101#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-16#015#012a=ptime:20#015#012a=sendrecv#015#012", "direction": [ "internal", "internal" ], "replace": [ "origin" ], "transport-protocol": "RTP/AVP", "call-id": "6211d0936a5f97f5517c70873c182119@next-id.de", "received-from": [ "IP4", "10.250.56.31" ], "from-tag": "as772abc3 ...
Nov 23 15:54:31 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de]: ... d", "to-tag": "as3095ae9f", "command": "answer" }
Nov 23 15:54:31 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de]: answer time = 0.000120 sec
Nov 23 15:54:31 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de]: Replying to 'answer' from 10.250.56.5:39533
Nov 23 15:54:31 rtp-dtag-bln rtpengine[10274]: DEBUG: [6211d0936a5f97f5517c70873c182119@next-id.de]: Response dump for 'answer' to 10.250.56.5:39533: { "sdp": "v=0#015#012o=root 416060021 416060022 IN IP4 10.250.56.6#015#012s=sip call#015#012c=IN IP4 10.250.56.6#015#012t=0 0#015#012m=audio 22286 RTP/AVP 8 101#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-16#015#012a=ptime:20#015#012a=sendrecv#015#012a=rtcp:22287#015#012a=candidate:US0WIoZouGYljMMr 1 UDP 2130706431 10.250.56.6 22286 typ host#015#012a=candidate:US0WIoZouGYljMMr 2 UDP 2130706430 10.250.56.6 22287 typ host#015#012", "result": "ok" }
Nov 23 15:54:35 rtp-dtag-bln rtpengine[10274]: INFO: [6211d0936a5f97f5517c70873c182119@next-id.de port 22286]: Confirmed peer address as 10.249.152.10:21418

**Comment by rfuchs** [comment]
Try adding the `port-latching` option in your calls to the `rtpengine_*` functions.

**Comment by MarcoHierl** [comment]
Great! port-latching did it! Thanks a lot!!!!
