### ISSUE TITLE
complie error under ubuntu 

### ISSUE THREAD

**Issue by futsystems** [sipwise/rtpengine#424]
In file included from epoll.h:7:0,
                 from epoll.c:1:
types.h:8:29: fatal error: libavutil/frame.h: No such file or directory
 #include <libavutil/frame.h>

i have installed  libavutil-dev
so what header package  i missed?

**Comment by denyspozniak** [comment]
Hello!

**Comment by denyspozniak** [comment]
Hello!
I could build packages on Ubuntu 16.04.3 couple of days ago, seems you are doing something wrong.
Check issue #421 maybe it will help you.

**Comment by rfuchs** [comment]
Which Ubuntu version are you using?
