### ISSUE TITLE
CPU usage upto 300% + rtpengine continusly printing  ERR: Too many packets in UDP receive queue (more than 50), aborting loop.

### ISSUE THREAD

**Issue by Ravi116** [sipwise/rtpengine#425]
Hi 
i am using opensips + rtpengine git-master-af1db75 with ipv4 and ipv6 interface like without kernel module support.
init option :: /usr/local/bin/rtpengine -p /var/run/rtpengine.pid --interface=internal/0.0.0.0 --interface=external/::1 -n 60000 -m 10000 -M 20000 --log-facility=local1 -L 7
my call flow requires to loop around my opensips and this creates loop in call as well as rtp flow due to this rtpengine continuously prints error messages like this even after call is hangup : 
 ERR: [tnscnRNq77 port 10386]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
i have seen rtpengine cpu usage gone upto 300% on server even when none sip call was going on please provide relevant help on this issue.

**Comment by rfuchs** [comment]
Simple: do not make rtpengine loop your RTP to itself. Unlike rtpproxy, rtpengine does not have built-in protection against rewriting an SDP twice. See issue #415 for a possible solution if you can't otherwise avoid passing an already rewritten SDP back into rtpengine.

**Comment by rfuchs** [comment]
Closing due to 1477f97
