### ISSUE TITLE
How disable rtcp offer?

### ISSUE THREAD

**Issue by kertor** [sipwise/rtpengine#428]
Hello! Some vendors(for example Zyxcel) no ability to work with attribute "a=rtcp:XXXXX" in SDP.
Case:
1) We send INVITE Zyxel router with media attribute "a=rtcp:XXXXX"(XXXXX here is random port) in SDP.
2) Zyxel router cannot process this SDP and drop call. He send me "406 Not Acceptable" reply.
I did not find how i may disable this option. Zyxel engineers say me that problem in rtcp attribute.
Can yoy help me?
I use rtpengine "Version: 4.5.0-0.el7" in a bunch with opensips.

Thanks!

**Comment by rfuchs** [comment]
Point the Zyxel engineers to the last sentence of section 5.13 of RFC 4566:  `If an attribute is received that is not understood, it MUST be ignored by the receiver.`

**Comment by kertor** [comment]
I gave this information to Zyxel engineers , but maybe have ability to disable attribute on rtpengine side for good compability with various SIP clients?

**Comment by rbetancor** [comment]
@kertor that will not be a good aproach ... that will be a workaround for a broken UAC
