### ISSUE TITLE
asymmetrik rtp to callee after early announcement

### ISSUE THREAD

**Issue by MarcoHierl** [sipwise/rtpengine#429]
Hello,
after an early announcement I make a 2nd rtpengine_offer for the INVITE to the callee. But now rtp is not send from the port that is indicated in the INVITE anymore.
I tried "reset", "media=handover", "port-latching" and "symmetric"... but always get asymmetric rtp on the leg to the caller.
What can I do?
thanks and best regards
  Marco

**Comment by MarcoHierl** [comment]
SORRY: wrong heading!!! it's the callee (b-site) where the problem occurs!!
The rtp to the caller (a-site) is symmetric!!!!

**Comment by rfuchs** [comment]
Can you post a concrete example of what's happening?

**Comment by MarcoHierl** [comment]
attached is the log from rtpengine and a sip trace.

call from 10.250.56.13 to my sip proxy (10.250.56.5 with rtpengine on 10.250.56.6) 10.249.152.21 is the announcement server, 10.250.56.31 is the gateway to the callee (b-site). The rtp port in the INVITE to the callee is 25190. But we are sending rtp from port 25222

[sip_overview_withRTP.txt](https://github.com/sipwise/rtpengine/files/1539063/sip_overview_withRTP.txt)

[rtpengine_cbc1.log](https://github.com/sipwise/rtpengine/files/1538680/rtpengine_cbc1.log)

**Comment by MarcoHierl** [comment]
Richard, If the traces in my last comment are not enough, I also can send a pcap file... but I was not able to upload it here..

**Comment by MarcoHierl** [comment]
attached is the pcap file:

In frame 1 we receive the INVITE
In frame 2 we send INVITE to the announcement server
In frame 3216 we send INVITE to the gateway to the callee
e.g. in frame 5005 RTP is send from port 26090 instead of 26064 -> but we need to habe symmetric rtp

[cbc2.zip](https://github.com/sipwise/rtpengine/files/1558351/cbc2.zip)

**Comment by rfuchs** [comment]
The problem is that you have 3 SIP clients (tag `as5b47a2d0` making the offer, then `as16480267` and `as0ff319ce` both answering) participating in the dialog. You left out the "final packet stats" portion of the log files, but this would actually be the most helpful lines in seeing the established forwarding setup at the end of the call.

Neither port latching nor the media handover feature work in this scenario, as ports as allocated specific to each participating SIP client (identified by its tag). I'm not sure if there's a feasible solution for this, but I do agree that the signalling part results in an incorrect port due to port latching enabled. I'll have a closer look at this.

For reference, this is what the flow of events looks like. Excuse the bad graphics. The port 26090 is (probably) allocated when the second answer from the third SIP client comes in.

```
SIP client	      |	rtpengine	      |	rtpengine	      |	SIP client
		      |			      |			      |
as5b47a2d0 -> offer ->|			      |			      |
10.250.56.15:21592    |			      |			      |
		      |			      |	-> offer ->	      |
		      |			      |	10.250.56.6:26064     |
		      |			      |			      |
		      |			      |			      |
		      |			      |			      |
		      |			      |			      |	<- answer <- as16480267
		      |			      |			      |	10.249.152.21:12682
		      |	<- answer <-	      |			      |
		      |	10.250.56.6:26080     |			      |
		      |			      |			      |
		      |			      |			      |
		      |			      |			      |	^ confirmed OK
^ confirmed OK	      |			      |			      |
		      |			      |			      |
		      |			      |			      |
		      |			      |			      |
		      |			      |			      |
as5b47a2d0 -> offer ->|			      |			      |
10.250.56.15:21592    |			      |			      |
		      |			      |	-> offer ->	      |
		      |			      |	10.250.56.6:26064     |
		      |			      |			      |
		      |			      |			      |
		      |			      |			      |	<- answer <- as0ff319ce
		      |			      |			      |	10.250.56.31:17744
		      |	<- answer <-	      |			      |
		      |	10.250.56.6:26080     |			      |
		      |			      |			      |
		      |			      |			      |	^ confirmed OK
^ confirmed as 10.250.56.15:22180
```

**Comment by MarcoHierl** [comment]
thanks for your help & here are the missing lines:

Dec 14 08:15:00 rtp-dtag-bln rtpengine[1038]: INFO: [1f1721066d0e341b252a5ca7282a9f59@next-id.de]: Call branch 'as0ff319ce' (via-branch '') deleted
Dec 14 08:16:06 rtp-dtag-bln rtpengine[1038]: INFO: [1f1721066d0e341b252a5ca7282a9f59@next-id.de]: Closing call due to timeout
Dec 14 08:16:06 rtp-dtag-bln rtpengine[1038]: INFO: [1f1721066d0e341b252a5ca7282a9f59@next-id.de]: Final packet stats:
Dec 14 08:16:06 rtp-dtag-bln rtpengine[1038]: INFO: [1f1721066d0e341b252a5ca7282a9f59@next-id.de]: --- Tag 'as5b47a2d0', created 1:56 ago for branch '', in dialogue with 'as0ff319ce'
Dec 14 08:16:06 rtp-dtag-bln rtpengine[1038]: INFO: [1f1721066d0e341b252a5ca7282a9f59@next-id.de]: ------ Media #1 (audio over RTP/AVP) using PCMA/8000
Dec 14 08:16:06 rtp-dtag-bln rtpengine[1038]: INFO: [1f1721066d0e341b252a5ca7282a9f59@next-id.de]: --------- Port     10.250.56.6:26080 <>    10.250.56.15:22180, SSRC 2077538516, 917 p, 157724 b, 0 e, 96 ts
Dec 14 08:16:06 rtp-dtag-bln rtpengine[1038]: INFO: [1f1721066d0e341b252a5ca7282a9f59@next-id.de]: --------- Port     10.250.56.6:26081 <>    10.250.56.15:22181 (RTCP), SSRC 1203598759, 3 p, 192 b, 0 e, 101 ts
Dec 14 08:16:06 rtp-dtag-bln rtpengine[1038]: INFO: [1f1721066d0e341b252a5ca7282a9f59@next-id.de]: --- Tag 'as16480267', created 1:56 ago for branch '', in dialogue with 'as5b47a2d0'
Dec 14 08:16:06 rtp-dtag-bln rtpengine[1038]: INFO: [1f1721066d0e341b252a5ca7282a9f59@next-id.de]: ------ Media #1 (audio over RTP/AVP) using PCMA/8000
Dec 14 08:16:06 rtp-dtag-bln rtpengine[1038]: INFO: [1f1721066d0e341b252a5ca7282a9f59@next-id.de]: --------- Port     10.250.56.6:26064 <>    10.250.56.31:17744, SSRC 541315084, 932 p, 159888 b, 0 e, 95 ts
Dec 14 08:16:06 rtp-dtag-bln rtpengine[1038]: INFO: [1f1721066d0e341b252a5ca7282a9f59@next-id.de]: --------- Port     10.250.56.6:26065 <>    10.250.56.31:17745 (RTCP), SSRC 541315084, 3 p, 192 b, 0 e, 97 ts
Dec 14 08:16:06 rtp-dtag-bln rtpengine[1038]: INFO: [1f1721066d0e341b252a5ca7282a9f59@next-id.de]: --- Tag 'as0ff319ce', created 1:44 ago for branch '', in dialogue with 'as5b47a2d0'
Dec 14 08:16:06 rtp-dtag-bln rtpengine[1038]: INFO: [1f1721066d0e341b252a5ca7282a9f59@next-id.de]: ------ Media #1 (audio over RTP/AVP) using unknown codec
Dec 14 08:16:06 rtp-dtag-bln rtpengine[1038]: INFO: [1f1721066d0e341b252a5ca7282a9f59@next-id.de]: --------- Port     10.250.56.6:26090 <>    10.250.56.31:17744, SSRC 0, 0 p, 0 b, 0 e, 104 ts
Dec 14 08:16:06 rtp-dtag-bln rtpengine[1038]: INFO: [1f1721066d0e341b252a5ca7282a9f59@next-id.de]: --------- Port     10.250.56.6:26091 <>    10.250.56.31:17745 (RTCP), SSRC 0, 0 p, 0 b, 0 e, 104 ts
Dec 14 08:16:06 rtp-dtag-bln rtpengine[1038]: INFO: [1f1721066d0e341b252a5ca7282a9f59@next-id.de]: --- SSRC 1203598759
Dec 14 08:16:06 rtp-dtag-bln rtpengine[1038]: INFO: [1f1721066d0e341b252a5ca7282a9f59@next-id.de]: ------ Average MOS 4.3, lowest MOS 4.3 (at 0:10), highest MOS 4.4 (at 0:05)
Dec 14 08:16:06 rtp-dtag-bln rtpengine[1038]: INFO: [1f1721066d0e341b252a5ca7282a9f59@next-id.de]: --- SSRC 541315084
Dec 14 08:16:06 rtp-dtag-bln rtpengine[1038]: INFO: [1f1721066d0e341b252a5ca7282a9f59@next-id.de]: ------ Average MOS 4.3, lowest MOS 4.2 (at 0:14), highest MOS 4.4 (at 0:19)
Dec 14 08:16:06 rtp-dtag-bln rtpengine[1038]: INFO: [1f1721066d0e341b252a5ca7282a9f59@next-id.de]: --- SSRC 885284920
Dec 14 08:16:06 rtp-dtag-bln rtpengine[1038]: INFO: [1f1721066d0e341b252a5ca7282a9f59@next-id.de]: ------ Average MOS 4.4, lowest MOS 4.4 (at 0:05), highest MOS 4.4 (at 0:05)
opensips@rtp-dtag-bln:/var/log/opensips$

**Comment by rfuchs** [comment]
Right, so the third SIP client `as0ff319ce` was supposed to talk to local port 26090, but ended up being unused due to the port latching option. I would expect this scenario to work correctly without port latching, but of course you would see an expected port change.

**Comment by MarcoHierl** [comment]
Yes, that's correct. Unfortunately german telekom neither accepts the port change NOR asymmetric rtp... 
I really hope that a solution is possible!?!

**Comment by rfuchs** [comment]
Cleaning up old tickets
