### ISSUE TITLE
rtpengine loop

### ISSUE THREAD

**Issue by kertor** [sipwise/rtpengine#431]
Hello guys, in prod we had problem with loop on rtpengine. The loop gradually occupied all the ports and caused a denial of service. On our side we solved problem in this way: if in SDP from UAC we receive ip address(External or Internal) opensips blocked call.
Scheme of problem:
![error_scheme](https://user-images.githubusercontent.com/3471049/33989414-7947723e-e0d8-11e7-821e-d46363bfa311.png)

On zabbix graph we have this screen(total current sessions):
![zabbix](https://user-images.githubusercontent.com/3471049/33989441-8fc8b392-e0d8-11e7-95bf-545f11498a3f.png)

In log of rtpengine we have:
```
Dec  8 00:21:30 rtp1 rtpengine[4329]: INFO: [K6yw15oPgPYZo8qWbPBtkQ..]: Received command 'offer' from 10.55.30.182:53271
Dec  8 00:21:30 rtp1 rtpengine[4329]: NOTICE: [K6yw15oPgPYZo8qWbPBtkQ..]: Creating new call
Dec  8 00:21:30 rtp1 rtpengine[4329]: INFO: [K6yw15oPgPYZo8qWbPBtkQ..]: offer time = 0.000169 sec
Dec  8 00:21:30 rtp1 rtpengine[4329]: INFO: [K6yw15oPgPYZo8qWbPBtkQ..]: Replying to 'offer' from 10.55.30.182:53271
Dec  8 00:22:01 rtp1 rtpengine[4329]: INFO: [K6yw15oPgPYZo8qWbPBtkQ..]: Received command 'delete' from 10.55.30.182:34262
Dec  8 00:22:01 rtp1 rtpengine[4329]: INFO: [K6yw15oPgPYZo8qWbPBtkQ..]: Scheduling deletion of call branch '682f7805' (via-branch '') in 5 seconds
Dec  8 00:22:01 rtp1 rtpengine[4329]: INFO: [K6yw15oPgPYZo8qWbPBtkQ..]: delete time = 0.000085 sec
Dec  8 00:22:01 rtp1 rtpengine[4329]: INFO: [K6yw15oPgPYZo8qWbPBtkQ..]: Replying to 'delete' from 10.55.30.182:34262
Dec  8 00:22:04 rtp1 rtpengine[4329]: INFO: [K6yw15oPgPYZo8qWbPBtkQ..]: Received command 'offer' from 10.55.50.50:55484
Dec  8 00:22:04 rtp1 rtpengine[4329]: INFO: [K6yw15oPgPYZo8qWbPBtkQ..]: offer time = 0.000125 sec
Dec  8 00:22:04 rtp1 rtpengine[4329]: INFO: [K6yw15oPgPYZo8qWbPBtkQ..]: Replying to 'offer' from 10.55.50.50:55484
Dec  8 00:22:04 rtp1 rtpengine[4329]: INFO: [K6yw15oPgPYZo8qWbPBtkQ..]: Received command 'answer' from 10.55.30.182:34262
Dec  8 00:22:04 rtp1 rtpengine[4329]: INFO: [K6yw15oPgPYZo8qWbPBtkQ..]: answer time = 0.000085 sec
Dec  8 00:22:04 rtp1 rtpengine[4329]: INFO: [K6yw15oPgPYZo8qWbPBtkQ..]: Replying to 'answer' from 10.55.30.182:34262
Dec  8 00:22:04 rtp1 rtpengine[4329]: INFO: [K6yw15oPgPYZo8qWbPBtkQ.. port 17560]: Switching local interface to 90.90.90.90:17560
Dec  8 00:22:04 rtp1 rtpengine[4329]: ERR: [K6yw15oPgPYZo8qWbPBtkQ.. port 17560]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
Dec  8 00:22:04 rtp1 rtpengine[4329]: ERR: [K6yw15oPgPYZo8qWbPBtkQ.. port 17560]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
Dec  8 00:22:04 rtp1 rtpengine[4329]: ERR: [K6yw15oPgPYZo8qWbPBtkQ.. port 17560]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
Dec  8 00:22:04 rtp1 rtpengine[4329]: ERR: [K6yw15oPgPYZo8qWbPBtkQ.. port 17560]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
Dec  8 00:22:04 rtp1 rtpengine[4329]: ERR: [K6yw15oPgPYZo8qWbPBtkQ.. port 17560]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
Dec  8 00:22:04 rtp1 rtpengine[4329]: ERR: [K6yw15oPgPYZo8qWbPBtkQ.. port 17560]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
Dec  8 00:22:04 rtp1 rtpengine[4329]: ERR: [K6yw15oPgPYZo8qWbPBtkQ.. port 17560]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
Dec  8 00:22:04 rtp1 rtpengine[4329]: ERR: [K6yw15oPgPYZo8qWbPBtkQ.. port 17560]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
Dec  8 00:22:04 rtp1 rtpengine[4329]: ERR: [K6yw15oPgPYZo8qWbPBtkQ.. port 17560]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
Dec  8 00:22:04 rtp1 rtpengine[4329]: ERR: [K6yw15oPgPYZo8qWbPBtkQ.. port 17560]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
Dec  8 00:22:04 rtp1 rtpengine[4329]: ERR: [K6yw15oPgPYZo8qWbPBtkQ.. port 17560]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
Dec  8 00:22:04 rtp1 rtpengine[4329]: ERR: [K6yw15oPgPYZo8qWbPBtkQ.. port 17560]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
Dec  8 00:22:04 rtp1 rtpengine[4329]: ERR: [K6yw15oPgPYZo8qWbPBtkQ.. port 17560]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
....
```

Can you think about this and try to implement protection from such loops?
Opensips(ver. 2.2) install on sip-nodes.
Thanks!

**Comment by rfuchs** [comment]
You're supposed to have protection against this in your SIP proxy or other controlling agent. There are legitimate reasons to loop a call through rtpengine multiple times, so integrating a protection against this into rtpengine is not a feasible solution.

**Comment by rfuchs** [comment]
Supported now by 1477f97

**Comment by nikbyte** [comment]
Hi Richard!

I reviwed this issue today and found that this commit is addressed to another issue than described here. This commit just protects when call is looping inside rtpengine few times. But here described a little bit different situation.

For example, we have rtpengine with external IP 8.8.8.8

Only one call is enough to hang it.

INVITE -> with any SDP
<- 100
<- 183 - 8.8.8.8 in SDP as rtp source.

rtpengine starts to loop this call inside, it uses too much of CPU too.

**Comment by rfuchs** [comment]
So how does this happen?

**Comment by nikbyte** [comment]
I don't know exactly. Possible DOS attempts or broken UAC. But when I receive own IP in SDP, I have an issue.

**Comment by nikbyte** [comment]
We fixed this in opensips configuration by checking IP address in SDP, but it would be great to add such check on your side.

**Comment by soulofmischief87** [comment]
Is it possible this happening due to a reinvite going through the only reply route and causing several answers commands? I had this issue when using ICE clients that reinvited to and moved out of the relay. My solution was to use a different route without rtpengine commands in it.

**Comment by nikbyte** [comment]
No. Switch where we met this is common proxy. It passes calls in only one direction, ICE is disabled there and we saw this in 183 or 200 on 1st INVITE.

**Comment by nikbyte** [comment]
And also we suppress retransmits and use flags to not call offer/answer more than one time.

**Comment by nikbyte** [comment]
I think check must be added to rtpengine to not loop self IP, agree with me?

**Comment by nikbyte** [comment]
Maybe open separate issue?

**Comment by rfuchs** [comment]
The problem is that rtpengine sending to its own address is a valid use case.

**Comment by nikbyte** [comment]
Not for everybody. Maybe add flag to deny this behaviour?

**Comment by nikbyte** [comment]
Or improve loop protect feature with this.

**Comment by mrsanvicente** [comment]
Hello nikbyte,
Can you explain more or give a sample of how you implemented the loop protect at opensips?
I have loop protect enabled at rtpengine and still the aborting loop issue is happening, and all RTP drops.

ERR: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets
possible

Thank you in advance
