### ISSUE TITLE
Unknown STUN attribute: 0xc057

### ISSUE THREAD

**Issue by BroWater** [sipwise/rtpengine#436]
Hi all,

If there is a call includes WebRTC from Chrome，
the log appears to be flooded by the followings:

Jan  3 16:20:44 rtpengine[6333]: NOTICE: [vt8svf90kjrte7trnkk1 port 30428]: Unknown STUN attribute: 0xc057
Jan  3 16:20:46 rtpengine[6333]: NOTICE: [vt8svf90kjrte7trnkk1 port 30398]: Unknown STUN attribute: 0xc057
Jan  3 16:20:46 rtpengine[6333]: NOTICE: [vt8svf90kjrte7trnkk1 port 30428]: Unknown STUN attribute: 0xc057
Jan  3 16:20:49 rtpengine[6333]: NOTICE: [vt8svf90kjrte7trnkk1 port 30398]: Unknown STUN attribute: 0xc057
Jan  3 16:20:49 rtpengine[6333]: NOTICE: [vt8svf90kjrte7trnkk1 port 30428]: Unknown STUN attribute: 0xc057
Jan  3 16:20:50 rtpengine[6333]: WARNING: [1501294409 port 30526]: Error parsing RTP header: invalid header version
Jan  3 16:20:51 rtpengine[6333]: NOTICE: [vt8svf90kjrte7trnkk1 port 30398]: Unknown STUN attribute: 0xc057
Jan  3 16:20:51 rtpengine[6333]: NOTICE: [vt8svf90kjrte7trnkk1 port 30428]: Unknown STUN attribute: 0xc057
Jan  3 16:20:54 rtpengine[6333]: NOTICE: [vt8svf90kjrte7trnkk1 port 30398]: Unknown STUN attribute: 0xc057
Jan  3 16:20:54 rtpengine[6333]: NOTICE: [vt8svf90kjrte7trnkk1 port 30428]: Unknown STUN attribute: 0xc057
Jan  3 16:20:56 rtpengine[6333]: NOTICE: [vt8svf90kjrte7trnkk1 port 30398]: Unknown STUN attribute: 0xc057
Jan  3 16:20:56 rtpengine[6333]: NOTICE: [vt8svf90kjrte7trnkk1 port 30428]: Unknown STUN attribute: 0xc057
Jan  3 16:20:59 rtpengine[6333]: NOTICE: [vt8svf90kjrte7trnkk1 port 30398]: Unknown STUN attribute: 0xc057

After searching on Google,
I got some answers from the following links:
(1) https://www.ietf.org/mail-archive/web/ice/current/msg00247.html
(2) https://www.ietf.org/mail-archive/web/ice/current/msg00305.html
(3) https://tools.ietf.org/html/draft-thatcher-ice-network-cost-00

Will this case be handled in the future version?

Thanks.

**Comment by rfuchs** [comment]
Sounds like it's safe to ignore this attribute for now
