### ISSUE TITLE
Recording - inband ringing

### ISSUE THREAD

**Issue by dancmsgit** [sipwise/rtpengine#438]
When receiving a 183 session progress I end up with a separate recording of the inband ringing.

Is there anyway to signal rtpengine to not record this or other way to get around this?

**Comment by rfuchs** [comment]
You could delay starting recording until the 200 OK comes in.

**Comment by dancmsgit** [comment]
Great idea... That worked nicely, thanks!

**Comment by dancmsgit** [comment]
While not getting inband ringing now, I still end up with multiple streams, only when receiving 183 Session Progress,

I am starting recording using - rtpengine_manage("trust-address replace-origin replace-session-connection record-call metadata=xxxx:xxxx|";

I am seeing the above command executed only once during the call. 

Anything else that could cause this behavior?

**Comment by dancmsgit** [comment]
Calls with 3 recorded streams:
caller
callee
<1 second of nothing.

Calls with 4 streams:
Cant draw any correlation from the audio. Different portions of the call.

Call with 5 recorded streams:
ringing
caller stream
callee (IVR + ringing)
callee (person as result of IVR selection, hold music during transfer)
callee (new IVR + new person)

Note that callee in all cases is a registered UA (appears to be a PBX).

SDP headers all indicate proper IP's, no re-invites.

**Comment by rfuchs** [comment]
I'm guessing they're all from different SSRCs?

**Comment by dancmsgit** [comment]
I suspect but haven't verified. I will look into when I'm in position to do so. If this is the case, anything that can be done to remedy?

**Comment by dancmsgit** [comment]
Confirmed, different SSRC's.

**Comment by rfuchs** [comment]
Other than enabling the full mixed output and disabling single outputs, no. Currently there's no support for selectively mixing or ignoring outputs.

**Comment by dancmsgit** [comment]
Ok. For full mixed output, are there any options to control type of mix (mono/stereo)?

**Comment by rfuchs** [comment]
Number of channels is determined by whatever the clients are using. Sample rate is too, unless you use the resample-to option.

**Comment by dancmsgit** [comment]
Ok, thanks,
