### ISSUE TITLE
disable or make configurable kernel support & logging

### ISSUE THREAD

**Issue by sigxcpu76** [sipwise/rtpengine#440]
We are using rtpengine in user space, as containers in Kubernetes. The nodes are in GKE and we don't want to depend on underlying node architecture for the kernel stuff.
The problem is that each call spews this in logs for each call:
```
WARNING: [1473e38c55f9e549247ba2370979b1e8@10.32.6.61:5060 port 11952]: No support for kernel packet forwarding available (interface to kernel module not open)
```

Logging missing kernel support at the beginning is enough. We already know that we don't have support.

Can the missing kernel support logging be put behind a flag?

**Comment by rfuchs** [comment]
These should go away if you use the `table = -1` config option

**Comment by sigxcpu76** [comment]
Thanks! I will check this and report back.
