### ISSUE TITLE
iOS Safari - No Media

### ISSUE THREAD

**Issue by msalman212** [sipwise/rtpengine#441]
Hi Team,

Since iOS and Mac browsers now support WebRTC, I have been trying to test interoperability for iOS Safari.

**Scenario**:
Caller: Chrome Desktop Browser
Callee: iOS Safari

**Result**: no media flows, also see some ICE disconnects in RTPengine logs.

rtpengine **logs**
https://pastebin.com/bDv5FyWb

Seems codecs are negotiated fine, is it due to bundle support ? Can you point me to some direction here. Thanks

Regards,
Salman

**Comment by rfuchs** [comment]
Hard to say from just that. Are there are errors or messages on any of the browsers?

**Comment by rfuchs** [comment]
Closing due to lack of feedback, possibly fixed by e84fd8612ba49f151ad0a904e94f7236ddd38ce8
