### ISSUE TITLE
Consistent callid logging

### ISSUE THREAD

**Issue by negbie** [sipwise/rtpengine#442]
Hi,
would it be possible to log the callid in a more consistent way? From this:

rtpengine[18904]: INFO: [4A5234339745199346116]: Replying to 'answer'
rtpengine[18904]: INFO: [4A5234339745199346116 port 34560]: Confirmed peer address

To mby this

rtpengine[18904]: INFO: [ID="4A5234339745199346116"]: Replying to 'answer'
rtpengine[18904]: INFO: [ID="4A5234339745199346116" port 34560]: Confirmed peer address

**Comment by rfuchs** [comment]
Why?

**Comment by negbie** [comment]
Less expensive grok pattern to parse
