### ISSUE TITLE
why not remove kernel table when shutdown

### ISSUE THREAD

**Issue by zhouyu8x** [sipwise/rtpengine#443]
Each time a restart will report 'kernel table already exists' error because the table has already created during the first start. Manually table removing is required to allow daemon to restart.
Is there any reason to not remove kernel table when daemon shutdown?

**Comment by rfuchs** [comment]
The idea is to let the kernel module continue forwarding packets while the daemon is being restarted (or after it crashed or whatever) in order to minimize service interruption. Normally the startup script is responsible for deleting an existing kernel table before the daemon recreates it.

**Comment by zhouyu8x** [comment]
OK, got it.

**Comment by amessina** [comment]
It looks like since fd3c1d2519f2e55483725b40e4a06b14b63d828f, the startup script won't have to handle this any longer.
