### ISSUE TITLE
Chrome 63 DTLS and SDES issue

### ISSUE THREAD

**Issue by conraddeweteuphoria** [sipwise/rtpengine#444]
Since Chrome 63, we have not be able to accept calls (in the browser), but are able to make calls fine. The layout is as follows:
Chrome <=> OpenSIP & RTPengine <=> Asteriks

At no point does Asterisk use any Web sockets or call encryption, we relay purely on OpenSIP to provide this. So our offer from the OpenSIPS to RTPengine when making a call from asterisk to chrome, is:

`UDP/TLS/RTP/SAVPF ICE=force rtcp-mux-offer`

The way i understand it... this gives both the crypto attribute (for SDES) and the fingerprint attribute (for DTLS):
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:TPRmu........
a=fingerprint:sha-1 5E:68:A8:B1:24:.....

But now I understand this is no longer correct, and since Chrome 63, we must force fingerprint as Chrome only accepts DTLS.

So we changed the offer params to:
`UDP/TLS/RTP/SAVPF ICE=force rtcp-mux-offer SDES-off`

But this results in both the crypto attribute AND the fingerprint attribute to be removed from the SDP.

Is this is bug? do i need to upgrade, im on 2.3.0
Or is there some combination that will keep the fingerprint attribute and drop the crypto attribute?

**Comment by rfuchs** [comment]
Please try a newer version. `SDES-off` should leave the DTLS stuff in place.

**Comment by conraddeweteuphoria** [comment]
Getting a problem with you Git download:

error: unable to create file daemon/aux.c: No such file or directory
error: unable to create file daemon/aux.h: No such file or directory
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by conraddeweteuphoria** [comment]
Can't seem to compile, using Centos 6.8, and yes I do have libevent2-devel (had to remove old one)

According to documents
"The following software packages are required to compile the daemon:
	- *gcc*
	- *make*
	- *pkgconfig*
	- *glib2-devel*
	- *hiredis-devel*
	- *libcurl-devel*
	- *openssl-devel*
	- *pcre-devel*
	- *xmlrpc-c-devel*
	- *zlib-devel*
"
However:

```
yum install gcc make pkgconfig glib2-devel hiredis-devel libcurl-devel openssl-devel pcre-devel xmlrpc-c-devel zlib-devel
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: repos-jnb.psychz.net
 * epel: mirror.wbs.co.za
 * extras: repos-jnb.psychz.net
 * updates: mirror.bitco.co.za
Package gcc-4.4.7-18.el6.x86_64 already installed and latest version
Package 1:make-3.81-23.el6.x86_64 already installed and latest version
Package 1:pkgconfig-0.23-9.1.el6.x86_64 already installed and latest version
Package glib2-devel-2.28.8-9.el6.x86_64 already installed and latest version
Package libcurl-devel-7.19.7-53.el6_9.x86_64 already installed and latest version
Package openssl-devel-1.0.1e-57.el6.x86_64 already installed and latest version
Package pcre-devel-7.8-7.el6.x86_64 already installed and latest version
Package xmlrpc-c-devel-1.16.24-1210.1840.el6.x86_64 already installed and latest version
Package zlib-devel-1.2.3-29.el6.x86_64 already installed and latest version
Nothing to do
```

Most the of .o files complain about the same thing:

```
cc -g -Wall -pthread -fno-strict-aliasing -std=c99 `pkg-config --cflags glib-2.0` `pkg-config --cflags gthread-2.0` `pkg-config --cflags zlib` `pkg-config --cflags openssl` `pkg-config --cflags libevent_pthreads` `pcre-config --cflags` `pkg-config xmlrpc_client --cflags 2> /dev/null || xmlrpc-c-config client --cflags` `pkg-config xmlrpc --cflags 2> /dev/null` `pkg-config xmlrpc_util --cflags 2> /dev/null` `pkg-config --cflags json-glib-1.0` -I. -I../kernel-module/ -I../lib/ -D_GNU_SOURCE -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DRTPENGINE_VERSION="\"2.3.1\"" -O3   -c -o ssrc.o ssrc.c
In file included from ssrc.h:8,
                 from ssrc.c:1:
aux.h: In function âatomic64_get_setâ:
aux.h:489: warning: passing argument 1 of âg_atomic_pointer_compare_and_exchangeâ from incompatible pointer type
/usr/include/glib-2.0/glib/gatomic.h:48: note: expected âvoid * volatile*â but argument is of type âvolatile void **â
```

The rtpengine binary does not build

Any ideas?

**Comment by rfuchs** [comment]
What you posted is just a warning, not an error, and so doesn't stop compilation. Find the error that stops it and post it.

**Comment by conraddeweteuphoria** [comment]
Ah, right i see, then i make again, and this is what i get:

```
make rtpengine
make[1]: Entering directory `/root/rtpengine/daemon'
cc -g -Wall -pthread -fno-strict-aliasing -std=c99 `pkg-config --cflags glib-2.0` `pkg-config --cflags gthread-2.0` `pkg-config --cflags zlib` `pkg-config --cflags openssl` `pkg-config --cflags libevent_pthreads` `pcre-config --cflags` `pkg-config xmlrpc_client --cflags 2> /dev/null || xmlrpc-c-config client --cflags` `pkg-config xmlrpc --cflags 2> /dev/null` `pkg-config xmlrpc_util --cflags 2> /dev/null` `pkg-config --cflags json-glib-1.0` -I. -I../kernel-module/ -I../lib/ -D_GNU_SOURCE -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DRTPENGINE_VERSION="\"2.3.1\"" -O3   -c -o iptables.o iptables.c
In file included from socket.h:106,
                 from iptables.h:5,
                 from iptables.c:1:
aux.h: In function âatomic64_get_setâ:
aux.h:489: warning: passing argument 1 of âg_atomic_pointer_compare_and_exchangeâ from incompatible pointer type
/usr/include/glib-2.0/glib/gatomic.h:48: note: expected âvoid * volatile*â but argument is of type âvolatile void **â
iptables.c: In function âiptables_initâ:
iptables.c:316: error: ârtpe_configâ undeclared (first use in this function)
iptables.c:316: error: (Each undeclared identifier is reported only once
iptables.c:316: error: for each function it appears in.)
make[1]: *** [iptables.o] Error 1
make[1]: Leaving directory `/root/rtpengine/daemon'
make: *** [all] Error 2
```

Seems like something to do with iptables, but i have set "with_iptables_option ?= no"

**Comment by rfuchs** [comment]
Please update (pull) and try again

**Comment by conraddeweteuphoria** [comment]
WooHoo! :) build success.

Going to test the  DTLS and SDES issue now...

**Comment by conraddeweteuphoria** [comment]
The behavior is the same:

Without SDES-off ("UDP/TLS/RTP/SAVPF ICE=force rtcp-mux-offer")
```
v=0
o=root 438513301 438513301 IN IP4 41.221.5.245
s=Asterisk PBX 11.19.0
c=IN IP4 41.221.5.245
t=0 0
m=audio 30026 UDP/TLS/RTP/SAVPF 107 18 101
a=rtpmap:107 opus/48000/2
a=maxptime:60
a=fmtp:107 maxplaybackrate=16000; stereo=0; sprop-stereo=0; useinbandfec=0
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=sendrecv
a=rtcp:30027
a=rtcp-mux
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:SlH+hk9rI7JCnyj9fDsqz6qvZ/2FETTtKUDJX4ah
a=setup:actpass
a=fingerprint:sha-1 45:96:DD:A5:F2:33:F7:AF:F0:B4:8B:4F:C4:BE:21:50:6A:96:6D:C6
a=ice-ufrag:xd356dm6
a=ice-pwd:tzizDzwV5Wq35xhpiIjiWvD0iS
a=candidate:x2vyj6uwqIjZjQn8 1 UDP 2130706431 41.221.5.245 30026 typ host
a=candidate:x2vyj6uwqIjZjQn8 2 UDP 2130706430 41.221.5.245 30027 typ host
```

Chrome Error:
> Failed to set remote offer sdp: Session error code: ERROR_CONTENT. Session error description: Cryptos must be empty when DTLS is active..

With SDES-off ("UDP/TLS/RTP/SAVPF ICE=force rtcp-mux-offer SDES-off")
```
v=0
o=root 1777993668 1777993668 IN IP4 41.221.5.245
s=Asterisk PBX 11.19.0
c=IN IP4 41.221.5.245
t=0 0
m=audio 19484 RTP/AVP 107 18 101
a=rtpmap:107 opus/48000/2
a=maxptime:60
a=fmtp:107 maxplaybackrate=16000; stereo=0; sprop-stereo=0; useinbandfec=0
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=sendrecv
```

Chrome error: 
> Failed to set remote offer sdp: Called with SDP without DTLS fingerprint.

**Comment by rfuchs** [comment]
That SDP looks like it hasn't been rewritten at all. Please check and confirm that there isn't some other error occurring somewhere.

**Comment by conraddeweteuphoria** [comment]
I'm 100% sure, especially since this works fine in Chrome < 63, and also, the only thing im doing is adding or removing the "SDES-off" to the offer, and re-trying the exact same call. It's a perfectly repeatable and recreateable scenario. I have literally copied and pasted these outputs directly from the Chrome output in the same session.

I agree with you - it seems that the SDP is somehow getting re-set. But the only thing that changes is the  "SDES-off" gets added.

**Comment by rfuchs** [comment]
I understand that the addition of `SDES-off` is what makes this happen, but I don't think that rtpengine as it fault here. Can you please check anyway to see if there are other errors anywhere else. Like, look in your logs.

**Comment by rfuchs** [comment]
You're probably running into the same issue as #437

**Comment by conraddeweteuphoria** [comment]
Yip!

```
.../opensips[11182]: RTPengine Offer UDP/TLS/RTP/SAVPF ICE=force rtcp-mux-offer SDES-off
.../opensips[11182]: ERROR:rtpengine:parse_flags: error processing flag `SDES-off': unknown flag
```
what's the right flag?
So im assuming OpenSIPS, is rejecting this and handing an empty offer to RTPengine?

Anyway, i guess this isn't your thing.
Thanks for the help! I'll hunt on OpenSIPS for the correct flag.

**Comment by rfuchs** [comment]
I think OpenSIPS is actually not sending an offer to rtpengine at all and so you end up with the original SDP going out.
