### ISSUE TITLE
SRTCP/SRTP output wanted, but no crypto suite was negotiated

### ISSUE THREAD

**Issue by bharathkumardk** [sipwise/rtpengine#450]
Hi, I was trying to make a call from webrtc (chrome browser) to sip(softphone) , the call is triggered and get terminated as soon as I answer the call. I have posted my opensips log and browser log below. Kindly let me know if you looking for any further information. Any help would be appreciated. Thanks.

Note: Web to Web calls works fine

Opensips Log:

Feb  2 16:40:22 opensips-sbc-01 rsyslogd-2177: imuxsock begins to drop messages from pid 11318 due to rate-limiting
Feb  2 16:40:22 opensips-sbc-01 rtpengine[7525]: INFO: [o09ve0afn68c4mvt1h91]: Received command 'offer' from 127.0.0.1:35912
Feb  2 16:40:22 opensips-sbc-01 rtpengine[7525]: NOTICE: [o09ve0afn68c4mvt1h91]: Creating new call
Feb  2 16:40:22 opensips-sbc-01 rtpengine[7525]: INFO: [o09ve0afn68c4mvt1h91]: offer time = 0.001115 sec
Feb  2 16:40:22 opensips-sbc-01 rtpengine[7525]: INFO: [o09ve0afn68c4mvt1h91]: Replying to 'offer' from 127.0.0.1:35912
Feb  2 16:40:24 opensips-sbc-01 rtpengine[7525]: ERR: [o09ve0afn68c4mvt1h91 port 19961]: SRTCP output wanted, but no crypto suite was negotiated
Feb  2 16:40:24 opensips-sbc-01 rtpengine[7525]: ERR: [o09ve0afn68c4mvt1h91 port 19960]: SRTP output wanted, but no crypto suite was negotiated
Feb  2 16:40:24 opensips-sbc-01 /usr/sbin/opensips[11316]: UDP/TLS/RTP/SAVPF ICE=remove
Feb  2 16:40:24 opensips-sbc-01 rtpengine[7525]: INFO: [o09ve0afn68c4mvt1h91]: Received command 'answer' from 127.0.0.1:47461
Feb  2 16:40:24 opensips-sbc-01 rtpengine[7525]: INFO: [o09ve0afn68c4mvt1h91]: answer time = 0.000712 sec
Feb  2 16:40:24 opensips-sbc-01 rtpengine[7525]: INFO: [o09ve0afn68c4mvt1h91]: Replying to 'answer' from 127.0.0.1:47461
Feb  2 16:40:24 opensips-sbc-01 /usr/sbin/opensips[11316]: incoming reply
Feb  2 16:40:24 opensips-sbc-01 /usr/sbin/opensips[11316]: ACC: transaction answered: timestamp=1517550024;method=INVITE;from_tag=orn3d6l88b;to_tag=5fabe96f;call_id=o09ve0afn68c4mvt1h91;code=200;reason=OK
Feb  2 16:40:24 opensips-sbc-01 rsyslogd-2177: imuxsock lost 72 messages from pid 11318 due to rate-limiting
Feb  2 16:40:24 opensips-sbc-01 rsyslogd-2177: imuxsock begins to drop messages from pid 11318 due to rate-limiting
Feb  2 16:40:24 opensips-sbc-01 /usr/sbin/opensips[11317]: ACC: transaction answered: timestamp=1517550024;method=BYE;from_tag=orn3d6l88b;to_tag=5fabe96f;call_id=o09ve0afn68c4mvt1h91;code=200;reason=OK

Browser Log:

INVITE sip:test1@xx.xx.x.x SIP/2.0
Via: SIP/2.0/WSS g6e8diqkm8vi.invalid;branch=z9hG4bK3134416
Max-Forwards: 70
To: <sip:test1@x.x.x.x>
From: <sip:dk@x.x.x.x>;tag=im319t2mrm
Call-ID: ui1p0mcqlac2n5rm2nr4
CSeq: 1736 INVITE
Contact: <sip:25uhgb3o@g6e8diqkm8vi.invalid;transport=ws;ob>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: outbound
User-Agent: SIP.js/0.7.8
Content-Type: application/sdp
Content-Length: 1867

v=0
o=- 825063557950989006 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS 4vrUH7uPO7su7PWoEBahxwsxVG3E0iMhjrJz
m=audio 50657 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 x.x.x.x
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:2346683772 1 udp 2122255103 2001::9d38:6abd:86d:353e:ce00:3509 50656 typ host generation 0 network-id 2 network-cost 50
a=candidate:3732548911 1 udp 2122194687 10.203.1.192 50657 typ host generation 0 network-id 1
a=candidate:3311169932 1 tcp 1518275327 2001::9d38:6abd:86d:353e:ce00:3509 9 typ host tcptype active generation 0 network-id 2 network-cost 50
a=candidate:2432291295 1 tcp 1518214911 x.x.x.x 9 typ host tcptype active generation 0 network-id 1
a=candidate:678057211 1 udp 1685987071 x.x.x.x6 50657 typ srflx raddr 10.203.1.192 rport 50657 generation 0 network-id 1
a=ice-ufrag:+AD8
a=ice-pwd:AOLa93b5mC7cKxqgGKXBFXfF
a=ice-options:trickle
a=fingerprint:sha-256 60:2E:36:CF:0E:F6:0E:32:55:C0:0A:D0:BF:97:F0:FE:83:94:CE:0B:6A:2C:3B:D7:A3:D2:CF:24:C0:C5:CB:3C
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:3578243101 cname:TAMV9cp+rMAk4c95
a=ssrc:3578243101 msid:4vrUH7uPO7su7PWoEBahxwsxVG3E0iMhjrJz ac6f8d03-698b-4f97-9e0b-f9d2d6c3ffe9
a=ssrc:3578243101 mslabel:4vrUH7uPO7su7PWoEBahxwsxVG3E0iMhjrJz
a=ssrc:3578243101 label:ac6f8d03-698b-4f97-9e0b-f9d2d6c3ffe9

sip-0.7.8.min.js:36 Fri Feb 02 2018 16:27:24 GMT+1100 (AUS Eastern Summer Time) | sip.transport | received WebSocket text message:

SIP/2.0 100 Giving a try
Via: SIP/2.0/WSS g6e8diqkm8vi.invalid;received=10.203.1.192;branch=z9hG4bK3134416
To: <sip:test1@10.216.235.71>
From: <sip:dk@10.216.235.71>;tag=im319t2mrm
Call-ID: ui1p0mcqlac2n5rm2nr4
CSeq: 1736 INVITE
Server: OpenSIPS (2.2.6 (x86_64/linux))
Content-Length: 0

sip-0.7.8.min.js:36 Fri Feb 02 2018 16:27:24 GMT+1100 (AUS Eastern Summer Time) | sip.transport | received WebSocket text message:

SIP/2.0 180 Ringing
Via: SIP/2.0/WSS g6e8diqkm8vi.invalid;received=10.203.1.192;branch=z9hG4bK3134416
Record-Route: <sip:x.x.x.x;r2=on;lr>
Record-Route: <sip:x.x.x.x:4433;transport=wss;r2=on;lr>
Contact: <sip:test1@x.x.x.x:50022;rinstance=8ac0f3737974daaf>
To: "test1"<sip:test1@x.x.x.x1>;tag=3bea7f6a
From: <sip:dk@10.216.235.71>;tag=im319t2mrm
Call-ID: ui1p0mcqlac2n5rm2nr4
CSeq: 1736 INVITE
User-Agent: X-Lite release 5.1.0 stamp 89322
Allow-Events: talk, hold
Content-Length: 0

sip-0.7.8.min.js:36 Fri Feb 02 2018 16:27:24 GMT+1100 (AUS Eastern Summer Time) | sip.dialog | new UAC dialog created with status EARLY
sip-0.7.8.min.js:36 Fri Feb 02 2018 16:27:41 GMT+1100 (AUS Eastern Summer Time) | sip.transport | received WebSocket text message:

SIP/2.0 200 OK
Via: SIP/2.0/WSS g6e8diqkm8vi.invalid;received=10.203.1.192;branch=z9hG4bK3134416
Record-Route: <sipx.x.x.x;r2=on;lr>
Record-Route: <sip:x.x.x.x:4433;transport=wss;r2=on;lr>
Contact: <sip:test1@x.x.x.x:50022;rinstance=8ac0f3737974daaf>
To: <sip:test1@x.x.x.x>;tag=3bea7f6a
From: <sip:dk@x.x.x.x>;tag=im319t2mrm
Call-ID: ui1p0mcqlac2n5rm2nr4
CSeq: 1736 INVITE
Allow: SUBSCRIBE, NOTIFY, INVITE, ACK, CANCEL, BYE, REFER, INFO, OPTIONS, MESSAGE
Content-Type: application/sdp
Supported: replaces
User-Agent: X-Lite release 5.1.0 stamp 89322
Content-Length: 421

v=0
o=- 1093291577 3 IN IP4 1x.x.x.x
s=X-Lite release 5.1.0 stamp 89322
c=IN IP4 10.216.235.71
t=0 0
m=audio 19952 UDP/TLS/RTP/SAVPF 111 9 0 8 126
a=rtpmap:111 opus/48000/2
a=fmtp:111 useinbandfec=1; usedtx=1; maxaveragebitrate=64000
a=rtpmap:126 telephone-event/8000
a=fmtp:126 0-15
a=sendrecv
a=rtcp:19953
a=setup:active
a=fingerprint:sha-1 72:B4:4A:A8:B7:62:FC:5A:81:3F:5C:1B:E9:23:7D:F1:1D:D8:28:A2

sip-0.7.8.min.js:36 Fri Feb 02 2018 16:27:41 GMT+1100 (AUS Eastern Summer Time) | sip.dialog | dialog ui1p0mcqlac2n5rm2nr4im319t2mrm3bea7f6a  changed to CONFIRMED state
sip-0.7.8.min.js:36 DOMException: Failed to set remote answer sdp: Called with SDP without ice-ufrag and ice-pwd.
c.print @ sip-0.7.8.min.js:36
c.(anonymous function) @ sip-0.7.8.min.js:36
b.(anonymous function) @ sip-0.7.8.min.js:36
(anonymous) @ sip-0.7.8.min.js:38
Promise rejected (async)
receiveInviteResponse @ sip-0.7.8.min.js:38
receiveResponse @ sip-0.7.8.min.js:37
e.receiveResponse @ sip-0.7.8.min.js:39
onMessage @ sip-0.7.8.min.js:39
ws.onmessage @ sip-0.7.8.min.js:39
sip-0.7.8.min.js:36 Fri Feb 02 2018 16:27:41 GMT+1100 (AUS Eastern Summer Time) | sip.transport | sending WebSocket message:

ACK sip:test1@x.x.x.x:50022;rinstance=8ac0f3737974daaf SIP/2.0
Route: <sip:x.x.x.x:4433;transport=wss;r2=on;lr>
Route: <sip:x.x.x.x;r2=on;lr>
Via: SIP/2.0/WSS g6e8diqkm8vi.invalid;branch=z9hG4bK4123144
Max-Forwards: 70
To: <sip:test1@10.216.235.71>;tag=3bea7f6a
From: <sip:dk@10.216.235.71>;tag=im319t2mrm
Call-ID: ui1p0mcqlac2n5rm2nr4
CSeq: 1736 ACK
Supported: outbound
User-Agent: SIP.js/0.7.8
Content-Length: 0

sip-0.7.8.min.js:36 Fri Feb 02 2018 16:27:41 GMT+1100 (AUS Eastern Summer Time) | sip.transport | sending WebSocket message:

BYE sip:test1@x.x.x.x:50022;rinstance=8ac0f3737974daaf SIP/2.0
Route: <sip:x.x.x.x:4433;transport=wss;r2=on;lr>
Route: <sip:x.x.x.x;r2=on;lr>
Via: SIP/2.0/WSS g6e8diqkm8vi.invalid;branch=z9hG4bK9840546
Max-Forwards: 70
To: <sip:test1@x.x.x.x>;tag=3bea7f6a
From: <sip:dk@x.x.x.x>;tag=im319t2mrm
Call-ID: ui1p0mcqlac2n5rm2nr4
CSeq: 1737 BYE
Reason: SIP ;cause=488 ;text="Not Acceptable Here"
Supported: outbound
User-Agent: SIP.js/0.7.8
Content-Length: 0

sip-0.7.8.min.js:36 Fri Feb 02 2018 16:27:41 GMT+1100 (AUS Eastern Summer Time) | sip.transport | received WebSocket text message:

SIP/2.0 200 OK
Via: SIP/2.0/WSS g6e8diqkm8vi.invalid;received=x.x.x.x;branch=z9hG4bK9840546
Contact: <sip:test1@x.x.x.x:50022;rinstance=8ac0f3737974daaf>
To: <sip:test1@x.x.x.x>;tag=3bea7f6a
From: <sip:dk@x.x.x.x>;tag=im319t2mrm
Call-ID: ui1p0mcqlac2n5rm2nr4
CSeq: 1737 BYE
User-Agent: X-Lite release 5.1.0 stamp 89322
Content-Length: 0

**Comment by rfuchs** [comment]
You're probably not using the correct options to rtpengine. Run it in log level 7 and post the resulting log.

**Comment by bharathkumardk** [comment]
Hi @rfuchs,

Opensips Log with log level 7

Feb  5 10:18:35 opensips-sbc-01 rsyslogd-2177: imuxsock begins to drop messages from pid 19774 due to rate-limiting
Feb  5 10:18:39 opensips-sbc-01 rsyslogd-2177: imuxsock lost 30 messages from pid 19774 due to rate-limiting
Feb  5 10:18:39 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms]: Received command 'offer' from 127.0.0.1:59284
Feb  5 10:18:39 opensips-sbc-01 rtpengine[7525]: NOTICE: [ifo85pqtv3r70e9073ms]: Creating new call
Feb  5 10:18:39 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms]: offer time = 0.003222 sec
Feb  5 10:18:39 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms]: Replying to 'offer' from 127.0.0.1:59284
Feb  5 10:18:48 opensips-sbc-01 rtpengine[7525]: ERR: [ifo85pqtv3r70e9073ms port 19987]: SRTCP output wanted, but no crypto suite was negotiated
Feb  5 10:18:48 opensips-sbc-01 rtpengine[7525]: ERR: [ifo85pqtv3r70e9073ms port 19986]: SRTP output wanted, but no crypto suite was negotiated
Feb  5 10:18:48 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms]: Received command 'answer' from 127.0.0.1:60665
Feb  5 10:18:48 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms]: answer time = 0.000607 sec
Feb  5 10:18:48 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms]: Replying to 'answer' from 127.0.0.1:60665
Feb  5 10:18:48 opensips-sbc-01 /usr/sbin/opensips[19773]: ACC: transaction answered: timestamp=1517786328;method=INVITE;from_tag=9tbn6ss6sj;to_tag=194fca75;call_id=ifo85pqtv3r70e9073ms;code=200;reason=OK
Feb  5 10:18:48 opensips-sbc-01 rtpengine[7525]: NOTICE: [ifo85pqtv3r70e9073ms port 19996]: Unknown STUN attribute: 0xc057
Feb  5 10:18:48 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms port 19996]: ICE negotiated: peer for component 1 is 10.203.1.192:52879
Feb  5 10:18:48 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms port 19996]: ICE negotiated: local interface 10.216.235.71
Feb  5 10:18:48 opensips-sbc-01 rsyslogd-2177: imuxsock begins to drop messages from pid 19774 due to rate-limiting
Feb  5 10:18:48 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms]: Received command 'delete' from 127.0.0.1:59284
Feb  5 10:18:48 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms]: Scheduling deletion of call branch '9tbn6ss6sj' (via-branch '') in 30 seconds
Feb  5 10:18:48 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms]: delete time = 0.000310 sec
Feb  5 10:18:48 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms]: Replying to 'delete' from 127.0.0.1:59284
Feb  5 10:18:48 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms port 19996]: DTLS: Peer certificate accepted
Feb  5 10:18:48 opensips-sbc-01 rtpengine[7525]: NOTICE: [ifo85pqtv3r70e9073ms port 19996]: Unknown STUN attribute: 0xc057
Feb  5 10:18:48 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms port 19996]: DTLS-SRTP successfully negotiated
Feb  5 10:18:48 opensips-sbc-01 rtpengine[7525]: NOTICE: [ifo85pqtv3r70e9073ms port 19996]: Unknown STUN attribute: 0xc057
Feb  5 10:18:49 opensips-sbc-01 rtpengine[7525]: NOTICE: [ifo85pqtv3r70e9073ms port 19996]: Unknown STUN attribute: 0xc057
Feb  5 10:18:50 opensips-sbc-01 rtpengine[7525]: NOTICE: [ifo85pqtv3r70e9073ms port 19996]: Unknown STUN attribute: 0xc057
Feb  5 10:18:50 opensips-sbc-01 rtpengine[7525]: WARNING: [ifo85pqtv3r70e9073ms port 19996]: RTP packet with unknown payload type 73 received
Feb  5 10:18:50 opensips-sbc-01 rtpengine[7525]: WARNING: [ifo85pqtv3r70e9073ms port 19996]: Discarded invalid SRTP packet: authentication failed
Feb  5 10:18:52 opensips-sbc-01 rtpengine[7525]: NOTICE: [ifo85pqtv3r70e9073ms port 19996]: Unknown STUN attribute: 0xc057
Feb  5 10:18:55 opensips-sbc-01 rtpengine[7525]: NOTICE: [ifo85pqtv3r70e9073ms port 19996]: Unknown STUN attribute: 0xc057
Feb  5 10:18:55 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms port 19996]: Confirmed peer address as 10.203.1.192:52879
Feb  5 10:18:57 opensips-sbc-01 rtpengine[7525]: NOTICE: [ifo85pqtv3r70e9073ms port 19996]: Unknown STUN attribute: 0xc057
Feb  5 10:19:00 opensips-sbc-01 rtpengine[7525]: NOTICE: [ifo85pqtv3r70e9073ms port 19996]: Unknown STUN attribute: 0xc057
Feb  5 10:19:02 opensips-sbc-01 rtpengine[7525]: NOTICE: [ifo85pqtv3r70e9073ms port 19996]: Unknown STUN attribute: 0xc057
Feb  5 10:19:05 opensips-sbc-01 rtpengine[7525]: NOTICE: [ifo85pqtv3r70e9073ms port 19996]: Unknown STUN attribute: 0xc057
Feb  5 10:19:07 opensips-sbc-01 rtpengine[7525]: NOTICE: [ifo85pqtv3r70e9073ms port 19996]: Unknown STUN attribute: 0xc057
Feb  5 10:19:08 opensips-sbc-01 rtpengine[7525]: WARNING: [ifo85pqtv3r70e9073ms port 19996]: RTP packet with unknown payload type 73 received
Feb  5 10:19:08 opensips-sbc-01 rtpengine[7525]: WARNING: [ifo85pqtv3r70e9073ms port 19996]: Discarded invalid SRTP packet: authentication failed
Feb  5 10:19:10 opensips-sbc-01 rtpengine[7525]: NOTICE: [ifo85pqtv3r70e9073ms port 19996]: Unknown STUN attribute: 0xc057
Feb  5 10:19:12 opensips-sbc-01 rtpengine[7525]: NOTICE: [ifo85pqtv3r70e9073ms port 19996]: Unknown STUN attribute: 0xc057
Feb  5 10:19:15 opensips-sbc-01 rtpengine[7525]: NOTICE: [ifo85pqtv3r70e9073ms port 19996]: Unknown STUN attribute: 0xc057
Feb  5 10:19:17 opensips-sbc-01 rtpengine[7525]: NOTICE: [ifo85pqtv3r70e9073ms port 19996]: Unknown STUN attribute: 0xc057
Feb  5 10:19:18 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms]: Call branch '9tbn6ss6sj' (via-branch '') deleted, no more branches remaining
Feb  5 10:19:18 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms]: Final packet stats:
Feb  5 10:19:18 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms]: --- Tag '9tbn6ss6sj', created 0:39 ago for branch '', in dialogue with '194fca75'
Feb  5 10:19:18 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms]: ------ Media #1 (audio over UDP/TLS/RTP/SAVPF) using unknown codec
Feb  5 10:19:18 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms]: --------- Port   10.216.235.71:19996 <>    10.203.1.192:52879, 7 p, 404 b, 6 e, 1517786357 last_packet
Feb  5 10:19:18 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms]: --------- Port   10.216.235.71:19997 <>          (null):0     (RTCP), 0 p, 0 b, 0 e, 1517786319 last_packet
Feb  5 10:19:18 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms]: --- Tag '194fca75', created 0:39 ago for branch '', in dialogue with '9tbn6ss6sj'
Feb  5 10:19:18 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms]: ------ Media #1 (audio over RTP/AVP) using opus/48000/2
Feb  5 10:19:18 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms]: --------- Port   10.216.235.71:19986 <>    10.203.1.192:52654, 5 p, 839 b, 0 e, 1517786328 last_packet
Feb  5 10:19:18 opensips-sbc-01 rtpengine[7525]: INFO: [ifo85pqtv3r70e9073ms]: --------- Port   10.216.235.71:19987 <>    10.203.1.192:52655 (RTCP), 2 p, 92 b, 0 e, 1517786328 last_packet

**Comment by rfuchs** [comment]
You need to run rtpengine with log level 7 to see useful output, not Opensips.

**Comment by bharathkumardk** [comment]
Thanks a lot, @rfuchs . The issue is fixed now, I can make the audio call from browser to softphone.

Issue:
I noticed a warning in chrome console like "Error Content. Session error description: rtcpMuxPlocy is required but media description does not contain 'a=rtcp-mux"

Resolution:
Added "rtcpMuxpolicy: negotiate" to my user agent config
ua = new SIP.UA({
uri: myAuth + "@x.x.x.x.x",
wsServers: "wss://x.x.x.x.x:port",
traceSip: true,
authorizationUser: '4566',
password: '6568',
rtcpMuxPolicy: 'negotiate'

                });
This might be a temporary solution because still I get warning like [Deprecation] The rtcpMuxPolicy option is being considered for sip-0.7.8.min.js:40 removal and may be removed no earlier than M62, around October 2017. If you depend on it, please see https://www.chromestatus.com/features/5654810086866944 for more details.

**Comment by bharathkumardk** [comment]
Hi @rfuchs,

Now I'm trying to make calls from softphone ---> rtpengine+opensips ----> web browser but the SDP is offered with **crypto** and I'm getting an error in chrome console like **"Failed to set remote offer sdp: Session error code:  ERROR_CONTENT. Session error description: Cryptos must be empty when DTLS is active".** Do you know how to remove crypto from the SDP sent from softphone.

SDP from softphone:

v=0
o=- 13162369371085049 1 IN IP4 x.x.x.x
s=X-Lite release 5.1.0 stamp 89322
c=IN IP4 x.x.x.x
t=0 0
m=audio 18940 UDP/TLS/RTP/SAVPF 9 8 85 120 0 84 3 101
a=rtpmap:85 speex/8000
a=rtpmap:120 opus/48000/2
a=fmtp:120 useinbandfec=1; usedtx=1; maxaveragebitrate=64000
a=rtpmap:84 speex/16000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=rtcp:18941
a=rtcp-mux
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:VlrbUiK1MRKmbVuistI29RyS769T7xjYJppU2vym
a=setup:actpass
a=fingerprint:sha-1 6E:B2:3D:66:7A:A4:A8:D5:A8:13:65:BA:80:12:67:EA:8C:B9:60:B7
a=ice-ufrag:9XiJt50F
a=ice-pwd:wmXRGJwkr60gGJvOgjmTovNvs3
a=candidate:xRV8HlrmLEotEXJi 1 UDP 2130706431 10.216.235.71 18940 typ host
a=candidate:xRV8HlrmLEotEXJi 2 UDP 2130706430 10.216.235.71 18941 typ host

**Comment by rfuchs** [comment]
You can force rtcp-mux by using one of `rtcp-mux-offer` or `rtcp-mux-require` options. You can disable SDES by using `SDES-off`. These are all documented options.

**Comment by rfuchs** [comment]
Assuming resolved

**Comment by bharathkumardk** [comment]
Thanks @rfuchs. It is resolved by upgrading my opensips from 2.2 to 2.3 and setting SDES-no in rtpengine offer when creating the offer.
