### ISSUE TITLE
Intermittent failure to negotiate DTLS when using mixed IP6 and IP4 candidates

### ISSUE THREAD

**Issue by etamme** [sipwise/rtpengine#451]
I have been testing with MR6.1 in a situation where a WebRTC client has an IP6 address, and the other client is simply an IP4 client.  

I have found the vast majority of the time, when the leg between rtpengine and the webrtc client sets up after stun binding requests, the client sends DTLS client hello to the IP6 listening address of rtpengine, but rtpengine responds to the IP4 candidate address from its IP4 interface.  

Occasionally I will get a call where rtpengine eventually responds to the IP6 candidate, on its IP6 interface, and then everything works well with bi directional audio.

In the linked "working" pcap, this exchange happens at packets 109 and 110, however you can see in previous packets that a hello was sent IP6, but responded to on IP4.   In the non working pcap, you can see it never sends a server hello back IP6.

I suspect that there is something happening with ICE here, like ... rtpengine has somehow decided the IP4 candidate is to be used, but this is just my guess.

Here is the log of a working call on full debug, and pcap from rtpengine:  https://gist.github.com/etamme/43408e34bdbf7d0261bef1e63edd01d5

https://nofile.io/f/FZ14wQtEVOu/mobile_ip6_working.pcap

Here is the log of the non working call on full debug and pcap from rtpengine:  https://gist.github.com/etamme/8aa0552bc41748760f118eb3a02bd124

https://nofile.io/f/DYQfEhKnkZM/mobile_ip6_not_working.pcap

The notable difference between the two is in the non-working case the log has errors about SRTP wanted, but no crypto was negotiated.

It is worth noting that the WebRTC client is the UAC in both these call examples, however the offer answer model is 200/ACK.  So the UAS (IP4 only client) is generating the initial offer while the UAC is generating the answer.

**Comment by rfuchs** [comment]
I'm getting a "file not found" on those pcaps.

**Comment by etamme** [comment]
@rfuchs I sent the two pcap's to you direct via email - sorry, dont know a good public file host.

**Comment by rfuchs** [comment]
So, as far as I can tell, this is caused by a combination of several things.

First is a definite bug, where replies to DTLS packets were sent from the wrong source socket. While this might still have worked when two local IPv4 sockets were mixed up, it would have failed if it tried to send to an IPv6 address from an IPv4 socket and vice versa.

The other issue seems to be a special case for ICE not being taken into account. Normally the DTLS connection is bound to the host/post/host/port quadruplet. But ICE specifies that all local ports (and presumably all remote ports) are supposed to be seen as belonging to the same DTLS connection.

The commit referenced above tries to fix both issues. Entirely untested.

**Comment by etamme** [comment]
Thanks Richard, I'l start testing this on monday.

**Comment by etamme** [comment]
This appears to have fixed the DTLS negotiation, I am 100% consistently getting one way audio, but I'm still tracking down what is going on.  I'll post data when I get anything conclusive.  Thank you.

**Comment by etamme** [comment]
Hey again Richard,

Ive been testing with the same scenario as before, mobile IP6 webrtc client calls rtp/avp ip4 client.  IP4 client does offer in 200 OK, IP6 client does answer in ACK.

100% of the time, the IP6 client can hear the IP4 client, but the IP4 client can not hear the IP6 client.

Ive taken traces on the RTPengine server, and 100% of the time rtp is flowing bi-directionally between the IP6 client and RTPengine on its IP6 interface, and 100% of the time rtp is reaching rtpengine from the IP4 client, but it is sending nothing downstream to the IP4 client.

Interestingly enough, RTPengine **_does_** send RTCP reports downstream to the IP4 clients, which you can see in the linked trace, but it sends nothing else.

The call summary, and doing rtpengine-ctl list-sessions on the call ID lead me to believe that RTPengine "thinks" it is sending media downstream to the IP4 client, however as I've said that is not the case.  

This only happens in this same specific call scenario.  I've tested other IP4 webrtc clients, using the same rfuchs/gh451 branch on the same server,  and I get bi-directional audio.

RTPengine verbose log: https://gist.github.com/etamme/d303f748b64b43584a2e8a9dcf72e994

PCAP from rtpengine server: https://owncloud.uphreak.com/index.php/s/QJV7gSqjP6Md4Qh

**Comment by rfuchs** [comment]
The pcap download link doesn't work.

These are suspicious:
```
2018-02-13T20:59:34.007618+00:00 media-relay3-0 rtpengine[2857]: INFO: [0s9f1uot885sh9nl40or port 51924]: Kernelizing media stream: 50.198.204.238:5036
2018-02-13T20:59:34.007627+00:00 media-relay3-0 rtpengine[2857]: ERR: [0s9f1uot885sh9nl40or port 51924]: Failed to push relay stream to kernel: Invalid argument
2018-02-13T20:59:34.010933+00:00 media-relay3-0 rtpengine[2857]: INFO: [0s9f1uot885sh9nl40or port 51938]: Kernelizing media stream: 2607:fb90:6ef7:3788:148e:9c:ed69:dfb2:47776
2018-02-13T20:59:34.010939+00:00 media-relay3-0 rtpengine[2857]: WARNING: [0s9f1uot885sh9nl40or port 51938]: No support for kernel packet forwarding available (decryption cipher or HMAC not supported by kernel module)
```

I'll investigate.

**Comment by rfuchs** [comment]
Just a quick question - which commit did you end up using? I've updated it a few times, b385f1a being the newest one, and 360526e being the oldest one. b385f1a might fix this issue.

**Comment by etamme** [comment]
I am running b385f1ad17ef52813fcfd56bf52e290453f5f54d on the rfuchs/gh451 branch.

**Comment by rfuchs** [comment]
OK, found one more instance of the same issue. Update to 0bbe6a6 please

**Comment by etamme** [comment]
hmm im getting a build error after pull.

`dtls.c: In function ‘dtls_setup_crypto’:
dtls.c:647:1: error: expected expression before ‘<<’ token
 <<<<<<< HEAD
 ^
dtls.c:652:16: error: ‘sfd’ undeclared (first use in this function)
   crypto_init(&sfd->crypto, &server);
                ^
dtls.c:652:16: note: each undeclared identifier is reported only once for each function it appears in
dtls.c:658:1: error: expected expression before ‘==’ token
 =======
 ^
dtls.c:671:9: error: invalid suffix "bbe6a6df194f1b0a72ba272ef6da751fcbfb545" on integer constant
 >>>>>>> 0bbe6a6df194f1b0a72ba272ef6da751fcbfb545
         ^
dtls.c:827:1: error: expected declaration or statement at end of input
 }
 ^
make[2]: *** [dtls.o] Error 1
make[2]: Leaving directory `/usr/local/src/rtpengine/daemon'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/local/src/rtpengine/daemon'
make: *** [all] Error 2
`

**Comment by rfuchs** [comment]
Looks like you pulled in a merge conflict. Do a `git reset --hard HEAD^` and then pull again.

**Comment by etamme** [comment]
yeah derp ... i just opened the file and saw that, my bad.

**Comment by etamme** [comment]
This is looking good on initial testing.  I will follow up after i've done more comprehensive testing.  Thanks Richard.

**Comment by etamme** [comment]
All of my tests of this scenario and others to check for regression are working.  Thanks again Richard.
