### ISSUE TITLE
Cryptos must be empty when DTLS is active

### ISSUE THREAD

**Issue by bharathkumardk** [sipwise/rtpengine#454]
Hi,
I'm trying to make calls from softphone ---> rtpengine+opensips ----> web browser but the SDP is offered with crypto and I'm getting an error in chrome console like **"Failed to set remote offer SDP: Session error code: ERROR_CONTENT. Session error description: Cryptos must be empty when DTLS is active"**. Any thoughts on how to resolve this issue. Thanks in advance.

SDP from softphone:

v=0
o=- 13162369371085049 1 IN IP4 x.x.x.x
s=X-Lite release 5.1.0 stamp 89322
c=IN IP4 x.x.x.x
t=0 0
m=audio 18940 UDP/TLS/RTP/SAVPF 9 8 85 120 0 84 3 101
a=rtpmap:85 speex/8000
a=rtpmap:120 opus/48000/2
a=fmtp:120 useinbandfec=1; usedtx=1; maxaveragebitrate=64000
a=rtpmap:84 speex/16000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=rtcp:18941
a=rtcp-mux
**a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:VlrbUiK1MRKmbVuistI29RyS769T7xjYJppU2vym**
a=setup:actpass
a=fingerprint:sha-1 6E:B2:3D:66:7A:A4:A8:D5:A8:13:65:BA:80:12:67:EA:8C:B9:60:B7
a=ice-ufrag:9XiJt50F
a=ice-pwd:wmXRGJwkr60gGJvOgjmTovNvs3
a=candidate:xRV8HlrmLEotEXJi 1 UDP 2130706431 10.216.235.71 18940 typ host
a=candidate:xRV8HlrmLEotEXJi 2 UDP 2130706430 10.216.235.71 18941 typ host

**Comment by rfuchs** [comment]
Duplicate to #433 #444 and #437
