### ISSUE TITLE
dpkg-shlibdeps: error: no dependency information found for /usr/local/lib/libbcg729.so.0

### ISSUE THREAD

**Issue by denyspozniak** [sipwise/rtpengine#460]
Hello!

My steps to build rtpengine transcoder with G729 supporting:
1) I put bcg729 to rtpengine-master folder and run:
```
cmake .
make 
make install

```
2) run dpkg-buildpackage
3) got error:
```
dpkg-shlibdeps: error: no dependency information found for /usr/local/lib/libbcg729.so.0 (used by debian/ngcp-rtpengine-daemon/usr/sbin/rtpengine)
Hint: check if the library actually comes from a package.
dh_shlibdeps: dpkg-shlibdeps -Tdebian/ngcp-rtpengine-daemon.substvars debian/ngcp-rtpengine-daemon/usr/sbin/rtpengine returned exit code 2
debian/rules:23: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: debian/rules binary gave error exit status 2
```

4) added to **debian/rules** strings after  **dh $@ --parallel** section, must be TAB before dh_shlibdeps
```
override_dh_shlibdeps:
        dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info
```

5) run dpkg-buildpackage again
6) root@ip:/usr/src# rtpengine --codecs
                **G729: fully supported**

Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-112-lowlatency x86_64)

**Comment by rfuchs** [comment]
We'll have a packaged libbcg729 available shortly, so this error can be resolved properly. Or you can use https://github.com/ossobv/bcg729-deb

**Comment by danias** [comment]
For using https://github.com/ossobv/bcg729-deb also read [this](https://github.com/ossobv/bcg729-deb/issues/1) because you need to `export DEB_BUILD_OPTIONS=nocheck` for it to work but still need to add `override_dh_shlibdeps` in **debian/rules** as mentioned above.

**Comment by MaoJianwei** [comment]
Please refer to this, I resolve this problem by using pbuilder: https://gitlab.com/wireshark/wireshark/-/issues/19217
