### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by voztovoice** [sipwise/rtpengine#464]
Hello,
I can't compile the latest master branch version on CentOS 7. Two days ago I could. The error:
------------------------------------------------------
codeclib.o: En la función `bcg729_encoder_close':
/usr/src/rtpengine2/daemon/codeclib.c:1321: referencia a `closeBcg729EncoderChannel' sin definir
codeclib.o: En la función `bcg729_decoder_close':
/usr/src/rtpengine2/daemon/codeclib.c:1277: referencia a `closeBcg729DecoderChannel' sin definir
codeclib.o: En la función `bcg729_decoder_input':
/usr/src/rtpengine2/daemon/codeclib.c:1266: referencia a `bcg729Decoder' sin definir
codeclib.o: En la función `bcg729_decoder_init':
/usr/src/rtpengine2/daemon/codeclib.c:1242: referencia a `initBcg729DecoderChannel' sin definir
codeclib.o: En la función `bcg729_def_init':
/usr/src/rtpengine2/daemon/codeclib.c:1229: referencia a `initBcg729EncoderChannel' sin definir
/usr/src/rtpengine2/daemon/codeclib.c:1230: referencia a `initBcg729DecoderChannel' sin definir
/usr/src/rtpengine2/daemon/codeclib.c:1233: referencia a `closeBcg729EncoderChannel' sin definir
codeclib.o: En la función `bcg729_encoder_input':
/usr/src/rtpengine2/daemon/codeclib.c:1307: referencia a `bcg729Encoder' sin definir
codeclib.o: En la función `bcg729_encoder_init':
/usr/src/rtpengine2/daemon/codeclib.c:1282: referencia a `initBcg729EncoderChannel' sin definir
codeclib.o: En la función `bcg729_def_init':
/usr/src/rtpengine2/daemon/codeclib.c:1237: referencia a `closeBcg729DecoderChannel' sin definir
collect2: error: ld devolvió el estado de salida 1
make[2]: *** [rtpengine] Error 1
make[2]: se sale del directorio `/usr/src/rtpengine2/daemon'
make[1]: *** [all] Error 2
make[1]: se sale del directorio `/usr/src/rtpengine2/daemon'
make: *** [all] Error 2
--------------------------------------------------
Thank You

Regards

**Comment by rfuchs** [comment]
Looks like the makefile can't find your bcg729 library. Where is it located?

**Comment by voztovoice** [comment]
hello,
now is bcg729 mandatory to compile RTPEngine?
Thank you and Regards

**Comment by rfuchs** [comment]
No it isn't. It's optional. The build system only tries to include it if it detects one of the header files present, or if the respective flag is set to true manually. Check the makefile.

**Comment by voztovoice** [comment]
Sorry for the noise... my fault. SOLVED
Regards
