### ISSUE TITLE
FFMPEG libavresample deprecated

### ISSUE THREAD

**Issue by SpaceVarmint** [sipwise/rtpengine#465]
When compiling the latest version of FFMPEG from GIT, it no longer installs libavresample by default and it is marked as deprecated with warning. As I am also compiling the latest version of rtpengine from GIT, I notice it will not compile without libavresample. For right now, there is a configure switch you can use to include libavresample in the FFMPEG installation process, but I am assuming it will go away soon.

**Comment by rfuchs** [comment]
Thanks for the heads up. Migrating to swresample should be pretty straight forward.

**Comment by rfuchs** [comment]
How does OpenCV relate to rtpengine?

**Comment by Rvldo** [comment]
hmm
