### ISSUE TITLE
add no-rtcp-filtering flag 

### ISSUE THREAD

**Issue by jerzyptak** [sipwise/rtpengine#466]
Hi, 
I have noticed that rtpengine is filtering out rtcp feedback packets from AVP/SAVP streams. This behaviour is breaking calls from endpoints that declare AVP/SAVP profiles, but declare support for rtcp feedback in SDP. 

For example fragment of SDP generated by Cisco-SX10:
`m=video 19506 RTP/AVP 97 126 96 34 123`
`b=TIAS:3072000`
`a=rtpmap:97 H264/90000`
`a=fmtp:97 packetization-mode=0;profile-level-id=428020profile-level-id=428020;max-br=2500;max-mbps=245000;max-fs=8160;max-smbps=245000;max-fps=3000`
`a=rtpmap:126 H264/90000`
`a=fmtp:126 packetization-mode=1;profile-level-id=428020profile-level-id=428020;max-br=2500;max-mbps=245000;max-fs=8160;max-smbps=245000;max-fps=3000`
`a=rtpmap:96 H263-1998/90000`
`a=fmtp:96 custom=1280,720,1;custom=1024,768,1;custom=1024,576,1;custom=800,600,1;cif4=1;custom=720,480,1;custom=640,480,1;custom=512,288,1;cif=1;custom=352,240,1;qcif=1;maxbr=30000`
`a=rtpmap:34 H263/90000`
`a=fmtp:34 cif4=2;cif=1;qcif=1;maxbr=10000`
`a=rtpmap:123 x-ulpfecuc/8000`
`a=fmtp:123 multi_ssrc=1;feedback=0;max_esel=1450;m=8;max_n=64;FEC_ORDER=FEC_SRTP;non_seq=1`
`a=label:11`
`a=answer:full`
`a=content:main`
`a=rtcp-fb:* nack pli`
`a=rtcp-fb:* ccm fir`
`a=rtcp-fb:* ccm tmmbr`
`a=sendrecv`

I have implemented a change that adds no-rtcp-filtering flag, that disables rtcp feedback filtering.
[rtpengine.patch.txt](https://github.com/sipwise/rtpengine/files/1733058/rtpengine.patch.txt)
I hope that this is a sensible change and it can be included in rtpengine.

Regards

**Comment by rfuchs** [comment]
Please submit it as a pull request

**Comment by rfuchs** [comment]
Generally though, filtering only happens towards RTP/(S)AVP endpoints. If an endpoint supports RTCP feedback, it should be RTP/(S)AVPF.

**Comment by jerzyptak** [comment]
Pull request created.

I agree that in principle endpoints should declare RTP/(S)AVPF profile if they intend to use rtcp feedback, but a lot of implementations does not do that as rtcp feedback support is negotiated in separate a parameters in SDP anyway.

**Comment by rfuchs** [comment]
Perhaps it would be better to make the filtering dependent on the presence of these SDP attributes then, instead of having to manually set a flag.

**Comment by jerzyptak** [comment]
Yes that is a better solution and I have already considered it, but unfortunately I did not have enough time to implement it as first attempt, so I would consider this as an improvement to the manual handling of no-rtcp-filtering flag.
