### ISSUE TITLE
Segmentation fault in codec_make_payload_type

### ISSUE THREAD

**Issue by claudiupb** [sipwise/rtpengine#471]
Hello, 

We have noticed rtpengine crash with a SIGSEGV with the following trace:

#0  codec_make_payload_type (codec_str=codec_str@entry=0x7f503003f980, media=media@entry=0x7f5030042470) at codec.c:486
#1  0x000055fd5aa8483e in rbl_cb_plts_g (s=0x7f503003f980, ptr=ptr@entry=0x7f5030042470, list=<optimized out>, q=<optimized out>) at redis.c:1211
#2  0x000055fd5aa8491c in rbl_cb_plts_r (s=<optimized out>, q=<optimized out>, list=<optimized out>, ptr=0x7f5030042470) at redis.c:1221
#3  0x000055fd5aa7853e in json_build_list_cb (q=q@entry=0x0, key=key@entry=0x55fd5aabd9c8 "payload_types", idx=idx@entry=2, list=list@entry=0x0, 
    cb=cb@entry=0x55fd5aa84910 <rbl_cb_plts_r>, ptr=ptr@entry=0x7f5030042470, root_reader=0x55fd5be55520, c=0x7f5030029080) at redis.c:981
#4  0x000055fd5aa85ee9 in json_medias (root_reader=<optimized out>, medias=<optimized out>, c=<optimized out>) at redis.c:1274
#5  json_restore_call (r=r@entry=0x55fd5be589c0, callid=callid@entry=0x7f505d58f730, type=type@entry=CT_FOREIGN_CALL) at redis.c:1573
#6  0x000055fd5aa86f1f in on_redis_notification (actx=<optimized out>, reply=0x7f50300028e0, privdata=<optimized out>) at redis.c:369
#7  0x00007f5078ba454d in redisProcessCallbacks () from /usr/lib/x86_64-linux-gnu/libhiredis.so.0.13
#8  0x00007f5079ccd5a0 in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#9  0x000055fd5aa8838a in redis_notify () at redis.c:563
#10 0x000055fd5aa886f7 in redis_notify_loop (d=<optimized out>) at redis.c:600
#11 0x000055fd5aa7c6a4 in thread_detach_func (d=0x55fd5be1eb10) at aux.c:143
#12 0x00007f5075a51494 in start_thread (arg=0x7f505d590700) at pthread_create.c:333
#13 0x00007f5075793aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

From a quick check with gdb it seems the problem is here:
https://github.com/sipwise/rtpengine/blob/7ee73fe7f939f0abb5cda5d454cd1c9b71ef39c3/daemon/codec.c#L477
The return value of `codec_find` is never checked and when the crash occurs `def` will point to NULL. Later when trying to access `def->default_ptime` the SEGV is generated.

The return value for `codec_find` should be checked but I am not sure what to do in case it is NULL (maybe 'codec_make_payload_type' should also return NULL?)

**Comment by rfuchs** [comment]
Fixed in 65c75c5
