### ISSUE TITLE
ERROR: failed to open UDP control connection port on boot

### ISSUE THREAD

**Issue by Piszi** [sipwise/rtpengine#474]
Hello,

I installed rtpengine on Debian jessie and after experimenting with the parameters I configured rtpengine to start with those params at boot. But I get 'failed to open UDP control connection' error BUT after the system is booted and I start rtpengine manually with `/etc/init.d/ngcp-rtpengine-daemon start` it starts without an error.

here is my config file: 
```
table = 0
interface = 10.1.10.74
listen-ng = 10.1.10.74:60000
listen-cli = 10.1.10.74:60001

foreground = true
pidfile = /var/run/ngcp-rtpengine-daemon.pid

port-min = 50000
port-max = 65000

recording-dir = /recording
recording-method = proc
recording-format = raw

log-level = 7
log-stderr = true
log-facility = local2
log-facility-cdr = local3
log-facility-rtcp = local4
```

What could be the problem?

**Comment by rfuchs** [comment]
Possibly because rtpengine tries to start before the network is fully up. 2ebe76d535dc5b9dcc3a42260ed620d5fbf0761f has just been pushed to address this.

**Comment by Piszi** [comment]
I did made the changes you linked to `/etc/init.d/ngcp-rtpengine-daemon` but on boot I still get the same error and now there is a new one.
If I call `restart` instead of `start` I get this error after the timeout `Failed to start LSB: Ngcp Rtpengine.`
 
Probably not important, but do you really need $local_fs in the LSB if $remote_fs is specified?

**Comment by rfuchs** [comment]
Anything useful in the log output?

**Comment by Piszi** [comment]
You know whats funny I get failed when I call `restart` or `force-reload` but in reality the daemon starts. I just checked syslog and obviously the last etnry is rtpengine and the last line is `INFO: Startup complete, version 6.2.0.0+0~mr6.2.0.0 git-master-22431f5` and netstat shows rtpengine listening.
Now thats interesting.

As for the boot I still get same `CRIT: Fatal error: failed to open UDP control connection` but going through the syslog what I see is Network manager strats than reads conf than enables WEXT support and than bang rtpengine recording daemon starts than rtpengine-daemon starts and fails than after a couple of services later Network Manager again with `init` and parsing network interfaces. If the lines in the log represent the actual timeline than rtpengine doesn't waits for network to fully load.

**Comment by taurus-forever** [comment]
@Piszi Just for for the history here: do you use systemd or sysv on your's Debian jessie?

**Comment by Piszi** [comment]
As far as know systemd. if I'm not mistaken the offical Jessie uses systemd "out of the box" and I did not change that.

**Comment by taurus-forever** [comment]
Did you perform "systemctl daemon-reload" after changing the init script?
Since it is an sysv init script you need to force systemd-sysv-generator to regenerate the unit file and call systemd to reload it.

Also you can use "systemd-analyze critical-chain ngcp-rtpengine-daemon.service" to see the service dependencies, ensure your's rtpengine waits for network.target/network-online.target.

Also if you want to see the full boot process, use "systemd-analyze plot > /tmp/boot.svg".
I hope those command will help you trace the boot issue you have.

JFYI, we are in a process of migration to systemd, so rtpengine should receive pure systemd unit soon.

**Comment by Piszi** [comment]
@taurus-forever thanks for the help. It turns out, that rtpengine starts while the network is still initializing. I tried adding should-start to the LSB with a service that starts way after the network but it looks like rtpengine ignores it and always start at the same time. 

But if I change listen-ng and -cli to 127.0.0.1  than rtpengine starts without error. 
I think I will keep it this way for now, I moved opensips from our other machine to the machine running rtpengine so the 127.0.0.1 config is fine.

At the same time I'm looking forward to see systemd implemented into rtpengine.

**Comment by taurus-forever** [comment]
> It turns out, that rtpengine starts while the network is still initializing. 

It sounds strange, on my Debian _**stretch**_ test VM rtpengine from trunk waits for network-online.target:
```
root@spce:~# systemd-analyze critical-chain ngcp-rtpengine-daemon.service
The time after the unit is active or started is printed after the "@" character.
The time the unit takes to start is printed after the "+" character.

ngcp-rtpengine-daemon.service +1.484s
└─network-online.target @3.033s
  └─network.target @3.019s
    └─networking.service @769ms +2.250s
      └─network-pre.target @761ms
        └─netfilter-persistent.service @362ms +398ms
          └─local-fs.target @360ms
            └─local-fs-pre.target @360ms
              └─lvm2-monitor.service @195ms +164ms
                └─lvm2-lvmetad.service @287ms
                  └─lvm2-lvmetad.socket @193ms
                    └─-.mount @150ms
                      └─system.slice @174ms
                        └─-.slice @150ms

root@spce:~# systemctl cat  ngcp-rtpengine-daemon.service | head -2
# /run/systemd/generator.late/ngcp-rtpengine-daemon.service
# Automatically generated by systemd-sysv-generator

root@spce:~# head -25 /etc/init.d/ngcp-rtpengine-daemon | grep -E '^#'
#! /bin/sh
### BEGIN INIT INFO
# Provides:          ngcp-rtpengine-daemon
# Required-Start:    $network $local_fs $remote_fs $syslog
# Required-Stop:     $network $local_fs $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Ngcp Rtpengine
# Description:       Proxy for RTP and other media streams
### END INIT INFO
root@spce:~# 

root@spce:~# apt-cache policy systemd
systemd:
  Installed: 232-25+deb9u1
  Candidate: 232-25+deb9u1
  Version table:
 *** 232-25+deb9u1 500
        500 https://debian.sipwise.com/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status
root@spce:~# 
```

No ideas here so far. Maybe worth to try Debian stretch with newer systemd?

**Comment by Piszi** [comment]
@taurus-forever I think the problem is caused because we use wifi and network-online.target is reached before wifi is up and configured.  And I just realized this so I did a search on network-online/wifi and turns out its not an uncommon problem. 

The best solution I found is to add the device to the `BindsTo` and `After` in your systemd yourapp.service file.

**Comment by taurus-forever** [comment]
> I think the problem is caused because we use wifi ...

Good to know, I would say SIP server over WiFi is really not a common setup.

> The best solution I found is to add the device to the BindsTo and After in your systemd yourapp.service file.

If you need to change systemd unit, the best approach is to use 'systemd override' solution instead of modifying the upstream service file directly, like /etc/systemd/system/ngcp-rtpengine-daemon.d/override.conf

Have fun! I believe the bug report can be closed.

**Comment by rfuchs** [comment]
Another option is to set the `net.ipv4.ip_nonlocal_bind` sysctl to `1` (recent kernels have an IPv6 counterpart as well). This allows any process to bind to any address even if it's not actually configured yet.

**Comment by Piszi** [comment]
Thank you for your help!
