### ISSUE TITLE
SIGABRT, transcoding G729

### ISSUE THREAD

**Issue by rb-beip** [sipwise/rtpengine#475]
Hello!

Trying to use rtpengine for G729 transcoding. The call goes from WebRTC client to UAS, enforcing G729 codec for the test. Rtpengine is used with custom compiled BCG729 library version 1.0.4. This is output from gdb:

`
```
14:55:43 [root@rb-dev-60.rb-dev-60.local.beip.be] log # gdb --symbols=/usr/lib/debug/.build-id/a8/737f7d5503e1c07e06cc82bf0f907fab842e4d.debug --pid=9853
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/lib/debug/.build-id/a8/737f7d5503e1c07e06cc82bf0f907fab842e4d.debug...done.
Attaching to process 9853
[New LWP 9854]
[New LWP 9855]
[New LWP 9856]
[New LWP 9857]
[New LWP 9858]
[New LWP 9859]
[New LWP 9860]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f9d3574424d in nanosleep () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) thread apply all bt

Thread 8 (Thread 0x7f9d1bc97700 (LWP 9860)):
#0  0x00007f9d357750f3 in epoll_wait () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00005584908e047d in poller_poll (p=p@entry=0x558491f09ca0, timeout=timeout@entry=100) at poller.c:304
#2  0x00005584908e099d in poller_loop (d=0x558491f09ca0) at poller.c:505
#3  0x00005584908e0a14 in thread_detach_func (d=0x558491ee9910) at aux.c:143
#4  0x00007f9d35a32494 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f9d35774aff in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 7 (Thread 0x7f9d1c498700 (LWP 9859)):
#0  0x00007f9d357750f3 in epoll_wait () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00005584908e047d in poller_poll (p=p@entry=0x558491f09ca0, timeout=timeout@entry=100) at poller.c:304
#2  0x00005584908e099d in poller_loop (d=0x558491f09ca0) at poller.c:505
#3  0x00005584908e0a14 in thread_detach_func (d=0x558491ee9900) at aux.c:143
#4  0x00007f9d35a32494 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f9d35774aff in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 6 (Thread 0x7f9d1cc99700 (LWP 9858)):
#0  0x00007f9d357750f3 in epoll_wait () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00005584908e047d in poller_poll (p=p@entry=0x558491f09ca0, timeout=timeout@entry=100) at poller.c:304
#2  0x00005584908e099d in poller_loop (d=0x558491f09ca0) at poller.c:505
#3  0x00005584908e0a14 in thread_detach_func (d=0x558491ee98c0) at aux.c:143
#4  0x00007f9d35a32494 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f9d35774aff in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 5 (Thread 0x7f9d1d49a700 (LWP 9857)):
#0  0x00007f9d357750f3 in epoll_wait () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00005584908e047d in poller_poll (p=p@entry=0x558491f09ca0, timeout=timeout@entry=100) at poller.c:304
#2  0x00005584908e099d in poller_loop (d=0x558491f09ca0) at poller.c:505
#3  0x00005584908e0a14 in thread_detach_func (d=0x558491ee98b0) at aux.c:143
#4  0x00007f9d35a32494 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f9d35774aff in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 4 (Thread 0x7f9d1dc9b700 (LWP 9856)):
#0  0x00007f9d35a38508 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000055849090efde in __cond_timedwait_tv (tv=<synthetic pointer>, m=0x558490b3d440 <ice_agents_timers_lock>, 
    c=0x558490b3d400 <ice_agents_timers_cond>) at aux.h:295
#2  ice_thread_run (p=<optimized out>) at ice.c:1367
#3  0x00005584908e0a14 in thread_detach_func (d=0x558491ee98a0) at aux.c:143
#4  0x00007f9d35a32494 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f9d35774aff in clone () from /lib/x86_64-linux-gnu/libc.so.6

---Type <return> to continue, or q <return> to quit---
Thread 3 (Thread 0x7f9d1e49c700 (LWP 9855)):
#0  0x00007f9d3574424d in nanosleep () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f9d3576dbb4 in usleep () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00005584908e096c in poller_timer_loop (d=0x558491f09ca0) at poller.c:492
#3  0x00005584908e0a14 in thread_detach_func (d=0x558491ee9890) at aux.c:143
#4  0x00007f9d35a32494 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f9d35774aff in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7f9d1ec9d700 (LWP 9854)):
#0  0x00007f9d356bfd9c in sigtimedwait () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00005584908dd6d3 in sighandler (x=<optimized out>) at main.c:85
#2  0x00005584908e0a14 in thread_detach_func (d=0x558491ee9880) at aux.c:143
#3  0x00007f9d35a32494 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#4  0x00007f9d35774aff in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7f9d3b86acc0 (LWP 9853)):
#0  0x00007f9d3574424d in nanosleep () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f9d3576dbb4 in usleep () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00005584908dcf12 in main (argc=<optimized out>, argv=<optimized out>) at main.c:728
(gdb) continue
Continuing.

Thread 7 "rtpengine" received signal SIGABRT, Aborted.
[Switching to Thread 0x7f9d1c498700 (LWP 9859)]
0x00007f9d356befcf in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) backtrace
#0  0x00007f9d356befcf in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f9d356c03fa in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f9d356fcbd0 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f9d35702f96 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007f9d357037de in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x000055849091b702 in codec_packet_free (pp=0x7f9d0c001780) at codec.c:445
#6  0x000055849091366d in stream_packet (phc=0x7f9d1c494f30) at media_socket.c:1666
#7  stream_fd_readable (fd=<optimized out>, p=0x7f9d04012170, u=<optimized out>) at media_socket.c:1746
#8  0x00005584908e05f8 in poller_poll (p=p@entry=0x558491f09ca0, timeout=timeout@entry=100) at poller.c:350
#9  0x00005584908e099d in poller_loop (d=0x558491f09ca0) at poller.c:505
#10 0x00005584908e0a14 in thread_detach_func (d=0x558491ee9900) at aux.c:143
#11 0x00007f9d35a32494 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#12 0x00007f9d35774aff in clone () from /lib/x86_64-linux-gnu/libc.so.6
```
`

If I force some other codec in UAS, like g722 for example, it works, I have the sound. But there are quite a lot of error messages like this:
`Feb 27 15:06:24 rb-dev-60 rtpengine[11557]: ERR: [do43t23rbr7m0hfh9tek port 30082]: av_log: Decoding error: corrupted stream
Feb 27 15:06:24 rb-dev-60 rtpengine[11557]: ERR: [do43t23rbr7m0hfh9tek port 30082]: Error decoding media packet: failed to send packet to avcodec
Feb 27 15:06:24 rb-dev-60 rtpengine[11557]: ERR: [do43t23rbr7m0hfh9tek port 30082]: av_log: Decoding error: corrupted stream
Feb 27 15:06:24 rb-dev-60 rtpengine[11557]: ERR: [do43t23rbr7m0hfh9tek port 30082]: Error decoding media packet: failed to send packet to avcodec
Feb 27 15:06:24 rb-dev-60 rtpengine[11557]: ERR: [do43t23rbr7m0hfh9tek port 30082]: av_log: Decoding error: corrupted stream
Feb 27 15:06:24 rb-dev-60 rtpengine[11557]: ERR: [do43t23rbr7m0hfh9tek port 30082]: Error decoding media packet: failed to send packet to avcodec
Feb 27 15:06:24 rb-dev-60 rtpengine[11557]: ERR: [do43t23rbr7m0hfh9tek port 30082]: av_log: Decoding error: corrupted stream
Feb 27 15:06:24 rb-dev-60 rtpengine[11557]: ERR: [do43t23rbr7m0hfh9tek port 30082]: Error decoding media packet: failed to send packet to avcodec
`

One last question - in the README you specify version 1.0.3 of BCG729 library, I try to use 1.0.4. Could it be also the problem here?

**Comment by rb-beip** [comment]
I've tried with the version 1.0.3 of BCG729 library, I have the same result. But in a couple of the attempts I had different backtraces. One is the same as in the first message. The other one is:

`
(gdb) backtrace
#0  0x00007ff43ab8cfcf in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ff43ab8e3fa in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ff43abcabd0 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ff43abd0f96 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ff43abd1388 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x00007ff43abd2dca in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007ff43abd5986 in calloc () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x00007ff43abc9793 in open_memstream () from /lib/x86_64-linux-gnu/libc.so.6
#8  0x00007ff43ac3db21 in __vsyslog_chk () from /lib/x86_64-linux-gnu/libc.so.6
#9  0x00007ff43ac3e07f in syslog () from /lib/x86_64-linux-gnu/libc.so.6
#10 0x0000559be7092ad1 in __vpilog (prio=prio@entry=7, prefix=prefix@entry=0x7ff422163c30 "[82pj97r5863albqm4dn3 port 30000]: ", 
    fmt=fmt@entry=0x559be70a0c88 "Received RTP packet: SSRC %x, PT %u, seq %u, TS %u, len %i", ap=ap@entry=0x7ff422163c18)
    at loglib.c:189
#11 0x0000559be707b7f6 in __ilog (prio=prio@entry=7, 
    fmt=fmt@entry=0x559be70a0c88 "Received RTP packet: SSRC %x, PT %u, seq %u, TS %u, len %i") at log.c:104
#12 0x0000559be70916df in handler_func_transcode (h=0x7ff41c016cf0, media=<optimized out>, mp=0x7ff422163f88) at codec.c:724
#13 0x0000559be70892cf in stream_packet (phc=0x7ff422163f30) at media_socket.c:1628
#14 stream_fd_readable (fd=<optimized out>, p=0x7ff41c029000, u=<optimized out>) at media_socket.c:1746
#15 0x0000559be70565f8 in poller_poll (p=p@entry=0x559be873d9a0, timeout=timeout@entry=100) at poller.c:350
#16 0x0000559be705699d in poller_loop (d=0x559be873d9a0) at poller.c:505
#17 0x0000559be7056a14 in thread_detach_func (d=0x559be871c8c0) at aux.c:143
#18 0x00007ff43af00494 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#19 0x00007ff43ac42aff in clone () from /lib/x86_64-linux-gnu/libc.so.6
`

**Comment by rfuchs** [comment]
Might be the same issue as #480 

Please try and let me know

**Comment by rb-beip** [comment]
I've compiled the new version with your fix and it seems to solve the crush issue. Thank you!
