### ISSUE TITLE
compile time flag to disable transcoding on daemon build

### ISSUE THREAD

**Issue by etamme** [sipwise/rtpengine#478]
Hey Richard,

I am running into an issue with our rpm build process because transcoding is enabled by default, and I can find no way to disable it via a compile time flag.  

we basically run a 
`git archive --format=tar.gz --prefix=$NAME-$VERSION/ $SHORTHASH >  $SOURCESDIR/$NAME-$VERSION-$RELEASE.tar.gz
`

To create a tgz to run the rpmbuild against, so I cant make a change to the daemon/Makefile that will persist through to the build unless I commit it.  

I basically want to be able to run my build script against vanilla upstream and not carry any local changes, so this breaks my ability to do that.  Is it possible to get a compile time flag added?

**Comment by rfuchs** [comment]
Environment variables are the way to go, it can be as simple as running `with_transcoding=no make`

**Comment by etamme** [comment]
perfect, thanks
