### ISSUE TITLE
Segfault when tanscoding with SRTP enabled

### ISSUE THREAD

**Issue by matt01** [sipwise/rtpengine#480]
Hi, 

Ok, so just been playing with the transcoding options and everything looks like its working well if I don't have SRTP enabled on the client.

If I enable SRTP though I get a segfault.

A GDB backtrace is available here: 
[gdbout_rtpengine_srtp.txt](https://github.com/sipwise/rtpengine/files/1778615/gdbout_rtpengine_srtp.txt)

The options I am passing in to rtpengine are ...

`trust-address replace-origin replace-session-connection ICE=remove transcode-opus`
for offers going towards the client and 
`trust-address replace-origin replace-session-connection ICE=remove codec-mask-all transcode-PCMA RTP AVP`
for offers going towards an asterisk instance.

The client i'm using to test is CSipSimple, however, I'm getting the same issue with a Grandstream DP750.

If you need any additional info then please ask.

Thanks, 

Matt.

**Comment by matt01** [comment]
Oh, also ...

```
# /usr/sbin/rtpengine -v
Version: git-master-620cf61
```
```
# ffmpeg -version
ffmpeg version N-90214-gdd3f1e3a11
```
```
# kamailio -V
version: kamailio 5.1.1 (x86_64/linux) 
```

Matt.

**Comment by rfuchs** [comment]
I don't have a quick way to reproduce this right now, but I think I know what's going wrong. See commit referenced above. Please try and let me know.

**Comment by arkadiam** [comment]
I've experienced the similar segfault when transcoding from Opus to PCMU and stripping SDES. 

rtpengine_manage_flags=direction=pub direction=priv replace-origin replace-session-connection ICE=remove SDES-off transcode-PCMU codec-mask-opus

My backtrace was:
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3867
#5  0x00007f467f0ba53c in __GI___libc_free (mem=<optimized out>) at malloc.c:2968
#6  0x0000000000483921 in codec_packet_free (pp=0x7f4660001920) at codec.c:447
#7  0x00000000004775cb in stream_packet (phc=0x7f466629a0f0) at media_socket.c:1666
#8  0x0000000000477d3b in stream_fd_readable (fd=8, p=0x7f46600270a0, u=0) at media_socket.c:1746
#9  0x000000000040e690 in poller_poll (p=0x1fa9ce0, timeout=100) at poller.c:350

After applying 88b2f36 rtpengine doesn't crash anymore.

**Comment by matt01** [comment]
I can confirm, this is fixed for me as well. Thanks.
