### ISSUE TITLE
Error Compiling Centos7 with recent test macro update push

### ISSUE THREAD

**Issue by MagnifyTelecom** [sipwise/rtpengine#483]
[root@localhost kernel-module]# make
make -C /lib/modules/3.10.0-693.17.1.el7.x86_64/build M=/usr/local/src/rtpengine                                                                                                                                                             /kernel-module O=/lib/modules/3.10.0-693.17.1.el7.x86_64/build modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-693.17.1.el7.x86_64'
  CC [M]  /usr/local/src/rtpengine/kernel-module/xt_RTPENGINE.o
/bin/sh: line 1:  1664 Segmentation fault      (core dumped) ./tools/objtool/obj                                                                                                                                                             tool check "/usr/local/src/rtpengine/kernel-module/xt_RTPENGINE.o"
make[3]: *** [/usr/local/src/rtpengine/kernel-module/xt_RTPENGINE.o] Error 139
make[2]: *** [_module_/usr/local/src/rtpengine/kernel-module] Error 2
make[1]: *** [sub-make] Error 2
make[1]: Leaving directory `/usr/src/kernels/3.10.0-693.17.1.el7.x86_64'
make: *** [modules] Error 2

______________________________________________________________________________________________________________

CentOS Linux release 7.4.1708 (Core)
3.10.0-693.17.1.el7.x86_64

**Comment by rfuchs** [comment]
Wait, what? The build itself segfaults? I don't think that's rtpengine's fault :rofl:

Update your build tools maybe?

**Comment by MagnifyTelecom** [comment]
Not sure where I went wrong, tried two fresh installs, updated all the packages etc, don't see anything out of place. Everything else is building fine rtpengine/daemon , iptables-extension but kernel-module make gives me the finger..

**Comment by rfuchs** [comment]
Can't reproduce.

```
[root@localhost kernel-module]# make
make -C /lib/modules/3.10.0-693.17.1.el7.x86_64/build M=/root/rtpengine/kernel-module O=/lib/modules/3.10.0-693.17.1.el7.x86_64/build modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-693.17.1.el7.x86_64'
  CC [M]  /root/rtpengine/kernel-module/xt_RTPENGINE.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /root/rtpengine/kernel-module/xt_RTPENGINE.mod.o
  LD [M]  /root/rtpengine/kernel-module/xt_RTPENGINE.ko
make[1]: Leaving directory `/usr/src/kernels/3.10.0-693.17.1.el7.x86_64'
[root@localhost kernel-module]# uname -a
Linux localhost.localdomain 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost kernel-module]# cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core) 
[root@localhost kernel-module]# cat /etc/centos-release-upstream 
Derived from Red Hat Enterprise Linux 7.4 (Source)
[root@localhost kernel-module]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) 
[root@localhost kernel-module]# make clean
make -C /lib/modules/3.10.0-693.17.1.el7.x86_64/build M=/root/rtpengine/kernel-module clean || true
make[1]: Entering directory `/usr/src/kernels/3.10.0-693.17.1.el7.x86_64'
  CLEAN   /root/rtpengine/kernel-module/.tmp_versions
  CLEAN   /root/rtpengine/kernel-module/Module.symvers
make[1]: Leaving directory `/usr/src/kernels/3.10.0-693.17.1.el7.x86_64'
[root@localhost kernel-module]# KBUILD_VERBOSE=1 make
make -C /lib/modules/3.10.0-693.17.1.el7.x86_64/build M=/root/rtpengine/kernel-module O=/lib/modules/3.10.0-693.17.1.el7.x86_64/build modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-693.17.1.el7.x86_64'
make -C /usr/src/kernels/3.10.0-693.17.1.el7.x86_64 \
KBUILD_SRC=/usr/src/kernels/3.10.0-693.17.1.el7.x86_64 \
KBUILD_EXTMOD="/root/rtpengine/kernel-module" -f /usr/src/kernels/3.10.0-693.17.1.el7.x86_64/Makefile \
modules
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (		\
echo >&2;							\
echo >&2 "  ERROR: Kernel configuration is invalid.";		\
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";	\
echo >&2 ;							\
/bin/false)
mkdir -p /root/rtpengine/kernel-module/.tmp_versions ; rm -f /root/rtpengine/kernel-module/.tmp_versions/*
make -f /usr/src/kernels/3.10.0-693.17.1.el7.x86_64/scripts/Makefile.build obj=/root/rtpengine/kernel-module
  gcc -Wp,-MD,/root/rtpengine/kernel-module/.xt_RTPENGINE.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include -I/usr/src/kernels/3.10.0-693.17.1.el7.x86_64/arch/x86/include -Iarch/x86/include/generated  -I/usr/src/kernels/3.10.0-693.17.1.el7.x86_64/include -Iinclude -I/usr/src/kernels/3.10.0-693.17.1.el7.x86_64/arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I/usr/src/kernels/3.10.0-693.17.1.el7.x86_64/include/uapi -Iinclude/generated/uapi -include /usr/src/kernels/3.10.0-693.17.1.el7.x86_64/include/linux/kconfig.h   -I/root/rtpengine/kernel-module -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -std=gnu89 -O2 -m64 -mno-mmx -mno-sse -mpreferred-stack-boundary=3 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -Wframe-larger-than=2048 -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -Wframe-larger-than=2048 -fstack-protector-strong -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -g -pg -mfentry -DCC_USING_FENTRY -fno-inline-functions-called-once -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -DRTPENGINE_VERSION="\"undefined\"" -D__RE_EXTERNAL  -DMODULE  -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(xt_RTPENGINE)"  -D"KBUILD_MODNAME=KBUILD_STR(xt_RTPENGINE)" -c -o /root/rtpengine/kernel-module/.tmp_xt_RTPENGINE.o /root/rtpengine/kernel-module/xt_RTPENGINE.c
  if [ "-pg" = "-pg" ]; then if [ /root/rtpengine/kernel-module/xt_RTPENGINE.o != "scripts/mod/empty.o" ]; then ./scripts/recordmcount  "/root/rtpengine/kernel-module/xt_RTPENGINE.o"; fi; fi;
(cat /dev/null;   echo kernel//root/rtpengine/kernel-module/xt_RTPENGINE.ko;) > /root/rtpengine/kernel-module/modules.order
make -f /usr/src/kernels/3.10.0-693.17.1.el7.x86_64/scripts/Makefile.modpost
  find /root/rtpengine/kernel-module/.tmp_versions -name '*.mod' | xargs -r grep -h '\.ko$' | sort -u | sed 's/\.ko$/.o/' | scripts/mod/modpost -m -a -i ./Module.symvers -I /root/rtpengine/kernel-module/Module.symvers  -o /root/rtpengine/kernel-module/Module.symvers  -w -s -T -
  gcc -Wp,-MD,/root/rtpengine/kernel-module/.xt_RTPENGINE.mod.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include -I/usr/src/kernels/3.10.0-693.17.1.el7.x86_64/arch/x86/include -Iarch/x86/include/generated  -I/usr/src/kernels/3.10.0-693.17.1.el7.x86_64/include -Iinclude -I/usr/src/kernels/3.10.0-693.17.1.el7.x86_64/arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I/usr/src/kernels/3.10.0-693.17.1.el7.x86_64/include/uapi -Iinclude/generated/uapi -include /usr/src/kernels/3.10.0-693.17.1.el7.x86_64/include/linux/kconfig.h   -I/root/rtpengine/kernel-module -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -std=gnu89 -O2 -m64 -mno-mmx -mno-sse -mpreferred-stack-boundary=3 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -Wframe-larger-than=2048 -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -Wframe-larger-than=2048 -fstack-protector-strong -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -g -pg -mfentry -DCC_USING_FENTRY -fno-inline-functions-called-once -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -DRTPENGINE_VERSION="\"undefined\"" -D__RE_EXTERNAL  -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(xt_RTPENGINE.mod)"  -D"KBUILD_MODNAME=KBUILD_STR(xt_RTPENGINE)" -DMODULE  -c -o /root/rtpengine/kernel-module/xt_RTPENGINE.mod.o /root/rtpengine/kernel-module/xt_RTPENGINE.mod.c
  ld -r -m elf_x86_64 -T /usr/src/kernels/3.10.0-693.17.1.el7.x86_64/scripts/module-common.lds --build-id  -o /root/rtpengine/kernel-module/xt_RTPENGINE.ko /root/rtpengine/kernel-module/xt_RTPENGINE.o /root/rtpengine/kernel-module/xt_RTPENGINE.mod.o
make[1]: Leaving directory `/usr/src/kernels/3.10.0-693.17.1.el7.x86_64'
```

**Comment by MagnifyTelecom** [comment]
Yeah strange versions etc all match up still getting error,. will try again on different hardware.

[root@localhost kernel-module]# uname -a
Linux localhost.localdomain 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost kernel-module]# cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)
[root@localhost kernel-module]# cat /etc/centos-release-upstream
Derived from Red Hat Enterprise Linux 7.4 (Source)
[root@localhost kernel-module]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)
[root@localhost kernel-module]# make clean
make -C /lib/modules/3.10.0-693.17.1.el7.x86_64/build M=/root/rtpengine/kernel-module clean || true
make[1]: Entering directory `/usr/src/kernels/3.10.0-693.17.1.el7.x86_64'
  CLEAN   /root/rtpengine/kernel-module/.tmp_versions
make[1]: Leaving directory `/usr/src/kernels/3.10.0-693.17.1.el7.x86_64'
[root@localhost kernel-module]# KBUILD_VERBOSE=1 make
make -C /lib/modules/3.10.0-693.17.1.el7.x86_64/build M=/root/rtpengine/kernel-module O=/lib/modules/3.10.0-693.17.1.el7.x86_64/build modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-693.17.1.el7.x86_64'
make -C /usr/src/kernels/3.10.0-693.17.1.el7.x86_64 \
KBUILD_SRC=/usr/src/kernels/3.10.0-693.17.1.el7.x86_64 \
KBUILD_EXTMOD="/root/rtpengine/kernel-module" -f /usr/src/kernels/3.10.0-693.17.1.el7.x86_64/Makefile \
modules
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (                \
echo >&2;                                                       \
echo >&2 "  ERROR: Kernel configuration is invalid.";           \
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";      \
echo >&2 ;                                                      \
/bin/false)
mkdir -p /root/rtpengine/kernel-module/.tmp_versions ; rm -f /root/rtpengine/kernel-module/.tmp_versions/*
make -f /usr/src/kernels/3.10.0-693.17.1.el7.x86_64/scripts/Makefile.build obj=/root/rtpengine/kernel-module
  gcc -Wp,-MD,/root/rtpengine/kernel-module/.xt_RTPENGINE.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include -I/usr/src/kernels/3.10.0-693.17.1.el7.x86_64/arch/x86/include -Iarch/x86/include/generated  -I/usr/src/kernels/3.10.0-693.17.1.el7.x86_64/include -Iinclude -I/usr/src/kernels/3.10.0-693.17.1.el7.x86_64/arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I/usr/src/kernels/3.10.0-693.17.1.el7.x86_64/include/uapi -Iinclude/generated/uapi -include /usr/src/kernels/3.10.0-693.17.1.el7.x86_64/include/linux/kconfig.h   -I/root/rtpengine/kernel-module -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -std=gnu89 -O2 -m64 -mno-mmx -mno-sse -mpreferred-stack-boundary=3 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -Wframe-larger-than=2048 -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -Wframe-larger-than=2048 -fstack-protector-strong -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -g -pg -mfentry -DCC_USING_FENTRY -fno-inline-functions-called-once -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -DRTPENGINE_VERSION="\"undefined\"" -D__RE_EXTERNAL  -DMODULE  -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(xt_RTPENGINE)"  -D"KBUILD_MODNAME=KBUILD_STR(xt_RTPENGINE)" -c -o /root/rtpengine/kernel-module/.tmp_xt_RTPENGINE.o /root/rtpengine/kernel-module/xt_RTPENGINE.c
/bin/sh: line 1:  2221 Segmentation fault      (core dumped) ./tools/objtool/objtool check "/root/rtpengine/kernel-module/xt_RTPENGINE.o"
make[3]: *** [/root/rtpengine/kernel-module/xt_RTPENGINE.o] Error 139
make[2]: *** [_module_/root/rtpengine/kernel-module] Error 2
make[1]: *** [sub-make] Error 2
make[1]: Leaving directory `/usr/src/kernels/3.10.0-693.17.1.el7.x86_64'
make: *** [modules] Error 2
[root@localhost kernel-module]#
