### ISSUE TITLE
One way audio for transcoded calls

### ISSUE THREAD

**Issue by pavanps** [sipwise/rtpengine#484]
HI,

I have configured one user agent to use Opus codec and another user agent to use PCMA codec. But observed one way audio. Please find the attached logs of rtpengine. 

[rtpengine.txt](https://github.com/sipwise/rtpengine/files/1793399/rtpengine.txt)

Please let me know if i need to configure anything else.

Thank you

**Comment by rfuchs** [comment]
Probably a version test issue. Open `resample.c` and look for the `#if ...` and `#endif` lines near the top of the function. Remove them, recompile and try again.
