### ISSUE TITLE
g_queue_free_full Error when compiling latest version on Centos 6.6

### ISSUE THREAD

**Issue by JonHVU** [sipwise/rtpengine#485]
Hi,

Sorry for the noise! 

Just trying to install the latest version from sources, and as mentioned in issue 392, I get the following error when trying to compile;

codec.o: In function `__payload_queue_free':
/usr/local/src/rtpengine/daemon/codec.c:902: undefined reference to `g_queue_free_full'
collect2: ld returned 1 exit status
make[1]: *** [rtpengine] Error 1
make[1]: Leaving directory `/usr/local/src/rtpengine/daemon'
make: *** [all] Error 2

Am I missing some packages? 

Any pointers would be great.

Many thanks

Jon

**Comment by rfuchs** [comment]
You'll need a newer glib. `g_queue_free_full` is available since 2.32.
