### ISSUE TITLE
media_socket.c segfault ssrc_in_p

### ISSUE THREAD

**Issue by etamme** [sipwise/rtpengine#488]
Hey Richard, 
Just got a segfault after running about a week on 4538af32b4647e0ea6e605870ab80cd482bb1b25

Heres the BT: https://gist.github.com/etamme/cbb1f0d9dc25133a59c907b034975202

**Comment by rfuchs** [comment]
What does gdb say to `print *(*ssrc_in_p)` ?

**Comment by etamme** [comment]
(gdb) print *(*ssrc_in_p)
$1 = {parent = 0x7fc57019e170, payload_type = -1, srtp_index = 0, srtcp_index = 0, ssrc_map_out = 790339811, packets = {p = 0x0}, octets = {p = 0x0}, packets_lost = {p = 0x0}, duplicates = {p = 0x0}, 
  last_seq = {p = 0x0}, last_ts = {p = 0x0}}

**Comment by rfuchs** [comment]
Hm that seems reasonable. How about `print *(*ssrc_in_p)->parent` ?

**Comment by etamme** [comment]
(gdb) print *(*ssrc_in_p)->parent
$2 = {h = {lock = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, ssrc = 0}, 
  input_ctx = {parent = 0x7fc57019e170, payload_type = -1, srtp_index = 0, srtcp_index = 0, ssrc_map_out = 790339811, packets = {p = 0x0}, octets = {p = 0x0}, packets_lost = {p = 0x0}, duplicates = {p = 0x0}, 
    last_seq = {p = 0x0}, last_ts = {p = 0x0}}, output_ctx = {parent = 0x7fc57019e170, payload_type = -1, srtp_index = 0, srtcp_index = 0, ssrc_map_out = 892173031, packets = {p = 0x0}, octets = {p = 0x0}, 
    packets_lost = {p = 0x0}, duplicates = {p = 0x0}, last_seq = {p = 0x0}, last_ts = {p = 0x0}}, sender_reports = {head = 0x0, tail = 0x0, length = 0}, rr_time_reports = {head = 0x0, tail = 0x0, length = 0}, 
  stats_blocks = {head = 0x0, tail = 0x0, length = 0}, lowest_mos = 0x0, highest_mos = 0x0, average_mos = {reported = {tv_sec = 0, tv_usec = 0}, jitter = 0, rtt = 0, packetloss = 0, mos = 0}, last_rtt = 0}

**Comment by rfuchs** [comment]
Do you ever see the log message (debug-level) `SSRC hash table exceeded size limit ...` in your logs?

**Comment by etamme** [comment]
hmm, we are currently running at log-level 6.  grep shows nothing in the logs, I can turn it up to 7 and see if that log appears.

**Comment by rfuchs** [comment]
Thank you. Must be a race condition of some sort.

**Comment by etamme** [comment]
Hey Richard, 
I checked the logs, and we are getting TONS (1,422 lines) of the following logs

SSRC hash table exceeded size limit (trying to add 2a67efd5) - deleting SSRC 65f8a493

**Comment by rfuchs** [comment]
Thanks for confirming my suspicion. Try with the patch referenced above.
