### ISSUE TITLE
segfault in dump_key crypto.c

### ISSUE THREAD

**Issue by etamme** [sipwise/rtpengine#489]
Hey Richard,

Got another segfault today, running 4538af3

Here is the bt: https://gist.github.com/etamme/b560a7d463104e249797604dfb81ee91

**Comment by rfuchs** [comment]
Just to confirm, please post the output of `print *c`

**Comment by etamme** [comment]
(gdb) print *c
$1 = {params = {crypto_suite = 0x0, master_key = '\000' <repeats 31 times>, master_salt = '\000' <repeats 13 times>, mki = 0x0, mki_len = 0, session_params = {unencrypted_srtcp = 0, unencrypted_srtp = 0, 
      unauthenticated_srtp = 0}}, session_key = '\000' <repeats 31 times>, session_salt = '\000' <repeats 13 times>, session_auth_key = '\000' <repeats 19 times>, session_key_ctx = {0x0, 0x0}, 
  have_session_key = 0}

**Comment by rfuchs** [comment]
How about `thread apply all bt` ? :)

**Comment by etamme** [comment]
here is a gist with the output: https://gist.github.com/etamme/9589b7aa7c17b6f60631de2543801008
