### ISSUE TITLE
No audio in Chrome after 11 minutes - failed to unprotect audio RTP packet

### ISSUE THREAD

**Issue by l7s** [sipwise/rtpengine#495]
Hi, I am using RTPEngine to bridge audio between Chrome and Asterisk. In most cases it is all working fine, however on some Chrome clients exactly 11 minutes after the call was established, Chrome logs:

`channel.cc(876)] Failed to unprotect audio RTP packet: size=176, seqnum=5271, SSRC=1044128664`

and stops rendering audio (despite SRTP packets are still being delivered from RTPEngine just fine).

We use no STUN/TURN and Chrome behind NAT sends SIP Signalling via OpenSIPS which replaces private with public IP in SDP and communicates with RTPEngine to establish a call.

There is nothing in RTPEngine logs to suggest what the problem might be.

Would anyone be able to suggest how to start troubleshooting this?

**Comment by rfuchs** [comment]
Run rtpengine with log level 7 and post the full log for a failed call.
Post a pcap containing all of the relevant traffic (RTP, RTCP, DTLS, etc) for the same call.
Post which version of rtpengine you're using, as well as any other relevant info (e.g. Chrome log output)

**Comment by l7s** [comment]
Just a quick note: still unable to reproduce the issue when collecting logs / pcap trace at the same time :( will be trying more mid next week and uploading all traces as soon as I have them.
Regards,
Chris

**Comment by etamme** [comment]
Hey Richard,

We are running 5a73f12adb00f9603fc2bc067b69d446bca10dbd

We have experienced this EXACT same phenomenon, we are able to reproduce the issue using chrome or firefox when calling freeswitch.

After 11 minutes, browser logs stream:

[1:32:0411/142056.136759:ERROR:srtptransport.cc(160)] Failed to unprotect RTP packet: size=150, seqnum=21994, SSRC=1124631734

with increasing seqnum.

The rtpengine logs ALWAYS show repeated logs of:

2018-04-11T20:20:45.568371+00:00 media-relay0-0 rtpengine[15034]: INFO: [todrrshfpinh21c03vuf port 58290]: Kernelizing media stream: 199.7.175.150:28664

When this happens.  It's like it ... can't kernelize, but keeps trying?

I have captured rtp pcap on the rtpengine, logs at loglevel 7 from the rtpengine, sip signaling from the core proxy, and webrtc logging from the browser.

While it does not happen on every call, we are able to reproduce it regularly.

All logs and pcaps are available at:

https://owncloud.uphreak.com/index.php/s/pdPPZD7RA8MktgI


Please let me know if I can get any other info or help to debug this issue.

**Comment by etamme** [comment]
@l7s  we are running 6.1.1 5a73f12 which is a later version than you are running.

**Comment by l7s** [comment]
Right, in this case perhaps a clue might be in dependency libs. As we not only migrated RTPEngine to higher version, but also underlying OS from Debian 7 to Debian 9, so version of all dependency libs increased.

**Comment by etamme** [comment]
Hey Richard,
We've had to roll back to 5.1.1 as a result of this issue.  Please let me know if you need anything from me to help debug.

**Comment by egreenmachine** [comment]
Upon further investigation it appears that for the case @etamme and I are working on, disabling the kernel module appears to allow media to flow indefinitely. I had multiple calls that stayed up 20+ minutes with media flowing. This leads me to believe that the bug is either in the code that does the kernelization or the kernel module itself.

**Comment by egreenmachine** [comment]
@rfuchs thanks for getting to this. We will compile and test today.

**Comment by etamme** [comment]
thanks again richard you - picking from upstream now.

**Comment by egreenmachine** [comment]
@rfuchs initial smoke testing looks good. The repeated kernelization messages are gone and media flowed for 20+ minutes without issue across multiple calls. We are moving forward with it. Thanks again for the help.
