### ISSUE TITLE
Failed build with ../lib/fix_frame_channel_layout-02.h

### ISSUE THREAD

**Issue by prashantvidja** [sipwise/rtpengine#496]
Environment:
centos 7  64 bit
after below command getting error 
cd /usr/local/src/rtpengine/daemon && make

> cat ../lib/"resample.c" >> "resample.c"
cc -g -Wall -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread    -I/usr/include/libxml2   -I/usr/include/libxml2        -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -D_GNU_SOURCE      -DWITH_TRANSCODING -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DRTPENGINE_VERSION="\"6.2.0.0+0~mr6.2.0.0 git-master-4d9d140\"" -O3 -g -O2 -M main.c kernel.c poller.c aux.c control_tcp.c streambuf.c call.c control_udp.c redis.c bencode.c cookie_cache.c udp_listener.c control_ng.c sdp.c stun.c rtcp.c crypto.c rtp.c call_interfaces.c dtls.c log.c cli.c graphite.c ice.c socket.c media_socket.c homer.c recording.c statistics.c cdr.c ssrc.c iptables.c tcp_listener.c codec.c loglib.c auxlib.c rtplib.c str.c codeclib.c resample.c | sed -e 's/:/ .depend:/' > .depend
make[1]: Leaving directory `/usr/local/src/rtpengine/daemon'
make[1]: Entering directory `/usr/local/src/rtpengine/daemon'
cc -g -Wall -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread    -I/usr/include/libxml2   -I/usr/include/libxml2        -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -D_GNU_SOURCE      -DWITH_TRANSCODING -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DRTPENGINE_VERSION="\"6.2.0.0+0~mr6.2.0.0 git-master-4d9d140\"" -O3 -g -O2   -c -o fix_frame_channel_layout-test.o fix_frame_channel_layout-test.c
make[1]: Leaving directory `/usr/local/src/rtpengine/daemon'
Failed build with ../lib/fix_frame_channel_layout-01.h
Trying build with ../lib/fix_frame_channel_layout-02.h
make[1]: Entering directory `/usr/local/src/rtpengine/daemon'
rm -f "resample.c"
echo '/******** GENERATED FILE ********/' > "resample.c"
cat ../lib/"resample.c" >> "resample.c"
cc -g -Wall -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread    -I/usr/include/libxml2   -I/usr/include/libxml2        -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -D_GNU_SOURCE      -DWITH_TRANSCODING -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DRTPENGINE_VERSION="\"6.2.0.0+0~mr6.2.0.0 git-master-4d9d140\"" -O3 -g -O2 -M main.c kernel.c poller.c aux.c control_tcp.c streambuf.c call.c control_udp.c redis.c bencode.c cookie_cache.c udp_listener.c control_ng.c sdp.c stun.c rtcp.c crypto.c rtp.c call_interfaces.c dtls.c log.c cli.c graphite.c ice.c socket.c media_socket.c homer.c recording.c statistics.c cdr.c ssrc.c iptables.c tcp_listener.c codec.c loglib.c auxlib.c rtplib.c str.c codeclib.c resample.c | sed -e 's/:/ .depend:/' > .depend
make[1]: Leaving directory `/usr/local/src/rtpengine/daemon'
make[1]: Entering directory `/usr/local/src/rtpengine/daemon'
cc -g -Wall -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread    -I/usr/include/libxml2   -I/usr/include/libxml2        -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -D_GNU_SOURCE      -DWITH_TRANSCODING -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DRTPENGINE_VERSION="\"6.2.0.0+0~mr6.2.0.0 git-master-4d9d140\"" -O3 -g -O2   -c -o fix_frame_channel_layout-test.o fix_frame_channel_layout-test.c
make[1]: Leaving directory `/usr/local/src/rtpengine/daemon'
Failed build with ../lib/fix_frame_channel_layout-02.h
make: *** [fix_frame_channel_layout.h] Error 1

**Comment by rfuchs** [comment]
You're probably missing the ffmpeg/libavcodec development packages. Build with the `with_transcoding=no` option if you don't have them available.https://github.com/sipwise/rtpengine#manual-compilation

**Comment by ovoshlook** [comment]
Hi Have same problem
Installed ffmpeg dev packages as described on ffmpeg official page  but problem stil exists
Maybe some need to move these libbs to some dir?

**Comment by rfuchs** [comment]
Apply 4ac6473 and build again to see where it's going wrong

**Comment by mavroudis** [comment]
I have the same issue with jessie on master.  Also using:

with_transcoding=no make

fails as well with:
```
make[2]: *** No rule to make target 'resample.h', needed by '.depend'.  Stop.
make[2]: Leaving directory '/usr/src/rtpengine/recording-daemon'
Failed build with ../lib/fix_frame_channel_layout-02.h
../lib/common.Makefile:33: recipe for target 'fix_frame_channel_layout.h' failed
make[1]: *** [fix_frame_channel_layout.h] Error 1
make[1]: Leaving directory '/usr/src/rtpengine/recording-daemon'
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 2
```
All dependencies have been verified with dpkg-checkbuilddeps.

**Comment by rfuchs** [comment]
If you want to do a build without transcoding, you need to clean your build directory first.

**Comment by pkuzak** [comment]
We also have issues with this:
```
In file included from fix_frame_channel_layout-test.c:1:0:
fix_frame_channel_layout.h:2:29: fatal error: libavutil/frame.h: Datei oder Verzeichnis nicht gefunden
 #include <libavutil/frame.h>
                             ^
compilation terminated.
make[3]: *** [fix_frame_channel_layout-test.o] Fehler 1
```
The build directory was clean.

**Comment by pkuzak** [comment]
Solved it. Mine was a _dpkg-buildpackage_ issue on Ubuntu when trying to build a source package. Solved my issue by passing _-nc_ to _dpkg-buildpackage_ when building the source package.

**Comment by adil-mafzool** [comment]
Merged the changes today with the master branch from Version: 6.2.0.0+0~mr6.2.0.0 git-master-ce44eaf to the latest 9c3edee (HEAD -> master, origin/master, origin/HEAD) 
on Debian 9:  -
Linux rtpengine-dev 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u2 (2018-02-21) x86_64 GNU/Linux

with ffmpeg and libavcodec-dev installed but unfortunately it failed: -


rtpuser@rtpengine-dev:~/rtpengine/rtpengine$ dpkg-buildpackage -us -uc
dpkg-buildpackage: info: source package ngcp-rtpengine
dpkg-buildpackage: info: source version 6.3.0.0+0~mr6.3.0.0
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Sipwise Jenkins Builder <jenkins@sipwise.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build rtpengine
dpkg-source: info: using options from rtpengine/debian/source/options: --extend-diff-ignore=.gitreview
 fakeroot debian/rules clean
dh clean --parallel
   debian/rules override_dh_auto_clean
make[1]: Entering directory '/home/rtpuser/rtpengine/rtpengine'
(cd daemon && /usr/bin/make clean)
make[2]: Entering directory '/home/rtpuser/rtpengine/rtpengine/daemon'
echo "Looking for usable alternative for fix_frame_channel_layout.h"; \
rm -f fix_frame_channel_layout-test.[co]; \
ln -s ../lib/fix_frame_channel_layout-test.c; \
for x in ../lib/fix_frame_channel_layout-*.h; do \
        echo "Trying build with $x"; \
        rm -f "fix_frame_channel_layout.h"; \
        echo '/******** GENERATED FILE ********/' > "fix_frame_channel_layout.h"; \
        cat "$x" >> "fix_frame_channel_layout.h"; \
        /usr/bin/make fix_frame_channel_layout-test.o && break; \
        echo "Failed build with $x"; \
        rm -f "fix_frame_channel_layout.h"; \
done; \
rm -f fix_frame_channel_layout-test.[co]; \
test -f "fix_frame_channel_layout.h"
Looking for usable alternative for fix_frame_channel_layout.h
Trying build with ../lib/fix_frame_channel_layout-01.h
make[3]: Entering directory '/home/rtpuser/rtpengine/rtpengine/daemon'
rm -f "resample.c"
echo '/******** GENERATED FILE ********/' > "resample.c"
cat ../lib/"resample.c" >> "resample.c"
make[3]: *** No rule to make target 'main.h', needed by '.depend'.  Stop.
make[3]: Leaving directory '/home/rtpuser/rtpengine/rtpengine/daemon'
Failed build with ../lib/fix_frame_channel_layout-01.h
Trying build with ../lib/fix_frame_channel_layout-02.h
make[3]: Entering directory '/home/rtpuser/rtpengine/rtpengine/daemon'
rm -f "resample.c"
echo '/******** GENERATED FILE ********/' > "resample.c"
cat ../lib/"resample.c" >> "resample.c"
make[3]: *** No rule to make target 'main.h', needed by '.depend'.  Stop.
make[3]: Leaving directory '/home/rtpuser/rtpengine/rtpengine/daemon'
Failed build with ../lib/fix_frame_channel_layout-02.h
Trying build with ../lib/fix_frame_channel_layout-03.h
make[3]: Entering directory '/home/rtpuser/rtpengine/rtpengine/daemon'
rm -f "resample.c"
echo '/******** GENERATED FILE ********/' > "resample.c"
cat ../lib/"resample.c" >> "resample.c"
make[3]: *** No rule to make target 'main.h', needed by '.depend'.  Stop.
make[3]: Leaving directory '/home/rtpuser/rtpengine/rtpengine/daemon'
Failed build with ../lib/fix_frame_channel_layout-03.h
Trying build with ../lib/fix_frame_channel_layout-04.h
make[3]: Entering directory '/home/rtpuser/rtpengine/rtpengine/daemon'
rm -f "resample.c"
echo '/******** GENERATED FILE ********/' > "resample.c"
cat ../lib/"resample.c" >> "resample.c"
make[3]: *** No rule to make target 'main.h', needed by '.depend'.  Stop.
make[3]: Leaving directory '/home/rtpuser/rtpengine/rtpengine/daemon'
Failed build with ../lib/fix_frame_channel_layout-04.h
../lib/common.Makefile:38: recipe for target 'fix_frame_channel_layout.h' failed
make[2]: *** [fix_frame_channel_layout.h] Error 1
make[2]: Leaving directory '/home/rtpuser/rtpengine/rtpengine/daemon'

**Comment by adil-mafzool** [comment]
thanks!
