### ISSUE TITLE
 error: Unmet build dependencies: libbcg729-dev

### ISSUE THREAD

**Issue by prashantvidja** [sipwise/rtpengine#497]
debian 9 64 bit

after fire below command  getting error
dpkg-buildpackage

dpkg-buildpackage
dpkg-buildpackage: info: source package ngcp-rtpengine
dpkg-buildpackage: info: source version 6.2.0.0+0~mr6.2.0.0
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Sipwise Jenkins Builder <jenkins@sipwise.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build rtpengine
dpkg-source: info: using options from rtpengine/debian/source/options: --extend-diff-ignore=.gitreview
dpkg-checkbuilddeps: error: Unmet build dependencies: libbcg729-dev
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)

**Comment by rfuchs** [comment]
This is addressed in the readme https://github.com/sipwise/rtpengine#on-a-debian-system
