### ISSUE TITLE
AMR Transcoding issues

### ISSUE THREAD

**Issue by ngvoice** [sipwise/rtpengine#498]
Hi,

i haven't checked the source-code for fixes or issues, but I came accross the following issue, when checking for the new AMR-Transcoding capabilities of RTPEngine:

Both for AMR-NB and AMR-WB I end up having distorted audio (a-Party is a Samsung S5 / S6 VoLTE handset, B-Party is Asterisk or FreeSwitch (this is likely just a configuration issue of the libav-transcoder).

In the SDP of the A-Party it's:

m=audio 1324 RTP/AVP 107 116 96 118 111 110
b=AS:41
b=RS:512
b=RR:1537
a=rtpmap:107 AMR-WB/16000/1
a=fmtp:107 octet-align=1;mode-change-capability=2;max-red=0
a=rtpmap:116 AMR-WB/16000/1
a=fmtp:116 mode-change-capability=2;max-red=0
a=rtpmap:96 AMR/8000/1
a=fmtp:96 octet-align=1;mode-change-capability=2;max-red=0
a=rtpmap:118 AMR/8000/1
a=fmtp:118 mode-change-capability=2;max-red=0
a=rtpmap:111 telephone-event/16000
a=fmtp:111 0-15
a=rtpmap:110 telephone-event/8000
a=fmtp:110 0-15

(please be aware, that both AMR and AMR-WB are provided in different variants, e.g. Octet-Aligned vs. Bandwidth efficient)

This is more a note to myself and to others, that there is an issue with AMR/AMR-WB and RTPEngine.

Just another note:
in lib/codeclib.c, Line 303:
It should be "AV_CODEC_ID_AMR_WB" instead of "AV_CODEC_ID_AMR_NB for the AMR-WB codec, but that didn't solve the issue. Without this change, the following error occurs:

Mar 20 14:11:03 pcscf-dev-fra1-02 rtpengine[27744]: ERR: [3809212901@192.168.4.2 port 20178]: Error configuring media output for codec AMR-WB: failed to open output context
Mar 20 14:11:03 pcscf-dev-fra1-02 rtpengine[27744]: ERR: [3809212901@192.168.4.2 port 20178]: av_log: Only 8000Hz sample rate supported

With this change, it's:

Mar 20 14:25:59 pcscf-dev-fra1-02 rtpengine[2193]: ERR: [1413244716@192.168.4.2 port 20038]: Error decoding media packet: failed to decode audio packet
Mar 20 14:25:59 pcscf-dev-fra1-02 rtpengine[2193]: ERR: [1413244716@192.168.4.2 port 20038]: av_log: Invalid mode 14

When trying to force AMR-NB:

Mar 20 14:27:06 pcscf-dev-fra1-02 rtpengine[2193]: ERR: [1336609775@192.168.4.2 port 20072]: Error decoding media packet: failed to decode audio packet
Mar 20 14:27:06 pcscf-dev-fra1-02 rtpengine[2193]: ERR: [1336609775@192.168.4.2 port 20072]: av_log: Corrupt bitstream

I wonder, if the contents of the fmtp-parameters in the SDP are parsed / passed to libav....

Thanks,
Carsten

**Comment by rfuchs** [comment]
See #492 for the codec ID mismatch.

I don't currently have a (good) way to test AMR myself, so any help is appreciated.

**Comment by ngvoice** [comment]
Just a quick note:
One way to test AMR/AMR-WB is using Asterisk 13 on Debian 9 (the official Debian Repository Version has built in AMR support, no need for extra repositories).

**Comment by agranig** [comment]
The above commit is confirmed to work with linphone AMR-WB, which is sending "AMR-WB/16000" and "octet-align=1", but nothing else.

**Comment by mtryfoss** [comment]
I think Linphone only supports octet-aligned mode, but it doesn't care what's specified in the fmtp line. 

Asterisk with AMR support probably also got some issues when both octet-aligned and bandwidth-efficient modes are specified at the same time. Asterisk core can't distinguish two codecs based on a fmtp-parameter.

**Comment by ngvoice** [comment]
Tested AMR/AMR-WB with a off-the shelf VoLTE Phone (Gigaset GS270). Works! Thanks! The only topic, I haven't checked so far, was comfort-noise & AMR, but it's supposed to be supported by FFMpeg.
