### ISSUE TITLE
Playback of pre-recorded streams/announcements

### ISSUE THREAD

**Issue by paulandrewhughes** [sipwise/rtpengine#499]
I  noticed on README for rtpEngine you have:
Rtpengine does not (yet) support:
* Playback of pre-recorded streams/announcements

Is there a roadmap or plan to implement this feature?

Thanks.

**Comment by rfuchs** [comment]
Nothing planned for the time being.

**Comment by paulandrewhughes** [comment]
Hi Richard, 

I noticed that transcoding feature was implemented recently, with bounty/sponsor support in [#392](https://github.com/sipwise/rtpengine/issues/392).
Would you be interesting in implementing the announcement feature under similar arrangement?

Thanks.

**Comment by rfuchs** [comment]
Transcoding has not actually been a sponsored development, so it's unlikely.
