### ISSUE TITLE
DTLS negotiation issue because of candidates/interfaces order.

### ISSUE THREAD

**Issue by sarumjanuch** [sipwise/rtpengine#500]
Hi guys! First of all, thanks a lot for such good software published in open source, and for all your work on it. Right now we are testing abilities of rtpengine, and trapped into an interesting issue. The story began when we started testing rtpengine in an environment where it listens on multiple interfaces (multihomed NATed). This means, that we have to smart guess the proper "direction" for each individual call, based on signaling path and user location. While we have no options for legacy phones, WebRTC capable endpoints can pass this work on ICE shoulders. We decided to put all server interfaces into "default address family", with idea that rtpengine will announce all it addresses using ICE candidates, and ICE process will take care about most optimal media path.  At the first look Everything was working as planned, but then we started to adding interfaces that are not reachable by some clients (this is why we need ICE), and this is where the issue raised. If the first candidate address from rtpengine is a candidate that is not reachable by the client, then the call is doomed... Ice connection status will persist in "checking" state till timeout. We started to debug it and find out that ICE binding checks are passing, and both server and client nominates and sets working pairs, but DTLS can't be established in such cases. If rtpengine is in "setup:active" role, it won't generate any "client hello" packets towards the selected pair, whereas if it in "setup:passive" role, client (latest chrome) generates DTLS "client hello" packets towards proper pair to rtpengine, and I can sniff them both on client and server, but rtpengine silently ignore such packets. The easiest way to reproduce this is to create address family with localhost as top priority (first) candidate, this will imitate unreachable candidate. Of course, it is possible to do smart gues and announce only reachable candidates to WebRTC endpoint, but then we lose the whole point of ICE. I am attaching 4 log files, with log-level 7, where you can see with which arguments rtpengine was run. The only change between working and the non-working call is the order of interfaces to listen during the start, which will result in candidates priorities. We made shots in both "setup:active" "setup:passive" roles for rtpengine. I would be able to dump traffic if needed, but then please provide me an email to send them to, as I would like to not announce my IP's to the whole GitHub.  If you require any additional information, I am always here, same is true regarding testing.  Thanks a lot for your attention. 

[Bad DTLS-active.txt](https://github.com/sipwise/rtpengine/files/1834729/bad_DTLS-active.txt)
[Bad DTLS-passive.txt](https://github.com/sipwise/rtpengine/files/1834733/bad_DTLS-passive.txt)

[Good DTLS-active.txt](https://github.com/sipwise/rtpengine/files/1834737/good_DTLS-active.txt)
[Good DTLS-passive.txt](https://github.com/sipwise/rtpengine/files/1834738/good_DTLS-passive.txt)

**Comment by rfuchs** [comment]
I think I see where it's going wrong. Please try with the commit referenced above.

**Comment by sarumjanuch** [comment]
Hi Richard. Hope will do tests today. Thanks!

**Comment by sarumjanuch** [comment]
Hi again, finally was able to test your changes, I confirm that everything is working now. I have tested all 4 cases from above, and few more: what was working, keeps working, and what was not, is working now. We highly appreciate your rapid reaction. Thanks again for all your work, have a good one!
