### ISSUE TITLE
xt_RTPENGINE null pointer dereference / system crash

### ISSUE THREAD

**Issue by etamme** [sipwise/rtpengine#503]
Hey Richard,

Fun one here - running 5a73f12adb00f9603fc2bc067b69d446bca10dbd all appeared well in lab testing, but as soon as it got any production traffic the box kept rebooting.  

We looked into it and the xt_RTPENGINE kernel module is doing null pointer dereferences.   

Here are two system crash reports with backtraces.

crash1: https://gist.github.com/etamme/e67914a2aa37993722d1bf3029d121a9

crash2: https://gist.github.com/etamme/700c8e51319f054d3d86aa9b0e9a1a2c

Please let me know if I can do anything further to help diagnose this.

-Eric

**Comment by rfuchs** [comment]
CentOS?

**Comment by etamme** [comment]
Yes, CentOS 7.

**Comment by rfuchs** [comment]
OK, I give up trying to cater to the CentOS kernel.

Look for the line `#elif (LINUX_VERSION_CODE == KERNEL_VERSION(3,10,0) && RHEL_MAJOR == 7) /* CentOS 7 */` and delete the one `ip_select_ident` statement directly underneath it.

**Comment by etamme** [comment]
Ok, I will do that, rebuild and test.  

Can you shed any light on what happened to cause the crash?  I'd like to know since I wasnt able to make it happen in my lab environment, but had it immediately go down in flames as soon as production traffic hit it.

As always, thanks again for your prompt responses.

**Comment by rfuchs** [comment]
I can't say for sure as CentOS seems to do its own thing with the kernel and the version test macro I mentioned is specific to the CentOS kernel and not any stock kernel.

**Comment by etamme** [comment]
Ok yeah - just looking for a way to test/verify before throwing production traffic on it again.

**Comment by etamme** [comment]
removing that line seems to have cleared things up - i did a manual install on a single relay box with a small amount of prod. traffic.  ill leave this open till i can get a bit larger sample, but first tests are looking good.
