### ISSUE TITLE
Feature request: Codec selection for recorded Pcaps

### ISSUE THREAD

**Issue by adil-mafzool** [sipwise/rtpengine#504]
Currently pcaps are recorded with the codecs for the call. 

This means when the call is being transcoded between for example G729 to G711alaw. The resulted pcap will contain two RTP streams with one each of codec G729 and G711alaw respectively. 

Will it be possible to have a feature in RTPEngine with like new parameter say called recording-pcap? This parameter can specify the codec type for recording pcap. 

This process may increase the load on RTPEngine but would be an interesting when somebody wishes to use pcap rather than rtpengine-recording-daemon.

**Comment by rfuchs** [comment]
Currently not in scope for us, but I welcome third party pull requests.

Another option would be to have a pcap output format in the recording-daemon.
