### ISSUE TITLE
missing rtpengine-recording.sample.conf

### ISSUE THREAD

**Issue by juha-h** [sipwise/rtpengine#505]
debian/ngcp-rtpengine-recording-daemon.default has:

`CONFIG_FILE=/etc/rtpengine/rtpengine-recording.conf`
`# CONFIG_SECTION=rtpengine-recording`

but there is no sample in etc dir.

etc/rtpengine.sample.conf has in [rtpengine] section:

`# recording-dir = /var/spool/rtpengine`
`# recording-method = proc`
`# recording-format = raw`

Should those line be moved to [rtpengine-recording] section of (not yet existing) rtpengine-recording.sample.conf?

**Comment by juha-h** [comment]
I found from source code, that the three recording-* lines indeed must be in rtpengine.conf file. rtpengine-recording.conf is for rtpengine-recording-daemon.  A sample would still be good to have.

**Comment by rfuchs** [comment]
Fixed by #521
