### ISSUE TITLE
recording .meta file gets deleted after call is finished

### ISSUE THREAD

**Issue by juha-h** [sipwise/rtpengine#507]
With this kind of recording configuration:

`[rtpengine]`
`recording-dir = /var/spool/rtpengine`
`recording-method = proc`

`[rtpengine-recording]`
`table = 0`
`output-format = wav`
`output-mixed = 1`
`spool-dir = /var/spool/rtpengine`
`output-dir = /var/spool/rtpengine`

.meta file gets deleted from /var/spool/rtpengine dir after the call is finished leaving only .wav file there.

**Comment by rfuchs** [comment]
That's by design. The metafile only serves as intermediary between rtpengine and the recording daemon. If you wish to retain metadata after the call finished, the recording daemon can write that into a mysql db.

**Comment by juha-h** [comment]
Richard Fuchs writes:

> That's by design. The metafile only serves as intermediary between
> rtpengine and the recording daemon. If you wish to retain metadata
> after the call finished, the recording daemon can write that into a
> mysql db.

OK, thanks for the info.  In another issue, I was after
recording-deamon.sample.conf.  That example file could include also
example of mysql config vars and mysql schema description.

I'll close this issue,

-- Juha

**Comment by juha-h** [comment]
Solved.
