### ISSUE TITLE
Wrong payload type(first packet only) 126 instead of 96 for Opus pcap recording 

### ISSUE THREAD

**Issue by adil-mafzool** [sipwise/rtpengine#509]
A minor bug where rtpengine daemon (Version: 6.2.0.0+0~mr6.2.0.0 git-master-ce44eaf)  is recording wrong payload type(first packet only) 126 instead of 96 for Opus call with recording method set to pcap.

Please see the attached capture: -

[9ca0d5f9-19e0b719-464022f9%40172_opus.zip](https://github.com/sipwise/rtpengine/files/1876427/9ca0d5f9-19e0b719-464022f9.40172_opus.zip)

**Comment by rfuchs** [comment]
Any more details? Transcoding enabled?

**Comment by adil-mafzool** [comment]
Transcoding was enabled. 

Please find the rtpengine log and opus capture attached here: -
[WrongOpusPacket.zip](https://github.com/sipwise/rtpengine/files/1876570/WrongOpusPacket.zip)

**Comment by rfuchs** [comment]
Are you sure that this is not what is actually being received?
`Apr  4 16:50:24 rtpengine-dev rtpengine[8912]: WARNING: [ac6a7619-81a33bf9-54b44119@172.31.17.20~2o port 30710]: RTP packet with unknown payload type 126 received`
Do you have a pcap done on the actual wire (wireshark or tcpdump) to compare it with?
