### ISSUE TITLE
store recorded audio to database

### ISSUE THREAD

**Issue by juha-h** [sipwise/rtpengine#510]
Currently recording-daemon stores recorded audio to file(s) in output-dir and the name and path of the file(s) is stored in recording_streams table of rtpengine database.  In order to avoid use of NFS to get access to the file(s) from another host, it would be desirable that the audio can be stored in a blob type field of database table.

**Comment by juha-h** [comment]
I made a trial implementation of storing streams to a new mediumblob field in recording_streams table.  Question:  should a new config var/vars be introduced to turn on this feature and/or turn off storing of streams to the file system?  Any suggestions?

**Comment by rfuchs** [comment]
A tristate option would probably make most sense: store files on FS only, store files in DB only, or store files in both.

**Comment by juha-h** [comment]
How about 'output-storage' with values "db|file|both"?  Or some better name?

**Comment by rfuchs** [comment]
Sounds good to me.

**Comment by juha-h** [comment]
Implemented.
