### ISSUE TITLE
memory leaks in dtls and ssrc handling

### ISSUE THREAD

**Issue by jerzyptak** [sipwise/rtpengine#511]
I have identified few memory leaks:
- in packet_stream structure ice_dtls property is initialised but dtls_connection_cleanup is never called on it
- in codec_handlers_update function passthrough_handlers is not always emptied
- in few places reference to ssrc object is not decremented

I have implemented fixes for those and pull request will follow shortly.

**Comment by rfuchs** [comment]
Very nice, thank you. Closing this in favour of #512
