### ISSUE TITLE
recording-daemon does not store metadata to recording_metakeys table

### ISSUE THREAD

**Issue by juha-h** [sipwise/rtpengine#513]
Using mr6.2, recording-daemon does not store metadata records to recording_metakeys table.  Records to recording_calls and recording_streams do get properly inserted and updated.

**Comment by juha-h** [comment]
I'm giving this kind of offer:

rtpengine_offer(ICE=force replace-session-connection replace-origin rtcp-mux-demux via-branch=extra trust-address record-call=on metadata=rp@30001)

rtpengine.conf has:

[rtpengine]
table = 0
...
recording-dir = /var/spool/rtpengine
recording-method = proc

rtpengine-recording.conf is:

[rtpengine-recording]
table = 0
output-format = mp3
output-mixed = 1
spool-dir = /var/spool/rtpengine
output-dir = /var/spool/rtpengine
mysql-host = 127.0.0.1
mysql-port = 3306
mysql-user = user
mysql-pass = pass
mysql-db = rtpengine

The result is that a new record is inserted to recording_calls and recording_streams tables, but nothing gets inserted to recording_streams table.  correct .meta file exists for a short while in /var/spool/rtpengine/ dir.

**Comment by rfuchs** [comment]
The recording daemon expects the metadata as a list of key/value pairs separated by pipe characters, for example `key1:val1|key2:val2`

**Comment by juha-h** [comment]
Richard Fuchs writes:

> The recording daemon expects the metadata as a list of key/value pairs
> separated by pipe characters, for example `key1:val1|key2:val2`

Thanks, that was it.  I'll try to create pull request on README.md
'metadata' key.

-- Juha
