### ISSUE TITLE
Max number of ICE candidates exceeded?

### ISSUE THREAD

**Issue by timrsa** [sipwise/rtpengine#515]
Hi everyone,

I am wondering if anyone else has had this issue before, I have multiple servers (all configured identically) running opensips and RTPengine, they all work except one. I can register my extension and make calls perfectly but inbound fails, it seems it doesn't even make it back to webRTC. Below is an extraction of some logs of a call, I have the log level on 7.

`
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8411]: INVITE From: 41.x.x.x (Asterisk) does not use WebSockets
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8411]: RTPengine Offer UDP/TLS/RTP/SAVPF ICE=force rtcp-mux-offer
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] Received command 'offer' from 127.0.0.1:48395
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] Maxmimum number of ICE candidates exceeded
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] offer time = 0.000350 sec
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] Replying to 'offer' from 127.0.0.1:48395
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8408]: ERROR:core:print_rr_body: too many RR
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8408]: ERROR:dialog:get_routing_info: failed to print route records
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8408]: INVITE From: 41.x.x.x (Asterisk) does not use WebSockets
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8408]: RTPengine Offer UDP/TLS/RTP/SAVPF ICE=force rtcp-mux-offer
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] Received command 'offer' from 127.0.0.1:43506
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] Maxmimum number of ICE candidates exceeded
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] offer time = 0.000347 sec
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] Replying to 'offer' from 127.0.0.1:43506
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8411]: ERROR:core:print_rr_body: too many RR
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8411]: ERROR:dialog:get_routing_info: failed to print route records
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8411]: INVITE From: 41.x.x.x (Asterisk) does not use WebSockets
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8411]: RTPengine Offer UDP/TLS/RTP/SAVPF ICE=force rtcp-mux-offer
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] Received command 'offer' from 127.0.0.1:48395
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] Maxmimum number of ICE candidates exceeded
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] offer time = 0.000450 sec
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] Replying to 'offer' from 127.0.0.1:48395
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8408]: ERROR:core:print_rr_body: too many RR
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8408]: ERROR:dialog:get_routing_info: failed to print route records
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8408]: INVITE From: 41.x.x.x (Asterisk) does not use WebSockets
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8408]: RTPengine Offer UDP/TLS/RTP/SAVPF ICE=force rtcp-mux-offer
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] Received command 'offer' from 127.0.0.1:43506
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] Maxmimum number of ICE candidates exceeded
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] offer time = 0.000396 sec
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] Replying to 'offer' from 127.0.0.1:43506
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8409]: ERROR:core:print_rr_body: too many RR
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8409]: ERROR:dialog:get_routing_info: failed to print route records
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8409]: INVITE From: 41.x.x.x (Asterisk) does not use WebSockets
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8409]: RTPengine Offer UDP/TLS/RTP/SAVPF ICE=force rtcp-mux-offer
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] Received command 'offer' from 127.0.0.1:51541
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] Maxmimum number of ICE candidates exceeded
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] offer time = 0.000397 sec
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] Replying to 'offer' from 127.0.0.1:51541
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8408]: ERROR:core:print_rr_body: too many RR
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8408]: ERROR:dialog:get_routing_info: failed to print route records
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8408]: INVITE From: 41.x.x.x (Asterisk) does not use WebSockets
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8408]: RTPengine Offer UDP/TLS/RTP/SAVPF ICE=force rtcp-mux-offer
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] Received command 'offer' from 127.0.0.1:43506
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] Maxmimum number of ICE candidates exceeded
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] offer time = 0.000411 sec
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] Replying to 'offer' from 127.0.0.1:43506
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8411]: ERROR:core:print_rr_body: too many RR
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8411]: ERROR:dialog:get_routing_info: failed to print route records
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8411]: INVITE From: 41.x.x.x (Asterisk) does not use WebSockets
Apr  6 10:09:29 sip1 /usr/local/opensips_2_2/sbin/opensips[8411]: RTPengine Offer UDP/TLS/RTP/SAVPF ICE=force rtcp-mux-offer
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] Received command 'offer' from 127.0.0.1:48395
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] Maxmimum number of ICE candidates exceeded
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] offer time = 0.000424 sec
Apr  6 10:09:29 sip1 rtpengine[8005]: [6b1f8a05387f011973eaee02663ba191@41.x.x.x:5060] Replying to 'offer' from 127.0.0.1:48395`

I had to update and recompile rtpengine and opensips recently due to chrome and an SDES issue. I tried to compile the previous versions of rtpengine and opensips to see if the call even hit the browser, which it doesnt. Im not entirely sure where else to look. 

I would just like to know if anyone else else has had this issue and can maybe give me a little more insite into it, it also seems like the RR is too large, so could there be a loop somewhere?

**Comment by rfuchs** [comment]
`MAX_ICE_CANDIDATES` defaults to 100, so you'd have to try very hard to exceed that. Seeing as the same call ID appears over and over again, I'd say you're looping the same call back to yourself.

As this is a SIP signalling issue and not directly related to rtpengine, I'm closing this issue.
