### ISSUE TITLE
rtpengine doesn't start with interface option

### ISSUE THREAD

**Issue by pasanmdev** [sipwise/rtpengine#516]
Hi Guys,

I'm having trouble starting my rtpengine daemon when I specfy the interface option in the config file. Below is my config
/etc/rtpengine/rtpengine.conf

[rtpengine]
table = 0
"### a single interface:"
interface = 10.3.1.138
listen-ng = 2223

I'm getting the following error

rtpengine: CRIT: Fatal error: Invalid interface specification: 10.3.1.138
ngcp-rtpengine-daemon[1667]: Starting RTP/media proxy: ngcp-rtpengine-daemon:[1523008607.347052] CRIT: Fatal error: Invalid interface specification: 10.3.1.138

If I specify the ADDRESS var in /etc/default/ngcp-rtpengine-daemon it starts fine.

ADDRESS=10.3.1.138

Can't spot what I'm doing wrong here.

**Comment by rfuchs** [comment]
Possibly some stray invisible characters in the file or something, or a linefeed format (CRLF/LF) mismatch. Do a hex dump (e.g. using `xxd`) on the config file to see if that's the case. Feel free to post the hexdump here if you're unsure.

**Comment by pasanmdev** [comment]
@rfuchs you are correct. It was a trailing whitepace after the ip address.

broken one
xxd /etc/rtpengine/rtpengine.conf
00000000: 5b72 7470 656e 6769 6e65 5d0a 0a74 6162  [rtpengine]..tab
00000010: 6c65 203d 2030 0a23 2323 2061 2073 696e  le = 0.### a sin
00000020: 676c 6520 696e 7465 7266 6163 653a 0a69  gle interface:.i
00000030: 6e74 6572 6661 6365 203d 2031 302e 332e  nterface = 10.3.
00000040: 312e 3133 3820 0a0a 6c69 7374 656e 2d6e  1.138 ..listen-n
00000050: 6720 3d20 3232 3233 0a0a 7469 6d65 6f75  g = 2223..timeou
00000060: 7420 3d20 3630 0a73 696c 656e 742d 7469  t = 60.silent-ti
00000070: 6d65 6f75 7420 3d20 3336 3030 0a74 6f73  meout = 3600.tos
00000080: 203d 2031 3834 0a0a 706f 7274 2d6d 696e   = 184..port-min
00000090: 203d 2035 3030 3030 0a70 6f72 742d 6d61   = 50000.port-ma
000000a0: 7820 3d20 3630 3030 300a 6d61 782d 7365  x = 60000.max-se
000000b0: 7373 696f 6e73 203d 2032 3030 300a       ssions = 2000.

correct one
xxd /etc/rtpengine/rtpengine.conf
00000000: 5b72 7470 656e 6769 6e65 5d0a 0a74 6162  [rtpengine]..tab
00000010: 6c65 203d 2030 0a23 2323 2061 2073 696e  le = 0.### a sin
00000020: 676c 6520 696e 7465 7266 6163 653a 0a69  gle interface:.i
00000030: 6e74 6572 6661 6365 203d 2031 302e 332e  nterface = 10.3.
00000040: 312e 3133 380a 0a6c 6973 7465 6e2d 6e67  1.138..listen-ng
00000050: 203d 2032 3232 330a 0a74 696d 656f 7574   = 2223..timeout
00000060: 203d 2036 300a 7369 6c65 6e74 2d74 696d   = 60.silent-tim
00000070: 656f 7574 203d 2033 3630 300a 746f 7320  eout = 3600.tos 
00000080: 3d20 3138 340a 0a70 6f72 742d 6d69 6e20  = 184..port-min 
00000090: 3d20 3530 3030 300a 706f 7274 2d6d 6178  = 50000.port-max
000000a0: 203d 2036 3030 3030 0a6d 6178 2d73 6573   = 60000.max-ses
000000b0: 7369 6f6e 7320 3d20 3230 3030 0a         sions = 2000.

But why is it so sensitive on such things ? can't config file parse deal with word boundaries ?

**Comment by rfuchs** [comment]
Config file parsing is handled by GLib: https://developer.gnome.org/glib/stable/glib-Key-value-file-parser.html

So I don't have much control over it.
