### ISSUE TITLE
SDP missing = sign

### ISSUE THREAD

**Issue by nakchak** [sipwise/rtpengine#52]
Just come accross a bit of a strange issue when i try and place a call to holly ivr with the rtp streams transiting through rtpengine.  The initial invite is ok, but when the 200 ok reply from holly hits rtpengine i get the following error:

Dec 18 18:40:28 vs-kam-prod02 rtpengine[9856]: Error parsing SDP at offset 262: Missing '=' sign

I have picked apart the sdp body and its well formed with the exception that it seems to have an extra blank line at the end.  Having had a cursory look at sdp.c it seems that their isnt a check that the line is > 0 chars in length before its parsed?

What if any impact would skipping blank lines in the sdp body cause?  As this system used to work fine before i put it behind kamailio and rtpengine...

**Comment by nakchak** [comment]
Patch seems to have done the trick, many thanks

**Comment by AKovalsky** [comment]
Hello guys, can you please tell how can I enable that feature using dpkg-buildpackage?

**Comment by rfuchs** [comment]
You can override the build flags through environment variables supported by `dpkg-buildflags`

For example:

`$ DEB_CFLAGS_SET=-DTERMINATE_SDP_AT_BLANK_LINE dpkg-buildpackage`

**Comment by brooksbridges-call48** [comment]
Is there any way to utilize this with the repository version or will it absolutely require a manually compiled or dpkg version?

**Comment by rfuchs** [comment]
I think it's time to turn this into a regular config option...

**Comment by brooksbridges-call48** [comment]
Please let me know if I can be of any assistance with testing.  We have a full development environment for this, so just say the word!

**Comment by rfuchs** [comment]
This is now merged to master as a default-on option, see f869c23
