### ISSUE TITLE
two recording related warnings after rtpengine_delete()

### ISSUE THREAD

**Issue by juha-h** [sipwise/rtpengine#520]
When a call that is recorded is terminated with rtpengine_delete(), first (after 30 secods) three INFO entries appear in syslog:

Apr  9 14:58:54 trout rtpengine-recording[4972]: INFO: [C fcf47aeae94dfa11-2db6e9e423caa81d.meta] [S tag-0-media-1-component-2-RTCP-id-3] EOF on stream tag-0-media-1-component-2-RTCP-id-3
Apr  9 14:58:54 trout rtpengine-recording[4972]: INFO: [C fcf47aeae94dfa11-2db6e9e423caa81d.meta] [S tag-0-media-1-component-1-RTP-id-2] EOF on stream tag-0-media-1-component-1-RTP-id-2
Apr  9 14:58:54 trout rtpengine-recording[4972]: INFO: [C fcf47aeae94dfa11-2db6e9e423caa81d.meta] [S tag-1-media-1-component-2-RTCP-id-1] EOF on stream tag-1-media-1-component-2-RTCP-id-1
Apr  9 14:58:54 trout rtpengine-recording[4972]: INFO: [C fcf47aeae94dfa11-2db6e9e423caa81d.meta] [S tag-1-media-1-component-1-RTP-id-0] EOF on stream tag-1-media-1-component-1-RTP-id-0

And then 5 seconds later two warnings:

Apr  9 14:58:59 trout rtpengine-recording[4972]: WARNING: av_log: 11 frames left in the queue on closing
Apr  9 14:58:59 trout rtpengine-recording[4972]: WARNING: NUL character in section header in fcf47aeae94dfa11-2db6e9e423caa81d-mix.mp3

The first is real in the sense that a couple of last seconds of the call is missing from the recording.  I don't know if the second has any significance.

**Comment by rfuchs** [comment]
The first warning might be due to a missing flush of the encoder, but I'm not sure if 11 frames are enough to account for seconds of missing audio. Still worth a try, see above commit.

The second warning would be due to some mistake in the metafile. Perhaps you can provide an example of a metafile that triggered this warning (zipped or as hexdump or something, so non-text data doesn't get lost).

**Comment by rfuchs** [comment]
0993065 seems to work for me, but I can't be sure if I'm running into the same issue you're having.

**Comment by juha-h** [comment]
Richard Fuchs writes:

> The second warning would be due to some mistake in the
> metafile. Perhaps you can provide an example of a metafile that
> triggered this warning (zipped or as hexdump or something, so non-text
> data doesn't get lost).

Attached is 'hexdump 5d8d588c93de3b72-b79c420bed477fc1.meta'.

-- Juha

**Comment by rfuchs** [comment]
Doesn't look like attachments to github via email work.

**Comment by juha-h** [comment]
I placed the hexdump here: https://box.tutpro.com/tmp/hexdump.txt

**Comment by juha-h** [comment]
Richard Fuchs writes:

> 0993065 seems to work for me, but I can't be sure if I'm running into
> the same issue you're having.

The crash was due to my mistake in applying the patch (had not updated
all four files).  I tried again and the crash is gone, but I still get
both warnings:

Apr 17 21:57:00 trout rtpengine-recording[1904]: [1523991420.101674] WARNING: av_log: 9 frames left in the queue on closing
Apr 17 21:57:00 trout rtpengine-recording[1904]: [1523991420.101978] WARNING: NUL character in section header in 2cbf1522e826344b-0403f101e8fd14e6-mix.mp3

-- Juha

**Comment by rfuchs** [comment]
re the NUL character warning: were you using the metadata= option at all?

**Comment by rfuchs** [comment]
Oh wait... are you using the same directory for the metafiles as you are for the mp3/wav output files?

**Comment by juha-h** [comment]
Richard Fuchs writes:

> re the NUL character warning: were you using the metadata= option at
> all?

No, offer looked like this:

Apr 17 21:56:19 trout /usr/bin/sip-proxy[29437]: INFO: ===== rtpengine_offer(ICE=force replace-session-connection replace-origin rtcp-mux-demux via-branch=extra trust-address record-call=on)

**Comment by juha-h** [comment]
Richard Fuchs writes:
> Oh wait... are you using the same directory for the metafiles as you
> are for the mp3/wav output files?

My rtpengine-recording.conf looks like this:

[rtpengine-recording]
table = 0
output-storage = db
output-format = mp3
output-mixed = 1
spool-dir = /var/spool/rtpengine
output-dir = /var/spool/rtpengine
mysql-host = 127.0.0.1
mysql-port = 3306
mysql-user = foo
mysql-pass = bar
mysql-db = rtpengine

**Comment by rfuchs** [comment]
Yeah, that doesn't work. You can't use the same directory for both spool and output.

**Comment by juha-h** [comment]
Richard Fuchs writes:

> Yeah, that doesn't work. You can't use the same directory for both
> spool and output.

OK, I changed conf like this:

spool-dir = /var/spool/rtpengine
output-dir = /var/spool/rtpengine/tmp

and the second warning "WARNING: NUL character in section header" does
not appear anymore.

Only this is left:

Apr 18 21:02:31 trout rtpengine-recording[10153]: [1524074551.208101] WARNING: av_log: 11 frames left in the queue on closing

even after I have applied

https://github.com/sipwise/rtpengine/commit/0993065f1648418b9a016aeab07352a4c165563c

-- Juha

**Comment by juha-h** [comment]
I double checked that patch 0993065 was properly installed and then
changed codec used in the test calls from PCMU to opus.  With that
syslog reports more frames (14 - 18) left in the queue:

Apr 19 08:53:47 trout rtpengine-recording[21350]: [1524117227.513029] WARNING: av_log: 18 frames left in the queue on closing

-- Juha

**Comment by juha-h** [comment]
I did tests with mr7.2 and all warnings are gone.  Recordings still stop about 1-2 seconds before calls end, but that is not a big issue.

**Comment by john08burke** [comment]
@rfuchs are there any plans to merge [0993065](https://github.com/sipwise/rtpengine/commit/0993065f1648418b9a016aeab07352a4c165563c) with master? I noticed the last few frames missing from recordings as well. I have not done any tests with this patch, but from this thread it looks like it works?

**Comment by rfuchs** [comment]
@john08burke are you able to test the patch and confirm that it actually fixes what you're seeing?

**Comment by john08burke** [comment]
yes :smile: 
I'll do some testing in the next day or so and post results.

**Comment by juha-h** [comment]
Richard Fuchs writes:

> @john08burke are you able to test the patch and confirm that it
> actually fixes what you're seeing?

I applied the patch to version 7.2.2.0+0~mr7.2.2.0 and made two recording
test.  I counted from one to ten and in both tests "nine" was the last I
heard in the recording.

**Comment by john08burke** [comment]
@rfuchs I can confirm the results that @juha-h reported.  I applied to 7.1.0.0+0~mr7.1.0.0 and had same results.  I did notice that the following warning no longer gets logged with patch.

> WARNING: av_log: 11 frames left in the queue on closing

**Comment by juha-h** [comment]
Just checked with rtpengine 8.5.1 (most likely also some earlier versions) and complete calls are now recorded, i.e., nothing is missing from the end of the call.
