### ISSUE TITLE
RTP markering question (rtp.marker=true)

### ISSUE THREAD

**Issue by denyspozniak** [sipwise/rtpengine#524]
Hello!
I do not really understand this topic, but think that something is wrong with RTP packet markering.
I enabled on rtpengine pcap recording and noticed, that incoming stream (webrtc/opus side) does not have packets with Mark flag (rtp.marker=false), but stream from rtpengine (sip/opus) has some packets with (rtp.marker=true). And as I think, this markering leads to some kind of voice distortion when transcoding from opus to alaw on FreeSWITCH.

Can you explain rtpengine behavior and are there any possibilities to change it?

RFC 3551 says: _" For applications which send either no packets or occasional comfort- noise packets during silence, the first packet of a talkspurt, that is, the first packet after a silence period during which packets have not been transmitted contiguously, SHOULD be distinguished by setting the marker bit in the RTP data header to one. The marker bit in all other packets is zero. The beginning of a talkspurt MAY be used to adjust the playout delay to reflect changing network delays. Applications without silence suppression MUST set the marker bit to zero."_

**Comment by rfuchs** [comment]
The meaning of the marker bit is dependent on the RTP profile and also on the particular codec. Rtpengine doesn't current set the marker bit at all in outgoing packets when transcoding. In incoming packets it ignores it.

**Comment by rfuchs** [comment]
Without transcoding, it's passed through as received.
