### ISSUE TITLE
 codec-strip with video codecs

### ISSUE THREAD

**Issue by ryan-esty** [sipwise/rtpengine#525]
When I do a codec-strip with an audio codec things seem to work. When I do it with a video codec nothing happens. Is stripping of video codecs supported? For example if I do a codec-strip-VP8 rtpengine reports this back:
rtpengine:parse_flags: error processing flag `codec-strip-VP8': unknown error. Can someone tell me if I'm doing this incorrectly?

Ryan

**Comment by rfuchs** [comment]
Where do you see this error exactly?

**Comment by ryan-esty** [comment]
Sorry about that it appears to be an opensips issue. The opensips guys just said they fixed this back in February. I'm closing this now.

Ryan
