### ISSUE TITLE
Sessions with offer only are long placed in memory

### ISSUE THREAD

**Issue by kertor** [sipwise/rtpengine#526]
Hello! Find dome "strange behavior" of rtpengine.
Use "rtpengine-ctl list session all" i see some sessions  are long placed in memory.
I found out, if was only offer (no answer and no delete), session will stay in memory long time.
rtpengine not delete session by this timeout:
```
-o, --timeout=SECS               RTP timeout
```
p.s. this situation may be reproduce. For example, if restart opensips in call-establishment process.

**Comment by rfuchs** [comment]
Say what?

**Comment by kertor** [comment]
fix description.

**Comment by kertor** [comment]
Is this possible to add timeout for such calls?

**Comment by rfuchs** [comment]
The RTP timeout is intentionally only applied to fully established (two-way) calls. One-sided calls are exempted from it. The SIP proxy is responsible for tearing them down when an offer timeout occurs.

**Comment by kertor** [comment]
what if sip proxy crashed? these calls will be always on rtpengine side.

**Comment by rfuchs** [comment]
Use a SIP proxy that doesn't crash :smile:

**Comment by nikbyte** [comment]
@rfuchs I have the same issue. Sometimes calls are hung and under traffic there may be too many hung calls. Why not to have timeout for this?

**Comment by nikbyte** [comment]
it's clean. if you have (for example) offer and have no answer in a few minutes, this call is wrong.

**Comment by rfuchs** [comment]
How does 3c9f1a81ef2afc17210e6f52b912f788dc430168 look?

**Comment by nikbyte** [comment]
For me it's exactly what I need. Thanks!

**Comment by kertor** [comment]
Thanks, it is good!
