### ISSUE TITLE
Prioritising the codecs for transcoding

### ISSUE THREAD

**Issue by adil-mafzool** [sipwise/rtpengine#527]
Trying the following scenario: -
Caller (Side A) supports:
G722
PCMA
PCMU
G729

Callee (Side B) supports:
PCMA
PCMU
G729

Configured kamailio with:
rtpengine_offer("...codec-mask-opus codec-mask-G722 codec-mask-PCMA codec-mask-PCMU codec-mask-G729 transcode-PCMA transcode-PCMU transcode-G729")

But both sides end up on PCMA; where as I would like that G722 for Caller side and PCMA for Callee's end with rtpengine should transcode between G722 to PCMA and vice versa.

Is the above scenario possible with rtpengine configuration?

rtpengine --version
Version: 6.2.0.0+0~mr6.2.0.0 git-master-ce44eaf

[rtpengine_16_04_2018.zip](https://github.com/sipwise/rtpengine/files/1915045/rtpengine_16_04_2018.zip)

**Comment by rfuchs** [comment]
If there's a codec that both sides support, then rtpengine will gladly let both sides talk that codec to each other and won't interfere with transcoding. If you want to force G.722 on the caller's side, you have to ignore the other codecs that were offered (`codec-strip-PCMA` etc) and then offer them for transcoding (`transcode-PCMA`).

**Comment by adil-mafzool** [comment]
You mean the following: -

codec-mask-opus codec-mask-G722 codec-strip-PCMA codec-strip-PCMU codec-strip-G729 transcode-PCMA transcode-PCMU transcode-G729

But what would happen when caller has the following priority : -
PCMA
PCMU
G729
G722

Callee (Side B) answers:
PCMA
PCMU
G729

This will end up transcoding G722 and PCMA where this call should connect with PCMA only with no transcoding. 

Is it possible for rtpengine to consider the codec priority order from the call when applying codec-strip-PCMA?

**Comment by rfuchs** [comment]
Currently there's no such option. Codecs are seen as either supported or not supported. Priority is only considered when selecting a codec to transcode to (e.g. the first supported codec will be chosen). Quite frankly I'm not sure what you're trying to achieve here.

**Comment by adil-mafzool** [comment]
Well, I am trying to implement the rtpengine in a scenario where one side we have endpoints where endpoints will have the following codecs available: -
opus
G722
PCMA
PCMU
G729

an ITSP where only following codecs available: -
PCMA
PCMU
G729

Requirement is that when endpoint has put opus or g722 as first priority in the SDP; RTPengine should transcode those calls otherwise when PCMA, PCMU and G729 the transcoding is not necessarily required.

**Comment by rfuchs** [comment]
No I understood that much, but what's the reason behind insisting on using the highest priority codec?

**Comment by adil-mafzool** [comment]
Effectively managing and controlling endpoints and the trancoding rtpengine resources. Endpoints are being provisioned with codecs settings.
Hence, the better call quality where the newer endpoint implementation support codecs like opus and g722. 
Where as the old endpoints which don't support opus should work as they are now.

**Comment by rfuchs** [comment]
Your best bet might be to make the parameters given in the offer conditional on who/what the caller is or what they offer. If you have external knowledge of the caller, use that, or otherwise inspect the SDP and use that to determine which parameters to include.

I don't grasp your use case well enough to make another recommendation. For example, I can envision something like an `always-transcode` flag, with which rtpengine would skip the codec matchup procedure and always go along with the highest priority supported codec. But I don't know if that would actually solve what you're trying to do.

**Comment by adil-mafzool** [comment]
Something like a new flag of codec-order-offer which may carry out codec matchup on the basis of offer sent codec order after applying the codec-masks. 

codec-mask-opus codec-mask-G722 codec-mask-PCMA codec-mask-PCMU codec-mask-G729 transcode-PCMA transcode-PCMU transcode-G729 codec-order-offer 

Caller (Side A) SDP offer order: G722 PCMA PCMU G729
Callee (Side B) reply order: PCMA  PCMU G729
It would transcode G722 and PCMA

Where as there is no need to transacode 
Caller (Side A) SDP offer order: PCMA PCMU G729 G722 
Callee (Side B) reply order: PCMA  PCMU G729

**Comment by adil-mafzool** [comment]
Experiencing the issue where opus to pcma transcoding is not happening: -

Caller (Side A): G729 PCMA PCMU 

kamailio offer for Side A: 
codec-strip-G729 codec-mask-PCMA codec-mask-PCMU transcode-opus transcode-G722 transcode-PCMA transcode-PCMU transcode-G729 always-transcode 

which rtpengine makes opus G722 PCMA PCMU G729 

Yealink Callee (Side B) reply order: opus, G722, PCMU, PCMA and G729

Yealink is correctly sending opus but rtpengine is sending PCMA causing one way voice.

Please find the log attached rtpengine.zip 

rtpengine version: -
Version: 6.3.2.0+0~mr6.3.2.0 git-mr6.3-de223d9

[rtpengine.zip](https://github.com/sipwise/rtpengine/files/2357896/rtpengine.zip)

**Comment by adil-mafzool** [comment]
@rfuchs many thanks

**Comment by Jakihiko** [comment]
I'm in the same situation but it does not work,

**Caller** (Side A), offer codec by order: `OPUS, PCMA, PCMU`

Kamailio offer for Side A: `codec-strip=all codec-transcode=PCMA codec-transcode=PCMU`, 
then  rtpengine makes `PCMA PCMU` to callee

**Callee** (Side B) reply: `PCMA`
- Kamailio offer for Side A: `codec-strip=all  codec-accept=all`, 
- then  rtpengine makes `PCMA` to caller

I expect the answer should be OPUS (as the highest priority codec of caller )
 @rfuchs  could you please guide me how to archive this?
