### ISSUE TITLE
Segfault with large number of ssrc entries in ssrc_hash

### ISSUE THREAD

**Issue by scottcurtis** [sipwise/rtpengine#533]
Apr 12 13:06:15 us2rtpengine1 kernel: [3760025.839228] rtpengine[21193]: segfault at 80000002a ip 000000000042b01f sp 00007f6243fee030 error 4 in rtpengine[400000+59000]

Rtpengine Version: 
5.5.3.1+0~mr5.5.3.1

BackTrace:
#0  ng_stats_stream (totals=<optimized out>, ps=<optimized out>, list=<optimized out>) at call_interfaces.c:929
#1  ng_stats_media (totals=<optimized out>, m=<optimized out>, list=<optimized out>) at call_interfaces.c:984
#2  ng_stats_monologue (dict=0x0, dict@entry=0x7f6700129a7f, ml=0x7f6700132638, ml@entry=0x7f66f003e2d0, totals=0x3, totals@entry=0x7f67199c30e0) at call_interfaces.c:1017
#3  0x000000000042cbfa in ng_call_stats (call=<optimized out>, fromtag=<optimized out>, totag=<optimized out>, output=<optimized out>, totals=<optimized out>) at call_interfaces.c:1124
#4  0x000000000041336d in call_delete_branch (m=0x0, callid=0x22637273735f6563, branch=0x3, fromtag=0x7f67199c32a0, totag=0x7f67199c32b0, output=0x7f672044a99a <_IO_vfprintf_internal+22490>, delete_delay=30) at call.c:2465
#5  0x000000000042c69c in call_delete_ng (input=0x7f6700066878, m=0x1b82c80, output=0x7f6700066818) at call_interfaces.c:863
#6  0x000000000041d91a in control_ng_incoming (obj=0x1b84000, buf=<optimized out>, sin=0x7f67199c34e0, addr=0x7f67199c3500 "206.205.44.14:40489", ul=0x1b840a0) at control_ng.c:210
#7  0x000000000041c874 in udp_listener_incoming (fd=<optimized out>, p=0x1b7d0a0, x=<optimized out>) at udp_listener.c:56
#8  0x000000000040bf4e in poller_poll (p=p@entry=0x1b79d80, timeout=timeout@entry=100) at poller.c:350
#9  0x000000000040c2ed in poller_loop (d=0x1b79d80) at poller.c:505
#10 0x000000000040c360 in thread_detach_func (d=0x1b5cf50) at aux.c:143
#11 0x00007f67207b2064 in start_thread (arg=0x7f67199d4700) at pthread_create.c:309
#12 0x00007f67204e762d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Here is the line of code that is failing:
bencode_dictionary_add_integer(dict, "SSRC", ps->ssrc_in->parent->ssrc);

print *ps looks reasonable, however *(ps->ssrc_in) doesn't:
gdb) print *(ps->ssrc_in)
$2 = {parent = 0x800000002, srtp_index = 3761667022817283917, srtcp_index = 140059756036760}
(gdb) print *(ps->ssrc_in->parent)
Cannot access memory at address 0x800000002

Our application keeps one leg up while connecting that leg to multiple client legs resulting in multiple ssrc entries in the ssrc_hash . Although most of our customers have less than 10 connections in a session, some of our customers generate over 300 client connections for the original leg. Originally we were running on mr5.5.1.1. With that version we overran the check for ht->q.length >20 in get_ssrc() (ssrc.c) and received a large number of "SSRC hash table exceed" logs. This was prior to the fix to remove an entry from the hash table so our solution was to increase the check from 20 to 1000. However, we then ran into a problem where the delete response was too large for the socket send. At that time we discovered the fix in 5.5.3.1 that deleted an entry in the hash table and kept the number of entries at 20 which seemed like a good fix.

However, with 5.5.3.1 we are running into the segfault detailed above. Looking at other issues (#488) it looks like there may be a fix to "use reference counting on ssrc objects" in mr6.2 which may address our issue. 

1.	Based on the backtrace, does this look like the same issue that could be fixed by deploying mr6.2?
2.	A different fix I have been considering is to not even create the ssrc_entry. From what I can tell, this is only used to log stats and provide additional statistics in the query and delete response. However, we use kamailio and it is not using the ssrc_entry data returned in the query or delete response. I have created a version in which get_ssrc() (ssrc.c) immediately returns NULL and it seems to work fine, but I am not sure if there are side effects caused by this change. Is there risk in this solution or something I am missing in the way the ssrc_entry is used? 

Note: for 2, I also changed redis.c to check for the null in the return from get_ssrc(). This seems to be the only place that wasn't checking for null before using ssrc_entry pointer.

**Comment by rfuchs** [comment]
I think you're spot on in your assessment, both points. This does seem to be the same issue. In mr5.5, the SSRC stuff is used only for MOS calculations, so it's safe to disarm it like you did. (In newer versions, it's also used for transcoding.) That being said, this is still a bug that should get fixed. I'll see if I can backport the relevant change.

However, rtpengine isn't really made to expect hundreds of concurrent SSRC entries in one call, so you might be better off leaving the SSRC stuff disabled completely.

**Comment by rfuchs** [comment]
Check out the code in this branch https://github.com/sipwise/rtpengine/tree/rfuchs/gh533

**Comment by scottcurtis** [comment]
Thanks for the quick response! We will try the rfuchs/gh533 branch. It will probably take us a week to verify this since we have only been able to reproduce the segfault on production systems so need to wait for the appropriate window to deploy. I will provide an update once we have run this for a couple of days.

**Comment by rfuchs** [comment]
Any update here?

**Comment by scottcurtis** [comment]
Sorry for the delay. We have been slow getting this deployed to our production systems, but I have been able to reproduce it in a test environment and have confirmed the rfuch/gh533 branch does fix the problem.

Thanks for your help resolving the issue.

**Comment by rfuchs** [comment]
Merged to mr5.5
