### ISSUE TITLE
Recording Daemon : forward-to option  example code request

### ISSUE THREAD

**Issue by balazsradak** [sipwise/rtpengine#535]
I'm trying to use the Recording Daemon's _**forward-to**_ option, but with no luck. 
As I understand, this will send the calls meta info + streams to a socket server with the type of SOCK_SEQPACKET? 

Unfortunately I'm not so familiar with Unix Sockets, so would you be so kind to provide a very basic example code how to receive the data?

Thanks!

**Comment by pkuzak** [comment]
Did you configure the recording daemon correctly? I guess you set the _forward-to_ parameter, but in order this to work, you also need to set _output-format = none_. Did you do this?
For a basic example code you might take [this one](http://www.linuxhowtos.org/data/6/server.c), which is taken from [this page](http://www.linuxhowtos.org/C_C++/socket.htm). 
You have to replace 
`sockfd = socket(AF_INET, SOCK_STREAM, 0);`
with
`sockfd = socket(AF_UNIX, SOCK_SEQPACKET, 0);`
I did not test that code snippet, so I don't know if this works out of the box.

**Comment by balazsradak** [comment]
Thanks! I didn't know that _output-format_ has to be none with _forward-to_ option!
I have now the following in the syslog: _**Trying to send packets, but connection not initialized!**_ , but at least the recording-daemon doesn't stops as it did before setting the _output-format=none_ parameter.

**Comment by balazsradak** [comment]
I tried with this socket server:
 [https://github.com/balazsradak/simple-unix-socket-server/blob/master/unix_socket_server_seqpacket.c](url), but it doesnt't work. 

Syslog says: **_Trying to send packets, but connection not initialized!_**

With this client, I can send data to socket: 
[https://github.com/balazsradak/simple-unix-socket-server/blob/master/unix_socket_client_seqpacket.c](url)

Here is my _rtpengine-recording.conf_:

[rtpengine-recording]
table = 0
forward-to = /tmp/rtpengine
output-format = none

Do I need to set any other parameter maybe?

Thanks!

**Comment by pkuzak** [comment]
What version of _rtpengine_ are you using? Could you try with commit 79a74f69ff4b4f032a3af78f3be41c0b7050ff5b ? At least this commit is working for me, I didn't test with newer ones. 
I'd say you do not need any more settings.

**Comment by pkuzak** [comment]
Do you have configured 

> recording-dir = /var/spool/rtpengine
recording-method = proc
recording-format = raw

in _rtpengine_ configuration file?

**Comment by rfuchs** [comment]
Looks like the `forwarding` capture method depends on the presence of the `metadata=` option coming from the SIP proxy.

**Comment by balazsradak** [comment]
Now I'm on version 6.2, and yes, I have configured the recording parameters.

> recording-dir = /var/spool/rtpengine
> recording-method = proc
> recording-format = raw

The result is the same: 
_ERR: [C 1504209331%40192.168.9.146-fca4d70e26c77632.meta] [S tag-0-media-1-component-1-RTP-id-2] Trying to send packets, but connection not initialized!_

**Comment by balazsradak** [comment]
OK, I added metadata: 
> rtpengine_offer("record-call=on metadata={\"Meta\"}")

Now, when a call is initiated, I can see the metadata in socket server log, and when the call is established, nothing, but error message from syslog:

 **tag-0-media-1-component-1-RTP-id-2] Error sending: Broken**

**Comment by balazsradak** [comment]
OK, thank you for your help! 
I'll check things at my side.
