### ISSUE TITLE
Recording Daemon: Splitting audio stream for caller/callee

### ISSUE THREAD

**Issue by zpnielsen** [sipwise/rtpengine#536]
Hi all,

Just curious if the rtpengine recording daemon had the ability to parse the RTP audio into two separate recordings per call -- that being separate audio for caller and callee. We're wanting to isolate each stream for use with machine learning, but I haven't quite been able to figure out if that capability is a thing. I had an idea to record in pcap format and pipe that into tshark to isolate the streams, but that's just sloppy. I was hoping to be able to do this native to the recorder daemon, especially using the /proc recording option. Any insight y'all have would be greatly appreciated.

Thanks!
Zach

**Comment by rfuchs** [comment]
Yes, that is supported. You have the choice between one audio file per SSRC (generally one SSRC per participant), or a mixed audio file, or both.

**Comment by Jaykah** [comment]
@rfuchs Was unable to find this in the docs, how would one go about recording both separate streams (for caller and callee) and a mixed audio file?

Thanks!

**Comment by rfuchs** [comment]
@Jaykah  That's the default setting. `output-mixed=1` and `output-single=1`

**Comment by Jaykah** [comment]
@rfuchs thank you for your prompt response! Would that mean that just setting both options to 1 would generate 3 files per call (for two participants and 4+ for more participants)?

is there a way to name those files? E.g. leg1-031419.wav leg2-031419.wav mixed-031419.wav ?

**Comment by rfuchs** [comment]
That's exactly what it does. The files for the individual/directional streams are named with their SSRC in their name (e.g. `foobar-12345678.wav`) and the mixed file has `mixed` it its name (e.g. `foobar-mixed.wav`)

**Comment by Jaykah** [comment]
@rfuchs any way to change the naming scheme? Thanks!

**Comment by rfuchs** [comment]
Not currently, no. The way to associate a particular party with a recorded stream is through the `label` passed down from rtpengine, and enable the DB storage backend, as it stores the details for each file together with the label.

**Comment by Jaykah** [comment]
@rfuchs is there any documentation for those labels? were unable to locate those in Redis

**Comment by rfuchs** [comment]
They're not in Redis, they're in MySQL/MariaDB. You do something like `rtpengine_offer("... label=foobar")` and then when the recording daemon populates the `recording_streams` table, it will set the `tag_label` column to `foobar` for that call participant.

**Comment by Jaykah** [comment]
@rfuchs Got it, thanks! We do not have this table - where can we get the schema to create it? Was unable to find it in the repo

**Comment by rfuchs** [comment]
https://github.com/sipwise/rtpengine/blob/master/recording-daemon/db.c#L13

**Comment by zbazarov** [comment]
@rfuchs Hi! Tag_label is always empty... Adding label in rtpengine_offer/rtpengine_answer didn't work for me.  So you have any idea what the problem could be? Many thank's

**Comment by rfuchs** [comment]
@zbazarov post some logs and/or your config?

**Comment by zbazarov** [comment]
@rfuchs good morning! Thank's for u reply.

route[RECORDING] {
        if (!is_method("INVITE") || !has_body("application/sdp")) return;
        $var(record_dir) = $hdr(x-record);
        remove_hf("x-record");
        rtpengine_offer("label=foobar");
        start_recording();
}

I'm also tried do something like this:
 if ( is_method("ACK|BYE") ) {
        rtpengine_answer("label=foobar");
 }

**Comment by Jaykah** [comment]
@rfuchs where would the logs go? getting nothing related to recording in both the rtpengine log and syslog

Raised the log level in the config, yet getting nothing still, any suggestions?

**Comment by rfuchs** [comment]
The recording daemon logs the same way the rtpengine daemon does, but with the syslog ident `rtpengine-recording`. You need to look into your syslog config to see where that is going.
