### ISSUE TITLE
test case compilation failure

### ISSUE THREAD

**Issue by zhouyu8o** [sipwise/rtpengine#539]
**Error Message**
amr-encode-test.o: In function `dec_cb':
./amr-encode-test.c:18: undefined reference to `g_string_new'
./amr-encode-test.c:41: undefined reference to `g_string_free'
amr-encode-test.o: In function `do_test_amr_xx':
./amr-encode-test.c:74: undefined reference to `av_frame_alloc'
./amr-encode-test.c:79: undefined reference to `av_get_default_channel_layout'
./amr-encode-test.c:80: undefined reference to `av_frame_get_buffer'
codeclib.o: In function `avc_encoder_close':
./codeclib.c:1019: undefined reference to `avcodec_close'
./codeclib.c:1020: undefined reference to `avcodec_free_context'

**Root Cause**
The default rule of make put LDFLAGS immediately after cc command which causes cc fails to find libraries.

**Fix**
```
amr-decode-test: amr-decode-test.o codeclib.o str.o auxlib.o resample.o rtplib.o loglib.o
	$(CC) -o $@ $^ $(LDFLAGS)
 
amr-encode-test: amr-encode-test.o codeclib.o str.o auxlib.o resample.o rtplib.o loglib.o
	$(CC) -o $@ $^ $(LDFLAGS)

```

**Comment by rfuchs** [comment]
What system/platform/compiler does this happen on?

**Comment by rfuchs** [comment]
Does it work for you if the libs are placed in `LDLIBS` instead of `LDFLAGS`?

**Comment by zhouyu8o** [comment]
Ubuntu 18.04

Linux version 4.15.0-20-generic (buildd@lgw01-amd64-039) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.3.0-16ubuntu3' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --with-as=/usr/bin/x86_64-linux-gnu-as --with-ld=/usr/bin/x86_64-linux-gnu-ld --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)

**Comment by zhouyu8o** [comment]
it works by using LDLIBS

**Comment by zhouyu8o** [comment]
**LDFLAGS**
Extra flags to give to compilers when they are supposed to invoke the linker, ‘ld’, such as -L. Libraries (-lfoo) should be added to the LDLIBS variable instead.

**LDLIBS**
Library flags or names given to compilers when they are supposed to invoke the linker, ‘ld’. LOADLIBES is a deprecated (but still supported) alternative to LDLIBS. Non-library linker flags, such as -L, should go in the LDFLAGS variable.
