### ISSUE TITLE
amr-decode-test test failure

### ISSUE THREAD

**Issue by arkadiam** [sipwise/rtpengine#541]
Master branch build fails due to amr-decode-test failure.
amr-encode-test and bitstr-test pass fine.
System is Ubuntu 16.04.4 LTS. Please advise how to troubleshoot this issue.
Thanks.

./amr-decode-test 
Codec QCELP is only supported for decoding by codec library
Codec G729 is only supported for decoding by codec library
Codec iLBC is not supported by codec library
Codec ATRAC3 is only supported for decoding by codec library
Codec ATRAC-X is only supported for decoding by codec library
running test amr-decode-test.c:88
av_log: Using fltp internally between filters

test ok: amr-decode-test.c:88
running test amr-decode-test.c:93
av_log: Using fltp internally between filters

test ok: amr-decode-test.c:93
running test amr-decode-test.c:98
av_log: Using fltp internally between filters

test ok: amr-decode-test.c:98
running test amr-decode-test.c:103
av_log: Using fltp internally between filters

packet content mismatch
expected 320 bytes, received 320 bytes
expected:
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f8fff8ff10000000e8fff8ff28000000c8ff00003800f8ffb0ff08004800f0ffa8ff08006000f8ff98ff08008800f0ff88ff10008800e8ff70ff18008000d8ff70ff08007800d8ff88ff08007800e8ff90ff10007000e0ff90ff08006800f8ff88ff00008000f8ff88ff00008000f8ff78ff08008000e8ff78ff08007800e0ff88ff10007000e8ff90ff10006800e0ff98ff08007000e8ffa8fff8ff7000f0ff98fff8ff6800000080fff8ff6800f8ff90ff00007000f8ff90ff00007800f0ff88ff00008000f8ff80ff00008800f8ff80fff8ff8800f8ff70ff00008000f0ff80fff8ff8000e8ff80fff0ff8800
received:
0000000000000000000000000000000000000000ffff000000000000000000000000000000000000000000000000010001000000000001000000ffffffff00000000ffffffff000000000000000000001400e7fff9ff39000400cefff9ff4f00ffffacff06005400faff9bff0c005e00eeff9cff0d007400f5ff8fff0e009a00eeff80ff12009200f0ff67ff16008600d9ff6dff07008500dbff87ff0a008000ecff89ff13007500e9ff8dff09007400fbff8bff01008400f9ff8cff05008300fcff7eff0c008400ebff7aff0b007b00eaff88ff10007400f0ff8fff12006f00e7ff98ff09007800eaffa3fffbff7a00f1ff9efff8ff6e0000008bfffeff6b00fcff96ff04006c00fcff99fffbff7900f6ff8fff00007f0001008afffbff8700000088fff3ff860001007afff9ff8300f9ff83fff7ff8100f2ff86ffeaff8a00

**Comment by rfuchs** [comment]
Probably just a mismatch in codec algorithm that can be ignored. The details of the AMR tests are still being worked out and currently depend on a recent ffmpeg version.

**Comment by arkadiam** [comment]
Is it possible to make those tests optional so build can finish without errors?
