### ISSUE TITLE
Transcoding should check both send & recv when allocating new payload type

### ISSUE THREAD

**Issue by wshallum-kmk** [sipwise/rtpengine#544]
When trying to transcode using the following config, the default selected codec for the caller is not found in the SDP answer but is used anyway (I think).

Caller offer has payload type 97 as preferred codec. When adding 2 codecs to the answer it starts at 96 and overwrites 97 with another codec (Opus/48000) that is later removed. Transcoding still uses payload type 97 as output (in log message: "Default sink codec is ...") but it is no longer in the answer SDP.

Reproducible with version 9e43369b845cd3c44a386e0a1e83351b6ad5cd0c 

Repro script that calls rtpengine-ng-ctl w/ relevant SDP attached below.

[repro.sh.txt](https://github.com/sipwise/rtpengine/files/1982779/repro.sh.txt)

Checking both `media->codecs_recv` and `media->codecs_send` in `codec_add_payload_type` instead of only `media->codecs_recv` seems to fix this.

**Comment by rfuchs** [comment]
I don't think I see or understand the problem. Caller offers a bunch of AMR variants (and PCMA which is removed and ignored). So on the caller's side, AMR 97 is the default sink, as it's the first supported codec. Opus is added for transcoding on callee's side as 102. Callee then accepts Opus as 102 and rejects everything else. So on the callee's side, Opus is the default sink. This then goes back to the caller, with Opus removed (it wasn't offered) and AMR accepted, with 97 being the first and thus the sink. AFAICS this is exactly what's supposed to happen.

There is a problem with the different AMR variants not being treated as such (the `fmtp` should be taken into account), which results in another AMR instance being added when probably it shouldn't be, but that's not what you're talking about, is it?

**Comment by wshallum-kmk** [comment]
Choosing 97 is fine and as it should be, but 97 is not in the SDP returned for the answer.

**Comment by rfuchs** [comment]
97 isn't used on the caller's side. 97 is for Opus on the callee's side. Or do you have a pcap that shows 97 being used on the caller's side?

**Comment by rfuchs** [comment]
It is for me:
```
New SDP:
-----8<-----8<-----8<-----8<-----8<-----
v=0
o=- 2597503949481915186 2 IN IP4 192.0.2.2
s=-
t=0 0
a=msid-semantic: WMS stream_local
m=audio 30000 RTP/AVP 97 98 99 100 101
c=IN IP4 172.17.0.1
a=rtpmap:97 AMR-WB/16000/1
a=rtpmap:98 AMR-WB/16000/1
a=rtpmap:99 AMR/8000/1
a=rtpmap:100 AMR/8000/1
a=rtpmap:101 AMR-WB/16000/1
a=fmtp:97 mode-set=0,1,2,4;mode-change-period=2;mode-change-neighbor=1
a=fmtp:98 mode-set=0,1,2;mode-change-period=2;mode-change-neighbor=1
a=fmtp:99 mode-set=0,1,2,3,4,5,6,7;mode-change-period=2;mode-change-neighbor=1
a=fmtp:100 mode-set=0,1,2,3,4,5,6,7
a=fmtp:101 mode-set=0,1,2,8;mode-change-period=2;mode-change-neighbor=1
a=sendrecv
a=rtcp:30001
a=ptime:20
```

**Comment by rfuchs** [comment]
Don't use the transcoding options in the `answer`. Only use them in the `offer`.

**Comment by wshallum-kmk** [comment]
That makes a lot more sense. Thank you very much for your assistance.
