### ISSUE TITLE
Log facility provided to --log-facility seems to be ignored 

### ISSUE THREAD

**Issue by pkuzak** [sipwise/rtpengine#546]
I used to use the log facility _local7_ for normal logs. This seems not to work anymore. Doesn't matter what I configure as _log-facility_ in configuration file, it always logs to _/var/log/syslog_. It gets parsed, cause I get an error when I configure an invalid log facility, but if it's valid, it seems to be ignored.

**Comment by rfuchs** [comment]
Cannot reproduce. Confirmed with strace: Without giving the option (defaults to `daemon`), it shows `sendto(3, "<31>...`. With `--log-facility=local7`, it shows `sendto(3, "<191>...`

`LOG_DAEMON` is `(3<<3)`, `LOG_LOCAL7` is `(23<<3)`. `LOG_DEBUG` is 7.
```
(gdb) p (23<<3)|7
$1 = 191
(gdb) p (3<<3)|7
$2 = 31
```

**Comment by pkuzak** [comment]
I guess I found the/my problem. Could you take a look on the pull request I've referenced, which I think solves it.
