### ISSUE TITLE
segfault at rtpengine 6.1

### ISSUE THREAD

**Issue by descartin** [sipwise/rtpengine#550]
hello all, 

we have deployed the Version: 6.1.0.0+0~mr6.1.0.0 git-v6.1-8e00868 in 2 systems (debian8 and debian9), to use the feature of commit 018e35cba8e3268457bfc81728f822f35cc170e1
Date:   Tue Jan 2 10:57:38 2018 -0500
    TT#27200 add option to omit a=rtcp attribute

and after 2-3 weeks of working ok, the rtpengine started to have segfaults like
May 12 05:35:04 rtpengine-2 kernel: [5691082.755813] rtpengine[665]: segfault at ffffffff00000000 ip 00007efc49e875c5 sp 00007efc3a7f90d0 error 5 in libglib-2.0.so.0.4200.1[7efc49e21000+10c000]
May 13 10:13:16 rtpengine-2 kernel: [5794094.553454] rtpengine[83030]: segfault at ffffffff00000000 ip 00007fe39ff9d5c5 sp 00007fe3978ff0d0 error 5 in libglib-2.0.so.0.4200.1[7fe39ff37000+10c000]
May 13 13:17:47 rtpengine-2 kernel: [5805156.779214] rtpengine[117592]: segfault at ffffffff00000000 ip 00007ff17a7ae5c5 sp 00007ff15a7f90d0 error 5 in libglib-2.0.so.0.4200.1[7ff17a748000+10c000]
May 13 14:45:23 rtpengine-2 kernel: [5810409.563935] rtpengine[124462]: segfault at ffffffff00000000 ip 00007f218813e5c5 sp 00007f217affa0d0 error 5 in libglib-2.0.so.0.4200.1[7f21880d8000+10c000]
May 13 15:36:09 rtpengine-2 kernel: [5813453.083553] rtpengine[127797]: segfault at ffffffff00000000 ip 00007f3d33c9c5c5 sp 00007f3d295fa0d0 error 5 in libglib-2.0.so.0.4200.1[7f3d33c36000+10c000]
in the last coredump generated we can see this information

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/rtpengine --table=1 -i 79.170.66.74 -u 79.170.66.24:22221 -l 79.170.6'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  magazine_chain_pop_head (magazine_chunks=0x7f3cfc0009b0) at /build/glib2.0-y6934K/glib2.0-2.42.1/./glib/gslice.c:539
539	/build/glib2.0-y6934K/glib2.0-2.42.1/./glib/gslice.c: No such file or directory.
(gdb) bt
#0  magazine_chain_pop_head (magazine_chunks=0x7f3cfc0009b0) at /build/glib2.0-y6934K/glib2.0-2.42.1/./glib/gslice.c:539
#1  thread_memory_magazine1_alloc (tmem=<optimized out>, ix=14) at /build/glib2.0-y6934K/glib2.0-2.42.1/./glib/gslice.c:842
#2  g_slice_alloc (mem_size=mem_size@entry=240) at /build/glib2.0-y6934K/glib2.0-2.42.1/./glib/gslice.c:998
#3  0x00007f3d33c9cbfe in g_slice_alloc0 (mem_size=240) at /build/glib2.0-y6934K/glib2.0-2.42.1/./glib/gslice.c:1032
#4  0x000000000043ebcf in ?? ()
#5  0x000000000043efb8 in ?? ()
#6  0x000000000043846c in ?? ()
#7  0x000000000043a49b in ?? ()
#8  0x000000000040c27e in ?? ()
#9  0x000000000040c61d in ?? ()
#10 0x000000000040c690 in ?? ()
#11 0x00007f3d30bdc064 in start_thread (arg=0x7f3d295fd700) at pthread_create.c:309
#12 0x00007f3d3091162d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) bt full
#0  magazine_chain_pop_head (magazine_chunks=0x7f3cfc0009b0) at /build/glib2.0-y6934K/glib2.0-2.42.1/./glib/gslice.c:539
        chunk = 0xffffffff00000000
#1  thread_memory_magazine1_alloc (tmem=<optimized out>, ix=14) at /build/glib2.0-y6934K/glib2.0-2.42.1/./glib/gslice.c:842
        mag = 0x7f3cfc0009b0
#2  g_slice_alloc (mem_size=mem_size@entry=240) at /build/glib2.0-y6934K/glib2.0-2.42.1/./glib/gslice.c:998
        ix = 14
        tmem = 0x7f3cfc0008c0
        chunk_size = 240
        mem = <optimized out>
#3  0x00007f3d33c9cbfe in g_slice_alloc0 (mem_size=240) at /build/glib2.0-y6934K/glib2.0-2.42.1/./glib/gslice.c:1032
        mem = <optimized out>
#4  0x000000000043ebcf in ?? ()
No symbol table info available.
#5  0x000000000043efb8 in ?? ()
No symbol table info available.
#6  0x000000000043846c in ?? ()
No symbol table info available.
#7  0x000000000043a49b in ?? ()
No symbol table info available.
#8  0x000000000040c27e in ?? ()
No symbol table info available.
#9  0x000000000040c61d in ?? ()
No symbol table info available.
#10 0x000000000040c690 in ?? ()
No symbol table info available.
#11 0x00007f3d30bdc064 in start_thread (arg=0x7f3d295fd700) at pthread_create.c:309
        __res = <optimized out>
        pd = 0x7f3d295fd700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139900663879424, 6471983605857827913, 0, 139900846764128, 0, 139900663879424, -6364913988743021495, 
                -6364857621726053303}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#12 0x00007f3d3091162d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

could you please check if this is a known issue and we are missing something, or we need to compile some library or some other commit? 
If you need any other kind of information please let us know

thanks  alot and regards
david escartin

**Comment by rfuchs** [comment]
Please install the debug symbols package and do the backtrace again

**Comment by descartin** [comment]
hello Richard

i attach you the file
in one of the machines i could not get the dbg packages installed, but on the debian 9 i could so i recompiled the binary with them and ran the gdb again of another core that happened there

[bt_full_550.log](https://github.com/sipwise/rtpengine/files/2001232/bt_full_550.log)

best regards
david

**Comment by descartin** [comment]
yes, i do see

May 13 15:36:09 rtpengine-2 rtpengine[127788]: DEBUG: [6b2b8c15-3510-433b-9d59-f69f90b1435f port 45620]: SSRC hash table exceeded size limit (trying to add 242942510) - deleting SSRC 1549658012
May 13 15:36:09 rtpengine-2 rtpengine[127788]: DEBUG: [6b2b8c15-3510-433b-9d59-f69f90b1435f port 45620]: SSRC hash table exceeded size limit (trying to add 2042065314) - deleting SSRC 777165193
May 13 15:36:09 rtpengine-2 rtpengine[127788]: DEBUG: [6b2b8c15-3510-433b-9d59-f69f90b1435f port 45620]: SSRC hash table exceeded size limit (trying to add 129732400) - deleting SSRC 1565168031
May 13 15:36:09 rtpengine-2 rtpengine[127788]: DEBUG: [6b2b8c15-3510-433b-9d59-f69f90b1435f port 45620]: SSRC hash table exceeded size limit (trying to add 654839985) - deleting SSRC 472103204

they start 5min or so before the crash

regards
david

**Comment by rfuchs** [comment]
I've backported the fix for the suspected culprit on top of mr6.1 and pushed it to a private branch for you to test. See https://github.com/sipwise/rtpengine/tree/rfuchs/gh550

**Comment by descartin** [comment]
hello Richard

ok i recomplied it and i will test, i will let you know

thanks a lot
david

**Comment by rfuchs** [comment]
Merged to mr6.1
