### ISSUE TITLE
is there a specific intent to require epel-release in centos spec file?

### ISSUE THREAD

**Issue by etamme** [sipwise/rtpengine#551]
Hey Richard,

Our systems team let me know that the spec file for rtpengine centos rpm builds is pulling in epel-release for the dkms module

>Requires(post): epel-release dkms
>Requires(preun): epel-release dkms

Is there a specific intent in doing this?  We maintain our own repos for our production services and this breaks our consistency.  I'd like to remove it, but wanted to know what the intent was before doing anything.

**Comment by rfuchs** [comment]
I have no knowledge of anything RedHat or CentOS specific. All the RPM stuff was contributed by 3rd parties. Feel free to send a pull request if you have any improvements. The line you mention comes from #19 by @mtryfoss

**Comment by etamme** [comment]
Thanks Richard
