### ISSUE TITLE
How to use forward-to in recording-daemon?

### ISSUE THREAD

**Issue by Destreyf** [sipwise/rtpengine#556]
I have been trying to figure out how to leverage the 'forward-to' property in the recording daemon, no matter how i setup the unix socket file (socat,netcat-openbsd,python) i keep getting an error "Protocol wrong type for socket" and upon answering the call or hanging up, it actually crashes the recording daemon entirely.

here's a copy of the backtrace that happens, although i don't think it'll be too helpful

https://pastebin.com/raw/hMhvHDg5

it also looks like (from looking at the code) that free can get called twice in the error definition of the forward.c file.

**Comment by rfuchs** [comment]
On Linux, the code calls for a Unix socket of type `SOCK_SEQPACKET`. Most (all?) normal tools will create a normal datagram socket (`SOCK_DGRAM`) instead. Check the `unix(7)` man page for details.

**Comment by rfuchs** [comment]
The segfault seems to be happen if both file output and forwarding is enabled at the same time. I'll push a fix for that use case shortly.

**Comment by pkuzak** [comment]
See also #535. Maybe the discussion there can help you.

**Comment by Destreyf** [comment]
@rfuchs Are `forward-to` and `output-dir` mutually exclusive?  The reason i was trying to use the `forward-to` is that i wanted to know when the recording finished in order to push it upto S3.

**Comment by rfuchs** [comment]
They are right now, but that's a bug. Like I said, fix is coming shortly.

You can tell that a recording is finished by enabling the DB storage (either just for the metadata or for the entire recordings), or by monitoring for the file close event using inotify.
