### ISSUE TITLE
general protection ip:42bcc3 sp:7fb02d91a040 error:0 in rtpengine[400000+59000]

### ISSUE THREAD

**Issue by denislemire** [sipwise/rtpengine#558]
Experiencing a crash issue, dumped some info below, let me know if there's anything else I can provide too assist in debugging.

Syslog:

May 22 20:08:29 rtpeng02 rtpengine[6574]: INFO: [086e03e3269076086f8017d204b3a614@67.223.107.69:5060]: Received command 'answer' from 206.80.250.84:45914
May 22 20:08:29 rtpeng02 rtpengine[6574]: INFO: [086e03e3269076086f8017d204b3a614@67.223.107.69:5060]: answer time = 0.000063 sec
May 22 20:08:29 rtpeng02 rtpengine[6574]: INFO: [086e03e3269076086f8017d204b3a614@67.223.107.69:5060]: Replying to 'answer' from 206.80.250.84:45914
May 22 20:08:29 rtpeng02 rtpengine[6574]: INFO: [09d03e5f4364a963532a204e44d37852@67.223.107.69:5060]: Received command 'answer' from 206.80.250.84:45914
May 22 20:08:29 rtpeng02 rtpengine[6574]: INFO: [09d03e5f4364a963532a204e44d37852@67.223.107.69:5060]: answer time = 0.000051 sec
May 22 20:08:29 rtpeng02 rtpengine[6574]: INFO: [09d03e5f4364a963532a204e44d37852@67.223.107.69:5060]: Replying to 'answer' from 206.80.250.84:45914
May 22 20:08:29 rtpeng02 rtpengine[6574]: INFO: [086e03e3269076086f8017d204b3a614@67.223.107.69:5060]: Received command 'answer' from 206.80.250.84:58491
May 22 20:08:29 rtpeng02 rtpengine[6574]: INFO: [086e03e3269076086f8017d204b3a614@67.223.107.69:5060]: answer time = 0.000063 sec
May 22 20:08:29 rtpeng02 rtpengine[6574]: INFO: [086e03e3269076086f8017d204b3a614@67.223.107.69:5060]: Replying to 'answer' from 206.80.250.84:58491
May 22 20:08:29 rtpeng02 rtpengine[6574]: INFO: [086e03e3269076086f8017d204b3a614@67.223.107.69:5060]: Received command 'offer' from 206.80.250.84:53280
May 22 20:08:29 rtpeng02 rtpengine[6574]: INFO: [086e03e3269076086f8017d204b3a614@67.223.107.69:5060]: offer time = 0.000080 sec
May 22 20:08:29 rtpeng02 rtpengine[6574]: INFO: [086e03e3269076086f8017d204b3a614@67.223.107.69:5060]: Replying to 'offer' from 206.80.250.84:53280
May 22 20:08:29 rtpeng02 rtpengine[6574]: INFO: [086e03e3269076086f8017d204b3a614@67.223.107.69:5060]: Received command 'offer' from 206.80.250.84:40202
May 22 20:08:29 rtpeng02 rtpengine[6574]: INFO: [086e03e3269076086f8017d204b3a614@67.223.107.69:5060]: offer time = 0.000036 sec
May 22 20:08:29 rtpeng02 rtpengine[6574]: INFO: [086e03e3269076086f8017d204b3a614@67.223.107.69:5060]: Replying to 'offer' from 206.80.250.84:40202
May 22 20:08:29 rtpeng02 rtpengine[6574]: INFO: [086e03e3269076086f8017d204b3a614@67.223.107.69:5060]: Received command 'answer' from 206.80.250.84:45914
May 22 20:08:29 rtpeng02 rtpengine[6574]: INFO: [086e03e3269076086f8017d204b3a614@67.223.107.69:5060]: answer time = 0.000044 sec
May 22 20:08:29 rtpeng02 rtpengine[6574]: INFO: [086e03e3269076086f8017d204b3a614@67.223.107.69:5060]: Replying to 'answer' from 206.80.250.84:45914
May 22 20:08:29 rtpeng02 rtpengine[6574]: INFO: [E1999B6F@209.197.130.80]: Received command 'delete' from 206.80.250.84:59218
May 22 20:08:29 rtpeng02 kernel: [5560704.593767] traps: rtpengine[6583] general protection ip:42bcc3 sp:7fb02d91a040 error:0 in rtpengine[400000+59000]

SDP from most recent RE-INVITE:

v=0
o=amphion 1289067022 1289067027 IN IP4 0.0.0.0
s=XCSBC1
c=IN IP4 0.0.0.0
t=0 0
m=audio 23872 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=silenceSupp:off - - - -
a=ptime:20
a=sendrecv

Backtrace, not sure if useful without debugging symbols:

#0  0x000000000042bcc3 in ?? ()
No symbol table info available.
#1  0x000000000042d852 in ?? ()
No symbol table info available.
#2  0x00000000004133bd in ?? ()
No symbol table info available.
#3  0x000000000042d2ec in ?? ()
No symbol table info available.
#4  0x000000000041dbbe in ?? ()
No symbol table info available.
#5  0x000000000041cb63 in ?? ()
No symbol table info available.
#6  0x000000000040c44e in ?? ()
No symbol table info available.
#7  0x000000000040c7ed in ?? ()
No symbol table info available.
#8  0x000000000040c860 in ?? ()
No symbol table info available.
#9  0x00007fb036ba16ba in start_thread (arg=0x7fb02d92b700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fb02d92b700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140394655561472, 6738145253533857274, 0, 140724297486735, 140394655562176, 0, -6709545076586007046, -6709556281828133382}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0},
            data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#10 0x00007fb0368d741d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

**Comment by denislemire** [comment]
Version is mr6.1.1.1 / 0b72381 - packages were built using dpkg-buildpackage but no dbgsym package was generated. Is there a build step I missed to generate the dbgsym package?

**Comment by rfuchs** [comment]
See issue #459 about the dbgsym package

**Comment by denislemire** [comment]
Building on 16.04 with DH_BUILD_DDEBS=1 with does get me dbgsym package.

Not sure the symbols would perfectly match the version I built previously though. Might be best for me to upgrade to the 6.2 branch (with debugging symbols installed) and see if the issue recurs there.

**Comment by rfuchs** [comment]
Yeah the dbgsym package would have to be from the same build as the one that dumped core.

**Comment by denislemire** [comment]
Based on that, not sure we can do anything more. I can submit an new issue if I experience a similar crash on the newer version. Next time around I'll have proper debugging symbols to generate a useful backtrace.

Thanks for the efforts, regardless!
