### ISSUE TITLE
Wrong "Average call duration"

### ISSUE THREAD

**Issue by kertor** [sipwise/rtpengine#559]
Hello! I see wrong statistics in rtpengine-ctl:
```
rtpengine-ctl -port 9900 list totals
Average call duration                           :-191741.-18032
```

root@media:~# rtpengine -v
Version: 6.3.0.0+0~mr6.3.0.4 git-master-79807a9

Thanks!

**Comment by pkuzak** [comment]
Can you reproduce this? A somehow related issue has been reported here a few weeks ago (#543) and a commit has been pushed (db58aa80d0b1ca942cf290099058ae5f458da4ce). Could you maybe try with that version as well? Do you use Graphite? Can you maybe provide a debug log?

**Comment by rsmck** [comment]
Should the average call duration be in seconds? I get sensible numbers but they are way higher than the actual call durations.
