### ISSUE TITLE
Transcoding G722, one direction garbled Voice

### ISSUE THREAD

**Issue by adil-mafzool** [sipwise/rtpengine#560]
Hi
I am experiencing the issue when transcoding using RTP Engine between RTP G711a to RTP G722 and vice versa.

(Polycom)IP phone <---> B2BUA<---> Kamailio <---> IP phone (SPA508G)
RTP G711A <---> RTP Engine version (Version: 6.3.0.0+0~mr6.3.0.0 ) git-master-9c3edee  <---> RTP G722

RTP G722 to RTP G711A is working fine .
RTP G711A to RTP G722 is garbled

Please find the attached garbled_722_audio.log and advice what is making it not work properly

The issue doesnt occur on the version 6.2.0.0+0~mr6.2.0.0 git-master-ce44eaf

[Garbled722.zip](https://github.com/sipwise/rtpengine/files/2035186/Garbled722.zip)

**Comment by rfuchs** [comment]
Can't seem to reproduce this. Can you make a pcap of this including the RTP?

**Comment by adil-mafzool** [comment]
Please find the pcap attached for the following call: -
(Polycom)IP phone <---> B2BUA<---> Kamailio <---> IP phone (SPA508G)
RTP G711A <---> RTP Engine version (Version: 6.3.0.0+0~mr6.3.0.0 ) git-master-9c3edee <---> RTP G722

RTP G722 to RTP G711A is working fine .
RTP G711A to RTP G722 is garbled

It looks the timestamp is being incremented with 320 instead of 160 for 20ms.

[Garbled722Call.zip](https://github.com/sipwise/rtpengine/files/2048412/Garbled722Call.zip)

**Comment by adil-mafzool** [comment]
Thanks! Its working OK  now!
