### ISSUE TITLE
rtpengine ignores anonymous STUN binding requests

### ISSUE THREAD

**Issue by billsimon** [sipwise/rtpengine#561]
The scenario is this: A phone initiates a call without ICE, but rtpengine is set to ICE=force on offer and answer. As a result, the answer back to the phone has ice candidates but no ice-ufrag/password attributes.

The phone proceeds to interleave anonymous STUN binding requests in the RTP stream but rtpengine ignores them.

Without binding credentials should it not accept and respond to the anonymous STUN requests?

**Comment by billsimon** [comment]
I have worked around this with scripting. It would be a nice feature to add to rtpengine - don't answer back ICE to the client who didn't offer it. Closing ticket.

**Comment by rfuchs** [comment]
I agree. Will open an internal dev ticket for this.

**Comment by billsimon** [comment]
Thanks rfuchs, I appreciate that.
