### ISSUE TITLE
dpkg-buildpackage linking errors on Ubuntu 16.04 and 18.04

### ISSUE THREAD

**Issue by denislemire** [sipwise/rtpengine#563]
Trying to build latest version mr6.2.1.2 on Ubuntu 16.04 or Ubuntu 18.04 and get linking errors:

![image](https://user-images.githubusercontent.com/139257/40622586-9833e840-625f-11e8-93c9-c4ab062154c6.png)

All dependencies are satisfied via dpkg-checkbuilddeps...

mr6.1.2.1 builds without issue.

**Comment by rfuchs** [comment]
Can't reproduce this on Ubuntu. Make sure you have a clean build environment (`git clean -x -d -f`) or a fresh checkout.

**Comment by denislemire** [comment]
Weird... I reproduced this on a clean system with a clean checkout... Occurred in more than one environment... I wonder what's different on your system...

**Comment by denislemire** [comment]
Oh! I was using the release tarballs from github, I will try with a clone.

**Comment by rfuchs** [comment]
Actually I believe this is fixed by 85afd74f which isn't present in 6.2.1

**Comment by denislemire** [comment]
OK - I'll build the latest from the master branch and confirm success shortly.

**Comment by rfuchs** [comment]
You can also go with mr6.2 as it includes some fixes (including this one) which aren't in mr6.2.1 but will be in mr6.2.2

**Comment by denislemire** [comment]
I have confirmed the git mr6.2 branch builds without this issue.
