### ISSUE TITLE
trap divide error crash for rtpengine 6.1.3

### ISSUE THREAD

**Issue by descartin** [sipwise/rtpengine#564]
Hello all 

coming from issue 550 (which i think was solved by your commit Richard), i compiled the last version of rtpentine 6.1.3 
Version: 6.1.3.0+0~mr6.1.3.0 git-v.6.1-384c6a0

but when i have high load traffic and the log level at DEBUG level, i experience this type of crashes
May 28 14:38:35 mad-dedalus-ms-4 kernel: [432840.016049] traps: rtpengine[2161] trap divide error ip:561fefabe014 sp:7f0f68fe7fc0 error:0
May 28 14:38:35 mad-dedalus-ms-4 kernel: [432840.016057]  in rtpengine[561fefa7b000+5c000]
May 28 15:44:01 mad-dedalus-ms-4 kernel: [436765.591349] traps: rtpengine[31672] trap divide error ip:56505f1b9014 sp:7f6594854fc0 error:0
May 28 15:44:01 mad-dedalus-ms-4 kernel: [436765.591357]  in rtpengine[56505f176000+5c000]

and the core is
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/rtpengine --table=1 -i 79.170.65.77 -u 79.170.64.182:22221 -l 79.170.'.
Program terminated with signal SIGFPE, Arithmetic exception.
#0  0x000056505f1b9014 in ?? ()
[Current thread is 1 (Thread 0x7f6594866700 (LWP 31672))]
(gdb) bt
#0  0x000056505f1b9014 in  ()
#1  0x000056505f18a637 in  ()
#2  0x000056505f1a4635 in  ()
#3  0x000056505f196e0b in  ()
#4  0x000056505f196122 in  ()
#5  0x000056505f185248 in  ()
#6  0x000056505f1855ed in  ()
#7  0x000056505f185664 in  ()
#8  0x00007f659b7ef494 in start_thread (arg=0x7f6594866700) at pthread_create.c:333
#9  0x00007f659b531acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
(gdb) bt full
#0  0x000056505f1b9014 in  ()
#1  0x000056505f18a637 in  ()
#2  0x000056505f1a4635 in  ()
#3  0x000056505f196e0b in  ()
#4  0x000056505f196122 in  ()
#5  0x000056505f185248 in  ()
#6  0x000056505f1855ed in  ()
#7  0x000056505f185664 in  ()
#8  0x00007f659b7ef494 in start_thread (arg=0x7f6594866700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f6594866700
        now = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {140074260260608, 1276401337424314090, 0, 140731230927823, 0, 140074437427264, -1189626173722558742, -1189646579767148822}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#9  0x00007f659b531acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
(gdb) 

unfortunately i dont have the debug symbols compiled. So if you can give me any guidance, let me know if i should recompile them and try to reproduce the issue?

thanks a lot and regards
david

**Comment by rfuchs** [comment]
Debug symbols are available if the dbgsym package is installed. If this package doesn't get built (on Ubuntu) see issue #459

**Comment by descartin** [comment]
Hello Richard.

We are using debian9 and i think i have them generated. I will recompile. Compiling those debug packets can affect the performance on high traffic load?

And do you recommend ubuntu better than debian by the way? or is it fine with using debian?

Best regards and thanks
David

**Comment by rfuchs** [comment]
You don't need to recompile if you have the debug package available. Just install it. Having debug symbols available or installed has zero impact on performance. And I recommend Debian over Ubuntu since Debian is what we develop for.

I think I have the fix for this issue, stay tuned.
