### ISSUE TITLE
RTPEngine not keeping track of offered sessions

### ISSUE THREAD

**Issue by petekelly** [sipwise/rtpengine#567]
We have been running RTPEngine with no issues for a number of months, however yesterday we noticed strange behaviour for some calls. This is what is happening:

1) rtpengine_offer is called (from Kamailio), rtpengine receives the offer and duly rewrites the SDP and hands it back to Kamailio. However rtpengine is then *not* recording this in the logs at all - normally we see a "NOTICE - Creating new call" type log entry. This is not happening.

2) when rtpengine_answer is called, rtpengine is failing to rewrite the SDP, and produces an error in its logs with the messsage "Unknown call-id"

I've done a lot of investigation and it seems interesting that for the offer RTPEngine is rewriting the SDP correctly but is not recording this in the syslog - does anyone have any knowledge of what conditions of environment might cause this behaviour, or possibly point us to the relevant piece of source code where this is happening?

We are running version 5.0.0.0

Any help, advice or pointers would be appreciated.

**Comment by petekelly** [comment]
I have just checked into a specific example, where the port in question that was allocated is 15520 - I then managed to find a call which was established 4 seconds earlier which was also given the same port of 15520 (the call was still ongoing).

I'm sure this isn't normal behaviour, rtpengine should not be reallocating the same port to calls that it has already allocated?

**Comment by rfuchs** [comment]
Are you sure you don't have two instances of rtpengine running or something like that?

Please post your config (both rtpengine and Kamailio module config) and perhaps a concrete example from the logs. Running rtpengine with log level 7 would be the best option. Also try using Wireshark to capture the control protocol between Kamailio and rtpengine when this is happening.

**Comment by petekelly** [comment]
Thanks for that, I have all the logs and config and wireshark traces, I will need to anonymise them slightly, but I will get them posted later.

In the  meantime, there are actually multiple rtpengine instances running, but each has its own distinct RTP port range, and distinct control port.

The examples I'm looking at are where the same rtpengine instance was hit by the subsequent calls.

**Comment by o1bbridges** [comment]
Was this ever followed up?  I appear to have run into a similar issue on git-master-4eb80da
