### ISSUE TITLE
Interop Feature Request: Ignore crypto lifetime flag

### ISSUE THREAD

**Issue by nakchak** [sipwise/rtpengine#57]
Would it be possible to add the functionality to disable the validation of the crypto lifetime attribute if present?

In order to get various phones to work (notably the grandstream 2130) i have had to comment out the error checking between lines 485 - 500 of sdp.c, as the devices in question (incorrectly in my opinion) force the crypto lifetime attribute

After a quite puzzling debugging session, where no errors were reported in the syslog output of the grandstream phone where the call was dropped without reason when the called party answered,  i finally saw that the solution was staring me in the face in the rtpengine logs, `Jan  8 13:18:23 kambox rtpengine[16719]: Failed to parse a=crypto attribute: invalid key lifetime` 

This is the same as this asterisk issue: https://issues.asterisk.org/jira/browse/ASTERISK-17899
Grandstream even have an FAQ entry advising you to patch your environment around their stubbornness to make this configurable on the phone... http://www.grandstream.com/support/faq/gxp-enterprise-phone-series#25 

Although i don't like disabling validations, i think for the sake of interop with less standards compliant devices and systems it would be beneficial if this behavior could be switched off if required, ideally as a flag in the kamailio module/control protocol or as a make flag.

**Comment by rfuchs** [comment]
Do you have an example of what such a crypto attribute looks like?

**Comment by nakchak** [comment]
Hi Richard

I should have added the preceeding lines in the log to the original post

`Got valid command from 127.0.0.1:48814: offer - { "sdp": "v=0#015#012o=testextension3 8000 8000 IN IP4 192.168.1.105#015#012s=SIP Call#015#012c=IN IP4 192.168.1.105#015#012t=0 0#015#012m=audio 50480 RTP/SAVP 18 8 0 9 2 101#015#012a=sendrecv#015#012a=rtpmap:18 G729/8000#015#012a=ptime:20#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:9 G722/8000#015#012a=rtpmap:2 G726-32/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-15#015#012a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:WvrRHbu90YH7c/7rduJ7JR4362HF/4ueb4Fhktsw|2^32#015#012a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:wjUqk1PlUSRnTJdlNw1HsjNl6R7Hrh1STYzTrh6u|2^32#015#012", "direction": [ "external", "internal" ], "replace": [ "origin", "session-connection" ], "transport-protocol": "RTP/AVP", "call-id": "304278042-24554-36@BJC.BGI.B.BAF", "received-from": [ "IP4", "111.111.111.111" ], "from-tag": "2111593418", "command": "offer" }`

specifically i believe its this part: `a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:...|2^32` the 2^32 seems to be failing on the second check  where its compared against `c->crypto_suite->srtp_lifetime` & `c->crypto_suite->srtcp_lifetime`
