### ISSUE TITLE
Issue cloning repository

### ISSUE THREAD

**Issue by ekoome** [sipwise/rtpengine#576]
I'm getting the following error when cloning the repository:
git clone https://github.com/sipwise/rtpengine
Cloning into 'rtpengine'...
remote: Counting objects: 12580, done.
remote: Total 12580 (delta 0), reused 0 (delta 0), pack-reused 12580
Receiving objects: 100% (12580/12580), 4.79 MiB | 462.00 KiB/s, done.
Resolving deltas: 100% (9424/9424), done.
error: unable to create file daemon/aux.c: No such file or directory
error: unable to create file include/aux.h: No such file or directory
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by linuxmaniac** [comment]
No problem here
```
$ git clone https://github.com/sipwise/rtpengine.git
Cloning into 'rtpengine'...
remote: Counting objects: 12580, done.
remote: Total 12580 (delta 0), reused 0 (delta 0), pack-reused 12580
Receiving objects: 100% (12580/12580), 4.79 MiB | 2.36 MiB/s, done.
Resolving deltas: 100% (9424/9424), done.
```

**Comment by taurus-forever** [comment]
Windows... JFYI, https://github.com/sipwise/rtpengine/issues/376

**Comment by rfuchs** [comment]
Don't clone to a Windows machine.
