### ISSUE TITLE
[Bug] rtpengine is only forwarding the one crypto suite that it accepted itself.

### ISSUE THREAD

**Issue by netaskd** [sipwise/rtpengine#577]
It would be great to have possibility to disable some cripto suits before negotiating.
Eg. 
I have client on A-side with support AES256 crypto suite:
```
a=crypto:1 AES_CM_256_HMAC_SHA1_80 inline:Qu99l...
a=crypto:2 AES_CM_256_HMAC_SHA1_32 inline:dq9Sq...
a=crypto:3 AES_CM_128_HMAC_SHA1_80 inline:IG0H3...
a=crypto:4 AES_CM_128_HMAC_SHA1_32 inline:bYzK/8...
```
but B-side desn't support AES256 crypto suite and supported AES128 only.
```
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:KS73K...
a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:9xSB7...
```
So, now rtpengine negotiated with AES_CM_256_HMAC_SHA1_80 and negotiation with B-side failed.
I use rtpengine-6.4.0.0-1.el7 and opensips-2.4.1 (x86_64/linux)
rtpengine offer flags: "replace-session-connection replace-origin ICE=remove"

**Comment by rfuchs** [comment]
It shouldn't be necessary to disable any crypto suites. Can you post the full dialogue that shows where exactly it fails?

**Comment by rfuchs** [comment]
Ah I see what's happening. It's only forwarding the one crypto suite that it accepted itself. I'd count that as a bug that needs to be fixed.
