### ISSUE TITLE
metadata ignored unless 'record call' is yes

### ISSUE THREAD

**Issue by davehorton** [sipwise/rtpengine#579]
I am supplying metadata in the ng 'offer' command, but I notice it my metadata is not written to the metadata file unless {'record call': 'yes'} is included in the options.  In fact the metadata file also does not include both SDPs unless this is the case.  

Here is the offer parameters I supply:
```
    call-id: "1000004807199210_Monitor2@10.40.102.21"
    from-tag: "SDs9qu201-gK0c66ca77"
    sdp: "v=0\r\no=- 2311154566 0 IN IP4 10.40.102.21\r\ns=Pactolus Media Server\r\nc=IN IP4 10.40.102.21\r\nt=0 0\r\nm=audio 20022 RTP/AVP 0 101\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:101 telephone-event/8000\r\na=fmtp:101 0-15\r\n"
    ICE: "remove"
    port latching: "yes"
    media handover: "yes"
    replace: [
      "origin",
      "session connection"
    ]
    metadata: "{\"rapidflexSessionId\":\"7.19.Monitor2.9210@10.40.102.21\",\"redact-secs\":0}"
```

I get a response that indicates success:

```
    sdp: "v=0\r\no=- 2311154566 0 IN IP4 10.40.102.111\r\ns=Pactolus Media Server\r\nc=IN IP4 10.40.102.111\r\nt=0 0\r\nm=audio 40656 RTP/AVP 0 101\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:101 telephone-event/8000\r\na=fmtp:101 0-15\r\na=sendrecv\r\na=rtcp:40657\r\n"
    result: "ok"
```

I later call 'answer' and get a successful response.  Immediately after 'answer' I send a 'start recording' command, and that completes successfully as well.

However, at the end of my call, the metadata file is missing both SDPs as well as the custom metadata I supplied:

```
cat /tmp/metadata/rtpengine-meta-1000004807199210_Monitor2%4010.40.102.21-74569b2c073e7c87.txt
/tmp/pcaps/1000004807199210_Monitor2%4010.40.102.21-74569b2c073e7c87.pcap


Timestamp terminated ms(first monologue): 1531836272049.036

call start time: 2018-07-17T10:04:19
call end time: 2018-07-17T10:04:32
```
No metadata, no SDPs.

If I include 'record call': 'yes' on my initial offer (and therefore don't later call 'start recording') I get the expected file content -- i.e. the two SDPs plus my metadata.

Is this a known bug?  Am I doing something wrong?

**Comment by davehorton** [comment]
any comment on this?

**Comment by rfuchs** [comment]
It's a legitimate concern. I'll fix it.

**Comment by rfuchs** [comment]
That being said, you'll never see SDPs that were handled before recording was started. They're not saved internally just in case somebody starts recording afterwards.

**Comment by davehorton** [comment]
ok, for my use case that is fine.  I just need my custom metadata that I provided with the offer.

**Comment by davehorton** [comment]
Having said that, I can certainly see use cases where the SDPs might be useful / necessary.  Since you are able to start recording at any point in a call, it is possible that certain post-processing actions could benefit from and/or require knowledge of the SDPs exchanged.  But for my needs right now I can do without that

**Comment by davehorton** [comment]
Hi there, for my planning purposes, would it be possible to give me a sense of when a change might be committed for this issue?

**Comment by rfuchs** [comment]
Probably in a week or two

**Comment by davehorton** [comment]
just checking back on this.....any update?

**Comment by davehorton** [comment]
since I need this, perhaps it would make sense for me to attempt a fix. Would you be open to a PR on this?  It seems like the simplest solution would be to move the metadata string from the recording stuct to the call struct..

**Comment by rfuchs** [comment]
The patch is currently in review and will be merged later today.
