### ISSUE TITLE
Log file of RTPEngine

### ISSUE THREAD

**Issue by VuDn5** [sipwise/rtpengine#580]
Dear All, 
First, for give me about my stupid  question.. i run rtpengine follow params:  xx is my ip
`
/sbin/rtpengine -p /var/run/rtpengine.pid -i eth0/xx.xx.xx.xx -n xx.xxxxx.xx:60000 -c 127.0.0.1:60001 -m xx000 -M xx000 -E -L 7     
`
But i don't know where are log file of rtpengine save,   please help me!  thank!

**Comment by rfuchs** [comment]
With the `-E` option, logs are written to stderr only. If you want to save them somewhere, redirect stderr to a file or run rtpengine from something that handles stderr output for you (for example systemd).

**Comment by VuDn5** [comment]
@rfuchs   
thanks for your help!  With the command above:   how i can change it to save log file?  
You can give me more examples basic?    i must write options like that?

**Comment by rfuchs** [comment]
If you omit the `-E` option, it will send the logs to syslog like any other daemon.
Or redirect to a file, for example by appending `2> output-file'

**Comment by shekhshadul** [comment]
I have same question above can you tell me how to separate rtpengine log from system logs
