### ISSUE TITLE
Correspondence between UUID and SSRC

### ISSUE THREAD

**Issue by DavidNemeskey** [sipwise/rtpengine#582]
I am processing the output of recording-daemon, and I was wondering if there was any correspondence between the UUIDs received in the first message and the SSRCs of the RTP packages in the rest.

If I understand correctly, the UUIDs are the caller/callee identifiers in SIP. SSRCs play the same role in RTP packages. But is there a way to find out the mapping from the output? Specifically, is it always true that the SSRC in the first message corresponds to the first UUID in the call id?

**Comment by rfuchs** [comment]
Sorry, but what UUIDs? :)

**Comment by DavidNemeskey** [comment]
The first message I receive from the recording-daemon is the UUID pair of the connection, e.g.
`uuid:XX-X-X-XX|uuid:YY-Y-Y-YY|`. I guess that's the SIP call id? The first UUID should be the caller's, the second the callee's. That's the content of the `METADATA` section in the metafile, anyway.

**Comment by rfuchs** [comment]
The metadata is generated and sent by the SIP proxy, not by rtpengine.

Is this a Sipwise NGCP/C5 system you're working on?

**Comment by DavidNemeskey** [comment]
Very good question, I don't know ATM; I'll try to find out. I guess the question boils down to this: in case of a SIP call, is the first RTP package sent by the recording-daemon guaranteed to come from the caller?

**Comment by rfuchs** [comment]
No, not at all. But when writing to individual output files, the SSRC of the RTP stream is encoded into the filename. Not sure if that helps your issue.

**Comment by DavidNemeskey** [comment]
Not really: I can extract the SSRC from the RTP packets themselves; that's
not the problem. The problem is finding out which party started the call.
Is it possible that this information is not provided by RTP?

**Comment by DavidNemeskey** [comment]
I see. Does this mean that the SSRC also comes from the SIP proxy, and not from inside rtpengine?

**Comment by rfuchs** [comment]
The SSRC is a random value chosen by each participating RTP source. It is not normally related to anything you see on the SIP side.

**Comment by DavidNemeskey** [comment]
Does this mean that there is no way whatsoever to know who the caller is? If the SSRC is chosen at random in rtpengine, and it is the only identifier I see in the RTP stream*, it doesn't matter how I set up the SIP proxy, because there is no way to match the SSRC with anything in the metadata.

Or did I miss something? Identifying the caller seems such an obvious feature, I find it hard to believe it is unavailable.

*Please correct me if I am wrong. I really hope I am.

**Comment by rfuchs** [comment]
Correct, you can't tell from the SSRC. However you can tell from the media addresses. There are different ways to get to this information, depending on which recording mechanism you're using. Both rtpengine and the recording daemon know which UA is using which media addresses, and from this you can tell which media stream belongs to which UA.

**Comment by DavidNemeskey** [comment]
@rfuchs Could you elaborate a bit on this? ATM we are using the recording daemon. Thanks!

**Comment by rfuchs** [comment]
Sure, but the recording daemon supports multiple output mechanisms. Are you writing audio files or using the `forward` mechanism?

**Comment by DavidNemeskey** [comment]
The latter, although we are not adamant about this choice.

**Comment by rfuchs** [comment]
In that case, you need to inspect the packet IP and UDP headers and correlate them with the SDP bodies found in the metafile. The metafile will also tell you the SIP from/to tag corresponding to each UA (in the `TAG` chunk). If you want to further correlate, you need to instruct your SIP proxy to keep track of which SIP from/to tag corresponds to who (e.g. caller, callee, etc). You can put that info into the `metadata=` or log it elsewhere.

So for example:
In the SIP proxy: from-tag `46wergsd` = caller UA.
In the metafile: `TAG 2` = `46wergsd`.
Followed by: SDP bodies (before and after rewrite) for `TAG 2` (UA `46wergsd`).
SDP bodies contains the IPs and ports. Match those against the RTP packets.

**Comment by DavidNemeskey** [comment]
@rfuchs Thanks, we are investigating this route. Just to be clear: in order to use this solution, we will need to modify the rtpengine code? Or is it enough to read the metafile (but then how do we find the metafile that corresponds to the call)?

**Comment by rfuchs** [comment]
You don't need to modify the code. The name of the metafile has the SIP call ID in it.

**Comment by DavidNemeskey** [comment]
OK, thanks! Once we get it working, I'll close the issue.

**Comment by DavidNemeskey** [comment]
@rfuchs Could you perhaps explain in a few lines why and how the commit solves this issue? Does it change how the caller can be identified? Thanks!

**Comment by rfuchs** [comment]
It lets you use the `label=` feature (for example `rtpengine_offer("label=caller")`) and then that label will be saved to the recording database along with the other stream infos.
