### ISSUE TITLE
Switching from IPv4 to IPv6 `advertised_endpoint` is not updated.

### ISSUE THREAD

**Issue by egreenmachine** [sipwise/rtpengine#584]
In [`media_packet_address_check`](https://github.com/sipwise/rtpengine/blob/master/daemon/media_socket.c#L1417) there is the ability to update the destination address which could change from IPv4 to IPv6. When this happens, the `advertised_endpoint` or src address of where the packets are coming from is not updated from IPv4 to IPv6. This causes the pcap for recordings to have corrupted src headers for packets. 

It appears that `advertised_endpoint` is only set in [`__fill_stream`](https://github.com/sipwise/rtpengine/blob/master/daemon/call.c#L941) when `__init_streams` is called. 

We are seeing this happen on calls to/from Chrome in a mixed IPv4/6 environment. Looking at the raw data in the PCAP confirms that the src address that is written is the IPv4 address, even though the headers indicate IPv6 and the packet traversed IPv6. The destination information is all correct. It looks as if Chrome is sending a single RTP packet via IPv4 then switching to IPv6. The pcap information for the single IPv4 packet is correct.

**Comment by egreenmachine** [comment]
```

**Comment by egreenmachine** [comment]
```
--- a/daemon/media_socket.c
+++ b/daemon/media_socket.c
@@ -1499,6 +1499,7 @@ update_addr:
        if (phc->mp.stream->selected_sfd && phc->mp.sfd != phc->mp.stream->selected_sfd) {
                ilog(LOG_INFO, "Switching local interface to %s", endpoint_print_buf(&phc->mp.sfd->socket.local));
                phc->mp.stream->selected_sfd = phc->mp.sfd;
+               phc->mp.stream->advertised_endpoint = phc->mp.fsin;
                phc->unkernelize = 1;
                phc->update = 1;
        }
```
This diff gets me closer. With this I just end up with 2 extra bytes in the IPv6 headers written to the PCAP.

**Comment by rfuchs** [comment]
I think this is the wrong solution to the problem. The `advertised_endpoint` is the endpoint advertised by the UA (in the SDP). It should never be updated except through another received SDP.

**Comment by egreenmachine** [comment]
I see. Let me see what is available in the recording code if we can use something else for the IP headers instead of `advertised_endpoint`. That being said, `advertised_endpoint` does not appear to be completely accurate for `ICE` endpoints.

**Comment by egreenmachine** [comment]
@rfuchs thoughts about this diff? This appears to be getting me the correct information for IPv6 and IPv4 and does not rely on the `advertised_endpoint`

```
--- a/daemon/recording.c
+++ b/daemon/recording.c
@@ -477,7 +477,7 @@ static void pcap_recording_finish_file(struct recording *recording) {

 // "out" must be at least inp->len + MAX_PACKET_HEADER_LEN bytes
 static unsigned int fake_ip_header(unsigned char *out, struct packet_stream *stream, const str *inp) {
-       endpoint_t *src_endpoint = &stream->advertised_endpoint;
+       endpoint_t *src_endpoint = &stream->selected_sfd->stream->endpoint;
        endpoint_t *dst_endpoint = &stream->selected_sfd->socket.local;

        unsigned int hdr_len =
```

Additionally, the 2 extra bytes i mentioned earlier appears to be the checksum for IPv6. I think that these have to be in there, but putting all 0's is causing Wireshark to complain about the packet. I do not think this is an issue for our needs though, as we can simply ignore the checksum.

**Comment by rfuchs** [comment]
`stream->selected_sfd->stream->endpoint` is equivalent to just `stream->endpoint`

`stream->endpoint` is the *destination* address of *outgoing* packets towards that stream. In case of asynchronous RTP, it doesn't necessarily match the source address of incoming packets.

I believe the correct solution here is to change the signature of the `dump_packet` functions and pass the actual source address to them as it was received. I think a good way to do this is to use the `media_packet` struct, as it includes all the necessary info, so that would give you (in `struct recording_method`) `void (*dump_packet)(struct media_packet *, const str *s);`

**Comment by egreenmachine** [comment]
Yeah. I did realize that `stream->endpoint` is the same after posting it. In my testing it appears that `stream->endpoint` is pointing to the source of the packet. See the screenshot below.

![screen shot 2018-08-02 at 11 01 17 am](https://user-images.githubusercontent.com/1035982/43592393-74b0a5d0-9643-11e8-92f6-b09d67982a2d.png)

**Comment by egreenmachine** [comment]
Sorry. I missed the part about async RTP in my first read. I trust that you are correct, I am just not sure how to test that. Either way, I have a branch that is close to what you recommended. Let me go down that path and push it up to Github for you to review. Thanks for the advice.
