### ISSUE TITLE
RTPEngine supports only AES_CM_128_HMAC_SHA1_80???

### ISSUE THREAD

**Issue by joeygo** [sipwise/rtpengine#588]
Hello

RTPEngine negotiates only AES_CM_128_HMAC_SHA1_80 although both of my clients supports 256 as well.

Client A send INVITE with the following crypto suites:
a=crypto:1 AES_CM_256_HMAC_SHA1_80
a=crypto:2 AES_CM_256_HMAC_SHA1_32
a=crypto:3 AES_CM_128_HMAC_SHA1_80
a=crypto:4 AES_CM_128_HMAC_SHA1_32

But client B gets the INVITE only with a=crypto:3 AES_CM_128_HMAC_SHA1_80.

I’m using the latest version of RTPEngine.

How can I use AES 256 with RTPEngine?

Thanks,

Joey.

**Comment by joeygo** [comment]
Just saw the bug: rtpengine is only forwarding the one crypto suite that it accepted itself.

would this be fixed soon?

**Comment by rfuchs** [comment]
Yes, closing in favour of #577
