### ISSUE TITLE
WebRTC One way video Issue

### ISSUE THREAD

**Issue by adil-mafzool** [sipwise/rtpengine#589]
Encountering one-way video where webrtc client caller never sees the webrtc client callee but webrtc client callee can see the webrtc client caller.

The following scenario is working: -
Web RTC Caller(441334961001) ---RTP/SAVPF ---> Kamailio Proxy with RTPEngine ---RTP/SAVPF--->B2BUA ---RTP/SAVPF--->Kamailio Proxy with RTPEngine ---RTP/SAVPF--->Web RTC Callee(441214968009)

But the following scenario doesn't: -
Web RTC Caller(441334961001) ---RTP/SAVPF ---> Kamailio Proxy with RTPEngine ---RTP/AVP--->B2BUA ---RTP/AVP--->Kamailio Proxy with RTPEngine ---RTP/SAVPF---> Web RTC Callee(441214968009)
                                                                                            
RTPEngine
Version: 6.3.2.0+0~mr6.3.2.0 git-mr6.3-de223d9

Please find the attached and advice what is making it not work properly

[oneway_video.log](https://github.com/sipwise/rtpengine/files/2265914/oneway_video.log)

**Comment by jsingh4** [comment]
I am having the same issue i.e. the video not working and only starts from one end and freezes soon after. . . 

Any recommended Fixes/Workarounds?

**Comment by rfuchs** [comment]
This might be due to the lack of RTCP feedback messages coming from the non-WebRTC client. At this point, the only workaround is to make sure it supports and uses RTCP feedback messages (RTP/AVPF profile instead of RTP/AVP).

**Comment by jsingh4** [comment]
Thanks @rfuchs, that seems to have fix the issue for us.

**Comment by adil-mafzool** [comment]
@rfuchs the issue is that the 3rd party B2BUA uses rtpproxy which doesn't particular like AVPF pass through which is becoming show stopper. 
Will it be possible to force RTCP feedback messages with pretending AVP?
Or add a new flag rtcp-fb=true or false to enable RTCP feedback messages with AVP.
Is there specific code change you can suggest?

**Comment by rfuchs** [comment]
The only solution would be to have rtpengine generate feedback messages, which is not a trivial feature to implement and currently out of scope for us.

**Comment by adil-mafzool** [comment]
@rfuchs can you keep this issue open please?
