### ISSUE TITLE
problem with init script

### ISSUE THREAD

**Issue by johandeclercqdemocon** [sipwise/rtpengine#595]
Rtpengine installed on Debian Stretch. 

Please find below an excerpt of /etc/rtpengine/rtpengine.conf
[rtpengine]

table = 0
interface = 127.0.0.1 
.... 

when I do /etc/init.d/ngcp-rtpengine-daemon start

I get the following in syslog: 

Aug 15 15:59:04 ns3012072 systemd[1]: Starting NGCP RTP/media Proxy Daemon...
Aug 15 15:59:04 ns3012072 systemd[1]: Started NGCP RTP/media Proxy Daemon.
Aug 15 15:59:04 ns3012072 rtpengine[2219]: [1534341544.116429] CRIT: Fatal error: Invalid interface specification: 127.0.0.1

Please advise. 

BR, Johan.

**Comment by rfuchs** [comment]
Check if you don't have a stray space or other invisible characters after or around the IP address in the config file.

**Comment by johandeclercqdemocon** [comment]
That was fast, thank you. You can close the issue.
