### ISSUE TITLE
Daemon -v , undefined

### ISSUE THREAD

**Issue by nicoonline** [sipwise/rtpengine#596]
Hello,

Rtpengine -v shows no version output > Undefined

**Comment by rfuchs** [comment]
The output returned by `-v` depends on your build environment. If you build outside a Debian environment and without any git support, there will be no version information. Build from a git tree and it will be there.

**Comment by nicoonline** [comment]
I build on a Centos environment. So if i understand there will be no version information.

**Comment by rfuchs** [comment]
There will be if you build from a git tree. I have no idea about the CentOS/RPM build system. If there's a problem with the RPM build files, please submit a patch to fix it as they're not supported by us.

**Comment by nicoonline** [comment]
I build from the gIT
cd /usr/local/src
git clone https://github.com/sipwise/rtpengine.git
cd /usr/local/src/rtpengine/daemon && make

**Comment by mika** [comment]
@nicoonline What's the output of `git branch --no-color --no-column -v` run from inside the `/usr/local/src/rtpengine/daemon/` and `/usr/local/src/rtpengine/` directories?

**Comment by nicoonline** [comment]
[root@proxy2 rtpengine]# git branch -v
* master f91b64f Make recording more accurately report source address. Fixes #584

[root@proxy2 daemon]# git branch -v
* master f91b64f Make recording more accurately report source address. Fixes #584

De : Michael Prokop <notifications@github.com>
Envoyé : jeudi 16 août 2018 14:33
À : sipwise/rtpengine <rtpengine@noreply.github.com>
Cc : Nicolas Breuer <Nicolas.Breuer@belcenter.biz>; Mention <mention@noreply.github.com>
Objet : Re: [sipwise/rtpengine] Daemon -v , undefined (#596)


@nicoonline<https://github.com/nicoonline> What's the output of git branch --no-color --no-column -v run from inside the /usr/local/src/rtpengine/daemon/ and /usr/local/src/rtpengine/ directories?

**Comment by mika** [comment]
@nicoonline hm, then you should have `git-master-f91b64f` inside the version script. What's the output of:

```
git branch --no-color --no-column -v 2> /dev/null | awk '/^\*/ {OFS="-"; print "git", $2, $3}'
```

?

**Comment by nicoonline** [comment]
Nothing
[root@proxy2 daemon]# git branch --no-color --no-column -v 2> /dev/null | awk '/^\*/ {OFS="-"; print "git", $2, $3}'
[root@proxy2 daemon]# cd ../
[root@proxy2 rtpengine]# git branch --no-color --no-column -v 2> /dev/null | awk '/^\*/ {OFS="-"; print "git", $2, $3}'
[root@proxy2 rtpengine]#


De : Michael Prokop <notifications@github.com>
Envoyé : jeudi 16 août 2018 14:45
À : sipwise/rtpengine <rtpengine@noreply.github.com>
Cc : Nicolas Breuer <Nicolas.Breuer@belcenter.biz>; Mention <mention@noreply.github.com>
Objet : Re: [sipwise/rtpengine] Daemon -v , undefined (#596)


@nicoonline<https://github.com/nicoonline> hm, then you should have git-master-f91b64f inside the version script. What's the output of:

git branch --no-color --no-column -v 2> /dev/null | awk '/^\*/ {OFS="-"; print "git", $2, $3}'

?

**Comment by rfuchs** [comment]
I can't reproduce this on my CentOS VM.
```
[root@localhost rtpengine]# git branch --no-color --no-column -v 2> /dev/null | awk '/^\*/ {OFS="-"; print "git", $2, $3}'
git-master-d4afb14
[root@localhost rtpengine]# 
```
Maybe a locale issue? What's the output of `locale` ?

**Comment by nicoonline** [comment]
--no-color --no-column are not valid options

[root@proxy2 daemon]# git branch -v 2> /dev/null | awk '/^\*/ {OFS="-"; print "git", $2, $3}'
git-master-f91b64f

**Comment by nicoonline** [comment]
[root@proxy2 daemon]# git --version
git version 1.7.1

**Comment by mika** [comment]
Ah I see, you didn't invoke the requested in https://github.com/sipwise/rtpengine/issues/596#issuecomment-413531016 :)

Uff, git 1.7.1 dates back to 2010, that's really old, what CentOS version is this?

**Comment by rfuchs** [comment]
Well, that explains...
```
[root@localhost rtpengine]# git --version
git version 1.8.3.1
```

**Comment by nicoonline** [comment]
Centos 6.10

**Comment by mika** [comment]
Does `git branch --column=never --color=never -v` work in git 1.7.1?

**Comment by nicoonline** [comment]
error: unknown option `column=never'
usage: git branch [options] [-r | -a] [--merged | --no-merged]
   or: git branch [options] [-l] [-f] <branchname> [<start-point>]
   or: git branch [options] [-r] (-d | -D) <branchname>
   or: git branch [options] (-m | -M) [<oldbranch>] <newbranch>

Generic options
    -v, --verbose         be verbose
    -t, --track           set up tracking mode (see git-pull(1))
    --set-upstream        change upstream info
    --color[=<when>]      use colored output
    -r                    act on remote-tracking branches
    --contains <commit>   print only branches that contain the commit
    --abbrev[=<n>]        use <n> digits to display SHA-1s

Specific git-branch actions:
    -a                    list both remote-tracking and local branches
    -d                    delete fully merged branch
    -D                    delete branch (even if not merged)
    -m                    move/rename a branch and its reflog
    -M                    move/rename a branch, even if target exists
    -l                    create the branch's reflog
    -f, --force           force creation (when already exists)
    --no-merged <commit>  print only not merged branches
    --merged <commit>     print only merged branches

**Comment by mika** [comment]
Thanks, so @rfuchs question is whether we really need the column option (and AFAIK the color won't become active anyway if the command is piped to something else, maybe same for column option)?

**Comment by rfuchs** [comment]
@mika unfortunately it still produces colour when `=always` is set, even when piped.

Re column:
```
$ git branch -v --column=always
fatal: --column and --verbose are incompatible
```
So that would probably fail if the config file lists `column=always`

**Comment by rfuchs** [comment]
@mika perhaps it would be better to use porcelain?

**Comment by nicoonline** [comment]
[root@proxy2 daemon]# git branch -v --color=never
* master f91b64f Make recording more accurately report source address. Fixes #584
works.

**Comment by mika** [comment]
@rfuchs would be nice to have working `git describe`, but that's not how we use the repos, so either porcelain or checking for git options and falling back to known working options then, ACK.

**Comment by rfuchs** [comment]
`git rev-parse HEAD` gives the commit ID.
`git rev-parse --symbolic-full-name --abbrev-ref HEAD` gives the branch.

**Comment by mika** [comment]
@rfuchs: `git branch -v --column=never` with:

``
[column]
  ui = always 
```

in ~/.gitconfig seems to work, JFYI

**Comment by rfuchs** [comment]
@mika, sure, but old git doesn't know `--column` :)

**Comment by rfuchs** [comment]
@mika I suggest
```
GIT_BR_COMMIT=git-$(shell git rev-parse --abbrev-ref --symbolic-full-name HEAD)-$(shell git rev-parse --short HEAD)
```

**Comment by nicoonline** [comment]
I upgraded my git to Git 1.8.1.2

[root@proxy2 daemon]# ./rtpengine --version
Version: git-mr6.4.1-0309abe
Working 😊


De : Richard Fuchs <notifications@github.com>
Envoyé : jeudi 16 août 2018 15:26
À : sipwise/rtpengine <rtpengine@noreply.github.com>
Cc : Nicolas Breuer <Nicolas.Breuer@belcenter.biz>; Mention <mention@noreply.github.com>
Objet : Re: [sipwise/rtpengine] Daemon -v , undefined (#596)


@mika<https://github.com/mika> I suggest

GIT_BR_COMMIT=git-$(shell git rev-parse --abbrev-ref --symbolic-full-name HEAD)-$(shell git rev-parse --short HEAD)

**Comment by mika** [comment]
@rfuchs: LGTM
