### ISSUE TITLE
disable syslog logging.

### ISSUE THREAD

**Issue by nicoonline** [sipwise/rtpengine#597]
Hello,

I want to disable the logging in /var/log/messages

I created a local6 in my rsyslogd.conf
in /etc/rtpengine.conf, i put these values 
log-facility = local6
log-facility-rtcp = local6

I still see logs in /var/log/messages
my new /var/log/rtpengine.log is also populated

**Comment by rfuchs** [comment]
You'll have to change your syslogd config for that. Rtpengine itself doesn't control that.
