### ISSUE TITLE
rare behaviour when receiving a RTP payload number twice

### ISSUE THREAD

**Issue by descartin** [sipwise/rtpengine#598]
hello all

we are using at this moment Version: 6.1.3.0+0~mr6.1.3.0 git-v.6.1.3-1af3774
and we have seen that if we receive an SDP in the first INVITE like

m=audio 18280 RTP/AVP 8 0 101 4 4 18.
a=rtpmap:8 PCMA/8000.
a=rtpmap:0 PCMU/8000.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-15.
a=rtpmap:4 G723/8000.
a=fmtp:4 annexa=no;bitrate=6.3.
a=rtpmap:4 G723/8000.
a=fmtp:4 annexa=yes;bitrate=6.3.
a=rtpmap:18 G729/8000.
a=fmtp:18 annexb=yes.
a=ptime:20.
a=silenceSupp:on - - - -.

the rtpengine sometimes changes it to 
m=audio 32598 RTP/AVP 8 0 101 2953202768 4 18.
a=rtpmap:8 PCMA/8000.
a=rtpmap:0 PCMU/8000.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-15.
a=rtpmap:4 G723/8000.
a=fmtp:4 annexa=no;bitrate=6.3.
a=rtpmap:4 G723/8000.
a=fmtp:4 annexa=yes;bitrate=6.3.
a=rtpmap:18 G729/8000.
a=fmtp:18 annexb=yes.
a=ptime:20.
a=silenceSupp:on - - - -.
a=sendrecv.
a=rtcp:32599.

where i dont know what number 2953202768 is.
other times we just have a 0 instead the second 4 number of the media description

could you please tell me if this is a known issue?
i'm not sure if sending a payload number twice is invalid or not, i didnt see that on rfc4566

thanks a lto and regards
david

**Comment by rfuchs** [comment]
Good question. I would assume that payload type numbers ought to be unique, but you're right, it doesn't say that. Either way, it shouldn't result in a garbage output.

**Comment by rfuchs** [comment]
ba081be fixes this for mr6.1, but it will remove the duplicate payload type (i.e. `4` will appear only once in your example).

mr6.2 and up properly supports this use case and will leave duplicate payload types in place.

**Comment by descartin** [comment]
thanks for the update Richard
Fix seems it works

best regards
