### ISSUE TITLE
opensips + rtpengine, not voice

### ISSUE THREAD

**Issue by xiaoluweiba** [sipwise/rtpengine#600]
Yealink <-> opensips/rtpengine <-> asterisk

install rtpengine:
**dpkg -i ngcp-rtpengine-daemon_6.5.0.0+0~mr6.5.0.0_amd64.deb**

start rtpengine:
**rtpengine  -p /var/run/rtpengine.pid -i external/10.0.1.2 -i internal/192.88.99.100 --sip-source -n 127.0.0.1:7890 -c 127.0.0.1:7891 -m 20000 -M 40000 -E -L 7**

about opensips:
**rtpengine_offer("internal external replace-origin replace-session-connection address-family=IP4 RTP/AVP ICE=remove");
rtpengine_answer("external internal replace-origin replace-session-connection address-family=IP4 ICE=remove RTP/AVP ");**

sip flow is corret and SDP Part (c or m) had change ,but voice didn't transfer between external and internal 

Am I config wrong ? Can you give me some advice?

**Comment by rfuchs** [comment]
What does the log output show?

**Comment by xiaoluweiba** [comment]
it's must start rtpengine with flag --table? 
When I set it and change rtpengine_answer flag direction same as offer , It's OK.
rtpengine_answer("**internal externa**l replace-origin replace-session-connection address-family=IP4 ICE=remove RTP/AVP ");

**Comment by xiaoluweiba** [comment]
I am ready to replace rtpproxy use rtpengine, because I need ICE to support WebRTC.
now use IPhone to IPhone is OK ,but WebRTC to IPhone have problem.

I install opensips and rtpengine in AWS with Ubuntun system.
WebRTC <->WAN  LAN<-> asterisk
WAN IP = 10.0.1.2 have a outgoing public ip 47.96.131.184


when WebRTC send invite call in 
**rtpengine_offer("internal external replace-origin replace-session-connection UDP/TLS/RTP/SAVPF ICE=force");**
response 200OK for WebRTC's INVITE
**rtpengine_answer("internal external replace-origin replace-session-connection media-address=47.96.131.184 ICE=force UDP/TLS/RTP/SAVPF ");**

different start opensips have different result;
**not any voice**
rtpengine --table=0 -p /var/run/rtpengine.pid -i external/10.0.1.2 -i internal/192.88.99.100 --sip-source -n 127.0.0.1:7890 -c 127.0.0.1:7891 -m 20000 -M 40000 -E -L 7

**one way voice: IPhone->WebRTC is OK**
rtpengine --table=0 -p /var/run/rtpengine.pid -i external/10.0.1.2!47.96.131.184 -i internal/192.88.99.100 --sip-source -n 127.0.0.1:7890 -c 127.0.0.1:7891 -m 20000 -M 40000 -E -L 7

I am very grateful to receive your suggestion.  can you give me some advice to debug it ? I have SIP flow log and opensips log, Do you need?

**Comment by rfuchs** [comment]
Don't use directional flags (internal/external) in the answer. Only use them in the offer.
