### ISSUE TITLE
Need help in converting RTPEngine recorded pcap file to audio wav file for OPUS codec

### ISSUE THREAD

**Issue by lavanyakumars** [sipwise/rtpengine#601]
Hello,

I'm facing issue in decoding pcap file to audio wav format for opus codec related calls. But it is working fine for PCMU calls. These pcap file is recorded through RTPEngine and opensips. I'm using the below script with some minor changes as per my setup, https://gist.github.com/avimar/d2e9d05e082ce273962d742eb9acac16. 

Here i'm attaching the recorded pcap file as well. 

Can someone help to solve my issue. Please suggest if any other inputs required from my side.

Thanks,
Lavanyakumar
[7_pgonhoUqU5hijFkGKzOw..-3675b8c8d285cb05.zip](https://github.com/sipwise/rtpengine/files/2305144/7_pgonhoUqU5hijFkGKzOw.-3675b8c8d285cb05.zip)

**Comment by rfuchs** [comment]
Wireshark should work. Or take up the issue with the author of the script you linked. We don't support this use case directly.

**Comment by lavanyakumars** [comment]
Hi,

Thanks for your quick response. Sure will try to do that. 

Please ignore the conversion part, Could you please confirm whether the captured pcap file through RTPEngine has proper RTP packets with audio. Can you guide me how to verify captured audio from wireshark file directly.

The problem for me is, i'm unable to identify where the problem is exactly. Whether at RTPEngine recording or at conversion. Would be helpful if you can confirm attached wireshark file is fine, I'll continue to work on conversion part.

Thanks.

**Comment by rfuchs** [comment]
Yes you can absolutely reconstruct the audio from a recorded pcap. In Wireshark, you would use the menu option Telephony > RTP > RTP Streams, then "Analyze" one, which finally brings you to the screen that allows you to play and save the audio. You may have to tell Wireshark that the UDP packets are RTP first, by right-clicking and using the "decode as" option. The codec must be supported by Wireshark for this to work. I'm not sure if Opus is supported. Please use Google, I cannot provide support for Wireshark here. If Wireshark doesn't support Opus, then you need some other tool or script to do the conversion. Again I cannot provide support for this here.

**Comment by lavanyakumars** [comment]
Thanks for suggestion. 

I tried with wireshark as mentioned, but it couldn't play audio though RTP packets are there. But we can ignore this discussion about wireshark or conversion part. 

My request is, how to validate whether the recorded packets are properly done by RTPEngine. and whether i'm using RTPEngine in correct way. Please suggest, if it can be validated by provided pcap file. Or any other inputs required from my side.
