### ISSUE TITLE
ICE force-relay mutually exclusive with replace session-connection

### ISSUE THREAD

**Issue by dtryba** [sipwise/rtpengine#602]
I found out (the hard way) that if ICE force-relay is used the c= and o= values aren't replaced (non ICE clients aren't rewritten and audio fails if and endpoint is NATed).

Documentation says:
`With force-relay, existing ICE candidates are left in place except relay type candidates, and rtpengine inserts itself as a relay candidate. It will also leave SDP c= and m= lines unchanged.

This flag operates independently of the replace flags.`

I interpretted this as in force-relay doesn't do anything to c=/m= by itself. The last line indicates that it shouldn't interfere with replace.

But the way the flags work together implies that replace and ICE force-relay are mutually exclusive.

So my issue is, are the flags mutually exclusive by design? Or should ICE force-relay and replace origin session-connection both rewrite (different parts of) the SDP body?

Current results:
`0_17158_1 d3:sdp262:v=0.
o=- 230217372 230217372 IN IP4 10.0.4.143.
s=digphn.
b=AS:84.
t=0 0.
a=X-nat:0.
m=audio 4078 RTP/AVP 8 96.
c=IN IP4 10.0.4.143.
b=TIAS:64000.
a=rtcp:4079 IN IP4 10.0.4.143.
a=sendrecv.
a=rtpmap:8 PCMA/8000.
a=rtpmap:96 telephone-event/8000.
a=fmtp:96 0-16.
3:ICE11:force-relay5:flagsl13:trust-addresse7:replacel6:origin18:session-connectione18:transport-protocol7:RTP/AVP7:call-id32:04m-0J1impy.nPqhbdvm9F5ZNgNk9y0u13:received-froml3:IP413:109.235.32.57e8:from-tag32:hbymDLKQgVY.bnHtYr7yvLdqbDOSXeWp7:command5:offere
#
U 109.235.32.42:7723 -> 185.61.68.107:50489
0_17158_1 d3:sdp536:v=0.
o=- 230217372 230217372 IN IP4 10.0.4.143.
s=digphn.
b=AS:84.
t=0 0.
a=X-nat:0.
m=audio 4078 RTP/AVP 8 96.
c=IN IP4 10.0.4.143.
b=TIAS:64000.
a=rtcp:4079 IN IP4 10.0.4.143.
a=rtpmap:8 PCMA/8000.
a=rtpmap:96 telephone-event/8000.
a=fmtp:96 0-16.
a=sendrecv.
a=ice-ufrag:O2A51kRJ.
a=ice-pwd:htBFCcAlxpUmxoN1loBbgVFX9n.
a=candidate:UtJ7nahFpQLQ5VrR 1 UDP 16777215 109.235.32.42 30040 typ relay raddr 109.235.32.42 rport 30040.
a=candidate:UtJ7nahFpQLQ5VrR 2 UDP 16777214 109.235.32.42 30041 typ relay raddr 109.235.32.42 rport 30041.
6:result2:oke
`

Expected result was that 10.0.4.143 would be replaced with 109.235.32.42.

**Comment by rfuchs** [comment]
Yes, this is by design. The c= and m= lines should point to the higher priority / primary ICE candidates. With force-relay, rtpengine becomes a low priority candidate, and so c= and m= should not point to it.

**Comment by rfuchs** [comment]
To elaborate on your specific example, force-relay is meant to be used when there's already ICE candidates in place. If the offering client doesn't support ICE, you should probably use one of the other ICE flags (for example the default, which is to omit `ICE=` altogether).
