### ISSUE TITLE
MOS not calculated

### ISSUE THREAD

**Issue by nicoonline** [sipwise/rtpengine#603]
Hello,

We enabled the RTCP reports on Cisco Voice Gateways.
MOS is not calculated and we received RTCP packets.

Aug 22 11:15:30 proxy1 rtpengine[5888]: [ZPWg5ZaaYOvu5JBj2n1jsg..] version=2, padding=0, count=1, payloadtype=200, length=12, ssrc=638124190, ntp_sec=399, ntp_fractions=3491808411, rtp_ts=3219634551, sender_packets=19990, sender_bytes=3198400, ssrc=17787, fraction_lost=0, packet_loss=0, last_seq=21328, jitter=1, last_sr=0, delay_since_last_sr=0, version=2, padding=0, count=1, payloadtype=202, length=7

but se saw that delay since last sr is "0".

**Comment by rfuchs** [comment]
Do you receive RTCP going both ways? Delay since last SR should not be 0 if RTCP is going both ways.

**Comment by nicoonline** [comment]
Hi,

What i see on the final packet stats

--- Tag '86407DC4-1136', created 3:11 ago for branch '', in dialogue with 'sansay296484849rdb2267'
------ Media #1 (audio over RTP/AVP) using PCMA/8000
--------- Port  X.X.X.10:10660 <>      X.X.X.12:47152, SSRC 343e4632, 7824 p, 1345728 b, 0 e, 31 ts
--------- Port  X.X.X.10:10661 <>      X.X.X.12:47153 (RTCP), SSRC 343e4632, 16 p, 576 b, 0 e, 34 ts
--- Tag 'sansay296484849rdb2267', created 3:11 ago for branch '', in dialogue with '86407DC4-1136'
------ Media #1 (audio over RTP/AVP) using PCMA/8000
--------- Port  X.X.X.10:10652 <>     Y.Y.8.42:52790, SSRC ca11001f, 7920 p, 1362240 b, 0 e, 31 ts
--------- Port  X.X.X.10:10653 <>     Y.Y.8.42:52791 (RTCP), SSRC ca11001f, 34 p, 2856 b, 0 e, 34 ts


De : Richard Fuchs <notifications@github.com>
Envoyé : mercredi 22 août 2018 14:02
À : sipwise/rtpengine <rtpengine@noreply.github.com>
Cc : Nicolas Breuer <Nicolas.Breuer@belcenter.biz>; Author <author@noreply.github.com>
Objet : Re: [sipwise/rtpengine] MOS not calculated (#603)


Do you receive RTCP going both ways? Delay since last SR should not be 0 if RTCP is going both ways.

**Comment by rfuchs** [comment]
In that case, the content of the RTCP is probably broken. MOS cannot be calculated without valid "last SR" and "delay since last SR" values.

**Comment by nicoonline** [comment]
Ticket has been opened with Cisco TAC.


De : Richard Fuchs <notifications@github.com>
Envoyé : mercredi 22 août 2018 14:11
À : sipwise/rtpengine <rtpengine@noreply.github.com>
Cc : Nicolas Breuer <Nicolas.Breuer@belcenter.biz>; Author <author@noreply.github.com>
Objet : Re: [sipwise/rtpengine] MOS not calculated (#603)


In that case, the content of the RTCP is probably broken. MOS cannot be calculated without valid "last SR" and "delay since last SR" values.

**Comment by rfuchs** [comment]
Closing this one then.
