### ISSUE TITLE
Failed to set remote answer sdp: Called with SDP without DTLS fingerprint.

### ISSUE THREAD

**Issue by ceniymei** [sipwise/rtpengine#605]
sipml5 -> opensips/rtpengine -> freeswitch

opensips: 2.4.2
rtpengine:  git-tags/mr6.4.1.1-0309abe
freeswitch: FreeSWITCH Version 1.8.1+git~20180724T160524Z~b33bc925c5~64bit (git b33bc92 2018-07-24 16:05:24Z 64bit)

I am able to make a call without any problem. But after call sipml5 , session.hold() to hold the phone,  the following error will occur.   Please take a look,  appreciate for your help.

chrome console error: 
DOMException: Failed to set remote answer sdp: Called with SDP without DTLS fingerprint.

rtpengine log:
ERR: [9096eb4b-222c-1237-41b9-00163e052ef1 port 55441]: SRTCP output wanted, but no crypto suite was negotiated

opensips rtpengine offer:
$var(rtpengine_flags) = "UDP/TLS/RTP/SAVPF ICE=force SDES-off rtcp-mux-offer";

rtpengine log file:
[bak.log](https://github.com/sipwise/rtpengine/files/2318039/bak.log)

sip log :
[siplog.txt](https://github.com/sipwise/rtpengine/files/2318042/siplog.txt)

rtpengine command line:
rtpengine --pidfile /var/run/rtpengine.pid -m 55000 -n 127.0.0.1:2223 --log-level=7 -M 60000 --log-facility=local1 -i 172.31.9.19\!47.105.46.35 --dtls-passive

**Comment by rfuchs** [comment]
For some reason you're looping the rewritten output offer SDP back into rtpengine as another input offer.
```
Aug 24 18:37:55 izm5ecbd2icvurwdr4pr6az rtpengine[10210]: DEBUG: [9096eb4b-222c-1237-41b9-00163e052ef1]: Response dump for 'offer' to 127.0.0.1:59604: { "sdp": "v=0
o=- 1231761716923460600 3 IN IP4 47.105.46.35
s=Doubango Telecom - chrome
t=0 0
a=msid-semantic: WMS
m=audio 55440 RTP/AVP 9 8 102 0 101 103 127 104 106 105 13 112 113
c=IN IP4 47.105.46.35
a=rtpmap:9 G722/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:102 opus/48000/2
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=rtpmap:103 telephone-event/48000
a=rtpmap:127 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=fmtp:102 minptime=10;useinbandfec=1
a=sendonly
a=rtcp:55441
a=rtcp-mux
a=ptime:20
", "result": "ok" }
Aug 24 18:37:55 izm5ecbd2icvurwdr4pr6az rtpengine[10210]: INFO: [9096eb4b-222c-1237-41b9-00163e052ef1]: Received command 'offer' from 127.0.0.1:59348
Aug 24 18:37:55 izm5ecbd2icvurwdr4pr6az rtpengine[10210]: DEBUG: [9096eb4b-222c-1237-41b9-00163e052ef1]: Dump for 'offer' from 127.0.0.1:59348: { "sdp": "v=0
o=- 1231761716923460600 3 IN IP4 47.105.46.35
s=Doubango Telecom - chrome
t=0 0
a=msid-semantic: WMS
m=audio 55440 RTP/AVP 9 8 102 0 101 103 127 104 106 105 13 112 113
c=IN IP4 47.105.46.35
a=rtpmap:9 G722/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:102 opus/48000/2
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=rtpmap:103 telephone-event/48000
a=rtpmap:127 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=fmtp:102 minptime=10;useinbandfec=1
a=sendonly
a=rtcp:55441
a=rtcp-mux
a=ptime:20
", "ICE": "remove", "replace": [ "session-connection", "origin" ], "transport-protocol": "RTP/AVP", "call-id": "9096eb4b-222c-1237-41b9-00163e052ef1", "received-from": [ "IP4", "47.105.46.35" ], "from-tag": "IbI2T6xLicSbeP1UlSC7", "to-tag": "6UQv1gQ6ScN3N", "command": "offer" }
```
Don't do that. This is a problem with config/signalling script.

**Comment by ceniymei** [comment]
@rfuchs You are correct. It's the problem with opensips relay routing. The invite message is send back to opensips again which cause the problem. Thank you for your help.
