### ISSUE TITLE
No Audio/Video on WebTRC (caller) side when using rptengine

### ISSUE THREAD

**Issue by gethubsw** [sipwise/rtpengine#606]
Hello,

My current configuration is =>
Asterisk+ Kamailio + rtpengine (I installed rtpengine from GitHub two weeks ago).

My issue =>
Without rtpengine I can make two-way Audio/Video calls originating from either a soft-phone (provider software phone) or a WebRTC client, without any issues.  When using rtpengine, I can make successful two-way media calls, if the call originates from the the soft-phone; if the call originates from the WebRTC client then I only have one way Audio/Video.  The caller (the WebRTC client) has no Audio/Video, but the callee (the soft-phone, etc) has Audio and Video, also note that this call does stay connected.

Thank you,

**Comment by gethubsw** [comment]
I have discovered that some WebRTC=>Soft-phone calls work.  It seems to be dependent on which provider's Soft-phone is being used.  I don't know why one would work but the other wouldn't.
Any ideas?

Thank you,

**Comment by rfuchs** [comment]
Could be any number of things. Codec support perhaps? Impossible to say without logs from the affected components. If it's the softphone rejecting the call, it should tell you why it's doing that.
