### ISSUE TITLE
Connection with kamailio via unix socket

### ISSUE THREAD

**Issue by ovoshlook** [sipwise/rtpengine#607]
Hi
I jsut wanted to ask and maybe add this to feature request
At the kamailio rtpengine module in rtpengine_sock param description I found that I can connect to rtpengine via unix socket, but when I trying to read about it at the rtpengine doc i found for "--listen" param only tcp|udp|ng protos but did'nt find a way to add to unix socket 

So my question is - is it just not documented at the rtpengine guide  or this just a wrong information at the kamialio rtpengien odule description?

**Comment by rfuchs** [comment]
Actually it's neither. The Kamailio rtpengine module was forked from the rtpproxy module, which did support Unix sockets, and so the rtpengine module also supports them. However, support for Unix sockets was never implemented in the rtpengine daemon, making for a somewhat useless feature in the module.

It should be fairly trivial to implement Unix socket support in the rtpengine daemon, so patches are welcome.
