### ISSUE TITLE
ngcp-rtpengine-daemon.service: Main process exited, code=killed, status=6/ABRT

### ISSUE THREAD

**Issue by denislemire** [sipwise/rtpengine#608]
Running rtpengine 6.5.0.0+0~mr6.5.0.0 on Ubuntu 18.04 we're seeing the daemon terminate from time with a message like:

ngcp-rtpengine-daemon.service: Main process exited, code=killed, status=6/ABRT

As there is no core dump in this case, how can I provide more data to find the root cause of the issue?

The last logs before the process exit vary, examples include:
rtpengine[25720]: munmap_chunk(): invalid pointer
rtpengine[638]: malloc(): smallbin double linked list corrupted

**Comment by rfuchs** [comment]
Does your build include commit d4afb14 ?

Also a SIGABRT should produce a core dump.

**Comment by denislemire** [comment]
No, my build predates that commit. I'll do a new build and watch for new issues.

I found no core files on the system, might be due to some config on the system.

**Comment by denislemire** [comment]
Actually, my build also predates https://github.com/sipwise/rtpengine/commit/178391e1776052641a1b89f61601a588ee644a1d - I built it the day before!

I bet that's the ticket...

**Comment by denislemire** [comment]
My build based on commit 7dd8ed0b8f34cd4e2a390ef5913b6e73cfd9eaea has been running for over a week at this point, without issue. Closing.
