### ISSUE TITLE
SRTP -> RTP Bridging

### ISSUE THREAD

**Issue by greenfieldtech-nirs** [sipwise/rtpengine#613]
I have the following scenario:

UA ---> SIP TLS ---> Kamailio ---> SIP ---> Asterisk
    \ ---> SRTP --> RTPENGINE ---> SRTP ---/

I would like to force RTPENGINE to accept SRTP on one side, but only offer RTP to 
my Asterisk server. I've tried the following combination:

DTLS=passive SDES=unauthenticated_srtp SDES=unencrypted_srtp SDES=encrypted_srtp SDES=authenticated_srtp

But I believe I'm missing something in understanding how RTPEngine manipulates SRTP in this 
regard. Assistance would be highly appreciated.

**Comment by rfuchs** [comment]
Get rid of the SDES flags and instead specify the transport protocol you'd like to translate to. If it's an offer that goes to a plain RTP endpoint, put `RTP/AVP`. If it's an offer that goes to an SRTP endpoint, put `RTP/SAVP`. You don't need to do anything special for the answer.

**Comment by greenfieldtech-nirs** [comment]
Thanks - issue resolved.
