### ISSUE TITLE
Transcoding opus, one direction garbled Voice

### ISSUE THREAD

**Issue by adil-mafzool** [sipwise/rtpengine#616]
Hi

I am experiencing the issue when transcoding using RTP Engine using transcoded RTP opus to Yealink T58. 

(Snom)IP phone <------------> B2BUA<pcma-----------------pcma> Kamailio (RTP Engine version:: 6.3.2.0+0~mr6.3.2.0 git-mr6.3-de223d9)<opus------opus> Yealink T58

The transcoded generated opus by RTPEngine is not understood by Yealink T58 and garble audio is heard. I think since when rtpengine generate opus it doesn't append fmtp parameters like : -

useinbandfec=1; maxaveragebitrate=40000; maxplaybackrate=8000; 
As I have seen Yealink T58 opus working fine with FreeSwitch opus. Is there possibility we can set fmtp attributes for opus generated by rtpengine.

Please find the attached garbled_opus_audio.log and advice what is making it not work properly

[garbled_opus_audio.zip](https://github.com/sipwise/rtpengine/files/2371522/garbled_opus_audio.zip)

**Comment by rfuchs** [comment]
Are you able to confirm that it is in fact the missing fmtp that's causing the issue?

**Comment by adil-mafzool** [comment]
@rfuchs
I have another hardware phone showing similar issue where no audio at PolyComm VVX 600. 

Looking into the wireshark I have seen that very first opus packet  # 184 sent by rtpengine to Polycomm has Timestamp: 1182479278

packet  # 188  Timestamp: 1182479926 - 1182479278 = 648 ??
packet  # 182  Timestamp: 1182480886 - 1182479926 = 960

Please find the attached NoOpusAudioPolyComm.zip with log and rtpengine pcapture.

[NoOpusAudioPolyComm.zip](https://github.com/sipwise/rtpengine/files/2392197/NoOpusAudioPolyComm.zip)

**Comment by rfuchs** [comment]
I used rtpengine's own recording daemon to decode your pcaps. I played the pcaps back into the recording daemon and had it decode the audio. It comes out just fine. I'm attaching the resulting audio files for you to inspect. (Use the SSRC encoded in the filename to match the audio file to the RTP stream.)

[decoded.zip](https://github.com/sipwise/rtpengine/files/2393039/decoded.zip)

So AFAICT there's nothing wrong with the Opus payload that rtpengine generates, it's rather a problem of the phone not understanding it in some way. I don't have a way to troubleshoot this. Note that the Opus payload is generated by libopus via ffmpeg, not rtpengine directly.

If you suspect codec parameters are to blame, I encourage you to customise them and see if you find a solution. Look in `codeclib.c` for `opus_set_enc_options()`. All codec options supported by ffmpeg (its `libopus` encoder) can be added here. For a list see https://www.ffmpeg.org/ffmpeg-codecs.html#libopus-1

**Comment by adil-mafzool** [comment]
Thanks for your pointers about codeclib.c for opus_set_enc_options(). Will definitely try it.

Just wanted to confirm with you that the log showing samples 864 instead of (ptime 20 for 960 samples per frame) in the log **Sep 18 09:27:23 RTP media successfully decoded: TS 0, samples 864**

Hardware phones use voice dsp which are being confused with wrong ptime value which they are picking from the initial few packet and garbled happens because of wrong time.

Sep 18 09:27:23 Adding 160 bytes to packetizer
Sep 18 09:27:23 Received packet of 160 bytes from packetizer
Sep 18 09:27:23 Received RTP packet: SSRC 8d04cb06, PT 136, seq 29631, TS 1996004404, len 160
Sep 18 09:27:23 Creating SSRC transcoder from PCMA/8000/1 to opus/48000/2
Sep 18 09:27:23 Initialized encoder with frame size 960 samples
Sep 18 09:27:23 Encoder created with clockrate 48000, 2 channels, using sample format 1 (ptime 20 for 960 samples per frame and 960 samples (0 bytes) per packet)
Sep 18 09:27:23 Decoding RTP packet: seq 29631, TS 1996004404
Sep 18 09:27:23 av_log: Using s16p internally between filters
Sep 18 09:27:23 av_log: Matrix coefficients:
Sep 18 09:27:23 av_log: FL: 
Sep 18 09:27:23 av_log: FC:0.707107 
Sep 18 09:27:23 av_log: 
Sep 18 09:27:23 av_log: FR: 
Sep 18 09:27:23 av_log: FC:0.707107 
Sep 18 09:27:23 av_log: 
Sep 18 09:27:23 RTP media successfully decoded: TS 0, samples 864

is there any possible patch to try to ensure samples 960 in the initial packet?

**Comment by rfuchs** [comment]
864 is what's coming out of the resampler, not out of the codec. The resampler uses an internal dither buffer, so not all input samples are immediately converted to output samples. Some are retained in the buffer and will be returned when more input is provided. This is unrelated to what libopus is producing.

**Comment by denyspozniak** [comment]
Hello! 
@rfuchs , my question is a bit beyond discussion, but could you explain in details how to decode opus in wav via recording daemon? 

> I used rtpengine's own recording daemon to decode your pcaps. I played the pcaps back into the recording daemon and had it decode the audio.

**Comment by rfuchs** [comment]
Open pcap in Wireshark, set a filter for just the RTP stream you wanna decode (say per SSRC), save to new pcap containing just that. Load kernel module, make sure table 0 exists (`echo add 0 > /proc/rtpengine/control`), start recording daemon. (Main rtpengine daemon must not be running - alternatively you can use a different kernel table.) Use `kernel-intercept-pcap-replay.pl` to play the pcap into the recording daemon. Usage examples at the top of the file. Some values are hardcoded in the script. Use a recent version for support for non-RFC types such as Opus.

**Comment by adil-mafzool** [comment]
Yealink firmware had the issue which they have sent me the fixed firmware for testing and showing promising response.

**Comment by adil-mafzool** [comment]
Yealink have fixed this issue so closing it now

**Comment by StellaTeam** [comment]
@adil-mafzool Do the firmware provided by Yealink have been publicly released or is it still a beta one?
As we experience the same problems and the latest 83.0.25 hasn't fixed it...

**Comment by adil-mafzool** [comment]
@StellaTeam  The issue was fixed by Yealink T58 firmware version: 58.83.0.22 when it was reported in November 2019.
