### ISSUE TITLE
rtcp-mux attribute are not included in sdp

### ISSUE THREAD

**Issue by owpqwo** [sipwise/rtpengine#617]
even though "rtcp-mux" : ["offer"]  option are given for answer SDP.
return SDP does not have rtcp-mux attribute.

in case of offer SDP contains rtcp-mux but for the answer SDP does not have.
these are the option we used for answer SDP and input/output sdp.

options :
        "ICE": "force",
        "transport protocol": "RTP/SAVPF",
        "DTLS": "passive",
        "SDES": ["off"],
        "rtcp-mux": ["require"],
        "codec":{
          "offer" : "opus"
        },
        "replace": ["origin","session connection"]

Input : answer SDP
v=0
o=68a0a537_4130_ut454225706aaf 1536818134 1536818134 IN IP4 0.0.0.0
s=TEST
c=IN IP4 0.0.0.0
t=0 0
m=audio 12934 RTP/AVP 0 126
a=rtpmap:0 PCMU/8000
a=rtpmap:126 telephone-event/8000
a=ptime:20

output : answer SDP from rtpengine

v=0
o=95a6db0e_4130_ut7e5f9c59ecd3 1536822231 1536822231 IN IP4 0.0.0.0
s=TEST
c=IN IP4 0.0.0.0
t=0 0
m=audio 50424 RTP/SAVPF 0 126
a=rtpmap:0 PCMU/8000
a=rtpmap:126 telephone-event/8000
a=sendrecv
a=rtcp:50425
a=setup:passive
a=fingerprint:sha-1 83:6C:7B:75:CE:37:F6:23:33:1E:E0:0B:8F:2E:93:9E:02:18:60:59
a=ptime:20
a=ice-ufrag:Y9lUilIk
a=ice-pwd:w3FVyfOlN8ObjY8pWa04NjfEsB
a=candidate:5mki5JZOAdtZ9iXq 1 UDP 2130706431 ip 50424 typ host
a=candidate:5mki5JZOAdtZ9iXq 2 UDP 2130706430 ip 50425 typ host

**Comment by rfuchs** [comment]
The answer SDP goes back to the offering client, and so the answer SDP can only contain rtcp-mux if the original offer also contained rtcp-mux. Did the original offer contain rtcp-mux?
