### ISSUE TITLE
no audio from kamailio user to pstn (one way audio) 

### ISSUE THREAD

**Issue by eyasbar** [sipwise/rtpengine#618]
hello dears 

i'm using rtpengine Version: 6.5.0.0+0~mr6.5.0.0 git-master-bc9f09c with kamailio 
both of kamailio and rtp engine have a public IP 
and i'm using ZOIPER as a client 
when i'm trying to make a call from kamailio to pstn all is going will , but when i'm trying to do it In reverse there is one way audio .
on zoiper client i see the call statistics there is received and transmitted packets but the transmitted grater than the received packets (about twice).
and the log of RTPengine is as following : 

rtpengine[8302]: [1537027457.052948] INFO: [u8kn465847pqol8ptq45l545l9lfoto4@10.18.5.64]: Received command 'offer' from 94.252.181.93:8486
rtpengine[8302]: [1537027457.053058] INFO: [u8kn465847pqol8ptq45l545l9lfoto4@10.18.5.64]: Received command 'offer' from 94.252.181.93:2481
rtpengine[8302]: [1537027457.053114] NOTICE: [u8kn465847pqol8ptq45l545l9lfoto4@10.18.5.64]: Creating new call
rtpengine[8302]: [1537027457.053425] INFO: [u8kn465847pqol8ptq45l545l9lfoto4@10.18.5.64]: Replying to 'offer' from 94.252.181.93:2481 (elapsed time 0.000352 sec)
rtpengine[8302]: [1537027457.053558] INFO: [u8kn465847pqol8ptq45l545l9lfoto4@10.18.5.64]: Replying to 'offer' from 94.252.181.93:8486 (elapsed time 0.000590 sec)
rtpengine[8302]: [1537027457.377935] INFO: [u8kn465847pqol8ptq45l545l9lfoto4@10.18.5.64]: Received command 'delete' from 94.252.181.93:23071
rtpengine[8302]: [1537027457.378016] INFO: [u8kn465847pqol8ptq45l545l9lfoto4@10.18.5.64]: Scheduling deletion of call branch '9lkla5np-CC-1038-OFC-36' (via-branch '') in 30 seconds
rtpengine[8302]: [1537027457.378039] INFO: [u8kn465847pqol8ptq45l545l9lfoto4@10.18.5.64]: Replying to 'delete' from 94.252.181.93:23071 (elapsed time 0.000076 sec)
rtpengine[8302]: [1537027466.632686] WARNING: [u8kn465847pqol8ptq45l545l9lfoto4@10.18.5.64 port  1030]: RTP packet with unknown payload type 95 received
rtpengine[8302]: [1537027466.726081] INFO: [u8kn465847pqol8ptq45l545l9lfoto4@10.18.5.64]: Received command 'answer' from 94.252.181.93:23071
rtpengine[8302]: [1537027466.726273] INFO: [u8kn465847pqol8ptq45l545l9lfoto4@10.18.5.64]: Replying to 'answer' from 94.252.181.93:23071 (elapsed time 0.000161 sec)
rtpengine[8302]: [1537027468.599354] INFO: [u8kn465847pqol8ptq45l545l9lfoto4@10.18.5.64 port  1031]: Connecting to Homer at 10.192.129.145:9060
rtpengine[8302]: [1537027468.599416] INFO: [u8kn465847pqol8ptq45l545l9lfoto4@10.18.5.64 port  1031]: Connection to Homer at 10.192.129.145:9060 has been established
rtpengine[8302]: [1537027470.000913] INFO: [u8kn465847pqol8ptq45l545l9lfoto4@10.18.5.64 port  1040]: Confirmed peer address as 94.252.181.57:1420
rtpengine[8302]: [1537027470.004096] INFO: [u8kn465847pqol8ptq45l545l9lfoto4@10.18.5.64 port  1030]: Confirmed peer address as 5.155.155.153:7720
rtpengine[8302]: [1537027470.004126] INFO: [u8kn465847pqol8ptq45l545l9lfoto4@10.18.5.64 port  1030]: Kernelizing media stream: 5.155.155.153:7720
rtpengine[8302]: [1537027470.005841] INFO: [u8kn465847pqol8ptq45l545l9lfoto4@10.18.5.64 port  1040]: Kernelizing media stream: 94.252.181.57:1420
rtpengine[8302]: [1537027472.494474] INFO: [u8kn465847pqol8ptq45l545l9lfoto4@10.18.5.64 port  1031]: Confirmed peer address as 5.155.155.153:7721
rtpengine[8302]: [1537027472.807588] INFO: [u8kn465847pqol8ptq45l545l9lfoto4@10.18.5.64 port  1041]: Confirmed peer address as 94.252.181.57:1421
rtpengine[8302]: [1537027478.000083] INFO: [4by5s51ihgioziroy4yzqg0oqbb4gq1u@10.18.5.64]: Call branch '52ii0i0u-CC-1087-OFC-36' (via-branch '') deleted, no more branches remaining
rtpengine[8302]: [1537027478.000141] INFO: [4by5s51ihgioziroy4yzqg0oqbb4gq1u@10.18.5.64]: Final packet stats:
rtpengine[8302]: [1537027478.000155] INFO: [4by5s51ihgioziroy4yzqg0oqbb4gq1u@10.18.5.64]: --- Tag '52ii0i0u-CC-1087-OFC-36', created 0:46 ago for branch '', in dialogue with ''
rtpengine[8302]: [1537027478.000165] INFO: [4by5s51ihgioziroy4yzqg0oqbb4gq1u@10.18.5.64]: ------ Media #1 (audio over RTP/AVP) using unknown codec
rtpengine[8302]: [1537027478.000178] INFO: [4by5s51ihgioziroy4yzqg0oqbb4gq1u@10.18.5.64]: --------- Port   94.252.181.49:1014  <>   94.252.181.57:1416 , SSRC 0, 0 p, 0 b, 0 e, 46 ts
rtpengine[8302]: [1537027478.000191] INFO: [4by5s51ihgioziroy4yzqg0oqbb4gq1u@10.18.5.64]: --------- Port   94.252.181.49:1015  <>   94.252.181.57:1417  (RTCP), SSRC 0, 0 p, 0 b, 0 e, 46 ts
rtpengine[8302]: [1537027478.000201] INFO: [4by5s51ihgioziroy4yzqg0oqbb4gq1u@10.18.5.64]: --- Tag '', created 0:46 ago for branch '', in dialogue with '52ii0i0u-CC-1087-OFC-36'
rtpengine[8302]: [1537027478.000211] INFO: [4by5s51ihgioziroy4yzqg0oqbb4gq1u@10.18.5.64]: ------ Media #1 (audio over RTP/AVP) using unknown codec
rtpengine[8302]: [1537027478.000223] INFO: [4by5s51ihgioziroy4yzqg0oqbb4gq1u@10.18.5.64]: --------- Port   94.252.181.49:1000  <>          (null):0    , SSRC 0, 0 p, 0 b, 0 e, 46 ts
rtpengine[8302]: [1537027478.000234] INFO: [4by5s51ihgioziroy4yzqg0oqbb4gq1u@10.18.5.64]: --------- Port   94.252.181.49:1001  <>          (null):0     (RTCP), SSRC 0, 0 p, 0 b, 0 e, 46 ts

i found in it something like delete after answering the call is that the cause or some thing else and how to fix it ??? 

thanks in advance

**Comment by rfuchs** [comment]
Your log shows two different call IDs. Which one is it?
