### ISSUE TITLE
Kamailio + rtpengine web to sip

### ISSUE THREAD

**Issue by spencerfontein** [sipwise/rtpengine#620]
Hello,

I am using kamailio and rtpengine. I have web phone to web phone working and sip phone to sip phone working, but I have an issue with getting web to sip and sip to web. 

When I go from web to sip I get this in the logs:

SIP/2.0 488 Not Acceptable Here
Via: SIP/2.0/WSS pa1s0e9agt60.invalid;rport=7037;received=104.15.89.240;branch=z9hG4bK9248186
To: <sip:1003@allbluedev-phone.ngdesk.com>;tag=32d87c74
From: "Spencer" <sip:1000@allbluedev-phone.ngdesk.com>;tag=tuuss3do1i
Call-ID: 5v795avsf86mfid8svv9
CSeq: 1978 INVITE
User-Agent: Bria 5 release 5.3.4 stamp 93181
Warning: 305 devnull "SDP: Incompatible media format: no common codec"
Content-Length: 0

This is part of my kamailio config where the route NATMANAGE is

```
route[NATMANAGE] {
	if (is_request()) {
		if(has_totag()) {
			if(check_route_param("nat=yes")) {
				setbflag(FLB_NATB);
			} else {
				if (check_route_param("nat=ws")) {
					setbflag(FLB_NATWS);
				}
			}
		}
	}

	if (!(isflagset(FLT_NATS) || isbflagset(FLB_NATB) || isbflagset(FLB_NATWS))) {
		return;
	}

	if (isbflagset(FLB_NATWS)) { # We need RTPEngine web/SIP bridging
		if ($proto =~ "ws") { # This message coming from web --> SIP
			if (is_request()) {
				xlog("L_INFO", "$rm request: WebRTC --> SIP");
			} else {
				xlog("L_INFO", "$rs response: WebRTC --> SIP");
			}

			rtpengine_manage("trust-address replace-origin replace-session-connection rtcp-mux-dmux RTP/AVP media-address=192.66.61.101 record-call=on");
		} else { # This message coming from SIP --> web
			if (is_request()) {
				xlog("L_INFO", "$rm request: SIP --> WebRTC");
			} else {
				xlog("L_INFO", "$rs response: SIP --> WebRTC");
			}

			if(nat_uac_test("8")) {
				rtpengine_manage("replace-origin replace-session-connection rtcp-mux-offer rtcp-mux-accept media-address=192.66.61.101 RTP/SAVPF record-call=on");
			} else {
				rtpengine_manage("trust-address replace-origin replace-session-connection rtcp-mux-offer rtcp-mux-accept media-address=192.66.61.101   RTP/SAVPF record-call=on");
			}
		}
	} else { # We need NAT, but not SIP/web bridging
		if ($proto =~ "ws") { # Web --> web
			if (is_request()) {
				xlog("L_INFO", "$rm request: WebRTC --> WebRTC");
			} else {
				xlog("L_INFO", "$rs response: WebRTC --> WebRTC");
			}

			rtpengine_manage("trust-address replace-origin replace-session-connection rtcp-mux-offer rtcp-mux-accept media-address=192.66.61.101 record-call=on");
		} else { # SIP --> SIP
			if (is_request()) {
				xlog("L_INFO", "$rm request: SIP --> SIP");
			} else {
				xlog("L_INFO", "$rs response: SIP --> SIP");
			}

			if(nat_uac_test("8")) {
				rtpengine_manage("replace-origin replace-session-connection rtcp-mux-offer rtcp-mux-accept media-address=192.66.61.101 record-call=on");
			} else {
				rtpengine_manage("trust-address replace-origin replace-session-connection rtcp-mux-offer rtcp-mux-accept media-address=192.66.61.101 record-call=on");
			}
		}
	}

	if (is_request()) {
		if (!has_totag()) {
			if(t_is_branch_route()) {
				if(isbflagset(FLB_NATWS)) {
					add_rr_param(";nat=ws");
				} else {
					add_rr_param(";nat=yes");
				}
			}
		}
	}

	if (is_reply()) {
		if(isbflagset(FLB_NATB)) {
			if(is_first_hop()) {
				set_contact_alias();
			}
		}
	}
	return;
} 
```

Is there anything wrong with my kamailio config I am using https://sipjs.com/demo-phone/ for the web and Bria on my desktop. And have all codecs enabled.

**Comment by denyspozniak** [comment]
Hello!
Looks like something is not ok with codecs.
You can enable transcoding on rtpengine or choose common codec for both parties.

> Warning: 305 devnull "SDP: Incompatible media format: no common codec"

**Comment by efistokl** [comment]
@denyspozniak Could you tell how to enable transcoding?
Sorry if I am being stupid. I have not yet managed to find that in the documentation. Still looking for it.
Thank you very much!

@spencerfontein did you solve your problem? Please tell how. I would be extremely grateful to you!

**Comment by denyspozniak** [comment]
> As far as I understood, we need to pass an option codec-transcode-CODECNAMEHERE to rtpengine_manage call, don't we?
Yes.

**Comment by rfuchs** [comment]
Cleaning up old tickets
