### ISSUE TITLE
SRTP without DTLS together with SRTP with DTLS

### ISSUE THREAD

**Issue by valenciaj** [sipwise/rtpengine#623]
RTPEngine is offering SRTP without DTLS together with SRTP with DTLS. WebRTC no longer supports a=crypto (SRTP without DTLS).

> INVITE sip:ffiqsp5t@lgiajor4g7es.invalid;transport=ws SIP/2.0 
> Record-Route: <sip:[WEBRTC_IP];transport=ws;r2=on;lr=on;nat=ws> 
> Record-Route: <sip:[WEBRTC_IP];r2=on;lr=on;nat=ws> 
> Record-Route: <sip:[PBX_PROXY_IP];lr=on;ftag=as11c88554;nat=yes> 
> Via: SIP/2.0/WSS [WEBRTC_IP];branch=z9hG4bK74f.28a122c82eca1c0ca2ad1fac3fc56f31.0 
> Via: SIP/2.0/UDP [PBX_PROXY_IP];rport=5060;branch=z9hG4bK74f.15bd57b25fe2015e66f3980121a298b5.1 
> Via: SIP/2.0/UDP [PBX_IP]:5060;rport=5060;branch=z9hG4bK6d000c38 
> Max-Forwards: 68 
> From: "Anonymous" <sip:anonymous@anonymous.invalid>;tag=as11c88554 
> To: <sip:[SIP_USER]@[SIP_DOMAIN]> 
> Contact: <sip:anonymous@[PBX_IP]:5060> 
> Call-ID: 3611a91f6b8ed0b10ed41ad47cd7be67@[SIP_DOMAIN] 
> CSeq: 102 INVITE 
> User-Agent: [PROVIDER] 
> Date: Tue, 25 Sep 2018 16:20:16 GMT 
> Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH 
> Supported: replaces, timer 
> Content-Type: application/sdp 
> Content-Length: 635 
> 
> v=0 
> o=[PROVIDER] 862649117 862649117 IN IP4 [WEBRTC_IP] 
> s=[PROVIDER] 
> c=IN IP4 [WEBRTC_IP] 
> t=0 0 
> m=audio 37556 RTP/SAVPF 18 8 101 
> a=nortpproxy:yes 
> a=rtpmap:18 G729/8000 
> a=rtpmap:8 PCMA/8000 
> a=rtpmap:101 telephone-event/8000 
> a=fmtp:18 annexb=no 
> a=fmtp:101 0-16 
> a=sendrecv 
> a=rtcp:37556 
> a=rtcp-mux 
> a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:64tgrt1lUekLKBdYbJUYKgOe8Y4n346q/He3nckf 
> a=setup:actpass 
> a=fingerprint:sha-1 7D:3C:40:41:E2:86:55:FB:6D:44:BB:BA:D4:24:60:65:D2:21:76:72 
> a=ptime:20 
> a=ice-ufrag:bHkkJohr 
> a=ice-pwd:sYsqG7AAXB1bfOk42GMNoSftIm 
> a=candidate:RG9aaauBbjtoxiud 1 UDP 2130706431 [WEBRTC_IP] 37556 typ host 
>

**Comment by rfuchs** [comment]
Use `SDES-off` to remove the `a=crypto` attributes.

**Comment by valenciaj** [comment]
It's working properly.

Thanks @rfuchs
