### ISSUE TITLE
rtpengine: CRIT: Fatal error: Bad command line: No such file or directory

### ISSUE THREAD

**Issue by mislav-eu** [sipwise/rtpengine#624]
Hello.

I've installed ngcp-rtengine kernel but daemon refuses to start, it returns the following:

>Sep 26 13:39:03 mislav-test2 systemd[1]: Starting NGCP RTP/media Proxy Daemon...
Sep 26 13:39:03 mislav-test2 kernel: [6759111.620098] Registering xt_RTPENGINE module - version 7.0.0.0+0~mr7.0.0.0
Sep 26 13:39:03 mislav-test2 rtpengine: CRIT: Fatal error: Bad command line: No such file or directory
Sep 26 13:39:03 mislav-test2 rtpengine[13034]: [1537961943.612788] CRIT: Fatal error: Bad command line: No such file or directory
Sep 26 13:39:03 mislav-test2 systemd[1]: ngcp-rtpengine-daemon.service: Main process exited, code=exited, status=255/n/a
Sep 26 13:39:04 mislav-test2 kernel: [6759112.707932] Unregistering xt_RTPENGINE module
Sep 26 13:39:04 mislav-test2 systemd[1]: Failed to start NGCP RTP/media Proxy Daemon.
Sep 26 13:39:04 mislav-test2 systemd[1]: ngcp-rtpengine-daemon.service: Unit entered failed state.
Sep 26 13:39:04 mislav-test2 systemd[1]: ngcp-rtpengine-daemon.service: Failed with result 'exit-code'.

What file or directory is missing exactly?

**Comment by mislav-eu** [comment]
I installed that meanwhile and updated my problem above.

**Comment by rfuchs** [comment]
Still probably the config file missing

**Comment by mislav-eu** [comment]
File /etc/default/ngcp-rtpengine-daemon exists.

Content is:

> RUN_RTPENGINE=yes
LISTEN_TCP=25060
LISTEN_UDP=12222
LISTEN_NG=22222
LISTEN_CLI=9900
INTERFACES="192.168.0.197"
TIMEOUT=60
SILENT_TIMEOUT=3600
PIDFILE=/var/run/ngcp-rtpengine-daemon.pid
FORK=yes
TABLE=0
PORT_MIN=16384
PORT_MAX=16485

**Comment by rfuchs** [comment]
Are you running this under systemd? Only the SysV init file uses the values from the defaults file. Under systemd, you need to use the actual config file `/etc/rtpengine/rtpengine.conf`

**Comment by mislav-eu** [comment]
Indeed, that file was missing - only sample config was there. Thank you very much for this!
Owners should really improve this procedure to either include this step in the manual OR provide better debug output.
