### ISSUE TITLE
Kamailio-RTPEngine-Asterisk inbound call works with IOS but not Windows

### ISSUE THREAD

**Issue by gethubsw** [sipwise/rtpengine#626]
UAC: soft-phone on IOS/Windows calling a WebRTC client. 
Call flow: Kamailio=>RTPEngine=>Asterisk

I am using Kamailio 5.0, Asterisk 15.3 (pjsip), and the GitHub version of RTPEngine.

I have an issue where calls work when a soft-phone on an IOS phone makes a call to a WebRTC client.  However, if the same soft-phone is on Windows, it does not work (No Audio/Video).  I noticed in the Wireshark trace that when using IOS I see STUN packets, but when using Windows I see no STUN packets, but I do see RTP traffic; I **think** this may be the issue, but I am not sure why the IOS version would create STUN packets but when using Windows I get no STUN packets (or why the Windows version of the soft-phone is not going through STUN).  Any thoughts on what could be causing this? is STUN really the issue?

Note, I am using the 'default' rtpengine_manage() call (but I have tried a multitude of suggested options), and I have tried "ICE=force" in all the rtpengine_manage() calls => rtpengine_manage( "ICE=force").  

Thank you

**Comment by gethubsw** [comment]
I now believe this problem is being caused by a DTMF issue, because the IOS version responds to the input of a number key (which is used by a menu in the application) but the Windows version in not responding to the number key.  The Windows version works if rtpengine is disabled.  Any ideas?

Thank you,
Steve












/

**Comment by rfuchs** [comment]
Please run rtpengine with log level 7 and post the resulting logs. Also post pcaps of these calls.

**Comment by gethubsw** [comment]
Hello Richard, is there a possibility that this is an ICE (STUN) problem?

Thank you!,
-Steve

**Comment by rfuchs** [comment]
Try using one of the ICE= options, either ICE=remove if you want to disable/disallow ICE, or ICE=force if you need to support ICE towards the clients.
