### ISSUE TITLE
dpkg-shlibdeps: error: no dependency information found for /usr/local/lib/libcurl.so.4

### ISSUE THREAD

**Issue by ForGuru** [sipwise/rtpengine#628]
> dh_installdeb        -pngcp-rtpengine-daemon -P/usr/local/src/rtpengine/debian/ngcp-rtpengine-daemon
> dh_shlibdeps         -pngcp-rtpengine-daemon -P/usr/local/src/rtpengine/debian/ngcp-rtpengine-daemon
> dpkg-shlibdeps: error: no dependency information found for /usr/local/lib/libcurl.so.4 (used by /usr/local/src/rtpengine/debian/ngcp-rtpengine-daemon/usr/sbin/rtpengine)
> Hint: check if the library actually comes from a package.
> dh_shlibdeps: dpkg-shlibdeps -Tdebian/ngcp-rtpengine-daemon.substvars /usr/local/src/rtpengine/debian/ngcp-rtpengine-daemon/usr/sbin/rtpengine returned exit code 2
> debian/rules:86: recipe for target 'ngcp-rtpengine-daemon' failed
> make: *** [ngcp-rtpengine-daemon] Error 2

Getting above on Ubuntu 16.04.4 LTS

**Comment by guillemj** [comment]
Well, sure. As the error message states, you've got a locally installed library under /usr/local/lib, which contains no dependency information so dpkg-shlibdeps cannot proceed.
