### ISSUE TITLE
RTPEngine doesn't switch media stream to a new endpoint after re-INVITE

### ISSUE THREAD

**Issue by KonstantinPundyk** [sipwise/rtpengine#630]
Good day gents,
I've faced an issue with RTPEngine not switching media receiver endpoint after a re-INVITE needed to put a call on hold. 
We have a stack of Kamailio, Asterisk and RTPEngine. Short story is:
1) Media between endpoints **A** and **B** flows through RTPEngine, it was called twice by Kamailio to form the SDPs for both of them.
2) Endpoint **A** puts the call on hold. re-INVITE sent towards **B** has Asterisk in Connection Information now as it generates music oh hold.
3) Asterisk re-INVITEs **B** and starts sending music on hold media.
4) Kamailio calls RTPEngine once again to pass the INVITE generated by Asterisk and, basically, replaces **B** with Asterisk:
```
U 2018/10/02 10:11:00.704692 127.0.0.1:36162 -> 127.0.0.1:1026
0_2523_18 d3:sdp401:v=0.
o=root 1922459611 1922459612 IN IP4 127.0.0.1.
s=.
c=IN IP4 127.0.0.1.
b=CT:384.
t=0 0.
m=audio 26184 RTP/AVP 8 0.
a=rtpmap:8 PCMA/8000.
a=rtpmap:0 PCMU/8000.
a=ptime:20.
a=recvonly.
m=video 22572 RTP/AVP 100 99.
a=rtpmap:100 VP8/90000.
a=rtcp-fb:100 ack rpsi.
a=rtcp-fb:100 ccm fir.
a=rtpmap:99 H264/90000.
a=fmtp:99 profile-level-id=42801F.
a=rtcp-fb:99 ccm fir.
a=recvonly.
3:ICE5:force5:flagsl13:trust-address8:SDES-off13:strict-sourcee7:replacel6:origin18:session-connectione18:transport-protocol9:RTP/SAVPF8:rtcp-muxl5:offere7:call-id32:290162157403c55d1f60f2256057f48513:received-froml3:IP49:127.0.0.1e8:from-tag10:iol7a6d1oq6:to-tag10:as17b127217:command6:answere

U 2018/10/02 10:11:00.706696 127.0.0.1:1026 -> 127.0.0.1:36162
0_2523_18 d3:sdp937:v=0.
o=root 1922459611 1922459612 IN IP4 34.252.198.209.
s=.
c=IN IP4 34.252.198.209.
b=CT:384.
t=0 0.
m=audio 38844 RTP/SAVPF 8 0.
a=rtpmap:8 PCMA/8000.
a=rtpmap:0 PCMU/8000.
a=ptime:20.
a=recvonly.
a=rtcp:38844.
a=rtcp-mux.
a=setup:passive.
a=fingerprint:sha-1 D4:02:D1:DB:AD:B8:AD:0C:25:23:1D:1D:78:AB:73:26:5A:7A:95:50.
a=ice-ufrag:N79iqvhu.
a=ice-pwd:Lozq7PJjnuxFMVLbJJP3C8dnfn.
a=candidate:w47efz2X2dco7N3T 1 UDP 2130706431 34.252.198.209 38844 typ host.
m=video 38874 RTP/SAVPF 100 99.
a=rtpmap:100 VP8/90000.
a=rtcp-fb:100 ack rpsi.
a=rtcp-fb:100 ccm fir.
a=rtpmap:99 H264/90000.
a=fmtp:99 profile-level-id=42801F.
a=rtcp-fb:99 ccm fir.
a=recvonly.
a=rtcp:38874.
a=rtcp-mux.
a=setup:passive.
a=fingerprint:sha-1 D4:02:D1:DB:AD:B8:AD:0C:25:23:1D:1D:78:AB:73:26:5A:7A:95:50.
a=ice-ufrag:js1hhvVE.
a=ice-pwd:OKaNxvtXlYGSOFfRJqAwRtJbVI.
a=candidate:w47efz2X2dco7N3T 1 UDP 2130706431 34.252.198.209 38874 typ host.
6:result2:oke
```
So from this point an on I expect Asterisk to be getting media stream which prior to this re-INVITE **B** was getting from RTPEngine. As you might've guessed already this is not happening. What actually happens: RTPEngine keeps sending an empty steam towards **B** which results in **B** getting 2 simultaneous streams and it kinda breaks stuff.

  Flags being passed to RTPEngine by  Kamailio are the following:
` trust-address replace-origin replace-session-connection SDES-off strict-source ICE=force RTP/SAVPF rtcp-mux-offer  direction=pub direction=pub `
**NOTE:** I tried the `assymmetric` flag and it solves the particular issue but breaks pretty much everything else as both endpoints are behind NAT.

I'm attaching full logs below:
Interaction between Kamailio and RTPEngine - [RTPEngine_no_hold_music_ngrep_p1026.txt](https://github.com/sipwise/rtpengine/files/2449642/RTPEngine_no_hold_music_ngrep_p1026.txt)
Full RTPEngine log lvl 7 - [RTPEngine_no_hold_music_rtpenginelog.txt](https://github.com/sipwise/rtpengine/files/2449643/RTPEngine_no_hold_music_rtpenginelog.txt)

I'm not superior with RTPEngine logs reading, but at some point it says that endpoint has changed and I expect it to take corresponding actions. 

Please let me know if there're any knows resolutions to this or if you need me to provide more information.

Thanks in advance,
Konstantin

**Comment by rfuchs** [comment]
That's some interesting log formats you have there. How much of rtpengine has been modified in the version you're running?

Generally speaking, if an advertised endpoint changes from one SDP to another (i.e. from 10.100.4.234:7076 in the original offer to 127.0.0.1:26184 in the re-invite answer), then rtpengine will generate a new endpoint on its own. I'm not sure why this doesn't happen here and I won't speculate for obviously modified code. The normal way to prevent this from happening is to use the `port-latching` option. Try it, maybe it works for you. Also try a stock rtpengine installation maybe.
