### ISSUE TITLE
Multiple a=crypto lines on RE-INVITE

### ISSUE THREAD

**Issue by denislemire** [sipwise/rtpengine#631]
A recent behaviour change in RTPENGINE somewhere between 6.4.1 and 6.5.x is causing our RE-INVITES to fail with a BYE response back from the far side of containing a reason header:
```
REASON: Q.850;cause=65;text="a6bbde45-023d-409a-9b1e-a467f2ff1c91;InternalDiagCode: OnlyOneSrtpCryptoKeyExpected, InternalErrorPhrase: Only one crypto key should be in SDP answer"
```
My best guess is that this is related to commit cab9d895b208721da6c57cdc2ea91d896cd27ba8

Is the new behaviour configurable?

**Comment by rfuchs** [comment]
No, it's not configurable. Can you post a full debug log of such a call?

**Comment by denislemire** [comment]
Uploaded the RTPENGINE debug logs as well as the SIP dialogue on the TLS side of the conversation. The issue is the multiple crypto lines on the 200 OK on line 326... This behaviour causes the far side to reject the call, see BYE on line 401, particularly the Q.850 cause.

Previous version of RTPENGINE did not have the multiple crypto lines on the 200 OK of the RE-INVITE.

[rtpengine-issue-631.syslog.txt](https://github.com/sipwise/rtpengine/files/2511890/rtpengine-issue-631.syslog.txt)

[rtpengine-issue-631.sip.txt](https://github.com/sipwise/rtpengine/files/2511894/rtpengine-issue-631.sip.txt)

**Comment by rfuchs** [comment]
Can't reproduce this with current master nor with mr6.5.1. Which version are you running exactly?

**Comment by denislemire** [comment]
Just tested this against master branch commit 60bd4a681e425b15ebd46eedfe2c3a1e2fbcf7a7 and the issue still occurs.

**Comment by denislemire** [comment]
Not sure of the exact commit used to build the packages but we have rtpengine 6.5.0.0+0~mr6.5.0.0 running without this issue.

The packages were built Aug 7th so probably based on commit f91b64fcdfbaac9bb5be6b2db206e1fd03546fb7

**Comment by rfuchs** [comment]
See the commit referenced above. I think that should fix it. Let me know how it works out for you.

**Comment by denislemire** [comment]
Awesome! I will test this out and let you know. Thanks so much for your continuous efforts!

**Comment by denislemire** [comment]
Actually, this failed call has some other quirks related that might be tainting my results... CSeq for ACK/200 are getting out of sync.

**Comment by denislemire** [comment]
Hi Richard, apologies for the delay. Finally had a chance to circle back. It seems whatever new issue we were having in November was not to do with this patch but maybe something else in the tree at the time.

Applying your patch from origin/rfuchs/gh631 to the current master branch seems to give us an version that solves our original issue without introducing any others. Thanks!

**Comment by denislemire** [comment]
Richard, just to make sure I spoke clearly, we still need the patch in origin/rfuchs/gh631 to fix our issue...

Just when I tested it previously I ran into other issues at the time... Will you be merging the patch into master?

**Comment by denislemire** [comment]
Hooray!!! Thanks Richard for all your effort resolving this. Much appreciated!
