### ISSUE TITLE
Segfault when starting with newest hiredis

### ISSUE THREAD

**Issue by ovoshlook** [sipwise/rtpengine#632]
Hi. Just found that rtpengine crashes when start --redis with newly updated hiredis (last update 6 days ago to 0.14 version)
tested on RTPengine mr6.0 and mr6.1.2 on the debian 9
Not sure it is RTPengine related segfault but anyway good to know and test more deep
I still have one installation with newest redis, so let me know if need more info ( what kind and etc)
```
Oct  8 05:22:43 rtpengine1 rtpengine[2507]: INFO: Use Redis 10.10.120.145:6379 for notifications
Oct  8 05:22:43 rtpengine1 rtpengine[2507]: DEBUG: Success alloc redis_notify_event_base
Oct  8 05:22:43 rtpengine1 rtpengine[2507]: INFO: Use Redis 10.10.120.145:6379 to subscribe to notifications
Oct  8 05:22:43 rtpengine1 kernel: [ 4009.477443] rtpengine[2511]: segfault at 38 ip 00007f9e841434fa sp 00007f9e76ffc9d0 error 4 in libevent-2.0.so.5.1.9[7f9e84136000+46000]
```

**Comment by rfuchs** [comment]
Can you pull a backtrace from gdb? With debug package installed?
