### ISSUE TITLE
Can rtpengine convert SRTP to RTP?

### ISSUE THREAD

**Issue by DavidNemeskey** [sipwise/rtpengine#633]
We use rtpengine's forwarding daemon to monitor RTP traffic. It works perfectly fine, but we recently switched our devices to SRTP. We expected that rtpengine would convert the packages to RTP before forwarding them to a domain socket, but it does not.

I was wondering if we missed some configuration options that would allow SRTP to RTP conversion. [This page](https://www.kamailio.org/w/2018/02/transcoding-with-kamailio-and-rtpengine/) says "Along with its old popular feature to gateway between WebRTC DTLS-SRTP and plain RTP (decryption/encryption)", but it does not say how, nor if the feature is available when forwarding.

Is it possible to decrypt SRTP in rtpengine and forward the packages as RTP? If so, how to set it up?

**Comment by ovoshlook** [comment]
I will answer instead of Richard - yes it can. In case of kamailio/opnesips looks at the module description. You can find keys that describes profile and allows you dynamically say RTPengine hoe to convert RTP for the realtime data.
In case of pure rtpengine - it has API that allows you to do same thing

**Comment by DavidNemeskey** [comment]
I had a look here at the rtpengine options, and unfortunately didn't get any wiser. Could you perhaps point me to the relevant parts in the documentation? Thanks!

We are using Sipwise's Community edition, so Kamailio + rtpengine.

**Comment by ovoshlook** [comment]
Here is a flags you can use
https://kamailio.org/docs/modules/5.1.x/modules/rtpengine.html#rtpengine.f.rtpengine_offer

**Comment by rfuchs** [comment]
Basically you need to tell rtpengine what to do with the parameters in the SDP. For example if a plain RTP SDP offer is to be sent to an SRTP endpoint, you'd use the flag `RTP/SAVP`. In the opposite case, you'd use the flag `RTP/AVP`. You can omit these flags in the answer as rtpengine will automatically do the right thing. There's lots of concrete usage examples to be found online.
