### ISSUE TITLE
media loss in case of rtpenigne in middle of call . 

### ISSUE THREAD

**Issue by sasmita11** [sipwise/rtpengine#635]
I am using rtpengine with opensips-2.2 .
Version: git-master-e860b64

I am facing some issue in media loss . The call in which there is media loss for that the rtpengine logs looks like below . 

 Received command 'offer' from 52.200.138.x:47332
 Creating new call
 Replying to 'offer' from 52.200.138.x:47332 (elapsed time 0.000844 sec)
 DTLS-SRTP successfully negotiated
 DTLS-SRTP successfully negotiated
 Received command 'answer' from 52.200.138.x:43801
 DTLS: Peer certificate accepted
 Replying to 'answer' from 52.200.138.x:43801 (elapsed time 0.000223 sec)
 ICE negotiated: local interface 206.189.y.x
 Confirmed peer address as 34.236.b.a:10346
 Confirmed peer address as 74.96.b.a:59179
 Confirmed peer address as 34.236.b.a:10347
 Received command 'delete' from 52.200.138.x:44034
 Call-ID to delete not found
 Replying to 'delete' from 52.200.138.x:44034 (elapsed time 0.000017 sec)

There delete command received after 20min of starting the call . But its saying Call-ID not found . And media in the call lost after 5min of call . What will be the possible reason of media break .

**Comment by rfuchs** [comment]
Could you post a more detailed log? Like with log level 7 and including timestamps?
