### ISSUE TITLE
One way video issue when using rtpengine, but two way video if no rtpengine

### ISSUE THREAD

**Issue by gethubsw** [sipwise/rtpengine#636]
Hello All,

I'm still working through the one way video issue when using rtpengine and have a quick question.  I am seeing the following in the rtpengine log. An ICE error followed by an Successful STUN binding.  I am just wondering if the ICE error is related to the one way video. (whether it is inbound or outbound call, I never get video on the webrtc client side but always on the provider device, I get two way video if rtpengine is off).

Here is the log I am looking at

Oct 13 18:29:45  srvr1 rtpengine[9464]: NOTICE: [SDnkgs801-1ccee50a91c750ea36f10cc95aa0b1e4-gun02k1 port 10929]: Failed to determine ICE candidate from STUN request (from 50.50.50.50:13501 on interface 20.20.20.20:10929)
Oct 13 18:29:45  srvr1 rtpengine[9464]: DEBUG: [SDnkgs801-1ccee50a91c750ea36f10cc95aa0b1e4-gun02k1 port 10929]: Successful STUN binding request from 50.50.50.50:13501
Oct 13 18:29:45  srvr1 rtpengine[9464]: NOTICE: [SDnkgs801-1ccee50a91c750ea36f10cc95aa0b1e4-gun02k1 port 10955]: Failed to determine ICE candidate from STUN request (from 50.50.50.50:12523 on interface 20.20.20.20:10955)
Oct 13 18:29:45  srvr1 rtpengine[9464]: DEBUG: [SDnkgs801-1ccee50a91c750ea36f10cc95aa0b1e4-gun02k1 port 10955]: Successful STUN binding request from 50.50.50.50:12523

20.20.20.20 => Kamailio
50.50.50.50 => Asterisk

Thank you,
-Steve

**Comment by rfuchs** [comment]
It's probably receiving non-ICE STUN packets. You can confirm that by doing a packet dump (Wireshark). Closing this in favour of #626
