### ISSUE TITLE
[CentOS 7] Spec file suggestion

### ISSUE THREAD

**Issue by denyspozniak** [sipwise/rtpengine#637]
Hello!

I think you need to add _iptables-utils_ to **Requires:** string in spec file to work in-kernel module for CentOS 7.
https://github.com/sipwise/rtpengine/blob/master/el/rtpengine.spec

```
...
%package kernel
Summary:	NGCP rtpengine in-kernel packet forwarding
Group:		System Environment/Daemons
BuildRequires:	gcc make redhat-rpm-config iptables-devel
Requires:	iptables iptables-ipv6
Requires:	%{name}%{?_isa} = %{version}-%{release}
Requires: 	%{name}-dkms = %{version}-%{release}

%description kernel
%{summary}.
...

```

**Comment by rfuchs** [comment]
Please submit this as a pull request as I'm blind with regards to RPM stuff.
