### ISSUE TITLE
RTPEngine incorrectly processes SDP

### ISSUE THREAD

**Issue by calimasurian** [sipwise/rtpengine#639]
Hello! 

We are using 6.4 RTPENGINE release with Kamailio.
I see that sometimes after hold/un-hold RTPENGINE doesn't send rtp media stream to the IP address which is received in SDP.

Example:
1. Making outbound call (INVITE with SDP IP A.A.A.A)
2. RTPENGINE sends RTP to IP A.A.A.A.
3. Put the call on hold (re-INVITE with 0.0.0.0 SDP)
4. Send music on hold (re-INVITE from media application with IP X.X.X.X in SDP)
5. RTPENGINE sends RTP to ip X.X.X.X.
6. Take the call from hold back (re-INVITE with SDP A.A.A.A)
7. RTPENGINE sends RTP to IP X.X.X.X

Interesting fact that sometimes it works well and RTPengine sends media to the correct IP, but sometimes to incorrect.

I suppose it is incorrect behaviour of RTPengine. Could you please help us?
Thank you very much!

--------
What I see in RTPEngine logs:

=== GOOD part of call

Oct 18 16:27:05 sbc1 rtpengine[28517]: [1539869225.526497] DEBUG: [0001B468-61BA-1BC7-96DF-0514000AAA77-23566@10.0.20.21]: Dump for 'offer' from 127.0.0.1:60023: { "sdp": "v=0
Oct 18 16:27:05 sbc1 rtpengine[28517]: o=29407 1539796904 6 IN IP4 172.10.10.14
Oct 18 16:27:05 sbc1 rtpengine[28517]: s=SIP Call
**Oct 18 16:27:05 sbc1 rtpengine[28517]: c=IN IP4 172.10.10.14**
Oct 18 16:27:05 sbc1 rtpengine[28517]: t=0 0
Oct 18 16:27:05 sbc1 rtpengine[28517]: m=audio 5004 RTP/AVP 8 101
Oct 18 16:27:05 sbc1 rtpengine[28517]: a=sendrecv
Oct 18 16:27:05 sbc1 rtpengine[28517]: a=ptime:20
Oct 18 16:27:05 sbc1 rtpengine[28517]: a=rtpmap:8 PCMA/8000
Oct 18 16:27:05 sbc1 rtpengine[28517]: a=rtpmap:101 telephone-event/8000
Oct 18 16:27:05 sbc1 rtpengine[28517]: a=fmtp:101 0-15
...
Oct 18 16:27:05 sbc1 rtpengine[28517]: [1539869225.564064] INFO: [0001B468-61BA-1BC7-96DF-0514000AAA77-23566@10.0.20.21 port 10424]: Switching local interface to 10.0.20.19:10424
Oct 18 16:27:05 sbc1 rtpengine[28517]: [1539869225.701757] INFO: [0001B468-61BA-1BC7-96DF-0514000AAA77-23566@10.0.20.21 port 10442]: **Kernelizing media stream: 172.10.10.14:5004**
Oct 18 16:27:05 sbc1 rtpengine[28517]: [1539869225.703935] INFO: [0001B468-61BA-1BC7-96DF-0514000AAA77-23566@10.0.20.21 port 10424]: Kernelizing media stream: 111.81.130.61:16976

=== BAD part of call

Oct 18 16:27:19 sbc1 rtpengine[28517]: [1539869239.188728] DEBUG: [0001B468-61BA-1BC7-96DF-0514000AAA77-23566@10.0.20.21]: Dump for 'offer' from 127.0.0.1:39301: { "sdp": "v=0
Oct 18 16:27:19 sbc1 rtpengine[28517]: o=29407 1539796904 9 IN IP4 172.10.10.14
Oct 18 16:27:19 sbc1 rtpengine[28517]: s=SIP Call
**Oct 18 16:27:19 sbc1 rtpengine[28517]: c=IN IP4 172.10.10.14**
Oct 18 16:27:19 sbc1 rtpengine[28517]: t=0 0
Oct 18 16:27:19 sbc1 rtpengine[28517]: m=audio 5004 RTP/AVP 8 101
Oct 18 16:27:19 sbc1 rtpengine[28517]: a=sendrecv
Oct 18 16:27:19 sbc1 rtpengine[28517]: a=ptime:20
Oct 18 16:27:19 sbc1 rtpengine[28517]: a=rtpmap:8 PCMA/8000
Oct 18 16:27:19 sbc1 rtpengine[28517]: a=rtpmap:101 telephone-event/8000
Oct 18 16:27:19 sbc1 rtpengine[28517]: a=fmtp:101 0-15
...
Oct 18 16:27:19 sbc1 rtpengine[28517]: [1539869239.223882] INFO: [0001B468-61BA-1BC7-96DF-0514000AAA77-23566@10.0.20.21 port 10424]: Switching local interface to 10.0.20.19:10424
Oct 18 16:27:19 sbc1 rtpengine[28517]: [1539869239.366114] INFO: [0001B468-61BA-1BC7-96DF-0514000AAA77-23566@10.0.20.21 port 10442]: **Kernelizing media stream: 10.0.20.7:20002**
Oct 18 16:27:19 sbc1 rtpengine[28517]: [1539869239.381776] INFO: [0001B468-61BA-1BC7-96DF-0514000AAA77-23566@10.0.20.21 port 10424]: Kernelizing media stream: 111.81.130.61:16976

**Comment by rfuchs** [comment]
It's probably receiving UDP packets on that port from some place else. You can confirm that by doing a packet dump, e.g. with Wireshark.

**Comment by calimasurian** [comment]
Hello! Thank you for the response!
I am not sure because there were no any more calls but mine at that time.

I also have to say, that I've solved this issue, I hope my experience will help anybody else.
The problem was that from Kamailio I've sent rtpengine_manage with a param "unidirectional" (more info [here](https://www.kamailio.org/docs/modules/5.0.x/modules/rtpengine.html)). When I'put it away, everything works well.

rtpengine_manage("trust-address direction=$(dlg_var(call_int){s.select,1,|}) direction=$(dlg_var(call_int){s.select,0,|}) replace-origin replace-session-connection **unidirectional** ICE=remove RTP/AVP");

**Comment by rfuchs** [comment]
It does not necessarily have to be a UDP packet from another call, it could also be some other stray UDP packet. But as you solved the problem, I will close the ticket.
