### ISSUE TITLE
scheluding call branch for 30secs

### ISSUE THREAD

**Issue by descartin** [sipwise/rtpengine#64]
Dear all

we have recently moved from mediaproxy-ng to rtpengine, and we have observed the 30 deletion scheluding for all the call branch deleted in the kamailio we are connected to.
this increases the number of active ports we have in the system. is there anyway to configure this deletion or to suppress it?

thanks a lot and regards
david

**Comment by slavrov** [comment]
-d, --delete-delay               Delay for deleting a session from memory.

**Comment by descartin** [comment]
thanks a lot! i didnt notice of the flag meaning when reading the man page XD
