### ISSUE TITLE
a=mid lines required for Firefox 63+

### ISSUE THREAD

**Issue by egreenmachine** [sipwise/rtpengine#641]
Due to recent work on transceivers in firefox, `a=mid` lines are required for SDP to work in Firefox even though there is no `BUNDLE`. Their "recommended" approach is to just add `a=mid` lines to the various sections of the SDP regardless. Can this be added to the SDP generated by rtpengine?

https://bugzilla.mozilla.org/show_bug.cgi?id=1495569

**Comment by rfuchs** [comment]
Sure, but it makes me wonder how many other cases it would break, where a client rejects the SDP with an unexpected `a=mid`...

**Comment by juha-h** [comment]
Richard Fuchs writes:

> Sure, but it makes me wonder how many other cases it would break,
> where a client rejects the SDP with an unexpected `a=mid`...

Same here.  Seems like each new version of Firefox and Chrome makes some
non backwards compatible changes to WebRTC SDP.  One day the web phone
works and the next day it gets broken by a browser update.  Better to
give up the mess.

**Comment by rfuchs** [comment]
FWIW, Firefox probably expects a fully WebRTC compliant SDP, and rtpengine doesn't produce these (yet) as it doesn't do the BUNDLE thing (yet). So I wouldn't be too quick to blame Firefox here.

**Comment by egreenmachine** [comment]
The `a=mid` lines are required for the transceiver work that the WebRTC guys are working on. All browsers are moving towards the [SDP Unified Plan](https://webrtc.org/web-apis/chrome/unified-plan/). I haven't had enough time to look into it fully and see if RTPEngine is compatible with it. The old "Plan B" will still be supported at least through the end of the year.

My thought is that it may be good to put this stuff behind a flag. We already have ICE and DTLS behind flags that we turn on when we think the endpoint is compatible. This could be the same.

**Comment by juha-h** [comment]
If I understood correcly the last few messages of this thread:
```
https://bugzilla.mozilla.org/show_bug.cgi?id=1495569
```
latest Firefox now accepts offer without a=mid.

**Comment by nud** [comment]
As of today, firefox 63.0.3 rejects calls without a=mid, while firefox 64b11 accepts them.

**Comment by nud** [comment]
OTOH it looks like the bug still exists in firefox 64b1 when holding/unholding media (with sendonly then sendrecv)

```
Tue Nov 27 2018 11:29:45 GMT+0100 (Central European Standard Time) | sip.inviteservercontext | 58a4f4d7 | sessionDescriptionHandler error error: DOMException
​​message: "Local descriptions must have a=mid attributes."
​​name: "InvalidSessionDescriptionError"
```
