### ISSUE TITLE
Session Description Protocol Version (v) 0 listed twice when using rtpengine

### ISSUE THREAD

**Issue by gethubsw** [sipwise/rtpengine#643]
Hello

I have noticed that  the Session Description Protocol Version (v) 0 to be repeated when using rtpengine.  I see it twice with what look like all the same data in a 200 OK in the Message Body?  I believe this is causing some provider phones to fail.

Thank you

**Comment by rfuchs** [comment]
I believe this has been sufficiently addressed here: https://lists.kamailio.org/pipermail/sr-users/2018-October/103530.html
