### ISSUE TITLE
weird handling of payloads in reinvites 

### ISSUE THREAD

**Issue by descartin** [sipwise/rtpengine#645]
hello Richard

from issue 642,
thanks, i can schedule to move to 6.5. 
I just tried now to compile but i see several things changed (using systemd, the xt_RTPENGINE.ko module) and i still would need some time to test, schedule and migrate the production systems to this version.

IN the meantime, could it be possible if you check the chnage i made for 6.1.3? would that change break soemthing or it's fine?

i also already tested th same call on 6.5.2 and i also saw th issue that repeated codecs are not removed.
However i cannot post you logs becase i see
.....
Oct 25 15:35:42 rtpengine-transcoding.bts.io rtpengine[4853]: INFO: [0c08fdac-afcb-4fc8-9bf7-aeb3c2dc83da]: Replying to 'answer' from 5.5.5.5:45138 (elapsed time 0.000116 sec)
Oct 25 15:35:42 rtpengine-transcoding.bts.io rtpengine[4853]: [277B blob data]
Oct 25 15:35:43 rtpengine-transcoding.bts.io rtpengine[4853]: DEBUG: timer run time = 0.000049 sec
Oct 25 15:35:44 rtpengine-transcoding.bts.io rtpengine[4853]: INFO: [0c08fdac-afcb-4fc8-9bf7-aeb3c2dc83da]: Received command 'answer' from 5.5.5.5:41716
Oct 25 15:35:44 rtpengine-transcoding.bts.io rtpengine[4853]: [514B blob data]
.....
no idea yet about those blob data, i just compiled 6.5 :$

Anycase, a feedback about 6.1.3 question would be really appreciated

regards
david

**Comment by descartin** [comment]
well i guess is not a big deal the payloads are repeated, the issue of #598 was the rtpengine was generating a rare out of range payload if some of them were repeated. Seems on 6.5 it's not.

So i will consider move to 6.5 once we make some tests for regresion to move our live systems.

But please, in the meantime i would need to fix the issue i have now with 6.1.3 which is my live version, no not strip undesirable payloads from offers/answers of each streams.

i would need to know if cleaning the hash for media->codecs is ok

thanks a lot and best regardsd
david

**Comment by descartin** [comment]
hello 

well i applied the change of issue 642, while we test version 6.5 to use it live.

regards

**Comment by rfuchs** [comment]
Cleaning up old tickets
