### ISSUE TITLE
RTPEngine Appending invalid rtpmaps in SDP for disabled video 

### ISSUE THREAD

**Issue by adil-mafzool** [sipwise/rtpengine#646]
Hi

I am experiencing the issue RTP Engine which is appending invalid rtpmaps in SDP for disabled video when SIP the re-invite is being processed by RTPEngine.

(Yealink T58 with Video) IP Phone <----> B2BUA <----> Kamailio (RTP Engine version:: 6.3.2.0+0~mr6.3.2.0 git-mr6.3-de223d9) <----> (Snom with No Video)IP phone 

Initial call is set up with no issue. 

The first SIP re-invite also work fine. After 10 seconds of second SIP re-invite is generated from B2BUA with the following offer to SNOM: -

Oct 29 10:25:54 rtpengine-media-01 rtpengine: DEBUG: [3_187817234@172.31.17.17~2o]: Dump for 'offer' from 10.20.11.196:46329:
v=0
o=Sippy 1418786894539849065 2 IN IP4 91.228.242.21
s=SDP data
b=AS:786
t=0 0
m=audio 36686 RTP/AVP 8 101
c=IN IP4 91.228.242.21
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
m=video 0 RTP/AVP 110 97 99 98 117
c=IN IP4 91.228.242.21

Which is being converted by RTPEngine to the following SDP: -

Oct 29 10:25:54 rtpengine-media-01 rtpengine: DEBUG: [3_187817234@172.31.17.17~2o]: Response dump for 'offer' to 10.20.11.196:46329:
v=0
o=Sippy 1418786894539849065 2 IN IP4 185.28.212.156
s=SDP data
b=AS:786
t=0 0
m=audio 38618 RTP/SAVP 8 101 96 9
c=IN IP4 185.28.212.156
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=rtpmap:96 opus/48000/2
a=rtpmap:9 G722/8000
a=fmtp:101 0-15
a=sendrecv
a=rtcp:38619
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:fHrm4gcmy/cWsCeYQ/YdTwI1v6acCtTLYX30NpwK
m=video 0 RTP/SAVP 110 97 99 98 117
c=IN IP4 185.28.212.156
a=rtpmap:110 
a=rtpmap:97 
a=rtpmap:99 
a=rtpmap:98 
a=rtpmap:117 

The above SDP is wrong as it is missing rtp maps encoding details.

The call is hung-up as the consequences of this issue. 
Please find the attached log
[Wrong_rtpmap_for_disabled_video.zip](https://github.com/sipwise/rtpengine/files/2525109/Wrong_rtpmap_for_disabled_video.zip)

**Comment by rfuchs** [comment]
Already reported and fixed in #638
