### ISSUE TITLE
After replying to offer anser , rtpengine gives this error and there is no audio . 

### ISSUE THREAD

**Issue by sasmita11** [sipwise/rtpengine#647]
DEBUG: [35cab66fb0c34be68091012a0d319bec port 30366]: Processing incoming DTLS packet
 WARNING: [35cab66fb0c34be68091012a0d319bec port 30366]: DTLS: Peer certificate rejected - fingerprint mismatch
 ERR: [35cab66fb0c34be68091012a0d319bec port 30366]: DTLS error: 1 (certificate verify failed)
 ERR: [35cab66fb0c34be68091012a0d319bec port 30366]: DTLS error on local port 30366
 NOTICE: [35cab66fb0c34be68091012a0d319bec port 30366]: Received invalid STUN packet from 205.254.147.8:3195: MESSAGE_INTEGRITY attribute missing

Please do help me to solve this . I got this once in 300 calls . So not sure whats the reason behind this .

**Comment by rfuchs** [comment]
Probably a client error. The certificate the client used in the DTLS negotiation and the fingerprint used in the SDP didn't match. I don't think there's much rtpengine can do about it.
