### ISSUE TITLE
rtpengine removes a=group and a=mid attributes from sdp.

### ISSUE THREAD

**Issue by tiglat** [sipwise/rtpengine#651]
Hello. 

We are using rtpengine mr5.2.1.1 to work with WebRTC clients.
Recently we have met an issue that FireFox starts to answer with 500 response on our INVITEs, although that worked fine more than 1 year!!!

Now FireFox requires to have a=group and a=mid attributes inside SDP body. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1495569 

We tried to insert such attributes into our SDP bodies but we found that rtpengine always removes attribute a=mid.

Could you please help us with the issue?
Thank you in advance
Best regards.

**Comment by rfuchs** [comment]
Discussion in #641
