### ISSUE TITLE
Build without ngcp-rtpengine-recording-daemon?

### ISSUE THREAD

**Issue by denislemire** [sipwise/rtpengine#656]
Is there a way to build without the ngcp-rtpengine-recording-daemon? Documentation suggests its optional but current builds end up making it a dependency.

During installation It fails to start with:
[1542297487.412865] CRIT: Fatal error: inotify_add_watch failed: No such file or directory

That failure causes the rest of the installation to fail.

**Comment by rfuchs** [comment]
Can you post more context of what you're trying to do? The recording daemon should not cause the installation to fail.

**Comment by denislemire** [comment]
Simply trying to install the packages, on install apt tries to install and start the recording daemon. That fails and leaves everything in a sad state.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/139257/48566712-b4d0a800-e8b8-11e8-91b0-22779fd0d3f4.png">

**Comment by denislemire** [comment]
I should add this is installing packages that were built on a equivalent but different machine. That may be related to the issue.

**Comment by rfuchs** [comment]
That screenshot is missing the crucial part of what is actually causing the error. But anyway, you can always just install the individual packages separately without the metapackage, i.e. -daemon, -dkms and -iptables.

**Comment by denislemire** [comment]
The error was on the original comment... The recording daemon fails to start with the following
[1542297487.412865] CRIT: Fatal error: inotify_add_watch failed: No such file or directory

The error doesn't indicate what file is the issue.

That said, your suggestion to just not use the meta-package did resolve my immediate problem.

**Comment by guss77** [comment]
Just had the same problem with rtpengine 7.5.2.1

OS: Ubuntu 18.04.3, with packages built on the same OS but a different machine.

installing `ngcp-rtpengine-recording-daemon` causes the system to start `ngcp-rtpengine-recording-daemon.service`, and that causes the postinst script to fail with this error:

```
Job for ngcp-rtpengine-recording-daemon.service failed because the control process exited with error code.
See "systemctl status ngcp-rtpengine-recording-daemon.service" and "journalctl -xe" for details.
invoke-rc.d: initscript ngcp-rtpengine-recording-daemon, action "start" failed.
● ngcp-rtpengine-recording-daemon.service - NGCP RTP/media Recording Daemon
   Loaded: loaded (/lib/systemd/system/ngcp-rtpengine-recording-daemon.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-11-27 13:54:22 UTC; 6ms ago
  Process: 18989 ExecStart=/usr/sbin/rtpengine-recording -f -E --no-log-timestamps --pidfile /run/ngcp-rtpengine-recording-daemon.pid --config-file /etc/rtpengine/rtpengine-recording.conf (code=exited, status=255)
 Main PID: 18989 (code=exited, status=255)

Nov 27 13:54:22 media-34-237-207-205.us-east-1.use1.media.cloudonix.io systemd[1]: Starting NGCP RTP/media Recording Daemon...
Nov 27 13:54:22 media-34-237-207-205.us-east-1.use1.media.cloudonix.io rtpengine-recording[18989]: INFO: Creating output dir '/var/lib/rtpengine-recording'
Nov 27 13:54:22 media-34-237-207-205.us-east-1.use1.media.cloudonix.io rtpengine-recording[18989]: CRIT: Fatal error: inotify_add_watch failed: No such file or directory
Nov 27 13:54:22 media-34-237-207-205.us-east-1.use1.media.cloudonix.io systemd[1]: ngcp-rtpengine-recording-daemon.service: Main process exited, code=exited, status=255/n/a
Nov 27 13:54:22 media-34-237-207-205.us-east-1.use1.media.cloudonix.io systemd[1]: ngcp-rtpengine-recording-daemon.service: Failed with result 'exit-code'.
Nov 27 13:54:22 media-34-237-207-205.us-east-1.use1.media.cloudonix.io systemd[1]: Failed to start NGCP RTP/media Recording Daemon.
dpkg: error processing package ngcp-rtpengine-recording-daemon (--configure):
 installed ngcp-rtpengine-recording-daemon package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 ngcp-rtpengine-recording-daemon
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

The install process itself fails due to a missing configuration file `/etc/rtpengine/rtpengine-recording.conf`, which I fixed (copied the sample) and then when I ran `sudo apt install -f`, I got the error above.

The problem *cannot* be worked around with the suggested workaround because I didn't even try to install `ngcp-rtpengine-recording-daemon` - it was required by `ngcp-rtpengine-daemon`:

```
$ apt show ngcp-rtpengine-daemon 
Package: ngcp-rtpengine-daemon
Version: 7.5.2.1+0~mr7.5.2.1-cx1
Priority: optional
Section: net
Source: ngcp-rtpengine
Maintainer: Sipwise Development Team <support@sipwise.com>
Installed-Size: 618 kB
Depends: lsb-base (>= 3.0-6), libavcodec57 (>= 7:3.4.6) | libavcodec-extra57 (>= 7:3.4.6), libavfilter6 (>= 7:3.4.6) | libavfilter-extra6 (>= 7:3.4.6), libavformat57 (>= 7:3.4.6), libavutil55 (>= 7:3.4.6), libbcg729-0 (>= 1.0.0), libc6 (>= 2.14), libevent-2.1-6 (>= 2.1.8-stable), libevent-pthreads-2.1-6 (>= 2.1.8-stable), libglib2.0-0 (>= 2.31.8), libhiredis0.13 (>= 0.13.1), libip4tc0 (>= 1.6.0+snapshot20161117), libip6tc0 (>= 1.6.0+snapshot20161117), libjson-glib-1.0-0 (>= 0.13.2), libmysqlclient20 (>= 5.7.11), libpcap0.8 (>= 0.9.8), libpcre3, libspandsp2 (>= 0.0.6), libssl1.1 (>= 1.1.0), libswresample2 (>= 7:3.4.6), libsystemd0, libxmlrpc-core-c3, zlib1g (>= 1:1.1.4)
Recommends: ngcp-rtpengine-recording-daemon, ngcp-rtpengine-utils
Suggests: ngcp-system-tools
Conflicts: ngcp-mediaproxy-ng-daemon, ngcp-rtpengine-redis1
Replaces: ngcp-mediaproxy-ng-daemon, ngcp-rtpengine-redis1
Homepage: https://www.sipwise.com/
```

The workaround is to install rtpengine using `apt install ngcp-rtpengine-daemon --no-install-recommends`, and that works - but its a problem for automatic installations as some systems (such as cloud-init) do not support disabling recommendations.

**Comment by rfuchs** [comment]
I suppose the root cause here is that neither packaging nor daemon itself creates the default spool directory.
