### ISSUE TITLE
Redis and call resiliency?

### ISSUE THREAD

**Issue by denislemire** [sipwise/rtpengine#662]
Am I understanding correctly in storing call state in Redis would allow calls to survive an RTPENGINE crash and reload? I can see the Call-IDs show in Redis but in experimenting with a restart of ngcp-rtpengine-daemon mid-call, my audio was lost.

Am I misunderstanding the functionality that Redis backing of state provides or is there limitations such as SRTP to RTP calls not being preserved?

**Comment by rfuchs** [comment]
No that is exactly what it's supposed to do. There's only a few limitations to it. One is that the DTLS state is not preserved. SRTP keys do get preserved in Redis, but the DTLS connection gets lost and would have to be re-established (which might upset some clients). (SDES SRTP should not have any issues whatsoever.)

**Comment by denislemire** [comment]
Thanks for the clarification!
