### ISSUE TITLE
Is there a way to make rtpengine stateless?

### ISSUE THREAD

**Issue by ovoshlook** [sipwise/rtpengine#663]
We are working on some horizontal scalable platform and in case of this we chosen stateless signaling servers
this means we are not keeping info of the transaction at all (or trying to not keep it)
so for signaling it is not a huge problem but in case of rtpengine as we see after offer message it stores data of the connection and expects to match answer to open second pair of the ports (sender->rtpnengine)
My question is it a way to not map offer and answer and keep connection just for the each media leg independently to have a possibility to manage offer and answer via different rtpengines?

**Comment by rfuchs** [comment]
No there is no such thing. I'm not sure how that would work even theoretically since RTP is (usually) bidirectional and having the offer and answer handled by different instances would break that.

**Comment by ovoshlook** [comment]
Hi thx for the response
main idea was just to open an map ordered ports in case of every message

when arrives offer it says which port is will listen (lets say ip:port pair A)
In case of rtpengine it just changes port and IP to itself (in simplest scenario) (lets say to ip:port pair B)
Then receiver party, starts to send RTP to  rtpengine  B that resends it to A

this behavior works same as for the offer as for the answer. isn't it?
 
Idea of my question was just to allow define port ip for the leg and start to listed dialog immediately

so lets say each request is just an offer and answer.

Yes there are limitations - both parties should generate rtp before timeout  but in case of RTP relaying it looks like simple...

In that case request and reply can be independend of each others and it gives possibility to use different rtpengines for the different legs

If you will find it interesting for realization and nice to have will be cool. Otherwise just close this issue :-)

**Comment by rfuchs** [comment]
No that doesn't work, because (using your example) rtpengine receiving media on local ip:port pair B needs to send that media to ip:port pair A, but needs to use a second local port as outgoing source address, which would be ip:port pair C. And when the answer comes through, rtpengine needs to replace the SDP address with that same ip:port pair C. If you choose a different local address (for example from a difference instance), you get asymmetric RTP, which is not what you want (usually, anyway).

**Comment by ovoshlook** [comment]
Hm... why it will use same ip:port pair C. cound you explain it little bit deeper?
I cofnused because as I know negotiation flow works like that:

Caller sends SDP with the data that says:
 - Hey I will listen this ip:port (A)
 - RTPengine maps this with rewritten by itself ip:port (B)
Callee catches request 
 - Remembers information B
Callee sends response
 - Ok. I will listen then ip: port (C)
 - RTPengine maps this with rewritten by itself ip:port (D)
Caller Catches response
 - Remembers information D

Callee starts to send rtp to B (rtpengine) that maps to A (Caller)
Caller start to send rtp to D (rtpengine ) that maps to C (Callee)

Isn't it?

**Comment by rfuchs** [comment]
1) "RTPengine decides from what ip:port pair this traffic should be send to the Caller when it will arrive to the B"
2) "RTPengine maps this with rewritten by itself ip:port (D)"

If those two are not the same, then you get asymmetric RTP.

Caller A sends offer to callee B. Offer is handled by rtpengine instance R1. B sees R1 in SDP.
Callee B responds with answer to A. Answer is handled by rtpengine instance R2. A sees R2 in SDP.
A therefore sends RTP to R2, which forwards it to B.
B sends RTP to R1, which forwards it to A.
A therefore sends RTP to R2 but receives it from R1, and B sends to R1 but receives from R2.
This is asymmetric RTP.

And this isn't even getting into how to handle call teardowns or re-invites. So if you don't care about having asymmetric RTP or possibly changing SDP endpoints mid-session (if re-invites are handled by different instances) and have a solution for call teardown, then yes you can do it, but at that point I have to wonder why you would want to use rtpengine in the first place :)

**Comment by ovoshlook** [comment]
thx for the response :)
I got now what you talking about
I just thought we talking of kinda of NATing.

regarding Re-INVITEs it is a good question - so for now we don't need to manage it.
Regarding RTPengine to use in case of these scenarios - We have really good experience in case of using it and know its possibilities - that is main idea why we chosen it

thx you for the discussion and your time, and sorry for misunderstanding :)

Don't know if you will decide to add this simplified functionality to the rtpengine but anyway thx!
Maybe in case of free time we will try to investigate it and make pull request from our side.
