### ISSUE TITLE
RTPEngine doesn't work properly with implementation of SRTP Replay Protection (rfc3711#section-3.2.3)

### ISSUE THREAD

**Issue by adil-mafzool** [sipwise/rtpengine#664]
I am experiencing the issue RTP Engine where Call-Hold/UnHold from the callee after SIP the re-invite using SRTP. The phone isn't playing the audio sent by
rtpengine as it using SRTP replay protection (rfc3711#section-3.2.3). Replay protection is part of SRTP and not used in normal unsecured RTP.

A cryptographic context SHALL be uniquely identified by the triplet context identifier:

`context id = <SSRC, destination network address, destination transport port number>`

`<CallerPhone-A> (SRTP)<--> (SRTP) Kamailio Proxy (RTP Engine: 6.5.2.0+0~mr6.5.2.0 git-mr6.5-3d84f49)(RTP) <-->B2BUA (RTP)<--> <CalleePhone-B>`
RTP is setup as follow: -

Initial call is set up OK with `call-id: 88309YWQwNDczNzEzY2ZmYjM3OTY3ZDg2ZjQ5OGNkMTdjM2U.`
`CallerPhone-A (payload opus: 120) 0x439f0e50 <---->  RTP Engine (payload opus: 120) 0x5e8f116a`

`Last sequence number 33074 before CalleePhone-B Hold for SSRC: 0x5e8f116a`

Call Hold from CalleePhone-B

`Sendonly stream RTP Engine (payload opus: 96) 0x719502aa ----- > CallerPhone-A (payload opus: 96)`
 
Call UnHold from CalleePhone-B

`CallerPhone-A (payload opus: 96) 0x439f0e50 <---->  RTP Engine (payload opus: 96) 0x5e8f116a`

`First sequence number 23080 after UnHold for SSRC: 0x5e8f116a`

Additionally, its not ideal that RTPEngine is generating the different payload type for currently active session when the SIP re-INVITE is received from the CalleePhone-B.

Please find the RTPEngine log attached herewith
[SRTP_replay_protection.zip](https://github.com/sipwise/rtpengine/files/2611456/SRTP_replay_protection.zip)

**Comment by rfuchs** [comment]
That's a known issue when the transcoding engine is active. Sequence numbers are handled in the transcoding context, which is specific for each SSRC _and_ codec pair-ups, when instead it should be specific to the SSRC only.

**Comment by adil-mafzool** [comment]
@rfuchs Is there any pointers to correct the behaviour?

What about rtpengine generating different payload type for the in-dialog re-invite from other side.

**Comment by rfuchs** [comment]
The payload type is probably due to your usage of the flags `"codec-strip-opus", "transcode-opus"` in the reverse re-invite, which removes the Opus codec and then re-adds it, thus generating a new payload type.

As for fixing the sequencing, it's not a trivial change, as otherwise I'd already have done it myself. The sequencing is handling in `codec.c` in `__output_rtp`. The sequence number is taken from the `struct codec_ssrc_handler *ch` object, which is passed down all the way from `__handler_func_sequencer` where it's retrieved via `get_ssrc(mp->rtp->ssrc, h->ssrc_hash)`. The `struct codec_handler *h` object in turn is created in `codec_handlers_update` which creates one for each input codec and decides what to do with packets received for each codec. To fix it, the sequencing needs to be moved out of the codec-specific `codec_ssrc_handler` object and into a higher level SSRC-specific object.

**Comment by rfuchs** [comment]
Commit 0ee0e75 in branch `rfuchs/664` may be a possible fix for this. Can you try to confirm?

**Comment by adil-mafzool** [comment]
Will test and get back to you.

**Comment by adil-mafzool** [comment]
Unfortunately the situation remain the same with wrong sequence number after unhold from callee.

<CallerPhone-A> (SRTP)<--> (SRTP) Kamailio Proxy (RTP Engine: 7.1.0.0+0~mr7.1.0.0 git-mz-srtp-fix-0ee0e75)(RTP) <-->B2BUA (RTP)<--> <CalleePhone-B>
RTP is setup as follow: -

Initial call is set up OK with call-id: 88309NTRhNTVjZGMyMmE3ZWIzMzhiMDAyODcwZDA3MGI5NzU.
CallerPhone-A (payload opus: 120) 0x50110336 <----> RTP Engine (payload opus: 120) 0x79F7B249

Last sequence number 45161 before CalleePhone-B Hold for SSRC: 0x79F7B249

Call Hold from CalleePhone-B

There is one packer sequence number 45163 with SSRC: 0x79F7B249 after which following sendonly stream picks up the sendonly stream RTP Engine (payload opus: 96) 0x7F51EC0D ----- > CallerPhone-A (payload opus: 96)

Call UnHold from CalleePhone-B

CallerPhone-A (payload opus: 96) 0x50110336 <----> RTP Engine (payload opus: 96) 0x79F7B249

First sequence number 39380 after UnHold for SSRC: 0x79F7B249

Please find the RTPEngine log attached herewith

[SRTP_Replay_Protection71.zip](https://github.com/sipwise/rtpengine/files/2736501/SRTP_Replay_Protection71.zip)

**Comment by adil-mafzool** [comment]
@rfuchs the issue seems to be that the input rtp stream sequence number has changed to lower as can be seen with "Seq reset detected". When generating output srtp stream after decoded sequence; it should be re-generated for srtp rather than using rtp sent sequence number.
Is in the function __output_rtp we have a way to determined that we are generating srtp and not rtp?
or is it possible to change ssrc for srtp when "Seq reset detected" for rtp stream to be transcoded?

**Comment by adil-mafzool** [comment]
@rfuchs please can you review the pull request #690!!

**Comment by rfuchs** [comment]
So 76d5614 is my latest attempt to fix this and seems to pass all the tests. There's an outstanding issue about preventing streams from getting kernelized, but that shouldn't be relevant to your case.

**Comment by adil-mafzool** [comment]
Unfortunately, I am seeing the following warning! 

Feb 28 17:08:53 rtpengine-dev rtpengine[20300]: [1551373733.883409] WARNING: [88309MGI0NTEwNGI2MzM5Y2FkNDBmNTMyYTZhMWY1ZmY4ZjQ]: Unknown flag encountered: 'codec-mask-PCMA'
Feb 28 17:08:53 rtpengine-dev rtpengine[20300]: [1551373733.883436] WARNING: [88309MGI0NTEwNGI2MzM5Y2FkNDBmNTMyYTZhMWY1ZmY4ZjQ]: Unknown flag encountered: 'codec-mask-PCMU'
Feb 28 17:08:53 rtpengine-dev rtpengine[20300]: [1551373733.883453] WARNING: [88309MGI0NTEwNGI2MzM5Y2FkNDBmNTMyYTZhMWY1ZmY4ZjQ]: Unknown flag encountered: 'codec-mask-G729'

Looking at the code git commit "e1d6c83 ignore transcoding options in non-offer messages" doesn't like these options in answer. As we need these option in answer to ensure initial SIP invite request codec priority order is taken into.

**Comment by rfuchs** [comment]
You should be able to achieve what you're trying to do by using the right options in the offer. Can you give a concrete example?

**Comment by adil-mafzool** [comment]
Please find the following attached logs: -

8th January 2019 working log : -
[SRTP_Replay_Protection71.zip](https://github.com/sipwise/rtpengine/files/2918881/SRTP_Replay_Protection71.zip)

1st March 2019 which generates warning: -
 [codec_mask_not_in_answer.zip](https://github.com/sipwise/rtpengine/files/2918868/codec_mask_not_in_answer.zip)

The major difference between the two being that OPUS is answered backed by rtpengine on the 8th Jan 2019 where as 1st March 2019 version rtpengine is answered as G711-Alaw.

**Comment by rfuchs** [comment]
Ok, completely different issue. The `always-transcode` flag in the offer is supposed to make that work. Commit 8f3c309 should fix this.
