### ISSUE TITLE
Issues compiling rtpengine on RedHat 7.6

### ISSUE THREAD

**Issue by gethubsw** [sipwise/rtpengine#665]
Hello,

I am trying to compile rtpengine on RedHat 7.6. but it will not compile.  There are many missing dependencies...starting with xmlrpc_client.h.  Has rtpengine ever been compiled on this version of linux?

Thank you,

**Comment by gethubsw** [comment]
I appear to be in an "Old School DLL dependency struggle".  I try to add the required library and it is dependent on something else...and so on.  I rarely have this issue with modern Linux systems, so I was hoping someone else was able to get rtpengine to compile and would know what could be missing.

**Comment by denyspozniak** [comment]
Hey!
I could build month ago for CentOS, you can try to fork and rebuild for RedHat. 
[https://copr.fedorainfracloud.org/coprs/denysp/rtpengine/](https://copr.fedorainfracloud.org/coprs/denysp/rtpengine/)

**Comment by taurus-forever** [comment]
@gethubsw feel free to send pull request to the repository and update README or some 'spec' file for building on RedHat. Sipwise (rtpengine maintainer) cares about Debian only at the moment.

Tnx!
