### ISSUE TITLE
rtcp attribute in SDP loosing the ipaddress

### ISSUE THREAD

**Issue by gethubsw** [sipwise/rtpengine#668]
Hello,

If I receive an INVITE and the SDP rtcp attribute is .e.g. "rtcp:12345 IN IP4 222.333.444.555", it is getting changed to "rtcp:12345".  Is there a way to keep the IN IP4.....?

Thank you,
-Steve

**Comment by rfuchs** [comment]
No, why do you need that?

**Comment by rfuchs** [comment]
That would be a broken device, not an old device.

The proper place to add this is in sdp.c, in `sdp_replace()` where it inserts `a=rtcp`. It would have to append something similar to what `replace_network_address()` is doing.
