### ISSUE TITLE
Recording functionality

### ISSUE THREAD

**Issue by oteren** [sipwise/rtpengine#67]
Hello.

It seems like recording functionality is planned. 

Is there any kind of road map or timeline for this?

**Comment by rfuchs** [comment]
It's not really planned, it's only part of the control interface because the old one (rtpproxy) also had it. We may implement it at some point, but I can't give any ETA.

**Comment by oteren** [comment]
Thank you for the swift reply :smile: 

I suggest you put that info in the readme.md, as it looks a bit like its planned with how its worded right now.
