### ISSUE TITLE
High CPU load on RTPEngine 7.1.0.0 even when idle

### ISSUE THREAD

**Issue by ewsamuels** [sipwise/rtpengine#671]
Hello,

I am running rtpengine 7.1.0.0 on a Debian Stretch VM with Kamailio 5.1.6 after upgrading from rtpengine 6.5.0.0 due to this same issue with the following packages installed:

ngcp-rtpengine-daemon
ngcp-rtpengine-daemon-dbgsym	
ngcp-rtpengine-iptables
ngcp-rtpengine-kernel-dkms	
ngcp-rtpengine-kernel-source
ngcp-rtpengine-utils

Even when there are no calls on the system rtpengine shows over 200% cpu during the day when there are approx 300 calls on the server that goes up to 400% - 500%.

The system is a KVM VM with 8 cores.  The strange thing is we have another VM with exactly the same config and no issues.

If I reboot the server it is fine for about 15 mins.

```
12896 root      20   0 1570396  36628  28172 S 231.9  0.2  40:13.58 rtpengine
load average: 1.79, 1.60, 1.48
```

IPTables

```
Chain rtpengine (1 references)
target     prot opt source               destination         
RTPENGINE  udp  --  0.0.0.0/0            0.0.0.0/0            RTPENGINE id:0
```

Here is the rtpengine.conf

```
[rtpengine]

table = 0

### a single interface:
interface = 1.1.1.1 (realip changed)
listen-ng = 2223

timeout = 60
silent-timeout = 3600
tos = 184
port-min = 16384
port-max = 32768
log-level = 0

```

I also tried with this config and it made no difference.

```
[rtpengine]

table = 0
no-fallback = false

### a single interface:
interface = 1.1.1.1

listen-ng = 2223
# listen-tcp = 25060
# listen-udp = 12222

timeout = 60
silent-timeout = 3600
foreground = false
tos = 184
port-min = 16384
port-max = 32768
# max-sessions = 5000

log-level = 0
delete-delay = 30
max-sessions = -1
max-load = 0
max-cpu = 0
max-bandwidth = 0
scheduling = default
priority = 0
idle-scheduling = default
idle-priority = 0
```

Any assistance would be greatly appreciated.

Thanks in Advance.
ES

**Comment by rfuchs** [comment]
When you turn on debug logging (log level 7), what does it show while it's idle?

What does attaching with `strace -f -p PID` show?

**Comment by ewsamuels** [comment]
Hi rfuchs,

Thanks for looking at the issue.

The server is live at the moment with just over 400 calls, if I turn up logging it will probably kill the server.  See attached strace below.
[strace.txt](https://github.com/sipwise/rtpengine/files/2652239/strace.txt)

This is what we have at the moment.
![screen shot 2018-12-06 at 08 29 51](https://user-images.githubusercontent.com/5496519/49571447-32745a80-f931-11e8-8479-fa2e1b5201b9.png)

Thanks again.

**Comment by rfuchs** [comment]
The strace doesn't help while there's calls on the server. It would only be helpful while it's idle.

But seeing the ksoftirqd so high makes me suspect that this is an issue with the underlying VM and has nothing to do with rtpengine itself.

**Comment by ewsamuels** [comment]
I was thinking the same also but will investigate further.

**Comment by andycol** [comment]
I notice this is also happening on a bare metal machine and the load is maxed by ksoftirqd
we are running debian 9, do you guys recommend any other OS or version perhaps?

**Comment by ewsamuels** [comment]
@rfuchs there is something interesting that I discovered!

We moved the rtpengine to a 12 core dedicated box and got the same issue with ksoftirqd maxing out the CPU.   The image below is from the dedicated Box .

![screen shot 2018-12-07 at 13 22 02](https://user-images.githubusercontent.com/5496519/49650158-413b3a00-fa23-11e8-9ded-1ceebb868e70.png)

We could not find what was causing the ksoftirqd to spike like that so I thought to flush IPTables.  After flushing IPTables that high cpu usage of ksoftirq went away immediately and we monitored ksoftirqd for a while.  
Then I decided to just add just the single iptables rule on both the VM and the Dedicated box:

`iptables -I INPUT -p udp -j RTPENGINE --id 0`

and within a few seconds of adding that rule there was that huge spike again.  I remove the rule and it disappears although rtpengine does show about 200% cpu but we know its because rtpengine not doing In-kernel packet forwarding.

Any ideas?

**Comment by rfuchs** [comment]
Post the contents of /proc/rtpengine/ID/list while you see ksoftirqd spiking

**Comment by ewsamuels** [comment]
Hi @rfuchs 

Please see the results attached.
[test1.txt](https://github.com/sipwise/rtpengine/files/2657497/test1.txt)

**Comment by rfuchs** [comment]
Ok, just what I thought.
```
local inet4 1.1.1.37:19060
       src inet4 1.1.1.37:19042
       dst inet4 1.1.1.37:19060
    stats:            310713440 bytes,              9709795 packets,                    0 errors
        RTP payload type   8:                    0 bytes,                    0 packets
        RTP payload type  18:            310713504 bytes,              9709797 packets
```
You created a forwarding loop. Packets received on 1.1.1.37:19060 are forwarded to 1.1.1.37:19060.

**Comment by andycol** [comment]
> Ok, just what I thought.
> 
> ```
> local inet4 1.1.1.37:19060
>        src inet4 1.1.1.37:19042
>        dst inet4 1.1.1.37:19060
>     stats:            310713440 bytes,              9709795 packets,                    0 errors
>         RTP payload type   8:                    0 bytes,                    0 packets
>         RTP payload type  18:            310713504 bytes,              9709797 packets
> ```
> You created a forwarding loop. Packets received on 1.1.1.37:19060 are forwarded to 1.1.1.37:19060.

@rfuchs What do you think would cause this loop?

**Comment by rfuchs** [comment]
Some problem in your signalling or network configuration.

**Comment by andycol** [comment]
> Some problem in your signalling or network configuration.

can you perhaps give me some guidance of where to look to fix it?

**Comment by rfuchs** [comment]
Run rtpengine with log level 7, wait for the problem to occur, look in the /proc list to identify the culprit port (like 19060 in the example above), look in the log to identify which call that port belongs to (search for a string like `port 19060`), then use that call ID to see in the log what happened during the signalling in that call.

**Comment by andycol** [comment]
> Run rtpengine with log level 7, wait for the problem to occur, look in the /proc list to identify the culprit port (like 19060 in the example above), look in the log to identify which call that port belongs to (search for a string like `port 19060`), then use that call ID to see in the log what happened during the signalling in that call.

Do you offer commercial support?

**Comment by ewsamuels** [comment]
Hello @rfuchs,

Thank you for your assistance with this.  

With regards to the forwarding loop we we doing bypass-media on Freeswitch and using Kamailio as Outbound Proxy.  At the moment we have Freeswitch back into the media so as to avoid that forwarding loop with the RTP and we have some stability with rtpengine load very low as expected.

Tonight after hours we will make some further test with Freeswitch in Transparent Proxy mode and with bypass media on the internal profile to see the difference and report back tomorrow.

Thanks again

**Comment by goharahmed** [comment]
Hi All,

This seems like an interesting situation. @andycol if I'm right you're bypassing media from FreeSWITCH and still engaging RTPEngine for both incoming legs and outgoing leg on Kamailio/rtpengine. So the RTPEngine interfacing the FS boxes creates this "forward-loop" since FS doesn't modify the SDP?

If that is correct then @rfuchs is there any function where we can tell RTPEngine to NOT create this forward loop since "A Leg's outbound SDP" is essentially the same as "B Leg's incoming SDP" - I guess all we need to do is tell RTPEngine of this relation i.e (its single call). 

I believe the only reason this is happening is because of different "Call-ID" due to B2BUA involvement. 

Is there a better way to handle this scenario? This is closest to what I can imagine as bridging b/w two subnets except the user doesnt want the B2BUA pool to create extra hop for media (additional badnwidth costs etc)

Thanks,
Gohar

**Comment by rfuchs** [comment]
The proper way to solve media loops like this is from the signalling side. If it's possible for the media proxy to be engaged in a loop, then the SIP proxy should make sure that this doesn't happen.

If that's not achievable, then the `loop-protect` flag can be used to keep rtpengine from acting on its own SDPs. But doing that can break legitimate use cases.
