### ISSUE TITLE
when rtpengine working in kernel module, it can't transcode correctly

### ISSUE THREAD

**Issue by Sunldon** [sipwise/rtpengine#672]
My environment is : 

    softphone A(10.10.18.203) G711 uLaw <-->(10.10.200.55)kamailio+rtpengine(192.168.200.55)<-->softphone B(192.168.18.45) G711 uLaw

the start option of daemon is : 

    ./rtpengine -n 127.0.0.1:7722 --interface=pub/10.10.200.55 --interface=priv/192.168.200.55 --log-facility=local3 --num-threads=32 --no-fallback --table=0 --tos=184

In the kamailio.cfg, I configure rtpengine as:

    rtpengine_offer("codec-strip-all codec-transcode-PCMA codec-transcode-PCMU codec-transcode-G729 replace-origin replace-session-connection direction=pub direction=priv ICE=force ")
and

    rtpengine_answer();

I use iptables as:

    iptables -I INPUT -d 10.10.200.55 -p udp -j RTPENGINE --id 0
    iptables -I INPUT -d 192.168.200.55 -p udp -j RTPENGINE --id 0
After iptables set, through "iptables -nvL ", it's as show below:
```
    [root@localhost daemon]# iptables -nvL
Chain INPUT (policy ACCEPT 43191 packets, 5063K bytes)
 pkts bytes target     prot opt in     out     source               destination         
17625 1269K RTPENGINE  udp  --  *      *       0.0.0.0/0            10.10.200.55         RTPENGINE id:0
17673 3520K RTPENGINE  udp  --  *      *       0.0.0.0/0            192.168.200.55       RTPENGINE id:0

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 42718 packets, 14M bytes)
 pkts bytes target     prot opt in     out     source               destination   
```
When softphone A and softphone B use G711 uLaw codec, it can see result through /proc/rtpengine/0/list: 
```
[root@localhost daemon]# cat /proc/rtpengine/0/list 
local inet4 192.168.200.55:30028
       src inet4 10.10.200.55:30030
       dst inet4 10.10.18.203:42254
    stats:               171828 bytes,                  999 packets,                    0 errors
        RTP payload type   0:               171828 bytes,                  999 packets
    option: stun
local inet4 10.10.200.55:30030
       src inet4 192.168.200.55:30028
       dst inet4 192.168.18.45:5062
    stats:               172000 bytes,                 1000 packets,                    0 errors
        RTP payload type   0:               172000 bytes,                 1000 packets

```

But when I change the softphone A codec to G729, the environment is : 
   
    softphone A(10.10.18.203) G729 <-->(10.10.200.55)kamailio+rtpengine(192.168.200.55)<-->softphone B(192.168.18.45) G711 uLaw

the rtpengine can't work correctly, the fail result can see through /proc/rtpengine/0/list: 
```
[root@localhost daemon]# cat /proc/rtpengine/0/list 
local inet4 192.168.200.55:30062
       src inet4 10.10.200.55:30052
       dst inet4 10.10.18.203:45434
    stats:                    0 bytes,                    0 packets,                    0 errors
        RTP payload type  18:                    0 bytes,                    0 packets
    option: stun
    option: transcoding
local inet4 10.10.200.55:30052
       src inet4 192.168.200.55:30062
       dst inet4 192.168.18.45:5062
    stats:                    0 bytes,                    0 packets,                    0 errors

```

I add the some debug code in xt_RTPENGINE.c as  : 
```

static inline int rtp_payload_type(const struct rtp_header *hdr, const struct rtpengine_target_info *tg) {
	unsigned char pt, *match;

	pt = hdr->m_pt & 0x7f;
	unsigned char *pl=&(tg->payload_types);

	DBG("rtp_payload_type pt=0x%x tg->num_payload_types=%d \n",pt,tg->num_payload_types);
	DBG("payload_types = 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x \n",pl[0],pl[1],pl[2],pl[3],pl[4],pl[5],pl[6],pl[7],pl[8],pl[0],pl[10],pl[11],pl[12],pl[13],pl[14],pl[15]);

	match = bsearch(&pt, tg->payload_types, tg->num_payload_types, sizeof(pt), rtp_payload_match);
	if (!match){
		return -1;
	}
	return match - tg->payload_types;
}
```

The dmesg result is : 
```
[ 9134.984543] [PID 1967 line 673] ref_get(ffff8802347ac000) - refcnt is 1
[ 9134.984551] [PID 1967 line 3919] udp payload = 32
[ 9134.984557] [PID 1967 line 1598] re_address_match 10.10.200.55 10.10.200.55 
[ 9134.984568] [PID 1967 line 3929] target found, src 2:c0a8c837000000000000000000000000:30062 -> dst 2:c0a8122d000000000000000000000000:5062
[ 9134.984571] [PID 1967 line 3931] target decrypt hmac and cipher are NULL and NULL
[ 9134.984575] [PID 1967 line 3499] rtp header parsed, payload length is 20
[ 9134.984578] [PID 1967 line 3835] rtp_payload_type pt=0x12 tg->num_payload_types=0 
[ 9134.984583] [PID 1967 line 3836] payload_types = 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 
[ 9134.984588] [PID 1967 line 3988] rtp_pt_idx =  rtp_payload_type(rtp.header, &g->target); =-1 

[ 9135.000202] [PID 1967 line 673] ref_get(ffff8802347ac000) - refcnt is 1
[ 9135.000203] [PID 1967 line 3919] udp payload = 172
[ 9135.000205] [PID 1967 line 1598] re_address_match 192.168.200.55 192.168.200.55 
[ 9135.000207] [PID 1967 line 3929] target found, src 2:0a0ac837000000000000000000000000:30052 -> dst 2:0a0a12cb000000000000000000000000:45434
[ 9135.000207] [PID 1967 line 3931] target decrypt hmac and cipher are NULL and NULL
[ 9135.000208] [PID 1967 line 3499] rtp header parsed, payload length is 160
[ 9135.000208] [PID 1967 line 3835] rtp_payload_type pt=0x0 tg->num_payload_types=1 
[ 9135.000210] [PID 1967 line 3836] payload_types = 0x12 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x12 0x0 0x0 0x0 0x0 0x0 0x0 
[ 9135.000210] [PID 1967 line 3988] rtp_pt_idx =  rtp_payload_type(rtp.header, &g->target); =-1 

[ 9135.004568] [PID 0 line 673] ref_get(ffff8802347ac000) - refcnt is 1
[ 9135.004571] [PID 0 line 3919] udp payload = 32
[ 9135.004572] [PID 0 line 1598] re_address_match 10.10.200.55 10.10.200.55 
[ 9135.004574] [PID 0 line 3929] target found, src 2:c0a8c837000000000000000000000000:30062 -> dst 2:c0a8122d000000000000000000000000:5062
[ 9135.004575] [PID 0 line 3931] target decrypt hmac and cipher are NULL and NULL
[ 9135.004576] [PID 0 line 3499] rtp header parsed, payload length is 20
[ 9135.004577] [PID 0 line 3835] rtp_payload_type pt=0x12 tg->num_payload_types=0 
[ 9135.004578] [PID 0 line 3836] payload_types = 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 
[ 9135.004579] [PID 0 line 3988] rtp_pt_idx =  rtp_payload_type(rtp.header, &g->target); =-1 

[ 9135.020220] [PID 0 line 673] ref_get(ffff8802347ac000) - refcnt is 1
[ 9135.020223] [PID 0 line 3919] udp payload = 172
[ 9135.020225] [PID 0 line 1598] re_address_match 192.168.200.55 192.168.200.55 
[ 9135.020227] [PID 0 line 3929] target found, src 2:0a0ac837000000000000000000000000:30052 -> dst 2:0a0a12cb000000000000000000000000:45434
[ 9135.020228] [PID 0 line 3931] target decrypt hmac and cipher are NULL and NULL
[ 9135.020229] [PID 0 line 3499] rtp header parsed, payload length is 160
[ 9135.020230] [PID 0 line 3835] rtp_payload_type pt=0x0 tg->num_payload_types=1 
[ 9135.020231] [PID 0 line 3836] payload_types = 0x12 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x12 0x0 0x0 0x0 0x0 0x0 0x0 
[ 9135.020232] [PID 0 line 3988] rtp_pt_idx =  rtp_payload_type(rtp.header, &g->target); =-1 


```

It seems that there is a problem with the two variables **"tg->payload_types" and "tg->num_payload_types"** . I dont know how the  **"tg->payload_types" and "tg->num_payload_types"** interact with userspace (or iptables) to get correct value. 

The rtpengine debug log is as below:
[rtpengine.log](https://github.com/sipwise/rtpengine/files/2662401/rtpengine.log)

**Comment by rfuchs** [comment]
I'm not sure I understand the problem. What is it that you're expecting to see instead?

**Comment by Sunldon** [comment]
But when I change the softphone A codec to G729, is /proc/rtpengine/0/list is : 
[root@localhost daemon]# cat /proc/rtpengine/0/list 
local inet4 192.168.200.55:30062
       src inet4 10.10.200.55:30052
       dst inet4 10.10.18.203:45434
    **stats:                    0 bytes,                    0 packets,                    0 errors**
        RTP payload type  18:                    0 bytes,                    0 packets
    option: stun
    option: transcoding
local inet4 10.10.200.55:30052
       src inet4 192.168.200.55:30062
       dst inet4 192.168.18.45:5062
    **stats:                    0 bytes,                    0 packets,                    0 errors**

The stats is " 0 bytes,   0 packets,  0 errors". The rtp packets can't forward  properly in kernel. 
If the softphone A codec is same as softphone B (G711 u Law), The rtp packets can forward  properly in kernel.

**Comment by rfuchs** [comment]
Yes, the kernel doesn't do transcoding. Only the userspace daemon does. So when a call needs transcoding, the kernel stats will show zero.

**Comment by Sunldon** [comment]
Thank you for your help, I have already understand this issue now.

**Comment by Sunldon** [comment]
I want to confirm that, if a call needs transcoding, is it the daemon forwarding packet or the kernel forwarding packet?

**Comment by rfuchs** [comment]
It depends. With transcoding enabled for a call, packets that carry RTP payload types (codecs) that must be transcoded will be handled, transcoded, and forwarded by the daemon, while packets that carry RTP payload types that do not need transcoding will be forwarded by the kernel module.

In `/proc/rtpengine/ID/list`, in entries with `option: transcoding` enabled, the printed list of payload types is the list of payload types handled and forwarded by the kernel module. Packets received with other payload types not shown in the list are passed to the daemon.

**Comment by Sunldon** [comment]
At my situtation: 
```
softphone A(10.10.18.203) G729 <-->(10.10.200.55)kamailio+rtpengine(192.168.200.55)<-->softphone B(192.168.18.45) G711 uLaw

[root@localhost daemon]# cat /proc/rtpengine/0/list 
local inet4 192.168.200.55:30062
       src inet4 10.10.200.55:30052
       dst inet4 10.10.18.203:45434
    stats:                    0 bytes,                    0 packets,                    0 errors
        RTP payload type  18:                    0 bytes,                    0 packets
    option: stun
    option: transcoding
local inet4 10.10.200.55:30052
       src inet4 192.168.200.55:30062
       dst inet4 192.168.18.45:5062
    stats:                    0 bytes,                    0 packets,                    0 errors
```
My understand is :  The packets of RTP payload type equal to 18 (G729) are forwarded by kernel module, and another packets of RTP payload type (G711 uLaw) are passed to the daemon. Is it right?

**Comment by Sunldon** [comment]
Thanks.
