### ISSUE TITLE
In some cases call from chrome webrtc to webrtc problem with ssrc (no video)

### ISSUE THREAD

**Issue by Vladvladd** [sipwise/rtpengine#673]
Hello!
In some cases when call from webrtc chrome A -> kamailio -> rtpengine -> asterisk -> rtpengine -> kamailio -> webrtc chrome B with video chrome not see correct ssrc for video frame and not show video. More details in attachment file (tcpdump.txt is tcpdump file - tcpdump.pcap, debug of rtpengine - no_video_rtpengine_debug.txt , screen of chrome webinternals - 1_chrome.png, 2_chrome.png). Also Can you describe algorithm of creating new ssrc ?
[no_video_rtpengine_debug.txt](https://github.com/sipwise/rtpengine/files/2662587/no_video_rtpengine_debug.txt) 
[tcpdump.txt](https://github.com/sipwise/rtpengine/files/2662597/tcpdump.txt)
![1_chrome](https://user-images.githubusercontent.com/45755707/49724717-a173eb00-fc72-11e8-9294-3fead1a59346.png)
![2_chrome](https://user-images.githubusercontent.com/45755707/49724722-a3d64500-fc72-11e8-814f-9dcd19f43d49.png)

**Comment by rfuchs** [comment]
The SSRC is only touched when transcoding is engaged in the call in some way. Otherwise it passes through unchanged. Can you be more specific about what exactly the issue is that you're seeing?

**Comment by Vladvladd** [comment]
I this case ssrc 271137176, 1535076722, 1081692434 which send by srtcp packets not sip packets as other ssrc - not shown in chrome chrome://webrtc-internals/. And if see Conn-video from side A bytesSent video 258828, but in side B byteReceived 1513. And as final - we not see video.

**Comment by rfuchs** [comment]
The SSRCs you mention are not coming from rtpengine, at least as shown in the log. 271137176 is a translation of 2347531305, which happens for packets received on port 10440 and sent back out from port 10264. The log says that these ports are both coming from external clients and are not rtpengine ports. The same is true for 1535076722, which is a translation from 3962141150 via ports 10264 and 10440 (opposite direction). 1081692434 is a translation of 73513056 via 10440 and 10264 (also same ports). Again these are not rtpengine ports according to the log.

Also the log shows that there seem to be 2 distinct calls going on, at least one of them having a call leg that is not WebRTC (RTP/AVP on 10264 and RTP/AVPF on 10440). Lack of required RTCP feedback messages might be why you're not seeing video.

**Comment by rfuchs** [comment]
Cleaning up old tickets
