### ISSUE TITLE
one way audio in transcoding --ng and loop

### ISSUE THREAD

**Issue by iman432** [sipwise/rtpengine#675]
Hi all

i force A-Side on GSM and B-Side on AMR and i did below changes in rtp.cfg of kamailio but when A-Side calls to B-Side only A-Side has sound of B-Side and B-side hasnt sound of A-Side and when B-side calls to A-side just B-side has A-side sound and A-side hasnt B-side sound 

route[ENC_RTP] {
        add_rr_param(";rm=7");
        $avp(rtpproxy_offer_flags) = "replace-origin replace-session-connection ICE=force transcode-GSM transcode-AMR RTP AVP";
        $avp(rtpproxy_answer_flags) = "replace-origin replace-session-connection ICE=remove RTP AVP";
}

route[DEC_RTP] {
        add_rr_param(";rm=8");
        $avp(rtpproxy_offer_flags) = "replace-origin replace-session-connection ICE=remove RTP AVP";
        $avp(rtpproxy_answer_flags) = "replace-origin replace-session-connection ICE=force RTP AVP";

of course loop problem exist: 
ERR: [MjYxZGI4NDRkNThjYzExMWQ5YTAzYmRkYWVhODhkZGY. port 33209]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible

this loop only happens when A-Side calls to B-Side.

in sdp offers and answer everthing is ok and client and servers are in same range of ip for discarding NAT problems

where is problem?

Thanks in advance

**Comment by rfuchs** [comment]
Post a debug log?

**Comment by iman432** [comment]
sure
[AMR-GSM.txt](https://github.com/sipwise/rtpengine/files/2676891/AMR-GSM.txt)
[GSM-AMR.txt](https://github.com/sipwise/rtpengine/files/2676892/GSM-AMR.txt)

**Comment by rfuchs** [comment]
That doesn't include debug level log messages. Use log level 7.

**Comment by iman432** [comment]
ok
[AMR-GSM.txt](https://github.com/sipwise/rtpengine/files/2677003/AMR-GSM.txt)
[GSM-AMR.txt](https://github.com/sipwise/rtpengine/files/2677004/GSM-AMR.txt)

**Comment by rfuchs** [comment]
You have a problem with your signalling. You're looping the output SDP generated by rtpengine back into rtpengine as an input. That's broken signalling, breaks media flow, and causes the loop errors you see.

```
Dec 13 20:40:30 P-CSCF rtpengine[2816]: DEBUG: [1cf3da94f129447292e8cdff62ce7d1b]: Response dump for 'offer' to 127.0.0.1:39518: { "sdp": "v=0
o=- 3753722430 3753722430 IN IP4 10.25.5.120
s=pjmedia
b=AS:29
t=0 0
a=X-nat:0
m=audio 30064 RTP/AVP 120 101
c=IN IP4 10.25.5.120
b=TIAS:12200
a=ssrc:567501065 cname:0ace261f6e6a5b80
a=rtpmap:120 AMR/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:120 octet-align=1
a=fmtp:101 0-16
a=sendrecv
a=rtcp:30065
", "result": "ok" }
Dec 13 20:40:30 P-CSCF kamailio[2857]: 21(2895) ERROR: <script>: INVITE (sip:411@mnc001.mcc001.3gppnetwork.org (10.25.5.121:6060) to sip:60@mnc001.mcc001.3gppnetwork.org, 1cf3da94f129447292e8cdff62ce7d1b)
Dec 13 20:40:30 P-CSCF rtpengine[2816]: INFO: [1cf3da94f129447292e8cdff62ce7d1b]: Received command 'offer' from 127.0.0.1:48546
Dec 13 20:40:30 P-CSCF rtpengine[2816]: DEBUG: [1cf3da94f129447292e8cdff62ce7d1b]: Dump for 'offer' from 127.0.0.1:48546: { "sdp": "v=0
o=- 3753722430 3753722430 IN IP4 10.25.5.120
s=pjmedia
b=AS:29
t=0 0
a=X-nat:0
m=audio 30064 RTP/AVP 120 101
c=IN IP4 10.25.5.120
b=TIAS:12200
a=ssrc:567501065 cname:0ace261f6e6a5b80
a=rtpmap:120 AMR/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:120 octet-align=1
a=fmtp:101 0-16
a=sendrecv
a=rtcp:30065
", "ICE": "force", "flags": [ "transcode-AMR", "transcode-GSM" ], "replace": [ "origin", "session-connection" ], "transport-pro ...
Dec 13 20:40:30 P-CSCF rtpengine[2816]: DEBUG: [1cf3da94f129447292e8cdff62ce7d1b]: ... tocol": "RTP/AVP", "call-id": "1cf3da94f129447292e8cdff62ce7d1b", "received-from": [ "IP4", "10.25.5.121" ], "from-tag": "8b53663d1e2244f4926ec4480eccb5a5", "command": "offer" }
```

**Comment by iman432** [comment]
Thanks for checking but where I did wrong that output media back into rtpengine as input media?and loop causes one way sound?

**Comment by rfuchs** [comment]
It's probably in your SIP proxy config/script somewhere. You can use the `loop-protect` flag to make rtpengine refuse to work on its own SDPs, but I highly recommend debugging your SIP setup instead and find the root cause of why you're looping the signalling like this.

**Comment by iman432** [comment]
when i add flags=loop protect,rtpengine dosent transcode anymore.

$avp(rtpproxy_offer_flags) = "replace-origin replace-session-connection flags=loop protect ICE=force transcode-AMR transcode-GSM RTP-AVP

**Comment by iman432** [comment]
Yes you are right,that works and loop is discarded and one way sound was solve with below command in rtp.cfg 

route[ENC_RTP] {
add_rr_param(";rm=7");
$avp(rtpproxy_offer_flags) = "replace-origin replace-session-connection loop-protect ICE=force transcode-GSM transcode-AMR RTP AVP";
$avp(rtpproxy_answer_flags) = "replace-origin replace-session-connection ICE=remove RTP AVP";
}

route[DEC_RTP] {
add_rr_param(";rm=8");
$avp(rtpproxy_answer_flags) = "replace-origin replace-session-connection ICE=force RTP AVP";

Thanks for support
