### ISSUE TITLE
Question regarding RTPEngine Volume

### ISSUE THREAD

**Issue by greenfieldtech-nirs** [sipwise/rtpengine#679]
Is there a way to control the volume of specific codec paths? 

For example, let's imagine I'm transcoding from Opus to ULAW. Is there a way to make rtpengine increase the audio on Opus (in both directions) by a preset factor?

I tried looking into the documentation, but couldn't find anything like this.

**Comment by rfuchs** [comment]
No there's no feature like that. Wouldn't be difficult to implement though since there's always PCM in between.

**Comment by rfuchs** [comment]
Cleaning up old tickets
