### ISSUE TITLE
rtpengine not converting savpf to savp

### ISSUE THREAD

**Issue by donfanning** [sipwise/rtpengine#68]
Hello all,

The target machine I am trying to connect to (openmcu) does not support SAVPF so I'm trying to use rtpengine to convert the packet to SAVP but nothing is converted.

http://pastebin.com/Whqz38xJ - is the output from the rtpengine/kamailio logs.

I'm currently using this to convert:   rtpengine_manage("transport-protocol=UDP/TLS/RTP/SAVP replace-session-connection ICE=force_relay replace-origin symmetric trust-address force");

Thanks for any help!

**Comment by rfuchs** [comment]
Try with ICE=force instead of force-relay. With force-relay, rtpengine cannot guarantee that the media actually passes through itself, and therefore it enables passthrough mode, as can be seen in the log.

**Comment by donfanning** [comment]
Thanks!  That forced the packet to SAVP.
