### ISSUE TITLE
Compile question on Centos 7

### ISSUE THREAD

**Issue by gethubsw** [sipwise/rtpengine#682]
Hello,

I have the following compile issue on Centos 7

 make rtpengine
make[1]: Entering directory `/usr/local/src/rtpengine/daemon'
cc  -g -Wall -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include
-pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include      
-pthread -I/usr/include/libxml2 -I/usr/include/libxml2  
-pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include    
-DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg
-I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   
-DWITH_TRANSCODING -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DRTPENGINE_VERSION="\"git-master-0e129ed\"" 
-O3 -o rtpengine main.o kernel.o poller.o aux.o control_tcp.o streambuf.o call.o control_udp.o redis.o bencode.o 
cookie_cache.o udp_listener.o control_ng.strhash.o sdp.strhash.o stun.o rtcp.o crypto.o rtp.o call_interfaces.strhash.o 
dtls.o log.o cli.o graphite.o ice.o socket.o media_socket.o homer.o recording.o statistics.o cdr.o ssrc.o iptables.o 
tcp_listener.o codec.o load.o dtmf.o loglib.o auxlib.o rtplib.o str.o codeclib.o resample.o -lm -lglib-2.0   
-pthread -lgthread-2.0 -lglib-2.0   -lz   -lpcre   -lcrypto   -lssl -lcrypto   -levent_pthreads -levent   
-lpcap -lxmlrpc_client   -lxmlrpc   -lxmlrpc_util   -lhiredis -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0   
-lip4tc -lip6tc   -lavcodec   -lavformat   -lavutil   -lswresample   -lavfilter
main.o: In function `options':
/usr/local/src/rtpengine/daemon/main.c:308: undefined reference to `dtls_passive_def'
/usr/local/src/rtpengine/daemon/main.c:514: undefined reference to `trust_address_def

Am I missing a library?

Thank you!

**Comment by rfuchs** [comment]
Probably an incomplete source checkout or the build directly not cleaned before building. Or maybe a problem with your `gperf` which is the only new dependency.

**Comment by gethubsw** [comment]
The issue was gperf.  I reinstalled gperf and now rtpengine compiles.

Thank you!
