### ISSUE TITLE
SDP -101 missing

### ISSUE THREAD

**Issue by nicoonline** [sipwise/rtpengine#686]
Hello,

RtpEngine 6.4.1 
I suspect something wrong in the rewrite.... It's rejected by the carrier 

I get a re-invite for a t38 transmission;

What i receive is : 
o=UserA 3272146361 4237707437 IN IP4 192.168.2.2.
s=Session SDP.
c=IN IP4 192.168.2.2.
t=0 0.
m=audio 0 RTP/AVP 8 101.
m=image 49158 udptl t38.
c=IN IP4 192.168.2.2.
a=T38FaxVersion:0.
a=T38FaxRateManagement:transferredTCF.

transformed in 
(xxx = ip address >OK)

o=Media*Proxy1 3272146361 4237707437 IN IP4 xxxx
c=IN IP4 xxx
t=0 0.
m=audio 0 RTP/AVP 8 101.
a=rtpmap:8 PCMA/8000.
a=rtpmap:101 .
m=image 14972 udptl t38.
c=IN IP4 xxx.
a=T38FaxVersion:0.
a=T38FaxRateManagement:transferredTCF.
a=sendrecv.

The error is line "a=rtpmap:101 . "

**Comment by nicoonline** [comment]
Can you confirm it's a bug fixed just now ?

**Comment by rfuchs** [comment]
Yes, see the commits above.
