### ISSUE TITLE
Build error with 6.4.1.1-1.el7

### ISSUE THREAD

**Issue by dragonfly-net** [sipwise/rtpengine#687]
centos 7 x86_64
git clone https://github.com/sipwise/rtpengine.git rtpengine
git archive --output ~/rpmbuild/SOURCES/ngcp-rtpengine-6.4.1.1.tar.gz --prefix=rtpengine-mr6.4.1.1/ master
rpmbuild -ta ~/rpmbuild/SOURCES/ngcp-rtpengine-6.4.1.1.tar.gz

Out:
+ cd /home/builder/rpmbuild/BUILD
+ cd rtpengine-mr6.4.1.1
+ cd daemon
+ RTPENGINE_VERSION='"6.4.1.1-1.el7"'
+ make
Makefile:135: .depend: No such file or directory
../utils/const_str_hash < control_ng.c > control_ng.strhash.c
open2: exec of gperf -t -E -l -c -t -I -H __csh_hash -N __csh_lookup_raw failed at ../utils/const_str_hash line 37.
make: *** [control_ng.strhash.c] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.NDulzf (%build)

**Comment by rfuchs** [comment]
You probably need to install `gperf`

**Comment by rfuchs** [comment]
We don't maintain the RPM stuff. If you know how to fix it, please submit a pull request.
