### ISSUE TITLE
Restart Ip Tables

### ISSUE THREAD

**Issue by nicoonline** [sipwise/rtpengine#691]
Hello,

Any ideas how to deal with a restart of iptables, what is the consequences on a current call ?

**Comment by nicoonline** [comment]
i put the rules in /etc/sysconfig/iptables .
Before the rules were created in rtpengine.ini.

**Comment by nicoonline** [comment]
how can i verify if the stream is handled by the kernel module ? stopping iptables -> proxy still working.

**Comment by rfuchs** [comment]
If the iptables rule is removed or otherwise becomes defunct, packet forwarding will fall back to be handled in userspace. When the iptables rule is restored, in-kernel forwarding will resume. You can confirm it by looking at the packet stats in `/proc/rtpengine/$ID/list`. If the packet counters are increasing, then kernel forwarding is functional.

**Comment by nicoonline** [comment]
Hi,
Thanks. i checked and i see the call on the control/list but counters stays @0 

I put that on the top of my iptables files

-N rtpengine
-I INPUT -p udp --dport 10000:20000 -j rtpengine
-I rtpengine -j RTPENGINE --id 0

I have also an other chain below for the RTP flows called Sip_Carriers to Accept or Deny the flow:

-A INPUT -p udp --dport 10000:20000 -j SIP_Carriers
-A SIP_Carriers -s 1.1.1.1/32 -j ACCEPT

**Comment by nicoonline** [comment]
After one minute : 
[root@proxy2 sysconfig]# cat /proc/rtpengine/0/list 
local inet4 112.112.180.9:10456
       src inet4 112.112.180.9:10466
       dst inet4 91.171.20.203:42184
    stats:                    0 bytes,                    0 packets,                    0 errors
        RTP payload type   8:                    0 bytes,                    0 packets
    option: stun
local inet4 112.112.180.9:10466
       src inet4 112.112.180.9:10456
       dst inet4 112.110.38.228:27354
    stats:                    0 bytes,                    0 packets,                    0 errors
        RTP payload type   8:                    0 bytes,                    0 packets

**Comment by rfuchs** [comment]
The rules look fine. Any transcoding involved? Anything in the logs? The config is set to use table 0 as well?

**Comment by nicoonline** [comment]
Conf :
[rtpengine]
table = 0
no-fallback = false


Establish a call :

Jan 26 15:03:36 proxy2 rtpengine[31771]: INFO: [5b5ee695421c49bd601675466bec0556@proxy2.]: Received command 'offer' from 127.0.0.1:47955
Jan 26 15:03:36 proxy2 rtpengine[31771]: NOTICE: [5b5ee695421c49bd601675466bec0556@proxy2.]: Creating new call
Jan 26 15:03:36 proxy2 rtpengine[31771]: INFO: [5b5ee695421c49bd601675466bec0556@proxy2.]: Replying to 'offer' from 127.0.0.1:47955 (elapsed time 0.000326 sec)
Jan 26 15:03:37 proxy2 rtpengine[31771]: INFO: [5b5ee695421c49bd601675466bec0556@proxy2.]: Received command 'answer' from 127.0.0.1:52263
Jan 26 15:03:37 proxy2 rtpengine[31771]: INFO: [5b5ee695421c49bd601675466bec0556@proxy2.]: Replying to 'answer' from 127.0.0.1:52263 (elapsed time 0.000085 sec)
Jan 26 15:03:38 proxy2 rtpengine[31771]: INFO: [5b5ee695421c49bd601675466bec0556@proxy2.]: Received command 'answer' from 127.0.0.1:36269
Jan 26 15:03:38 proxy2 rtpengine[31771]: INFO: [5b5ee695421c49bd601675466bec0556@proxy2.]: Replying to 'answer' from 127.0.0.1:36269 (elapsed time 0.000079 sec)
Jan 26 15:03:42 proxy2 rtpengine[31771]: INFO: [5b5ee695421c49bd601675466bec0556@proxy2. port 10062]: Confirmed peer address as 11.171.20.203:42670
Jan 26 15:03:42 proxy2 rtpengine[31771]: INFO: [5b5ee695421c49bd601675466bec0556@proxy2. port 10040]: Confirmed peer address as 112.110.38.228:27136
Jan 26 15:03:42 proxy2 rtpengine[31771]: INFO: [5b5ee695421c49bd601675466bec0556@proxy2. port 10040]: Kernelizing media stream: 112.110.38.228:27136
Jan 26 15:03:42 proxy2 rtpengine[31771]: INFO: [5b5ee695421c49bd601675466bec0556@proxy2. port 10062]: Kernelizing media stream: 11.171.20.203:42670
Jan 26 15:03:42 proxy2 rtpengine[31771]: INFO: [5b5ee695421c49bd601675466bec0556@proxy2. port 10041]: Confirmed peer address as 112.110.38.228:27137
Jan 26 15:03:42 proxy2 rtpengine[31771]: INFO: [5b5ee695421c49bd601675466bec0556@proxy2. port 10063]: Confirmed peer address as 11.171.20.203:42671



[root@proxy2 ~]# ls /proc/rtpengine/
0  control  list
[root@proxy2 ~]# ls /proc/rtpengine/0/
blist  calls  control  list  status


In private, full config can be shared AND / OR remote access to the server 😊


De : Richard Fuchs <notifications@github.com>
Envoyé : samedi 26 janvier 2019 14:10
À : sipwise/rtpengine <rtpengine@noreply.github.com>
Cc : Nicolas Breuer <Nicolas.Breuer@belcenter.biz>; Author <author@noreply.github.com>
Objet : Re: [sipwise/rtpengine] Restart Ip Tables (#691)


The rules look fine. Any transcoding involved? Anything in the logs? The config is set to use table 0 as well?

**Comment by nicoonline** [comment]
Engine 6.5 build :)

**Comment by rfuchs** [comment]
Any transcoding involved?

**Comment by nicoonline** [comment]
nop G711 used.

**Comment by rfuchs** [comment]
Post the full output of `iptables -L -v -n`

**Comment by nicoonline** [comment]
Chain rtpengine (3 references)
 pkts bytes target     prot opt in     out     source               destination         
 7467 1490K RTPENGINE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            RTPENGINE id:0
28505 5691K RTPENGINE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            RTPENGINE id:0
58338   12M RTPENGINE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            RTPENGINE id:0

**Comment by nicoonline** [comment]
The top of :  
[root@proxy2 ~]# iptables -L -v -n
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 2489  497K rtpengine  udp  --  *      *       0.0.0.0/0            0.0.0.0/0           udp dpts:10000:20000 
13008 2597K rtpengine  udp  --  *      *       0.0.0.0/0            0.0.0.0/0           udp dpts:10000:20000 
42841 8554K rtpengine  udp  --  *      *       0.0.0.0/0            0.0.0.0/0           udp dpts:10000:20000 

I posted only the Rtpengine statistics

**Comment by nicoonline** [comment]
[root@proxy2 ~]# iptables -L -v -n
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 4964  991K rtpengine  udp  --  *      *       0.0.0.0/0            0.0.0.0/0           udp dpts:10000:20000 
    4   224 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0           
  355 84086 ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0           
.....
Chain rtpengine (1 references)
 pkts bytes target     prot opt in     out     source               destination         
 4964  991K RTPENGINE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            RTPENGINE id:0

**Comment by rfuchs** [comment]
Looks like it should work. Kernel version?

**Comment by nicoonline** [comment]
2.6.32-754.10.1.el6.x86_64

**Comment by nicoonline** [comment]
So in your opinion, the things are working well but no statistics ?

**Comment by rfuchs** [comment]
No. If the counters aren't increasing, then there's no kernel forwarding.

I'm guessing it's because of your very old kernel. Do you have a kernel >= 3.0 available? Older kernels aren't really supported any more.

**Comment by nicoonline** [comment]
No we are working with Centos 6.10 and the kernel is still 2.6.32. Do you have the possibility to test your module on 2.6.32 kernel ?

**Comment by nicoonline** [comment]
- I applied manually the modification in the .c file
- i built it 
- i copied the .ko file to /lib/modules/2.6.32-754.10.1.el6.x86_64/updates/
- restart rtpengine + restart iptables

same behavior - counters = 0

**Comment by nicoonline** [comment]
just have this message when i build

make -C /lib/modules/2.6.32-754.10.1.el6.x86_64/build M=/var/instapp/rtp-engine/rtp6.5/kernel-module O=/lib/modules/2.6.32-754.10.1.el6.x86_64/build modules
make[1]: Entering directory `/usr/src/kernels/2.6.32-754.10.1.el6.x86_64'
  CC [M]  /var/instapp/rtp-engine/rtp6.5/kernel-module/xt_RTPENGINE.o
/var/instapp/rtp-engine/rtp6.5/kernel-module/xt_RTPENGINE.c: In function ârtp_payload_typeâ:
/var/instapp/rtp-engine/rtp6.5/kernel-module/xt_RTPENGINE.c:3797: warning: assignment discards qualifiers from pointer target type
/var/instapp/rtp-engine/rtp6.5/kernel-module/xt_RTPENGINE.c: At top level:
/var/instapp/rtp-engine/rtp6.5/kernel-module/xt_RTPENGINE.c:3781: warning: ârtp_payload_matchâ defined but not used
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /var/instapp/rtp-engine/rtp6.5/kernel-module/xt_RTPENGINE.mod.o
  LD [M]  /var/instapp/rtp-engine/rtp6.5/kernel-module/xt_RTPENGINE.ko.unsigned
  NO SIGN [M] /var/instapp/rtp-engine/rtp6.5/kernel-module/xt_RTPENGINE.ko
make[1]: Leaving directory `/usr/src/kernels/2.6.32-754.10.1.el6.x86_64'

**Comment by nicoonline** [comment]
Ok i restarted the server. It's working well now !
Can you please put in the 6.5 branch.

Thanks for the modification !
