### ISSUE TITLE
SDES-no-SUITE flags don't work

### ISSUE THREAD

**Issue by vitalikvoip** [sipwise/rtpengine#692]
I'm using rtpengine 7.0.1.1 and opensips-2.4.
Due to one broken SIP client I have to turn off a couple of SDES crypto suites.
According to docs I just have to add SDES-no-SUITE to rtpengine_manage params. Opensips sends those flags to rtpgengine and here is how offer command looks like in traffic capture:
`3:ICE6:remove5:flagsl25:SDES-no-NULL_HMAC_SHA1_3225:SDES-no-NULL_HMAC_SHA1_80e7:call-id33:58f4ffc06d389b11-075612a4d8e9418e13:received-froml3:IP413:91.228.59.126e8:from-tag16:2ce11d047ab2f24c7:command5:offere`

Accepting this offer rtpengine ignores those flags and inserts mentioned crypto suites into its reply and write these log messages:
`Unknown 'SDES' flag encountered: 'no-NULL_HMAC_SHA1_32'`
`Unknown 'SDES' flag encountered: 'no-NULL_HMAC_SHA1_80'`

**Comment by rfuchs** [comment]
The `SDES-no` option isn't present in version 7.0.x. Upgrade to 7.1.
