### ISSUE TITLE
SDES-off is not working properly in forked calls scenario

### ISSUE THREAD

**Issue by korayvt** [sipwise/rtpengine#693]
When a call started from an SDES client and is forked to two different clients which one of them is SDES and the other one is DTLS, one crypto line remains in the offer response in DTLS case.

offer for the SDES client = "replace-origin replace-session-connection ICE=remove DTLS=off rtcp-mux-demux RTP/SAVPF"

offer for the DTLS client = "replace-origin replace-session-connection ICE=force DTLS=passive SDES-off rtcp-mux-offer UDP/TLS/RTP/SAVPF"

rtpengine log is the following:

Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: INFO: [icf04gvnaA]: Received command 'offer' from 172.21.145.73:63096
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Dump for 'offer' from 172.21.145.73:63096: { "sdp": "v=0#015#012o=905309769612 2510 1115 IN IP4 100.81.124.137#015#012s=Talk#015#012c=IN IP4 100.81.124.137#015#012t=0 0#015#012a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics#015#012m=audio 51242 RTP/SAVPF 96 97 0 8 101 98#015#012a=rtpmap:96 opus/48000/2#015#012a=fmtp:96 useinbandfec=0; maxplaybackrate=8000; maxptime=40; ptime=40; minptime=40; cbr=0;#015#012a=rtpmap:97 speex/8000#015#012a=fmtp:97 vbr=on#015#012a=rtpmap:101 telephone-event/48000#015#012a=rtpmap:98 telephone-event/8000#015#012a=crypto ...
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: ... :1 AES_CM_128_HMAC_SHA1_80 inline:PjEpSwBQlpQ2YyNwK/YyMqhaaYRxLwAcTkyYECc+#015#012a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:d/2iVSNfxRABUpFx/r1MTJe88H4dO3fHiyrnAAX1#015#012a=crypto:3 AES_256_CM_HMAC_SHA1_80 inline:1gmaxD9Kl6vqHoAmnV4/g4jhqx5ZpCpeCyrZ+CVGHghP/+4M3zsjtnFGUjYEOA==#015#012a=crypto:4 AES_256_CM_HMAC_SHA1_32 inline:+kOH+BeGyOvwoE42030a4hrwFVkKmq3wjzKO5KC7DHeZH2vRwiHDC2pt71SFnQ==#015#012a=rtcp-fb:* trr-int 5000#015#012a=rtcp-fb:* ccm tmmbr#015#012m=video 54116 RTP/SAVPF 96 97#015#012a=rtpmap:96 H264/90000#015#012a=fmtp:96 profile-le ...
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: ... vel-id=42801F#015#012a=rtpmap:97 VP8/90000#015#012a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:cJOJ7kxQjhFBp2fP6AYjs3vKw7CeBdWZCj0isbJv#015#012a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:VAzLKvoE3jG9cdH/AZsl/ZqWNXrUzyM4Gw6chrFr#015#012a=crypto:3 AES_256_CM_HMAC_SHA1_80 inline:8AbZePWwsKhLGX3GlXA+yHYPQ3cgraer/9DkFJYCOPZZy3o9wC0NIbIFYZfyHw==#015#012a=crypto:4 AES_256_CM_HMAC_SHA1_32 inline:2GLk3p/csdno4KlGO1TxCVaEt+bifmDlQ5NjnCb5cJYPURiGRSTBEtEq37db8g==#015#012a=rtcp-fb:* trr-int 5000#015#012a=rtcp-fb:* ccm tmmbr#015#012a=rtcp-fb:96 nack pli#015#012a=rtcp ...
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: ... -fb:96 ccm fir#015#012a=rtcp-fb:97 nack pli#015#012a=rtcp-fb:97 nack sli#015#012a=rtcp-fb:97 ack rpsi#015#012a=rtcp-fb:97 ccm fir#015#012", "ICE": "remove", "DTLS": "off", "replace": [ "origin", "session-connection" ], "call-id": "icf04gvnaA", "received-from": [ "IP4", "178.243.126.179" ], "from-tag": "QezW2loeE", "command": "offer" }
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: ERR: [icf04gvnaA]: Failed to parse a=crypto attribute, ignoring: unknown crypto suite
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: ERR: [icf04gvnaA]: Failed to parse a=crypto attribute, ignoring: unknown crypto suite
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: ERR: [icf04gvnaA]: Failed to parse a=crypto attribute, ignoring: unknown crypto suite
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: ERR: [icf04gvnaA]: Failed to parse a=crypto attribute, ignoring: unknown crypto suite
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: NOTICE: [icf04gvnaA]: Creating new call
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Default sink codec is opus/48000/2
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Creating codec handler for opus/48000/2
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Sink supports codec opus/48000/2
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Creating codec handler for speex/8000
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Creating codec handler for PCMU/8000
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Sink supports codec PCMU/8000
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Creating codec handler for PCMA/8000
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Sink supports codec PCMA/8000
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Creating codec handler for telephone-event/48000
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Creating codec handler for telephone-event/8000
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: set FILLED flag for stream 100.81.124.137:51242
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: set FILLED flag for stream 100.81.124.137:51243
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Creating codec handler for H264/90000
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Creating codec handler for VP8/90000
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: set FILLED flag for stream 100.81.124.137:54116
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: set FILLED flag for stream 100.81.124.137:54117
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: INFO: [icf04gvnaA]: Replying to 'offer' from 172.21.145.73:63096 (elapsed time 0.000547 sec)
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Response dump for 'offer' to 172.21.145.73:63096: { "sdp": "v=0#015#012o=905309769612 2510 1115 IN IP4 86.108.185.102#015#012s=Talk#015#012c=IN IP4 86.108.185.102#015#012t=0 0#015#012a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics#015#012m=audio 10158 RTP/SAVPF 96 97 0 8 101 98#015#012a=rtcp-fb:* trr-int 5000#015#012a=rtcp-fb:* ccm tmmbr#015#012a=rtpmap:96 opus/48000/2#015#012a=rtpmap:97 speex/8000#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:101 telephone-event/48000#015#012a=rtpmap:98 telephone-event/8000#015#012a=fmtp:96 useinban ...
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: ... dfec=0; maxplaybackrate=8000; maxptime=40; ptime=40; minptime=40; cbr=0;#015#012a=fmtp:97 vbr=on#015#012a=sendrecv#015#012a=rtcp:10159#015#012a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:PjEpSwBQlpQ2YyNwK/YyMqhaaYRxLwAcTkyYECc+#015#012m=video 10180 RTP/SAVPF 96 97#015#012a=rtcp-fb:* trr-int 5000#015#012a=rtcp-fb:* ccm tmmbr#015#012a=rtcp-fb:96 nack pli#015#012a=rtcp-fb:96 ccm fir#015#012a=rtcp-fb:97 nack pli#015#012a=rtcp-fb:97 nack sli#015#012a=rtcp-fb:97 ack rpsi#015#012a=rtcp-fb:97 ccm fir#015#012a=rtpmap:96 H264/90000#015#012a=rtpmap:97 VP8/90000#015#012a=fmtp:96 profile-level-id=42801F#015#012 ...
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: ... a=sendrecv#015#012a=rtcp:10181#015#012a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:cJOJ7kxQjhFBp2fP6AYjs3vKw7CeBdWZCj0isbJv#015#012", "result": "ok" }
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: INFO: [icf04gvnaA]: Received command 'offer' from 172.21.145.73:63096
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Dump for 'offer' from 172.21.145.73:63096: { "sdp": "v=0#015#012o=905309769612 2510 1115 IN IP4 100.81.124.137#015#012s=Talk#015#012c=IN IP4 100.81.124.137#015#012t=0 0#015#012a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics#015#012m=audio 51242 RTP/SAVPF 96 97 0 8 101 98#015#012a=rtpmap:96 opus/48000/2#015#012a=fmtp:96 useinbandfec=0; maxplaybackrate=8000; maxptime=40; ptime=40; minptime=40; cbr=0;#015#012a=rtpmap:97 speex/8000#015#012a=fmtp:97 vbr=on#015#012a=rtpmap:101 telephone-event/48000#015#012a=rtpmap:98 telephone-event/8000#015#012a=crypto ...
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: ... :1 AES_CM_128_HMAC_SHA1_80 inline:PjEpSwBQlpQ2YyNwK/YyMqhaaYRxLwAcTkyYECc+#015#012a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:d/2iVSNfxRABUpFx/r1MTJe88H4dO3fHiyrnAAX1#015#012a=crypto:3 AES_256_CM_HMAC_SHA1_80 inline:1gmaxD9Kl6vqHoAmnV4/g4jhqx5ZpCpeCyrZ+CVGHghP/+4M3zsjtnFGUjYEOA==#015#012a=crypto:4 AES_256_CM_HMAC_SHA1_32 inline:+kOH+BeGyOvwoE42030a4hrwFVkKmq3wjzKO5KC7DHeZH2vRwiHDC2pt71SFnQ==#015#012a=rtcp-fb:* trr-int 5000#015#012a=rtcp-fb:* ccm tmmbr#015#012m=video 54116 RTP/SAVPF 96 97#015#012a=rtpmap:96 H264/90000#015#012a=fmtp:96 profile-le ...
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: ... vel-id=42801F#015#012a=rtpmap:97 VP8/90000#015#012a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:cJOJ7kxQjhFBp2fP6AYjs3vKw7CeBdWZCj0isbJv#015#012a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:VAzLKvoE3jG9cdH/AZsl/ZqWNXrUzyM4Gw6chrFr#015#012a=crypto:3 AES_256_CM_HMAC_SHA1_80 inline:8AbZePWwsKhLGX3GlXA+yHYPQ3cgraer/9DkFJYCOPZZy3o9wC0NIbIFYZfyHw==#015#012a=crypto:4 AES_256_CM_HMAC_SHA1_32 inline:2GLk3p/csdno4KlGO1TxCVaEt+bifmDlQ5NjnCb5cJYPURiGRSTBEtEq37db8g==#015#012a=rtcp-fb:* trr-int 5000#015#012a=rtcp-fb:* ccm tmmbr#015#012a=rtcp-fb:96 nack pli#015#012a=rtcp ...
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: ... -fb:96 ccm fir#015#012a=rtcp-fb:97 nack pli#015#012a=rtcp-fb:97 nack sli#015#012a=rtcp-fb:97 ack rpsi#015#012a=rtcp-fb:97 ccm fir#015#012", "ICE": "force", "DTLS": "passive", "replace": [ "origin", "session-connection" ], "transport-protocol": "UDP/TLS/RTP/SAVPF", "rtcp-mux": [ "offer" ], "SDES": [ "off" ], "call-id": "icf04gvnaA", "received-from": [ "IP4", "178.243.126.179" ], "from-tag": "QezW2loeE", "command": "offer" }
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: ERR: [icf04gvnaA]: Failed to parse a=crypto attribute, ignoring: unknown crypto suite
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: ERR: [icf04gvnaA]: Failed to parse a=crypto attribute, ignoring: unknown crypto suite
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: ERR: [icf04gvnaA]: Failed to parse a=crypto attribute, ignoring: unknown crypto suite
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: ERR: [icf04gvnaA]: Failed to parse a=crypto attribute, ignoring: unknown crypto suite
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Default sink codec is opus/48000/2
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Sink supports codec opus/48000/2
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: __free_ssrc_handler
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: __free_ssrc_handler
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Sink supports codec PCMU/8000
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: __free_ssrc_handler
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Sink supports codec PCMA/8000
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: __free_ssrc_handler
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: __free_ssrc_handler
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: __free_ssrc_handler
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: __free_ssrc_handler
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: __free_ssrc_handler
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: INFO: [icf04gvnaA]: Replying to 'offer' from 172.21.145.73:63096 (elapsed time 0.000860 sec)
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Response dump for 'offer' to 172.21.145.73:63096: { "sdp": "v=0#015#012o=905309769612 2510 1115 IN IP4 86.108.185.102#015#012s=Talk#015#012c=IN IP4 86.108.185.102#015#012t=0 0#015#012a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics#015#012m=audio 10158 UDP/TLS/RTP/SAVPF 96 97 0 8 101 98#015#012a=rtcp-fb:* trr-int 5000#015#012a=rtcp-fb:* ccm tmmbr#015#012a=rtpmap:96 opus/48000/2#015#012a=rtpmap:97 speex/8000#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:101 telephone-event/48000#015#012a=rtpmap:98 telephone-event/8000#015#012a=fmtp:96  ...
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: ... useinbandfec=0; maxplaybackrate=8000; maxptime=40; ptime=40; minptime=40; cbr=0;#015#012a=fmtp:97 vbr=on#015#012a=sendrecv#015#012a=rtcp:10159#015#012a=rtcp-mux#015#012a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:PjEpSwBQlpQ2YyNwK/YyMqhaaYRxLwAcTkyYECc+#015#012a=setup:actpass#015#012a=fingerprint:sha-1 8A:67:7F:18:23:90:E2:EA:22:3B:C0:35:06:B4:27:55:B4:FF:24:B2#015#012a=ice-ufrag:QyQZnNYX#015#012a=ice-pwd:ZhkOeeyB1ziLafuaYPbUbiScrJ#015#012a=candidate:xmzD8xmprLgDZ6Vp 1 UDP 2130706431 86.108.185.102 10158 typ host#015#012a=candidate:xmzD8xmprLgDZ6Vp 2 UDP 21307064 ...
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: ... 30 86.108.185.102 10159 typ host#015#012m=video 10180 UDP/TLS/RTP/SAVPF 96 97#015#012a=rtcp-fb:* trr-int 5000#015#012a=rtcp-fb:* ccm tmmbr#015#012a=rtcp-fb:96 nack pli#015#012a=rtcp-fb:96 ccm fir#015#012a=rtcp-fb:97 nack pli#015#012a=rtcp-fb:97 nack sli#015#012a=rtcp-fb:97 ack rpsi#015#012a=rtcp-fb:97 ccm fir#015#012a=rtpmap:96 H264/90000#015#012a=rtpmap:97 VP8/90000#015#012a=fmtp:96 profile-level-id=42801F#015#012a=sendrecv#015#012a=rtcp:10181#015#012a=rtcp-mux#015#012a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:cJOJ7kxQjhFBp2fP6AYjs3vKw7CeBdWZCj0isbJv#015#012a=setup:actpass#015#012a=fingerprint:sha-1 8 ...
Jan 26 16:18:02 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: ... A:67:7F:18:23:90:E2:EA:22:3B:C0:35:06:B4:27:55:B4:FF:24:B2#015#012a=ice-ufrag:AXuqWopp#015#012a=ice-pwd:UCeGzgsGZoN5oLQbtZAXXKpKz9#015#012a=candidate:xmzD8xmprLgDZ6Vp 1 UDP 2130706431 86.108.185.102 10180 typ host#015#012a=candidate:xmzD8xmprLgDZ6Vp 2 UDP 2130706430 86.108.185.102 10181 typ host#015#012", "result": "ok" }
Jan 26 16:18:03 TESTTRS01 rtpengine[6388]: DEBUG: timer run time = 0.000036 sec
Jan 26 16:18:05 TESTTRS01 rtpengine[6388]: DEBUG: timer run time = 0.000041 sec
Jan 26 16:18:06 TESTTRS01 rtpengine[6388]: DEBUG: timer run time = 0.000034 sec
Jan 26 16:18:08 TESTTRS01 rtpengine[6388]: DEBUG: timer run time = 0.000043 sec
Jan 26 16:18:10 TESTTRS01 rtpengine[6388]: DEBUG: timer run time = 0.000042 sec
Jan 26 16:18:12 TESTTRS01 rtpengine[6388]: DEBUG: timer run time = 0.000038 sec
Jan 26 16:18:13 TESTTRS01 rtpengine[6388]: DEBUG: timer run time = 0.000048 sec
Jan 26 16:18:14 TESTTRS01 rtpengine[6388]: DEBUG: timer run time = 0.000035 sec
Jan 26 16:18:15 TESTTRS01 rtpengine[6388]: DEBUG: timer run time = 0.000035 sec
Jan 26 16:18:16 TESTTRS01 rtpengine[6388]: INFO: [icf04gvnaA]: Received command 'delete' from 172.21.145.73:44746
Jan 26 16:18:16 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Dump for 'delete' from 172.21.145.73:44746: { "ICE": "remove", "DTLS": "off", "call-id": "icf04gvnaA", "received-from": [ "IP4", "178.243.126.179" ], "from-tag": "QezW2loeE", "command": "delete" }
Jan 26 16:18:16 TESTTRS01 rtpengine[6388]: INFO: [icf04gvnaA]: Scheduling deletion of call branch 'QezW2loeE' (via-branch '') in 30 seconds
Jan 26 16:18:16 TESTTRS01 rtpengine[6388]: INFO: [icf04gvnaA]: Replying to 'delete' from 172.21.145.73:44746 (elapsed time 0.000096 sec)
Jan 26 16:18:16 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: Response dump for 'delete' to 172.21.145.73:44746: { "created": 1548508682, "created_us": 134696, "last signal": 1548508682, "SSRC": {  }, "tags": { "QezW2loeE": { "tag": "QezW2loeE", "created": 1548508682, "in dialogue with": "", "medias": [ { "index": 1, "type": "audio", "protocol": "RTP/SAVPF", "streams": [ { "local port": 10170, "endpoint": { "family": "IPv4", "address": "100.81.124.137", "port": 51242 }, "advertised endpoint": { "family": "IPv4", "address": "100.81.124.137", "port": 51242 } ...
Jan 26 16:18:16 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: ... , "last packet": 1548508682, "flags": [ "RTP", "filled" ], "stats": { "packets": 0, "bytes": 0, "errors": 0 } }, { "local port": 10171, "endpoint": { "family": "IPv4", "address": "100.81.124.137", "port": 51243 }, "advertised endpoint": { "family": "IPv4", "address": "100.81.124.137", "port": 51243 }, "last packet": 1548508682, "flags": [ "RTCP", "filled" ], "stats": { "packets": 0, "bytes": 0, "errors": 0 } } ], "flags": [ "initialized", "send", "recv", "SDES" ] }, { "index": 2, "type": "video" ...
Jan 26 16:18:16 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: ... , "protocol": "RTP/SAVPF", "streams": [ { "local port": 10190, "endpoint": { "family": "IPv4", "address": "100.81.124.137", "port": 54116 }, "advertised endpoint": { "family": "IPv4", "address": "100.81.124.137", "port": 54116 }, "last packet": 1548508682, "flags": [ "RTP", "filled" ], "stats": { "packets": 0, "bytes": 0, "errors": 0 } }, { "local port": 10191, "endpoint": { "family": "IPv4", "address": "100.81.124.137", "port": 54117 }, "advertised endpoint": { "family": "IPv4", "address": "100 ...
Jan 26 16:18:16 TESTTRS01 rtpengine[6388]: DEBUG: [icf04gvnaA]: ... .81.124.137", "port": 54117 }, "last packet": 1548508682, "flags": [ "RTCP", "filled" ], "stats": { "packets": 0, "bytes": 0, "errors": 0 } } ], "flags": [ "initialized", "send", "recv", "SDES" ] } ] } }, "totals": { "RTP": { "packets": 0, "bytes": 0, "errors": 0 }, "RTCP": { "packets": 0, "bytes": 0, "errors": 0 } }, "result": "ok" }

**Comment by rfuchs** [comment]
You need to tell rtpengine that this is a forked call. Otherwise rtpengine will believe that this is a re-invite going to the same client. Without a distinct to-tag, rtpengine can only tell from the via-branch that this is a branched offer, and so you need to include the via-branch option in both the offers and the answer.

**Comment by korayvt** [comment]
Thanks for the quick response.

I'm using kamailio as a sip server. According to the rtpengine module documentation, I set via-branch options in offer and answer, 1 and 2 respectively.
However all branched offer's via-branch option seems the same as the incoming INVITE's via branch id.
As a result, again rtpengine thinks that the two offers belong to the same session I guess.

I would appreciate any suggestion.

**Comment by rfuchs** [comment]
If I remember right, it depends on where you issue the call to rtpengine within your routing logic. Before or after actually branching the dialogue. This is not my forte, I will try to clarify.

**Comment by rfuchs** [comment]
Also just to mention, as an alternative you can use the `extra_id_pv` option of the Kamailio module. If the extra_id is set, it will be used in place of the via-branch parameter. You can use this if you have some other way to identify and distinguish the two branches. The important part is to use the same extra_id in the answer that was used in the matching offer branch.

**Comment by rfuchs** [comment]
Are you doing the calls to rtpengine in the request_route or in the branch_route?

**Comment by denyspozniak** [comment]
@korayvt, you need to insert rtpengine_offer() to the branch route and used via-branch parameter.

**Comment by korayvt** [comment]
> @korayvt, you need to insert rtpengine_offer() to the branch route and use via-branch parameter.

Yes, I'm trying to use it, but I have some issues as I mentioned in my previous comments.

**Comment by korayvt** [comment]
Hi,
Finally I had some time to try this extra_id_pv option.
I set different via-branch values for two branches in the offer, answer and delete commands.
However ports remain open after both of the branches deleted. 

Am I missing something?

Ports are closed after 60 min. I don't know which timeout value this is? 

I attached rtpengine log:
[rtpengine-D6z-nMXE1V.log](https://github.com/sipwise/rtpengine/files/2878407/rtpengine-D6z-nMXE1V.log)

Netstat output is here after call is ended:

$ netstat -na | grep udp  | grep 172.21.142.153
udp        0      0 172.21.142.153:10228        0.0.0.0:*
udp        0      0 172.21.142.153:10229        0.0.0.0:*
udp        0      0 172.21.142.153:123          0.0.0.0:*
udp        0      0 172.21.142.153:10240        0.0.0.0:*
udp        0      0 172.21.142.153:10241        0.0.0.0:*
udp        0      0 172.21.142.153:7722         0.0.0.0:*
udp        0      0 172.21.142.153:7733         0.0.0.0:*
udp        0      0 172.21.142.153:10212        0.0.0.0:*
udp        0      0 172.21.142.153:10213        0.0.0.0:*

**Comment by korayvt** [comment]
Hi,
I have a question regarding this via-branch usage:

In the attached rtpengine log below, I set different via-branch values in the offer commands of two branches.
When 200OK received from one branch, I sent answer and delete commands with corresponding via-branch values.
However allocated ports of the deleted branch remain open until the last delete command, in which I didn't use via-branch option, received.

Is this the expected behaviour?

I was thinking that unused ports are released when delete command received.

[rtpengine-9mexyH1swI.log](https://github.com/sipwise/rtpengine/files/2878701/rtpengine-9mexyH1swI.log)

**Comment by rfuchs** [comment]
Yes, this is expected. Ports are opened as needed but are closed only at the end of the call, when the "final packet stats" are printed to the log.

**Comment by korayvt** [comment]
One more question:
In media update with REINVITE case, after the media session established by using via-branch option, do I need to use via-branch option again in the offer and answer commands to identify the session or can it be empty just like in the delete command?

**Comment by rfuchs** [comment]
You can omit the via-branch option if there's both a from-tag and a to-tag present (which is usually the case during a re-invite), or if only one active dialogue association remains (i.e. all others have been deleted, which is also usually the case during a re-invite).
