### ISSUE TITLE
CentOS7 Compilation

### ISSUE THREAD

**Issue by voztovoice** [sipwise/rtpengine#694]
Hello,

from today I can't compile RTPEngine.

The error that returns is:

/usr/src/rtpengine/daemon **make**
_Makefile:135: .depend: No existe el fichero o el directorio
../utils/const_str_hash < control_ng.c > control_ng.strhash.c
Use of bare << to mean <<"" is deprecated at ../utils/const_str_hash line 16.
Global symbol "$line" requires explicit package name at ../utils/const_str_hash line 16.
Global symbol "$line" requires explicit package name at ../utils/const_str_hash line 16.
Global symbol "$key" requires explicit package name at ../utils/const_str_hash line 16.
Global symbol "$key" requires explicit package name at ../utils/const_str_hash line 16.
Global symbol "$line" requires explicit package name at ../utils/const_str_hash line 16.
Global symbol "$key" requires explicit package name at ../utils/const_str_hash line 16.
Global symbol "$line" requires explicit package name at ../utils/const_str_hash line 16.
Global symbol "$key" requires explicit package name at ../utils/const_str_hash line 16.
Global symbol "$key" requires explicit package name at ../utils/const_str_hash line 16.
Global symbol "$line" requires explicit package name at ../utils/const_str_hash line 16.
syntax error at ../utils/const_str_hash line 33, near ">>) "
  (Might be a runaway multi-line << string starting on line 16)
../utils/const_str_hash has too many errors.
make: *** [control_ng.strhash.c] Error 255_

Any hint to solve, please?
Regards

**Comment by voztovoice** [comment]
Release mr4.5.11.2 compile fine.

**Comment by voztovoice** [comment]
Release mr6.5.3.1 compile fine too.

**Comment by rfuchs** [comment]
Probably due to an outdated Perl version

**Comment by rfuchs** [comment]
due to ff3b821e47e1117e082db1298267716f56c678ad

**Comment by voztovoice** [comment]
Thank you. So, I have tu upgrade my perl version?
Regards

**Comment by mika** [comment]
JFTR: the `<<>>`` operator is supported by Perl >=5.22 only, yes (see https://perldoc.perl.org/perl5220delta.html#New-double-diamond-operator). Perl >=5.26 is available for CentOS 7 via 
Software Collection (SCL), see https://lists.centos.org/pipermail/centos-announce/2018-June/022917.html (though I'm wondering whether we have any other common systems out there which don't ship perl >=5.22 yet?)

**Comment by MarkFomin** [comment]
Also you need to install packet **gperf** if you have problem like this:
`# make
Makefile:135: .depend: No file or directory
../utils/const_str_hash < control_ng.c > control_ng.strhash.c
open2: exec of gperf -t -E -l -c -t -I -H __csh_hash -N __csh_lookup_raw failed at ../utils/const_str_hash line 37.
`
