### ISSUE TITLE
rtpengine.init (el)

### ISSUE THREAD

**Issue by nicoonline** [sipwise/rtpengine#696]
when a chain already exists 

[root@proxy2 el]# ./rtpengine.init start
Loading module for in-kernel packet forwarding
iptables: Chain already exists.

script adds a second line in the chain : 
Chain rtpengine (2 references)
num  target     prot opt source               destination         
1    RTPENGINE  udp  --  0.0.0.0/0            0.0.0.0/0            RTPENGINE id:0
2    RTPENGINE  udp  --  0.0.0.0/0            0.0.0.0/0            RTPENGINE id:0

**Comment by rfuchs** [comment]
Is this with or without firewalld (firewall-cmd)?

**Comment by nicoonline** [comment]
Without

Le 28 janv. 2019 à 21:24, Richard Fuchs <notifications@github.com<mailto:notifications@github.com>> a écrit :


Is this with or without firewalld (firewall-cmd)?

**Comment by nicoonline** [comment]
Thanks Richard.

**Comment by nicoonline** [comment]
echo "del $TABLE" > /proc/rtpengine/control
produce an error
/etc/rc.d/rtpengine.init: line 210: echo: write error: Invalid argument

**Comment by mika** [comment]
@rfuchs I think the issue @nicoonline has is caused by "$TABLE" not being set? Should be set by default in `el/rtpengine.init` and before `/etc/sysconfig/rtpengine` is being read/sourced?

**Comment by nicoonline** [comment]
good point :)
Thanks

**Comment by mika** [comment]
Prepared PR in https://github.com/sipwise/rtpengine/pull/698
