### ISSUE TITLE
proxy replied with error: Ran out of ports

### ISSUE THREAD

**Issue by iman432** [sipwise/rtpengine#699]
Hi

I get these errors when call per second exceeded from 200(kamailio):

rtpengine [rtpengine.c:2273]: rtpp_function_call(): proxy replied with error: Ran out of ports

rtpengine[2348]: ERR: [1473-1752@10.25.5.40]: Failed to get 2 consecutive ports on interface 10.25.5.110 for media relay (last error: Address already in use)

rtpengine[2348]: ERR: [1473-1752@10.25.5.40]: Failed to get 2 consecutive ports on all locals of logical 'default'
rtpengine[2348]: ERR: [1473-1752@10.25.5.40]: Error allocating media ports
rtpengine[2348]: ERR: [1473-1752@10.25.5.40]: Destroying call

BYE is received by server and rtpengine_delete(); runs

I changed ulimit but it wasn't useful

where is problem?

Thanks in Advanced

**Comment by rfuchs** [comment]
Maybe you actually ran out of ports? Too many calls running?

"Address already in use" hints to something else using the same ports that you've allocated for rtpengine. Maybe a booboo in your network config or rtpengine config?

**Comment by prathibhacdac** [comment]
Facing the same issue.
