### ISSUE TITLE
Interface: UDP is subject to packet truncation, what about TCP support?

### ISSUE THREAD

**Issue by krieger-od** [sipwise/rtpengine#70]
According to http://kamailio.org/docs/modules/devel/modules/rtpengine.html#rtpengine.p.rtpengine_sock , the connection between kamailio and rtpengine can use UNIX socket or UDP.
When rtpengine and kamailio are setup on a different hosts, we cannot use UNIX sockets because they are local, so we use UDP. But SDP for video calls with encryption may easily exceed common MTU=1500, and packets get trunkated, which breaks communication between kamailio and rtpengine.
This may be sorted out with some VPN with custom high MTU, which should prevent UDP packets truncation. But it would be better if this scenario would work without additional measures.
Would it be reasonable to add support of TCP interfacing or anything like that? Please let me know what you think.
I am ready to test this feature and maybe even help to develop it.

**Comment by rfuchs** [comment]
UDP packets have a maximum length of 65535 bytes. If the size exceeds the MTU, they get fragmented, not truncated.

**Comment by krieger-od** [comment]
Thanks for the reply!
Then is must be networking issue in my setup. But still, would you accept what I offered, so that other newcomers avoid the issue I am currently experiencing?

**Comment by rfuchs** [comment]
I see no reason to support TCP, datagrams work just fine. If you're having MTU issues, chances are that you're gonna have problems with TCP as well.

**Comment by krieger-od** [comment]
Actually, I tried such combinations:
- amazon VPS (MTU 9001) + digitalocean VPS (MTU 1500)
- amazon VPS (MTU 9001) +  amazon VPS (MTU 9001)
For all hosts, MTU values were not changed by me.
In both cases, datagram contents seem trunkated to ~1473 characters. MTU 9001 must be default for amazon hosts.

**Comment by rfuchs** [comment]
Jumbo frames are fine if the network really supports them, as long as ICMP packets aren't filtered out, which would hinder path MTU discovery.

**Comment by krieger-od** [comment]
Will check this with admins. Thank you very much.

**Comment by krieger-od** [comment]
Figured out that the command line ```ngrep -t -e -d any -W byline port 22222``` was insufficient for adequate dumping of streams. Using ```ngrep -t -e -d any -W byline port 22222 or '(ip[6:2]' '&' '0x1fff)' '!=' '0'``` shows that fragments of large datagrams get delivered finely.
But still having issue, probably kamailio's module wrongly decides there's a timeout waiting for rtpengine's reply:
```
/usr/local/sbin/kamailio[10060]: ERROR: rtpengine [rtpengine.c:1540]: send_rtpp_command(): timeout waiting reply from a RTP proxy
```
More info on this situation will follow.

**Comment by rfuchs** [comment]
Closing as this is a network problem and no TCP support is planned.

**Comment by jmealo** [comment]
@krieger-od I found this ticket while searching for information on Digital Ocean. I have noticed that the MTU as reported on Network Interfaces on Linux guests on GCE and DO are not correct (both KVM).

For example, the private and public network interfaces on Digital Ocean are reported as MTU 1500. I tested the private network in NYC2 and it is actually 1472.

To further complicate things, if you're running OpenVPN, you have to set the ``tun-mtu`` to 1344 for it to work.

You can test the effective MTU using a ``ping`` command.

**Comment by andrey-utkin** [comment]
@jmealo Thanks, any info about Amazon?

**Comment by jmealo** [comment]
@andrey-utkin: I didn't do any testing on AWS.
