### ISSUE TITLE
Callee unhold transcoding issue with RTP G711a to SRTPG711a

### ISSUE THREAD

**Issue by adil-mafzool** [sipwise/rtpengine#701]
I am experiencing the issue when transcoding using RTP Engine between RTP G711a to SRTP G711a. 
The SRTP G711a generated by rtpengine cannot be decrypt by Yealink Phone  and Wireshark.

Caller (SNOM)IP phone <-------------> 3rd Party B2BUA<--------------> Kamailio <--------------------> Yealink Phone Callee
                RTP  <------> RTP Engine version (Version: 7.1.0.0+0~mr7.1.0.0 ) SRTP <----->  SRTP

Initial call from SNOM is using (RTP) G729 which is being trancoded to (SRTP) G729  Yealink Phone Callee which works fine.

SNOM phone puts the call hold twice and connects the call back with no issue two way-audio.
When Yealink Phone Callee using SRTP puts the call hold with SRTP G711a as priority all is still fine.
But when Yealink Phone Callee using SRTP takes call off-hold using SRTP G711a as priority.

Yealink Phone Callee as well wireshark cannot decrypt the transcoded SRTP G711a audio sent by rtpengine.
The issue doesn't occur all the time but it is quite regular.
Please find the wireshark trace and rtpengine debug logs attached.

[rtpengine-wrong-srtp-audio-after-callee-hold.zip](https://github.com/sipwise/rtpengine/files/2846138/rtpengine-wrong-srtp-audio-after-callee-hold.zip)

**Comment by rfuchs** [comment]
This looks to be the same issue as #664. The jump in output sequence number is probably seen as a rollover by the receiver, so they increase the ROC to 1, while rtpengine is sending with a ROC of 0. The fix for #664 should fix this too.
