### ISSUE TITLE
Error!! Unmet build dependencies : libbcg729-dev

### ISSUE THREAD

**Issue by Diamond555** [sipwise/rtpengine#706]
Hi
i install RTPEngine And it caused Erre.

dpkg-checkbuilddeps: error: Unmet build dependencies: libbcg729-dev
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)

what should I do?
Thank you.

**Comment by rfuchs** [comment]
You should read the README.

https://github.com/sipwise/rtpengine#g729-support
