### ISSUE TITLE
provide better output at daemon start due "rtpengine: CRIT: Fatal error"

### ISSUE THREAD

**Issue by mckaygerhard** [sipwise/rtpengine#713]
after many "tries" installing and resolvin due the issue #624  i can see that the daemon are not very xplicit with the init script or the systemd, aftyer solved with that isue got still problems and see later ONLY BY FILTER THE LOG FILE, the proble that no interfaces was defined but, the problem its that the daemon does not pointed that so many...

```
Feb 25 16:28:45 ip-10-101-2-211 systemd[1]: Starting RTP/media Proxy Daemon...
Feb 25 16:28:45 ip-10-101-2-211 rtpengine[25750]: [1551112125.186388] CRIT: Fatal error: Missing option --interface
```

due the rtpengine seems by default logs all to daemon log, so its hard to find reasons of problems due the large set of entries in that file!

**Comment by rfuchs** [comment]
In the .deb, the config file is provided only as a sample `rtpengine.sample.conf` which makes it quite clear that it needs to be edited properly. If started through systemd, the startup failure is quite clear and so is the reason for it:
```
Job for ngcp-rtpengine-daemon.service failed because the control process exited with error code.
See "systemctl status ngcp-rtpengine-daemon.service" and "journalctl -xe" for details.
invoke-rc.d: initscript ngcp-rtpengine-daemon, action "restart" failed.
● ngcp-rtpengine-daemon.service - NGCP RTP/media Proxy Daemon
   Loaded: loaded (/lib/systemd/system/ngcp-rtpengine-daemon.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-02-25 13:17:39 EST; 38ms ago
  Process: 31997 ExecStopPost=/usr/sbin/ngcp-rtpengine-iptables-setup stop (code=exited, status=0/SUCCESS)
  Process: 31991 ExecStart=/usr/sbin/rtpengine -f -E --pidfile /run/ngcp-rtpengine-daemon.pid --config-file /etc/rtpengine/rtpengine.conf --table $TABLE (code=exited, status=255)
  Process: 31972 ExecStartPre=/usr/sbin/ngcp-rtpengine-iptables-setup start (code=exited, status=0/SUCCESS)
 Main PID: 31991 (code=exited, status=255)

root@debian:~# journalctl -xe
...
Feb 25 13:17:37 debian rtpengine[31991]: CRIT: Fatal error: Bad command line: No such file or directory
Feb 25 13:17:37 debian rtpengine[31991]: [1551118657.972896] CRIT: Fatal error: Bad command line: No such file or directory
```

If you ignore the docs and try to use the sample config unedited, the failure and its reason are also clear:
```
root@debian:~# systemctl start ngcp-rtpengine-daemon.service
Job for ngcp-rtpengine-daemon.service failed because the control process exited with error code.
See "systemctl status ngcp-rtpengine-daemon.service" and "journalctl -xe" for details.

root@debian:~# journalctl -xe
...
-- Unit ngcp-rtpengine-daemon.service has begun starting up.
Feb 25 13:23:27 debian kernel: Registering xt_RTPENGINE module - version 7.2.0.0+0~mr7.2.0.0
Feb 25 13:23:27 debian rtpengine[32117]: [1551119007.727496] CRIT: Fatal error: Missing option --interface
```

There's nothing to do here.

**Comment by mckaygerhard** [comment]
ummm ok well an admin must be know what are doint! thanks!

**Comment by mithkum** [comment]
root@telegestion ~]# journalctl -xe
-- Subject: Unit session-3721.scope has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit session-3721.scope has finished starting up.
-- 
-- The start-up result is done.
Aug 30 04:32:01 telegestion systemd[1]: Started Session 3724 of user root.
-- Subject: Unit session-3724.scope has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit session-3724.scope has finished starting up.
-- 
-- The start-up result is done.
Aug 30 04:32:01 telegestion CROND[14656]: (root) CMD (/usr/share/astguiclient/AST_conf_update.pl)
Aug 30 04:32:01 telegestion CROND[14658]: (root) CMD (/usr/share/astguiclient/AST_VDhopper.pl -q)
Aug 30 04:32:01 telegestion CROND[14659]: (root) CMD (/usr/share/astguiclient/AST_manager_kill_hung_congested.pl)
Aug 30 04:32:01 telegestion CROND[14657]: (root) CMD (/usr/share/astguiclient/ADMIN_keepalive_ALL.pl)
Aug 30 04:32:32 telegestion polkitd[568]: Registered Authentication Agent for unix-process:14704:3881757 (system bus name :1.7464 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent,
Aug 30 04:32:32 telegestion polkitd[568]: Unregistered Authentication Agent for unix-process:14704:3881757 (system bus name :1.7464, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Aug 30 04:32:49 telegestion polkitd[568]: Registered Authentication Agent for unix-process:14732:3883514 (system bus name :1.7466 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent,
Aug 30 04:32:49 telegestion systemd[1]: Starting LSB: NGCP rtpengine...
-- Subject: Unit ngcp-rtpengine.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit ngcp-rtpengine.service has begun starting up.
Aug 30 04:32:49 telegestion ngcp-rtpengine[14738]: Loading module for in-kernel packet forwarding
Aug 30 04:32:49 telegestion ngcp-rtpengine[14738]: modprobe: FATAL: Module xt_RTPENGINE not found.
Aug 30 04:32:49 telegestion ngcp-rtpengine[14738]: iptables: Chain already exists.
Aug 30 04:32:49 telegestion ngcp-rtpengine[14738]: iptables: No chain/target/match by that name.
Aug 30 04:32:49 telegestion ngcp-rtpengine[14738]: ip6tables: Chain already exists.
Aug 30 04:32:49 telegestion ngcp-rtpengine[14738]: ip6tables: No chain/target/match by that name.
Aug 30 04:32:49 telegestion rtpengine[14761]: INFO: Generating new DTLS certificate
Aug 30 04:32:49 telegestion rtpengine[14761]: ERR: FAILED TO CREATE KERNEL TABLE 0 (No such file or directory), KERNEL FORWARDING DISABLED
Aug 30 04:32:49 telegestion ngcp-rtpengine[14738]: Starting rtpengine: [1598761969.739793] ERR: FAILED TO CREATE KERNEL TABLE 0 (No such file or directory), KERNEL FORWARDING DISABLED
Aug 30 04:32:49 telegestion ngcp-rtpengine[14738]: [1598761969.739819] CRIT: Userspace fallback disallowed - exiting
Aug 30 04:32:49 telegestion rtpengine[14761]: CRIT: Userspace fallback disallowed - exiting
Aug 30 04:32:49 telegestion ngcp-rtpengine[14738]: [FAILED]
Aug 30 04:32:49 telegestion systemd[1]: ngcp-rtpengine.service: control process exited, code=exited status=1
Aug 30 04:32:49 telegestion systemd[1]: Failed to start LSB: NGCP rtpengine.
-- Subject: Unit ngcp-rtpengine.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit ngcp-rtpengine.service has failed.
-- 
-- The result is failed.
Aug 30 04:32:49 telegestion systemd[1]: Unit ngcp-rtpengine.service entered failed state.
Aug 30 04:32:49 telegestion systemd[1]: ngcp-rtpengine.service failed.
Aug 30 04:32:49 telegestion polkitd[568]: Unregistered Authentication Agent for unix-process:14732:3883514 (system bus name :1.7466, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
