### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by dancmsgit** [sipwise/rtpengine#714]
CentOS 7 and ffmpeg 3.4.5-2.el7 from rpmfusion

Make results in -
make[1]: Entering directory `/usr/local/src/rtpengine/daemon'
make[1]: *** No rule to make target `/usr/include/ffmpeg/libavutil/old_pix_fmts.h', needed by `.depend'.  Stop.
make[1]: Leaving directory `/usr/local/src/rtpengine/daemon'
make: *** [all] Error 2

make[1]: Entering directory `/usr/local/src/rtpengine/daemon'
make[1]: *** No rule to make target `/usr/include/ffmpeg/libavcodec/old_codec_ids.h', needed by `.depend'.  Stop.
make[1]: Leaving directory `/usr/local/src/rtpengine/daemon'

I manually copied these files from an older install. Make now results in:

main.o: In function `options':
/usr/local/src/rtpengine/daemon/main.c:308: undefined reference to `dtls_passive_def'
/usr/local/src/rtpengine/daemon/main.c:514: undefined reference to `trust_address_def'
main.o: In function `init_everything':
/usr/local/src/rtpengine/daemon/main.c:609: undefined reference to `sdp_init'
/usr/local/src/rtpengine/daemon/main.c:615: undefined reference to `control_ng_init'
/usr/local/src/rtpengine/daemon/main.c:616: undefined reference to `call_interfaces_init'
main.o: In function `create_everything':
/usr/local/src/rtpengine/daemon/main.c:680: undefined reference to `rtpe_control_ng'
/usr/local/src/rtpengine/daemon/main.c:683: undefined reference to `control_ng_new'
/usr/local/src/rtpengine/daemon/main.c:683: undefined reference to `rtpe_control_ng'
control_tcp.o: In function `control_stream_parse':
/usr/local/src/rtpengine/daemon/control_tcp.c:93: undefined reference to `call_request_tcp'
/usr/local/src/rtpengine/daemon/control_tcp.c:95: undefined reference to `call_lookup_tcp'
/usr/local/src/rtpengine/daemon/control_tcp.c:97: undefined reference to `call_delete_tcp'
/usr/local/src/rtpengine/daemon/control_tcp.c:99: undefined reference to `calls_status_tcp'
call.o: In function `call_delete_branch':
/usr/local/src/rtpengine/daemon/call.c:2793: undefined reference to `ng_call_stats'
control_udp.o: In function `control_udp_incoming':
/usr/local/src/rtpengine/daemon/control_udp.c:89: undefined reference to `call_update_udp'
/usr/local/src/rtpengine/daemon/control_udp.c:91: undefined reference to `call_lookup_udp'
/usr/local/src/rtpengine/daemon/control_udp.c:93: undefined reference to `call_delete_udp'
/usr/local/src/rtpengine/daemon/control_udp.c:95: undefined reference to `call_query_udp'
cli.o: In function `cli_incoming_set_controltos':
/usr/local/src/rtpengine/daemon/cli.c:1419: undefined reference to `rtpe_control_ng'
cli.o: In function `cli_incoming_list_totals':
/usr/local/src/rtpengine/daemon/cli.c:470: undefined reference to `rtpe_cngs_lock'
/usr/local/src/rtpengine/daemon/cli.c:471: undefined reference to `rtpe_cngs_hash'
/usr/local/src/rtpengine/daemon/cli.c:493: undefined reference to `rtpe_cngs_lock'
collect2: error: ld returned 1 exit status
make[1]: *** [rtpengine] Error 1
make[1]: Leaving directory `/usr/local/src/rtpengine/daemon'
make: *** [all] Error 2

Is there another recommended package/s to solve this?

**Comment by rfuchs** [comment]
Make sure you have a clean build directory, either a fresh clean git checkout and/or `git clean -f -x -d` before building.

**Comment by dancmsgit** [comment]
Tried that and now receive -

Makefile:135: .depend: No such file or directory
../utils/const_str_hash < control_ng.c > control_ng.strhash.c
open2: exec of gperf -t -E -l -c -t -I -H __csh_hash -N __csh_lookup_raw failed at ../utils/const_str_hash line 37.
make: *** [control_ng.strhash.c] Error 2

**Comment by rfuchs** [comment]
yum install gperf

**Comment by dancmsgit** [comment]
Not sure how that was missing but good to go. Thanks for the assist.
