### ISSUE TITLE
Could the Sipwise Jenkins Builder also change the version in the el/rtpengine.spec

### ISSUE THREAD

**Issue by khorsmann** [sipwise/rtpengine#719]
Hi all!

This is a feature request for the *Sipwise Jenkins Builder*.

Could the *Sipwise Jenkins Builder* also change the version in the **el/rtpengine.spec**?
At this time it ignores the Version in the **el/rtpengine.spec** cos target is "debian" based.

https://github.com/sipwise/rtpengine/blob/mr7.1.1.2/el/rtpengine.spec#L2
mr7.1.1.2 says its rpm version 6.4.1.1. Thats not true.

If the Builder sets the Version Line to the tag-Version (without mr prefix) it would be consistent.

Kind Regards

**Comment by taurus-forever** [comment]
Technically everything is possible as it is just a software,
unfortunately development here is required but all our
forces are pointed into another direction right now.

Richard, feel free to improve release-tools.git/repo_brancher from your side.
Hint: duplicate bump_changelog_version()->set_changelog_string()
and perform necessary actions into el/rtpengine.spec
to bump the version if the file is available.

Have fun!

**Comment by rfuchs** [comment]
Done. Should start working at the next release/branch.

**Comment by taurus-forever** [comment]
Works: https://github.com/sipwise/rtpengine/commit/cd6fca553628f05b9938fc42d830c2ca25aae1e0

**Comment by khorsmann** [comment]
I will test it tomorrow. Thanks.
