### ISSUE TITLE
SRTP output wanted, but no crypto suite was negotiated

### ISSUE THREAD

**Issue by johandeclercqdemocon** [sipwise/rtpengine#723]
Hello Richard, 

I believe that I have an issue with SRTP: 
my signaling is crystal clear but I see an error as mentioned in the title.  I wonder if I have to worry about this.   In any case , the 200 OK is not accepted by Zoiper giving below error:
"
DEBUG | 20190304-181203.199 | RESIP:APP | 11720 | sdp_crypto_attr.cpp:318 | incorrect key size 45 for suite AES_CM_256_HMAC_SHA1_80
"

Can you please let shine your light on this ? 

rtpengine.conf : interface =provider/10.3.0.150;phone/10.3.0.150!10.200.0.150

Mar  4 17:58:40 opensips /data/opensips/sbin/opensips[17371]: callid=cz3V4dI1uF18EFMNmskgwg..: route[setrtpengineflags]: call is to gateway avp(gwid) , we transcode ALWAYS to G711A or G711U var(rtpengine_flags) RTP/AVP in-iface=phone out-iface=provider replace-origin replace-session-connection ICE=remove codec-strip-telephone-event codec-strip-PCMA codec-strip-PCMU codec-strip-all codec-transcode-PCMA codec-transcode-PCMU codec-offer-telephone-event
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: Adding a proxy for control ng stats:127.0.0.1
Mar  4 17:58:40 opensips rtpengine[29225]: INFO: [cz3V4dI1uF18EFMNmskgwg..]: Received command 'offer' from 127.0.0.1:37379
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Dump for 'offer' from 127.0.0.1:37379: { "sdp": "v=0#015#012o=Zoiper 1045030 0 IN IP4 10.204.0.29#015#012s=Z#015#012c=IN IP4 10.204.0.29#015#012t=0 0#015#012m=audio 46658 RTP/SAVP 3 101 0 8 97 110#015#012a=rtpmap:3 GSM/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-16#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:97 iLBC/8000#015#012a=fmtp:97 mode=30#015#012a=rtpmap:110 speex/8000#015#012a=sendrecv#015#012a=crypto:5 AES_256_CM_HMAC_SHA1_80 inline:Eo21u0Vcxp5takAELuMsfm6TQ5TKRMBGhL6M8jDOiUn5iza2LlrbY5j05YTtDA==#015#012a=crypto:6 AES_256_CM_HMAC_S ...
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: ... HA1_32 inline:Eo21u0Vcxp5takAELuMsfm6TQ5TKRMBGhL6M8jDOiUn5iza2LlrbY5j05YTtDA==#015#012a=crypto:9 AES_CM_256_HMAC_SHA1_80 inline:Eo21u0Vcxp5takAELuMsfm6TQ5TKRMBGhL6M8jDOiUn5iza2LlrbY5j05YTtDA==#015#012a=crypto:10 AES_CM_256_HMAC_SHA1_32 inline:Eo21u0Vcxp5takAELuMsfm6TQ5TKRMBGhL6M8jDOiUn5iza2LlrbY5j05YTtDA==#015#012a=crypto:3 AES_192_CM_HMAC_SHA1_80 inline:Eo21u0Vcxp5takAELuMsfm6TQ5TKRMBGhL6M8jDOiUn5iza2Llo=#015#012a=crypto:4 AES_192_CM_HMAC_SHA1_32 inline:Eo21u0Vcxp5takAELuMsfm6TQ5TKRMBGhL6M8jDOiUn5iza2Llo=#015#012a=crypto:7  ...
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: ... AES_CM_192_HMAC_SHA1_80 inline:Eo21u0Vcxp5takAELuMsfm6TQ5TKRMBGhL6M8jDOiUn5iza2Llo=#015#012a=crypto:8 AES_CM_192_HMAC_SHA1_32 inline:Eo21u0Vcxp5takAELuMsfm6TQ5TKRMBGhL6M8jDOiUn5iza2Llo=#015#012a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:Eo21u0Vcxp5takAELuMsfm6TQ5TKRMBGhL6M8jDO#015#012a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:Eo21u0Vcxp5takAELuMsfm6TQ5TKRMBGhL6M8jDO#015#012", "ICE": "remove", "direction": [ "phone", "provider" ], "flags": [ "codec-strip-telephone-event", "codec-strip-PCMA", "codec-strip-PCMU", "codec-stri ...
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: ... p-all", "codec-transcode-PCMA", "codec-transcode-PCMU", "codec-offer-telephone-event" ], "replace": [ "origin", "session-connection" ], "transport-protocol": "RTP/AVP", "call-id": "cz3V4dI1uF18EFMNmskgwg..", "received-from": [ "IP4", "10.204.0.29" ], "from-tag": "672df213", "command": "offer" }
Mar  4 17:58:40 opensips rtpengine[29225]: ERR: [cz3V4dI1uF18EFMNmskgwg..]: Failed to parse a=crypto attribute, ignoring: unknown crypto suite
Mar  4 17:58:40 opensips rtpengine[29225]: ERR: [cz3V4dI1uF18EFMNmskgwg..]: Failed to parse a=crypto attribute, ignoring: unknown crypto suite
Mar  4 17:58:40 opensips rtpengine[29225]: ERR: [cz3V4dI1uF18EFMNmskgwg..]: Failed to parse a=crypto attribute, ignoring: unknown crypto suite
Mar  4 17:58:40 opensips rtpengine[29225]: ERR: [cz3V4dI1uF18EFMNmskgwg..]: Failed to parse a=crypto attribute, ignoring: unknown crypto suite
Mar  4 17:58:40 opensips rtpengine[29225]: NOTICE: [cz3V4dI1uF18EFMNmskgwg..]: Creating new call
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Stripping codec 'GSM/8000'
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Stripping codec 'telephone-event/8000'
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Stripping codec 'PCMU/8000'
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Stripping codec 'PCMA/8000'
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Stripping codec 'iLBC/8000'
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Stripping codec 'speex/8000'
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Restoring codec 'telephone-event' from stripped codecs (1 payload types)
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Restoring codec 'PCMA' from stripped codecs (1 payload types)
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Restoring codec 'PCMU' from stripped codecs (1 payload types)
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Default sink codec is PCMA/8000
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Creating codec handler for telephone-event/8000
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Creating codec handler for PCMA/8000
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Sink supports codec PCMA/8000
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Creating codec handler for PCMU/8000
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Sink supports codec PCMU/8000
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: set FILLED flag for stream 10.204.0.29:46658
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: [10.3.0.150:30008] Initialized incoming SRTP with SDES crypto params: suite AES_CM_256_HMAC_SHA1_80, tag 9, key Eo21u0Vcxp5takAELuMsfm6TQ5TKRMBGhL6M8jDOiUk= salt +Ys2ti5a22OY9OWE7Qw=
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: [1] Initialized outgoing SRTP with SDES crypto params: <none>
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: set FILLED flag for stream 10.204.0.29:46659
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: [10.3.0.150:30009] Initialized incoming SRTP with SDES crypto params: suite AES_CM_256_HMAC_SHA1_80, tag 9, key Eo21u0Vcxp5takAELuMsfm6TQ5TKRMBGhL6M8jDOiUk= salt +Ys2ti5a22OY9OWE7Qw=
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: [2] Initialized outgoing SRTP with SDES crypto params: <none>
Mar  4 17:58:40 opensips rtpengine[29225]: INFO: [cz3V4dI1uF18EFMNmskgwg..]: Replying to 'offer' from 127.0.0.1:37379 (elapsed time 0.000679 sec)
Mar  4 17:58:40 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Response dump for 'offer' to 127.0.0.1:37379: { "sdp": "v=0#015#012o=Zoiper 1045030 0 IN IP4 10.3.0.150#015#012s=Z#015#012c=IN IP4 10.3.0.150#015#012t=0 0#015#012m=audio 30000 RTP/AVP 101 8 0#015#012a=rtpmap:101 telephone-event/8000#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:0 PCMU/8000#015#012a=fmtp:101 0-16#015#012a=sendrecv#015#012a=rtcp:30001#015#012", "result": "ok" }
Mar  4 17:58:40 opensips /data/opensips/sbin/opensips[17371]: callid=cz3V4dI1uF18EFMNmskgwg..: route[rtpengine]: INVITE has SDP -> rtpengine_offered and successfull, avp(nat) normal
Mar  4 17:58:40 opensips /data/opensips/sbin/opensips[17371]: callid=cz3V4dI1uF18EFMNmskgwg..: Branch_route[per_branch_ops]: new branch at sip:3215666666@192.168.174.251:5060;transport=udp
Mar  4 17:58:40 opensips /data/opensips/sbin/opensips[17361]: callid=cz3V4dI1uF18EFMNmskgwg..: Onreply_route[handle_nat]: incoming reply
Mar  4 17:58:40 opensips /data/opensips/sbin/opensips[17361]: callid=cz3V4dI1uF18EFMNmskgwg..: route[setrtpengineflagsonreply]: call is from gateway -> var(rtpengine_flags): in-iface=provider out-iface=phone replace-session-connection replace-origin ICE=remove
Mar  4 17:58:41 opensips rtpengine[29225]: DEBUG: timer run time = 0.000016 sec
Mar  4 17:58:41 opensips /data/opensips/sbin/opensips[17361]: callid=cz3V4dI1uF18EFMNmskgwg..: Onreply_route[handle_nat]: incoming reply
Mar  4 17:58:41 opensips /data/opensips/sbin/opensips[17361]: callid=cz3V4dI1uF18EFMNmskgwg..: route[setrtpengineflagsonreply]: call is from gateway -> var(rtpengine_flags): in-iface=provider out-iface=phone replace-session-connection replace-origin ICE=remove
Mar  4 17:58:41 opensips /data/opensips/sbin/opensips[17361]: callid=cz3V4dI1uF18EFMNmskgwg..: Onreply_route[handle_nat]: incoming reply
Mar  4 17:58:41 opensips /data/opensips/sbin/opensips[17361]: callid=cz3V4dI1uF18EFMNmskgwg..: route[setrtpengineflagsonreply]: call is from gateway -> var(rtpengine_flags): in-iface=provider out-iface=phone replace-session-connection replace-origin ICE=remove
Mar  4 17:58:42 opensips rtpengine[29225]: DEBUG: timer run time = 0.000011 sec
Mar  4 17:58:43 opensips rtpengine[29225]: DEBUG: timer run time = 0.000011 sec
Mar  4 17:58:45 opensips rtpengine[29225]: DEBUG: timer run time = 0.000012 sec
Mar  4 17:58:46 opensips rtpengine[29225]: ERR: [cz3V4dI1uF18EFMNmskgwg.. port 30000]: SRTP output wanted, but no crypto suite was negotiated
Mar  4 17:58:46 opensips /data/opensips/sbin/opensips[17361]: callid=cz3V4dI1uF18EFMNmskgwg..: Onreply_route[handle_nat]: incoming reply
Mar  4 17:58:46 opensips /data/opensips/sbin/opensips[17361]: callid=cz3V4dI1uF18EFMNmskgwg..: route[setrtpengineflagsonreply]: call is from gateway -> var(rtpengine_flags): in-iface=provider out-iface=phone replace-session-connection replace-origin ICE=remove
Mar  4 17:58:46 opensips /data/opensips/sbin/opensips[17361]: callid=cz3V4dI1uF18EFMNmskgwg..: Onreply_route[handle_nat]:rtpengine_answer as avp(nat) normal=normal
Mar  4 17:58:46 opensips rtpengine[29225]: INFO: [cz3V4dI1uF18EFMNmskgwg..]: Received command 'answer' from 127.0.0.1:33322
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Dump for 'answer' from 127.0.0.1:33322: { "sdp": "v=0#015#012o=Sonus_UAC 108138770323554 108138770323554 IN IP4 192.168.174.251#015#012s=-#015#012c=IN IP4 192.168.174.251#015#012t=0 0#015#012m=audio 20268 RTP/AVP 8 101#015#012a=sendrecv#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-15#015#012a=maxptime:20#015#012", "ICE": "remove", "direction": [ "provider", "phone" ], "replace": [ "session-connection", "origin" ], "call-id": "cz3V4dI1uF18EFMNmskgwg..", "received-from": [ "IP4", "192.168.174.251" ], "from-tag": "672df ...
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: ... 213", "to-tag": "sip+3+f07018d+d62f25eb", "command": "answer" }
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Eliminating asymmetric inbound codec PCMU/8000
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Default sink codec is PCMA/8000
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Eliminating asymmetric outbound codec PCMU/8000
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Creating codec handler for PCMA/8000
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Sink supports codec PCMA/8000
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Creating codec handler for telephone-event/8000
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: [10.3.0.150:30008] Initialized incoming SRTP with SDES crypto params: suite AES_CM_256_HMAC_SHA1_80, tag 9, key Eo21u0Vcxp5takAELuMsfm6TQ5TKRMBGhL6M8jDOiUk= salt +Ys2ti5a22OY9OWE7Qw=
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: [1] Initialized outgoing SRTP with SDES crypto params: suite AES_CM_256_HMAC_SHA1_80, tag 9, key nEkwQXmwy4z6WVS/OWrrCv/0eKxdL8/9ZO76qeSlI50= salt XO2Zj4NRxJMD19XkfUQ=
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: [10.3.0.150:30009] Initialized incoming SRTP with SDES crypto params: suite AES_CM_256_HMAC_SHA1_80, tag 9, key Eo21u0Vcxp5takAELuMsfm6TQ5TKRMBGhL6M8jDOiUk= salt +Ys2ti5a22OY9OWE7Qw=
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: [2] Initialized outgoing SRTP with SDES crypto params: suite AES_CM_256_HMAC_SHA1_80, tag 9, key nEkwQXmwy4z6WVS/OWrrCv/0eKxdL8/9ZO76qeSlI50= salt XO2Zj4NRxJMD19XkfUQ=
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: set FILLED flag for stream 192.168.174.251:20268
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: set FILLED flag for stream 192.168.174.251:20269
Mar  4 17:58:46 opensips rtpengine[29225]: INFO: [cz3V4dI1uF18EFMNmskgwg..]: Replying to 'answer' from 127.0.0.1:33322 (elapsed time 0.000268 sec)
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Response dump for 'answer' to 127.0.0.1:33322: { "sdp": "v=0#015#012o=Sonus_UAC 108138770323554 108138770323554 IN IP4 10.200.0.150#015#012s=-#015#012c=IN IP4 10.200.0.150#015#012t=0 0#015#012m=audio 30008 RTP/SAVP 8 101#015#012a=maxptime:20#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-15#015#012a=sendrecv#015#012a=rtcp:30009#015#012a=crypto:9 AES_CM_256_HMAC_SHA1_80 inline:nEkwQXmwy4z6WVS/OWrrCv/0eKxdL8/9ZO76qeSlI51c7ZmPg1HEkwPX1eR9RJ#015#012", "result": "ok" }
Mar  4 17:58:46 opensips /data/opensips/sbin/opensips[17361]: callid=cz3V4dI1uF18EFMNmskgwg..: Onreply_route[handle_nat]: incoming reply
Mar  4 17:58:46 opensips /data/opensips/sbin/opensips[17361]: callid=cz3V4dI1uF18EFMNmskgwg..: Onreply_route[handle_nat]: extra accounting, source_ip 192.168.174.251 of first final reply is dest_ip
Mar  4 17:58:46 opensips /data/opensips/sbin/opensips[17361]: callid=cz3V4dI1uF18EFMNmskgwg..: route[setrtpengineflagsonreply]: call is from gateway -> var(rtpengine_flags): in-iface=provider out-iface=phone replace-session-connection replace-origin ICE=remove
Mar  4 17:58:46 opensips /data/opensips/sbin/opensips[17361]: callid=cz3V4dI1uF18EFMNmskgwg..: Onreply_route[handle_nat]:rtpengine_answer as avp(nat) normal=normal
Mar  4 17:58:46 opensips rtpengine[29225]: INFO: [cz3V4dI1uF18EFMNmskgwg..]: Received command 'answer' from 127.0.0.1:33322
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Dump for 'answer' from 127.0.0.1:33322: { "sdp": "v=0#015#012o=Sonus_UAC 108138770323554 108138770323554 IN IP4 192.168.174.251#015#012s=-#015#012c=IN IP4 192.168.174.251#015#012t=0 0#015#012m=audio 20268 RTP/AVP 8 101#015#012a=sendrecv#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-15#015#012a=maxptime:20#015#012", "ICE": "remove", "direction": [ "provider", "phone" ], "replace": [ "session-connection", "origin" ], "call-id": "cz3V4dI1uF18EFMNmskgwg..", "received-from": [ "IP4", "192.168.174.251" ], "from-tag": "672df ...
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: ... 213", "to-tag": "sip+3+f07018d+d62f25eb", "command": "answer" }
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Default sink codec is PCMA/8000
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Sink supports codec PCMA/8000
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: __free_ssrc_handler
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: __free_ssrc_handler
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: [10.3.0.150:30008] Initialized incoming SRTP with SDES crypto params: suite AES_CM_256_HMAC_SHA1_80, tag 9, key Eo21u0Vcxp5takAELuMsfm6TQ5TKRMBGhL6M8jDOiUk= salt +Ys2ti5a22OY9OWE7Qw=
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: [1] Initialized outgoing SRTP with SDES crypto params: suite AES_CM_256_HMAC_SHA1_80, tag 9, key nEkwQXmwy4z6WVS/OWrrCv/0eKxdL8/9ZO76qeSlI50= salt XO2Zj4NRxJMD19XkfUQ=
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: [10.3.0.150:30009] Initialized incoming SRTP with SDES crypto params: suite AES_CM_256_HMAC_SHA1_80, tag 9, key Eo21u0Vcxp5takAELuMsfm6TQ5TKRMBGhL6M8jDOiUk= salt +Ys2ti5a22OY9OWE7Qw=
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: [2] Initialized outgoing SRTP with SDES crypto params: suite AES_CM_256_HMAC_SHA1_80, tag 9, key nEkwQXmwy4z6WVS/OWrrCv/0eKxdL8/9ZO76qeSlI50= salt XO2Zj4NRxJMD19XkfUQ=
Mar  4 17:58:46 opensips rtpengine[29225]: INFO: [cz3V4dI1uF18EFMNmskgwg..]: Replying to 'answer' from 127.0.0.1:33322 (elapsed time 0.000175 sec)
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Response dump for 'answer' to 127.0.0.1:33322: { "sdp": "v=0#015#012o=Sonus_UAC 108138770323554 108138770323554 IN IP4 10.200.0.150#015#012s=-#015#012c=IN IP4 10.200.0.150#015#012t=0 0#015#012m=audio 30008 RTP/SAVP 8 101#015#012a=maxptime:20#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-15#015#012a=sendrecv#015#012a=rtcp:30009#015#012a=crypto:9 AES_CM_256_HMAC_SHA1_80 inline:nEkwQXmwy4z6WVS/OWrrCv/0eKxdL8/9ZO76qeSlI51c7ZmPg1HEkwPX1eR9RJ#015#012", "result": "ok" }
Mar  4 17:58:46 opensips /data/opensips/sbin/opensips[17371]: callid=cz3V4dI1uF18EFMNmskgwg..: route[relay]: routing the call
Mar  4 17:58:46 opensips /data/opensips/sbin/opensips[17371]: callid=cz3V4dI1uF18EFMNmskgwg..: route[relay]: routing the call
Mar  4 17:58:46 opensips /data/opensips/sbin/opensips[17371]: callid=cz3V4dI1uF18EFMNmskgwg..: route[rtpengine]: method == BYE || CANCEL -> rtpengine_delete
Mar  4 17:58:46 opensips rtpengine[29225]: INFO: [cz3V4dI1uF18EFMNmskgwg..]: Received command 'delete' from 127.0.0.1:37379
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Dump for 'delete' from 127.0.0.1:37379: { "call-id": "cz3V4dI1uF18EFMNmskgwg..", "received-from": [ "IP4", "10.204.0.29" ], "from-tag": "672df213", "command": "delete" }
Mar  4 17:58:46 opensips rtpengine[29225]: INFO: [cz3V4dI1uF18EFMNmskgwg..]: Scheduling deletion of call branch '672df213' (via-branch '') in 30 seconds
Mar  4 17:58:46 opensips rtpengine[29225]: INFO: [cz3V4dI1uF18EFMNmskgwg..]: Replying to 'delete' from 127.0.0.1:37379 (elapsed time 0.000184 sec)
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: Response dump for 'delete' to 127.0.0.1:37379: { "created": 1551722320, "created_us": 322182, "last signal": 1551722326, "SSRC": { "300219398": {  } }, "tags": { "672df213": { "tag": "672df213", "created": 1551722320, "in dialogue with": "sip+3+f07018d+d62f25eb", "medias": [ { "index": 1, "type": "audio", "protocol": "RTP/SAVP", "streams": [ { "local port": 30008, "endpoint": { "family": "IPv4", "address": "10.204.0.29", "port": 46658 }, "advertised endpoint": { "family": "IPv4", "address": "10. ...
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: ... 204.0.29", "port": 46658 }, "crypto suite": "AES_CM_256_HMAC_SHA1_80", "last packet": 1551722320, "flags": [ "RTP", "filled" ], "stats": { "packets": 0, "bytes": 0, "errors": 0 } }, { "local port": 30009, "endpoint": { "family": "IPv4", "address": "10.204.0.29", "port": 46659 }, "advertised endpoint": { "family": "IPv4", "address": "10.204.0.29", "port": 46659 }, "crypto suite": "AES_CM_256_HMAC_SHA1_80", "last packet": 1551722320, "flags": [ "RTCP", "filled" ], "stats": { "packets": 0, "bytes": ...
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: ...  0, "errors": 0 } } ], "flags": [ "initialized", "send", "recv", "SDES" ] } ] }, "sip+3+f07018d+d62f25eb": { "tag": "sip+3+f07018d+d62f25eb", "created": 1551722320, "in dialogue with": "672df213", "medias": [ { "index": 1, "type": "audio", "protocol": "RTP/AVP", "streams": [ { "local port": 30000, "endpoint": { "family": "IPv4", "address": "192.168.174.251", "port": 20268 }, "advertised endpoint": { "family": "IPv4", "address": "192.168.174.251", "port": 20268 }, "last packet": 1551722326, "flag ...
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: ... s": [ "RTP", "filled" ], "SSRC": 300219398, "stats": { "packets": 21, "bytes": 3612, "errors": 0 } }, { "local port": 30001, "endpoint": { "family": "IPv4", "address": "192.168.174.251", "port": 20269 }, "advertised endpoint": { "family": "IPv4", "address": "192.168.174.251", "port": 20269 }, "last packet": 1551722320, "flags": [ "RTCP", "filled" ], "stats": { "packets": 0, "bytes": 0, "errors": 0 } } ], "flags": [ "initialized", "send", "recv", "ICE controlling" ] } ] } }, "totals": { "RTP": {  ...
Mar  4 17:58:46 opensips rtpengine[29225]: DEBUG: [cz3V4dI1uF18EFMNmskgwg..]: ... "packets": 21, "bytes": 3612, "errors": 0 }, "RTCP": { "packets": 0, "bytes": 0, "errors": 0 } }, "result": "ok" }
Mar  4 17:58:47 opensips rtpengine[29225]: DEBUG: timer run time = 0.000014 sec
Mar  4 17:58:48 opensips rtpengine[29225]: DEBUG: timer run time = 0.000013 sec
Mar  4 17:58:49 opensips rtpengine[29225]: DEBUG: timer run time = 0.000011 sec
Mar  4 17:58:50 opensips rtpengine[29225]: DEBUG: timer run time = 0.000010 sec
Mar  4 17:58:52 opensips rtpengine[29225]: DEBUG: timer run time = 0.000012 sec
Mar  4 17:58:53 opensips rtpengine[29225]: DEBUG: timer run time = 0.000012 sec
Mar  4 17:58:55 opensips rtpengine[29225]: DEBUG: timer run time = 0.000012 sec
Mar  4 17:58:57 opensips rtpengine[29225]: DEBUG: timer run time = 0.000011 sec
Mar  4 17:58:58 opensips rtpengine[29225]: DEBUG: timer run time = 0.000012 sec
Mar  4 17:59:00 opensips rtpengine[29225]: DEBUG: timer run time = 0.000012 sec
Mar  4 17:59:01 opensips rtpengine[29225]: DEBUG: timer run time = 0.000011 sec
Mar  4 17:59:01 opensips CRON[29945]: (root) CMD (/usr/local/rtm/bin/rtm 28 > /dev/null 2> /dev/null)
Mar  4 17:59:02 opensips rtpengine[29225]: DEBUG: timer run time = 0.000019 sec
Mar  4 17:59:04 opensips rtpengine[29225]: DEBUG: timer run time = 0.000012 sec
Mar  4 17:59:04 opensips systemd[1]: Started Check_MK (10.3.0.34:43536).
Mar  4 17:59:06 opensips rtpengine[29225]: DEBUG: timer run time = 0.000021 sec
Mar  4 17:59:07 opensips rtpengine[29225]: DEBUG: timer run time = 0.000011 sec
Mar  4 17:59:09 opensips rtpengine[29225]: DEBUG: timer run time = 0.000013 sec
Mar  4 17:59:11 opensips rtpengine[29225]: DEBUG: timer run time = 0.000012 sec
Mar  4 17:59:12 opensips rtpengine[29225]: DEBUG: timer run time = 0.000013 sec
Mar  4 17:59:14 opensips rtpengine[29225]: DEBUG: timer run time = 0.000013 sec
Mar  4 17:59:16 opensips rtpengine[29225]: INFO: [cz3V4dI1uF18EFMNmskgwg..]: Call branch '672df213' (via-branch '') deleted, no more branches remaining
Mar  4 17:59:16 opensips rtpengine[29225]: INFO: [cz3V4dI1uF18EFMNmskgwg..]: Final packet stats:
Mar  4 17:59:16 opensips rtpengine[29225]: INFO: [cz3V4dI1uF18EFMNmskgwg..]: --- Tag '672df213', created 0:36 ago for branch '', in dialogue with 'sip+3+f07018d+d62f25eb'
Mar  4 17:59:16 opensips rtpengine[29225]: INFO: [cz3V4dI1uF18EFMNmskgwg..]: ------ Media #1 (audio over RTP/SAVP) using unknown codec
Mar  4 17:59:16 opensips rtpengine[29225]: INFO: [cz3V4dI1uF18EFMNmskgwg..]: --------- Port      10.3.0.150:30008 <>     10.204.0.29:46658, SSRC 0, 0 p, 0 b, 0 e, 36 ts
Mar  4 17:59:16 opensips rtpengine[29225]: INFO: [cz3V4dI1uF18EFMNmskgwg..]: --------- Port      10.3.0.150:30009 <>     10.204.0.29:46659 (RTCP), SSRC 0, 0 p, 0 b, 0 e, 36 ts
Mar  4 17:59:16 opensips rtpengine[29225]: INFO: [cz3V4dI1uF18EFMNmskgwg..]: --- Tag 'sip+3+f07018d+d62f25eb', created 0:36 ago for branch '', in dialogue with '672df213'
Mar  4 17:59:16 opensips rtpengine[29225]: INFO: [cz3V4dI1uF18EFMNmskgwg..]: ------ Media #1 (audio over RTP/AVP) using PCMA/8000
Mar  4 17:59:16 opensips rtpengine[29225]: INFO: [cz3V4dI1uF18EFMNmskgwg..]: --------- Port      10.3.0.150:30000 <> 192.168.174.251:20268, SSRC 11e4fc06, 27 p, 4644 b, 0 e, 30 ts
Mar  4 17:59:16 opensips rtpengine[29225]: INFO: [cz3V4dI1uF18EFMNmskgwg..]: --------- Port      10.3.0.150:30001 <> 192.168.174.251:20269 (RTCP), SSRC 0, 0 p, 0 b, 0 e, 36 ts

**Comment by rfuchs** [comment]
Same issue as #717
