### ISSUE TITLE
a=sip , b=tls; a hears b but b does not hear a

### ISSUE THREAD

**Issue by johandeclercqdemocon** [sipwise/rtpengine#727]
Hello again Richard, 

when I make a call from a registered user A on transport udp to another user B on transport tls , a hears B but B does not hear A. 
To me it seems that this is a phone issue, at least I don't see an error in this log:

Mar  7 21:19:21 opensips /data/opensips/sbin/opensips[13100]: callid=8XXWQF4oMTepP3HrEZRR0Q..: route[setrtpengineflags]:lookup(location) B is user, A is UDP, B is TLS -> var(rtpengine_flags): RTP/SAVP pad-crypto in-iface=phone out-iface=phone replace-session-connection replace-origin ICE=remove
Mar  7 21:19:21 opensips /data/opensips/sbin/opensips[13100]: callid=8XXWQF4oMTepP3HrEZRR0Q..: route[setrtpengineflags] -> Exit
Mar  7 21:19:21 opensips /data/opensips/sbin/opensips[13100]: callid=8XXWQF4oMTepP3HrEZRR0Q..: route[setadvertisedaddress]:call is from echo avp(si) echo, advertised address is 10.200.0.150
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: Adding a proxy for control ng stats:127.0.0.1
Mar  7 21:19:21 opensips rtpengine[23951]: INFO: [8XXWQF4oMTepP3HrEZRR0Q..]: Received command 'offer' from 127.0.0.1:33665
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Dump for 'offer' from 127.0.0.1:33665: { "sdp": "v=0#015#012o=Zoiper 1900699 0 IN IP4 10.204.0.21#015#012s=Z#015#012c=IN IP4 10.204.0.21#015#012t=0 0#015#012m=audio 38316 RTP/AVP 3 101 0 8 110 97#015#012a=rtpmap:3 GSM/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-16#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:110 speex/8000#015#012a=rtpmap:97 iLBC/8000#015#012a=fmtp:97 mode=30#015#012a=sendrecv#015#012", "ICE": "remove", "direction": [ "phone", "phone" ], "flags": [ "pad-crypto" ], "replace": [ "session-connection", "origin" ], "transpo ...
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: ... rt-protocol": "RTP/SAVP", "call-id": "8XXWQF4oMTepP3HrEZRR0Q..", "received-from": [ "IP4", "10.204.0.21" ], "from-tag": "ad62bf5e", "command": "offer" }
Mar  7 21:19:21 opensips rtpengine[23951]: NOTICE: [8XXWQF4oMTepP3HrEZRR0Q..]: Creating new call
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Default sink codec is GSM/8000
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Creating codec handler for GSM/8000
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Sink supports codec GSM/8000
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Creating codec handler for telephone-event/8000
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Creating codec handler for PCMU/8000
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Sink supports codec PCMU/8000
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Creating codec handler for PCMA/8000
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Sink supports codec PCMA/8000
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Creating codec handler for speex/8000
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Sink supports codec speex/8000
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Creating codec handler for iLBC/8000
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: [10.3.0.150:30000] Initialized incoming SRTP with SDES crypto params: <none>
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: [1] Initialized outgoing SRTP with SDES crypto params: suite AES_CM_128_HMAC_SHA1_80, tag 1, key nPiAuXPugPXNfKtRnsCJAw== salt igqTkpWcAEWxEPOep9o=
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: [10.3.0.150:30001] Initialized incoming SRTP with SDES crypto params: <none>
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: [2] Initialized outgoing SRTP with SDES crypto params: suite AES_CM_128_HMAC_SHA1_80, tag 1, key nPiAuXPugPXNfKtRnsCJAw== salt igqTkpWcAEWxEPOep9o=
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: set FILLED flag for stream 10.204.0.21:38316
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: set FILLED flag for stream 10.204.0.21:38317
Mar  7 21:19:21 opensips rtpengine[23951]: INFO: [8XXWQF4oMTepP3HrEZRR0Q..]: Replying to 'offer' from 127.0.0.1:33665 (elapsed time 0.002468 sec)
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Response dump for 'offer' to 127.0.0.1:33665: { "sdp": "v=0#015#012o=Zoiper 1900699 0 IN IP4 10.200.0.150#015#012s=Z#015#012c=IN IP4 10.200.0.150#015#012t=0 0#015#012m=audio 30000 RTP/SAVP 3 101 0 8 110 97#015#012a=rtpmap:3 GSM/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:110 speex/8000#015#012a=rtpmap:97 iLBC/8000#015#012a=fmtp:101 0-16#015#012a=fmtp:97 mode=30#015#012a=sendrecv#015#012a=rtcp:30001#015#012a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:nPiAuXPugPXNfKtRnsCJA4oKk5KVnABFsRDznqfa#015#012a=crypto:2 AES_CM_128_HMAC_SH ...
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: ... A1_32 inline:jZPx2UUw1disdI3N5+DM5QnYwwwv+EiM0DE1jV7S#015#012a=crypto:3 AES_CM_192_HMAC_SHA1_80 inline:ka/4IvCxgLPkntmNjh9DZ9gfOQKs02xHE6mgbuh5WYXun9X4wSs=#015#012a=crypto:4 AES_CM_192_HMAC_SHA1_32 inline:sBBJBJt5WDqAFVpvOGDnVimjzJ3Ebw2bzbbPO+DZ7A4cNbWEc/0=#015#012a=crypto:5 AES_CM_256_HMAC_SHA1_80 inline:10aO2AD6Wt7bHKaVyVeJ9qXxpTYM4hbmrZv+AnG6pppa0VpiYZJCyY/4c455q5==#015#012a=crypto:6 AES_CM_256_HMAC_SHA1_32 inline:emFoadN5alwZrUj901JiorVlSnLd3A2DsG7llFaqLiimXM2ffLkKtMbgoV+ltC==#015#012a=crypto:7 F8_128_HMAC_SHA1_80 inline ...
Mar  7 21:19:21 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: ... :Hy580bdMd8aRtQsGGkVw1lZoYYX7ZyX5rFWG/mEa#015#012a=crypto:8 F8_128_HMAC_SHA1_32 inline:nO8zxVSee3A3J93sIjLEz6twIeswbfPK82v+uzOT#015#012a=crypto:9 NULL_HMAC_SHA1_80 inline:+pIUjsP7DM+5cgKRtvr16rlg8qLGf6pWXVQXabFU#015#012a=crypto:10 NULL_HMAC_SHA1_32 inline:I6xWCtCoPByDS9e/qgda6wfxLLU3gKN6FqKKfdQF#015#012a=setup:actpass#015#012a=fingerprint:sha-1 6D:49:6B:29:C2:D1:14:8F:76:C1:A5:F0:3C:D5:4F:D2:A7:F2:30:E0#015#012", "result": "ok" }
Mar  7 21:19:21 opensips /data/opensips/sbin/opensips[13100]: callid=8XXWQF4oMTepP3HrEZRR0Q..: route[rtpengine]: INVITE has SDP -> rtpengine_offered and successfull, avp(nat) normal
Mar  7 21:19:21 opensips /data/opensips/sbin/opensips[13100]: callid=8XXWQF4oMTepP3HrEZRR0Q..: Branch_route[per_branch_ops]: new branch at sip:32478720105@10.204.0.29:51295;transport=TLS;rinstance=645bd0e8f95af2b3
Mar  7 21:19:22 opensips rtpengine[23951]: DEBUG: timer run time = 0.000043 sec
Mar  7 21:19:22 opensips /data/opensips/sbin/opensips[13112]: callid=8XXWQF4oMTepP3HrEZRR0Q..: Onreply_route[handle_nat]: incoming reply
Mar  7 21:19:22 opensips /data/opensips/sbin/opensips[13112]: callid=8XXWQF4oMTepP3HrEZRR0Q..: onreply_route[handle_nat]: start, we call route(setadvertisedaddress)
Mar  7 21:19:22 opensips /data/opensips/sbin/opensips[13112]: callid=8XXWQF4oMTepP3HrEZRR0Q..: route[setadvertisedaddress]:call is from echo avp(si) echo, advertised address is 10.200.0.150
Mar  7 21:19:22 opensips /data/opensips/sbin/opensips[13112]: callid=8XXWQF4oMTepP3HrEZRR0Q..: Onreply_route[handle_nat]: incoming reply
Mar  7 21:19:22 opensips /data/opensips/sbin/opensips[13112]: callid=8XXWQF4oMTepP3HrEZRR0Q..: onreply_route[handle_nat]: start, we call route(setadvertisedaddress)
Mar  7 21:19:22 opensips /data/opensips/sbin/opensips[13112]: callid=8XXWQF4oMTepP3HrEZRR0Q..: route[setadvertisedaddress]:call is from echo avp(si) echo, advertised address is 10.200.0.150
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: timer run time = 0.000031 sec
Mar  7 21:19:24 opensips rtpengine[23951]: WARNING: [8XXWQF4oMTepP3HrEZRR0Q.. port 30000]: RTP packet with unknown payload type 95 received
Mar  7 21:19:24 opensips rtpengine[23951]: ERR: [8XXWQF4oMTepP3HrEZRR0Q.. port 30000]: SRTP output wanted, but no crypto suite was negotiated
Mar  7 21:19:24 opensips /data/opensips/sbin/opensips[13112]: callid=8XXWQF4oMTepP3HrEZRR0Q..: Onreply_route[handle_nat]: incoming reply
Mar  7 21:19:24 opensips /data/opensips/sbin/opensips[13112]: callid=8XXWQF4oMTepP3HrEZRR0Q..: onreply_route[handle_nat]: start, we call route(setadvertisedaddress)
Mar  7 21:19:24 opensips /data/opensips/sbin/opensips[13112]: callid=8XXWQF4oMTepP3HrEZRR0Q..: route[setadvertisedaddress]:call is from echo avp(si) echo, advertised address is 10.200.0.150
Mar  7 21:19:24 opensips /data/opensips/sbin/opensips[13112]: callid=8XXWQF4oMTepP3HrEZRR0Q..: Onreply_route[handle_nat]: extra accounting, source_ip 10.204.0.29 of first final reply is dest_ip
Mar  7 21:19:24 opensips /data/opensips/sbin/opensips[13112]: callid=8XXWQF4oMTepP3HrEZRR0Q..: route[setrtpengineflagsonreply] -> entry
Mar  7 21:19:24 opensips /data/opensips/sbin/opensips[13112]: callid=8XXWQF4oMTepP3HrEZRR0Q..: route[setrtpengineflagsonreply] avp(si) echo==echo
Mar  7 21:19:24 opensips /data/opensips/sbin/opensips[13112]: ERROR:core:parse_uri: uri too short: <200> (3)
Mar  7 21:19:24 opensips /data/opensips/sbin/opensips[13112]: ERROR:registrar:extract_aor: failed to parse Address of Record
Mar  7 21:19:24 opensips /data/opensips/sbin/opensips[13112]: ERROR:registrar:lookup: failed to extract address of record
Mar  7 21:19:24 opensips /data/opensips/sbin/opensips[13112]: callid=8XXWQF4oMTepP3HrEZRR0Q..: route[setrtpengineflagsonreply]:default B is Dust user, A is UDP, B is TLS -> var(rtpengine_flags): RTP/AVP in-iface=phone out-iface=phone replace-session-connection replace-origin ICE=remove
Mar  7 21:19:24 opensips /data/opensips/sbin/opensips[13112]: callid=8XXWQF4oMTepP3HrEZRR0Q..: route[setrtpengineflagsonreply] -> exit
Mar  7 21:19:24 opensips /data/opensips/sbin/opensips[13112]: callid=8XXWQF4oMTepP3HrEZRR0Q..: Onreply_route[handle_nat]:rtpengine_answer as avp(nat) normal=normal
Mar  7 21:19:24 opensips rtpengine[23951]: INFO: [8XXWQF4oMTepP3HrEZRR0Q..]: Received command 'answer' from 127.0.0.1:47432
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Dump for 'answer' from 127.0.0.1:47432: { "sdp": "v=0#015#012o=Zoiper 0 2 IN IP4 10.204.0.29#015#012s=Z#015#012c=IN IP4 10.204.0.29#015#012t=0 0#015#012m=audio 62780 RTP/SAVP 0 8 101#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-16#015#012a=sendrecv#015#012a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:eFF2WwHyHky87+AsPtToUR9q0zfJA8LXcYUau+Xb#015#012", "ICE": "remove", "direction": [ "phone", "phone" ], "replace": [ "session-connection", "origin" ], "transport-protocol": "RTP/AVP", "call-id": "8XXWQF4 ...
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: ... oMTepP3HrEZRR0Q..", "received-from": [ "IP4", "10.204.0.29" ], "from-tag": "ad62bf5e", "to-tag": "f3231059", "command": "answer" }
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Eliminating asymmetric inbound codec GSM/8000
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Eliminating asymmetric inbound codec speex/8000
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Eliminating asymmetric inbound codec iLBC/8000
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Default sink codec is PCMU/8000
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Eliminating asymmetric outbound codec GSM/8000
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Eliminating asymmetric outbound codec speex/8000
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Eliminating asymmetric outbound codec iLBC/8000
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Creating codec handler for PCMU/8000
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Sink supports codec PCMU/8000
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Creating codec handler for PCMA/8000
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Sink supports codec PCMA/8000
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Creating codec handler for telephone-event/8000
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: set FILLED flag for stream 10.204.0.29:62780
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: [10.3.0.150:30000] Initialized incoming SRTP with SDES crypto params: suite AES_CM_128_HMAC_SHA1_80, tag 1, key eFF2WwHyHky87+AsPtToUQ== salt H2rTN8kDwtdxhRq75ds=
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: [1] Initialized outgoing SRTP with SDES crypto params: suite AES_CM_128_HMAC_SHA1_80, tag 1, key nPiAuXPugPXNfKtRnsCJAw== salt igqTkpWcAEWxEPOep9o=
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: set FILLED flag for stream 10.204.0.29:62781
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: [10.3.0.150:30001] Initialized incoming SRTP with SDES crypto params: suite AES_CM_128_HMAC_SHA1_80, tag 1, key eFF2WwHyHky87+AsPtToUQ== salt H2rTN8kDwtdxhRq75ds=
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: [2] Initialized outgoing SRTP with SDES crypto params: suite AES_CM_128_HMAC_SHA1_80, tag 1, key nPiAuXPugPXNfKtRnsCJAw== salt igqTkpWcAEWxEPOep9o=
Mar  7 21:19:24 opensips rtpengine[23951]: INFO: [8XXWQF4oMTepP3HrEZRR0Q..]: Replying to 'answer' from 127.0.0.1:47432 (elapsed time 0.000368 sec)
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Response dump for 'answer' to 127.0.0.1:47432: { "sdp": "v=0#015#012o=Zoiper 0 2 IN IP4 10.200.0.150#015#012s=Z#015#012c=IN IP4 10.200.0.150#015#012t=0 0#015#012m=audio 30020 RTP/AVP 0 8 101#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-16#015#012a=sendrecv#015#012a=rtcp:30021#015#012", "result": "ok" }
Mar  7 21:19:24 opensips /data/opensips/sbin/opensips[13100]: callid=8XXWQF4oMTepP3HrEZRR0Q..: route[relay]: routing the call
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q.. port 30000]: bubble up pt 0 from idx 1 to 0
Mar  7 21:19:24 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q.. port 30000]: bubble up pt 0 from idx 1 to 0
Mar  7 21:19:25 opensips rtpengine[23951]: DEBUG: timer run time = 0.000011 sec
Mar  7 21:19:27 opensips rtpengine[23951]: DEBUG: timer run time = 0.000014 sec
Mar  7 21:19:27 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q.. port 30001]: Calling handler for RTCP packet type 201
Mar  7 21:19:27 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q.. port 30001]: Calling handler for RTCP packet type 202
Mar  7 21:19:28 opensips rtpengine[23951]: DEBUG: timer run time = 0.000013 sec
Mar  7 21:19:28 opensips rtpengine[23951]: INFO: [8XXWQF4oMTepP3HrEZRR0Q.. port 30000]: Confirmed peer address as 10.204.0.29:62780
Mar  7 21:19:30 opensips rtpengine[23951]: DEBUG: timer run time = 0.000011 sec
Mar  7 21:19:31 opensips rtpengine[23951]: DEBUG: timer run time = 0.000012 sec
Mar  7 21:19:31 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q.. port 30001]: Calling handler for RTCP packet type 201
Mar  7 21:19:31 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q.. port 30001]: Calling handler for RTCP packet type 202
Mar  7 21:19:31 opensips rtpengine[23951]: INFO: [8XXWQF4oMTepP3HrEZRR0Q.. port 30001]: Confirmed peer address as 10.204.0.29:62781
Mar  7 21:19:33 opensips rtpengine[23951]: DEBUG: timer run time = 0.000014 sec
Mar  7 21:19:34 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q.. port 30001]: Calling handler for RTCP packet type 201
Mar  7 21:19:34 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q.. port 30001]: Calling handler for RTCP packet type 202
Mar  7 21:19:34 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q.. port 30001]: Calling handler for RTCP packet type 203
Mar  7 21:19:34 opensips /data/opensips/sbin/opensips[13112]: callid=8XXWQF4oMTepP3HrEZRR0Q..: route[relay]: routing the call
Mar  7 21:19:34 opensips /data/opensips/sbin/opensips[13112]: callid=8XXWQF4oMTepP3HrEZRR0Q..: route[rtpengine]: method == BYE || CANCEL -> rtpengine_delete
Mar  7 21:19:34 opensips rtpengine[23951]: INFO: [8XXWQF4oMTepP3HrEZRR0Q..]: Received command 'delete' from 127.0.0.1:47432
Mar  7 21:19:34 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Dump for 'delete' from 127.0.0.1:47432: { "call-id": "8XXWQF4oMTepP3HrEZRR0Q..", "received-from": [ "IP4", "10.204.0.29" ], "from-tag": "f3231059", "command": "delete" }
Mar  7 21:19:34 opensips rtpengine[23951]: INFO: [8XXWQF4oMTepP3HrEZRR0Q..]: Scheduling deletion of call branch 'f3231059' (via-branch '') in 30 seconds
Mar  7 21:19:34 opensips rtpengine[23951]: INFO: [8XXWQF4oMTepP3HrEZRR0Q..]: Replying to 'delete' from 127.0.0.1:47432 (elapsed time 0.000118 sec)
Mar  7 21:19:34 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: Response dump for 'delete' to 127.0.0.1:47432: { "created": 1551993561, "created_us": 827819, "last signal": 1551993564, "SSRC": { "3977644928": {  } }, "tags": { "f3231059": { "tag": "f3231059", "created": 1551993561, "in dialogue with": "ad62bf5e", "medias": [ { "index": 1, "type": "audio", "protocol": "RTP/SAVP", "streams": [ { "local port": 30000, "endpoint": { "family": "IPv4", "address": "10.204.0.29", "port": 62780 }, "advertised endpoint": { "family": "IPv4", "address": "10.204.0.29", "p ...
Mar  7 21:19:34 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: ... ort": 62780 }, "crypto suite": "AES_CM_128_HMAC_SHA1_80", "last packet": 1551993574, "flags": [ "RTP", "filled", "confirmed" ], "SSRC": 3977644928, "stats": { "packets": 486, "bytes": 83443, "errors": 1 } }, { "local port": 30001, "endpoint": { "family": "IPv4", "address": "10.204.0.29", "port": 62781 }, "advertised endpoint": { "family": "IPv4", "address": "10.204.0.29", "port": 62781 }, "crypto suite": "AES_CM_128_HMAC_SHA1_80", "last packet": 1551993574, "flags": [ "RTCP", "filled", "confirme ...
Mar  7 21:19:34 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: ... d" ], "SSRC": 3977644928, "stats": { "packets": 3, "bytes": 116, "errors": 0 } } ], "flags": [ "initialized", "send", "recv", "SDES", "ICE controlling" ] } ] }, "ad62bf5e": { "tag": "ad62bf5e", "created": 1551993561, "in dialogue with": "f3231059", "medias": [ { "index": 1, "type": "audio", "protocol": "RTP/AVP", "streams": [ { "local port": 30020, "endpoint": { "family": "IPv4", "address": "10.204.0.21", "port": 38316 }, "advertised endpoint": { "family": "IPv4", "address": "10.204.0.21", "port ...
Mar  7 21:19:34 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: ... ": 38316 }, "last packet": 1551993561, "flags": [ "RTP", "filled" ], "stats": { "packets": 0, "bytes": 0, "errors": 0 } }, { "local port": 30021, "endpoint": { "family": "IPv4", "address": "10.204.0.21", "port": 38317 }, "advertised endpoint": { "family": "IPv4", "address": "10.204.0.21", "port": 38317 }, "last packet": 1551993561, "flags": [ "RTCP", "filled" ], "stats": { "packets": 0, "bytes": 0, "errors": 0 } } ], "flags": [ "initialized", "send", "recv" ] } ] } }, "totals": { "RTP": { "packe ...
Mar  7 21:19:34 opensips rtpengine[23951]: DEBUG: [8XXWQF4oMTepP3HrEZRR0Q..]: ... ts": 486, "bytes": 83443, "errors": 1 }, "RTCP": { "packets": 3, "bytes": 116, "errors": 0 } }, "result": "ok" }
Mar  7 21:20:05 opensips rtpengine[23951]: INFO: [8XXWQF4oMTepP3HrEZRR0Q..]: Call branch 'f3231059' (via-branch '') deleted, no more branches remaining
Mar  7 21:20:05 opensips rtpengine[23951]: INFO: [8XXWQF4oMTepP3HrEZRR0Q..]: Final packet stats:
Mar  7 21:20:05 opensips rtpengine[23951]: INFO: [8XXWQF4oMTepP3HrEZRR0Q..]: --- Tag 'ad62bf5e', created 0:44 ago for branch '', in dialogue with 'f3231059'
Mar  7 21:20:05 opensips rtpengine[23951]: INFO: [8XXWQF4oMTepP3HrEZRR0Q..]: ------ Media #1 (audio over RTP/AVP) using unknown codec
Mar  7 21:20:05 opensips rtpengine[23951]: INFO: [8XXWQF4oMTepP3HrEZRR0Q..]: --------- Port      10.3.0.150:30020 <>     10.204.0.21:38316, SSRC 0, 0 p, 0 b, 0 e, 44 ts
Mar  7 21:20:05 opensips rtpengine[23951]: INFO: [8XXWQF4oMTepP3HrEZRR0Q..]: --------- Port      10.3.0.150:30021 <>     10.204.0.21:38317 (RTCP), SSRC 0, 0 p, 0 b, 0 e, 44 ts
Mar  7 21:20:05 opensips rtpengine[23951]: INFO: [8XXWQF4oMTepP3HrEZRR0Q..]: --- Tag 'f3231059', created 0:44 ago for branch '', in dialogue with 'ad62bf5e'
Mar  7 21:20:05 opensips rtpengine[23951]: INFO: [8XXWQF4oMTepP3HrEZRR0Q..]: ------ Media #1 (audio over RTP/SAVP) using PCMU/8000
Mar  7 21:20:05 opensips rtpengine[23951]: INFO: [8XXWQF4oMTepP3HrEZRR0Q..]: --------- Port      10.3.0.150:30000 <>     10.204.0.29:62780, SSRC ed160b80, 486 p, 83443 b, 1 e, 31 ts
Mar  7 21:20:05 opensips rtpengine[23951]: INFO: [8XXWQF4oMTepP3HrEZRR0Q..]: --------- Port      10.3.0.150:30001 <>     10.204.0.29:62781 (RTCP), SSRC ed160b80, 3 p, 116 b, 0 e, 31 ts

**Comment by rfuchs** [comment]
I would agree. Just looking at the last part:
```
 Mar 7 21:20:05 opensips rtpengine[23951]: INFO: [8XXWQF4oMTepP3HrEZRR0Q..]: --------- Port 10.3.0.150:30020 <> 10.204.0.21:38316, SSRC 0, 0 p, 0 b, 0 e, 44 ts
```
Again all the counters are zero, indicating the rtpengine never received anything on that port.

**Comment by rfuchs** [comment]
Cleaning up old tickets
