### ISSUE TITLE
ng protocol rare logs

### ISSUE THREAD

**Issue by descartin** [sipwise/rtpengine#73]
Dear all

we are using ng protocol of rtpengine "speaking" with a kamailio and when a call finish we see in the syslog some logs that are dificult to understand.

Jan 20 07:18:54 debian rtpengine[3357]: [d59ed01a-a0a6-11e4-bd9c-8df1a9bd1b7d] ... e6:errorsi0eeed10:local porti8013e8:endpointd6:family4:IPv47:address12:79.170.64.564:porti17937ee19:advertised endpointd6:family4:IPv47:address12:79.170.64.564:porti17937ee11:last packeti1421759933e5:flagsl4:RTCP6:filled9:confirmed10:kernelized17:no kernel supporte5:statsd7:packetsi4e5:bytesi528e6:errorsi0eeee5:flagsl11:initialized4:send4:recveeee13:C7C33608-1EA5d3:tag13:C7C33608-1EA57:createdi1421759912e16:in dialogue with13:yHrmevF4pvBcg6:mediasld5:indexi1e4:type5:audio8:protocol7:RTP/AVP7:str ...
Jan 20 07:18:54 debian rtpengine[3357]: [d59ed01a-a0a6-11e4-bd9c-8df1a9bd1b7d] ... eamsld10:local porti8000e8:endpointd6:family4:IPv47:address12:79.170.64.564:porti18802ee19:advertised endpointd6:family4:IPv47:address12:79.170.64.564:porti18802ee11:last packeti1421759934e5:flagsl3:RTP6:filled9:confirmed10:kernelizede5:statsd7:packetsi356e5:bytesi16764e6:errorsi0eeed10:local porti8001e8:endpointd6:family4:IPv47:address12:79.170.64.564:porti18803ee19:advertised endpointd6:family4:IPv47:address12:79.170.64.564:porti18803ee11:last packeti1421759932e5:flagsl4:RTCP6:filled9:confirme ...
Jan 20 07:18:54 debian rtpengine[3357]: [d59ed01a-a0a6-11e4-bd9c-8df1a9bd1b7d] ... d10:kernelized17:no kernel supporte5:statsd7:packetsi4e5:bytesi528e6:errorsi0eeee5:flagsl11:initialized4:send4:recveeeee6:totalsd3:RTPd7:packetsi901e5:bytesi44434e6:errorsi0ee4:RTCPd7:packetsi8e5:bytesi1056e6:errorsi0eee6:result2:oke

is there any way to make them more readable or a way to not show them ?

thanks a lot and regard
david

**Comment by rfuchs** [comment]
These are the call stats that are sent back to Kamailio when the call is finished. You can run with a lower log level if you don't want to see them in the log, e.g. 5.

**Comment by rfuchs** [comment]
But I agree that these messages should probably be changed to a DEBUG log level.

**Comment by descartin** [comment]
hello Richard

thanks for the update, however i dont think i can reduce the loglevel to 5 because if i do that inonly get this message for an entire call
Feb 13 14:18:54 rtpengine-test rtpengine[19539]: [4b49ed49-2e2d-1233-05b8-021923691058] Creating new call

if it could be moved to level7 it would be great

thanks a lot and regards
david
