### ISSUE TITLE
Cookie length and format for

### ISSUE THREAD

**Issue by ovoshlook** [sipwise/rtpengine#733]
Hi! Sorry for posting this here but did not find another place to send this question:
I wanna use Call-ID as cookie for creating message
so here are 3 issues :
1 it could be different size for different requests
2 it not matches format XXX_1 as I saw at the example
3 It has definitely more length than example

so my questions are:
1. Is there some limitations for cookie length?
2. Is it must be at the some strict format?

**Comment by rfuchs** [comment]
The cookie can be any length and any format. That being said, using the call ID as cookie is probably not a good idea, as the cookie is supposed to be unique for each individual message and is used to detect duplicates (retransmissions). So each message you send should have its own unique cookie, and using the call ID would fail to do that if you send more than one message for a call.

**Comment by rfuchs** [comment]
Closing as it's not an issue. You can still post if you have more questions.

**Comment by ovoshlook** [comment]
Thx for the response! I got your point
Yes I will add some posfix to uniq  every message. Here is more point about length and format.
so you fully answered my question  :-)
