### ISSUE TITLE
does a java implementation of ng protocol exist?

### ISSUE THREAD

**Issue by jefframin** [sipwise/rtpengine#735]
Hello folks.

I need to use the ng control protocol to integrate a java application with sipwise. My web searches for a java implementation have not turned up anything.

Does one exist? Thanks!

**Comment by rfuchs** [comment]
Not to my knowledge. There are several implementation of bencode though, which is the most important portion of it. Other than that, it's a simple UDP request/response protocol.

**Comment by rfuchs** [comment]
Cleaning up old tickets
