### ISSUE TITLE
block Media / Unblock Media

### ISSUE THREAD

**Issue by vimmadi** [sipwise/rtpengine#739]
I tried using the block Media , unblock Media by sending a command to the rtpengine. The rtpengine recorder ( the  recording daemon in the rtpengine github) still recording the entire call. By block Media I was expecting to mask/stop/pause recording of those packets which are blocked after the command is issued.   And unmask/start/resume recording once I issue the unblock media.

Am I missing something ?

**Comment by rfuchs** [comment]
Yes. Block/unblock media is about media forwarding, not recording. It has no influence on recording.

**Comment by vimmadi** [comment]
I want to pause and resume recording on the rtpengine. Our SBC is not able to sending the a=inactive  attribute in SDP to do this. So, the solution I am looking for is to use some kind of API on the rptEngine which will allow me to do this.  block , unblock didn't work while using the recording daemon nor just generating the raw pcap files in a different mode. 

Any suggestions ?

**Comment by rfuchs** [comment]
How about `stop_recording()` ?

**Comment by vimmadi** [comment]
stop recording doesn't pause, it ends up creating a new file if we resume recording.

**Comment by rfuchs** [comment]
Well, that's all we have right now :smile:

**Comment by jonhvoxbox** [comment]
Hi @rfuchs hope you are well? Will there be an option to pause/mask recordings at some point in a new release? 

Many thanks

Jon

**Comment by rfuchs** [comment]
Still no plans for it at this point.

**Comment by jonhvoxbox** [comment]
Ok thank you.

**Comment by rfuchs** [comment]
Cleaning up old tickets
