### ISSUE TITLE
Question about rtpengine

### ISSUE THREAD

**Issue by africallshop** [sipwise/rtpengine#74]
Hi there,

It is not an issue but a question.

Is it possible to run rtpengine to receive rtp traffic on a signe port (eg. 443) ?

Or how bypass firewall blocking ?

Regards

**Comment by rfuchs** [comment]
No, each media stream requires its own port, generally at least 4 ports per call. As a proxy, it's not supposed to be run behind a firewall, it's supposed to be fully reachable by all the clients that it serves.

**Comment by africallshop** [comment]
Thanks... :+1:
