### ISSUE TITLE
Compiling on CentOS 7.6

### ISSUE THREAD

**Issue by solarmon** [sipwise/rtpengine#743]
Hi,

I'm having problems compiling rtpengine (latest version from github) on CentOS Linux release 7.6.1810 (Core).

I'm having similar issues to:

https://github.com/sipwise/rtpengine/issues/682

and I have already installed gperf packages:

gperftools-libs-2.6.1-1.el7.x86_64
gperftools-devel-2.6.1-1.el7.x86_64
gperf-3.0.4-8.el7.x86_64
gperftools-2.6.1-1.el7.x86_64

But I'm still getting such make errors:

make -C daemon
make[1]: Entering directory `/usr/local/src/rtpengine/daemon'
make rtpengine rtpengine.8
make[2]: Entering directory `/usr/local/src/rtpengine/daemon'
cc  -g -Wall -Wstrict-prototypes -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread     -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include     -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -DWITH_TRANSCODING -I/usr/include/mysql -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DRTPENGINE_VERSION="\"git-master-32c0f76\"" -O3 -o rtpengine main.o kernel.o poller.o aux.o control_tcp.o call.o control_udp.o redis.o bencode.o cookie_cache.o udp_listener.o control_ng.strhash.o sdp.strhash.o stun.o rtcp.o crypto.o rtp.o call_interfaces.strhash.o dtls.o log.o cli.o graphite.o ice.o media_socket.o homer.o recording.o statistics.o cdr.o ssrc.o iptables.o tcp_listener.o codec.o load.o dtmf.o timerthread.o media_player.o loglib.o auxlib.o rtplib.o str.o socket.o streambuf.o ssllib.o codeclib.o resample.o -lm -lglib-2.0   -pthread -lgthread-2.0 -lglib-2.0   -lz   -lpcre   -lcrypto   -lssl -lcrypto   -levent_pthreads -levent   -lpcap -lxmlrpc_client   -lxmlrpc   -lxmlrpc_util   -lhiredis -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0   -lip4tc -lip6tc   -lavcodec   -lavformat   -lavutil   -lswresample   -lavfilter   -L/usr/lib64/mysql -lmysqlclient -lpthread -lz -lm -ldl -lssl -lcrypto
main.o: In function `options':
/usr/local/src/rtpengine/daemon/main.c:310: undefined reference to `dtls_passive_def'
/usr/local/src/rtpengine/daemon/main.c:522: undefined reference to `trust_address_def'
main.o: In function `init_everything':
/usr/local/src/rtpengine/daemon/main.c:634: undefined reference to `sdp_init'
/usr/local/src/rtpengine/daemon/main.c:640: undefined reference to `control_ng_init'
/usr/local/src/rtpengine/daemon/main.c:641: undefined reference to `call_interfaces_init'
main.o: In function `create_everything':
/usr/local/src/rtpengine/daemon/main.c:706: undefined reference to `rtpe_control_ng'
/usr/local/src/rtpengine/daemon/main.c:709: undefined reference to `control_ng_new'
/usr/local/src/rtpengine/daemon/main.c:709: undefined reference to `rtpe_control_ng'
control_tcp.o: In function `control_stream_parse':
/usr/local/src/rtpengine/daemon/control_tcp.c:93: undefined reference to `call_request_tcp'
/usr/local/src/rtpengine/daemon/control_tcp.c:95: undefined reference to `call_lookup_tcp'
/usr/local/src/rtpengine/daemon/control_tcp.c:97: undefined reference to `call_delete_tcp'
/usr/local/src/rtpengine/daemon/control_tcp.c:99: undefined reference to `calls_status_tcp'
call.o: In function `call_delete_branch':
/usr/local/src/rtpengine/daemon/call.c:2760: undefined reference to `ng_call_stats'
control_udp.o: In function `control_udp_incoming':
/usr/local/src/rtpengine/daemon/control_udp.c:89: undefined reference to `call_update_udp'
/usr/local/src/rtpengine/daemon/control_udp.c:91: undefined reference to `call_lookup_udp'
/usr/local/src/rtpengine/daemon/control_udp.c:93: undefined reference to `call_delete_udp'
/usr/local/src/rtpengine/daemon/control_udp.c:95: undefined reference to `call_query_udp'
cli.o: In function `cli_incoming_set_controltos':
/usr/local/src/rtpengine/daemon/cli.c:1419: undefined reference to `rtpe_control_ng'
cli.o: In function `cli_incoming_list_totals':
/usr/local/src/rtpengine/daemon/cli.c:470: undefined reference to `rtpe_cngs_lock'
/usr/local/src/rtpengine/daemon/cli.c:471: undefined reference to `rtpe_cngs_hash'
/usr/local/src/rtpengine/daemon/cli.c:493: undefined reference to `rtpe_cngs_lock'
collect2: error: ld returned 1 exit status
make[2]: *** [rtpengine] Error 1
make[2]: Leaving directory `/usr/local/src/rtpengine/daemon'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/local/src/rtpengine/daemon'
make: *** [all] Error 2

Any advice on how to resolve this issue?

**Comment by rfuchs** [comment]
I suspect an unclean build directory. Do a fresh checkout/clone, or run `git clean -f -x -d`, then try again.

**Comment by solarmon** [comment]
Hi,

I did try that, but did it again - note the 'make check' failed twice before being OK:

1. git clean (git clean -f -x -d)
2. deleted rtpengine src directory 
3. new git clone (git clone https://github.com/sipwise/rtpengine.git)

Cloning into 'rtpengine'...
remote: Enumerating objects: 37, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 14408 (delta 7), reused 8 (delta 2), pack-reused 14371
Receiving objects: 100% (14408/14408), 5.64 MiB | 3.30 MiB/s, done.
Resolving deltas: 100% (10871/10871), done.


4. cd to rtpengine/daemon

5. make check

Makefile:140: .depend: No such file or directory
../utils/const_str_hash < control_ng.c > control_ng.strhash.c
Can't locate IPC/Cmd.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ../utils/const_str_hash line 6.
BEGIN failed--compilation aborted at ../utils/const_str_hash line 6.
make: *** [control_ng.strhash.c] Error 2

6. make check

Makefile:140: .depend: No such file or directory
../utils/const_str_hash < sdp.c > sdp.strhash.c
Can't locate IPC/Cmd.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ../utils/const_str_hash line 6.
BEGIN failed--compilation aborted at ../utils/const_str_hash line 6.
make: *** [sdp.strhash.c] Error 2

7. make check

Makefile:140: .depend: No such file or directory
../utils/const_str_hash < call_interfaces.c > call_interfaces.strhash.c
Can't locate IPC/Cmd.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ../utils/const_str_hash line 6.
BEGIN failed--compilation aborted at ../utils/const_str_hash line 6.
make: *** [call_interfaces.strhash.c] Error 2
[root@PCTDOUAT-SIP-MG01 daemon]# make check
Makefile:140: .depend: No such file or directory
rm -f "loglib.c"
echo '/******** GENERATED FILE ********/' > "loglib.c"
cat ../lib/"loglib.c" >> "loglib.c"
rm -f "auxlib.c"
echo '/******** GENERATED FILE ********/' > "auxlib.c"
cat ../lib/"auxlib.c" >> "auxlib.c"
rm -f "rtplib.c"
echo '/******** GENERATED FILE ********/' > "rtplib.c"
cat ../lib/"rtplib.c" >> "rtplib.c"
rm -f "str.c"
echo '/******** GENERATED FILE ********/' > "str.c"
cat ../lib/"str.c" >> "str.c"
rm -f "socket.c"
echo '/******** GENERATED FILE ********/' > "socket.c"
cat ../lib/"socket.c" >> "socket.c"
rm -f "streambuf.c"
echo '/******** GENERATED FILE ********/' > "streambuf.c"
cat ../lib/"streambuf.c" >> "streambuf.c"
rm -f "ssllib.c"
echo '/******** GENERATED FILE ********/' > "ssllib.c"
cat ../lib/"ssllib.c" >> "ssllib.c"
rm -f "codeclib.c"
echo '/******** GENERATED FILE ********/' > "codeclib.c"
cat ../lib/"codeclib.c" >> "codeclib.c"
echo "Looking for usable alternative for fix_frame_channel_layout.h"; \
rm -f fix_frame_channel_layout-test.[co]; \
ln -s ../lib/fix_frame_channel_layout-test.c; \
for x in ../lib/fix_frame_channel_layout-*.h; do \
        echo "Trying build with $x"; \
        rm -f "fix_frame_channel_layout.h"; \
        echo '/******** GENERATED FILE ********/' > "fix_frame_channel_layout.h"; \
        cat "$x" >> "fix_frame_channel_layout.h"; \
        make fix_frame_channel_layout-test.o && break; \
        echo "Failed build with $x"; \
        rm -f "fix_frame_channel_layout.h"; \
done; \
rm -f fix_frame_channel_layout-test.[co]; \
test -f "fix_frame_channel_layout.h"
Looking for usable alternative for fix_frame_channel_layout.h
Trying build with ../lib/fix_frame_channel_layout-01.h
make[1]: Entering directory `/usr/local/src/rtpengine/daemon'
Makefile:140: .depend: No such file or directory
rm -f "resample.c"
echo '/******** GENERATED FILE ********/' > "resample.c"
cat ../lib/"resample.c" >> "resample.c"
cc -g -Wall -Wstrict-prototypes -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread     -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include     -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -DWITH_TRANSCODING -I/usr/include/mysql -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DRTPENGINE_VERSION="\"git-master-32c0f76\"" -O3 -M main.c kernel.c poller.c aux.c control_tcp.c call.c control_udp.c redis.c bencode.c cookie_cache.c udp_listener.c control_ng.strhash.c sdp.strhash.c stun.c rtcp.c crypto.c rtp.c call_interfaces.strhash.c dtls.c log.c cli.c graphite.c ice.c media_socket.c homer.c recording.c statistics.c cdr.c ssrc.c iptables.c tcp_listener.c codec.c load.c dtmf.c timerthread.c media_player.c loglib.c auxlib.c rtplib.c str.c socket.c streambuf.c ssllib.c codeclib.c resample.c  | sed -e 's/:/ .depend:/' > .depend
make[1]: Leaving directory `/usr/local/src/rtpengine/daemon'
make[1]: Entering directory `/usr/local/src/rtpengine/daemon'
cc -g -Wall -Wstrict-prototypes -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread     -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include     -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -DWITH_TRANSCODING -I/usr/include/mysql -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DRTPENGINE_VERSION="\"git-master-32c0f76\"" -O3   -c -o fix_frame_channel_layout-test.o fix_frame_channel_layout-test.c
make[1]: Leaving directory `/usr/local/src/rtpengine/daemon'
rm -f "resample.c"
echo '/******** GENERATED FILE ********/' > "resample.c"
cat ../lib/"resample.c" >> "resample.c"
cc -g -Wall -Wstrict-prototypes -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread     -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include     -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -DWITH_TRANSCODING -I/usr/include/mysql -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DRTPENGINE_VERSION="\"git-master-32c0f76\"" -O3 -M main.c kernel.c poller.c aux.c control_tcp.c call.c control_udp.c redis.c bencode.c cookie_cache.c udp_listener.c control_ng.strhash.c sdp.strhash.c stun.c rtcp.c crypto.c rtp.c call_interfaces.strhash.c dtls.c log.c cli.c graphite.c ice.c media_socket.c homer.c recording.c statistics.c cdr.c ssrc.c iptables.c tcp_listener.c codec.c load.c dtmf.c timerthread.c media_player.c loglib.c auxlib.c rtplib.c str.c socket.c streambuf.c ssllib.c codeclib.c resample.c  | sed -e 's/:/ .depend:/' > .depend
make: *** No rule to make target `check'.  Stop.

8. make - same errors at end:

:
:
main.o: In function `options':
/usr/local/src/rtpengine/daemon/main.c:310: undefined reference to `dtls_passive_def'
/usr/local/src/rtpengine/daemon/main.c:522: undefined reference to `trust_address_def'
main.o: In function `init_everything':
/usr/local/src/rtpengine/daemon/main.c:634: undefined reference to `sdp_init'
/usr/local/src/rtpengine/daemon/main.c:640: undefined reference to `control_ng_init'
/usr/local/src/rtpengine/daemon/main.c:641: undefined reference to `call_interfaces_init'
main.o: In function `create_everything':
/usr/local/src/rtpengine/daemon/main.c:706: undefined reference to `rtpe_control_ng'
/usr/local/src/rtpengine/daemon/main.c:709: undefined reference to `control_ng_new'
/usr/local/src/rtpengine/daemon/main.c:709: undefined reference to `rtpe_control_ng'
control_tcp.o: In function `control_stream_parse':
/usr/local/src/rtpengine/daemon/control_tcp.c:93: undefined reference to `call_request_tcp'
/usr/local/src/rtpengine/daemon/control_tcp.c:95: undefined reference to `call_lookup_tcp'
/usr/local/src/rtpengine/daemon/control_tcp.c:97: undefined reference to `call_delete_tcp'
/usr/local/src/rtpengine/daemon/control_tcp.c:99: undefined reference to `calls_status_tcp'
call.o: In function `call_delete_branch':
/usr/local/src/rtpengine/daemon/call.c:2760: undefined reference to `ng_call_stats'
control_udp.o: In function `control_udp_incoming':
/usr/local/src/rtpengine/daemon/control_udp.c:89: undefined reference to `call_update_udp'
/usr/local/src/rtpengine/daemon/control_udp.c:91: undefined reference to `call_lookup_udp'
/usr/local/src/rtpengine/daemon/control_udp.c:93: undefined reference to `call_delete_udp'
/usr/local/src/rtpengine/daemon/control_udp.c:95: undefined reference to `call_query_udp'
cli.o: In function `cli_incoming_set_controltos':
/usr/local/src/rtpengine/daemon/cli.c:1419: undefined reference to `rtpe_control_ng'
cli.o: In function `cli_incoming_list_totals':
/usr/local/src/rtpengine/daemon/cli.c:470: undefined reference to `rtpe_cngs_lock'
/usr/local/src/rtpengine/daemon/cli.c:471: undefined reference to `rtpe_cngs_hash'
/usr/local/src/rtpengine/daemon/cli.c:493: undefined reference to `rtpe_cngs_lock'
collect2: error: ld returned 1 exit status
make[1]: *** [rtpengine] Error 1
make[1]: Leaving directory `/usr/local/src/rtpengine/daemon'
make: *** [all] Error 2

**Comment by rfuchs** [comment]
`make check` is a target only supported in the top level directory, not in the subdirectories. You're missing some Perl modules for the tests, `IPC::Cmd` and perhaps others. `make check` is optional anyway and you can skip it if you don't have the dependencies.

**Comment by solarmon** [comment]
OK, but even after a `git clean -f -x -d`, a `make` in the either the root or the 'daemon' directory fails 3 times (with same `Can't locate IPC/Cmd.pm` message) before trying to compile but failing with the `undefined reference to` errors, as above.

I did a `git clean -f -x -d` and installed the perl-IPC-Cmd package (`yum install perl-IPC-Cmd -y`)  and now `make` seems to be compiling OK!

**Comment by rfuchs** [comment]
Ah yes, the gperf helper script also needs IPC::Cmd. Will add as dependency.
