### ISSUE TITLE
Strange behaviour of /proc fs

### ISSUE THREAD

**Issue by nikbyte** [sipwise/rtpengine#744]
Hi!

I expect strange behaviour of /proc fs.
When I run rtpengine daemon with table 0 and then read file
/proc/rtpengine/0/status
I see there
```
Refcount:    1
Control PID: 17906
Targets:     0
```

If re-run daemon few times (usually on second time) I see next content in /proc/rtpengine/0/status
```
Refcount:    1
Control PID: 0
Targets:     0
```

Why PID is 0 if daemon is running and it's working ok?
Is this possible to fix?

**Comment by rfuchs** [comment]
Can you confirm that the daemon is actually using the kernel module when it shows that?

**Comment by nikbyte** [comment]
you're right. sometimes it cannot use kernel, but why? I do 10 restarts, it can use kernel module 8 times and 2 it cannot.

**Comment by rfuchs** [comment]
Possibly a race condition in your restart procedure? The daemon takes a second or so to actually shut down. If another instance starts up before that time is up, it wouldn't be able to open the same kernel table.

**Comment by nikbyte** [comment]
Maybe, I'll check. Thank you.
