### ISSUE TITLE
recording of g722 media gets 4 times speedup

### ISSUE THREAD

**Issue by juha-h** [sipwise/rtpengine#748]
Any idea why recording of g722 (codec G722/8000) media gets 4 times speedup?  For example, mp3 recording of a call that lasts 80 seconds is 20 seconds long and sounds OK if played in 4 times slow motion.

**Comment by rfuchs** [comment]
Probably a booboo with the `clockrate_mult` somewhere, division instead of multiplication or the other way around. G.722 is actually 16 kHz but advertised as 8 kHz in the SDP, and so this needs to be corrected in all the relevant places, which is what `clockrate_mult` is used for. Do you have resampling enabled in the config?

**Comment by juha-h** [comment]
Richard Fuchs writes:

> Probably a booboo with the `clockrate_mult` somewhere, division
> instead of multiplication or the other way around. G.722 is actually
> 16 kHz but advertised as 8 kHz in the SDP, and so this needs to be
> corrected in all the relevant places, which is what `clockrate_mult`
> is used for. Do you have resampling enabled in the config?

There is currently no "resample-to = 8000" in the config.  We can try
with that.

I too was wondering, why the SDP had G722/8000, when baresip uses
G722/16000.

**Comment by rfuchs** [comment]
A mistake in the SDP could also cause this. G.722 must be advertised as 8 kHz in the SDP even though it really is 16 kHz. If the SDP states G722/16000 then that is wrong and would give you a wrong output file.

**Comment by juha-h** [comment]
Richard Fuchs writes:

> A mistake in the SDP could also cause this. G.722 must be advertised
> as 8 kHz in the SDP even though it really is 16 kHz. If the SDP states
> G722/16000 then that is wrong and would give you a wrong output file.

The call where the problem was noticed used G722/16000 in the SDP:

a=rtpmap:9 G722/8000.

**Comment by juha-h** [comment]
juha-h writes:

> The call where the problem was noticed used G722/16000 in the SDP:
> 
> a=rtpmap:9 G722/8000.

Sorry, as the example above shows, the call where the problem appeared,
used G722/8000 in the SDP.

**Comment by rfuchs** [comment]
Can't really reproduce this. Which version is this? What's your config?

**Comment by juha-h** [comment]
I started to do tests with latest branch mr7.2.1, but for some reason cannot get any audio to mp3 file.  Looks like only the header is there.  Metadata is below.
``
CALL-ID
16:
92cefc082c4dd4b7

PARENT
33:
92cefc082c4dd4b7-db3cefd29ed8d99d

RECORDING 0
0:


FORWARDING 0
0:


STREAM 0 details
49:
TAG 1 MEDIA 0 TAG-MEDIA 1 COMPONENT 1 FLAGS 65664

STREAM 0 interface
34:
tag-1-media-1-component-1-RTP-id-0

STREAM 1 details
50:
TAG 1 MEDIA 0 TAG-MEDIA 1 COMPONENT 2 FLAGS 131200

STREAM 1 interface
35:
tag-1-media-1-component-2-RTCP-id-1

STREAM 2 details
51:
TAG 0 MEDIA 1 TAG-MEDIA 1 COMPONENT 1 FLAGS 1114240

STREAM 2 interface
34:
tag-0-media-1-component-1-RTP-id-2

STREAM 3 details
51:
TAG 0 MEDIA 1 TAG-MEDIA 1 COMPONENT 2 FLAGS 1179776

STREAM 3 interface
35:
tag-0-media-1-component-2-RTCP-id-3

MEDIA 0 PAYLOAD TYPE 101
20:
telephone-event/8000

MEDIA 0 PAYLOAD TYPE 0
9:
PCMU/8000

MEDIA 0 PAYLOAD TYPE 8
9:
PCMA/8000

TAG 0
16:
c88d1e6ba24b2271

SDP from 0 before offer
570:
v=0
o=- 1965457596 402422726 IN IP4 192.26.134.10
s=-
c=IN IP4 192.26.134.10
t=0 0
a=tool:baresip 0.6.1
m=audio 30356 RTP/AVP 0 8 101
a=label:1
a=rtcp-rsize
a=ssrc:1591902852 cname:sip:+35832345670@test.tutpro.com
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=rtcp:30357
a=ptime:20
a=ice-ufrag:FKmPRgWP
a=ice-pwd:uI2HXSBQXLd6hXyIyqfFovIK5g
a=candidate:zALn5geBQqDWFyJv 1 UDP 2130706431 192.26.134.10 30356 typ host
a=candidate:zALn5geBQqDWFyJv 2 UDP 2130706430 192.26.134.10 30357 typ host


SDP from 0 after offer
570:
v=0
o=- 1965457596 402422726 IN IP4 192.168.43.98
s=-
c=IN IP4 192.168.43.98
t=0 0
a=tool:baresip 0.6.1
m=audio 30192 RTP/AVP 0 8 101
a=label:1
a=rtcp-rsize
a=ssrc:1591902852 cname:sip:+35832345670@test.tutpro.com
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=rtcp:30193
a=ptime:20
a=ice-ufrag:QuG7WJKt
a=ice-pwd:LXklGKr5zy4SFzwc0JHQ2H0zHp
a=candidate:SbHu4aXONd4pVSf6 1 UDP 2130706431 192.168.43.98 30192 typ host
a=candidate:SbHu4aXONd4pVSf6 2 UDP 2130706430 192.168.43.98 30193 typ host


MEDIA 1 PAYLOAD TYPE 101
20:
telephone-event/8000

MEDIA 1 PAYLOAD TYPE 0
9:
PCMU/8000

MEDIA 1 PAYLOAD TYPE 8
9:
PCMA/8000

TAG 1
16:
d488d427924fb781

SDP from 1 before answer
344:
v=0
o=- 2561233718 1964582506 IN IP4 192.168.43.98
s=-
c=IN IP4 192.168.43.98
t=0 0
a=tool:baresip 0.6.1
m=audio 12278 RTP/AVP 0 8 101
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=label:1
a=rtcp-rsize
a=ssrc:153488184 cname:sip:+35892345670@test.tutpro.com
a=ptime:20


SDP from 1 after answer
570:
v=0
o=- 2561233718 1964582506 IN IP4 192.168.43.98
s=-
c=IN IP4 192.168.43.98
t=0 0
a=tool:baresip 0.6.1
m=audio 30208 RTP/AVP 0 8 101
a=label:1
a=rtcp-rsize
a=ssrc:153488184 cname:sip:+35892345670@test.tutpro.com
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=rtcp:30209
a=ptime:20
a=ice-ufrag:bGR40RPF
a=ice-pwd:5lsSJn3lLFlu3Tftvdohox9mP8
a=candidate:SbHu4aXONd4pVSf6 1 UDP 2130706431 192.168.43.98 30208 typ host
a=candidate:SbHu4aXONd4pVSf6 2 UDP 2130706430 192.168.43.98 30209 typ host
``

**Comment by juha-h** [comment]
Config is below.
``
rtpengine-recording]
table = 0
output-storage = db
output-format = mp3
spool-dir = /var/spool/rtpengine
output-dir = /var/spool/rtpengine/tmp
resample-to = 8000
mp3_bitrate = 24000
output-mixed = 1
mysql-host = 127.0.0.1
mysql-port = 3306
mysql-user = xxx
mysql-pass = xxx
mysql-db = rtpengine
``

**Comment by juha-h** [comment]
I have tried with several config value combinations and recording daemon always outputs only mp3 header of 261 bytes to xxx-mix.mp3 file.  Audio itself is missing.

**Comment by juha-h** [comment]
I reinstalled rtpengine (this time version 7.0.1.1+0~mr7.0.1.1) and got recording working.  Recording worked fine with PCMU codec, but had the speedup problem with G722 both with and without 'resample-to = 8000'. I'll try next with the latest master.

**Comment by juha-h** [comment]
I created new issue about empty recording stream with branches 7.2.1 and master. WIth branches 7.0.1 and 7.1.2 recording works fine, but G722 stream gets 4 times speeup.

**Comment by juha-h** [comment]
Sipwise Jenkins User writes:

> Closed #748 via ac825cc47a73326aee4831f5cb3102ee96381a7f.

Thanks.  I'll to backport this to mr7.1.2 for testing, since recording
does not work for me in later branches or master.

**Comment by juha-h** [comment]
juha-h writes:

> Sipwise Jenkins User writes:
> 
> > Closed #748 via ac825cc47a73326aee4831f5cb3102ee96381a7f.
> 
> Thanks.  I'll to backport this to mr7.1.2 for testing, since recording
> does not work for me in later branches or master.

The commit is already on mr7.1.2.  Thanks.

**Comment by juha-h** [comment]
Sipwise Jenkins User writes:

> Closed #748 via ac825cc47a73326aee4831f5cb3102ee96381a7f.

Works fine with 7.1.2.2+0~mr7.1.2.2.
