### ISSUE TITLE
Segfault on call pickup

### ISSUE THREAD

**Issue by Jaykah** [sipwise/rtpengine#75]
Hi,

Updating to latest build is causing RTPEngine to segfault on call pickup.

```
send_rtpp_command(): can't send command to a RTP proxy
Feb 17 22:19:29 Kamailio kamailio[1003]: ERROR: rtpengine [rtpengine.c:1582]: send_rtpp_command(): proxy <udp:127.0.0.1:7724> does not respond, disable it
Feb 17 22:19:29 Kamailio kamailio[1003]: ERROR: rtpengine [rtpengine.c:1452]: rtpp_test(): proxy did not respond to ping
Feb 17 22:19:29 Kamailio kamailio[1003]: ERROR: rtpengine [rtpengine.c:1358]: rtpp_function_call(): no available proxies
```

```
/bin/bash: line 1:   681 Segmentation fault      (core dumped) /usr/local/src/rtpengine/daemon/rtpengine -f --interface=10.0.12.124\!235.155.55.255 --listen-udp=127.0.0.1:7723 --listen-ng=127.0.0.1:7724 --tos=184 --pidfile=/var/run/rtpengine.pid
```

Setting --log-level=7 does not give us any additional information. I also cannot find the actual core dump to debug this further (I have set ulimit -c to a non-zero number).

**Comment by rfuchs** [comment]
If you run it in the foreground anyway, you can run it through gdb to see where it segfaults. Simply prepend "gdb --args" to your command line, then say "run" and use it until it crashes. Then print a backtrace.

**Comment by rfuchs** [comment]
https://github.com/sipwise/rtpengine/commit/f224babc54bc0bf8db97ee96d74987225fa26301 might be the fix you're looking for.

**Comment by Jaykah** [comment]
Yep, that solved it. Thanks!

**Comment by redashu** [comment]
I am facing same issue on my setup. Can i tell me how you solved this issue permanently.

**Comment by rfuchs** [comment]
This should have been solved long time ago, unless you're running an old version. Can you give some more details please.
