### ISSUE TITLE
query api request doesn't work

### ISSUE THREAD

**Issue by ovoshlook** [sipwise/rtpengine#751]
Hi! 
I'm trying use rtpegnine API to get some info about calls
For not Im using 6.1.2 version and trying to make query call but response gives me an error:

I got UDP dump for other commands that kamailio (5.1) uses and did not find any difference.

`1-36455@10.10.120.47 l7:call-id20:1-36455@10.10.120.477:command5:querye`
`1-36455@10.10.120.47 d6:result5:error12:error-reason27:Could not decode dictionarye`

Here is delete request that succesfully works

`0_2739_13 d3:ICE6:remove7:call-id20:1-36455@10.10.120.4713:received-froml3:IP412:10.10.120.47e8:from-tag15:36455SIPpTag0017:command6:deletee`

So there eare 2 questions:
1. Does 6.1.2 implements query reuqest ? (Yes according docs but...)
2. Maybe soemthing bas in my query?

**Comment by rfuchs** [comment]
Yeah that query request is wrong. It's a list, not a dictionary. Where is that request coming from?

**Comment by ovoshlook** [comment]
This is from my application. Just first time with bencode. Did not know that here are some differences
will fix. Thank u for response

**Comment by ovoshlook** [comment]
Fixed thx! Works as a charm
