### ISSUE TITLE
RTPEngine-recording sound cuts when multiple recording

### ISSUE THREAD

**Issue by altzone** [sipwise/rtpengine#754]
Hello,
I have a problem with rtpengine-recording when I test with a single call, the recording is perfect but if there is more recording it happens very frequently that there is hatching in the recording.

I have the same problem on MR6.3 and 7.1
the paremetres are as follows:
rtpengine-daemon (launch command):
`/usr/sbin/rtpengine --config-file = /etc/rtpengine/rtpengine.conf --config-section = rtpengine --pidfile =/var/run/ngcp-rtpengine-daemon.pid --table = 0 - recording-dir = /var/spool/recording --recording-method = proc`

rtpengine.conf:
```
[rtpengine]

table = 0
interface = prive/10.10.205.178;public/xx.xx.205.178
listen-ng = 10.10.205.178:22222
listen-tcp = 25060
listen-udp = 12222
listen-cli = 9900
timeout = 40
silent-timeout = 180
tos = 184
control-tos = 184
delete-delay = 10
final-timeout = 10800
num-threads = 16
port-min = 30000
port-max = 60000
b2b-url = http://%%:5060/RTP
xmlrpc-format = 2
log-level = 1
log-stderr = false
log-facility = local0
homer = 10.10.69.70:9060
homer-protocol = udp
homer-id = 402
```

rtpengine-recording-daemon:
```
[Rtpengine-recording]
table = 0
num-threads = 4
output-storage = file
output-format = mp3
resample-to = 8000
mp3-bitrate = 16000
output-mixed = 1
log-level = 0

spool-dir = /var/spool/recording
output-dir = /Recording
### mysql configuration for db storage
mysql-host = 10.10.xx.xx
mysql-port = 3306
mysql-user = sbc1
mysql-pass = xxxx
mysql-db = rtprecords

```
I tried to change the bitrate and resample, switch to wav and pass without mixer but the problem is still present.

there is no apparent error when I pass log-level in debug mode.

Do you have an idea?
Thank you !

**Comment by rfuchs** [comment]
There is what in the recordings? Hatching?

**Comment by altzone** [comment]
Hi, yes hatching

**Comment by rfuchs** [comment]
Sorry, I don't know what that means.

Assuming you mean some sort of defect in the audio: is the system perhaps overloaded in terms of CPU usage? Individual calls can't really interfere with each other, so that would be my best guess.

**Comment by altzone** [comment]
indeed it is a good hypothesis alas it produces even with only a few calls (between 10 and 20) and at this time the cpu is almost not used.  I do not understand the problem because the calls themselves are not hatched.  the hatching is not regular as one could note it with a concern of ptime.

**Comment by altzone** [comment]
by hatched I meant stuttering

**Comment by rfuchs** [comment]
I don't really have an explanation for you. As I said, individual calls are handled separately and can't interfere with each other. So I can only suggest to look into some sort of resource overload. Are you running this on a VM?

**Comment by altzone** [comment]
Yes, the server is a VM on a node of several vMware hypervisors. there is no saturation of resource yet.

I will install a physical machine and retest.

**Comment by rfuchs** [comment]
Cleaning up old tickets
