### ISSUE TITLE
Forwarding received RTP stream to multiple destination.

### ISSUE THREAD

**Issue by alishir** [sipwise/rtpengine#756]
Is it possible to forward received RTP stream to multiple destination in rtpengine? I want to send voice received for a user to other users.

**Comment by daviddean99** [comment]
I'm also interested in whether this would be possible for a conference-type scenario where one incoming RTP stream is forwarded to multiple recipients. Thx.

**Comment by rfuchs** [comment]
This is not currently supported and we also have no plans for this in the foreseeable future.
