### ISSUE TITLE
problem adding multiple variants of opus

### ISSUE THREAD

**Issue by johandeclercqdemocon** [sipwise/rtpengine#759]
I need to add opus in 2 variants when a call comes from a provider to my user. 
I thought that I could do it with these parameters: 
RTP/SAVP pad-crypto in-iface=phone out-iface=provider replace-session-connection replace-origin codec-transcode-opus/48000/1/8000 codec-transcode-opus/48000/2/48000  ICE=remove

however I get this in the sdp : ... opus/48000#015#012a=rtpmap:100 opus/48000/2#015#012a=fmtp:101 

can you please have a look ?
full trace below

var(rtpengine_flags): RTP/SAVP pad-crypto in-iface=phone out-iface=provider replace-session-connection replace-origin codec-transcode-opus/48000/1/8000 codec-transcode-opus/48000/2/48000  ICE=remove
Apr 24 19:38:59 opensips /data/opensips/sbin/opensips[16158]: callid=16d850990e6e5d9120e7353457f62fb0@192.168.174.253: route[setrtpengineflags] -> Exit
Apr 24 19:38:59 opensips /data/opensips/sbin/opensips[16158]: callid=16d850990e6e5d9120e7353457f62fb0@192.168.174.253: route[setadvertisedaddress]:call is to world avp(rd) world, advertised address is 10.3.0.150
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: Adding a proxy for control ng stats:127.0.0.1
Apr 24 19:38:59 opensips rtpengine[17157]: INFO: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Received command 'offer' from 127.0.0.1:34975
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Dump for 'offer' from 127.0.0.1:34975: { "sdp": "v=0#015#012o=MG4000|2.0 90168584026823 90168584026823 IN IP4 192.168.174.253#015#012s=-#015#012c=IN IP4 192.168.174.253#015#012t=0 0#015#012m=audio 20020 RTP/AVP 8 0 18 98 96 97 101#015#012a=rtpmap:98 G.729a/8000#015#012a=rtpmap:96 G.729ab/8000#015#012a=rtpmap:97 G.729b/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-15#015#012a=fmtp:18 annexb=no#015#012a=X-vrzcap:vbd Ver=1 Mode=FaxPr ModemRtpRed=0#015#012a=X-vrzcap:identification bin=DSR1922 Prot=mgcp App=MG#015#012a=ptime:20#015#012", "ICE": "remove", "direction": [ ...
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: ...  "phone", "provider" ], "flags": [ "pad-crypto", "codec-transcode-opus/48000/1/8000", "codec-transcode-opus/48000/2/48000" ], "replace": [ "session-connection", "origin" ], "transport-protocol": "RTP/SAVP", "call-id": "16d850990e6e5d9120e7353457f62fb0@192.168.174.253", "received-from": [ "IP4", "192.168.174.253" ], "from-tag": "192.168.174.253+5+2e0945f1+bc4dd251", "command": "offer" }
Apr 24 19:38:59 opensips rtpengine[17157]: NOTICE: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Creating new call
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Codec 'opus/48000' added for transcoding with payload type 99
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Codec 'opus/48000/2' added for transcoding with payload type 100
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Default sink codec is PCMA/8000
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Creating codec handler for PCMA/8000
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Sink supports codec PCMA/8000
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Creating codec handler for PCMU/8000
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Sink supports codec PCMU/8000
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Creating codec handler for G729/8000
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Creating codec handler for G.729a/8000
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Creating codec handler for G.729ab/8000
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Creating codec handler for G.729b/8000
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Creating codec handler for telephone-event/8000
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Creating codec handler for opus/48000
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Sink does not support codec opus/48000
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Creating SSRC transcoder from opus/48000/1 to PCMA/8000/1
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Initialized encoder with frame size 160 samples
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Encoder created with clockrate 8000, 1 channels, using sample format 1 (ptime 20 for 160 samples per frame and 160 samples (160 bytes) per packet, bitrate 0)
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Created transcode context for opus/48000 -> PCMA/8000
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Creating codec handler for opus/48000/2
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Sink does not support codec opus/48000/2
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Creating SSRC transcoder from opus/48000/2 to PCMA/8000/1
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Initialized encoder with frame size 160 samples
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Encoder created with clockrate 8000, 1 channels, using sample format 1 (ptime 20 for 160 samples per frame and 160 samples (160 bytes) per packet, bitrate 0)
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Created transcode context for opus/48000/2 -> PCMA/8000
Apr 24 19:38:59 opensips rtpengine[17157]: INFO: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Enabling transcoding engine
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Stripping unsupported codec G729 due to active transcoding
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Stripping unsupported codec G.729a due to active transcoding
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Stripping unsupported codec G.729ab due to active transcoding
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Stripping unsupported codec G.729b due to active transcoding
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: __free_ssrc_handler
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: __free_ssrc_handler
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: __free_ssrc_handler
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: __free_ssrc_handler
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: __free_ssrc_handler
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: __free_ssrc_handler
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: [10.3.0.150:30000] Initialized incoming SRTP with SDES crypto params: <none>
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: [1] Initialized outgoing SRTP with SDES crypto params: suite AES_CM_128_HMAC_SHA1_80, tag 1, key ylnqMnrASSARF10WdSFr1Q== salt ZUT/XVPpj2byDSPLTl0=
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: [10.3.0.150:30001] Initialized incoming SRTP with SDES crypto params: <none>
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: [2] Initialized outgoing SRTP with SDES crypto params: suite AES_CM_128_HMAC_SHA1_80, tag 1, key ylnqMnrASSARF10WdSFr1Q== salt ZUT/XVPpj2byDSPLTl0=
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: set FILLED flag for stream 192.168.174.253:20020
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: set FILLED flag for stream 192.168.174.253:20021
Apr 24 19:38:59 opensips rtpengine[17157]: INFO: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Replying to 'offer' from 127.0.0.1:34975 (elapsed time 0.003055 sec)
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: Response dump for 'offer' to 127.0.0.1:34975: { "sdp": "v=0#015#012o=MG4000|2.0 90168584026823 90168584026823 IN IP4 10.3.0.150#015#012s=-#015#012c=IN IP4 10.3.0.150#015#012t=0 0#015#012m=audio 30000 RTP/SAVP 8 0 101 99 100#015#012a=X-vrzcap:vbd Ver=1 Mode=FaxPr ModemRtpRed=0#015#012a=X-vrzcap:identification bin=DSR1922 Prot=mgcp App=MG#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=rtpmap:99 opus/48000#015#012a=rtpmap:100 opus/48000/2#015#012a=fmtp:101 0-15#015#012a=sendrecv#015#012a=rtcp:30001#015#012a=crypto:1 AES_CM_128_HMAC_SH ...
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: ... A1_80 inline:ylnqMnrASSARF10WdSFr1WVE/11T6Y9m8g0jy05d#015#012a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:6aRU6YXEKtoY27S03Uai7VtcaOrptXRDNk9V/PZ5#015#012a=crypto:3 AES_CM_192_HMAC_SHA1_80 inline:/l427OQbFGFrZ9DHKJpFx+gHOkVn1WMCoLYWZ0I2YVeFu02F+gk=#015#012a=crypto:4 AES_CM_192_HMAC_SHA1_32 inline:w1r1T1GojEQxteM5smx2N6ECOmtZkQmQZZdcYZmIQ3dvR5WQIl0=#015#012a=crypto:5 AES_CM_256_HMAC_SHA1_80 inline:3g+YWoEwscjNK9qHGQc2sEjhT+p+vqiAeq/Muc0v0ZylIdMBykX5G4Q1i1yMjp==#015#012a=crypto:6 AES_CM_256_HMAC_SHA1_32 inline:oGYRdze89HSMYhnt46+ ...
Apr 24 19:38:59 opensips rtpengine[17157]: DEBUG: [16d850990e6e5d9120e7353457f62fb0@192.168.174.253]: ... Q0Cil77fo9bl5Z/lMv5DGGqQ/yTGnTlpTLhJWiY714a==#015#012a=crypto:7 F8_128_HMAC_SHA1_80 inline:FQD+6udTW110HU58p/f0HkgFhU6d9RjNRhz/3dLC#015#012a=crypto:8 F8_128_HMAC_SHA1_32 inline:iGH+J76BrX3C5Qe5Thu1QsYzU05OJ7I2U4sdn2rA#015#012a=crypto:9 NULL_HMAC_SHA1_80 inline:wLmHnYFF44exWnwMadEa5ySTLPQ0+e01NvsO07WA#015#012a=crypto:10 NULL_HMAC_SHA1_32 inline:1RTxqO1fpRcT6cpbgoYJQovf6n2jf+ex3UvGNoJN#015#012a=setup:actpass#015#012a=fingerprint:sha-1 47:C1:37:10:D0:86:69:58:DE:C7:DE:18:66:68:91:3F:59:34:F1:B5#015#012a=ptime:20#015#012", "result": "ok" }

**Comment by rfuchs** [comment]
Looks good to me. You're adding one mono Opus and one stereo Opus, and you get:
```
m=audio 30000 RTP/SAVP 8 0 101 99 100
...
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=rtpmap:99 opus/48000
a=rtpmap:100 opus/48000/2
a=fmtp:101 0-15
```
99 is your mono Opus and 100 is your stereo Opus. Isn't that what you want?

**Comment by johandeclercqdemocon** [comment]
Actually I want opus 8000 (2G) and opus 48000 (>=$G)

**Comment by rfuchs** [comment]
8000 as in bit rate or sample rate? Opus is always presented with a sample rate of 48000. The final `/8000` is the encoder bit rate, which will be used, but is not reflected in the SDP.

**Comment by johandeclercqdemocon** [comment]
Well, 

I am not too good in Opus … 

Actually I want to have it with bandwidth as wide as possible and as small as possible 

So I think that for the smallest I need 96 and for the widest 99. 

 

BR, 

 

P.S. are you at kamailioworld ?

**Comment by rfuchs** [comment]
See https://wiki.xiph.org/index.php?title=Opus_Recommended_Settings&mobileaction=toggle_view_desktop for recommended and supported bit rates

Lowest recommended bit rate for mono is 10k, but bit rates down to 6k are supported. For stereo full band stereo, at least 64k is recommended, up to 96k.

**Comment by rfuchs** [comment]
And no, I won't be at kamailioworld.

**Comment by johandeclercqdemocon** [comment]
Okay, but what do I need to put to have 96 as below : 

rtpmap:96 opus/48000/2

fmtp:96 useinbandfec=1

rtpmap:101 telephone-event/48000

rtpmap:97 telephone-event/8000

**Comment by rfuchs** [comment]
You need a particular payload type number? Why? These are dynamically assigned and bear no specific meaning.

**Comment by johandeclercqdemocon** [comment]
Thanks Richard, then I will try as is. 

 

BR,
