### ISSUE TITLE
Installing fails. Modules is present but can't be loaded.

### ISSUE THREAD

**Issue by davidcsi** [sipwise/rtpengine#761]
Hello,

I'm having a weird sutiation.

I installed rtpengine on an AWS instance (debian 9), the module was installed on 
```
/lib/modules/4.9.0-8-amd64
```

Something must have change in AWS' debian 9, now, when i install `dkms` which is mandatory for the kernel module, a dir is created, in addition to `/lib/modules/4.9.0-8-amd64` it creates `/lib/modules/4.9.0-9-amd64`.

And when modprobbing it can't find the module:

```
# modprobe xt_RTPENGINE
modprobe: FATAL: Module xt_RTPENGINE not found in directory /lib/modules/4.9.0-8-amd64
```

The module is actually installed on 

```
# find /lib/modules/ -name "xt_RTPENGINE*"
/lib/modules/4.9.0-9-amd64/updates/dkms/xt_RTPENGINE.ko
```

REALLY appreciate some help!

David

**Comment by rfuchs** [comment]
Does it work after running `depmod`?

**Comment by rfuchs** [comment]
Oh nevermind. Looks like a version mismatch. Seems like you're running `4.9.0-8-amd64` while the module is compiled for `4.9.0-9-amd64`. Might just be a matter of rebooting the system.

**Comment by davidcsi** [comment]
trying that!

**Comment by davidcsi** [comment]
that didn't help, i installed dkms, rebooted and yes the module is now installed on `/lib/modules/4.9.0-9-amd64`, but 2 things go wrong:

morprobe is looking for it on the wrong path:

```
# modprobe xt_RTPENGINE
modprobe: FATAL: Module xt_RTPENGINE not found in directory /lib/modules/4.9.0-8-amd64
```

when it's located on `/lib/modules/4.9.0-9-amd64`

```
# find /lib/modules/ -name "xt_RTPENGINE*"
/lib/modules/4.9.0-9-amd64/updates/dkms/xt_RTPENGINE.ko
```

when i try to load that one with insmod:

```
# insmod `find /lib/modules/ -name "xt_RTPENGINE*"`
insmod: ERROR: could not insert module /lib/modules/4.9.0-9-amd64/updates/dkms/xt_RTPENGINE.ko: Invalid module format
```

**Comment by rfuchs** [comment]
I bet you're still running `4.9.0-8-amd64`. Check `uname -r`

**Comment by davidcsi** [comment]
I am, why on reboot doesn't it goes to 4.9.0-9?

**Comment by rfuchs** [comment]
Can't really help you with that...

**Comment by davidcsi** [comment]
I need to do a kernel update before installing... trying againt to confirm.

**Comment by mika** [comment]
@davidcsi looks like a problem with the running kernel version and not being related to rtpengine itself to me, so we're assuming this issue has been resolved in the meanwhile and hereby close the issue, if there's anything else to be taken care of let us know
