### ISSUE TITLE
RTPEngine stops sending audio to the phone after SIP Re-INVITE

### ISSUE THREAD

**Issue by adil-mafzool** [sipwise/rtpengine#765]
I am experiencing the issue RTP Engine where SIP Re-INVITE from the callee. RTPEngine stop sending audio to the phone after SIP Re-INVITE.

`<CallerPhone-A> (RTP)<--> (RTP) Kamailio Proxy (RTP Engine: Version 7.1.0.0+0~mr7.1.0.0 git-mr7.1-cloudcall-mg-145731e) <-->B2BUA (RTP)<--> <CalleePhone-B>`
RTP is setup as follow with (RTP Engine Transcoding enabled): -

Initial call is set up OK with `call-id: 15_76038634@172.31.17.174` with audio exchange.

`Last sequence number 27741 before CalleePhone-B SIP Re-INVITE for SSRC: (Packet 152)0x1b578619 -> (Packet 153)0x6f09c071`

After the SIP OK of SIP Re-INVITE RTP Engine has generated only two packets that were sent to CallerPhone-A: -

```
Sequence number 27742 with SSRC: (Packet 159) 0x1b578619 -> (Packet 160) 0x1b578619
Sequence number 27743 with SSRC: (Packet 166) 0x1b578619 -> (Packet 167) 0x1b578619
```

But nothing after those packets are forwarded to the CallerPhone-A even though rtpengine is receiving the RTP packets : -

```
Sequence number 27744 with SSRC: (Packet 170) 0x1b578619 -> ??
Sequence number 27745 with SSRC: (Packet 175) 0x1b578619 -> ??
Sequence number 27746 with SSRC: (Packet 178) 0x1b578619 -> ??
Sequence number 27747 with SSRC: (Packet 181) 0x1b578619 -> ??
Sequence number 27748 with SSRC: (Packet 182) 0x1b578619 -> ??
```

Hence, rtpengine is causing one-way audio to the CallerPhone-A after SIP re-INVITE.

Please find the RTPEngine log attached herewith [RTPEngineStopAudioAfterReInvite.zip](https://github.com/sipwise/rtpengine/files/3131940/RTPEngineStopAudioAfterReInvite.zip)

**Comment by rfuchs** [comment]
Because of this:
![image](https://user-images.githubusercontent.com/3227418/56975838-9fd29300-6b3f-11e9-9387-7fd616eea837.png)

**Comment by adil-mafzool** [comment]
Thanks good spot!!!

**Comment by rfuchs** [comment]
Closing as this is an external issue
