### ISSUE TITLE
The gaps in the wavs under "high load"

### ISSUE THREAD

**Issue by ivangirko** [sipwise/rtpengine#768]
Hello.

Configs:
<details><summary>rtpengine.conf</summary>

```
[rtpengine]
table = 0
listen-ng = 192.168.20.128:2223
interface = 192.168.20.128
timeout = 180
silent-timeout = 10800
tos = 184
delete-delay = 30
final-timeout = 10800
offer-timeout = 10800
num-threads = 10
port-min = 30000
port-max = 40000
recording-dir = /opt/rtpengine/spool
recording-method = proc
log-level = 7
```
</details>
<details><summary>rtpengine-recording.conf</summary>

```
[rtpengine-recording]
table = 0
num-threads = 10
output-format = wav
output-mixed = 0
output-single = 1
spool-dir = /opt/rtpengine/spool
output-dir = /opt/rtpengine/records
resample-to = 8000
mp3_bitrate = 16000
log-level = 7
```
</details>

```
rtpengine:
- 1 instance
- 10 threads

rtpengine-recording:
- 1 instance
- 10 threads

communication via table 0
My machine has 40 virtual cors (2 processors with 10 phys cores each and HT-support enabled)
My spool and recording dirs are in tmpfs
```

Stream sdp:
```
BIND to v=0
o=- 1889726760 1889726760 IN IP4 10.81.21.100
s=-
c=IN IP4 10.81.21.100
t=0 0
m=audio 32988 RTP/AVP 8
a=silenceSupp:off - - - -
a=rtpmap:8 PCMA/8000
a=sendrecv
```

Gaps in the wavs appear already at 60-80 simultaneous recordings. In this case, CPU of the  rtpengine-recording can grow upper then 100% and at the same time the CPU of the child threads is about 6-10% (CPU of rtpengine daemon not so high - ~40-60%)...
I want to give more simultaneous recordings, about 500-1500, and I don`t understand capabilities  of rtpengine-recording  daemon, may be I need to start several separated instances ?

**Comment by rfuchs** [comment]
Cleaning up old tickets

**Comment by dvillaume** [comment]
hello @ivangirko, 
Did you manage to go further on this ? 
If so, i would be interrested in your total recording capabilities with rtpengine.
Thanks
