### ISSUE TITLE
SDP with CRLF giving errors

### ISSUE THREAD

**Issue by descartin** [sipwise/rtpengine#77]
Dear all

we have tested some traffic using ng protocol in rtpengine and we haev noticed that when the SDP has one or more CRLF at the end of the SDP, it gives and error like this

Feb 24 12:03:44 rtpengine[28204]: Error parsing SDP at offset 149: Missing '=' sign
Feb 24 12:03:44 rtpengine[28204]: Protocol error in packet from 79.170.64.185:35646: Failed to parse SDP [d3:sdp151:v=0#015#012o=user1 53655765 2353687637 IN IP4 79.170.68.171#015#012s=-#015#012c=IN IP4 79.170.68.171#015#012t=0 0#015#012m=audio 6000 RTP/AVP 0#015#012a=rtpmap:0 PCMU/8000#015#012a=sendrecv#015#012#015#0123:ICE6:remove5:flagsl13:trust-addresse7:replacel18:session-connectione7:call-id21:1-24945@79.170.68.17113:received-froml3:IP413:79.170.71.132e8:from-tag15:24945SIPpTag0016:to-tag1:27:command6:answere]

and the kamailio connected to the rtpengine doesnt receive a proper response to do the rtpengine.

is this behaviour expected, or it can be fixed? in the udp version this doesnt seem to happen

thanks a lot and regards
david

**Comment by rfuchs** [comment]
This is expected since it's a malformed SDP (the specification doesn't allow for blank lines, not even at the end).  However there's a compile switch in the makefile to make it more tolerant, just uncomment this:

#CFLAGS+=       -DTERMINATE_SDP_AT_BLANK_LINE

**Comment by descartin** [comment]
Hello Richard

thanks for the update
we dont have intention to use the change in live traffic since we also prefer the b-leg fixes that SDP, but anycase i let you know that i just recompiled the rtpengine after changing that line in Makefile of daemon directory, but testing again is the same

Feb 24 14:39:19 rtpengine-test rtpengine[20128]: Startup complete, version 3.3.0.0+0~mr3.8.0.0
.....
Feb 24 14:41:50 rtpengine-test rtpengine[20128]: Got valid command from 79.170.64.185:51892: answer - { "sdp": "v=0#015#012o=user1 53655765 2353687637 IN IP4 79.170.68.171#015#012s=-#015#012c=IN IP4 79.170.68.171#015#012t=0 0#015#012m=audio 6000 RTP/AVP 0#015#012a=rtpmap:0 PCMU/8000#015#012a=sendrecv#015#012#015#012", "ICE": "remove", "flags": [ "trust-address" ], "replace": [ "session-connection" ], "call-id": "1-25557@79.170.68.171", "received-from": [ "IP4", "79.170.71.132" ], "from-tag": "25557SIPpTag001", "to-tag": "7", "command": "answer" }
Feb 24 14:41:50 rtpengine-test rtpengine[20128]: Error parsing SDP at offset 149: Missing '=' sign
Feb 24 14:41:50 rtpengine-test rtpengine[20128]: Protocol error in packet from 79.170.64.185:51892: Failed to parse SDP [d3:sdp151:v=0#015#012o=user1 53655765 2353687637 IN IP4 79.170.68.171#015#012s=-#015#012c=IN IP4 79.170.68.171#015#012t=0 0#015#012m=audio 6000 RTP/AVP 0#015#012a=rtpmap:0 PCMU/8000#015#012a=sendrecv#015#012#015#0123:ICE6:remove5:flagsl13:trust-addresse7:replacel18:session-connectione7:call-id21:1-25557@79.170.68.17113:received-froml3:IP413:79.170.71.132e8:from-tag15:25557SIPpTag0016:to-tag1:77:command6:answere]
Feb 24 14:41:50 rtpengine-test rtpengine[20128]: Returning to SIP proxy: d6:result5:error12:error-reason19:Failed to parse SDPe
.....

best regards
david

**Comment by rfuchs** [comment]
Did you run "make clean" first?

**Comment by descartin** [comment]
yes i did on daemon only, but now i did un apt-get remove of all the packets installed 
apt-get remove ngcp-rtpengine-daemon ngcp-rtpengine-iptables ngcp-rtpengine-kernel-dkms ngcp-rtpengine-kernel-source

and then reinstalled again the rtpengine and seems now it works with no error

thanks for your help
david
