### ISSUE TITLE
Kernel indicates that ancillary data was truncated

### ISSUE THREAD

**Issue by korayvt** [sipwise/rtpengine#770]
Hi,
I have two rtpengines running on two different servers.
On one of the servers, the following warning log continuously is printed during the call:

WARNING: [RJCPF6~Myg port 12554]: Kernel indicates that ancillary data was truncated

Do you have any idea what the cause of this is?

**Comment by rfuchs** [comment]
Curious. Which kernel version and architecture is this one?

**Comment by korayvt** [comment]
Linux version 2.6.32-504.el6.x86_64 (mockbuild@x86-023.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) ) #1 SMP Tue Sep 16 01:56:35 EDT 2014

**Comment by korayvt** [comment]
Are there any system parameter that can cause those logs?
Because the other server has also very similar kernel version:

Linux version 2.6.32-431.el6.x86_64 (mockbuild@x86-023.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) ) #1 SMP Sun Nov 10 22:19:54 EST 2013

**Comment by rfuchs** [comment]
Not to my knowledge. You can try increasing the size of the buffer used for the ancillary data. Look for `char ctrl[32]` in `socket.c` and increase it to 64. Recompile and see if that fixes it.

**Comment by korayvt** [comment]
Yes, increasing the buffer size fixed the issue. Thanks.
