### ISSUE TITLE
Multiple interface IPs without multiple instances

### ISSUE THREAD

**Issue by denislemire** [sipwise/rtpengine#772]
We're running at a scale where we approach the limit of available UDP ports that can be used with a single IP but the host load is still sufficiently low that binding additional IPs would be a valid option to scale up.

I couldn't deduce a clear answer from the docs. Is it possible to setup a single instance of RTPENGINE to utilize a single interface with multiple IPs and have it balance the load across the available IPs?

My current setup has the actual media IP bound to lo with the media statically routed to the underlying box. I'd like to add an additional public loopback IP to double our media handling capacity.

**Comment by rfuchs** [comment]
Sure. Configure multiple interfaces using the `foo:bar` naming scheme. For example, `pub:1/192.0.2.67 ; pub:2/10.35.2.75`. You can then refer to the interface named `pub` (via `direction=...`) and it will do a round-robin between `pub:1` and `pub:2`.

**Comment by denislemire** [comment]
I've setup rtpengine.conf as follows:

```
[rtpengine]
table = 0
#interface = default/x.x.x.140
interface = default:1/x.x.x.x.140; default:2/x.x.x.142
listen-ng = x.x.x.140:2223
listen-cli = x.x.x.140:9900
timeout = 60
silent-timeout = 3600
tos = 184
redis = 127.0.0.1:6379/1
```

I'm not using 'direction=' anywhere but given there's only one named interface, do I need to?

This doesn't seem to be doing round-robin, rather all calls are using the .140 IP... Should it actually round-robin or will it end up using the secondary IP if the range of the first is fully utilized?

Do I need a specific version, I'm using 7.2.0.0+0~mr7.2.0.0

**Comment by rfuchs** [comment]
Yes you still need to use `direction=`, otherwise the first interface (`default:1`) will always be used.

**Comment by denislemire** [comment]
I don't think I can set direction appropriately to round-robin with the RTPENGINE module in OpenSIPS 2.2. OpenSIPS 2.4 should be fine because it passes flags through more freely...

**Comment by rodrigodc** [comment]
Just in case someone ever needs it:

https://www.sipwise.com/doc/mr12.2.1/spce/ce/mr12.2.1/network-config/network-config.html#_extended_rtp_port_range_using_multiple_interfaces
