### ISSUE TITLE
RTP Stream UAC/UAC

### ISSUE THREAD

**Issue by eliakimfelmorais** [sipwise/rtpengine#777]
Hello,

I'd like to know if in RTPEngine is possible to play a stream prompt before the user answer the call, like in RTPProxy have the commands rtpproxy_stream2uac and rtpproxy_stream2uas.

**Comment by rfuchs** [comment]
Yes, through `play_media` - see https://github.com/sipwise/rtpengine#play-media-message and https://kamailio.org/docs/modules/5.3.x/modules/rtpengine.html#rtpengine.f.play_media
