### ISSUE TITLE
Invalid RFC2833 timestamp for RTPEngine transcoded session

### ISSUE THREAD

**Issue by adil-mafzool** [sipwise/rtpengine#778]
RTPEngine isn't transcoding DTMF RTPEvent when using opus to PCMA because of invalid timestamp: -

CallerPhone-A (RTP) Offer
```
m=audio 6562 RTP/AVP 8 0 18 96
c=IN IP4 91.228.242.87
a=rtpmap:96 telephone-event/8000
a=fmtp:96 0-15
```

Kamailio Proxy (RTP Engine: Version 7.1.0.0+0~mr7.1.0.0 git-mr7.1-cloudcall-mg-145731e) Offer
```
m=audio 41622 RTP/AVP 97 9 8 0 18 96
c=IN IP4 91.228.242.98
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:18 G729/8000
a=rtpmap:96 telephone-event/8000
a=rtpmap:97 opus/48000/2
a=rtpmap:9 G722/8000
a=fmtp:96 0-15
a=sendrecv
a=rtcp:41623
```

CalleePhone-B Answer
```
m=audio 50134 RTP/AVP 97 8 0 18 96
c=IN IP4 172.31.17.152
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:97 opus/48000/2
a=fmtp:97 sprop-maxcapturerate=48000; maxaveragebitrate=40000; maxplaybackrate=48000; useinbandfec=1
a=ptime:20
a=rtpmap:96 telephone-event/8000
a=fmtp:96 0-15
a=sendrecv
```

RTP Engine: (Version 7.1.0.0+0~mr7.1.0.0 git-mr7.1-cloudcall-mg-145731e) Answer to CallerPhone-A: -
```
c=IN IP4 91.228.242.98
m=audio 41636 RTP/AVP 8 96
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:18 G729/8000
a=rtpmap:96 telephone-event/8000
a=fmtp:96 0-15
a=sendrecv
a=rtcp:41637
a=ptime:20
```

First Opus RTPEvent transcoded packet
`Packet # 3451 timestamp: 810240` is correct for opus stream
last `RTP Packet # 3448 timestamp: 135520`  for transcoded PCMA
but 
First transcoded session PCMA `Packet # 3452 timestamp: 810240` is wrong and as it should have been `135680`

 As it is stated in the `rfc2833` section` 3 RTP Payload Format for Named Telephone Events`
>     DTMF digits and named telephone events are carried as part of the
>    audio stream, and MUST use the same sequence number and time-stamp
>    base as the regular audio channel to simplify the generation of audio
>    waveforms at a gateway. The default clock frequency is 8,000 Hz, but
>    the clock frequency can be redefined when assigning the dynamic
>    payload type.

Hence, the RTPEvent packets are not being processed by B2BUA. 
Please can someone have look at this issue. 

Wirshark attached here.
(https://github.com/sipwise/rtpengine/files/3203450/InvalidRfc2833Timestamp.zip)

**Comment by rfuchs** [comment]
DTMF transcoding is not currently supported. That includes scaling timestamps. Support is coming soon though.

**Comment by adil-mafzool** [comment]
This isn't dtmf rfc2833 transcoded issue but the timestamp is wrong for the rtp stream, since it hasn't been handled in the same way as rtp stream time stamp. Sequence number is handled correctly. 
RFC2833 required both sequence number and timestamp to be handled.

**Comment by rfuchs** [comment]
Yes I understand, but DTMF payloads are not handled in a transcoding scenario.

**Comment by adil-mafzool** [comment]
Do I know when will this feature will be available?

**Comment by rfuchs** [comment]
Within the next few weeks

**Comment by adil-mafzool** [comment]
Could you drop me a line when it is available?

**Comment by adil-mafzool** [comment]
@rfuchs will the DTMF handling back ported to mr7.1 ?

**Comment by rfuchs** [comment]
No. New features don't get backported.

This has been merged to master now btw.
