### ISSUE TITLE
Failed to set Opus frame_duration option to 20: Option not found

### ISSUE THREAD

**Issue by juha-h** [sipwise/rtpengine#779]
I tested play_media to an opus coded call and got warning message:
```
May 22 13:57:16 salmon rtpengine[5756]: WARNING: [b2fde618f8521b71]: Failed to set Opus frame_duration option to 20: Option not found
```
There is no frame duration option in sdp offer or answer. Both look like this:
```
a=rtpmap:96 opus/48000/2.
a=fmtp:96 stereo=0;sprop-stereo=0;maxaveragebitrate=28000;cbr=0;useinbandfec=1.
```

**Comment by juha-h** [comment]
Actually, there is this codec independent attribute in the sdp:
```
a=ptime:20.
```
Baresip adds that by default.  Why does rtpengine generate the warning?

**Comment by juha-h** [comment]
SDP RFC4566 tells that ptime is "is intended as a recommendation for the encoding/packetisation of audio".  Since it is only a recommendation, I would suggest lowering the log level of this message to INFO or DEBUG.

**Comment by rfuchs** [comment]
This actually comes from libav/ffmpeg. Rtpengine wants to honour the ptime but ffmpeg returns an error when trying to set it. So I'd say a warning is appropriate. I'm not sure why ffmpeg returns an error though as according to the docs, that option should exist...

**Comment by juha-h** [comment]
Sipwise Jenkins User writes:

> Closed #779 via ca30ecaa3d7bdf6193c7890508cf33df8b068cfa.

Thanks, Juha

**Comment by mtejedas** [comment]
I need help, I have the same problem in transcoding

rtpengine git-master-6e1d94d (March 2020)
ffmpeg version 3.4.7

Initial INVITE SDP
v=0
o=6737 668 65 IN IP4 X.X.X.X
s=Talk
c=IN IP4 X.X.X.X
t=0 0
a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
m=audio 7078 RTP/AVP 96 101
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
a=rtpmap:101 telephone-event/48000
a=rtcp-fb:* trr-int 1000
a=rtcp-fb:* ccm tmmbr

SDP return

v=0
o=MySWITCH 1586189963 1586189964 IN IP4 X.X.X.X
s=MySWITCH
c=IN IP4 X.X.X.X
t=0 0
m=audio 12536 RTP/AVP 96 101
a=rtpmap:96 opus/48000/2
a=rtpmap:101 telephone-event/48000
a=fmtp:96 useinbandfec=1
a=sendrecv
a=rtcp:12537
a=ptime:20

But one way transcode and log error:

WARNING: [ICEmi-cAP- port 12638]: Failed to set Opus frame_duration option to 20: Option not found
ERR: [ICEmi-cAP- port 12638]: Error configuring media output for codec opus: failed to open output context

![Captura](https://user-images.githubusercontent.com/48223721/78613932-1f321180-783b-11ea-8586-16a44a8b75fd.JPG)


I would appreciate your help.
Thanks.

**Comment by rfuchs** [comment]
This is probably a problem with your ffmpeg. Lack of a frame_duration should not keep Opus from functioning. Are you able to try a different (newer) ffmpeg version? Which platform/system/release is this on?
