### ISSUE TITLE
rtpengine not bridging audio from ipv4 to ipv6 interface

### ISSUE THREAD

**Issue by sanket-ecos** [sipwise/rtpengine#781]
We have configured rtpengine with Kamailio. This rtpengine is configured work on both ipv4 and ipv6 interfaces. The issue is that rtpengine is not able to bridge rtp from ipv4 to ipv6 interface. Though it is able to bridge from ipv6 to ipv4 interface. Kamailio is working as a proxy between two endpoints. 

Attaching pcap(as .txt file) and logs(as .log file) of rtpengine for a simple call from endpoint A (Having rtp ipv6 : 2401:2d00:3:70::a) to endpoint B (on a local ipv4 have rtp ip : 10.50.8.8). RTP ipv6 for rtpengine is 2607:f900:3::6 and that for ipv4 is 10.50.8.6. In this case RTP flowing from endpoint A to B(IPv6 to IPv4) but not flowing from B to A (IPv4 to IPv6), though it is reaching up to rtpengine from endpoint B but rtpengine not sending it out. 
 
RTPengine configuration : 
ExecStart=/usr/local/bin/rtpengine -p /var/run/rtpengine.pid --table=1 --interface internal/10.50.8.6!198.136.226.6 --interface external/2607:F900:3::6 --listen-ng 127.0.0.1:53331 -m 10000 -M 37500 -L 7 --log-facility=local1

Kamailio configuration for offer : 
rtpengine_offer("trust-address media-address=LOCAL_IP ICE=remove direction=external direction=internal")

Kamaiio configuratio for answer : 
rtpengine_answer("trust-address ICE=remove direction=internal direction=external")

rtpengine Version: git-master-ca30eca(Built from latest master branch)
kamailio version: kamailio 5.0.2 (x86_64/linux)
OS : CentOS Linux 7
Kernel : 5.1.0

[no_audio_ipv6.log](https://github.com/sipwise/rtpengine/files/3211788/no_audio_ipv6.log)
[no_audio_ipv6.txt](https://github.com/sipwise/rtpengine/files/3211830/no_audio_ipv6.txt)

**Comment by rfuchs** [comment]
Check your firewall and routing config. There's no reason this shouldn't be working.

**Comment by sanket-ecos** [comment]
We have checked firewall config for this and that seems perfect to us.

I have a little doubt regarding this firewall setting, firewall setting should matter for incoming RTP packet and that is flowing perfectly. And if it is blocking outgoing RTP then those rtp packets must be available in tcpdump packet capture indicating that they have been generated by rtpengine. We did captures on an interface but no outgoing rtp packets were available. So still I have a doubt that this issue belongs to bridging from ipv4 to ipv6.

**Comment by rfuchs** [comment]
If packets are blocked in an OUTPUT rule, then you wouldn't see them in a tcpdump. Also the routing config is important. If IPv6 routing is not correct, no packets can be sent, and you wouldn't see them either. You should be able to verify either quite easily through ping6, netcat6, or similar.

Last resort is to attach an strace (`strace -f -p $PID`) to rtpengine and look for the `sendmsg` calls sending packets to the IPv6 address.

**Comment by rfuchs** [comment]
Cleaning up old tickets
