### ISSUE TITLE
AMR/AMR-WB: Bandwidth Efficient by Default or configurable

### ISSUE THREAD

**Issue by ngvoice** [sipwise/rtpengine#784]
Hi,

when transcoding INTO AMR or AMR-WB, the offer will be only Octet-Aligned (OA) (transcode=amr transcode=amr-wb), but not "bandwidth efficient". Transcoding FROM AMR/AMR-WB in "bandwidth efficient" mode works.

It would be nice, to make it either selectable through command options or by setting this through configuration options.

Thanks,
Carsten

**Comment by energygreek** [comment]
ffmpeg does not support this option for encode neither,  how do you solve this problem? @ngvoice

**Comment by energygreek** [comment]
thanks but what's the appropriate fmtp option string for "amr_nb/amr_wb bandwith-efficient" mode?

**Comment by rfuchs** [comment]
Some examples are given in the docs: https://github.com/sipwise/rtpengine#amr-and-amr-wb

For example `codec-transcode-AMR-WB/16000/1/23850//mode-set--0,1,2,3,4,5;octet-align--0`

**Comment by rfuchs** [comment]
Use the mailing list for further general questions: https://rtpengine.com/mailing-list
