### ISSUE TITLE
Issue Installing RTPEngine on Centos 7

### ISSUE THREAD

**Issue by T-XCV** [sipwise/rtpengine#787]
Hi Guys,

I have been following the instructions to install RTPEngine on Centos 7 on "https://github.com/sipwise/rtpengine/wiki/Install-RTPEngine-on-Centos-7" using the source code from the master branch on "https://github.com/sipwise/rtpengine".

Initially when I ran make in daemon i got the following error as I did not have the library spandsp

[root@f945378543ff daemon]# make
make: *** No rule to make target `/usr/include/spandsp/telephony.h', needed by `.depend'.  Stop.

after installing spandsp and spandsp-devel I got the error undefined reference to `dtmf_rx_fillin:

[root@f945378543ff daemon]# make
make rtpengine rtpengine.8
make[1]: Entering directory `/usr/local/src/rtpengine/daemon'
cc  -g -Wall -Wstrict-prototypes -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread     -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include     -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg     -DWITH_TRANSCODING -I/usr/include/mysql -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DRTPENGINE_VERSION="\"git-master-e17544a\"" -O3 -o rtpengine main.o kernel.o poller.o aux.o control_tcp.o call.o control_udp.o redis.o bencode.o cookie_cache.o udp_listener.o control_ng.strhash.o sdp.strhash.o stun.o rtcp.o crypto.o rtp.o call_interfaces.strhash.o dtls.o log.o cli.o graphite.o ice.o media_socket.o homer.o recording.o statistics.o cdr.o ssrc.o iptables.o tcp_listener.o codec.o load.o dtmf.o timerthread.o media_player.o loglib.o auxlib.o rtplib.o str.o socket.o streambuf.o ssllib.o dtmflib.o codeclib.o resample.o -lm -lglib-2.0   -pthread -lgthread-2.0 -lglib-2.0   -lz   -lpcre   -lcrypto   -lssl -lcrypto   -levent_pthreads -levent   -lpcap -lxmlrpc_client   -lxmlrpc   -lxmlrpc_util   -lhiredis -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0   -lip4tc -lip6tc   -lavcodec   -lavformat   -lavutil   -lswresample   -lavfilter   -L$(exec_prefix)/lib64 -lspandsp -ltiff -lm   -L/usr/lib64 -lmysqlclient -lpthread -lz -lm -ldl -lssl -lcrypto
/bin/sh: exec_prefix: command not found
codec.o: In function `__dtmf_detect':
/usr/local/src/rtpengine/daemon/codec.c:1377: undefined reference to `dtmf_rx_fillin'
collect2: error: ld returned 1 exit status
make[1]: *** [rtpengine] Error 1
make[1]: Leaving directory `/usr/local/src/rtpengine/daemon'
make: *** [all] Error 2

`dtmf_rx_fillin' is not defined in dtmf.h in spandsp.

I have seen it defined in the freeswitch spandsp "http://code.thunisoft.com/media/freeswitch/blob/master/src/libs/spandsp/src/dtmf.c"

Any help would be appreciated,

Thanks,

Tino

**Comment by olegans1972** [comment]
I have the same behavior and errors.

**Comment by rfuchs** [comment]
Looks like the version shipped with CentOS doesn't include that function, even though supposedly it's the same version as shipped in Jessie, which does include that function.

**Comment by olegans1972** [comment]
And how now to be?

**Comment by n8twj** [comment]
This is still an issue


# make -j2
make rtpengine rtpengine.8
make[1]: Entering directory `/root/rtpengine-mr9.0.1.1/daemon'
cc  -g -Wall -Wstrict-prototypes -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread     -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include     -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg     -DWITH_TRANSCODING -I/usr/include/mysql -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DRTPENGINE_VERSION="\"undefined\"" -O3 -o rtpengine main.o kernel.o poller.o aux.o control_tcp.o call.o control_udp.o redis.o bencode.o cookie_cache.o udp_listener.o control_ng.strhash.o sdp.strhash.o stun.o rtcp.o crypto.o rtp.o call_interfaces.strhash.o dtls.o log.o cli.o graphite.o ice.o media_socket.o homer.o recording.o statistics.o cdr.o ssrc.o iptables.o tcp_listener.o codec.o load.o dtmf.o timerthread.o media_player.o jitter_buffer.o t38.o loglib.o auxlib.o rtplib.o str.o socket.o streambuf.o ssllib.o dtmflib.o codeclib.o resample.o -lm -lglib-2.0   -pthread -lgthread-2.0 -lglib-2.0   -lz   -lpcre   -lcrypto   -lssl -lcrypto   -levent_pthreads -levent   -lpcap -lxmlrpc_client   -lxmlrpc   -lxmlrpc_util   -lhiredis -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0   -lip4tc -lip6tc   -lavcodec   -lavformat   -lavutil   -lswresample   -lavfilter   -L$(exec_prefix)/lib64 -lspandsp -ltiff -lm   -L/usr/lib64/mysql -lmysqlclient -lpthread -lz -lm -ldl -lssl -lcrypto
make[1]: `rtpengine.8' is up to date.
/bin/sh: exec_prefix: command not found
main.o: In function `init_everything':
/root/rtpengine-mr9.0.1.1/daemon/main.c:811: undefined reference to `sdp_init'
/root/rtpengine-mr9.0.1.1/daemon/main.c:817: undefined reference to `control_ng_init'
main.o: In function `create_everything':
/root/rtpengine-mr9.0.1.1/daemon/main.c:883: undefined reference to `rtpe_control_ng'
main.o: In function `main':
/root/rtpengine-mr9.0.1.1/daemon/main.c:1051: undefined reference to `rtpe_control_ng'
/root/rtpengine-mr9.0.1.1/daemon/main.c:1051: undefined reference to `rtpe_control_ng'
main.o: In function `create_everything':
/root/rtpengine-mr9.0.1.1/daemon/main.c:886: undefined reference to `control_ng_new'
/root/rtpengine-mr9.0.1.1/daemon/main.c:886: undefined reference to `rtpe_control_ng'
rtcp.o: In function `rtcp_sender_report':
/root/rtpengine-mr9.0.1.1/daemon/rtcp.c:1445: undefined reference to `rtpe_instance_id'
/root/rtpengine-mr9.0.1.1/daemon/rtcp.c:1472: undefined reference to `rtpe_instance_id'
call_interfaces.strhash.o: In function `call_offer_answer_ng':
/root/rtpengine-mr9.0.1.1/daemon/call_interfaces.strhash.c:1368: undefined reference to `sdp_parse'
/root/rtpengine-mr9.0.1.1/daemon/call_interfaces.strhash.c:1371: undefined reference to `sdp_is_duplicate'
/root/rtpengine-mr9.0.1.1/daemon/call_interfaces.strhash.c:1496: undefined reference to `sdp_free'
/root/rtpengine-mr9.0.1.1/daemon/call_interfaces.strhash.c:1379: undefined reference to `sdp_streams'
/root/rtpengine-mr9.0.1.1/daemon/call_interfaces.strhash.c:1436: undefined reference to `sdp_chopper_new'
/root/rtpengine-mr9.0.1.1/daemon/call_interfaces.strhash.c:1437: undefined reference to `sdp_chopper_destroy'
/root/rtpengine-mr9.0.1.1/daemon/call_interfaces.strhash.c:1362: undefined reference to `magic_load_limit_strings'
/root/rtpengine-mr9.0.1.1/daemon/call_interfaces.strhash.c:1457: undefined reference to `sdp_replace'
cli.o: In function `cli_incoming_set_controltos':
/root/rtpengine-mr9.0.1.1/daemon/cli.c:1397: undefined reference to `rtpe_control_ng'
statistics.o: In function `statistics_gather_metrics':
/root/rtpengine-mr9.0.1.1/daemon/statistics.c:493: undefined reference to `rtpe_cngs_lock'
/root/rtpengine-mr9.0.1.1/daemon/statistics.c:494: undefined reference to `rtpe_cngs_hash'
/root/rtpengine-mr9.0.1.1/daemon/statistics.c:558: undefined reference to `rtpe_cngs_lock'
collect2: error: ld returned 1 exit status
make[1]: *** [rtpengine] Error 1
make[1]: Leaving directory `/root/rtpengine-mr9.0.1.1/daemon'
make: *** [all] Error 2

**Comment by n8twj** [comment]
CentOS Linux release 7.8.2003 (Core)

**Comment by n8twj** [comment]
Following https://github.com/sipwise/rtpengine/wiki/Install-RTPEngine-on-Centos-7

**Comment by cervajs** [comment]
it works with spandsp builds from freeswitch https://files.freeswitch.org/repo/yum/centos-release/7/x86_64/

**Comment by mrsanvicente** [comment]
Still the same issue: on 
CentOS Linux release 7.9.2009 (Core)


/bin/sh: exec_prefix: command not found
media_player.o: In function `__media_player_free':
/usr/src/rtpengine/daemon/media_player.c:101: undefined reference to `av_packet_free'
media_player.o: In function `media_player_new':
/usr/src/rtpengine/daemon/media_player.c:128: undefined reference to `av_packet_alloc'
codeclib.o: In function `avc_decoder_init':
/usr/src/rtpengine/daemon/codeclib.c:598: undefined reference to `av_packet_alloc'
codeclib.o: In function `avc_decoder_close':
/usr/src/rtpengine/daemon/codeclib.c:730: undefined reference to `av_packet_free'
codeclib.o: In function `encoder_new':
/usr/src/rtpengine/daemon/codeclib.c:1239: undefined reference to `av_packet_alloc'
codeclib.o: In function `encoder_free':
/usr/src/rtpengine/daemon/codeclib.c:1381: undefined reference to `av_packet_free'
collect2: error: ld returned 1 exit status
make[1]: *** [rtpengine] Error 1
make[1]: Leaving directory `/usr/src/rtpengine/daemon'
make: *** [all] Error 2

**Comment by adil-mafzool** [comment]
@mrsanvicente Is this issue resolved or you still having this issue? As I am experiencing this issue too

**Comment by mrsanvicente** [comment]
Hello @adil-mafzool.


Yes, I was not able to solve it on Centos.   I moved to Debian 10 and it is working fine.

Cheers
Mario San Vicente

**Comment by nithinsr** [comment]
- To fix `/bin/sh: exec_prefix: command not found` install spandsp and spandsp-devel from https://files.freeswitch.org/repo/yum/centos-release/7/x86_64/
- To fix `__media_player_free': /usr/src/rtpengine/daemon/media_player.c:101: undefined reference to av_packet_free'` and if you do not need transcoding, then edit Makefile and change `with_transcoding ?= yes` to `with_transcoding ?= no`

**Comment by Aayush-jain007** [comment]
I am having issues installing rtp engine in debian. Can anyone help me with any doucmentation of any kind. I tried to follow many documentations and I have got the same issue with them all.
dpkg -i command is not able to unpack the .deb files properly and is giving dependencies error. ngcp-rtpengine-record-daemon error
