### ISSUE TITLE
Debian packages available for master branch

### ISSUE THREAD

**Issue by gled-rs** [sipwise/rtpengine#79]
Leaving a note here, if someone needs debian packages, they are automatically built at each commit on the master branch. They are built without the ngcp dependancies.

Url of the repo is http://repo.remote-shell.net ( only unstable are built now ).

The stable packages can also be built if someone needs it, just leave me a note !

**Comment by rfuchs** [comment]
Nice, thank you.

**Comment by lopezdonaque** [comment]
The current Debian packages on the repository are not updated.

**Comment by rfuchs** [comment]
Closing this as this is not maintained by us.

**Comment by gled-rs** [comment]
Oh yes correct, should have warned. 

I am migrating the servers, it should be back soon !
