### ISSUE TITLE
no rtcp-mux attribute in answer response for multiple branches

### ISSUE THREAD

**Issue by korayvt** [sipwise/rtpengine#793]
Hi,

I attached two different log files.

One is for single branch call (rctp-mux.log) and the other is for multiple branch call (no-rtcp-mux.log). 
Although the command for the answer is similar in those two scenarios, I could not get rtcp-mux attribute in answer response sdp in multiple branch call.

Am I missing something?

[no-rtcp-mux.log](https://github.com/sipwise/rtpengine/files/3274989/no-rtcp-mux.log)
[rtcp-mux.log](https://github.com/sipwise/rtpengine/files/3274990/rtcp-mux.log)

**Comment by rfuchs** [comment]
Can confirm that this is not working as expected
