### ISSUE TITLE
support for transcoding G.729b (SID frames)

### ISSUE THREAD

**Issue by davehorton** [sipwise/rtpengine#794]
Does rtpengine support (decoding) G729 annex B?

This line:

https://github.com/sipwise/rtpengine/blob/e1e3f2f6df023e96d00299da9c41265f46eaacf9/lib/codeclib.c#L1629

makes me think it does not (yet).  The `SIDFrameFlag` parameter in the call to `bcg729Decoder` is hardcoded to 0 (?).  Please let me know if I am incorrect, or overlooking something..

**Comment by rfuchs** [comment]
That's correct, that's not currently supported. Shouldn't be too difficult to add though, at least for decoding.

**Comment by davehorton** [comment]
ok thanks.  My need is for decoding (only).  Would you be interested in a pull request and/or some form of collaboration (which may involve me shooting you some questions now and then)?

**Comment by rfuchs** [comment]
Pull request is fine if you're comfortable with it. Also feel free to ask questions.

**Comment by rfuchs** [comment]
Cleaning up old tickets
