### ISSUE TITLE
[Improvement] Resolve redis endpoint at connection

### ISSUE THREAD

**Issue by bodji** [sipwise/rtpengine#799]
Hi,

We are deploying RTPEgine in a container cluster.

The redis container has a volatile private IP, and when the container 
change of host, or restarts, the ip is changing, and the daemon try to reconnect 
on old IP indefinitely.

As you see, the resolve is done only at startup : 
```
	if (redisps)
		if (redis_ep_parse(&rtpe_config.redis_ep, &rtpe_config.redis_db, &rtpe_config.redis_auth, "RTPENGINE_REDIS_AUTH_PW", redisps))
			die("Invalid Redis endpoint [IP:PORT/INT] '%s' (--redis)", redisps);

	if (redisps_write)
		if (redis_ep_parse(&rtpe_config.redis_write_ep, &rtpe_config.redis_write_db, &rtpe_config.redis_write_auth,
					"RTPENGINE_REDIS_WRITE_AUTH_PW", redisps_write))
			die("Invalid Redis endpoint [IP:PORT/INT] '%s' (--redis-write)", redisps_write);

```

Do you think it's possible to do the resolution 
everytime a new connection is made ?

Kind regards,
Mathieu Bodjikian

**Comment by rfuchs** [comment]
It's possible, but it's not ideal, as a DNS resolve takes time and in some instances when Redis commands are issued, extra delay might cause timeouts. I would suggest to solve this in a different way instead, for example using a shared floating IP, or a local Redis instance as intermediate that replicates to an upstream master.

**Comment by rfuchs** [comment]
Cleaning up old tickets
