### ISSUE TITLE
missing description in documentation

### ISSUE THREAD

**Issue by ovoshlook** [sipwise/rtpengine#800]
Hi
I'm working with rtpengine by getting info from query command for now and found that messages next after 1 contains SSRC field that was undocumented
"SSRC": {
	"3390111744": {},
	"1109023349": {
		"average MOS": {
			"packet loss": 0,
			"MOS": 44,
			"jitter": 0,
			"samples": 1,
			"round-trip time": 0
		},
		"highest MOS": {
			"packet loss": 0,
			"reported at": 1561971072,
			"MOS": 44,
			"jitter": 0,
			"round-trip time": 0
		},
		"lowest MOS": {
			"packet loss": 0,
			"reported at": 1561971072,
			"MOS": 44,
			"jitter": 0,
			"round-trip time": 0
		},
		"MOS progression": {
			"interval": 0,
			"entries": [{
				"packet loss": 0,
				"reported at": 1561971072,
				"MOS": 44,
				"jitter": 0,
				"round-trip time": 0
			}]
		}
	}
}
Im working right now with 6.3.1 version
This is really cool that rtpengine also sends this information but I just wanted to wonder is this also allowed for 5.x and 7.x version?

If yes - could I help to update documentation then?

Sorry for posting this in the issues track

**Comment by rfuchs** [comment]
This was added in mr5.3. All later versions support it. It's also reported back in the response to a `delete` command. It's used for MOS and other call quality stats reporting to Kamailio.

**Comment by ovoshlook** [comment]
thx a lot for answer!
