### ISSUE TITLE
Rtpengine-recording labels issue.

### ISSUE THREAD

**Issue by zbazarov** [sipwise/rtpengine#801]
Hello! I ran into an issue with rtpengine_recording daemon...
When I put label into offer message like this:
rtpengine_offer("label=foobar");

Label success adding into database into tag_label column, but only when it was just SIP call....
 I can't insert label name into database when WEBrtc calls(there are records but column tag_label is empty)...
 But rtpengine-recording.log is the same for both case...

 
Jul  1 21:30:40 ip-10-4-1-247 rtpengine[27696]: INFO: [v891ug61419qjf5pjekm]: --- Tag 'as1d6eb694' (label 'foobar'), created 0:39 ago for branch '', in dialogue with 'p6nqk2uj2a'
Jul  1 21:30:48 ip-10-4-1-247 rtpengine[27696]: INFO: [IJh3TZY2ze4EJLvqbRMT_w..]: Call branch '6dd1a06b' (label 'foobar', via-branch '') deleted, no more branches remaining
Jul  1 21:30:48 ip-10-4-1-247 rtpengine[27696]: INFO: [IJh3TZY2ze4EJLvqbRMT_w..]: --- Tag '6dd1a06b' (label 'foobar'), created 0:36 ago for branch '', in dialogue with 'as11f2c69e'
Jul  1 21:30:48 ip-10-4-1-247 rtpengine[27696]: INFO: [IJh3TZY2ze4EJLvqbRMT_w..]: --- Tag 'as11f2c69e' (label 'foobar'), created 0:36 ago for branch '', in dialogue with '6dd1a06b'

**Comment by rfuchs** [comment]
Can you post a full log for an entire call?

**Comment by zbazarov** [comment]
@rfuchs Thanks for you reply. Yes, I'll able do that in a few hours... But, side question... Could you, please, explain principle of work label tags? I mean, Do I need firstly add the label and than execute start_recording, or I should do it after I have executed start_recording?
Now I'm executing start_recording in on_reply routes(FROM_WS, TO_WS, SIP_TO_SIP) and in case SIP_TO_SIP - everything is ok..

**Comment by rfuchs** [comment]
The label is applied to the side that is doing the signalling (e.g. in an `rtpengine_offer` from an INVITE you could say `label=caller`). Then, when recording is started, the labels are passed to the recording daemon for later storage. So the labels must already be in place when the recording is being started.

**Comment by zbazarov** [comment]
Should I use multiple start_recording e.g. in on_reply_route - or single running will be enough??
I mean, I was trying add labels on each offer message, and was trying execute start_recording in each part of kamailio route config, but it was useful for WEBrtc legs.. 
Everything is recorded but without label tag..

**Comment by rfuchs** [comment]
Just one `start_recording`. The label must be set when the corresponding call party is first seen, or before recording is started. So for example, this should work:
```
rtpengine_offer("label=caller");
start_recording();
...
rtpengine_answer("label=callee");
...
```

while this wouldn't:

```
rtpengine_offer("");
start_recording();
...
rtpengine_offer("label=caller");
...
rtpengine_answer("");
...
rtpengine_answer("label=callee");
```

**Comment by zbazarov** [comment]
Is this right route?
route[RECORDING] {
        if (!is_method("INVITE") || !has_body("application/sdp")) return;
        start_recording();
}

 I'm going to put this into initial INVITE request. And than add needed labels to each of legs(on_reply_routes, request routes) ... Is it ok? 


And btw:
How I can use start_recording without sdp? I mean, we have to use INVITE without sdp in future for WEBrtc clients for early media posibility via PRACK and 100rel...

**Comment by rfuchs** [comment]
I can't answer that without seeing the rest of the script. The order is important. The labels have to be set before recording is started (or at the same time).

And you don't need an SDP to start recording. It can be done at any point during the call, with or without corresponding SIP request or SDP.

**Comment by zbazarov** [comment]
@rfuchs many thanks for your answers! Now its more clearly for me. I'll try something.

**Comment by zbazarov** [comment]
@rfuchs Hello! I'm a little confused... SIPtoSIP label tag has been fully implemented... But in WebRTC label-taging works half the time(In one call everything is ok, but in next one call only one leg has label)
And another one question: How I can tag mixed record ? mixed record is always empty... Maybe it possible to set custom call-id? - I mean use asterisk's uniqueid for mark each call. 
What's best practice? There is almost no info into google about this questions(

**Comment by rfuchs** [comment]
Rtpengine doesn't treat WebRTC calls any different from any other calls, so it has to be a usage error on your side. Which is why I asked for full log in the first place.

As for mixed recordings: The label tags are for individual call participants, not for the call itself. The mixed recording is for the entire call, so there is no label tag. The call ID is sufficient to identify the mixed recording for a particular call.

**Comment by zbazarov** [comment]
@rfuchs Hello! Is it makes any sense what place start_recording are executed from? 
I mean code and method/request and reply?

**Comment by zbazarov** [comment]
and also, is it ok to add flag record-call=on instead of start_recording()?

**Comment by rfuchs** [comment]
No it doesn't make a difference where you call start_recording from, and no it doesn't make a difference whether you use start_recording or the record-call flag.

**Comment by zbazarov** [comment]
Hello @rfuchs .. Sorry for bother you, but I can't find the solution on my own... rtpengine records calls well but Label-tag column is still empty in DB..

# ROUTE TO ASTERISK
                        $var(rtp_flags)="replace-origin replace-session-connection ICE=remove RTP/AVP rtcp-mux-demux";
                        if(is_method("INVITE") && $hdr(x-record) != 0 && has_body("application/sdp")) {
                        $var(rtp_flags) = $var(rtp_flags) + " label=foobar record-call=on";
                        }
                        rtpengine_manage($var(rtp_flags));


[rtpengine.log](https://github.com/sipwise/rtpengine/files/3464297/rtpengine.log)


Please, check it, when u get a chance...

**Comment by rfuchs** [comment]
Assuming this is about call `336418f75c36f6aa426abbc1188f4ef4@asterisk.local.address:port`

First you have an offer from `as29c7507d` that sets the label and also turns on recording. So far so good.

Then you have another offer from `as11051135` but going to `as29c7507d`. No label is set. Looks like this really should be an answer?

Finally you have an answer from `as11051135` to `as29c7507d` with an identical SDP than the previous offer. Also no label is set. And then this answer is repeated 3 times.

You should get rid of the extra reverse offer, and set an appropriate label in the answer.

**Comment by rfuchs** [comment]
Cleaning up old tickets
