### ISSUE TITLE
Debian 10 - SIGTERM/SIGINT issue

### ISSUE THREAD

**Issue by rrb3942** [sipwise/rtpengine#804]
I built and installed rtpengine on Debian 10 and ran into an odd issue.

On stopping the daemon systemd sends rtpengine SIGTERM but rtpengine does not exit, eventually being killed when systemd times out and sends SIGKILL.

rtpengine doesn't seem to be ignoring signals as I tested sending SIGUSR1 & SIGUSR2 to it which increased/decreased the log level.

Attached below is the output of running rtpengine on the console and the signals I sent to it from another terminal.
[rtpe_daemon_console.log](https://github.com/sipwise/rtpengine/files/3379542/rtpe_daemon_console.log)
[rtpe_signals.log](https://github.com/sipwise/rtpengine/files/3379543/rtpe_signals.log)

I see that when rtpengine gets SIGTERM/SIGINT it sets rtpe_shutdown to 1. Even though this is flagged as volatile it doesn't seem like changes to this variable are being picked up in other threads.

I also have rtpengine install on Ubuntu 18.04 and it does not exhibit this issue, and it seems to be restricted to Debian 10.

**Comment by rfuchs** [comment]
Can you attach an strace to see what's going on after sending the signal? For example, `strace -f -s 1000 -o strace.out -p $PID` while it's already running as $PID, then send SIGTERM, then post the output file `strace.out`

**Comment by rrb3942** [comment]
So, with STRACE attached rtpengine does exit, but I get a couple new lines of log output :

> INFO: Startup complete, version 7.5.0.0+0`~`mr7.5.0.0 git-master-fea0206
INFO: Use Redis 10.100.155.65:6379 for notifications
INFO: Use Redis 10.100.155.65:6379 to subscribe to notifications
**ERR: Fail redisAsyncCommand on JSON UNSUBSCRIBE_ALL
ERR: redis_async_context_disconnect initiated by user**
INFO: Version 7.5.0.0+0~mr7.5.0.0 git-master-fea0206 shutting down

Disabling redis and everything stops fast/restarts like normal.

strace attached
[strace.txt](https://github.com/sipwise/rtpengine/files/3393918/strace.txt)

**Comment by rfuchs** [comment]
Can you post your config file?

**Comment by rrb3942** [comment]
Config File:
[rtpengine.txt](https://github.com/sipwise/rtpengine/files/3408627/rtpengine.txt)
