### ISSUE TITLE
No rtp between two rtpengine instances

### ISSUE THREAD

**Issue by korayvt** [sipwise/rtpengine#806]
Hi,

I have the following architecture.

When I start a call, there are no rtp packets flowing between RtpEngine1 and RtpEngine2 although client sides have incoming rtp packets.

As I understand, both of them are waiting some rtp packets for inspection before relaying  incoming packets from client side.

      [ Client1 ] <--->  [ RtpEngine1 ] ------- [ RtpEngine2 ] <--->  [ Client2 ]  
                                |                     |
                                |                     |
                          [ Kamailio1 ]         [ Kamailio2 ]
					   
					   
Is there a way to make media flow between RtpEngine instances?

**Comment by rfuchs** [comment]
That should work out of the box provided signalling is correct. Do you have a log?

**Comment by korayvt** [comment]
After your comment, I solved the problem. There was an unexpected firewall issue. Thank you.
