### ISSUE TITLE
daemon crashes on Restoring calls from Redis if SRTP

### ISSUE THREAD

**Issue by gmaruzz** [sipwise/rtpengine#811]
Hello Richard,

i can consistently crash the daemon by having it restarted when in Redis there is a call with SRTP

from some "printf" debugging, seems to be related with sdes reconstruction, but not sure at all

in attachment, a cut and paste from redis-cli that shows the only one key into Redis (eg, Redis is empty, just this key)

If you put that key in Redis and start the daemon, daemon
[crash_redis_key.txt](https://github.com/sipwise/rtpengine/files/3406805/crash_redis_key.txt)

 will crashes

**Comment by gmaruzz** [comment]
I tested both with latest git and with 7.4.1.1

**Comment by rfuchs** [comment]
Do you have a gdb backtrace from one such crash?

**Comment by gmaruzz** [comment]
nope
what is the procedure? I must install the dbgsyms packages, get a core, then gdb bt?

**Comment by rfuchs** [comment]
You got it right :+1:

**Comment by gmaruzz** [comment]
K
I will paste here asap, hopefully tomorrow

thank you!

**Comment by gmaruzz** [comment]
yay!
so fast !!!!!
Thank you!
