### ISSUE TITLE
rtpengine and kamailio

### ISSUE THREAD

**Issue by gethubsw** [sipwise/rtpengine#812]
Just a real quick questions.  
Normally when I start Kamailio (and using rtpengine) I see approximately 10 ping/pong transactions in the rtpengine log.  For some reason, on one of my systems I only see one such transaction.  Nothing else appears out of the normal.  Is there a reason for this? is there some kind of error that I am need seeing?

Thank you!

**Comment by rfuchs** [comment]
Each Kamailio worker process that loads the rtpengine module does a ping to rtpengine during startup. So the number of pings you see should equal the number of Kamailio processes you have.

**Comment by rfuchs** [comment]
Cleaning up old tickets
