### ISSUE TITLE
Rtpengine public/private interfaces

### ISSUE THREAD

**Issue by zbazarov** [sipwise/rtpengine#814]
Hello. We have rtpengine and kamailio with public and private IP's, and we have asterisk in local network.. 
The scheme is: 
some global UAC = (pub_ip)kamailio+rtpengine(priv_ip) => (priv_ip)asterisk

rtpengine started with option --interface=internal_ip\!public_ip
So, the question is: what is best practice to configure offers and answers into rtpengine?
And also: have we can to rewrite sdp IN address? I mean, we need to use internal ip when invite goes to asterisk, and use public ip when to global UAC's.

Thanks.

**Comment by rfuchs** [comment]
The `!` notation (advertised address) is for NAT scenarios. You use it for example if you have a private address bound on your network interfaces, but you need to use a different public address to communicate to outside peers. If that's not your case, don't use it.

If you just have multiple network interfaces that you need to distinguish (doesn't matter if private or public), use multiple named interface configs. For example, with one public and one private, you could use `--interface=private/10.0.0.1 --interface=public/100.0.0.1`. And then you would use the `direction=` arguments in the `offer` to tell rtpengine which interfaces to use. For example, an offer coming from the public interface going to the private one, use `direction=public direction=private`

**Comment by zbazarov** [comment]
Hmm, thanks... 
So I need to use both direction at the same offer, right? 
I mean src is global its direction=pub, and additional direction=private - to local asterisk, it is?
I mean like this rtpengine_offer("direction=private direction=private")  for implement offer from local kam interface to local asterisk interface is it? 

Am I right?

**Comment by rfuchs** [comment]
Yes, always two `direction=`, the first where the offer is coming from, the second where it's going to.

**Comment by zbazarov** [comment]
oh, ok.. 
So, I guess the best way to implement it - is put this things into some 'NATMANAGE' route... 
And use some dynamic rtp_flags for avoid hardcode for each branch. 
correct?

**Comment by rfuchs** [comment]
Yes, you need to know which network your A is on, and which network your B is on, and pass appropriate `direction=` flags.

**Comment by zbazarov** [comment]
And also, seems like I need to check source protocol to. I mean from what device request coming from - 'ws' 'sip' etc...

**Comment by zbazarov** [comment]
okay, gotcha.. I will try. I'll tell you how it's going. 
Thanks, rly appreciate it. Its pretty complicated to find any example of implementation stuff like this

**Comment by mrsanvicente** [comment]
Hello,

I am implementing the same scenario described here, the call flow  from Public to Private on the the SDP i see the offer is fine, but the 180 ringing SDP and the answer propose the private ip to the Public one.

Any idea how to solve this?  
Also, while calling the rtpengine, should i use one table for both interfaces?
/usr/sbin/rtpengine --table=0 --interface=private/x.x.x.x --interface=public/y.y.y.y --listen-ng=127.0.0.1:2224 --tos=184 --pidfile=/run/rtpengine-1.pid --no-fallback

Public           Server          Private
Inv SDP           |                Inv SDP          
Puplicip           |                Private IP
----->              | 
                        |       -----> 
                        |       <-----    100 Trying 
                        |       <-----    180 Ringing SDP 
                        |                       Private IP
180 Ringing     |
SDP Private IP  |      
<-----               |
                        |       <-----    200 OK SDP 
                        |                       Private IP
200 Ok SDP     |
SDP Private IP  |      
<-----               |
ACK                  |
------->            |              ACK
                         |            -------->
  -----NO AUDIO---------------- 

Thanks  you in advance
Mario

**Comment by rfuchs** [comment]
All you need to do is use `direction=public direction=private` in the offer flags. Post a debug log if this doesn't seem to work for you.

**Comment by rfuchs** [comment]
Cleaning up old tickets

**Comment by vadimd333** [comment]
Hello! I have such opensips config block. But It doesn't not work for me.
Rtpengine runs with this options: --interface=private/10.0.0.2 --interface=public/XXX.XXX.XXX.XXX

```
branch_route[BRANCH_TO_PUB] {

        xlog("L_INFO", "New branch To PUB client: $si");
        rtpengine_manage("replace-origin direction=private direction=public");
}


onreply_route[REPLY_FROM_PUB] {

        xlog("L_INFO", "Reply From PUB client: $rs $si");
        rtpengine_manage("replace-origin direction=public direction=private");
}


branch_route[BRANCH_TO_PRIV] {

        xlog("L_INFO", "New branch To PRIV client: $si");
        rtpengine_manage("replace-origin direction=public direction=private");
}


onreply_route[REPLY_FROM_PRIV] {

        xlog("L_INFO", "Reply From PRIV client: $rs $si");
        rtpengine_manage("replace-origin direction=private direction=public");
}
```

Can anyone tell me what am I doing wrong?

**Comment by abieuzent** [comment]
Hi,

 

 Correct syntax for RTPENGINE module on Opensips is not “direction=” but” in-iface=” or “out-iface=”

 

https://opensips.org/docs/modules/3.1.x/rtpengine.html

 

regards

 

De : vadimd333 ***@***.***>
Répondre à : sipwise/rtpengine ***@***.***>
Date : mercredi 17 août 2022 à 22:26
À : sipwise/rtpengine ***@***.***>
Cc : Subscribed ***@***.***>
Objet : Re: [sipwise/rtpengine] Rtpengine public/private interfaces (#814)

 

Hello! I have such opensips config block. But It doesn't not work for me.
Rtpengine runs with this options: --interface=private/10.0.0.2 --interface=public/XXX.XXX.XXX.XXX
branch_route[BRANCH_TO_PUB] {
 
        xlog("L_INFO", "New branch To PUB client: $si");
        rtpengine_manage("replace-origin direction=private direction=public");
}
 
 
onreply_route[REPLY_FROM_PUB] {
 
        xlog("L_INFO", "Reply From PUB client: $rs $si");
        rtpengine_manage("replace-origin direction=public direction=private");
}
 
 
branch_route[BRANCH_TO_PRIV] {
 
        xlog("L_INFO", "New branch To PRIV client: $si");
        rtpengine_manage("replace-origin direction=public direction=private");
}
 
 
onreply_route[REPLY_FROM_PRIV] {
 
        xlog("L_INFO", "Reply From PRIV client: $rs $si");
        rtpengine_manage("replace-origin direction=private direction=public");
}
Can anyone tell me what am I doing wrong?

**Comment by vadimd333** [comment]
abieuzent, thank You!

It helped me ...
