### ISSUE TITLE
Error from RTPEngine.

### ISSUE THREAD

**Issue by nicoonline** [sipwise/rtpengine#815]
Hello,

Since yesterday i have this error with RTPEngine.

Jul 21 08:50:59 proxy1 rtpengine[1320]: WARNING: [762bfc640fc001711cfa0594166ba3ca@proxy1.s]: Protocol error in packet from 127.0.0.1:35365: Error rewriting SDP [d3:sdp564:v=0#015#01

 version git-mr6.5.4-8029bbc

**Comment by rfuchs** [comment]
Is this actually a question?

The actual error is further down the log, at the end of the log message.

**Comment by rfuchs** [comment]
... or perhaps in a different log line, either just above or below.

**Comment by nicoonline** [comment]
Hello Richard, 
i have two lines :

NOTICE: [4424d42e0d13715344b2e201689d8c83@xxx]: Creating new call
ERR: [4424d42e0d13715344b2e201689d8c83@xxx]: Error rewriting SDP
WARNING: [4424d42e0d13715344b2e201689d8c83@xxx]: Protocol error in packet from 127.0.0.1:41882: Error rewriting SDP.... and the raw of the SDP.

Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: Call branch 'as2b9f61a9' (via-branch '') deleted, no more branches remaining
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: Final packet stats:
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: --- Tag 'as2b9f61a9', created 1:00 ago for branch '', in dialogue with 'mD4N4Hg15Xm9Q'
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: ------ Media #1 (audio over RTP/AVP) using unknown codec
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: --------- Port  100.112.180.10:14340 <>   10.171.20.203:41950, SSRC 0, 0 p, 0 b, 0 e, 60 ts
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: --------- Port  100.112.180.10:14341 <>   10.171.20.203:41951 (RTCP), SSRC 0, 0 p, 0 b, 0 e, 60 ts
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: ------ Media #2 (audio over RTP/AVP) using unknown codec
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: --------- Port         0.0.0.0:0     <>          (null):0    , SSRC 0, 0 p, 0 b, 0 e, 59 ts
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: --------- Port         0.0.0.0:0     <>          (null):0     (RTCP), SSRC 0, 0 p, 0 b, 0 e, 59 ts
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: ------ Media #3 (audio over RTP/AVP) using unknown codec
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: --------- Port  100.112.180.10:14352 <>          (null):0    , SSRC 0, 0 p, 0 b, 0 e, 59 ts
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: --------- Port  100.112.180.10:14353 <>          (null):0     (RTCP), SSRC 0, 0 p, 0 b, 0 e, 59 ts
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: ------ Media #4 (audio over RTP/AVP) using unknown codec
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: --------- Port         0.0.0.0:0     <>          (null):0    , SSRC 0, 0 p, 0 b, 0 e, 59 ts
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: --------- Port         0.0.0.0:0     <>          (null):0     (RTCP), SSRC 0, 0 p, 0 b, 0 e, 59 ts
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: --- Tag 'mD4N4Hg15Xm9Q', created 1:00 ago for branch '', in dialogue with 'as2b9f61a9'
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: ------ Media #1 (audio over RTP/AVP) using unknown codec
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: --------- Port  100.112.180.10:14324 <>     xxx.66.8.22:42602, SSRC 0, 0 p, 0 b, 0 e, 60 ts
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: --------- Port  100.112.180.10:14325 <>     xxx.66.8.22:42603 (RTCP), SSRC 0, 0 p, 0 b, 0 e, 60 ts
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: ------ Media #2 (audio over RTP/AVP) using unknown codec
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: --------- Port         0.0.0.0:0     <>     xxx.66.8.22:0    , SSRC 0, 0 p, 0 b, 0 e, 59 ts
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: --------- Port         0.0.0.0:0     <>     xxx.66.8.22:1     (RTCP), SSRC 0, 0 p, 0 b, 0 e, 59 ts
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: ------ Media #3 (audio over RTP/AVP) using unknown codec
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: --------- Port  100.112.180.10:14364 <>     xxx.66.8.22:42602, SSRC 0, 0 p, 0 b, 0 e, 59 ts
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: --------- Port  100.112.180.10:14365 <>     xxx.66.8.22:42603 (RTCP), SSRC 0, 0 p, 0 b, 0 e, 59 ts
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: ------ Media #4 (audio over RTP/AVP) using unknown codec
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: --------- Port         0.0.0.0:0     <>     xxx.66.8.22:0    , SSRC 0, 0 p, 0 b, 0 e, 59 ts
Jul 20 18:34:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: --------- Port         0.0.0.0:0     <>     xxx.66.8.22:1     (RTCP), SSRC 0, 0 p, 0 b, 0 e, 59 ts

the problem was auto solved by rebooting the service three times.

**Comment by taurus-forever** [comment]
> the problem was auto solved by rebooting the service three times.

We should consider to commit this solution :-D

**Comment by rfuchs** [comment]
Pretty sure there has to be another error/warning message in the vicinity of the one you posted.

**Comment by nicoonline** [comment]
Jul 20 18:33:09 proxy1 rtpengine[1321]: NOTICE: [4424d42e0d13715344b2e201689d8c83@xxx]: Creating new call
Jul 20 18:33:09 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: Replying to 'offer' from 127.0.0.1:47187 (elapsed time 0.000155 sec)
Jul 20 18:33:10 proxy1 rtpengine[1321]: INFO: [4424d42e0d13715344b2e201689d8c83@xxx]: Received command 'answer' from 127.0.0.1:4xxx2
Jul 20 18:33:10 proxy1 rtpengine[1321]: ERR: [4424d42e0d13715344b2e201689d8c83@xxx]: Error rewriting SDP
Jul 20 18:33:10 proxy1 rtpengine[1321]: WARNING: [4424d42e0d13715344b2e201689d8c83@xxx]: Protocol error in packet from 127.0.0.1:4xxx2: Error rewriting SDP [d3:sdp576:v=0#015#012o=Media*Proxy1 559206999 559206999 IN IP4 xxx.66.8.22#015#012s=SIP Call - Session Border Controller - #015#012c=IN IP4 xxx.66.8.22#015#012t=0 0#015#012m=audio 42602 RTP/AVP 8 101#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-16#015#012a=ptime:20#015#012a=sendrecv#015#012a=rtcp:42603#015#012m=audio 0 RTP/AVP 8 96#015#012v=0#015#012o=root 559206999 559206999 IN IP4 xxx.66.8.22#015#012s= VoipSwitch#015#012c=IN IP4 xxx.66.8.22#015#012t=0 0#015#012m=audio 426 ...
Jul 20 18:33:10 proxy1 rtpengine[1321]: WARNING: [4424d42e0d13715344b2e201689d8c83@xxx]: ... 02 RTP/AVP 8 101#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-16#015#012a=ptime:20#015#012a=sendrecv#015#012a=rtcp:42603#015#012m=audio 0 RTP/AVP 8 96#015#0123:ICE6:remove7:replacel6:origin18:session-connectione7:call-id57:4424d42e0d13715344b2e201689d8c83@xxx13:received-froml3:IP411:xxx.66.8.22e8:from-tag10:as2b9f61a96:to-tag13:mD4N4Hg15Xm9Q7:command6:answere]

**Comment by rfuchs** [comment]
Ok, that could possibly be an extra m= line that shouldn't be there. Hard to say without seeing the corresponding offer.

**Comment by nicoonline** [comment]
Offer is :

v=0
o=root 1762535573 1762535574 IN IP4 xxx.171.20.203
s=xxx
c=IN IP4 xxx.171.20.203
t=0 0
m=audio 41950 RTP/AVP 8 101
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=maxptime:150
a=sendrecv



De : Richard Fuchs <notifications@github.com>
Envoyé : lundi 22 juillet 2019 17:32
À : sipwise/rtpengine <rtpengine@noreply.github.com>
Cc : Nicolas Breuer <Nicolas.Breuer@belcenter.biz>; State change <state_change@noreply.github.com>
Objet : Re: [sipwise/rtpengine] Error from RTPEngine. (#815)


Ok, that could possibly be an extra m= line that shouldn't be there. Hard to say without seeing the corresponding offer.

**Comment by rfuchs** [comment]
No, that explains is already. The answer had two m= lines while the offer only had one. That's invalid as per the RFC.

**Comment by nicoonline** [comment]
Thanks Richard !
