### ISSUE TITLE
[Question] How to prevent answer from changing a:setup=active to holdconn

### ISSUE THREAD

**Issue by space88man** [sipwise/rtpengine#819]
I am testing rtpengine mr7.4.1.1 between two Firefox browsers. When processing the answer:
Incoming SDP
a=setup:active

Rewritten SDP
a=setup:holdconn

but Firefox doesn't like holdconn: Description has illegal setup attribute "holdconn" in m-section at level 0.

Can we prevent rtpengine from changing the a=setup attribute?

**Comment by rfuchs** [comment]
`holdconn` is only used if setup is neither active nor passive, which shouldn't happen. Post a full log for this?

**Comment by space88man** [comment]
Sorry for the noise: it was a bug in my NGCP commands sent to rtpengine.

**Comment by daaaanil81** [comment]
> Sorry for the noise: it was a bug in my NGCP commands sent to rtpengine.
Please say me, which it was a bug? Because I have this problem.

**Comment by daaaanil81** [comment]
Help me please with this problem: How to prevent answer from changing a:setup=active to holdconn
