### ISSUE TITLE
ERR: SRTCP output wanted, but no crypto suite was negotiated

### ISSUE THREAD

**Issue by hamidrhashmi** [sipwise/rtpengine#820]
I am trying to configure SRTP but #A (MicroSIP) ends the call immediately when #B answers the call.  and on #A it shows error 488 Not Acceptable. 

![image](https://user-images.githubusercontent.com/14875110/61806884-f1926d00-ae51-11e9-8d1f-c3673f107679.png)

**ERR: SRTCP output wanted, but no crypto suite was negotiated**

Please find the RTPEngine logs. (Level 7) i have also tried ```rtcp-mux-offer``` and ```SDES-no```(https://github.com/sipwise/rtpengine/issues/450#issuecomment-363409241) but no success. 
[RTPEngine_rtcpmux_SDES-off.txt](https://github.com/sipwise/rtpengine/files/3427514/RTPEngine_rtcpmux_SDES-off.txt)

**Comment by rfuchs** [comment]
Looks like the answer from B (200 OK with SDP) is passed to rtpengine as an `offer` instead an `answer`. This is an error in your Kamailio script.

**Comment by hamidrhashmi** [comment]
I am using RTPengine Manage function. It works fine without SRTP.  I will change it to Answer and let you know.

**Comment by hamidrhashmi** [comment]
Yes, This worked when I explicitly called answer instead of manage function.
