### ISSUE TITLE
debian Unmet build dependencies: debhelper-compat (= 12)

### ISSUE THREAD

**Issue by juha-h** [sipwise/rtpengine#825]
Commit https://github.com/sipwise/rtpengine/commit/2868fc6f559fe0996b2f0f96c4266f42d949b8c3 changed Debian build dependency from debhelper (>= 5) to  debhelper-compat (= 12).  The issue is that debhelper-compat package does not exist in Debian stable (Buster) ror old stable (Stretch).

**Comment by reguluskinglet** [comment]
Same issue.

**Comment by linuxmaniac** [comment]
debhelper-compat is provided by debhelper package

https://packages.debian.org/source/stable/debhelper

```
 vseva@debnuc  ~/Foehn  apt-cache show debhelper
Package: debhelper
Version: 12.1.1
Installed-Size: 1609
Maintainer: Debhelper Maintainers <debhelper@packages.debian.org>
Architecture: all
Replaces: dh-systemd (<< 1.38)
Provides: debhelper-compat (= 9), debhelper-compat (= 10), debhelper-compat (= 11), debhelper-compat (= 12), dh-sequence-dwz, dh-sequence-installinitramfs, dh-sequence-systemd
Depends: autotools-dev, dh-autoreconf (>= 17~), dh-strip-nondeterminism (>= 0.028~), dpkg (>= 1.18.0~), dpkg-dev (>= 1.18.2~), dwz, file (>= 3.23), libdpkg-perl (>= 1.17.14), man-db, po-debconf, perl
Suggests: dh-make
Breaks: cmake (<< 3.9~), dh-systemd (<< 1.38), meson (<< 0.40.0~)
Description-en: helper programs for debian/rules
 A collection of programs that can be used in a debian/rules file to
 automate common tasks related to building Debian packages. Programs
 are included to install various files into your package, compress
 files, fix file permissions, integrate your package with the Debian
 menu system, debconf, doc-base, etc. Most Debian packages use debhelper
 as part of their build process.
Description-md5: c3d35229c1ce392f77324206e097b92e
Multi-Arch: foreign
Tag: devel::buildtools, devel::debian, devel::packaging,
 implemented-in::perl, interface::commandline, role::program,
 scope::utility, suite::debian, works-with::software:source
Section: devel
Priority: optional
Filename: pool/main/d/debhelper/debhelper_12.1.1_all.deb
Size: 1015864
MD5sum: 96dbab538a607b8fb6f1e29ba7dc4bf7
SHA256: e61d34665cd26876ab86f998062e6d6b227c9cac96acd48ae36da8cd3811a57f
```

**Comment by juha-h** [comment]
Victor Seva writes:

> debhelper-compat is provided by debhelper package
> 
> https://packages.debian.org/source/stable/debhelper

Yes, but should rtpengine dependency then be on debhelper package?

**Comment by linuxmaniac** [comment]
> Yes, but should rtpengine dependency then be on debhelper package?

No according to the documentation: https://manpages.debian.org/testing/debhelper/debhelper.7.en.html#Supported_compatibility_levels

> In current debhelper, you can specify the compatibility level in debian/control by adding a Build-Depends on the debhelper-compat package. For example, to use v12 mode, ensure debian/control has:  Build-Depends: debhelper-compat (= 12)
> This also serves as an appropriate versioned build dependency on a sufficient version of the debhelper package, so you do not need to specify a separate versioned build dependency on the debhelper package unless you need a specific point release of debhelper (such as for the introduction of a new feature or bugfix within a compatibility level).

**Comment by juha-h** [comment]
OK.  It turned out that pbuilder automatically installed debhelper:
```
dpkg: pbuilder-satisfydepends-dummy: dependency problems, but configuring anyway as you requested:
 pbuilder-satisfydepends-dummy depends on debhelper-compat (= 12); however:
  Package debhelper-compat is not installed.

Setting up pbuilder-satisfydepends-dummy (0.invalid.0) ...
Reading package lists...
Building dependency tree...
Reading state information...
Initializing package states...
Writing extended state information...
Building tag database...
pbuilder-satisfydepends-dummy is already installed at the requested version (0.invalid.0)
pbuilder-satisfydepends-dummy is already installed at the requested version (0.invalid.0)
The following NEW packages will be installed:
  debhelper{a} dh-autoreconf{a} dh-strip-nondeterminism{a} 
```
