### ISSUE TITLE
Rtpengine won't compile on RHEL7, but does on Centos 7

### ISSUE THREAD

**Issue by githubsw** [sipwise/rtpengine#827]
Hello,

Rtpengine will not compile on RHEL 7, I get the error => Can't locate IPC/Cmd.pm in @INC.  and I can't seem to get the correct required libraries.  Does anyone know what I could be missing?  As a side note, it compiles fine on Centos 7.  I verified that the Perl version is the same on both servers.

Thank you

**Comment by rfuchs** [comment]
Possible solution: https://unix.stackexchange.com/questions/447929/rhel-7-4-moreutils-dependency-on-perl-ipcrun

**Comment by rfuchs** [comment]
Otherwise install via cpan

**Comment by rfuchs** [comment]
Cleaning up old tickets
