### ISSUE TITLE
RTP SSRC Multiplexing support

### ISSUE THREAD

**Issue by isuruanu** [sipwise/rtpengine#83]
This is more of a suggestion. 

My main concern related to firewall rules to allow multiple UDP ports to connect from internet. Firewall will allow maximum 3,4 port for rtpengine to allow rtp entity to stream. 

I have went through
https://tools.ietf.org/html/draft-peterson-rosenberg-avt-rtp-ssrc-demux-00#page-4

There is a suggested way to multiplex multiple rtp session to (I only need RTP voice) two ports rtp-voice, and rtpc-voice ports. This is RTP SSRC multiplexing approach.  

Can rtpengine comply with this. ?

**Comment by rfuchs** [comment]
As an RTP proxy, rtpengine isn't meant to be run behind NAT or behind a restrictive firewall. You need a properly accessible address. Right now, the SSRC isn't even looked at, and while it may be used to distinguish multiple sources appearing on the same port (as it can happen after a forked call), we won't support any more multiplexing than this, and especially not this draft, as it requires support from the endpoints as well.
