### ISSUE TITLE
Invalid RTT - discarding - does this drop rtp packet?

### ISSUE THREAD

**Issue by nhadzter** [sipwise/rtpengine#835]
Hi newbie here, we have a SIP server and there are random drop of RTP mid-conversation.
one side just all of sudden just stop sending RTP so the other side don't hear anything.

I'm a loss at how to troubleshoot as maybe this is caused by the CPE as RTP drops from that end. from DEBUG log i "Invalid RTT" just wondering what that is for and if that does drop the packet, or is there any other component on rtpengine that drops it?

**Comment by rfuchs** [comment]
"Invalid RTT" relates to the roundtrip time calculated from RTCP packets. It's used for MOS calculation. It doesn't mean that any packets were dropped.

You should probably look at Wireshark traces to see if it's the CPE that stops sending RTP, or if it's rtpengine that stops forwarding it.

**Comment by nhadzter** [comment]
thank you. based on traffic capture it was the CPE dropping RTP.
