### ISSUE TITLE
rtp ports are not freed after rtpengine delete if used "via-branch" parameter

### ISSUE THREAD

**Issue by vance-od** [sipwise/rtpengine#840]
hi there!

we have an issue in following case:
- incoming call to WebRTC endpoint, user B (rtpengine offer)
- user A cancel the call 
A => CANCEL => B
A <= 487 <= B --- here we do rtpengine delete
as a result in logs I see that the dialog is removed, but allocated ports are not freed

later ports are freed via a timeout in 1 hour

Making some research I found out that the difference  in working and non working case is "via-branch" parameter
If in offer/delete I do not specify "via-branch" - than ports are freed in correct way

log of call with netstat output is here: https://pastebin.com/pbyTJdZm

rtpengine -v
Version: 7.0.1.1+0~mr7.0.1.1

any ideas, is it some misuse or I did something wrong?

thanks in advance for the help!

regards, Vasiliy

**Comment by rfuchs** [comment]
Hm yes, looks like in this case (no to-tag but via-branch present) the logic is reversed, i.e. the delete is seen to be coming from the opposite side. I don't think that's correct.

**Comment by vance-od** [comment]
many thanks for the fix, Richard!

checked the patch and confirm that the issue is no longer reproduced in my setup
