### ISSUE TITLE
Media packets are being dropped after SDES negotiation

### ISSUE THREAD

**Issue by rajmohanb** [sipwise/rtpengine#842]
The scenario involves bridging unencrypted rtp on one end and sending encrypted media to the other end using SDES. When srtp is enabled and sdes is used for encryption, the negotiation seems to succeed because rtpengine sends out a modified answer. After rtpengine receives answer and processes it, it assigns the crypto params for media encryption and returns modified answer. But packets received later are dropped and the error shown is 

"[1567672066.883626] ERR: [1-106895@10.198.161.110 port 30023]: SRTCP output wanted, but no crypto suite was negotiated".

Please see the attached log which contains the offer-answer details.

[sdes_logs.txt](https://github.com/sipwise/rtpengine/files/3589046/sdes_logs.txt)

**Comment by rfuchs** [comment]
This is because the original offer is in `RTP/AVP` (no SRTP), but in the answer rtpengine is instructed to translate to `"transport protocol": "RTP/SAVP"`. This is a usage error as this protocol doesn't match what was in the offer.

**Comment by rajmohanb** [comment]
My bad, thanks for pointing out the usage error. Please close this ticket.
