### ISSUE TITLE
spaces at lines end in config file, errors

### ISSUE THREAD

**Issue by gmaruzz** [sipwise/rtpengine#843]
eg (config file):
         interface = internal/192.168.1.130;external/192.168.1.131

if there are spaces at line end (eg, after 131), gives error:

        rtpengine[603]: CRIT: Fatal error: Invalid interface specification: 'external'

( very confusing, indeed ;) )

**Comment by arsperger** [comment]
Just got the same in docker trying to run rtpengine with arguments. Giovanni, saved my day with this post :)
