### ISSUE TITLE
Command line options are removed from readme file.

### ISSUE THREAD

**Issue by tiglat** [sipwise/rtpengine#846]
Hello. 

I lost description of command line options of daemon which were presented inside readme in release 5.0.2 for example. 
Could you please tell me where can I find this description?
Thank you

**Comment by rfuchs** [comment]
They've been moved to the man page is installed as `rtpengine(8)` as part of the Debian packaging.

https://github.com/sipwise/rtpengine/blob/master/daemon/rtpengine.pod
