### ISSUE TITLE
Fail to build on Ubuntu Bionic

### ISSUE THREAD

**Issue by farmorg** [sipwise/rtpengine#847]
Hello

I'm trying to build RTPengine on Ubuntu Server (Bionic) but both mr7.5.1.2 (from tarball) & mr8.0 (fresh clone from git) fail to build:

dpkg-buildpackage -d
dpkg-buildpackage: info: source package ngcp-rtpengine
dpkg-buildpackage: info: source version 8.0.0.0+0~mr8.0.0.0
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Sipwise Jenkins Builder <jenkins@sipwise.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build rtpengine
dpkg-source: info: using options from rtpengine/debian/source/options: --extend-diff-ignore=.gitreview
 debian/rules clean
dh clean
dh: Compatibility levels before 5 are no longer supported (level 1 requested)
debian/rules:25: recipe for target 'clean' failed
make: *** [clean] Error 2
dpkg-buildpackage: error: debian/rules clean subprocess returned exit status 2

------------

dpkg-buildpackage -d
dpkg-buildpackage: info: source package ngcp-rtpengine
dpkg-buildpackage: info: source version 7.5.1.2+0~mr7.5.1.2
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Sipwise Jenkins Builder <jenkins@sipwise.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build rtpengine-mr7.5.1.2
dpkg-source: info: using options from rtpengine-mr7.5.1.2/debian/source/options: --extend-diff-ignore=.gitreview
 debian/rules clean
dh clean
dh: Compatibility levels before 5 are no longer supported (level 1 requested)
debian/rules:25: recipe for target 'clean' failed
make: *** [clean] Error 2
dpkg-buildpackage: error: debian/rules clean subprocess returned exit status 2

--------

My server details:

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

Does anyone know how to fix this please? I don't have or need G.722 support - hence the -d and I removed the dependency on debhelper-compat in debian/control so dpkg-checkbuilddeps completes without error.

Many thanks

**Comment by rfuchs** [comment]
Well, the debhelper-compat dependency specifies the compatibility level (12), so removing it makes it revert to 1, which is wrong. You probably need the debhelper and debhelper-compat package from the bionic-backports repo.

**Comment by farmorg** [comment]
Thanks very much for the reply. It was almost right, I needed to add the back ports repo and force the upgrade:

apt install -t bionic-backports debhelper

Hope this helps someone else.
