### ISSUE TITLE
invoke-rc.d missing --skip-systemd-native (Ubuntu Bionic)

### ISSUE THREAD

**Issue by farmorg** [sipwise/rtpengine#848]
Good morning

Now that I've got the build working, the install fails with the following error:

Unpacking ngcp-rtpengine-utils (8.0.0.0+0~mr8.0.0.0) ...
Setting up ngcp-rtpengine-daemon (8.0.0.0+0~mr8.0.0.0) ...
invoke-rc.d: syntax error: unknown option "--skip-systemd-native"
dpkg: error processing package ngcp-rtpengine-daemon (--install):
 installed ngcp-rtpengine-daemon package post-installation script subprocess returned error exit status 1

This happens for all of the various .deb packages.

Google suggests that the --skip-systemd-native option was removed from upstream Debian.

I have tried editing the source code to remove all of the --skip-systemd-native entries and also in the install files in /var/lib/dpkg/info/ngcp* but weirdly they seem to reappear in the install files when I run dpkg-buildpackage.

The resulting package states:

dpkg -l | grep -i ngcp
iU  ngcp-rtpengine                        8.0.0.0+0~mr8.0.0.0                        all          NGCP RTP/media proxy - meta package
iF  ngcp-rtpengine-daemon                 8.0.0.0+0~mr8.0.0.0                        amd64        proxy for RTP and media streams used in NGCP, userspace part
ii  ngcp-rtpengine-iptables               8.0.0.0+0~mr8.0.0.0                        amd64        IPtables extension module for the kernel-space NGCP media proxy
ii  ngcp-rtpengine-kernel-dkms            8.0.0.0+0~mr8.0.0.0                        all          IPtables kernel module for the NGCP media proxy - DKMS
ii  ngcp-rtpengine-kernel-source          8.0.0.0+0~mr8.0.0.0                        all          IPtables kernel module for the NGCP media proxy - source
iF  ngcp-rtpengine-recording-daemon       8.0.0.0+0~mr8.0.0.0                        amd64        recording daemon for RTP and media streams
ii  ngcp-rtpengine-utils                  8.0.0.0+0~mr8.0.0.0                        all          scripts and Perl modules for NGCP rtpengine

**Comment by rfuchs** [comment]
Have you tried with `init-system-helpers` from Bionic backports?

**Comment by farmorg** [comment]
Thankyou, that solved it.

**Comment by guss77** [comment]
I had the same problem, solved it by adding the file `/etc/apt/preferences.d/init-system-helpers` with the content:

```
Package: init-system-helpers
Pin: release a=bionic-backports
Pin-Priority: 500
```

And then an update installed the required package.

This also works well in cloud-init with `package_upgrade: true` - the upgrade process updates `init-system-helpers`, then when the `packages` module installs RTPEngine, everything is already prepared.

**Comment by lawensong** [comment]
> I had the same problem, solved it by adding the file `/etc/apt/preferences.d/init-system-helpers` with the content:
> 
> ```
> Package: init-system-helpers
> Pin: release a=bionic-backports
> Pin-Priority: 500
> ```
> 
> And then an update installed the required package.
> 
> This also works well in cloud-init with `package_upgrade: true` - the upgrade process updates `init-system-helpers`, then when the `packages` module installs RTPEngine, everything is already prepared.

yeah.  It is work for me

**Comment by prashantinfi** [comment]
```
sudo apt-get install init-system-helpers
sudo apt update
```

Running this worked for me!
