### ISSUE TITLE
Rtp-Recording Filename

### ISSUE THREAD

**Issue by nicoonline** [sipwise/rtpengine#849]
Hello,
We installed the RTP-Recording feature on our server.

Is it the RTP-Recording who's taking care of the file-naming ?

Filename of audio recording is : 616e6101526cdfec37b98f1e7a3f14f8%40
Is there a way to convert the %40 to the @ char ?

**Comment by rfuchs** [comment]
This is intentional. The file names are based on the call ID but they're URI escaped to protect from unintended interactions with the file system.

**Comment by nicoonline** [comment]
Putting this code in a html form seems doesn't works.
<audio controls src="data/voice/wav/6b169d5817cc589012bb2dac73b5ff00%40XXXX-a6eb081f10cf7442-mix.wav" type="audio/wav"> </audio>

**Comment by nicoonline** [comment]
i try to listen the audio file with our webserver. It works perfectly when there is no @ in the name.
Seems the web-server transforms the %40 to a "@" but the file doesn't contains the "@" so it returns a "404"

**Comment by rfuchs** [comment]
Ok I can't really help you with the setup of your web services. But since the file name contains a literal `%` you probably have to URI escape that, turning `%40` in the file name into `%2540`
