### ISSUE TITLE
UNAUTHENTICATED_SRTP support

### ISSUE THREAD

**Issue by alexcme** [sipwise/rtpengine#85]
Is it visible to support UNAUTHENTICATED_SRTP ? Or it is intentionally not supported ?

**Comment by rfuchs** [comment]
Are you talking about the SDES tag from RFC 4568?

**Comment by alexcme** [comment]
Yes, the one when only RTCP has to be authenticated

**Comment by rfuchs** [comment]
Session parameters aren't supported right now, because I haven't seem them used in any client yet. But there's no reason why it couldn't be supported.

**Comment by alexcme** [comment]
That would be nice as we have a lot of such clients

**Comment by rfuchs** [comment]
Try with 9c7e1df applied (branch `rfuchs/sdes-session-params`), let me know how that works.

**Comment by alexcme** [comment]
Just found we still on CentOS 6.5 and having trouble compiling the code (still can't find how others were able to use required glibc). Upgrading to CentOS 7, will test and update.

**Comment by alexcme** [comment]
Perfect, it works when we receive an offer with UNAUTHENTICATED_SRTP. Can we have a flag to generate the same when we pass SAVPF (DTLS) - > SAVP (SDES) for bridging?

**Comment by rfuchs** [comment]
Take a look at the code in branch `rfuchs/sdes-session-params` especially the README, as it contains the info on how to use the flags that you want.
