### ISSUE TITLE
When offer has a transcodeable codec with a dynamic payload type, rtpenging relays packets without recoding payload type

### ISSUE THREAD

**Issue by guss77** [sipwise/rtpengine#851]
rtpengine version: 6.4.1.1

I have rtpengine configured to mask all codecs from side A and transcode just Opus towards side B. This works very well if side A doesn't offer Opus. But if side A offers Opus, rtpengine will not transcode and just relay the packets (which is the expected behavior), but it will not update the payload type field in the relayed packets - so that side A uses a different dynamic payload type than what rtpengine decided to use (it always uses 96 as it is the only codec offered) then the RTP recipient on side B will get RTP packets with an unknown payload type and will ignore them.

Setting `always transcode` works around the problem, but I would prefer not needing to transcode Opus to Opus.

I'm aware that 6.4.1.1 is an old version and this problem may have been fixed in newer versions, but after searching I haven't seen another similar issue reported in the past.

Please let me know if there's a better (i.e. doesn't cause unneeded transcoding) workaround and if there is a fix in a more recent versions.

**Comment by guss77** [comment]
Actually, I did set `always transcode` and thought it worked before, but now it doesn't - so here's a pcap trace of the problem:

[rtpengine-relay-wront-pt.pcapng.gz](https://github.com/sipwise/rtpengine/files/3648017/rtpengine-relay-wront-pt.pcapng.gz)

In the trace we can see SIP call `pm9Nrnk.vNgs5TnRqEE4dlt0Zhy1BLG7` from `109.226.52.34` through a Kamailio SIP proxy shown in the trace as `172.24.51.7` (it is behind a 1-to-1 NAT) relayed to `172.24.41.56`, using the rtpengine at `3.8.44.129` as a media relay and transcoder (this machine is shown later in the trace as `172.28.11.218` - it is also behind a 1-to-1 NAT).

When the session starts, the MUA invites, and Kamailio issues `offer`:

```
d3:sdp356:v=0
o=- 3778327632 3778327632 IN IP4 109.226.52.34
s=pjmedia
b=AS:84
t=0 0
a=X-nat:0 Unknown
m=audio 28616 RTP/AVP 120 0 96
c=IN IP4 109.226.52.34
b=TIAS:64000
a=rtcp:28617 IN IP4 172.18.4.200
a=sendrecv
a=rtpmap:120 opus/48000/2
a=rtpmap:0 PCMU/8000
a=rtpmap:96 telephone-event/8000
a=fmtp:96 0-16
a=ssrc:1736154542 cname:474fba76435abd8d
3:ICE6:remove5:flagsl16:always-transcodee7:replacel6:origine5:codecd4:maskl3:alle9:transcodel4:opuse5:offerl15:telephone-evente5:stripl15:telephone-eventee7:call-id32:pm9Nrnk.vNgs5TnRqEE4dlt0Zhy1BLG713:received-froml3:IP413:109.226.52.34e8:from-tag32:6geyOwh4kJVLzGIMHqUT.jIddelsi3bK7:command5:offere
```

rtpengine replies:

```
d3:sdp304:v=0
o=- 3778327632 3778327632 IN IP4 3.8.44.129
s=pjmedia
b=AS:84
t=0 0
a=X-nat:0 Unknown
m=audio 36784 RTP/AVP 96 97
c=IN IP4 3.8.44.129
b=TIAS:64000
a=ssrc:1736154542 cname:474fba76435abd8d
a=rtpmap:96 telephone-event/8000
a=rtpmap:97 opus/48000/2
a=fmtp:96 0-16
a=sendrecv
a=rtcp:36785
6:result2:oke
```

As you can see, we asked to transcode everything to Opus, the MUA offered Opus with PT=120 and we got a reply SDP with Opus at PT=96. This should be OK, but looking at the RTP packets after the setup completes, we can see that the RTP packets from the MUA (`109.226.52.34:28616`) to rtpengine (`172.28.11.218:36802`) are Opus with PT=120 and the packets relayed out from rtpengine (`172.28.11.218:36784`) to the recipient (`18.191.232.30:10874`) are Opus - again with PT=120 **even though the offer reply's SDP promise PT=97**.

**Comment by rfuchs** [comment]
So this is actually due to the fact that codecs removed through `mask` are not restored through `transcode`. In other words, if you `mask` the Opus entry, and then `transcode` to Opus, rtpengine will create a new Opus codec entry with a new payload type, and not re-use the one that was removed by `mask`.

I assume you expect that `mask` plus `transcode` to the same entry will restore the entry that was removed by `mask`?

**Comment by guss77** [comment]
I read a few places that using `transcode` after `mask` or `strip` "restores" the codec, but that likely have been interpretations of observed behavior and not actual understanding. 

I actually expect that `transcode=opus` would transcode opus to opus, if not by default then with `always transcode` set, but it doesn't. I would have been OK with getting the "`mask` and `transcode` on the same codec causes to just relay without transcoding" behavior, but that's not what happening either:

RTPEngine negotiates a new payload type as if it is about to transcode, but then just relays the packets without modification - not even the payload type field.

**Comment by rfuchs** [comment]
Yeah, so `strip` (especially `strip=all`) plus either `transcode` or `offer` will do what you describe: restore the removed codec back into the offer. But this doesn't work with `mask` (instead of `strip`) because `mask` removes the codec only unidirectionally. It could be implemented if there was a use case for it, but right now this isn't supported. So what happens instead is that `mask` removes the codec on one side, and then `transcode` adds a new instance (of the same codec) on the other side. So you get different payload types.

I do believe that a newer version fixes what you're seeing because at some point there was a change from matching codecs based on codec names (which isn't correct in all cases) to matching codecs based on payload type numbers. Please try and confirm.

**Comment by guss77** [comment]
I will try with 7.5. I'll update.

**Comment by guss77** [comment]
OK, so as far as I understand, `mask` removes the codec while `strip` just "hides" the codec.

I still think there is a broken behavior here, and its like this: Supposed the two sides are talking Opus, and I `mask` Opus in the configuration. Then rtpengine will negotiate Opus on both sides of the session, but - because its the same codec, it will not transcode (unless `always transcode` is specified, which is one work around) and just relay, but because it negotiated "different codecs" on either side, it will use different payload types. Then when it relays the packets, it will not do anything to the packet being relayed, not even update the payload type.

This configuration, which on the face of it looks valid, causes a broken session, and I do believe updating the RTP payload type during relay (without transocoding) is easy, cheap and **correct**.

That being said, replacing `mask` with `strip` is also a workaround for the problem and doesn't require transcoding. I think that there may be a use case where `mask` is actually required and then none of the workarounds would be valid, but I don't understand enough of the problem space and I can't think of such a use case now.

Verified with rtpengine versions 7.5.2.1 and 6.4.1.1

**Comment by guss77** [comment]
> OK, so as far as I understand, `mask` removes the codec while `strip` just "hides" the codec.

BTW - just looking at `mask` vs. `strip` as the meaning of the words in English, one might think that the behavior is the reverse: `mask` would hide the codec from negotiation but leave it available for relay while `strip` would remove the codec. This probably added to my confusion about all of this.

**Comment by rfuchs** [comment]
No you actually got it right. `strip` does remove the codec entirely and `mask` only hides it but makes it available for use towards A.

**Comment by guss77** [comment]
> `strip` does remove the codec entirely and `mask` only hides it but makes it available for use towards A.

hmm... but ...

> So this is actually due to the fact that codecs removed through `mask` are not restored through `transcode`. In other words, if you `mask` the Opus entry, and then `transcode` to Opus, rtpengine will create a new Opus codec entry with a new payload type, and not re-use the one that was removed by `mask`.

So... `mask` removes the codec so it can't be restored - if we negotiate the same codec, we are actually getting a new instance, while `strip` removes the codec in a way that *can* be restored (just hiding it), so that if we offer/transcode to the same codec, we are using the original ("stripped") codec. That seems to work well, though again: a bit confusing.

**Comment by rfuchs** [comment]
No you misunderstand. A codec removed with `strip` is not hidden. It's removed entirely. The exception is that if `offer` is used on the same codec (only really makes sense with `strip=all`). In that case, the `strip` is reversed. This is the sole purpose of the `offer` option. The end result is that the codec is not stripped at all. The "hiding" you seem to see in this case only happens temporarily and internally during codec processing. But the end result is always either that the codec is removed entirely, or that it's left intact. Therefore, `strip`

A codec removed with `mask` is only removed from the B side, but left intact for the A side. Therefore, it's available to A but "hidden" (masked) towards B. Using `offer` or `transcode` to reverse this (as `offer` does with `strip`) is currently just not supported.

**Comment by guss77** [comment]
OK, I think I understand much better now, thank you.

What finally clicked for me was that in my setup (which is basically a proxy with lots of different codecs possible from A transcoded or relayed to a single supported codec on B), when setting `strip=all transcode={B-codec}`, the SDP in the reply back to A (183 and 200) always only offers "B-codec" regardless of what A used in the `INVITE`, while with `mask=all transcode={B-codec}`, the codec advertised in A's `INVITE` is offered in the reply.

So, I think we still have a problem. I'm going to run some more tests to get a clear reproduction, and this probably only manifests for Opus users (or at least that's the only codec I use, other than `telephone-events` that is a dynamic payload), but it goes something like this:

* I don't want to transcode needlessly - if A's invite has a codec B supports, I want to just relay it.
* I want to make sure that the reply to A's INVITE uses the codec(s) from A's INVITE (sometimes called symmetric payload negotiation?).
* I want to support a large range of codecs from A.

Now I'm running a scenario where A only likes "A-codec" (it may support others, but it only offers this one in the SDP) and B only works with "B-codec" (they are not the same codec):

1. If I set `strip=all transcode={B-codec}`, rtpengine transcodes from A to B, but offers "B-codec" in the reply to A - i.e. not symmetric (I think it does this because B's reply includes only "B-Codec").
2. If I set `mask=all transcode={B-codec}`, rtpengine transcodes from A to B, and correctly offers "A-codec" in the relay to A.
3. If I set `offer={B-codec}` (regardless of whether I used `strip` or `mask`, the SDP sent to B does not include any codec and the call fails - so obviously I can't use this configuration.

Now a different A `INVITE`s the same proxy with the same configuration and chooses the same codec a B (what we call "B-codec") in it's `INVITE`:

1. If I set `strip=all transcode={B-codec}`, rtpengine relays from A to B, including retaining the dynamic payload type, and offers the replied codec with its payload type in the reply to A - if A can handle the new payload type, then everything works, otherwise we may run into problems with an arguably non-compliant A.
2. If I set `mask=all transcode={B-codec}`, rtpengine relays from A to B but uses a new payload type, causing RTP with dynamic payload type to fail because B expects the new payload type and not A's payload type.

That means I can't handle both the "transcoding a non-compatible codec" scenario and "relaying a compatible codec" scenario in a single configuration - when "B-codec" uses a dynamic payload type and I can't verify that both A and B select the same payload type for the codec.

The current workarounds that I can think of are:
1. Never use a dynamic payload type codec for "B-codec" - i.e. avoid Opus.
2. Verify that both A and B always use the same payload type - which is very hard to do if you intend to support any SIP compatible client.
3. Don't use a static configuration: make the proxy smarter, so it can choose `strip` or `mask` on a per-call basis depending on what A `INVITE`d with - this may or may not be easy or feasible depending on what proxy software you use.

Or - fix this issue: make rtpengine rewrite the payload type when it relays RTP packets. :-)

**Comment by rfuchs** [comment]
> when setting `strip=all transcode={B-codec}`, the SDP in the reply back to A (183 and 200) always only offers "B-codec" regardless of what A used in the INVITE,

That's because `strip=all` without a subsequent `offer=...` is invalid as it leaves no codecs left that can be used towards A. Rtpengine recognises this situation and restores the full codec list from A so that the call can be established.

> I don't want to transcode needlessly - if A's invite has a codec B supports, I want to just relay it.

If you know what codec B supports ahead of time (and you want to talk that codec to B), you should make the flags used in the offer conditional on what's offered by A. If A already offers the codec you want to use towards B, use `strip=all offer=X`. If it doesn't, use `mask=all transcode=X`. (This can be extended further if you also want to use a particular codec towards A.)

> Don't use a static configuration: make the proxy smarter, so it can choose strip or mask on a per-call basis depending on what A INVITEd with - this may or may not be easy or feasible depending on what proxy software you use.

If your SIP proxy can't do that, use a different SIP proxy :)

> Or - fix this issue: make rtpengine rewrite the payload type when it relays RTP packets. :-)

No, that would not be correct. If you want to use the same codec on both sides without transcoding, then make sure the payload type is also the same. Anything else indicates a usage error.

**Comment by guss77** [comment]
> > Or - fix this issue: make rtpengine rewrite the payload type when it relays RTP packets. :-)
> 
> No, that would not be correct. If you want to use the same codec on both sides without transcoding, then make sure the payload type is also the same. Anything else indicates a usage error.

What you say here makes sense, except when using codecs that require dynamic-PT: we can't specify the PT to rtpengine, so it just chooses the next available dynamic PT when creating the B-side SDP and that is **very** likely not to be the correct PT for the RTP that A sends. rtpengine *must* make sure that when it relays RTP packets with dyamic-PT, the PT matches the PT it offered in the B-side SDP.

One simple way to do this (other than rewriting the RTP PT during relay, as I suggested above) is to create the SDP correctly: if the request SDP specifies that Opus is PT 120 (as in my second comment), and rtpengine decides to use Opus in the response SDP - then it should also use dynamic PT 120 for Opus in the response SDP.

**Comment by rfuchs** [comment]
> What you say here makes sense, except when using codecs that require dynamic-PT: we can't specify the PT to rtpengine, so it just chooses the next available dynamic PT when creating the B-side SDP and that is very likely not to be the correct PT for the RTP that A sends. rtpengine must make sure that when it relays RTP packets with dyamic-PT, the PT matches the PT it offered in the B-side SDP.

Yes, and it does that if the codec is passed through from A to B, in which case no transcoding happens. If you create a new instance of the codec, you will be transcoding and you will get a new PT.

**Comment by whyteks** [comment]
I just observed something that looks related to this. 

With codec-mask-all and codec-transcode-telephone-event, 

I'm seeing that the A leg INVITE has **a=rtpmap:101 telephone-event/8000** 
but the B leg INVITE has **a=rtpmap:97 telephone-event/8000**

When I send DTMF from the A origin, I see the telephone-event on the A leg, but on the B leg I see 
**RTP (Unassigned)**

I have not (yet) although I could capture the traffic and take a look at the rtp payload type header, but it would seem pretty likely here that rtpengine is either just passing the RTP or is using the wrong payload type header in on the B leg. 

Can telephone event be "transcoded" as such? 

Sorry, I have not done any code analysis yet on this.

**Comment by whyteks** [comment]
Ok, I just went through this thread, giving it more attention and I see the details of what's going on. thanks again to @rfuchs' concise explanations.

Conclusion then, BE VERY WARY of using mask=all when there are dynamic PTs in the mix. Especially something as subtle to miss as telephone-event.

Implementation of that kind of a use case requires extra conditions in the logic the proxy control commands to rtpengine. For anyone else looking here who uses kamailio, I think you probably would want the SDPOPS module here. If you've got something better, or examples, please post.

**Comment by rfuchs** [comment]
A pcap would be helpful if you see that the PT is coming out wrong. In general, yes telephone-event can (and in some cases must) be "transcoded" in such a way. I also do plan to improve the mask=all cases at some point, but haven't had a chance to do it yet.

**Comment by rfuchs** [comment]
Cleaning up old tickets
