### ISSUE TITLE
Installation on Debian 10 fails

### ISSUE THREAD

**Issue by sashasaturn** [sipwise/rtpengine#853]
Hi all,
The kernel module installation (module-assistant auto-install ngcp-rtpengine-kernel-source
 )fails on fresh Debian 10 with the following error

│   CC      /usr/src/modules/ngcp-rtpenginxt_RTPENGINE.mod.o
│   LD [M]  /usr/src/modules/ngcp-rtpengine/xt_RTPENGINE.ko                                                                                             
│ make[3]: Leaving directory '/usr/src/linux-headers-4.19.0-6-amd64'                                                                                    
│ make[2]: Leaving directory '/usr/src/modules/ngcp-rtpengine'                                                                                          
│ # Install the module                                                                                                                                  
│ install -D -m 0644 xt_RTPENGINE.ko                                                                                                                    
│ debian/ngcp-rtpengine-kernel-modules-4.19.0-6-amd64/lib/modules/4.19.0-6-a                                                                            
│ md64/extra/xt_RTPENGINE.ko                                                                                                                            
│ dh_installdocs                                                                                                                                        
│ dh_installdocs: Please specify the compatibility level in debian/compat                                                                               
│ make[1]: *** [debian/rules:64: binary-modules] Error 2                                                                                                
│ make[1]: Leaving directory '/usr/src/modules/ngcp-rtpengine'                                                                                          
│ make: *** [/usr/share/modass/include/common-rules.make:56: kdist_build]

**Comment by rfuchs** [comment]
Can you post a full log, so we can see what you were doing?

**Comment by juha-h** [comment]
Install works OK on my Debian 10.

**Comment by mika** [comment]
@sashasaturn what's the output of `dpkg --list debhelper` on your (build) system? Does this match version `12.1.1`?

**Comment by sashasaturn** [comment]
@mika  sorry for a delay.

I had a debhelper issue on Debian 9, thats why I decided to switch to Debian 10


dpkg --list debhelper
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  debhelper      12.1.1       all          helper programs for debian/rules

I will provide full log during the next day or two

Thank you for your patience!

**Comment by sashasaturn** [comment]
@rfuchs  please see detailed log ....

**lsb_release -a**
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

**uname -a** 
Linux server 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux

**apt install git

mkdir /opt/rtpengine

cd /opt/rtpengine

git clone https://github.com/sipwise/rtpengine.git .

export DEBIAN_FRONTEND=noninteractive 

export DEB_BUILD_PROFILES="pkg.ngcp-rtpengine.nobcg729"

apt-get update -qqy 

mkdir -p ./debian/flavors 

touch ./debian/flavors/no_ngcp 

apt install -qqy apt-utils dpkg-dev debhelper iptables iptables-dev libcurl4-openssl-dev libglib2.0-dev libavcodec-extra libhiredis-dev libpcre3-dev libssl-dev libxmlrpc-core-c3-dev markdown zlib1g-dev module-assistant dkms gettext  default-libmysqlclient-dev gperf libavcodec-dev libavfilter-dev libavformat-dev libavutil-dev  libbencode-perl libcrypt-openssl-rsa-perl libcrypt-rijndael-perl libdigest-crc-perl libdigest-hmac-perl libevent-dev libio-multiplex-perl libio-socket-inet6-perl libjson-glib-dev libnet-interface-perl libpcap0.8-dev libsocket6-perl libswresample-dev libsystemd-dev nfs-common netcat-openbsd netcat  unzip libspandsp-dev**

 **apt install -y linux-headers-$(uname -r) linux-image-$(uname -r)**

Reading package lists... Done
Building dependency tree
Reading state information... Done
linux-headers-4.19.0-6-amd64 is already the newest version (4.19.67-2+deb10u1).
linux-headers-4.19.0-6-amd64 set to manually installed.
linux-image-4.19.0-6-amd64 is already the newest version (4.19.67-2+deb10u1).
linux-image-4.19.0-6-amd64 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**dpkg-checkbuilddeps**


**dpkg-buildpackage -b -us -uc**


**dpkg -i ../*.deb**
Selecting previously unselected package ngcp-rtpengine.
(Reading database ... 58862 files and directories currently installed.)
Preparing to unpack .../ngcp-rtpengine_8.0.0.0+0~mr8.0.0.0_all.deb ...
Unpacking ngcp-rtpengine (8.0.0.0+0~mr8.0.0.0) ...
Selecting previously unselected package ngcp-rtpengine-daemon.
Preparing to unpack .../ngcp-rtpengine-daemon_8.0.0.0+0~mr8.0.0.0_amd64.deb ...
Unpacking ngcp-rtpengine-daemon (8.0.0.0+0~mr8.0.0.0) ...
Selecting previously unselected package ngcp-rtpengine-daemon-dbgsym.
Preparing to unpack .../ngcp-rtpengine-daemon-dbgsym_8.0.0.0+0~mr8.0.0.0_amd64.deb ...
Unpacking ngcp-rtpengine-daemon-dbgsym (8.0.0.0+0~mr8.0.0.0) ...
Selecting previously unselected package ngcp-rtpengine-iptables.
Preparing to unpack .../ngcp-rtpengine-iptables_8.0.0.0+0~mr8.0.0.0_amd64.deb ...
Unpacking ngcp-rtpengine-iptables (8.0.0.0+0~mr8.0.0.0) ...
Selecting previously unselected package ngcp-rtpengine-iptables-dbgsym.
Preparing to unpack .../ngcp-rtpengine-iptables-dbgsym_8.0.0.0+0~mr8.0.0.0_amd64.deb ...
Unpacking ngcp-rtpengine-iptables-dbgsym (8.0.0.0+0~mr8.0.0.0) ...
Selecting previously unselected package ngcp-rtpengine-kernel-dkms.
Preparing to unpack .../ngcp-rtpengine-kernel-dkms_8.0.0.0+0~mr8.0.0.0_all.deb ...
Unpacking ngcp-rtpengine-kernel-dkms (8.0.0.0+0~mr8.0.0.0) ...
Selecting previously unselected package ngcp-rtpengine-kernel-source.
Preparing to unpack .../ngcp-rtpengine-kernel-source_8.0.0.0+0~mr8.0.0.0_all.deb ...
Unpacking ngcp-rtpengine-kernel-source (8.0.0.0+0~mr8.0.0.0) ...
Selecting previously unselected package ngcp-rtpengine-recording-daemon.
Preparing to unpack .../ngcp-rtpengine-recording-daemon_8.0.0.0+0~mr8.0.0.0_amd64.deb ...
Unpacking ngcp-rtpengine-recording-daemon (8.0.0.0+0~mr8.0.0.0) ...
Selecting previously unselected package ngcp-rtpengine-recording-daemon-dbgsym.
Preparing to unpack .../ngcp-rtpengine-recording-daemon-dbgsym_8.0.0.0+0~mr8.0.0.0_amd64.deb ...
Unpacking ngcp-rtpengine-recording-daemon-dbgsym (8.0.0.0+0~mr8.0.0.0) ...
Selecting previously unselected package ngcp-rtpengine-utils.
Preparing to unpack .../ngcp-rtpengine-utils_8.0.0.0+0~mr8.0.0.0_all.deb ...
Unpacking ngcp-rtpengine-utils (8.0.0.0+0~mr8.0.0.0) ...
Setting up ngcp-rtpengine-daemon (8.0.0.0+0~mr8.0.0.0) ...
Created symlink /etc/systemd/system/rtpengine.service → /lib/systemd/system/ngcp-rtpengine-daemon.service.
Created symlink /etc/systemd/system/multi-user.target.wants/ngcp-rtpengine-daemon.service → /lib/systemd/system/ngcp-rtpengine-daemon.service.
Job for ngcp-rtpengine-daemon.service failed because the control process exited with error code.
See "systemctl status ngcp-rtpengine-daemon.service" and "journalctl -xe" for details.
Setting up ngcp-rtpengine-daemon-dbgsym (8.0.0.0+0~mr8.0.0.0) ...
Setting up ngcp-rtpengine-iptables (8.0.0.0+0~mr8.0.0.0) ...
Setting up ngcp-rtpengine-iptables-dbgsym (8.0.0.0+0~mr8.0.0.0) ...
Setting up ngcp-rtpengine-kernel-dkms (8.0.0.0+0~mr8.0.0.0) ...

Creating symlink /var/lib/dkms/ngcp-rtpengine/8.0.0.0+0~mr8.0.0.0/source ->
                 /usr/src/ngcp-rtpengine-8.0.0.0+0~mr8.0.0.0

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=4.19.0-6-amd64 -C /lib/modules/4.19.0-6-amd64/build M=/var/lib/dkms/ngcp-rtpengine/8.0.0.0+0~mr8.0.0.0/build RTPENGINE_VERSION=8.0.0.0+0~mr8.0.0.0....
cleaning build area...

DKMS: build completed.

xt_RTPENGINE.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.0-6-amd64/updates/dkms/

depmod..............

DKMS: install completed.
_Job for ngcp-rtpengine-daemon.service failed because the control process exited with error code._
See "systemctl status ngcp-rtpengine-daemon.service" and "journalctl -xe" for details.
invoke-rc.d: initscript ngcp-rtpengine-daemon, action "restart" failed.
● ngcp-rtpengine-daemon.service - NGCP RTP/media Proxy Daemon
   Loaded: loaded (/lib/systemd/system/ngcp-rtpengine-daemon.service; enabled; vendor preset: enabled)
   _Active: failed (Result: exit-code) since Thu 2019-10-03 10:3ls -8:04 EDT; 8ms ago_
  Process: 3961 ExecStartPre=/usr/sbin/ngcp-rtpengine-iptables-setup start (code=exited, status=0/SUCCESS)
  Process: 3976 ExecStart=/usr/sbin/rtpengine -f -E --no-log-timestamps --pidfile /run/ngcp-rtpengine-daemon.pid --config-file /etc/rtpengine/rtpengine.conf --table $TABLE (code=exited, status=255/EXCEPTION)
  Process: 3977 ExecStopPost=/usr/sbin/ngcp-rtpengine-iptables-setup stop (code=exited, status=0/SUCCESS)
 Main PID: 3976 (code=exited, status=255/EXCEPTION)

_Oct 03 10:38:03 server systemd[1]: Starting NGCP RTP/media Proxy Daemon...
Oct 03 10:38:03 server rtpengine[3976]: CRIT: Fatal error: Bad command line: No such file or directory
Oct 03 10:38:03 server rtpengine[3976]: CRIT: Fatal error: Bad command line: No such file or directory
Oct 03 10:38:03 server systemd[1]: ngcp-rtpengine-daemon.service: Main process exited, code=exited, status=255/EXCEPTION_
Oct 03 10:38:04 server systemd[1]: ngcp-rtpengine-daemon.service: Failed with result 'exit-code'.
Oct 03 10:38:04 server systemd[1]: Failed to start NGCP RTP/media Proxy Daemon.
Setting up ngcp-rtpengine-kernel-source (8.0.0.0+0~mr8.0.0.0) ...
Setting up ngcp-rtpengine-recording-daemon (8.0.0.0+0~mr8.0.0.0) ...
Created symlink /etc/systemd/system/rtpengine-recording.service → /lib/systemd/system/ngcp-rtpengine-recording-daemon.service.
Created symlink /etc/systemd/system/multi-user.target.wants/ngcp-rtpengine-recording-daemon.service → /lib/systemd/system/ngcp-rtpengine-recording-daemon.service.
Job for ngcp-rtpengine-recording-daemon.service failed because the control process exited with error code.
See "systemctl status ngcp-rtpengine-recording-daemon.service" and "journalctl -xe" for details.
Created symlink /etc/systemd/system/multi-user.target.wants/ngcp-rtpengine-recording-nfs-mount.service → /lib/systemd/system/ngcp-rtpengine-recording-nfs-mount.service.
Setting up ngcp-rtpengine-recording-daemon-dbgsym (8.0.0.0+0~mr8.0.0.0) ...
Setting up ngcp-rtpengine-utils (8.0.0.0+0~mr8.0.0.0) ...
Setting up ngcp-rtpengine (8.0.0.0+0~mr8.0.0.0) ...
Processing triggers for systemd (241-7~deb10u1) ...
Processing triggers for man-db (2.8.5-2) ...

The reason why systemctl is unable to start daemons - missing  config files and it's easy fix

**ls -la /etc/rtpengine/**
_rtpengine-recording.sample.conf  rtpengine.sample.con_

The most interesting part 
**module-assistant auto-install ngcp-rtpengine-kernel-source**


																					  ─────────────┤ module-assistant, interactive mode ├─────────────┐
                                                                                      │ Build of the package ngcp-rtpengine-kernel-source failed! How │
                                                                                      │ do you wish to proceed?                                       │
                                                                                      │                                                               │
                                                                                      │      VIEW     Examine the build log file                      │
                                                                                      │      CONTINUE Skip and continue with the next operation       │
                                                                                      │      STOP     Stop processing the build commands              │
                                                                                      │                                                               │
                                                                                      │                                                               │
                                                                                      │                                                               │
                                                                                      │                                                               │
                                                                                      │                <Ok>                    <Cancel>               │
                                                                                      │                                                 






dh_testdir
                                                                               │ /usr/bin/make clean
                                                                               │ make[1]: Entering directory '/usr/src/modules/ngcp-rtpengine'
                                                                               │ /usr/bin/make -C /lib/modules/4.19.0-6-amd64/build
                                                                               │ M=/usr/src/modules/ngcp-rtpengine clean || true
                                                                               │ make[2]: Entering directory '/usr/src/linux-headers-4.19.0-6-amd64'
                                                                               │ make[2]: Leaving directory '/usr/src/linux-headers-4.19.0-6-amd64'
                                                                               │ make[1]: Leaving directory '/usr/src/modules/ngcp-rtpengine'
                                                                               │ dh_clean
                                                                               │ /usr/bin/make  -f debian/rules clean
                                                                               │ make[1]: Entering directory '/usr/src/modules/ngcp-rtpengine'
                                                                               │ dh_testdir
                                                                               │ /usr/bin/make clean
                                                                               │ make[2]: Entering directory '/usr/src/modules/ngcp-rtpengine'
                                                                               │ /usr/bin/make -C /lib/modules/4.19.0-6-amd64/build


and after "STOP " option ends with 


Updated infos about 1 packages
Getting source for kernel version: 4.19.0-6-amd64
Kernel headers available in /lib/modules/4.19.0-6-amd64/build
Creating symlink...
apt-get install build-essential
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.6).
build-essential set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Done!
unpack
Extracting the package tarball, /usr/src/ngcp-rtpengine.tar.bz2, please wait...
"/usr/share/modass/overrides/ngcp-rtpengine-kernel-source" build KVERS=4.19.0-6-amd64 KSRC=/lib/modules/4.19.0-6-amd64/build KDREV=4.19.67-2+deb10u1 kdist_image


**root@server:/opt/rtpengine# cat /var/cache/modass/ngcp-rtpengine-kernel-source.buildlog.4.19.0-6-amd64.1570113951**
dh_testdir
/usr/bin/make clean
make[1]: Entering directory '/usr/src/modules/ngcp-rtpengine'
/usr/bin/make -C /lib/modules/4.19.0-6-amd64/build M=/usr/src/modules/ngcp-rtpengine clean || true
make[2]: Entering directory '/usr/src/linux-headers-4.19.0-6-amd64'
make[2]: Leaving directory '/usr/src/linux-headers-4.19.0-6-amd64'
make[1]: Leaving directory '/usr/src/modules/ngcp-rtpengine'
dh_clean
/usr/bin/make  -f debian/rules clean
make[1]: Entering directory '/usr/src/modules/ngcp-rtpengine'
dh_testdir
/usr/bin/make clean
make[2]: Entering directory '/usr/src/modules/ngcp-rtpengine'
/usr/bin/make -C /lib/modules/4.19.0-6-amd64/build M=/usr/src/modules/ngcp-rtpengine clean || true
make[3]: Entering directory '/usr/src/linux-headers-4.19.0-6-amd64'
make[3]: Leaving directory '/usr/src/linux-headers-4.19.0-6-amd64'
make[2]: Leaving directory '/usr/src/modules/ngcp-rtpengine'
dh_clean
make[1]: Leaving directory '/usr/src/modules/ngcp-rtpengine'
/usr/bin/make  -f debian/rules kdist_clean kdist_config binary-modules
make[1]: Entering directory '/usr/src/modules/ngcp-rtpengine'
dh_testdir
/usr/bin/make clean
make[2]: Entering directory '/usr/src/modules/ngcp-rtpengine'
/usr/bin/make -C /lib/modules/4.19.0-6-amd64/build M=/usr/src/modules/ngcp-rtpengine clean || true
make[3]: Entering directory '/usr/src/linux-headers-4.19.0-6-amd64'
make[3]: Leaving directory '/usr/src/linux-headers-4.19.0-6-amd64'
make[2]: Leaving directory '/usr/src/modules/ngcp-rtpengine'
dh_clean
/usr/bin/make -w -f debian/rules clean
make[2]: Entering directory '/usr/src/modules/ngcp-rtpengine'
dh_testdir
/usr/bin/make clean
make[3]: Entering directory '/usr/src/modules/ngcp-rtpengine'
/usr/bin/make -C /lib/modules/4.19.0-6-amd64/build M=/usr/src/modules/ngcp-rtpengine clean || true
make[4]: Entering directory '/usr/src/linux-headers-4.19.0-6-amd64'
make[4]: Leaving directory '/usr/src/linux-headers-4.19.0-6-amd64'
make[3]: Leaving directory '/usr/src/modules/ngcp-rtpengine'
dh_clean
make[2]: Leaving directory '/usr/src/modules/ngcp-rtpengine'
make[1]: Nothing to be done for 'kdist_config'.
for templ in ; do \
    cp $templ `echo $templ | sed -e 's/_KVERS_/4.19.0-6-amd64/g'` ; \
  done
for templ in `ls debian/*.modules.in` ; do \
    test -e ${templ%.modules.in}.backup || cp ${templ%.modules.in} ${templ%.modules.in}.backup 2>/dev/null || true; \
    sed -e 's/##KVERS##/4.19.0-6-amd64/g ;s/#KVERS#/4.19.0-6-amd64/g ; s/_KVERS_/4.19.0-6-amd64/g ; s/##KDREV##/4.19.67-2+deb10u1/g ; s/#KDREV#/4.19.67-2+deb10u1/g ; s/_KDREV_/4.19.67-2+deb10u1/g  ' < $templ > ${templ%.modules.in}; \
  done
dh_testroot
dh_prep
# Build the module
/usr/bin/make modules KSRC=/lib/modules/4.19.0-6-amd64/build KVER=4.19.0-6-amd64
make[2]: Entering directory '/usr/src/modules/ngcp-rtpengine'
/usr/bin/make -C /lib/modules/4.19.0-6-amd64/build M=/usr/src/modules/ngcp-rtpengine O=/lib/modules/4.19.0-6-amd64/build modules
make[3]: Entering directory '/usr/src/linux-headers-4.19.0-6-amd64'
  CC [M]  /usr/src/modules/ngcp-rtpengine/xt_RTPENGINE.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /usr/src/modules/ngcp-rtpengine/xt_RTPENGINE.mod.o
  LD [M]  /usr/src/modules/ngcp-rtpengine/xt_RTPENGINE.ko
make[3]: Leaving directory '/usr/src/linux-headers-4.19.0-6-amd64'
make[2]: Leaving directory '/usr/src/modules/ngcp-rtpengine'
# Install the module
install -D -m 0644 xt_RTPENGINE.ko debian/ngcp-rtpengine-kernel-modules-4.19.0-6-amd64/lib/modules/4.19.0-6-amd64/extra/xt_RTPENGINE.ko
dh_installdocs
dh_installdocs: Please specify the compatibility level in debian/compat
make[1]: *** [debian/rules:64: binary-modules] Error 2
make[1]: Leaving directory '/usr/src/modules/ngcp-rtpengine'
make: *** [/usr/share/modass/include/common-rules.make:56: kdist_build] Error 2

**Comment by rfuchs** [comment]
How about using `ngcp-rtpengine-kernel-dkms` instead of `ngcp-rtpengine-kernel-source` with module-assistant?

**Comment by sashasaturn** [comment]
@rfuchs it also fails 

**module-assistant auto-install ngcp-rtpengine-kernel-dkms**

Updated infos about 1 packages
Getting source for kernel version: 4.19.0-6-amd64
Kernel headers available in /lib/modules/4.19.0-6-amd64/build
apt-get install build-essential
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.6).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Done!
unpack
The source tarball could not be found!
Package ngcp-rtpengine-kernel-dkms not installed?
Running "m-a -f get ngcp-rtpengine-kernel-dkms" may help.
"/usr/share/modass/packages/default.sh" build KVERS=4.19.0-6-amd64 KSRC=/lib/modules/4.19.0-6-amd64/build KDREV=4.19.67-2+deb10u1 kdist_image


**dpkg -l |grep ngcp**
ii  ngcp-rtpengine                         8.0.0.0+0~mr8.0.0.0          all          NGCP RTP/media proxy - meta package
ii  ngcp-rtpengine-daemon                  8.0.0.0+0~mr8.0.0.0          amd64        proxy for RTP and media streams used in NGCP, userspace part
ii  ngcp-rtpengine-daemon-dbgsym           8.0.0.0+0~mr8.0.0.0          amd64        debug symbols for ngcp-rtpengine-daemon
ii  ngcp-rtpengine-iptables                8.0.0.0+0~mr8.0.0.0          amd64        IPtables extension module for the kernel-space NGCP media proxy
ii  ngcp-rtpengine-iptables-dbgsym         8.0.0.0+0~mr8.0.0.0          amd64        debug symbols for ngcp-rtpengine-iptables
ii  ngcp-rtpengine-kernel-dkms             8.0.0.0+0~mr8.0.0.0          all          IPtables kernel module for the NGCP media proxy - DKMS
ii  ngcp-rtpengine-kernel-source           8.0.0.0+0~mr8.0.0.0          all          IPtables kernel module for the NGCP media proxy - source
ii  ngcp-rtpengine-recording-daemon        8.0.0.0+0~mr8.0.0.0          amd64        recording daemon for RTP and media streams
ii  ngcp-rtpengine-recording-daemon-dbgsym 8.0.0.0+0~mr8.0.0.0          amd64        debug symbols for ngcp-rtpengine-recording-daemon
ii  ngcp-rtpengine-utils                   8.0.0.0+0~mr8.0.0.0          all          scripts and Perl modules for NGCP rtpengine

**Comment by rfuchs** [comment]
Actually you've already installed the dkms package.

```
Preparing to unpack .../ngcp-rtpengine-kernel-dkms_8.0.0.0+0mr8.0.0.0_all.deb ...
Unpacking ngcp-rtpengine-kernel-dkms (8.0.0.0+0mr8.0.0.0) ...
...
Setting up ngcp-rtpengine-kernel-dkms (8.0.0.0+0~mr8.0.0.0) ...

Creating symlink /var/lib/dkms/ngcp-rtpengine/8.0.0.0+0mr8.0.0.0/source ->
/usr/src/ngcp-rtpengine-8.0.0.0+0mr8.0.0.0

DKMS: add completed.
```

You shouldn't have to do anything else. `modprobe xt_RTPENGINE` should work.

**Comment by sashasaturn** [comment]
@rfuchs looks like you are correct

**lsmod** 

Module                  Size  Used by
xt_RTPENGINE           49152  4
iptable_filter         16384  0
sunrpc                425984  1
xt_tcpudp              16384  0
nft_compat             20480  2
nft_counter            16384  4
nf_tables             143360  12 nft_compat,nft_counter
nfnetlink              16384  2 nft_compat,nf_tables
vmwgfx                331776  1
ttm                   131072  1 vmwgfx
drm_kms_helper        208896  1 vmwgfx
joydev                 24576  0
vmw_balloon            20480  0
sg                     36864  0
drm                   495616  4 vmwgfx,drm_kms_helper,ttm
evdev                  28672  2
vmw_vmci               81920  1 vmw_balloon
serio_raw              16384  0
pcspkr                 16384  0
edac_mce_amd           28672  0
ac                     16384  0
button                 16384  0
ip_tables              28672  1 iptable_filter
x_tables               45056  5 iptable_filter,nft_compat,xt_tcpudp,xt_RTPENGINE,ip_tables
autofs4                49152  2
ext4                  737280  2
crc16                  16384  1 ext4
mbcache                16384  1 ext4
jbd2                  122880  1 ext4
crc32c_generic         16384  3
fscrypto               32768  1 ext4
ecb                    16384  0
crypto_simd            16384  0
cryptd                 28672  1 crypto_simd
glue_helper            16384  0
aes_x86_64             20480  0
dm_mod                155648  6
sr_mod                 28672  0
cdrom                  65536  1 sr_mod
ata_generic            16384  0
sd_mod                 61440  3
psmouse               172032  0
ata_piix               36864  0
libata                270336  2 ata_piix,ata_generic
vmw_pvscsi             28672  2
scsi_mod              249856  5 vmw_pvscsi,sd_mod,libata,sg,sr_mod
vmxnet3                69632  0
i2c_piix4              24576  0
floppy                 86016  0


modinfo xt_RTPENGINE
filename:       /lib/modules/4.19.0-6-amd64/updates/dkms/xt_RTPENGINE.ko
license:        GPL
depends:        x_tables
retpoline:      Y
name:           xt_RTPENGINE
vermagic:       4.19.0-6-amd64 SMP mod_unload modversions
parm:           proc_uid:rtpengine procfs tree user id (uint)
parm:           proc_gid:rtpengine procfs tree group id (uint)
parm:           stream_packets_list_limit:maximum number of packets to retain for intercept streams (uint)
parm:           log_errors:generate kernel log lines from forwarding errors (bool)

So the only thing which I believe I have to fix in my installation process  - creation of .conf files prior to **dpkg -i../*.deb**

Thank you!

**Comment by mika** [comment]
Actually the `dh_installdocs: Please specify the compatibility level in debian/compat` is an actual issue in the build process, thanks @sashasaturn for providing your detailed instructions, I could reproduce your issue and will provide an according fix for the `ngcp-rtpengine-kernel-source` package soon.
