### ISSUE TITLE
Compiling rtpengine on RHEL 7

### ISSUE THREAD

**Issue by githubsw** [sipwise/rtpengine#855]
Hello I am running into an issue compiling rtpengine on RHEL.  I have compiled it on RHEL before but something seems to be missing on my current server.
 I am running into the error "expected ')' before 'PRIx32" in call.c and redis.c.  I also see a similar error for PRIu64 in redis.c.  

I have verified that <inttypes.h> is included in these c files, and that inttypes.h contains these definitions.  I'm note sure what is missing.  Any ideas?

Example: ilog(LOG_INFO, "------ Average MOS %" PRIu64 ".%"......... will throw a compile error 

Thank you,

**Comment by rfuchs** [comment]
Can you post a full build log?

**Comment by sergey-safarov** [comment]
I have tested build RPM packages on CentOS 8.
No issues.
Think this may be closed.

**Comment by sergey-safarov** [comment]
Sorry reported CentOS 7
