### ISSUE TITLE
empty SSRC while getting "query" during the WebRTC call

### ISSUE THREAD

**Issue by ovoshlook** [sipwise/rtpengine#857]
Hello. I tried this on 7.5.1 and 6.3.1 versions of rtpengine and , actually can't be sure that this is RTPegnine problem but will try to describe it here because it looks strange:
During the webRTC call I making requests to rtpengine about call state via "query" request
So far everything is really good but during WebRTC call I found that SSRC contains some entries (those  7 entries in example is about call during 14 seconds or so. so it sends it really often), but all of them are empty:
Here is an output of SSRC part what I got (bencode decoded to JSON for easy read)
`
"SSRC":{"3124747344":{},"1934083840":{},"1864918075":{},"2501070600":{},"1056770950":{},"2939055258":{},"1435226208":{}}
`
All objects are empty but entries exists...
My mind that WebRTC sends wrong data or unreadable data

For webRTC Im using chome (jssip.net lib over WebRTC but this makes no sence about RTCP data) for tests right now.

Just wondering here because probably you already had same issue and questions about it.
If no - Im ready to get more information, but just don't know which. I will try to get data from browser directly meanwhile you answering :-)

**Comment by rfuchs** [comment]
These are populated with stats that are derived from RTCP reports coming from the RTP endpoints. If no RTCP is received (or the packets contain garbage) then you'd get empty fields as you see.

**Comment by ovoshlook** [comment]
but isn't should be no entries at all?
I just confused that I have entries and also I see
`"stats":{"bytes":300,"packets":3,"errors":0}` for one leg here and also in totals (that summarises I suppose:
`"totals":{"RTCP":{"bytes":300,"packets":3,"errors":0}`
It looks like some packets exists and it should be present at the SSRC (that also filled for one leg at the streams array:
`"SSRC":1056770950`

**Comment by rfuchs** [comment]
No, like I said, the list you posted is only for stats derived from RTCP.

**Comment by ovoshlook** [comment]
Ok got it. Thx for clarification. At least now it is more clear where to search :-)

**Comment by rfuchs** [comment]
If you want, you can add additional fields to the output here, even if MOS data is not available. See `ng_stats_ssrc`

**Comment by ovoshlook** [comment]
hm it is interesting. Thanks a lot!

**Comment by ovoshlook** [comment]
Hi once more time
We still trying to figure out and get more clearance about existing RTCP received from webRTC and we found that data RTPengine  received from webRTC over RTCP is encrypted and looks like we never getting this data decrypted because we getting an error about 
`SRTCP output wanted but no crypto was negotiated`. 
But this is quite strange because we are not using early media or something that can affect us with that.

Is there any aditional information how we can get this encrypted?

**Comment by rfuchs** [comment]
Does the log show that the DTLS connection on the RTCP port gets established?

**Comment by ovoshlook** [comment]
I facing only 
`DTLS-SRTP successfully negotiated`
but for SRTCP still 
`SRTCP output wanted but no crypto was negotiated`

I changed a bit scenario
Not I running rtcp-mux from both sides, so they are in the same stream with RTP and RTPengine does not need to mux it by itself but still facing the same issue

**Comment by rfuchs** [comment]
Post full logs please. The log lines are prefixed with the port, which tells you whether DTLS was negotiated on the RTP port or the RTCP port (or both).

**Comment by ovoshlook** [comment]
[rtpengine.txt](https://github.com/sipwise/rtpengine/files/3708888/rtpengine.txt)
Done!

**Comment by rfuchs** [comment]
Yeah, so DTLS on the RTCP port 10045 never gets established. My guess is that this is from a WebRTC client which expects rtcp-mux to be accepted and functional, regardless of negotiation. But you never instruct rtpengine to do anything with rtcp-mux, so it's passed on to your B, who rejects it (probably not supported). So rtpengine passes that rejection back to your A, and subsequently expects RTCP to flow on the separate RTCP port. But WebRTC ignores that part and continues with rtcp-mux enabled.

You should use the flag `rtcp-mux-demux` in your offer.

**Comment by ovoshlook** [comment]
Yeah! Definitely you right :-)
thought that rtpengine does it automatically (rtcp-mux-demux)this works! thx for help :-)

Probably B endpoint needs to be set up as `rtcp-mux` also to not negotiate 2 channels instead of one. but asterisk event with rtcp_mux=yes does not do it...
but this is different one :-) thx a lot for help one more time!
