### ISSUE TITLE
Client STUN Keepalives and performance impact?

### ISSUE THREAD

**Issue by camilleoudot** [sipwise/rtpengine#86]
Hi,

using the 3.8 branch, and Chrome 41 as a client, I see a lot of STUN requests (2 per second) sent from Chrome to rtpengine during a media session. This results in the following messages being print in the rtpengine logs:

```
Mar 19 11:06:30 dev-arch-sep1 rtpengine[17478]: [829d8d34bbacc835c1bdd6118224d4af@127.0.0.1 port 30052] ICE pair k5WxxQ2vverxm5yr:1104935029:1 has been nominated by peer
Mar 19 11:06:30 dev-arch-sep1 rtpengine[17478]: [829d8d34bbacc835c1bdd6118224d4af@127.0.0.1 port 30052] ICE completed, using pair k5WxxQ2vverxm5yr:1104935029:1
Mar 19 11:06:30 dev-arch-sep1 rtpengine[17478]: [829d8d34bbacc835c1bdd6118224d4af@127.0.0.1 port 30052] Successful STUN binding request from C.C.C.C:49495
Mar 19 11:06:30 dev-arch-sep1 rtpengine[17478]: [829d8d34bbacc835c1bdd6118224d4af@127.0.0.1 port 30040] Kernelizing media stream
Mar 19 11:06:30 dev-arch-sep1 rtpengine[17478]: [829d8d34bbacc835c1bdd6118224d4af@127.0.0.1 port 30052] Kernelizing media stream
```

These lines are repeated every second for one call. Does this have a performance impact? Is the call unkernelized and rekernelized every second?

**Comment by uloyulocas** [comment]
Same here (

**Comment by rfuchs** [comment]
Shouldn't have any impact other then the redundant log messages, but I agree that these should be silenced.

**Comment by rfuchs** [comment]
I believe 20ac7cd5f7da6d26cfdb0d6b489812eee09fd68a fixes this.

**Comment by camilleoudot** [comment]
Yes it does, only `Successful STUN binding request from C.C.C.C:ppppp` remains, but in DEBUG level so it's fine.
Thanks
