### ISSUE TITLE
Dead(?) link in G729 (minor documentation issue)

### ISSUE THREAD

**Issue by Doranku** [sipwise/rtpengine#860]
The link to https://deb.sipwise.com/spce/mr6.2.1/pool/main/b/bcg729/ 
here in the sentence "Sipwise provides a pre-packaged version of this as part of our C5 CE product which is available **here**", appears to be dead or atleast not working (502)

**Comment by taurus-forever** [comment]
I have checked the link from the several places and I see the listing of all files there and I am able to download the package, here is the direct link https://deb.sipwise.com/spce/mr6.2.1/pool/main/b/bcg729/libbcg729-0_1.0.4+git20180222-0.1~bpo9+1_amd64.deb

Is it still reproducible now?
Maybe it is IPv4/IPv6 issue, are you using IPv6?

Keep in mind your link is for version mr6.2.1, you probably need to download package version which matches your rtpengine version, just tune "mrX.X.X" in your link, like https://deb.sipwise.com/spce/mr7.5.1/pool/main/b/bcg729/ , etc.

**Comment by Doranku** [comment]
It works with IPv4, it is IPv6 that gives a 502.

`$ curl -v -6 https://deb.sipwise.com/spce/mr7.5.1/pool/main/b/bcg729/
*   Trying 2600:1901:0:da64::...
* Connected to deb.sipwise.com (2600:1901:0:da64::) port 443 (#0)
...
*        SSL certificate verify ok.
> GET /spce/mr7.5.1/pool/main/b/bcg729/ HTTP/1.1
> User-Agent: curl/7.38.0
> Host: deb.sipwise.com
> Accept: */*
> 
< HTTP/1.1 502 Bad Gateway
< Content-Type: text/html; charset=UTF-8
< Referrer-Policy: no-referrer
< Content-Length: 332
< Date: Mon, 14 Oct 2019 15:32:03 GMT
< Alt-Svc: clear
`

Thanks for the hint, it has been a long time since I have seen IPv6 misconfigurations.

**Comment by rfuchs** [comment]
This should be fixed now.
