### ISSUE TITLE
Feature request: expose API or kind of to get events about OPUS bandwidth changes

### ISSUE THREAD

**Issue by ovoshlook** [sipwise/rtpengine#863]
Hello!
This is not even future request but kinda question about is it in your plans or not.
so question is about exposing some events or sending responses to external service on requests about opus codec TOS params was changed during existing dialog.

Im gonna get it at the future and probably build it  by myself, but if it is some work already done in that direction will be great to know about it to not do this job twice.

**Comment by rfuchs** [comment]
No such plans at this time. In fact Opus bitrate is completely non adaptive for the time being.
