### ISSUE TITLE
DTMF Transconding

### ISSUE THREAD

**Issue by vtzan** [sipwise/rtpengine#864]
Dear Team,

I would like to ask a question about DTMF Transcoding.
Its been asked before here -> https://github.com/sipwise/rtpengine/issues/724
and the answer from @rfuchs was 
`We don't currently support transcoding between inline audio DTMF and DTMF payload types, but we will in the near(ish) future.`

I don't know if this is possible now or not I would like to know if there is a way to force rtpengine to do specific transcoding to RFC2833 or INBAND? 

I have tried codec-transcode-telephone-event flag in rtpengine_offer which indeed creates the telephone event line in the sdp part on the INVITE but when the user inside (which is trying to reach an endpoint which supports inband only) is sending RFC2833
DTMFs are not working. When the same phone sends inband the DTMFs are working fine.

rtpengine_flags used in rtpengine_offer : 
`$var(rtpengine_flags) = "codec-strip-all RTP/AVP replace-session-connection replace-origin ICE=remove codec-mask-all codec-transcode-PCMA codec-transcode-G722 codec-transcode-G729 codec-transcode-telephone-event codec-offer-telephone-event ptime=20";`

Could you please help me out find a way to normalize the DTMF scenarios so that every time rtpengine will convert the dtmf according to what the endpoint supports?

Thank you in advance for your support.
Vasilios Tzanoudakis

**Comment by rfuchs** [comment]
This is described in https://github.com/sipwise/rtpengine#dtmf-transcoding

The flags you posted used in an offer should enable transcoding between an A using inband DTMF to a B using RFC DTMF events. Even though I can't be 100% sure off the top of my head about the interaction between that and `codec-mask-all` and `codec-offer-telephone-event`.

If it's not working, try reducing the number of codec related flags to just what you need. If still not working, enable debug logging and post the result.

**Comment by vtzan** [comment]
Dear @rfuchs,

Thank you for your fast response. 
Regarding the opposite scenario, RFC DTMF (A side) and inband DTMF (B side) are my flags correct for this scenario too?

I am trying to understand if rtpengine can behave just like asterisk chan_sip when setting dtmf=auto to sip trunk which does RFC DTMF first and then failover to INBAND DTMF

I will try reduce the flags and put only PCMA just like you proposed and let you know the results.

Thank you for your support
Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Dear @rfuchs,

Thank you for your response. As you can see in my flags I have `ptime=20` which will force transcoding according to https://github.com/sipwise/rtpengine#transcoding 
Is this correct or I have to put the `always-transcode` either way to enable it?

Thank you for your support
Vasilios Tzanoudakis

**Comment by rfuchs** [comment]
You still have to include `always-transcode`

**Comment by vtzan** [comment]
Dear @rfuchs 

Thank you for your support on this. I will try it in a few hours and let you know.

Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Dear @rfuchs,

I added the always-transcode flag but it didn't worked.

I am sending you the full rtpengine debug file.
In this scenario A Side = RFC2833 calls -- B Side = DTMF INBAND
[rtpengine-dtmf.log](https://github.com/sipwise/rtpengine/files/3769585/rtpengine-dtmf.log)

Thank you in advance for your support
Vasilios Tzanoudakis

**Comment by rfuchs** [comment]
Add `always-transcode` to the flags in your `answer`. As per the docs: `Unlike other transcoding options, this one is directional, which means that it's applied only to the one side doing the signalling that is being handled (i.e. the side doing the offer or the answer).`

**Comment by vtzan** [comment]
Dear @rfuchs,

Thank you for your reply.
I will try it and let you know.

Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Dear @rfuchs,

Sorry for the delay on this case. I have added the always-transcode flag on anwser too but the problem is the same. We pressed number 9 on dtmf but it didn't passed on the other side.
I have attached full rtpengine debug.

thank you in advance for your support on this case.
Vasilios Tzanoudakis

[rtpengine-dtmf-always-transcode.log](https://github.com/sipwise/rtpengine/files/3935453/rtpengine-dtmf-always-transcode.log)

**Comment by rfuchs** [comment]
Try without wildly mixing strip/mask/offer/transcode flags and instead just use the flags you really need. In your example, since you end up talking PCMA which was in the original offer, you can just use `always-transcode` and no other codec related flags. If you need to offer additional codecs, add them with `transcode`. Don't use strip/mask if you don't need them.

**Comment by vtzan** [comment]
Dear @rfuchs 

Thank you very much for your reply. I am using strip-all / codec-mask-all  because I don't control what codecs the A side will send to my SIP Server so I want to be sure that on the B side RTPEngine will offer only these codecs PCMA,G722,G729 with ptime=20 and always transcode.

I have also tried with setting flags to :
`codec-strip-all RTP/AVP replace-session-connection replace-origin ICE=remove codec-transcode-PCMA codec-transcode-telephone-event ptime=20 always-transcode`

Let me ask you about `codec-transcode-telephone-event `& `always-transcode` are ok to be used together? Do they overlap?

Either way just to let you know setting `always-transcode` to rtpengine_answer flag with whatever flags I put there then the DTMF transcoding works for almost 70% of the times.

I am setting up a lab to verify this behavior and I would like to know what are the minimal flags to try hiding all codecs from A side and only have PCMA and full transcoding on the B side including DTMF transcoding.

thank you once again for your support on this case.
Vasilios Tzanoudakis

**Comment by rfuchs** [comment]
The `strip` option, in particular `strip=all` is only useful in conjunction with a `codec-offer` option. You cannot use `strip=all` with just `transcode=...` options.

If you want to accept all codecs coming from A and only offer the ones you mentioned to B, use `mask=all transcode=PCMA transcode=G722 transcode=G729 transcode=telephone-event always-transcode`

As per docs, `transcode=telephone-event` is for forward DTMF transcoding (in the offer), while `always-transcode` is for reverse DTMF transcoding (in the answer). Both can be used at the same time.

**Comment by vtzan** [comment]
Dear @rfuchs ,

We can close this issue for now. 
It seems that the problem was on the other side (vendor) and its working now.
thank you for your support.

Vasilios Tzanoudakis
