### ISSUE TITLE
How to strip/offer with passthrough media

### ISSUE THREAD

**Issue by rnewman** [sipwise/rtpengine#869]
I'm receiving an INVITE with SDP that includes a `t38` m-line and G.711 audio — a typical fax request, something like this:

```
o=Sonus_UAC 344024 479547 IN IP4 123.123.96.6
s=SIP Media Capabilities
c=IN IP4 123.123.96.8
t=0 0
m=image 9612 udptl t38
a=T38FaxVersion:0
a=T38MaxBitRate:14400
a=T38FaxRateManagement:transferredTCF
a=T38FaxMaxBuffer:262
a=T38FaxMaxDatagram:176
a=T38FaxUdpEC:t38UDPRedundancy
a=sendrecv
m=audio 0 RTP/AVP 8
a=rtpmap:8 PCMA/8000
a=inactive
a=rtcp:64865
```

I am trying to use the `strip=all`/`offer` approach to intersect the supported set of audio codecs with PCMU/8000. When I do, the resulting SDP is totally sparse, something like:

```
v=0
o=- 2209001886 0695171000 IN IP4 123.123.75.41
s=no_session_name
t=0 0
m=audio 50004 RTP/AVP 0
c=IN IP4 123.123.75.41
a=rtpmap:0 pcmu/8000
a=sendrecv
a=rtcp:50005
m=audio 50038 RTP/AVP 8
c=IN IP4 123.123.75.41
a=rtpmap:8 pcma/8000
a=sendrecv
a=rtcp:50039
```

I can't find any documentation for how to instruct RTPEngine in an `offer` command to preserve `m=image` and its corresponding attribute lines.

Is there a good way to do this with RTPEngine?

**Comment by rfuchs** [comment]
I can't reproduce this and this doesn't look like an SDP produced by rtpengine. Can you post a complete example? Ideally from a full debug log.

**Comment by rnewman** [comment]
You're right, @rfuchs; not sure why I was getting that, but it's working now. I appreciate the quick response.
