### ISSUE TITLE
play media with rtpengine

### ISSUE THREAD

**Issue by bshirazi** [sipwise/rtpengine#870]
Hi
Please forgive me if my question is very basic.
Do you have a working sample of playing a wav file with rtpengine+kamailio/opensips ?
I followed this procedure but cannot make all massages myself.
1- receiving invite with sdp 
2-rtpengine_manage();
3-making 200 ok with sdp or 183 with sdp   manually(?)
4-play_media(file=...)
need another rtpengine_answer() before play_media ?
A working sample will solve all questions.
Thank you very much !

Regards
M.Shirazi

**Comment by rfuchs** [comment]
You don't need to craft an SDP or produce extra signalling. At the bare minimum you need to present an `offer` (through `rtpengine_offer` or `rtpengine_manage`) followed by `play_media` towards the A party. An `answer` is only needed if you want to play towards the B party.

**Comment by bshirazi** [comment]
Thanks for reply.
There is only one A caller there is no called (B) party.
I want to Opernsips+rtpengine act as B party and play wav file.
Is it possible?  in this case how B party sdp(rtp ports...) was created? 
Regards
M.Shirazi

**Comment by rfuchs** [comment]
You can play media towards A without an answer SDP. The A party would then receive the audio as "early media" without the call being established and without having received an answer SDP.

If you require an answer SDP you would have to craft one yourself (using some sort of black hole network destination), pass it to rtpengine as `answer`, and then inject it towards A as a 183 or 200. There is no support for this in rtpengine.

**Comment by bshirazi** [comment]
Hi
Is there a way to we know play media function use which port for playing media?
According to my traces it use a port number usually 8-22 number more than 2 rtp ports rtpengine uses for sdp rewrite. If I have play media rtp port number I can set it in 183 reply sdp body.
Regards
M.Shirazi

**Comment by rfuchs** [comment]
Sounds like you're selecting the wrong party to play to. A full debug log would be helpful.

**Comment by ovoshlook** [comment]
Hello, I will probably join to this conversation:
I am trying to play audio as early media in case of offer received (actually I am using SDP returned from rtpengine as answer for endpoint, by sending it to originator)
It looks like incorrect because of port, that rtpengine corresponds back is allocated for the B leg
 but I can't get how to send to endpoint back correct one

So the situation is that after handling offer from endpoint rtpengine returns handled SDP with port allocated 30030, but tries to play media form port 30050. In that case as port is not matches to that one. Endpoint drops media

I'm thinking about to do some answer emulation, but not sure if there is more correct way to build this scenario.

**Comment by rfuchs** [comment]
Of course you get a different port when you do that. The port returned in the SDP from A's offer is the one that corresponds to B. If you want to get the SDP that corresponds to A, you need to process the answer from B.

You should be able to play media to A without sending an SDP there. If that doesn't work for some reason, you can try to synthesise an answer SDP, but we don't support this use case for the time being.

**Comment by ovoshlook** [comment]
Yeah. Thx for the confirmation ( I've got the samefrom the tests I've done while you answered )
With the answer emulation procedure I getting what I need.

**Comment by bshirazi** [comment]
> 
> 
> Yeah. Thx for the confirmation ( I've got the samefrom the tests I've done while you answered )
> With the answer emulation procedure I getting what I need.

Hi @ovoshlook 
Did you get successful result with your answer emulation procedure ?
Can you play media with Kamailio/Opensips+rtpengine for caller when there is no B party ?

Regards
Shirazi

**Comment by ovoshlook** [comment]
hi yep
I've made it working
I just landed a request on my Kamailio and generated a response with proper SDP.

**Comment by bshirazi** [comment]
> 
> 
> hi yep
> I've made it working
> I just landed a request on my Kamailio and generated a response with proper SDP.

@ovoshlook 
Would you please kindly share sample part of script for doing this  ?

Regards
Shirazi

**Comment by bshirazi** [comment]
Hi @rfuchs 
Regarding recent above discussion is there a way we know what rtp port rtpengine will send media so we can put that port number in our reply sdp ?

Regards
Shirazi

**Comment by rfuchs** [comment]
The best way to do this is probably to hand-craft an SDP with a black-hole endpoint address (e.g. localhost port 9) and run that through rtpengine like a regular answer and then use the output SDP.

**Comment by babarShahzad** [comment]
> 
> 
> hi yep
> I've made it working
> I just landed a request on my Kamailio and generated a response with proper SDP.

@ovoshlook 
Would you please kindly share sample part of script for doing this or guide us how can we achieve this any help would be appreciated  ?

**Comment by babarShahzad** [comment]
> 
> 
> > hi yep
> > I've made it working
> > I just landed a request on my Kamailio and generated a response with proper SDP.
> 
> @ovoshlook
> Would you please kindly share sample part of script for doing this ?
> 
> Regards
> Shirazi

@bshirazi i have used this small code snippet on initial invite and it fulfill our need of playing early media without having bParty.

route[early_media] {
	xlog("kalsym: handling early_media\n");
	rtpengine_manage();
	$var(body)= $(rb{re.subst,/(IP4.).*/\192.168.129.129/g});
	set_reply_body($var(body), "application/sdp");
	t_send_reply("183", "Session Progress");
   	xlog("kalsym: method was invite playing media hello.wav\n");
        unblock_dtmf("all");
	play_media("file=/usr/share/media/hello.wav");
}

@rfuchs could you please help me out how to get dtmf during early media ?  
i can only get dtmf when call bridges between aPArty and bParty.

**Comment by rfuchs** [comment]
What do you mean with "get DTMF?"

**Comment by babarShahzad** [comment]
> 
> 
> What do you mean with "get DTMF?"

let me explain my scenario.
i have to play media to calling party and he will give his input as dtmf for further call processing.

for example: caller listen a prompt "xyz are the charges of the call if you want to continue call please input 1 or to cancel input any other value." once calling party gives his input i will store his input some where and will finish the call session immediately

**Comment by rfuchs** [comment]
This isn't really a supported use case, but we do have the DTMF logging option that can be enabled. AFAIK it only works on RFC event packets and not PCM DTMF tones. And I'm not sure if it works during a media playback without a real B party (even though I assume your synthesised SDP would count as a B party).

**Comment by babarShahzad** [comment]
> 
> 
> This isn't really a supported use case, but we do have the DTMF logging option that can be enabled. AFAIK it only works on RFC event packets and not PCM DTMF tones. And I'm not sure if it works during a media playback without a real B party (even though I assume your synthesised SDP would count as a B party).

@rfuchs thanks for your kind response 
can i achieve this with following options
Kamailio for SIP PLANE + RTPEngine for Media PLANE + Asterisk for Call handling (get dtmf on early media , hangup call etc)

**Comment by ot-i-to** [comment]
working example [https://sysinfo.pro/e/ru/VoIP/OpenSIPs/os_rtpengine_nat](url)

**Comment by davidcsi** [comment]
@bshirazi could you please plaster what you did that works for you? I'm interested in the same scenario but I can't make it work.

Thanks!

**Comment by fuine6** [comment]
OpenSIPS + RTPengine in a NAT environment, playing media without a callee.

```
route[play_media_without_callee] {
        rtpengine_use_set(0);
        rtpengine_offer("replace-origin media-address=PUBLIC_IP");

        # Use $rtpquery to find the caller’s RTP port.
        $var(local_rtp_port) = NULL;
        $var(local_rtcp_port) = NULL;
        $json(rtp_reply) := $rtpquery;
        for ($json(media) in $(json(rtp_reply/tags/$ft/medias)[*])) {
                if($json(media/type) == "audio") {
                        for ($json(stream) in $(json(media/streams)[*])) {
                                for ($var(flag) in $(json(stream/flags)[*])) {
                                        if($var(flag) == "RTP") {
                                                $var(local_rtp_port) = $json(stream/local port);
                                        }

                                        if($var(flag) == "RTCP") {
                                                $var(local_rtcp_port) = $json(stream/local port);
                                        }
                                }
                        }
                }
        }

        # I believe that RTPengine will not start endpoint learning before receiving the answer, so you need to send a fake answer before calling play_media.
        route(http_rtpengine_answer);

        # Customize this section
        $var(answer_sdp) = "v=0\r\n" +
                "o=noreply 0 0 IN IP4 PUBLIC_IP\r\n" +
                "s=Talk\r\n" +
                "c=IN IP4 PUBLIC_IP\r\n" +
                "t=0 0\r\n" +
                "a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics\r\n" +
                "m=audio " + $var(local_rtp_port) + " RTP/AVP 96 9 3 8 0 101\r\n" +
                "a=rtpmap:96 BV16/8000\r\n" +
                "a=rtpmap:101 telephone-event/8000\r\n" +
                "a=rtcp:" + $var(local_rtcp_port) + "\r\n" +
                "a=rtcp-fb:* trr-int 1000\r\n" +
                "a=rtcp-fb:* ccm tmmbr\r\n";

        append_to_reply("Content-Type: application/sdp\r\n");
        t_reply_with_body(183, "Session Progress", $var(answer_sdp));

        rtpengine_use_set(0);
        rtpengine_play_media("to-tag=$ft repeat-times=1 file=/audio.wav");
}

########################################################################
# OpenSIPS’s rtpengine_answer is not allowed in the initial INVITE, so I call rtpengine directly.
# Reference: https://github.com/OpenSIPS/opensips/blob/3.6.1/modules/rtpengine/rtpengine.c#L3946
########################################################################
route[http_rtpengine_answer] {

        # https://rtpengine.readthedocs.io/en/latest/http_websocket_support.html#ng-protocol-interface
        $var(url) = "http://172.16.0.1:12224/ng";

        $json(rtpengine_answer_request) := "{}";
        $json(rtpengine_answer_request/command) = "answer";
        $json(rtpengine_answer_request/call-id) = $ci;
        $json(rtpengine_answer_request/from-tag) = $ft;
        $json(rtpengine_answer_request/to-tag) = $uuid;
        $json(rtpengine_answer_request/media-address) = "PUBLIC_IP";
        $json(rtpengine_answer_request/replace) := '["origin"]';
        $json(rtpengine_answer_request/received-from) := '["IP4","xxx.xxx.xxx.xxx"]';

        $var(sdp_body) = "v=0\r\n" +
                "o=t1709110059 2969 431 IN IP4 192.168.0.100\r\n" +
                "s=Talk\r\n" +
                "c=IN IP4 192.168.0.100\r\n" +
                "t=0 0\r\n" +
                "m=audio 7078 RTP/AVP 0 8 9 101\r\n" +
                "a=rtpmap:101 telephone-event/8000\r\n";

        $json(rtpengine_answer_request/sdp) = $var(sdp_body);

        $var(cookie_uuid) = $uuid;
        $var(request_body) = $var(cookie_uuid) + " " + $json_compact(rtpengine_answer_request);

        $var(rc) = rest_post($var(url), 
                $var(request_body),
                "application/x-rtpengine-ng",
                $var(body),
                $var(ct), 
                $var(rcode));
}
```
