### ISSUE TITLE
how to transcode 2833 from sender to PCMU/tones (and sending them back 2833)

### ISSUE THREAD

**Issue by davehorton** [sipwise/rtpengine#871]
I have a SIP endpoint sending me an SDP with PCMU and RFC 2833.  The stream is going to pass through rtpengine and go to a media server that must receive inband tones (no RFC 2833).  So what I want to achieve is this:

1. sender sends INVITE with PCMU & 2833
2. I call rtpengine 'offer' requesting it to transcode 2833 to tones
3.  I send INVITE to media server, get 200 OK back with only PCMU
4.  I call rtpengine 'answer' with that SDP requesting it to transcode tones back to RFC 2833
5.  I send 200 OK back to sender with that sdp, which accepts 2833

I have it working properly except for step 4&5.  When I call 'answer', feeding in an SDP offering only PCMU, I get back an SDP with only PCMU -- I wanted 2833 added in.

I've followed the instructions as to DTMF transcoding on the README, so I am creating this issue asking for a bit more help.

Here is a [gist](https://gist.github.com/davehorton/e8345d0fd5b286c718076867df99c952) showing the debug rtpengine log with my 'offer' and 'answer' commands.  Again, the outcome I am looking for is that the sdp coming back from 'answer' has telephone-event added back in.

**Comment by rfuchs** [comment]
The option `strip=all` in your offer doesn't do what you want to do. If you strip a codec, rtpengine behaves as if it wasn't there at all. IOW rtpengine will not know that it can do RFC DTMF output towards A. You should use `mask=all` instead (or some combination of the flags, depending on your exact use case).

**Comment by davehorton** [comment]
hmm, I tried using `mask=all` on my initial offer, but that made things worse.  Now the SDP I get back from that 'offer' command _does_ still include 2833.  I want an SDP back from the offer that I can send to my PCMU-only media server.

I've updated the [gist](https://gist.github.com/davehorton/e8345d0fd5b286c718076867df99c952) to show the latest logs ("using mask instead of strip")

**Comment by rfuchs** [comment]
Ok, so `offer` as a counteraction to `mask` isn't supported. Instead you have to add the codec back as a `transcode` codec. Or be more specific about what to do with each codec. So for example `codec-mask=all codec-transcode=PCMU` or `codec-mask=telephone-event codec-strip=G729` (both with `always-transcode`)

Also, don't use any transcoding options in your `answer`. They're ignored in newer versions of rtpengine, but can confuse it in older versions.

**Comment by davehorton** [comment]
Many thanks for your helpful responses.  I ended up using 
```
{
  flags: ['asymmetric', 'always transcode']
},
{
  codec: {
    mask: ['all'],
    transcode: ['PCMU']
  }
}
```
in my offer and that did the trick.
