### ISSUE TITLE
RTP Engine RTP Redundancy Does not Work when servers are behind NAT. 

### ISSUE THREAD

**Issue by pateldp** [sipwise/rtpengine#872]
I'm using rtpengine with redis pubsub support to achieve HA in aws servers which are behind NAT. This setup already works in my other project which works fine but difference is they are not behind NAT.
- In Current Setup using Elastic IP and monitor the rtpengine using pacemaker. rtpengine is added as a resource to monitor.
- I configured rtpengines with following way.

AWS-1

OPTIONS=--interface 172.31.22.47![ELASTIC IP] --interface pub1/172.31.20.244![ELASTIC IP]  pub2/172.31.22.47![ELASTIC IP] --redis=172.31.20.244:6379/1 --listen-ng 127.0.0.1:22222 -m 10000 -M 50000  --listen-cli 127.0.0.1:9900 --log-facility=local1 -L 7 subscribe-keyspace=2

AWS-2

OPTIONS=--interface 172.31.22.47![ELASTIC IP]  --interface pub2/172.31.22.47![ELASTIC IP]  --interface pub1/172.31.20.244![ELASTIC IP]  --redis=172.31.20.244:6379/2 --listen-ng 127.0.0.1:22222 -m 10000 -M 50000  --listen-cli 127.0.0.1:9900 --log-facility=local1 -L 7 subscribe-keyspace=1

In Redis Configuration i set the following parameter to enable notify.
notify-keyspace-events "AKE"

I did not find any errors in both redis server and rtpengine.

Is this wrongly configured rtpengine or this is not possible in case of behind NAT servers.

**Comment by rfuchs** [comment]
And what exactly is it that doesn't work?

**Comment by pateldp** [comment]
> And what exactly is it that doesn't work?

Actually, i want to redundant my RTP on both the Active Passive node of HA using pacemaker. I did not get foreign sessions using above configuration in rtpengine in aws servers which are behind NAT.

**Comment by rfuchs** [comment]
It should work the same regardless of whether NAT is configured or not.

**Comment by pateldp** [comment]
Hello @rfuchs,
Yes, it should work but can you help me out how can i configure the rtpengine behind NAT?
i configured my rtpengine following on both aws servers, Anything wrong in this configuration ?

AWS-1

OPTIONS=--interface 172.31.22.47![ELASTIC IP] --interface pub1/172.31.20.244![ELASTIC IP] pub2/172.31.22.47![ELASTIC IP] --redis=172.31.20.244:6379/1 --listen-ng 127.0.0.1:22222 -m 10000 -M 50000 --listen-cli 127.0.0.1:9900 --log-facility=local1 -L 7 subscribe-keyspace=2

AWS-2

OPTIONS=--interface 172.31.22.47![ELASTIC IP] --interface pub2/172.31.22.47![ELASTIC IP] --interface pub1/172.31.20.244![ELASTIC IP] --redis=172.31.20.244:6379/2 --listen-ng 127.0.0.1:22222 -m 10000 -M 50000 --listen-cli 127.0.0.1:9900 --log-facility=local1 -L 7 subscribe-keyspace=1

In Redis Configuration i set the following parameter to enable notify.
notify-keyspace-events "AKE"

Can i provide more information other than this which helps me to figure it out.

**Comment by rfuchs** [comment]
Yes, this is how you configure it behind NAT. Looks OK to me. I can't give any better advice without knowing what exactly doesn't work, or what your use cases look like. The duplicated IP address between the default interface and `pub2` looks somewhat strange, as does the different ordering in the interfaces between the two instances. And I assume you actually have two dashes `--` before `subscribe-keyspace` ?

**Comment by rfuchs** [comment]
Cleaning up old tickets
