### ISSUE TITLE
Mixed call has lose data while seperated stayed fine

### ISSUE THREAD

**Issue by idoMajor41** [sipwise/rtpengine#873]
Hello everyone, 

My current environment:
- RTPEngine version 7.5.0.0
- AWS Ubuntu Server 18.04 LTS
- VMWare of Ubuntu Server 18.04 LTS

I've installed an environment with RTPEngine which runs on AWS EC2.
I've also installed a local environment using virtual machines.
On the environment of the virtual machines I'm not receiving any problems and I get perfectly fine separated and mixed files.
On the environment which resides on AWS EC2, the mixed file has incomplete data in it or simply distorted in terms of missing frames or some other reason.

What I'm doing with RTPEngine is getting RTP data off course, and save it to .wav files.
While I've stored it, I'm receiving the data which I can see it using wireshark, after i issued tcpdump -i 'interface-name' -w pcap_file.pcap.

When i used the Telephone->RTP analyze tool, I've heard the audio perfectly fine.
The .wav file on the machine it self which were 3 were good for both sides of the conversation.
But, when I ran the *-mix.wav file, it wasn't that perfect in terms of audio data once I heard it.
So I think the reason behind it might be the mixing itself of the 2 RTP connections into 1 .wav file.

I saw on other issues in the past, about the fact of mismatching versions of the libav.
So I saw that both my local virtual machine and my EC2 machine were both equally in all packages relevant to the RTPEngine.

I'm trying to understand the following:
1. How can I solve the problem with my distorted mix file.
2. How can I activate the logs for the RTPEngine, so I could see any bugs if it has any.
I haven't found them using journatlctl/(/var/log/rtpengine...)/rtpengine --log-level=x.
3. Is there a chance to better the sound quality in other terms other than resampling?
Once I've changed the resampling from 8000 to 16000, the files got bigger and the audio got a lot better.
4. Is there a chance that it could be related to timestamp problems with the RTP stream itself, once the mixer mix both streams?

These are my configurations:
**/etc/rtpengine/rtpengine.conf**
```
[rtpengine]

table = 0
# no-fallback = false
### for userspace forwarding only:
# table = -1

### a single interface:
interface = 192.168.10.50
### separate multiple interfaces with semicolons:
# interface = internal/12.23.34.45;external/23.34.45.54
### for different advertised address:
# interface = 12.23.34.45!23.34.45.56



listen-ng = 127.0.0.1:22222
# listen-tcp = 25060
listen-udp = 12222

timeout = 60
silent-timeout = 3600
tos = 184
#control-tos = 184
# delete-delay = 30
# final-timeout = 10800

# foreground = false
# pidfile = /run/ngcp-rtpengine-daemon.pid
# num-threads = 16

port-min = 16384
port-max = 32766
# max-sessions = 5000

recording-dir = /var/spool/rtpengine
recording-method = proc
recording-format = raw

# redis = 127.0.0.1:6379/5
# redis-write = password@12.23.34.45:6379/42
# redis-num-threads = 8
# no-redis-required = false
# redis-expires = 86400
# redis-allowed-errors = -1
# redis-disable-time = 10
# redis-cmd-timeout = 0
# redis-connect-timeout = 1000

# b2b-url = http://127.0.0.1:8090/
# xmlrpc-format = 0

# log-level = 6
# log-stderr = false
# log-facility = daemon
# log-facility-cdr = local0
# log-facility-rtcp = local1

# graphite = 127.0.0.1:9006
# graphite-interval = 60
# graphite-prefix = foobar.

# homer = 123.234.345.456:65432
# homer-protocol = udp
# homer-id = 2001

# sip-source = false
# dtls-passive = false

[rtpengine-testing]
table = -1
interface = 10.15.20.121
listen-ng = 2223
foreground = true
log-stderr = true
log-level = 7
```

**/etc/rtpengine/rtpengine-recording.conf**

```
[rtpengine-recording]
table = 0
output-format = wav
output-mixed = 1
resample-to = 16000
log-level = 1
output-single = 1
spool-dir = /var/spool/rtpengine
output-dir = /var/spool/rtpengine
```

**/etc/default/ngcp-rtpengine-daemon**

```
RUN_RTPENGINE=yes
LISTEN_UDP=12222
LISTEN_NG=22222
LISTEN_CLI=9900
INTERFACES="internal/127.0.0.1!192.168.10.50 external/192.168.10.50"
TIMEOUT=60
SILENT_TIMEOUT=3600
PIDFILE=/var/run/ngcp-rtpengine-daemon.pid
FORK=yes
TABLE=0
PORT_MIN=16384
PORT_MAX=32766

CONFIG_FILE=/etc/rtpengine/rtpengine.conf
# CONFIG_SECTION=rtpengine
#MANAGE_IPTABLES=yes
#SET_USER=root
#SET_GROUP=root # GROUP only needs to be set if USER is not set or if the user isn't in the group
```

**/etc/default/ngcp-rtpengine-recording-daemon**

```
TABLE=0
RUN_RTPENGINE_RECORDING=yes
CONFIG_FILE=/etc/rtpengine/rtpengine-recording.conf
CONFIG_SECTION=rtpengine-recording
PIDFILE=/run/ngcp-rtpengine-recording-daemon.pid
RECORDING_DIR=/var/spool/rtpengine/
RECORDING_METHOD=proc

#SET_USER=root
#SET_GROUP=root # GROUP only needs to be set if USER is not set or if the user isn't in the group
#
MUST_NFS=no
NFS_HOST=192.168.1.1
NFS_REMOTE_PATH=/var/recordings
NFS_LOCAL_MOUNT=/var/lib/rtpengine-recording # must match output-dir if used
NFS_OPTIONS=hard,intr,tcp
```

I hope the post is quite informative and if anything is missing I'll gladly try to add the required data of config.
I tried to look at other issues in order to drill down deeply on the problem but I haven't found another clue to continue researching this problem.

Thank you very much heads up! :)

**Comment by rfuchs** [comment]
Which version are you running?

**Comment by idoMajor41** [comment]
> Which version are you running?

I've updated the main post :)

**Comment by rfuchs** [comment]
A specific commit or tagged release version would have been more helpful, because a similar issue has just been recently fixed, see https://github.com/sipwise/rtpengine/issues/861#event-2787961701

**Comment by idoMajor41** [comment]
The commit I've took is 2397723.
I've just also checked the last commit which is the current version on master and also experienced with the same problem 😅

**Comment by rfuchs** [comment]
In that case a pcap with sample data to reproduce the issue would be needed

**Comment by idoMajor41** [comment]
I've included a zip file which has the pcap from the AWS machine, which receives the SIP-REC session and as well the RTP itself.
The voice is still distorted and I've used for this test the following configuration for the /etc/rtpengine/rtpengine-recording.conf file:


```
[rtpengine-recording]
table = 0
output-format = wav
output-mixed = 1
resample-to = 16000
log-level = 1
spool-dir = /var/spool/rtpengine
output-dir = /var/spool/rtpengine
```


[test_output.zip](https://github.com/sipwise/rtpengine/files/3862801/test_output.zip)

**Comment by rfuchs** [comment]
First thing you should do is not put the spool files in the same directory as the output files. That might just fix all your issues.

**Comment by idoMajor41** [comment]
> First thing you should do is not put the spool files in the same directory as the output files. That might just fix all your issues.

I just added in my configuration the following change:


```
[rtpengine-recording]
table = 0
output-format = wav
output-mixed = 1
output-single = 1
resample-to = 16000
log-level = 1
spool-dir = /var/spool/rtpengine
output-dir = /var/spool/rtpengine/myrecordings

```


As a result I've got the files attached in the comment.
I had inside myrecordings dir 3 .wav files of each stream and the mixed one.
In the root directory of /var/spool/rtpengine i got another mix file which was smaller by half from the mix file inside myrecordings dir.


[AWS-SPOOL-DIR-TEST-GITHUB.zip](https://github.com/sipwise/rtpengine/files/3864298/AWS-SPOOL-DIR-TEST-GITHUB.zip)

**Comment by rfuchs** [comment]
The spool dir of the recording daemon has to match the recording dir of the main rtpengine daemon, otherwise those two components don't communicate.

If you still got an output file in /var/spool/rtpengine with the above config, then you must have another instance of the recording daemon with a different config running, or something like that. The recording daemon does not save output files into the spool directory.

**Comment by idoMajor41** [comment]
> The spool dir of the recording daemon has to match the recording dir of the main rtpengine daemon, otherwise those two components don't communicate.
> 
> If you still got an output file in /var/spool/rtpengine with the above config, then you must have another instance of the recording daemon with a different config running, or something like that. The recording daemon does not save output files into the spool directory.

What about another files?
Does the ngcp-rtpengine-recording-daemon needs to address the same dir which rtpengine-recording.conf and rtpengine.conf are configured?

**Comment by idoMajor41** [comment]
As well, I've wrote in other comments - is there a chance you tell me how to see logs of the rtpengine and rtpengine-recording daemons? :)

**Comment by idoMajor41** [comment]
> The spool dir of the recording daemon has to match the recording dir of the main rtpengine daemon, otherwise those two components don't communicate.
> 
> If you still got an output file in /var/spool/rtpengine with the above config, then you must have another instance of the recording daemon with a different config running, or something like that. The recording daemon does not save output files into the spool directory.

I've made the change you mentioned and the voice does sound better now.
The problem is it's not that good comparing to the single outputs.
Also, it doesn't record the entire call, it cuts a few seconds out of it.

Please tell me you have a suggestion :) 
BTW, including the output .wav files from this test , if you want to checkout something special about them in terms of sound graph.

[4th-test.zip](https://github.com/sipwise/rtpengine/files/3864554/4th-test.zip)

**Comment by rfuchs** [comment]
Logs are written according to you syslog config, usually /var/log/daemon.log on Debian systems.

To repeat:
The `recording-dir` of rtpengine has to match the `spool-dir` of rtpengine-recording.
The `output-dir` of rtpengine-recording has to be a different dir.
Ideally neither should be a subdirectory of the other.
If you're referring to the /etc/default/ file, that is for the NFS mount and is optional.

There can only be a single instance of the recording daemon running. Have you figured out (and fixed) why you were still getting output files in the spool directory? There is no point in looking further unless you have a clean setup.

**Comment by idoMajor41** [comment]
> Logs are written according to you syslog config, usually /var/log/daemon.log on Debian systems.
> 
> To repeat:
> The `recording-dir` of rtpengine has to match the `spool-dir` of rtpengine-recording.
> The `output-dir` of rtpengine-recording has to be a different dir.
> Ideally neither should be a subdirectory of the other.
> If you're referring to the /etc/default/ file, that is for the NFS mount and is optional.
> 
> There can only be a single instance of the recording daemon running. Have you figured out (and fixed) why you were still getting output files in the spool directory? There is no point in looking further unless you have a clean setup.

I'll run another few tests to check if everything is as it should be and I'll comment
