### ISSUE TITLE
rtpengine delete entire call in case we try to delete specific via-branch

### ISSUE THREAD

**Issue by sem32** [sipwise/rtpengine#875]
Hi there!

We have an issue in following case:
- UserA have WebRTCPhone
- UserB have WebRTCPhone + HardwarePhone
- Forked call to two UAs and answer on one of them
```
A => INVITE -> KAMAILIO -> INVITE => B (web) [via-branch: XXX.1]
               KAMAILIO -> INVITE => B (hardware) [via-branch: XXX.0]
A <= 200 OK <- KAMAILIO <- 200OK <= B (hardware)
               KAMAILIO -> CANCEL => B (web)
               KAMAILIO <- 487 <= B (web) --- here we do rtpengine delete for via-branch: XXX.1
```
In last step we do rtpengine delete for via-branch: XXX.1 but rtpengine **deleting entire call**

After some research this issue start to reproduced after [commit](https://github.com/sipwise/rtpengine/commit/b79295518807f75d68e7d39316986a14d3b797db), but without this changes we have open RTP ports after 487 for each branches for call, as it was in sipwise/rtpengine/issues/840
Seems that we should delete and free resources only for deleting monologue by branch. 
Am I do something wrong?

rtpengine -v
Version: 8.0.1.1+0~mr8.0.1.1 git-mr8.0.1-9839f95

[Full log](https://github.com/sipwise/rtpengine/files/3850347/rtpengine_mr8.0.1-9839f95.txt)

Thanks in advance for the help!
Regards, Semen

**Comment by rfuchs** [comment]
Looks like the previous commit (the one you references) wasn't quite correct. I've pushed an updated one (see above) which actually reverts that previous commit and adds a different approach. This should cover both cases. Please try and let me know.

**Comment by sem32** [comment]
Hi Richard!

Thanks a lot for your fast reaction and for your time.

Your patch works.
1. After CANCEL from UserA all sessions are closed - OK
2. After answer (200 OK) from UserB and CANCEL of all forked sessions media exists - OK

Small issue for case 2: RTPEngine don't free resources for deleted monologue till call will be ended (in netstat I see a batch of ports, allocated for deleted monologues)

Thank you!
Regards, Semen

**Comment by rfuchs** [comment]
That's by design. All resources are freed only at the end of the call.

**Comment by sem32** [comment]
Thank you very much!
