### ISSUE TITLE
metadata with no SDP for pcap recording start after the call was connected

### ISSUE THREAD

**Issue by adil-mafzool** [sipwise/rtpengine#877]
We are experiencing issues for pcap recording enabled with start_recording but meta file generated doesn't contain any SDP information.

```
rtpengine-media-01:~$ cat /var/recordings/metadata/rtpengine-meta-3534005291%40172.31.12.17-b8e4f69c4b576f8b.txt
/var/recordings/pcaps/3534005291%40172.31.12.17-b8e4f69c4b576f8b.pcap

Timestamp terminated ms(first monologue): 1573834985759.423

call start time: 2019-11-15T16:22:58
call end time: 2019-11-15T16:23:05
```

**Comment by rfuchs** [comment]
Post a debug log?

**Comment by adil-mafzool** [comment]
Please log attached.. Its log with level 6 for the call-id: 3534005291@172.31.12.17 

[no_sdp_in_metadata.zip](https://github.com/sipwise/rtpengine/files/3852482/no_sdp_in_metadata.zip)

**Comment by rfuchs** [comment]
Ok, that's because you turn on call recording after the offer/answer. Rtpengine only writes the SDP bodies to the metadata file as they're passing through, when and if recording is already in effect.

**Comment by adil-mafzool** [comment]
Yes i know thats why... is it possible we can implement sdp_before for pcap and call it for start_recording ?

**Comment by rfuchs** [comment]
Not easily as rtpengine doesn't currently remember SDP bodies for that purpose.

**Comment by adil-mafzool** [comment]
where sdp stored in rtpengine for the call? which can be extracted into pcap_meta_finish_file function.

**Comment by rfuchs** [comment]
The SDP is not stored at all, which is the problem.

**Comment by adil-mafzool** [comment]
can we store into struct call two str variable of offer_sdp and answer_sdp?

**Comment by rfuchs** [comment]
Possibly yes. Pull requests welcome :)

**Comment by adil-mafzool** [comment]
Which function rtpengine has receiving raw sdp from kamailio for offer/answer?

**Comment by rfuchs** [comment]
call_offer_answer_ng() in call_interfaces.c

**Comment by adil-mafzool** [comment]
Isn't recording doesn't use the raw sdp.. rather it uses returned sdp for recording purpose to avoid encrypted sdp

**Comment by rfuchs** [comment]
Sorry I don't understand the question?

**Comment by adil-mafzool** [comment]
Sdp written in the metadata file isn’t the raw sdp rather the returned sdp from RTPEngine

**Comment by rfuchs** [comment]
Both are supported as hooks in the code, `sdp_before` and `sdp_after`, look for it in the code

**Comment by rfuchs** [comment]
Cleaning up old tickets
