### ISSUE TITLE
feature request: Combine two inputs into one stereo output 

### ISSUE THREAD

**Issue by sashasaturn** [sipwise/rtpengine#878]
Hello,

I have a question regarding possible support of upsampling two mono inputs into a  resulting file in stereo format. Is that something that you have on your road map?

Thanks,

Alex

**Comment by rfuchs** [comment]
No we don't have any such plans. However it shouldn't be too difficult to do by replacing the `amix` filter with a `join` or `amerge` filter.

**Comment by sashasaturn** [comment]
@rfuchs  thanks for the answer.

Can I assume that it should be done in mix.c in the line  

const AVFilter *flt = avfilter_get_by_name("amix");

Thanks,

Alex

**Comment by rfuchs** [comment]
That would be the right place, yes

**Comment by sashasaturn** [comment]
@rfuchs  

I've tried to use both amerge and join, unfortunately, they both still produce mono.

Any other ideas?

Thanks a lot,

Alex

**Comment by sashasaturn** [comment]
Hi @rfuchs, 

Sorry to bother you, I did more tests with different filters and all produced files are mono. 

Can I assume that we also have to pass 'channel_layouts=stereo' somewhere in mix.c?

Thanks,

Alex

**Comment by rfuchs** [comment]
Probably yes. There's examples of how to set options within the same code, i.e. where "inputs=%lu" is set for amix.

**Comment by sashasaturn** [comment]
@rfuchs  so I did the following

        // amix
        err = "no amix filter available";
        const AVFilter *flt = avfilter_get_by_name("join");
        if (!flt)
                goto err;

        snprintf(args, sizeof(args), "inputs=%lu:channel_layout=0x%"PRIx64, (unsigned long) NUM_INPUTS, (uint64_t)AV_CH_LAYOUT_STEREO);
        err = "failed to create amix filter context";
        if (avfilter_graph_create_filter(&mix->amix_ctx, flt, NULL, args, NULL, mix->graph))
                goto err;

and the output is still mono ... 

I also checked the documentation here https://ffmpeg.org/ffmpeg-filters.html#join and looks like for join filter and according to documentation channel_layout is the desired output channel layout. It defaults to stereo.

What I'm missing?

Thank in advance,

Alex

**Comment by sashasaturn** [comment]
So I've added a variable
#define VCHANNELMAP "0.0-FL|1.0-FR"

and added this variable to  avfilter_get_by_name("join")

const AVFilter *flt = avfilter_get_by_name("join");
        if (!flt)
                goto err;

        snprintf(args, sizeof(args), "inputs=%lu:map=%s:channel_layout=0x%" PRIx64, (unsigned long) NUM_INPUTS, VCHANNELMAP, (uint64_t)AV_CH_LAYOUT_STEREO);
        err = "failed to create amix filter context";

In debug logs I'm seeing the following

 [mix.c:112] init input ctx 0
 av_log: Setting 'time_base' to value '1/16000'
 av_log: Setting 'sample_rate' to value '16000'
 av_log: Setting 'sample_fmt' to value 's32p'
 av_log: Setting 'channel_layout' to value '0x4'
 av_log: tb:1/16000 samplefmt:s32p samplerate:16000 chlayout:0x4
[mix.c:112] init input ctx 1
[mix.c:112] init input ctx 2
[mix.c:112] init input ctx 3
av_log: query_formats: 6 queried, 15 merged, 0 already done, 0 delayed
av_log: mappings:
av_log: 0.FC => FL
1.FC => FR
av_log:
av_log: No channels are used from input stream 2.
av_log: No channels are used from input stream 3.

And as a result .... again mono

So I went back to https://trac.ffmpeg.org/wiki/AudioChannelManipulation#Remapchannels to section 2 x mono -> stereo  and join is described as following

ffmpeg -i left.mp3 -i right.mp3 -filter_complex "[0:a][1:a]join=inputs=2:channel_layout=stereo[a]" -map "[a]" output.mp3

If I understand this correctly currently I have join=inputs=2:channel_layout=stereo via   snprintf(args, sizeof(args), "inputs=%lu:map=%s:channel_layout=0x%" PRIx64,  however the importent part of proper mapping is missing  [0:a][1:a]j ..... [a] -map "a"

Again looks like I cannot [0:a][1:a]j ..... [a] -map "a" as addon to argument.

Can you please help to understand what needs to be added?

Thanks,

Alex

**Comment by rfuchs** [comment]
Sorry but I don't have any experience with this myself, so I can't provide any help. The only thing that comes to mind is that the output itself (meaning the file being written to) is configured through `output_config()` (in `decoder_got_frame()`) and this happens before the mixer is configured. So I assume that this needs to be forced to be stereo as well.

The mapping itself I assume to be already taken care of through `avfilter_link`, same as for amix.

**Comment by sashasaturn** [comment]
@rfuchs  BIG thank you,  output_config () was exactly the place ...

For those who probably also want to have stereo recording output with RTPEngine:

**recording-daemon/decoder.c**

 // we can now config our output, which determines the sample format we convert to
        format_t out_format = {
                .clockrate = clockrate,
                .channels = **2**,
                .format = -1,
        };

- **recording-daemon/mix.c**

#define VCHANNELMAP "0.0-FL|1.0-FR"
....
const AVFilter *flt = avfilter_get_by_name("join");
        if (!flt)
                goto err;
        snprintf(args, sizeof(args), "inputs=%lu:map=%s:channel_layout=0x%" PRIx64, (unsigned long) NUM_INPUTS, VCHANNELMAP, (uint64_t)AV_CH_LAYOUT_STEREO);
        err = "failed to create amix filter context";



Again, @rfuchs thank you very much and I really appreciate all your help!

Thanks,

Alex

**Comment by rfuchs** [comment]
Would you be able to package this into a proper pull request with a config option to turn this feature on and off?

**Comment by sashasaturn** [comment]
@rfuchs, unfortunately, my programming skills are very poor, but I will try to do my best to prepare a pull request

**Comment by rfuchs** [comment]
Supported as of a5d283761
