### ISSUE TITLE
no available proxies

### ISSUE THREAD

**Issue by nicoonline** [sipwise/rtpengine#882]
Hello,

I got those logs today multiple times.

Nov 25 15:02:33 proxy1 /usr/sbin/kamailio[25213]: ERROR: rtpengine [rtpengine.c:2744]: send_rtpp_command(): timeout waiting reply for command "offer" from RTP proxy <udp:127.0.0.1:9999>
Nov 25 15:02:33 proxy1 /usr/sbin/kamailio[25213]: ERROR: rtpengine [rtpengine.c:2440]: rtpp_function_call(): no available proxies
Nov 25 15:02:36 proxy1 /usr/sbin/kamailio[25211]: ERROR: rtpengine [rtpengine.c:2440]: rtpp_function_call(): no available proxies
Nov 25 15:02:39 proxy1 /usr/sbin/kamailio[25210]: ERROR: rtpengine [rtpengine.c:2440]: rtpp_function_call(): no available proxies
Nov 25 15:02:39 proxy1 /usr/sbin/kamailio[25211]: ERROR: rtpengine [rtpengine.c:2440]: rtpp_function_call(): no available proxies

in rtpengine.log:
Nov 25 15:02:34 proxy1 rtpengine[1453]: INFO: Detected command from 127.0.0.1:59454 as a duplicate
Nov 25 15:02:34 proxy1 rtpengine[1453]: INFO: Detected command from 127.0.0.1:59454 as a duplicate
Nov 25 15:02:34 proxy1 rtpengine[1453]: INFO: Increasing timer run interval to 2 seconds
Nov 25 15:02:34 proxy1 rtpengine[1453]: INFO: Detected command from 127.0.0.1:59454 as a duplicate
Nov 25 15:02:34 proxy1 rtpengine[1453]: INFO: Detected command from 127.0.0.1:59454 as a duplicate
Nov 25 15:02:36 proxy1 rtpengine[1453]: INFO: Decreasing timer run interval to 1 seconds

Maybe all rtpengine processes are busy ?

**Comment by nicoonline** [comment]
any  helps on this ? I should increase the number of threads?

**Comment by rfuchs** [comment]
Can't really say. Duplicate or lost messages over localhost are very unusual. Do you perhaps have a firewall script that's interfering with UDP over localhost?

**Comment by nicoonline** [comment]
No. Iptables doesn't interfer with localhost.

**Comment by nicoonline** [comment]
Logs from today :
[root@proxy1 ~]# grep duplicate /var/log/rtpengine.log
Nov 26 07:11:22 proxy1 rtpengine[1453]: INFO: Detected command from 127.0.0.1:56499 as a duplicate
Nov 26 07:41:39 proxy1 rtpengine[1453]: INFO: Detected command from 127.0.0.1:56499 as a duplicate
Nov 26 07:41:39 proxy1 rtpengine[1453]: INFO: Detected command from 127.0.0.1:56499 as a duplicate
Nov 26 07:46:47 proxy1 rtpengine[1453]: INFO: Detected command from 127.0.0.1:37185 as a duplicate
Nov 26 09:36:45 proxy1 rtpengine[1453]: INFO: Detected command from 127.0.0.1:37185 as a duplicate
Nov 26 13:24:54 proxy1 rtpengine[1453]: INFO: Detected command from 127.0.0.1:59454 as a duplicate
Nov 26 13:24:54 proxy1 rtpengine[1453]: INFO: Detected command from 127.0.0.1:59454 as a duplicate
Nov 26 13:24:54 proxy1 rtpengine[1453]: INFO: Detected command from 127.0.0.1:59454 as a duplicate
Nov 26 13:24:54 proxy1 rtpengine[1453]: INFO: Detected command from 127.0.0.1:59454 as a duplicate

**Comment by nicoonline** [comment]
I saw somewhere that number of threads= number of cpu => i have 4 cpu.
Can  i try to add more threads in the config file?.

**Comment by rfuchs** [comment]
You can have as many threads as you want, but that would only make a difference if either the CPU is maxed out (and then it wouldn't really solve the problem), or if the process is blocked in some way, which should never happen. But feel free to try.

You can use a packet dump (tcpdump or Wireshark) on UDP port 9999 to see what's happening with those control messages. The important distinction is whether rtpengine is really slow to respond, or if it's rather the messages getting lost somewhere.

**Comment by bazrafshanmh** [comment]
something to write.
