### ISSUE TITLE
rtpengine-recording daemon and transcoding feature

### ISSUE THREAD

**Issue by tiglat** [sipwise/rtpengine#883]
Hello!

According to the spec file rtpengine-recording daemon is built and installed under with_transcoding define. But it looks like the transcoding feature does not require the rtpengine-recording daemon.

Does rtpengine transcoding feature use rtpengine-recording daemon?

Thank you.
Best regards.

**Comment by rfuchs** [comment]
No it does not. But they both use the same code base that provides the transcoding engine.
