### ISSUE TITLE
High CPU issue on Version: 7.3.0.0+0 :Too many packets in UDP receive queue (more than 50), aborting loop. 

### ISSUE THREAD

**Issue by jonhvoxbox** [sipwise/rtpengine#885]
Hi Guys,

We are using rtpengine to bridge between networks(external and internal) using kamailio 5.2 on ubuntu 18.04.3 LTS and are using the following rtpengine version;

Version: 7.3.0.0+0~mr7.3.0.0 git-master-3d64af1

We are in the process of migrating from one platform to another so we are actually tromboning calls at the moment in and out of the 
kamailio instance, and in the initial branch I am using rtpengine_manage with the following flags;

branch_route;

rtpengine_manage("direction=external direction=internal ICE=remove  replace-origin replace-session-connection  codec-strip-PCMU codec-strip-G729");

onreply route;

rtpengine_manage("direction=internal direction=external ICE=remove  replace-origin replace-session-connection  codec-strip-PCMU codec-strip-G729");

And the call establishes fine as flow is Carrier--->kamailio---->IP PBX

However we then push the call back to kamailio and rtpengine from the IP PBX and to terminate on a Gensys platform, and again with the branch and reply we engage 
rtpengine again;

branch_route;

rtpengine_manage("direction=internal direction=external ICE=remove  replace-origin replace-session-connection  codec-strip-PCMU codec-strip-G729");

onreply route;

rtpengine_manage("direction=external direction=internal ICE=remove  replace-origin replace-session-connection  codec-strip-PCMU codec-strip-G729");

Now this all works fine, however traffic levels have been increasing and I am now seeing this in the logs;

Nov 26 11:03:21 mer-prd-sbc0 rtpengine[51207]: ERR: [d5873a70-ab4d-4948-8419-b5d5ba2f809c port 45360]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
Nov 26 11:03:21 mer-prd-sbc0 rtpengine[51207]: message repeated 5 times: [ ERR: [d5873a70-ab4d-4948-8419-b5d5ba2f809c port 45360]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible]
Nov 26 11:03:21 mer-prd-sbc0 rtpengine[51207]: ERR: [d5873a70-ab4d-4948-8419-b5d5ba2f809c port 45360]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
Nov 26 11:03:21 mer-prd-sbc0 rtpengine[51207]: ERR: [d5873a70-ab4d-4948-8419-b5d5ba2f809c port 45360]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
Nov 26 11:03:21 mer-prd-sbc0 rtpengine[51207]: message repeated 8 times: [ ERR: [d5873a70-ab4d-4948-8419-b5d5ba2f809c port 45360]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible]

Now unfortunately I have tried using loop-protect however it then breaks my media flow, and I am trying to establish what flow exactly is causing the issue, as rtpengine keeps writing these logs
to syslog and the cpu is going through the roof.

I also cant really increase the rtpengine logging to debug yet, so was wondering what tips if any you can suggest for me to troubleshoot this issue or if we need to upgrade the version to 
avoid this type of thing, or I need to reevalute the rtpengine_manage statements or move to rtpengine_offer/answer commands?

Any help appreciated as we have homer capturing sip traffic but its tricky to find and correlate the UDP port reported in the rtp engine logs, which I presume will be the one from the side
before rtpengine is engaged? So either from the Carrier or IP pbx?

MAny thanks

Jon

**Comment by jonhvoxbox** [comment]
Note Also I think it may be when there is a within dialog reinvite and I look to engage rtpengine again, I assume this may be contributing? 

Jon

**Comment by jonhvoxbox** [comment]
Sorry guys last comment, how can you stop this error log being outputted without restarting the application? Is it possible? Thanks Jon

**Comment by rfuchs** [comment]
Looks like a packet forwarding loop. You can enable debug logging (log level 7) and inspect the SDP going in and out to see where it's happening. Also the `final packet stats` when a call is closed logs the forwarding destinations.

For a temporary remedy, you can close an offending call via the CLI if you have the interface enabled. Something like `rtpengine-ctl terminate $callid`

**Comment by jonhvoxbox** [comment]
Thanks Richard appreciate the response, can you just confirm how to enable the interface for ctl commands, as I run the following and get;

 rtpengine-ctl terminate d5873a70-ab4d-4948-8419-b5d5ba2f809c
Cannot connect to the rtpengine Connection refused

Do I need to add something in rtpengine.conf to allow connections?

Thanks!

**Comment by rfuchs** [comment]
Yes, it's the `listen-cli` option. The default for `rtpengine-ctl` is `127.0.0.1:9900`. If you already have it enabled but on a different port, you can use `-ip` and `-port` options to `rtpengine-ctl`

**Comment by jonhvoxbox** [comment]
Great thanks Richard works a treat and found the loop and stopped it.

**Comment by jonhvoxbox** [comment]
Hi Richard, Sorry to make further noise on this, the rtpengine-ctl is working pretty well in killing the streams, I do notice when it reporting loops such as this ;

05afa62d-6476-474b-afa1-d75ae5315dbb port 33077

The port number is the RTCP port, and this seems to flag when a reinvite is sent to a pbx after having passed via rtpengine and it just sends it back.   Is it normal to be the RTCP port being flagged as well as the media port at times?

I presume just adding loop-protect on this flow would stop this, and that the terminate should stop the loop in question and also stop it logging? 

Thanks

Jon

**Comment by rfuchs** [comment]
If you're creating a forwarding loop, then both RTP and RTCP would be looping. And you're right in both of your assumptions.

**Comment by jonhvoxbox** [comment]
Ok great thank you, I assume the following will require an application restart as its not finding it but still logging it;

rtpengine[60151]: ERR: [4463bf2e-bb16-49bb-ba9c-12c88caef976 port 49837]: Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible


 rtpengine-ctl terminate 4463bf2e-bb16-49bb-ba9c-12c88caef976

Call Id not found (4463bf2e-bb16-49bb-ba9c-12c88caef976).


Everything else works perfectly thank you.

**Comment by rfuchs** [comment]
Cleaning up old tickets
