### ISSUE TITLE
Is there an option for fast writing of rtp stream to .wav?

### ISSUE THREAD

**Issue by idoMajor41** [sipwise/rtpengine#886]
Hello,

I'm currently using RTPEngine to receive RTP stream and save it to .wav files.
I have a CPP application which takes those .wav files, when it sees a new .wav file created.
I'm currently using the "output-mixed" option so I'm streaming both RTP streams of the call to a mixed file as you can already presume.

My .cpp app is using GStreamer which allows me to stream .wav file over RTSP to a remote destination.
I'm experiencing a problem in which my GStreamer app is stopping the stream, because (which I'm currently guessing after long testings..) the .wav file is not being written to all the time and only in huge chunks of data, from what I saw when I issued ls -ail on the command line, while RTPEngine was saving the RTP to .wav file.

After the long explanation :)
Is there a way to configure the buffer in which the RTP/RTP-RECORDER use to save the .wav files, in a way that will allow faster writings so the file will be updated really fast?

Thank you very much heads up!

**Comment by rfuchs** [comment]
Well, not as such. Output is handled internally by ffmpeg through its avio interface. I'm sure there's a way to tell it not to flush more often or to buffer less, but I'm not that familiar with the details. At a quick glance, perhaps passing the flag `AVIO_FLAG_DIRECT` to `avio_open` might do the trick. See https://ffmpeg.org/doxygen/3.0/avio_8h.html

But this really sounds like the wrong approach to what you're trying to do. The recording daemon supports a PCM forwarding mechanism, perhaps that would be more useful to you?

**Comment by idoMajor41** [comment]
By the way, I've read bit of the code, especially the recording-daemon directory, and you did a great code design for my personal taste, just wanted to mention it :)
Is there a chance you reference me to the piece of code, where the data is being retrieved and sent to the libav of ffmpeg to be mixed up?

**Comment by idoMajor41** [comment]
Also what do you mean by PCM forwarding? :)

**Comment by idoMajor41** [comment]
By the way, I've did a test with the ffmpeg as you suggested.
I recompiled the rtpengine, and the result was that the file was written pretty much all the time, so it gained size very fast in every second.

But, I still do have problems streaming the output .wav file using RTSP.
I'm using the same code which I've used for the output .wav files from RTPEngine and also for Asterisk call center, which also produced for me .wav files.

When I'm using my cpp app which streams RTSP using RTPEngine against Asterisk, the gstreamer (RTSP connection) stops after a while, which I suggest it because of End of Stream of the file, which is the error I receive from GStreamer itself.

Do you maybe have another suggestion that I could test as well?

Thanks :)

**Comment by rfuchs** [comment]
The relevant code is in output.c, output_config():
```
av_ret = avio_open(&output->fmtctx->pb, full_fn, AVIO_FLAG_WRITE);
```
You can try adding the flag AVIO_FLAG_DIRECT there and see what happens, i.e:
```
av_ret = avio_open(&output->fmtctx->pb, full_fn, AVIO_FLAG_WRITE | AVIO_FLAG_DIRECT);
```
Other than that, audio is passed to the avio context in output_got_packet() via av_write_frame(). You can try calling an avio flush function directly afterwards.

The PCM forwarding option is enabled by setting `tls-send-to=` to some destination (as well as `tls-resample=`). With that enabled, the daemon will open a TCP/TLS connection to the configured destination for each stream and start delivering raw PCM (16 bit signed) into it in realtime. The initial data in each connection is a custom metadata string (e.g. the call ID, or whatever else you want) plus a null byte, so you can identify different streams. You'd have to use `start forwarding` instead of `start recording` from the controlling rtpengine, and mixed output is not supported.

**Comment by idoMajor41** [comment]
Hello again,
I've tried the flag for avio_open.
I've know took both .wav file from my asterisk and also the rtpengine.
The result in terms of the headers differences, is that the .wav file from rtpengine holds:

extras: {
     IsTruncated: Yes
}

Can it be related to RTPEngine itself or is it relating to FFMPEG?

Thanks :)

**Comment by rfuchs** [comment]
I can only speculate that this is set by ffmpeg to indicate an incomplete file while it's being written, which is true. Some header fields (such as length) can only be written when the file is closed, which is why I originally said that I think this approach of reading .wav files as they're being written is the wrong approach.

**Comment by idoMajor41** [comment]
Hello again,

After long research, the .wav files which are being saved, aren't standard wav header files.
The standard size of a newly created wave file is 44 bytes, while rtpengine because of ffmpeg gets a 78 bytes.

I'm not saying it's the RTPEngine which causes this but the FFMPEG.
It adds more fields like the encoder and a extras field.
I think it causes my GStreamer not to read the .wav file from FFMPEG correctly and in a result, the GStreamer might be stopping the stream due to that incorrect format, of the .wav headers.

I wanted to ask because I'm not that of an expert with FFMPEG.
Is there a chance to get a hint of how can I do the change in terms of calling the ffmpeg library, so it will make the standard 44 bytes file size?

Thanks! :)

**Comment by rfuchs** [comment]
Honestly I have no idea

**Comment by idoMajor41** [comment]
Well anyways thank you for your great support, greatly appreciate it :)

**Comment by ashupednekar** [comment]
@idoMajor41 Hi, you mentioned you are using rtp engine to receive wav files, but where is the stream coming from?

Are you using ffmpeg/gstreamer for that?

If yes, could you please help out with the exact commands?

I'm currently trying this:

```
ffmpeg -i file.mp3 -vn -c:a copy -f rtp rtp://20.46.44.246:12222
```

On the rtpengine logs, I'm getting the following error...

```
[1608983711.223930] WARNING: Failed to properly parse UDP command line '�\��8�]�
                                                                                ' from 157.33.89.18:51302, using fallback RE
```

Thanks in advance...
