### ISSUE TITLE
Ran out of ports - 6.5.5.5.4

### ISSUE THREAD

**Issue by nicoonline** [sipwise/rtpengine#887]
Hello,

Since this morning i got a Ran out of ports message.
```
Dec  3 08:26:34 proxy1 rtpengine[1429]: ERR: [689069377f6afc8f76137dc4230e61b3@sip.voice.xxx]: Failed to get 2 consecutive ports on interface 217.112.XX for media relay (last error: Success)
Dec  3 08:26:34 proxy1 rtpengine[1429]: ERR: [689069377f6afc8f76137dc4230e61b3@sip.voice.xxx]: Failed to get 2 consecutive ports on all locals of logical 'default'
Dec  3 08:26:34 proxy1 rtpengine[1429]: ERR: [689069377f6afc8f76137dc4230e61b3@sip.voice.xxx]: Error allocating media ports
Dec  3 08:26:34 proxy1 rtpengine[1429]: ERR: [689069377f6afc8f76137dc4230e61b3@sip.voice.xxx]: Destroying call
```
Protocol error in packet from 127.0.0.1:44801: Ran out of ports 
```
rtpengine conf :
port-min = 10000
port-max = 20000
```

**Comment by rfuchs** [comment]
So, give it more ports?

**Comment by nicoonline** [comment]
10.000 is not enough ? we talked here about 30 simultaneous calls max.

**Comment by rfuchs** [comment]
Well you didn't mention that. In that case you're probably not deleting the calls properly.

**Comment by nicoonline** [comment]
i use the rtpengine_manage function.. Strange... How can i debug it more within the logs?

**Comment by rfuchs** [comment]
Just look for the `delete` messages, you should see them the same as `offer` and `answer`. Also at the end of each call, the `final packet stats` are logged when the RTP ports are finally freed.

**Comment by nicoonline** [comment]
well i see the delete,offer and answer message just before the "out of ports".

**Comment by rfuchs** [comment]
For all calls that were ever processed?

**Comment by nicoonline** [comment]
i think so. how can we attach a file privately ?

**Comment by rfuchs** [comment]
You can send it per email.

**Comment by nicoonline** [comment]
trying to find  your email but didn't found it ;)

**Comment by linuxmaniac** [comment]
> trying to find your email but didn't found it ;)

It's in every commit. See https://github.com/sipwise/rtpengine/commit/c36a44580d8d32f88b7b777bbc6ecc0483d4d445.patch for instance.

**Comment by nicoonline** [comment]
> 
> 
> > trying to find your email but didn't found it ;)
> 
> It's in every commit. See https://github.com/sipwise/rtpengine/commit/c36a44580d8d32f88b7b777bbc6ecc0483d4d445.patch for instance.

Thanks Linuxmaniac.

**Comment by rfuchs** [comment]
There's lots of call deletions missing.
```
moose:~$ grep "Received command 'offer'" rtpengine.log | wc -l
4602
moose:~$ grep "Received command 'answer'" rtpengine.log | wc -l
506
moose:~$ grep "Received command 'delete'" rtpengine.log | wc -l
694
```
Calls which are created with just an `offer` and no corresponding `answer` or `delete` remain open for an hour (by default) and will keep the ports open during that time.

**Comment by nicoonline** [comment]
Ok let me check the configuration. Thanks for having a look.

**Comment by nicoonline** [comment]
I tried to reproduce the issue with a simple call :

Dec  3 18:20:28 proxy2 rtpengine[1426]: INFO: [9d902409335f46fb1ce15b2f61e75d2c]: Received command 'offer' from 127.0.0.1:55131
Dec  3 18:20:28 proxy2 rtpengine[1426]: NOTICE: [9d902409335f46fb1ce15b2f61e75d2c]: Creating new call
Dec  3 18:20:28 proxy2 rtpengine[1426]: NOTICE: [9d902409335f46fb1ce15b2f61e75d2c]: Turning on call recording.
Dec  3 18:20:28 proxy2 rtpengine[1426]: INFO: [9d902409335f46fb1ce15b2f61e75d2c]: Replying to 'offer' from 127.0.0.1:55131 (elapsed time 0.037582 sec)
Dec  3 18:20:33 proxy2 rtpengine[1426]: INFO: [9d902409335f46fb1ce15b2f61e75d2c]: Received command 'answer' from 127.0.0.1:42295
Dec  3 18:20:33 proxy2 rtpengine[1426]: INFO: [9d902409335f46fb1ce15b2f61e75d2c]: Replying to 'answer' from 127.0.0.1:42295 (elapsed time 0.031580 sec)
Dec  3 18:20:33 proxy2 rtpengine-recording[1463]: WARNING: [C 9d902409335f46fb1ce15b2f61e75d2c-cecdc333ae887a40.meta] [S tag-0-media-1-component-1-RTP-id-2] Failed to parse packet headers
Dec  3 18:20:36 proxy2 rtpengine[1426]: INFO: [9d902409335f46fb1ce15b2f61e75d2c]: Received command 'delete' from 127.0.0.1:48814
Dec  3 18:20:36 proxy2 rtpengine[1426]: INFO: [9d902409335f46fb1ce15b2f61e75d2c]: Scheduling deletion of call branch 'fbb71737729dfcc8' (via-branch '') in 30 seconds
Dec  3 18:20:36 proxy2 rtpengine[1426]: INFO: [9d902409335f46fb1ce15b2f61e75d2c]: Replying to 'delete' from 127.0.0.1:48814 (elapsed time 0.000098 sec)
Dec  3 18:20:36 proxy2 rtpengine[1426]: INFO: [9d902409335f46fb1ce15b2f61e75d2c]: Received command 'delete' from 127.0.0.1:41586
Dec  3 18:20:36 proxy2 rtpengine[1426]: INFO: [9d902409335f46fb1ce15b2f61e75d2c]: Scheduling deletion of call branch 'fbb71737729dfcc8' (via-branch '') in 30 seconds
Dec  3 18:20:36 proxy2 rtpengine[1426]: INFO: [9d902409335f46fb1ce15b2f61e75d2c]: Replying to 'delete' from 127.0.0.1:41586 (elapsed time 0.000084 sec)
Dec  3 18:20:47 proxy2 rtpengine[1426]: INFO: [7ca79d7fe62ef946585dbb3ddf49d446]: Call branch 'gK09ed4dd5' (via-branch '') deleted, no more branches remaining
Dec  3 18:20:47 proxy2 rtpengine[1426]: INFO: [7ca79d7fe62ef946585dbb3ddf49d446]: Final packet stats:

So i got : 
- offer
-answer
-delete

**Comment by nicoonline** [comment]
Would be a good idea to print somewhere the number of used ports. If i setup 10.000 udp ports, i suppose we can count on minimum 5000 calls. I cannot explain why there is 4062 offer & 506 answer in the rtpengine.log.

**Comment by nicoonline** [comment]
can we change the default timeout in the config file ?

**Comment by nicoonline** [comment]
i see three timeouts in default cfg

timeout = 60
silent-timeout = 3600
# final-timeout = 10800

**Comment by rfuchs** [comment]
`final-timeout` is the maximum duration of any call under any circumstances

`silent-timeout` is the timeout for calls without active RTP, which also applies for calls that are only half-established (`offer` only)

But you should really fix your signalling to tear down calls when they're done.

**Comment by nicoonline** [comment]
Final-Timeout is unlimited if not specified.

I have checked the code and there is a delete when the call is done, so i think there is no issue with the kamailio code.
It's true that this morning we had a lot of calls without answer on the other end... i think that can explain the "4000" calls without RTP. (even if this number is huge for me).

stats for now (traffic was stopped from this morning to 6pm
[root@proxy1 log]# grep "Received command 'offer'" rtpengine.log | wc -l
5589
[root@proxy1 log]# grep "Received command 'delete'" rtpengine.log | wc -l
1555

**Comment by rfuchs** [comment]
Every `offer` should have a corresponding `delete`, otherwise signalling is broken. If the call is not answered, the SIP proxy should time out the call and issue a `delete`

**Comment by nicoonline** [comment]
i will mail Kamailio then just tried the following scenario, inbound call with no answer, i don't see the delete from the rtpengine.


Packet sent to host :
Dec  3 21:21:19 proxy1 /usr/sbin/kamailio[10745]: NOTICE: calling function  rtpengine_manage function
Dec  3 21:21:19 proxy1 /usr/sbin/kamailio[10743]: NOTICE: calling function  rtpengine_manage function

Received a Ring
Dec  3 21:21:19 proxy1 /usr/sbin/kamailio[10744]: NOTICE: 0ebe00a62434ee9 |-----> Call Ring (180)

I hangup
Dec  3 21:21:19 proxy1 /usr/sbin/kamailio[10744]: NOTICE: calling function  rtpengine_manage function

**Comment by nicoonline** [comment]
was a logic issue in the kamailio script.

**Comment by prathibhacdac** [comment]
Facing the same issue. How to resolve it?

**Comment by saleemjaffer** [comment]
@rfuchs 

In my case, the ports keep increasing even though the `offer` and `delete` counts almost match and eventually the system runs out of ports. Can you please help here?
```
root@ip-10-0-0-110:/home/admin# grep "Received command 'offer'" /var/log/syslog | wc -l
18101
root@ip-10-0-0-110:/home/admin# grep "Received command 'answer'" /var/log/syslog | wc -l
18058
root@ip-10-0-0-110:/home/admin# grep "Received command 'delete'" /var/log/syslog | wc -l
18028
root@ip-10-0-0-110:/home/admin# netstat -au  | wc -l
1561
```

**Comment by Joshuaald** [comment]
Hi, I'm having the same problem, I'm having the same problem.

**Comment by Joshuaald** [comment]
> Hi, [nicoonline](https://github.com/nicoonline),  I'm having the same problem, I'm having the same problem.
