### ISSUE TITLE
Codec-offer flag not works

### ISSUE THREAD

**Issue by giupand** [sipwise/rtpengine#888]
Hi,
I'm using rtpengine (version 8.0.1.1+0~mr8.0.1.1) to bridge networks internal/external with kamailio 5.3.1 and I think that the codec-offer flag not works.

If I don't wrong codec-offer is a codec whitelist, from documentation:

> Contains a list of strings. Each string is the name of a codec that should be included in the list of codecs offered. This is primarily useful to block all codecs (strip -> all) except the ones given in the offer whitelist. Codecs that were not present in the original list of codecs offered by the client will be ignored.
> This list also supports codec format parameters as per above.

Below trace in my context:

Offer Flags: [direction=internal direction=external asymmetric codec-offer-G729 ICE=remove address-family=IP4 replace-origin=10.10.10.3 TOS=184 RTP/AVP DTLS=off]

Dump for 'offer' from 127.0.0.1:48083: { "supports": [ "load limit" ], "sdp": "v=0
o=- 7336 7336 IN IP4 127.0.0.1
s=-
c=IN IP4 192.168.1.79
t=0 0
a=sendrecv
m=audio 2310 RTP/AVP 18 8 110 111 9 127
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:8 PCMA/8000
a=rtpmap:110 iLBC/8000
a=fmtp:110 mode=20
a=rtpmap:111 SIREN/16000
a=fmtp:111 bitrate=16000
a=rtpmap:9 G722/8000
a=rtpmap:127 telephone-event/8000
a=sendrecv

DEBUG: [3287B58E-0000093E000E3983-748D5530]: ... OS": 184, "DTLS": "off", "direction": [ "internal", "external" ], "flags": [ "asymmetric" ], "replace": [ "origin" ], "codec": { "offer": [ "G729" ] }, "transport-protocol": "RTP/AVP", "call-id": "3287B58E-0000093E000E3983-748D5530", "received-from": [ "IP4", "127.0.0.1" ], "from-tag": "7DDAA77B-0000093E000E3969-748D5530", "command": "offer" }

[...]

Response dump for 'offer' to 127.0.0.1:48083: { "sdp": "v=0
o=- 7336 7336 IN IP4 10.10.10.3
s=-
c=IN IP4 10.10.10.3
t=0 0
m=audio 10038 RTP/AVP 18 8 110 111 9 127
a=rtpmap:18 G729/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:110 iLBC/8000
a=rtpmap:111 SIREN/16000
a=rtpmap:9 G722/8000
a=rtpmap:127 telephone-event/8000
a=fmtp:18 annexb=no
a=fmtp:110 mode=20
a=fmtp:111 bitrate=16000
a=sendrecv
a=rtcp:10039
", "result": "ok" }

I believe the response should be as below:

Response dump for 'offer' to 127.0.0.1:48083: { "sdp": "v=0
o=- 7336 7336 IN IP4 10.10.10.3
s=-
c=IN IP4 10.10.10.3
t=0 0
m=audio 10038 RTP/AVP 18 127
a=rtpmap:18 G729/8000
a=rtpmap:127 telephone-event/8000
a=fmtp:18 annexb=no
a=sendrecv
a=rtcp:10039
", "result": "ok" }

**Comment by rfuchs** [comment]
It is a whitelist, but only if used in opposition to `codec-strip=all`. It has no effect just on its own. So you want to do `codec-strip=all codec-offer=G729 codec-offer=telephone-event`

**Comment by giupand** [comment]
Thanks for reply,
if I use codec-strip=all codec-offer=G729 codec-offer=telephone-event I strip all codec list and recreate it, so for example could change the telephone-event payload.
This may not be correct, what do you think about it?

**Comment by rfuchs** [comment]
The payload type will not be changed. `offer` strictly is the counteraction to `strip`, so you will always get what was in the original offer.

**Comment by giupand** [comment]
Perfect, it works!
thanks
