### ISSUE TITLE
transcoding informations in rtpengine-ctl output

### ISSUE THREAD

**Issue by giupand** [sipwise/rtpengine#889]
Hi,
using rtpengine for transcoding, is it possible recover the codecs in use between rtpengine sides?
I trying to use rtpengine-cli but it don't retrieve transcoded codecs informations.
Is it possible modify rtpengine-cli adding to output informations about transcoded codecs?

For example:
uac  <--- g711 --->  rtpengine <--- g729 --->  uas
---------------------- call-id: 12345 ------------------

_rtpengine-ctl -ip cli-ip -port cli-port get sessions 12345_
```
--- Tag '12345' type: FROM_TAG, callduration 50.476333 , in dialogue with 'abcd'
------ Media #1, local-ip:local-port <>  remote-ip:remote-port , 2469 p, 424668 b, 0 e, 2376 last_packet, **CODEC=G711**
------ Media #1, local-ip:local-port <>  remote-ip:remote-port  (RTCP), 10 p, 920 b, 0 e, 2376 last_packet
--- Tag 'abcd' type: TO_TAG, callduration 49.561709 , in dialogue with '12345'
------ Media #1,      local-ip:local-port <>     remote-ip:remote-port , 2473 p, 79136 b, 0 e, 2376 last_packet, **CODEC=G729**
------ Media #1,      local-ip:local-port <>     remote-ip:remote-port  (RTCP), 0 p, 0 b, 0 e, 2326 last_packet
```

**Comment by rfuchs** [comment]
Probably a good idea, yes
