### ISSUE TITLE
Can we setup conference call with rtpengine?

### ISSUE THREAD

**Issue by frknyldz** [sipwise/rtpengine#891]
Hi,

We are using rtpengine without Kamailio and when we tried setup a call with 2 participants , it works fine. Media stream shown as below. (1 offer 1 answer)
![image](https://user-images.githubusercontent.com/23285358/70620431-55160f00-1c28-11ea-818d-e39cd7faae9c.png)
Is it right approach ? Do we need to seperate orig and terminating parts ? 

Can we use only rtpengine to create conference call ? If it is possible ,how we need to create offer and answer commands? 
I expect the flow as below.

![image](https://user-images.githubusercontent.com/23285358/70620412-3ca5f480-1c28-11ea-99cc-7df15fd0a375.png)

When client A send a packet , I expect rtpengine send that packet to all other participants.
Thanks for any advice.

**Comment by rfuchs** [comment]
That kind of setup is not supported. Rtpengine only does 1-to-1 media streams.

**Comment by frknyldz** [comment]
Thanks @rfuchs
