### ISSUE TITLE
codec-transcode-telephone-event payload

### ISSUE THREAD

**Issue by giupand** [sipwise/rtpengine#894]
Hi,
the telephone-event's payloads are dynamic payload whit values from 96 to 127.
When I set codec-transcode-telephone-event flag the payload used is 96.
Is it possible to chose the payload number?
For example:
If I set codec-transcode-telephone-event the default value will be 96.
 if I set a flag codec-transcode-telephone-event**101** will be use the payload value 101.
Thanks

**Comment by rfuchs** [comment]
Why would you need to do that?

**Comment by giupand** [comment]
Because, if I have a scenario where the called want use a specific payload for telephone event I could set it in in offer.

**Comment by rfuchs** [comment]
Is that just a peculiarity of the RTP client involved? Because dynamic payload types should really be, well, dynamic. Just trying to understand if maybe there's some kind of underlying usage error here.

**Comment by giupand** [comment]
You are right, it could be a particular scenario, but in voip world it' s possible "meets" some UA that want use a specifics offer set. rtppengine is a very good software, so I'm asking if is ti possible.

**Comment by rfuchs** [comment]
Not currently possibly, no.

**Comment by giupand** [comment]
Ok, thanks for reply.
