### ISSUE TITLE
RTPengine Not suppoerted iLBC CODEC

### ISSUE THREAD

**Issue by imdrpn** [sipwise/rtpengine#897]
Hello all,
         how to add iLBC codec in rtpengine i am using git version **git-develop-fa380de**
 and after command rtpengine --codecs i saw the codec list which is supported to rtpengine, anyone please  tell me how can i add support of iLBC codec in rtpengine.

my rtpengine codec list :

[root@localhost daemon]# rtpengine --codecs
                PCMA: fully supported
                PCMU: fully supported
                G723: fully supported
                G722: fully supported
               QCELP: supported for decoding only
                G729: supported for decoding only
               speex: fully supported
                 GSM: fully supported
                iLBC: not supported
                opus: fully supported
              vorbis: fully supported
                 ac3: fully supported
                eac3: fully supported
              ATRAC3: supported for decoding only
             ATRAC-X: supported for decoding only
                 AMR: fully supported
              AMR-WB: fully supported
           PCM-S16LE: fully supported
                 MP3: fully supported
[root@localhost daemon]#

**Comment by rfuchs** [comment]
Support depends on what's supported by your ffmpeg. You need to have an ffmpeg lib installed that supports iLBC and then (re)build rtpengine against that. Then you'll have support.
