### ISSUE TITLE
memory leak on 6.5 version

### ISSUE THREAD

**Issue by descartin** [sipwise/rtpengine#898]
Dear all

i just notice one thing on a device i have in production. Seems that the memory used by the application increases very slowly in 6.5 and not in 6.1 version.
I'm using debian9 in these live systems. They handle around 3000-5000 simultaneous calls (12k-20k ports) consistently.
And after several weeks the memory get to a value around 75% of the machine. The effect i could see with that value is that the delete delay of 5 secs we have configured was not respected and the session lasted more time (~40secs-1min) to be deleted.
I restarted the application to reduce the leak, so i didnt put the process reaching to higher than 90% of mem used so no crash was expected of affectation to offer/answer messages (i guess)

this happens with 
Version: 6.5.4.0+0~ mr6.5.4.0 git-v6.5-530c02d, and not with 
Version: 6.1.3.0+0~ mr6.1.3.0 git-v.6.1-8defb93

i add you a snapshot where you can see in the last 30days the evolution of the memory used by the application. The flat lines are for 4 6.1.3 rtpengine versions, and the one increasing is the 6.5.4.

![image](https://user-images.githubusercontent.com/7767994/70903521-57e57b00-1fff-11ea-8495-010a14e316ea.png)

Could you please give me any key to investigate deeper which setup or code could be causing this slow degradation?

thanks a lot and regards
david

**Comment by rfuchs** [comment]
The best way to debug this is to run it through valgrind. However, this results in abysmal performance and so isn't really usable for a live system. If you're able to do this on a lab system, run rtpengine as `G_SLICE=always-malloc valgrind --show-leak-kinds=all --log-file=valgrind.output.txt rtpengine ...`, let it run for a while, and post the resulting `valgrind.output.txt` after rtpengine has shut down.

Otherwise post some (full debug) logs of some of your usual call load and I can try to reproduce it.

The graph seems to show mem usage increasing in steps and not continuously. Is that an artefact of how you're monitoring usage or is that how it actually happens?

**Comment by descartin** [comment]
Dear Richard

thanks for your response.
unfortunately i cannot run the device with those options. I will try to duplicate on a lab system to check if i can see the mem increase, but i might be not easy to see because it's a very small increase.

Othercase i will collect some logs and will share to you. By default i have the instance running with NOTICE or lower log level to not affect the performance. I have experienced that when using full debug level7, the rtt in the communication between kamailio and rtpengine increases. Not to make anything crush but it might have some side effect.

about the way to measure it, we can see it with the MEM used of the top command and checking /proc/meminfo file MemFree field

i will let you know
best regards
david

**Comment by rfuchs** [comment]
Are you seeing this on a Redis slave (using keyspace notifications) by any chance?

**Comment by descartin** [comment]
dear Richard

i'm afraid the instance is running is not subscribed to any redis instance, is running alone.
Does make it sense anyway to apply the patch?

thanks a lot and regards
david

**Comment by rfuchs** [comment]
Still working on this one. There's some other unrelated leaks too. It always makes sense to apply it :) see if it fixes the leak for you.

**Comment by rfuchs** [comment]
7290668 is the last iteration of this patch, so feel free to try.

**Comment by descartin** [comment]
Dear Richard

this patch seems to be for version 8.2
i'm using a 6.5 version
is it possible to have a backport for 6.5?

thanks a lot and regards
david

**Comment by rfuchs** [comment]
It's already been backported to mr6.5: 5097926b

**Comment by descartin** [comment]
Hello Richard

thanks a lot. i applied it. I will let you know if i see any improvement

regards
david
