### ISSUE TITLE
Segmentation fault on get_interface_address call.c:3502

### ISSUE THREAD

**Issue by hcouplet** [sipwise/rtpengine#90]
On the latest master build, I have sometime Segmentation fault.
I recompiled in debug.

The error is on call.c : line 3502 at   if (!q->head).  See below the source code.

static struct interface_address *get_interface_address(struct local_interface *lif, int family) {
  const GQueue *q;

  q = &lif->list;
  if (!q->head)
      return NULL;
  return q->head->data;
}

Here is the log with debug level : 

Mar 24 14:53:41 proxmox2 rtpengine[283088]: Generating new DTLS certificate
Mar 24 14:53:41 proxmox2 rtpengine[283088]: Dump of DTLS certificate:
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- -----BEGIN CERTIFICATE-----
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- MIIBpDCCAQ2gAwIBAAIJAPnuysLwSWnKMA0GCSqGSIb3DQEBBQUAMBQxEjAQBgNV
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- BAMTCXJ0cGVuZ2luZTAeFw0xNTAzMjMxMzUzNDFaFw0xNTA0MjMxMzUzNDFaMBQx
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- EjAQBgNVBAMTCXJ0cGVuZ2luZTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- uYvl6Q6bYz/mDKN/7/wiHZ/K9xH5uJkwDXe11wibZJowY41IWrbf11buqrZUsjDh
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- LjebPe0306zR+rvKnkMw9GaBI6XFjdAlRTdQCUxu6n7z+TP+JozvZzlMOsZlLW76
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- cG603avlPWMJObXLoWAmXlqOCqV3Ygx9RWM61G9ZcxkCAwEAATANBgkqhkiG9w0B
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- AQUFAAOBgQALeqrVVlkmyh6yJ/g9z4phXyBZb300mPkJS0Rmd1kdWYtPCAF8EniE
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- Ua7xpNDVA1ptwAdU804pkc38IcmaNWoDJX6ZXqe3vhbCIpl1lEQjNqGvf0IGGoRT
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- OCXI0cZikcOzjMjmwLvEbzz/1M7BxTnFbbYKdGgO2ZTVV5i1tKJLxQ==
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- -----END CERTIFICATE-----
Mar 24 14:53:41 proxmox2 rtpengine[283088]: Dump of DTLS private key:
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- -----BEGIN PRIVATE KEY-----
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALmL5ekOm2M/5gyj
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- f+/8Ih2fyvcR+biZMA13tdcIm2SaMGONSFq239dW7qq2VLIw4S43mz3tN9Os0fq7
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- yp5DMPRmgSOlxY3QJUU3UAlMbup+8/kz/iaM72c5TDrGZS1u+nButN2r5T1jCTm1
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- y6FgJl5ajgqld2IMfUVjOtRvWXMZAgMBAAECgYEAlPHxqIl6QUztHh4tuHcc58z7
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- QCSk4wPNqDH9vdWB8Fs6FuA2QePlgladllpxWO2WBeTLcQW5N+nWUcFoIG1toJWj
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- IBvhZ//GbixDwuPGZe702NVsB5p/lIgYb6CFkVdi1FOp5hLWEjHVGeLNzhpijzEA
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- j1T6DstU4o3zYQbJWwECQQDeJuyIEP/M+RR+ovnNZ95P7YghPpLN3vq3d3W3H/yW
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- 89cj8avd4qJBhF1vKWdz10pIrrQZBzilpqGY2bYTRxKhAkEA1dErBNeJoczUcUB8
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- 1ab31jwXYVTankuG9zTIrORCTbiTzPpWnPRWpWXz0siMEkpUxryChpKV5iMId0CY
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- AZSFeQJAdt7lGjneZtOxP8H9YQf/UU2M1h0heL+j8KAfgQnAoxV/PWCH0ob+w4gM
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- ZvsEvFurCBFTlUDj8t+jAKMeZlpVgQJBAJYwEHmcNG7Ug7zxQT6Jw7hWCU4y3kUm
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- ZC0shHD8/J2/MwJeLYyeDGatkHDUsZ7/W0EllMGWIXi/zuiFFMC3ZHECQEs9G4DA
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- QqnkRbsmyGbZq6zGRcC1eTo9oWqJ0F/izii/cObymGmuJAISNebuGXws1QfJXnFw
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- z+5i5z14sUygR6U=
Mar 24 14:53:41 proxmox2 rtpengine[283088]: --- -----END PRIVATE KEY-----
Mar 24 14:53:41 proxmox2 rtpengine[283089]: Startup complete, version 3.3.0.0+0~mr4.0.0.0
Mar 24 14:58:01 proxmox2 rrdcached[3084]: flushing old values
Mar 24 14:58:01 proxmox2 rrdcached[3084]: rotating journals
Mar 24 14:58:01 proxmox2 rrdcached[3084]: started new journal /var/lib/rrdcached/journal/rrd.journal.1427205481.321212
Mar 24 14:58:01 proxmox2 rrdcached[3084]: removing old journal /var/lib/rrdcached/journal/rrd.journal.1427198281.321241
Mar 24 14:59:54 proxmox2 rtpengine[283089]: Adding a proxy for control ng stats:192.0.2.1
Mar 24 14:59:54 proxmox2 rtpengine[283089]: Received command 'ping' from 192.0.2.1:43088
Mar 24 14:59:54 proxmox2 rtpengine[283089]: Dump for 'ping' from 192.0.2.1:43088: { "command": "ping" }
Mar 24 14:59:54 proxmox2 rtpengine[283089]: Replying to 'ping' from 192.0.2.1:43088
Mar 24 14:59:54 proxmox2 rtpengine[283089]: Response dump for 'ping' to 192.0.2.1:43088: { "result": "pong" }
Mar 24 14:59:54 proxmox2 rtpengine[283089]: [bf449dbe-9c29-8902-1a22-73fc04f7b5f7] Received command 'offer' from 192.0.2.1:43088
Mar 24 14:59:54 proxmox2 rtpengine[283089]: [bf449dbe-9c29-8902-1a22-73fc04f7b5f7] Dump for 'offer' from 192.0.2.1:43088: { "sdp": "v=0#015#012o=- 983536712325009000 2 IN IP4 127.0.0.1#015#012s=Doubango Telecom - chrome#015#012t=0 0#015#012a=group:BUNDLE audio#015#012a=msid-semantic: WMS PVrO4ZFFRnQDPnURjlmSwPS3GTAE9FT9eBTG#015#012m=audio 60480 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 126#015#012c=IN IP6 2001::5ef5:79fd:cd4:3bc9:2a24:6c58#015#012a=rtcp:60480 IN IP6 2001::5ef5:79fd:cd4:3bc9:2a24:6c58#015#012a=candidate:3570486776 1 udp 2122255103 2001::5ef5:79fd:cd4:3bc9:2a24:6c58 60480 typ host generation 0#015#012a=candidate:357 ...
Mar 24 14:59:54 proxmox2 rtpengine[283089]: [bf449dbe-9c29-8902-1a22-73fc04f7b5f7] ... 0486776 2 udp 2122255103 2001::5ef5:79fd:cd4:3bc9:2a24:6c58 60480 typ host generation 0#015#012a=candidate:916932142 1 udp 2122194687 172.27.1.58 60481 typ host generation 0#015#012a=candidate:916932142 2 udp 2122194687 172.27.1.58 60481 typ host generation 0#015#012a=candidate:2589110536 1 tcp 1518275327 2001::5ef5:79fd:cd4:3bc9:2a24:6c58 0 typ host tcptype active generation 0#015#012a=candidate:2589110536 2 tcp 1518275327 2001::5ef5:79fd:cd4:3bc9:2a24:6c58 0 typ host tcptype active generation 0#015#012a=candidate:201567305 ...
Mar 24 14:59:54 proxmox2 rtpengine[283089]: [bf449dbe-9c29-8902-1a22-73fc04f7b5f7] ... 4 1 tcp 1518214911 172.27.1.58 0 typ host tcptype active generation 0#015#012a=candidate:2015673054 2 tcp 1518214911 172.27.1.58 0 typ host tcptype active generation 0#015#012a=ice-ufrag:9lvGDZjai2kwFIQl#015#012a=ice-pwd:0EFsRN94i+BbRyupiGggYSRz#015#012a=ice-options:google-ice#015#012a=fingerprint:sha-256 1F:F2:9F:12:97:1F:E4:8E:85:9E:58:69:95:98:BE:89:9B:C5:7D:47:74:5F:4C:45:50:9D:23:96:A6:2D:13:05#015#012a=setup:actpass#015#012a=mid:audio#015#012a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level#015#012a=extmap:3 http://www.webrtc.org/experim ...
Mar 24 14:59:54 proxmox2 rtpengine[283089]: [bf449dbe-9c29-8902-1a22-73fc04f7b5f7] ... ents/rtp-hdrext/abs-send-time#015#012a=sendrecv#015#012a=rtcp-mux#015#012a=rtpmap:111 opus/48000/2#015#012a=fmtp:111 minptime=10; useinbandfec=1#015#012a=rtpmap:103 ISAC/16000#015#012a=rtpmap:104 ISAC/32000#015#012a=rtpmap:9 G722/8000#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:106 CN/32000#015#012a=rtpmap:105 CN/16000#015#012a=rtpmap:13 CN/8000#015#012a=rtpmap:126 telephone-event/8000#015#012a=maxptime:60#015#012a=ssrc:4181559711 cname:HwWwc2WPFBiGYHBy#015#012a=ssrc:4181559711 msid:PVrO4ZFFRnQDPnURjlmSwPS3GTAE9FT9eBTG 91c90702-25b2-4f77-a1e4-fb013f26416b#015#012a=ssr ...
Mar 24 14:59:54 proxmox2 rtpengine[283089]: [bf449dbe-9c29-8902-1a22-73fc04f7b5f7] ... c:4181559711 mslabel:PVrO4ZFFRnQDPnURjlmSwPS3GTAE9FT9eBTG#015#012a=ssrc:4181559711 label:91c90702-25b2-4f77-a1e4-fb013f26416b#015#012a=direction:active#015#012", "ICE": "remove", "DTLS": "passive", "flags": [ "trust-address" ], "replace": [ "origin", "session-connection" ], "transport-protocol": "RTP/AVP", "call-id": "bf449dbe-9c29-8902-1a22-73fc04f7b5f7", "received-from": [ "IP4", "127.0.0.1" ], "from-tag": "dxL7DMRyv6GVtrZF8uhM", "command": "offer" }
Mar 24 14:59:54 proxmox2 rtpengine[283089]: [bf449dbe-9c29-8902-1a22-73fc04f7b5f7] Creating new call
Mar 24 14:59:54 proxmox2 rtpengine[283089]: [bf449dbe-9c29-8902-1a22-73fc04f7b5f7] getting monologue for tag 'dxL7DMRyv6GVtrZF8uhM' in call 'bf449dbe-9c29-8902-1a22-73fc04f7b5f7'
Mar 24 14:59:54 proxmox2 rtpengine[283089]: [bf449dbe-9c29-8902-1a22-73fc04f7b5f7] creating new monologue
Mar 24 14:59:54 proxmox2 rtpengine[283089]: [bf449dbe-9c29-8902-1a22-73fc04f7b5f7] tagging monologue with 'dxL7DMRyv6GVtrZF8uhM'
Mar 24 14:59:54 proxmox2 rtpengine[283089]: [bf449dbe-9c29-8902-1a22-73fc04f7b5f7] creating new monologue
Mar 24 14:59:54 proxmox2 rtpengine[283089]: [bf449dbe-9c29-8902-1a22-73fc04f7b5f7] this= other=dxL7DMRyv6GVtrZF8uhM
Mar 24 14:59:54 proxmox2 rtpengine[283089]: [bf449dbe-9c29-8902-1a22-73fc04f7b5f7] processing media stream #1
Mar 24 14:59:54 proxmox2 rtpengine[283089]: [bf449dbe-9c29-8902-1a22-73fc04f7b5f7] allocating new call_media for stream #1
Mar 24 14:59:54 proxmox2 rtpengine[283089]: [bf449dbe-9c29-8902-1a22-73fc04f7b5f7] allocating new call_media for stream #1
Mar 24 14:59:54 proxmox2 rtpengine[283089]: [bf449dbe-9c29-8902-1a22-73fc04f7b5f7] Interface '' not found, using default

Here is the info from the core : 

GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/sbin/rtpengine...done.
[New LWP 283097]
[New LWP 283098]
[New LWP 283099]
[New LWP 283105]
[New LWP 283101]
[New LWP 283095]
[New LWP 283096]
[New LWP 283100]
[New LWP 283089]
[New LWP 283104]
[New LWP 283094]
[New LWP 283102]
[New LWP 283093]
[New LWP 283103]
[New LWP 283090]
[New LWP 283091]

warning: Can't read pathname for load map: Input/output error.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7ffff8125000
Core was generated by `/usr/sbin/rtpengine --interface=109.69.220.186 --listen-ng=22222 --timeout=60 -'.
Program terminated with signal 11, Segmentation fault.
#0  0x000000000041cf66 in get_interface_address (lif=0x0, family=10) at call.c:3502
3502	call.c: No such file or directory.

Here is the command line that started the application : 
/usr/sbin/rtpengine --interface=109.69.220.186 --listen-ng=22222 --timeout=60 --silent-timeout=3600 --pidfile=/var/run/ngcp-rtpengine-daemon.pid --tos=184 --port-min=30000 --port-max=50000 --table=0 --log-level=7 --log-facility=daemon

Do you have any idea how I can fix this ?

**Comment by rfuchs** [comment]
Ah, you've received an invite from an IPv6 endpoint but don't have an IPv6 address yourself. This case isn't properly handled in the code yet. Fix is coming shortly.

**Comment by hcouplet** [comment]
I am not using IPv6.

Doing a tcpdump on all interfaces looking for ipv6 traffic return nothing. ( tcpdump -i any  -vv ip6 ).
So this confirm there is no ipv6 invite.

**Comment by rfuchs** [comment]
Yes it's an IPv6 invite. The c= line from the SDP says `c=IN IP6 2001::5ef5:79fd:cd4:3bc9:2a24:6c58`

**Comment by rfuchs** [comment]
Let me know if this fixes it for you

**Comment by hcouplet** [comment]
Thanks for your fix.  You were right the issue came from the IPv6 address in the SDP.

I have tested your fix and I confirme that the issue is resolved.
No more segmentation fault and call is going through normally.

Thanks for you quick response !
