### ISSUE TITLE
rtpengine: error while loading shared libraries: libevent_pthreads-2.0.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by billsimon** [sipwise/rtpengine#905]
dpkg build on Debian 10 using git pull from just now. The dpkg build is error free but rtpengine fails to run due to being linked against libevent_pthreads-2.0.so.5. However Debian 10 seems to have libevent_pthreads-2.1.so.6 packaged.

**Comment by rfuchs** [comment]
That can't really be. The binary that dpkg builds will be linked against whatever is present on the system. If you get a mismatch there, you have a broken system.

**Comment by billsimon** [comment]
Yeah... it just MIGHT be that old rtpengine binary that was hiding out in /usr/local/sbin ... 

Closing ticket due to operator is a moron.
