### ISSUE TITLE
rtpengine forwarding packets to Public IP instead of Private-IP

### ISSUE THREAD

**Issue by githubsw** [sipwise/rtpengine#910]
Hello, 
rtpengine is working great on my Kamailio/rtpengine/Asterisk system, however, I am trying to force the RTP traffic via the Asterisk Private-IP instead of it's Public-IP.   I have tried several rtpengine configurations, e.g. I tried (dir priviate dir private), amongst a few others. but I just cannot get the traffic to flow to the Asterisk Private-IP.  

Am I missing something, or is there a different configuration I need?

Thank you,

**Comment by rfuchs** [comment]
Probably yes both :)

You need to define the IP address in the rtpengine configuration, and then tell it to use it via the `direction=` flags in your offer/answer messages.

If you've done that already, post 1) your configuration, 2) the flags you're using, 3) what you see rtpengine doing, 4) what you expect it to do instead.

**Comment by githubsw** [comment]
Hello rfuchs,
Thank you for the response, but I am little confused because I don't see how I can hard-code an IP address that Kamailio/retengine will forward traffic to because the traffic may go to Kamailio/Asterisk (Inbound calls), or it may go to a provider UAC (Outbound calls).  I just want to make sure that rtpengine uses the Private-IP of Asterisk when rtpengine forwards media traffic to Asterisk.

As I mentioned rtpengine is working great, but I am having difficulties solving this issue.

Thank you again,

**Comment by rfuchs** [comment]
You have to include that logic into your Kamailio script. Rtpengine cannot possibly know where an offer will be sent to ahead of time. So it needs to be instructed by Kamailio. The `direction=` flags must be made dynamic depending on where the offer comes from and where it will be sent to.
