### ISSUE TITLE
Query Around rtpengine, docker and alpine

### ISSUE THREAD

**Issue by jonhvoxbox** [sipwise/rtpengine#911]
Hi Guys, 

Sorry to post this here but I just wondered if anyone had successfully deployed an rtpengine container using alpine as the base? I appreciate this may not be possible but just wondered if it was an option.

Thanks

Jon

**Comment by jbg** [comment]
Yes, it works fine

**Comment by jbg** [comment]
Adjust as needed. If you want kernel forwarding you will need the headers in the builder and to remove the env var from the make invocation. The module would need to be loaded on the host and I guess the container will need some capabilities added.

```
FROM alpine:latest AS builder
RUN apk --update add build-base git pkgconf perl gperf glib-dev ffmpeg-dev openssl-dev libevent-dev libpcap-dev spandsp-dev json-glib-dev hiredis-dev xmlrpc-c-dev mariadb-connector-c-dev cmake
RUN git clone https://github.com/sipwise/rtpengine
RUN git clone https://github.com/BelledonneCommunications/bcg729
RUN cd bcg729 && cmake . && make && make install && cd ..
RUN cd rtpengine/daemon && with_iptables_option=no make

FROM alpine:latest
RUN apk update && apk upgrade && apk add glib ffmpeg openssl libevent libpcap spandsp json-glib hiredis xmlrpc-c xmlrpc-c-client mariadb-connector-c strace && addgroup -S rtpengine && adduser -S rtpengine -G rtpengine
COPY --from=builder /rtpengine/daemon/rtpengine /
COPY --from=builder /usr/local/lib64/libbcg729.so.0 /usr/lib/
USER rtpengine
ENTRYPOINT ["/rtpengine"]
```

**Comment by rfuchs** [comment]
Closing this then as it's been answered

**Comment by jonhvoxbox** [comment]
Thanks Jasper yes I figured it out but thanks for the response much appreciated :)
