### ISSUE TITLE
Codec Reinvites

### ISSUE THREAD

**Issue by nicoonline** [sipwise/rtpengine#912]
Hello,

I'm facing an issue with a codec renegociation / bad rtp packet transmission.

INVITE TO OLO with G722.
Ringing in G722.

Ack : 
U 2020/01/22 09:37:27.139803
SIP/2.0 200 OK.
....
.
v=0.
o=Sonus_UAC 712 21341 IN IP4 80.229.94.14.
s=SIP Media Capabilities.
c=IN IP4 80.229.94.4.
t=0 0.
m=audio 17202 RTP/AVP 9 101.
a=rtpmap:9 G722/8000.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-15.
a=sendrecv.
Ack in G722

=> sent to UAC

Reinvite in G711
U 2020/01/22 09:37:27.178069 80.229.94.14:5060 -> 217.112.180.10:5060

v=0.
o=Sonus_UAC 712 21342 IN IP4 80.229.94.14.
s=SIP Media Capabilities.
c=IN IP4 80.229.94.4.
t=0 0.
m=audio 17202 RTP/AVP 8 101.
a=rtpmap:8 PCMA/8000.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-15.
a=sendrecv.
a=maxptime:20.

=> sent to UAC and we got a 200 OK with the new rtp informations:

U 2020/01/22 09:37:27.195927 10.0.11.12:58845 
SIP/2.0 200 OK.

.
v=0.
o=CiscoSystemsSIP-GW-UserAgent 7202 8461 IN IP4 10.0.11.12.
s=SIP Call.
c=IN IP4 10.0.11.12.
t=0 0.
m=audio 41064 RTP/AVP 8 101.
c=IN IP4 10.0.11.12.
a=rtpmap:8 PCMA/8000.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-15.
a=ptime:20.

No sound on far-end, in rtpengine.log
Jan 22 09:38:06 proxy1 rtpengine[1429]: INFO: [3DAA04D8-3C2911EA-ABFB850C-63AFD997@10.0.11.12]: --- Tag 'D23A3047-CBF', created 0:45 ago for branch '', in dialogue with 'gK09e66332'
Jan 22 09:38:06 proxy1 rtpengine[1429]: INFO: [3DAA04D8-3C2911EA-ABFB850C-63AFD997@10.0.11.12]: ------ Media #1 (audio over RTP/AVP) using G722/8000
Jan 22 09:38:06 proxy1 rtpengine[1429]: INFO: [3DAA04D8-3C2911EA-ABFB850C-63AFD997@10.0.11.12]: --------- Port  217.112.180.10:15696 <>      10.0.11.12:41064, SSRC 0, 473 p, 81356 b, 0 e, 29 ts
Jan 22 09:38:06 proxy1 rtpengine[1429]: INFO: [3DAA04D8-3C2911EA-ABFB850C-63AFD997@10.0.11.12]: --------- Port  217.112.180.10:15697 <>      10.0.11.12:41065 (RTCP), SSRC 0, 1 p, 36 b, 0 e, 37 ts
Jan 22 09:38:06 proxy1 rtpengine[1429]: INFO: [3DAA04D8-3C2911EA-ABFB850C-63AFD997@10.0.11.12]: --- Tag 'gK09e66332', created 0:45 ago for branch '', in dialogue with 'D23A3047-CBF'
Jan 22 09:38:06 proxy1 rtpengine[1429]: INFO: [3DAA04D8-3C2911EA-ABFB850C-63AFD997@10.0.11.12]: ------ Media #1 (audio over RTP/AVP) using PCMA/8000
Jan 22 09:38:06 proxy1 rtpengine[1429]: INFO: [3DAA04D8-3C2911EA-ABFB850C-63AFD997@10.0.11.12]: --------- Port  217.112.180.10:15682 <>     80.229.94.4:17202, SSRC 129972eb, 404 p, 69488 b, 0 e, 29 ts
Jan 22 09:38:06 proxy1 rtpengine[1429]: INFO: [3DAA04D8-3C2911EA-ABFB850C-63AFD997@10.0.11.12]: --------- Port  217.112.180.10:15683 <>     80.229.94.4:17203 (RTCP), SSRC 0, 0 p, 0 b, 0 e, 45 ts

path between UAC 10.0.11.12 and the proxy is still in G722 according to rtpengine.log.

**Comment by rfuchs** [comment]
Any transcoding involved?

**Comment by nicoonline** [comment]
no we have disabled the transcoding. What i didn't understand is :
- We have a reinvite from OLO side
- We sent the reinvite to the customer
- We have the OK for the codec G711

RTPengine see a G722

**Comment by rfuchs** [comment]
Ok, so the codec information you see in the log output doesn't reflect rtpengine's internal state. Rtpengine will forward RTP regardless of what payload type or codec is used. The codec information in the log output is merely based on which codec (payload type) was seen the most of throughout the call. So if the codec information shown there doesn't reflect the codecs after the re-invite, then either the RTP client stopped sending RTP, or it didn't send enough of the new codec to "override" the one seen previously.
