### ISSUE TITLE
Rtpengine statistics description

### ISSUE THREAD

**Issue by rb-beip** [sipwise/rtpengine#913]
Hello,

Is it possible to find somewhere the description of statistics metrics published by rtpengine to graphite?

This is the full list of metrics which I get:

- answers_ps_avg
- answers_ps_max
- answers_ps_min
- answer_time_avg
- answer_time_max
- answer_time_min
- average_call_dur
- call_dur
- current_sessions_foreign
- current_sessions_own
- current_sessions_total
- deletes_ps_avg
- deletes_ps_max
- deletes_ps_min
- delete_time_avg
- delete_time_max
- delete_time_min
- final_timeout_sess
- forced_term_sess
- managed_sess_max
- managed_sess_min
- managed_sess
- nopacket_relayed_sess
- offers_ps_avg
- offers_ps_max
- offers_ps_min
- offer_time_avg
- offer_time_max
- offer_time_min
- offer_timeout_sess
- oneway_stream_sess
- regular_term_sess
- reject_sess
- relayed_errors
- relayed_packets
- silent_timeout_sess
- timeout_sess

Description for some metrics is obvious from the names but for some other is not.

Thanks in advance!

**Comment by pkuzak** [comment]
Do you know about following command:
> $ /usr/sbin/rtpengine-ctl list totals
This lists almost the same stats sent to Graphite, but the output is more "human understandable".

**Comment by rb-beip** [comment]
OK, thx! That's indeed enough to clarify the description.
