### ISSUE TITLE
Multiple dlg.terminate_dlg on RTP timeout 

### ISSUE THREAD

**Issue by mitesh-thakkar-plivo** [sipwise/rtpengine#914]
I am facing one issue on RTP timeout.

RTPEngine is sending two "dlg.terminate_dlg" events for single call to kamailio with same call-id but reversed to-tag and from-tag in second event. I believe this is due to two separate RTP streams.

Problem here is that - in first event kamailio terminates the call, hence when second event comes, kamailio says - call-id not found and send response back to RTPEngine. But still RTPEngine keeps sending that event message for three more times. Kamailio has to respond to it with call-id not found. Which is overhead. Not recommended for production environment.

How can I avoid this? Any help is appreciated.

**Comment by rfuchs** [comment]
Yes, I suppose trying to terminate the reverse path is superfluous. I'll prepare a fix.

**Comment by rfuchs** [comment]
Branch `rfuchs/914` contains two commits (5868c34 and 640d6f6) which should fix this. Entirely untested.

**Comment by mitesh-thakkar-plivo** [comment]
Thank you @rfuchs for immediate action on this. I will try those commits.

**Comment by rfuchs** [comment]
Any luck with this?

**Comment by mitesh-thakkar-plivo** [comment]
Hey, I couldn't test it yet. I got some other priority. I will come back to this soon. I will update once take this up.
