### ISSUE TITLE
No audio after 10 min

### ISSUE THREAD

**Issue by sem32** [sipwise/rtpengine#922]
Hi 

We have an issue with one way audio after hold / unhold call that have duration more than 10 min.

RTPEngine version: 8.1.1.3+0~mr8.1.1.3 git-mr8.1-b58aa79

Signaling path:
UserA (Telephone (pjsip)) -> kamailio -> rtpengine -> asterisk -> rtpengine -> kamailio -> UserB (WebRTC (SipJs))

Step to reproduce:
1. UserA call to UserB
2. UserB answer the call
3. UserA and UserB talk more then 10min
4. UserB put on hold UserA -> ~5sec UserB made un hold UserA
6. No audio for UserB (Media from RTPEngine exists, but  in Chrome logs I see:
[43799:4615:0128/182213.767919:WARNING:srtp_session.cc(146)] Failed to unprotect SRTP packet, err=7, previous failure count: 600
[43799:4615:0128/182213.768020:ERROR:srtp_transport.cc(222)] Failed to unprotect RTP packet: size=182, seqnum=2457, SSRC=1364914132, previous failure count: 600 

On side SipJs implemented reset peer connection for events hold / unhold (Browser initiate new DTLS connection, use new RTP port, use new fingerprint)

In case if I made hold / unhold before duration of call 10 minutes, media exists for both directions.

[Debug logs with log level 7](https://github.com/sipwise/rtpengine/files/4148856/rtpengine_log.txt)

**Comment by rfuchs** [comment]
Can you post your configuration? I'm a bit confused by some of the ICE messages. I suspect that your local interface is configured with an advertised address? Not that that's a problem, just to confirm what's in the log.

Other than that, the only unusual thing I see in the log is that after the final re-invite, a different peer address is negotiated through ICE than it was before. First:
```
Feb  3 14:24:33 2211000021be rtpengine[27809]: DEBUG: [322463603a2665474ec9d2252ebe8d61 port 35252]: ICE completed, using pair 4dRIXWHmsfyOAKxV:1902797413:1

a=candidate:1902797413 1 udp 1686052607 154.41.3.130 61406 typ srflx raddr 10.100.6.123 rport 61406 generation 0 network-id 1
```
After:
```
Feb  3 14:35:35 2211000021be rtpengine[27809]: DEBUG: [322463603a2665474ec9d2252ebe8d61 port 35252]: ICE completed, using pair 4dRIXWHmsfyOAKxV:931cdc2832db31ba0:1

Feb  3 14:35:35 2211000021be rtpengine[27809]: DEBUG: [322463603a2665474ec9d2252ebe8d61 port 35252]: Created candidate pair 4dRIXWHmsfyOAKxV:931cdc2832db31ba0:1 between 172.31.30.143 and 3.121.175.190:57451, type prflx
```
That port seems to be belong to an ICE candidate advertised by the WebRTC client, but with a different address:
```
v=0
o=- 8857061440834209924 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS 6s9TiZGsuemGMPRE6Hpf6PKKKCKjafdSRlhh
m=audio 57451 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 172.31.30.143
a=rtcp:9 IN IP4 0.0.0.0
...
a=candidate:3252810987 1 udp 41885439 172.31.30.143 57451 typ relay raddr 154.41.3.130 rport 52557 generation 0 network-id 1
```
In particular, both 172.31.30.143 and 3.121.175.190 seem to be local addresses? So it looks like the offer is sent, from the WebRTC's point of view, with the remote address in the SDP instead of the local one.

**Comment by sem32** [comment]
Hello Richard!
You are right I have one interface on cloud AWS 
Configuration: 
```
RUN_RTPENGINE=yes
PORT_MIN=35001
PORT_MAX=54998
LOG_LEVEL=7
TOS=0
LISTEN_NG=127.0.0.1:1026
LISTEN_CLI=127.0.0.1:1027
TIMEOUT=60
SILENT_TIMEOUT=300
PIDFILE=/var/run/rtpengine/rtpengine.pid
FORK=yes
TABLE=-1
LOG_FACILITY=daemon
NUM_THREADS=5
DELETE_DELAY=0
INTERFACES="all/172.31.30.143!3.121.175.190 "
```
So, 
PBX IPs: 172.31.30.143 - local address, 3.121.175.190 - external (advertised) address
WebRTC IPs: 10.100.6.123 - local address, 154.41.3.130 - external address
On side SipJs we added server reflexive candidate from STUN, and relay candidate for TURN,
but we have the same issue without these changes

New debug, logs and config (without reflexive candidates)
Version of RTPEngine is the same (RTPEngine version: 8.1.1.3+0~mr8.1.1.3 git-mr8.1-b58aa79)
Scenario for reproduce the same.
```
RUN_RTPENGINE=yes
PORT_MIN=37500
PORT_MAX=59998
LOG_LEVEL=7
TOS=0
LISTEN_NG=127.0.0.1:1026
LISTEN_CLI=127.0.0.1:1027
TIMEOUT=60
SILENT_TIMEOUT=300
PIDFILE=/var/run/rtpengine/rtpengine.pid
FORK=yes
TABLE=-1
LOG_FACILITY=daemon
NUM_THREADS=5
DELETE_DELAY=0
INTERFACES="all/172.31.47.218!52.29.93.114 "
```

Client IPs: local: 192.168.31.107, extern: 188.163.101.49
PBX IPs: local: 172.31.47.218, extern: 52.29.93.114

[rtpengine log debug level 7](https://github.com/sipwise/rtpengine/files/4159136/rtpengine_log3.txt)

Thank you

**Comment by rfuchs** [comment]
That still shows the same odd behaviour coming from the WebRTC client in that in inserts the wrong local IP in the SDP in the re-invites.

First SDP:
```
m=audio 55678 UDP/TLS/RTP/SAVPF 8 0
c=IN IP4 192.168.31.107
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:888428568 1 udp 2122260223 192.168.31.107 55678 typ host generation 0 network-id 1 network-cost 10
a=candidate:637429059 1 udp 2122194687 10.64.100.30 62952 typ host generation 0 network-id 2 network-cost 50
...
Created candidate pair JkclVCPYXGrciI0g:b6b56765387d0aba0:1 between 172.31.47.218 and 188.163.101.49:4537, type prflx
...
ICE completed, using pair JkclVCPYXGrciI0g:b6b56765387d0aba0:1
ICE negotiated: local interface 172.31.47.218
```
Re-invite SDP:
```
m=audio 60962 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 172.31.47.218
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:888428568 1 udp 2122260223 192.168.31.107 64027 typ host generation 0 network-id 1 network-cost 10
a=candidate:637429059 1 udp 2122194687 10.64.100.30 62632 typ host generation 0 network-id 2 network-cost 50
a=candidate:2054661352 1 tcp 1518280447 192.168.31.107 9 typ host tcptype active generation 0 network-id 1 network-cost 10
a=candidate:1803393459 1 tcp 1518214911 10.64.100.30 9 typ host tcptype active generation 0 network-id 2 network-cost 50
a=candidate:3208306489 1 udp 8331007 172.31.47.218 60962 typ relay raddr 127.0.0.1 rport 57669 generation 0 network-id 1 network-cost 10
```
However that doesn't seem to affect rtpengine much as ICE is still negotiated onto the same address:
```
Created candidate pair JkclVCPYXGrciI0g:b6b5641a387d0aba0:1 between 172.31.47.218 and 188.163.101.49:4806, type prflx
...
ICE completed, using pair JkclVCPYXGrciI0g:b6b5641a387d0aba0:1
ICE negotiated: peer for component 1 is 188.163.101.49:4806
ICE negotiated: local interface 172.31.47.218
```
DTLS is also established and media flows correctly in both directions:
```
Feb  5 11:51:35 221100000f0f rtpengine[14365]: INFO: [1080dee9452e5b397fed222122266d78 port 37642]: DTLS: Peer certificate accepted
Feb  5 11:51:35 221100000f0f rtpengine[14365]: DEBUG: [1080dee9452e5b397fed222122266d78 port 37642]: DTLS handshake successful
Feb  5 11:51:35 221100000f0f rtpengine[14365]: INFO: [1080dee9452e5b397fed222122266d78 port 37642]: DTLS-SRTP successfully negotiated
Feb  5 11:51:35 221100000f0f rtpengine[14365]: DEBUG: [1080dee9452e5b397fed222122266d78 port 37642]: SRTP keys, incoming:
Feb  5 11:51:35 221100000f0f rtpengine[14365]: DEBUG: [1080dee9452e5b397fed222122266d78 port 37642]: --- AES_CM_128_HMAC_SHA1_80 key eSlWedjDi+Y87xozWvKhTQ== salt aeTaYT2rmIycbsoiBig=
Feb  5 11:51:35 221100000f0f rtpengine[14365]: DEBUG: [1080dee9452e5b397fed222122266d78 port 37642]: SRTP keys, outgoing:
Feb  5 11:51:35 221100000f0f rtpengine[14365]: DEBUG: [1080dee9452e5b397fed222122266d78 port 37642]: --- AES_CM_128_HMAC_SHA1_80 key xX8Neb+yDj9BfAgHzLWRHA== salt D+v7VsBHgLOa7stWfz8=
Feb  5 11:51:35 221100000f0f rtpengine[14365]: INFO: [1080dee9452e5b397fed222122266d78 port 37642]: DTLS-SRTP successfully negotiated
Feb  5 11:51:35 221100000f0f rtpengine[14365]: DEBUG: [1080dee9452e5b397fed222122266d78 port 37642]: SRTP keys, incoming:
Feb  5 11:51:35 221100000f0f rtpengine[14365]: DEBUG: [1080dee9452e5b397fed222122266d78 port 37642]: --- AES_CM_128_HMAC_SHA1_80 key eSlWedjDi+Y87xozWvKhTQ== salt aeTaYT2rmIycbsoiBig=
Feb  5 11:51:35 221100000f0f rtpengine[14365]: DEBUG: [1080dee9452e5b397fed222122266d78 port 37642]: SRTP keys, outgoing:
Feb  5 11:51:35 221100000f0f rtpengine[14365]: DEBUG: [1080dee9452e5b397fed222122266d78 port 37642]: --- AES_CM_128_HMAC_SHA1_80 key xX8Neb+yDj9BfAgHzLWRHA== salt D+v7VsBHgLOa7stWfz8=
...
Feb  5 11:51:43 221100000f0f rtpengine[14365]: DEBUG: [1080dee9452e5b397fed222122266d78 port 37712]: Forward to sink endpoint: 188.163.101.49:4806 (RTP seq 3890 TS 4904800)
Feb  5 11:51:43 221100000f0f rtpengine[14365]: DEBUG: [1080dee9452e5b397fed222122266d78 port 37642]: Forward to sink endpoint: 52.29.93.114:17818 (RTP seq 32117 TS 3305700013)
```
So I can't really see anything wrong here other than the odd choice of primary address in the WebRTC client.

**Comment by rfuchs** [comment]
Cleaning up old tickets
