### ISSUE TITLE
RTPengine 7.5.1 version. Can't get statistics for one leg: No payload type known for RTCP RR, discarding

### ISSUE THREAD

**Issue by ovoshlook** [sipwise/rtpengine#924]
Hi here. 
I'm using 7.5.1.
Im trying to figure out why I can't get RTCP Stats for one of the legs (there is actually 2 calls, but issue happens for both)
I see RTCP SR and RR packets comes from both endpoins for all calls but can't get why RR can't be parsed. (I see message No payload type known for RTCP RR, discarding ).

So it happens for the 201 payload arrived. 
SR/RR messages looks fine ( at least I don't see anything really weird in it )

On 6.3 version of RTPengine it seems works fine (or just ignores payload but still parses successfully )

file with DEBUG level output attached
[rtpegnine_eu_c.log](https://github.com/sipwise/rtpengine/files/4160119/rtpegnine_eu_c.log)

Really appreciate help with understanding what is goes wrong. 
Thank you.

P.S. Meanwhile Im gonna update to newest version to see if it will help, but still understanding of the issue will be helpfull anyway.

**Comment by rfuchs** [comment]
Compare the SSRCs from the RTCP with the SSRCs of the actual RTP. If the RTCP is either from or about an SSRC that wasn't actually seen participating in the RTP, it will have to be discarded because it's unknown which codec that SSRC is speaking. The codec must be known because the jitter value is reported based on the codec's clock rate.

**Comment by ovoshlook** [comment]
Thx for the response. I make a couple of other tests and - Yeah, It is definitely something weird happens on the UA side that is behind rtpengines.

It is a Asterisk B2BUA  behind and when I land call to the asterisk and just answer - everything goes well,
But if I make second call from the Asterisk to somewhere else - this happens. Looks like asterisk sends SSRC of wrong leg. Will investigate deeper and update here at least for the history. Closing this ticket.

**Comment by ovoshlook** [comment]
Hello, Did not have enough time to investigate problem described in my message above, but now found some interesting behaviour  which I should share here as it more about rtpegnine, than B2BUA:

So, I have a scenario:
UAC 1 <----> rtpengine <----> b2bua <-----> rtpengine <----> UAC 2

when call reaches UAC2 and b2bua answers, in time before b2bua will send Accept response to UA 1 it strats to generate RTP with ssrc 1111

So in this case we have :
b2bua (ssrc 1111) ----> rtpengine ----> UAC2

uac 2 responses with ssrc 2222:
b2bua <---- rtpengine <---- (ssrc 2222 ) UAC2

And this ssrc 2222 resends to UAC1 via b2bua:
UAC1<---- rtpengine <---- b2bua <---- rtpengine <---- (ssrc 2222 ) UAC2

UAC1 starts to generate it's rtp:
UAC1 (ssrc 3333)----> rtpengine ----> b2bua ----> rtpengine ----> UAC2

This means that for RTPengine ssrc 2222 and ssrc 3333 the same for 2 different calls, they are just have opposite direction.

If I will use 2 rtpengines (one for inbounds and another for outbounds ) it looks like ok, but as I got it rtpengine has no namespace for the call and in that case it tries to match SSRC for one call with SSRC for another call and discards it.

Is there anyway to add some namespace or context for the RTCP stats to get understanding that calls does not cross.

I can put some details here with dumps and logs from RTPengine if scenario is not really clear, but I hope it is :-)

P.S: I will reopen it.

**Comment by rfuchs** [comment]
That is easily possible if you just use the same call ID :smile:

**Comment by ovoshlook** [comment]
Main thing that I don't.
Im using asterisk as B2BUA so I kind of protected of that as asterisk generates it's own call ID for the second leg.
Here is a RTPengine output above attached (it is looks the same with above I sent, but here is a proof that I am not using the same callID)
[rtpengine.log](https://github.com/sipwise/rtpengine/files/4344362/rtpengine.log)

**Comment by rfuchs** [comment]
This should work though. It's basically just two separate calls with media flowing both ways in both.

The only things I notice are:

1) No RTCP port listed in the final stats - presumably due to BUNDLE? AFAIK the fallback RTCP port should still be listed though.

2) The SSRC reported in the MOS output doesn't match any of the SSRC seen in the RTP stats. So again, as I said before, something weird going on with the SSRCs coming from the clients, and you can check that by doing a packet dump and looking at the SSRCs in the RTP and RTCP.

**Comment by ovoshlook** [comment]
Yeah I have a dump (it was cantched on B2BUA as central point : 10.10.102.8 that begind rtpengine 10.10.102.13 ):
[dump.pcap.zip](https://github.com/sipwise/rtpengine/files/4344731/dump.pcap.zip)

It is definitely something strange on B2BUA side:
In case of pcap - I see some sender requests that was sent from b2bUA with "old" SSRC's (that belonged to first couple of packets from B2BUA to rtpengine , like 8087 packet number and 8095 )

But my point of "it more about rtpegnine, than B2BUA"  not about - rtpengine works incorrect or so

I found discarded packets in the scenario when 2 separate rtpengines involved for each leg ( one for UAC1 <---> rtpengine1 and rtpenigne2 <---> UAC2 )
But in that case I still facing 2 of 3 SSRC's filled  for each leg:
for 1'st leg 2 SSRC's and stats for them filled succesfully and for 2'd same.

but in case of 1 rtpengine I see 2 SSRC's filled only for one leg, and another leg does not filled (you could see it in a query requests for the different legs).

That is why I thinking that it is mixed context of 2 separate calls with when same SSRC. at leas I don't have additional understanding of lost stats in case of using 1 rtpengine

**Comment by rfuchs** [comment]
What do your offer/answer options looks like? They're missing from the log.

**Comment by ovoshlook** [comment]
Sorry, I forgot to answer: yeah it is a BUNDLE for both sides (B2BUA is Asterisk with pjsip driver with rtcp_mux=yes setup )

So I use kamailio with rtpengine module, so flags are:
To B2BUA: replace-origin replace-session-connection direction=pub direction=priv ICE=remove RTP/AVP

from B2BUA: replace-origin replace-session-connection SDES-off DTLS=passive direction=priv direction=pub ICE=force rtcp-mux-accept rtcp-mux-offer UDP/TLS/RTP/SAVPF

**Comment by rfuchs** [comment]
Any chance you can post a full log that has the offer and answer included, together with a matching pcap?

**Comment by ovoshlook** [comment]
yeah. Here it is:
[Archive.zip](https://github.com/sipwise/rtpengine/files/4345261/Archive.zip)

**Comment by rfuchs** [comment]
Detailed analysis is below, the TLDR version is:

Apply the filter `udp.srcport == 14100` in Wireshark to see just one RTP media flow, plus the RTCP reports coming from the same source. The RTP media uses SSRC 962a6216, but the RTCP reports use sender SSRC 5e031902. This is obviously incorrect and so rtpengine has no way to match up the RTCP reports with the RTP media. So whatever is sending from that port 14100 is at fault.

You can look at the reverse flow with `udp.dstport == 14100` to see how RTP and RTCP SSRCs should correctly match up.

Details:

The pcap only shows the plain RTP side of the call and omits the SRTP side. So this isn't very helpful to see where the SSRC mismatch comes from.

Take this one for example:
```
Mar 17 18:49:01  rtpengine[28256]: DEBUG: [84080051-bccc-4544-86c9-3dbfe1f0406a port 45514]: Calling handler for RTCP packet type 201
Mar 17 18:49:01  rtpengine[28256]: DEBUG: [84080051-bccc-4544-86c9-3dbfe1f0406a port 45514]: RR from f3f90a71 about 962a6216: FL 0 TL 0 HSR 2407 J 167 LSR 0 DLSR 0
Mar 17 18:49:01  rtpengine[28256]: DEBUG: [84080051-bccc-4544-86c9-3dbfe1f0406a port 45514]: No payload type known for RTCP RR, discarding
```
So rtpengine complains about now knowing about SSRC 962a6216. This SSRC clearly shows up in the pcap, but only in plain RTP. From the log, rtpengine port 45514 (where this was received) is SRTP.

I can match this RTCP to packet 5226 in the pcap, sent to port 14100 (outgoing I assume).

Now the reverse side of this call leg would be on rtpengine's port 45532. SSRC 962a6216 is clearly active there:
```
Mar 17 18:49:44  rtpengine[28256]: INFO: [84080051-bccc-4544-86c9-3dbfe1f0406a]: --------- Port    10.10.102.13:45532 <>     10.10.102.8:14100, SSRC 962a6216, 1732 p, 130363 b, 0 e, 29 ts
```
However, all the RTCP reports received on that port claimed to be from a different SSRC:
```
Mar 17 18:49:00  rtpengine[28256]: DEBUG: [84080051-bccc-4544-86c9-3dbfe1f0406a port 45532]: SR from 5e031902: RTP TS 771059136 PC 997 OC 63896 NTP TS 3793459740/453385216=3793459740.105562
Mar 17 18:49:00  rtpengine[28256]: DEBUG: [84080051-bccc-4544-86c9-3dbfe1f0406a port 45532]: RR from 5e031902 about f3f90a71: FL 0 TL 0 HSR 17320 J 167 LSR 2437323340 DLSR 136445
```
This is packet 4890 in the pcap. With the sender SSRC in the RTCP reports not matching the SSRC used in the RTP media, rtpengine cannot match up the report with the media.
