### ISSUE TITLE
Interfaces configuration

### ISSUE THREAD

**Issue by volga629** [sipwise/rtpengine#93]
In my setup I have 2 interfaces private and public ip. Rtpengine as run the following
Can't find where is miss configured.

```
rtpengine_manage("replace-origin replace-session-connection internal external RTP/AVP");
```

```
root     19082     1  0 Mar22 ?        00:02:32 /usr/sbin/rtpengine --pidfile /var/run/rtpengine.pid --port-min=10000 --listen-ng=127.0.0.1:2223 --table=5 --log-level=6 --port-max=20000 --listen-udp=127.0.0.1:2222 --log-facility=local2 --interface pub/public ip --interface priv/private ip
```
The issue 

```
No usable address in interface 'external' found, using default
```

**Comment by rfuchs** [comment]
If you want to use the "internal" and "external" flags, you need to name your interfaces accordingly, i.e. `--interface internal/public ip --interface external/private ip` or some such. Alternatively, you would use `direction=pub direction=priv` instead.

**Comment by volga629** [comment]
Thank I fixed my configuration and everything works as expected.
