### ISSUE TITLE
Customize naming of call records

### ISSUE THREAD

**Issue by Shkiperon** [sipwise/rtpengine#930]
Hello.
Is it possible to make custom naming of call records like "callid-datestamp" instead of "callid-randomHash"?
Or maybe there is a way to somehow collect the file names in the CDR?

**Comment by rfuchs** [comment]
You can enable the MySQL database backend and the recording daemon will write the call metadata to the DB, including any custom metadata string you have set for it.

**Comment by Shkiperon** [comment]
Is it possible to use Redis backend for saving names of call records?

**Comment by rfuchs** [comment]
Only MySQL is supported for this right now.

**Comment by Shkiperon** [comment]
Ok, thanks for the information
