### ISSUE TITLE
RTPEngine MOS labeling and stats

### ISSUE THREAD

**Issue by andrepi** [sipwise/rtpengine#931]
Hello, we have the following scenario: SIP Server > K+RTPengine > Webrtc SIP.js client and  we have just started using Homer. We labeled rtpengine so we could have MOS statistics from each leg. The question is:

What is the leg definition for MOS calculation?

1) The direction of the RTP stream:
Leg A is RTP stream from SIP server > K+RTPEngine > Webrtc
Leb B is  RTP stream from Webrtc > K+RTPEngine > SIP Server

2) Each leg of the call
Leg A: inbound and outbound RTP Stream from SIP Server t> K+RTPEngine
Leg B: inbound and outbound RTP Stream from Webrtc > K+RTPEngine

In definition 1 if there is a connection problems with webrtc network will impact both Leg A and Leg B MOS. On the other hand, on definition 2, a problem with webrtc network would affect only  Leg B MOS.

Thanks!

**Comment by rfuchs** [comment]
MOS calculation is based on RTCP receiver reports sent by the RTP clients. Those are a unidirectional view of the RTP that they receive. So the MOS calculated for leg A is based on A's view of the RTP quality that A received.

**Comment by andrepi** [comment]
Thanks rfuchs! Just to confirm my understanding, so in my example, once webrtc side had network issues (pakket loss, latency, ...) the MOS from SIP server will be affected and both leg A and B MOS will be low, right?

**Comment by rfuchs** [comment]
If the packet loss is bidirectional, then yes, both MOS will be affected.

**Comment by andrepi** [comment]
Got it rfuchs!! Thanks a lot!!
