### ISSUE TITLE
How to install rtpengine 8.2.1 to debian 9?

### ISSUE THREAD

**Issue by thadeu** [sipwise/rtpengine#932]
Currently is broken this deb source 

`https://deb.sipwise.com/spce/mr8.2.1`

![Screen Shot 2020-02-17 at 13 27 28](https://user-images.githubusercontent.com/77889/74671230-7693f980-5189-11ea-8c5e-7ed9836565ea.png)

**Comment by thadeu** [comment]
When I use http://deb.sipwise.com/debian latest build is `7.4.2.2+0~mr7.4.2.2`

**Comment by mika** [comment]
@thadeu where do have that `stretch` for NGCP 8.2.1 from? The mr8.2.1 release is `buster` based (so Debian 10), so you need to put `buster` into it, or if you want a stretch based build then use a stretch based release (like `mr7.4.2` what you've configured already), but using a buster based release won't work with stretch. ;)
