### ISSUE TITLE
chrome console output "obsolete (D)TLS version"

### ISSUE THREAD

**Issue by xmglin** [sipwise/rtpengine#933]
How to fix "obsolete (D)TLS version"?
rtpengine: 8.2.1.1
kamailio: 5.3.2
lastest chrome console output:
[Deprecation] Your partner is negotiating an obsolete (D)TLS version. Support for this will be removed in M81, around March 2020. Please check with your partner to have this fixed.
Any suggestion?

**Comment by seanbright** [comment]
What version of OpenSSL do you have installed?

**Comment by xmglin** [comment]
openssl-1.0.1e-58.el6_10.x86_64
latest CentOS6
should I upgrade openssl?

**Comment by seanbright** [comment]
Yes. You need 1.0.2 or higher.

**Comment by rfuchs** [comment]
Thanks @seanbright

**Comment by xmglin** [comment]
Thanks @seanbright
