### ISSUE TITLE
Detected command ... as a duplicate

### ISSUE THREAD

**Issue by MarcoHierl** [sipwise/rtpengine#935]
Hello,

I'm using rtpengine (Version: 8.3.0.0+0~mr8.3.0.0 git-master-088c58d8) on Debian GNU/Linux 10 with OpenSIPS 2.4 and for about every fith call I get one-way-speech in one or the other direction.

In the rtpengine log (see below) I found: Detected command from 10.249.152.7:58897 as a duplicate. 
There was only 1 call on that machine during that time and I can see from IP trace on listen-ng interface (see below), that the message only came once!

In my example the offer got a new SDP back from rtpengine, but the answer failed:

**seen from sip proxy:**

Feb 19 14:14:30 sbc-colt-hh /usr/opensips/akt/sbin/opensips[4174]: ........... rtpengine_offer(in-iface=internal out-iface=internal replace-session-connection replace-origin port-latching ICE=remove,,10,udp:10.249.152.8:60001)
Feb 19 14:14:34 sbc-colt-hh /usr/opensips/akt/sbin/opensips[4174]: ........... rtpengine_answer(in-iface=internal out-iface=internal replace-session-connection replace-origin port-latching ICE=remove,,10)
**Feb 19 14:14:34 sbc-colt-hh /usr/opensips/akt/sbin/opensips[4174]: ERROR:rtpengine:rtpengine_offer_answer: failed to extract sdp body from proxy reply**
Feb 19 14:14:49 sbc-colt-hh /usr/opensips/akt/sbin/opensips[4179]: ........... rtpengine_delete(rtpset=10)

**trace to listen-ng:**

U 10.249.152.7:58897 -> 10.249.152.8:60001 #87
0_9 d3:sdp239:v=0.
o=root 1296435396 1296435396 IN IP4 10.250.56.11.
s=Asterisk PBX 16.6.2.
c=IN IP4 10.250.56.11.
t=0 0.
m=audio 20548 RTP/AVP 8 101.
a=rtpmap:8 PCMA/8000.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-16.
a=maxptime:150.
a=sendrecv.
3:ICE6:remove9:directionl8:internal8:internale5:flagsl13:port-latchinge7:replacel18:session-connection6:origine7:call-id43:73901ba04126e46b0c920dbd5c5d3c0a@next-id.de13:received-froml3:IP411:10.250.56.9e8:from-tag10:as217f34be7:command5:offere

U 10.249.152.8:60001 -> 10.249.152.7:58897 #88
0_9 d3:sdp253:v=0.
o=root 1296435396 1296435396 IN IP4 10.249.152.8.
s=Asterisk PBX 16.6.2.
c=IN IP4 10.249.152.8.
t=0 0.
m=audio 24686 RTP/AVP 8 101.
a=maxptime:150.
a=rtpmap:8 PCMA/8000.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-16.
a=sendrecv.
a=rtcp:24687.
6:result2:oke

U 10.249.152.7:58897 -> 10.249.152.8:60001 #89
0_10 d3:sdp224:v=0.
o=root 647105837 647105837 IN IP4 10.249.152.33.
s=sip call.
c=IN IP4 10.249.152.33.
t=0 0.
m=audio 16930 RTP/AVP 8 101.
a=rtpmap:8 PCMA/8000.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-16.
a=ptime:20.
a=sendrecv.
3:ICE6:remove9:directionl8:internal8:internale5:flagsl13:port-latchinge7:replacel18:session-connection6:origine7:call-id43:73901ba04126e46b0c920dbd5c5d3c0a@next-id.de13:received-froml3:IP413:10.249.152.33e8:from-tag10:as217f34be6:to-tag10:as2fed14517:command6:answere

U 10.249.152.8:60001 -> 10.249.152.7:58897 #90
0_10 d7:createdi1582118010e10:created_usi849720e11:last signali1582118012e4:SSRCd9:419571653de10:1081578067dee4:tagsd10:as42349182d3:tag10:as423491827:createdi1582118010e16:in dialogue with10:as48ab29dc6:mediasld5:indexi1e4:type5:audio8:protocol7:RTP/AVP7:streamsld10:local porti24596e8:endpointd6:family4:IPv47:address13:10.249.152.314:porti18024ee19:advertised endpointd6:family4:IPv47:address13:10.249.152.314:porti18024ee11:last packeti1582118015e5:flagsl3:RTP6:fillede4:SSRCi419571653e5:statsd7:packetsi222e5:bytesi38184e6:errorsi0eeed10:local porti24597e8:endpointd6:family4:IPv47:address13:10.249.152.314:porti18025ee19:advertised endpointd6:family4:IPv47:address13:10.249.152.314:porti18025ee11:last packeti1582118010e5:flagsl4:RTCP6:fillede5:statsd7:packetsi0e5:bytesi0e6:errorsi0eeee5:flagsl11:initialized4:send4:recv15:ICE controllingeeee10:as48ab29dcd3:tag10:as48ab29dc7:createdi1582118010e16:in dialogue with10:as423491826:mediasld5:indexi1e4:type5:audio8:protocol7:RTP/AVP7:streamsld10:local porti24610e8:endpointd6:family4:IPv47:address13:10.249.152.934:porti27572ee19:advertised endpointd6:family4:IPv47:address13:10.249.152.934:porti27572ee11:last packeti1582118015e5:flagsl3:RTP6:fillede4:SSRCi1081578067e5:statsd7:packetsi124e5:bytesi21328e6:errorsi0eeed10:local porti24611e8:endpointd6:family4:IPv47:address13:10.249.152.934:porti27573ee19:advertised endpointd6:family4:IPv47:address13:10.249.152.934:porti27573ee11:last packeti1582118010e5:flagsl4:RTC

U 10.249.152.7:60252 -> 10.249.152.8:60001 #91
0_48 d7:call-id43:73901ba04126e46b0c920dbd5c5d3c0a@next-id.de13:received-froml3:IP413:10.249.152.33e8:from-tag10:as2fed14517:command6:deletee

U 10.249.152.8:60001 -> 10.249.152.7:60252 #92
0_48 d7:warning38:Call-ID not found or tags didn't match6:result2:oke

**and the log from rtpengine:**

Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: INFO: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: Received command 'offer' from 10.249.152.7:58897
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: Dump for 'offer' from 10.249.152.7:58897: { "sdp": "v=0
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: o=root 1296435396 1296435396 IN IP4 10.250.56.11
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: s=Asterisk PBX 16.6.2
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: c=IN IP4 10.250.56.11
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: t=0 0
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: m=audio 20548 RTP/AVP 8 101
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: a=rtpmap:8 PCMA/8000
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: a=rtpmap:101 telephone-event/8000
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: a=fmtp:101 0-16
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: a=maxptime:150
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: a=sendrecv
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: ", "ICE": "remove", "direction": [ "internal", "internal" ], "flags": [ "port-latching" ], "replace": [ "session-connection", "origin" ], "call-id": "73901ba04126e46b0c920dbd5c5d3c0a@next-id.de", "received-from": [ "IP4", "10.250.56.9" ], "from-tag": "as217f34be", "command": "offer" }
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: NOTICE: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: Creating new call
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: Default sink codec is PCMA/8000
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: 0 DTMF sink entries
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: Creating codec handler for PCMA/8000
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: Sink supports codec PCMA/8000
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: Using passthrough handler for PCMA/8000
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: Creating codec handler for telephone-event/8000
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: Sink supports codec telephone-event/8000
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: Using passthrough handler for telephone-event/8000
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: creating send_timer
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: creating send_timer
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: creating send_timer
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: creating send_timer
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: set FILLED flag for stream 10.250.56.11:20548
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: set FILLED flag for stream 10.250.56.11:20549
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: INFO: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: Replying to 'offer' from 10.249.152.7:58897 (elapsed time 0.000161 sec)
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: Response dump for 'offer' to 10.249.152.7:58897: { "sdp": "v=0
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: o=root 1296435396 1296435396 IN IP4 10.249.152.8
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: s=Asterisk PBX 16.6.2
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: c=IN IP4 10.249.152.8
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: t=0 0
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: m=audio 24686 RTP/AVP 8 101
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: a=maxptime:150
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: a=rtpmap:8 PCMA/8000
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: a=rtpmap:101 telephone-event/8000
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: a=fmtp:101 0-16
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: a=sendrecv
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: a=rtcp:24687
Feb 19 14:14:30 rtp-colt-hh rtpengine[1609]: ", "result": "ok" }
**Feb 19 14:14:34 rtp-colt-hh rtpengine[1609]: INFO: Detected command from 10.249.152.7:58897 as a duplicate**
Feb 19 14:14:35 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de port 24687]: Calling handler for RTCP packet type 200
Feb 19 14:14:35 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de port 24687]: SR from 3f9c0c84: RTP TS 40000 PC 250 OC 40000 NTP TS 3791106875/2166094475=3791106875.504333
Feb 19 14:14:35 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de port 24687]: RR from 3f9c0c84 about 75c22e37: FL 0 TL 0 HSR 19110 J 14 LSR 0 DLSR 884703494
Feb 19 14:14:35 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de port 24687]: No payload type known for RTCP RR, discarding
Feb 19 14:14:35 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de port 24687]: Calling handler for RTCP packet type 202
Feb 19 14:14:35 rtp-colt-hh rtpengine: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de] version=2, padding=0, count=1, payloadtype=200, length=12, ssrc=1067191428, ntp_sec=3791106875, ntp_fractions=2166094475, rtp_ts=40000, sender_packets=250, sender_bytes=40000, ssrc=1975660087, fraction_lost=0, packet_loss=0, last_seq=19110, jitter=14, last_sr=0, delay_since_last_sr=884703494, version=2, padding=0, count=1, payloadtype=202, length=2
Feb 19 14:14:40 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de port 24687]: Calling handler for RTCP packet type 200
Feb 19 14:14:40 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de port 24687]: SR from 3f9c0c84: RTP TS 80000 PC 500 OC 80000 NTP TS 3791106880/2167434505=3791106880.504645
Feb 19 14:14:40 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de port 24687]: RR from 3f9c0c84 about 75c22e37: FL 0 TL 0 HSR 19360 J 10 LSR 3007309215 DLSR 37027
Feb 19 14:14:40 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de port 24687]: No payload type known for RTCP RR, discarding
Feb 19 14:14:40 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de port 24687]: Calling handler for RTCP packet type 202
Feb 19 14:14:40 rtp-colt-hh rtpengine: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de] version=2, padding=0, count=1, payloadtype=200, length=12, ssrc=1067191428, ntp_sec=3791106880, ntp_fractions=2167434505, rtp_ts=80000, sender_packets=500, sender_bytes=80000, ssrc=1975660087, fraction_lost=0, packet_loss=0, last_seq=19360, jitter=10, last_sr=3007309215, delay_since_last_sr=37027, version=2, padding=0, count=1, payloadtype=202, length=2
Feb 19 14:14:45 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de port 24687]: Calling handler for RTCP packet type 200
Feb 19 14:14:45 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de port 24687]: SR from 3f9c0c84: RTP TS 120000 PC 750 OC 120000 NTP TS 3791106885/2165261251=3791106885.504139
Feb 19 14:14:45 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de port 24687]: RR from 3f9c0c84 about 75c22e37: FL 0 TL 0 HSR 19611 J 7 LSR 3007636891 DLSR 36896
Feb 19 14:14:45 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de port 24687]: No payload type known for RTCP RR, discarding
Feb 19 14:14:45 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de port 24687]: Calling handler for RTCP packet type 202
Feb 19 14:14:45 rtp-colt-hh rtpengine: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de] version=2, padding=0, count=1, payloadtype=200, length=12, ssrc=1067191428, ntp_sec=3791106885, ntp_fractions=2165261251, rtp_ts=120000, sender_packets=750, sender_bytes=120000, ssrc=1975660087, fraction_lost=0, packet_loss=0, last_seq=19611, jitter=7, last_sr=3007636891, delay_since_last_sr=36896, version=2, padding=0, count=1, payloadtype=202, length=2
Feb 19 14:14:49 rtp-colt-hh rtpengine[1609]: INFO: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: Received command 'delete' from 10.249.152.7:60252
Feb 19 14:14:49 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: Dump for 'delete' from 10.249.152.7:60252: { "call-id": "73901ba04126e46b0c920dbd5c5d3c0a@next-id.de", "received-from": [ "IP4", "10.249.152.33" ], "from-tag": "as2fed1451", "command": "delete" }
Feb 19 14:14:49 rtp-colt-hh rtpengine[1609]: INFO: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: Tag 'as2fed1451' in delete message not found, ignoring
Feb 19 14:14:49 rtp-colt-hh rtpengine[1609]: INFO: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: Replying to 'delete' from 10.249.152.7:60252 (elapsed time 0.000007 sec)
Feb 19 14:14:49 rtp-colt-hh rtpengine[1609]: DEBUG: [73901ba04126e46b0c920dbd5c5d3c0a@next-id.de]: Response dump for 'delete' to 10.249.152.7:60252: { "warning": "Call-ID not found or tags didn't match", "result": "ok" }

**Comment by rfuchs** [comment]
This might be a bug in the OpenSIPS version of the control module. The first token in each UDP command (e.g. `0_9`) is supposed to be a unique message identifier and is (in Kamailio) the process ID plus an increasing counter. Zero is obvious not a valid PID and so I suspect there's collisions there. You should take it up with the OpenSIPS people.

**Comment by razvancrainea** [comment]
@rfuchs I agree the problem is on the OpenSIPS side - although the identifier in OpenSIPS is generated in the same manner as Kamailio, there seems to be a corner case where we're not properly populating the local pid. That, of course, will generate the broken message identifier. Thanks for taking your time to look into this!

**Comment by MarcoHierl** [comment]
Working, thanks!!
Indeed the problem occured when I tried to phase in rtpengine on a life server. In set 0 rtpproxy was active, in set 10 rtpengine was defined and I did not restart opensips befor using set 10.
