### ISSUE TITLE
Closing call due to timeout

### ISSUE THREAD

**Issue by abieuzent** [sipwise/rtpengine#938]
Hi,

when i look to the current session handling, i find some calls already end. In logs this calls is ended 1 hours after the real end of the call with this information :

Feb 20 11:39:17 rtpe-owf-out01 rtpengine[10711]: INFO: [39f2c1770429f6296bbab699785927ce@185.101.180.137:5060]: Closing call due to timeout

Why the timeout or silent-timeout didn't close this call before ?

I'm running rtpengine : 7.4.2.2+0~mr7.4.2.2 

rtpengine.conf :

timeout = 60
 silent-timeout = 120
 tos = 184
 delete-delay = 0
 # final-timeout = 10800

Thanks

**Comment by rfuchs** [comment]
Impossible to say without knowing what happened throughout the lifetime of this call. Was it only half established? Did it have RTP one-way? Were there any lingering branches?

**Comment by rfuchs** [comment]
Cleaning up old tickets
