### ISSUE TITLE
When receiving an SDP with multiple c lines, rtpengine transforms only one of them

### ISSUE THREAD

**Issue by SipSeb** [sipwise/rtpengine#942]
From time to time, we receive INVITEs from foreign networks with SDP looking like this:

```
v=0
o=- 1636970084 1972 IN IP4 10.0.206.138
s=-
c=IN IP4 1.2.3.4
t=0 0
m=audio 10998 RTP/AVP 8 101
c=IN IP4 1.2.3.4
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=ptime:20
```

Notice the duplicate c= lines. According to [RfC4566 section 5.7](https://tools.ietf.org/html/rfc4566#section-5.7), multiple c lines are only allowed in multicast scenarios. So it is probably a bug at the sender side. However, since we can't fix all carriers out there, we have to deal with that scenario internally.

After handling the SDP, it looks like this:

```
v=0
o=- 1636970084 1972 IN IP4 3.3.3.3
s=-
c=IN IP4 1.2.3.4
t=0 0
m=audio 22020 RTP/AVP 8 101
c=IN IP4 5.5.5.5
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=rtcp:22021
a=ptime:20
```

This causes one of the devices in our network to try to send audio directly to 1.2.3.4 (the carrier IP address) instead of sending it to 5.5.5.5 (our rtpengine IP address) as desired.

Can you add a fix to rtpengine, so it fixes all c lines in the SDP? That would help a lot. Thanks.

We are still on revision 7.5.2.x, but will upgrade to 8.2.1 if needed.

**Comment by rfuchs** [comment]
Use `replace-session-connection`

**Comment by SipSeb** [comment]
Thanks, I missed that. Works.
