### ISSUE TITLE
Ptime missmatch between both parties

### ISSUE THREAD

**Issue by nicoonline** [sipwise/rtpengine#944]
Hello,

We tried to engage the transcoding to repacketize the stream based on the maxptime in the answer SIP packet. As stated in the doc this is not supported. Do you think it will be in the future ?
Using the transcoding is a nice feature but we cannot know the maxptime before the answer :)

Any ideas can help :)

**Comment by rfuchs** [comment]
We don't have plans for such a feature, at least in the foreseeable future. My understanding is that both ptime and maxptime in the SDP are just hints anyway, so I would just use the ptime you want to use.

**Comment by nicoonline** [comment]
I agree but if a choose a ptime of 20 (default) and on a few calls we got a maxptime of 10, it will not works
