### ISSUE TITLE
Failed to init DTLS connection: ee key too small

### ISSUE THREAD

**Issue by mwoop** [sipwise/rtpengine#945]
I am a bit confused: signalling is fine, determined IPs and ports in rtpengine are fine, ... but audio is not flowing - looks like we have an issue with DTLS here: "Failed to init DTLS connection: ee key too small" - never seen this error before.

JSSIP WebRTC client on Chrome calls via Kamailio/rtpengine to an Asterisk box which simply plays an audio file.

Mar  6 10:12:11 webrtc rtpengine[2325]: INFO: Received command 'ping' from 10.19.0.6:34394
Mar  6 10:12:11 webrtc rtpengine[2325]: INFO: Replying to 'ping' from 10.19.0.6:34394 (elapsed time 0.000000 sec)
Mar  6 10:12:25 webrtc rtpengine[2325]: INFO: [l551bavtb4v6klidbfec]: Received command 'offer' from 10.19.0.6:45110
Mar  6 10:12:25 webrtc rtpengine[2325]: NOTICE: [l551bavtb4v6klidbfec]: Creating new call
Mar  6 10:12:25 webrtc rtpengine[2325]: ERR: [l551bavtb4v6klidbfec]: Failed to init DTLS connection: ee key too small
Mar  6 10:12:25 webrtc rtpengine[2325]: ERR: [l551bavtb4v6klidbfec]: Failed to init DTLS connection: ee key too small
Mar  6 10:12:25 webrtc rtpengine[2325]: INFO: [l551bavtb4v6klidbfec]: Replying to 'offer' from 10.19.0.6:45110 (elapsed time 0.001887 sec)
Mar  6 10:12:25 webrtc rtpengine[2325]: INFO: [l551bavtb4v6klidbfec]: Received command 'answer' from 10.19.0.6:59213
Mar  6 10:12:25 webrtc rtpengine[2325]: ERR: [l551bavtb4v6klidbfec]: Failed to init DTLS connection: ee key too small
Mar  6 10:12:25 webrtc rtpengine[2325]: ERR: [l551bavtb4v6klidbfec]: Failed to init DTLS connection: ee key too small
Mar  6 10:12:25 webrtc rtpengine[2325]: INFO: [l551bavtb4v6klidbfec]: Replying to 'answer' from 10.19.0.6:59213 (elapsed time 0.000951 sec)
Mar  6 10:12:25 webrtc rtpengine[2325]: INFO: [l551bavtb4v6klidbfec port 30426]: ICE negotiated: local interface 10.19.0.6
Mar  6 10:13:25 webrtc rtpengine[2325]: INFO: [l551bavtb4v6klidbfec]: Closing call due to timeout
Mar  6 10:13:25 webrtc rtpengine[2325]: INFO: [l551bavtb4v6klidbfec]: Final packet stats:
Mar  6 10:13:25 webrtc rtpengine[2325]: INFO: [l551bavtb4v6klidbfec]: --- Tag 'h8pf20blb5', created 1:00 ago for branch '', in dialogue with 'as6fc29e37'
Mar  6 10:13:25 webrtc rtpengine[2325]: INFO: [l551bavtb4v6klidbfec]: ------ Media #1 (audio over RTP/SAVPF) using unknown codec
Mar  6 10:13:25 webrtc rtpengine[2325]: INFO: [l551bavtb4v6klidbfec]: --------- Port       10.19.0.6:30426 <>  185.22.143.242:59362, SSRC 0, 1 p, 64 b, 0 e, 60 ts
Mar  6 10:13:25 webrtc rtpengine[2325]: INFO: [l551bavtb4v6klidbfec]: --- Tag 'as6fc29e37', created 1:00 ago for branch '', in dialogue with 'h8pf20blb5'
Mar  6 10:13:25 webrtc rtpengine[2325]: INFO: [l551bavtb4v6klidbfec]: ------ Media #1 (audio over RTP/AVP) using unknown codec
Mar  6 10:13:25 webrtc rtpengine[2325]: INFO: [l551bavtb4v6klidbfec]: --------- Port       10.19.0.6:30404 <>    18.197.25.18:15296, SSRC 0, 0 p, 0 b, 0 e, 60 ts
Mar  6 10:13:25 webrtc rtpengine[2325]: INFO: [l551bavtb4v6klidbfec]: --------- Port       10.19.0.6:30405 <>    18.197.25.18:15297 (RTCP), SSRC 0, 0 p, 0 b, 0 e, 60 ts

Kamailio & rtpengine are running on a low-memory virtual machine (1GB RAM). 

Any help  is appreciated. Let me know in case you'll need more infos.

Mark.

**Comment by rfuchs** [comment]
You can try updating your OpenSSL, or maybe something akin to https://github.com/sipwise/rtpengine/pull/918/commits/ce55edf063f94ed73a5dc46e9653545c8cc93004

**Comment by mwoop** [comment]
OpenSSL is up to date (latest stable version 1.1.1) and changing/recompiling the source code as suggested didn't help either. I will re-investigate after my well deserved holiday.

Thanks so far!

**Comment by sergey-safarov** [comment]
You can try config option `dtls-rsa-key-size`.
For me, it helps me resolve the error `Failed to init DTLS connection: ee key too small`.

**Comment by rfuchs** [comment]
We have these options available in newer versions now, yes. Also the defaults should be more appropriate.

Closing issue.
