### ISSUE TITLE
Build of mr8.2.1.2 fails without WITH_TRANSCODING on Debian Buster

### ISSUE THREAD

**Issue by abalashov** [sipwise/rtpengine#949]
If `with_transcoding` is set to no in the `Makefile`, it seems there's a reference to a function that is only defined `#ifdef WITH_TRANSCODING`:

```
codec.c: In function ‘codec_handlers_free’:
codec.c:807:47: error: ‘__codec_handler_free’ undeclared (first use in this function); did you mean ‘codec_handler_free’?
  g_queue_clear_full(&m->codec_handlers_store, __codec_handler_free);
                                               ^~~~~~~~~~~~~~~~~~~~
                                               codec_handler_free
codec.c:807:47: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by abalashov** [comment]
This seems to do the trick:

```
diff --git a/daemon/codec.c b/daemon/codec.c
index 5f608c2f..260367e9 100644
--- a/daemon/codec.c
+++ b/daemon/codec.c
@@ -804,8 +804,8 @@ void codec_handlers_free(struct call_media *m) {
                g_hash_table_destroy(m->codec_handlers);
        m->codec_handlers = NULL;
        m->codec_handler_cache = NULL;
-       g_queue_clear_full(&m->codec_handlers_store, __codec_handler_free);
 #ifdef WITH_TRANSCODING
+       g_queue_clear_full(&m->codec_handlers_store, __codec_handler_free);
        m->dtmf_injector = NULL;
 #endif
 }
```

**Comment by rfuchs** [comment]
This is already fixed in the mr8.2 branch.

**Comment by abalashov** [comment]
Ausgezeichnet! Danke schön. :-)

On Wed, Mar 11, 2020 at 10:28:06AM -0700, Richard Fuchs wrote:
> This is already fixed in the mr8.2 branch.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sipwise/rtpengine/issues/949#issuecomment-597765320

-- 
Alex Balashov | Principal | Evariste Systems LLC

Tel: +1-706-510-6800 / +1-800-250-5920 (toll-free) 
Web: http://www.evaristesys.com/, http://www.csrpswitch.com/
