### ISSUE TITLE
Build Fails on Debian 10.1 with transcoding

### ISSUE THREAD

**Issue by dimm71** [sipwise/rtpengine#950]
I want to build it with transcoding support.
But it doesn 't pass the test...

#   Failed test 'received packet matches'
#   at ../perl/NGCP/Rtpengine/AutoTest.pm line 169.
#                   '���8B���'
#     doesn't match '(?^s:^\�\�\\�\\\8B\�\�a\\\�$)'
rtp in 0 1005 3800 13398
rtp matcher 101 1005 3640 1116327009 080f0140
rtp recv 101 1005 3640 1116327009 08100140
not ok 686 - received packet matches
#   Failed test 'received packet matches'
#   at ../perl/NGCP/Rtpengine/AutoTest.pm line 169.
#                   '�e�8B��@'
#     doesn't match '(?^s:^\�e\\�\\\8B\�\�a\\\@$)'
rtp in 0 1006 3960 13398
rtp matcher 101 1006 3640 1116327009 088f01e0
rtp recv 101 1006 3640 1116327009 089001e0
not ok 687 - received packet matches
#   Failed test 'received packet matches'
#   at ../perl/NGCP/Rtpengine/AutoTest.pm line 169.
#                   '�e�8B����'
#     doesn't match '(?^s:^\�e\\�\\\8B\�\�a\\�$)'

...
...
# Looks like you failed 20 tests of 732.
make[3]: *** [Makefile:111: daemon-tests] Error 20
rm sdp.strhash.c call_interfaces.strhash.c control_ng.strhash.c
make[3]: Leaving directory '/usr/src/rtpengine/t'
make[2]: *** [../lib/common.Makefile:4: all] Error 2
make[2]: Leaving directory '/usr/src/rtpengine/t'
make[1]: *** [Makefile:34: check] Error 2
make[1]: Leaving directory '/usr/src/rtpengine'
dh_auto_test: make -j4 check returned exit code 2
make: *** [debian/rules:25: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

**Comment by rfuchs** [comment]
Post more of the output please, so I can see which tests those are

**Comment by dimm71** [comment]
Here is a more complete log https://pastebin.com/tVcFg3Ex

**Comment by rfuchs** [comment]
Looks like your spandsp is returning a slightly different volume for the DTMF events. What platform is this on?

**Comment by dimm71** [comment]
This is a single-board computer http://www.orangepi.org/orangepiplus2e/

**Comment by rfuchs** [comment]
That explains. Fix coming shortly.

**Comment by rfuchs** [comment]
Does it work for you with c0be3ea applied?

**Comment by dimm71** [comment]
Yes. All tests passed. Packages are collected. Thanks
