### ISSUE TITLE
Replying to optional SRTP with RTP/SAVP

### ISSUE THREAD

**Issue by billsimon** [sipwise/rtpengine#951]
We are using rtpengine as a media decryption point in our network. On the public side of the proxy calls come to us with SRTP or DTLS media encryption, and then the offer is made to internal media servers with the "RTP/AVP" flag set to decrypt the media inside the private network.

When calls come using optional SRTP (media transport RTP/AVP but includes a=crypto lines) rtpengine answers with RTP/AVP, no crypto. Is there a configuration for rtpengine to tell it to reply to such offers with encrypted media?

**Comment by rfuchs** [comment]
That kind of SDP is not supported right now. Is there an RFC for this?

**Comment by billsimon** [comment]
See https://tools.ietf.org/html/rfc8643 for "Opportunistic SRTP"

Even though the RFC is new, this practice seems to have been going on for a while. 

The media server we use, FreeSwitch, acknowledges this practice and provides an exception flag to allow for it (https://freeswitch.org/confluence/display/FREESWITCH/NDLB - see NDLB-allow-crypto-in-avp)

**Comment by rfuchs** [comment]
Thanks, will try to add support for this in the near future.

**Comment by billsimon** [comment]
Here is an example of an offer I just captured (the RFC is plenty clear, but it's always nice to have examples).

```
m=audio 64718 RTP/AVP 9 0 8 101
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=crypto:1 AES_CM_128_HMAC_SHA1_32 inline:QL0eZKqjhrmUzBmCEw7EeKfAWyRV20yamJANR16+
a=crypto:2 AES_CM_128_HMAC_SHA1_80 inline:QL0eZKqjhrmUzBmCEw7EeKfAWyRV20yamJANR16+
a=sendrecv
m=video 54066 RTP/AVP 99 34
a=rtpmap:99 H264/90000
a=fmtp:99 profile-level-id=42801f;packetization-mode=0
a=rtpmap:34 H263/90000
a=fmtp:34 CIF4=1;CIF=1;QCIF=1
a=rtcp-fb:* ccm fir
a=rtcp-fb:* nack pli
a=crypto:1 AES_CM_128_HMAC_SHA1_32 inline:Q3G5CE39sQ/2NOWbcMaIhVC0YpYZ6mJT4pF0r/CQ
a=crypto:2 AES_CM_128_HMAC_SHA1_80 inline:Q3G5CE39sQ/2NOWbcMaIhVC0YpYZ6mJT4pF0r/CQ
a=content:main
a=sendrecv
```

**Comment by billsimon** [comment]
Thanks so much for the quick feature-add, @rfuchs !
