### ISSUE TITLE
[HELP] How to get number of "active calls" through NG

### ISSUE THREAD

**Issue by Shkiperon** [sipwise/rtpengine#954]
ngcp-rtpengine-daemon version is mr8.4.0.0
Is it possible to get through ng-protocol number of "active calls" from rtpengine instance?
What I have found in README:

`rtpengine-ng-client list --proxy-address=127.0.0.1 --proxy-port=2223`
this command write in output up to 32 calls in list

```
rtpengine-ng-client list limit='5' --proxy-address=127.0.0.1 --proxy-port=2223
rtpengine-ng-client list limit 5 --proxy-address=127.0.0.1 --proxy-port=2223
rtpengine-ng-client list limit=5 --proxy-address=127.0.0.1 --proxy-port=2223
```
These commands write in output up to 32 calls too.

I need just a number of active calls on rtpengine instance. Is it possible to do that through ng protocol or I must to use another solutions to resolve my issue?

**Comment by rfuchs** [comment]
We don't currently have a stats query like this in NG, and the `list` output is limited due to it being UDP. You can use the shell tool `rtpengine-ctl` though.

`rtpengine-ctl list numsessions`

**Comment by Shkiperon** [comment]
Ok, thanks for the help
