### ISSUE TITLE
srtp_session.cc(146) Failed to unprotect SRTP packet, err=7

### ISSUE THREAD

**Issue by jamesaylett** [sipwise/rtpengine#956]
Hi,

We encountered an obscure issue with RTPEngine and what we believe to be OpenSSL with the latest Intel CPUs. See https://software.intel.com/en-us/articles/openssl-sha-crash-bug-requires-application-update. We run RTPEngine on CentOS 7 (which the default repo's latest OpenSSL is 1.0.2k).

When this issue occurs, RTPEngine doesn't log anything to suggest an error - however chrome debug logs would log: 

> srtp_session.cc(146) Failed to unprotect SRTP packet, err=7

After which the client would no longer hear any audio (as chrome would discard the SRTP packets because the authentication tag failed to match the computed tag in libsrtp.

We resolved the issue by targeting a later OpenSSL version - CentOS EPEL v1.1.1c.

This issue was difficult to analyse as RTPEngine doesn't output any packet info when debug logging, instead we had to resort to tshark captures and manual encrypt/decrypt using the srtp-debug-helper util. It might be worth logging some more information to help debugging (auth tags/payload before/after encryption).

I opened this in case others encounter similar issues. Feel free to close.

**Comment by rfuchs** [comment]
What kind of debug output would have been helpful to you?

**Comment by jamesaylett** [comment]
I think it would be useful to log the same info that is required and outputted by the srtp-debug-helper - that way we can be sure what RTPEngine's view of the data is. When investigating we couldn't be sure if the problem was a bug with RTPEngine, packet corruption from some other source (Firewall/Docker/network stack). It was an odd problem to debug as we run the same OpenSSL version on our development kit but older hardware so initially we were ruling out OpenSSL.

You already log the session keys, and seq no's on debug, so perhaps every 500 packets or so you log the unencrypted payload, roll over counter, encrypted payload, and computed auth tag. Then it would trivial to verify with srtp-debug-helper from just the logs.
