### ISSUE TITLE
Transcode and Telephone-Event

### ISSUE THREAD

**Issue by lasseo** [sipwise/rtpengine#963]
Hi all, 

I need to know if I am doing something wrong or if I have spotted a bug, perhaps it is both.
DTMF support via RFC 2833/4733 wanted.

Client uses Opus/48000. Remote part is PCMA.

Client SDP offer
```
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1;maxplaybackrate=16000;sprop-maxcapturerate=16000;maxaveragebitrate=12000;cbr=1
a=rtpmap:120 telephone-event/48000
a=fmtp:120 0-16
```

RtpEngine command:
```replace-origin replace-session-connection ICE=remove direction=external direction=internal codec-mask-all transcode-PCMA transcode-telephone-event```

RtpEngine offer:
```
a=rtpmap:8 PCMA/8000
a=rtpmap:96 telephone-event/8000
a=fmtp:96 0-15
```
SEMS response:
```
a=rtpmap:8 PCMA/8000
a=rtpmap:96 telephone-event/8000
a=fmtp:96 0-15
```

RtpEngine command:
```replace-origin replace-session-connection ICE=remove symmetric-codecs always-transcode```

RtpEngine response:
```
    m=audio 30054 RTP/AVP 96 120
    a=direction:both
    a=rtpmap:96 telephone-event/8000
    a=rtpmap:120 telephone-event/48000
    a=fmtp:96 0-15
    a=fmtp:120 0-16
```

**Opus codec is not listed within the RtpEngine reply!?**

If I remove transcode-telephone-event, Opus is replied back as expected.
Is this the correct way to handle DTMF conversion?

**Comment by rfuchs** [comment]
Which version are you on?

**Comment by lasseo** [comment]
> Which version are you on?
From GitRepo synced last week.

**Comment by rfuchs** [comment]
Ah, this is a collision in numeric payload types... 🙄 will fix.

**Comment by rfuchs** [comment]
See 1055a1e71e3b5d63912f5adc1e8e58b8a10a4f58 for a patch that should fix it.

**Comment by lasseo** [comment]
@rfuchs The patch resolves the issue.
