### ISSUE TITLE
SDES KeyInfo

### ISSUE THREAD

**Issue by alextatham** [sipwise/rtpengine#966]
Hello everyone,

I'm asking for some help to modify rtpengine to provide the KeyInfo in the SDES offer.  I'm working to use RTPEngine with Microsoft Direct Routing but I thik there is a problem with the SDES headers in the SDP offer.  As I understand it, in their platform, and I'm not 100% on my terminology here, the lifetime of the key must be added to the end of the key/salt.  I got as far as editing the sdp.c to output this in versions up to 6 but it wasn't working.  I updated to version 8 and now the unit testing defeates me and I'm utterly stuck.

The second part of the problem is, and I don't know for sure, but I think the code also needs to be modified to absorb the lifetime when it is processed back in the other direction.

I think this is all just in the sdp.c file but that's about as far as I can get.  For a proper solution it really needs a flag that can be used to turn this on or off.

Is anyone willing to help with this.  I have an Office 365 tenant and Kamailio server built and I have it working with a commercial SBC for comparison.

Hoping for some friendly help and thanks.

**Comment by rfuchs** [comment]
You're talking about the `["|" lifetime]` parameter from https://tools.ietf.org/html/rfc4568#section-6.1 ?

Adding it to the SDP wouldn't be a big problem, but as you've correctly noted, key lifetimes aren't supported. The reason is that an expired master key would require a re-invite to exchange new master keys, and rtpengine has no way to trigger or generate a re-invite.

**Comment by alextatham** [comment]
Yeah that is the paramater.  I don't think re-negotiating the key is that critical to my needs as in all the testing I've done they only support one encryption method and it always gives the lifetime as 2^31 which is the equivalent of 68 years.  I've noted in Oracle's SBC how they got over compatability with Microsoft's platform is added the ability to concatenate text onto the crypto header.  That's where I was going with my thinking.  I appreciate that this might be implementing part but not all of a protocol.

**Comment by rfuchs** [comment]
Try with e59ccc2 (branch `rfuchs/966`)

**Comment by alextatham** [comment]
Cool.  I'll take a copy of that branch and feedback.

**Comment by alextatham** [comment]
Thanks for your help with this.

The code builds installs and the debugger module logs the crypto line with the lifetime as per below so many thumbs up.  Unfortunately the symtoms remain.  I'm going to keep working this problem.

**Comment by rfuchs** [comment]
As a suggestion, also try `SDES-pad` and/or disable unsupported crypto suites with `SDES-no-AES_256_CM_HMAC_SHA1_80` etc
