### ISSUE TITLE
RTP Recording Issue

### ISSUE THREAD

**Issue by nicoonline** [sipwise/rtpengine#968]
Hello,

We have this in our logs (in loop)

Apr 16 11:18:03 proxy1 rtpengine-recording[1468]: ERR: [C 1980126900_114049848%400000-e99a7eedac697812.meta] [S tag-1-media-1-component-1-RTP-id-0] [0x6fc6e1d6] Failed to add frame to mixer: index out of range
Apr 16 11:18:03 proxy1 rtpengine-recording[1468]: ERR: [C 1980126900_114049848%400000-e99a7eedac697812.meta] [S tag-1-media-1-component-1-RTP-id-0] [0x6fc6e1d6] Failed to add decoded packet to mixed output
Apr 16 11:18:03 proxy1 rtpengine-recording[1468]: ERR: [C 1980126900_114049848%400000-e99a7eedac697812.meta] [S tag-1-media-1-component-1-RTP-id-0] [0x6fc6e1d6] Failed to add frame to mixer: index out of range
Apr 16 11:18:03 proxy1 rtpengine-recording[1468]: ERR: [C 1980126900_114049848%400000-e99a7eedac697812.meta] [S tag-1-media-1-component-1-RTP-id-0] [0x6fc6e1d6] Failed to add decoded packet to mixed output
Apr 16 11:18:03 proxy1 rtpengine-recording[1468]: ERR: [C 1980126900_114049848%400000-e99a7eedac697812.meta] [S tag-1-media-1-component-1-RTP-id-0] [0x6fc6e1d6] Failed to add frame to mixer: index out of range
Apr 16 11:18:03 proxy1 rtpengine-recording[1468]: ERR: [C 1980126900_114049848%400000-e99a7eedac697812.meta] [S tag-1-media-1-component-1-RTP-id-0] [0x6fc6e1d6] Failed to add decoded packet to mixed output
Apr 16 11:18:03 proxy1 rtpengine-recording[1468]: ERR: [C 1980126900_114049848%400000-e99a7eedac697812.meta] [S tag-1-media-1-component-1-RTP-id-0] [0x6fc6e1d6] Failed to add frame to mixer: index out of range
Apr 16 11:18:03 proxy1 rtpengine-recording[1468]: ERR: [C 1980126900_114049848%400000-e99a7eedac697812.meta] [S tag-1-media-1-component-1-RTP-id-0] [0x6fc6e1d6] Failed to add decoded packet to mixed output
Apr 16 11:18:03 proxy1 rtpengine-recording[1468]: ERR: [C 1980126900_114049848%400000-e99a7eedac697812.meta] [S tag-1-media-1-component-1-RTP-id-0] [0x6fc6e1d6] Failed to add frame to mixer: index out of range
Apr 16 11:18:03 proxy1 rtpengine-recording[1468]: ERR: [C 1980126900_114049848%400000-e99a7eedac697812.meta] [S tag-1-media-1-component-1-RTP-id-0] [0x6fc6e1d6] Failed to add decoded packet to mixed output
Apr 16 11:18:03 proxy1 rtpengine-recording[1468]: ERR: [C 1980126900_114049848%400000-e99a7eedac697812.meta] [S tag-1-media-1-component-1-RTP-id-0] [0x6fc6e1d6] Failed to add frame to mixer: index out of range

Is it expected?

**Comment by rfuchs** [comment]
This can happen if there are too many SSRCs seen participating in a call. The mixer uses one input slot per SSRC and only has a fixed number of them (4 I think) allocated.

Some RTP clients seem to change SSRC randomly during a call for some reason. That's not currently well supported.

**Comment by digipigeon** [comment]
I am also experiencing this error. 60 times per second.

It seems to add a considerable amount of CPU overhead when we see this. If this happens is there any possibility of recovering. If not could we move to stop the recording operation, or at least reduce whatever is CPU bound here?

**Comment by rfuchs** [comment]
I have a fix for this on my short-term radar.

**Comment by digipigeon** [comment]
Hi @rfuchs I don't suppose you have been able to push a fix for this one yet, as its still causing us loading problems.

Thanks.

**Comment by rfuchs** [comment]
We have it as TT#86103 internally but I've been sidetracked with other issues in the meantime.

**Comment by digipigeon** [comment]
Hi @rfuchs I just wanted to follow up on this one to see if it has been fixed yet, thank you.

**Comment by rfuchs** [comment]
I don't have a good way to test this myself, so can you see if 3e2d16f works for you please.
