### ISSUE TITLE
Permit the use of Hostname in --interface parameter

### ISSUE THREAD

**Issue by felipem1210** [sipwise/rtpengine#969]
Hi, 
It would be a nice feature to permit the use of hostname in the --interface parameter. I say it because I'm trying to have a cluster of Rtpengine machines in AWS putting them behind a Netwok Load Balancer. So I would like to make rtpengine use a hostname pointing to NLB. Is this topic on the table for you? 

Thanks
Best regards

**Comment by rfuchs** [comment]
We've had some talk about DNS-based load balancing, but nothing concrete is planned yet. Also it depends on your exact use case. Host name in `c=` line? Or resolve the address on startup? Or continuously during runtime? Or ...?

**Comment by felipem1210** [comment]
ON startup
When I start the daemon in --interface option, in my case:

rtpengine -i external/10.0.8.34!MY_HOSTNAME_HERE -n 10.0.8.34:22222 -m 7000 -M 65000 --table=0 -L 7 --log-stderr

**Comment by rfuchs** [comment]
DNS resolve of the advertised address on startup should be pretty easy to implement. Look at `if_addr_parse()` in `main.c` (esp lines 220-225) if you want to give it a shot yourself.
