### ISSUE TITLE
feature: backport echo canceler into rtpengine kernel module

### ISSUE THREAD

**Issue by sergey-safarov** [sipwise/rtpengine#970]
Linux kernel have [`echo`](https://cateee.net/lkddb/web-lkddb/ECHO.html) module that implements echo canceler for "mISDN and Zaptel drivers".

I have source code short view and not found dependency for other drivers. I believe we can utilize this module for VoIP lines without modification.
Any way if other kernel module dependency is present, could you back port echo canceler implementation into `rtpengine` kernel module.

**Comment by rfuchs** [comment]
Er, no. The rtpengine kernel module does packet forwarding. It doesn't get into the audio data, which is required for echo cancellation. If you want echo cancellation, it would have to be done in userspace by decoding and re-encoding the audio streams, adding an appropriate filter in between.
