### ISSUE TITLE
RTP-Recording : bad quality wav.

### ISSUE THREAD

**Issue by nicoonline** [sipwise/rtpengine#979]
Hello,

We are using RTP Recording version 6.5.7.4 and we experienced bad quality audio on some wav's.
That doesn't affect RTP audio heared by both ends.

Can i send you a wav example in private ?

Thanks

**Comment by rfuchs** [comment]
Ya sure. Ideally with a matching pcap that contains the RTP so I can try to reproduce it.

**Comment by nicoonline** [comment]
Bug here https://github.com/sipwise/rtpengine/issues/861
Will be backported to mr6.5

**Comment by rfuchs** [comment]
Fixes backported and release tagged.
