### ISSUE TITLE
Blocking inband DTMF

### ISSUE THREAD

**Issue by goharahmed** [sipwise/rtpengine#980]
Hi, 
I was testing the block DTMF function and it works perfectly with RFC2833 packets however the inband DTMF were still passing through. I know we're detecting the inband DTMFs via DSP (as mentioned in docs and another issue), however, is it possible to drop inbands as well ! 

If its already implemented then possibly I missed some flag, I only used rtpengine with "block DTMF" params thinking it should be sufficient enough.

**Comment by rfuchs** [comment]
No, that's not currently implemented. Blocking is supported for RFC events only.

**Comment by goharahmed** [comment]
Ok thanks for clarification. I'm going to look if I can manage to modify source code to make it work.

**Comment by rfuchs** [comment]
It probably requires engaging the DSP as it would when transcoding PCM<>RFC, and then suppress output of the actual events when blocking is enabled.

**Comment by goharahmed** [comment]
I was going to do that, and got shy asking if Im headed in right direction or not.
Thankyou.
