### ISSUE TITLE
rtpengine cannot reconnect to redis after lost connection

### ISSUE THREAD

**Issue by kdanderso** [sipwise/rtpengine#982]
I am building an active/passive Pacemaker HA system for Kamailio using rtpengine with redis to persist rtp on failover.  The system uses a floating IP (10.9.9.120 on my system) that is assigned to the master node.  There are only two nodes in the system.  I am using the latest commit of rtpengine (2ef93af).

rtpengine and redis will be running on both nodes when the system is fully operational.  redis will be configured as master on the master node and slave on the slave node.  rtpengine on both nodes is configured to connect to redis using the floating IP address.

One of the tests I am using to verify failover operation is to kill redis-server on the master node, which causes the rtpengine instances on both nodes to lose their connection to redis.

Once the connection is lost, rtpengine enters a loop to re-establish the connection and I see the following log message once per second:

    INFO: RE-Establishing connection for Redis server 10.9.9.120:6379

Pacemaker will eventually detect the loss of redis, demote the current master, and promote the current slave.  At that time, rtpengine should be able to connect to redis (since redis is again running at 10.9.9.120) but the above message continues to be logged once per second.

I added some additional debug to redis.c and see the following behavior:

rtpengine calls redis_notify_loop() (line 578) in redis.c.  This establishes a connection to redis and ultimately calls redis_notify() at line 607.  As long as the connection remains up, redis_notify() does not return.

When the connection is lost, redis_notify() returns and the code enters a while() loop.  A call is made to redis_check_conn() at line 620.

redis_check_conn() will attempt to PING redis (line 722) and returns REDIS_STATE_CONNECTED if the ping is successful.  In my tests, once redis is back up after the failover, the PING succeeds so this is the path taken.

redis_notify_loop() checks the return value, and since it isn't REDIS_STATE_RECONNECTED, the code in the corresponding if clause is not executed.  Hence, there is no call to redis_notify(), so the loop continues to try to re-connect and continues to do so forever.

If I add a check for REDIS_STATE_CONNECTED on the return, the problem seems to be resolved.  However, I don't fully understand all of what is happening in redis_check_conn() so am concerned that there might be side effects that I am unaware of.

**Comment by rfuchs** [comment]
Looking at the code, I believe REDIS_STATE_CONNECTED and REDIS_STATE_RECONNECTED should really be the same thing as there's no point in distinguishing between the two. I don't quite understand how in your case you immediately get a successful PING after being disconnected from Redis without going through redis_connect() (line 735) first, but the point remains.

**Comment by rfuchs** [comment]
Give 85328a8b a try

**Comment by kdanderso** [comment]
Thank you for the update.  It appears to resolve the issue I had described.

I was also concerned about not having gone through redis_connect(), so have done some additional testing.  This is what I'm seeing:

When redis-server on the node with the floating IP is killed, the other node can no longer communicate with redis, so it enters the loop to monitor for a reconnection (line 611).  Eventually, the floating IP gets moved to the second node.  When redis_check_conn() subsequently calls redis_connect(), redis_connect() is able to establish a connection with redis.

However, once redis_connect() makes it through AUTH, PING, and SELECT, it checks to see if redis is master or slave.  In this case, redis is slave, but it needs to be master (i.e. redis has not been promoted yet).  redis_connect() checks for master mode two times and then returns -1, indicating an error.  redis_check_conn() returns REDIS_STATE_DISCONNECTED and the monitoring loop keeps trying.

The next call to redis_check_conn() succeeds, because the connection is established and so PING is successful.  redis_check_conn() returns REDIS_STATE_CONNECTED and the monitoring loop exits successfully.  However, redis is still in slave mode, even though it needs to be in master mode.

Eventually, redis gets promoted to master and everything seems to work.  But if redis_connect() is supposed to prevent connections when redis is in the wrong mode, it seems like redis_check_conn() should not be succeeding in this case.  Does that issue need to be addressed?

**Comment by rfuchs** [comment]
Yes you're quite right. See 9da12d8. This is contributed code so I'm not 100% sure about this, but I'm pretty confident.

**Comment by kdanderso** [comment]
The latest version is working in my tests.  I think it's good to go.

Thank you for your time.
