### ISSUE TITLE
nftables kernel module

### ISSUE THREAD

**Issue by amessina** [sipwise/rtpengine#984]
This is simply a feature request, in case there is interest other than mine, for an nftables kernel module.

**Comment by jrozhon** [comment]
Yep, this module would be highly appreciated. Count me in.

**Comment by sergey-safarov** [comment]
Could you can look also [cilium](https://github.com/cilium/cilium)
This project also actively use XDP and used in Kubernetes.

If some refactoring is possible in the future, could you also implemented with XDP support.
This allows use the `RTPengine` with `Kamailio` in `Kubernetes` environment as `SIP ingres`.

**Comment by gedia** [comment]
So it appears debian bullseye comes with nft by default. I wonder if rtpengine's xtables module is still compatible with this distro or if some sort of development would be required...

**Comment by rfuchs** [comment]
As of right now, the kernel module is fully usable and compatible with the `iptables-nft` frontend from Bullseye. The only thing that doesn't work is manipulating the corresponding chain entry directly with the `nft` tool.

**Comment by amessina** [comment]
As time has passed, I'm wondering if there is any interest in an nftables approach.  A firewalld user is reporting upcoming RHEL-based depreciation warnings related to nft_compat: https://github.com/firewalld/firewalld/issues/1111

**Comment by rfuchs** [comment]
To my knowledge this would require a patched/custom set of nft CLI tools as there's no support for plugins or modules.

**Comment by amessina** [comment]
> To my knowledge this would require a patched/custom set of nft CLI tools as there's no support for plugins or modules.

I'm sure you're right, @rfuchs.  I'm just trying to look ahead from a Fedora sysadmin perspective as to what it could/would look like as the legacy tools begin to move away.

**Comment by amessina** [comment]
Thank you @rfuchs for starting development on this.  In initial testing (Fedora 38), I get the following error on startup when using rtpengine built with nftables support:
```
kernel: xt_RTPENGINE ID too high (32764 >= 64)
rtpengine[581494]: CRIT: [core] Fatal error: Failed to create nftables chains or rules: error returned from netlink for add rule (Invalid argument)
```
