### ISSUE TITLE
opensips rtpnegine and freeswitch

### ISSUE THREAD

**Issue by dimebage** [sipwise/rtpengine#986]
Dear team we have scenario which we are not sure how to correctly implement .
we have clients on public network coming into opensips on public interface then we forward the call on private interface to freeswitch , freeswitch does some control mechanism and lookup and then invite the opensips again on private interface to dial the callee as opensips is our AOR keeper .
rtpengine in engaged in following form :

from caller to rtpengine  external interface -> from rtpengine  internal interface to freeswitch -> from freeswitch to rtpengine internal interface -> from rtpengine  internal interface to external client.

This actually works without problem , but we have requirements in which mostly we do not want to freeswitch to be in RTP path unless in some specific cases so we use reinvite from freeswitch so it should come out of media path.
This is where things are not working and after reinvite we loose the media on clients and the call would drop possibly because of media going to wrong destination and timeouts.
Would you please advise how rtpenigne should engage in this case ?
Regards

**Comment by rfuchs** [comment]
This is hard to answer without seeing the signalling flow in detail, but in general: In the initial `offer` (invite), you tell rtpengine through the two `direction=` flags which interface the offer is arriving on (caller interface) and which interface it's leaving on (called interface). In subsequent signalling (which includes the `answer` as well as any re-invites) you would simply omit the `direction=` flags, assuming the interfaces in use don't change and that all the signalling details (call ID, from/to tags) are correct.

**Comment by dimebage** [comment]
Thank you rfuchs,
In fact we are nearly doing as you have said.
But im not really clear on what to do when reinvites occur some how we want to terminate the freeswitch two RTP legs toward rtpengine on internal interface  and the clients should then become proxied over external interface.
Currently when reinvites occur i have mess at my hand as i have not found any way to tell rtpengine to forget about the internal legs it had with freeswitch and continue the media between two client on public interface.
I will add signaling flow and description regarding this.
Best regards
