### ISSUE TITLE
rtpengine general questions forum

### ISSUE THREAD

**Issue by githubsw** [sipwise/rtpengine#987]
Hello, 
I know this is not an issue but I did not know where else to ask this question - 
Is there an rtpengine forum to ask general questions?

Thank you,

**Comment by rfuchs** [comment]
You can ask here, or perhaps on our corporate mailing list (even though not specific to rtpengine): https://lists.sipwise.com/mailman/listinfo/spce-user_lists.sipwise.com

If it's more related to SIP/Kamailio in general, their mailing list would be appropriate: https://lists.kamailio.org/cgi-bin/mailman/listinfo/sr-users

**Comment by githubsw** [comment]
Great, Thank you.

I have rtpengine installed and working with Kamailio on several servers.  I can verify, with traces, that the RTP flow is correct, however, on some servers I do not see the RTP packets in the rtpengine log file.  Usually I see them flow by as the call continues.  I have verified the rtpengne configurations are the same on all servers.  Does anyone have an idea as to what could be happening.

Thank you

**Comment by rfuchs** [comment]
If a packet trace (taken locally on the server) confirms that the RTP packets are actually arriving but not registering with rtpengine, then it's probably a local network configuration issue (e.g. mismatched IP addresses), and/or perhaps a local firewall blocking them.

**Comment by AshishPandyaEcosmob** [comment]
Hello Folks,

I am trying to install RTPEngine v12.x in Amazon Linux 2023. But during installation, i am facing issue of dependency of several packages which is not there on Amazon Linux 2023 i.e. FFmpeg, libwebsockets, lame, libopus, and opus. I have done manual compilation of all these packages from their respective github repositories. After that, RTPEngine started to compile but stuck with missing "avcodec_close" flag which is related to FFMPEG. As per few articles, this flag is deprecated and not any more in use by FFMPEG 7.x. 

I need help or suggestion from RTPEngine community to resolve this issue. Main requirement is to install RTPEngine in Amazon Linux 2023 only.

Regards,
