### ISSUE TITLE
Problems with SRTP using openssl 1.0.1e-30.el6.5 or higher on CentOS 6

### ISSUE THREAD

**Issue by ulfwatt** [sipwise/rtpengine#99]
Hi,
I’m not actually sure this is an issue in rtpengine, but anyway. I patched our CentOS servers and got this error 
‘rtpengine[11098]: [audioa9193f70-9d16-4e0d-b7ad-b4e7dec2c163 port 32086] SRTP output wanted, but no crypto suite was negotiated’ 
And there was no sound, I guess due to that it can’t de-crypt. After a lot of trail and error I downgraded openssl to version 1.0.1e-30.el6.4, then error was gone and we had sound again. Have any of one else seen this? Any idea on what do do, if we want to use latest openssl for CentOS6?

Thanks

**Comment by rfuchs** [comment]
Is this with a recent rtpengine version? 2af682bdd534317f2caf28ac59db698593f6d9cc should be the fix for this.

**Comment by ulfwatt** [comment]
Ok, we are at 3.7.2. Maybe time to goto 3.8 then.

Thanks

**Comment by ulfwatt** [comment]
I merged over the change in dtls.c to 3.7.2. I can confirm that it then works also with latest openssl version. 
Thanks for your quick response
