### ISSUE TITLE
how can I query number of active streams via ng-protocol?

### ISSUE THREAD

**Issue by davehorton** [sipwise/rtpengine#992]
I would like a simple way via ng to determine the number of active media streams.  The 'list' command deosn't work because of the size limitations on a UDP buffer, and I don't want or need all of the call-ids anyways, I just want a simple integer number.  This would be highly useful to be able to report to monitoring systems

**Comment by rfuchs** [comment]
We don't have any really useful stats commands in NG yet, but we plan to add stats output in the near future. Or you can give it a shot adding it yourself, it should be pretty easy to do.

**Comment by davehorton** [comment]
ok, cool, if I find time I might do that.

**Comment by rfuchs** [comment]
JFYI we have that on our internal to-do list now for the near future.
