### ISSUE TITLE
WebRTC issue

### ISSUE THREAD

**Issue by 27902644** [sipwise/rtpengine#996]
Hi all,
I'm having trouble with both  jssip + opensips + freeswitch. 
When I make a call from a sip phone to the web, there are many errors and warning in rtpengine & opensips logs,

rtpengine's version is  git-mr8.3-6acf76c
Here are the logs as attached.
[rtpengine.log](https://github.com/sipwise/rtpengine/files/4681983/rtpengine.log)

**Comment by rfuchs** [comment]
The SDP has extra trailing spaces at the end of the `m=` line, past the list of RTP payload types: `#015#012m=audio 52920 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110   #015#012` (the `#015#012` is the newline). This is invalid as per the RFC and so rtpengine rejects it.

**Comment by 27902644** [comment]
so could you please tell me how to fix it，is there any way to walkaround for rtpengine， or only jssip？thanks in advance.

**Comment by rfuchs** [comment]
You need to fix it on the side that's producing the SDP, I'm guessing JSSIP. I'm somewhat reluctant to try to make rtpengine accept broken SDPs.

**Comment by 27902644** [comment]
I've fixed it on the JSSIP side, thank you very much!
