### ISSUE TITLE
rtcp and silence suppresion questions

### ISSUE THREAD

**Issue by descartin** [sipwise/rtpengine#999]
Hello all

we are using 7.5.3.0+0~mr7.5.3.0 git-mr7.5-925-212d71e2 and we have 2 questions
1- I know that rtcp was not generated by the rtpengine, but in case of transcoding calls, is there any way or option to enable that the rtpengine generates rtcp? 
2- Is the rtpengine working in silence supression ON by default, i mean if the rtpengine receives no packet, it sends nothing to the other endpoint, but could it be a way to generate CN payload if the client included it on the offer for example and the other end uses silence suppression? I think now that is not possible, right?

thanks a lot and regards
david

**Comment by rfuchs** [comment]
We have support for generating RTCP now, although it's only enabled for media playback scenarios for now. We'll extend this to additional scenarios (transcoding probably being the first) in the near future.

And no, we don't support CN in this way or really in any other way right now.

**Comment by descartin** [comment]
hello Richard

thanks for the feedback. There are some endpoints which seem to check the packet loses and even cut the calls based on that %packet loses, and sometimes we have experienced issues with them when silence suppresion is activated. It would be really great to have the option to generate CN to workaround or fix an interconnection between 2 endpoints one of them using silence suppression and the other one expecting to get CN.

And if you let me i would like to ask if rtpengine will support clearmode payload passthrough?

thanks a lot and regards
david

**Comment by rfuchs** [comment]
We support passthrough of any sort of data carried over UDP, whether in RTP or not. So clearmode passthrough works just fine.
